CREATE PROCEDURE [dbo].[PermitContactsForPermitId]
	@PERMITID AS VARCHAR(36)
AS

	SELECT
		pc.ISBILLING AS "PermitContactIsBilling",
		pct.NAME AS "PermitContactTypeName",
		c.GLOBALENTITYNAME AS "PermitContactCompanyName",
		c.ISCOMPANY AS "PermitContactIsCompany",
		c.ISCONTACT AS "PermitContactIsContact",
		c.EMAIL AS "PermitContactEmailAddress",
		c.BUSINESSPHONE AS "PermitContactBusinessPhone",
		c.HOMEPHONE AS "PermitContactHomePhone",
		c.MOBILEPHONE AS "PermitContactMobilePhone",
		c.OTHERPHONE AS "PermitContactOtherPhone",
		c.FAX AS "PermitContactFax",
		c.FIRSTNAME AS "PermitContactFirstName",
		c.LASTNAME AS "PermitContactLastName",
		c.MIDDLENAME AS "PermitContactMiddleName",
		c.TITLE AS "PermitContactTitle",
		(SELECT TOP 1 ma.ADDRESSLINE1 
			FROM [$(EnerGovDatabase)].dbo.GLOBALENTITYMAILINGADDRESS gema 
			INNER JOIN [$(EnerGovDatabase)].dbo.MAILINGADDRESS ma ON gema.MAILINGADDRESSID = ma.MAILINGADDRESSID 
			WHERE gema.GLOBALENTITYID = c.GLOBALENTITYID) AS "PermitContactAddressLine1",
		(SELECT TOP 1 ma.ADDRESSLINE2 
			FROM [$(EnerGovDatabase)].dbo.GLOBALENTITYMAILINGADDRESS gema 
			INNER JOIN [$(EnerGovDatabase)].dbo.MAILINGADDRESS ma ON gema.MAILINGADDRESSID = ma.MAILINGADDRESSID 
			WHERE gema.GLOBALENTITYID = c.GLOBALENTITYID) AS "PermitContactAddressLine2",
		(SELECT TOP 1 ma.ADDRESSLINE3 
			FROM [$(EnerGovDatabase)].dbo.GLOBALENTITYMAILINGADDRESS gema 
			INNER JOIN [$(EnerGovDatabase)].dbo.MAILINGADDRESS ma ON gema.MAILINGADDRESSID = ma.MAILINGADDRESSID 
			WHERE gema.GLOBALENTITYID = c.GLOBALENTITYID) AS "PermitContactAddressLine3",
		(SELECT TOP 1 ma.CITY 
			FROM [$(EnerGovDatabase)].dbo.GLOBALENTITYMAILINGADDRESS gema 
			INNER JOIN [$(EnerGovDatabase)].dbo.MAILINGADDRESS ma ON gema.MAILINGADDRESSID = ma.MAILINGADDRESSID 
			WHERE gema.GLOBALENTITYID = c.GLOBALENTITYID) AS "PermitAddressCity",
		(SELECT TOP 1 ma.STATE 
			FROM [$(EnerGovDatabase)].dbo.GLOBALENTITYMAILINGADDRESS gema 
			INNER JOIN [$(EnerGovDatabase)].dbo.MAILINGADDRESS ma ON gema.MAILINGADDRESSID = ma.MAILINGADDRESSID 
			WHERE gema.GLOBALENTITYID = c.GLOBALENTITYID) AS "PermitAddressState",
		(SELECT TOP 1 ma.POSTALCODE 
			FROM [$(EnerGovDatabase)].dbo.GLOBALENTITYMAILINGADDRESS gema 
			INNER JOIN [$(EnerGovDatabase)].dbo.MAILINGADDRESS ma ON gema.MAILINGADDRESSID = ma.MAILINGADDRESSID 
			WHERE gema.GLOBALENTITYID = c.GLOBALENTITYID) AS "PermitAddressPostalCode",
		(SELECT TOP 1 ma.POSTDIRECTION 
			FROM [$(EnerGovDatabase)].dbo.GLOBALENTITYMAILINGADDRESS gema 
			INNER JOIN [$(EnerGovDatabase)].dbo.MAILINGADDRESS ma ON gema.MAILINGADDRESSID = ma.MAILINGADDRESSID 
			WHERE gema.GLOBALENTITYID = c.GLOBALENTITYID) AS "PermitAddressPostDirection",
		(SELECT TOP 1 ma.PREDIRECTION 
			FROM [$(EnerGovDatabase)].dbo.GLOBALENTITYMAILINGADDRESS gema 
			INNER JOIN [$(EnerGovDatabase)].dbo.MAILINGADDRESS ma ON gema.MAILINGADDRESSID = ma.MAILINGADDRESSID 
			WHERE gema.GLOBALENTITYID = c.GLOBALENTITYID) AS "PermitAddressPreDirection",
		(SELECT TOP 1 ma.STREETTYPE 
			FROM [$(EnerGovDatabase)].dbo.GLOBALENTITYMAILINGADDRESS gema 
			INNER JOIN [$(EnerGovDatabase)].dbo.MAILINGADDRESS ma ON gema.MAILINGADDRESSID = ma.MAILINGADDRESSID 
			WHERE gema.GLOBALENTITYID = c.GLOBALENTITYID) AS "PermitAddressStreetType",
		(SELECT TOP 1 ma.UNITORSUITE 
			FROM [$(EnerGovDatabase)].dbo.GLOBALENTITYMAILINGADDRESS gema 
			INNER JOIN [$(EnerGovDatabase)].dbo.MAILINGADDRESS ma ON gema.MAILINGADDRESSID = ma.MAILINGADDRESSID 
			WHERE gema.GLOBALENTITYID = c.GLOBALENTITYID) AS "PermitAddressUnitOrSuite",
		(SELECT TOP 1 lct.NAME 
			FROM [$(EnerGovDatabase)].dbo.PMPERMITCONTACT xpc 
			INNER JOIN [$(EnerGovDatabase)].dbo.GLOBALENTITY pcge ON xpc.GLOBALENTITYID = pcge.GLOBALENTITYID
			INNER JOIN [$(EnerGovDatabase)].dbo.COLICENSECERTIFICATION lc ON pcge.GLOBALENTITYID = lc.GLOBALENTITYID
			INNER JOIN [$(EnerGovDatabase)].dbo.COLICENSECERTIFICATIONTYPE lct ON lc.COSIMPLELICCERTTYPEID = lct.COSIMPLELICCERTTYPEID
			INNER JOIN [$(EnerGovDatabase)].dbo.PMPERMIT xp ON xpc.PMPERMITID = xp.PMPERMITID
			INNER JOIN laxreports.PermitTypeReleventContactClassification ptcrcc ON xp.PMPERMITTYPEID = ptcrcc.PermitTypeId AND lct.COSIMPLELICCERTTYPEID = ptcrcc.CertificationTypeId
			WHERE lc.ISSUEDATE <= xp.APPLYDATE AND lc.EXPIREDATE >= xp.APPLYDATE AND xpc.PMPERMITCONTACTID = pc.PMPERMITCONTACTID
			ORDER BY xp.APPLYDATE DESC) AS "PermitContactCertificationTypeName",
		(SELECT TOP 1 lc.LICENSENUMBER 
			FROM [$(EnerGovDatabase)].dbo.PMPERMITCONTACT xpc 
			INNER JOIN [$(EnerGovDatabase)].dbo.GLOBALENTITY pcge ON xpc.GLOBALENTITYID = pcge.GLOBALENTITYID
			INNER JOIN [$(EnerGovDatabase)].dbo.COLICENSECERTIFICATION lc ON pcge.GLOBALENTITYID = lc.GLOBALENTITYID
			INNER JOIN [$(EnerGovDatabase)].dbo.COLICENSECERTIFICATIONTYPE lct ON lc.COSIMPLELICCERTTYPEID = lct.COSIMPLELICCERTTYPEID
			INNER JOIN [$(EnerGovDatabase)].dbo.PMPERMIT xp ON xpc.PMPERMITID = xp.PMPERMITID
			INNER JOIN laxreports.PermitTypeReleventContactClassification ptcrcc ON xp.PMPERMITTYPEID = ptcrcc.PermitTypeId AND lct.COSIMPLELICCERTTYPEID = ptcrcc.CertificationTypeId
			WHERE lc.ISSUEDATE <= xp.APPLYDATE AND lc.EXPIREDATE >= xp.APPLYDATE AND xpc.PMPERMITCONTACTID = pc.PMPERMITCONTACTID
			ORDER BY xp.APPLYDATE DESC) AS "PermitContactCertificationNumber",
		(SELECT TOP 1 lc.ISSUEDATE 
			FROM [$(EnerGovDatabase)].dbo.PMPERMITCONTACT xpc 
			INNER JOIN [$(EnerGovDatabase)].dbo.GLOBALENTITY pcge ON xpc.GLOBALENTITYID = pcge.GLOBALENTITYID
			INNER JOIN [$(EnerGovDatabase)].dbo.COLICENSECERTIFICATION lc ON pcge.GLOBALENTITYID = lc.GLOBALENTITYID
			INNER JOIN [$(EnerGovDatabase)].dbo.COLICENSECERTIFICATIONTYPE lct ON lc.COSIMPLELICCERTTYPEID = lct.COSIMPLELICCERTTYPEID
			INNER JOIN [$(EnerGovDatabase)].dbo.PMPERMIT xp ON xpc.PMPERMITID = xp.PMPERMITID
			INNER JOIN laxreports.PermitTypeReleventContactClassification ptcrcc ON xp.PMPERMITTYPEID = ptcrcc.PermitTypeId AND lct.COSIMPLELICCERTTYPEID = ptcrcc.CertificationTypeId
			WHERE lc.ISSUEDATE <= xp.APPLYDATE AND lc.EXPIREDATE >= xp.APPLYDATE AND xpc.PMPERMITCONTACTID = pc.PMPERMITCONTACTID
			ORDER BY xp.APPLYDATE DESC) AS "PermitContactCertificationIssuedDate",
		(SELECT TOP 1 lc.EXPIREDATE 
			FROM [$(EnerGovDatabase)].dbo.PMPERMITCONTACT xpc 
			INNER JOIN [$(EnerGovDatabase)].dbo.GLOBALENTITY pcge ON xpc.GLOBALENTITYID = pcge.GLOBALENTITYID
			INNER JOIN [$(EnerGovDatabase)].dbo.COLICENSECERTIFICATION lc ON pcge.GLOBALENTITYID = lc.GLOBALENTITYID
			INNER JOIN [$(EnerGovDatabase)].dbo.COLICENSECERTIFICATIONTYPE lct ON lc.COSIMPLELICCERTTYPEID = lct.COSIMPLELICCERTTYPEID
			INNER JOIN [$(EnerGovDatabase)].dbo.PMPERMIT xp ON xpc.PMPERMITID = xp.PMPERMITID
			INNER JOIN laxreports.PermitTypeReleventContactClassification ptcrcc ON xp.PMPERMITTYPEID = ptcrcc.PermitTypeId AND lct.COSIMPLELICCERTTYPEID = ptcrcc.CertificationTypeId
			WHERE lc.ISSUEDATE <= xp.APPLYDATE AND lc.EXPIREDATE >= xp.APPLYDATE AND xpc.PMPERMITCONTACTID = pc.PMPERMITCONTACTID
			ORDER BY xp.APPLYDATE DESC) AS "PermitContactCertificationExpirationDate",
		(SELECT TOP 1 NAME FROM (SELECT lct.NAME, ROW_NUMBER() OVER(ORDER BY xp.APPLYDATE DESC) as "Row" 
			FROM [$(EnerGovDatabase)].dbo.PMPERMITCONTACT xpc 
			INNER JOIN [$(EnerGovDatabase)].dbo.GLOBALENTITY pcge ON xpc.GLOBALENTITYID = pcge.GLOBALENTITYID
			INNER JOIN [$(EnerGovDatabase)].dbo.COLICENSECERTIFICATION lc ON pcge.GLOBALENTITYID = lc.GLOBALENTITYID
			INNER JOIN [$(EnerGovDatabase)].dbo.COLICENSECERTIFICATIONTYPE lct ON lc.COSIMPLELICCERTTYPEID = lct.COSIMPLELICCERTTYPEID
			INNER JOIN [$(EnerGovDatabase)].dbo.PMPERMIT xp ON xpc.PMPERMITID = xp.PMPERMITID
			INNER JOIN laxreports.PermitTypeReleventContactClassification ptcrcc ON xp.PMPERMITTYPEID = ptcrcc.PermitTypeId AND lct.COSIMPLELICCERTTYPEID = ptcrcc.CertificationTypeId
			WHERE lc.ISSUEDATE <= xp.APPLYDATE AND lc.EXPIREDATE >= xp.APPLYDATE AND xpc.PMPERMITCONTACTID = pc.PMPERMITCONTACTID) AS temp WHERE Row=2) AS "PermitContactCertificationTypeName2",
		(SELECT TOP 1 LICENSENUMBER FROM (SELECT lc.LICENSENUMBER, ROW_NUMBER() OVER(ORDER BY xp.APPLYDATE DESC) as "Row" 
			FROM [$(EnerGovDatabase)].dbo.PMPERMITCONTACT xpc 
			INNER JOIN [$(EnerGovDatabase)].dbo.GLOBALENTITY pcge ON xpc.GLOBALENTITYID = pcge.GLOBALENTITYID
			INNER JOIN [$(EnerGovDatabase)].dbo.COLICENSECERTIFICATION lc ON pcge.GLOBALENTITYID = lc.GLOBALENTITYID
			INNER JOIN [$(EnerGovDatabase)].dbo.COLICENSECERTIFICATIONTYPE lct ON lc.COSIMPLELICCERTTYPEID = lct.COSIMPLELICCERTTYPEID
			INNER JOIN [$(EnerGovDatabase)].dbo.PMPERMIT xp ON xpc.PMPERMITID = xp.PMPERMITID
			INNER JOIN laxreports.PermitTypeReleventContactClassification ptcrcc ON xp.PMPERMITTYPEID = ptcrcc.PermitTypeId AND lct.COSIMPLELICCERTTYPEID = ptcrcc.CertificationTypeId
			WHERE lc.ISSUEDATE <= xp.APPLYDATE AND lc.EXPIREDATE >= xp.APPLYDATE AND xpc.PMPERMITCONTACTID = pc.PMPERMITCONTACTID) AS temp WHERE Row=2) AS "PermitContactCertificationNumber2",
		(SELECT TOP 1 ISSUEDATE FROM (SELECT lc.ISSUEDATE, ROW_NUMBER() OVER(ORDER BY xp.APPLYDATE DESC) as "Row" 
			FROM [$(EnerGovDatabase)].dbo.PMPERMITCONTACT xpc 
			INNER JOIN [$(EnerGovDatabase)].dbo.GLOBALENTITY pcge ON xpc.GLOBALENTITYID = pcge.GLOBALENTITYID
			INNER JOIN [$(EnerGovDatabase)].dbo.COLICENSECERTIFICATION lc ON pcge.GLOBALENTITYID = lc.GLOBALENTITYID
			INNER JOIN [$(EnerGovDatabase)].dbo.COLICENSECERTIFICATIONTYPE lct ON lc.COSIMPLELICCERTTYPEID = lct.COSIMPLELICCERTTYPEID
			INNER JOIN [$(EnerGovDatabase)].dbo.PMPERMIT xp ON xpc.PMPERMITID = xp.PMPERMITID
			INNER JOIN laxreports.PermitTypeReleventContactClassification ptcrcc ON xp.PMPERMITTYPEID = ptcrcc.PermitTypeId AND lct.COSIMPLELICCERTTYPEID = ptcrcc.CertificationTypeId
			WHERE lc.ISSUEDATE <= xp.APPLYDATE AND lc.EXPIREDATE >= xp.APPLYDATE AND xpc.PMPERMITCONTACTID = pc.PMPERMITCONTACTID) AS temp WHERE Row=2) AS "PermitContactCertificationIssuedDate2",
		(SELECT TOP 1 EXPIREDATE FROM (SELECT lc.EXPIREDATE, ROW_NUMBER() OVER(ORDER BY xp.APPLYDATE DESC) as "Row" 
			FROM [$(EnerGovDatabase)].dbo.PMPERMITCONTACT xpc 
			INNER JOIN [$(EnerGovDatabase)].dbo.GLOBALENTITY pcge ON xpc.GLOBALENTITYID = pcge.GLOBALENTITYID
			INNER JOIN [$(EnerGovDatabase)].dbo.COLICENSECERTIFICATION lc ON pcge.GLOBALENTITYID = lc.GLOBALENTITYID
			INNER JOIN [$(EnerGovDatabase)].dbo.COLICENSECERTIFICATIONTYPE lct ON lc.COSIMPLELICCERTTYPEID = lct.COSIMPLELICCERTTYPEID
			INNER JOIN [$(EnerGovDatabase)].dbo.PMPERMIT xp ON xpc.PMPERMITID = xp.PMPERMITID
			INNER JOIN laxreports.PermitTypeReleventContactClassification ptcrcc ON xp.PMPERMITTYPEID = ptcrcc.PermitTypeId AND lct.COSIMPLELICCERTTYPEID = ptcrcc.CertificationTypeId
			WHERE lc.ISSUEDATE <= xp.APPLYDATE AND lc.EXPIREDATE >= xp.APPLYDATE AND xpc.PMPERMITCONTACTID = pc.PMPERMITCONTACTID) AS temp WHERE Row=2) AS "PermitContactCertificationExpirationDate2"
	FROM [$(EnerGovDatabase)].dbo.PMPERMITCONTACT pc
	INNER JOIN [$(EnerGovDatabase)].dbo.LANDMANAGEMENTCONTACTTYPE pct ON pc.LANDMANAGEMENTCONTACTTYPEID = pct.LANDMANAGEMENTCONTACTTYPEID
	INNER JOIN [$(EnerGovDatabase)].dbo.GLOBALENTITY c ON pc.GLOBALENTITYID = c.GLOBALENTITYID
	WHERE pc.PMPERMITID = @PERMITID