CREATE PROCEDURE [cashieringsetup].[USP_BONDINTERESTSCHEDULE_SELECT_LOOKUP]
AS
SET NOCOUNT ON;
SELECT 
	[dbo].[BONDINTERESTSCHEDULE].[BONDINTERESTSCHEDULEID],
	[dbo].[BONDINTERESTSCHEDULE].[NAME]
FROM [dbo].[BONDINTERESTSCHEDULE]
ORDER BY [dbo].[BONDINTERESTSCHEDULE].[NAME]