CREATE PROCEDURE [cashieringsetup].[USP_GLACCOUNT_SELECT_LOOKUP]
AS
BEGIN
	SELECT 
		[dbo].[GLACCOUNT].[GLACCOUNTID],
		[dbo].[GLACCOUNT].[NAME]
	FROM [dbo].[GLACCOUNT]
	ORDER BY [dbo].[GLACCOUNT].[NAME]
END