CREATE PROCEDURE [energovsystemreport].[USP_RPTREPORT_GETBYRPTFRMTOBUSOBJMAPID]
(
	@RPTFRMTOBUSOBJMAPID CHAR(36)
)
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 
		[dbo].[RPTREPORT].[RPTREPORTID],
		[dbo].[RPTREPORT].[REPORTNAME],
		[dbo].[RPTREPORT].[FRIENDLYNAME],
		[dbo].[RPTFORMTOBUSINESSOBJECTMAPPING].[FORMNAME],
		[dbo].[RPTREPORT].[RPTREPORTTYPEID],
		[dbo].[RPTREPORT].[REPORTPREVIEWIMAGE]
	FROM [dbo].[RPTREPORT]
	LEFT JOIN [dbo].[RPTFORMTOBUSINESSOBJECTMAPPING] ON [dbo].[RPTREPORT].[RPTFRMTOBUSOBJMAPID] = [dbo].[RPTFORMTOBUSINESSOBJECTMAPPING].[RPTFRMTOBUSOBJMAPID]
	WHERE [dbo].[RPTREPORT].[RPTFRMTOBUSOBJMAPID] = @RPTFRMTOBUSOBJMAPID
	ORDER BY [dbo].[RPTREPORT].[FRIENDLYNAME]

	EXEC [energovsystemreport].[USP_RPTREPORTATTRIBUTE_GETBYPARENTID] @RPTFRMTOBUSOBJMAPID
END