CREATE TABLE [dbo].[USERSFORMSGRIDVIEWSXREF] (
    [USERID]                  CHAR (36)       NOT NULL,
    [FORMID]                  CHAR (36)       NOT NULL,
    [GRIDVIEWNAME]            VARCHAR (50)    NOT NULL,
    [GRIDVIEWPERSISTENCEDATA] VARBINARY (MAX) NOT NULL,
    CONSTRAINT [PK_USERSFORMSGRDVIEWXREF] PRIMARY KEY CLUSTERED ([USERID] ASC, [FORMID] ASC, [GRIDVIEWNAME] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_USERSFORMSGRDVIEWXREF_FORMS] FOREIGN KEY ([FORMID]) REFERENCES [dbo].[FORMS] ([SFORMSGUID]),
    CONSTRAINT [FK_USERSFORMSGRDVIEWXREF_USERS] FOREIGN KEY ([USERID]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);

