CREATE TABLE [dbo].[USERSETTINGVALUE] (
    [USERSETTINGVALUEID] CHAR (36)      NOT NULL,
    [USERSETTINGID]      CHAR (36)      NOT NULL,
    [USERID]             CHAR (36)      NOT NULL,
    [BITVALUE]           BIT            NULL,
    [STRINGVALUE]        NVARCHAR (MAX) NULL,
    [INTVALUE]           INT            NULL,
    CONSTRAINT [PK_USERSETTINGVALUE] PRIMARY KEY CLUSTERED ([USERSETTINGVALUEID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_USERSETTINGVALUE_SETTING] FOREIGN KEY ([USERSETTINGID]) REFERENCES [dbo].[USERSETTING] ([USERSETTINGID]),
    CONSTRAINT [FK_USERSETTINGVALUE_USER] FOREIGN KEY ([USERID]) REFERENCES [dbo].[USERS] ([SUSERGUID]),
    CONSTRAINT [UK_USERSETTING_USER] UNIQUE NONCLUSTERED ([USERSETTINGID] ASC, [USERID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_USERSETTINGVALUE_USERSETTINGID]
    ON [dbo].[USERSETTINGVALUE]([USERSETTINGID] ASC);

