CREATE TABLE [dbo].[USERSETTING] (
    [USERSETTINGID] CHAR (36)     NOT NULL,
    [NAME]          NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_USERSETTING] PRIMARY KEY CLUSTERED ([USERSETTINGID] ASC) WITH (FILLFACTOR = 90)
);

