CREATE PROCEDURE [events].[USP_INSPECTIONEVENTQUEUE_CLEANUP]
@PROCESSEDDATELIMIT DATETIME
AS
BEGIN
	SET NOCOUNT ON;

	DELETE FROM [dbo].[INSPECTIONEVENTQUEUE] 
					WHERE [dbo].[INSPECTIONEVENTQUEUE].[PROCESSEDDATE] < @PROCESSEDDATELIMIT
		
END