CREATE PROCEDURE [events].[USP_INSPECTIONEVENTQUEUE_DELETED_EVENT_SELECT_LOOKUP]
(
	@BATCHSIZE AS INT = 1000
)
AS
BEGIN

	SELECT TOP(@BATCHSIZE)
        [INSPECTIONEVENTQUEUE].[INSPECTIONEVENTQUEUEID],
		[INSPECTIONEVENTQUEUE].[CREATEDDATE],
		[INSPECTIONEVENTQUEUE].[IMINSPECTIONID],
		[INSPECTIONEVENTQUEUE].[INSPECTIONNUMBER],
		CASE WHEN COALESCE([USERS].[FNAME], '') = ''
			 THEN CASE WHEN COALESCE([USERS].[LNAME], '') = '' 
					   THEN ''
					   ELSE [USERS].[LNAME] END
			 ELSE CASE WHEN COALESCE([USERS].[LNAME], '') = ''
						THEN [USERS].[FNAME]
						ELSE [USERS].[LNAME] + ', ' + [USERS].[FNAME] END
		END AS LASTCHANGEDBYNAME

		FROM [dbo].[INSPECTIONEVENTQUEUE]
		LEFT JOIN [dbo].[USERS] ON [dbo].[INSPECTIONEVENTQUEUE].[INSPECTIONLASTCHANGEDBY] = [dbo].[USERS].[SUSERGUID]
		WHERE [dbo].[INSPECTIONEVENTQUEUE].[PROCESSEDDATE] IS NULL
		AND [INSPECTIONEVENTQUEUE].INSPECTIONEVENTTYPEID = 5
		ORDER BY [dbo].[INSPECTIONEVENTQUEUE].[CREATEDDATE]
END