CREATE PROCEDURE [events].[USP_TXREMITTANCEEVENTQUEUE_CLEANUP]
@PROCESSEDDATELIMIT DATETIME
AS
BEGIN
	SET NOCOUNT ON;

	DELETE FROM [dbo].[TXREMITTANCEEVENTQUEUE] 
					WHERE [dbo].[TXREMITTANCEEVENTQUEUE].[PROCESSEDDATE] < @PROCESSEDDATELIMIT
		
END