CREATE PROCEDURE [events].[USP_CODECASEEVENTQUEUE_CLEANUP]
@PROCESSEDDATELIMIT DATETIME
AS
BEGIN
	SET NOCOUNT ON;

	DELETE FROM [dbo].[CODECASEEVENTQUEUE] 
					WHERE [dbo].[CODECASEEVENTQUEUE].[PROCESSEDDATE] < @PROCESSEDDATELIMIT
		
END