CREATE PROCEDURE [events].[USP_PERMIT_PAIDEVENT_SELECT_LOOKUP]
(
	@PMPERMITID AS CHAR(36) = ''
)
AS
BEGIN  
	-- select all the invoice and amountpaid for the given recordid e.g. pmpermitid, plplanid....
	SELECT 
		[CAINVOICE].CAINVOICEID INVOICEID,
		[CAINVOICE].INVOICENUMBER INVOICENUMBER,
		COALESCE(SUM(CACOMPUTEDFEE.AMOUNTPAIDTODATE), 0.00) TOTALPAID

	FROM [dbo].PMPERMITFEE 
	INNER JOIN [dbo].[CACOMPUTEDFEE] ON [PMPERMITFEE].CACOMPUTEDFEEID = [CACOMPUTEDFEE].CACOMPUTEDFEEID
	INNER JOIN [dbo].[CAINVOICEFEE] ON [CAINVOICEFEE].CACOMPUTEDFEEID = [CACOMPUTEDFEE].CACOMPUTEDFEEID
	INNER JOIN [dbo].[CAINVOICE] ON [CAINVOICE].CAINVOICEID = [CAINVOICEFEE].[CAINVOICEID]
	WHERE PMPERMITFEE.PMPERMITID = @PMPERMITID
	--since we need the totalpaid for the invoice we use group by
	GROUP BY [CAINVOICE].CAINVOICEID,[CAINVOICE].INVOICENUMBER	
	ORDER BY [CAINVOICE].INVOICENUMBER
END