CREATE PROCEDURE [events].[USP_CUSTOMEVENTQUEUE_SELECT_LOOKUP]
(
	@BATCHSIZE INT = 1000
)
AS
BEGIN
	SELECT TOP(@BATCHSIZE)
	[dbo].[CUSTOMEVENTQUEUE].[CUSTOMEVENTQUEUEID],
	[dbo].[CUSTOMEVENTQUEUE].[RECORDID],
	[dbo].[CUSTOMEVENTQUEUE].[CREATEDDATE],
	[dbo].[CUSTOMEVENTTYPE].[STOREDPROCEDURENAME],
	LTRIM(RTRIM(CONCAT([dbo].[USERS].[FNAME], ' ', [dbo].[USERS].[LNAME]))) AS [LASTCHANGEDBY]

	FROM [dbo].[CUSTOMEVENTQUEUE]
	INNER JOIN [dbo].[CUSTOMEVENTTYPE] ON [dbo].[CUSTOMEVENTTYPE].[CUSTOMEVENTTYPEID] = [dbo].[CUSTOMEVENTQUEUE].[CUSTOMEVENTTYPEID]
	LEFT JOIN [dbo].[USERS] ON [dbo].[USERS].[SUSERGUID] = [dbo].[CUSTOMEVENTQUEUE].[RECORDLASTCHANGEDBY]
	WHERE [dbo].[CUSTOMEVENTQUEUE].[PROCESSEDDATE] IS NULL AND [dbo].[CUSTOMEVENTTYPE].[ACTIVE] = 1
	ORDER BY [dbo].[CUSTOMEVENTQUEUE].[CREATEDDATE]
END