CREATE PROCEDURE [events].[USP_CUSTOMEVENTQUEUE_CLEANUP]
@PROCESSEDDATELIMIT DATETIME
AS
BEGIN
	SET NOCOUNT ON;

	DELETE FROM [dbo].[CUSTOMEVENTQUEUE] 
					WHERE [dbo].[CUSTOMEVENTQUEUE].[PROCESSEDDATE] < @PROCESSEDDATELIMIT
		
END