

CREATE PROCEDURE [dbo].[PMO_AUDIT_REPORT_BL_NOISSUED_STATUS]
AS

SELECT BLLICENSESTATUS.NAME AS LIC_STATUS, BLLICENSESTATUS.DESCRIPTION AS LIC_STATUS_DESC, BLLICENSESTATUSSYSTEM.NAME AS LIC_SYSTEM_STATUS
FROM BLLICENSESTATUS 
INNER JOIN BLLICENSESTATUSSYSTEM ON BLLICENSESTATUS.BLLICENSESTATUSSYSTEMID = BLLICENSESTATUSSYSTEM.BLLICENSESTATUSSYSTEMID
WHERE BLLICENSESTATUSSYSTEM.NAME='Issued'

