

CREATE PROCEDURE [dbo].[PMO_AUDIT_REPORT_FEE_INPUTS_ON_ACTIVITY_CFLAYOUTS]
AS
SELECT     CAFEETEMPLATEFEEINPUT.INPUTVALUE AS FEE_TEMPLATE_INPUT, CUSTOMFIELD.SFIELDNAME AS CF_NAME, CUSTOMFIELDLAYOUT.SNAME AS CF_LAYOUT, 
                      COALESCE (BLLICENSEACTIVITYTYPE.NAME, CMCODEACTIVITYTYPE.NAME, ILLICENSEACTIVITYTYPE.NAME, PLPLANACTIVITYTYPE.NAME, PMPERMITACTIVITYTYPE.NAME, 
                      RPLANDLORDLICACTIVITYTYPE.NAME, RPPROPERTYACTIVITYTYPE.NAME) AS ACTIVITY_NAME, CUSTOMFIELDMODULES.MODULENAME, CAFEE.NAME AS FEE_NAME, 
                      CAFEETEMPLATE.CAFEETEMPLATENAME
FROM         CAFEETEMPLATEFEEINPUT INNER JOIN
                      CUSTOMFIELD ON CAFEETEMPLATEFEEINPUT.INPUTVALUE = CUSTOMFIELD.SFIELDNAME INNER JOIN
                      CUSTOMFIELDOBJECT ON CUSTOMFIELD.GCUSTOMFIELD = CUSTOMFIELDOBJECT.FKGCUSTOMFIELD INNER JOIN
                      CUSTOMFIELDLAYOUT ON CUSTOMFIELDOBJECT.FKGCUSTOMFIELDLAYOUT = CUSTOMFIELDLAYOUT.GCUSTOMFIELDLAYOUTS INNER JOIN
                      CUSTOMFIELDMODULES ON CUSTOMFIELDLAYOUT.CUSTOMFIELDMODULEID = CUSTOMFIELDMODULES.CUSTOMFIELDMODULEID INNER JOIN
                      CAFEETEMPLATEFEE ON CAFEETEMPLATEFEEINPUT.CAFEETEMPLATEFEEID = CAFEETEMPLATEFEE.CAFEETEMPLATEFEEID INNER JOIN
                      CAFEE ON CAFEETEMPLATEFEE.CAFEEID = CAFEE.CAFEEID INNER JOIN
                      CAFEETEMPLATE ON CAFEETEMPLATEFEE.CAFEETEMPLATEID = CAFEETEMPLATE.CAFEETEMPLATEID LEFT OUTER JOIN
                      RPPROPERTYACTIVITYTYPE ON CUSTOMFIELDLAYOUT.GCUSTOMFIELDLAYOUTS = RPPROPERTYACTIVITYTYPE.CUSTOMFIELDLAYOUTID LEFT OUTER JOIN
                      RPLANDLORDLICACTIVITYTYPE ON CUSTOMFIELDLAYOUT.GCUSTOMFIELDLAYOUTS = RPLANDLORDLICACTIVITYTYPE.CUSTOMFIELDLAYOUTID LEFT OUTER JOIN
                      PMPERMITACTIVITYTYPE ON CUSTOMFIELDLAYOUT.GCUSTOMFIELDLAYOUTS = PMPERMITACTIVITYTYPE.CUSTOMFIELDID LEFT OUTER JOIN
                      PLPLANACTIVITYTYPE ON CUSTOMFIELDLAYOUT.GCUSTOMFIELDLAYOUTS = PLPLANACTIVITYTYPE.CUSTOMFIELDID LEFT OUTER JOIN
                      ILLICENSEACTIVITYTYPE ON CUSTOMFIELDLAYOUT.GCUSTOMFIELDLAYOUTS = ILLICENSEACTIVITYTYPE.CUSTOMFIELDLAYOUTID LEFT OUTER JOIN
                      CMCODEACTIVITYTYPE ON CUSTOMFIELDLAYOUT.GCUSTOMFIELDLAYOUTS = CMCODEACTIVITYTYPE.CUSTOMFIELDID LEFT OUTER JOIN
                      BLLICENSEACTIVITYTYPE ON CUSTOMFIELDLAYOUT.GCUSTOMFIELDLAYOUTS = BLLICENSEACTIVITYTYPE.CUSTOMFIELDLAYOUTID
WHERE     (COALESCE (BLLICENSEACTIVITYTYPE.NAME, CMCODEACTIVITYTYPE.NAME, ILLICENSEACTIVITYTYPE.NAME, PLPLANACTIVITYTYPE.NAME, PMPERMITACTIVITYTYPE.NAME, 
                      RPLANDLORDLICACTIVITYTYPE.NAME, RPPROPERTYACTIVITYTYPE.NAME) IS NOT NULL)

