


CREATE PROCEDURE [dbo].[PMO_AUDIT_REPORT_SYS_USERS_NOTNULL_GLOBALENTITY]
AS

SELECT     USERS.ID AS LOGIN, USERS.FNAME AS USER_FIRST, USERS.LNAME AS USER_LAST, GLOBALENTITY.GLOBALENTITYNAME AS CONTACT_COMPANY, 
                      GLOBALENTITY.FIRSTNAME AS CONTACT_FIRST, GLOBALENTITY.LASTNAME AS CONTACT_LAST
FROM         USERS INNER JOIN
                      GLOBALENTITY ON USERS.GLOBALENTITYID = GLOBALENTITY.GLOBALENTITYID
WHERE     (USERS.SROLEID IS NOT NULL) AND (USERS.GLOBALENTITYID IS NOT NULL)


