


CREATE PROCEDURE [dbo].[PMO_AUDIT_REPORT_LANDMGMT_CONTACT_CONTRACTOR]
AS

SELECT     LANDMANAGEMENTCONTACTTYPE.NAME AS CONT_TYPE, LANDMANAGEMENTCONTACTSYSTEMTYP.NAME AS SYSTEM_TYPE
FROM         LANDMANAGEMENTCONTACTTYPE INNER JOIN
                      LANDMANAGEMENTCONTACTSYSTEMTYP ON 
                      LANDMANAGEMENTCONTACTTYPE.LANDMANAGEMENTCONTACTSYSTEMTYP = LANDMANAGEMENTCONTACTSYSTEMTYP.LANDMANAGEMENTCONTACTSYSTEMTYP
WHERE LANDMANAGEMENTCONTACTSYSTEMTYP.NAME='Contractor'

