



CREATE PROCEDURE [dbo].[PMO_AUDIT_REPORT_SYS_IOS_NOT_POSTPROCESS]
AS

SELECT     WORKFLOW.WORKFLOWNAME, WORKFLOW.ISSERVER, WORKFLOW.ISCLIENT, WORKFLOW.ISPOSTPROCESS, WORKFLOWACTIONTYPE.WORKFLOWACTIONTYPENAME
FROM         WORKFLOW INNER JOIN
                      WORKFLOWACTION ON WORKFLOW.WORKFLOWID = WORKFLOWACTION.WORKFLOWID INNER JOIN
                      WORKFLOWACTIONTYPE ON WORKFLOWACTION.WORKFLOWACTIONTYPEID = WORKFLOWACTIONTYPE.WORKFLOWACTIONTYPEID
WHERE ISPOSTPROCESS=0 and WORKFLOWACTIONTYPE.WORKFLOWACTIONTYPENAME in ('Stored Procedure','Attach Document','Email w/ Attachment')

