


CREATE PROCEDURE [dbo].[PMO_AUDIT_REPORT_INSP_STATUSES_WITHOUT_DESCR]
AS

SELECT     IMINSPECTIONSTATUS.STATUSNAME, IMINSPECTIONSTATUS.DESCRIPTION, IMINSPECTIONLINK.NAME AS MODULE
FROM         IMINSPECTIONSTATUS INNER JOIN
                      IMINSPECTIONSTATUSENTITY ON IMINSPECTIONSTATUS.IMINSPECTIONSTATUSENTITYID = IMINSPECTIONSTATUSENTITY.IMINSPECTIONSTATUSENTITYID INNER JOIN
                      IMINSPECTIONLINK ON IMINSPECTIONSTATUSENTITY.IMINSPECTIONLINKID = IMINSPECTIONLINK.IMINSPECTIONLINKID
WHERE     (IMINSPECTIONSTATUS.DESCRIPTION IS NULL) OR
                      (IMINSPECTIONSTATUS.DESCRIPTION = '')

