


CREATE PROCEDURE [dbo].[RPT_PL_PLAN_TIME_TRACKING_REPORT]
@PLANID AS VARCHAR(36)
AS
SELECT TIMETRACKINGTYPE.NAME AS TIMETRACKINGTYPE, TIMETRACKING.LOGDATE, TIMETRACKING.COMMENTS, TIMETRACKING.STARTTIME, TIMETRACKING.ENDTIME, 
       TIMETRACKING.HOURS, TIMETRACKING.MINUTES, TIMETRACKING.TOTALTIME, TIMETRACKING.BILLABLEAMOUNT, USERS.FNAME, USERS.LNAME, USERS.ID, 
       TIMETRACKING.TIMETRACKINGID, TIMETRACKING.BILLED, PLPLAN.PLANNUMBER AS PLANNUMBER, CONVERT(DATEtime,TIMETRACKING.LOGDATE) AS LogDateDate
FROM TIMETRACKINGTYPE 
INNER JOIN TIMETRACKING ON TIMETRACKINGTYPE.TIMETRACKINGTYPEID = TIMETRACKING.TIMETRACKINGTYPEID 
INNER JOIN USERS ON TIMETRACKING.LogUSERID = USERS.SUSERGUID 
INNER JOIN PLPLAN ON TIMETRACKING.PrimaryRecordID = PLPLAN.PLPLANID
WHERE PLPLAN.PLPLANID = @PLANID


