




CREATE PROCEDURE [dbo].[rpt_PL_Plan_Detail_Report]
@PLANID AS VARCHAR(36)
AS

SELECT PLPLAN.PLANNUMBER, PLPLAN.APPLICATIONDATE, PLPLAN.EXPIREDATE, PLPLAN.COMPLETEDATE, PLPLAN.VALUE, PLPLAN.SQUAREFEET, 
       PLPLAN.DESCRIPTION, PLPLANSTATUS.NAME AS STATUS, PLPLANTYPE.PLANNAME AS PLANTYPE, DISTRICT.NAME AS DISTRICT, PLPLANWORKCLASS.NAME AS WORKCLASS, 
       PLPLAN.PLPLANID, PRPROJECT.NAME AS PROJECT, USERS.FNAME, USERS.LNAME
FROM PLPLAN 
INNER JOIN PLPLANTYPE ON PLPLAN.PLPLANTYPEID = PLPLANTYPE.PLPLANTYPEID 
INNER JOIN PLPLANSTATUS ON PLPLAN.PLPLANSTATUSID = PLPLANSTATUS.PLPLANSTATUSID 
INNER JOIN PLPLANWORKCLASS ON PLPLAN.PLPLANWORKCLASSID = PLPLANWORKCLASS.PLPLANWORKCLASSID 
LEFT OUTER JOIN DISTRICT ON PLPLAN.DISTRICTID = DISTRICT.DISTRICTID 
LEFT OUTER JOIN USERS ON PLPLAN.ASSIGNEDTO = USERS.SUSERGUID
LEFT OUTER JOIN PRPROJECTPLAN ON PRPROJECTPLAN.PLPLANID = PLPLAN.PLPLANID 
LEFT OUTER JOIN PRPROJECT ON PRPROJECT.PRPROJECTID = PRPROJECTPLAN.PRPROJECTID 
WHERE PLPLAN.PLPLANID = @PLANID


