





CREATE PROCEDURE [dbo].[rpt_PL_Internal_Review_Time_For_Completed_Plans_By_User]
@STARTDATE AS DATETIME,
@ENDDATE AS DATETIME
AS
SET @ENDDATE = DATEADD(S,-1,DATEADD(D,1,@ENDDATE))
SELECT     PLPLAN.PLPLANID, PLPLAN.PLANNUMBER, PLPLAN.COMPLETEDATE AS PLANCOMPLETEDATE, PLSUBMITTALTYPE.TYPENAME AS SUBMITTALTYPE, PLPLANWFSTEP.PRIORITYORDER, 
                      PLPLANWFSTEP.SORTORDER, PLPLANWFSTEP.VERSIONNUMBER, PLPLANWFSTEP.NAME AS STEPNAME, PLPLANWFSTEP.WFSTEPTYPEID, 
                      PLPLANWFACTIONSTEP.WFACTIONTYPEID, PLPLANWFACTIONSTEP.PRIORITYORDER AS ACTIONPRIORITY, 
                      PLPLANWFACTIONSTEP.SORTORDER AS ACTIONSORTORDER, PLPLANWFACTIONSTEP.VERSIONNUMBER AS ACTIONVERSIONNUMBER, 
                      PLITEMREVIEWTYPE.NAME AS REVIEWTYPE, PLITEMREVIEW.ASSIGNEDDATE, PLITEMREVIEW.COMPLETEDATE, DEPARTMENT.NAME AS DEPARTMENT, 
                      USERS.ID AS USERID
FROM         USERS RIGHT OUTER JOIN
                      PLSUBMITTALTYPE INNER JOIN
                      PLSUBMITTAL ON PLSUBMITTALTYPE.PLSUBMITTALTYPEID = PLSUBMITTAL.PLSUBMITTALTYPEID INNER JOIN
                      PLITEMREVIEW ON PLITEMREVIEW.PLSUBMITTALID = PLSUBMITTAL.PLSUBMITTALID INNER JOIN
                      PLITEMREVIEWTYPE ON PLITEMREVIEWTYPE.PLITEMREVIEWTYPEID = PLITEMREVIEW.PLITEMREVIEWTYPEID INNER JOIN
                      DEPARTMENT ON DEPARTMENT.DEPARTMENTID = PLITEMREVIEWTYPE.DEPARTMENTID INNER JOIN
                      PLPLANWFSTEP INNER JOIN
                      PLPLAN ON PLPLANWFSTEP.PLPLANID = PLPLAN.PLPLANID INNER JOIN
                      PLPLANWFACTIONSTEP ON PLPLANWFSTEP.PLPLANWFSTEPID = PLPLANWFACTIONSTEP.PLPLANWFSTEPID ON 
                      PLSUBMITTAL.PLPLANWFACTIONSTEPID = PLPLANWFACTIONSTEP.PLPLANWFACTIONSTEPID ON USERS.SUSERGUID = PLITEMREVIEW.ASSIGNEDUSERID
WHERE     (PLPLAN.COMPLETED = 1) AND (NOT (PLPLAN.COMPLETEDATE IS NULL)) AND (PLPLAN.COMPLETEDATE BETWEEN @STARTDATE AND @ENDDATE)

