
CREATE PROCEDURE rpt_PM_Permit_Detailed_Dept_A_Inspections
@PMPERMITID varchar(36)
AS

SELECT DISTINCT PWFS.PMPERMITID, PWFAS.NAME, IMT.IVRNUMBER
			  , ROW_NUMBER() OVER (PARTITION BY PWFS.PMPERMITID ORDER BY PWFS.PRIORITYORDER, PWFS.SORTORDER, PWFS.[NAME], PWFS.VERSIONNUMBER, PWFAS.PRIORITYORDER, PWFAS.SORTORDER, PWFAS.[NAME], PWFAS.VERSIONNUMBER) WF_SORT
			  , CASE WHEN EXISTS (SELECT TOP 1 * FROM IVInspectionStaging) 
		        THEN 'Y' 
		        ELSE 'N'
		        END AS IVR_FLAG
FROM PMPERMITWFSTEP PWFS
INNER JOIN PMPERMITWFACTIONSTEP PWFAS ON PWFS.PMPERMITWFSTEPID = PWFAS.PMPERMITWFSTEPID 
INNER JOIN IMINSPECTIONTYPE IMT ON PWFAS.IMINSPECTIONTYPEID = IMT.IMINSPECTIONTYPEID
WHERE PWFS.PMPERMITID = @PMPERMITID
ORDER BY WF_SORT

