
CREATE PROCEDURE rpt_PM_SR_Submittal_Timeline_For_Received_Submittals
@PMPERMITID AS VARCHAR(36)
AS



SELECT PM.PMPERMITID,
	PM.PERMITNUMBER,
	PLS.RECEIVEDDATE,
	PLS.COMPLETEDATE,
	PLS.DUEDATE,
	WFS.NAME ACTIONSTATUS,
	CASE WFS.NAME WHEN 'STOPPED' THEN dbo.ELAPSEDBDAYS(PLS.RECEIVEDDATE, GETDATE()) WHEN 'NOT STARTED' THEN '' ELSE dbo.ELAPSEDBDAYS(PLS.RECEIVEDDATE, PLS.COMPLETEDATE) END NUMBER_DAYS,
	PMWFS.PRIORITYORDER STEP_PRIORITY,
	PMWFAS.PRIORITYORDER ACTION_PRIORITY,
	PMWFAS.NAME ACTION_NAME,
	PMWFAS.VERSIONNUMBER,
	PLST.TYPENAME SUBMITTAL_TYPE,
	(SELECT CASE WHEN R.[IMAGE] IS NULL THEN ( SELECT TOP 1 IMAGEVALUE FROM SETTINGS WHERE NAME = 'LogoImage' ) ELSE R.IMAGE END FROM RPTIMAGELIB R
		WHERE R.IMAGENAME = 'Municipality_Logo') LOGO,
	(SELECT CASE WHEN R.[IMAGE] IS NULL AND ( SELECT TOP 1 IMAGEVALUE FROM SETTINGS WHERE NAME = 'LogoImage' ) IS NULL THEN 'N' ELSE 'Y' END FROM RPTIMAGELIB R
		WHERE R.IMAGENAME = 'Municipality_Logo') SHOWLOGO,
	(SELECT R.REPORTTEXT FROM RPTTEXTLIB R
		WHERE R.TEXTNAME = 'Municipality_Name') Municipality_Name,	   
	(SELECT R.REPORTTEXT FROM RPTTEXTLIB R
		WHERE R.TEXTNAME = 'Municipality_Page_Footer') Municipality_Page_Footer
FROM PMPERMIT PM
INNER JOIN PMPERMITWFSTEP PMWFS ON PMWFS.PMPERMITID = PM.PMPERMITID
INNER JOIN PMPERMITWFACTIONSTEP PMWFAS ON PMWFAS.PMPERMITWFSTEPID = PMWFS.PMPERMITWFSTEPID
INNER JOIN PLSUBMITTAL PLS ON PLS.PMPERMITWFACTIONSTEPID = PMWFAS.PMPERMITWFACTIONSTEPID
INNER JOIN PLSUBMITTALTYPE PLST ON PLST.PLSUBMITTALTYPEID = PLS.PLSUBMITTALTYPEID
INNER JOIN PLSUBMITTALSTATUS PLSS ON PLSS.PLSUBMITTALSTATUSID = PLS.PLSUBMITTALSTATUSID
INNER JOIN WORKFLOWSTATUS WFS ON WFS.WORKFLOWSTATUSID = PMWFAS.WORKFLOWSTATUSID
WHERE PM.PMPERMITID = @PMPERMITID


