

CREATE PROCEDURE [dbo].[rpt_PR_Project_Detail_Report_Requests]
@PROJECTID AS VARCHAR(36)
AS
SELECT     CITIZENREQUEST.REQUESTNUMBER, CITIZENREQUESTTYPE.NAME AS RequestType, CITIZENREQUESTSTATUS.STATUS, CITIZENREQUEST.DATEFILED, 
                      CITIZENREQUEST.COMPDEADLINE, CITIZENREQUEST.COMPCOMPLETE
FROM         PRPROJECTCITIZENREQUEST INNER JOIN
                      CITIZENREQUEST ON PRPROJECTCITIZENREQUEST.CITIZENREQUESTID = CITIZENREQUEST.CITIZENREQUESTID INNER JOIN
                      CITIZENREQUESTTYPE ON CITIZENREQUEST.CITIZENREQUESTTYPEID = CITIZENREQUESTTYPE.CITIZENREQUESTTYPEID INNER JOIN
                      CITIZENREQUESTSTATUS ON CITIZENREQUEST.CITIZENREQUESTSTATUSID = CITIZENREQUESTSTATUS.CITIZENREQUESTSTATUSID
WHERE PRPROJECTCITIZENREQUEST.PRPROJECTID = @PROJECTID

