

CREATE PROCEDURE [dbo].[rpt_PL_SR_Plan_Corrections_Report_Conditions]
@PLPLANID AS VARCHAR(36)
AS
BEGIN

SELECT PLC.PLANID PLPLANID,
	CASE PLC.ISSATISFIED WHEN 0 THEN 'No' WHEN 1 THEN 'Yes' END ISSATISFIED,
	C.NAME CONDITION_NAME,
	C.[DESCRIPTION] CONDITION_DESCRIPTION,
	C.COMMENTS CONDITION_COMMENTS,
	CS.SCOPENAME
FROM PLPLANCONDITION PLC
INNER JOIN CONDITION C ON C.CONDITIONID = PLC.CONDITIONID
INNER JOIN CONDITIONSCOPE CS ON CS.CONDITIONSCOPEID = PLC.SCOPE
WHERE PLC.ISSATISFIED = 0 AND PLC.PLANID = @PLPLANID

END
