
/*
exec [rpt_PL_SR_Plan_Detail_Report] '2327a091-9b9f-4ac2-9d59-45ad3aa11480'
select top(10) * from plplan order by applicationdate desc
*/


CREATE PROCEDURE [dbo].[rpt_PL_SR_Plan_Detail_Report]
@PLPLANID AS VARCHAR(36)
AS

SELECT PLPLAN.PLANNUMBER, PLPLAN.APPLICATIONDATE, PLPLAN.EXPIREDATE, PLPLAN.COMPLETEDATE, PLPLAN.VALUE, PLPLAN.SQUAREFEET, 
       PLPLAN.DESCRIPTION, PLPLANSTATUS.NAME AS STATUS, PLPLANTYPE.PLANNAME AS PLANTYPE, DISTRICT.NAME AS DISTRICT, PLPLANWORKCLASS.NAME AS WORKCLASS, 
       PLPLAN.PLPLANID, PRPROJECT.NAME AS PROJECT, USERS.FNAME, USERS.LNAME, PLPLAN.APPROVALEXPIREDATE,
	   (SELECT R.[IMAGE] FROM RPTIMAGELIB R
		WHERE R.IMAGENAME = 'Municipality_Logo') LOGO,
	   (SELECT CASE WHEN R.[IMAGE] IS NULL THEN 'N' ELSE 'Y' END FROM RPTIMAGELIB R
		WHERE R.IMAGENAME = 'Municipality_Logo') SHOWLOGO,
	   (SELECT R.REPORTTEXT FROM RPTTEXTLIB R
		WHERE R.TEXTNAME = 'Municipality_Name') Municipality_Name,	   
	   (SELECT R.REPORTTEXT FROM RPTTEXTLIB R
		WHERE R.TEXTNAME = 'Municipality_Page_Footer') Municipality_Page_Footer

FROM PLPLAN 
INNER JOIN PLPLANTYPE ON PLPLAN.PLPLANTYPEID = PLPLANTYPE.PLPLANTYPEID 
INNER JOIN PLPLANSTATUS ON PLPLAN.PLPLANSTATUSID = PLPLANSTATUS.PLPLANSTATUSID 
INNER JOIN PLPLANWORKCLASS ON PLPLAN.PLPLANWORKCLASSID = PLPLANWORKCLASS.PLPLANWORKCLASSID 
LEFT OUTER JOIN DISTRICT ON PLPLAN.DISTRICTID = DISTRICT.DISTRICTID 
LEFT OUTER JOIN USERS ON PLPLAN.ASSIGNEDTO = USERS.SUSERGUID
LEFT OUTER JOIN PRPROJECTPLAN ON PRPROJECTPLAN.PLPLANID = PLPLAN.PLPLANID 
LEFT OUTER JOIN PRPROJECT ON PRPROJECT.PRPROJECTID = PRPROJECTPLAN.PRPROJECTID 
WHERE PLPLAN.PLPLANID = @PLPLANID

