


CREATE PROCEDURE [dbo].[RPT_PM_PERMIT_DETAIL_REPORT_ADDRESS]
@PERMITID AS VARCHAR(36)
AS
SELECT MAILINGADDRESS.ADDRESSLINE1, MAILINGADDRESS.ADDRESSLINE2, MAILINGADDRESS.ADDRESSLINE3, MAILINGADDRESS.CITY, MAILINGADDRESS.STATE, MAILINGADDRESS.POSTALCODE, 
       MAILINGADDRESS.POSTDIRECTION, MAILINGADDRESS.PREDIRECTION, MAILINGADDRESS.STREETTYPE, MAILINGADDRESS.PARCELNUMBER, MAILINGADDRESS.UNITORSUITE, PMPERMITADDRESS.MAILINGADDRESSID, PMPERMITADDRESS.MAIN
FROM PMPERMITADDRESS 
INNER JOIN MAILINGADDRESS ON PMPERMITADDRESS.MAILINGADDRESSID = MAILINGADDRESS.MAILINGADDRESSID
WHERE PMPERMITADDRESS.PMPERMITID = @PERMITID


