
CREATE PROCEDURE [dbo].[rpt_PM_SR_Permit_Corrections_Report_Conditions]
@PMPERMITID AS VARCHAR(36)
AS
BEGIN

SELECT PLC.PMPERMITID PMPERMITID,
	CASE PLC.ISSATISFIED WHEN 0 THEN 'No' WHEN 1 THEN 'Yes' END ISSATISFIED,
	C.NAME CONDITION_NAME,
	C.[DESCRIPTION] CONDITION_DESCRIPTION,
	C.COMMENTS CONDITION_COMMENTS,
	CS.SCOPENAME
FROM PMPERMITCONDITION PLC
INNER JOIN CONDITION C ON C.CONDITIONID = PLC.CONDITIONID
INNER JOIN CONDITIONSCOPE CS ON CS.CONDITIONSCOPEID = PLC.SCOPE
WHERE PLC.ISSATISFIED = 0 AND PLC.PMPERMITID = @PMPERMITID
END
