

CREATE PROCEDURE [dbo].[rpt_PR_SR_Project_Listing]
@STARTDATE AS DATETIME,
@ENDDATE AS DATETIME,
@FILTER AS VARCHAR(150)
AS
SET @STARTDATE=dateadd(dd,datediff(dd,0,@STARTDATE),0)
SET @ENDDATE = DATEADD(S,-1,DATEADD(D,1,@ENDDATE))


SELECT PRPROJECTFEE.PRPROJECTID, SUM(CACOMPUTEDFEE.COMPUTEDAMOUNT) FEETOTAL
INTO #FEES
FROM PRPROJECTFEE 
INNER JOIN CACOMPUTEDFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = PRPROJECTFEE.CACOMPUTEDFEEID
WHERE CACOMPUTEDFEE.CASTATUSID NOT IN (5,10) --VOID, DELETED
GROUP BY PRPROJECTFEE.PRPROJECTID


CREATE INDEX TEMP1 ON #FEES (PRPROJECTID);

SELECT PRPROJECT.NAME AS Project, PRPROJECT.PROJECTNUMBER, PARENT.NAME PARENTPROJECT, PRPROJECT.STARTDATE, PRPROJECT.EXPECTEDENDDATE, PRPROJECT.COMPLETEDATE, PRPROJECT.DESCRIPTION, PRPROJECT.COMPLETE,
       COALESCE(NULLIF(DISTRICT.NAME,''),'Not Assigned') AS District, 
       PRPROJECTTYPE.NAME AS ProjectType, 
       PRPROJECTSTATUS.NAME STATUS, PRPROJECT.PRPROJECTID,	
	   PARCEL.PARCELNUMBER,  
	   MAILINGADDRESS.ADDRESSLINE1, MAILINGADDRESS.ADDRESSLINE2, MAILINGADDRESS.ADDRESSLINE3, MAILINGADDRESS.CITY, MAILINGADDRESS.STATE, 
	   MAILINGADDRESS.POSTALCODE, MAILINGADDRESS.POSTDIRECTION, MAILINGADDRESS.PREDIRECTION, MAILINGADDRESS.STREETTYPE, MAILINGADDRESS.UNITORSUITE,
	  --(SELECT R.[IMAGE] FROM RPTIMAGELIB R
	  --WHERE R.IMAGENAME = 'Municipality_Logo') LOGO,
	  (SELECT CASE WHEN R.[IMAGE] IS NULL THEN 'N' ELSE 'Y' END FROM RPTIMAGELIB R
	   WHERE R.IMAGENAME = 'Municipality_Logo') SHOWLOGO,
	  (SELECT R.REPORTTEXT FROM RPTTEXTLIB R
	   WHERE R.TEXTNAME = 'Municipality_Name') Municipality_Name,	   
	  (SELECT R.REPORTTEXT FROM RPTTEXTLIB R
	   WHERE R.TEXTNAME = 'Municipality_Page_Footer') Municipality_Page_Footer,
	   FEES.FEETOTAL

FROM PRPROJECT 
INNER JOIN PRPROJECTTYPE ON PRPROJECT.PRPROJECTTYPEID = PRPROJECTTYPE.PRPROJECTTYPEID  
INNER JOIN PRPROJECTSTATUS ON PRPROJECT.PRPROJECTSTATUSID = PRPROJECTSTATUS.PRPROJECTSTATUSID
LEFT OUTER JOIN PRPROJECT PARENT ON PRPROJECT.PRPROJECTPARENTID = PARENT.PRPROJECTID 
LEFT JOIN (SELECT MAILINGADDRESS.ADDRESSLINE1, MAILINGADDRESS.ADDRESSLINE2, MAILINGADDRESS.ADDRESSLINE3, MAILINGADDRESS.CITY, MAILINGADDRESS.STATE, 
				MAILINGADDRESS.POSTALCODE, MAILINGADDRESS.POSTDIRECTION, MAILINGADDRESS.PREDIRECTION, MAILINGADDRESS.STREETTYPE, 
				MAILINGADDRESS.UNITORSUITE, PRPROJECTADDRESS.PRPROJECTID
			FROM PRPROJECTADDRESS 
				INNER JOIN MAILINGADDRESS ON PRPROJECTADDRESS.MAILINGADDRESSID = MAILINGADDRESS.MAILINGADDRESSID
			WHERE PRPROJECTADDRESS.MAIN = 1) MAILINGADDRESS ON PRPROJECT.PRPROJECTID = MAILINGADDRESS.PRPROJECTID
LEFT OUTER JOIN PRPROJECTPARCEL ON PRPROJECT.PRPROJECTID = PRPROJECTPARCEL.PRPROJECTID AND PRPROJECTPARCEL.MAIN = 1
LEFT OUTER JOIN PARCEL ON PRPROJECTPARCEL.PARCELID = PARCEL.PARCELID 
LEFT OUTER JOIN DISTRICT ON PRPROJECT.DISTRICTID = DISTRICT.DESCRIPTION
LEFT JOIN #FEES FEES ON PRPROJECT.PRPROJECTID = FEES.PRPROJECTID

WHERE (CASE @FILTER 
	     WHEN 'START DATE' THEN PRPROJECT.STARTDATE
	     WHEN 'EXPECTED END DATE' THEN PRPROJECT.EXPECTEDENDDATE
		 WHEN 'COMPLETED DATE' THEN PRPROJECT.COMPLETEDATE END)
         BETWEEN @STARTDATE AND @ENDDATE
