


CREATE PROCEDURE [dbo].[RPT_PM_PERMIT_DETAIL_REPORT_ACTIVITY]
@PERMITID AS VARCHAR(36)
AS
SELECT PMPERMITACTIVITY.PMPERMITACTIVITYID, PMPERMITACTIVITY.PERMITACTIVITYNAME, PMPERMITACTIVITY.PERMITACTIVITYNUMBER, PMPERMITACTIVITYTYPE.NAME AS ACTIVITYTYPE, 
       USERS.FNAME, USERS.LNAME, PMPERMITACTIVITY.CREATEDON
FROM PMPERMITACTIVITY 
INNER JOIN PMPERMITACTIVITYTYPE ON PMPERMITACTIVITY.PMPERMITACTIVITYTYPEID = PMPERMITACTIVITYTYPE.PMPERMITACTIVITYTYPEID 
INNER JOIN USERS ON PMPERMITACTIVITY.SUSERGUID = USERS.SUSERGUID
WHERE PMPERMITACTIVITY.PMPERMITID = @PERMITID


