

CREATE PROCEDURE [dbo].[RPT_PL_PLAN_CORRECTIONS_REPORT]
@PLPLANID AS VARCHAR(36)
AS
SELECT PLPLAN.PLPLANID, PLPLAN.PLANNUMBER, PLPLAN.APPLICATIONDATE, PLPLAN.EXPIREDATE, PLPLAN.DESCRIPTION, PLPLAN.SQUAREFEET, PLPLAN.VALUE, 
       PLITEMREVIEWTYPE.NAME AS REVIEWITEM, USERS.FNAME, USERS.LNAME, USERS.PHONE, USERS.EMAIL, USERS.TITLE, USERS.CREDENTIALS, 
       PLPLANCORRECTIONTYPE.NAME AS CORRECTIONTYPE, PLPLANCORRECTION.COMMENTS AS [CORRECTIVEACTIONS COMMENTS], 
       PLPLANCORRECTION.PLPLANCORRECTIONID, PLITEMREVIEWTYPE.DESCRIPTION AS ITEMREVIEWDESC,
	   PARCEL.PARCELNUMBER, PLITEMREVIEW.PLITEMREVIEWID,
	   MA.ADDRESSLINE1, MA.ADDRESSLINE2, MA.ADDRESSLINE3, MA.CITY, MA.STATE, MA.POSTALCODE, 
       MA.POSTDIRECTION, MA.PREDIRECTION, MA.STREETTYPE, MA.UNITORSUITE
FROM PLPLAN 
INNER JOIN PLITEMREVIEW ON PLPLAN.PLPLANID = PLITEMREVIEW.PLPLANID 
INNER JOIN PLITEMREVIEWTYPE ON PLITEMREVIEW.PLITEMREVIEWTYPEID = PLITEMREVIEWTYPE.PLITEMREVIEWTYPEID 
INNER JOIN PLPLANCORRECTION ON PLITEMREVIEW.PLITEMREVIEWID = PLPLANCORRECTION.PLITEMREVIEWID 
INNER JOIN PLPLANCORRECTIONTYPE ON PLPLANCORRECTION.PLPLANCORRECTIONTYPEID = PLPLANCORRECTIONTYPE.PLPLANCORRECTIONTYPEID 
INNER JOIN USERS ON PLITEMREVIEW.ASSIGNEDUSERID = USERS.SUSERGUID 
LEFT JOIN PLPLANPARCEL ON PLPLAN.PLPLANID = PLPLANPARCEL.PLPLANID AND PLPLANPARCEL.MAIN = 1
LEFT JOIN PARCEL ON PLPLANPARCEL.PARCELID = PARCEL.PARCELID
LEFT JOIN (SELECT PLPLANADDRESS.PLPLANID, MAILINGADDRESS.ADDRESSLINE1, MAILINGADDRESS.ADDRESSLINE2, MAILINGADDRESS.ADDRESSLINE3, MAILINGADDRESS.CITY, MAILINGADDRESS.STATE, MAILINGADDRESS.POSTALCODE, 
				   MAILINGADDRESS.POSTDIRECTION, MAILINGADDRESS.PREDIRECTION, MAILINGADDRESS.STREETTYPE, MAILINGADDRESS.UNITORSUITE
			FROM PLPLANADDRESS 
			INNER JOIN MAILINGADDRESS ON PLPLANADDRESS.MAILINGADDRESSID = MAILINGADDRESS.MAILINGADDRESSID
			WHERE PLPLANADDRESS.PLPLANID = @PLPLANID 
			AND PLPLANADDRESS.MAIN = 'TRUE') AS MA ON PLPLAN.PLPLANID = MA.PLPLANID
WHERE PLPLAN.PLPLANID = @PLPLANID

