
CREATE PROCEDURE rpt_PM_SR_Permit_Listing
	@STARTDATE AS DATETIME,
	@ENDDATE AS DATETIME,
	@FILTER AS VARCHAR(150),
	@CASEORIGIN AS VARCHAR(50)
	AS
Begin
SET @STARTDATE = DATEADD(dd, DATEDIFF(dd, 0, @startdate), 0)
SET @ENDDATE = DATEADD(S,-1,DATEADD(D,1,@ENDDATE))  

SELECT PF.PMPERMITID, SUM(C.COMPUTEDAMOUNT) FEETOTAL
INTO #FEES
FROM PMPERMITFEE PF
INNER JOIN CACOMPUTEDFEE C ON C.CACOMPUTEDFEEID = PF.CACOMPUTEDFEEID
WHERE C.CASTATUSID NOT IN (5,10) --VOID, DELETED
GROUP BY PF.PMPERMITID

SELECT DISTINCT PMH.PMPERMITID
INTO #HOLDS
FROM PMPERMITHOLD PMH
WHERE PMH.ACTIVE = 1


CREATE INDEX TEMP1 ON #FEES (PMPERMITID);
CREATE INDEX TEMP1 ON #HOLDS (PMPERMITID);

SELECT PMPERMITSTATUS.NAME AS PermitStatus, PMPERMITTYPE.NAME AS PermitType, PMPERMITWORKCLASS.NAME AS PermitClass, 
       PMPERMIT.PERMITNUMBER, PMPERMIT.EXPIREDATE, PMPERMIT.VALUE, PMPERMIT.DESCRIPTION AS PermitDesc, 
	   CASE WHEN PMPERMIT.ISAPPLIEDONLINE = 1 THEN 'Yes' ELSE 'No' END APPLIEDONLINE,
       PRPROJECT.NAME AS ProjectName, PMPERMIT.SQUAREFEET, DISTRICT.NAME AS District, PARCEL.PARCELNUMBER, 
       TB_ADDR.ADDRESSLINE1, TB_ADDR.ADDRESSLINE2, TB_ADDR.ADDRESSLINE3, TB_ADDR.CITY, TB_ADDR.STATE, 
       TB_ADDR.POSTALCODE, TB_ADDR.POSTDIRECTION, TB_ADDR.PREDIRECTION, TB_ADDR.STREETTYPE, TB_ADDR.UNITORSUITE,
       PMPERMIT.PMPERMITID, PMPERMIT.APPLYDATE, PMPERMIT.FINALIZEDATE, PMPERMIT.ISSUEDATE, PMPERMITWORKCLASS.NAME WorkClass,
	   U.FNAME + ' ' + U.LNAME ASSIGNEDTO, PMPERMIT.LASTINSPECTIONDATE, 
	   F.FEETOTAL,
	   Z.ZONECODE + ' ' + Z.NAME AS ZONE,
	   CASE WHEN H.PMPERMITID IS NULL THEN 'N' ELSE 'Y' END AS HOLDFLAG,
	 --  ,(select #FEES.PMPERMITID from #FEES where #FEES.PMPERMITID=PMPERMIT.PMPERMITID )
	 --(SELECT R.[IMAGE] FROM RPTIMAGELIB R
		--WHERE R.IMAGENAME = 'Municipality_Logo') LOGO,
	   (SELECT CASE WHEN R.[IMAGE] IS NULL THEN 'N' ELSE 'Y' END FROM RPTIMAGELIB R
		WHERE R.IMAGENAME = 'Municipality_Logo') SHOWLOGO,
	   (SELECT R.REPORTTEXT FROM RPTTEXTLIB R
		WHERE R.TEXTNAME = 'Municipality_Name') Municipality_Name,	   
	   (SELECT R.REPORTTEXT FROM RPTTEXTLIB R
		WHERE R.TEXTNAME = 'Municipality_Page_Footer') Municipality_Page_Footer
FROM PMPERMIT PMPERMIT
INNER JOIN PMPERMITSTATUS ON PMPERMIT.PMPERMITSTATUSID = PMPERMITSTATUS.PMPERMITSTATUSID
INNER JOIN PMPERMITTYPE ON PMPERMIT.PMPERMITTYPEID = PMPERMITTYPE.PMPERMITTYPEID
INNER JOIN PMPERMITWORKCLASS ON PMPERMIT.PMPERMITWORKCLASSID = PMPERMITWORKCLASS.PMPERMITWORKCLASSID
INNER JOIN DISTRICT ON PMPERMIT.DISTRICTID = DISTRICT.DISTRICTID
LEFT OUTER JOIN PRPROJECTPERMIT ON PMPERMIT.PMPERMITID = PRPROJECTPERMIT.PMPERMITID
LEFT OUTER JOIN PRPROJECT ON PRPROJECTPERMIT.PRPROJECTID = PRPROJECT.PRPROJECTID
LEFT OUTER JOIN ( SELECT * FROM PMPERMITPARCEL WHERE PMPERMITPARCEL.MAIN = 1 ) AS PMPERMITPARCEL ON PMPERMIT.PMPERMITID = PMPERMITPARCEL.PMPERMITID
LEFT OUTER JOIN PARCEL ON PMPERMITPARCEL.PARCELID = PARCEL.PARCELID
LEFT OUTER JOIN ( SELECT PMPERMITADDRESS.PMPERMITID, MAILINGADDRESS.MAILINGADDRESSID, MAILINGADDRESS.ADDRESSTYPE, MAILINGADDRESS.PARCELNUMBER, 
                         MAILINGADDRESS.ADDRESSLINE1, MAILINGADDRESS.ADDRESSLINE2, MAILINGADDRESS.ADDRESSLINE3, MAILINGADDRESS.CITY, MAILINGADDRESS.STATE, 
                         MAILINGADDRESS.POSTALCODE, MAILINGADDRESS.POSTDIRECTION, MAILINGADDRESS.PREDIRECTION, MAILINGADDRESS.STREETTYPE, MAILINGADDRESS.UNITORSUITE
                  FROM PMPERMITADDRESS 
                  INNER JOIN MAILINGADDRESS ON PMPERMITADDRESS.MAILINGADDRESSID = MAILINGADDRESS.MAILINGADDRESSID
                  WHERE PMPERMITADDRESS.MAIN = 1
                ) AS TB_ADDR ON PMPERMIT.PMPERMITID = TB_ADDR.PMPERMITID
LEFT JOIN USERS U ON PMPERMIT.ASSIGNEDTO = U.SUSERGUID
LEFT JOIN #FEES F ON PMPERMIT.PMPERMITID = F.PMPERMITID
LEFT JOIN PMPERMITZONE PZ ON PMPERMIT.PMPERMITID = PZ.PMPERMITID AND PZ.MAIN = 1
LEFT JOIN [ZONE] Z ON Z.ZONEID = PZ.ZONEID
LEFT JOIN #HOLDS H ON H.PMPERMITID = PMPERMIT.PMPERMITID
WHERE (CASE @FILTER 
	WHEN 'EXPIRATION DATE' THEN PMPERMIT.EXPIREDATE
	WHEN 'APPLIED DATE' THEN PMPERMIT.APPLYDATE
	WHEN 'FINALED DATE' THEN PMPERMIT.FINALIZEDATE
	WHEN 'ISSUED DATE' THEN PMPERMIT.ISSUEDATE
	WHEN 'LAST INSPECTION DATE' THEN PMPERMIT.LASTINSPECTIONDATE END)  BETWEEN @STARTDATE AND @ENDDATE
   AND CASE @CASEORIGIN
			WHEN 'Online Only' THEN 1
			WHEN 'Back Office Only' THEN 0
			ELSE PMPERMIT.ISAPPLIEDONLINE
	    END = PMPERMIT.ISAPPLIEDONLINE


DROP TABLE #FEES;
DROP TABLE #HOLDS;

END
