
-- SELECT * FROM PMPERMIT
-- EXEC rpt_PM_Standard_Inspection_Card_Inspections 'da071fe9-aae6-4657-8b58-746ce05777ff'

CREATE PROCEDURE rpt_PM_Standard_Inspection_Card_Inspections
@PMPERMITID varchar(36)
AS

SELECT DISTINCT IMT.NAME AS InspectionType, CAST(IMT.IVRNUMBER AS INT) INSP_IVRNUMBER
     , ROW_NUMBER() OVER (PARTITION BY PWFS.PMPERMITID ORDER BY PWFS.PRIORITYORDER, PWFS.SORTORDER, PWFS.[NAME], PWFS.VERSIONNUMBER, PWFAS.PRIORITYORDER, PWFAS.SORTORDER, PWFAS.[NAME], PWFAS.VERSIONNUMBER) WF_SORT
	 , CASE WHEN EXISTS (SELECT TOP 1 * FROM IVInspectionStaging) 
		    THEN 'Y' 
	    	ELSE 'N'
		    END AS IVR_FLAG
FROM PMPERMITWFSTEP PWFS
INNER JOIN PMPERMITWFACTIONSTEP PWFAS ON PWFS.PMPERMITWFSTEPID = PWFAS.PMPERMITWFSTEPID 
INNER JOIN IMINSPECTIONTYPE IMT ON PWFAS.IMINSPECTIONTYPEID = IMT.IMINSPECTIONTYPEID
WHERE PWFS.PMPERMITID = @PMPERMITID
ORDER BY WF_SORT

