




CREATE PROCEDURE [dbo].[rpt_PL_Plan_Detail_Report_Activity]
@PLANID AS VARCHAR(36)
AS

SELECT PLPLANACTIVITY.PLPLANACTIVITYID, PLPLANACTIVITY.PLANACTIVITYNAME, PLPLANACTIVITY.PLANACTIVITYNUMBER, PLPLANACTIVITYTYPE.NAME AS ACTIVITYTYPE, 
       USERS.FNAME, USERS.LNAME, PLPLANACTIVITY.CREATEDON
FROM PLPLANACTIVITY 
INNER JOIN PLPLANACTIVITYTYPE ON PLPLANACTIVITY.PLPLANACTIVITYTYPEID = PLPLANACTIVITYTYPE.PLPLANACTIVITYTYPEID 
INNER JOIN USERS ON PLPLANACTIVITY.SUSERGUID = USERS.SUSERGUID 
WHERE PLPLANACTIVITY.PLPLANID = @PLANID



