

CREATE PROCEDURE [dbo].[rpt_PR_Project_Detail_Report_Conditions]
@PROJECTID AS VARCHAR(36)
AS
SELECT     CONDITION.NAME AS ConditionName, CONDITIONCATEGORY.NAME AS ConditionCategory, CONDITION.DESCRIPTION AS ConditionDescription, 
                      CONDITION.COMMENTS AS ConditionComments, CONDITION.ISENABLE AS Enabled, CONDITIONSCOPE.SCOPENAME AS ScopeName, 
                      CONDITION.ORIGINOBJECT
FROM         PRPROJECTCONDITION INNER JOIN
                      CONDITION ON PRPROJECTCONDITION.CONDITIONID = CONDITION.CONDITIONID INNER JOIN
                      CONDITIONCATEGORY ON CONDITION.CONDITIONCATEGORYID = CONDITIONCATEGORY.CONDITIONCATEGORYID INNER JOIN
                      CONDITIONSCOPE ON PRPROJECTCONDITION.CONDITIONSCOPEID = CONDITIONSCOPE.CONDITIONSCOPEID
WHERE PRPROJECTCONDITION.PRPROJECTID = @PROJECTID

