

CREATE PROCEDURE [dbo].[rpt_PM_SR_Permit_Time_Tracking_Report]
@PMPERMITID AS VARCHAR(36)
AS
BEGIN
SELECT PMPERMIT.PERMITNUMBER, 
TIMETRACKINGTYPE.NAME AS TIMETRACKINGTYPE, 
TIMETRACKING.LOGDATE, 
TIMETRACKING.COMMENTS, 
TIMETRACKING.STARTTIME, 
TIMETRACKING.ENDTIME, 
TIMETRACKING.[HOURS] as "HOURS",
TIMETRACKING.[MINUTES] as "MINUTES", 
TIMETRACKING.TOTALTIME, 
TIMETRACKING.BILLABLEAMOUNT, 
USERS.FNAME, 
USERS.LNAME, 
USERS.ID, 
TIMETRACKING.TIMETRACKINGID,
TIMETRACKING.Billed, 
CONVERT(DATE,TIMETRACKING.LOGDATE) AS LogDateDate,
--(SELECT R.[IMAGE] FROM RPTIMAGELIB R	WHERE R.IMAGENAME = 'Municipality_Logo') LOGO,
(SELECT CASE WHEN R.[IMAGE] IS NULL THEN 'N' ELSE 'Y' END FROM RPTIMAGELIB R WHERE R.IMAGENAME = 'Municipality_Logo') SHOWLOGO,
(SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'Municipality_Name') Municipality_Name,	   
(SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'Municipality_Page_Footer') Municipality_Page_Footer
FROM TIMETRACKINGTYPE 
INNER JOIN TIMETRACKING ON TIMETRACKINGTYPE.TIMETRACKINGTYPEID = TIMETRACKING.TIMETRACKINGTYPEID 
INNER JOIN PMPERMIT ON TIMETRACKING.PRIMARYRECORDID = PMPERMIT.PMPERMITID 
INNER JOIN USERS ON TIMETRACKING.LOGUSERID = USERS.SUSERGUID
WHERE PMPERMIT.PMPERMITID = @PMPERMITID

END
