

CREATE PROCEDURE [dbo].[rpt_PR_SR_Project_Detail_Report_Contact]
@PRPROJECTID AS VARCHAR(36)
AS
SELECT * FROM (
SELECT	GLOBALENTITY.FIRSTNAME, GLOBALENTITY.LASTNAME, MAILINGADDRESS.ADDRESSLINE1, MAILINGADDRESS.ADDRESSLINE2, 
		MAILINGADDRESS.ADDRESSLINE3, MAILINGADDRESS.CITY, MAILINGADDRESS.STATE, MAILINGADDRESS.POSTALCODE, MAILINGADDRESS.POSTDIRECTION, 
		MAILINGADDRESS.PREDIRECTION, MAILINGADDRESS.STREETTYPE, MAILINGADDRESS.UNITORSUITE, LANDMANAGEMENTCONTACTTYPE.NAME AS ContactType, 
		GLOBALENTITY.BUSINESSPHONE, GLOBALENTITY.HOMEPHONE, GLOBALENTITY.MOBILEPHONE, GLOBALENTITY.GLOBALENTITYNAME,
		ROW_NUMBER() OVER (PARTITION BY GLOBALENTITY.GLOBALENTITYID ORDER BY MAILINGADDRESS.ADDRESSTYPE, MAILINGADDRESS.MAILINGADDRESSID) 'RowNBR'
FROM	PRPROJECTCONTACT 
INNER JOIN LANDMANAGEMENTCONTACTTYPE ON PRPROJECTCONTACT.LANDMANAGEMENTCONTACTTYPEID = LANDMANAGEMENTCONTACTTYPE.LANDMANAGEMENTCONTACTTYPEID
INNER JOIN GLOBALENTITY ON PRPROJECTCONTACT.GLOBALENTITYID = GLOBALENTITY.GLOBALENTITYID  
LEFT OUTER JOIN GLOBALENTITYMAILINGADDRESS ON GLOBALENTITY.GLOBALENTITYID = GLOBALENTITYMAILINGADDRESS.GLOBALENTITYID
LEFT OUTER JOIN MAILINGADDRESS ON GLOBALENTITYMAILINGADDRESS.MAILINGADDRESSID = MAILINGADDRESS.MAILINGADDRESSID 
WHERE PRPROJECTCONTACT.PRPROJECTID = @PRPROJECTID
)AS CONTACTINFO WHERE CONTACTINFO.RowNBR = 1
