

CREATE PROCEDURE [dbo].[rpt_PR_Project_Detail_Report_Fees]
@PROJECTID AS VARCHAR(36)
AS
SELECT     CACOMPUTEDFEE.FEENAME, CACOMPUTEDFEE.COMPUTEDAMOUNT, CAINVOICE.INVOICENUMBER, CAINVOICE.INVOICEDATE, CAINVOICE.CAINVOICEID, 
                      CAINVOICEFEE.CACOMPUTEDFEEID, CASTATUS.NAME AS INVOICESTATUS, CASTATUS_1.NAME AS COMPUTEDFEESTATUS, CASTATUS_2.NAME AS [TRANSACTIONFEE STATUS], 
                      CATRANSACTIONSTATUS.NAME AS TRANSACTIONSTATUS, CATRANSACTIONFEE.PAIDAMOUNT, CATRANSACTION.RECEIPTNUMBER
FROM         CATRANSACTION INNER JOIN
                      CATRANSACTIONFEE ON CATRANSACTION.CATRANSACTIONID = CATRANSACTIONFEE.CATRANSACTIONID INNER JOIN
                      CATRANSACTIONSTATUS ON CATRANSACTION.CATRANSACTIONSTATUSID = CATRANSACTIONSTATUS.CATRANSACTIONSTATUSID INNER JOIN
                      CASTATUS AS CASTATUS_2 ON CATRANSACTIONFEE.CASTATUSID = CASTATUS_2.CASTATUSID RIGHT OUTER JOIN
                      PRPROJECTFEE INNER JOIN
                      CACOMPUTEDFEE ON PRPROJECTFEE.CACOMPUTEDFEEID = CACOMPUTEDFEE.CACOMPUTEDFEEID INNER JOIN
                      CAINVOICEFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CAINVOICEFEE.CACOMPUTEDFEEID INNER JOIN
                      CAINVOICE ON CAINVOICEFEE.CAINVOICEID = CAINVOICE.CAINVOICEID INNER JOIN
                      CASTATUS ON CAINVOICE.CASTATUSID = CASTATUS.CASTATUSID INNER JOIN
                      CASTATUS AS CASTATUS_1 ON CACOMPUTEDFEE.CASTATUSID = CASTATUS_1.CASTATUSID ON 
                      CATRANSACTIONFEE.CACOMPUTEDFEEID = CACOMPUTEDFEE.CACOMPUTEDFEEID
WHERE     (PRPROJECTFEE.PRPROJECTID = @PROJECTID) AND (CASTATUS.CASTATUSID <> 5) AND (CASTATUS_1.CASTATUSID <> 5) AND CATRANSACTIONSTATUS.CATRANSACTIONSTATUSID NOT IN (2,3)

