

CREATE PROCEDURE [dbo].[rpt_PL_SR_Plan_Detail_Report_Hold]
@PLPLANID AS VARCHAR(36)
AS
SELECT PLPLANHOLD.PLPLANHOLDID, PLPLANHOLD.COMMENTS, PLPLANHOLD.CREATEDDATE, PLPLANHOLD.ACTIVE, USERS.FNAME, USERS.LNAME, 
       HOLDTYPESETUPS.NAME AS HOLDTYPE
FROM PLPLANHOLD 
INNER JOIN HOLDTYPESETUPS ON PLPLANHOLD.HOLDSETUPID = HOLDTYPESETUPS.HOLDSETUPID 
INNER JOIN USERS ON PLPLANHOLD.SUSERGUID = USERS.SUSERGUID
WHERE PLPLANHOLD.PLPLANID = @PLPLANID

