



CREATE PROCEDURE [dbo].[RPT_PM_EXPIRED_PERMITS]
@STARTDATE AS DATETIME,
@ENDDATE AS DATETIME
AS
SET @ENDDATE = DATEADD(S,-1,DATEADD(D,1,@ENDDATE))
SELECT PMPERMIT.PERMITNUMBER, PMPERMIT.APPLYDATE, PMPERMIT.EXPIREDATE, PMPERMIT.ISSUEDATE, PMPERMIT.FINALIZEDATE, PMPERMIT.VALUE, PMPERMIT.SQUAREFEET, 
       PMPERMITTYPE.NAME AS PERMITTYPE, PMPERMITWORKCLASS.NAME AS WORKCLASS, PMPERMITSTATUS.NAME AS STATUS, PMPERMIT.PMPERMITID
FROM PMPERMIT 
INNER JOIN PMPERMITTYPE ON PMPERMIT.PMPERMITTYPEID = PMPERMITTYPE.PMPERMITTYPEID 
INNER JOIN PMPERMITWORKCLASS ON PMPERMIT.PMPERMITWORKCLASSID = PMPERMITWORKCLASS.PMPERMITWORKCLASSID 
INNER JOIN PMPERMITSTATUS ON PMPERMIT.PMPERMITSTATUSID = PMPERMITSTATUS.PMPERMITSTATUSID
WHERE PMPERMIT.EXPIREDATE BETWEEN @STARTDATE AND @ENDDATE



