

--[dbo].[RPT_PL_PLAN_PLANNING_ACTIVITY_REPORT] '01/01/2012 00:00:00'

CREATE PROCEDURE [dbo].[rpt_PL_Workload_Completed_Report]
@STARTDATE DATETIME,
@ENDDATE DATETIME
AS

SET @ENDDATE = DATEADD(S,-1,DATEADD(D,1,@ENDDATE))

BEGIN
 --SELECT "PLPlanType"."PLANNAME", "PLPlan"."PLANNUMBER", "Users"."FNAME", "Users"."LNAME", "PLPlan"."APPLICATIONDATE", "PLPlan"."COMPLETED"
 --FROM   ("EnerGov_Gaithersburg"."dbo"."PLPLAN" "PLPlan" INNER JOIN "EnerGov_Gaithersburg"."dbo"."PLPLANTYPE" "PLPlanType" ON "PLPlan"."PLPLANTYPEID"="PLPlanType"."PLPLANTYPEID") INNER JOIN "EnerGov_Gaithersburg"."dbo"."USERS" "Users" ON "PLPlan"."ASSIGNEDTO"="Users"."SUSERGUID"
 --WHERE  ("PLPlan"."APPLICATIONDATE">={ts '2012-12-03 00:00:00'} AND "PLPlan"."APPLICATIONDATE"<{ts '2012-12-15 00:00:00'}) AND "PLPlan"."COMPLETED"=0
 
 
SELECT PL.APPLICATIONDATE, PLPLANTYPE.PLANNAME, PL.PLPLANID, PL.PLANNUMBER, USERS.FNAME, USERS.LNAME, PL.COMPLETED 
FROM PLPLAN PL
INNER JOIN PLPLANTYPE ON PL.PLPLANTYPEID = PLPLANTYPE.PLPLANTYPEID
INNER JOIN USERS ON PL.ASSIGNEDTO = USERS.SUSERGUID
WHERE PL.APPLICATIONDATE >= @STARTDATE  
AND PL.APPLICATIONDATE < @ENDDATE
AND PL.COMPLETED = 1

END

