

CREATE PROCEDURE [dbo].[rpt_PM_SR_Permit_Corrections_Report_Recommendations]
@PLITEMREVIEWID AS VARCHAR(36)
AS
BEGIN

SELECT DISTINCT PIR.PLITEMREVIEWID, PR.RECOMMENDATION, PR.PLPLANRECOMENDATIONID
	, RE.PAGENUMBER, RE.COMMENTS RECOMMENDATION_COMMENTS
FROM PLITEMREVIEW PIR
INNER JOIN PLPLANRECOMMENDATION PR ON PIR.PLITEMREVIEWID = PR.PLITEMREVIEWID
LEFT JOIN ERRECOMMENDATIONELEMENT RE ON PR.PLPLANRECOMENDATIONID = RE.PLPLANRECOMMENDATIONID
WHERE PIR.PLITEMREVIEWID = @PLITEMREVIEWID 
END
