
CREATE PROCEDURE rpt_PM_SR_Permit_Inspection_History_Report_Checklist_Items
@INSPECTIONID AS VARCHAR(36)
AS
BEGIN
SELECT     IMCHECKLIST.NAME AS [CHECKLIST ITEM], IMINSPECTIONCHECKLISTXREF.PASSED, IMINSPECTIONCHECKLISTXREF.COMMENTS, IMINSPECTIONCHECKLISTXREF.IMCHECKLISTID
FROM         IMCHECKLIST INNER JOIN
                      IMINSPECTIONCHECKLISTXREF ON IMCHECKLIST.IMCHECKLISTID = IMINSPECTIONCHECKLISTXREF.IMCHECKLISTID
WHERE IMINSPECTIONCHECKLISTXREF.IMINSPECTIONID = @INSPECTIONID
ORDER BY IMINSPECTIONCHECKLISTXREF.ORDERNUM
END
