

CREATE PROCEDURE rpt_PL_Standard_Plan_Detailed_Fees_Paid 
@PLPLANID VARCHAR(36)
AS

SELECT P.PLPLANID
     , SUM(CF.COMPUTEDAMOUNT) TOTAL

INTO #OWED
FROM PLPLAN P
INNER JOIN PLPLANFEE PF ON p.PLPLANID=PF.PLPLANID
INNER JOIN CACOMPUTEDFEE CF ON PF.CACOMPUTEDFEEID=CF.CACOMPUTEDFEEID AND CF.CASTATUSID NOT IN (5,10)
WHERE P.PLPLANID = @PLPLANID
GROUP BY P.PLPLANID 


SELECT DISTINCT 
	P.PLPLANID,
	O.TOTAL,
	T.CATRANSACTIONID,
	I.CAINVOICEID,I.INVOICENUMBER,
	SUM(CASE WHEN T.CATRANSACTIONTYPEID = 4 THEN 0-TF.REFUNDAMOUNT ELSE TF.PAIDAMOUNT END) PAYMENT_AMOUNT,
	CPM.NAME PAYMETHOD,
	TP.SUPPLEMENTALDATA AS CHECK_NUMBER
	
FROM PLPLAN P
INNER JOIN #OWED O ON P.PLPLANID = O.PLPLANID
INNER JOIN PLPLANFEE PMF ON P.PLPLANID=PMF.PLPLANID
INNER JOIN CACOMPUTEDFEE CF ON PMF.CACOMPUTEDFEEID = CF.CACOMPUTEDFEEID AND CF.CASTATUSID NOT IN (5,10) --VOID, DELETED
INNER JOIN CATRANSACTIONFEE TF ON CF.CACOMPUTEDFEEID = TF.CACOMPUTEDFEEID AND (TF.CASTATUSID NOT IN (5, 10)) --VOID, DELETED
INNER JOIN CATRANSACTION T ON TF.CATRANSACTIONID = T.CATRANSACTIONID AND T.CATRANSACTIONSTATUSID NOT IN (2,3) --VOID, NSF
INNER JOIN CATRANSACTIONPAYMENT TP ON T.CATRANSACTIONID = TP.CATRANSACTIONID AND TP.CAPAYMENTSTATUSID NOT IN (3,5) --NSF, VOID
INNER JOIN CATRANSACTIONTYPE TT ON T.CATRANSACTIONTYPEID = TT.CATRANSACTIONTYPEID AND (TT.CATRANSACTIONTYPEID NOT IN (5, 6)) --NSF, VOID REVERSAL
INNER JOIN CAPAYMENTMETHOD CPM ON CPM.CAPAYMENTMETHODID = TP.CAPAYMENTMETHODID
INNER JOIN CATRANSACTIONINVOICE TI ON TI.CATRANSACTIONID = T.CATRANSACTIONID
INNER JOIN CAINVOICE I ON I.CAINVOICEID = TI.CAINVOICEID
INNER JOIN CAINVOICEFEE CI ON I.CAINVOICEID = CI.CAINVOICEID AND CI.CACOMPUTEDFEEID = CF.CACOMPUTEDFEEID
WHERE P.PLPLANID = @PLPLANID
GROUP BY P.PLPLANID, O.TOTAL, T.CATRANSACTIONID, CPM.NAME, TP.SUPPLEMENTALDATA, I.CAINVOICEID, I.INVOICENUMBER

DROP TABLE #OWED;

