


CREATE PROCEDURE [dbo].[RPT_PM_PERMIT_DETAIL_REPORT]
@PERMITID AS VARCHAR(36)
AS

SELECT PMPERMIT.PERMITNUMBER, PMPERMIT.APPLYDATE, PMPERMIT.EXPIREDATE, PMPERMIT.ISSUEDATE, PMPERMIT.FINALIZEDATE, PMPERMIT.VALUE, PMPERMIT.SQUAREFEET, 
PMPERMIT.DESCRIPTION, PMPERMITSTATUS.NAME AS STATUS, PMPERMITTYPE.NAME AS PERMITTYPE, DISTRICT.NAME AS DISTRICT, PMPERMITWORKCLASS.NAME AS WORKCLASS, 
PMPERMIT.PMPERMITID, PRPROJECT.NAME AS PROJECT
FROM PMPERMIT 
INNER JOIN PMPERMITTYPE ON PMPERMIT.PMPERMITTYPEID = PMPERMITTYPE.PMPERMITTYPEID 
INNER JOIN PMPERMITSTATUS ON PMPERMIT.PMPERMITSTATUSID = PMPERMITSTATUS.PMPERMITSTATUSID 
INNER JOIN PMPERMITWORKCLASS ON PMPERMIT.PMPERMITWORKCLASSID = PMPERMITWORKCLASS.PMPERMITWORKCLASSID 
LEFT OUTER JOIN DISTRICT ON PMPERMIT.DISTRICTID = DISTRICT.DISTRICTID
LEFT OUTER JOIN PRPROJECTPERMIT ON PRPROJECTPERMIT.PMPERMITID = PMPERMIT.PMPERMITID 
LEFT OUTER JOIN PRPROJECT ON PRPROJECT.PRPROJECTID = PRPROJECTPERMIT.PRPROJECTID
WHERE PMPERMIT.PMPERMITID = @PERMITID


