
CREATE PROCEDURE [dbo].[rpt_PM_SR_Permit_Corrections_Report_ERMarkup]
@PLPLANCORRECTIONID AS VARCHAR(36)
AS
BEGIN

SELECT ME.PLPLANCORRECTIONID
	, ME.PAGENUMBER, ME.COMMENTS MARKUP_COMMENTS
FROM ERMARKUPELEMENT ME
WHERE ME.PLPLANCORRECTIONID = @PLPLANCORRECTIONID

END
