

--[dbo].[RPT_PL_PLAN_PLANNING_ACTIVITY_REPORT] '01/01/2012 00:00:00'

CREATE PROCEDURE [dbo].[rpt_PL_PlanCases_ByUser]
@STARTDATE DATETIME,
@ENDDATE DATETIME

AS

BEGIN

SELECT PLPlan.PLANNUMBER, PLPlan.APPLICATIONDATE, PLPlan.[EXPIREDATE], PLPlan.COMPLETED, PLPlanStatus.NAME, Users.FNAME, Users.LNAME

FROM PLPLAN
INNER JOIN PLPLANTYPE ON PLPLAN.PLPLANTYPEID = PLPLANTYPE.PLPLANTYPEID
INNER JOIN PLPLANSTATUS ON PLPLAN.PLPLANSTATUSID = PLPLANSTATUS.PLPLANSTATUSID
LEFT OUTER JOIN USERS ON PLPLAN.ASSIGNEDTO = USERS.SUSERGUID


WHERE PLPlan.APPLICATIONDATE BETWEEN @STARTDATE AND @ENDDATE 


END

