


CREATE PROCEDURE [dbo].[RPT_PM_PERMIT_DETAIL_REPORT_CONTACT]
@PERMITID AS VARCHAR(36)
AS
SELECT PMPERMITCONTACT.GLOBALENTITYID, LANDMANAGEMENTCONTACTTYPE.NAME AS CONTACTTYPE, GLOBALENTITY.GLOBALENTITYNAME, GLOBALENTITY.FirStNAME, 
       GLOBALENTITY.LaStNAME, MAILINGADDRESS.ADDRESSLINE1, MAILINGADDRESS.ADDRESSLINE2, MAILINGADDRESS.ADDRESSLINE3, MAILINGADDRESS.CITY, MAILINGADDRESS.STATE, 
       MAILINGADDRESS.POSTALCODE, MAILINGADDRESS.POSTDIRECTION, MAILINGADDRESS.PREDIRECTION, MAILINGADDRESS.STREETTYPE, MAILINGADDRESS.ADDRESSTYPE, 
       MAILINGADDRESS.UNITORSUITE, GLOBALENTITY.BUSINESSPHONE, GLOBALENTITY.HOMEPHONE, GLOBALENTITY.MOBILEPHONE
FROM PMPERMITCONTACT 
INNER JOIN LANDMANAGEMENTCONTACTTYPE ON PMPERMITCONTACT.LANDMANAGEMENTCONTACTTYPEID = LANDMANAGEMENTCONTACTTYPE.LANDMANAGEMENTCONTACTTYPEID 
INNER JOIN GLOBALENTITY ON PMPERMITCONTACT.GLOBALENTITYID = GLOBALENTITY.GLOBALENTITYID 
LEFT OUTER JOIN GLOBALENTITYMAILINGADDRESS ON GLOBALENTITYMAILINGADDRESS.GLOBALENTITYID = GLOBALENTITY.GLOBALENTITYID
LEFT OUTER JOIN MAILINGADDRESS ON MAILINGADDRESS.MAILINGADDRESSID = GLOBALENTITYMAILINGADDRESS.MAILINGADDRESSID 
WHERE PMPERMITCONTACT.PMPERMITID = @PERMITID


