

CREATE PROCEDURE [dbo].[rpt_PR_SR_Project_Detail_Report_Holds]
@PRPROJECTID AS VARCHAR(36)
AS
SELECT	USERS.FNAME, USERS.LNAME, HOLDTYPE.HOLDTYPENAME AS HoldType, PRPROJECTHOLD.CREATEDDATE, PRPROJECTHOLD.COMMENTS, 
		PRPROJECTHOLD.ACTIVE, PRPROJECTHOLD.PRPROJECTHOLDID
FROM	PRPROJECTHOLD 
INNER JOIN USERS ON PRPROJECTHOLD.SUSERGUID = USERS.SUSERGUID 
INNER JOIN HOLDTYPESETUPS ON PRPROJECTHOLD.HOLDSETUPID = HOLDTYPESETUPS.HOLDSETUPID 
INNER JOIN HOLDTYPE ON HOLDTYPESETUPS.HOLDTYPEID = HOLDTYPE.HOLDTYPEID
WHERE PRPROJECTHOLD.PRPROJECTID = @PRPROJECTID
