

CREATE PROCEDURE [dbo].[RPT_PL_PLAN_HISTORY_REPORT]
@PLANID AS VARCHAR(36)
AS
SELECT USERS.FNAME, USERS.LNAME, PLPLAN.PLANNUMBER AS PLANNUMBER, HISTORYPLANMANAGEMENT.ROWVERSION, HISTORYPLANMANAGEMENT.CHANGEDON, 
       HISTORYPLANMANAGEMENT.FIELDNAME, HISTORYPLANMANAGEMENT.OLDVALUE, HISTORYPLANMANAGEMENT.NEWVALUE, HISTORYPLANMANAGEMENT.ADDITIONALINFO,
       CONVERT(DATEtime,HISTORYPLANMANAGEMENT.CHANGEDON) AS ChangedOnDate
FROM HISTORYPLANMANAGEMENT 
INNER JOIN USERS ON HISTORYPLANMANAGEMENT.CHANGEDBY = USERS.SUSERGUID 
INNER JOIN PLPLAN ON HISTORYPLANMANAGEMENT.ID = PLPLAN.PLPLANID
WHERE PLPLAN.PLPLANID = @PLANID


