

CREATE PROCEDURE [dbo].[rpt_PR_Project_Detail_Report_Applications]
@PROJECTID AS VARCHAR(36)
AS
SELECT     PLAPPLICATION.APPNUMBER, PLAPPLICATIONTYPE.APPLICATIONTYPENAME, PLAPPLICATIONSTATUS.STATUS, PLAPPLICATION.APPLICATIONDATE
FROM         PRPROJECTAPPLICATION INNER JOIN
                      PLAPPLICATION ON PRPROJECTAPPLICATION.PLAPPLICATIONID = PLAPPLICATION.PLAPPLICATIONID INNER JOIN
                      PLAPPLICATIONTYPE ON PLAPPLICATION.PLAPPLICATIONTYPEID = PLAPPLICATIONTYPE.PLAPPLICATIONTYPEID INNER JOIN
                      PLAPPLICATIONSTATUS ON PLAPPLICATION.PLAPPLICATIONSTATUSID = PLAPPLICATIONSTATUS.PLAPPLICATIONSTATUSID
WHERE PRPROJECTAPPLICATION.PRPROJECTID = @PROJECTID

