
CREATE PROCEDURE [dbo].[rpt_PR_SR_Project_History_Report]
@PRPROJECTID AS VARCHAR(36)
AS
SELECT HISTORYPROJMANAGEMENT.ID, HISTORYPROJMANAGEMENT.ROWVERSION, HISTORYPROJMANAGEMENT.CHANGEDON, 
       HISTORYPROJMANAGEMENT.FIELDNAME, HISTORYPROJMANAGEMENT.OLDVALUE, HISTORYPROJMANAGEMENT.NEWVALUE, 
       HISTORYPROJMANAGEMENT.ADDITIONALINFO, USERS.FNAME, USERS.LNAME, PRPROJECT.PROJECTNUMBER,
       PRPROJECT.PRPROJECTID, CONVERT(DATE,HISTORYPROJMANAGEMENT.CHANGEDON) AS ChangedDate,
	   (SELECT R.[IMAGE] FROM RPTIMAGELIB R
		WHERE R.IMAGENAME = 'Municipality_Logo') LOGO,
	   (SELECT CASE WHEN R.[IMAGE] IS NULL THEN 'N' ELSE 'Y' END FROM RPTIMAGELIB R
		WHERE R.IMAGENAME = 'Municipality_Logo') SHOWLOGO,
	   (SELECT R.REPORTTEXT FROM RPTTEXTLIB R
		WHERE R.TEXTNAME = 'Municipality_Name') Municipality_Name,	   
	   (SELECT R.REPORTTEXT FROM RPTTEXTLIB R
		WHERE R.TEXTNAME = 'Municipality_Page_Footer') Municipality_Page_Footer

FROM HISTORYPROJMANAGEMENT
INNER JOIN PRPROJECT ON HISTORYPROJMANAGEMENT.ID = PRPROJECT.PRPROJECTID
INNER JOIN USERS ON HISTORYPROJMANAGEMENT.CHANGEDBY = USERS.SUSERGUID
WHERE PRPROJECT.PRPROJECTID = @PRPROJECTID
