

/****** Object:  StoredProcedure [dbo].[rpt_PM_SR_Permit_Detailed_Report_ACTIVITY]    Script Date: 02/25/2011 15:58:53 ******/
CREATE PROCEDURE [dbo].[rpt_PM_SR_Permit_Detailed_Report_Activity]
@PMPERMITID AS VARCHAR(36)
AS

SELECT PMPERMITACTIVITY.PMPERMITACTIVITYID, PMPERMITACTIVITY.PERMITACTIVITYNAME, PMPERMITACTIVITY.PERMITACTIVITYNUMBER, PMPERMITACTIVITYTYPE.NAME AS ACTIVITYTYPE, 
       USERS.FNAME, USERS.LNAME, PMPERMITACTIVITY.CREATEDON
       
FROM PMPERMITACTIVITY 
INNER JOIN PMPERMITACTIVITYTYPE ON PMPERMITACTIVITY.PMPERMITACTIVITYTYPEID = PMPERMITACTIVITYTYPE.PMPERMITACTIVITYTYPEID 
INNER JOIN USERS ON PMPERMITACTIVITY.SUSERGUID = USERS.SUSERGUID
WHERE PMPERMITACTIVITY.PMPERMITID = @PMPERMITID

