

CREATE PROCEDURE [dbo].[rpt_PL_SR_Plan_Detail_Report_Fees]
@PLPLANID AS VARCHAR(36)
AS
SELECT	PLPLANFEE.PLPLANID, CACOMPUTEDFEE.FEENAME, CACOMPUTEDFEE.COMPUTEDAMOUNT, CACOMPUTEDFEE.AMOUNTPAIDTODATE AS PAIDAMOUNT, CACOMPUTEDFEE.CACOMPUTEDFEEID, 
		ISNULL(CAINVOICE.INVOICENUMBER,'NOT INVOICED') INVOICENUMBER, CAINVOICE.CAINVOICEID
FROM PLPLANFEE 
INNER JOIN CACOMPUTEDFEE ON PLPLANFEE.CACOMPUTEDFEEID = CACOMPUTEDFEE.CACOMPUTEDFEEID 
	AND NOT CACOMPUTEDFEE.CASTATUSID in (5,10)
LEFT OUTER JOIN CAINVOICEFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CAINVOICEFEE.CACOMPUTEDFEEID 
LEFT OUTER JOIN CAINVOICE ON CAINVOICEFEE.CAINVOICEID = CAINVOICE.CAINVOICEID 
	AND CAINVOICE.CASTATUSID NOT IN (5,10)
WHERE PLPLANFEE.PLPLANID = @PLPLANID

