

/****** Object:  StoredProcedure [dbo].[rpt_PM_SR_Permit_Detailed_Report_NOTE]    Script Date: 02/25/2011 15:58:53 ******/
CREATE PROCEDURE [dbo].[rpt_PM_SR_Permit_Detailed_Report_Note]
@PMPERMITID AS VARCHAR(36)
AS

SELECT PMPERMITNOTE.PMPERMITNOTEID, PMPERMITNOTE.TEXT, PMPERMITNOTE.CREATEDBY, PMPERMITNOTE.CREATEDDATE, USERS.FNAME, USERS.LNAME

FROM PMPERMITNOTE 
INNER JOIN USERS ON PMPERMITNOTE.CREATEDBY = USERS.SUSERGUID
WHERE PMPERMITNOTE.PMPERMITID = @PMPERMITID

