

/****** Object:  StoredProcedure [dbo].[rpt_PM_SR_Permit_Detailed_Report_OBJECT]    Script Date: 1/16/2014 1:36:39 PM ******/
CREATE PROCEDURE [dbo].[rpt_PM_SR_Permit_Detailed_Report_Object]
@PMPERMITID AS VARCHAR(36)
AS

SELECT	PMPERMITOBJECT.PMPERMITID,
		OMOBJECT.OMOBJECTID, OMOBJECT.OBJECTNUMBER, OMOBJECT.INSTALLDATE, OMOBJECT.OPERATIONSTARTDATE, OMOBJECT.OPERATIONENDDATE,
		OMOBJECTTYPE.NAME OBJECTTYPE,
		OMOBJECTCLASSIFICATION.NAME OBJECTCLASS,
		OMOBJECTSTATUS.NAME OBJECTSTATUS

FROM	PMPERMITOBJECT 
		INNER JOIN OMOBJECT ON PMPERMITOBJECT.OMOBJECTID = OMOBJECT.OMOBJECTID
		INNER JOIN OMOBJECTTYPE ON OMOBJECT.OMOBJECTTYPEID = OMOBJECTTYPE.OMOBJECTTYPEID
		INNER JOIN OMOBJECTCLASSIFICATION ON OMOBJECT.OMOBJECTCLASSIFICATIONID = OMOBJECTCLASSIFICATION.OMOBJECTCLASSIFICATIONID
		INNER JOIN OMOBJECTSTATUS ON OMOBJECT.OMOBJECTSTATUSID = OMOBJECTSTATUS.OMOBJECTSTATUSID
WHERE	PMPERMITOBJECT.PMPERMITID = @PMPERMITID

