


CREATE PROCEDURE [dbo].[RPT_PM_PERMIT_BONDS_CONTACTS]
@GLOBALENTITYID AS VARCHAR(36)
AS
SELECT GLOBALENTITYNAME, FIRSTNAME, LASTNAME
FROM GLOBALENTITY
WHERE GLOBALENTITY.GLOBALENTITYID = @GLOBALENTITYID


