

/****** Object:  StoredProcedure [dbo].[rpt_PM_SR_Permit_Detailed_Report_ADDRESS]    Script Date: 02/25/2011 15:58:53 ******/
CREATE PROCEDURE [dbo].[rpt_PM_SR_Permit_Detailed_Report_Address]
@PMPERMITID AS VARCHAR(36)
AS

SELECT MAILINGADDRESS.ADDRESSLINE1, MAILINGADDRESS.ADDRESSLINE2, MAILINGADDRESS.ADDRESSLINE3, MAILINGADDRESS.CITY, MAILINGADDRESS.STATE, MAILINGADDRESS.POSTALCODE, 
       MAILINGADDRESS.POSTDIRECTION, MAILINGADDRESS.PREDIRECTION, MAILINGADDRESS.STREETTYPE, MAILINGADDRESS.PARCELNUMBER, MAILINGADDRESS.UNITORSUITE, PMPERMITADDRESS.MAILINGADDRESSID, PMPERMITADDRESS.MAIN

FROM PMPERMITADDRESS 
INNER JOIN MAILINGADDRESS ON PMPERMITADDRESS.MAILINGADDRESSID = MAILINGADDRESS.MAILINGADDRESSID
WHERE PMPERMITADDRESS.PMPERMITID = @PMPERMITID

