



CREATE PROCEDURE [dbo].[RPT_PM_PERMITS_BY_PARCEL_REPORT]
@PARCELID AS VARCHAR(36)
AS

SELECT PMPERMIT.PERMITNUMBER, PMPERMITTYPE.NAME AS PERMITTYPE, PMPERMITSTATUS.NAME AS STATUS, PARCEL.PARCELNUMBER, PMPERMITWORKCLASS.NAME AS WORKCLASS, 
       PMPERMIT.ISSUEDATE, PMPERMIT.EXPIREDATE, PARCEL.PARCELID
FROM PMPERMITTYPE 
INNER JOIN PMPERMIT ON PMPERMITTYPE.PMPERMITTYPEID = PMPERMIT.PMPERMITTYPEID 
INNER JOIN PMPERMITWORKCLASS ON PMPERMIT.PMPERMITWORKCLASSID = PMPERMITWORKCLASS.PMPERMITWORKCLASSID 
INNER JOIN PMPERMITSTATUS ON PMPERMIT.PMPERMITSTATUSID = PMPERMITSTATUS.PMPERMITSTATUSID 
LEFT OUTER JOIN PMPERMITPARCEL ON PMPERMIT.PMPERMITID = PMPERMITPARCEL.PMPERMITID
LEFT OUTER JOIN PARCEL ON PMPERMITPARCEL.PARCELID = PARCEL.PARCELID 

WHERE PARCEL.PARCELID = @PARCELID 
AND PMPERMITPARCEL.MAIN = 'TRUE'



