CREATE PROCEDURE [dbo].[USP_PLCONTACTTYPEREF_UPDATE]
(
	@CONTACTTYPEEXTID CHAR(36),
	@LANDMANAGEMENTCONTACTTYPEID CHAR(36),
	@CONTACTTYPEGROUP INT,
	@ISREQUIRED BIT,
	@OBJCLASSID CHAR(36),
	@OBJTYPEID CHAR(36),
	@OBJMODULEID INT
)
AS

UPDATE [dbo].[PLCONTACTTYPEREF] SET
	[LANDMANAGEMENTCONTACTTYPEID] = @LANDMANAGEMENTCONTACTTYPEID,
	[CONTACTTYPEGROUP] = @CONTACTTYPEGROUP,
	[ISREQUIRED] = @ISREQUIRED,
	[OBJCLASSID] = @OBJCLASSID,
	[OBJTYPEID] = @OBJTYPEID,
	[OBJMODULEID] = @OBJMODULEID

WHERE
	[CONTACTTYPEEXTID] = @CONTACTTYPEEXTID