CREATE PROCEDURE [dbo].[USP_PMPERMITVALUATIONTYPEVALGROUPX_UPDATE]
(
	@PMPERMITVALUATIONTYPEVALGRPXID CHAR(36),
	@PMPERMITVALUATIONTYPEID CHAR(36),
	@PMPERMITVALUATIONGROUPID CHAR(36),
	@PMPERMITVALTYPEVALGRPID CHAR(36),
	@FACTOR DECIMAL(18,2),
	@EDITABLE BIT
)
AS

UPDATE	[dbo].[PMPERMITVALUATIONTYPEVALGROUPX] 
SET		[PMPERMITVALUATIONTYPEID] = @PMPERMITVALUATIONTYPEID,
		[PMPERMITVALUATIONGROUPID] = @PMPERMITVALUATIONGROUPID,
		[PMPERMITVALTYPEVALGRPID] = @PMPERMITVALTYPEVALGRPID,
		[FACTOR] = @FACTOR,
		[EDITABLE] = @EDITABLE
WHERE	[PMPERMITVALUATIONTYPEVALGRPXID] = @PMPERMITVALUATIONTYPEVALGRPXID