CREATE PROCEDURE [dbo].[USP_PLPLANTYPEGROUP_DELETE]
(
	@PLPLANTYPEGROUPID CHAR(36),
	@ROWVERSION INT
)
AS
DELETE FROM [dbo].[PLPLANTYPEGROUP]
WHERE
	[PLPLANTYPEGROUPID] = @PLPLANTYPEGROUPID AND 
	[ROWVERSION]= @ROWVERSION