CREATE PROCEDURE [dbo].[USP_PLPLANTYPEWORKCLASS_DELETE]
(
@PLPLANTYPEWORKCLASSID CHAR(36)
)
AS

DECLARE @PLANTYPEID CHAR(36), @PLANWORKCLASSID CHAR(36)

SELECT @PLANTYPEID = [PLPLANTYPEID], @PLANWORKCLASSID = [PLPLANWORKCLASSID] 
	FROM [dbo].[PLPLANTYPEWORKCLASS] WHERE [PLPLANTYPEWORKCLASSID] = @PLPLANTYPEWORKCLASSID

-- Delete Allowed Unit types for (plantype, planworkclass)
EXEC [USP_PLPLANTYPEUNITTYPE_DELETE_BYPARENTID] @PLANTYPEID, @PLANWORKCLASSID


-- Delete Contact types for (plantype, planworkclass)
EXEC [USP_PLCONTACTTYPEREF_PLPLANTYPE_DELETE_BYPARENTID] @PLANTYPEID, @PLPLANTYPEWORKCLASSID

-- Delete System task type workclass for (plantype,planworkclass)
EXEC [common].[USP_SYSTEMTASKTYPEWORKCLASS_DELETE_BYPARENTID] @PLANTYPEID, @PLPLANTYPEWORKCLASSID

DELETE FROM [dbo].[PLPLANTYPEWORKCLASS]
WHERE
	[PLPLANTYPEWORKCLASSID] = @PLPLANTYPEWORKCLASSID