CREATE PROCEDURE [dbo].[USP_PMPERMITVALUATIONGROUP_DELETE]
(
	@PMPERMITVALUATIONGROUPID CHAR(36),
	@ROWVERSION INT
)
AS
DELETE FROM [dbo].[PMPERMITVALUATIONGROUP]
WHERE
	[PMPERMITVALUATIONGROUPID] = @PMPERMITVALUATIONGROUPID AND 
	[ROWVERSION]= @ROWVERSION