CREATE PROCEDURE [dbo].[USP_PRPROJECTSTATUS_INSERT]
(
	@PRPROJECTSTATUSID CHAR(36),
	@NAME NVARCHAR(100),
	@DESCRIPTION NVARCHAR(MAX),
	@HOLDFLAG BIT,
	@COMPLETEDFLAG BIT,
	@CANCELLEDFLAG BIT,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
INSERT INTO [dbo].[PRPROJECTSTATUS](
	[PRPROJECTSTATUSID],
	[NAME],
	[DESCRIPTION],
	[HOLDFLAG],
	[COMPLETEDFLAG],
	[CANCELLEDFLAG],
	[LASTCHANGEDBY],
	[LASTCHANGEDON],
	[ROWVERSION]
)
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
VALUES
(
	@PRPROJECTSTATUSID,
	@NAME,
	@DESCRIPTION,
	@HOLDFLAG,
	@COMPLETEDFLAG,
	@CANCELLEDFLAG,
	@LASTCHANGEDBY,
	@LASTCHANGEDON,
	@ROWVERSION
)
SELECT * FROM @OUTPUTTABLE