CREATE PROCEDURE [dbo].[USP_PLPLANALLOWEDACTIVITY_INSERT]
(
	@PLPLANALLOWEDACTIVITYID CHAR(36),
	@PLPLANTYPEID CHAR(36),
	@PLPLANACTIVITYTYPEID CHAR(36)
)
AS

INSERT INTO [dbo].[PLPLANALLOWEDACTIVITY](
	[PLPLANALLOWEDACTIVITYID],
	[PLPLANTYPEID],
	[PLPLANACTIVITYTYPEID]
)

VALUES
(
	@PLPLANALLOWEDACTIVITYID,
	@PLPLANTYPEID,
	@PLPLANACTIVITYTYPEID
)