CREATE PROCEDURE [dbo].[USP_PLPLANACTIVITYTYPE_DELETE]
(
	@PLPLANACTIVITYTYPEID CHAR(36),
	@ROWVERSION INT
)
AS
DELETE FROM [dbo].[PLPLANACTIVITYTYPE]
WHERE
	[PLPLANACTIVITYTYPEID] = @PLPLANACTIVITYTYPEID AND 
	[ROWVERSION]= @ROWVERSION