CREATE PROCEDURE [dbo].[USP_PMPERMITVALUATIONTYPEVALGROUPX_INSERT]
(
	@PMPERMITVALUATIONTYPEVALGRPXID CHAR(36),
	@PMPERMITVALUATIONTYPEID CHAR(36),
	@PMPERMITVALUATIONGROUPID CHAR(36),
	@PMPERMITVALTYPEVALGRPID CHAR(36),
	@FACTOR DECIMAL(18,2),
	@EDITABLE BIT
)
AS

INSERT INTO [dbo].[PMPERMITVALUATIONTYPEVALGROUPX]
(
	[PMPERMITVALUATIONTYPEVALGRPXID],
	[PMPERMITVALUATIONTYPEID],
	[PMPERMITVALUATIONGROUPID],
	[PMPERMITVALTYPEVALGRPID],
	[FACTOR],
	[EDITABLE]
)

VALUES
(
	@PMPERMITVALUATIONTYPEVALGRPXID,
	@PMPERMITVALUATIONTYPEID,
	@PMPERMITVALUATIONGROUPID,
	@PMPERMITVALTYPEVALGRPID,
	@FACTOR,
	@EDITABLE
)