CREATE PROCEDURE [dbo].[USP_PARCELCONTACTTYPE_UPDATE]
(
	@PARCELCONTACTTYPEID CHAR(36),
	@NAME VARCHAR(50),
	@DESCRIPTION NVARCHAR(MAX),
	@PARCELCONTACTSYSTEMTYPEID INT,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
UPDATE [dbo].[PARCELCONTACTTYPE] SET
	[NAME] = @NAME,
	[DESCRIPTION] = @DESCRIPTION,
	[PARCELCONTACTSYSTEMTYPEID] = @PARCELCONTACTSYSTEMTYPEID,
	[LASTCHANGEDBY] = @LASTCHANGEDBY,
	[LASTCHANGEDON] = @LASTCHANGEDON,
	[ROWVERSION] = @ROWVERSION + 1
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE
	[PARCELCONTACTTYPEID] = @PARCELCONTACTTYPEID AND 
	[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE