CREATE PROCEDURE [dbo].[USP_PMPERMITACTIVITYTYPE_UPDATE]
(
	@PMPERMITACTIVITYTYPEID CHAR(36),
	@NAME NVARCHAR(50),
	@DESCRIPTION NVARCHAR(MAX),
	@CANEDIT BIT,
	@PREFIXID NVARCHAR(10),
	@ALLOWDUPLICATE BIT,
	@CREATEID BIT,
	@CUSTOMFIELDID CHAR(36),
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
UPDATE [dbo].[PMPERMITACTIVITYTYPE] SET
	[NAME] = @NAME,
	[DESCRIPTION] = @DESCRIPTION,
	[CANEDIT] = @CANEDIT,
	[PREFIXID] = @PREFIXID,
	[ALLOWDUPLICATE] = @ALLOWDUPLICATE,
	[CREATEID] = @CREATEID,
	[CUSTOMFIELDID] = @CUSTOMFIELDID,
	[LASTCHANGEDBY] = @LASTCHANGEDBY,
	[LASTCHANGEDON] = @LASTCHANGEDON,
	[ROWVERSION] = @ROWVERSION + 1
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE
	[PMPERMITACTIVITYTYPEID] = @PMPERMITACTIVITYTYPEID AND 
	[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE