CREATE PROCEDURE [dbo].[USP_PMPERMITVALUATIONTYPEVALGROUP_UPDATE]
(
	@PMPERMITVALTYPEVALGRPID CHAR(36),
	@NAME NVARCHAR(255),
	@DESCRIPTION NVARCHAR(MAX),
	@EFFECTIVEDATE DATETIME,
	@EXPIRATIONDATE DATETIME,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
UPDATE	[dbo].[PMPERMITVALUATIONTYPEVALGROUP] 
SET		[NAME] = @NAME,
		[DESCRIPTION] = @DESCRIPTION,
		[EFFECTIVEDATE] = @EFFECTIVEDATE,
		[EXPIRATIONDATE] = @EXPIRATIONDATE,
		[LASTCHANGEDBY] = @LASTCHANGEDBY,
		[LASTCHANGEDON] = @LASTCHANGEDON,
		[ROWVERSION] = @ROWVERSION + 1
OUTPUT	inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE	[PMPERMITVALTYPEVALGRPID] = @PMPERMITVALTYPEVALGRPID AND 
		[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE