CREATE PROCEDURE [dbo].[USP_PMPERMITTYPEUNITTYPE_INSERT]
(
	@PMPERMITTYPEIPUNITTYPEID CHAR(36),
	@PMPERMITTYPEID CHAR(36),
	@PMPERMITWORKCLASSID CHAR(36),
	@IPUNITTYPEID CHAR(36),
	@ISREQUIRED BIT,
	@UNITTYPEGROUP INT
)
AS

INSERT INTO [dbo].[PMPERMITTYPEUNITTYPE](
	[PMPERMITTYPEIPUNITTYPEID],
	[PMPERMITTYPEID],
	[PMPERMITWORKCLASSID],
	[IPUNITTYPEID],
	[ISREQUIRED],
	[UNITTYPEGROUP]
)

VALUES
(
	@PMPERMITTYPEIPUNITTYPEID,
	@PMPERMITTYPEID,
	@PMPERMITWORKCLASSID,
	@IPUNITTYPEID,
	@ISREQUIRED,
	@UNITTYPEGROUP
)