CREATE PROCEDURE [dbo].[USP_PLAPPLICATIONSTATUS_DELETE]
(
	@PLAPPLICATIONSTATUSID CHAR(36),
	@ROWVERSION INT
)
AS
DELETE FROM [dbo].[PLAPPLICATIONSTATUS]
WHERE
	[PLAPPLICATIONSTATUSID] = @PLAPPLICATIONSTATUSID AND 
	[ROWVERSION]= @ROWVERSION