CREATE PROCEDURE [dbo].[USP_PLPLANSTATUS_UPDATE]
(
	@PLPLANSTATUSID CHAR(36),
	@NAME NVARCHAR(100),
	@SUCCESSFLAG BIT,
	@HOLDFLAG BIT,
	@FAILUREFLAG BIT,
	@CANCELLEDFLAG BIT,
	@DESCRIPTION NVARCHAR(MAX),
	@DESCRIPTION_SPANISH NVARCHAR(MAX),
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
UPDATE [dbo].[PLPLANSTATUS] SET
	[NAME] = @NAME,
	[SUCCESSFLAG] = @SUCCESSFLAG,
	[HOLDFLAG] = @HOLDFLAG,
	[FAILUREFLAG] = @FAILUREFLAG,
	[CANCELLEDFLAG] = @CANCELLEDFLAG,
	[DESCRIPTION] = @DESCRIPTION,
	[DESCRIPTION_SPANISH] = @DESCRIPTION_SPANISH,
	[LASTCHANGEDBY] = @LASTCHANGEDBY,
	[LASTCHANGEDON] = @LASTCHANGEDON,
	[ROWVERSION] = @ROWVERSION + 1
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE
	[PLPLANSTATUSID] = @PLPLANSTATUSID AND 
	[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE