CREATE PROCEDURE [dbo].[USP_PLPLANADDRESS_UPDATE]
(
	@PLPLANADDRESSID CHAR(36),
	@MAIN BIT
)
AS
BEGIN
BEGIN
		UPDATE [dbo].[PLPLANADDRESS] SET [MAIN] = @MAIN
		WHERE [PLPLANADDRESSID] = @PLPLANADDRESSID
	END
END