CREATE PROCEDURE [dbo].[USP_PRPROJECTSTATUS_UPDATE]
(
	@PRPROJECTSTATUSID CHAR(36),
	@NAME NVARCHAR(100),
	@DESCRIPTION NVARCHAR(MAX),
	@HOLDFLAG BIT,
	@COMPLETEDFLAG BIT,
	@CANCELLEDFLAG BIT,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
UPDATE [dbo].[PRPROJECTSTATUS] SET
	[NAME] = @NAME,
	[DESCRIPTION] = @DESCRIPTION,
	[HOLDFLAG] = @HOLDFLAG,
	[COMPLETEDFLAG] = @COMPLETEDFLAG,
	[CANCELLEDFLAG] = @CANCELLEDFLAG,
	[LASTCHANGEDBY] = @LASTCHANGEDBY,
	[LASTCHANGEDON] = @LASTCHANGEDON,
	[ROWVERSION] = @ROWVERSION + 1
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE
	[PRPROJECTSTATUSID] = @PRPROJECTSTATUSID AND 
	[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE