CREATE PROCEDURE [dbo].[USP_PMPERMITTYPEBUSLICTYPE_UPDATE]
(
	@PMPERMITTYPEBUSLICTYPEID CHAR(36),
	@PMPERMITTYPEID CHAR(36),
	@PMPERMITWORKCLASSID CHAR(36),
	@BLLICENSETYPEID CHAR(36),
	@PMPERMITTYPEWORKCLASSID CHAR(36)
)
AS

UPDATE [dbo].[PMPERMITTYPEBUSLICTYPE] SET
	[PMPERMITTYPEID] = @PMPERMITTYPEID,
	[PMPERMITWORKCLASSID] = @PMPERMITWORKCLASSID,
	[BLLICENSETYPEID] = @BLLICENSETYPEID,
	[PMPERMITTYPEWORKCLASSID] = @PMPERMITTYPEWORKCLASSID

WHERE
	[PMPERMITTYPEBUSLICTYPEID] = @PMPERMITTYPEBUSLICTYPEID