CREATE PROCEDURE [dbo].[USP_PLPLANTYPEWORKCLASS_UPDATE]
(
	@PLPLANTYPEWORKCLASSID CHAR(36),
	@PLPLANTYPEID CHAR(36),
	@PLPLANWORKCLASSID CHAR(36),
	@WFTEMPLATEID CHAR(36),
	@CUSTOMFIELDLAYOUTID CHAR(36),
	@CAFEETEMPLATEID CHAR(36),
	@ONLINECUSTOMFIELDLAYOUTID CHAR(36),
	@INTERNETFLAG BIT,
	@PLPLANCAPAPPLICATIONTYPEID INT,
	@ISCAPADDRESSREQUIRED BIT,
	@PLREVIEWITEMCAPVISIBILITYID INT,
	@FILESETID CHAR(36),
	@DEFAULTCASEASSIGNEDTO CHAR(36)
)
AS

UPDATE [dbo].[PLPLANTYPEWORKCLASS] SET
	[PLPLANTYPEID] = @PLPLANTYPEID,
	[PLPLANWORKCLASSID] = @PLPLANWORKCLASSID,
	[WFTEMPLATEID] = @WFTEMPLATEID,
	[CUSTOMFIELDLAYOUTID] = @CUSTOMFIELDLAYOUTID,
	[CAFEETEMPLATEID] = @CAFEETEMPLATEID,
	[ONLINECUSTOMFIELDLAYOUTID] = @ONLINECUSTOMFIELDLAYOUTID,
	[INTERNETFLAG] = @INTERNETFLAG,
	[PLPLANCAPAPPLICATIONTYPEID] = @PLPLANCAPAPPLICATIONTYPEID,
	[ISCAPADDRESSREQUIRED] = @ISCAPADDRESSREQUIRED,
	[PLREVIEWITEMCAPVISIBILITYID] = @PLREVIEWITEMCAPVISIBILITYID,
	[FILESETID] = @FILESETID,
	[DEFAULTCASEASSIGNEDTO] = @DEFAULTCASEASSIGNEDTO

WHERE
	[PLPLANTYPEWORKCLASSID] = @PLPLANTYPEWORKCLASSID