CREATE PROCEDURE [dbo].[USP_PMPERMITACTIVITYTYPE_DELETE]
(
	@PMPERMITACTIVITYTYPEID CHAR(36),
	@ROWVERSION INT
)
AS
DELETE FROM [dbo].[PMPERMITACTIVITYTYPE]
WHERE
	[PMPERMITACTIVITYTYPEID] = @PMPERMITACTIVITYTYPEID AND 
	[ROWVERSION]= @ROWVERSION