CREATE PROCEDURE [dbo].[USP_PERMITEVENTQUEUE_UPDATE]
(
@PERMITEVENTQUEUEID AS BIGINT,
@EVENTSTATUSID INT
)
AS  
BEGIN  
	SET NOCOUNT ON;
	UPDATE [dbo].PERMITEVENTQUEUE
	SET 
		PROCESSEDDATE = GETDATE(),
		EVENTSTATUSID = @EVENTSTATUSID
	WHERE [dbo].PERMITEVENTQUEUE.PERMITEVENTQUEUEID = @PERMITEVENTQUEUEID

END