CREATE PROCEDURE [dbo].[USP_PLSUBMITTALTYPEITEMREVIEWTYPEX_DELETE]
(
 @PLSUBMITTALTYPEITEMREVWTYPXID CHAR(36)
)
AS

DELETE FROM [dbo].[PLSUBMITTALTYPEITEMREVIEWTYPEX] 
WHERE [dbo].[PLSUBMITTALTYPEITEMREVIEWTYPEX].[PLSUBMITTALTYPEITEMREVWTYPXID] = @PLSUBMITTALTYPEITEMREVWTYPXID