CREATE PROCEDURE [dbo].[USP_PMWCCERTCLASS_DELETE_BYPARENTID]  
(  
@PERMITTYPEID CHAR(36),
@PERMITWORKCLASSID CHAR(36),
@PMPERMITTYPELICENSETYPEID CHAR(36)
)  
AS  
DELETE [dbo].[PMWCCERTCLASS] FROM [dbo].[PMWCCERTCLASS]
INNER JOIN [dbo].[PMPERMITTYPELICENSETYPE] ON [dbo].[PMWCCERTCLASS].[PMPERMITTYPELICENSETYPEID] = [dbo].[PMPERMITTYPELICENSETYPE].[PMPERMITTYPELICENSETYPEID]
WHERE
	(@PMPERMITTYPELICENSETYPEID IS NULL OR [dbo].[PMPERMITTYPELICENSETYPE].[PMPERMITTYPELICENSETYPEID] = @PMPERMITTYPELICENSETYPEID) 
	AND (@PERMITTYPEID IS NULL OR [dbo].[PMPERMITTYPELICENSETYPE].[PMPERMITTYPEID] = @PERMITTYPEID) 
	AND (@PERMITWORKCLASSID IS NULL OR [dbo].[PMPERMITTYPELICENSETYPE].[PMPERMITWORKCLASSID] = @PERMITWORKCLASSID)