CREATE PROCEDURE [dbo].[USP_PMPERMITDIMENSIONCATEGORY_UPDATE]
(
	@PMPERMITDIMENSIONCATEGORYID CHAR(36),
	@CATEGORY NVARCHAR(100),
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
UPDATE [dbo].[PMPERMITDIMENSIONCATEGORY] SET
	[CATEGORY] = @CATEGORY,
	[LASTCHANGEDBY] = @LASTCHANGEDBY,
	[LASTCHANGEDON] = @LASTCHANGEDON,
	[ROWVERSION] = @ROWVERSION + 1
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE
	[PMPERMITDIMENSIONCATEGORYID] = @PMPERMITDIMENSIONCATEGORYID AND 
	[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE