CREATE PROCEDURE [dbo].[USP_PMPERMITTYPEUNITTYPE_UPDATE]
(
	@PMPERMITTYPEIPUNITTYPEID CHAR(36),
	@PMPERMITTYPEID CHAR(36),
	@PMPERMITWORKCLASSID CHAR(36),
	@IPUNITTYPEID CHAR(36),
	@ISREQUIRED BIT,
	@UNITTYPEGROUP INT
)
AS

UPDATE [dbo].[PMPERMITTYPEUNITTYPE] SET
	[PMPERMITTYPEID] = @PMPERMITTYPEID,
	[PMPERMITWORKCLASSID] = @PMPERMITWORKCLASSID,
	[IPUNITTYPEID] = @IPUNITTYPEID,
	[ISREQUIRED] = @ISREQUIRED,
	[UNITTYPEGROUP] = @UNITTYPEGROUP

WHERE
	[PMPERMITTYPEIPUNITTYPEID] = @PMPERMITTYPEIPUNITTYPEID