CREATE PROCEDURE [dbo].[USP_PMPERMITTYPEILLICTYPEILWCT_INSERT]
(
	@PMPERMITTYPEILLICENSETYPEID CHAR(36),
	@ILLICENSECLASSIFICATIONTYPEID CHAR(36)
)
AS

INSERT INTO [dbo].[PMPERMITTYPEILLICTYPEILWCT](
	[PMPERMITTYPEILLICENSETYPEID],
	[ILLICENSECLASSIFICATIONTYPEID]
)

VALUES
(
	@PMPERMITTYPEILLICENSETYPEID,
	@ILLICENSECLASSIFICATIONTYPEID
)