CREATE PROCEDURE [dbo].[USP_PMPERMITDIMENSIONCATEGORY_INSERT]
(
	@PMPERMITDIMENSIONCATEGORYID CHAR(36),
	@CATEGORY NVARCHAR(100),
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
INSERT INTO [dbo].[PMPERMITDIMENSIONCATEGORY](
	[PMPERMITDIMENSIONCATEGORYID],
	[CATEGORY],
	[LASTCHANGEDBY],
	[LASTCHANGEDON],
	[ROWVERSION]
)
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
VALUES
(
	@PMPERMITDIMENSIONCATEGORYID,
	@CATEGORY,
	@LASTCHANGEDBY,
	@LASTCHANGEDON,
	@ROWVERSION
)
SELECT * FROM @OUTPUTTABLE