CREATE PROCEDURE [dbo].[USP_PMPERMITTYPELICENSETYPE_UPDATE]
(
	@PMPERMITTYPELICENSETYPEID CHAR(36),
	@PMPERMITTYPEID CHAR(36),
	@PMPERMITWORKCLASSID CHAR(36),
	@COSIMPLELICCERTTYPEID CHAR(36),
	@REQUIREALLCERTCLASS BIT
)
AS

UPDATE [dbo].[PMPERMITTYPELICENSETYPE] SET
	[PMPERMITTYPEID] = @PMPERMITTYPEID,
	[PMPERMITWORKCLASSID] = @PMPERMITWORKCLASSID,
	[COSIMPLELICCERTTYPEID] = @COSIMPLELICCERTTYPEID,
	[REQUIREALLCERTCLASS] = @REQUIREALLCERTCLASS

WHERE
	[PMPERMITTYPELICENSETYPEID] = @PMPERMITTYPELICENSETYPEID