CREATE PROCEDURE [dbo].[USP_PMPERMITTYPE_DELETE]
(
	@PMPERMITTYPEID CHAR(36),
	@ROWVERSION INT
)
AS

SET NOCOUNT ON;

EXEC [dbo].[USP_PMPERMITALLOWEDACTIVITY_DELETE_BYPARENTID] @PMPERMITTYPEID

EXEC [dbo].[USP_PMPERMITTYPEWORKCLASS_DELETE_BYPARENTID] @PMPERMITTYPEID

SET NOCOUNT OFF;
DELETE FROM [dbo].[PMPERMITTYPE]
WHERE
	[PMPERMITTYPEID] = @PMPERMITTYPEID AND 
	[ROWVERSION]= @ROWVERSION