CREATE PROCEDURE [dbo].[USP_PRPROJECTTYPEPERMITLIMIT_INSERT]
(
	@PRPROJECTTYPEPERMITLIMITID CHAR(36),
	@PRPROJECTTYPEID CHAR(36),
	@PMPERMITTYPEID CHAR(36),
	@PMPERMITWORKCLASSID CHAR(36),
	@PERMITLIMIT INT
)
AS

INSERT INTO [dbo].[PRPROJECTTYPEPERMITLIMIT](
	[PRPROJECTTYPEPERMITLIMITID],
	[PRPROJECTTYPEID],
	[PMPERMITTYPEID],
	[PMPERMITWORKCLASSID],
	[PERMITLIMIT]
)

VALUES
(
	@PRPROJECTTYPEPERMITLIMITID,
	@PRPROJECTTYPEID,
	@PMPERMITTYPEID,
	@PMPERMITWORKCLASSID,
	@PERMITLIMIT
)