CREATE PROCEDURE [dbo].[USP_PLITEMREVIEWSTATUS_DELETE]
(
	@PLITEMREVIEWSTATUSID CHAR(36),
	@ROWVERSION INT
)
AS
DELETE FROM [dbo].[PLITEMREVIEWSTATUS]
WHERE
	[PLITEMREVIEWSTATUSID] = @PLITEMREVIEWSTATUSID AND 
	[ROWVERSION]= @ROWVERSION