CREATE PROCEDURE [dbo].[USP_PLAPPLICATIONALLOWEDACTIVITY_DELETE]
(
	@PLAPPLICATIONALLOWEDACTIVITYID CHAR(36)
)
AS
DELETE FROM [dbo].[PLAPPLICATIONALLOWEDACTIVITY]
WHERE
	[PLAPPLICATIONALLOWEDACTIVITYID] = @PLAPPLICATIONALLOWEDACTIVITYID