CREATE PROCEDURE [dbo].[USP_PMPERMITPARCEL_INSERT]
(
	@PMPERMITID CHAR(36),
	@PARCELID CHAR(36),
	@MAIN BIT,
	@PARCELSPLITPROCESS BIT
)
AS
BEGIN
INSERT INTO [dbo].[PMPERMITPARCEL]
		(
			[PMPERMITPARCELID],
			[PMPERMITID],
			[PARCELID],
			[MAIN],
			[PARCELSPLITPROCESS]
		)
		VALUES
		(
			NEWID(),
			@PMPERMITID,
			@PARCELID,
			@MAIN,
			@PARCELSPLITPROCESS
		)
END