CREATE PROCEDURE [dbo].[USP_PLPLANALLOWEDACTIVITY_DELETE]
(
@PLPLANALLOWEDACTIVITYID CHAR(36)
)
AS
DELETE FROM [dbo].[PLPLANALLOWEDACTIVITY]
WHERE
	[PLPLANALLOWEDACTIVITYID] = @PLPLANALLOWEDACTIVITYID