CREATE PROCEDURE [dbo].[USP_PRPROJECTSTATUS_DELETE]
(
	@PRPROJECTSTATUSID CHAR(36),
	@ROWVERSION INT
)
AS
DELETE FROM [dbo].[PRPROJECTSTATUS]
WHERE
	[PRPROJECTSTATUSID] = @PRPROJECTSTATUSID AND 
	[ROWVERSION]= @ROWVERSION