CREATE PROCEDURE [dbo].[USP_PMPERMITTYPELICENSETYPE_INSERT]
(
	@PMPERMITTYPELICENSETYPEID CHAR(36),
	@PMPERMITTYPEID CHAR(36),
	@PMPERMITWORKCLASSID CHAR(36),
	@COSIMPLELICCERTTYPEID CHAR(36),
	@REQUIREALLCERTCLASS BIT
)
AS

INSERT INTO [dbo].[PMPERMITTYPELICENSETYPE](
	[PMPERMITTYPELICENSETYPEID],
	[PMPERMITTYPEID],
	[PMPERMITWORKCLASSID],
	[COSIMPLELICCERTTYPEID],
	[REQUIREALLCERTCLASS]
)

VALUES
(
	@PMPERMITTYPELICENSETYPEID,
	@PMPERMITTYPEID,
	@PMPERMITWORKCLASSID,
	@COSIMPLELICCERTTYPEID,
	@REQUIREALLCERTCLASS
)