CREATE PROCEDURE [dbo].[USP_PLANEVENTQUEUE_UPDATE]
(
@EVENTQUEUEID AS BIGINT,
@EVENTSTATUSID INT
)
AS
BEGIN  
	SET NOCOUNT ON;
	UPDATE [dbo].[PLANEVENTQUEUE]
	SET 
		PROCESSEDDATE = GETDATE(),
		EVENTSTATUSID = @EVENTSTATUSID
	WHERE [dbo].[PLANEVENTQUEUE].[PLANEVENTQUEUEID] = @EVENTQUEUEID
END