CREATE PROCEDURE [dbo].[USP_PMPERMITTYPEGROUP_DELETE]
(
	@PMPERMITTYPEGROUPID CHAR(36),
	@ROWVERSION INT
)
AS
DELETE FROM [dbo].[PMPERMITTYPEGROUP]
WHERE
	[PMPERMITTYPEGROUPID] = @PMPERMITTYPEGROUPID AND 
	[ROWVERSION]= @ROWVERSION