CREATE PROCEDURE [dbo].[USP_PLPLANTYPEWORKCLASS_SELECT_LOOKUP]
(
	@ACTIVEONLY BIT = 1
)
AS
BEGIN
SET NOCOUNT ON;

SELECT
	[dbo].[PLPLANTYPE].[PLPLANTYPEID],
	[dbo].[PLPLANTYPE].[PLANNAME]
FROM [dbo].[PLPLANTYPE]
WHERE [dbo].[PLPLANTYPE].[ACTIVE] = @ACTIVEONLY OR @ACTIVEONLY = 0
ORDER BY [dbo].[PLPLANTYPE].[PLANNAME]

EXEC [dbo].[USP_PLPLANWORKCLASS_SELECT_LOOKUP] @ACTIVEONLY

END