CREATE PROCEDURE [dbo].[USP_PLPLANWORKCLASS_SELECT_LOOKUP]
(
	@ACTIVEONLY BIT = 1
)
AS
SET NOCOUNT ON;

SELECT 
	[dbo].[PLPLANWORKCLASS].[PLPLANWORKCLASSID],
	[dbo].[PLPLANWORKCLASS].[NAME],
	[dbo].[PLPLANTYPE].[PLPLANTYPEID]
FROM [dbo].[PLPLANWORKCLASS]
JOIN [dbo].[PLPLANTYPEWORKCLASS] ON [dbo].[PLPLANWORKCLASS].[PLPLANWORKCLASSID] = [dbo].[PLPLANTYPEWORKCLASS].[PLPLANWORKCLASSID]
JOIN [dbo].[PLPLANTYPE] ON [dbo].[PLPLANTYPEWORKCLASS].[PLPLANTYPEID] = [dbo].[PLPLANTYPE].[PLPLANTYPEID]
WHERE [dbo].[PLPLANTYPE].[ACTIVE] = @ACTIVEONLY OR @ACTIVEONLY = 0
ORDER BY [dbo].[PLPLANWORKCLASS].[NAME]