CREATE PROCEDURE [dbo].[USP_PLPLANTYPE_DELETE]
(
	@PLPLANTYPEID CHAR(36),
	@ROWVERSION INT
)
AS
SET NOCOUNT ON;

EXEC [dbo].[USP_PLPLANALLOWEDACTIVITY_DELETE_BYPARENTID] @PLPLANTYPEID
EXEC [dbo].[USP_PLPLANTYPEWORKCLASS_DELETE_BYPARENTID] @PLPLANTYPEID

SET NOCOUNT OFF;
DELETE FROM [dbo].[PLPLANTYPE]
WHERE
	[PLPLANTYPEID] = @PLPLANTYPEID AND 
	[ROWVERSION]= @ROWVERSION