CREATE PROCEDURE [dbo].[USP_PLSUBMITTALSTATUS_UPDATE]
(
	@PLSUBMITTALSTATUSID CHAR(36),
	@NAME NVARCHAR(50),
	@DESCRIPTION NVARCHAR(MAX),
	@DESCRIPTIONSPANISH NVARCHAR(MAX),
	@SUCCESSFLAG BIT,
	@FAILUREFLAG BIT,
	@NOTREQUIREDFLAG BIT,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
UPDATE [dbo].[PLSUBMITTALSTATUS] SET
	[NAME] = @NAME,
	[DESCRIPTION] =@DESCRIPTION,
	[DESCRIPTION_SPANISH]= @DESCRIPTIONSPANISH,
	[SUCCESSFLAG] = @SUCCESSFLAG,
	[FAILUREFLAG] = @FAILUREFLAG,
	[NOTREQUIREDFLAG] = @NOTREQUIREDFLAG,
	[LASTCHANGEDBY] = @LASTCHANGEDBY,
	[LASTCHANGEDON] = @LASTCHANGEDON,
	[ROWVERSION] = @ROWVERSION + 1
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE
	[PLSUBMITTALSTATUSID] = @PLSUBMITTALSTATUSID AND 
	[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE