CREATE PROCEDURE [dbo].[USP_PMPERMITWORKCLASS_DELETE]
(
	@PMPERMITWORKCLASSID CHAR(36),
	@ROWVERSION INT
)
AS
DELETE FROM [dbo].[PMPERMITWORKCLASS]
WHERE
	[PMPERMITWORKCLASSID] = @PMPERMITWORKCLASSID AND 
	[ROWVERSION]= @ROWVERSION