CREATE PROCEDURE [dbo].[USP_PLPLANTYPEUNITTYPE_DELETE_BYPARENTID]  
(  
@PLPLANTYPEID CHAR(36),
@PLPLANWORKCLASSID CHAR(36) 
)  
AS  
DELETE FROM [dbo].[PLPLANTYPEUNITTYPE]
WHERE
	[PLPLANTYPEID] = @PLPLANTYPEID AND (@PLPLANWORKCLASSID IS NULL OR [PLPLANWORKCLASSID] = @PLPLANWORKCLASSID)