

CREATE View LOOKUPVIEWFAILSAFE
As 
SELECT 
	GLOBALENTITY.GLOBALENTITYID As UniqueID,
	CASE WHEN LEN(COALESCE(GLOBALENTITY.GLOBALENTITYNAME,''))>0
		THEN GLOBALENTITY.GLOBALENTITYNAME
		ELSE GLOBALENTITY.FIRSTNAME + ' ' + GLOBALENTITY.LASTNAME
	END	 AS StringValue,
	'GLOBALENTITY' As TableName
	From dbo.GLOBALENTITY
UNION ALL
	SELECT 
	PRPROJECT.PRPROJECTID AS UNIQUEID,
	PRPROJECT.NAME AS STRINGVALUE,
	'PRPROJECT' AS TABLENAME
	FROM dbo.PRPROJECT	
UNION ALL	
	SELECT 
	CONDITION.CONDITIONID AS UNIQUEID,
	CONDITION.NAME AS STRINGVALUE,
	'CONDITION' AS TABLENAME
	FROM CONDITION
UNION ALL
	SELECT
	OMOBJECT.OMOBJECTID AS UNIQUEID,
	OMOBJECT.OBJECTNUMBER AS STRINGVALUE,
	'OMOBJECT' AS TABLENAME
	FROM dbo.OMOBJECT	
UNION ALL
	SELECT
	PLPLAN.PLPLANID AS UNIQUEID,
	PLPLAN.PLANNUMBER AS STRINGVALUE,
	'PLPLAN' AS TABLENAME
	FROM dbo.PLPLAN	
/*CWH 11/12/2012 - Bug 2694*/
UNION ALL
	SELECT BLGLOBALENTITYEXTENSIONID AS UNIQUEID,
	CASE WHEN LEN(COALESCE(GLOBALENTITY.GLOBALENTITYNAME,''))>0
		THEN GLOBALENTITY.GLOBALENTITYNAME
		ELSE GLOBALENTITY.FIRSTNAME + ' ' + GLOBALENTITY.LASTNAME
	END	 AS StringValue,
	'BLGLOBALENTITYEXTENSION' AS TABLENAME
	FROM BLGLOBALENTITYEXTENSION
	INNER JOIN GLOBALENTITY ON BLGLOBALENTITYEXTENSION.GLOBALENTITYID = GLOBALENTITY.GLOBALENTITYID 
UNION ALL
	SELECT
	ILLICENSEGROUP.ILLICENSEGROUPID AS UNIQUEID,
	ILLICENSEGROUP.NAME AS STRINGVALUE,
	'ILLICENSEGROUP' AS TABLENAME
	FROM ILLICENSEGROUP	
/*Bug  3439 5/7/2013*/
UNION ALL
SELECT PARCEL.PARCELID AS UNIQUEID, PARCEL.PARCELNUMBER AS STRINGVALUE, 'PARCEL' AS TABLENAME FROM dbo.PARCEL
/*CWH 11/01/2013 - Bug 4829 / TFS Bug 1578:LOOKUPVIEWFAILSAFE error*/
UNION ALL
	SELECT 
	MAILINGADDRESS.MAILINGADDRESSID AS UNIQUEID, 
	MAILINGADDRESS.ADDRESSLINE1 AS STRINGVALUE, 
	'MAILINGADDRESS' AS TABLENAME 
	FROM MAILINGADDRESS
/*CWH 01/03/2014 - Bug 4544 / TFS Bug 2100:LookupViewFailSafe Needs Rental Property*/
UNION ALL
	SELECT 
	RPPROPERTYTYPE.RPPROPERTYTYPEID AS UNIQUEID, 
	RPPROPERTYTYPE.NAME AS STRINGVALUE, 
	'RPPROPERTYTYPEP' AS TABLENAME
	FROM RPPROPERTYTYPE
UNION ALL
SELECT 
	ERPROJECT.ERPROJECTID AS UNIQUEID,
	ERPROJECT.PROJECTNUM AS STRINGVALUE,
	'ERPROJECT' AS TABLENAME
	FROM dbo.ERPROJECT	
/* TFS 24208 & 16450 Move large unions to failsafe */
UNION ALL
SELECT
	GLOBALENTITYACCOUNT.GLOBALENTITYACCOUNTID AS UNIQUEID,
	GLOBALENTITYACCOUNT.NAME AS STRINGVALUE,
	'GLOBALENTITYACCOUNT' AS TABLENAME
	FROM dbo.GLOBALENTITYACCOUNT
UNION ALL
SELECT 
	CUSTOMFIELDPICKLISTITEM.GCUSTOMFIELDPICKLISTITEM AS UNIQUEID,
	CUSTOMFIELDPICKLISTITEM.SVALUE AS STRINGVALUE,
	'CUSTOMFIELDPICKLISTITEM' AS TABLENAME
	FROM dbo.CUSTOMFIELDPICKLISTITEM	
UNION ALL
SELECT 
	CAFEETEMPLATEFEE.CAFEETEMPLATEFEEID AS UNIQUEID,
	CAFEETEMPLATEFEE.[FEEDESCRIPTION] AS STRINGVALUE,
	'CAFEETEMPLATEFEE' AS TABLENAME
	FROM dbo.CAFEETEMPLATEFEE	
UNION ALL
SELECT 
	CAFEE.CAFEEID AS UNIQUEID,
	CAFEE.[NAME] AS STRINGVALUE,
	'CAFEE' AS TABLENAME
	FROM dbo.CAFEE	
UNION ALL
SELECT 
	PMPERMIT.PMPERMITID AS UNIQUEID,
	PMPERMIT.PERMITNUMBER AS STRINGVALUE,
	'PMPERMIT' AS TABLENAME
	FROM dbo.PMPERMIT	
UNION ALL
SELECT 
	PARCELADDRESS.ADDRESSID AS UNIQUEID, 
	PARCELADDRESS.ADDRESSLINE1 AS STRINGVALUE, 
	'PARCELADDRESS' AS TABLENAME 
	FROM dbo.PARCELADDRESS
UNION ALL
SELECT 
	FIREOCCUPANCY.ID AS UNIQUEID,
	FIREOCCUPANCY.FIREOCCUPANCYNUMBER AS STRINGVALUE,
	'FIREOCCUPANCY' AS TABLENAME
	FROM dbo.FIREOCCUPANCY