
CREATE VIEW [dbo].[LOOKUPVIEWFORINTEGERS]
AS 

SELECT 
	CAFEETYPE.CAFEETYPEID AS UNIQUEID,
	CAFEETYPE.[NAME] AS STRINGVALUE,
	'CAFEETYPE' AS TABLENAME
	FROM dbo.CAFEETYPE
UNION ALL
SELECT 
	CAMODULE.CAMODULEID AS UNIQUEID,
	CAMODULE.[NAME] AS STRINGVALUE,
	'CAMODULE' AS TABLENAME
	FROM dbo.CAMODULE	
UNION ALL
SELECT 
	CAENTITY.CAENTITYID AS UNIQUEID,
	CAENTITY.[NAME] AS STRINGVALUE,
	'CAENTITY' AS TABLENAME
	FROM dbo.CAENTITY
UNION ALL
SELECT 
	WORKFLOWSTATUS.WORKFLOWSTATUSID AS UNIQUEID,
	WORKFLOWSTATUS.NAME AS STRINGVALUE,
	'WORKFLOWSTATUS' AS TABLENAME
	FROM dbo.WORKFLOWSTATUS
UNION ALL
SELECT
	CAPAYMENTTYPE.CAPAYMENTTYPEID AS UNIQUEID,
	CAPAYMENTTYPE.NAME AS STRINGVALUE,
	'CAPAYMENTTYPE' AS TABLENAME
	FROM dbo.CAPAYMENTTYPE
UNION ALL
SELECT
	CASTATUS.CASTATUSID AS UNIQUEID,
	CASTATUS.NAME AS STRINGVALUE,
	'CASTATUS' AS TABLENAME
	FROM dbo.CASTATUS	
UNION ALL
SELECT
	CATRANSACTIONSTATUS.CATRANSACTIONSTATUSID AS UNIQUEID,
	CATRANSACTIONSTATUS.NAME AS STRINGVALUE,
	'CATRANSACTIONSTATUS' AS TABLENAME
	FROM dbo.CATRANSACTIONSTATUS	
UNION ALL
SELECT
	CAPAYMENTSTATUS.CAPAYMENTSTATUSID AS UNIQUEID,
	CAPAYMENTSTATUS.NAME AS STRINGVALUE,
	'CAPAYMENTSTATUS' AS TABLENAME
	FROM dbo.CAPAYMENTSTATUS	
UNION ALL
SELECT
	CAACCOUNTACTION.CAACCOUNTACTIONID AS UNIQUEID,
	CAACCOUNTACTION.NAME AS STRINGVALUE,
	'CAACCOUNTACTION' AS TABLENAME
	FROM dbo.CAACCOUNTACTION
UNION ALL
SELECT 
	CAFEEROUNDINGTYPE.CAFEEROUNDINGTYPEID AS UNIQUEID,
	CAFEEROUNDINGTYPE.NAME AS STRINGVALUE,
	'CAFEEROUNDINGTYPE' AS TABLENAME
	FROM dbo.CAFEEROUNDINGTYPE
UNION ALL
SELECT
	BLCONTACTTYPESYSTEM.BLCONTACTTYPESYSTEMID AS UNIQUEID,
	BLCONTACTTYPESYSTEM.NAME AS STRINGVALUE,
	'BLCONTACTTYPESYSTEM' AS TABLENAME
	FROM dbo.BLCONTACTTYPESYSTEM
UNION ALL
SELECT
	BLEXTSTATUSSYSTEM.BLEXTSTATUSSYSTEMID AS UNIQUEID,
	BLEXTSTATUSSYSTEM.NAME AS STRINGVALUE,
	'BLEXTSTATUSSYSTEM' AS TABLENAME
	FROM dbo.BLEXTSTATUSSYSTEM
UNION ALL
SELECT
	CAROUNDINGTYPE.CAROUNDINGTYPEID AS UNIQUEID,
	CAROUNDINGTYPE.NAME AS STRINGVALUE,
	'CAROUNDINGTYPE' AS TABLENAME
	FROM dbo.CAROUNDINGTYPE
UNION ALL
SELECT
	CACOMPUTATIONTYPE.CACOMPUTATIONTYPEID AS UNIQUEID,
	CACOMPUTATIONTYPE.NAME AS STRINGVALUE,
	'CACOMPUTATIONTYPE' AS TABLENAME
	FROM dbo.CACOMPUTATIONTYPE
UNION ALL
SELECT
	PMPERMITCAPAPPLICATIONTYPE.PMPERMITCAPAPPLICATIONTYPEID AS UNIQUEID,
	PMPERMITCAPAPPLICATIONTYPE.NAME AS STRINGVALUE,
	'PMPERMITCAPAPPLICATIONTYPE' AS TABLENAME
	FROM dbo.PMPERMITCAPAPPLICATIONTYPE
UNION ALL
SELECT
	BLLICENSECAPAPPLICATIONTYPE.BLLICENSECAPAPPLICATIONTYPEID AS UNIQUEID,
	BLLICENSECAPAPPLICATIONTYPE.NAME AS STRINGVALUE,
	'BLLICENSECAPAPPLICATIONTYPE' AS TABLENAME
	FROM dbo.BLLICENSECAPAPPLICATIONTYPE
UNION ALL
SELECT
	CATRANSACTIONTYPE.CATRANSACTIONTYPEID AS UNIQUEID,
	CATRANSACTIONTYPE.NAME AS STRINGVALUE,
	'CATRANSACTIONTYPE' AS TABLENAME
	FROM dbo.CATRANSACTIONTYPE
UNION ALL
SELECT
	EXAMFORMAT.EXAMFORMATID AS UNIQUEID,
	EXAMFORMAT.NAME AS STRINGVALUE,
	'EXAMFORMAT' AS TABLENAME
	FROM dbo.EXAMFORMAT
UNION ALL
SELECT
	EXAMLINK.EXAMLINKID AS UNIQUEID,
	EXAMLINK.NAME AS STRINGVALUE,
	'EXAMLINK' AS TABLENAME
	FROM dbo.EXAMLINK
UNION ALL
SELECT
	EXAMFORMATTYPE.EXAMFORMATTYPEID AS UNIQUEID,
	EXAMFORMATTYPE.NAME AS STRINGVALUE,
	'EXAMFORMATTYPE' AS TABLENAME
	FROM dbo.EXAMFORMATTYPE
UNION ALL
SELECT
	GLOBALPREFFERCOMM.GLOBALPREFFERCOMMID AS UNIQUEID,
	GLOBALPREFFERCOMM.PREFNAME AS STRINGVALUE,
	'GLOBALPREFFERCOMM' AS TABLENAME
	FROM dbo.GLOBALPREFFERCOMM
UNION ALL
SELECT
	CONTACTCONFIRMSTATUS.CONTACTCONFIRMSTATUSID AS UNIQUEID,
	CONTACTCONFIRMSTATUS.NAME AS STRINGVALUE,
	'CONTACTCONFIRMSTATUS' AS TABLENAME
	FROM dbo.CONTACTCONFIRMSTATUS
UNION ALL
SELECT
	CAFEETEMPLATEINPUTTYPE.CAFEETEMPLATEINPUTTYPEID AS UNIQUEID,
	CAFEETEMPLATEINPUTTYPE.NAME AS STRINGVALUE,
	'CAFEETEMPLATEINPUTTYPE' AS TABLENAME
	FROM dbo.CAFEETEMPLATEINPUTTYPE
UNION ALL
SELECT
	CAPRORATIONMODEL.CAPRORATIONMODELID AS UNIQUEID,
	CAPRORATIONMODEL.NAME AS STRINGVALUE,
	'CAPRORATIONMODEL' AS TABLENAME
	FROM dbo.CAPRORATIONMODEL
UNION ALL
SELECT
	IMNONCOMPLIANCERESPPARTY.IMNONCOMPLIANCERESPPARTYID AS UNIQUEID,
	IMNONCOMPLIANCERESPPARTY.NAME AS STRINGVALUE,
	'IMNONCOMPLIANCERESPPARTY' AS TABLENAME
	FROM dbo.IMNONCOMPLIANCERESPPARTY
UNION ALL
SELECT
	IMNONCOMPLIANCERISK.IMNONCOMPLIANCERISKID AS UNIQUEID,
	IMNONCOMPLIANCERISK.NAME AS STRINGVALUE,
	'IMNONCOMPLIANCERISK' AS TABLENAME
	FROM dbo.IMNONCOMPLIANCERISK
UNION ALL
SELECT
	IMINSPECTIONREQUESTEDSOURCE.IMINSPECTIONREQUESTEDSOURCEID AS UNIQUEID,
	IMINSPECTIONREQUESTEDSOURCE.NAME AS STRINGVALUE,
	'IMINSPECTIONREQUESTEDSOURCE' AS TABLENAME
	FROM IMINSPECTIONREQUESTEDSOURCE
UNION ALL
SELECT CACPICALCULATIONTYPE.CACPICALCULATIONTYPEID UNIQUEID  ,
       CACPICALCULATIONTYPE.NAME STRINGVALUE  ,
      'CACPICALCULATIONTYPE' TABLENAME  
  FROM CACPICALCULATIONTYPE 
UNION ALL
SELECT FILESTATUS.FILESTATUSID UNIQUEID,
       FILESTATUS.NAME STRINGVALUE,
      'FILESTATUS' TABLENAME  
  FROM FILESTATUS
    UNION ALL
SELECT HOLDSEVERITY.HOLDSEVERITYID UNIQUEID,
       HOLDSEVERITY.HOLDSEVERITYNAME STRINGVALUE,
      'HOLDSEVERITY' TABLENAME  
FROM HOLDSEVERITY