CREATE VIEW [dbo].[NONSEARCHABLE_CUSTOMFIELDSVIEW_V3]
AS
SELECT DISTINCT FKGCUSTOMFIELD GCUSTOMFIELD FROM CUSTOMFIELDOBJECT
WHERE FKGCUSTOMFIELDLAYOUT IN
(SELECT GCUSTOMFIELDLAYOUTS FROM CUSTOMFIELDLAYOUT cfo
WHERE cfo.GCUSTOMFIELDLAYOUTS IN
(
(
SELECT CUSTOMFIELDID 
FROM   CMCODEACTIVITYTYPE codAct
EXCEPT
SELECT CUSTOMFIELDID
FROM CMCASETYPE
UNION	
SELECT CUSTOMFIELDLAYOUTID
FROM   BLLICENSEACTIVITYTYPE blacttype
EXCEPT
	SELECT CUSTOMFIELDLAYOUTID
	 FROM BLLICENSETYPECLASS
	 UNION
	 SELECT ONLINECUSTOMFIELDLAYOUTID
	 FROM BLLICENSETYPECLASS	
UNION
SELECT 	CUSTOMFIELDID
FROM    CITIZENREQUESTACTIVITYTYPE
EXCEPT
	SELECT CUSTOMFIELDLAYOUTS
	 FROM CITIZENREQUESTTYPE
	 UNION
	 SELECT ONLINECUSTOMFIELDLAYOUTS
	 FROM CITIZENREQUESTTYPE			
UNION
SELECT 	CUSTOMFIELDLAYOUTID
FROM    ILLICENSEACTIVITYTYPE
EXCEPT
    ( SELECT CUSTOMFIELDLAYOUTID
	  FROM ILLICENSETYPE
      UNION ALL
	  SELECT CUSTOMFIELDLAYOUTID 
      FROM ILLICENSETYPELICENSECLASS
      UNION ALL
      SELECT ONLINECUSTOMFIELDLAYOUTID 
      FROM ILLICENSETYPELICENSECLASS )
UNION
SELECT 	CUSTOMFIELDID
FROM    PLPLANACTIVITYTYPE
EXCEPT
	(SELECT CUSTOMFIELDLAYOUTID
	 FROM PLPLANTYPEWORKCLASS
	 UNION
	 SELECT ONLINECUSTOMFIELDLAYOUTID
	 FROM PLPLANTYPEWORKCLASS	 			
	)		
UNION
SELECT 	CUSTOMFIELDID
FROM    PMPERMITACTIVITYTYPE
EXCEPT
	(SELECT CUSTOMFIELDLAYOUTID
	 FROM PMPERMITTYPEWORKCLASS
	 UNION
	 SELECT ONLINECUSTOMFIELDLAYOUTID
	 FROM PMPERMITTYPEWORKCLASS	 			
	)		
)	
)
)