CREATE VIEW [dbo].[PARCELSPLITVIEW]
AS
SELECT     'PlanManagement' AS MODULETYPE, dbo.PLPLANPARCEL.PLPLANPARCELID AS CASEPARCELID, dbo.PLPLANPARCEL.PLPLANID AS CASEID, dbo.PLPLAN.PLANNUMBER AS CASENUMBER, 
                  dbo.PLPLAN.PLPLANTYPEID AS CASETYPE, dbo.PLPLANPARCEL.PARCELID, dbo.PARCEL.PARCELNUMBER, dbo.PLPLANPARCEL.PARCELSPLITPROCESS
FROM        dbo.PLPLAN INNER JOIN
                  dbo.PLPLANPARCEL ON dbo.PLPLAN.PLPLANID = dbo.PLPLANPARCEL.PLPLANID INNER JOIN
                  dbo.PARCEL ON dbo.PLPLANPARCEL.PARCELID = dbo.PARCEL.PARCELID
WHERE     (dbo.PLPLANPARCEL.PARCELSPLITPROCESS = 1) AND (NOT EXISTS
                      (SELECT     1 AS Expr1
                       FROM        dbo.PARCELSPLIT AS ps
                       WHERE     (PARCELID = dbo.PLPLANPARCEL.PARCELID) AND (CASEID = dbo.PLPLANPARCEL.PLPLANID)))
UNION
SELECT     'PermitManagement' AS MODULETYPE, dbo.PMPERMITPARCEL.PMPERMITPARCELID AS CASEPARCELID, dbo.PMPERMITPARCEL.PMPERMITID AS CASEID, dbo.PMPERMIT.PERMITNUMBER AS CASENUMBER, 
                  dbo.PMPERMIT.PMPERMITTYPEID AS CASETYPE, dbo.PMPERMITPARCEL.PARCELID, dbo.PARCEL.PARCELNUMBER, dbo.PMPERMITPARCEL.PARCELSPLITPROCESS
FROM        dbo.PMPERMIT INNER JOIN
                  dbo.PMPERMITPARCEL ON dbo.PMPERMIT.PMPERMITID = dbo.PMPERMITPARCEL.PMPERMITID INNER JOIN
                  dbo.PARCEL ON dbo.PMPERMITPARCEL.PARCELID = dbo.PARCEL.PARCELID
WHERE     (dbo.PMPERMITPARCEL.PARCELSPLITPROCESS = 1) AND (NOT EXISTS
                      (SELECT     1 AS Expr1
                       FROM        dbo.PARCELSPLIT AS ps
                       WHERE     (PARCELID = dbo.PMPERMITPARCEL.PARCELID) AND (CASEID = dbo.PMPERMITPARCEL.PMPERMITID)))
