
CREATE VIEW [dbo].[PAYMENTVIEW]
AS
--PERMIT MODULE
SELECT     CACOMPUTEDFEE.FEENAME, CACOMPUTEDFEE.COMPUTEDAMOUNT AS COMPUTEDFEEAMOUNT, CAINVOICEFEE.PAIDAMOUNT AS INVOICEFEEPAIDAMOUNT, 
                      CAINVOICE.INVOICENUMBER, CATRANSACTIONINVOICE.PAIDAMOUNT AS AMOUNTAPPLIEDTOINVOICE, CATRANSACTION.CATRANSACTIONID, CATRANSACTION.RECEIPTNUMBER, 
                      CATRANSACTIONPAYMENT.PAYMENTDATE, CATRANSACTIONPAYMENT.SUPPLEMENTALDATA AS CHECKNUMBER, CATRANSACTIONPAYMENT.PAYMENTAMOUNT AS AMOUNTPAID, 
                      CAPAYMENTTYPE.NAME AS PAYMENTTYPE, CAPAYMENTSTATUS.NAME AS PAYMENTSTATUS, GLOBALENTITY.GLOBALENTITYNAME AS BILLINGCONTACTCOMPNAME, 
                      GLOBALENTITY.FIRSTNAME AS BILLINGCONTACTFNAME, GLOBALENTITY.LASTNAME AS BILLINGCONTACTLNAME, USERS.SUSERGUID AS CREATEDBYUSERGUID, 
                      USERS.ID AS CREATEDBYUSERID, USERS.FNAME AS CREATEDBYUSERFNAME, USERS.LNAME AS CREATEDBYUSERLNAME, CATRANSACTIONFEE.PAIDAMOUNT AS PAIDFEEAMOUNT, 
                      CAENTITY.NAME AS MODULENAME, CATRANSACTIONGLPOSTING.CATRANSACTIONGLPOSTINGID AS GLPOSTINGID, CATRANSACTIONGLPOSTING.CREDITACCOUNTNUMBER, 
                      CATRANSACTIONGLPOSTING.POSTINGAMOUNT AS GLPOSTINGAMOUNT, PMPERMIT.PERMITNUMBER AS CASENUMBER, PMPERMIT.PMPERMITID AS CASEID
FROM         CACOMPUTEDFEE INNER JOIN
                      CAINVOICEFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CAINVOICEFEE.CACOMPUTEDFEEID INNER JOIN
                      CAINVOICE ON CAINVOICEFEE.CAINVOICEID = CAINVOICE.CAINVOICEID INNER JOIN
                      CATRANSACTIONINVOICE ON CAINVOICE.CAINVOICEID = CATRANSACTIONINVOICE.CAINVOICEID INNER JOIN
                      CATRANSACTION ON CATRANSACTIONINVOICE.CATRANSACTIONID = CATRANSACTION.CATRANSACTIONID INNER JOIN
                      CATRANSACTIONPAYMENT ON CATRANSACTION.CATRANSACTIONID = CATRANSACTIONPAYMENT.CATRANSACTIONID INNER JOIN
                      CAPAYMENTTYPE ON CATRANSACTIONPAYMENT.CAPAYMENTTYPEID = CAPAYMENTTYPE.CAPAYMENTTYPEID INNER JOIN
                      CAPAYMENTSTATUS ON CATRANSACTIONPAYMENT.CAPAYMENTSTATUSID = CAPAYMENTSTATUS.CAPAYMENTSTATUSID INNER JOIN
                      GLOBALENTITY ON CATRANSACTION.GLOBALENTITYID = GLOBALENTITY.GLOBALENTITYID INNER JOIN
                      USERS ON CATRANSACTION.CREATEDBY = USERS.SUSERGUID INNER JOIN
                      CATRANSACTIONFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CATRANSACTIONFEE.CACOMPUTEDFEEID INNER JOIN
                      CAFEETEMPLATEFEE ON CACOMPUTEDFEE.CAFEETEMPLATEFEEID = CAFEETEMPLATEFEE.CAFEETEMPLATEFEEID INNER JOIN
                      CAFEETEMPLATE ON CAFEETEMPLATEFEE.CAFEETEMPLATEID = CAFEETEMPLATE.CAFEETEMPLATEID INNER JOIN
                      CAENTITY ON CAFEETEMPLATE.CAENTITYID = CAENTITY.CAENTITYID INNER JOIN
                      CATRANSACTIONFEEPOSTING ON CATRANSACTIONFEE.CATRANSACTIONFEEID = CATRANSACTIONFEEPOSTING.CATRANSACTIONFEEID INNER JOIN
                      CATRANSACTIONGLPOSTING ON CATRANSACTIONFEEPOSTING.CATRANSACTIONGLPOSTINGID = CATRANSACTIONGLPOSTING.CATRANSACTIONGLPOSTINGID INNER JOIN
                      PMPERMITFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = PMPERMITFEE.CACOMPUTEDFEEID INNER JOIN
                      PMPERMIT ON PMPERMITFEE.PMPERMITID = PMPERMIT.PMPERMITID
                      
UNION ALL
--PLAN MODULE
SELECT     CACOMPUTEDFEE.FEENAME, CACOMPUTEDFEE.COMPUTEDAMOUNT AS COMPUTEDFEEAMOUNT, CAINVOICEFEE.PAIDAMOUNT AS INVOICEFEEPAIDAMOUNT, 
                      CAINVOICE.INVOICENUMBER, CATRANSACTIONINVOICE.PAIDAMOUNT AS AMOUNTAPPLIEDTOINVOICE, CATRANSACTION.CATRANSACTIONID, CATRANSACTION.RECEIPTNUMBER, 
                      CATRANSACTIONPAYMENT.PAYMENTDATE, CATRANSACTIONPAYMENT.SUPPLEMENTALDATA AS CHECKNUMBER, CATRANSACTIONPAYMENT.PAYMENTAMOUNT AS AMOUNTPAID, 
                      CAPAYMENTTYPE.NAME AS PAYMENTTYPE, CAPAYMENTSTATUS.NAME AS PAYMENTSTATUS, GLOBALENTITY.GLOBALENTITYNAME AS BILLINGCONTACTCOMPNAME, 
                      GLOBALENTITY.FIRSTNAME AS BILLINGCONTACTFNAME, GLOBALENTITY.LASTNAME AS BILLINGCONTACTLNAME, USERS.SUSERGUID AS CREATEDBYUSERGUID, 
                      USERS.ID AS CREATEDBYUSERID, USERS.FNAME AS CREATEDBYUSERFNAME, USERS.LNAME AS CREATEDBYUSERLNAME, CATRANSACTIONFEE.PAIDAMOUNT AS PAIDFEEAMOUNT, 
                      CAENTITY.NAME AS MODULENAME, CATRANSACTIONGLPOSTING.CATRANSACTIONGLPOSTINGID AS GLPOSTINGID, 
                      CATRANSACTIONGLPOSTING.CREDITACCOUNTNUMBER AS GLACCOUNTNUMBER, CATRANSACTIONGLPOSTING.POSTINGAMOUNT AS GLPOSTINGAMOUNT, PLPLAN.PLANNUMBER AS CASENUMBER, 
                      PLPLAN.PLPLANID AS CASEID
FROM         CACOMPUTEDFEE INNER JOIN
                      CAINVOICEFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CAINVOICEFEE.CACOMPUTEDFEEID INNER JOIN
                      CAINVOICE ON CAINVOICEFEE.CAINVOICEID = CAINVOICE.CAINVOICEID INNER JOIN
                      CATRANSACTIONINVOICE ON CAINVOICE.CAINVOICEID = CATRANSACTIONINVOICE.CAINVOICEID INNER JOIN
                      CATRANSACTION ON CATRANSACTIONINVOICE.CATRANSACTIONID = CATRANSACTION.CATRANSACTIONID INNER JOIN
                      CATRANSACTIONPAYMENT ON CATRANSACTION.CATRANSACTIONID = CATRANSACTIONPAYMENT.CATRANSACTIONID INNER JOIN
                      CAPAYMENTTYPE ON CATRANSACTIONPAYMENT.CAPAYMENTTYPEID = CAPAYMENTTYPE.CAPAYMENTTYPEID INNER JOIN
                      CAPAYMENTSTATUS ON CATRANSACTIONPAYMENT.CAPAYMENTSTATUSID = CAPAYMENTSTATUS.CAPAYMENTSTATUSID INNER JOIN
                      GLOBALENTITY ON CATRANSACTION.GLOBALENTITYID = GLOBALENTITY.GLOBALENTITYID INNER JOIN
                      USERS ON CATRANSACTION.CREATEDBY = USERS.SUSERGUID INNER JOIN
                      CATRANSACTIONFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CATRANSACTIONFEE.CACOMPUTEDFEEID INNER JOIN
                      CAFEETEMPLATEFEE ON CACOMPUTEDFEE.CAFEETEMPLATEFEEID = CAFEETEMPLATEFEE.CAFEETEMPLATEFEEID INNER JOIN
                      CAFEETEMPLATE ON CAFEETEMPLATEFEE.CAFEETEMPLATEID = CAFEETEMPLATE.CAFEETEMPLATEID INNER JOIN
                      CAENTITY ON CAFEETEMPLATE.CAENTITYID = CAENTITY.CAENTITYID INNER JOIN
                      CATRANSACTIONFEEPOSTING ON CATRANSACTIONFEE.CATRANSACTIONFEEID = CATRANSACTIONFEEPOSTING.CATRANSACTIONFEEID INNER JOIN
                      CATRANSACTIONGLPOSTING ON CATRANSACTIONFEEPOSTING.CATRANSACTIONGLPOSTINGID = CATRANSACTIONGLPOSTING.CATRANSACTIONGLPOSTINGID INNER JOIN
                      PLPLANFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = PLPLANFEE.CACOMPUTEDFEEID INNER JOIN
                      PLPLAN ON PLPLANFEE.PLPLANID = PLPLAN.PLPLANID
                                                                  
UNION ALL
--APPLICATION MODULE
SELECT     CACOMPUTEDFEE.FEENAME, CACOMPUTEDFEE.COMPUTEDAMOUNT AS COMPUTEDFEEAMOUNT, CAINVOICEFEE.PAIDAMOUNT AS INVOICEFEEPAIDAMOUNT, 
                      CAINVOICE.INVOICENUMBER, CATRANSACTIONINVOICE.PAIDAMOUNT AS AMOUNTAPPLIEDTOINVOICE, CATRANSACTION.CATRANSACTIONID, CATRANSACTION.RECEIPTNUMBER, 
                      CATRANSACTIONPAYMENT.PAYMENTDATE, CATRANSACTIONPAYMENT.SUPPLEMENTALDATA AS CHECKNUMBER, CATRANSACTIONPAYMENT.PAYMENTAMOUNT AS AMOUNTPAID, 
                      CAPAYMENTTYPE.NAME AS PAYMENTTYPE, CAPAYMENTSTATUS.NAME AS PAYMENTSTATUS, GLOBALENTITY.GLOBALENTITYNAME AS BILLINGCONTACTCOMPNAME, 
                      GLOBALENTITY.FIRSTNAME AS BILLINGCONTACTFNAME, GLOBALENTITY.LASTNAME AS BILLINGCONTACTLNAME, USERS.SUSERGUID AS CREATEDBYUSERGUID, 
                      USERS.ID AS CREATEDBYUSERID, USERS.FNAME AS CREATEDBYUSERFNAME, USERS.LNAME AS CREATEDBYUSERLNAME, CATRANSACTIONFEE.PAIDAMOUNT AS PAIDFEEAMOUNT, 
                      CAENTITY.NAME AS MODULENAME, CATRANSACTIONGLPOSTING.CATRANSACTIONGLPOSTINGID AS GLPOSTINGID, 
                      CATRANSACTIONGLPOSTING.CREDITACCOUNTNUMBER AS GLACCOUNTNUMBER, CATRANSACTIONGLPOSTING.POSTINGAMOUNT AS GLPOSTINGAMOUNT, 
                      PLAPPLICATION.APPNUMBER AS CASENUMBER, 
                      PLAPPLICATION.PLAPPLICATIONID AS CASEID
FROM         CACOMPUTEDFEE INNER JOIN
                      CAINVOICEFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CAINVOICEFEE.CACOMPUTEDFEEID INNER JOIN
                      CAINVOICE ON CAINVOICEFEE.CAINVOICEID = CAINVOICE.CAINVOICEID INNER JOIN
                      CATRANSACTIONINVOICE ON CAINVOICE.CAINVOICEID = CATRANSACTIONINVOICE.CAINVOICEID INNER JOIN
                      CATRANSACTION ON CATRANSACTIONINVOICE.CATRANSACTIONID = CATRANSACTION.CATRANSACTIONID INNER JOIN
                      CATRANSACTIONPAYMENT ON CATRANSACTION.CATRANSACTIONID = CATRANSACTIONPAYMENT.CATRANSACTIONID INNER JOIN
                      CAPAYMENTTYPE ON CATRANSACTIONPAYMENT.CAPAYMENTTYPEID = CAPAYMENTTYPE.CAPAYMENTTYPEID INNER JOIN
                      CAPAYMENTSTATUS ON CATRANSACTIONPAYMENT.CAPAYMENTSTATUSID = CAPAYMENTSTATUS.CAPAYMENTSTATUSID INNER JOIN
                      GLOBALENTITY ON CATRANSACTION.GLOBALENTITYID = GLOBALENTITY.GLOBALENTITYID INNER JOIN
                      USERS ON CATRANSACTION.CREATEDBY = USERS.SUSERGUID INNER JOIN
                      CATRANSACTIONFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CATRANSACTIONFEE.CACOMPUTEDFEEID INNER JOIN
                      CAFEETEMPLATEFEE ON CACOMPUTEDFEE.CAFEETEMPLATEFEEID = CAFEETEMPLATEFEE.CAFEETEMPLATEFEEID INNER JOIN
                      CAFEETEMPLATE ON CAFEETEMPLATEFEE.CAFEETEMPLATEID = CAFEETEMPLATE.CAFEETEMPLATEID INNER JOIN
                      CAENTITY ON CAFEETEMPLATE.CAENTITYID = CAENTITY.CAENTITYID INNER JOIN
                      CATRANSACTIONFEEPOSTING ON CATRANSACTIONFEE.CATRANSACTIONFEEID = CATRANSACTIONFEEPOSTING.CATRANSACTIONFEEID INNER JOIN
                      CATRANSACTIONGLPOSTING ON CATRANSACTIONFEEPOSTING.CATRANSACTIONGLPOSTINGID = CATRANSACTIONGLPOSTING.CATRANSACTIONGLPOSTINGID INNER JOIN
                      PLAPPLICATIONFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = PLAPPLICATIONFEE.CACOMPUTEDFEEID INNER JOIN
                      PLAPPLICATION ON PLAPPLICATIONFEE.PLAPPLICATIONID = PLAPPLICATION.PLAPPLICATIONID
                      
UNION ALL
--CODE MODULE
SELECT     CACOMPUTEDFEE.FEENAME, CACOMPUTEDFEE.COMPUTEDAMOUNT AS COMPUTEDFEEAMOUNT, CAINVOICEFEE.PAIDAMOUNT AS INVOICEFEEPAIDAMOUNT, 
                      CAINVOICE.INVOICENUMBER, CATRANSACTIONINVOICE.PAIDAMOUNT AS AMOUNTAPPLIEDTOINVOICE, CATRANSACTION.CATRANSACTIONID, CATRANSACTION.RECEIPTNUMBER, 
                      CATRANSACTIONPAYMENT.PAYMENTDATE, CATRANSACTIONPAYMENT.SUPPLEMENTALDATA AS CHECKNUMBER, CATRANSACTIONPAYMENT.PAYMENTAMOUNT AS AMOUNTPAID, 
                      CAPAYMENTTYPE.NAME AS PAYMENTTYPE, CAPAYMENTSTATUS.NAME AS PAYMENTSTATUS, GLOBALENTITY.GLOBALENTITYNAME AS BILLINGCONTACTCOMPNAME, 
                      GLOBALENTITY.FIRSTNAME AS BILLINGCONTACTFNAME, GLOBALENTITY.LASTNAME AS BILLINGCONTACTLNAME, USERS.SUSERGUID AS CREATEDBYUSERGUID, 
                      USERS.ID AS CREATEDBYUSERID, USERS.FNAME AS CREATEDBYUSERFNAME, USERS.LNAME AS CREATEDBYUSERLNAME, CATRANSACTIONFEE.PAIDAMOUNT AS PAIDFEEAMOUNT, 
                      CAENTITY.NAME AS MODULENAME, CATRANSACTIONGLPOSTING.CATRANSACTIONGLPOSTINGID AS GLPOSTINGID, 
                      CATRANSACTIONGLPOSTING.CREDITACCOUNTNUMBER AS GLACCOUNTNUMBER, CATRANSACTIONGLPOSTING.POSTINGAMOUNT AS GLPOSTINGAMOUNT, CMCODECASE.CASENUMBER,
                      CMCODECASE.CMCODECASEID AS CASEID
FROM         CACOMPUTEDFEE INNER JOIN
                      CAINVOICEFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CAINVOICEFEE.CACOMPUTEDFEEID INNER JOIN
                      CAINVOICE ON CAINVOICEFEE.CAINVOICEID = CAINVOICE.CAINVOICEID INNER JOIN
                      CATRANSACTIONINVOICE ON CAINVOICE.CAINVOICEID = CATRANSACTIONINVOICE.CAINVOICEID INNER JOIN
                      CATRANSACTION ON CATRANSACTIONINVOICE.CATRANSACTIONID = CATRANSACTION.CATRANSACTIONID INNER JOIN
                      CATRANSACTIONPAYMENT ON CATRANSACTION.CATRANSACTIONID = CATRANSACTIONPAYMENT.CATRANSACTIONID INNER JOIN
                      CAPAYMENTTYPE ON CATRANSACTIONPAYMENT.CAPAYMENTTYPEID = CAPAYMENTTYPE.CAPAYMENTTYPEID INNER JOIN
                      CAPAYMENTSTATUS ON CATRANSACTIONPAYMENT.CAPAYMENTSTATUSID = CAPAYMENTSTATUS.CAPAYMENTSTATUSID INNER JOIN
                      GLOBALENTITY ON CATRANSACTION.GLOBALENTITYID = GLOBALENTITY.GLOBALENTITYID INNER JOIN
                      USERS ON CATRANSACTION.CREATEDBY = USERS.SUSERGUID INNER JOIN
                      CATRANSACTIONFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CATRANSACTIONFEE.CACOMPUTEDFEEID INNER JOIN
                      CAFEETEMPLATEFEE ON CACOMPUTEDFEE.CAFEETEMPLATEFEEID = CAFEETEMPLATEFEE.CAFEETEMPLATEFEEID INNER JOIN
                      CAFEETEMPLATE ON CAFEETEMPLATEFEE.CAFEETEMPLATEID = CAFEETEMPLATE.CAFEETEMPLATEID INNER JOIN
                      CAENTITY ON CAFEETEMPLATE.CAENTITYID = CAENTITY.CAENTITYID INNER JOIN
                      CATRANSACTIONFEEPOSTING ON CATRANSACTIONFEE.CATRANSACTIONFEEID = CATRANSACTIONFEEPOSTING.CATRANSACTIONFEEID INNER JOIN
                      CATRANSACTIONGLPOSTING ON CATRANSACTIONFEEPOSTING.CATRANSACTIONGLPOSTINGID = CATRANSACTIONGLPOSTING.CATRANSACTIONGLPOSTINGID INNER JOIN
                      CMCODECASEFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CMCODECASEFEE.CACOMPUTEDFEEID INNER JOIN
                      CMCODECASE ON CMCODECASEFEE.CMCODECASEID = CMCODECASE.CMCODECASEID

UNION ALL
--PROJECT MODULE
SELECT     CACOMPUTEDFEE.FEENAME, CACOMPUTEDFEE.COMPUTEDAMOUNT AS COMPUTEDFEEAMOUNT, CAINVOICEFEE.PAIDAMOUNT AS INVOICEFEEPAIDAMOUNT, 
                      CAINVOICE.INVOICENUMBER, CATRANSACTIONINVOICE.PAIDAMOUNT AS AMOUNTAPPLIEDTOINVOICE, CATRANSACTION.CATRANSACTIONID, CATRANSACTION.RECEIPTNUMBER, 
                      CATRANSACTIONPAYMENT.PAYMENTDATE, CATRANSACTIONPAYMENT.SUPPLEMENTALDATA AS CHECKNUMBER, CATRANSACTIONPAYMENT.PAYMENTAMOUNT AS AMOUNTPAID, 
                      CAPAYMENTTYPE.NAME AS PAYMENTTYPE, CAPAYMENTSTATUS.NAME AS PAYMENTSTATUS, GLOBALENTITY.GLOBALENTITYNAME AS BILLINGCONTACTCOMPNAME, 
                      GLOBALENTITY.FIRSTNAME AS BILLINGCONTACTFNAME, GLOBALENTITY.LASTNAME AS BILLINGCONTACTLNAME, USERS.SUSERGUID AS CREATEDBYUSERGUID, 
                      USERS.ID AS CREATEDBYUSERID, USERS.FNAME AS CREATEDBYUSERFNAME, USERS.LNAME AS CREATEDBYUSERLNAME, CATRANSACTIONFEE.PAIDAMOUNT AS PAIDFEEAMOUNT, 
                      CAENTITY.NAME AS MODULENAME, CATRANSACTIONGLPOSTING.CATRANSACTIONGLPOSTINGID AS GLPOSTINGID, 
                      CATRANSACTIONGLPOSTING.CREDITACCOUNTNUMBER AS GLACCOUNTNUMBER, CATRANSACTIONGLPOSTING.POSTINGAMOUNT AS GLPOSTINGAMOUNT, 
                      PRPROJECT.PROJECTNUMBER AS CASENUMBER,
                      PRPROJECT.PRPROJECTID AS CASEID
FROM         CACOMPUTEDFEE INNER JOIN
                      CAINVOICEFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CAINVOICEFEE.CACOMPUTEDFEEID INNER JOIN
                      CAINVOICE ON CAINVOICEFEE.CAINVOICEID = CAINVOICE.CAINVOICEID INNER JOIN
                      CATRANSACTIONINVOICE ON CAINVOICE.CAINVOICEID = CATRANSACTIONINVOICE.CAINVOICEID INNER JOIN
                      CATRANSACTION ON CATRANSACTIONINVOICE.CATRANSACTIONID = CATRANSACTION.CATRANSACTIONID INNER JOIN
                      CATRANSACTIONPAYMENT ON CATRANSACTION.CATRANSACTIONID = CATRANSACTIONPAYMENT.CATRANSACTIONID INNER JOIN
                      CAPAYMENTTYPE ON CATRANSACTIONPAYMENT.CAPAYMENTTYPEID = CAPAYMENTTYPE.CAPAYMENTTYPEID INNER JOIN
                      CAPAYMENTSTATUS ON CATRANSACTIONPAYMENT.CAPAYMENTSTATUSID = CAPAYMENTSTATUS.CAPAYMENTSTATUSID INNER JOIN
                      GLOBALENTITY ON CATRANSACTION.GLOBALENTITYID = GLOBALENTITY.GLOBALENTITYID INNER JOIN
                      USERS ON CATRANSACTION.CREATEDBY = USERS.SUSERGUID INNER JOIN
                      CATRANSACTIONFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CATRANSACTIONFEE.CACOMPUTEDFEEID INNER JOIN
                      CAFEETEMPLATEFEE ON CACOMPUTEDFEE.CAFEETEMPLATEFEEID = CAFEETEMPLATEFEE.CAFEETEMPLATEFEEID INNER JOIN
                      CAFEETEMPLATE ON CAFEETEMPLATEFEE.CAFEETEMPLATEID = CAFEETEMPLATE.CAFEETEMPLATEID INNER JOIN
                      CAENTITY ON CAFEETEMPLATE.CAENTITYID = CAENTITY.CAENTITYID INNER JOIN
                      CATRANSACTIONFEEPOSTING ON CATRANSACTIONFEE.CATRANSACTIONFEEID = CATRANSACTIONFEEPOSTING.CATRANSACTIONFEEID INNER JOIN
                      CATRANSACTIONGLPOSTING ON CATRANSACTIONFEEPOSTING.CATRANSACTIONGLPOSTINGID = CATRANSACTIONGLPOSTING.CATRANSACTIONGLPOSTINGID INNER JOIN
                      PRPROJECTFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = PRPROJECTFEE.CACOMPUTEDFEEID INNER JOIN
                      PRPROJECT ON PRPROJECTFEE.PRPROJECTID = PRPROJECT.PRPROJECTID                 

UNION ALL

--LICENSING MODULE
SELECT     CACOMPUTEDFEE.FEENAME, CACOMPUTEDFEE.COMPUTEDAMOUNT AS COMPUTEDFEEAMOUNT, CAINVOICEFEE.PAIDAMOUNT AS INVOICEFEEPAIDAMOUNT, 
                      CAINVOICE.INVOICENUMBER, CATRANSACTIONINVOICE.PAIDAMOUNT AS AMOUNTAPPLIEDTOINVOICE, CATRANSACTION.CATRANSACTIONID, CATRANSACTION.RECEIPTNUMBER, 
                      CATRANSACTIONPAYMENT.PAYMENTDATE, CATRANSACTIONPAYMENT.SUPPLEMENTALDATA AS CHECKNUMBER, CATRANSACTIONPAYMENT.PAYMENTAMOUNT AS AMOUNTPAID, 
                      CAPAYMENTTYPE.NAME AS PAYMENTTYPE, CAPAYMENTSTATUS.NAME AS PAYMENTSTATUS, GLOBALENTITY.GLOBALENTITYNAME AS BILLINGCONTACTCOMPNAME, 
                      GLOBALENTITY.FIRSTNAME AS BILLINGCONTACTFNAME, GLOBALENTITY.LASTNAME AS BILLINGCONTACTLNAME, USERS.SUSERGUID AS CREATEDBYUSERGUID, 
                      USERS.ID AS CREATEDBYUSERID, USERS.FNAME AS CREATEDBYUSERFNAME, USERS.LNAME AS CREATEDBYUSERLNAME, CATRANSACTIONFEE.PAIDAMOUNT AS PAIDFEEAMOUNT, 
                      CAENTITY.NAME AS MODULENAME, CATRANSACTIONGLPOSTING.CATRANSACTIONGLPOSTINGID AS GLPOSTINGID, 
                      CATRANSACTIONGLPOSTING.CREDITACCOUNTNUMBER AS GLACCOUNTNUMBER, CATRANSACTIONGLPOSTING.POSTINGAMOUNT AS GLPOSTINGAMOUNT, BLLICENSE.LICENSENUMBER AS CASENUMBER, 
                      BLLICENSE.BLLICENSEID AS CASEID
FROM         CACOMPUTEDFEE INNER JOIN
                      CAINVOICEFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CAINVOICEFEE.CACOMPUTEDFEEID INNER JOIN
                      CAINVOICE ON CAINVOICEFEE.CAINVOICEID = CAINVOICE.CAINVOICEID INNER JOIN
                      CATRANSACTIONINVOICE ON CAINVOICE.CAINVOICEID = CATRANSACTIONINVOICE.CAINVOICEID INNER JOIN
                      CATRANSACTION ON CATRANSACTIONINVOICE.CATRANSACTIONID = CATRANSACTION.CATRANSACTIONID INNER JOIN
                      CATRANSACTIONPAYMENT ON CATRANSACTION.CATRANSACTIONID = CATRANSACTIONPAYMENT.CATRANSACTIONID INNER JOIN
                      CAPAYMENTTYPE ON CATRANSACTIONPAYMENT.CAPAYMENTTYPEID = CAPAYMENTTYPE.CAPAYMENTTYPEID INNER JOIN
                      CAPAYMENTSTATUS ON CATRANSACTIONPAYMENT.CAPAYMENTSTATUSID = CAPAYMENTSTATUS.CAPAYMENTSTATUSID INNER JOIN
                      GLOBALENTITY ON CATRANSACTION.GLOBALENTITYID = GLOBALENTITY.GLOBALENTITYID INNER JOIN
                      USERS ON CATRANSACTION.CREATEDBY = USERS.SUSERGUID INNER JOIN
                      CATRANSACTIONFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CATRANSACTIONFEE.CACOMPUTEDFEEID INNER JOIN
                      CAFEETEMPLATEFEE ON CACOMPUTEDFEE.CAFEETEMPLATEFEEID = CAFEETEMPLATEFEE.CAFEETEMPLATEFEEID INNER JOIN
                      CAFEETEMPLATE ON CAFEETEMPLATEFEE.CAFEETEMPLATEID = CAFEETEMPLATE.CAFEETEMPLATEID INNER JOIN
                      CAENTITY ON CAFEETEMPLATE.CAENTITYID = CAENTITY.CAENTITYID INNER JOIN
                      CATRANSACTIONFEEPOSTING ON CATRANSACTIONFEE.CATRANSACTIONFEEID = CATRANSACTIONFEEPOSTING.CATRANSACTIONFEEID INNER JOIN
                      CATRANSACTIONGLPOSTING ON CATRANSACTIONFEEPOSTING.CATRANSACTIONGLPOSTINGID = CATRANSACTIONGLPOSTING.CATRANSACTIONGLPOSTINGID INNER JOIN
                      BLLICENSEFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = BLLICENSEFEE.CACOMPUTEDFEEID INNER JOIN
                      BLLICENSE ON BLLICENSEFEE.BLLICENSEID = BLLICENSE.BLLICENSEID
UNION ALL

--BUSINESS MODULE
SELECT     CACOMPUTEDFEE.FEENAME, CACOMPUTEDFEE.COMPUTEDAMOUNT AS COMPUTEDFEEAMOUNT, CAINVOICEFEE.PAIDAMOUNT AS INVOICEFEEPAIDAMOUNT, 
                      CAINVOICE.INVOICENUMBER, CATRANSACTIONINVOICE.PAIDAMOUNT AS AMOUNTAPPLIEDTOINVOICE, CATRANSACTION.CATRANSACTIONID, CATRANSACTION.RECEIPTNUMBER, 
                      CATRANSACTIONPAYMENT.PAYMENTDATE, CATRANSACTIONPAYMENT.SUPPLEMENTALDATA AS CHECKNUMBER, CATRANSACTIONPAYMENT.PAYMENTAMOUNT AS AMOUNTPAID, 
                      CAPAYMENTTYPE.NAME AS PAYMENTTYPE, CAPAYMENTSTATUS.NAME AS PAYMENTSTATUS, GLOBALENTITY.GLOBALENTITYNAME AS BILLINGCONTACTCOMPNAME, 
                      GLOBALENTITY.FIRSTNAME AS BILLINGCONTACTFNAME, GLOBALENTITY.LASTNAME AS BILLINGCONTACTLNAME, USERS.SUSERGUID AS CREATEDBYUSERGUID, 
                      USERS.ID AS CREATEDBYUSERID, USERS.FNAME AS CREATEDBYUSERFNAME, USERS.LNAME AS CREATEDBYUSERLNAME, CATRANSACTIONFEE.PAIDAMOUNT AS PAIDFEEAMOUNT, 
                      CAENTITY.NAME AS MODULENAME, CATRANSACTIONGLPOSTING.CATRANSACTIONGLPOSTINGID AS GLPOSTINGID, 
                      CATRANSACTIONGLPOSTING.CREDITACCOUNTNUMBER AS GLACCOUNTNUMBER, CATRANSACTIONGLPOSTING.POSTINGAMOUNT AS GLPOSTINGAMOUNT, BLGLOBALENTITYEXTENSION.REGISTRATIONID AS CASENUMBER, 
                      BLGLOBALENTITYEXTENSION.BLGLOBALENTITYEXTENSIONID AS CASEID
FROM         CACOMPUTEDFEE INNER JOIN
                      CAINVOICEFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CAINVOICEFEE.CACOMPUTEDFEEID INNER JOIN
                      CAINVOICE ON CAINVOICEFEE.CAINVOICEID = CAINVOICE.CAINVOICEID INNER JOIN
                      CATRANSACTIONINVOICE ON CAINVOICE.CAINVOICEID = CATRANSACTIONINVOICE.CAINVOICEID INNER JOIN
                      CATRANSACTION ON CATRANSACTIONINVOICE.CATRANSACTIONID = CATRANSACTION.CATRANSACTIONID INNER JOIN
                      CATRANSACTIONPAYMENT ON CATRANSACTION.CATRANSACTIONID = CATRANSACTIONPAYMENT.CATRANSACTIONID INNER JOIN
                      CAPAYMENTTYPE ON CATRANSACTIONPAYMENT.CAPAYMENTTYPEID = CAPAYMENTTYPE.CAPAYMENTTYPEID INNER JOIN
                      CAPAYMENTSTATUS ON CATRANSACTIONPAYMENT.CAPAYMENTSTATUSID = CAPAYMENTSTATUS.CAPAYMENTSTATUSID INNER JOIN
                      GLOBALENTITY ON CATRANSACTION.GLOBALENTITYID = GLOBALENTITY.GLOBALENTITYID INNER JOIN
                      USERS ON CATRANSACTION.CREATEDBY = USERS.SUSERGUID INNER JOIN
                      CATRANSACTIONFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CATRANSACTIONFEE.CACOMPUTEDFEEID INNER JOIN
                      CAFEETEMPLATEFEE ON CACOMPUTEDFEE.CAFEETEMPLATEFEEID = CAFEETEMPLATEFEE.CAFEETEMPLATEFEEID INNER JOIN
                      CAFEETEMPLATE ON CAFEETEMPLATEFEE.CAFEETEMPLATEID = CAFEETEMPLATE.CAFEETEMPLATEID INNER JOIN
                      CAENTITY ON CAFEETEMPLATE.CAENTITYID = CAENTITY.CAENTITYID INNER JOIN
                      CATRANSACTIONFEEPOSTING ON CATRANSACTIONFEE.CATRANSACTIONFEEID = CATRANSACTIONFEEPOSTING.CATRANSACTIONFEEID INNER JOIN
                      CATRANSACTIONGLPOSTING ON CATRANSACTIONFEEPOSTING.CATRANSACTIONGLPOSTINGID = CATRANSACTIONGLPOSTING.CATRANSACTIONGLPOSTINGID INNER JOIN
                      BLGLOBALENTITYEXTENSIONFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = BLGLOBALENTITYEXTENSIONFEE.CACOMPUTEDFEEID INNER JOIN
                      BLGLOBALENTITYEXTENSION ON BLGLOBALENTITYEXTENSIONFEE.BLGLOBALENTITYEXTENSIONFEEID = BLGLOBALENTITYEXTENSION.BLGLOBALENTITYEXTENSIONID

UNION ALL
/*PROF LICENSING MODULE*/ SELECT CACOMPUTEDFEE.FEENAME, CACOMPUTEDFEE.COMPUTEDAMOUNT AS COMPUTEDFEEAMOUNT, 
                      CAINVOICEFEE.PAIDAMOUNT AS INVOICEFEEPAIDAMOUNT, CAINVOICE.INVOICENUMBER, CATRANSACTIONINVOICE.PAIDAMOUNT AS AMOUNTAPPLIEDTOINVOICE, 
                      CATRANSACTION.CATRANSACTIONID, CATRANSACTION.RECEIPTNUMBER, CATRANSACTIONPAYMENT.PAYMENTDATE, 
                      CATRANSACTIONPAYMENT.SUPPLEMENTALDATA AS CHECKNUMBER, CATRANSACTIONPAYMENT.PAYMENTAMOUNT AS AMOUNTPAID, 
                      CAPAYMENTTYPE.NAME AS PAYMENTTYPE, CAPAYMENTSTATUS.NAME AS PAYMENTSTATUS, 
                      GLOBALENTITY.GLOBALENTITYNAME AS BILLINGCONTACTCOMPNAME, GLOBALENTITY.FIRSTNAME AS BILLINGCONTACTFNAME, 
                      GLOBALENTITY.LASTNAME AS BILLINGCONTACTLNAME, USERS.SUSERGUID AS CREATEDBYUSERGUID, USERS.ID AS CREATEDBYUSERID, 
                      USERS.FNAME AS CREATEDBYUSERFNAME, USERS.LNAME AS CREATEDBYUSERLNAME, CATRANSACTIONFEE.PAIDAMOUNT AS PAIDFEEAMOUNT, 
                      CAENTITY.NAME AS MODULENAME, CATRANSACTIONGLPOSTING.CATRANSACTIONGLPOSTINGID AS GLPOSTINGID, 
                      CATRANSACTIONGLPOSTING.CREDITACCOUNTNUMBER AS GLACCOUNTNUMBER, CATRANSACTIONGLPOSTING.POSTINGAMOUNT AS GLPOSTINGAMOUNT, ILLICENSE.LICENSENUMBER AS CASENUMBER, 
                      ILLICENSE.ILLICENSEID AS CASEID
FROM         CACOMPUTEDFEE INNER JOIN
                      CAINVOICEFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CAINVOICEFEE.CACOMPUTEDFEEID INNER JOIN
                      CAINVOICE ON CAINVOICEFEE.CAINVOICEID = CAINVOICE.CAINVOICEID INNER JOIN
                      CATRANSACTIONINVOICE ON CAINVOICE.CAINVOICEID = CATRANSACTIONINVOICE.CAINVOICEID INNER JOIN
                      CATRANSACTION ON CATRANSACTIONINVOICE.CATRANSACTIONID = CATRANSACTION.CATRANSACTIONID INNER JOIN
                      CATRANSACTIONPAYMENT ON CATRANSACTION.CATRANSACTIONID = CATRANSACTIONPAYMENT.CATRANSACTIONID INNER JOIN
                      CAPAYMENTTYPE ON CATRANSACTIONPAYMENT.CAPAYMENTTYPEID = CAPAYMENTTYPE.CAPAYMENTTYPEID INNER JOIN
                      CAPAYMENTSTATUS ON CATRANSACTIONPAYMENT.CAPAYMENTSTATUSID = CAPAYMENTSTATUS.CAPAYMENTSTATUSID INNER JOIN
                      GLOBALENTITY ON CATRANSACTION.GLOBALENTITYID = GLOBALENTITY.GLOBALENTITYID INNER JOIN
                      USERS ON CATRANSACTION.CREATEDBY = USERS.SUSERGUID INNER JOIN
                      CATRANSACTIONFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CATRANSACTIONFEE.CACOMPUTEDFEEID INNER JOIN
                      CAFEETEMPLATEFEE ON CACOMPUTEDFEE.CAFEETEMPLATEFEEID = CAFEETEMPLATEFEE.CAFEETEMPLATEFEEID INNER JOIN
                      CAFEETEMPLATE ON CAFEETEMPLATEFEE.CAFEETEMPLATEID = CAFEETEMPLATE.CAFEETEMPLATEID INNER JOIN
                      CAENTITY ON CAFEETEMPLATE.CAENTITYID = CAENTITY.CAENTITYID INNER JOIN
                      CATRANSACTIONFEEPOSTING ON CATRANSACTIONFEE.CATRANSACTIONFEEID = CATRANSACTIONFEEPOSTING.CATRANSACTIONFEEID INNER JOIN
                      CATRANSACTIONGLPOSTING ON 
                      CATRANSACTIONFEEPOSTING.CATRANSACTIONGLPOSTINGID = CATRANSACTIONGLPOSTING.CATRANSACTIONGLPOSTINGID INNER JOIN
                      ILLICENSEFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = ILLICENSEFEE.CACOMPUTEDFEEID INNER JOIN
                      ILLICENSE ON 
                      ILLICENSEFEE.ILLICENSEID = ILLICENSE.ILLICENSEID
--MISC FEES
--//USING CAMISCFEE.PAIDAMOUNT AS INVOICEFEEPAIDAMOUNT AND PAIDFEEAMOUNT//                                            
UNION ALL

SELECT     CAMISCFEE.FEENAME, CAMISCFEE.AMOUNT AS COMPUTEDFEEAMOUNT, CAMISCFEE.PAIDAMOUNT AS INVOICEFEEPAIDAMOUNT, 
                      CAINVOICE.INVOICENUMBER, CATRANSACTIONINVOICE.PAIDAMOUNT AS AMOUNTAPPLIEDTOINVOICE, CATRANSACTION.CATRANSACTIONID, CATRANSACTION.RECEIPTNUMBER, 
                      CATRANSACTIONPAYMENT.PAYMENTDATE, CATRANSACTIONPAYMENT.SUPPLEMENTALDATA AS CHECKNUMBER, CATRANSACTIONPAYMENT.PAYMENTAMOUNT AS AMOUNTPAID, 
                      CAPAYMENTTYPE.NAME AS PAYMENTTYPE, CAPAYMENTSTATUS.NAME AS PAYMENTSTATUS, GLOBALENTITY.GLOBALENTITYNAME AS BILLINGCONTACTCOMPNAME, 
                      GLOBALENTITY.FIRSTNAME AS BILLINGCONTACTFNAME, GLOBALENTITY.LASTNAME AS BILLINGCONTACTLNAME, USERS.SUSERGUID AS CREATEDBYUSERGUID, 
                      USERS.ID AS CREATEDBYUSERID, USERS.FNAME AS CREATEDBYUSERFNAME, USERS.LNAME AS CREATEDBYUSERLNAME, CAMISCFEE.PAIDAMOUNT AS PAIDFEEAMOUNT,
                      '' AS MODULENAME, '' AS GLPOSTINGID,
                      '' AS GLACCOUNTNUMBER, '' AS GLPOSTINGAMOUNT,
                      '' AS CASENUMBER,
                      '' AS CASEID
FROM         CAINVOICE INNER JOIN
                      CATRANSACTIONINVOICE ON CAINVOICE.CAINVOICEID = CATRANSACTIONINVOICE.CAINVOICEID INNER JOIN
                      CATRANSACTION ON CATRANSACTIONINVOICE.CATRANSACTIONID = CATRANSACTION.CATRANSACTIONID INNER JOIN
                      CATRANSACTIONPAYMENT ON CATRANSACTION.CATRANSACTIONID = CATRANSACTIONPAYMENT.CATRANSACTIONID INNER JOIN
                      CAPAYMENTTYPE ON CATRANSACTIONPAYMENT.CAPAYMENTTYPEID = CAPAYMENTTYPE.CAPAYMENTTYPEID INNER JOIN
                      CAPAYMENTSTATUS ON CATRANSACTIONPAYMENT.CAPAYMENTSTATUSID = CAPAYMENTSTATUS.CAPAYMENTSTATUSID INNER JOIN
                      GLOBALENTITY ON CATRANSACTION.GLOBALENTITYID = GLOBALENTITY.GLOBALENTITYID INNER JOIN
                      USERS ON CATRANSACTION.CREATEDBY = USERS.SUSERGUID INNER JOIN
                      CAINVOICEMISCFEE ON CAINVOICE.CAINVOICEID = CAINVOICEMISCFEE.CAINVOICEID INNER JOIN
                      CAMISCFEE ON CAINVOICEMISCFEE.CAMISCFEEID = CAMISCFEE.CAMISCFEEID