
CREATE VIEW [dbo].PORTALTODAYSINSPECTIONSVIEW
AS
SELECT
ii.IMINSPECTIONID INSPECTIONID, LINKID ENTITYID, LINKNUMBER ENTITYNUMBER, iil.NAME ENTITYTYPE, 
iit.NAME INSPECTIONTYPENAME, iis.STATUSNAME INSPECTIONSTATUSNAME, ii.INSPECTIONORDER, 
CASE WHEN u.SUSERGUID IS NOT NULL THEN (u.LNAME + ', ' + u.FNAME) ELSE NULL END PRIMARYINSPECTORNAME,
ii.SCHEDULEDSTARTDATE, ii.COMPLETE, 
RTRIM(
CASE WHEN LEN(ADDRESSLINE1) > 0 THEN ADDRESSLINE1 + ' ' ELSE '' END + 
CASE WHEN COUNTRYTYPE <> 1 AND LEN(PREDIRECTION) > 0 THEN PREDIRECTION + ' ' ELSE '' END + 
CASE WHEN LEN(ADDRESSLINE2) > 0 THEN ADDRESSLINE2 + ' ' ELSE '' END + 
CASE WHEN LEN(STREETTYPE) > 0 THEN STREETTYPE + ' ' ELSE '' END + 
CASE WHEN LEN(POSTDIRECTION) > 0 THEN POSTDIRECTION + ' ' ELSE '' END + 
CASE WHEN LEN(UNITORSUITE) > 0 THEN UNITORSUITE + ' ' ELSE '' END + 
CASE WHEN LEN(ADDRESSLINE3) > 0 THEN ADDRESSLINE3 + ' ' ELSE '' END + 
CASE WHEN LEN(CITY) > 0 THEN CITY + ', ' ELSE '' END + 
CASE WHEN COUNTRYTYPE = 1 AND LEN(PROVINCE) > 0 THEN PROVINCE + ' ' WHEN COUNTRYTYPE <> 1 AND LEN([STATE]) > 0 THEN [STATE] + ' ' ELSE '' END + 
CASE WHEN LEN(POSTALCODE) > 0 THEN POSTALCODE ELSE '' END
) [ADDRESS], ma.COUNTRYTYPE,
ma.ADDRESSLINE1, ma.PREDIRECTION, ma.ADDRESSLINE2, ma.STREETTYPE, ma.POSTDIRECTION, ma.UNITORSUITE, ma.ADDRESSLINE3, 
ma.CITY, ma.[STATE], ma.PROVINCE, ma.POSTALCODE
FROM IMINSPECTION ii
INNER JOIN IMINSPECTIONTYPE iit ON iit.IMINSPECTIONTYPEID = ii.IMINSPECTIONTYPEID
INNER JOIN IMINSPECTIONSTATUS iis ON iis.IMINSPECTIONSTATUSID = ii.IMINSPECTIONSTATUSID
INNER JOIN IMINSPECTIONLINK iil ON iil.IMINSPECTIONLINKID = ii.IMINSPECTIONLINKID
LEFT OUTER JOIN IMINSPECTORREF iir ON iir.INSPECTIONID = ii.IMINSPECTIONID AND iir.BPRIMARY = 1
LEFT OUTER JOIN USERS u ON iir.USERID = u.SUSERGUID
LEFT OUTER JOIN IMINSPECTIONADDRESS iia ON iia.IMINSPECTIONID = ii.IMINSPECTIONID AND iia.MAIN = 1
LEFT OUTER JOIN MAILINGADDRESS ma ON ma.MAILINGADDRESSID = iia.MAILINGADDRESSID
WHERE ii.IMINSPECTIONLINKID IN (1, 2)

