
CREATE VIEW [dbo].PORTALEREVIEWSIMPLEVIEW
AS

SELECT 
	ep.PLPLANID EntityID, ERPROJECTID ProjectID, PROJECTNUM ProjectNumber, s.NAME ProjectStatusName, x.PLANNUMBER CaseNumber, 
	MAX(applicant.CONTACTNAME) ApplicantName, MAX(contractor.CONTACTNAME) ContractorName
FROM ERPROJECT ep INNER JOIN
ERPROJECTSTATUS s ON ep.ERPROJECTSTATUSID = s.ERPROJECTSTATUSID INNER JOIN
PLPLAN x ON x.PLPLANID = ep.PLPLANID LEFT OUTER JOIN
(
SELECT CASE WHEN LEN(RTRIM(GLOBALENTITYNAME)) > 0 THEN GLOBALENTITYNAME ELSE LASTNAME + ', ' + FIRSTNAME END CONTACTNAME, PLPLANID
FROM
PLPLANCONTACT xc INNER JOIN
LANDMANAGEMENTCONTACTTYPE ct ON ct.LANDMANAGEMENTCONTACTTYPEID = xc.LANDMANAGEMENTCONTACTTYPEID AND ct.LANDMANAGEMENTCONTACTSYSTEMTYP = 1 INNER JOIN
GLOBALENTITY c ON c.GLOBALENTITYID = xc.GLOBALENTITYID 
) applicant ON applicant.PLPLANID = ep.PLPLANID LEFT OUTER JOIN
(
SELECT CASE WHEN LEN(RTRIM(GLOBALENTITYNAME)) > 0 THEN GLOBALENTITYNAME ELSE LASTNAME + ', ' + FIRSTNAME END CONTACTNAME, PLPLANID
FROM
PLPLANCONTACT xc INNER JOIN
LANDMANAGEMENTCONTACTTYPE ct ON ct.LANDMANAGEMENTCONTACTTYPEID = xc.LANDMANAGEMENTCONTACTTYPEID AND ct.LANDMANAGEMENTCONTACTSYSTEMTYP = 3 INNER JOIN
GLOBALENTITY c ON c.GLOBALENTITYID = xc.GLOBALENTITYID 
) contractor ON contractor.PLPLANID = ep.PLPLANID
GROUP BY ep.PLPLANID, ERPROJECTID, PROJECTNUM, NAME, PLANNUMBER
UNION
SELECT 
	ep.PMPERMITID EntityID, ERPROJECTID ProjectID, PROJECTNUM ProjectNumber, s.NAME ProjectStatusName, x.PERMITNUMBER CaseNumber, 
	MAX(applicant.CONTACTNAME) ApplicantName, MAX(contractor.CONTACTNAME) ContractorName
FROM ERPROJECT ep INNER JOIN
ERPROJECTSTATUS s ON ep.ERPROJECTSTATUSID = s.ERPROJECTSTATUSID INNER JOIN
PMPERMIT x ON x.PMPERMITID = ep.PMPERMITID LEFT OUTER JOIN
(
SELECT CASE WHEN LEN(RTRIM(GLOBALENTITYNAME)) > 0 THEN GLOBALENTITYNAME ELSE LASTNAME + ', ' + FIRSTNAME END CONTACTNAME, PMPERMITID
FROM
PMPERMITCONTACT xc INNER JOIN
LANDMANAGEMENTCONTACTTYPE ct ON ct.LANDMANAGEMENTCONTACTTYPEID = xc.LANDMANAGEMENTCONTACTTYPEID AND ct.LANDMANAGEMENTCONTACTSYSTEMTYP = 1 INNER JOIN
GLOBALENTITY c ON c.GLOBALENTITYID = xc.GLOBALENTITYID 
) applicant ON applicant.PMPERMITID = ep.PMPERMITID LEFT OUTER JOIN
(
SELECT CASE WHEN LEN(RTRIM(GLOBALENTITYNAME)) > 0 THEN GLOBALENTITYNAME ELSE LASTNAME + ', ' + FIRSTNAME END CONTACTNAME, PMPERMITID
FROM
PMPERMITCONTACT xc INNER JOIN
LANDMANAGEMENTCONTACTTYPE ct ON ct.LANDMANAGEMENTCONTACTTYPEID = xc.LANDMANAGEMENTCONTACTTYPEID AND ct.LANDMANAGEMENTCONTACTSYSTEMTYP = 3 INNER JOIN
GLOBALENTITY c ON c.GLOBALENTITYID = xc.GLOBALENTITYID 
) contractor ON contractor.PMPERMITID = ep.PMPERMITID
GROUP BY ep.PMPERMITID, ERPROJECTID, PROJECTNUM, NAME, PERMITNUMBER




