CREATE PROCEDURE [dbo].[USP_VALUATIONVARIABLE_UPDATE]
(
	@VALUATIONVARIABLEID CHAR(36),
	@VALUATIONTYPEID CHAR(36),
	@VALUATIONGROUPID CHAR(36),
	@VARIABLE NVARCHAR(100),
	@DESCRIPTION NVARCHAR(MAX),
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
UPDATE [dbo].[VALUATIONVARIABLE] SET
	[VALUATIONTYPEID] = @VALUATIONTYPEID,
	[VALUATIONGROUPID] = @VALUATIONGROUPID,
	[VARIABLE] = @VARIABLE,
	[DESCRIPTION] = @DESCRIPTION,
	[LASTCHANGEDBY] = @LASTCHANGEDBY,
	[LASTCHANGEDON] = @LASTCHANGEDON,
	[ROWVERSION] = @ROWVERSION + 1
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE
	[VALUATIONVARIABLEID] = @VALUATIONVARIABLEID AND 
	[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE