

CREATE FUNCTION [dbo].[CSS_INVOICE_CASE_MODULE]
(
	@INVOICE_ID CHAR(36)
)
RETURNS INT
AS
BEGIN
	DECLARE @RESULT AS INT
	BEGIN
	 SET @RESULT = COALESCE((SELECT TOP 1 2 AS "ENTITYTYPE"
                  FROM PLPLAN
                  INNER JOIN PLPLANFEE ON PLPLANFEE.PLPLANID = PLPLAN.PLPLANID
                  INNER JOIN CAINVOICEFEE ON CAINVOICEFEE.CACOMPUTEDFEEID = PLPLANFEE.CACOMPUTEDFEEID
                  WHERE CAINVOICEFEE.CAINVOICEID = @INVOICE_ID), 
            (SELECT TOP 1 3 AS "ENTITYTYPE"
                  FROM PMPERMIT
                  INNER JOIN PMPERMITFEE ON PMPERMITFEE.PMPERMITID = PMPERMIT.PMPERMITID
                  INNER JOIN CAINVOICEFEE ON CAINVOICEFEE.CACOMPUTEDFEEID = PMPERMITFEE.CACOMPUTEDFEEID
                  WHERE CAINVOICEFEE.CAINVOICEID = @INVOICE_ID),             
                  (SELECT TOP 1 5 AS "ENTITYTYPE"
                  FROM BLLICENSE
                  INNER JOIN BLLICENSEFEE ON BLLICENSEFEE.BLLICENSEID = BLLICENSE.BLLICENSEID
                  INNER JOIN CAINVOICEFEE ON CAINVOICEFEE.CACOMPUTEDFEEID = BLLICENSEFEE.CACOMPUTEDFEEID
                  WHERE CAINVOICEFEE.CAINVOICEID = @INVOICE_ID),   
				  (SELECT TOP 1 11 AS "ENTITYTYPE"
                  FROM ILLICENSE
                  INNER JOIN ILLICENSEFEE ON ILLICENSEFEE.ILLICENSEID = ILLICENSE.ILLICENSEID
                  INNER JOIN CAINVOICEFEE ON CAINVOICEFEE.CACOMPUTEDFEEID = ILLICENSEFEE.CACOMPUTEDFEEID
                  WHERE CAINVOICEFEE.CAINVOICEID = @INVOICE_ID),              
                  (SELECT TOP 1 4 AS "ENTITYTYPE"
                  FROM IMINSPECTION
                  INNER JOIN IMINSPECTIONFEE ON IMINSPECTIONFEE.IMINSPECTIONID = IMINSPECTION.IMINSPECTIONID
                  INNER JOIN CAINVOICEFEE ON CAINVOICEFEE.CACOMPUTEDFEEID = IMINSPECTIONFEE.CACOMPUTEDFEEID
                  WHERE CAINVOICEFEE.CAINVOICEID = @INVOICE_ID),                                                                
            1	 )   	
	END
	
	RETURN @RESULT
END