CREATE FUNCTION [DBO].[ELAPSEDBDAYS] (@START SMALLDATETIME, @END SMALLDATETIME)
RETURNS INT 
AS
BEGIN
/*
DESCRIPTION:
FUNCTION DESIGNED TO CALCULATE THE NUMBER OF BUSINESS DAYS BETWEEN TWO DATES.
*/
DECLARE @WEEKDAYS INT,@HOLIDAYS INT,@DAYS INT

IF DATEDIFF(DD, @START, @END) = 0 BEGIN
SELECT @DAYS = 1 
RETURN @DAYS
END

ELSE

SELECT @WEEKDAYS = (DATEDIFF(DD, @START, @END) + 1)
    -(DATEDIFF(WK, @START, @END) * 2)
    -(CASE WHEN DATEPART(DW, @START) = 1 THEN 1 ELSE 0 END)
    -(CASE WHEN DATEPART(DW, @END) = 7 THEN 1 ELSE 0 END)


SELECT @HOLIDAYS = COUNT(*) FROM HOLIDAY WHERE (HOLIDAYDATE BETWEEN @START AND @END) 
AND DATEPART(WEEKDAY,HOLIDAYDATE)-1 % 6 <> 0 


SELECT @DAYS = @WEEKDAYS - @HOLIDAYS


RETURN(@DAYS)

END