CREATE FUNCTION DBO.LINKEDAPPLICATIONFROMCONTACT
(	
	@ENTITY_ID char(36),
	@USER_ID char(36)	
)
RETURNS TABLE 
AS
RETURN 
(
	select PLAPPLICATIONCONTACT.PLAPPLICATIONID from PLAPPLICATIONCONTACT 
	INNER JOIN PLAPPLICATION ON PLAPPLICATIONCONTACT.PLAPPLICATIONID = PLAPPLICATION.PLAPPLICATIONID	
	INNER JOIN GETUSERVISIBLERECORDTYPES(@USER_ID) u on PLAPPLICATION.PLAPPLICATIONTYPEID = u.RECORDTYPEID
	where PLAPPLICATIONCONTACT.GLOBALENTITYID = @ENTITY_ID
)

