CREATE FUNCTION DBO.LINKEDPLANFROMPROPERTYMANAGEMENT
(	
	@ENTITY_ID char(36),
	@USER_ID char(36)
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT DISTINCT PLPLAN.PLPLANID, 0 AS ISCHILD, 1 AS ISPARENT FROM PLPLANPARCEL
	INNER JOIN PLPLAN ON  PLPLANPARCEL.PLPLANID = PLPLAN.PLPLANID
	INNER JOIN GETUSERVISIBLERECORDTYPES(@USER_ID) u on PLPLAN.PLPLANTYPEID = u.RECORDTYPEID
	WHERE (PLPLANPARCEL.PARCELID = @ENTITY_ID)
)