CREATE FUNCTION DBO.LINKEDRENTALPROPERTIESFROMCONTACT
(	
	@ENTITY_ID char(36),
	@USER_ID char(36)
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT lproperty.RPPROPERTYID FROM RPPROPERTY lproperty 
	INNER JOIN RPLANDLORDLICENSE llicense ON lproperty.RPLANDLORDLICENSEID = llicense.RPLANDLORDLICENSEID
	INNER JOIN GETUSERVISIBLERECORDTYPES(@USER_ID) u ON lproperty.RPPROPERTYTYPEID = u.RECORDTYPEID
	WHERE GLOBALENTITYID = @ENTITY_ID
)