CREATE FUNCTION DBO.LINKEDPROFLICENSEFROMCONTACT
(	
	@ENTITY_ID char(36),
	@USER_ID char(36)
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT DISTINCT pl.ILLICENSEID from ILLICENSECONTACT plc
	INNER JOIN ILLICENSE pl on plc.ILLICENSEID = pl.ILLICENSEID	
	INNER JOIN GETUSERVISIBLERECORDTYPES(@USER_ID) u on pl.ILLICENSETYPEID = u.RECORDTYPEID
	where plc.GLOBALENTITYID = @ENTITY_ID	
	UNION
	SELECT DISTINCT PLI.ILLICENSEID FROM ILLICENSE PLI
	INNER JOIN GETUSERVISIBLERECORDTYPES(@USER_ID) u on PLI.ILLICENSETYPEID = u.RECORDTYPEID
	WHERE PLI.GLOBALENTITYID = @ENTITY_ID
)