CREATE FUNCTION DBO.LINKEDPERMITFROMPROJECT
(	
	@ENTITY_ID char(36),
	@USER_ID char(36)
)
RETURNS TABLE 
AS
RETURN 
(
	Select PMPERMIT.PMPERMITID, 1 AS ISCHILD, 0 AS ISPARENT FROM PRPROJECTPERMIT 
	INNER JOIN PMPERMIT ON PRPROJECTPERMIT.PMPERMITID = PMPERMIT.PMPERMITID 
	INNER JOIN GETUSERVISIBLERECORDTYPES(@USER_ID) u on PMPERMIT.PMPERMITTYPEID = u.RECORDTYPEID
	WHERE(PRPROJECTPERMIT.PRPROJECTID = @ENTITY_ID)
)