CREATE FUNCTION DBO.LINKEDPROFLICENSEFROMPERMIT
(	
	@ENTITY_ID char(36),
	@USER_ID char(36)
)
RETURNS TABLE 
AS
RETURN 
(
		select oneLicense.ILLICENSEID from PMPERMITACTIONREF xref 
		INNER JOIN ILLICENSEWFACTIONSTEP illicense ON xref.OBJECTID = illicense.ILLICENSEWFACTIONSTEPID  
		INNER join ILLICENSEWFSTEP step on illicense.ILLICENSEWFSTEPID = step.ILLICENSEWFSTEPID  
		INNER JOIN ILLICENSE oneLicense on step.ILLICENSEID = oneLicense.ILLICENSEID  
		INNER JOIN GETUSERVISIBLERECORDTYPES(@USER_ID) u on oneLicense.ILLICENSETYPEID = u.RECORDTYPEID
		where xref.PMPERMITID = @ENTITY_ID
	 
)

