CREATE FUNCTION DBO.LINKEDCODECASEFROMCODECASE
(	
	@ENTITY_ID char(36),
	@USER_ID char(36)
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT CMCODECASE.CMCODECASEID,1 AS ISCHILD, 0 AS ISPARENT FROM CMCODEWFSTEP
	INNER JOIN CMCODEWFACTIONSTEP ON CMCODEWFSTEP.CMCODEWFSTEPID = CMCODEWFACTIONSTEP.CMCODEWFSTEPID
	INNER JOIN CMCODECASEACTIONREF ON CMCODEWFACTIONSTEP.CMCODEWFACTIONSTEPID = CMCODECASEACTIONREF.CMCODECASEACTIONREFID
	INNER JOIN CMCODECASE ON CMCODECASEACTIONREF.CMCODECASEID = CMCODECASE.CMCODECASEID
	INNER JOIN GETUSERVISIBLERECORDTYPES(@USER_ID) u on CMCODECASE.CMCASETYPEID = u.RECORDTYPEID
	WHERE (CMCODEWFSTEP.CMCODECASEID = @ENTITY_ID)
	UNION ALL 
	SELECT CMCODECASE.CMCODECASEID,0 AS ISCHILD, 1 AS ISPARENT FROM CMCODECASEACTIONREF
	INNER JOIN CMCODEWFACTIONSTEP ON CMCODECASEACTIONREF.CMCODECASEACTIONREFID = CMCODEWFACTIONSTEP.CMCODEWFACTIONSTEPID 
	INNER JOIN CMCODEWFSTEP ON CMCODEWFACTIONSTEP.CMCODEWFSTEPID = CMCODEWFSTEP.CMCODEWFSTEPID
	INNER JOIN CMCODECASE ON CMCODEWFSTEP.CMCODECASEID = CMCODECASE.CMCODECASEID
	INNER JOIN GETUSERVISIBLERECORDTYPES(@USER_ID) u on CMCODECASE.CMCASETYPEID = u.RECORDTYPEID
	WHERE (CMCODECASEACTIONREF.CMCODECASEID = @ENTITY_ID)
)