CREATE FUNCTION DBO.LINKEDAPPLICATIONFROMPROPERTYMANAGEMENT
(	
	@ENTITY_ID char(36),
	@USER_ID as CHAR(36)	
)
RETURNS TABLE 
AS
RETURN 
(
	select DISTINCT PLAPPLICATIONPARCEL.PLAPPLICATIONID from PLAPPLICATIONPARCEL
	INNER JOIN PLAPPLICATION ON PLAPPLICATIONPARCEL.PLAPPLICATIONID = PLAPPLICATION.PLAPPLICATIONID
	INNER JOIN GETUSERVISIBLERECORDTYPES(@USER_ID) u on PLAPPLICATION.PLAPPLICATIONTYPEID = u.RECORDTYPEID
	where PLAPPLICATIONPARCEL.PARCELID  = @ENTITY_ID
)