CREATE FUNCTION DBO.LINKEDPERMITFROMAPPLICATION
(	
	@ENTITY_ID char(36),
	@USER_ID char(36)
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT DISTINCT PMPERMIT.PMPERMITID, 0 AS ISCHILD, 1 AS ISPARENT FROM PLAPPLICATIONATTACHEDCASELIST 
	INNER JOIN PMPERMIT ON PMPERMIT.PMPERMITID = PLAPPLICATIONATTACHEDCASELIST.ATTACHEDCASEID
	INNER JOIN GETUSERVISIBLERECORDTYPES(@USER_ID) u on PMPERMIT.PMPERMITTYPEID = u.RECORDTYPEID
	WHERE (PLAPPLICATIONATTACHEDCASELIST.APPLICATIONID = @ENTITY_ID)
)