CREATE FUNCTION DBO.LINKEDPLANFROMBUSINESSLICENSE
(	
	@ENTITY_ID char(36),
	@USER_ID char(36)
)
RETURNS TABLE 
AS
RETURN 
(
	    SELECT PLPLAN.PLPLANID,1 as ISCHILD , 0 as ISPARENT FROM BLLICENSE 
		INNER JOIN BLLICENSEWFSTEP ON BLLICENSE.BLLICENSEID = BLLICENSEWFSTEP.BLLICENSEID 
		INNER JOIN BLLICENSEWFACTIONSTEP ON BLLICENSEWFSTEP.BLLICENSEWFSTEPID = BLLICENSEWFACTIONSTEP.BLLICENSEWFSTEPID
		INNER JOIN PLPLANACTIONREF ON BLLICENSEWFACTIONSTEP.BLLICENSEWFACTIONSTEPID = PLPLANACTIONREF.OBJECTID
		INNER JOIN PLPLAN ON PLPLANACTIONREF.PLPLANID = PLPLAN.PLPLANID 
		INNER JOIN GETUSERVISIBLERECORDTYPES(@USER_ID) u on PLPLAN.PLPLANTYPEID = u.RECORDTYPEID
		WHERE (BLLICENSE.BLLICENSEID = @ENTITY_ID)
		UNION ALL
		SELECT PLPLAN.PLPLANID,0 as ISCHILD , 1 as ISPARENT FROM BLLICENSEACTIONREF 
		INNER JOIN PLPLANWFACTIONSTEP ON BLLICENSEACTIONREF.OBJECTID = PLPLANWFACTIONSTEP.PLPLANWFACTIONSTEPID
		INNER JOIN PLPLANWFSTEP ON PLPLANWFACTIONSTEP.PLPLANWFSTEPID = PLPLANWFSTEP.PLPLANWFSTEPID
		INNER JOIN PLPLAN ON PLPLANWFSTEP.PLPLANID = PLPLAN.PLPLANID 
		INNER JOIN GETUSERVISIBLERECORDTYPES(@USER_ID) u on PLPLAN.PLPLANTYPEID = u.RECORDTYPEID
		WHERE (BLLICENSEACTIONREF.BLLICENSEID = @ENTITY_ID)
)