CREATE FUNCTION DBO.LINKEDCODECASEFROMBUSINESS
(	
	@ENTITY_ID char(36),
	@USER_ID char(36)
)
RETURNS TABLE 
AS
RETURN 
(	
	SELECT cc.CMCODECASEID,1 AS ISCHILD, 0 AS ISPARENT FROM CMCODECASE cc
	INNER JOIN BLGLOBALENTITYEXTENSIONCODECASEXREF xref ON cc.CMCODECASEID = xref.CMCODECASEID 	
	INNER JOIN GETUSERVISIBLERECORDTYPES(@USER_ID) u on cc.CMCASETYPEID = u.RECORDTYPEID
	WHERE (xref.BLGLOBALENTITYEXTENSIONID = @ENTITY_ID)
)