CREATE FUNCTION DBO.LINKEDPERMITFROMPERMIT
(	
	@ENTITY_ID char(36),
	@USER_ID char(36)
)
RETURNS TABLE 
AS
RETURN 
(
	Select PMPERMIT.PMPERMITID, 1 AS ISCHILD, 0 AS ISPARENT FROM PMPERMITWFSTEP 
	INNER JOIN PMPERMITWFACTIONSTEP ON PMPERMITWFSTEP.PMPERMITWFSTEPID = PMPERMITWFACTIONSTEP.PMPERMITWFSTEPID 
	INNER JOIN PMPERMITACTIONREF ON PMPERMITWFACTIONSTEP.PMPERMITWFACTIONSTEPID = PMPERMITACTIONREF.OBJECTID 
	INNER JOIN PMPERMIT ON PMPERMITACTIONREF.PMPERMITID = PMPERMIT.PMPERMITID 
	INNER JOIN GETUSERVISIBLERECORDTYPES(@USER_ID) u on PMPERMIT.PMPERMITTYPEID = u.RECORDTYPEID
	WHERE(PMPERMITWFSTEP.PMPERMITID = @ENTITY_ID)
	UNION ALL 
	SELECT PMPERMIT.PMPERMITID, 0 AS ISCHILD, 1 AS ISPARENT FROM PMPERMITACTIONREF 
	INNER JOIN PMPERMITWFACTIONSTEP ON PMPERMITACTIONREF.OBJECTID = PMPERMITWFACTIONSTEP.PMPERMITWFACTIONSTEPID 
	INNER JOIN PMPERMITWFSTEP ON PMPERMITWFACTIONSTEP.PMPERMITWFSTEPID = PMPERMITWFSTEP.PMPERMITWFSTEPID
	INNER JOIN PMPERMIT ON PMPERMITWFSTEP.PMPERMITID = PMPERMIT.PMPERMITID 
	INNER JOIN GETUSERVISIBLERECORDTYPES(@USER_ID) u on PMPERMIT.PMPERMITTYPEID = u.RECORDTYPEID
	WHERE(PMPERMITACTIONREF.PMPERMITID = @ENTITY_ID)
)
