CREATE FUNCTION DBO.LINKEDREQUESTFROMCONTACT
(	
	@ENTITY_ID char(36),
	@USER_ID as CHAR(36)
)
RETURNS TABLE 
AS
RETURN 
(
SELECT DISTINCT request.CITIZENREQUESTID
FROM CITIZENREQUEST request
INNER JOIN CITIZENREQUESTCALLERXREF xref ON request.CITIZENREQUESTID = xref.CITIZENREQUESTID
INNER JOIN GETUSERVISIBLERECORDTYPES(@USER_ID) u on request.CITIZENREQUESTTYPEID = u.RECORDTYPEID
WHERE xref.GLOBALENTITYID = @ENTITY_ID
)