CREATE FUNCTION DBO.LINKEDPLANFROMPLAN
(	
	@ENTITY_ID char(36),
	@USER_ID char(36)
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT PLPLAN.PLPLANID, 1 AS ISCHILD, 0 AS ISPARENT FROM PLPLANWFSTEP
	INNER JOIN PLPLANWFACTIONSTEP ON PLPLANWFSTEP.PLPLANWFSTEPID = PLPLANWFACTIONSTEP.PLPLANWFSTEPID
	INNER JOIN PLPLANACTIONREF ON PLPLANWFACTIONSTEP.PLPLANWFACTIONSTEPID = PLPLANACTIONREF.OBJECTID
	INNER JOIN PLPLAN ON PLPLANACTIONREF.PLPLANID = PLPLAN.PLPLANID
	INNER JOIN GETUSERVISIBLERECORDTYPES(@USER_ID) u on PLPLAN.PLPLANTYPEID = u.RECORDTYPEID
	WHERE (PLPLANWFSTEP.PLPLANID = @ENTITY_ID)
	UNION ALL
	SELECT PLPLAN.PLPLANID,0 AS ISCHILD, 1 AS ISPARENT FROM PLPLANACTIONREF
	INNER JOIN PLPLANWFACTIONSTEP ON PLPLANACTIONREF.OBJECTID = PLPLANWFACTIONSTEP.PLPLANWFACTIONSTEPID 
	INNER JOIN PLPLANWFSTEP ON PLPLANWFACTIONSTEP.PLPLANWFSTEPID = PLPLANWFSTEP.PLPLANWFSTEPID
	INNER JOIN PLPLAN ON PLPLANWFSTEP.PLPLANID = PLPLAN.PLPLANID 
	INNER JOIN GETUSERVISIBLERECORDTYPES(@USER_ID) u on PLPLAN.PLPLANTYPEID = u.RECORDTYPEID
	WHERE (PLPLANACTIONREF.PLPLANID = @ENTITY_ID)
)