CREATE FUNCTION DBO.LINKEDPLANFROMAPPLICATION
(	
	@ENTITY_ID char(36),
	@USER_ID char(36)
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT DISTINCT PLPLAN.PLPLANID, 0 AS ISCHILD, 1 AS ISPARENT FROM PLAPPLICATIONATTACHEDCASELIST 
	INNER JOIN PLPLAN ON PLPLAN.PLPLANID = PLAPPLICATIONATTACHEDCASELIST.ATTACHEDCASEID
	INNER JOIN GETUSERVISIBLERECORDTYPES(@USER_ID) u on PLPLAN.PLPLANTYPEID = u.RECORDTYPEID
	WHERE (PLAPPLICATIONATTACHEDCASELIST.APPLICATIONID = @ENTITY_ID)
)