CREATE FUNCTION DBO.LINKEDPLANFROMPERMIT
(	
	@ENTITY_ID char(36),
	@USER_ID char(36)
)
RETURNS TABLE 
AS
RETURN 
(
	    SELECT PLPLAN.PLPLANID,1 as ISCHILD , 0 as ISPARENT FROM PMPERMIT 
		INNER JOIN PMPERMITWFSTEP ON PMPERMIT.PMPERMITID = PMPERMITWFSTEP.PMPERMITID 
		INNER JOIN PMPERMITWFACTIONSTEP ON PMPERMITWFSTEP.PMPERMITWFSTEPID = PMPERMITWFACTIONSTEP.PMPERMITWFSTEPID
		INNER JOIN PLPLANACTIONREF ON PMPERMITWFACTIONSTEP.PMPERMITWFACTIONSTEPID = PLPLANACTIONREF.OBJECTID
		INNER JOIN PLPLAN ON PLPLANACTIONREF.PLPLANID = PLPLAN.PLPLANID 
		INNER JOIN GETUSERVISIBLERECORDTYPES(@USER_ID) u on PLPLAN.PLPLANTYPEID = u.RECORDTYPEID
		WHERE (PMPERMIT.PMPERMITID = @ENTITY_ID)
		UNION ALL
		SELECT PLPLAN.PLPLANID,0 as ISCHILD , 1 as ISPARENT FROM PMPERMITACTIONREF 
		INNER JOIN PLPLANWFACTIONSTEP ON PMPERMITACTIONREF.OBJECTID = PLPLANWFACTIONSTEP.PLPLANWFACTIONSTEPID
		INNER JOIN PLPLANWFSTEP ON PLPLANWFACTIONSTEP.PLPLANWFSTEPID = PLPLANWFSTEP.PLPLANWFSTEPID
		INNER JOIN PLPLAN ON PLPLANWFSTEP.PLPLANID = PLPLAN.PLPLANID 
		INNER JOIN GETUSERVISIBLERECORDTYPES(@USER_ID) u on PLPLAN.PLPLANTYPEID = u.RECORDTYPEID
		WHERE (PMPERMITACTIONREF.PMPERMITID = @ENTITY_ID)
)