CREATE FUNCTION DBO.LINKEDPLANFROMPROFESSIONALLICENSE
(	
	@ENTITY_ID char(36),
	@USER_ID char(36)
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT PLPLAN.PLPLANID,1 AS ISCHILD, 0 AS ISPARENT 	FROM ILLICENSE 
	INNER JOIN ILLICENSEWFSTEP ON ILLICENSE.ILLICENSEID = ILLICENSEWFSTEP.ILLICENSEID
	INNER JOIN ILLICENSEWFACTIONSTEP ON ILLICENSEWFSTEP.ILLICENSEWFSTEPID = ILLICENSEWFACTIONSTEP.ILLICENSEWFSTEPID
	INNER JOIN PLPLANACTIONREF ON ILLICENSEWFACTIONSTEP.ILLICENSEWFACTIONSTEPID = PLPLANACTIONREF.OBJECTID
	INNER JOIN PLPLAN ON PLPLANACTIONREF.PLPLANID = PLPLAN.PLPLANID 
	INNER JOIN GETUSERVISIBLERECORDTYPES(@USER_ID) u on PLPLAN.PLPLANTYPEID = u.RECORDTYPEID
	WHERE (ILLICENSE.ILLICENSEID = @ENTITY_ID)
)