CREATE FUNCTION DBO.LINKEDBUSINESSFROMCODECASE
(	
	@ENTITY_ID char(36),
	@BLEXTCOMPANYTYPEMODULE_ID INT
)
RETURNS TABLE 
AS
RETURN 
(		
	SELECT blg.BLGLOBALENTITYEXTENSIONID FROM BLGLOBALENTITYEXTENSION blg
	INNER JOIN BLGLOBALENTITYEXTENSIONCODECASEXREF xref ON xref.BLGLOBALENTITYEXTENSIONID = blg.BLGLOBALENTITYEXTENSIONID
	INNER JOIN BLEXTCOMPANYTYPE ON BLEXTCOMPANYTYPE.BLEXTCOMPANYTYPEID = blg.BLEXTCOMPANYTYPEID
	WHERE xref.CMCODECASEID = @ENTITY_ID AND BLEXTCOMPANYTYPE.BLEXTCOMPANYTYPEMODULEID= @BLEXTCOMPANYTYPEMODULE_ID	
)