CREATE FUNCTION DBO.LINKEDCODECASEFROMPLAN
(	
	@ENTITY_ID char(36),
	@USER_ID char(36)
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT CMCODECASE.CMCODECASEID, 1 AS ISCHILD, 0 AS ISPARENT	FROM PLPLAN 
	INNER JOIN PLPLANWFSTEP ON PLPLAN.PLPLANID = PLPLANWFSTEP.PLPLANID
	INNER JOIN PLPLANWFACTIONSTEP ON PLPLANWFSTEP.PLPLANWFSTEPID = PLPLANWFACTIONSTEP.PLPLANWFSTEPID
	INNER JOIN CMCODECASEACTIONREF ON PLPLANWFACTIONSTEP.PLPLANWFACTIONSTEPID = CMCODECASEACTIONREF.CMCODECASEACTIONREFID
	INNER JOIN CMCODECASE ON CMCODECASEACTIONREF.CMCODECASEID = CMCODECASE.CMCODECASEID 
	INNER JOIN GETUSERVISIBLERECORDTYPES(@USER_ID) u on CMCODECASE.CMCASETYPEID = u.RECORDTYPEID
	WHERE (PLPLAN.PLPLANID = @ENTITY_ID)
	UNION ALL
	SELECT CMCODECASE.CMCODECASEID, 0 AS ISCHILD, 1 AS ISPARENT	FROM PLPLANACTIONREF
	INNER JOIN CMCODEWFACTIONSTEP ON PLPLANACTIONREF.OBJECTID = CMCODEWFACTIONSTEP.CMCODEWFACTIONSTEPID
	INNER JOIN CMCODEWFSTEP ON CMCODEWFACTIONSTEP.CMCODEWFSTEPID = CMCODEWFSTEP.CMCODEWFSTEPID
	INNER JOIN CMCODECASE ON CMCODEWFSTEP.CMCODECASEID = CMCODECASE.CMCODECASEID 
	INNER JOIN PLPLAN ON PLPLANACTIONREF.PLPLANID = PLPLAN.PLPLANID
	INNER JOIN GETUSERVISIBLERECORDTYPES(@USER_ID) u on CMCODECASE.CMCASETYPEID = u.RECORDTYPEID
	WHERE (PLPLANACTIONREF.PLPLANID = @ENTITY_ID)
)