CREATE FUNCTION DBO.LINKEDINSPECTIONFROMPROJECT
(	
	@ENTITY_ID char(36),
	@USER_ID char(36)
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT IMINSPECTIONID from PRPROJECTPERMIT 
	INNER JOIN IMINSPECTION ON PRPROJECTPERMIT.PMPERMITID = IMINSPECTION.LINKID
	INNER JOIN GETUSERVISIBLERECORDTYPES(@USER_ID) u on IMINSPECTION.IMINSPECTIONTYPEID = u.RECORDTYPEID
	where PRPROJECTPERMIT.PRPROJECTID = @ENTITY_ID
	UNION
	SELECT IMINSPECTIONID from PRPROJECTPLAN  
	INNER JOIN IMINSPECTION ON PRPROJECTPLAN.PLPLANID = IMINSPECTION.LINKID
	INNER JOIN GETUSERVISIBLERECORDTYPES(@USER_ID) u on IMINSPECTION.IMINSPECTIONTYPEID = u.RECORDTYPEID
	where PRPROJECTPLAN.PRPROJECTID = @ENTITY_ID
	UNION
	SELECT IMINSPECTIONID from PRPROJECTCODECASE
	INNER JOIN IMINSPECTION ON PRPROJECTCODECASE.CMCODECASEID = IMINSPECTION.LINKID
	INNER JOIN GETUSERVISIBLERECORDTYPES(@USER_ID) u on IMINSPECTION.IMINSPECTIONTYPEID = u.RECORDTYPEID
	where PRPROJECTCODECASE.PRPROJECTID = @ENTITY_ID
	UNION
	SELECT IMINSPECTIONID from PRPROJECTCITIZENREQUEST
	INNER JOIN IMINSPECTION ON PRPROJECTCITIZENREQUEST.CITIZENREQUESTID = IMINSPECTION.LINKID
	INNER JOIN GETUSERVISIBLERECORDTYPES(@USER_ID) u on IMINSPECTION.IMINSPECTIONTYPEID = u.RECORDTYPEID
	where PRPROJECTCITIZENREQUEST.PRPROJECTID = @ENTITY_ID
)