
CREATE FUNCTION [dbo].[PERMIT_HAS_FAILED_INSPECTIONS]
(
	@PMPERMIT_ID CHAR(36)
)
RETURNS BIT
AS
BEGIN
	DECLARE @RESULT AS BIT
	SET @RESULT = 0
	
	IF (EXISTS(SELECT * FROM IMINSPECTION
					INNER JOIN PMPERMIT ON PMPERMIT.PMPERMITID = IMINSPECTION.LINKID
					INNER JOIN IMINSPECTIONSTATUS ON IMINSPECTIONSTATUS.IMINSPECTIONSTATUSID = IMINSPECTION.IMINSPECTIONSTATUSID
					WHERE PMPERMIT.PMPERMITID = @PMPERMIT_ID AND (IMINSPECTIONSTATUS.REINSPECTIONFLAG = 1 OR IMINSPECTIONSTATUS.INVIOLATIONFLAG = 1)))
	BEGIN
		SET @RESULT = 1
	END

	RETURN @RESULT
END

