
CREATE FUNCTION [dbo].[PLAN_HAS_UNPAID_FEES]
(
	@PLPLAN_ID CHAR(36)
)
RETURNS BIT
AS
BEGIN
	DECLARE @RESULT AS BIT
	SET @RESULT = 0
	
	IF (EXISTS(SELECT * FROM PLPLANFEE 
					INNER JOIN CACOMPUTEDFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = PLPLANFEE.CACOMPUTEDFEEID
					WHERE PLPLANFEE.PLPLANID = @PLPLAN_ID AND CACOMPUTEDFEE.CASTATUSID IN (6,7,8)))
	BEGIN
		SET @RESULT = 1
	END

	RETURN @RESULT
END
