
-- exec rpt_TX_SR_Tax_Remittance_Report_Top_Payers_Over_Date_Range '20150101', '20160901'

CREATE PROCEDURE [dbo].[rpt_TX_SR_Tax_Remittance_Report_Top_Payers_Over_Date_Range]
@StartDate AS DATETime,
@EndDate As DATETIME
AS

SET @StartDate=DATEADD(dd,DATEDIFF(dd,0,@STARTDATE),0)
SET @EndDate= DATEADD(S,-1,DATEADD(D,1,@EndDate))

;WITH CTE_PAID_AMT AS (
	SELECT CACOMPUTEDFEE.CAComputedFeeID
	FROM  TXREMITTANCEFEE
	INNER JOIN CACOMPUTEDFEE ON TXREMITTANCEFEE.CACOMPUTEDFEEID = CACOMPUTEDFEE.CACOMPUTEDFEEID
	INNER JOIN CATransactionFee ON CAComputedFee.CAComputedFeeID = CATransactionFee.CaComputedFeeID
	INNER JOIN CATRANSACTION ON CATRANSACTIONFEE.CATRANSACTIONID = CATRANSACTION.CATRANSACTIONID
	INNER JOIN CATRANSACTIONPAYMENT ON CATRANSACTION.CATRANSACTIONID = CATRANSACTIONPAYMENT.CATRANSACTIONID
	INNER JOIN CATRANSACTIONTYPE ON CATRANSACTION.CATRANSACTIONTYPEID = CATRANSACTIONTYPE.CATRANSACTIONTYPEID
	INNER JOIN CATRANSACTIONSTATUS ON CATRANSACTION.CATRANSACTIONSTATUSID = CATRANSACTIONSTATUS.CATRANSACTIONSTATUSID
	WHERE   (NOT (CATRANSACTIONTYPE.NAME IN ('Void Reversal','NSF Reversal')))
	AND     (NOT (CATRANSACTIONSTATUS.NAME IN ('Void','NSF')))
	AND CATRANSACTIONPAYMENT.PAYMENTDATE BETWEEN @StartDate AND @EndDate
	GROUP BY  CAComputedFee.CAComputedFeeID
), 

CTE_AMOUNT AS (
	SELECT	SUM(CaComputedFee.ComputedAmount) AS ComputedAMT, SUM(CaComputedFee.AMOUNTPAIDTODATE) AS PaidAMT, TXREMITTANCETYPE.NAME AS TXACCTTYPE
			,TXA.RemittanceAccountNumber AS REMAccount, GLOBALENTITY.GLOBALENTITYNAME, TXA.TXREMITTANCEACCOUNTID, TXB.PERIODNAME, Tx.AmountReported,
			DISTRICT.NAME AS District, DISTRICT.DISTRICTID,
			TXA.DESCRIPTION AS TX_REMIT_DESCRIPTION,txa.OPENDATE,TXA.CLOSEDATE,TXS.NAME AS TX_REMIT_STATUS
	FROM TxRemittanceAccount TXA
	INNER JOIN TXREMITTANCETYPE ON TXA.TXREMITTANCETYPEID = TXREMITTANCETYPE.TXREMITTANCETYPEID
	INNER JOIN TxRemittance TX ON Tx.TXREMITTANCEACCOUNTID = TXA.TXREMITTANCEACCOUNTID
	INNER JOIN TXREMITSTATUS TXS ON TXA.TXREMITTANCESTATUSID=TXS.TXREMITSTATUSID
	INNER JOIN TXBILLPERIOD TXB ON TX.TXBILLPERIODID = TXB.BILLPERIODID
	INNER JOIN TxRemitStatus ON TXA.TxRemittanceStatusID = TxRemitStatus.TxRemitStatusID and TxRemitStatus.TXREMITSTATUSSYSTEMID <> 2
	INNER JOIN TxRemittanceFee ON Tx.TXREMITTANCEID = TxRemittanceFee.TXREMITTANCEID
	INNER JOIN CAComputedFee ON CAComputedFee.CAComputedFeeID = TxRemittanceFee.CAComputedFeeID
	INNER JOIN CTE_PAID_AMT ON CTE_PAID_AMT.CACOMPUTEDFEEID = CACOMPUTEDFEE.CACOMPUTEDFEEID
	INNER JOIN BLGLOBALENTITYEXTENSION ON TXA.BLGLOBALENTITYEXTENSIONID = BLGLOBALENTITYEXTENSION.BLGLOBALENTITYEXTENSIONID
	INNER JOIN GLOBALENTITY ON GLOBALENTITY.GLOBALENTITYID  = BLGLOBALENTITYEXTENSION.GLOBALENTITYID
	INNER JOIN DISTRICT ON TXA.DISTRICT = DISTRICT.DISTRICTID
	GROUP BY TXA.RemittanceAccountNumber, TXA.TXREMITTANCEACCOUNTID, TXB.PERIODNAME, Tx.AmountReported, TXREMITTANCETYPE.NAME, GLOBALENTITY.GLOBALENTITYNAME, DISTRICT.NAME, DISTRICT.DISTRICTID,
		TXA.DESCRIPTION,TXA.OPENDATE,TXA.CLOSEDATE,TXS.NAME
)

SELECT REMAccount, TXACCTTYPE, PERIODNAME, AmountReported, ComputedAMT, PaidAMT, (ComputedAMT - PaidAMT) AS Balance, GLOBALENTITYNAME, 
PaidAMT/ComputedAMT*100 AS PAID_PERCENT, DISTRICT, DISTRICTID, TX_REMIT_STATUS, TX_REMIT_DESCRIPTION, OPENDATE, CLOSEDATE,
--(SELECT R.[IMAGE] FROM RPTIMAGELIB R
--		WHERE R.IMAGENAME = 'Municipality_Logo') LOGO,
(SELECT CASE WHEN R.[IMAGE] IS NULL THEN 'N' ELSE 'Y' END FROM RPTIMAGELIB R
		WHERE R.IMAGENAME = 'Municipality_Logo') SHOWLOGO,
(SELECT R.REPORTTEXT FROM RPTTEXTLIB R
		WHERE R.TEXTNAME = 'Municipality_Name') Municipality_Name,	   
(SELECT R.REPORTTEXT FROM RPTTEXTLIB R
		WHERE R.TEXTNAME = 'Municipality_Page_Footer') Municipality_Page_Footer
FROM  CTE_AMOUNT

