
CREATE PROCEDURE [dbo].[rpt_TX_SR_Tax_Remittance_Report_Pay_History]

@TXREMITTANCEACCOUNTID AS Varchar (36)
AS
-- exec rpt_TX_SR_Tax_Remittance_Report_Pay_History '037046BD-D7D3-470C-9B36-A500E3F1D595'
SELECT DISTINCT -- tx.txremittanceaccountid,
		Tx.AmountReported, Tx.PaymentDate
       ,TxRemittanceAccount.RemittanceAccountNumber AS REMAccount, COALESCE(NULLIF(GlobalEntity.GLOBALENTITYName,''),'N/A') AS BusinessName, TxRemittanceAccount.TxRemittanceStatusID
       ,TxRemitStatus.TxRemitStatusSystemID, TxRemitStatus.Name AS [Status],CaComputedFee.CACOMPUTEDFEEID
       ,CaComputedFee.ComputedAmount AS CompAmtInComputed, CaComputedFee.AmountPaidToDate As AmtPaidToDateInComputed, CaComputedFee.FeeOrder
       ,TxBillPeriod.StartDate AS StartDate, TxBillPeriod.ENDDATE AS EndDate,TxBillPeriod.DueDate AS DueDate,TxBillPeriod.PERIODNAME
       ,CaTransactionFee.PaidAmount As PaidAmtInTransaction, CaTransactionFee.RefundAmount
       ,CAINVOICE.InvoiceNumber,CaInvoice.INVOICETOTAL AS FeeAmount,CaComputedFee.CAStatusID, CaStatus.Name As InvoiceStatus
       ,GlobalEntity.GlobalEntityID ,cainvoice.INVOICEDATE ,InvoicePay.PAIDAMOUNT,
--(SELECT R.[IMAGE] FROM RPTIMAGELIB R
--		WHERE R.IMAGENAME = 'Municipality_Logo') LOGO,
(SELECT CASE WHEN R.[IMAGE] IS NULL THEN 'N' ELSE 'Y' END FROM RPTIMAGELIB R
		WHERE R.IMAGENAME = 'Municipality_Logo') SHOWLOGO,
(SELECT R.REPORTTEXT FROM RPTTEXTLIB R
		WHERE R.TEXTNAME = 'Municipality_Name') Municipality_Name,	   
(SELECT R.REPORTTEXT FROM RPTTEXTLIB R
		WHERE R.TEXTNAME = 'Municipality_Page_Footer') Municipality_Page_Footer

FROM   TXREMITTANCE Tx
INNER JOIN TxRemittanceAccount ON Tx.TXREMITTANCEACCOUNTID = TxRemittanceAccount.TXREMITTANCEACCOUNTID
INNER JOIN TXBILLPERIOD On Tx.TXBILLPERIODID = TxBillPeriod.BillPeriodID
INNER JOIN TxRemitStatus ON TxRemittanceAccount.TxRemittanceStatusID = TxRemitStatus.TxRemitStatusID
LEFT OUTER JOIN TxRemittanceFee ON Tx.TXREMITTANCEID = TxRemittanceFee.TXREMITTANCEID
LEFT OUTER JOIN CAComputedFee ON CAComputedFee.CAComputedFeeID = TxRemittanceFee.CAComputedFeeID
LEFT OUTER JOIN CAFeeTemplateFee ON CAComputedFee.CAFeeTemplateFeeID = CAFeeTemplateFee.CAFeeTemplateFeeID
LEFT OUTER JOIN CATransactionFee ON CAComputedFee.CAComputedFeeID = CATransactionFee.CaComputedFeeID
LEFT OUTER JOIN CATRANSACTION ON CATRANSACTIONFEE.CATRANSACTIONID = CATRANSACTION.CATRANSACTIONID
INNER JOIN BLGLOBALENTITYEXTENSION ON TXREMITTANCEACCOUNT.BLGLOBALENTITYEXTENSIONID = BLGLOBALENTITYEXTENSION.BLGLOBALENTITYEXTENSIONID
INNER JOIN GLOBALENTITY ON GLOBALENTITY.GLOBALENTITYID  = BLGLOBALENTITYEXTENSION.GLOBALENTITYID
LEFT OUTER JOIN GLOBALENTITYACCOUNTENTITY ON GLOBALENTITY.GLOBALENTITYID = GLOBALENTITYACCOUNTENTITY.GLOBALENTITYID
LEFT JOIN GLOBALENTITYACCOUNT ON GLOBALENTITYACCOUNT.GLOBALENTITYACCOUNTID =GLOBALENTITYACCOUNTENTITY.GLOBALENTITYACCOUNTID 
LEFT OUTER JOIN CATRANSACTIONINVOICE ON CATRANSACTION.CATRANSACTIONID = CATRANSACTIONINVOICE.CATRANSACTIONID -- CATRANSACTIONINVOICE is a link (VERY IMPORTANT)
INNER JOIN CAInvoiceFee ON CAComputedFee.CAComputedFeeID = CAInvoiceFee.CAComputedFeeID
LEFT OUTER JOIN CAINVOICE ON   CAInvoiceFee.CAInvoiceID = CAInvoice.CAInvoiceID 
LEFT OUTER JOIN CAStatus ON CAINVOICE.CASTATUSID = CASTATUS.CASTATUSID  
INNER JOIN CATRANSACTIONPAYMENT ON CATRANSACTION.CATRANSACTIONID = CATRANSACTIONPAYMENT.CATRANSACTIONID
INNER JOIN CATRANSACTIONTYPE ON CATRANSACTION.CATRANSACTIONTYPEID = CATRANSACTIONTYPE.CATRANSACTIONTYPEID 
INNER JOIN(SELECT sum(CATRANSACTIONFEE.Paidamount - CATRANSACTIONFEE.REFUNDAMOUNT) PaidAmount, CAINVOICE.INVOICENUMBER
                FROM   CACOMPUTEDFEE 
                INNER JOIN   CAINVOICEFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CAINVOICEFEE.CACOMPUTEDFEEID 
                INNER JOIN   CAINVOICE ON CAINVOICEFEE.CAINVOICEID = CAINVOICE.CAINVOICEID 
				INNER JOIN   CATRANSACTIONFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CATRANSACTIONFEE.CACOMPUTEDFEEID 
				INNER JOIN   CATRANSACTION ON CATRANSACTIONFEE.CATRANSACTIONID = CATRANSACTION.CATRANSACTIONID 
				INNER JOIN   CATRANSACTIONTYPE ON CATRANSACTION.CATRANSACTIONTYPEID = CATRANSACTIONTYPE.CATRANSACTIONTYPEID 
				INNER JOIN   CATRANSACTIONSTATUS ON CATRANSACTION.CATRANSACTIONSTATUSID = CATRANSACTIONSTATUS.CATRANSACTIONSTATUSID 
				WHERE     (NOT (CATRANSACTIONTYPE.NAME IN ('Void Reversal'))) 
				AND       (NOT (CATRANSACTIONSTATUS.NAME IN ('Void')))
				AND       (CAInvoice.CAStatusID <> 5)
				GROUP BY CAINVOICE.INVOICENUMBER
                 )InvoicePay ON CAINVOICE.INVOICENUMBER = InvoicePay.INVOICENUMBER

WHERE TxRemitStatus.TxRemitStatusSystemID <> 2 
AND Tx.TXREMITTANCEACCOUNTID = @TXREMITTANCEACCOUNTID

