CREATE PROCEDURE [dbo].[USP_TASK_UPDATE]
(
	@TASKID CHAR(36),
	@SUBJECT NVARCHAR(200),
	@TASKTEXT NVARCHAR(MAX),
	@STARTDATE DATETIME,
	@DUEDATE DATETIME,
	@TASKSTATUSID INT,
	@TASKPRIORITYID INT,
	@PERCENTCOMPLETE INT,
	@CREATEDBYID CHAR(36),
	@CREATEDON DATETIME,
	@FORMID CHAR(36),
	@UNIQUERECORDID CHAR(36),
	@SHOWONCALENDAR BIT,
	@TASKTYPEID CHAR(36),
	@COMPLETEDDATE DATETIME,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
UPDATE [dbo].[TASK] SET
	[SUBJECT] = @SUBJECT,
	[TASKTEXT] = @TASKTEXT,
	[STARTDATE] = @STARTDATE,
	[DUEDATE] = @DUEDATE,
	[TASKSTATUSID] = @TASKSTATUSID,
	[TASKPRIORITYID] = @TASKPRIORITYID,
	[PERCENTCOMPLETE] = @PERCENTCOMPLETE,
	[CREATEDBYID] = @CREATEDBYID,
	[CREATEDON] = @CREATEDON,
	[FORMID] = @FORMID,
	[UNIQUERECORDID] = @UNIQUERECORDID,
	[SHOWONCALENDAR] = @SHOWONCALENDAR,
	[TASKTYPEID] = @TASKTYPEID,
	[COMPLETEDDATE] = @COMPLETEDDATE,
	[LASTCHANGEDBY] = @LASTCHANGEDBY,
	[LASTCHANGEDON] = @LASTCHANGEDON,
	[ROWVERSION] = @ROWVERSION + 1
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE
	[TASKID] = @TASKID AND 
	[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE