CREATE PROCEDURE [dbo].[USP_TXREMITTANCETYPE_UPDATE]
(
	@TXREMITTANCETYPEID CHAR(36),
	@NAME NVARCHAR(50),
	@DESCRIPTION NVARCHAR(250),
	@ACTIVE BIT,
	@DEFAULTSTATUSID CHAR(36),
	@PREFIX NVARCHAR(20),
	@MULTIPLIERRATE DECIMAL(18,0),
	@CAFEETEMPLATEID CHAR(36),
	@CUSTOMFIELDLAYOUTID CHAR(36),
	@ONLINECUSTOMFIELDLAYOUTID CHAR(36),
	@INTERNETFLAG BIT,
	@INTERNETAPPLYTYPE INT,
	@DEFAULTGENERATEDATE DATETIME,
	@FRIENDLYNAME NVARCHAR(50),
	@ENABLEEXEMPTIONS BIT,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
UPDATE [dbo].[TXREMITTANCETYPE] SET
	[NAME] = @NAME,
	[DESCRIPTION] = @DESCRIPTION,
	[ACTIVE] = @ACTIVE,
	[DEFAULTSTATUSID] = @DEFAULTSTATUSID,
	[PREFIX] = @PREFIX,
	[MULTIPLIERRATE] = @MULTIPLIERRATE,
	[CAFEETEMPLATEID] = @CAFEETEMPLATEID,
	[CUSTOMFIELDLAYOUTID] = @CUSTOMFIELDLAYOUTID,
	[ONLINECUSTOMFIELDLAYOUTID] = @ONLINECUSTOMFIELDLAYOUTID,
	[INTERNETFLAG] = @INTERNETFLAG,
	[INTERNETAPPLYTYPE] = @INTERNETAPPLYTYPE,
	[DEFAULTGENERATEDATE] = @DEFAULTGENERATEDATE,
	[FRIENDLYNAME] = @FRIENDLYNAME,
	[ENABLEEXEMPTIONS] = @ENABLEEXEMPTIONS,
	[LASTCHANGEDBY] = @LASTCHANGEDBY,
	[LASTCHANGEDON] = @LASTCHANGEDON,
	[ROWVERSION] = @ROWVERSION + 1
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE
	[TXREMITTANCETYPEID] = @TXREMITTANCETYPEID AND 
	[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE