CREATE PROCEDURE [dbo].[USP_TRANSACTIONEVENTQUEUE_UPDATE]
(
	@TRANSACTIONEVENTQUEUEID AS BIGINT,
	@EVENTSTATUSID INT
)
AS  
BEGIN  
	SET NOCOUNT ON;
	UPDATE [dbo].[TRANSACTIONEVENTQUEUE]
	SET 
		PROCESSEDDATE = GETDATE(),
		EVENTSTATUSID = @EVENTSTATUSID
	WHERE [dbo].[TRANSACTIONEVENTQUEUE].[TRANSACTIONEVENTQUEUEID] = @TRANSACTIONEVENTQUEUEID
END