CREATE PROCEDURE [dbo].[USP_TASKTYPE_UPDATE]
(
	@TASKTYPEID CHAR(36),
	@NAME NVARCHAR(50),
	@DESCRIPTION NVARCHAR(MAX),
	@ACTIVE BIT,
	@ISDEFAULT BIT,
	@ISGLOBAL BIT,
	@DAYSUNTILDUE INT,
	@TASKTEXT NVARCHAR(MAX),
	@DEFAULTSUBJECT NVARCHAR(200),
	@TASKSTATUSID INT,
	@TASKPRIORITYID INT,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
UPDATE [dbo].[TASKTYPE] SET
	[NAME] = @NAME,
	[DESCRIPTION] = @DESCRIPTION,
	[ACTIVE] = @ACTIVE,
	[ISDEFAULT] = @ISDEFAULT,
	[ISGLOBAL] = @ISGLOBAL,
	[DAYSUNTILDUE] = @DAYSUNTILDUE,
	[TASKTEXT] = @TASKTEXT,
	[DEFAULTSUBJECT] = @DEFAULTSUBJECT,
	[TASKSTATUSID] = @TASKSTATUSID,
	[TASKPRIORITYID] = @TASKPRIORITYID,
	[LASTCHANGEDBY] = @LASTCHANGEDBY,
	[LASTCHANGEDON] = @LASTCHANGEDON,
	[ROWVERSION] = @ROWVERSION + 1
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE
	[TASKTYPEID] = @TASKTYPEID AND 
	[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE