CREATE PROCEDURE [taxremittanceaccount].[USP_TAXREMITTANCEHISTORY_GETRECENT]
(
	@TXREMITTANCEACCOUNTID AS CHAR(36)
)
AS

SELECT  TOP 5 
	[TXBILLPERIOD].[PERIODNAME], 
	CASE
		WHEN [TXREMITTANCE].[REPORTEDDATE] IS NOT NULL
		THEN CAST(0 AS BIT)
		ELSE CAST(1 AS BIT) 
	END AS [OPEN],
	[TXREMITTANCE].[AMOUNTREPORTED] AS AMOUNT
FROM [dbo].[TXREMITTANCE] 
INNER JOIN [dbo].[TXBILLPERIOD] 
	ON [TXREMITTANCE].TXBILLPERIODID = [TXBILLPERIOD].BILLPERIODID
WHERE [TXREMITTANCE].TXREMITTANCEACCOUNTID = @TXREMITTANCEACCOUNTID
ORDER BY [TXBILLPERIOD].[DUEDATE] DESC