CREATE PROCEDURE [taxremittanceaccount].[USP_UPDATERECENTCASESINFO]
(
	@RECENTCASEID NVARCHAR(36),
	@FORMID NVARCHAR(36),
	@CASEID NVARCHAR(36),
	@ACTIVETIME DateTime,
	@USERID NVARCHAR(36)
)
AS
BEGIN
DECLARE @CASENUMBER NVARCHAR(200)
	IF(LEN(ISNULL(@USERID,''))>0 AND LEN(ISNULL(@CASEID,''))>0)
	BEGIN
		IF(EXISTS(SELECT * FROM [dbo].[RECENTCASE] WHERE [USERID]=@USERID AND [RECORDID]=@CASEID))
		BEGIN
			UPDATE [dbo].[RECENTCASE]
			SET [ACTIVETIME]=ISNULL(@ACTIVETIME,GETDATE())
			WHERE [USERID]=@USERID AND [RECORDID]=@CASEID
		END
		ELSE BEGIN
				
				SELECT @CASENUMBER= REMITTANCEACCOUNTNUMBER FROM [dbo].[TXREMITTANCEACCOUNT]
				WHERE [TXREMITTANCEACCOUNTID]=@CASEID
					
				DELETE FROM [dbo].[RECENTCASE]
				WHERE [RECENTCASEID] NOT IN ( SELECT TOP ( 9 )
											[RECENTCASEID]
											FROM [dbo].[RECENTCASE]
											WHERE [USERID]=@USERID 
											ORDER BY [ACTIVETIME] DESC )
				AND [USERID]=@USERID

				INSERT INTO [dbo].[RECENTCASE]
				VALUES(@RECENTCASEID,@FORMID,@CASEID,ISNULL(@ACTIVETIME,GETDATE()),@USERID,@CASENUMBER)

				SELECT @RECENTCASEID RecentCaseId, @FORMID FormId, @CASEID CaseId, @ACTIVETIME ActiveTime, @USERID UserId
		END
	END
END