CREATE TABLE [dbo].[MAILMERGETEMPLATEUSERTYPE] (
    [MAILMERGETEMPLATEUSERTYPEID] INT           NOT NULL,
    [USERTYPENAME]                NVARCHAR (10) NULL,
    CONSTRAINT [PK_MailMergeTemplateUserType] PRIMARY KEY CLUSTERED ([MAILMERGETEMPLATEUSERTYPEID] ASC) WITH (FILLFACTOR = 90)
);

