CREATE TABLE [dbo].[MAPREQUEST] (
    [ID]             CHAR (36)      NOT NULL,
    [REQUESTID]      CHAR (36)      NOT NULL,
    [LOCATIONOBJECT] NVARCHAR (MAX) NOT NULL,
    [LOCATIONTYPE]   INT            NOT NULL,
    [REQUESTDATE]    DATETIME       NOT NULL,
    CONSTRAINT [PK_MAPREQUEST] PRIMARY KEY NONCLUSTERED ([ID] ASC)
);


GO
CREATE CLUSTERED INDEX [IX_MAPREQUEST_ALL]
    ON [dbo].[MAPREQUEST]([REQUESTID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_MAPREQUEST_REQUESTDATE]
    ON [dbo].[MAPREQUEST]([REQUESTDATE] ASC);

