CREATE TABLE [dbo].[MERGECONTACTMISSINGFKEYS] (
    [MERGECONTACTMISSINGFKEYSID] CHAR (36)    NULL,
    [FKEYTABLE]                  VARCHAR (50) NULL,
    [FKEYCOLUMN]                 VARCHAR (50) NULL,
    [REFERENCECOLUMN]            VARCHAR (50) NULL
);

