CREATE TABLE [dbo].[METADATACLASS] (
    [ID]           CHAR (36)      NOT NULL,
    [NAME]         VARCHAR (500)  NOT NULL,
    [TYPEFULLNAME] VARCHAR (500)  NOT NULL,
    [FRIENDLYNAME] NVARCHAR (250) NULL,
    [MODULEID]     INT            NULL,
    CONSTRAINT [PK_METADATACLASS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_METADATACLASS_MODULEID] FOREIGN KEY ([MODULEID]) REFERENCES [dbo].[SYSTEMMODULE] ([SYSTEMMODULEID])
);


GO
CREATE NONCLUSTERED INDEX [IX_UNIQUE_METADATACLASS_FULLNAME]
    ON [dbo].[METADATACLASS]([TYPEFULLNAME] ASC);

