CREATE TABLE [dbo].[MOBILEGOVATTACHMENTUPLOAD] (
    [ATTACHMENTID] CHAR (36)      NOT NULL,
    [INSPECTIONID] CHAR (36)      NOT NULL,
    [FILEPATH]     NVARCHAR (500) NULL,
    [FILENAME]     NVARCHAR (500) NULL,
    [UPLOADED]     BIT            DEFAULT ((0)) NULL,
    CONSTRAINT [PK_MobileGovAttachmentUpload] PRIMARY KEY CLUSTERED ([ATTACHMENTID] ASC) WITH (FILLFACTOR = 90)
);

