CREATE TABLE [dbo].[MOBILEGOVVIOLATIONUPDATES] (
    [VIOLATIONID]      CHAR (36)      NOT NULL,
    [STATUSID]         CHAR (36)      NOT NULL,
    [CORRECTIVEACTION] NVARCHAR (MAX) NULL,
    [NEWNOTES]         NVARCHAR (MAX) NOT NULL,
    [UPDATESENT]       BIT            DEFAULT ((0)) NULL,
    [UPDATETIME]       DATETIME       DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_MobileGovViolationUpdates] PRIMARY KEY CLUSTERED ([VIOLATIONID] ASC, [UPDATETIME] DESC) WITH (FILLFACTOR = 90)
);

