CREATE TABLE [dbo].[MODULERECORDTYPE] (
    [MODULERECORDTYPEID] INT            NOT NULL,
    [NAME]               NVARCHAR (100) NOT NULL,
    CONSTRAINT [PK_MODULERECORDTYPE] PRIMARY KEY CLUSTERED ([MODULERECORDTYPEID] ASC) WITH (FILLFACTOR = 90)
);

