CREATE FUNCTION [reviewcoordinator].[UFN_GET_BALANCE_DUE]
(
	@ENTITYID CHAR(36)
)
RETURNS MONEY
AS
BEGIN
DECLARE @statusdeleted INT = 10
DECLARE @statusVoid INT = 5

DECLARE @balanceDue MONEY = 0

;WITH RAW_DATA AS (
	SELECT SUM(CACOMPUTEDFEE.COMPUTEDAMOUNT - CACOMPUTEDFEE.AMOUNTPAIDTODATE) BALANCEDUE
	FROM PMPERMITFEE
	INNER JOIN CACOMPUTEDFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = PMPERMITFEE.CACOMPUTEDFEEID
	WHERE PMPERMITFEE.PMPERMITID = @ENTITYID AND
	CACOMPUTEDFEE.CASTATUSID != @STATUSDELETED AND CACOMPUTEDFEE.CASTATUSID != @STATUSVOID
	UNION ALL
	SELECT SUM(CACOMPUTEDFEE.COMPUTEDAMOUNT - CACOMPUTEDFEE.AMOUNTPAIDTODATE) BALANCEDUE
	FROM PLPLANFEE
	INNER JOIN CACOMPUTEDFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = PLPLANFEE.CACOMPUTEDFEEID
	WHERE PLPLANFEE.PLPLANID = @ENTITYID AND
	CACOMPUTEDFEE.CASTATUSID != @STATUSDELETED AND CACOMPUTEDFEE.CASTATUSID != @STATUSVOID
) SELECT @balanceDue = SUM(BALANCEDUE) FROM RAW_DATA

RETURN @balanceDue
END