CREATE TABLE [dbo].[PARCELORIGIN] (
    [PARCELORIGINID]    CHAR (36) NOT NULL,
    [PARCELID]          CHAR (36) NOT NULL,
    [PARCELSPLITCASEID] CHAR (36) NOT NULL,
    [PROCESSED]         BIT       CONSTRAINT [DF_ParcelOrigin_Processed] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_ParcelOrigin] PRIMARY KEY CLUSTERED ([PARCELORIGINID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_ParcelOrigin_Parcel] FOREIGN KEY ([PARCELID]) REFERENCES [dbo].[PARCEL] ([PARCELID])
);

