CREATE TABLE [dbo].[PLANEVENTTYPE] (
    [PLANEVENTTYPEID] INT            NOT NULL,
    [NAME]            NVARCHAR (50)  NOT NULL,
    [DESCRIPTION]     NVARCHAR (MAX) NULL,
    [ACTIVE]          BIT            DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_PLANEVENTTYPE] PRIMARY KEY CLUSTERED ([PLANEVENTTYPEID] ASC)
);

