CREATE TABLE [dbo].[PLANEVENTQUEUE] (
    [PLANEVENTQUEUEID]  BIGINT        IDENTITY (1, 1) NOT NULL,
    [PLPLANID]          CHAR (36)     NOT NULL,
    [PLANNUMBER]        NVARCHAR (50) NOT NULL,
    [PLANEVENTTYPEID]   INT           NOT NULL,
    [EVENTSTATUSID]     INT           NOT NULL,
    [CREATEDDATE]       DATETIME      NOT NULL,
    [PROCESSEDDATE]     DATETIME      NULL,
    [PLANLASTCHANGEDBY] CHAR (36)     NULL,
    CONSTRAINT [PK_PLANEVENTQUEUE] PRIMARY KEY CLUSTERED ([PLANEVENTQUEUEID] ASC),
    CONSTRAINT [FK_PlanEventQueue_EventStatus] FOREIGN KEY ([EVENTSTATUSID]) REFERENCES [dbo].[EVENTSTATUS] ([EVENTSTATUSID]),
    CONSTRAINT [FK_PlanEventQueue_PlanEventType] FOREIGN KEY ([PLANEVENTTYPEID]) REFERENCES [dbo].[PLANEVENTTYPE] ([PLANEVENTTYPEID]),
    CONSTRAINT [FK_PlanEventQueue_Users] FOREIGN KEY ([PLANLASTCHANGEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);


GO
CREATE NONCLUSTERED INDEX [PLANEVENTQUEUE_PROCESSEDDATE]
    ON [dbo].[PLANEVENTQUEUE]([PROCESSEDDATE] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PLANEVENTQUEUE_CREATEDDATE]
    ON [dbo].[PLANEVENTQUEUE]([CREATEDDATE] ASC);

