CREATE TABLE [dbo].[PLAPPLICATIONNOTE] (
    [PLAPPLICATIONNOTEID] CHAR (36)      NOT NULL,
    [PLAPPLICATIONID]     CHAR (36)      NOT NULL,
    [TEXT]                NVARCHAR (MAX) NULL,
    [CREATEDBY]           CHAR (36)      NOT NULL,
    [CREATEDDATE]         DATETIME       NULL,
    [TITLE]               VARCHAR (50)   CONSTRAINT [DF_PLAPPLICATIONNOTE_TITLE] DEFAULT ('') NULL,
    [PIN]                 BIT            CONSTRAINT [DF_PLAPPLICATIONNOTE_PIN] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_PLApplicationNote] PRIMARY KEY CLUSTERED ([PLAPPLICATIONNOTEID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PLApplicationNote_PLApplication] FOREIGN KEY ([PLAPPLICATIONID]) REFERENCES [dbo].[PLAPPLICATION] ([PLAPPLICATIONID]),
    CONSTRAINT [FK_PLApplicationNote_Users] FOREIGN KEY ([CREATEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PLAPPLICATIONNOTE_PLAPPLICATIONID]
    ON [dbo].[PLAPPLICATIONNOTE]([PLAPPLICATIONID] ASC);

