CREATE TABLE [dbo].[PLAPPLICATIONTYPE] (
    [PLAPPLICATIONTYPEID]        CHAR (36)      NOT NULL,
    [APPLICATIONTYPENAME]        NVARCHAR (255) NOT NULL,
    [DESCRIPTION]                NVARCHAR (MAX) NULL,
    [CUSTOMFIELDID]              CHAR (36)      NULL,
    [DEFAULTAPPLICATIONSTATUSID] CHAR (36)      NULL,
    [PREFIX]                     NVARCHAR (10)  NULL,
    [ISAUTONUMBER]               BIT            CONSTRAINT [DF_PLApplicationType_IsAutoNumber] DEFAULT ((0)) NOT NULL,
    [DEFAULTPERMITTYPE]          CHAR (36)      NULL,
    [DEFAULTPLANTYPE]            CHAR (36)      NULL,
    [CAFEETEMPLATEID]            CHAR (36)      NULL,
    [LASTCHANGEDBY]              CHAR (36)      NULL,
    [LASTCHANGEDON]              DATETIME       CONSTRAINT [DF_PLApplicationType_LastChangedOn] DEFAULT (getutcdate()) NOT NULL,
    [ROWVERSION]                 INT            CONSTRAINT [DF_PLApplicationType_RowVersion] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_PLApplicationType] PRIMARY KEY CLUSTERED ([PLAPPLICATIONTYPEID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_AppType_PermitType] FOREIGN KEY ([DEFAULTPERMITTYPE]) REFERENCES [dbo].[PMPERMITTYPE] ([PMPERMITTYPEID]),
    CONSTRAINT [FK_AppType_PlanType] FOREIGN KEY ([DEFAULTPLANTYPE]) REFERENCES [dbo].[PLPLANTYPE] ([PLPLANTYPEID]),
    CONSTRAINT [FK_PLApplicationType_CustomFieldLayout] FOREIGN KEY ([CUSTOMFIELDID]) REFERENCES [dbo].[CUSTOMFIELDLAYOUT] ([GCUSTOMFIELDLAYOUTS]),
    CONSTRAINT [FK_PLApplicationType_PLApplicationStatus] FOREIGN KEY ([DEFAULTAPPLICATIONSTATUSID]) REFERENCES [dbo].[PLAPPLICATIONSTATUS] ([PLAPPLICATIONSTATUSID]),
    CONSTRAINT [FK_PLAPPLICATIONTYPES_USERS] FOREIGN KEY ([LASTCHANGEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID]),
    CONSTRAINT [FK_PLAppType_FeeTemplate] FOREIGN KEY ([CAFEETEMPLATEID]) REFERENCES [dbo].[CAFEETEMPLATE] ([CAFEETEMPLATEID])
);


GO

CREATE TRIGGER [TG_PLAPPLICATIONTYPE_DELETE] ON PLAPPLICATIONTYPE
   AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [HISTORYSYSTEMSETUP]
    (	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )

	SELECT
			[deleted].[PLAPPLICATIONTYPEID],
			[deleted].[ROWVERSION],
			GETUTCDATE(),
			(SELECT dbo.UFN_GET_USERID_FROM_CONTEXT_INFO()),
			'Application Type Deleted',
			'',
			'',
			'Application Type (' + [deleted].[APPLICATIONTYPENAME] + ')',
			'0C9FECFF-F1B4-4A19-A89B-F7B414BC8D46',
			3,
			1,
			[deleted].[APPLICATIONTYPENAME]
	FROM	[deleted]
END
GO

CREATE TRIGGER [TG_PLAPPLICATIONTYPE_INSERT] ON PLAPPLICATIONTYPE
   FOR INSERT
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [HISTORYSYSTEMSETUP]
    (	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )

	SELECT
			[inserted].[PLAPPLICATIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Application Type Added',
			'',
			'',
			'Application Type (' + [inserted].[APPLICATIONTYPENAME] + ')',
			'0C9FECFF-F1B4-4A19-A89B-F7B414BC8D46',
			1,
			1,
			[inserted].[APPLICATIONTYPENAME]
	FROM	[inserted]	
END
GO

CREATE TRIGGER [TG_PLAPPLICATIONTYPE_UPDATE] ON PLAPPLICATIONTYPE
   AFTER UPDATE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [HISTORYSYSTEMSETUP]
    (	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )

	SELECT
			[inserted].[PLAPPLICATIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Name',
			[deleted].[APPLICATIONTYPENAME],
			[inserted].[APPLICATIONTYPENAME],
			'Application Type (' + [inserted].[APPLICATIONTYPENAME] + ')',
			'0C9FECFF-F1B4-4A19-A89B-F7B414BC8D46',
			2,
			1,
			[inserted].[APPLICATIONTYPENAME]
	FROM	[deleted]
	INNER JOIN [inserted] ON [deleted].PLAPPLICATIONTYPEID = [inserted].PLAPPLICATIONTYPEID
	WHERE	[deleted].[APPLICATIONTYPENAME] <> [inserted].[APPLICATIONTYPENAME]
	UNION ALL
	SELECT
			[inserted].[PLAPPLICATIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Description',
			ISNULL([deleted].[DESCRIPTION],'[none]'),
			ISNULL([inserted].[DESCRIPTION],'[none]'),
			'Application Type (' + [inserted].[APPLICATIONTYPENAME] + ')',
			'0C9FECFF-F1B4-4A19-A89B-F7B414BC8D46',
			2,
			1,
			[inserted].[APPLICATIONTYPENAME]
	FROM	[deleted]
	INNER JOIN [inserted] ON [deleted].PLAPPLICATIONTYPEID = [inserted].PLAPPLICATIONTYPEID
	WHERE	ISNULL([deleted].[DESCRIPTION], '') <> ISNULL([inserted].[DESCRIPTION], '')
	UNION ALL
	SELECT
			[inserted].[PLAPPLICATIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Custom Field Layout',
			ISNULL([DELETED_LAYOUT].[SNAME],'[none]'),
			ISNULL([INSERTED_LAYOUT].[SNAME],'[none]'),
			'Application Type (' + [inserted].[APPLICATIONTYPENAME] + ')',
			'0C9FECFF-F1B4-4A19-A89B-F7B414BC8D46',
			2,
			1,
			[inserted].[APPLICATIONTYPENAME]
	FROM	[deleted]
	INNER JOIN [inserted] ON [deleted].PLAPPLICATIONTYPEID = [inserted].PLAPPLICATIONTYPEID
	LEFT OUTER JOIN CUSTOMFIELDLAYOUT INSERTED_LAYOUT WITH (NOLOCK) ON INSERTED_LAYOUT.GCUSTOMFIELDLAYOUTS = [inserted].CUSTOMFIELDID
	LEFT OUTER JOIN CUSTOMFIELDLAYOUT DELETED_LAYOUT WITH (NOLOCK) ON DELETED_LAYOUT.GCUSTOMFIELDLAYOUTS = [deleted].CUSTOMFIELDID
	WHERE	ISNULL([inserted].[CUSTOMFIELDID],'') <> ISNULL([deleted].[CUSTOMFIELDID],'')
	UNION ALL
	SELECT
			[inserted].[PLAPPLICATIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Default Status',
			ISNULL([DELETED_STATUS].[STATUS],'[none]'),
			ISNULL([INSERTED_STATUS].[STATUS],'[none]'),
			'Application Type (' + [inserted].[APPLICATIONTYPENAME] + ')',
			'0C9FECFF-F1B4-4A19-A89B-F7B414BC8D46',
			2,
			1,
			[inserted].[APPLICATIONTYPENAME]
	FROM	[deleted]
	INNER JOIN [inserted] ON [deleted].PLAPPLICATIONTYPEID = [inserted].PLAPPLICATIONTYPEID
	LEFT OUTER JOIN PLAPPLICATIONSTATUS INSERTED_STATUS WITH (NOLOCK) ON INSERTED_STATUS.PLAPPLICATIONSTATUSID = [inserted].DEFAULTAPPLICATIONSTATUSID
	LEFT OUTER JOIN PLAPPLICATIONSTATUS DELETED_STATUS WITH (NOLOCK) ON DELETED_STATUS.PLAPPLICATIONSTATUSID = [deleted].DEFAULTAPPLICATIONSTATUSID
	WHERE	ISNULL([inserted].[DEFAULTAPPLICATIONSTATUSID],'') <> ISNULL([deleted].[DEFAULTAPPLICATIONSTATUSID],'')	
	UNION ALL
	SELECT
			[inserted].[PLAPPLICATIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Prefix',
			ISNULL([deleted].[PREFIX],'[none]'),
			ISNULL([inserted].[PREFIX],'[none]'),
			'Application Type (' + [inserted].[APPLICATIONTYPENAME] + ')',
			'0C9FECFF-F1B4-4A19-A89B-F7B414BC8D46',
			2,
			1,
			[inserted].[APPLICATIONTYPENAME]
	FROM	[deleted]
	INNER JOIN [inserted] ON [deleted].PLAPPLICATIONTYPEID = [inserted].PLAPPLICATIONTYPEID
	WHERE	ISNULL([deleted].[PREFIX], '') <> ISNULL([inserted].[PREFIX], '')
	UNION ALL
	SELECT
			[inserted].[PLAPPLICATIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Auto Create Application ID Flag',
			CASE WHEN [deleted].[ISAUTONUMBER] = 1 THEN 'Yes' ELSE 'No' END,
			CASE WHEN [inserted].[ISAUTONUMBER] = 1 THEN 'Yes' ELSE 'No' END,
			'Application Type (' + [inserted].[APPLICATIONTYPENAME] + ')',
			'0C9FECFF-F1B4-4A19-A89B-F7B414BC8D46',
			2,
			1,
			[inserted].[APPLICATIONTYPENAME]
	FROM	[deleted]
	INNER JOIN [inserted] ON [deleted].PLAPPLICATIONTYPEID = [inserted].PLAPPLICATIONTYPEID
	WHERE	[deleted].[ISAUTONUMBER] <> [inserted].[ISAUTONUMBER]
	UNION ALL
	SELECT
			[inserted].[PLAPPLICATIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Default Permit Type',
			ISNULL([DELETED_PMPERMITTYPE].[NAME],'[none]'),
			ISNULL([INSERTED_PMPERMITTYPE].[NAME],'[none]'),
			'Application Type (' + [inserted].[APPLICATIONTYPENAME] + ')',
			'0C9FECFF-F1B4-4A19-A89B-F7B414BC8D46',
			2,
			1,
			[inserted].[APPLICATIONTYPENAME]
	FROM	[deleted]
	INNER JOIN [inserted] ON [deleted].PLAPPLICATIONTYPEID = [inserted].PLAPPLICATIONTYPEID
	LEFT OUTER JOIN PMPERMITTYPE INSERTED_PMPERMITTYPE WITH (NOLOCK) ON INSERTED_PMPERMITTYPE.PMPERMITTYPEID = [inserted].[DEFAULTPERMITTYPE]
	LEFT OUTER JOIN PMPERMITTYPE DELETED_PMPERMITTYPE WITH (NOLOCK) ON DELETED_PMPERMITTYPE.PMPERMITTYPEID = [deleted].[DEFAULTPERMITTYPE]
	WHERE	ISNULL([inserted].[DEFAULTPERMITTYPE],'') <> ISNULL([deleted].[DEFAULTPERMITTYPE],'')	
	UNION ALL
	SELECT
			[inserted].[PLAPPLICATIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Default Plan Type',
			ISNULL([DELETED_PLPLANTYPE].[PLANNAME],'[none]'),
			ISNULL([INSERTED_PLPLANTYPE].[PLANNAME],'[none]'),
			'Application Type (' + [inserted].[APPLICATIONTYPENAME] + ')',
			'0C9FECFF-F1B4-4A19-A89B-F7B414BC8D46',
			2,
			1,
			[inserted].[APPLICATIONTYPENAME]
	FROM	[deleted]
	INNER JOIN [inserted] ON [deleted].PLAPPLICATIONTYPEID = [inserted].PLAPPLICATIONTYPEID
	LEFT OUTER JOIN PLPLANTYPE INSERTED_PLPLANTYPE WITH (NOLOCK) ON INSERTED_PLPLANTYPE.PLPLANTYPEID = [inserted].[DEFAULTPLANTYPE]
	LEFT OUTER JOIN PLPLANTYPE DELETED_PLPLANTYPE WITH (NOLOCK) ON DELETED_PLPLANTYPE.PLPLANTYPEID = [deleted].[DEFAULTPLANTYPE]
	WHERE	ISNULL([inserted].[DEFAULTPLANTYPE],'') <> ISNULL([deleted].[DEFAULTPLANTYPE],'')		
	UNION ALL
	SELECT
			[inserted].[PLAPPLICATIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Fee Template',
			ISNULL([DELETED_CAFEETEMPLATE].[CAFEETEMPLATENAME],'[none]'),
			ISNULL([INSERTED_CAFEETEMPLATE].[CAFEETEMPLATENAME],'[none]'),
			'Application Type (' + [inserted].[APPLICATIONTYPENAME] + ')',
			'0C9FECFF-F1B4-4A19-A89B-F7B414BC8D46',
			2,
			1,
			[inserted].[APPLICATIONTYPENAME]
	FROM	[deleted]
	INNER JOIN [inserted] ON [deleted].PLAPPLICATIONTYPEID = [inserted].PLAPPLICATIONTYPEID
	LEFT OUTER JOIN CAFEETEMPLATE INSERTED_CAFEETEMPLATE WITH (NOLOCK) ON INSERTED_CAFEETEMPLATE.CAFEETEMPLATEID = [inserted].CAFEETEMPLATEID
	LEFT OUTER JOIN CAFEETEMPLATE DELETED_CAFEETEMPLATE WITH (NOLOCK) ON DELETED_CAFEETEMPLATE.CAFEETEMPLATEID = [deleted].CAFEETEMPLATEID
	WHERE	ISNULL([inserted].[CAFEETEMPLATEID],'') <> ISNULL([deleted].[CAFEETEMPLATEID],'')	
END