CREATE TABLE [dbo].[PLAPPLICATIONALLOWEDACTIVITY] (
    [PLAPPLICATIONALLOWEDACTIVITYID] CHAR (36) NOT NULL,
    [PLAPPLICATIONTYPEID]            CHAR (36) NOT NULL,
    [PLAPPLICATIONACTIVITYTYPEID]    CHAR (36) NOT NULL,
    CONSTRAINT [PK_PLApplicationAllowedActivity] PRIMARY KEY CLUSTERED ([PLAPPLICATIONALLOWEDACTIVITYID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PLApplicationAllowedActivity_PLApplicationActivityType] FOREIGN KEY ([PLAPPLICATIONACTIVITYTYPEID]) REFERENCES [dbo].[PLAPPLICATIONACTIVITYTYPE] ([PLAPPLICATIONACTIVITYTYPEID]),
    CONSTRAINT [FK_PLApplicationAllowedActivity_PLApplicationType] FOREIGN KEY ([PLAPPLICATIONTYPEID]) REFERENCES [dbo].[PLAPPLICATIONTYPE] ([PLAPPLICATIONTYPEID])
);


GO

CREATE TRIGGER [TG_PLAPPLICATIONALLOWEDACTIVITY_DELETE] ON PLAPPLICATIONALLOWEDACTIVITY
   AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [HISTORYSYSTEMSETUP]
    (	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )

	SELECT
			[PLAPPLICATIONTYPE].[PLAPPLICATIONTYPEID],
			[PLAPPLICATIONTYPE].[ROWVERSION],
			GETUTCDATE(),
			(SELECT dbo.UFN_GET_USERID_FROM_CONTEXT_INFO()),
			'Application Allowed Activity Deleted',
			'',
			'',
			'Allowed Activity (' + [PLAPPLICATIONACTIVITYTYPE].[NAME] + ')',
			'0C9FECFF-F1B4-4A19-A89B-F7B414BC8D46',
			3,
			0,
			[PLAPPLICATIONACTIVITYTYPE].[NAME]
	FROM	[deleted]
	INNER JOIN PLAPPLICATIONTYPE ON PLAPPLICATIONTYPE.PLAPPLICATIONTYPEID = [deleted].PLAPPLICATIONTYPEID
	INNER JOIN PLAPPLICATIONACTIVITYTYPE ON PLAPPLICATIONACTIVITYTYPE.PLAPPLICATIONACTIVITYTYPEID = [deleted].PLAPPLICATIONACTIVITYTYPEID
END
GO

CREATE TRIGGER [TG_PLAPPLICATIONALLOWEDACTIVITY_INSERT] ON PLAPPLICATIONALLOWEDACTIVITY
   FOR INSERT
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [HISTORYSYSTEMSETUP]
    (	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )

	SELECT
			[PLAPPLICATIONTYPE].[PLAPPLICATIONTYPEID],
			[PLAPPLICATIONTYPE].[ROWVERSION],
			GETUTCDATE(),
			[PLAPPLICATIONTYPE].[LASTCHANGEDBY],
			'Application Allowed Activity Added',
			'',
			'',
			'Allowed Activity (' + [PLAPPLICATIONACTIVITYTYPE].[NAME] + ')',
			'0C9FECFF-F1B4-4A19-A89B-F7B414BC8D46',
			1,
			0,
			[PLAPPLICATIONACTIVITYTYPE].[NAME]
	FROM	[inserted]	
	INNER JOIN PLAPPLICATIONTYPE ON PLAPPLICATIONTYPE.PLAPPLICATIONTYPEID = [inserted].PLAPPLICATIONTYPEID
	INNER JOIN PLAPPLICATIONACTIVITYTYPE ON PLAPPLICATIONACTIVITYTYPE.PLAPPLICATIONACTIVITYTYPEID = [inserted].PLAPPLICATIONACTIVITYTYPEID
END