CREATE TABLE [dbo].[PLITEMREVIEW] (
    [PLITEMREVIEWID]           CHAR (36)       NOT NULL,
    [PLPLANID]                 CHAR (36)       NULL,
    [PLSUBMITTALID]            CHAR (36)       NOT NULL,
    [PLITEMREVIEWSTATUSID]     CHAR (36)       NOT NULL,
    [COMMENTS]                 NVARCHAR (MAX)  NULL,
    [ASSIGNEDDATE]             DATETIME        NULL,
    [ASSIGNEDUSERID]           CHAR (36)       NULL,
    [TEAMASSIGNEDTO]           CHAR (36)       NULL,
    [COMPLETEDATE]             DATETIME        NULL,
    [COMPLETED]                BIT             NOT NULL,
    [PASSED]                   BIT             NOT NULL,
    [HASUNRESOLVEDCORRECTIONS] BIT             NOT NULL,
    [HOURSSPENT]               DECIMAL (10, 2) NULL,
    [NOTREQUIRED]              BIT             NOT NULL,
    [APPROVEDUSERID]           CHAR (36)       NULL,
    [PLITEMREVIEWTYPEID]       CHAR (36)       NOT NULL,
    [DUEDATE]                  DATETIME        NULL,
    [ROWVERSION]               INT             CONSTRAINT [DF_PLItemReview_RowVersion] DEFAULT ((1)) NOT NULL,
    [LASTCHANGEDON]            DATETIME        NULL,
    [LASTCHANGEDBY]            CHAR (36)       NULL,
    [PRIORITYORDER]            INT             NULL,
    [PMPERMITID]               CHAR (36)       NULL,
    [SKIPPEDBYSYSTEM]          BIT             DEFAULT ((0)) NOT NULL,
    [STATUSCHANGEDDATE]        DATETIME        NULL,
    [BLLICENSEID]              CHAR (36)       NULL,
    [ILLICENSEID]              CHAR (36)       NULL,
    [PREVIOUSPLITEMREVIEWID]   CHAR (36)       NULL,
    CONSTRAINT [PK_PLItemReview] PRIMARY KEY CLUSTERED ([PLITEMREVIEWID] ASC),
    CONSTRAINT [FK_PLItemReview_BLLICENSE] FOREIGN KEY ([BLLICENSEID]) REFERENCES [dbo].[BLLICENSE] ([BLLICENSEID]),
    CONSTRAINT [FK_PLItemReview_ILLICENSE] FOREIGN KEY ([ILLICENSEID]) REFERENCES [dbo].[ILLICENSE] ([ILLICENSEID]),
    CONSTRAINT [FK_PLItemReview_PLItemReview] FOREIGN KEY ([PREVIOUSPLITEMREVIEWID]) REFERENCES [dbo].[PLITEMREVIEW] ([PLITEMREVIEWID]),
    CONSTRAINT [FK_PLItemReview_PLPlan] FOREIGN KEY ([PLPLANID]) REFERENCES [dbo].[PLPLAN] ([PLPLANID]),
    CONSTRAINT [FK_PLItemReview_PLSubmittal] FOREIGN KEY ([PLSUBMITTALID]) REFERENCES [dbo].[PLSUBMITTAL] ([PLSUBMITTALID]),
    CONSTRAINT [FK_PLITEMREVIEW_PMPERMIT] FOREIGN KEY ([PMPERMITID]) REFERENCES [dbo].[PMPERMIT] ([PMPERMITID]),
    CONSTRAINT [FK_PLItemReview_Status] FOREIGN KEY ([PLITEMREVIEWSTATUSID]) REFERENCES [dbo].[PLITEMREVIEWSTATUS] ([PLITEMREVIEWSTATUSID]),
    CONSTRAINT [FK_PLItemReview_Team] FOREIGN KEY ([TEAMASSIGNEDTO]) REFERENCES [dbo].[TEAM] ([TEAMID]),
    CONSTRAINT [FK_PLItemReview_Type] FOREIGN KEY ([PLITEMREVIEWTYPEID]) REFERENCES [dbo].[PLITEMREVIEWTYPE] ([PLITEMREVIEWTYPEID]),
    CONSTRAINT [FK_PLItemReview_Users] FOREIGN KEY ([ASSIGNEDUSERID]) REFERENCES [dbo].[USERS] ([SUSERGUID]),
    CONSTRAINT [FK_PLItemReview_Users1] FOREIGN KEY ([APPROVEDUSERID]) REFERENCES [dbo].[USERS] ([SUSERGUID]),
    CONSTRAINT [FK_PLItemReview_Users2] FOREIGN KEY ([LASTCHANGEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PLITEMREVIEW_BLLICENSE]
    ON [dbo].[PLITEMREVIEW]([BLLICENSEID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PLITEMREVIEW_COMPLETE_ASSIGNEDTO]
    ON [dbo].[PLITEMREVIEW]([ASSIGNEDUSERID] ASC, [COMPLETEDATE] ASC, [COMPLETED] ASC, [NOTREQUIRED] ASC)
    INCLUDE([PLPLANID], [PLSUBMITTALID], [PLITEMREVIEWSTATUSID], [PLITEMREVIEWTYPEID], [DUEDATE], [PMPERMITID]);


GO
CREATE NONCLUSTERED INDEX [IX_PLITEMREVIEW_COMPLETEDATE]
    ON [dbo].[PLITEMREVIEW]([COMPLETEDATE] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PLITEMREVIEW_DUEDATE]
    ON [dbo].[PLITEMREVIEW]([DUEDATE] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PLITEMREVIEW_HUB_INDEX]
    ON [dbo].[PLITEMREVIEW]([ASSIGNEDUSERID] ASC, [COMPLETED] ASC, [NOTREQUIRED] ASC)
    INCLUDE([PLPLANID], [PLSUBMITTALID], [PLITEMREVIEWSTATUSID], [ASSIGNEDDATE], [PLITEMREVIEWTYPEID], [DUEDATE], [PMPERMITID], [BLLICENSEID], [ILLICENSEID]);


GO
CREATE NONCLUSTERED INDEX [IX_PLITEMREVIEW_ILLICENSE]
    ON [dbo].[PLITEMREVIEW]([ILLICENSEID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PLITEMREVIEW_PERMIT]
    ON [dbo].[PLITEMREVIEW]([PMPERMITID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PLITEMREVIEW_PLAN]
    ON [dbo].[PLITEMREVIEW]([PLPLANID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PLITEMREVIEW_PLITEMREVIEWSTATUSID]
    ON [dbo].[PLITEMREVIEW]([PLITEMREVIEWSTATUSID] ASC)
    INCLUDE([PLSUBMITTALID], [ASSIGNEDDATE], [ASSIGNEDUSERID], [COMPLETEDATE], [COMPLETED], [NOTREQUIRED], [PLITEMREVIEWTYPEID], [DUEDATE]);


GO
CREATE NONCLUSTERED INDEX [IX_PLITEMREVIEW_PREVIOUSITEMREVIEW]
    ON [dbo].[PLITEMREVIEW]([PREVIOUSPLITEMREVIEWID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PLITEMREVIEW_SUBMIT]
    ON [dbo].[PLITEMREVIEW]([PLSUBMITTALID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_REVIEW_USER]
    ON [dbo].[PLITEMREVIEW]([ASSIGNEDUSERID] ASC, [COMPLETED] ASC);


GO

CREATE TRIGGER [TG_PLITEMREVIEW_INSERTUPDATE_ELASTIC_PERMIT] ON  [PLITEMREVIEW]
   AFTER INSERT, UPDATE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [ELASTICSEARCHOBJECT]
    ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID() ,
		[P].[PMPERMITID] ,
        'EnerGovBusiness.PermitManagement.Permit' ,
        [P].[ROWVERSION] ,
        GETDATE() ,
        NULL ,
        2 ,
        (SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Inserted]
	JOIN [PMPERMIT] AS [P] WITH (NOLOCK) ON [P].[PMPERMITID] = [Inserted].[PMPERMITID];

END
GO

CREATE TRIGGER [TG_PLITEMREVIEW_INSERT_RECORDCHANGETRACKQUEUE] ON [PLITEMREVIEW]
   AFTER INSERT
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [RECORDCHANGETRACKQUEUE]
    (
		[RECORDID], 
		[RECORDSOURCEID], 
		[CREATEDATE], 
		[PROCESSEDDATE], 
		[RECORDSTATUSID], 
		[RECORDACTIONID]
    )
	SELECT
		[Inserted].[PLITEMREVIEWID],
		14,
        GETDATE(),
        NULL, -- ProcessedDate is null
        1, -- 'Pending' from RECORDSTATUS table
		1  -- 'Insert' from RECORDACTION table
	FROM [Inserted]
END
GO
DISABLE TRIGGER [dbo].[TG_PLITEMREVIEW_INSERT_RECORDCHANGETRACKQUEUE]
    ON [dbo].[PLITEMREVIEW];


GO

CREATE TRIGGER [TG_PLITEMREVIEW_DELETE_RECORDCHANGETRACKQUEUE] ON [PLITEMREVIEW]
   AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [RECORDCHANGETRACKQUEUE]
    (
		[RECORDID], 
		[RECORDSOURCEID], 
		[CREATEDATE], 
		[PROCESSEDDATE], 
		[RECORDSTATUSID], 
		[RECORDACTIONID]
    )
	SELECT
		[Deleted].[PLITEMREVIEWID],
		14,
        GETDATE(),
        NULL, -- ProcessedDate is null
        1, -- 'Pending' from RECORDSTATUS table
		3  -- 'Delete' from RECORDACTION table
	FROM [Deleted]
END
GO
DISABLE TRIGGER [dbo].[TG_PLITEMREVIEW_DELETE_RECORDCHANGETRACKQUEUE]
    ON [dbo].[PLITEMREVIEW];


GO


CREATE TRIGGER [TG_PLITEMREVIEW_DELETE_ELASTIC_PLAN] ON  [PLITEMREVIEW]
   AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [ELASTICSEARCHOBJECT]
    ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID() ,
		[P].[PLPLANID] ,
        'EnerGovBusiness.PlanManagement.Plan' ,
        [P].[ROWVERSION] ,
        GETDATE() ,
        NULL ,
        2 ,
        (SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Deleted]
	JOIN [PLPLAN] AS [P] WITH (NOLOCK) ON [P].[PLPLANID] = [Deleted].[PLPLANID];

END
GO


CREATE TRIGGER [TG_PLITEMREVIEW_DELETE_ELASTIC_PERMIT] ON  [PLITEMREVIEW]
   AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [ELASTICSEARCHOBJECT]
    ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID() ,
		[P].[PMPERMITID] ,
        'EnerGovBusiness.PermitManagement.Permit' ,
        [P].[ROWVERSION] ,
        GETDATE() ,
        NULL ,
        2 ,
        (SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Deleted]
	JOIN [PMPERMIT] AS [P] WITH (NOLOCK) ON [P].[PMPERMITID] = [Deleted].[PMPERMITID];

END
GO

CREATE TRIGGER [TG_PLITEMREVIEW_INSERTUPDATE_ELASTIC_PLAN] ON  [PLITEMREVIEW]
   AFTER INSERT, UPDATE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [ELASTICSEARCHOBJECT]
    ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID() ,
		[P].[PLPLANID] ,
        'EnerGovBusiness.PlanManagement.Plan' ,
        [P].[ROWVERSION] ,
        GETDATE() ,
        NULL ,
        2 ,
        (SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Inserted]
	JOIN [PLPLAN] AS [P] WITH (NOLOCK) ON [P].[PLPLANID] = [Inserted].[PLPLANID];

END
GO

CREATE TRIGGER [TG_PLITEMREVIEW_UPDATE_RECORDCHANGETRACKQUEUE] ON [PLITEMREVIEW]
   AFTER UPDATE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [RECORDCHANGETRACKQUEUE]
    (
		[RECORDID], 
		[RECORDSOURCEID], 
		[CREATEDATE], 
		[PROCESSEDDATE], 
		[RECORDSTATUSID], 
		[RECORDACTIONID]
    )
	SELECT
		[Inserted].[PLITEMREVIEWID],
		14,
        GETDATE(),
        NULL, -- ProcessedDate is null
        1, -- 'Pending' from RECORDSTATUS table
		2  -- 'Update' from RECORDACTION table
	FROM [Inserted]
END
GO
DISABLE TRIGGER [dbo].[TG_PLITEMREVIEW_UPDATE_RECORDCHANGETRACKQUEUE]
    ON [dbo].[PLITEMREVIEW];

