CREATE TABLE [dbo].[PLPLANCORRECTION] (
    [PLPLANCORRECTIONID]         CHAR (36)      NOT NULL,
    [PLPLANID]                   CHAR (36)      NULL,
    [PLPLANCORRECTIONTYPEID]     CHAR (36)      NOT NULL,
    [PLITEMREVIEWID]             CHAR (36)      NOT NULL,
    [COMMENTS]                   NVARCHAR (MAX) NULL,
    [ISEREVIEW]                  BIT            NOT NULL,
    [CREATEDATE]                 DATETIME       NOT NULL,
    [RESOLVEDATE]                DATETIME       NULL,
    [ADDEDBYUSERID]              CHAR (36)      NOT NULL,
    [RESOLVEDBYUSERID]           CHAR (36)      NULL,
    [RESOLVED]                   BIT            NOT NULL,
    [ERPROJECTFILEVERSIONID]     CHAR (36)      NULL,
    [REPLIED]                    BIT            CONSTRAINT [DF_PLPlanCorrection_ERHasComment] DEFAULT ((0)) NOT NULL,
    [CORRECTIVEACTION]           NVARCHAR (MAX) NULL,
    [PMPERMITID]                 CHAR (36)      NULL,
    [SORTORDER]                  INT            DEFAULT ((0)) NOT NULL,
    [BLLICENSEID]                CHAR (36)      NULL,
    [ILLICENSEID]                CHAR (36)      NULL,
    [PREVIOUSPLPLANCORRECTIONID] CHAR (36)      NULL,
    CONSTRAINT [PK_PLPlanCorrection] PRIMARY KEY CLUSTERED ([PLPLANCORRECTIONID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PLPLANCORRECTION_BLLICENSE] FOREIGN KEY ([BLLICENSEID]) REFERENCES [dbo].[BLLICENSE] ([BLLICENSEID]),
    CONSTRAINT [FK_PLPlanCorrection_CorrectionType] FOREIGN KEY ([PLPLANCORRECTIONTYPEID]) REFERENCES [dbo].[PLPLANCORRECTIONTYPE] ([PLPLANCORRECTIONTYPEID]),
    CONSTRAINT [FK_PLPlanCorrection_ERProjectFile] FOREIGN KEY ([ERPROJECTFILEVERSIONID]) REFERENCES [dbo].[ERPROJECTFILEVERSION] ([ERPROJECTFILEVERSIONID]),
    CONSTRAINT [FK_PLPLANCORRECTION_ILLICENSE] FOREIGN KEY ([ILLICENSEID]) REFERENCES [dbo].[ILLICENSE] ([ILLICENSEID]),
    CONSTRAINT [FK_PLPlanCorrection_PLItemReview] FOREIGN KEY ([PLITEMREVIEWID]) REFERENCES [dbo].[PLITEMREVIEW] ([PLITEMREVIEWID]),
    CONSTRAINT [FK_PLPlanCorrection_PLPlan] FOREIGN KEY ([PLPLANID]) REFERENCES [dbo].[PLPLAN] ([PLPLANID]),
    CONSTRAINT [FK_PLPlanCorrection_PLPlanCorrection] FOREIGN KEY ([PREVIOUSPLPLANCORRECTIONID]) REFERENCES [dbo].[PLPLANCORRECTION] ([PLPLANCORRECTIONID]),
    CONSTRAINT [FK_PLPLANCORRECTION_PMPERMIT] FOREIGN KEY ([PMPERMITID]) REFERENCES [dbo].[PMPERMIT] ([PMPERMITID]),
    CONSTRAINT [FK_PLPlanCorrection_Users] FOREIGN KEY ([ADDEDBYUSERID]) REFERENCES [dbo].[USERS] ([SUSERGUID]),
    CONSTRAINT [FK_PLPlanCorrection_Users1] FOREIGN KEY ([RESOLVEDBYUSERID]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PLPLANCORRECTION_BLLICENSE]
    ON [dbo].[PLPLANCORRECTION]([BLLICENSEID] ASC, [PLPLANCORRECTIONID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PLPLANCORRECTION_ILLICENSE]
    ON [dbo].[PLPLANCORRECTION]([ILLICENSEID] ASC, [PLPLANCORRECTIONID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PLPLANCORRECTION_PLPLAN]
    ON [dbo].[PLPLANCORRECTION]([PLPLANID] ASC, [PLPLANCORRECTIONID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PLPLANCORRECTION_PMPERMIT]
    ON [dbo].[PLPLANCORRECTION]([PMPERMITID] ASC, [PLPLANCORRECTIONID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PLPLANCORRECTION_PLITEMREVIEWID]
    ON [dbo].[PLPLANCORRECTION]([PLITEMREVIEWID] ASC)
    INCLUDE([COMMENTS], [ADDEDBYUSERID]);


GO
CREATE NONCLUSTERED INDEX [IX_PLPLANCORRECTION_PREVIOUSPLPLANCORRECTIONID]
    ON [dbo].[PLPLANCORRECTION]([PREVIOUSPLPLANCORRECTIONID] ASC)
    INCLUDE([PLPLANCORRECTIONID]);

