CREATE TABLE [dbo].[PLPLANACTIONREF] (
    [OBJECTID] CHAR (36) NOT NULL,
    [PLPLANID] CHAR (36) NOT NULL,
    CONSTRAINT [PK_PLPlanActionRef] PRIMARY KEY CLUSTERED ([OBJECTID] ASC, [PLPLANID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PLPlanActionRef_PL] FOREIGN KEY ([PLPLANID]) REFERENCES [dbo].[PLPLAN] ([PLPLANID])
);

