CREATE TABLE [dbo].[PLPLANOBJECT] (
    [PLPLANOBJECTID] CHAR (36) NOT NULL,
    [PLPLANID]       CHAR (36) NOT NULL,
    [OMOBJECTID]     CHAR (36) NOT NULL,
    CONSTRAINT [PK_PLPLANOBJECT] PRIMARY KEY CLUSTERED ([PLPLANOBJECTID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PLPLANOBJECT_OMOBJECT] FOREIGN KEY ([OMOBJECTID]) REFERENCES [dbo].[OMOBJECT] ([OMOBJECTID]),
    CONSTRAINT [FK_PLPLANOBJECT_PLPLAN] FOREIGN KEY ([PLPLANID]) REFERENCES [dbo].[PLPLAN] ([PLPLANID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PLPLANOBJECT_PLAN]
    ON [dbo].[PLPLANOBJECT]([PLPLANID] ASC)
    INCLUDE([OMOBJECTID]) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_PLPLANOBJECT_OMOBJECTID_PLPLANID]
    ON [dbo].[PLPLANOBJECT]([OMOBJECTID] ASC, [PLPLANID] ASC);

