CREATE TABLE [dbo].[PLPLANDIMENSION] (
    [PLPLANDIMENSIONID]           CHAR (36)       NOT NULL,
    [PMPERMITDIMENSIONCATEGORYID] CHAR (36)       NOT NULL,
    [PLPLANID]                    CHAR (36)       NOT NULL,
    [LENGTH]                      DECIMAL (15, 2) NULL,
    [WIDTH]                       DECIMAL (15, 2) NULL,
    [SQUAREFEET]                  DECIMAL (15, 2) NULL,
    CONSTRAINT [PK_PLPlanDimension] PRIMARY KEY CLUSTERED ([PLPLANDIMENSIONID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PlanDimension_Category] FOREIGN KEY ([PMPERMITDIMENSIONCATEGORYID]) REFERENCES [dbo].[PMPERMITDIMENSIONCATEGORY] ([PMPERMITDIMENSIONCATEGORYID]),
    CONSTRAINT [FK_PlanDimension_PLPlan] FOREIGN KEY ([PLPLANID]) REFERENCES [dbo].[PLPLAN] ([PLPLANID])
);

