CREATE TABLE [dbo].[PLPLANREVIEWTEAM] (
    [PLPLANREVIEWTEAMID] CHAR (36) NOT NULL,
    [PLPLANID]           CHAR (36) NOT NULL,
    [DEPARTMENTID]       CHAR (36) NOT NULL,
    [USERID]             CHAR (36) NOT NULL,
    CONSTRAINT [PK_PLPlanReviewTeam] PRIMARY KEY CLUSTERED ([PLPLANREVIEWTEAMID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PlanReviewTeam_Dept] FOREIGN KEY ([DEPARTMENTID]) REFERENCES [dbo].[DEPARTMENT] ([DEPARTMENTID]),
    CONSTRAINT [FK_PLPlanReviewTeam_Plan] FOREIGN KEY ([PLPLANID]) REFERENCES [dbo].[PLPLAN] ([PLPLANID]),
    CONSTRAINT [FK_PLPlanReviewTeam_Users] FOREIGN KEY ([USERID]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);

