CREATE TABLE [dbo].[PLPLANCONDITION] (
    [PLPLANCONDITIONID] CHAR (36)   NOT NULL,
    [CONDITIONID]       CHAR (36)   NOT NULL,
    [PLANID]            CHAR (36)   NOT NULL,
    [ISSATISFIED]       BIT         NOT NULL,
    [SCOPE]             INT         NOT NULL,
    [CREATEDON]         DATETIME    NULL,
    [ORDER]             VARCHAR (5) NULL,
    [CREATEDBY]         CHAR (36)   NULL,
    CONSTRAINT [PK_PlanCondition] PRIMARY KEY CLUSTERED ([PLPLANCONDITIONID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PLPlanCondition_conCondition] FOREIGN KEY ([CONDITIONID]) REFERENCES [dbo].[CONDITION] ([CONDITIONID]),
    CONSTRAINT [FK_PLPlanCondition_ConditionScope] FOREIGN KEY ([SCOPE]) REFERENCES [dbo].[CONDITIONSCOPE] ([CONDITIONSCOPEID]),
    CONSTRAINT [FK_PLPlanCondition_PLPlan] FOREIGN KEY ([PLANID]) REFERENCES [dbo].[PLPLAN] ([PLPLANID]),
    CONSTRAINT [FK_PLPLANCONDITION_USERS] FOREIGN KEY ([CREATEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);


GO
CREATE NONCLUSTERED INDEX [NCIDX_PLPLANCONDITION_PLANID]
    ON [dbo].[PLPLANCONDITION]([PLANID] ASC) WITH (FILLFACTOR = 90, PAD_INDEX = ON);


GO


CREATE TRIGGER [TG_PLPLANCONDITION_DELETE_ELASTIC_EREVIEW] ON  PLPLANCONDITION
   AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [ELASTICSEARCHOBJECT]
    ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID() ,
		[E].[ERPROJECTID] ,
        'EnerGovBusiness.PlanManagement.EProject' ,
        [E].[ROWVERSION] ,
        GETDATE() ,
        NULL ,
        2 ,
        (SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Deleted]
	JOIN [PLPLAN] AS [P] WITH (NOLOCK) ON [P].[PLPLANID] = [Deleted].[PLANID]
	JOIN [ERPROJECT] AS [E] WITH (NOLOCK) ON [E].[PLPLANID] = [P].[PLPLANID];

END
GO

CREATE TRIGGER [TG_PLPLANCONDITION_INSERTUPDATE_ELASTIC_EREVIEW] ON  PLPLANCONDITION
   AFTER INSERT, UPDATE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [ELASTICSEARCHOBJECT]
    ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID() ,
		[E].[ERPROJECTID] ,
        'EnerGovBusiness.PlanManagement.EProject' ,
        [E].[ROWVERSION] ,
        GETDATE() ,
        NULL ,
        2 ,
        (SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Inserted]
	JOIN [PLPLAN] AS [P] WITH (NOLOCK) ON [P].[PLPLANID] = [Inserted].[PLANID]
	JOIN [ERPROJECT] AS [E] WITH (NOLOCK) ON [E].[PLPLANID] = [P].[PLPLANID];

END