CREATE TABLE [dbo].[PLPLANCAPAPPLICATIONTYPE] (
    [PLPLANCAPAPPLICATIONTYPEID] INT           NOT NULL,
    [NAME]                       NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_PLPLANCAPAPPLICATIONTYPE] PRIMARY KEY CLUSTERED ([PLPLANCAPAPPLICATIONTYPEID] ASC) WITH (FILLFACTOR = 90)
);

