CREATE TABLE [dbo].[PLPLANVALUATION] (
    [PLPLANVALUATIONID]          CHAR (36)       NOT NULL,
    [PLPLANID]                   CHAR (36)       NOT NULL,
    [SQUAREFEET]                 DECIMAL (15, 2) NULL,
    [VALUE]                      MONEY           NULL,
    [FACTOR]                     DECIMAL (15, 2) NULL,
    [PMPERMITVALTYPEVALGROUPXID] CHAR (36)       NULL,
    CONSTRAINT [PK_PLPlanValuation] PRIMARY KEY CLUSTERED ([PLPLANVALUATIONID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PLPlanValuation_Plan] FOREIGN KEY ([PLPLANID]) REFERENCES [dbo].[PLPLAN] ([PLPLANID]),
    CONSTRAINT [FK_PLPlanValuation_ValTypeValGroupXRef] FOREIGN KEY ([PMPERMITVALTYPEVALGROUPXID]) REFERENCES [dbo].[PMPERMITVALUATIONTYPEVALGROUPX] ([PMPERMITVALUATIONTYPEVALGRPXID])
);

