CREATE TABLE [dbo].[PLPLANTYPEUNITTYPE] (
    [PLPLANTYPEUNITTYPEID] CHAR (36) NOT NULL,
    [PLPLANTYPEID]         CHAR (36) NOT NULL,
    [PLPLANWORKCLASSID]    CHAR (36) NULL,
    [IPUNITTYPEID]         CHAR (36) NOT NULL,
    [ISREQUIRED]           BIT       NOT NULL,
    [UNITTYPEGROUP]        INT       NULL,
    CONSTRAINT [PK_PLPLANTYPEUNITTYPE] PRIMARY KEY CLUSTERED ([PLPLANTYPEUNITTYPEID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PLUNITTYPE_IPUNITTYPE] FOREIGN KEY ([IPUNITTYPEID]) REFERENCES [dbo].[IPUNITTYPE] ([IPUNITTYPEID]),
    CONSTRAINT [FK_PLUNITTYPE_PLPLANTYPE] FOREIGN KEY ([PLPLANTYPEID]) REFERENCES [dbo].[PLPLANTYPE] ([PLPLANTYPEID]),
    CONSTRAINT [FK_PLUNITTYPE_PLWORKCLASS] FOREIGN KEY ([PLPLANWORKCLASSID]) REFERENCES [dbo].[PLPLANWORKCLASS] ([PLPLANWORKCLASSID])
);


GO
CREATE TRIGGER [dbo].[TG_PLPLANTYPEUNITTYPE_INSERT]
   ON  [dbo].[PLPLANTYPEUNITTYPE]
   AFTER INSERT
AS 
BEGIN	
	SET NOCOUNT ON;	
	INSERT INTO [HISTORYSYSTEMSETUP]
    (
        [ID],
        [ROWVERSION],
        [CHANGEDON],
        [CHANGEDBY],
        [FIELDNAME],
        [OLDVALUE],
        [NEWVALUE],
        [ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT 
        [PLPLANTYPE].[PLPLANTYPEID], 
        [PLPLANTYPE].[ROWVERSION],
        GETUTCDATE(),
        [PLPLANTYPE].[LASTCHANGEDBY],	
        'Plan Type Allowed Unit Type Added',
        '',
        '',       
		'Plan Type (' + [PLPLANTYPE].[PLANNAME] + '), Work Class Name (' + ISNULL([PLPLANWORKCLASS].[NAME],'[none]') +'), Allowed Unit Type (' + [IPUNITTYPE].[NAME] +')',
		'DEC0149B-EF4A-4E0F-AA4A-E622B90C1545',
		1,
		0,
		[IPUNITTYPE].[NAME]
    FROM [inserted]
	INNER JOIN [IPUNITTYPE] WITH (NOLOCK) ON [IPUNITTYPE].[IPUNITTYPEID] = [inserted].[IPUNITTYPEID]
	INNER JOIN [PLPLANWORKCLASS] WITH (NOLOCK) ON [PLPLANWORKCLASS].[PLPLANWORKCLASSID] = [inserted].[PLPLANWORKCLASSID]
	INNER JOIN [PLPLANTYPE] ON [PLPLANTYPE].[PLPLANTYPEID] = [inserted].[PLPLANTYPEID]
END
GO
CREATE TRIGGER [dbo].[TG_PLPLANTYPEUNITTYPE_UPDATE]
   ON  [dbo].[PLPLANTYPEUNITTYPE] 
   AFTER UPDATE
AS 
BEGIN	
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
    (	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT 
			[PLPLANTYPE].[PLPLANTYPEID],
			[PLPLANTYPE].[ROWVERSION],
			GETUTCDATE(),
			[PLPLANTYPE].[LASTCHANGEDBY],
			'Unit Type Required Flag',
			CASE [deleted].[ISREQUIRED] WHEN 1 THEN 'Yes' WHEN 0 THEN 'No' END,
			CASE [inserted].[ISREQUIRED] WHEN 1 THEN 'Yes' WHEN 0 THEN 'No' END,
			'Plan Type (' + [PLPLANTYPE].[PLANNAME] + '), Work Class Name (' + ISNULL([PLPLANWORKCLASS].[NAME],'[none]') +'), Allowed Unit Type (' + [IPUNITTYPE].[NAME] +')',
			'DEC0149B-EF4A-4E0F-AA4A-E622B90C1545',
			2,
			0,
			[IPUNITTYPE].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[PLPLANTYPEUNITTYPEID] = [inserted].[PLPLANTYPEUNITTYPEID]
			INNER JOIN [IPUNITTYPE] WITH (NOLOCK) ON [IPUNITTYPE].[IPUNITTYPEID] = [inserted].[IPUNITTYPEID]
			INNER JOIN [PLPLANWORKCLASS] WITH (NOLOCK) ON [PLPLANWORKCLASS].[PLPLANWORKCLASSID] = [inserted].[PLPLANWORKCLASSID]
			INNER JOIN [PLPLANTYPE] ON [PLPLANTYPE].[PLPLANTYPEID] = [inserted].[PLPLANTYPEID]			
						
			
	WHERE	[deleted].[ISREQUIRED] <> [inserted].[ISREQUIRED]
	UNION ALL
	SELECT 
			[PLPLANTYPE].[PLPLANTYPEID],
			[PLPLANTYPE].[ROWVERSION],
			GETUTCDATE(),
			[PLPLANTYPE].[LASTCHANGEDBY],
			'Unit Type Set',
			ISNULL(CONVERT(NVARCHAR(MAX), [deleted].[UNITTYPEGROUP]),'[none]'),
			ISNULL(CONVERT(NVARCHAR(MAX), [inserted].[UNITTYPEGROUP]),'[none]'),			
			'Plan Type (' + [PLPLANTYPE].[PLANNAME] + '), Work Class Name (' + ISNULL([PLPLANWORKCLASS].[NAME],'[none]') +'), Allowed Unit Type (' + [IPUNITTYPE].[NAME] +')',
			'DEC0149B-EF4A-4E0F-AA4A-E622B90C1545',
			2,
			0,
			[IPUNITTYPE].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[PLPLANTYPEUNITTYPEID] = [inserted].[PLPLANTYPEUNITTYPEID]
			INNER JOIN [IPUNITTYPE] WITH (NOLOCK) ON [IPUNITTYPE].[IPUNITTYPEID] = [inserted].[IPUNITTYPEID]			
			INNER JOIN [PLPLANWORKCLASS] WITH (NOLOCK) ON [PLPLANWORKCLASS].[PLPLANWORKCLASSID] = [inserted].[PLPLANWORKCLASSID]
			INNER JOIN [PLPLANTYPE] ON [PLPLANTYPE].[PLPLANTYPEID] = [inserted].[PLPLANTYPEID]
	WHERE	ISNULL([deleted].[UNITTYPEGROUP],'') <> ISNULL([inserted].[UNITTYPEGROUP],'')
	
END
GO
CREATE TRIGGER [dbo].[TG_PLPLANTYPEUNITTYPE_DELETE]  
    ON  [dbo].[PLPLANTYPEUNITTYPE]
   AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
	(
		[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
	)
	SELECT
		[PLPLANTYPE].[PLPLANTYPEID],
		[PLPLANTYPE].[ROWVERSION],
		GETUTCDATE(),			
		(SELECT dbo.UFN_GET_USERID_FROM_CONTEXT_INFO()),
		'Plan Type Allowed Unit Type Deleted',
        '',
        '',       
		'Plan Type (' + [PLPLANTYPE].[PLANNAME] + '), Work Class Name (' + ISNULL([PLPLANWORKCLASS].[NAME],'[none]') +'), Allowed Unit Type (' + [IPUNITTYPE].[NAME] +')',
		'DEC0149B-EF4A-4E0F-AA4A-E622B90C1545',
		3,
		0,
		[IPUNITTYPE].[NAME]
    FROM [deleted]
	INNER JOIN [IPUNITTYPE] WITH (NOLOCK) ON [IPUNITTYPE].[IPUNITTYPEID] = [deleted].[IPUNITTYPEID]
	INNER JOIN [PLPLANWORKCLASS] WITH (NOLOCK) ON [PLPLANWORKCLASS].[PLPLANWORKCLASSID] = [deleted].[PLPLANWORKCLASSID]
	INNER JOIN [PLPLANTYPE] ON [PLPLANTYPE].[PLPLANTYPEID] = [deleted].[PLPLANTYPEID]
END