CREATE TABLE [dbo].[PLPLANACTIVITY] (
    [PLPLANACTIVITYID]     CHAR (36)      NOT NULL,
    [PLPLANID]             CHAR (36)      NOT NULL,
    [PLPLANACTIVITYTYPEID] CHAR (36)      NOT NULL,
    [PLANACTIVITYNAME]     NVARCHAR (255) NOT NULL,
    [PLANACTIVITYNUMBER]   NVARCHAR (255) NOT NULL,
    [PLANACTIVITYCOMMENTS] NVARCHAR (MAX) NOT NULL,
    [SUSERGUID]            CHAR (36)      NOT NULL,
    [CREATEDON]            DATETIME       NOT NULL,
    [PLPLANWFACTIONSTEPID] CHAR (36)      NULL,
    CONSTRAINT [PK_PLPlanActivity] PRIMARY KEY CLUSTERED ([PLPLANACTIVITYID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PLActivity_PLWFActionStep] FOREIGN KEY ([PLPLANWFACTIONSTEPID]) REFERENCES [dbo].[PLPLANWFACTIONSTEP] ([PLPLANWFACTIONSTEPID]),
    CONSTRAINT [FK_PLPlanActivity_PLPlan] FOREIGN KEY ([PLPLANID]) REFERENCES [dbo].[PLPLAN] ([PLPLANID]),
    CONSTRAINT [FK_PLPlanActivity_PLPlanActivityType] FOREIGN KEY ([PLPLANACTIVITYTYPEID]) REFERENCES [dbo].[PLPLANACTIVITYTYPE] ([PLPLANACTIVITYTYPEID]),
    CONSTRAINT [FK_PLPlanActivity_Users] FOREIGN KEY ([SUSERGUID]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);


GO
CREATE NONCLUSTERED INDEX [IMPORT1]
    ON [dbo].[PLPLANACTIVITY]([PLPLANACTIVITYTYPEID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IMPORT2]
    ON [dbo].[PLPLANACTIVITY]([PLPLANID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IMPORT3]
    ON [dbo].[PLPLANACTIVITY]([PLPLANWFACTIONSTEPID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_PLPLANACTIVITY_PLPLANWFACTIONSTEPID]
    ON [dbo].[PLPLANACTIVITY]([PLPLANWFACTIONSTEPID] ASC);

