CREATE TABLE [dbo].[PLREVIEWITEMCAPVISIBILITY] (
    [PLREVIEWITEMCAPVISIBILITYID] INT           NOT NULL,
    [NAME]                        NVARCHAR (40) NOT NULL,
    CONSTRAINT [PK_PLREVIEWITEMCAPVISIBILITY] PRIMARY KEY CLUSTERED ([PLREVIEWITEMCAPVISIBILITYID] ASC) WITH (FILLFACTOR = 90)
);

