CREATE TABLE [dbo].[PMPERMITTYPEILLICTYPE] (
    [PMPERMITTYPEILLICENSETYPEID] CHAR (36) NOT NULL,
    [PMPERMITTYPEID]              CHAR (36) NOT NULL,
    [PMPERMITWORKCLASSID]         CHAR (36) NOT NULL,
    [ILLICENSETYPEID]             CHAR (36) NOT NULL,
    [PMPERMITTYPEWORKCLASSID]     CHAR (36) NOT NULL,
    CONSTRAINT [PK_PMPermitTypeILLicenseType] PRIMARY KEY CLUSTERED ([PMPERMITTYPEILLICENSETYPEID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PMTypeIlLicType_ILLicType] FOREIGN KEY ([ILLICENSETYPEID]) REFERENCES [dbo].[ILLICENSETYPE] ([ILLICENSETYPEID]),
    CONSTRAINT [FK_PMTypeILLicType_PMType] FOREIGN KEY ([PMPERMITTYPEID]) REFERENCES [dbo].[PMPERMITTYPE] ([PMPERMITTYPEID]),
    CONSTRAINT [FK_PMTypeIlLicType_PMWC] FOREIGN KEY ([PMPERMITWORKCLASSID]) REFERENCES [dbo].[PMPERMITWORKCLASS] ([PMPERMITWORKCLASSID]),
    CONSTRAINT [FK_PMTypeIlLicType_PMWCTY] FOREIGN KEY ([PMPERMITTYPEWORKCLASSID]) REFERENCES [dbo].[PMPERMITTYPEWORKCLASS] ([PMPERMITTYPEWORKCLASSID])
);


GO
CREATE TRIGGER [dbo].[TG_PMPERMITTYPEILLICTYPE_INSERT]
   ON  [dbo].[PMPERMITTYPEILLICTYPE]
   AFTER INSERT
AS 
BEGIN	
	SET NOCOUNT ON;	
	INSERT INTO [HISTORYSYSTEMSETUP]
    (
        [ID],
        [ROWVERSION],
        [CHANGEDON],
        [CHANGEDBY],
        [FIELDNAME],
        [OLDVALUE],
        [NEWVALUE],
        [ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT 
        [PMPERMITTYPE].[PMPERMITTYPEID], 
        [PMPERMITTYPE].[ROWVERSION],
        GETUTCDATE(),
        [PMPERMITTYPE].[LASTCHANGEDBY],	
        'Permit Type Professional License Type Added',
        '',
        '',       
		'Permit Type (' + [PMPERMITTYPE].[NAME] + '), Work Class Name (' + [PMPERMITWORKCLASS].[NAME] +'), Professional License Type (' + [ILLICENSETYPE].[NAME] +')',
		'4976A4A9-20E8-4B8F-997D-CE244B540104',
		1,
		0,
		[ILLICENSETYPE].[NAME]
    FROM [inserted]
	INNER JOIN [PMPERMITTYPE] ON [PMPERMITTYPE].[PMPERMITTYPEID] = [inserted].[PMPERMITTYPEID]
	INNER JOIN [PMPERMITWORKCLASS] WITH (NOLOCK) ON [PMPERMITWORKCLASS].[PMPERMITWORKCLASSID] = [inserted].[PMPERMITWORKCLASSID]
	INNER JOIN [ILLICENSETYPE] WITH (NOLOCK) ON [ILLICENSETYPE].[ILLICENSETYPEID] = [inserted].[ILLICENSETYPEID]
END
GO
CREATE TRIGGER [dbo].[TG_PMPERMITTYPEILLICTYPE_DELETE]  
    ON  [dbo].[PMPERMITTYPEILLICTYPE]
   AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
	(
		[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
	)
	SELECT
		[PMPERMITTYPE].[PMPERMITTYPEID],
		[PMPERMITTYPE].[ROWVERSION],
		GETUTCDATE(),			
		(SELECT dbo.UFN_GET_USERID_FROM_CONTEXT_INFO()),
		'Permit Type Professional License Type Deleted',
        '',
        '',       
		'Permit Type (' + [PMPERMITTYPE].[NAME] + '), Work Class Name (' + [PMPERMITWORKCLASS].[NAME] +'), Professional License Type (' + [ILLICENSETYPE].[NAME] +')',
		'4976A4A9-20E8-4B8F-997D-CE244B540104',
		3,
		0,
		[ILLICENSETYPE].[NAME]
    FROM [deleted]
	INNER JOIN [PMPERMITTYPE] ON [PMPERMITTYPE].[PMPERMITTYPEID] = [deleted].[PMPERMITTYPEID]
	INNER JOIN [PMPERMITWORKCLASS] WITH (NOLOCK) ON [PMPERMITWORKCLASS].[PMPERMITWORKCLASSID] = [deleted].[PMPERMITWORKCLASSID]
	INNER JOIN [ILLICENSETYPE] WITH (NOLOCK) ON [ILLICENSETYPE].[ILLICENSETYPEID] = [deleted].[ILLICENSETYPEID]
END