CREATE TABLE [dbo].[PMPERMITCHECKLIST] (
    [PMPERMITCHECKLISTID] CHAR (36) NOT NULL,
    [PMPERMITTYPEID]      CHAR (36) NOT NULL,
    [COMPLETED]           BIT       NOT NULL,
    [ATTACHEDPMPERMITID]  CHAR (36) NOT NULL,
    [PMPERMITID]          CHAR (36) NOT NULL,
    CONSTRAINT [PK_PMPermitCheckList] PRIMARY KEY CLUSTERED ([PMPERMITCHECKLISTID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PMCheckList_PermitType] FOREIGN KEY ([PMPERMITTYPEID]) REFERENCES [dbo].[PMPERMITTYPE] ([PMPERMITTYPEID]),
    CONSTRAINT [FK_PMCheckList_PMPermit1] FOREIGN KEY ([ATTACHEDPMPERMITID]) REFERENCES [dbo].[PMPERMIT] ([PMPERMITID]),
    CONSTRAINT [FK_PMPermitCheckList_PMPermit] FOREIGN KEY ([PMPERMITID]) REFERENCES [dbo].[PMPERMIT] ([PMPERMITID])
);

