CREATE TABLE [dbo].[PMPERMITTYPEUNITTYPE] (
    [PMPERMITTYPEIPUNITTYPEID] CHAR (36) NOT NULL,
    [PMPERMITTYPEID]           CHAR (36) NOT NULL,
    [PMPERMITWORKCLASSID]      CHAR (36) NULL,
    [IPUNITTYPEID]             CHAR (36) NOT NULL,
    [ISREQUIRED]               BIT       NOT NULL,
    [UNITTYPEGROUP]            INT       NULL,
    CONSTRAINT [PK_PMPERMITTYPEUNITTYPE] PRIMARY KEY CLUSTERED ([PMPERMITTYPEIPUNITTYPEID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PMUNITTYPE_IPUNITTYPE] FOREIGN KEY ([IPUNITTYPEID]) REFERENCES [dbo].[IPUNITTYPE] ([IPUNITTYPEID]),
    CONSTRAINT [FK_PMUNITTYPE_PMPERMITTYPE] FOREIGN KEY ([PMPERMITTYPEID]) REFERENCES [dbo].[PMPERMITTYPE] ([PMPERMITTYPEID]),
    CONSTRAINT [FK_PMUNITTYPE_PMWORKCLASS] FOREIGN KEY ([PMPERMITWORKCLASSID]) REFERENCES [dbo].[PMPERMITWORKCLASS] ([PMPERMITWORKCLASSID])
);


GO
CREATE TRIGGER [dbo].[TG_PMPERMITTYPEUNITTYPE_DELETE]  
    ON  [dbo].[PMPERMITTYPEUNITTYPE]
   AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
	(
		[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
	)
	SELECT
		[PMPERMITTYPE].[PMPERMITTYPEID],
		[PMPERMITTYPE].[ROWVERSION],
		GETUTCDATE(),			
		(SELECT dbo.UFN_GET_USERID_FROM_CONTEXT_INFO()),
		'Permit Type Allowed Unit Type Deleted',
        '',
        '',       
		'Permit Type (' + [PMPERMITTYPE].[NAME] + '), Work Class Name (' + ISNULL([PMPERMITWORKCLASS].[NAME],'[none]') +'), Allowed Unit Type (' + [IPUNITTYPE].[NAME] +')',
		'4976A4A9-20E8-4B8F-997D-CE244B540104',
		3,
		0,
		[IPUNITTYPE].[NAME]
    FROM [deleted]
	INNER JOIN [PMPERMITTYPE] ON [PMPERMITTYPE].[PMPERMITTYPEID] = [deleted].[PMPERMITTYPEID]
	INNER JOIN [IPUNITTYPE] WITH (NOLOCK) ON [IPUNITTYPE].[IPUNITTYPEID] = [deleted].[IPUNITTYPEID]
	LEFT JOIN [PMPERMITWORKCLASS] WITH (NOLOCK) ON [PMPERMITWORKCLASS].[PMPERMITWORKCLASSID] = [deleted].[PMPERMITWORKCLASSID]
	
END
GO
CREATE TRIGGER [dbo].[TG_PMPERMITTYPEUNITTYPE_INSERT]
   ON  [dbo].[PMPERMITTYPEUNITTYPE]
   AFTER INSERT
AS 
BEGIN	
	SET NOCOUNT ON;	
	INSERT INTO [HISTORYSYSTEMSETUP]
    (
        [ID],
        [ROWVERSION],
        [CHANGEDON],
        [CHANGEDBY],
        [FIELDNAME],
        [OLDVALUE],
        [NEWVALUE],
        [ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT 
        [PMPERMITTYPE].[PMPERMITTYPEID], 
        [PMPERMITTYPE].[ROWVERSION],
        GETUTCDATE(),
        [PMPERMITTYPE].[LASTCHANGEDBY],	
        'Permit Type Allowed Unit Type Added',
        '',
        '',       
		'Permit Type (' + [PMPERMITTYPE].[NAME] + '), Work Class Name (' + ISNULL([PMPERMITWORKCLASS].[NAME],'[none]') +'), Allowed Unit Type (' + [IPUNITTYPE].[NAME] +')',
		'4976A4A9-20E8-4B8F-997D-CE244B540104',
		1,
		0,
		[IPUNITTYPE].[NAME]
    FROM [inserted]
	INNER JOIN [PMPERMITTYPE] ON [PMPERMITTYPE].[PMPERMITTYPEID] = [inserted].[PMPERMITTYPEID]
	INNER JOIN [IPUNITTYPE] WITH (NOLOCK) ON [IPUNITTYPE].[IPUNITTYPEID] = [inserted].[IPUNITTYPEID]
	LEFT JOIN [PMPERMITWORKCLASS] WITH (NOLOCK) ON [PMPERMITWORKCLASS].[PMPERMITWORKCLASSID] = [inserted].[PMPERMITWORKCLASSID]
	
END
GO
CREATE TRIGGER [dbo].[TG_PMPERMITTYPEUNITTYPE_UPDATE]
   ON  [dbo].[PMPERMITTYPEUNITTYPE] 
   AFTER UPDATE
AS 
BEGIN	
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
    (	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT 
			[PMPERMITTYPE].[PMPERMITTYPEID],
			[PMPERMITTYPE].[ROWVERSION],
			GETUTCDATE(),
			[PMPERMITTYPE].[LASTCHANGEDBY],
			'Required Flag',
			CASE [deleted].[ISREQUIRED] WHEN 1 THEN 'Yes' WHEN 0 THEN 'No' END,
			CASE [inserted].[ISREQUIRED] WHEN 1 THEN 'Yes' WHEN 0 THEN 'No' END,
			'Permit Type (' + [PMPERMITTYPE].[NAME] + '), Work Class Name (' + ISNULL([PMPERMITWORKCLASS].[NAME],'[none]') +'), Allowed Unit Type (' + [IPUNITTYPE].[NAME] +')',
			'4976A4A9-20E8-4B8F-997D-CE244B540104',
			2,
			0,
			[IPUNITTYPE].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[PMPERMITTYPEIPUNITTYPEID] = [inserted].[PMPERMITTYPEIPUNITTYPEID]
			INNER JOIN [PMPERMITTYPE] ON [PMPERMITTYPE].[PMPERMITTYPEID] = [inserted].[PMPERMITTYPEID]			
			INNER JOIN [IPUNITTYPE] WITH (NOLOCK) ON [IPUNITTYPE].[IPUNITTYPEID] = [inserted].[IPUNITTYPEID]			
			LEFT JOIN [PMPERMITWORKCLASS] WITH (NOLOCK) ON [PMPERMITWORKCLASS].[PMPERMITWORKCLASSID] = [inserted].[PMPERMITWORKCLASSID]
	WHERE	[deleted].[ISREQUIRED] <> [inserted].[ISREQUIRED]
	UNION ALL
	SELECT 
			[PMPERMITTYPE].[PMPERMITTYPEID],
			[PMPERMITTYPE].[ROWVERSION],
			GETUTCDATE(),
			[PMPERMITTYPE].[LASTCHANGEDBY],
			'Unit Type Set',
			ISNULL(CONVERT(NVARCHAR(MAX), [deleted].[UNITTYPEGROUP]),'[none]'),
			ISNULL(CONVERT(NVARCHAR(MAX), [inserted].[UNITTYPEGROUP]),'[none]'),			
			'Permit Type (' + [PMPERMITTYPE].[NAME] + '), Work Class Name (' + ISNULL([PMPERMITWORKCLASS].[NAME],'[none]') +'), Allowed Unit Type (' + [IPUNITTYPE].[NAME] +')',
			'4976A4A9-20E8-4B8F-997D-CE244B540104',
			2,
			0,
			[IPUNITTYPE].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[PMPERMITTYPEIPUNITTYPEID] = [inserted].[PMPERMITTYPEIPUNITTYPEID]
			INNER JOIN [PMPERMITTYPE] ON [PMPERMITTYPE].[PMPERMITTYPEID] = [inserted].[PMPERMITTYPEID]			
			INNER JOIN [IPUNITTYPE] WITH (NOLOCK) ON [IPUNITTYPE].[IPUNITTYPEID] = [inserted].[IPUNITTYPEID]			
			LEFT JOIN [PMPERMITWORKCLASS] WITH (NOLOCK) ON [PMPERMITWORKCLASS].[PMPERMITWORKCLASSID] = [inserted].[PMPERMITWORKCLASSID]
	WHERE	ISNULL([deleted].[UNITTYPEGROUP],'') <> ISNULL([inserted].[UNITTYPEGROUP],'')
	
END