CREATE TABLE [dbo].[PMPERMITGISFEATURE] (
    [PMPERMITGISFEATUREID] CHAR (36)     NOT NULL,
    [FEATURELAYER]         VARCHAR (100) NOT NULL,
    [ATTRIBUTEFIELD]       VARCHAR (50)  NULL,
    [KEYVALUE]             VARCHAR (50)  NOT NULL,
    [PMPERMITID]           CHAR (36)     NOT NULL,
    CONSTRAINT [PK_PMPermitGISFeatures] PRIMARY KEY CLUSTERED ([PMPERMITGISFEATUREID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PMPermitGISFeature_PMPermit] FOREIGN KEY ([PMPERMITID]) REFERENCES [dbo].[PMPERMIT] ([PMPERMITID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PRMGISFEAT_PERMIT_ALL]
    ON [dbo].[PMPERMITGISFEATURE]([PMPERMITID] ASC)
    INCLUDE([ATTRIBUTEFIELD], [FEATURELAYER], [KEYVALUE]) WITH (FILLFACTOR = 90);

