CREATE TABLE [dbo].[PMPERMITBOND] (
    [PMPERMITBONDID] CHAR (36) NOT NULL,
    [PMPERMITID]     CHAR (36) NOT NULL,
    [BONDID]         CHAR (36) NOT NULL,
    [CREATEDBY]      CHAR (36) NULL,
    [CREATEDATE]     DATETIME  NULL,
    CONSTRAINT [PK_PMPermitBond] PRIMARY KEY CLUSTERED ([PMPERMITBONDID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PMPermitBond_Bond] FOREIGN KEY ([BONDID]) REFERENCES [dbo].[BOND] ([BONDID]),
    CONSTRAINT [FK_PMPermitBond_PMPermit] FOREIGN KEY ([PMPERMITID]) REFERENCES [dbo].[PMPERMIT] ([PMPERMITID]),
    CONSTRAINT [FK_PMPermitBond_Users] FOREIGN KEY ([CREATEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);


GO
CREATE NONCLUSTERED INDEX [NCIDX1_PMPERMITBOND_BONDID]
    ON [dbo].[PMPERMITBOND]([BONDID] ASC)
    INCLUDE([PMPERMITID]);

