CREATE TABLE [dbo].[PMPERMITWFSTEP] (
    [PMPERMITWFSTEPID]       CHAR (36)       NOT NULL,
    [PMPERMITID]             CHAR (36)       NOT NULL,
    [WFSTEPTYPEID]           INT             NOT NULL,
    [PRIORITYORDER]          INT             NOT NULL,
    [STARTDATE]              DATETIME        NULL,
    [ENDDATE]                DATETIME        NULL,
    [DESCRIPTION]            NVARCHAR (MAX)  NULL,
    [WORKFLOWSTATUSID]       INT             NOT NULL,
    [ROWVERSION]             INT             NOT NULL,
    [LASTCHANGEDON]          DATETIME        NOT NULL,
    [LASTCHANGEDBY]          CHAR (36)       NOT NULL,
    [REQUIREDSUBPLPLANID]    CHAR (36)       NULL,
    [NAME]                   NVARCHAR (100)  NOT NULL,
    [WORKFLOWCOMPLETETYPEID] INT             NULL,
    [ICON]                   VARBINARY (MAX) NULL,
    [DAYSTOCOMPLETE]         INT             NULL,
    [PMPERMITWFPARENTSTEPID] CHAR (36)       NULL,
    [VERSIONNUMBER]          INT             NULL,
    [SORTORDER]              INT             DEFAULT ((0)) NOT NULL,
    [GENERALREASON]          NVARCHAR (MAX)  NULL,
    [AUTOCOMPLETED]          BIT             CONSTRAINT [DF_PMPermitWFStep_StepAutoCompleted] DEFAULT ((0)) NOT NULL,
    [WFTEMPLATESTEPID]       CHAR (36)       NULL,
    [NOPRIORITY]             BIT             DEFAULT ((0)) NOT NULL,
    [DUEDATE]                DATETIME        NULL,
    [IDENTITYCOLUMN]         BIGINT          IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_PMPermitWFStep] PRIMARY KEY NONCLUSTERED ([PMPERMITWFSTEPID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_PMPermitWFStep_PMPermit] FOREIGN KEY ([PMPERMITID]) REFERENCES [dbo].[PMPERMIT] ([PMPERMITID]),
    CONSTRAINT [FK_PMPermitWFStep_Type] FOREIGN KEY ([WFSTEPTYPEID]) REFERENCES [dbo].[WFSTEPTYPE] ([WFSTEPTYPEID]),
    CONSTRAINT [FK_PMPermitWFStep_Users] FOREIGN KEY ([LASTCHANGEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID]),
    CONSTRAINT [FK_Step_ParentStep] FOREIGN KEY ([PMPERMITWFPARENTSTEPID]) REFERENCES [dbo].[PMPERMITWFSTEP] ([PMPERMITWFSTEPID]),
    CONSTRAINT [FK_Step_WFCompleteType] FOREIGN KEY ([WORKFLOWCOMPLETETYPEID]) REFERENCES [dbo].[WORKFLOWCOMPLETETYPE] ([WORKFLOWCOMPLETETYPEID]),
    CONSTRAINT [FK_Step_WorkflowStatus] FOREIGN KEY ([WORKFLOWSTATUSID]) REFERENCES [dbo].[WORKFLOWSTATUS] ([WORKFLOWSTATUSID])
);


GO
CREATE CLUSTERED INDEX [CLIDX_PMPERMITWFNSTEP_IDCOL]
    ON [dbo].[PMPERMITWFSTEP]([IDENTITYCOLUMN] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IMPORT1]
    ON [dbo].[PMPERMITWFSTEP]([PMPERMITID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IMPORT3]
    ON [dbo].[PMPERMITWFSTEP]([WFSTEPTYPEID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [NCIDX1_PMPERMITWFACTIONSTEP_PMPERMITID_PMPERMITWFACTIONSTEPID]
    ON [dbo].[PMPERMITWFSTEP]([PMPERMITID] ASC, [PMPERMITWFSTEPID] ASC);

