CREATE TABLE [dbo].[PMPERMITFEE] (
    [PMPERMITFEEID]   CHAR (36) NOT NULL,
    [PMPERMITID]      CHAR (36) NOT NULL,
    [CACOMPUTEDFEEID] CHAR (36) NOT NULL,
    [CREATEDON]       DATETIME  NOT NULL,
    CONSTRAINT [PK_PMPermitFee] PRIMARY KEY NONCLUSTERED ([PMPERMITFEEID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_PMPermitFee_ComputedFee] FOREIGN KEY ([CACOMPUTEDFEEID]) REFERENCES [dbo].[CACOMPUTEDFEE] ([CACOMPUTEDFEEID]),
    CONSTRAINT [FK_PMPermitFee_PMPermit] FOREIGN KEY ([PMPERMITID]) REFERENCES [dbo].[PMPERMIT] ([PMPERMITID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PMPermitFee_Permit]
    ON [dbo].[PMPERMITFEE]([PMPERMITID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IX_PMPERMITFEE_COMP_FEE]
    ON [dbo].[PMPERMITFEE]([CACOMPUTEDFEEID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [PMFIDX1]
    ON [dbo].[PMPERMITFEE]([CACOMPUTEDFEEID] ASC)
    INCLUDE([PMPERMITID]);

