CREATE TABLE [dbo].[PMPERMITADDRESS] (
    [PMPERMITADDRESSID] CHAR (36) NOT NULL,
    [PMPERMITID]        CHAR (36) NOT NULL,
    [MAILINGADDRESSID]  CHAR (36) NOT NULL,
    [MAIN]              BIT       NOT NULL,
    CONSTRAINT [PK_PMPermitAddress] PRIMARY KEY CLUSTERED ([PMPERMITADDRESSID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_PMPermitAddress_Address] FOREIGN KEY ([MAILINGADDRESSID]) REFERENCES [dbo].[MAILINGADDRESS] ([MAILINGADDRESSID]),
    CONSTRAINT [FK_PMPermitAddress_PMPermit] FOREIGN KEY ([PMPERMITID]) REFERENCES [dbo].[PMPERMIT] ([PMPERMITID])
);


GO
CREATE NONCLUSTERED INDEX [IMPORT1]
    ON [dbo].[PMPERMITADDRESS]([MAILINGADDRESSID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IMPORT2]
    ON [dbo].[PMPERMITADDRESS]([PMPERMITID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IX_PMPERMITADDRESS_MAIN]
    ON [dbo].[PMPERMITADDRESS]([MAIN] ASC, [PMPERMITID] ASC)
    INCLUDE([PMPERMITADDRESSID], [MAILINGADDRESSID]);

