CREATE TABLE [dbo].[PMRENEWALCASETYPE] (
    [PMRENEWALCASETYPEID]        CHAR (36)      NOT NULL,
    [NAME]                       NVARCHAR (MAX) NOT NULL,
    [PREFIX]                     NVARCHAR (MAX) NULL,
    [INVOICEDAYSINADVANCE]       INT            NOT NULL,
    [SUCCESSFULLRENEWALSTATUSID] CHAR (36)      NOT NULL,
    [FAILEDRENEWALSTATUSID]      CHAR (36)      NOT NULL,
    [ACTIVE]                     BIT            NOT NULL,
    [DESCRIPTION]                NVARCHAR (MAX) NULL,
    [RECURRENCEID]               CHAR (36)      NULL,
    [LASTCHANGEDBY]              CHAR (36)      NULL,
    [LASTCHANGEDON]              DATETIME       CONSTRAINT [DF_PMRENEWALCASETYPE_LastChangedOn] DEFAULT (getutcdate()) NOT NULL,
    [ROWVERSION]                 INT            CONSTRAINT [DF_PMRENEWALCASETYPE_RowVersion] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_PMRENEWALCASETYPE] PRIMARY KEY CLUSTERED ([PMRENEWALCASETYPEID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PMRENEWALCASETYPE_USERS] FOREIGN KEY ([LASTCHANGEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID]),
    CONSTRAINT [FK_PMRENEWALTYPE_RECURR] FOREIGN KEY ([RECURRENCEID]) REFERENCES [dbo].[RECURRENCE] ([RECURRENCEID]),
    CONSTRAINT [FK_RENEWALCASE_SUCCESS] FOREIGN KEY ([SUCCESSFULLRENEWALSTATUSID]) REFERENCES [dbo].[PMPERMITSTATUS] ([PMPERMITSTATUSID]),
    CONSTRAINT [FK_RENEWALCASET_FAILED] FOREIGN KEY ([FAILEDRENEWALSTATUSID]) REFERENCES [dbo].[PMPERMITSTATUS] ([PMPERMITSTATUSID])
);


GO
CREATE TRIGGER [TG_PMRENEWALCASETYPE_DELETE] ON PMRENEWALCASETYPE
   AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [HISTORYSYSTEMSETUP]
    (	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )

	SELECT
			[deleted].[PMRENEWALCASETYPEID],
			[deleted].[ROWVERSION],
			GETUTCDATE(),
			(SELECT dbo.UFN_GET_USERID_FROM_CONTEXT_INFO()),
			'Renewal Case Type Deleted',
			'',
			'',
			'Renewal Case Type (' + [deleted].[NAME] + ')',
			'90DD4132-DB24-44AA-A06F-F09DE3113E72',
			3,
			1,
			[deleted].[NAME]
	FROM	[deleted]
END
GO

CREATE TRIGGER [TG_PMRENEWALCASETYPE_INSERT] ON PMRENEWALCASETYPE
   FOR INSERT
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [HISTORYSYSTEMSETUP]
    (	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT
			[inserted].[PMRENEWALCASETYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Renewal Case Type Added',
			'',
			'',
			'Renewal Case Type (' + [inserted].[NAME] + ')',
			'90DD4132-DB24-44AA-A06F-F09DE3113E72',
			1,
			1,
			[inserted].[NAME]
	FROM	[inserted]	
END
GO
CREATE TRIGGER [dbo].[TG_PMRENEWALCASETYPE_UPDATE] ON [dbo].[PMRENEWALCASETYPE]
   AFTER UPDATE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [HISTORYSYSTEMSETUP]
    (	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT
			[inserted].[PMRENEWALCASETYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Case Type',
			[deleted].[NAME],
			[inserted].[NAME],
			'Renewal Case Type (' + [inserted].[NAME] + ')',
			'90DD4132-DB24-44AA-A06F-F09DE3113E72',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].PMRENEWALCASETYPEID = [inserted].PMRENEWALCASETYPEID
	WHERE	[deleted].[NAME] <> [inserted].[NAME]
	UNION ALL
	SELECT
			[inserted].[PMRENEWALCASETYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Prefix',
			 ISNULL([deleted].[PREFIX],'[none]'),
			 ISNULL([inserted].[PREFIX],'[none]'),			 
			'Renewal Case Type (' + [inserted].[NAME] + ')',
			'90DD4132-DB24-44AA-A06F-F09DE3113E72',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].PMRENEWALCASETYPEID = [inserted].PMRENEWALCASETYPEID
	WHERE	ISNULL([deleted].[PREFIX], '') <> ISNULL([inserted].[PREFIX],'')
	UNION ALL
	SELECT
			[inserted].[PMRENEWALCASETYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Invoice Days In Advance',
			CAST([deleted].[INVOICEDAYSINADVANCE] AS NVARCHAR(MAX)),
			CAST([inserted].[INVOICEDAYSINADVANCE] AS NVARCHAR(MAX)),
			'Renewal Case Type (' + [inserted].[NAME] + ')',
			'90DD4132-DB24-44AA-A06F-F09DE3113E72',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].PMRENEWALCASETYPEID = [inserted].PMRENEWALCASETYPEID
	WHERE	[deleted].[INVOICEDAYSINADVANCE]<> [inserted].[INVOICEDAYSINADVANCE]
	UNION ALL
	SELECT
			[inserted].[PMRENEWALCASETYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Success Status',
			PMPERMITSTATUS_DELETED.[NAME],
			PMPERMITSTATUS_INSERTED.[NAME],
			'Renewal Case Type (' + [inserted].[NAME] + ')',
			'90DD4132-DB24-44AA-A06F-F09DE3113E72',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].PMRENEWALCASETYPEID = [inserted].PMRENEWALCASETYPEID
			INNER JOIN [PMPERMITSTATUS](NOLOCK) PMPERMITSTATUS_INSERTED   ON PMPERMITSTATUS_INSERTED.PMPERMITSTATUSID = [inserted].SUCCESSFULLRENEWALSTATUSID
			INNER JOIN [PMPERMITSTATUS](NOLOCK) PMPERMITSTATUS_DELETED  ON PMPERMITSTATUS_DELETED.PMPERMITSTATUSID= [deleted].SUCCESSFULLRENEWALSTATUSID
	WHERE	[deleted].[SUCCESSFULLRENEWALSTATUSID]<> [inserted].[SUCCESSFULLRENEWALSTATUSID]	
	UNION ALL
	SELECT
			[inserted].[PMRENEWALCASETYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Failed Status',
			PMPERMITSTATUS_DELETED.[NAME],
			PMPERMITSTATUS_INSERTED.[NAME],
			'Renewal Case Type (' + [inserted].[NAME] + ')',
			'90DD4132-DB24-44AA-A06F-F09DE3113E72',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].PMRENEWALCASETYPEID = [inserted].PMRENEWALCASETYPEID
			INNER JOIN [PMPERMITSTATUS](NOLOCK) PMPERMITSTATUS_INSERTED   ON PMPERMITSTATUS_INSERTED.PMPERMITSTATUSID = [inserted].FAILEDRENEWALSTATUSID
			INNER JOIN [PMPERMITSTATUS](NOLOCK) PMPERMITSTATUS_DELETED  ON PMPERMITSTATUS_DELETED.PMPERMITSTATUSID= [deleted].FAILEDRENEWALSTATUSID
	WHERE	[deleted].[FAILEDRENEWALSTATUSID]<> [inserted].[FAILEDRENEWALSTATUSID]	
	UNION ALL
	SELECT
			[inserted].[PMRENEWALCASETYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Active Flag',
			CASE WHEN [deleted].[ACTIVE] = 1 THEN 'Yes' ELSE 'No' END,
			CASE WHEN [inserted].[ACTIVE] = 1 THEN 'Yes' ELSE 'No' END,
			'Renewal Case Type (' + [inserted].[NAME] + ')',
			'90DD4132-DB24-44AA-A06F-F09DE3113E72',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].PMRENEWALCASETYPEID = [inserted].PMRENEWALCASETYPEID
	WHERE	[deleted].[ACTIVE]<> [inserted].[ACTIVE]	
	UNION ALL
	SELECT
			[inserted].[PMRENEWALCASETYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Description',
			ISNULL([deleted].[DESCRIPTION],'[none]'),
			ISNULL([inserted].[DESCRIPTION],'[none]'),
			'Renewal Case Type (' + [inserted].[NAME] + ')',
			'90DD4132-DB24-44AA-A06F-F09DE3113E72',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[PMRENEWALCASETYPEID] = [inserted].[PMRENEWALCASETYPEID]
	WHERE	ISNULL([deleted].[DESCRIPTION], '') <> ISNULL([inserted].[DESCRIPTION], '')
	UNION ALL
	SELECT
			[inserted].[PMRENEWALCASETYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Recurrence Cycle',
			ISNULL([RECURRENCE_DELETED].[NAME],'[none]'),
			ISNULL([RECURRENCE_INSERTED].[NAME],'[none]'),
			'Renewal Case Type (' + [inserted].[NAME] + ')',
			'90DD4132-DB24-44AA-A06F-F09DE3113E72',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[PMRENEWALCASETYPEID] = [inserted].[PMRENEWALCASETYPEID]
			LEFT JOIN [RECURRENCE](NOLOCK) RECURRENCE_INSERTED   ON RECURRENCE_INSERTED.RECURRENCEID = [inserted].RECURRENCEID
			LEFT JOIN [RECURRENCE](NOLOCK) RECURRENCE_DELETED  ON RECURRENCE_DELETED.RECURRENCEID= [deleted].RECURRENCEID
	WHERE	ISNULL([deleted].[RECURRENCEID], '') <> ISNULL([inserted].[RECURRENCEID], '')
END