CREATE TABLE [dbo].[PMRENEWALLOG] (
    [PMRENEWALLOGID]      CHAR (36)      NOT NULL,
    [PMRENEWALLOGTYPEID]  INT            NOT NULL,
    [PMRENEWALCASEID]     CHAR (36)      NOT NULL,
    [PMRENEWALCASENUMBER] NVARCHAR (MAX) NOT NULL,
    [PMPERMITID]          CHAR (36)      NULL,
    [PMPERMITNUMBER]      NVARCHAR (MAX) NULL,
    [INVALIDFIELDS]       NVARCHAR (MAX) NULL,
    [CAINVOICEID]         CHAR (36)      NULL,
    [CAINVOICENUMBER]     NVARCHAR (MAX) NULL,
    [ERROR]               NVARCHAR (MAX) NULL,
    [TIMESTAMP]           DATETIME       NOT NULL,
    [RENEWAL_ITERATOR]    NUMERIC (18)   NOT NULL,
    CONSTRAINT [PK_PMRENEWALLOG] PRIMARY KEY CLUSTERED ([PMRENEWALLOGID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_RENEWALLOG_RENEWALLOGTYPE] FOREIGN KEY ([PMRENEWALLOGTYPEID]) REFERENCES [dbo].[PMRENEWALLOGTYPE] ([PMRENEWALLOGTYPEID])
);

