CREATE TABLE [dbo].[PMRENEWALLOGTYPE] (
    [PMRENEWALLOGTYPEID] INT            NOT NULL,
    [TYPE]               NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_PMRENEWALLOGTYPE] PRIMARY KEY CLUSTERED ([PMRENEWALLOGTYPEID] ASC) WITH (FILLFACTOR = 90)
);

