CREATE TABLE [dbo].[PMWCCERTCLASS] (
    [PMPERMITTYPELICENSETYPEID] CHAR (36) NOT NULL,
    [ILLICENSECLASSIFICATIONID] CHAR (36) NOT NULL,
    CONSTRAINT [PK_PMWCCertClass] PRIMARY KEY CLUSTERED ([PMPERMITTYPELICENSETYPEID] ASC, [ILLICENSECLASSIFICATIONID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PMWC_Class] FOREIGN KEY ([ILLICENSECLASSIFICATIONID]) REFERENCES [dbo].[ILLICENSECLASSIFICATION] ([ILLICENSECLASSIFICATIONID]),
    CONSTRAINT [FK_PMWC_ptCerttype] FOREIGN KEY ([PMPERMITTYPELICENSETYPEID]) REFERENCES [dbo].[PMPERMITTYPELICENSETYPE] ([PMPERMITTYPELICENSETYPEID])
);


GO
CREATE TRIGGER [dbo].[TG_PMWCCERTCLASS_INSERT]
   ON  [dbo].[PMWCCERTCLASS]
   AFTER INSERT
AS 
BEGIN	
	SET NOCOUNT ON;	
	INSERT INTO [HISTORYSYSTEMSETUP]
    (
        [ID],
        [ROWVERSION],
        [CHANGEDON],
        [CHANGEDBY],
        [FIELDNAME],
        [OLDVALUE],
        [NEWVALUE],
        [ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT 
        [PMPERMITTYPE].[PMPERMITTYPEID], 
        [PMPERMITTYPE].[ROWVERSION],
        GETUTCDATE(),
        [PMPERMITTYPE].[LASTCHANGEDBY],	
        'Permit Type Classification Added',
        '',
        '',       
		'Permit Type (' + [PMPERMITTYPE].[NAME] + '), Work Class Name (' + [PMPERMITWORKCLASS].[NAME] +'), Certification (' + [COLICENSECERTIFICATIONTYPE].[NAME]+'), Classification (' + [ILLICENSECLASSIFICATION].[NAME] +')',
		'4976A4A9-20E8-4B8F-997D-CE244B540104',
		1,
		0,
		[ILLICENSECLASSIFICATION].[NAME]
    FROM [inserted]	
 	INNER JOIN [PMPERMITTYPELICENSETYPE] ON [PMPERMITTYPELICENSETYPE].[PMPERMITTYPELICENSETYPEID] = [inserted].[PMPERMITTYPELICENSETYPEID]
	INNER JOIN [PMPERMITTYPE] ON [PMPERMITTYPE].[PMPERMITTYPEID] = [PMPERMITTYPELICENSETYPE].[PMPERMITTYPEID]
	INNER JOIN [ILLICENSECLASSIFICATION] WITH (NOLOCK) ON [ILLICENSECLASSIFICATION].[ILLICENSECLASSIFICATIONID] = [inserted].[ILLICENSECLASSIFICATIONID]
	INNER JOIN [COLICENSECERTIFICATIONTYPE] WITH (NOLOCK) ON [COLICENSECERTIFICATIONTYPE].[COSIMPLELICCERTTYPEID] = [PMPERMITTYPELICENSETYPE].[COSIMPLELICCERTTYPEID]
	LEFT JOIN [PMPERMITWORKCLASS] WITH (NOLOCK) ON [PMPERMITWORKCLASS].[PMPERMITWORKCLASSID] = [PMPERMITTYPELICENSETYPE].[PMPERMITWORKCLASSID] 
END
GO
CREATE TRIGGER [dbo].[TG_PMWCCERTCLASS_DELETE]  
    ON  [dbo].[PMWCCERTCLASS]
   AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
	(
		[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
	)
	SELECT
		[PMPERMITTYPE].[PMPERMITTYPEID],
		[PMPERMITTYPE].[ROWVERSION],
		GETUTCDATE(),			
		(SELECT dbo.UFN_GET_USERID_FROM_CONTEXT_INFO()),
		'Permit Type Classification Deleted',
        '',
        '',       
		'Permit Type (' + [PMPERMITTYPE].[NAME] + '), Work Class Name (' + [PMPERMITWORKCLASS].[NAME]+'), Certification (' + [COLICENSECERTIFICATIONTYPE].[NAME] +'), Classification (' + [ILLICENSECLASSIFICATION].[NAME] +')',
		'4976A4A9-20E8-4B8F-997D-CE244B540104',
		3,
		0,
		[ILLICENSECLASSIFICATION].[NAME]
    FROM [deleted]
	INNER JOIN [PMPERMITTYPELICENSETYPE] WITH (NOLOCK) ON [PMPERMITTYPELICENSETYPE].[PMPERMITTYPELICENSETYPEID] = [deleted].[PMPERMITTYPELICENSETYPEID]
	INNER JOIN [PMPERMITTYPE] ON [PMPERMITTYPE].[PMPERMITTYPEID] = [PMPERMITTYPELICENSETYPE].[PMPERMITTYPEID]
	INNER JOIN [ILLICENSECLASSIFICATION] WITH (NOLOCK) ON [ILLICENSECLASSIFICATION].[ILLICENSECLASSIFICATIONID] = [deleted].[ILLICENSECLASSIFICATIONID]
	INNER JOIN [COLICENSECERTIFICATIONTYPE] WITH (NOLOCK) ON [COLICENSECERTIFICATIONTYPE].[COSIMPLELICCERTTYPEID] = [PMPERMITTYPELICENSETYPE].[COSIMPLELICCERTTYPEID]
	LEFT JOIN [PMPERMITWORKCLASS] WITH (NOLOCK) ON [PMPERMITWORKCLASS].[PMPERMITWORKCLASSID] = [PMPERMITTYPELICENSETYPE].[PMPERMITWORKCLASSID] 
END