CREATE TABLE [dbo].[PRPROJECTPLANORDER] (
    [PRPROJECTPLANORDERID] CHAR (36) NOT NULL,
    [PRPROJECTID]          CHAR (36) NOT NULL,
    [PLPLANTYPEID]         CHAR (36) NOT NULL,
    [PLPLANWORKCLASSID]    CHAR (36) NULL,
    [PLANORDER]            INT       NOT NULL,
    CONSTRAINT [PK_PRProjectPlanOrder] PRIMARY KEY CLUSTERED ([PRPROJECTPLANORDERID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PRProjectPlanOrder_PLPlanType] FOREIGN KEY ([PLPLANTYPEID]) REFERENCES [dbo].[PLPLANTYPE] ([PLPLANTYPEID]),
    CONSTRAINT [FK_PRProjectPlanOrder_PLPlanWorkClass] FOREIGN KEY ([PLPLANWORKCLASSID]) REFERENCES [dbo].[PLPLANWORKCLASS] ([PLPLANWORKCLASSID]),
    CONSTRAINT [FK_PRProjectPlanOrder_PRProject] FOREIGN KEY ([PRPROJECTID]) REFERENCES [dbo].[PRPROJECT] ([PRPROJECTID])
);

