CREATE TABLE [dbo].[PRPROJECTPERMIT] (
    [PRPROJECTPERMITID] CHAR (36) NOT NULL,
    [PRPROJECTID]       CHAR (36) NOT NULL,
    [PMPERMITID]        CHAR (36) NOT NULL,
    CONSTRAINT [PK_PRProjectPermit] PRIMARY KEY CLUSTERED ([PRPROJECTPERMITID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PRProjectPermit_PMPermit] FOREIGN KEY ([PMPERMITID]) REFERENCES [dbo].[PMPERMIT] ([PMPERMITID]),
    CONSTRAINT [FK_PRProjectPermit_PRProject] FOREIGN KEY ([PRPROJECTID]) REFERENCES [dbo].[PRPROJECT] ([PRPROJECTID])
);


GO
CREATE NONCLUSTERED INDEX [PRPROJECTPERMIT_IX_PERMIT]
    ON [dbo].[PRPROJECTPERMIT]([PMPERMITID] ASC, [PRPROJECTID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [NCIDX_PRPROJECTPERMIT_PMPERMITID_INCL]
    ON [dbo].[PRPROJECTPERMIT]([PMPERMITID] ASC)
    INCLUDE([PRPROJECTID]) WITH (FILLFACTOR = 90, PAD_INDEX = ON);


GO
CREATE NONCLUSTERED INDEX [IDX_PRPROJECTPERMIT_PROJECTID_PERMITID]
    ON [dbo].[PRPROJECTPERMIT]([PRPROJECTID] ASC, [PMPERMITID] ASC);

