CREATE TABLE [dbo].[PRPROJECTCONDITION] (
    [PRPROJECTCONDITIONID] CHAR (36)   NOT NULL,
    [CONDITIONID]          CHAR (36)   NOT NULL,
    [PRPROJECTID]          CHAR (36)   NOT NULL,
    [CONDITIONSCOPEID]     INT         NOT NULL,
    [CREATEDON]            DATETIME    NULL,
    [ISSATISFIED]          BIT         DEFAULT ((0)) NOT NULL,
    [ORDER]                VARCHAR (5) NULL,
    [CREATEDBY]            CHAR (36)   NULL,
    CONSTRAINT [PK_PRProjectCondition] PRIMARY KEY CLUSTERED ([PRPROJECTCONDITIONID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PRProjectCondition_Condition] FOREIGN KEY ([CONDITIONID]) REFERENCES [dbo].[CONDITION] ([CONDITIONID]),
    CONSTRAINT [FK_PRProjectCondition_ConditionScope] FOREIGN KEY ([CONDITIONSCOPEID]) REFERENCES [dbo].[CONDITIONSCOPE] ([CONDITIONSCOPEID]),
    CONSTRAINT [FK_PRProjectCondition_PRProject] FOREIGN KEY ([PRPROJECTID]) REFERENCES [dbo].[PRPROJECT] ([PRPROJECTID]),
    CONSTRAINT [FK_PRPROJECTCONDITION_USERS] FOREIGN KEY ([CREATEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);

