CREATE TABLE [dbo].[PRPROJECTADDRESS] (
    [PRPROJECTADDRESSID] CHAR (36) NOT NULL,
    [PRPROJECTID]        CHAR (36) NOT NULL,
    [MAILINGADDRESSID]   CHAR (36) NOT NULL,
    [MAIN]               BIT       NOT NULL,
    CONSTRAINT [PK_PRProjectAddress] PRIMARY KEY CLUSTERED ([PRPROJECTADDRESSID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PRProjectAddress_MailingAddress] FOREIGN KEY ([MAILINGADDRESSID]) REFERENCES [dbo].[MAILINGADDRESS] ([MAILINGADDRESSID]),
    CONSTRAINT [FK_PRProjectAddress_PRProject] FOREIGN KEY ([PRPROJECTID]) REFERENCES [dbo].[PRPROJECT] ([PRPROJECTID])
);

