CREATE TABLE [dbo].[PRPROJECTPERMITLIMIT] (
    [PRPROJECTPERMITLIMITID] CHAR (36) NOT NULL,
    [PRPROJECTID]            CHAR (36) NOT NULL,
    [PMPERMITTYPEID]         CHAR (36) NOT NULL,
    [PMPERMITWORKCLASSID]    CHAR (36) NOT NULL,
    [PERMITLIMIT]            INT       NOT NULL,
    CONSTRAINT [PK_PRProjectPermitLimit] PRIMARY KEY CLUSTERED ([PRPROJECTPERMITLIMITID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PRProjectPermitLimit_PMPermitType] FOREIGN KEY ([PMPERMITTYPEID]) REFERENCES [dbo].[PMPERMITTYPE] ([PMPERMITTYPEID]),
    CONSTRAINT [FK_PRProjectPermitLimit_PMPermitWorkClass] FOREIGN KEY ([PMPERMITWORKCLASSID]) REFERENCES [dbo].[PMPERMITWORKCLASS] ([PMPERMITWORKCLASSID]),
    CONSTRAINT [FK_PRProjectPermitLimit_PRProject] FOREIGN KEY ([PRPROJECTID]) REFERENCES [dbo].[PRPROJECT] ([PRPROJECTID])
);


GO
CREATE NONCLUSTERED INDEX [PRPROJECTPERMITLIMIT_IX_PERMITYPE_WORKCLASS]
    ON [dbo].[PRPROJECTPERMITLIMIT]([PRPROJECTID] ASC, [PMPERMITTYPEID] ASC, [PMPERMITWORKCLASSID] ASC);

