CREATE TABLE [dbo].[PRPROJECTNOTE] (
    [PRPROJECTNOTEID] CHAR (36)      NOT NULL,
    [PRPROJECTID]     CHAR (36)      NOT NULL,
    [TEXT]            NVARCHAR (MAX) NULL,
    [CREATEDBY]       CHAR (36)      NULL,
    [CREATEDDATE]     DATETIME       NULL,
    [TITLE]           NVARCHAR (50)  CONSTRAINT [DF_PRPROJECTNOTE_TITLE] DEFAULT ('') NULL,
    [PIN]             BIT            CONSTRAINT [DF_PRPROJECTNOTE_PIN] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_PRProjectNote] PRIMARY KEY CLUSTERED ([PRPROJECTNOTEID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PRNote_PRProject] FOREIGN KEY ([PRPROJECTID]) REFERENCES [dbo].[PRPROJECT] ([PRPROJECTID]),
    CONSTRAINT [FK_PRProjectNote_Users] FOREIGN KEY ([CREATEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);

