CREATE TABLE [dbo].[PRPROJECTCODECASE] (
    [PRPROJECTCODECASEID] CHAR (36) NOT NULL,
    [CMCODECASEID]        CHAR (36) NOT NULL,
    [PRPROJECTID]         CHAR (36) NOT NULL,
    CONSTRAINT [PK_ProjectCodeCase] PRIMARY KEY CLUSTERED ([PRPROJECTCODECASEID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_ProjectCodeCase_CodeCase] FOREIGN KEY ([CMCODECASEID]) REFERENCES [dbo].[CMCODECASE] ([CMCODECASEID]),
    CONSTRAINT [FK_ProjectCodeCase_Project] FOREIGN KEY ([PRPROJECTID]) REFERENCES [dbo].[PRPROJECT] ([PRPROJECTID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PROJECT_CASE]
    ON [dbo].[PRPROJECTCODECASE]([CMCODECASEID] ASC, [PRPROJECTID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IDX_PRPROJECTCODECASE_PROJECTID_CODECASEID]
    ON [dbo].[PRPROJECTCODECASE]([PRPROJECTID] ASC, [CMCODECASEID] ASC);

