CREATE TABLE [dbo].[PRPROJECTAPPLICATION] (
    [PRPROJECTAPPLICATIONID] CHAR (36) NOT NULL,
    [PLAPPLICATIONID]        CHAR (36) NOT NULL,
    [PRPROJECTID]            CHAR (36) NOT NULL,
    CONSTRAINT [PK_PRProjectApplication] PRIMARY KEY CLUSTERED ([PRPROJECTAPPLICATIONID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PRProjectApplication_PLApplication] FOREIGN KEY ([PLAPPLICATIONID]) REFERENCES [dbo].[PLAPPLICATION] ([PLAPPLICATIONID]),
    CONSTRAINT [FK_PRProjectApplication_Project] FOREIGN KEY ([PRPROJECTID]) REFERENCES [dbo].[PRPROJECT] ([PRPROJECTID])
);

