CREATE TABLE [dbo].[PUPAYMENTTERM] (
    [PUPAYMENTTERMID] CHAR (36)     NOT NULL,
    [NAME]            VARCHAR (50)  NOT NULL,
    [DESCRIPTION]     VARCHAR (MAX) NULL,
    CONSTRAINT [PK_PUPaymentTerm] PRIMARY KEY CLUSTERED ([PUPAYMENTTERMID] ASC) WITH (FILLFACTOR = 90)
);

