CREATE TABLE [dbo].[PUPURCHASEORDERSTATUS] (
    [PUPURCHASEORDERSTATUSID] CHAR (36)     NOT NULL,
    [NAME]                    VARCHAR (50)  NOT NULL,
    [DESCRIPTION]             VARCHAR (MAX) NULL,
    [SYSTEMACTIONID]          CHAR (36)     NOT NULL,
    CONSTRAINT [PK_PUPurchaseOrderStatus] PRIMARY KEY CLUSTERED ([PUPURCHASEORDERSTATUSID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PUPurOrdStatus_SysAct] FOREIGN KEY ([SYSTEMACTIONID]) REFERENCES [dbo].[SYSTEMACTION] ([SYSTEMACTIONID])
);

