CREATE TABLE [dbo].[PUPURCHASEORDERLINETYPE] (
    [PUPURCHASEORDERLINETYPEID] CHAR (36)     NOT NULL,
    [NAME]                      VARCHAR (50)  NOT NULL,
    [DESCRIPTION]               VARCHAR (MAX) NULL,
    [SYSTEMACTIONID]            CHAR (36)     NOT NULL,
    CONSTRAINT [PK_PUPurchaseOrderLineType] PRIMARY KEY CLUSTERED ([PUPURCHASEORDERLINETYPEID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PUPurchaseOrderLineType_SystemAction] FOREIGN KEY ([SYSTEMACTIONID]) REFERENCES [dbo].[SYSTEMACTION] ([SYSTEMACTIONID])
);

