CREATE TABLE [dbo].[PUREQUISITION] (
    [PUREQUISITIONID]       CHAR (36)       NOT NULL,
    [PUREQUISITIONSTATUSID] CHAR (36)       NOT NULL,
    [REQUISITIONNO]         VARCHAR (50)    NOT NULL,
    [CREATEDDATE]           DATETIME        NOT NULL,
    [DESCRIPTION]           VARCHAR (MAX)   NULL,
    [REQUESTOR]             CHAR (36)       NOT NULL,
    [TOTALCOST]             DECIMAL (38, 5) NOT NULL,
    [PROJECTID]             CHAR (36)       NULL,
    [CUSTOMFIELDLAYOUT]     CHAR (36)       NULL,
    [ROWVERSION]            INT             NOT NULL,
    [LASTCHANGEDON]         DATETIME        NULL,
    [LASTCHANGEDBY]         CHAR (36)       NULL,
    CONSTRAINT [PK_PURequisition] PRIMARY KEY CLUSTERED ([PUREQUISITIONID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PUReq_CustomFieldLayout] FOREIGN KEY ([CUSTOMFIELDLAYOUT]) REFERENCES [dbo].[CUSTOMFIELDLAYOUT] ([GCUSTOMFIELDLAYOUTS]),
    CONSTRAINT [FK_PUReq_PUReqStatus] FOREIGN KEY ([PUREQUISITIONSTATUSID]) REFERENCES [dbo].[PUREQUISITIONSTATUS] ([PUREQUISITIONSTATUSID]),
    CONSTRAINT [FK_PUReqLstChaBy_Users] FOREIGN KEY ([LASTCHANGEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID]),
    CONSTRAINT [FK_PUReqRequestor_Users] FOREIGN KEY ([REQUESTOR]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);

