CREATE TABLE [dbo].[PURECEIPTNOTE] (
    [PURECEIPTNOTEID] CHAR (36)      NOT NULL,
    [PURECEIPTID]     CHAR (36)      NOT NULL,
    [TEXT]            NVARCHAR (MAX) NULL,
    [CREATEDBY]       CHAR (36)      NULL,
    [CREATEDDATE]     DATETIME       NULL,
    CONSTRAINT [PK_PUReceiptNote] PRIMARY KEY CLUSTERED ([PURECEIPTNOTEID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PUReceiptNote_PUReceipt] FOREIGN KEY ([PURECEIPTID]) REFERENCES [dbo].[PURECEIPT] ([PURECEIPTID]),
    CONSTRAINT [FK_PUReceiptNote_Users] FOREIGN KEY ([CREATEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);

