CREATE PROCEDURE [professionallicense].[USP_PROFESSIONAL_LICENSE_GET_HOLD_ENTITIES_BY_PROF_LICENSEIDS]
	@IDS RECORDIDS readonly
AS
BEGIN
	SELECT ILLICENSEID,ILLICENSEHOLD .SUSERGUID  AS PARENTID, ILLICENSEHOLD.HOLDSETUPID AS ILLICENSE_HOLDSETUPID,ILLICENSEHOLD.ILLICENSEHOLDID AS HOLDID, ILLICENSEHOLD.ACTIVE AS ILLICENSE_ACTIVE,ILLICENSEHOLD.CREATEDDATE,HOLDTYPESETUPS .HOLDSETUPID AS HOLDTYPESETUPS_HOLDSETUPID,HOLDTYPESETUPS .NAME,HOLDTYPESETUPS.HOLDTYPEID, ALLOWHOLDOVERRIDES,HOLDTYPESETUPS.ACTIVE AS HOLDTYPESETUPS_ACTIVE, HOLDTYPESETUPS.PLRENEW
	FROM ILLICENSEHOLD 
	JOIN HOLDTYPESETUPS ON ILLICENSEHOLD.HOLDSETUPID = HOLDTYPESETUPS.HOLDSETUPID
    JOIN @IDS ON RECORDID = ILLICENSEHOLD.ILLICENSEID
END