
CREATE PROCEDURE MG_BLICENSEINSPECTIONTYPE
	@businessLicenseId char(36)
AS
BEGIN

--get the lowest step order priority
DECLARE @MinPriorityWFStepOrder INT
SET @MinPriorityWFStepOrder = 
(SELECT	MIN(BLLICENSEWFSTEP.PRIORITYORDER)
FROM    BLLICENSEWFACTIONSTEP 
			INNER JOIN BLLICENSEWFSTEP ON BLLICENSEWFACTIONSTEP.BLLICENSEWFSTEPID = BLLICENSEWFSTEP.BLLICENSEWFSTEPID
WHERE	BLLICENSEWFSTEP.BLLICENSEID = @businessLicenseId 
			AND BLLICENSEWFSTEP.NOPRIORITY = 0
			AND (BLLICENSEWFACTIONSTEP.WORKFLOWSTATUSID = 0 OR BLLICENSEWFACTIONSTEP.WORKFLOWSTATUSID = 5))

--get the lowest step order priority
DECLARE @MinWFStepOrder INT
SET @MinWFStepOrder = ISNull(@MinPriorityWFStepOrder, (SELECT	MIN(BLLICENSEWFSTEP.PRIORITYORDER)
FROM    BLLICENSEWFACTIONSTEP 
			INNER JOIN BLLICENSEWFSTEP ON BLLICENSEWFACTIONSTEP.BLLICENSEWFSTEPID = BLLICENSEWFSTEP.BLLICENSEWFSTEPID
WHERE	BLLICENSEWFSTEP.BLLICENSEID = @businessLicenseId 
			AND (BLLICENSEWFACTIONSTEP.WORKFLOWSTATUSID = 0 OR BLLICENSEWFACTIONSTEP.WORKFLOWSTATUSID = 5)))


--get the lowest action priorty
DECLARE @MinPriorityWFActionOrder INT
SET @MinPriorityWFActionOrder = 
(SELECT	MIN(BLLICENSEWFACTIONSTEP.PRIORITYORDER)
FROM    BLLICENSEWFACTIONSTEP 
			INNER JOIN BLLICENSEWFSTEP ON BLLICENSEWFACTIONSTEP.BLLICENSEWFSTEPID = BLLICENSEWFSTEP.BLLICENSEWFSTEPID
WHERE   BLLICENSEWFSTEP.BLLICENSEID = @businessLicenseId
			AND BLLICENSEWFSTEP.PRIORITYORDER = @MinWFStepOrder
			AND BLLICENSEWFACTIONSTEP.NOPRIORITY = 0
			AND (BLLICENSEWFACTIONSTEP.WORKFLOWSTATUSID = 0 OR BLLICENSEWFACTIONSTEP.WORKFLOWSTATUSID = 5))

--get the lowest action priorty
DECLARE @MinWFActionOrder INT
SET @MinWFActionOrder = ISNULL(@MinPriorityWFActionOrder, (SELECT	MIN(BLLICENSEWFACTIONSTEP.PRIORITYORDER)
FROM    BLLICENSEWFACTIONSTEP 
			INNER JOIN BLLICENSEWFSTEP ON BLLICENSEWFACTIONSTEP.BLLICENSEWFSTEPID = BLLICENSEWFSTEP.BLLICENSEWFSTEPID
WHERE   BLLICENSEWFSTEP.BLLICENSEID = @businessLicenseId
			AND BLLICENSEWFSTEP.PRIORITYORDER = @MinWFStepOrder
			AND (BLLICENSEWFACTIONSTEP.WORKFLOWSTATUSID = 0 OR BLLICENSEWFACTIONSTEP.WORKFLOWSTATUSID = 5)))
	
--select the available inspection types for the permit with the above priority orders
SELECT	BLLICENSEWFSTEP.BLLICENSEID, IMINSPECTIONTYPE.NAME, BLLICENSEWFACTIONSTEP.IMINSPECTIONTYPEID, BLLICENSEWFACTIONSTEP.WORKFLOWSTATUSID, BLLICENSEWFACTIONSTEP.BLLICENSEWFACTIONSTEPID
FROM	BLLICENSEWFACTIONSTEP
			INNER JOIN BLLICENSEWFSTEP ON BLLICENSEWFACTIONSTEP.BLLICENSEWFSTEPID = BLLICENSEWFSTEP.BLLICENSEWFSTEPID
			INNER JOIN IMINSPECTIONTYPE ON BLLICENSEWFACTIONSTEP.IMINSPECTIONTYPEID = IMINSPECTIONTYPE.IMINSPECTIONTYPEID
			LEFT JOIN IMINSPECTIONACTREF ON BLLICENSEWFACTIONSTEP.BLLICENSEWFACTIONSTEPID = IMINSPECTIONACTREF.OBJECTID
			LEFT JOIN IMINSPECTION ON IMINSPECTIONACTREF.IMINSPECTIONID = IMINSPECTION.IMINSPECTIONID
WHERE	 BLLICENSEWFSTEP.BLLICENSEID = @businessLicenseId
			AND BLLICENSEWFACTIONSTEP.WFACTIONTYPEID = 6 
			AND (((BLLICENSEWFSTEP.PRIORITYORDER = @MinWFStepOrder OR BLLICENSEWFSTEP.NOPRIORITY = 1) AND BLLICENSEWFACTIONSTEP.PRIORITYORDER = @MinWFActionOrder) OR BLLICENSEWFACTIONSTEP.NOPRIORITY = 1)
			AND (BLLICENSEWFACTIONSTEP.WORKFLOWSTATUSID = 0 OR (BLLICENSEWFACTIONSTEP.WORKFLOWSTATUSID = 5 AND IMINSPECTION.SCHEDULEDSTARTDATE IS NULL ))		  			
END