
CREATE PROCEDURE [dbo].[mg_Query_CodeCaseParentHistory]
	@ParentId char(36)
AS
BEGIN
SELECT    IMINSPECTION.IMINSPECTIONID, IMINSPECTION.INSPECTIONNUMBER, IMINSPECTION.SCHEDULEDSTARTDATE, IMINSPECTIONTYPE.NAME TYPENAME, IMINSPECTION.IMINSPECTIONSTATUSID, IMINSPECTIONSTATUS.STATUSNAME,		   USERS.LNAME, USERS.FNAME, IMINSPECTION.COMMENTS
                                    FROM        CMCODEWFACTIONSTEP INNER JOIN CMCODEWFSTEP ON CMCODEWFACTIONSTEP.CMCODEWFSTEPID = CMCODEWFSTEP.CMCODEWFSTEPID 
                                    INNER JOIN IMINSPECTIONTYPE ON CMCODEWFACTIONSTEP.IMINSPECTIONTYPEID = IMINSPECTIONTYPE.IMINSPECTIONTYPEID
                                    INNER JOIN IMINSPECTIONACTREF ON CMCODEWFACTIONSTEP.CMCODEWFACTIONSTEPID = IMINSPECTIONACTREF.OBJECTID
									INNER JOIN IMINSPECTION ON IMINSPECTIONACTREF.IMINSPECTIONID = IMINSPECTION.IMINSPECTIONID
									INNER JOIN IMINSPECTIONSTATUS ON IMINSPECTION.IMINSPECTIONSTATUSID = IMINSPECTIONSTATUS.IMINSPECTIONSTATUSID
									LEFT JOIN IMINSPECTORREF ON IMINSPECTORREF.INSPECTIONID = IMINSPECTION.IMINSPECTIONID
								    LEFT JOIN USERS ON USERS.SUSERGUID = IMINSPECTORREF.USERID
                                    WHERE     (CMCODEWFSTEP.CMCODECASEID = @ParentId) AND (CMCODEWFACTIONSTEP.WFACTIONTYPEID = 6)
                                   -- AND (CMCODEWFACTIONSTEP.WORKFLOWSTATUSID = 0 OR (CMCODEWFACTIONSTEP.WORKFLOWSTATUSID = 5 ) OR CMCODEWFACTIONSTEP.WORKFLOWSTATUSID =1 )    
                                    AND (IMINSPECTORREF.BPRIMARY = 1 OR ( IMINSPECTORREF.BPRIMARY IS NULL))
		   	
END

