
CREATE PROCEDURE [dbo].[mg_Query_BLicenseParentHistory]
	@ParentId char(36)
AS
BEGIN
SELECT    IMINSPECTION.IMINSPECTIONID, IMINSPECTION.INSPECTIONNUMBER, IMINSPECTION.SCHEDULEDSTARTDATE, IMINSPECTIONTYPE.NAME TYPENAME, IMINSPECTION.IMINSPECTIONSTATUSID, IMINSPECTIONSTATUS.STATUSNAME,		   USERS.LNAME, USERS.FNAME, IMINSPECTION.COMMENTS
                                    FROM        BLLICENSEWFACTIONSTEP INNER JOIN BLLICENSEWFSTEP ON BLLICENSEWFACTIONSTEP.BLLICENSEWFSTEPID = BLLICENSEWFSTEP.BLLICENSEWFSTEPID 
                                    INNER JOIN IMINSPECTIONTYPE ON BLLICENSEWFACTIONSTEP.IMINSPECTIONTYPEID = IMINSPECTIONTYPE.IMINSPECTIONTYPEID
                                    INNER JOIN IMINSPECTIONACTREF ON BLLICENSEWFACTIONSTEP.BLLICENSEWFACTIONSTEPID = IMINSPECTIONACTREF.OBJECTID
									INNER JOIN IMINSPECTION ON IMINSPECTIONACTREF.IMINSPECTIONID = IMINSPECTION.IMINSPECTIONID
									INNER JOIN IMINSPECTIONSTATUS ON IMINSPECTION.IMINSPECTIONSTATUSID = IMINSPECTIONSTATUS.IMINSPECTIONSTATUSID
									LEFT JOIN IMINSPECTORREF ON IMINSPECTORREF.INSPECTIONID = IMINSPECTION.IMINSPECTIONID
								    LEFT JOIN USERS ON USERS.SUSERGUID = IMINSPECTORREF.USERID
                                    WHERE     (BLLICENSEWFSTEP.BLLICENSEID = @ParentId) AND (BLLICENSEWFACTIONSTEP.WFACTIONTYPEID = 6)
                                    --AND (BLLICENSEWFACTIONSTEP.WORKFLOWSTATUSID = 0 OR (BLLICENSEWFACTIONSTEP.WORKFLOWSTATUSID = 5 ) OR BLLICENSEWFACTIONSTEP.WORKFLOWSTATUSID =1 )    
                                    AND (IMINSPECTORREF.BPRIMARY = 1 OR ( IMINSPECTORREF.BPRIMARY IS NULL))
		   	
END

