CREATE PROCEDURE [dbo].[USP_MAILINGADDRESSTYPE_UPDATE]
(
	@MAILINGADDRESSTYPEID CHAR(36),
	@MAILINGADDRESSTYPENAME NVARCHAR(30),
	@MAILINGADDRESSDESCRIPTION NVARCHAR(MAX),
	@SYSTEMACTIONID CHAR(36),
	@ISDEFAULT BIT,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
UPDATE [dbo].[MAILINGADDRESSTYPE] SET
	[MAILINGADDRESSTYPENAME] = @MAILINGADDRESSTYPENAME,
	[MAILINGADDRESSDESCRIPTION] = @MAILINGADDRESSDESCRIPTION,
	[SYSTEMACTIONID] = @SYSTEMACTIONID,
	[ISDEFAULT] = @ISDEFAULT,
	[LASTCHANGEDBY] = @LASTCHANGEDBY,
	[LASTCHANGEDON] = @LASTCHANGEDON,
	[ROWVERSION] = @ROWVERSION + 1
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE
	[MAILINGADDRESSTYPEID] = @MAILINGADDRESSTYPEID AND 
	[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE