CREATE PROCEDURE [dbo].[USP_MEETINGTYPE_INSERT]
(
	@MEETINGTYPEID CHAR(36),
	@NAME NVARCHAR(50),
	@DESCRIPTION NVARCHAR(MAX),
	@CUSTOMFIELDLAYOUTID CHAR(36),
	@DEFAULTSUBJECT VARCHAR(255),
	@DEFAULTLOCATION VARCHAR(255),
	@DEFAULTCOMMENT VARCHAR(MAX),
	@STIME DATETIME,
	@ETIME DATETIME,
	@RECURRENCEID CHAR(36),
	@CONTENTLIMIT INT,
	@LIMIT INT,
	@AVAILINCAP BIT,
	@AVAILINCAPCONTACTS BIT,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
INSERT INTO [dbo].[MEETINGTYPE](
	[MEETINGTYPEID],
	[NAME],
	[DESCRIPTION],
	[CUSTOMFIELDLAYOUTID],
	[DEFAULTSUBJECT],
	[DEFAULTLOCATION],
	[DEFAULTCOMMENT],
	[STIME],
	[ETIME],
	[RECURRENCEID],
	[CONTENTLIMIT],
	[LIMIT],
	[AVAILINCAP],
	[AVAILINCAPCONTACTS],
	[LASTCHANGEDBY],
	[LASTCHANGEDON],
	[ROWVERSION]
)
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
VALUES
(
	@MEETINGTYPEID,
	@NAME,
	@DESCRIPTION,
	@CUSTOMFIELDLAYOUTID,
	@DEFAULTSUBJECT,
	@DEFAULTLOCATION,
	@DEFAULTCOMMENT,
	@STIME,
	@ETIME,
	@RECURRENCEID,
	@CONTENTLIMIT,
	@LIMIT,
	@AVAILINCAP,
	@AVAILINCAPCONTACTS,
	@LASTCHANGEDBY,
	@LASTCHANGEDON,
	@ROWVERSION
)
SELECT * FROM @OUTPUTTABLE