CREATE PROCEDURE [dbo].[USP_MAILMERGETEMPLATEUSER_INSERT]
(
	@MAILMERGETEMPLATEUSERID CHAR(36),
	@MAILMERGETEMPLATEID CHAR(36),
	@USERID CHAR(36),
	@MAILMERGETEMPLATEUSERTYPEID int
)
AS
	INSERT INTO [dbo].[MAILMERGETEMPLATEUSER](
	[MAILMERGETEMPLATEUSERID],
	[MAILMERGETEMPLATEID],
	[USERID],
	[MAILMERGETEMPLATEUSERTYPEID]
)
VALUES(
	@MAILMERGETEMPLATEUSERID,
	@MAILMERGETEMPLATEID,
	@USERID,
	@MAILMERGETEMPLATEUSERTYPEID
)