CREATE PROCEDURE [dbo].[USP_MAILINGADDRESS_UPDATE]
(
	@MAILINGADDRESSID CHAR(36),
	@ADDRESSLINE1 NVARCHAR(200),
	@ADDRESSLINE2 NVARCHAR(200),
	@ADDRESSLINE3 NVARCHAR(200),
	@CITY NVARCHAR(50),
	@STATE NVARCHAR(50),
	@COUNTY NVARCHAR(50),
	@COUNTRY NVARCHAR(50),
	@POSTALCODE NVARCHAR(50),
	@COUNTRYTYPE INT,
	@LASTCHANGEDON DATETIME,
	@LASTCHANGEDBY CHAR(36),
	@POSTDIRECTION NVARCHAR(30),
	@PREDIRECTION NVARCHAR(30),
	@ROWVERSION INT,
	@ADDRESSID CHAR(36),
	@ADDRESSTYPE NVARCHAR(50),
	@STREETTYPE NVARCHAR(50),
	@PARCELID CHAR(36),
	@PARCELNUMBER NVARCHAR(50),
	@UNITORSUITE VARCHAR(20),
	@PROVINCE NVARCHAR(50),
	@RURALROUTE NVARCHAR(50),
	@STATION NVARCHAR(50),
	@COMPSITE NVARCHAR(50),
	@POBOX NVARCHAR(50),
	@ATTN NVARCHAR(50),
	@GENERALDELIVERY BIT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
UPDATE [dbo].[MAILINGADDRESS] SET
	[ADDRESSLINE1] = @ADDRESSLINE1,
	[ADDRESSLINE2] = @ADDRESSLINE2,
	[ADDRESSLINE3] = @ADDRESSLINE3,
	[CITY] = @CITY,
	[STATE] = @STATE,
	[COUNTY] = @COUNTY,
	[COUNTRY] = @COUNTRY,
	[POSTALCODE] = @POSTALCODE,
	[COUNTRYTYPE] = @COUNTRYTYPE,
	[LASTCHANGEDON] = @LASTCHANGEDON,
	[LASTCHANGEDBY] = @LASTCHANGEDBY,
	[POSTDIRECTION] = @POSTDIRECTION,
	[PREDIRECTION] = @PREDIRECTION,
	[ROWVERSION] = @ROWVERSION + 1,
	[ADDRESSID] = @ADDRESSID,
	[ADDRESSTYPE] = @ADDRESSTYPE,
	[STREETTYPE] = @STREETTYPE,
	[PARCELID] = @PARCELID,
	[PARCELNUMBER] = @PARCELNUMBER,
	[UNITORSUITE] = @UNITORSUITE,
	[PROVINCE] = @PROVINCE,
	[RURALROUTE] = @RURALROUTE,
	[STATION] = @STATION,
	[COMPSITE] = @COMPSITE,
	[POBOX] = @POBOX,
	[ATTN] = @ATTN,
	[GENERALDELIVERY] = @GENERALDELIVERY
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE
	[MAILINGADDRESSID] = @MAILINGADDRESSID AND 
	[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE