CREATE PROCEDURE [dbo].[USP_MAILMERGETEMPLATEUSER_DELETE_BYPARENTID]
(
	@WORKFLOWACTIONID CHAR(36),
	@WORKFLOWID CHAR(36)
)
AS
	DELETE [dbo].[MAILMERGETEMPLATEUSER] FROM [dbo].[MAILMERGETEMPLATEUSER] 
	INNER JOIN [dbo].[WORKFLOWACTIONMAILMERGETMPL] on [dbo].[MAILMERGETEMPLATEUSER].[MAILMERGETEMPLATEID] = [dbo].[WORKFLOWACTIONMAILMERGETMPL].[MAILMERGETEMPLATEID]
	INNER JOIN [dbo].[WORKFLOWACTION] on [dbo].[WORKFLOWACTIONMAILMERGETMPL].[WORKFLOWACTIONID] = [dbo].[WORKFLOWACTION].[WORKFLOWACTIONID]
	WHERE 
		(@WORKFLOWACTIONID IS NULL OR [dbo].[WORKFLOWACTION].[WORKFLOWACTIONID] = @WORKFLOWACTIONID) AND
		(@WORKFLOWID IS NULL OR [dbo].[WORKFLOWACTION].[WORKFLOWID] = @WORKFLOWID)