CREATE PROCEDURE [dbo].[USP_MEETINGCASETYPE_INSERT]
(
	@CASETYPEID CHAR(36),
	@MODULEID INT,
	@TYPEID CHAR(36),
	@WORKCLASSID CHAR(36),
	@LIMIT INT,
	@MEETINGTYPEID CHAR(36),
	@MODULENAME NVARCHAR(50),
	@TYPENAME NVARCHAR(50),
	@WORKCLASSNAME NVARCHAR(50)
)
AS

INSERT INTO [dbo].[MEETINGCASETYPE](
	[CASETYPEID],
	[MODULEID],
	[TYPEID],
	[WORKCLASSID],
	[LIMIT],
	[MEETINGTYPEID],
	[MODULENAME],
	[TYPENAME],
	[WORKCLASSNAME]
)

VALUES
(
	@CASETYPEID,
	@MODULEID,
	@TYPEID,
	@WORKCLASSID,
	@LIMIT,
	@MEETINGTYPEID,
	@MODULENAME,
	@TYPENAME,
	@WORKCLASSNAME
)