CREATE TABLE [dbo].[ILLICENSETYPECLASSTYPE] (
    [ILLICENSETYPECLASSTYPEID] CHAR (36) NOT NULL,
    [ILLICENSETYPEID]          CHAR (36) NOT NULL,
    [ILLICENSECLASSTYPEID]     CHAR (36) NOT NULL,
    CONSTRAINT [PK_ILLICENSETYPECLASSTYPE] PRIMARY KEY CLUSTERED ([ILLICENSETYPECLASSTYPEID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_ILLICTYPECLASSTYPE_TYPE] FOREIGN KEY ([ILLICENSETYPEID]) REFERENCES [dbo].[ILLICENSETYPE] ([ILLICENSETYPEID]),
    CONSTRAINT [FK_TYPECLASSTYPE_CLASSTYPE] FOREIGN KEY ([ILLICENSECLASSTYPEID]) REFERENCES [dbo].[ILLICENSECLASSTYPE] ([ILLICENSECLASSTYPEID])
);


GO
CREATE NONCLUSTERED INDEX [IX_ILLICENSETYPECLASSTYPE_ILLICENSETYPEID]
    ON [dbo].[ILLICENSETYPECLASSTYPE]([ILLICENSETYPEID] ASC);


GO

CREATE TRIGGER [dbo].[TG_ILLICENSETYPECLASSTYPE_DELETE]  ON  [dbo].[ILLICENSETYPECLASSTYPE]
   AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
	(
		[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
	)
	SELECT
		[ILLICENSETYPE].[ILLICENSETYPEID],
		[ILLICENSETYPE].[ROWVERSION],
		GETUTCDATE(),			
		(SELECT dbo.UFN_GET_USERID_FROM_CONTEXT_INFO()),
		'Professional License Type Allowed Classification Type Deleted',
        '',
        '',       
		'Professional License Type (' + [ILLICENSETYPE].[NAME] + '), Allowed Classification Type (' + [ILLICENSECLASSTYPE].[NAME] +')',
		'67978C16-D720-4F8E-8120-E00FBB732A77',
		3,
		0,
		[ILLICENSECLASSTYPE].[NAME]
    FROM [deleted]
	INNER JOIN [ILLICENSETYPE] ON [ILLICENSETYPE].[ILLICENSETYPEID] = [deleted].[ILLICENSETYPEID]
	INNER JOIN [ILLICENSECLASSTYPE] WITH (NOLOCK) ON [ILLICENSECLASSTYPE].[ILLICENSECLASSTYPEID] = [deleted].[ILLICENSECLASSTYPEID]
END
GO

CREATE TRIGGER [dbo].[TG_ILLICENSETYPECLASSTYPE_UPDATE]   ON  [dbo].[ILLICENSETYPECLASSTYPE] 
   AFTER UPDATE
AS 
BEGIN	
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
    (	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT 
			[ILLICENSETYPE].[ILLICENSETYPEID], 
			[ILLICENSETYPE].[ROWVERSION],
			GETUTCDATE(),
			[ILLICENSETYPE].[LASTCHANGEDBY],	
			'Classification Type Name',			
			[ILLICENSECLASSTYPE_DELETED].[NAME] ,
			[ILLICENSECLASSTYPE_INSERTED].[NAME] ,
			'Professional License Type (' + [ILLICENSETYPE].[NAME] + '), Allowed Classification Type (' + [ILLICENSECLASSTYPE_INSERTED].[NAME] +')',
			'67978C16-D720-4F8E-8120-E00FBB732A77',
			2,
			0,
			[ILLICENSECLASSTYPE_INSERTED].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[ILLICENSETYPECLASSTYPEID] = [inserted].[ILLICENSETYPECLASSTYPEID]			
			INNER JOIN [ILLICENSETYPE] ON [ILLICENSETYPE].[ILLICENSETYPEID] = [deleted].[ILLICENSETYPEID]
			INNER JOIN [ILLICENSECLASSTYPE] [ILLICENSECLASSTYPE_DELETED] WITH (NOLOCK) ON [ILLICENSECLASSTYPE_DELETED].[ILLICENSECLASSTYPEID] = [deleted].[ILLICENSECLASSTYPEID]
			INNER JOIN [ILLICENSECLASSTYPE] [ILLICENSECLASSTYPE_INSERTED] WITH (NOLOCK) ON [ILLICENSECLASSTYPE_INSERTED].[ILLICENSECLASSTYPEID] = [inserted].[ILLICENSECLASSTYPEID]
	WHERE	[deleted].[ILLICENSECLASSTYPEID] <>[inserted].[ILLICENSECLASSTYPEID]
END
GO

CREATE TRIGGER [dbo].[TG_ILLICENSETYPECLASSTYPE_INSERT] ON  [dbo].[ILLICENSETYPECLASSTYPE]
   AFTER INSERT
AS 
BEGIN	
	SET NOCOUNT ON;	
	INSERT INTO [HISTORYSYSTEMSETUP]
    (
        [ID],
        [ROWVERSION],
        [CHANGEDON],
        [CHANGEDBY],
        [FIELDNAME],
        [OLDVALUE],
        [NEWVALUE],
        [ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT 
        [ILLICENSETYPE].[ILLICENSETYPEID], 
        [ILLICENSETYPE].[ROWVERSION],
        GETUTCDATE(),
        [ILLICENSETYPE].[LASTCHANGEDBY],	
        'Professional License Type Allowed Classification Type Added',
        '',
        '',       
		'Professional License Type (' + [ILLICENSETYPE].[NAME] + '), Allowed Classification Type (' + [ILLICENSECLASSTYPE].[NAME] +')',
		'67978C16-D720-4F8E-8120-E00FBB732A77',
		1,
		0,
		[ILLICENSECLASSTYPE].[NAME]
    FROM [inserted]
	INNER JOIN [ILLICENSETYPE] ON [ILLICENSETYPE].[ILLICENSETYPEID] = [inserted].[ILLICENSETYPEID]
	INNER JOIN [ILLICENSECLASSTYPE] WITH (NOLOCK) ON [ILLICENSECLASSTYPE].[ILLICENSECLASSTYPEID] = [inserted].[ILLICENSECLASSTYPEID]
END