CREATE TABLE [dbo].[ILLICENSEREQUIREDFIELD] (
    [REQUIREDCUSTOMFIELDID]       CHAR (36) NOT NULL,
    [ILLICENSETYPELICENSECLASSID] CHAR (36) NULL,
    [GCUSTOMFIELD]                CHAR (36) NULL,
    [SORTORDER]                   INT       NULL,
    CONSTRAINT [PK_ILLICENSEREQUIREDFIELD] PRIMARY KEY CLUSTERED ([REQUIREDCUSTOMFIELDID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_ILLICENSEREQUIREDFIELD_CUSTOMFIELD] FOREIGN KEY ([GCUSTOMFIELD]) REFERENCES [dbo].[CUSTOMFIELD] ([GCUSTOMFIELD]),
    CONSTRAINT [FK_LICENSEREQUIRED_CLASS] FOREIGN KEY ([ILLICENSETYPELICENSECLASSID]) REFERENCES [dbo].[ILLICENSETYPELICENSECLASS] ([ILLICENSETYPELICENSECLASSID])
);


GO
CREATE NONCLUSTERED INDEX [IX_ILLICENSEREQUIREDFIELD_ILLICENSETYPELICENSECLASSID]
    ON [dbo].[ILLICENSEREQUIREDFIELD]([ILLICENSETYPELICENSECLASSID] ASC);


GO

CREATE TRIGGER [dbo].[TG_ILLICENSEREQUIREDFIELD_UPDATE]   ON  [dbo].[ILLICENSEREQUIREDFIELD] 
   AFTER UPDATE
AS 
BEGIN	
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
    (	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT 
			[ILLICENSETYPE].[ILLICENSETYPEID],
			[ILLICENSETYPE].[ROWVERSION],
			GETUTCDATE(),			
			[ILLICENSETYPE].[LASTCHANGEDBY],
			'Sort Order',			
			CASE WHEN [deleted].[SORTORDER] IS NULL THEN '[none]' ELSE CONVERT(NVARCHAR(MAX), [deleted].[SORTORDER]) END,
			CASE WHEN [inserted].[SORTORDER] IS NULL THEN '[none]' ELSE CONVERT(NVARCHAR(MAX), [inserted].[SORTORDER]) END,		
			'Professional License Type (' + [ILLICENSETYPE].[NAME] + '), Required Renewal Field Name (' + (CASE WHEN [CUSTOMFIELD].[SFIELDNAME]='' OR  [CUSTOMFIELD].[SFIELDNAME] IS NULL THEN [CUSTOMFIELD].SCUSTOMFIELD ELSE [CUSTOMFIELD].[SFIELDNAME]  END) +')',
			'67978C16-D720-4F8E-8120-E00FBB732A77',
			2,
			0,
			(CASE WHEN [CUSTOMFIELD].[SFIELDNAME]='' OR  [CUSTOMFIELD].[SFIELDNAME] IS NULL THEN [CUSTOMFIELD].SCUSTOMFIELD ELSE [CUSTOMFIELD].[SFIELDNAME]  END) 
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[REQUIREDCUSTOMFIELDID] = [inserted].[REQUIREDCUSTOMFIELDID]			
			INNER JOIN [ILLICENSETYPELICENSECLASS] ON [ILLICENSETYPELICENSECLASS].[ILLICENSETYPELICENSECLASSID] = [deleted].[ILLICENSETYPELICENSECLASSID]
			INNER JOIN [ILLICENSETYPE] ON [ILLICENSETYPE].[ILLICENSETYPEID] = [ILLICENSETYPELICENSECLASS].[ILLICENSETYPEID]
			LEFT JOIN [CUSTOMFIELD] WITH (NOLOCK) ON [CUSTOMFIELD].[GCUSTOMFIELD] = [deleted].[GCUSTOMFIELD]		
	WHERE	ISNULL([deleted].[SORTORDER],'') <> ISNULL([inserted].[SORTORDER],'')
END
GO

CREATE TRIGGER [dbo].[TG_ILLICENSEREQUIREDFIELD_INSERT] ON  [dbo].[ILLICENSEREQUIREDFIELD]
   AFTER INSERT
AS 
BEGIN	
	SET NOCOUNT ON;	
	INSERT INTO [HISTORYSYSTEMSETUP]
    (
        [ID],
        [ROWVERSION],
        [CHANGEDON],
        [CHANGEDBY],
        [FIELDNAME],
        [OLDVALUE],
        [NEWVALUE],
        [ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT 
        [ILLICENSETYPE].[ILLICENSETYPEID], 
        [ILLICENSETYPE].[ROWVERSION],
        GETUTCDATE(),
        [ILLICENSETYPE].[LASTCHANGEDBY],	
        'Professional License Type Required Renewal Field Added',
        '',
        '',       
		'Professional License Type (' + [ILLICENSETYPE].[NAME] + '), Required Renewal Field Name (' + (CASE WHEN [CUSTOMFIELD].[SFIELDNAME]='' OR  [CUSTOMFIELD].[SFIELDNAME] IS NULL THEN [CUSTOMFIELD].SCUSTOMFIELD ELSE [CUSTOMFIELD].[SFIELDNAME]  END) +')',
		'67978C16-D720-4F8E-8120-E00FBB732A77',
		1,
		0,
		(CASE WHEN [CUSTOMFIELD].[SFIELDNAME]='' OR  [CUSTOMFIELD].[SFIELDNAME] IS NULL THEN [CUSTOMFIELD].SCUSTOMFIELD ELSE [CUSTOMFIELD].[SFIELDNAME]  END) 
    FROM [inserted]
	INNER JOIN [ILLICENSETYPELICENSECLASS]  ON [ILLICENSETYPELICENSECLASS].[ILLICENSETYPELICENSECLASSID] = [inserted].[ILLICENSETYPELICENSECLASSID]
	INNER JOIN [ILLICENSETYPE] ON [ILLICENSETYPE].[ILLICENSETYPEID] = [ILLICENSETYPELICENSECLASS].[ILLICENSETYPEID]
	LEFT JOIN [CUSTOMFIELD] WITH (NOLOCK) ON [CUSTOMFIELD].[GCUSTOMFIELD] = [inserted].[GCUSTOMFIELD]
END
GO

CREATE TRIGGER [dbo].[TG_ILLICENSEREQUIREDFIELD_DELETE]  ON  [dbo].[ILLICENSEREQUIREDFIELD]
   AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
	(
		[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
	)
	SELECT
		[ILLICENSETYPE].[ILLICENSETYPEID],
		[ILLICENSETYPE].[ROWVERSION],
		GETUTCDATE(),			
		(SELECT dbo.UFN_GET_USERID_FROM_CONTEXT_INFO()),
		'Professional License Type Required Renewal Field Deleted',
        '',
        '',       
		'Professional License Type (' + [ILLICENSETYPE].[NAME] + '), Required Renewal Field Name (' + (CASE WHEN [CUSTOMFIELD].[SFIELDNAME]='' OR  [CUSTOMFIELD].[SFIELDNAME] IS NULL THEN [CUSTOMFIELD].SCUSTOMFIELD ELSE [CUSTOMFIELD].[SFIELDNAME]  END) +')',
		'67978C16-D720-4F8E-8120-E00FBB732A77',
		3,
		0,
		(CASE WHEN [CUSTOMFIELD].[SFIELDNAME]='' OR  [CUSTOMFIELD].[SFIELDNAME] IS NULL THEN [CUSTOMFIELD].SCUSTOMFIELD ELSE [CUSTOMFIELD].[SFIELDNAME]  END) 
    FROM [deleted]
	INNER JOIN [ILLICENSETYPELICENSECLASS] ON [ILLICENSETYPELICENSECLASS].[ILLICENSETYPELICENSECLASSID] = [deleted].[ILLICENSETYPELICENSECLASSID]
	INNER JOIN [ILLICENSETYPE] ON [ILLICENSETYPE].[ILLICENSETYPEID] = [ILLICENSETYPELICENSECLASS].[ILLICENSETYPEID]
	LEFT JOIN [CUSTOMFIELD] WITH (NOLOCK) ON [CUSTOMFIELD].[GCUSTOMFIELD] = [deleted].[GCUSTOMFIELD]
END