CREATE TABLE [dbo].[ILLICENSESYSTEMTYPE] (
    [ILLICENSESYSTEMTYPEID] INT           NOT NULL,
    [NAME]                  NVARCHAR (50) NOT NULL,
    [ALLOWCOMPANY]          BIT           NOT NULL,
    CONSTRAINT [PK_ILLICENSESYSTEMTYPE] PRIMARY KEY CLUSTERED ([ILLICENSESYSTEMTYPEID] ASC) WITH (FILLFACTOR = 90)
);

