CREATE TABLE [dbo].[IMINSPECTIONCASEPARCEL] (
    [IMINSPECTIONCASEPARCELID] CHAR (36) NOT NULL,
    [IMINSPECTIONCASEID]       CHAR (36) NOT NULL,
    [PARCELID]                 CHAR (36) NOT NULL,
    [MAIN]                     BIT       NOT NULL,
    CONSTRAINT [PK_IMINSPECTIONCASEPARCEL] PRIMARY KEY CLUSTERED ([IMINSPECTIONCASEPARCELID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_IMINSPECTIONCASEPARCEL_CA] FOREIGN KEY ([IMINSPECTIONCASEID]) REFERENCES [dbo].[IMINSPECTIONCASE] ([IMINSPECTIONCASEID]),
    CONSTRAINT [FK_IMINSPECTIONCASEPARCEL_PA] FOREIGN KEY ([PARCELID]) REFERENCES [dbo].[PARCEL] ([PARCELID])
);

