CREATE TABLE [dbo].[IMINSPECTORREF] (
    [INSPECTIONID]     CHAR (36) NOT NULL,
    [USERID]           CHAR (36) NOT NULL,
    [BPRIMARY]         BIT       NOT NULL,
    [IMINSPECTORREFID] CHAR (36) NOT NULL,
    CONSTRAINT [PK_IMInspectorRef] PRIMARY KEY CLUSTERED ([IMINSPECTORREFID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_IMInspectorRef_IMIns] FOREIGN KEY ([INSPECTIONID]) REFERENCES [dbo].[IMINSPECTION] ([IMINSPECTIONID]),
    CONSTRAINT [FK_IMInspectorRef_User] FOREIGN KEY ([USERID]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);


GO
CREATE NONCLUSTERED INDEX [IMINSPECTORREF_INSP]
    ON [dbo].[IMINSPECTORREF]([INSPECTIONID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IMINSPECTORREF_USER]
    ON [dbo].[IMINSPECTORREF]([USERID] ASC, [INSPECTIONID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [NCIDX_IMINSPECTORREF_BPRIMARY_INCL]
    ON [dbo].[IMINSPECTORREF]([BPRIMARY] ASC)
    INCLUDE([INSPECTIONID], [USERID]) WITH (FILLFACTOR = 90, PAD_INDEX = ON);


GO


CREATE TRIGGER [TG_IMINSPECTORREF_DELETE_ELASTIC] ON  [IMINSPECTORREF]
   AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [ELASTICSEARCHOBJECT]
    ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID() ,
		[I].[IMINSPECTIONID] ,
        'EnerGovBusiness.Inspections.Inspection' ,
        [I].[ROWVERSION] ,
        GETDATE() ,
        NULL ,
        2 ,
        (SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Deleted]
	JOIN [IMINSPECTION] AS [I] WITH (NOLOCK) ON [I].[IMINSPECTIONID] = [Deleted].[INSPECTIONID]

END
GO

CREATE TRIGGER [TG_IMINSPECTORREF_INSERTUPDATE_ELASTIC] ON  [IMINSPECTORREF]
   AFTER INSERT, UPDATE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [ELASTICSEARCHOBJECT]
    ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID() ,
		[I].[IMINSPECTIONID] ,
        'EnerGovBusiness.Inspections.Inspection' ,
        [I].[ROWVERSION] ,
        GETDATE() ,
        NULL ,
        2 ,
        (SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Inserted]
	JOIN [IMINSPECTION] AS [I] WITH (NOLOCK) ON [I].[IMINSPECTIONID] = [Inserted].[INSPECTIONID]

END