CREATE TABLE [dbo].[IMINSPECTIONNONCOMPLYCODE] (
    [IMINSPECTIONNONCOMPLYCODEID]   CHAR (36)       NOT NULL,
    [IMINSPECTIONID]                CHAR (36)       NOT NULL,
    [IMNONCOMPLIANCECODEID]         CHAR (36)       NOT NULL,
    [IMNONCOMPLIANCECODEREVISIONID] CHAR (36)       NOT NULL,
    [IMNONCOMPLIANCERISKID]         INT             NOT NULL,
    [IMNONCOMPLIANCERESPPARTYID]    INT             NOT NULL,
    [CODENUMBER]                    INT             NOT NULL,
    [CODEDESCRIPTION]               NVARCHAR (2000) NULL,
    [COMMENTS]                      NVARCHAR (2000) NULL,
    [DEADLINEDATE]                  DATETIME        NOT NULL,
    [RESOLVEDDATE]                  DATETIME        NULL,
    CONSTRAINT [PK_IMINSPECTIONNONCOMPLYCODE] PRIMARY KEY CLUSTERED ([IMINSPECTIONNONCOMPLYCODEID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_IMINSPCOMPLYCODE_CODE] FOREIGN KEY ([IMNONCOMPLIANCECODEID]) REFERENCES [dbo].[IMNONCOMPLIANCECODE] ([IMNONCOMPLIANCECODEID]),
    CONSTRAINT [FK_IMINSPCOMPLYCODE_INSP] FOREIGN KEY ([IMINSPECTIONID]) REFERENCES [dbo].[IMINSPECTION] ([IMINSPECTIONID]),
    CONSTRAINT [FK_IMINSPCOMPLYCODE_PARTY] FOREIGN KEY ([IMNONCOMPLIANCERESPPARTYID]) REFERENCES [dbo].[IMNONCOMPLIANCERESPPARTY] ([IMNONCOMPLIANCERESPPARTYID]),
    CONSTRAINT [FK_IMINSPCOMPLYCODE_REVIS] FOREIGN KEY ([IMNONCOMPLIANCECODEREVISIONID]) REFERENCES [dbo].[IMNONCOMPLIANCECODEREVISION] ([IMNONCOMPLIANCECODEREVISIONID]),
    CONSTRAINT [FK_IMINSPCOMPLYCODE_RISK] FOREIGN KEY ([IMNONCOMPLIANCERISKID]) REFERENCES [dbo].[IMNONCOMPLIANCERISK] ([IMNONCOMPLIANCERISKID])
);


GO
CREATE NONCLUSTERED INDEX [IX_IMINSPECTIONNONCOMPLY_INSP]
    ON [dbo].[IMINSPECTIONNONCOMPLYCODE]([IMINSPECTIONID] ASC) WITH (FILLFACTOR = 90);

