CREATE TABLE [dbo].[IMINSPECTIONGISASSIGNMENT] (
    [IMINSPECTIONGISASSIGNMENTID] INT           NOT NULL,
    [NAME]                        NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_IMINSPECTIONGISASSIGNMENT] PRIMARY KEY CLUSTERED ([IMINSPECTIONGISASSIGNMENTID] ASC) WITH (FILLFACTOR = 90)
);

