CREATE TABLE [dbo].[IMINSPECTIONVIOLATIONXREF] (
    [IMINSPECTIONVIOLATIONXREFID] CHAR (36) NOT NULL,
    [IMINSPECTIONID]              CHAR (36) NOT NULL,
    [IMVIOLATIONID]               CHAR (36) NOT NULL,
    PRIMARY KEY CLUSTERED ([IMINSPECTIONVIOLATIONXREFID] ASC),
    CONSTRAINT [FK_INSPVIOLATION_IMVIOLATION] FOREIGN KEY ([IMVIOLATIONID]) REFERENCES [dbo].[IMVIOLATION] ([IMVIOLATIONID]),
    CONSTRAINT [FK_INSPVIOLATION_INSPECTION] FOREIGN KEY ([IMINSPECTIONID]) REFERENCES [dbo].[IMINSPECTION] ([IMINSPECTIONID])
);

