CREATE TABLE [dbo].[IMINSPECTIONTYPE] (
    [IMINSPECTIONTYPEID]             CHAR (36)       NOT NULL,
    [IMINSPECTIONTYPEGROUPID]        CHAR (36)       NULL,
    [DEPARTMENTID]                   CHAR (36)       NULL,
    [NAME]                           NVARCHAR (50)   NOT NULL,
    [DESCRIPTION]                    NVARCHAR (MAX)  NULL,
    [IVRNUMBER]                      NVARCHAR (5)    NULL,
    [ESTIMATEDMINUTES]               DECIMAL (18, 4) NULL,
    [PRIORITYNUMBER]                 INT             NULL,
    [GCUSTOMFIELDLAYOUTS]            CHAR (36)       NULL,
    [IMINSPECTIONSTATUSID]           CHAR (36)       NULL,
    [PREFIX]                         NVARCHAR (10)   NULL,
    [MOBILEGOVDEFAULTRPTID]          CHAR (36)       NULL,
    [GISZONEMAPPINGID]               CHAR (36)       NULL,
    [EXTEND_DATE]                    BIT             DEFAULT ((1)) NOT NULL,
    [IMINSPECTIONSCHEDULETYPEID]     CHAR (36)       DEFAULT ('9E01EFDD-3FAF-41AA-87A0-0486564C7B85') NOT NULL,
    [IMINSPECTIONGISASSIGNMENTID]    INT             DEFAULT ((1)) NOT NULL,
    [GONLINECUSTOMFIELDLAYOUTS]      CHAR (36)       NULL,
    [CAFEETEMPLATEID]                CHAR (36)       NULL,
    [COPYCHECKLISTINFO]              BIT             DEFAULT ((0)) NOT NULL,
    [ISLIMITEXEMPT]                  BIT             DEFAULT ((1)) NOT NULL,
    [REINSPECTWAITTIME]              INT             DEFAULT ((0)) NOT NULL,
    [ENTITYPROPERTY]                 NVARCHAR (MAX)  NULL,
    [PROPERTYFRIENDLYNAME]           NVARCHAR (MAX)  NULL,
    [IMINSPECTIONLINKID]             INT             DEFAULT ((0)) NOT NULL,
    [ISNONCOMPLIANCETRACKED]         BIT             CONSTRAINT [DF_IMINSPECTIONTYPE_NCOMPLTRK] DEFAULT ((0)) NOT NULL,
    [ALLOWCAPNONCOMPLANCESUBMISSION] BIT             CONSTRAINT [DF_IMINSPECTIONTYPE_CAPSUBM] DEFAULT ((0)) NOT NULL,
    [DESCRIPTION_SPANISH]            NVARCHAR (MAX)  NULL,
    [ALLOWPUBLICREQUESTS]            BIT             DEFAULT ((1)) NOT NULL,
    [IMINSPECTIONCALENDARID]         CHAR (36)       NULL,
    [ISALLOWCODECASEFROMMOBILE]      BIT             DEFAULT ((0)) NOT NULL,
    [RECURRENCEID]                   CHAR (36)       NULL,
    [LASTCHANGEDBY]                  CHAR (36)       NULL,
    [LASTCHANGEDON]                  DATETIME        CONSTRAINT [DF_IMINSPECTIONTYPE_LastChangedOn] DEFAULT (getutcdate()) NOT NULL,
    [ROWVERSION]                     INT             CONSTRAINT [DF_IMINSPECTIONTYPE_RowVersion] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_IMInspectionType] PRIMARY KEY CLUSTERED ([IMINSPECTIONTYPEID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_IMInspectionType_CustomFieldLayout] FOREIGN KEY ([GCUSTOMFIELDLAYOUTS]) REFERENCES [dbo].[CUSTOMFIELDLAYOUT] ([GCUSTOMFIELDLAYOUTS]),
    CONSTRAINT [FK_IMInspectionType_Department] FOREIGN KEY ([DEPARTMENTID]) REFERENCES [dbo].[DEPARTMENT] ([DEPARTMENTID]),
    CONSTRAINT [FK_IMInspectionType_GISAssign] FOREIGN KEY ([IMINSPECTIONGISASSIGNMENTID]) REFERENCES [dbo].[IMINSPECTIONGISASSIGNMENT] ([IMINSPECTIONGISASSIGNMENTID]),
    CONSTRAINT [FK_IMInspectionType_GISZoneMapping] FOREIGN KEY ([GISZONEMAPPINGID]) REFERENCES [dbo].[GISZONEMAPPING] ([GISZONEMAPPINGID]),
    CONSTRAINT [FK_IMInspectionType_IMInspecti] FOREIGN KEY ([IMINSPECTIONTYPEGROUPID]) REFERENCES [dbo].[IMINSPECTIONTYPEGROUP] ([IMINSPECTIONTYPEGROUPID]),
    CONSTRAINT [FK_IMINSPECTIONTYPE_IMINSPECTIONCALENDAR] FOREIGN KEY ([IMINSPECTIONCALENDARID]) REFERENCES [dbo].[IMINSPECTIONCALENDAR] ([IMINSPECTIONCALENDARID]),
    CONSTRAINT [FK_IMINSPECTIONTYPE_LINK] FOREIGN KEY ([IMINSPECTIONLINKID]) REFERENCES [dbo].[IMINSPECTIONLINK] ([IMINSPECTIONLINKID]),
    CONSTRAINT [FK_IMINSPECTIONTYPE_RECURRENCE] FOREIGN KEY ([RECURRENCEID]) REFERENCES [dbo].[RECURRENCE] ([RECURRENCEID]),
    CONSTRAINT [FK_IMInspectionType_Status] FOREIGN KEY ([IMINSPECTIONSTATUSID]) REFERENCES [dbo].[IMINSPECTIONSTATUS] ([IMINSPECTIONSTATUSID]),
    CONSTRAINT [FK_IMINSPTYPE_FEETEMPL] FOREIGN KEY ([CAFEETEMPLATEID]) REFERENCES [dbo].[CAFEETEMPLATE] ([CAFEETEMPLATEID]),
    CONSTRAINT [FK_INSP_SCHEDULETYPE] FOREIGN KEY ([IMINSPECTIONSCHEDULETYPEID]) REFERENCES [dbo].[IMINSPECTIONSCHEDULETYPE] ([IMINSPECTIONSCHEDULETYPEID]),
    CONSTRAINT [FK_INSPTYPE_ONLINECFLAYOUT] FOREIGN KEY ([GONLINECUSTOMFIELDLAYOUTS]) REFERENCES [dbo].[CUSTOMFIELDLAYOUT] ([GCUSTOMFIELDLAYOUTS])
);


GO
CREATE NONCLUSTERED INDEX [NCIDX_IMINSPECTIONTYPE_IMINSPECTIONTYPEGROUPID_IMINSPECTIONTYPEID]
    ON [dbo].[IMINSPECTIONTYPE]([IMINSPECTIONTYPEGROUPID] ASC, [IMINSPECTIONTYPEID] ASC);


GO
CREATE NONCLUSTERED INDEX [NCIDX_IMINSPECTIONTYPE_IVRNUMBER_IMINSPECTIONTYPEGROUPID_IMINSPECTIONTYPEID]
    ON [dbo].[IMINSPECTIONTYPE]([IVRNUMBER] ASC, [IMINSPECTIONTYPEGROUPID] ASC, [IMINSPECTIONTYPEID] ASC);


GO
CREATE NONCLUSTERED INDEX [NCIDX_IMINSPECTIONTYPE_IVRNUMBER_IMINSPECTIONTYPEID_IMINSPECTIONTYPEGROUPID]
    ON [dbo].[IMINSPECTIONTYPE]([IVRNUMBER] ASC, [IMINSPECTIONTYPEID] ASC, [IMINSPECTIONTYPEGROUPID] ASC);


GO
CREATE TRIGGER [dbo].[TG_IMINSPECTIONTYPE_DELETE] ON [dbo].[IMINSPECTIONTYPE]
   AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [HISTORYSYSTEMSETUP]
    (	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )

	SELECT
			[deleted].[IMINSPECTIONTYPEID],
			[deleted].[ROWVERSION],
			GETUTCDATE(),
			(SELECT dbo.UFN_GET_USERID_FROM_CONTEXT_INFO()),
			'Inspection Type Deleted',
			'',
			'',
			'Inspection Type (' + [deleted].[NAME] + ')',
			'D6001D91-4891-41A9-8056-33EE10520A48',
			3,
			1,
			[deleted].[NAME]
	FROM	[deleted]
END
GO
CREATE TRIGGER [dbo].[TG_IMINSPECTIONTYPE_INSERT] ON [dbo].[IMINSPECTIONTYPE]
   FOR INSERT
AS 
BEGIN
	SET NOCOUNT ON;
	-- Check if LASTCHANGEDBY contains VALID User Id and it Exists in USERS table, this is in replacement to foreign key reference of IMINSPECTIONTYPE table with USERS table.
	IF EXISTS (SELECT * FROM inserted 
		LEFT OUTER JOIN USERS WITH (NOLOCK) ON USERS.SUSERGUID = inserted.LASTCHANGEDBY
		WHERE inserted.LASTCHANGEDBY IS NOT NULL AND USERS.SUSERGUID IS NULL)
	BEGIN		
		RAISERROR ('The INSERT or UPDATE statement conflicted with the FOREIGN KEY to table USERS', 16, 0);
		ROLLBACK;
		RETURN;
	END

    INSERT INTO [HISTORYSYSTEMSETUP]
    (	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT
			[inserted].[IMINSPECTIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Inspection Type Added',
			'',
			'',
			'Inspection Type (' + [inserted].[NAME] + ')',
			'D6001D91-4891-41A9-8056-33EE10520A48',
			1,
			1,
			[inserted].[NAME]
	FROM	[inserted]	
END
GO
CREATE TRIGGER [dbo].[TG_IMINSPECTIONTYPE_UPDATE] ON [dbo].[IMINSPECTIONTYPE]
   AFTER UPDATE
AS 
BEGIN
	SET NOCOUNT ON;
	-- Check if LASTCHANGEDBY contains VALID User Id and it Exists in USERS table, this is in replacement to foreign key reference of IMINSPECTIONTYPE table with USERS table.
	IF EXISTS (SELECT * FROM inserted 
		LEFT OUTER JOIN USERS WITH (NOLOCK) ON USERS.SUSERGUID = inserted.LASTCHANGEDBY
		WHERE inserted.LASTCHANGEDBY IS NOT NULL AND USERS.SUSERGUID IS NULL)
	BEGIN		
		RAISERROR ('The INSERT or UPDATE statement conflicted with the FOREIGN KEY to table USERS', 16, 0);
		ROLLBACK;
		RETURN;
	END

    INSERT INTO [HISTORYSYSTEMSETUP]
    (	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT
			[inserted].[IMINSPECTIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Name',
			[deleted].[NAME],
			[inserted].[NAME],
			'Inspection Type (' + [inserted].[NAME] + ')',
			'D6001D91-4891-41A9-8056-33EE10520A48',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[IMINSPECTIONTYPEID] = [inserted].[IMINSPECTIONTYPEID]
	WHERE	[deleted].[NAME] <> [inserted].[NAME]
	UNION ALL
	SELECT
			[inserted].[IMINSPECTIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Description',
			ISNULL([deleted].[DESCRIPTION],'[none]'),
			ISNULL([inserted].[DESCRIPTION],'[none]'),
			'Inspection Type (' + [inserted].[NAME] + ')',
			'D6001D91-4891-41A9-8056-33EE10520A48',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[IMINSPECTIONTYPEID] = [inserted].[IMINSPECTIONTYPEID]
	WHERE	ISNULL([deleted].[DESCRIPTION], '') <> ISNULL([inserted].[DESCRIPTION], '')
	UNION ALL
	SELECT
			[inserted].[IMINSPECTIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'IVR Number',
			ISNULL([deleted].[IVRNUMBER],'[none]'),
			ISNULL([inserted].[IVRNUMBER],'[none]'),
			'Inspection Type (' + [inserted].[NAME] + ')',
			'D6001D91-4891-41A9-8056-33EE10520A48',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[IMINSPECTIONTYPEID] = [inserted].[IMINSPECTIONTYPEID]
	WHERE	ISNULL([deleted].[IVRNUMBER], '') <> ISNULL([inserted].[IVRNUMBER], '')
	UNION ALL
	SELECT
			[inserted].[IMINSPECTIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Calendar',
			ISNULL([IMINSPECTIONCALENDAR_DELETED].[NAME],'[none]'),
			ISNULL([IMINSPECTIONCALENDAR_INSERTED].[NAME],'[none]'),
			'Inspection Type (' + [inserted].[NAME] + ')',
			'D6001D91-4891-41A9-8056-33EE10520A48',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[IMINSPECTIONTYPEID] = [inserted].[IMINSPECTIONTYPEID]
			LEFT JOIN [IMINSPECTIONCALENDAR] [IMINSPECTIONCALENDAR_DELETED] WITH (NOLOCK) ON [IMINSPECTIONCALENDAR_DELETED].[IMINSPECTIONCALENDARID] = [deleted].[IMINSPECTIONCALENDARID]
			LEFT JOIN [IMINSPECTIONCALENDAR] [IMINSPECTIONCALENDAR_INSERTED] WITH (NOLOCK) ON [IMINSPECTIONCALENDAR_INSERTED].[IMINSPECTIONCALENDARID] = [inserted].[IMINSPECTIONCALENDARID]
	WHERE	ISNULL([deleted].[IMINSPECTIONCALENDARID], '') <> ISNULL([inserted].[IMINSPECTIONCALENDARID], '')	
	UNION ALL
	SELECT
			[inserted].[IMINSPECTIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Priority Number',
			ISNULL(CONVERT(NVARCHAR(MAX),[deleted].[PRIORITYNUMBER]),'[none]'),
			ISNULL(CONVERT(NVARCHAR(MAX),[inserted].[PRIORITYNUMBER]),'[none]'),
			'Inspection Type (' + [inserted].[NAME] + ')',
			'D6001D91-4891-41A9-8056-33EE10520A48',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[IMINSPECTIONTYPEID] = [inserted].[IMINSPECTIONTYPEID]
	WHERE	ISNULL([deleted].[PRIORITYNUMBER], '') <> ISNULL([inserted].[PRIORITYNUMBER], '')
	UNION ALL
	SELECT
			[inserted].[IMINSPECTIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Inspection Type Group',
			ISNULL([IMINSPECTIONTYPEGROUP_DELETED].[NAME],'[none]'),
			ISNULL([IMINSPECTIONTYPEGROUP_INSERTED].[NAME],'[none]'),
			'Inspection Type (' + [inserted].[NAME] + ')',
			'D6001D91-4891-41A9-8056-33EE10520A48',
			2,
			1,
			[inserted].[NAME]	FROM	[deleted]
			JOIN [inserted] ON [deleted].[IMINSPECTIONTYPEID] = [inserted].[IMINSPECTIONTYPEID]
			LEFT JOIN [IMINSPECTIONTYPEGROUP] [IMINSPECTIONTYPEGROUP_DELETED] WITH (NOLOCK) ON [IMINSPECTIONTYPEGROUP_DELETED].[IMINSPECTIONTYPEGROUPID] = [deleted].[IMINSPECTIONTYPEGROUPID]
			LEFT JOIN [IMINSPECTIONTYPEGROUP] [IMINSPECTIONTYPEGROUP_INSERTED] WITH (NOLOCK) ON [IMINSPECTIONTYPEGROUP_INSERTED].[IMINSPECTIONTYPEGROUPID] = [inserted].[IMINSPECTIONTYPEGROUPID]
	WHERE	ISNULL([deleted].[IMINSPECTIONTYPEGROUPID], '') <> ISNULL([inserted].[IMINSPECTIONTYPEGROUPID], '')
	UNION ALL
	SELECT
			[inserted].[IMINSPECTIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Department',
			ISNULL([DEPARTMENT_DELETED].[NAME],'[none]'),
			ISNULL([DEPARTMENT_INSERTED].[NAME],'[none]'),
			'Inspection Type (' + [inserted].[NAME] + ')',
			'D6001D91-4891-41A9-8056-33EE10520A48',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[IMINSPECTIONTYPEID] = [inserted].[IMINSPECTIONTYPEID]
			LEFT JOIN [DEPARTMENT] [DEPARTMENT_DELETED] WITH (NOLOCK) ON [DEPARTMENT_DELETED].[DEPARTMENTID] = [deleted].[DEPARTMENTID]
			LEFT JOIN [DEPARTMENT] [DEPARTMENT_INSERTED] WITH (NOLOCK) ON [DEPARTMENT_INSERTED].[DEPARTMENTID] = [inserted].[DEPARTMENTID]
	WHERE	ISNULL([deleted].[DEPARTMENTID], '') <> ISNULL([inserted].[DEPARTMENTID], '')
	UNION ALL
	SELECT 
			[inserted].[IMINSPECTIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Custom Field Layout',
			ISNULL([CUSTOMFIELDLAYOUT_DELETED].[SNAME],'[none]'),		
			ISNULL([CUSTOMFIELDLAYOUT_INSERTED].[SNAME],'[none]'),
			'Inspection Type (' + [inserted].[NAME] + ')',
			'D6001D91-4891-41A9-8056-33EE10520A48',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[IMINSPECTIONTYPEID] = [inserted].[IMINSPECTIONTYPEID]
			LEFT JOIN [CUSTOMFIELDLAYOUT] [CUSTOMFIELDLAYOUT_DELETED] WITH (NOLOCK) ON [deleted].[GCUSTOMFIELDLAYOUTS] = [CUSTOMFIELDLAYOUT_DELETED].[GCUSTOMFIELDLAYOUTS]
			LEFT JOIN [CUSTOMFIELDLAYOUT] [CUSTOMFIELDLAYOUT_INSERTED] WITH (NOLOCK) ON [inserted].[GCUSTOMFIELDLAYOUTS] = [CUSTOMFIELDLAYOUT_INSERTED].[GCUSTOMFIELDLAYOUTS]
	WHERE	ISNULL([deleted].[GCUSTOMFIELDLAYOUTS],'') <> ISNULL([inserted].[GCUSTOMFIELDLAYOUTS],'')
	UNION ALL
	SELECT
			[inserted].[IMINSPECTIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Default Status',
			ISNULL([IMINSPECTIONSTATUS_DELETED].[STATUSNAME],'[none]'),
			ISNULL([IMINSPECTIONSTATUS_INSERTED].[STATUSNAME],'[none]'),
			'Inspection Type (' + [inserted].[NAME] + ')',
			'D6001D91-4891-41A9-8056-33EE10520A48',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[IMINSPECTIONTYPEID] = [inserted].[IMINSPECTIONTYPEID]
			LEFT JOIN [IMINSPECTIONSTATUS] [IMINSPECTIONSTATUS_INSERTED] WITH (NOLOCK) ON [IMINSPECTIONSTATUS_INSERTED].[IMINSPECTIONSTATUSID] = [inserted].[IMINSPECTIONSTATUSID]
			LEFT JOIN [IMINSPECTIONSTATUS] [IMINSPECTIONSTATUS_DELETED] WITH (NOLOCK) ON [IMINSPECTIONSTATUS_DELETED].[IMINSPECTIONSTATUSID] = [deleted].[IMINSPECTIONSTATUSID]
	WHERE	ISNULL([deleted].[IMINSPECTIONSTATUSID],'') <> ISNULL([inserted].[IMINSPECTIONSTATUSID],'')
	UNION ALL
	SELECT
			[inserted].[IMINSPECTIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Prefix',
			ISNULL([deleted].[PREFIX],'[none]'),
			ISNULL([inserted].[PREFIX],'[none]'),
			'Inspection Type (' + [inserted].[NAME] + ')',
			'D6001D91-4891-41A9-8056-33EE10520A48',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[IMINSPECTIONTYPEID] = [inserted].[IMINSPECTIONTYPEID]
	WHERE	ISNULL([deleted].[PREFIX], '') <> ISNULL([inserted].[PREFIX], '')
	UNION ALL
	SELECT 
			[inserted].[IMINSPECTIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Online Custom Field Layout',
			ISNULL([ONLINECUSTOMFIELDLAYOUT_DELETED].[SNAME],'[none]'),
			ISNULL([ONLINECUSTOMFIELDLAYOUT_INSERTED].[SNAME],'[none]'),
			'Inspection Type (' + [inserted].[NAME] + ')',
			'D6001D91-4891-41A9-8056-33EE10520A48',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[IMINSPECTIONTYPEID] = [inserted].[IMINSPECTIONTYPEID]			
			LEFT JOIN [CUSTOMFIELDLAYOUT] [ONLINECUSTOMFIELDLAYOUT_DELETED] WITH (NOLOCK) ON [deleted].[GONLINECUSTOMFIELDLAYOUTS] = [ONLINECUSTOMFIELDLAYOUT_DELETED].[GCUSTOMFIELDLAYOUTS]
			LEFT JOIN [CUSTOMFIELDLAYOUT] [ONLINECUSTOMFIELDLAYOUT_INSERTED] WITH (NOLOCK) ON [inserted].[GONLINECUSTOMFIELDLAYOUTS] = [ONLINECUSTOMFIELDLAYOUT_INSERTED].[GCUSTOMFIELDLAYOUTS]
	WHERE	ISNULL([deleted].[GONLINECUSTOMFIELDLAYOUTS],'') <> ISNULL([inserted].[GONLINECUSTOMFIELDLAYOUTS],'')
	UNION ALL
	SELECT 
			[inserted].[IMINSPECTIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Schedule Inspection As',
			[IMINSPECTIONSCHEDULETYPE_DELETED].[NAME],
			[IMINSPECTIONSCHEDULETYPE_INSERTED].[NAME],
			'Inspection Type (' + [inserted].[NAME] + ')',
			'D6001D91-4891-41A9-8056-33EE10520A48',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[IMINSPECTIONTYPEID] = [inserted].[IMINSPECTIONTYPEID]			
			INNER JOIN [IMINSPECTIONSCHEDULETYPE] [IMINSPECTIONSCHEDULETYPE_DELETED] WITH (NOLOCK) ON [deleted].[IMINSPECTIONSCHEDULETYPEID] = [IMINSPECTIONSCHEDULETYPE_DELETED].[IMINSPECTIONSCHEDULETYPEID]
			INNER JOIN [IMINSPECTIONSCHEDULETYPE] [IMINSPECTIONSCHEDULETYPE_INSERTED] WITH (NOLOCK) ON [inserted].[IMINSPECTIONSCHEDULETYPEID] = [IMINSPECTIONSCHEDULETYPE_INSERTED].[IMINSPECTIONSCHEDULETYPEID]
	WHERE	[deleted].[IMINSPECTIONSCHEDULETYPEID] <> [inserted].[IMINSPECTIONSCHEDULETYPEID]
	UNION ALL
	SELECT
			[inserted].[IMINSPECTIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Extend Date Flag',
			CASE [deleted].[EXTEND_DATE] WHEN 1 THEN 'Yes' WHEN 0 THEN 'No' END,
			CASE [inserted].[EXTEND_DATE] WHEN 1 THEN 'Yes' WHEN 0 THEN 'No' END,			
			'Inspection Type (' + [inserted].[NAME] + ')',
			'D6001D91-4891-41A9-8056-33EE10520A48',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[IMINSPECTIONTYPEID] = [inserted].[IMINSPECTIONTYPEID]
	WHERE	[deleted].[EXTEND_DATE] <> [inserted].[EXTEND_DATE]
	
	UNION ALL
	SELECT
			[inserted].[IMINSPECTIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'GIS Zone Data Source',
			ISNULL([GISZONEMAPPING_DELETED].[SOURCENAME],'[none]'),
			ISNULL([GISZONEMAPPING_INSERTED].[SOURCENAME],'[none]'),
			'Inspection Type (' + [inserted].[NAME] + ')',
			'D6001D91-4891-41A9-8056-33EE10520A48',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[IMINSPECTIONTYPEID] = [inserted].[IMINSPECTIONTYPEID]
			LEFT JOIN [GISZONEMAPPING] [GISZONEMAPPING_INSERTED] WITH (NOLOCK) ON [GISZONEMAPPING_INSERTED].[GISZONEMAPPINGID] = [inserted].[GISZONEMAPPINGID]
			LEFT JOIN [GISZONEMAPPING] [GISZONEMAPPING_DELETED] WITH (NOLOCK) ON [GISZONEMAPPING_DELETED].[GISZONEMAPPINGID] = [deleted].[GISZONEMAPPINGID]
	WHERE	ISNULL([deleted].[GISZONEMAPPINGID], '') <> ISNULL([inserted].[GISZONEMAPPINGID], '')
	UNION ALL
	SELECT
			[inserted].[IMINSPECTIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'GIS Assignment Method',
			[IMINSPECTIONGISASSIGNMENT_DELETED].[NAME],
			[IMINSPECTIONGISASSIGNMENT_INSERTED].[NAME],
			'Inspection Type (' + [inserted].[NAME] + ')',
			'D6001D91-4891-41A9-8056-33EE10520A48',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[IMINSPECTIONTYPEID] = [inserted].[IMINSPECTIONTYPEID]
			INNER JOIN [IMINSPECTIONGISASSIGNMENT] [IMINSPECTIONGISASSIGNMENT_INSERTED] WITH (NOLOCK) ON [IMINSPECTIONGISASSIGNMENT_INSERTED].[IMINSPECTIONGISASSIGNMENTID] = [inserted].[IMINSPECTIONGISASSIGNMENTID]
			INNER JOIN [IMINSPECTIONGISASSIGNMENT] [IMINSPECTIONGISASSIGNMENT_DELETED] WITH (NOLOCK) ON [IMINSPECTIONGISASSIGNMENT_DELETED].[IMINSPECTIONGISASSIGNMENTID] = [deleted].[IMINSPECTIONGISASSIGNMENTID]
	WHERE	[deleted].[IMINSPECTIONGISASSIGNMENTID] <> [inserted].[IMINSPECTIONGISASSIGNMENTID]
	UNION ALL
	SELECT 
			[inserted].[IMINSPECTIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Fee Template',
			ISNULL([CAFEETEMPLATE_DELETED].[CAFEETEMPLATENAME],'[none]'),
			ISNULL([CAFEETEMPLATE_INSERTED].[CAFEETEMPLATENAME],'[none]'),
			'Inspection Type (' + [inserted].[NAME] + ')',
			'D6001D91-4891-41A9-8056-33EE10520A48',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[IMINSPECTIONTYPEID] = [inserted].[IMINSPECTIONTYPEID]
			LEFT JOIN [CAFEETEMPLATE] [CAFEETEMPLATE_DELETED] WITH (NOLOCK) ON [deleted].[CAFEETEMPLATEID] = [CAFEETEMPLATE_DELETED].[CAFEETEMPLATEID]
			LEFT JOIN [CAFEETEMPLATE] [CAFEETEMPLATE_INSERTED] WITH (NOLOCK) ON [inserted].[CAFEETEMPLATEID] = [CAFEETEMPLATE_INSERTED].[CAFEETEMPLATEID]
	WHERE	ISNULL([deleted].[CAFEETEMPLATEID],'') <> ISNULL([inserted].[CAFEETEMPLATEID],'')
	UNION ALL
	SELECT
			[inserted].[IMINSPECTIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Copy Checklist information Flag',
			CASE [deleted].[COPYCHECKLISTINFO] WHEN 1 THEN 'Yes' WHEN 0 THEN 'No' END,
			CASE [inserted].[COPYCHECKLISTINFO] WHEN 1 THEN 'Yes' WHEN 0 THEN 'No' END,			
			'Inspection Type (' + [inserted].[NAME] + ')',
			'D6001D91-4891-41A9-8056-33EE10520A48',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[IMINSPECTIONTYPEID] = [inserted].[IMINSPECTIONTYPEID]
	WHERE	[deleted].[COPYCHECKLISTINFO] <> [inserted].[COPYCHECKLISTINFO]
	UNION ALL
	SELECT
			[inserted].[IMINSPECTIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Allow Public Requests Flag',
			CASE [deleted].[ALLOWPUBLICREQUESTS] WHEN 1 THEN 'Yes' WHEN 0 THEN 'No' END,
			CASE [inserted].[ALLOWPUBLICREQUESTS] WHEN 1 THEN 'Yes' WHEN 0 THEN 'No' END,			
			'Inspection Type (' + [inserted].[NAME] + ')',
			'D6001D91-4891-41A9-8056-33EE10520A48',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[IMINSPECTIONTYPEID] = [inserted].[IMINSPECTIONTYPEID]
	WHERE	[deleted].[ALLOWPUBLICREQUESTS] <> [inserted].[ALLOWPUBLICREQUESTS]
	UNION ALL
	SELECT
			[inserted].[IMINSPECTIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Inspection Limit Exempt Flag',
			CASE [deleted].[ISLIMITEXEMPT] WHEN 1 THEN 'Yes' WHEN 0 THEN 'No' END,
			CASE [inserted].[ISLIMITEXEMPT] WHEN 1 THEN 'Yes' WHEN 0 THEN 'No' END,			
			'Inspection Type (' + [inserted].[NAME] + ')',
			'D6001D91-4891-41A9-8056-33EE10520A48',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[IMINSPECTIONTYPEID] = [inserted].[IMINSPECTIONTYPEID]
	WHERE	[deleted].[ISLIMITEXEMPT] <> [inserted].[ISLIMITEXEMPT]
	UNION ALL
	SELECT
			[inserted].[IMINSPECTIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Reinspection Wait Time',
			CONVERT(NVARCHAR(MAX),[deleted].[REINSPECTWAITTIME]),
			CONVERT(NVARCHAR(MAX),[inserted].[REINSPECTWAITTIME]),
			'Inspection Type (' + [inserted].[NAME] + ')',
			'D6001D91-4891-41A9-8056-33EE10520A48',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[IMINSPECTIONTYPEID] = [inserted].[IMINSPECTIONTYPEID]
	WHERE	[deleted].[REINSPECTWAITTIME] <> [inserted].[REINSPECTWAITTIME]
	UNION ALL
	SELECT
			[inserted].[IMINSPECTIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Enable Non-Compliance Tracking Flag',
			CASE [deleted].[ISNONCOMPLIANCETRACKED] WHEN 1 THEN 'Yes' WHEN 0 THEN 'No' END,
			CASE [inserted].[ISNONCOMPLIANCETRACKED] WHEN 1 THEN 'Yes' WHEN 0 THEN 'No' END,			
			'Inspection Type (' + [inserted].[NAME] + ')',
			'D6001D91-4891-41A9-8056-33EE10520A48',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[IMINSPECTIONTYPEID] = [inserted].[IMINSPECTIONTYPEID]
	WHERE	[deleted].[ISNONCOMPLIANCETRACKED] <> [inserted].[ISNONCOMPLIANCETRACKED]
	UNION ALL
	SELECT
			[inserted].[IMINSPECTIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Allow Online Compliance Submissions Flag',
			CASE [deleted].[ALLOWCAPNONCOMPLANCESUBMISSION] WHEN 1 THEN 'Yes' WHEN 0 THEN 'No' END,
			CASE [inserted].[ALLOWCAPNONCOMPLANCESUBMISSION] WHEN 1 THEN 'Yes' WHEN 0 THEN 'No' END,			
			'Inspection Type (' + [inserted].[NAME] + ')',
			'D6001D91-4891-41A9-8056-33EE10520A48',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[IMINSPECTIONTYPEID] = [inserted].[IMINSPECTIONTYPEID]
	WHERE	[deleted].[ALLOWCAPNONCOMPLANCESUBMISSION] <> [inserted].[ALLOWCAPNONCOMPLANCESUBMISSION]
	UNION ALL
	SELECT
			[inserted].[IMINSPECTIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Estimated Minutes / Factor',
			ISNULL(CONVERT(NVARCHAR(22),[deleted].[ESTIMATEDMINUTES]),'[none]'),
			ISNULL(CONVERT(NVARCHAR(22),[inserted].[ESTIMATEDMINUTES]),'[none]'),
			'Inspection Type (' + [inserted].[NAME] + ')',
			'D6001D91-4891-41A9-8056-33EE10520A48',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[IMINSPECTIONTYPEID] = [inserted].[IMINSPECTIONTYPEID]
	WHERE	ISNULL(CONVERT(NVARCHAR(22),[deleted].[ESTIMATEDMINUTES]),'') <> ISNULL(CONVERT(NVARCHAR(22),[inserted].[ESTIMATEDMINUTES]), '')
	UNION ALL
	SELECT
			[inserted].[IMINSPECTIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Estimation Link Type',
			[IMINSPECTIONLINK_DELETED].[NAME],
			[IMINSPECTIONLINK_INSERTED].[NAME],
			'Inspection Type (' + [inserted].[NAME] + ')',
			'D6001D91-4891-41A9-8056-33EE10520A48',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[IMINSPECTIONTYPEID] = [inserted].[IMINSPECTIONTYPEID]
			INNER JOIN [IMINSPECTIONLINK] [IMINSPECTIONLINK_DELETED] WITH (NOLOCK) ON [IMINSPECTIONLINK_DELETED].[IMINSPECTIONLINKID] = [deleted].[IMINSPECTIONLINKID]
			INNER JOIN [IMINSPECTIONLINK] [IMINSPECTIONLINK_INSERTED] WITH (NOLOCK) ON [IMINSPECTIONLINK_INSERTED].[IMINSPECTIONLINKID] = [inserted].[IMINSPECTIONLINKID]
	WHERE	[deleted].[IMINSPECTIONLINKID] <> [inserted].[IMINSPECTIONLINKID]
	UNION ALL
	SELECT
			[inserted].[IMINSPECTIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Estimation Field',
			ISNULL([deleted].[PROPERTYFRIENDLYNAME],'[none]'),
			ISNULL([inserted].[PROPERTYFRIENDLYNAME],'[none]'),
			'Inspection Type (' + [inserted].[NAME] + ')',
			'D6001D91-4891-41A9-8056-33EE10520A48',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[IMINSPECTIONTYPEID] = [inserted].[IMINSPECTIONTYPEID]			
	WHERE	ISNULL([deleted].[PROPERTYFRIENDLYNAME],'') <> ISNULL([inserted].[PROPERTYFRIENDLYNAME],'')
	UNION ALL
	SELECT
			[inserted].[IMINSPECTIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Allow to Create Code Case From Mobile Flag',
			CASE [deleted].[ISALLOWCODECASEFROMMOBILE] WHEN 1 THEN 'Yes' WHEN 0 THEN 'No' END,
			CASE [inserted].[ISALLOWCODECASEFROMMOBILE] WHEN 1 THEN 'Yes' WHEN 0 THEN 'No' END,			
			'Inspection Type (' + [inserted].[NAME] + ')',
			'D6001D91-4891-41A9-8056-33EE10520A48',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[IMINSPECTIONTYPEID] = [inserted].[IMINSPECTIONTYPEID]
	WHERE	[deleted].[ISALLOWCODECASEFROMMOBILE] <> [inserted].[ISALLOWCODECASEFROMMOBILE]
	UNION ALL
	SELECT
			[inserted].[IMINSPECTIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Recurrence Cycle Name',
			ISNULL([RECURRENCE_DELETED].[NAME],'[none]'),
			ISNULL([RECURRENCE_INSERTED].[NAME],'[none]'),		
			'Inspection Type (' + [inserted].[NAME] + ')',
			'D6001D91-4891-41A9-8056-33EE10520A48',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[IMINSPECTIONTYPEID] = [inserted].[IMINSPECTIONTYPEID]
			LEFT JOIN [RECURRENCE] [RECURRENCE_DELETED] WITH (NOLOCK) ON [RECURRENCE_DELETED].[RECURRENCEID] = [deleted].[RECURRENCEID]
			LEFT JOIN [RECURRENCE] [RECURRENCE_INSERTED] WITH (NOLOCK) ON [RECURRENCE_INSERTED].[RECURRENCEID] = [inserted].[RECURRENCEID]
	WHERE	ISNULL([deleted].[RECURRENCEID],'') <> ISNULL([inserted].[RECURRENCEID],'')
	UNION ALL
	SELECT
			[inserted].[IMINSPECTIONTYPEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Spanish Description',
			ISNULL([deleted].[DESCRIPTION_SPANISH],'[none]'),
			ISNULL([inserted].[DESCRIPTION_SPANISH],'[none]'),
			'Inspection Type (' + [inserted].[NAME] + ')',
			'D6001D91-4891-41A9-8056-33EE10520A48',
			2,
			1,
			[inserted].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[IMINSPECTIONTYPEID] = [inserted].[IMINSPECTIONTYPEID]
	WHERE	ISNULL([deleted].[DESCRIPTION_SPANISH], '') <> ISNULL([inserted].[DESCRIPTION_SPANISH], '')
END