CREATE TABLE [dbo].[IMINSPECTIONREQUESTEDSOURCE] (
    [IMINSPECTIONREQUESTEDSOURCEID] INT            NOT NULL,
    [NAME]                          NVARCHAR (100) NOT NULL,
    CONSTRAINT [PK_IMInspectionRequestedSource] PRIMARY KEY CLUSTERED ([IMINSPECTIONREQUESTEDSOURCEID] ASC) WITH (FILLFACTOR = 90)
);

