CREATE TABLE [dbo].[IMINSPECTIONCASEADDRESS] (
    [IMINSPECTIONCASEADDRESSID] CHAR (36) NOT NULL,
    [IMINSPECTIONCASEID]        CHAR (36) NOT NULL,
    [MAILINGADDRESSID]          CHAR (36) NOT NULL,
    [MAIN]                      BIT       NOT NULL,
    CONSTRAINT [PK_IMINSPECTIONCASEADDRESS] PRIMARY KEY CLUSTERED ([IMINSPECTIONCASEADDRESSID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_IMINSPECTIONCASEADDRESS_CA] FOREIGN KEY ([IMINSPECTIONCASEID]) REFERENCES [dbo].[IMINSPECTIONCASE] ([IMINSPECTIONCASEID]),
    CONSTRAINT [FK_IMINSPECTIONCASEADDRESS_MA] FOREIGN KEY ([MAILINGADDRESSID]) REFERENCES [dbo].[MAILINGADDRESS] ([MAILINGADDRESSID])
);

