CREATE TABLE [dbo].[IMINSPECTIONCHECKLISTXREF] (
    [IMINSPECTIONCHECKLISTXREFID] CHAR (36)      NOT NULL,
    [IMINSPECTIONID]              CHAR (36)      NOT NULL,
    [IMCHECKLISTID]               CHAR (36)      NOT NULL,
    [PASSED]                      BIT            NOT NULL,
    [COMMENTS]                    NVARCHAR (MAX) NULL,
    [ORDERNUM]                    INT            NULL,
    [ISNA]                        BIT            DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_IMInspectionChecklistxRef] PRIMARY KEY CLUSTERED ([IMINSPECTIONCHECKLISTXREFID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_IMInspectionChecklistxRef_I] FOREIGN KEY ([IMCHECKLISTID]) REFERENCES [dbo].[IMCHECKLIST] ([IMCHECKLISTID]),
    CONSTRAINT [FK_InspChkXRef_Insp] FOREIGN KEY ([IMINSPECTIONID]) REFERENCES [dbo].[IMINSPECTION] ([IMINSPECTIONID])
);


GO
CREATE NONCLUSTERED INDEX [IX_IMINSPECTIONCHECKLT_INSP]
    ON [dbo].[IMINSPECTIONCHECKLISTXREF]([IMINSPECTIONID] ASC, [IMCHECKLISTID] ASC) WITH (FILLFACTOR = 80);

