CREATE TABLE [dbo].[IMOCCUPANCYPERMIT] (
    [IMOCCUPANCYPERMITID] CHAR (36)      NOT NULL,
    [IMINSPECTIONID]      CHAR (36)      NOT NULL,
    [FOPERMITTYPEID]      CHAR (36)      NOT NULL,
    [NOTE]                NVARCHAR (MAX) NULL,
    [QUANTITY]            INT            DEFAULT ((0)) NOT NULL,
    [FOPERMITSTATUSID]    CHAR (36)      NOT NULL,
    [ISSUEDDATE]          DATETIME       NOT NULL,
    [EXPIREDDATE]         DATETIME       NULL,
    [CREATEDBY]           CHAR (36)      NOT NULL,
    [CREATEDON]           DATETIME       NOT NULL,
    [LASTCHANGEDBY]       CHAR (36)      NOT NULL,
    [LASTCHANGEDON]       DATETIME       NOT NULL,
    CONSTRAINT [PK_IMOCCUPANCYPERMIT] PRIMARY KEY CLUSTERED ([IMOCCUPANCYPERMITID] ASC),
    CONSTRAINT [FK_IMOCCUPANCYPERMIT_FOPERMITSTATUS] FOREIGN KEY ([FOPERMITSTATUSID]) REFERENCES [dbo].[FOPERMITSTATUS] ([FOPERMITSTATUSID]),
    CONSTRAINT [FK_IMOCCUPANCYPERMIT_IMINSPECTION] FOREIGN KEY ([IMINSPECTIONID]) REFERENCES [dbo].[IMINSPECTION] ([IMINSPECTIONID]),
    CONSTRAINT [FK_IMOCCUPANCYPERMIT_PERMITTYPE] FOREIGN KEY ([FOPERMITTYPEID]) REFERENCES [dbo].[FOPERMITTYPE] ([FOPERMITTYPEID]),
    CONSTRAINT [FK_IMOCCUPANCYPERMIT_USERS_CREATEDBY] FOREIGN KEY ([CREATEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID]),
    CONSTRAINT [FK_IMOCCUPANCYPERMIT_USERS_LASTCHANGEDBY] FOREIGN KEY ([LASTCHANGEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);


GO
CREATE NONCLUSTERED INDEX [IX_IMOCCUPANCYPERMIT_CREATEDBY]
    ON [dbo].[IMOCCUPANCYPERMIT]([CREATEDBY] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_IMOCCUPANCYPERMIT_FOPERMITSTATUSID]
    ON [dbo].[IMOCCUPANCYPERMIT]([FOPERMITSTATUSID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_IMOCCUPANCYPERMIT_IMINSPECTIONID]
    ON [dbo].[IMOCCUPANCYPERMIT]([IMINSPECTIONID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_IMOCCUPANCYPERMIT_LASTCHANGEDBY]
    ON [dbo].[IMOCCUPANCYPERMIT]([LASTCHANGEDBY] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_IMOCCUPANCYPERMIT_FOPERMITTYPEID]
    ON [dbo].[IMOCCUPANCYPERMIT]([FOPERMITTYPEID] ASC);

