CREATE TABLE [dbo].[IMPREREQRULEGROUPXREF] (
    [IMPREREQRULEID]  CHAR (36) NOT NULL,
    [IMPREREQGROUPID] CHAR (36) NOT NULL,
    CONSTRAINT [PK_IMPREREQRULEGROUPXREF] PRIMARY KEY CLUSTERED ([IMPREREQRULEID] ASC, [IMPREREQGROUPID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_RULEGROUPXREF_IMPREREQGROUP] FOREIGN KEY ([IMPREREQGROUPID]) REFERENCES [dbo].[IMPREREQGROUP] ([IMPREREQGROUPID]),
    CONSTRAINT [FK_RULEGROUPXREF_IMPREREQRULE] FOREIGN KEY ([IMPREREQRULEID]) REFERENCES [dbo].[IMPREREQRULE] ([IMPREREQRULEID])
);

