CREATE TABLE [dbo].[IMPREREQCONDITION] (
    [IMPREREQCONDITIONID]    CHAR (36)      NOT NULL,
    [CONDITIONNAME]          NVARCHAR (50)  NOT NULL,
    [CONDITIONDESCRIPTION]   NVARCHAR (MAX) NULL,
    [FIELDLOGICALOPERATOR]   NVARCHAR (3)   NULL,
    [CASETYPEID]             CHAR (36)      NULL,
    [CASEWORKCLASSID]        CHAR (36)      NULL,
    [MODULE]                 INT            NOT NULL,
    [IMINSPECTIONTYPEID]     CHAR (36)      NULL,
    [PARENTGROUPCONDITIONID] CHAR (36)      NULL,
    [PARENTGROUPORCOND]      BIT            NULL,
    [PARENTMODULE]           INT            NULL,
    [CHILDGROUPCONDITIONID]  CHAR (36)      NULL,
    [CHILDGROUPORCOND]       BIT            NULL,
    [CHILDMODULE]            INT            NULL,
    [FAILMESSAGE]            NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_IMPREREQCONDITION] PRIMARY KEY CLUSTERED ([IMPREREQCONDITIONID] ASC) WITH (FILLFACTOR = 90)
);

