CREATE TABLE [dbo].[INSPECTIONNOTE_CHANGESET] (
    [INSPECTIONNOTE_CHANGESET_ID] CHAR (36)      NOT NULL,
    [INSPECTION_ID]               CHAR (36)      NOT NULL,
    [CREATED_BY_ID]               CHAR (36)      NOT NULL,
    [TEXT]                        NVARCHAR (MAX) NOT NULL,
    [CHANGESET_TAG]               CHAR (36)      NOT NULL,
    [CHANGE_TYPE]                 INT            NOT NULL,
    [SENT]                        BIT            NOT NULL,
    [APPLIED]                     BIT            NOT NULL,
    [CHANGE_COUNT]                INT            NOT NULL,
    CONSTRAINT [PK_INSPECTION_INSPECTIONNOTE_CHANGESET] PRIMARY KEY CLUSTERED ([INSPECTIONNOTE_CHANGESET_ID] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [IX_INSPECTIONNOTE_CHANGESET_SET]
    ON [dbo].[INSPECTIONNOTE_CHANGESET]([CHANGESET_TAG] ASC);

