CREATE TABLE [dbo].[INSTOREITEMSTATUS] (
    [INSTOREITEMSTATUSID] CHAR (36)      NOT NULL,
    [NAME]                VARCHAR (50)   NOT NULL,
    [DESCRIPTION]         NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_INStoreItemStatus] PRIMARY KEY CLUSTERED ([INSTOREITEMSTATUSID] ASC) WITH (FILLFACTOR = 90)
);

