CREATE TABLE [dbo].[INTAPPCONFIGPROCPARAM] (
    [INTAPPCONFIGPROCPARAMID] CHAR (36)      NOT NULL,
    [SQLDATATYPEID]           INT            NOT NULL,
    [INTAPPCONFIGID]          CHAR (36)      NOT NULL,
    [NAME]                    NVARCHAR (100) NOT NULL,
    [DESCRIPTION]             NVARCHAR (255) NULL,
    CONSTRAINT [PK_INTAPPCONFIGPROCPARAM] PRIMARY KEY CLUSTERED ([INTAPPCONFIGPROCPARAMID] ASC),
    CONSTRAINT [FK_INTAPPCONFIG_INTAPPCONFIGID] FOREIGN KEY ([INTAPPCONFIGID]) REFERENCES [dbo].[INTAPPCONFIG] ([INTAPPCONFIGID]),
    CONSTRAINT [FK_SQLDATATYPE_SQLDATATYPEID] FOREIGN KEY ([SQLDATATYPEID]) REFERENCES [dbo].[SQLDATATYPE] ([SQLDATATYPEID])
);


GO
CREATE NONCLUSTERED INDEX [IX_INTAPPCONFIGPROCPARAM_INTAPPCONFIGID]
    ON [dbo].[INTAPPCONFIGPROCPARAM]([INTAPPCONFIGID] ASC);

