CREATE TABLE [dbo].[IPCASE] (
    [IPCASEID]            CHAR (36)      NOT NULL,
    [CASENUMBER]          NVARCHAR (50)  NOT NULL,
    [DESCRIPTION]         NVARCHAR (MAX) NULL,
    [IPCASETYPEID]        CHAR (36)      NOT NULL,
    [IPCASESTATUSID]      CHAR (36)      NOT NULL,
    [SOURCECASEID]        CHAR (36)      NOT NULL,
    [SOURCECASENUMBER]    NVARCHAR (50)  NOT NULL,
    [PRPROJECTID]         CHAR (36)      NULL,
    [DISTRICTID]          CHAR (36)      NOT NULL,
    [CREATEDDATE]         DATETIME       NOT NULL,
    [APPROVALDATE]        DATETIME       NULL,
    [APPROVALEXPIREDDATE] DATETIME       NULL,
    [ROWVERSION]          INT            NOT NULL,
    [LASTCHANGEDON]       DATETIME       NOT NULL,
    [LASTCHANGEDBY]       CHAR (36)      NOT NULL,
    [SOURCECASEENTITY]    INT            NULL,
    CONSTRAINT [PK_IPCASE] PRIMARY KEY CLUSTERED ([IPCASEID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_IPCASE_DISTRICT] FOREIGN KEY ([DISTRICTID]) REFERENCES [dbo].[DISTRICT] ([DISTRICTID]),
    CONSTRAINT [FK_IPCASE_IPCASESTATUS] FOREIGN KEY ([IPCASESTATUSID]) REFERENCES [dbo].[IPCASESTATUS] ([IPCASESTATUSID]),
    CONSTRAINT [FK_IPCASE_IPCASETYPE] FOREIGN KEY ([IPCASETYPEID]) REFERENCES [dbo].[IPCASETYPE] ([IPCASETYPEID]),
    CONSTRAINT [FK_IPCASE_PRPROJECT] FOREIGN KEY ([PRPROJECTID]) REFERENCES [dbo].[PRPROJECT] ([PRPROJECTID]),
    CONSTRAINT [FK_IPCASE_USERS] FOREIGN KEY ([LASTCHANGEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);


GO

CREATE TRIGGER [TG_IPCASE_UPDATE_ELASTIC] ON IPCASE
	AFTER UPDATE
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO [ELASTICSEARCHOBJECT]
    ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID(),
		[Inserted].[IPCASEID],
		'EnerGovBusiness.ImpactManagement.ImpactCase',
		[Inserted].[ROWVERSION],
		GETDATE(),
		NULL,
		2,
		(SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Inserted];
END
GO

CREATE TRIGGER [TG_IPCASE_DELETE_ELASTIC] ON IPCASE
	AFTER DELETE
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO [ELASTICSEARCHOBJECT]
    ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID(),
		[Deleted].[IPCASEID],
		'EnerGovBusiness.ImpactManagement.ImpactCase',
		[Deleted].[ROWVERSION],
		GETDATE(),
		NULL,
		3,
		(SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Deleted];
END
GO

CREATE TRIGGER [TG_IPCASE_INSERT_ELASTIC] ON IPCASE
	AFTER INSERT
AS 
BEGIN
	SET NOCOUNT ON;

	INSERT INTO [ELASTICSEARCHOBJECT]
	 ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID(),
		[Inserted].[IPCASEID],
		'EnerGovBusiness.ImpactManagement.ImpactCase',
		[inserted].[ROWVERSION],
		GETDATE(),
		NULL,
		1,
		(SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Inserted];
END