CREATE TABLE [dbo].[IPCASEADDRESS] (
    [IPCASEADDRESSID]  CHAR (36) NOT NULL,
    [IPCASEID]         CHAR (36) NOT NULL,
    [MAILINGADDRESSID] CHAR (36) NOT NULL,
    [MAIN]             BIT       NOT NULL,
    CONSTRAINT [PK_IPCASEADDRESS] PRIMARY KEY CLUSTERED ([IPCASEADDRESSID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_IPCASEADDR_MAILINGADDR] FOREIGN KEY ([MAILINGADDRESSID]) REFERENCES [dbo].[MAILINGADDRESS] ([MAILINGADDRESSID]),
    CONSTRAINT [FK_IPCASEADDRESS_IPCASE] FOREIGN KEY ([IPCASEID]) REFERENCES [dbo].[IPCASE] ([IPCASEID])
);

