CREATE TABLE [dbo].[IPCASENOTE] (
    [IPCASENOTEID] CHAR (36)      NOT NULL,
    [IPCASEID]     CHAR (36)      NOT NULL,
    [TEXT]         NVARCHAR (MAX) NULL,
    [CREATEDBY]    CHAR (36)      NOT NULL,
    [CREATEDDATE]  DATETIME       NOT NULL,
    [TITLE]        NVARCHAR (50)  CONSTRAINT [DF_IPCASENOTE_TITLE] DEFAULT ('') NULL,
    [PIN]          BIT            CONSTRAINT [DF_IPCASENOTE_PIN] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_IPCASENOTE] PRIMARY KEY CLUSTERED ([IPCASENOTEID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_IPCASENOTE_IPCASE] FOREIGN KEY ([IPCASEID]) REFERENCES [dbo].[IPCASE] ([IPCASEID]),
    CONSTRAINT [FK_IPCASENOTE_USERS] FOREIGN KEY ([CREATEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);

