CREATE TABLE [dbo].[IPCONDITIONCASETYPE] (
    [IPCONDITIONCASETYPEID] CHAR (36) NOT NULL,
    [IPCONDITIONID]         CHAR (36) NOT NULL,
    [MODULECASETYPEID]      CHAR (36) NOT NULL,
    [MODULERECORDTYPEID]    INT       NOT NULL,
    CONSTRAINT [PK_IPCONDITIONCASETYPE] PRIMARY KEY CLUSTERED ([IPCONDITIONCASETYPEID] ASC),
    CONSTRAINT [FK_IPCONDITIONCASETYPE_IPCONDITION] FOREIGN KEY ([IPCONDITIONID]) REFERENCES [dbo].[IPCONDITION] ([IPCONDITIONID]),
    CONSTRAINT [FK_IPCONDITIONCASETYPE_MODULERECORDTYPE] FOREIGN KEY ([MODULERECORDTYPEID]) REFERENCES [dbo].[MODULERECORDTYPE] ([MODULERECORDTYPEID])
);


GO
CREATE NONCLUSTERED INDEX [IX_IPCONDITIONCASETYPE_IPCONDITIONID]
    ON [dbo].[IPCONDITIONCASETYPE]([IPCONDITIONID] ASC);

