CREATE TABLE [dbo].[IPCONDITIONNOTE] (
    [IPCONDITIONNOTEID] CHAR (36)      NOT NULL,
    [IPCONDITIONID]     CHAR (36)      NOT NULL,
    [TEXT]              NVARCHAR (MAX) NULL,
    [CREATEDBY]         CHAR (36)      NOT NULL,
    [CREATEDDATE]       DATETIME       NOT NULL,
    [TITLE]             NVARCHAR (50)  CONSTRAINT [DF_IPCONDITIONNOTE_TITLE] DEFAULT ('') NULL,
    [PIN]               BIT            CONSTRAINT [DF_IPCONDITIONNOTE_PIN] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_IPCONDITIONNOTE] PRIMARY KEY CLUSTERED ([IPCONDITIONNOTEID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_IPCONDITIONNOTE_IPCOND] FOREIGN KEY ([IPCONDITIONID]) REFERENCES [dbo].[IPCONDITION] ([IPCONDITIONID]),
    CONSTRAINT [FK_IPCONDITIONNOTE_USERS] FOREIGN KEY ([CREATEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);


GO
CREATE NONCLUSTERED INDEX [IPCONDITIONNOTE_IPCONDITION]
    ON [dbo].[IPCONDITIONNOTE]([IPCONDITIONID] ASC);

