CREATE TABLE [dbo].[IPCONDITIONCASETYPEWORKCLASS] (
    [IPCONDITIONCASETYPEWORKCLASSID] CHAR (36) NOT NULL,
    [IPCONDITIONCASETYPEID]          CHAR (36) NOT NULL,
    [MODULEWORKCLASSID]              CHAR (36) NOT NULL,
    CONSTRAINT [PK_IPCONDITIONCASETYPEWORKCLASS] PRIMARY KEY CLUSTERED ([IPCONDITIONCASETYPEWORKCLASSID] ASC),
    CONSTRAINT [FK_IPCONDITIONCASETYPEWORKCLASS_IPCONDITIONCASETYPE] FOREIGN KEY ([IPCONDITIONCASETYPEID]) REFERENCES [dbo].[IPCONDITIONCASETYPE] ([IPCONDITIONCASETYPEID])
);


GO
CREATE NONCLUSTERED INDEX [IX_IPCONDITIONCASETYPEWORKCLASS_IPCONDITIONCASETYPEID]
    ON [dbo].[IPCONDITIONCASETYPEWORKCLASS]([IPCONDITIONCASETYPEID] ASC);

