CREATE TABLE [dbo].[IPCONDITIONFUNALLOCATION] (
    [IPCONDITIONFUNDALLOCATIONID] CHAR (36)      NOT NULL,
    [IPCONDITIONID]               CHAR (36)      NOT NULL,
    [IPCAPITALPROJECTID]          CHAR (36)      NOT NULL,
    [RECOMMENDAMOUNT]             MONEY          NOT NULL,
    [APPROVEDAMOUNT]              MONEY          NULL,
    [APPROVEDDATE]                DATETIME       NULL,
    [RESOLUTIONNUMBER]            NVARCHAR (100) NULL,
    [COMMENTS]                    NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_IPCONDITIONFUNALLOCATION] PRIMARY KEY CLUSTERED ([IPCONDITIONFUNDALLOCATIONID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_IPCONDFUNALL_IPCAPITAL] FOREIGN KEY ([IPCAPITALPROJECTID]) REFERENCES [dbo].[IPCAPITALPROJECT] ([IPCAPITALPROJECTID]),
    CONSTRAINT [FK_IPCONDFUNALLO_IPCONDITION] FOREIGN KEY ([IPCONDITIONID]) REFERENCES [dbo].[IPCONDITION] ([IPCONDITIONID])
);

