CREATE TABLE [dbo].[IPCONDITIONMONETARY] (
    [IPCONDITIONMONETARYID]       CHAR (36)       NOT NULL,
    [IPCONDITIONID]               CHAR (36)       NOT NULL,
    [ASSESSAMOUNT]                MONEY           NOT NULL,
    [NUMOFCONDITIONUNIT]          DECIMAL (20, 4) NULL,
    [CAPCONDITIONUNIT]            BIT             NOT NULL,
    [IPTARGETEDFUNDTYPEID]        CHAR (36)       NOT NULL,
    [CREDITLANGUAGE]              BIT             NOT NULL,
    [LUMPSUM]                     BIT             NOT NULL,
    [IPINFLATIONTYPEID]           INT             NOT NULL,
    [EFFECTIVEDATE]               DATETIME        NULL,
    [BEGINNINGRATE]               DECIMAL (20, 4) NULL,
    [CURRENTRATE]                 DECIMAL (20, 4) NULL,
    [MAXIMUMRATE]                 DECIMAL (20, 4) NULL,
    [ORIGINASSESSAMOUNT]          MONEY           NOT NULL,
    [ORIGINTOTAL]                 MONEY           NOT NULL,
    [ACTUALCOLLECTEDTODATE]       MONEY           NOT NULL,
    [ORIGINACTUALCOLLECTEDTODATE] MONEY           NULL,
    CONSTRAINT [PK_IPCONDITIONMONETARY] PRIMARY KEY CLUSTERED ([IPCONDITIONMONETARYID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_IPCONDMONEY_IPCONDITION] FOREIGN KEY ([IPCONDITIONID]) REFERENCES [dbo].[IPCONDITION] ([IPCONDITIONID]),
    CONSTRAINT [FK_IPCONDMONEY_IPINFLATION] FOREIGN KEY ([IPINFLATIONTYPEID]) REFERENCES [dbo].[IPINFLATIONTYPE] ([IPINFLATIONTYPEID]),
    CONSTRAINT [FK_IPCONDMONEY_IPTARGETEDFUND] FOREIGN KEY ([IPTARGETEDFUNDTYPEID]) REFERENCES [dbo].[IPTARGETEDFUNDTYPE] ([IPTARGETEDFUNDTYPEID])
);

