CREATE TABLE [dbo].[IPGROUPIPCONDITIONS] (
    [IPGROUPIPCONDITIONSID] CHAR (36) NOT NULL,
    [IPCONDITIONGROUPID]    CHAR (36) NOT NULL,
    [IPCONDITIONID]         CHAR (36) NOT NULL,
    [SET]                   INT       NOT NULL,
    CONSTRAINT [PK_IPGROUPIPCONDITIONS] PRIMARY KEY CLUSTERED ([IPGROUPIPCONDITIONSID] ASC),
    CONSTRAINT [FK_IPGROUPIPCONDITIONS_IPCONDITION] FOREIGN KEY ([IPCONDITIONID]) REFERENCES [dbo].[IPCONDITION] ([IPCONDITIONID]),
    CONSTRAINT [FK_IPGROUPIPCONDITIONS_IPCONDITIONGROUP] FOREIGN KEY ([IPCONDITIONGROUPID]) REFERENCES [dbo].[IPCONDITIONGROUP] ([IPCONDITIONGROUPID])
);


GO
CREATE NONCLUSTERED INDEX [IX_IPGROUPIPCONDITIONS_IPCONDITIONGROUPID]
    ON [dbo].[IPGROUPIPCONDITIONS]([IPCONDITIONGROUPID] ASC);

