CREATE TABLE [dbo].[ITEM] (
    [ITEMID]        CHAR (36)       NOT NULL,
    [MANUFACTURER]  CHAR (36)       NULL,
    [NAME]          VARCHAR (100)   NOT NULL,
    [DESCRIPTION]   NVARCHAR (MAX)  NULL,
    [FUEL]          BIT             NOT NULL,
    [HAZARD]        BIT             NULL,
    [ITEMTYPEID]    CHAR (36)       NOT NULL,
    [UNITCOST]      MONEY           NULL,
    [ITEMSTATUSID]  CHAR (36)       NOT NULL,
    [LASTCHANGEDON] DATETIME        NULL,
    [LASTCHANGEDBY] CHAR (36)       NULL,
    [ROWVERSION]    INT             NOT NULL,
    [ITEMNO]        VARCHAR (50)    NOT NULL,
    [PHOTO]         VARBINARY (MAX) NULL,
    CONSTRAINT [PK_Item] PRIMARY KEY CLUSTERED ([ITEMID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Item_GECompany] FOREIGN KEY ([MANUFACTURER]) REFERENCES [dbo].[GLOBALENTITY] ([GLOBALENTITYID]),
    CONSTRAINT [FK_Item_ItemStatus] FOREIGN KEY ([ITEMSTATUSID]) REFERENCES [dbo].[ITEMSTATUS] ([ITEMSTATUSID]),
    CONSTRAINT [FK_Item_ItemType] FOREIGN KEY ([ITEMTYPEID]) REFERENCES [dbo].[ITEMTYPE] ([ITEMTYPEID]),
    CONSTRAINT [FK_Item_User] FOREIGN KEY ([LASTCHANGEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);

