

--exec [dbo].[rpt_BL_Tax_Remi_AccountUnreportedCoupon]
cREATE PROCEDURE [dbo].[rpt_BL_Tax_Remi_AccountUnreportedCoupon]

AS


SELECT  TX.AMOUNTREPORTED
       ,TXREMITTANCEACCOUNT.REMITTANCEACCOUNTNUMBER AS REMACCOUNT
       ,COALESCE(NULLIF(GLOBALENTITY.GLOBALENTITYNAME,''),'N/A') AS BUSINESSNAME
       ,TXRPTPERIOD.NAME REPORTPERIOD
       ,TXBILLPERIOD.STARTDATE, TXBILLPERIOD.ENDDATE,TXBILLPERIOD.DUEDATE,TxBillPeriod.PERIODNAME
       ,CAINVOICE.INVOICENUMBER,CAINVOICE.INVOICETOTAL
FROM TXREMITTANCE TX
INNER JOIN TXBILLPERIOD On TX.TXBILLPERIODID = TXBILLPERIOD.BILLPERIODID
INNER JOIN TXREMITTANCEACCOUNT ON Tx.TXREMITTANCEACCOUNTID = TXREMITTANCEACCOUNT.TXREMITTANCEACCOUNTID
LEFT OUTER JOIN TXRPTPERIOD ON TXREMITTANCEACCOUNT.REPORTPERIODID = TXRPTPERIOD.TXRPTPERIODID
INNER JOIN TXREMITSTATUS ON TXREMITTANCEACCOUNT.TXREMITTANCESTATUSID = TXREMITSTATUS.TXREMITSTATUSID
LEFT OUTER JOIN TXREMITTANCEFEE  ON Tx.TXREMITTANCEID = TXREMITTANCEFEE.TXREMITTANCEID
LEFT OUTER JOIN CACOMPUTEDFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = TXREMITTANCEFEE.CACOMPUTEDFEEID
LEFT OUTER JOIN CATRANSACTIONFEE ON CAComputedFee.CAComputedFeeID = CATransactionFee.CaComputedFeeID
LEFT OUTER JOIN CATRANSACTION ON  CATRANSACTION.CATRANSACTIONID = CATRANSACTIONFEE.CATRANSACTIONID 
LEFT OUTER JOIN CATRANSACTIONINVOICE ON CATRANSACTION.CATRANSACTIONID = CATRANSACTIONINVOICE.CATRANSACTIONID 
LEFT OUTER JOIN CAINVOICE ON CAINVOICE.CAINVOICEID = CATRANSACTIONINVOICE.CAINVOICEID 
INNER JOIN BLGLOBALENTITYEXTENSION ON TXREMITTANCEACCOUNT.BLGLOBALENTITYEXTENSIONID = BLGLOBALENTITYEXTENSION.BLGLOBALENTITYEXTENSIONID
INNER JOIN GLOBALENTITY ON GLOBALENTITY.GLOBALENTITYID  = BLGLOBALENTITYEXTENSION.GLOBALENTITYID

WHERE TxRemitStatus.TxRemitStatusSystemID <> 2 
--AND ((Tx.AmountReported IS NULL AND CaInvoice.InvoiceNumber IS NULL )OR (Tx.AmountReported = 0 AND CaInvoice.InvoiceNumber IS NULL ))
AND Tx.AmountReported IS NULL
ORDER BY TXBILLPERIOD.DUEDATE ASC
