

CREATE PROCEDURE [dbo].[rpt_BL_Companies_Opened_Reports_Address]
@GLOBALENTITYEXTENSIONID AS VARCHAR(36)
AS
SELECT MAILINGADDRESS.ADDRESSLINE1, MAILINGADDRESS.ADDRESSLINE2, MAILINGADDRESS.ADDRESSLINE3, MAILINGADDRESS.CITY, MAILINGADDRESS.STATE, 
       MAILINGADDRESS.POSTALCODE, MAILINGADDRESS.POSTDIRECTION, MAILINGADDRESS.PREDIRECTION, MAILINGADDRESS.STREETTYPE, 
       MAILINGADDRESS.UNITORSUITE
FROM BLGLOBALENTITYEXTENSIONADDRESS 
INNER JOIN MAILINGADDRESS ON BLGLOBALENTITYEXTENSIONADDRESS.MAILINGADDRESSID = MAILINGADDRESS.MAILINGADDRESSID
WHERE BLGLOBALENTITYEXTENSIONADDRESS.BLGLOBALENTITYEXTENSIONID = @GLOBALENTITYEXTENSIONID 
AND BLGLOBALENTITYEXTENSIONADDRESS.MAIN  = 'TRUE'

