CREATE PROCEDURE [dbo].[USP_BLTYPECLASSILCLASS_DELETE_BYPARENTID]  
(  
	@BLLICENSETYPEID CHAR(36),
	@BLLICENSETYPECLASSID CHAR(36),
	@BLTYPECLASSILTYPEID CHAR(36)
)  
AS  
BEGIN
	DELETE [dbo].[BLTYPECLASSILCLASS] FROM [dbo].[BLTYPECLASSILCLASS]  
	INNER JOIN [dbo].[BLTYPECLASSILTYPE]  
	 ON [dbo].[BLTYPECLASSILTYPE].[BLTYPECLASSILTYPEID] = [dbo].[BLTYPECLASSILCLASS].[BLTYPECLASSILTYPEID]  
	INNER JOIN [BLLICENSETYPECLASS]   
	 ON [dbo].[BLLICENSETYPECLASS].[BLLICENSETYPECLASSID] = [dbo].[BLTYPECLASSILTYPE].[BLLICENSETYPECLASSID]
	WHERE
		(@BLTYPECLASSILTYPEID IS NULL OR [dbo].[BLTYPECLASSILCLASS].[BLTYPECLASSILTYPEID] = @BLTYPECLASSILTYPEID)
		AND (@BLLICENSETYPEID IS NULL OR [dbo].[BLLICENSETYPECLASS].[BLLICENSETYPEID] = @BLLICENSETYPEID )
		AND (@BLLICENSETYPECLASSID IS NULL OR [dbo].[BLTYPECLASSILTYPE].[BLLICENSETYPECLASSID] = @BLLICENSETYPECLASSID)
END