CREATE PROCEDURE [dbo].[USP_BLTYPECLASSILCLASS_INSERT]
(
	@BLTYPECLASSILCLASSID CHAR(36),
	@BLTYPECLASSILTYPEID CHAR(36),
	@ILLICENSECLASSIFICATIONID CHAR(36)
)
AS
BEGIN
INSERT INTO [dbo].[BLTYPECLASSILCLASS](
	[BLTYPECLASSILCLASSID],
	[BLTYPECLASSILTYPEID],
	[ILLICENSECLASSIFICATIONID]
)

VALUES
(
	@BLTYPECLASSILCLASSID,
	@BLTYPECLASSILTYPEID,
	@ILLICENSECLASSIFICATIONID 
)
END