CREATE PROCEDURE [dbo].[USP_BLEXTBUSINESSTYPE_INSERT]
(
	@BLEXTBUSINESSTYPEID CHAR(36),
	@CODENUMBER NVARCHAR(10),
	@NAME NVARCHAR(250),
	@DESCRIPTION NVARCHAR(MAX),
	@BLEXTBUSINESSCATEGORYID CHAR(36),
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
INSERT INTO [dbo].[BLEXTBUSINESSTYPE](
	[BLEXTBUSINESSTYPEID],
	[CODENUMBER],
	[NAME],
	[DESCRIPTION],
	[BLEXTBUSINESSCATEGORYID],
	[LASTCHANGEDBY],
	[LASTCHANGEDON],
	[ROWVERSION]
)
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
VALUES
(
	@BLEXTBUSINESSTYPEID,
	@CODENUMBER,
	@NAME,
	@DESCRIPTION,
	@BLEXTBUSINESSCATEGORYID,
	@LASTCHANGEDBY,
	@LASTCHANGEDON,
	@ROWVERSION
)
SELECT * FROM @OUTPUTTABLE