CREATE PROCEDURE [dbo].[USP_BLTYPECLASSILCLASS_DELETE]  
(  
	@BLTYPECLASSILCLASSID CHAR(36)
)  
AS  
BEGIN  
	DELETE FROM [dbo].[BLTYPECLASSILCLASS]  
	WHERE  
	 [BLTYPECLASSILCLASSID] = @BLTYPECLASSILCLASSID 
END