CREATE PROCEDURE [dbo].[USP_BLEXTSTATUS_DELETE]
(
	@BLEXTSTATUSID CHAR(36),
	@ROWVERSION INT
)
AS
DELETE FROM [dbo].[BLEXTSTATUS]
WHERE
	[BLEXTSTATUSID] = @BLEXTSTATUSID AND 
	[ROWVERSION]= @ROWVERSION