CREATE PROCEDURE [dbo].[USP_BLLICENSEREQUIREDFIELD_INSERT]
(
	@BLREQUIREDCUSTOMFIELD CHAR(36),
	@BLLICENSETYPECLASSID CHAR(36),
	@GCUSTOMFIELD CHAR(36),
	@SORTORDER INT
)
AS

INSERT INTO [dbo].[BLLICENSEREQUIREDFIELD](
	[BLREQUIREDCUSTOMFIELD],
	[BLLICENSETYPECLASSID],
	[GCUSTOMFIELD],
	[SORTORDER]
)

VALUES
(
	@BLREQUIREDCUSTOMFIELD,
	@BLLICENSETYPECLASSID,
	@GCUSTOMFIELD,
	@SORTORDER
)