CREATE PROCEDURE [dbo].[USP_BLLICENSESTATUS_DELETE]
(
	@BLLICENSESTATUSID CHAR(36),
	@ROWVERSION INT
)
AS
DELETE FROM [dbo].[BLLICENSESTATUS]
WHERE
	[BLLICENSESTATUSID] = @BLLICENSESTATUSID AND 
	[ROWVERSION]= @ROWVERSION