CREATE PROCEDURE [dbo].[USP_BONDINTERESTRATE_INSERT]
(
	@BONDINTERESTRATEID CHAR(36),
	@CAPAYMENTMETHODID CHAR(36),
	@BONDINTERESTSCHEDULEID CHAR(36),
	@STARTDATE DATETIME,
	@ENDDATE DATETIME,
	@INTERESTRATE DECIMAL(20,4),
	@ACTIVE BIT
)
AS

INSERT INTO [dbo].[BONDINTERESTRATE](
	[BONDINTERESTRATEID],
	[CAPAYMENTMETHODID],
	[BONDINTERESTSCHEDULEID],
	[STARTDATE],
	[ENDDATE],
	[INTERESTRATE],
	[ACTIVE]
)

VALUES
(
	@BONDINTERESTRATEID,
	@CAPAYMENTMETHODID,
	@BONDINTERESTSCHEDULEID,
	@STARTDATE,
	@ENDDATE,
	@INTERESTRATE,
	@ACTIVE
)