CREATE PROCEDURE [dbo].[USP_BLCONTACTTYPEREF_UPDATE]
(
	@CONTACTTYPEEXTID CHAR(36),
	@BLCONTACTTYPEID CHAR(36),
	@CONTACTTYPEGROUP INT,
	@ISREQUIRED BIT,
	@OBJCLASSID CHAR(36),
	@OBJTYPEID CHAR(36),
	@OBJMODULEID INT,
	@ISDEFAULTONLINECONTACTTYPE BIT
)
AS

UPDATE [dbo].[BLCONTACTTYPEREF] SET
	[BLCONTACTTYPEID] = @BLCONTACTTYPEID,
	[CONTACTTYPEGROUP] = @CONTACTTYPEGROUP,
	[ISREQUIRED] = @ISREQUIRED,
	[OBJCLASSID] = @OBJCLASSID,
	[OBJTYPEID] = @OBJTYPEID,
	[OBJMODULEID] = @OBJMODULEID,
	[ISDEFAULTONLINECONTACTTYPE] = @ISDEFAULTONLINECONTACTTYPE

WHERE
	[CONTACTTYPEEXTID] = @CONTACTTYPEEXTID