CREATE PROCEDURE [dbo].[USP_BONDINTADJREASON_UPDATE]
(
	@BONDINTADJREASONID CHAR(36),
	@NAME NVARCHAR(50),
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
UPDATE [dbo].[BONDINTADJREASON] SET
	[NAME] = @NAME,
	[LASTCHANGEDBY] = @LASTCHANGEDBY,
	[LASTCHANGEDON] = @LASTCHANGEDON,
	[ROWVERSION] = @ROWVERSION + 1
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE
	[BONDINTADJREASONID] = @BONDINTADJREASONID AND 
	[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE