CREATE PROCEDURE [dbo].[USP_BLEXTCOMPANYTYPE_INSERT]
(
	@BLEXTCOMPANYTYPEID CHAR(36),
	@NAME NVARCHAR(50),
	@DESCRIPTION NVARCHAR(MAX),
	@BLEINFORMATID INT,
	@CUSTOMFIELDLAYOUTID CHAR(36),
	@CANAPPLYONLINE BIT,
	@DEFAULTWEBAPPLYSTATUSID CHAR(36),
	@ONLINECUSTOMFIELDLAYOUTID CHAR(36),
	@MANAGEBUSINESSTYPECODES BIT,
	@REQUIREBUSINESSTYPECODES BIT,
	@CAPADDRESSREQUIRED BIT,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT,
	@BLEXTCOMPANYTYPEMODULEID INT,
	@CAFEETEMPLATEID CHAR(36)
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
INSERT INTO [dbo].[BLEXTCOMPANYTYPE](
	[BLEXTCOMPANYTYPEID],
	[NAME],
	[DESCRIPTION],
	[BLEINFORMATID],
	[CUSTOMFIELDLAYOUTID],
	[CANAPPLYONLINE],
	[DEFAULTWEBAPPLYSTATUSID],
	[ONLINECUSTOMFIELDLAYOUTID],
	[MANAGEBUSINESSTYPECODES],
	[REQUIREBUSINESSTYPECODES],
	[CAPADDRESSREQUIRED],
	[LASTCHANGEDBY],
	[LASTCHANGEDON],
	[ROWVERSION],
	[BLEXTCOMPANYTYPEMODULEID],
	[CAFEETEMPLATEID]
)
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
VALUES
(
	@BLEXTCOMPANYTYPEID,
	@NAME,
	@DESCRIPTION,
	@BLEINFORMATID,
	@CUSTOMFIELDLAYOUTID,
	@CANAPPLYONLINE,
	@DEFAULTWEBAPPLYSTATUSID,
	@ONLINECUSTOMFIELDLAYOUTID,
	@MANAGEBUSINESSTYPECODES,
	@REQUIREBUSINESSTYPECODES,
	@CAPADDRESSREQUIRED,
	@LASTCHANGEDBY,
	@LASTCHANGEDON,
	@ROWVERSION,
	@BLEXTCOMPANYTYPEMODULEID,
	@CAFEETEMPLATEID
)
SELECT * FROM @OUTPUTTABLE