CREATE PROCEDURE [dbo].[USP_BLCONTACTTYPE_UPDATE]
(
	@BLCONTACTTYPEID CHAR(36),
	@NAME NVARCHAR(50),
	@DESCRIPTION NVARCHAR(MAX),
	@BLCONTACTTYPESYSTEMID CHAR(36),
	@REQUIREDVALIDLIC BIT,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
UPDATE [dbo].[BLCONTACTTYPE] SET
	[BLCONTACTTYPESYSTEMID] = @BLCONTACTTYPESYSTEMID,
	[NAME] = @NAME,
	[DESCRIPTION] = @DESCRIPTION,
	[REQUIREDVALIDLIC] = @REQUIREDVALIDLIC,
	[LASTCHANGEDBY] = @LASTCHANGEDBY,
	[LASTCHANGEDON] = @LASTCHANGEDON,
	[ROWVERSION] = @ROWVERSION + 1
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE
	[BLCONTACTTYPEID] = @BLCONTACTTYPEID AND 
	[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE