CREATE PROCEDURE [dbo].[USP_BLLICENSESTATUS_INSERT]
(
	@BLLICENSESTATUSID CHAR(36),
	@NAME NVARCHAR(50),
	@DESCRIPTION NVARCHAR(MAX),
	@BLLICENSESTATUSSYSTEMID INT,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
INSERT INTO [dbo].[BLLICENSESTATUS](
	[BLLICENSESTATUSID],
	[NAME],
	[DESCRIPTION],
	[BLLICENSESTATUSSYSTEMID],
	[LASTCHANGEDBY],
	[LASTCHANGEDON],
	[ROWVERSION]
)
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
VALUES
(
	@BLLICENSESTATUSID,
	@NAME,
	@DESCRIPTION,
	@BLLICENSESTATUSSYSTEMID,
	@LASTCHANGEDBY,
	@LASTCHANGEDON,
	@ROWVERSION
)
SELECT * FROM @OUTPUTTABLE