CREATE PROCEDURE [bulkupdate].[USP_GET_BULK_UPDATE_SERVICES]
(
	@SEARCH			AS NVARCHAR(MAX)	=	'',
	@PAGE_NUMBER	AS INT				=	1,
	@PAGE_SIZE		AS INT				=	10,
	@IS_ASCENDING	AS BIT				=	1,
	@COMPLETE		AS BIT
)
AS
BEGIN

WITH RAW_DATA AS 
(
SELECT	[dbo].[BUSERVICE].[BUSERVICEID], 
		[dbo].[BUSERVICE].[BATCHNUMBER], 
		[dbo].[BUENTITY].[NAME] AS ENTITY, 
		[dbo].[BUSERVICESTATUS].[NAME] AS SERVICESTATUS, 
		BatchRecords.TOTALCOUNT, 
		BatchRecords.PROCESSEDCOUNT, 
		[dbo].[USERS].[FNAME], 
		[dbo].[USERS].[LNAME], 
		[dbo].[BUSERVICE].[CREATEDATE],
		ROW_NUMBER() OVER(ORDER BY [dbo].[BUSERVICE].[CREATEDATE]) AS RowNumber,
		COUNT(1) OVER() AS TotalRows
		FROM [dbo].[BUSERVICE]
JOIN [bulkupdate].[UDF_GET_BURECORD_COUNTS]() BatchRecords ON [dbo].[BUSERVICE].[BUSERVICEID] = BatchRecords.BUSERVICEID
JOIN [dbo].[USERS] ON [dbo].[BUSERVICE].[CREATEDBY] = [dbo].[USERS].[SUSERGUID]
JOIN [dbo].[BUENTITY] ON [dbo].[BUSERVICE].[ENTITY] = [dbo].[BUENTITY].[BUENTITYID]
JOIN [dbo].[BUSERVICESTATUS] ON [dbo].[BUSERVICE].[SERVICESTATUS] = [dbo].[BUSERVICESTATUS].[BUSERVICESTATUSID]
WHERE 
((@COMPLETE IS NULL) OR (@COMPLETE = 1 AND [dbo].[BUSERVICE].[SERVICESTATUS] = 5) OR (@COMPLETE = 0 AND [dbo].[BUSERVICE].[SERVICESTATUS] <> 5)) AND
((@SEARCH IS NULL OR ([dbo].[BUENTITY].[NAME] LIKE '%' + @SEARCH + '%')) OR
(@SEARCH IS NULL OR ([dbo].[BUSERVICESTATUS].[NAME] LIKE '%' + @SEARCH + '%')) OR
(@SEARCH IS NULL OR (([dbo].[USERS].[FNAME] LIKE '%' + @SEARCH + '%') OR ([dbo].[USERS].[LNAME] LIKE '%' + @SEARCH + '%') OR (([dbo].[USERS].[FNAME] + ' ' + [dbo].[USERS].[LNAME]) LIKE '%' + @SEARCH + '%'))))
)
SELECT		* 
FROM		RAW_DATA
WHERE		RowNumber > @PAGE_SIZE * (@PAGE_NUMBER - 1) 
			AND RowNumber <= @PAGE_SIZE * @PAGE_NUMBER
ORDER BY	RowNumber

END