CREATE TABLE [dbo].[TASKPRIORITY] (
    [TASKPRIORITYID]   INT           NOT NULL,
    [TASKPRIORITYNAME] NVARCHAR (20) NOT NULL,
    CONSTRAINT [PK_TaskPriority] PRIMARY KEY CLUSTERED ([TASKPRIORITYID] ASC) WITH (FILLFACTOR = 90)
);

