CREATE TABLE [dbo].[TASK] (
    [TASKID]          CHAR (36)      NOT NULL,
    [SUBJECT]         NVARCHAR (200) NOT NULL,
    [TASKTEXT]        NVARCHAR (MAX) NOT NULL,
    [STARTDATE]       DATETIME       NULL,
    [DUEDATE]         DATETIME       NULL,
    [TASKSTATUSID]    INT            NOT NULL,
    [TASKPRIORITYID]  INT            NOT NULL,
    [PERCENTCOMPLETE] INT            NOT NULL,
    [CREATEDBYID]     CHAR (36)      NOT NULL,
    [CREATEDON]       DATETIME       NOT NULL,
    [FORMID]          CHAR (36)      NULL,
    [UNIQUERECORDID]  CHAR (36)      NULL,
    [SHOWONCALENDAR]  BIT            NOT NULL,
    [TASKTYPEID]      CHAR (36)      DEFAULT ('61F216A1-AF8B-4E8A-9452-7C4836408788') NOT NULL,
    [COMPLETEDDATE]   DATETIME       NULL,
    [LASTCHANGEDBY]   CHAR (36)      NULL,
    [LASTCHANGEDON]   DATETIME       CONSTRAINT [DF_TASK_LastChangedOn] DEFAULT (getutcdate()) NOT NULL,
    [ROWVERSION]      INT            CONSTRAINT [DF_TASK_RowVersion] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_Task] PRIMARY KEY CLUSTERED ([TASKID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_Task_Forms] FOREIGN KEY ([FORMID]) REFERENCES [dbo].[FORMS] ([SFORMSGUID]),
    CONSTRAINT [FK_Task_TaskPriority] FOREIGN KEY ([TASKPRIORITYID]) REFERENCES [dbo].[TASKPRIORITY] ([TASKPRIORITYID]),
    CONSTRAINT [FK_Task_TaskStatus] FOREIGN KEY ([TASKSTATUSID]) REFERENCES [dbo].[TASKSTATUS] ([TASKSTATUSID]),
    CONSTRAINT [FK_Task_TaskType] FOREIGN KEY ([TASKTYPEID]) REFERENCES [dbo].[TASKTYPE] ([TASKTYPEID]),
    CONSTRAINT [FK_Task_Users] FOREIGN KEY ([CREATEDBYID]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);


GO
CREATE NONCLUSTERED INDEX [IX_TASK_DUEDATE_MYTASK]
    ON [dbo].[TASK]([DUEDATE] ASC, [TASKSTATUSID] ASC, [TASKID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IX_TASK_COMPDATE_MYTASK]
    ON [dbo].[TASK]([COMPLETEDDATE] ASC, [TASKSTATUSID] ASC, [TASKID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [NCIDX_TASK_TASKSTATUSID_includes]
    ON [dbo].[TASK]([TASKSTATUSID] ASC)
    INCLUDE([TASKID]) WITH (FILLFACTOR = 90, PAD_INDEX = ON);


GO
CREATE NONCLUSTERED INDEX [IX_TASK_CREATEDBYID_TASK_STATUS]
    ON [dbo].[TASK]([CREATEDBYID] ASC)
    INCLUDE([TASKID], [TASKSTATUSID]);


GO
CREATE NONCLUSTERED INDEX [IX_TASK_DATE]
    ON [dbo].[TASK]([TASKSTATUSID] ASC, [SHOWONCALENDAR] ASC, [STARTDATE] ASC, [DUEDATE] ASC, [CREATEDBYID] ASC)
    INCLUDE([TASKID]);


GO
CREATE NONCLUSTERED INDEX [TASK_UNIQUERECORDID]
    ON [dbo].[TASK]([UNIQUERECORDID] ASC);

