CREATE TABLE [dbo].[TCMPOSTPROCESS] (
    [TCMPOSTPROCESSID] INT            IDENTITY (1, 1) NOT NULL,
    [CLASSNAME]        NVARCHAR (250) NOT NULL,
    [CREATEDATE]       DATETIME       NOT NULL,
    [USERID]           CHAR (36)      NOT NULL,
    [PROCESSEDDATE]    DATETIME       NULL,
    [ENTITYID]         CHAR (36)      NOT NULL,
    [RESULTLOG]        VARCHAR (MAX)  NULL,
    CONSTRAINT [PK_TCMPOSTPROCESS] PRIMARY KEY CLUSTERED ([TCMPOSTPROCESSID] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [FK_TCMPOSTPROCESS_USER] FOREIGN KEY ([USERID]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);

