CREATE TABLE [dbo].[TEMPLATEREF] (
    [TEMPLATEXREF]  CHAR (36) NOT NULL,
    [TEMPLATEDOCID] CHAR (36) NOT NULL,
    [SROLEGUID]     CHAR (36) NOT NULL,
    CONSTRAINT [PK_TemplateXref] PRIMARY KEY CLUSTERED ([TEMPLATEXREF] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_TemplateRef_Roles] FOREIGN KEY ([SROLEGUID]) REFERENCES [dbo].[ROLES] ([SROLEGUID]),
    CONSTRAINT [FK_TemplateRef_Templates] FOREIGN KEY ([TEMPLATEDOCID]) REFERENCES [dbo].[TEMPLATEDOC] ([TEMPLATEDOCID])
);

