CREATE TABLE [dbo].[TIMETRACKINGMODULE] (
    [MODULEID] INT            NOT NULL,
    [NAME]     NVARCHAR (100) NOT NULL,
    [FORMID]   CHAR (36)      NULL,
    CONSTRAINT [PK_TimeTrackingModule] PRIMARY KEY CLUSTERED ([MODULEID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_TimeTrackingModule_Forms] FOREIGN KEY ([FORMID]) REFERENCES [dbo].[FORMS] ([SFORMSGUID])
);

