CREATE TABLE [dbo].[TXREMITTANCEACCOUNTPARCEL] (
    [TXREMITTANCEACCOUNTPARCELID] CHAR (36) NOT NULL,
    [TXREMITTANCEACCOUNTID]       CHAR (36) NOT NULL,
    [PARCELID]                    CHAR (36) NOT NULL,
    [MAIN]                        BIT       NOT NULL,
    PRIMARY KEY CLUSTERED ([TXREMITTANCEACCOUNTPARCELID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_TXPARCELPARCELID] FOREIGN KEY ([PARCELID]) REFERENCES [dbo].[PARCEL] ([PARCELID]),
    CONSTRAINT [FK_TXPARCELTXREMITTANCEACCOUNTID] FOREIGN KEY ([TXREMITTANCEACCOUNTID]) REFERENCES [dbo].[TXREMITTANCEACCOUNT] ([TXREMITTANCEACCOUNTID])
);

