CREATE TABLE [dbo].[TYLERCASHIERINGTENDERTYPEUPDATEQUEUE] (
    [TYLERCASHIERINGTENDERTYPEUPDATEQUEUEID] BIGINT    IDENTITY (1, 1) NOT NULL,
    [PAYMENTMETHODID]                        CHAR (36) NULL,
    [TENDERTYPEID]                           INT       NULL,
    [PROCESSEDDATE]                          DATETIME  NULL,
    [SUCCESS]                                BIT       NULL,
    [SENTTOBUS]                              BIT       NULL,
    CONSTRAINT [PK_TYLERCASHIERINGTENDERTYPEUPDATEQUEUE] PRIMARY KEY CLUSTERED ([TYLERCASHIERINGTENDERTYPEUPDATEQUEUEID] ASC),
    CONSTRAINT [FK_TYLERCASHIERINGTENDERTYPEUPDATEQUEUE_CAPAYMENTMETHOD] FOREIGN KEY ([PAYMENTMETHODID]) REFERENCES [dbo].[CAPAYMENTMETHOD] ([CAPAYMENTMETHODID])
);


GO
CREATE NONCLUSTERED INDEX [TYLERCASHIERINGTENDERTYPEUPDATEQUEUE_PROCESSEDDATE]
    ON [dbo].[TYLERCASHIERINGTENDERTYPEUPDATEQUEUE]([PROCESSEDDATE] ASC);

