CREATE TABLE [dbo].[TYLERCASHIERINGUSERUPDATEQUEUE] (
    [TYLERCASHIERINGUSERUPDATEQUEUEID] BIGINT        IDENTITY (1, 1) NOT NULL,
    [USERGUID]                         CHAR (36)     NOT NULL,
    [USEREMAIL]                        NVARCHAR (80) NOT NULL,
    [PROCESSEDDATE]                    DATETIME      NULL,
    [SUCCESS]                          BIT           NULL,
    [SENTTOBUS]                        BIT           NULL,
    CONSTRAINT [PK_TYLERCASHIERINGUSERSQUEUE] PRIMARY KEY CLUSTERED ([TYLERCASHIERINGUSERUPDATEQUEUEID] ASC),
    CONSTRAINT [FK_TYLERCASHIERINGUSERSQUEUE_USERS] FOREIGN KEY ([USERGUID]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);


GO
CREATE NONCLUSTERED INDEX [TYLERCASHIERINGUSERSQUEUE_PROCESSEDDATE]
    ON [dbo].[TYLERCASHIERINGUSERUPDATEQUEUE]([PROCESSEDDATE] ASC);

