CREATE PROCEDURE [managebusiness].[USP_HISTORYBUSINESS_RECENT]
(@USER_ID AS CHAR(36), @BLEXTCOMPANYTYPEMODULEID INT)
AS
BEGIN
    DECLARE @RECENTBUSINESSLIST AS RecordIDs;

    INSERT INTO @RECENTBUSINESSLIST
    (
        RECORDID
    )
  SELECT TOP 15
           [RECENTHISTORYBUSINESS].[BLGLOBALENTITYEXTENSIONID]
    FROM [dbo].[RECENTHISTORYBUSINESS]
	INNER JOIN [dbo].[BLGLOBALENTITYEXTENSION] 
		ON [dbo].[RECENTHISTORYBUSINESS].[BLGLOBALENTITYEXTENSIONID] = [dbo].[BLGLOBALENTITYEXTENSION].[BLGLOBALENTITYEXTENSIONID]
	INNER JOIN [dbo].[BLEXTCOMPANYTYPE] 
		ON [dbo].[BLGLOBALENTITYEXTENSION].[BLEXTCOMPANYTYPEID] = [dbo].[BLEXTCOMPANYTYPE].[BLEXTCOMPANYTYPEID]		
    WHERE [RECENTHISTORYBUSINESS].[USERID] = @USER_ID AND [dbo].[BLEXTCOMPANYTYPE].[BLEXTCOMPANYTYPEMODULEID] = @BLEXTCOMPANYTYPEMODULEID
    ORDER BY [RECENTHISTORYBUSINESS].[LOGGEDDATETIME] DESC;

    EXEC [managebusiness].[USP_BLGLOBALENTITYEXTENSION_GETBYIDS] @RECENTBUSINESSLIST, @USER_ID;
	EXEC [managebusiness].[USP_BLGLOBALENTITYEXTENSIONADDRESS_GETALL] @RECENTBUSINESSLIST
END;