CREATE PROCEDURE [managebusiness].[USP_BLGLOBALENTITYEXTENSIONFIREOCCUPANTXREF_LINKED_GETBYFIREOCCUPANTIDS]
	@FIREOCCUPANTIDS [dbo].[IntegerIds] READONLY
AS
BEGIN
SET NOCOUNT ON;
SELECT DISTINCT
	[FIREOCCUPANTS].[ID] FIREOCCUPANTID,
	CASE WHEN [BLGLOBALENTITYEXTENSIONFIREOCCUPANTXREF].[BLGLOBALENTITYEXTENSIONID] IS NULL THEN CAST(0 AS BIT) ELSE CAST(1 AS BIT) END ISLINKED
FROM @FIREOCCUPANTIDS FIREOCCUPANTS
LEFT OUTER JOIN [BLGLOBALENTITYEXTENSIONFIREOCCUPANTXREF] ON [BLGLOBALENTITYEXTENSIONFIREOCCUPANTXREF].[FIREOCCUPANTID] = [FIREOCCUPANTS].[ID]
END