CREATE  PROCEDURE [managebusiness].[USP_TAXREMITTANCEACCOUNT_GETBYGLOBALENTITYID] 
@BLGLOBALENTITYEXTENSIONID CHAR(36) ,
@CURRENTDATE DATETIME    
AS    
BEGIN 
SET NOCOUNT ON;
 SELECT   
		 [TXREMITTANCEACCOUNT].[TXREMITTANCEACCOUNTID],
		 [TXREMITTANCEACCOUNT].[OPENDATE],
		 [TXREMITSTATUS].[NAME],
		 [TXREMITTANCEACCOUNT].[REMITTANCEACCOUNTNUMBER],
		 [TXREMITTANCETYPE].[NAME] AS TXREMITTANCETYPE
 FROM  [dbo].[TXREMITTANCEACCOUNT]
		INNER JOIN [dbo].[TXREMITTANCETYPE] ON 
				[TXREMITTANCETYPE].[TXREMITTANCETYPEID] = [TXREMITTANCEACCOUNT].[TXREMITTANCETYPEID]
		INNER JOIN [dbo].[TXREMITSTATUS] ON 
				[TXREMITSTATUS].[TXREMITSTATUSID] = [TXREMITTANCEACCOUNT].[TXREMITTANCESTATUSID]
 WHERE [TXREMITTANCEACCOUNT].[BLGLOBALENTITYEXTENSIONID] = @BLGLOBALENTITYEXTENSIONID
		AND ([TXREMITTANCEACCOUNT].[CLOSEDATE] IS NULL 
		OR [TXREMITTANCEACCOUNT].[CLOSEDATE] > @CURRENTDATE)
		AND [TXREMITSTATUS].[TXREMITSTATUSSYSTEMID] IN (1,3,4) -- Active,Hold,Other
END