CREATE  PROCEDURE [managebusiness].[USP_BLLICENSEFEE_GETBY_GLOBALENTITYEXTENSIONID]
@BLGLOBALENTITYEXTENSIONID CHAR(36),
@CURRENTDATE DATETIME
AS
BEGIN
SET NOCOUNT ON;
SELECT
[BLLICENSEFEE].[BLLICENSEFEEID],
[BLLICENSEFEE].[BLLICENSEID],
[BLLICENSEFEE].[CACOMPUTEDFEEID],
[BLLICENSEFEE].[CREATEDON]
 FROM  [dbo].[BLLICENSEFEE]
      INNER JOIN [dbo].[BLLICENSE]  ON [BLLICENSE].[BLLICENSEID] = [BLLICENSEFEE].[BLLICENSEID]
      INNER JOIN [dbo].[CACOMPUTEDFEE]  ON [CACOMPUTEDFEE].[CACOMPUTEDFEEID] = [BLLICENSEFEE].[CACOMPUTEDFEEID]
      INNER JOIN [dbo].[BLLICENSESTATUS] ON [BLLICENSE].[BLLICENSESTATUSID] = [BLLICENSESTATUS].[BLLICENSESTATUSID] AND [BLLICENSESTATUS].[BLLICENSESTATUSSYSTEMID] IN (1,2,4) --Issued, Expired, Other
 WHERE
      [BLLICENSE].[BLGLOBALENTITYEXTENSIONID] = @BLGLOBALENTITYEXTENSIONID
      AND [BLLICENSE].[LASTRENEWALDATE] IS NULL
      AND ([BLLICENSE].[EXPIRATIONDATE] IS NULL OR [BLLICENSE].[EXPIRATIONDATE] > @CURRENTDATE)
      AND ISNULL((SELECT COUNT(1) FROM BLLICENSE CHILD WHERE CHILD.BLLICENSEPARENTID IS NOT NULL AND CHILD.BLLICENSEPARENTID = BLLICENSE.BLLICENSEID), 0) = 0
      AND [CACOMPUTEDFEE].[CASTATUSID] NOT IN (10,5) -- FeeStatuses.Deleted,FeeStatuses.Void
      ORDER BY [BLLICENSEFEE].[BLLICENSEID]
END