CREATE PROCEDURE[managebusiness].[USP_BUSINESSCONTACTTYPES_GETBYID]
(
	@GLOBALENTITYEXTENSIONID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;

SELECT	
[BLCONTACTTYPE].[NAME],
[BLCONTACTTYPE].[BLCONTACTTYPEID]
FROM [dbo].[BLCONTACTTYPE]
		INNER JOIN [dbo].[BLGLOBALENTITYEXTENSIONCONTACT]  ON [BLGLOBALENTITYEXTENSIONCONTACT].[BLCONTACTTYPEID]=[BLCONTACTTYPE].[BLCONTACTTYPEID] 
WHERE 
	[BLGLOBALENTITYEXTENSIONCONTACT].[BLGLOBALENTITYEXTENSIONID] = @GLOBALENTITYEXTENSIONID
END