CREATE PROCEDURE [managebusiness].[USP_HOLDSETUP_GETBYID]
(@GLOBALENTITYEXTENSIONID CHAR(36))
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
	 [HOLDTYPESETUPS].[HOLDSETUPID],
           [HOLDTYPESETUPS].[NAME],
           [HOLDTYPESETUPS].[HOLDTYPEID],
           [HOLDTYPESETUPS].[ALLOWHOLDOVERRIDES],
           [HOLDTYPESETUPS].[ACTIVE],
           [HOLDTYPESETUPS].[BNEWLICENSE],
           [HOLDTYPESETUPS].[BUSINESSINSP],
           [HOLDTYPESETUPS].[BRENEWLICENSE],
           [HOLDTYPESETUPS].[BLWF],
           [HOLDTYPESETUPS].[BLPULLPERMIT],
           [HOLDTYPESETUPS].[BLPULLPLAN],
           [HOLDTYPESETUPS].[BLRENEW]
    FROM [dbo].[HOLDTYPESETUPS]
        INNER JOIN [dbo].[BLEXTHOLD]
            ON [BLEXTHOLD].[HOLDSETUPID] = [HOLDTYPESETUPS].[HOLDSETUPID]
    WHERE [BLEXTHOLD].[BLGLOBALENTITYEXTENSIONID] = @GLOBALENTITYEXTENSIONID;
END;