CREATE PROCEDURE [managebusiness].[USP_TAGGEDCMCODECASEFEE_GETBYGLOBALENTITYID]
(
   @BLGLOBALENTITYEXTENSIONID CHAR(36)
)
AS
BEGIN
    SET NOCOUNT ON;

    ;WITH RESULT AS
    (
        SELECT
            [dbo].[CMCODECASE].[CMCODECASEID],
            [dbo].[CMCODECASE].[CASENUMBER],
            ISNULL(SUM(CACOMPUTEDFEE.COMPUTEDAMOUNT),0) FEETOTAL,
            ISNULL(SUM(CACOMPUTEDFEE.AMOUNTPAIDTODATE),0) AMOUNTPAIDTOTAL,
            (ISNULL(SUM(CACOMPUTEDFEE.COMPUTEDAMOUNT),0) - ISNULL(SUM(CACOMPUTEDFEE.AMOUNTPAIDTODATE),0)) FEEDUE
        FROM [dbo].[CMCODECASEFEE]
        JOIN [dbo].[CMCODECASE] ON [dbo].[CMCODECASE].[CMCODECASEID] = [dbo].[CMCODECASEFEE].[CMCODECASEID]
        JOIN [dbo].[BLGLOBALENTITYEXTENSIONCODECASEXREF] ON [dbo].[BLGLOBALENTITYEXTENSIONCODECASEXREF].[CMCODECASEID] = [dbo].[CMCODECASEFEE].[CMCODECASEID]
        INNER JOIN [dbo].[CACOMPUTEDFEE]  ON [dbo].[CMCODECASEFEE].[CACOMPUTEDFEEID] = [CACOMPUTEDFEE].[CACOMPUTEDFEEID]
            AND [CACOMPUTEDFEE].[CASTATUSID] NOT IN (10,5) -- DELETED & VOID
        WHERE [dbo].[BLGLOBALENTITYEXTENSIONCODECASEXREF].[BLGLOBALENTITYEXTENSIONID] = @BLGLOBALENTITYEXTENSIONID
        GROUP BY [dbo].[CMCODECASE].[CMCODECASEID], [dbo].[CMCODECASE].[CASENUMBER]
    )
    SELECT * FROM RESULT WHERE FEEDUE>0
END;