CREATE PROCEDURE [managebusiness].[USP_BLGLOBALENTITYEXTENSIONADDRESS_GETALL]
(@RECENTBUSINESSLIST RecordIDs READONLY)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT
		[MAILINGADDRESS].[MAILINGADDRESSID],
		   [BLGLOBALENTITYEXTENSIONADDRESS].[BLGLOBALENTITYEXTENSIONID],
           [MAILINGADDRESS].[ADDRESSLINE1],
           [MAILINGADDRESS].[ADDRESSLINE2],
           [MAILINGADDRESS].[ADDRESSLINE3],
           [MAILINGADDRESS].[ADDRESSTYPE],
           [MAILINGADDRESS].[ATTN],
           [MAILINGADDRESS].[CITY],
           [MAILINGADDRESS].[COMPSITE],
		   [MAILINGADDRESS].[COUNTRY],
           [MAILINGADDRESSCOUNTRYTYPE].[MAILINGADDRESSCOUNTRYTYPEID],
		   [MAILINGADDRESSCOUNTRYTYPE].[MAILINGADDRESSCOUNTRYTYPENAME],	
		   [BLGLOBALENTITYEXTENSIONADDRESS].[MAIN],
           [MAILINGADDRESS].[POBOX],
           [MAILINGADDRESS].[POSTALCODE],
           [MAILINGADDRESS].[POSTDIRECTION],
           [MAILINGADDRESS].[PREDIRECTION],
           [MAILINGADDRESS].[PROVINCE],
           [MAILINGADDRESS].[RURALROUTE],
           [MAILINGADDRESS].[STATE],
           [MAILINGADDRESS].[STATION],
           [MAILINGADDRESS].[STREETTYPE],
           [MAILINGADDRESS].[UNITORSUITE],
           [MAILINGADDRESS].[ADDRESSID]
    FROM [dbo].[BLGLOBALENTITYEXTENSIONADDRESS]
        INNER JOIN [dbo].[MAILINGADDRESS] ON [MAILINGADDRESS].[MAILINGADDRESSID] = [BLGLOBALENTITYEXTENSIONADDRESS].[MAILINGADDRESSID]
		INNER JOIN MAILINGADDRESSCOUNTRYTYPE ON MAILINGADDRESS.COUNTRYTYPE = MAILINGADDRESSCOUNTRYTYPE.MAILINGADDRESSCOUNTRYTYPEID
        INNER JOIN @RECENTBUSINESSLIST RECENTBUSINESSLIST ON [BLGLOBALENTITYEXTENSIONADDRESS].[BLGLOBALENTITYEXTENSIONID] = RECENTBUSINESSLIST.RECORDID
    WHERE [BLGLOBALENTITYEXTENSIONADDRESS].[MAIN] = 1;
END;