CREATE PROCEDURE [map].[USP_MAPCONFIGURATION_GET]
	@USERID CHAR(36)
AS
BEGIN
	SET NOCOUNT ON;	
	SELECT 
		[dbo].[GISMAP].SMAPURL,
		[dbo].[USERS].MAINMAPSORTORDER,
		[dbo].[GISMAP].SADDRESSSEARCHURL,
		[dbo].[GISMAP].SPARCELLAYER,
		[dbo].[GISMAP].SPARCELOWNER,
		[dbo].[GISMAP].SGISFEATUREMAPURL,
		[dbo].[GISMAP].SINTERSECTIONLOCATORURL,
		[dbo].[GISMAP].SPINFIELD,
		[dbo].[GISMAP].SADDRESSSEARCHFIELD,
		[dbo].[GISMAP].SGEOMETRYSERVER,
		[dbo].[GISMAP].IDEFAULTLAYERNUMBER,
		[dbo].[GISMAP].SEXTENT,
		[dbo].[GISMAP].SGISFEATURESERVICEURL,
		[dbo].[GISMAP].SFEATURESERVICELIST,
		cast(isnull((select BITVALUE from SETTINGS WITH (NOLOCK) where SETTINGS.NAME='EnableUserNamePasswordInGISMap'), 0) as bit) ENABLEUSERNAMEPASSWORDINGISMAP,
		cast(isnull((select BITVALUE from SETTINGS WITH (NOLOCK) where SETTINGS.NAME='UseArcGISRESTEndPoint'), 0) as bit) USEARCGISRESTENDPOINT,
		cast(isnull((select BITVALUE from SETTINGS WITH (NOLOCK) where SETTINGS.NAME='IsOracleGISDatabase'), 0) as bit) ISORACLEGISDATABASE,
		isnull((select INTVALUE from SETTINGS WITH (NOLOCK) where SETTINGS.NAME='Esri_Server_Type'), 0) ESRISERVERTYPE,
		(select INTVALUE from SETTINGS WITH (NOLOCK) where SETTINGS.NAME='OnlineMapTokenValidity') ONLINEMAPTOKENVALIDITY
		FROM [dbo].[GISMAP] WITH (NOLOCK)
		INNER JOIN [dbo].[USERS] WITH (NOLOCK) ON [dbo].[USERS].GMAPID = [dbo].[GISMAP].GMAPID
		WHERE [dbo].[USERS].[SUSERGUID] = @USERID

	SELECT
		[dbo].[GISFEATURECLASS].GISFEATURECLASSID,
		[dbo].[GISFEATURECLASS].ATTRIBUTEFIELD,
		[dbo].[GISFEATURECLASS].LAYERNUMBER,
		[dbo].[GISFEATURECLASS].LAYERNAME,
		[dbo].[GISFEATURECLASS].ALIAS,
		[dbo].[GISFEATURECLASS].LAYERURL
		FROM [dbo].[GISFEATURECLASS] WITH (NOLOCK)

	SELECT
		[dbo].[GISFEATURECLASSSEARCHFIELD].GISFEATURECLASSSEARCHFIELDID,
		[dbo].[GISFEATURECLASSSEARCHFIELD].GISFEATURECLASSID,
		[dbo].[GISFEATURECLASSSEARCHFIELD].NAME,
		[dbo].[GISFEATURECLASSSEARCHFIELD].ALIAS
		FROM [dbo].[GISFEATURECLASSSEARCHFIELD] WITH (NOLOCK)

	SELECT 
		[dbo].[GISMAPLAYER].LAYERURL, 
		[dbo].[GISMAPLAYERXREF].SORTORDER, 
		[dbo].[GISMAPLAYERXREF].DEFAULTACTIVE
		FROM [dbo].[GISMAPLAYERXREF] WITH (NOLOCK)
		INNER JOIN [dbo].[GISMAPLAYER] WITH (NOLOCK) ON [dbo].[GISMAPLAYER].GISMAPLAYERID = [dbo].[GISMAPLAYERXREF].GISMAPLAYERID
	WHERE [dbo].[GISMAPLAYERXREF].SUSERGUID = @USERID
	ORDER BY [dbo].[GISMAPLAYERXREF].SORTORDER

    SELECT 
        [dbo].[GISMAPLAYER].[LAYERURL],
        [dbo].[GISMAPLAYER].[NAME],
        [dbo].[GISMAPLAYER].[LEGENDURL]
    FROM [dbo].[GISMAPLAYER]
    WHERE [dbo].[GISMAPLAYER].[IS_KOOP_ENDPOINT] = 1
END