CREATE TABLE [dbo].[HEARING] (
    [HEARINGID]       CHAR (36)       NOT NULL,
    [HEARINGTYPEID]   CHAR (36)       NOT NULL,
    [HEARINGSTATUSID] CHAR (36)       NOT NULL,
    [SUBJECT]         NVARCHAR (4000) NOT NULL,
    [LOCATION]        NVARCHAR (4000) NOT NULL,
    [COMMENTS]        NVARCHAR (MAX)  NULL,
    [STARTDATE]       DATETIME        NOT NULL,
    [ENDDATE]         DATETIME        NOT NULL,
    [LASTCHANGEDBY]   CHAR (36)       NULL,
    [LASTCHANGEDON]   DATETIME        CONSTRAINT [DF_HEARING_LastChangedOn] DEFAULT (getutcdate()) NOT NULL,
    [ROWVERSION]      INT             NOT NULL,
    [EXCHANGEITEMID]  VARCHAR (200)   NULL,
    [SHOWONCALENDAR]  BIT             DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_Hearing] PRIMARY KEY CLUSTERED ([HEARINGID] ASC),
    CONSTRAINT [FK_Hearing_HearingStatus] FOREIGN KEY ([HEARINGSTATUSID]) REFERENCES [dbo].[HEARINGSTATUS] ([HEARINGSTATUSID]),
    CONSTRAINT [FK_Hearing_HearingType] FOREIGN KEY ([HEARINGTYPEID]) REFERENCES [dbo].[HEARINGTYPE] ([HEARINGTYPEID])
);


GO
CREATE NONCLUSTERED INDEX [IX_HEARING_DATE]
    ON [dbo].[HEARING]([SHOWONCALENDAR] ASC, [STARTDATE] ASC, [ENDDATE] ASC)
    INCLUDE([HEARINGID]);


GO
CREATE NONCLUSTERED INDEX [IX_HEARING_ID_TYPE]
    ON [dbo].[HEARING]([HEARINGID] ASC, [HEARINGTYPEID] ASC)
    INCLUDE([STARTDATE], [COMMENTS]);


GO


CREATE TRIGGER [TG_HEARING_DELETE_ELASTIC_CODECASE] ON  [HEARING]
   AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [ELASTICSEARCHOBJECT]
    ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID() ,
		[C].[CMCODECASEID] ,
        'EnerGovBusiness.CodeEnforcement.CodeCase' ,
        [C].[ROWVERSION] ,
        GETDATE() ,
        NULL ,
        2 ,
        (SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Deleted]
	JOIN [HEARINGXREF] AS [H] WITH (NOLOCK) ON [H].[HEARINGID] = [Deleted].[HEARINGID]
	JOIN [CMCODEWFACTIONSTEP] AS [A] WITH (NOLOCK) ON [A].[CMCODEWFACTIONSTEPID] = [H].[OBJECTID]
	JOIN [CMCODEWFSTEP] AS [S] WITH (NOLOCK) ON [S].[CMCODEWFSTEPID] = [A].[CMCODEWFSTEPID]
	JOIN [CMCODECASE] AS [C] WITH (NOLOCK) ON [C].[CMCODECASEID] = [S].[CMCODECASEID]

END
GO


CREATE TRIGGER [TG_HEARING_DELETE_ELASTIC_BUSLIC] ON  [HEARING]
   AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [ELASTICSEARCHOBJECT]
    ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID() ,
		[B].[BLLICENSEID] ,
        'EnerGovBusiness.BusinessLicense.BusinessLicense' ,
        [B].[ROWVERSION] ,
        GETDATE() ,
        NULL ,
        2 ,
        (SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Deleted]
	JOIN [HEARINGXREF] AS [H] WITH (NOLOCK) ON [H].[HEARINGID] = [Deleted].[HEARINGID]
	JOIN [BLLICENSEWFACTIONSTEP] AS [A] WITH (NOLOCK) ON [A].[BLLICENSEWFACTIONSTEPID] = [H].[OBJECTID]
	JOIN [BLLICENSEWFSTEP] AS [S] WITH (NOLOCK) ON [S].[BLLICENSEWFSTEPID] = [A].[BLLICENSEWFSTEPID]
	JOIN [BLLICENSE] AS [B] WITH (NOLOCK) ON [B].[BLLICENSEID] = [S].[BLLICENSEID]

END
GO


CREATE TRIGGER [TG_HEARING_DELETE_ELASTIC_INDLIC] ON  [HEARING]
   AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [ELASTICSEARCHOBJECT]
    ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID() ,
		[I].[ILLICENSEID] ,
        'EnerGovBusiness.IndividualLicense.License' ,
        [I].[ROWVERSION] ,
        GETDATE() ,
        NULL ,
        2 ,
        (SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Deleted]
	JOIN [HEARINGXREF] AS [H] WITH (NOLOCK) ON [H].[HEARINGID] = [Deleted].[HEARINGID]
	JOIN [ILLICENSEWFACTIONSTEP] AS [A] WITH (NOLOCK) ON [A].[ILLICENSEWFACTIONSTEPID] = [H].[OBJECTID]
	JOIN [ILLICENSEWFSTEP] AS [S] WITH (NOLOCK) ON [S].[ILLICENSEWFSTEPID] = [A].[ILLICENSEWFSTEPID]
	JOIN [ILLICENSE] AS [I] WITH (NOLOCK) ON [I].[ILLICENSEID] = [S].[ILLICENSEID]

END
GO


CREATE TRIGGER [TG_HEARING_DELETE_ELASTIC_PERMIT] ON  [HEARING]
   AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [ELASTICSEARCHOBJECT]
    ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID() ,
		[P].[PMPERMITID] ,
        'EnerGovBusiness.PermitManagement.Permit' ,
        [P].[ROWVERSION] ,
        GETDATE() ,
        NULL ,
        2 ,
        (SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Deleted]
	JOIN [HEARINGXREF] AS [H] WITH (NOLOCK) ON [H].[HEARINGID] = [Deleted].[HEARINGID]
	JOIN [PMPERMITWFACTIONSTEP] AS [A] WITH (NOLOCK) ON [A].[PMPERMITWFACTIONSTEPID] = [H].[OBJECTID]
	JOIN [PMPERMITWFSTEP] AS [S] WITH (NOLOCK) ON [S].[PMPERMITWFSTEPID] = [A].[PMPERMITWFSTEPID]
	JOIN [PMPERMIT] AS [P] WITH (NOLOCK) ON [P].[PMPERMITID] = [S].[PMPERMITID]

END
GO


CREATE TRIGGER [TG_HEARING_DELETE_ELASTIC_PLAN] ON  [HEARING]
   AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [ELASTICSEARCHOBJECT]
    ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID() ,
		[P].[PLPLANID] ,
        'EnerGovBusiness.PlanManagement.Plan' ,
        [P].[ROWVERSION] ,
        GETDATE() ,
        NULL ,
        2 ,
        (SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Deleted]
	JOIN [HEARINGXREF] AS [H] WITH (NOLOCK) ON [H].[HEARINGID] = [Deleted].[HEARINGID]
	JOIN [PLPLANWFACTIONSTEP] AS [A] WITH (NOLOCK) ON [A].[PLPLANWFACTIONSTEPID] = [H].[OBJECTID]
	JOIN [PLPLANWFSTEP] AS [S] WITH (NOLOCK) ON [S].[PLPLANWFSTEPID] = [A].[PLPLANWFSTEPID]
	JOIN [PLPLAN] AS [P] WITH (NOLOCK) ON [P].[PLPLANID] = [S].[PLPLANID]

END
GO


CREATE TRIGGER [TG_HEARING_INSERTUPDATE_ELASTIC_BUSLIC] ON  [HEARING]
   AFTER INSERT, UPDATE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [ELASTICSEARCHOBJECT]
    ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID() ,
		[B].[BLLICENSEID] ,
        'EnerGovBusiness.BusinessLicense.BusinessLicense' ,
        [B].[ROWVERSION] ,
        GETDATE() ,
        NULL ,
        2 ,
        (SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Inserted]
	JOIN [HEARINGXREF] AS [H] WITH (NOLOCK) ON [H].[HEARINGID] = [Inserted].[HEARINGID]
	JOIN [BLLICENSEWFACTIONSTEP] AS [A] WITH (NOLOCK) ON [A].[BLLICENSEWFACTIONSTEPID] = [H].[OBJECTID]
	JOIN [BLLICENSEWFSTEP] AS [S] WITH (NOLOCK) ON [S].[BLLICENSEWFSTEPID] = [A].[BLLICENSEWFSTEPID]
	JOIN [BLLICENSE] AS [B] WITH (NOLOCK) ON [B].[BLLICENSEID] = [S].[BLLICENSEID]

END
GO

CREATE TRIGGER [TG_HEARING_INSERTUPDATE_ELASTIC_CODECASE] ON  [HEARING]
   AFTER INSERT, UPDATE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [ELASTICSEARCHOBJECT]
    ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID() ,
		[C].[CMCODECASEID] ,
        'EnerGovBusiness.CodeEnforcement.CodeCase' ,
        [C].[ROWVERSION] ,
        GETDATE() ,
        NULL ,
        2 ,
        (SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Inserted]
	JOIN [HEARINGXREF] AS [H] WITH (NOLOCK) ON [H].[HEARINGID] = [Inserted].[HEARINGID]
	JOIN [CMCODEWFACTIONSTEP] AS [A] WITH (NOLOCK) ON [A].[CMCODEWFACTIONSTEPID] = [H].[OBJECTID]
	JOIN [CMCODEWFSTEP] AS [S] WITH (NOLOCK) ON [S].[CMCODEWFSTEPID] = [A].[CMCODEWFSTEPID]
	JOIN [CMCODECASE] AS [C] WITH (NOLOCK) ON [C].[CMCODECASEID] = [S].[CMCODECASEID]

END
GO

CREATE TRIGGER [TG_HEARING_INSERTUPDATE_ELASTIC_INDLIC] ON  [HEARING]
   AFTER INSERT, UPDATE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [ELASTICSEARCHOBJECT]
    ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID() ,
		[I].[ILLICENSEID] ,
        'EnerGovBusiness.IndividualLicense.License' ,
        [I].[ROWVERSION] ,
        GETDATE() ,
        NULL ,
        2 ,
        (SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Inserted]
	JOIN [HEARINGXREF] AS [H] WITH (NOLOCK) ON [H].[HEARINGID] = [Inserted].[HEARINGID]
	JOIN [ILLICENSEWFACTIONSTEP] AS [A] WITH (NOLOCK) ON [A].[ILLICENSEWFACTIONSTEPID] = [H].[OBJECTID]
	JOIN [ILLICENSEWFSTEP] AS [S] WITH (NOLOCK) ON [S].[ILLICENSEWFSTEPID] = [A].[ILLICENSEWFSTEPID]
	JOIN [ILLICENSE] AS [I] WITH (NOLOCK) ON [I].[ILLICENSEID] = [S].[ILLICENSEID]

END
GO

CREATE TRIGGER [TG_HEARING_INSERTUPDATE_ELASTIC_PERMIT] ON  [HEARING]
   AFTER INSERT, UPDATE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [ELASTICSEARCHOBJECT]
    ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID() ,
		[P].[PMPERMITID] ,
        'EnerGovBusiness.PermitManagement.Permit' ,
        [P].[ROWVERSION] ,
        GETDATE() ,
        NULL ,
        2 ,
        (SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Inserted]
	JOIN [HEARINGXREF] AS [H] WITH (NOLOCK) ON [H].[HEARINGID] = [Inserted].[HEARINGID]
	JOIN [PMPERMITWFACTIONSTEP] AS [A] WITH (NOLOCK) ON [A].[PMPERMITWFACTIONSTEPID] = [H].[OBJECTID]
	JOIN [PMPERMITWFSTEP] AS [S] WITH (NOLOCK) ON [S].[PMPERMITWFSTEPID] = [A].[PMPERMITWFSTEPID]
	JOIN [PMPERMIT] AS [P] WITH (NOLOCK) ON [P].[PMPERMITID] = [S].[PMPERMITID]

END
GO

CREATE TRIGGER [TG_HEARING_INSERTUPDATE_ELASTIC_PLAN] ON  [HEARING]
   AFTER INSERT, UPDATE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [ELASTICSEARCHOBJECT]
    ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID() ,
		[P].[PLPLANID] ,
        'EnerGovBusiness.PlanManagement.Plan' ,
        [P].[ROWVERSION] ,
        GETDATE() ,
        NULL ,
        2 ,
        (SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Inserted]
	JOIN [HEARINGXREF] AS [H] WITH (NOLOCK) ON [H].[HEARINGID] = [Inserted].[HEARINGID]
	JOIN [PLPLANWFACTIONSTEP] AS [A] WITH (NOLOCK) ON [A].[PLPLANWFACTIONSTEPID] = [H].[OBJECTID]
	JOIN [PLPLANWFSTEP] AS [S] WITH (NOLOCK) ON [S].[PLPLANWFSTEPID] = [A].[PLPLANWFSTEPID]
	JOIN [PLPLAN] AS [P] WITH (NOLOCK) ON [P].[PLPLANID] = [S].[PLPLANID]

END