CREATE TABLE [dbo].[HEARINGATTENDEE] (
    [HEARINGATTENDEESID] CHAR (36) NOT NULL,
    [HEARINGID]          CHAR (36) NOT NULL,
    [ATTENDEEID]         CHAR (36) NOT NULL,
    [ISUSER]             BIT       CONSTRAINT [DF_HearingAttendee_IsUser] DEFAULT ((0)) NOT NULL,
    [ISGLOBALENTITY]     BIT       CONSTRAINT [DF_HearingAttendee_IsGlobalEntity] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_HearingAttendee] PRIMARY KEY CLUSTERED ([HEARINGATTENDEESID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_HearingAttendee_Hearing] FOREIGN KEY ([HEARINGID]) REFERENCES [dbo].[HEARING] ([HEARINGID])
);


GO
CREATE NONCLUSTERED INDEX [IX_HEARINGATTENDEE_ID_ATTENDEE]
    ON [dbo].[HEARINGATTENDEE]([ATTENDEEID] ASC)
    INCLUDE([HEARINGID]);

