CREATE TABLE [dbo].[HISTORYINDLICENSE] (
    [HISTORYINDLICENSEID] INT            IDENTITY (1, 1) NOT NULL,
    [ID]                  CHAR (36)      NOT NULL,
    [ROWVERSION]          INT            NOT NULL,
    [CHANGEDON]           DATETIME       NOT NULL,
    [CHANGEDBY]           CHAR (36)      NOT NULL,
    [FIELDNAME]           NVARCHAR (250) NOT NULL,
    [OLDVALUE]            NVARCHAR (MAX) NOT NULL,
    [NEWVALUE]            NVARCHAR (MAX) NOT NULL,
    [ADDITIONALINFO]      NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_HistoryIndLicenseID] PRIMARY KEY CLUSTERED ([HISTORYINDLICENSEID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [HistoryIndLicense_Users] FOREIGN KEY ([CHANGEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);


GO
CREATE NONCLUSTERED INDEX [HistoryIndLicense_ID]
    ON [dbo].[HISTORYINDLICENSE]([ID] ASC, [ROWVERSION] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IDX_HIL_ChangedOn]
    ON [dbo].[HISTORYINDLICENSE]([ID] ASC, [CHANGEDON] ASC, [HISTORYINDLICENSEID] ASC, [CHANGEDBY] ASC, [FIELDNAME] ASC)
    INCLUDE([ROWVERSION], [OLDVALUE], [NEWVALUE], [ADDITIONALINFO]) WITH (FILLFACTOR = 90);

