CREATE TABLE [dbo].[HISTORYCRMMANAGEMENT] (
    [HISTORYCRMMANAGEMENTID] INT            IDENTITY (1, 1) NOT NULL,
    [ID]                     CHAR (36)      NOT NULL,
    [ROWVERSION]             INT            NOT NULL,
    [CHANGEDON]              DATETIME       NOT NULL,
    [CHANGEDBY]              CHAR (36)      NOT NULL,
    [FIELDNAME]              NVARCHAR (250) NOT NULL,
    [OLDVALUE]               NVARCHAR (MAX) NOT NULL,
    [NEWVALUE]               NVARCHAR (MAX) NOT NULL,
    [ADDITIONALINFO]         NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_HistoryCRMManagementID] PRIMARY KEY CLUSTERED ([HISTORYCRMMANAGEMENTID] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [HistoryCRMManagement_Users] FOREIGN KEY ([CHANGEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);


GO
CREATE NONCLUSTERED INDEX [HistoryCRMManagement_ID]
    ON [dbo].[HISTORYCRMMANAGEMENT]([ID] ASC, [ROWVERSION] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IDX_HCRM_ChangedOn]
    ON [dbo].[HISTORYCRMMANAGEMENT]([CHANGEDON] ASC) WITH (FILLFACTOR = 80);

