CREATE TABLE [dbo].[HISTORYPLANMANAGEMENT] (
    [HISTORYPLANMANAGEMENTID] INT            IDENTITY (1, 1) NOT NULL,
    [ID]                      CHAR (36)      NOT NULL,
    [ROWVERSION]              INT            NOT NULL,
    [CHANGEDON]               DATETIME       NOT NULL,
    [CHANGEDBY]               CHAR (36)      NOT NULL,
    [FIELDNAME]               NVARCHAR (250) NOT NULL,
    [OLDVALUE]                NVARCHAR (MAX) NOT NULL,
    [NEWVALUE]                NVARCHAR (MAX) NOT NULL,
    [ADDITIONALINFO]          NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_HistoryPlanManagementID] PRIMARY KEY CLUSTERED ([HISTORYPLANMANAGEMENTID] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [HistoryPlanManagement_Users] FOREIGN KEY ([CHANGEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);


GO
CREATE NONCLUSTERED INDEX [HistoryPlanManagement_ID]
    ON [dbo].[HISTORYPLANMANAGEMENT]([ID] ASC, [ROWVERSION] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IDX_HPlan_ChangedOn]
    ON [dbo].[HISTORYPLANMANAGEMENT]([ID] ASC, [CHANGEDON] ASC, [HISTORYPLANMANAGEMENTID] ASC, [CHANGEDBY] ASC, [FIELDNAME] ASC)
    INCLUDE([ROWVERSION], [OLDVALUE], [NEWVALUE], [ADDITIONALINFO]) WITH (FILLFACTOR = 80);

