CREATE TABLE [dbo].[HISTORYINSPECTIONS] (
    [HISTORYINSPECTIONSID] INT            IDENTITY (1, 1) NOT NULL,
    [ID]                   CHAR (36)      NOT NULL,
    [ROWVERSION]           INT            NOT NULL,
    [CHANGEDON]            DATETIME       NOT NULL,
    [CHANGEDBY]            CHAR (36)      NOT NULL,
    [FIELDNAME]            NVARCHAR (250) NOT NULL,
    [OLDVALUE]             NVARCHAR (MAX) NOT NULL,
    [NEWVALUE]             NVARCHAR (MAX) NOT NULL,
    [ADDITIONALINFO]       NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_HistoryInspectionsID] PRIMARY KEY CLUSTERED ([HISTORYINSPECTIONSID] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [HistoryInspections_Users] FOREIGN KEY ([CHANGEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);


GO
CREATE NONCLUSTERED INDEX [HistoryInspections_ID]
    ON [dbo].[HISTORYINSPECTIONS]([ID] ASC, [ROWVERSION] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IDX_HInsp_ChangedOn]
    ON [dbo].[HISTORYINSPECTIONS]([ID] ASC, [CHANGEDON] ASC, [HISTORYINSPECTIONSID] ASC, [CHANGEDBY] ASC, [FIELDNAME] ASC)
    INCLUDE([ROWVERSION], [OLDVALUE], [NEWVALUE], [ADDITIONALINFO]) WITH (FILLFACTOR = 80);

