CREATE TABLE [dbo].[HISTORYINVMANAGEMENT] (
    [HISTORYINVENTORYMANAGEMENTID] INT            IDENTITY (1, 1) NOT NULL,
    [ID]                           CHAR (36)      NOT NULL,
    [ROWVERSION]                   INT            NOT NULL,
    [CHANGEDON]                    DATETIME       NOT NULL,
    [CHANGEDBY]                    CHAR (36)      NOT NULL,
    [FIELDNAME]                    NVARCHAR (250) NOT NULL,
    [OLDVALUE]                     NVARCHAR (MAX) NOT NULL,
    [NEWVALUE]                     NVARCHAR (MAX) NOT NULL,
    [ADDITIONALINFO]               NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_HistoryInventoryManagementI] PRIMARY KEY CLUSTERED ([HISTORYINVENTORYMANAGEMENTID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [HistoryInventoryManagement_Use] FOREIGN KEY ([CHANGEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);


GO
CREATE NONCLUSTERED INDEX [IDX_HInv_ChangedOn]
    ON [dbo].[HISTORYINVMANAGEMENT]([ID] ASC, [CHANGEDON] ASC, [HISTORYINVENTORYMANAGEMENTID] ASC, [CHANGEDBY] ASC, [FIELDNAME] ASC)
    INCLUDE([ROWVERSION], [OLDVALUE], [NEWVALUE], [ADDITIONALINFO]) WITH (FILLFACTOR = 90);

