CREATE TABLE [dbo].[HISTORYCODEMANAGEMENT] (
    [HISTORYCODEMANAGEMENTID] INT            IDENTITY (1, 1) NOT NULL,
    [ID]                      CHAR (36)      NOT NULL,
    [ROWVERSION]              INT            NOT NULL,
    [CHANGEDON]               DATETIME       NOT NULL,
    [CHANGEDBY]               CHAR (36)      NOT NULL,
    [FIELDNAME]               NVARCHAR (250) NOT NULL,
    [OLDVALUE]                NVARCHAR (MAX) NOT NULL,
    [NEWVALUE]                NVARCHAR (MAX) NOT NULL,
    [ADDITIONALINFO]          NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_HistoryCodeManagementID] PRIMARY KEY CLUSTERED ([HISTORYCODEMANAGEMENTID] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [HistoryCodeManagement_Users] FOREIGN KEY ([CHANGEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);


GO
CREATE NONCLUSTERED INDEX [HistoryCodeManagement_ID]
    ON [dbo].[HISTORYCODEMANAGEMENT]([ID] ASC, [ROWVERSION] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IDX_HCM_ChangedOn]
    ON [dbo].[HISTORYCODEMANAGEMENT]([ID] ASC, [CHANGEDON] ASC, [HISTORYCODEMANAGEMENTID] ASC, [CHANGEDBY] ASC, [FIELDNAME] ASC)
    INCLUDE([ROWVERSION], [OLDVALUE], [NEWVALUE], [ADDITIONALINFO]) WITH (FILLFACTOR = 80);

