CREATE TABLE [dbo].[HISTORYCACHE] (
    [SESSIONID]     CHAR (36)       NOT NULL,
    [ID]            CHAR (36)       NOT NULL,
    [ROWVERSION]    INT             NOT NULL,
    [ROOTCLASSNAME] CHAR (500)      NOT NULL,
    [OBJECTDATA]    VARBINARY (MAX) NOT NULL,
    [CREATEDON]     DATETIME        NOT NULL,
    CONSTRAINT [PK_HistoryCache] PRIMARY KEY NONCLUSTERED ([SESSIONID] ASC, [ID] ASC, [ROWVERSION] ASC, [ROOTCLASSNAME] ASC) WITH (FILLFACTOR = 90)
);

