CREATE TABLE [dbo].[HOLDSEVERITY] (
    [HOLDSEVERITYID]   INT          NOT NULL,
    [HOLDSEVERITYNAME] VARCHAR (50) NULL,
    CONSTRAINT [PK_HoldSeverity] PRIMARY KEY CLUSTERED ([HOLDSEVERITYID] ASC)
);

