CREATE PROCEDURE [dbo].[GETATTACHEDPERMITLIST]
-- Add the parameters for the stored procedure here
@CaseID char(36),
@ModuleID int
AS
BEGIN	
	IF @ModuleID = 1
	BEGIN
		SELECT	DISTINCT PMPERMIT.PMPERMITID,
				PMPERMIT.PERMITNUMBER,
				PMPERMITTYPE.NAME AS PERMITTYPE,
				PMPERMITWORKCLASS.NAME AS WORKCLASS,
				PMPERMITSTATUS.NAME AS STATUS,
				PMPERMIT.ISSUEDATE,
				PMPERMIT.EXPIREDATE
		FROM	PLPLANACTIONREF
		INNER JOIN PMPERMITWFACTIONSTEP ON PLPLANACTIONREF.OBJECTID = PMPERMITWFACTIONSTEP.PMPERMITWFACTIONSTEPID
		INNER JOIN PMPERMITWFSTEP ON PMPERMITWFSTEP.PMPERMITWFSTEPID = PMPERMITWFACTIONSTEP.PMPERMITWFSTEPID
		INNER JOIN PMPERMIT ON PMPERMIT.PMPERMITID = PMPERMITWFSTEP.PMPERMITID
		INNER JOIN PMPERMITTYPE ON PMPERMITTYPE.PMPERMITTYPEID = PMPERMIT.PMPERMITTYPEID
		INNER JOIN PMPERMITSTATUS ON PMPERMITSTATUS.PMPERMITSTATUSID = PMPERMIT.PMPERMITSTATUSID
		LEFT OUTER JOIN PMPERMITWORKCLASS ON PMPERMITWORKCLASS.PMPERMITWORKCLASSID = PMPERMIT.PMPERMITWORKCLASSID	
		WHERE PLPLANACTIONREF.PLPLANID = @CaseID								
		UNION
		SELECT  DISTINCT PMPERMIT.PMPERMITID,
				PMPERMIT.PERMITNUMBER,
				PMPERMITTYPE.NAME AS PERMITTYPE,
				PMPERMITWORKCLASS.NAME AS WORKCLASS,
				PMPERMITSTATUS.NAME AS STATUS,
				PMPERMIT.ISSUEDATE,
				PMPERMIT.EXPIREDATE
		FROM PLPLANWFSTEP
		INNER JOIN PLPLANWFACTIONSTEP ON PLPLANWFACTIONSTEP.PLPLANWFSTEPID = PLPLANWFSTEP.PLPLANWFSTEPID
		INNER JOIN PMPERMITACTIONREF ON PMPERMITACTIONREF.OBJECTID = PLPLANWFACTIONSTEP.PLPLANWFACTIONSTEPID
		INNER JOIN PMPERMIT ON PMPERMIT.PMPERMITID = PMPERMITACTIONREF.PMPERMITID
		INNER JOIN PMPERMITTYPE ON PMPERMITTYPE.PMPERMITTYPEID = PMPERMIT.PMPERMITTYPEID
		INNER JOIN PMPERMITSTATUS ON PMPERMITSTATUS.PMPERMITSTATUSID = PMPERMIT.PMPERMITSTATUSID
		LEFT OUTER JOIN PMPERMITWORKCLASS ON PMPERMITWORKCLASS.PMPERMITWORKCLASSID = PMPERMIT.PMPERMITWORKCLASSID	
		WHERE PLPLANWFSTEP.PLPLANID = @CaseID
	END	
	ELSE IF @ModuleID = 2
	BEGIN
		SELECT	DISTINCT PMPERMIT.PMPERMITID,
				PMPERMIT.PERMITNUMBER,
				PMPERMITTYPE.NAME AS PERMITTYPE,
				PMPERMITWORKCLASS.NAME AS WORKCLASS,
				PMPERMITSTATUS.NAME AS STATUS,
				PMPERMIT.ISSUEDATE,
				PMPERMIT.EXPIREDATE
		FROM	PMPERMITACTIONREF
		INNER JOIN PMPERMITWFACTIONSTEP ON PMPERMITACTIONREF.OBJECTID = PMPERMITWFACTIONSTEP.PMPERMITWFACTIONSTEPID
		INNER JOIN PMPERMITWFSTEP ON PMPERMITWFSTEP.PMPERMITWFSTEPID = PMPERMITWFACTIONSTEP.PMPERMITWFSTEPID
		INNER JOIN PMPERMIT ON PMPERMIT.PMPERMITID = PMPERMITWFSTEP.PMPERMITID
		INNER JOIN PMPERMITTYPE ON PMPERMITTYPE.PMPERMITTYPEID = PMPERMIT.PMPERMITTYPEID
		INNER JOIN PMPERMITSTATUS ON PMPERMITSTATUS.PMPERMITSTATUSID = PMPERMIT.PMPERMITSTATUSID
		LEFT OUTER JOIN PMPERMITWORKCLASS ON PMPERMITWORKCLASS.PMPERMITWORKCLASSID = PMPERMIT.PMPERMITWORKCLASSID	
		WHERE PMPERMITACTIONREF.PMPERMITID = @CaseID
		UNION
		SELECT  DISTINCT PMPERMIT.PMPERMITID,
				PMPERMIT.PERMITNUMBER,
				PMPERMITTYPE.NAME AS PERMITTYPE,
				PMPERMITWORKCLASS.NAME AS WORKCLASS,
				PMPERMITSTATUS.NAME AS STATUS,
				PMPERMIT.ISSUEDATE,
				PMPERMIT.EXPIREDATE
		FROM PMPERMITWFSTEP
		INNER JOIN PMPERMITWFACTIONSTEP ON PMPERMITWFACTIONSTEP.PMPERMITWFSTEPID = PMPERMITWFSTEP.PMPERMITWFSTEPID
		INNER JOIN PMPERMITACTIONREF ON PMPERMITACTIONREF.OBJECTID = PMPERMITWFACTIONSTEP.PMPERMITWFACTIONSTEPID
		INNER JOIN PMPERMIT ON PMPERMIT.PMPERMITID = PMPERMITACTIONREF.PMPERMITID
		INNER JOIN PMPERMITTYPE ON PMPERMITTYPE.PMPERMITTYPEID = PMPERMIT.PMPERMITTYPEID
		INNER JOIN PMPERMITSTATUS ON PMPERMITSTATUS.PMPERMITSTATUSID = PMPERMIT.PMPERMITSTATUSID
		LEFT OUTER JOIN PMPERMITWORKCLASS ON PMPERMITWORKCLASS.PMPERMITWORKCLASSID = PMPERMIT.PMPERMITWORKCLASSID	
		WHERE PMPERMITWFSTEP.PMPERMITID = @CaseID
	END
END