CREATE PROCEDURE [dbo].[GETATTACHEDPLANLIST]
-- Add the parameters for the stored procedure here
@CaseID char(36),
@ModuleID int
AS
BEGIN	
	IF @ModuleID = 1
	BEGIN
		SELECT	DISTINCT PLPLAN.PLPLANID,
				PLPLAN.PLANNUMBER,
				PLPLANTYPE.PLANNAME AS PLANTYPE,
				PLPLANWORKCLASS.NAME AS WORKCLASS,
				PLPLANSTATUS.NAME AS STATUS,
				PLPLAN.APPLICATIONDATE,
				PLPLAN.EXPIREDATE
		FROM	PLPLANACTIONREF
		INNER JOIN PLPLANWFACTIONSTEP ON PLPLANACTIONREF.OBJECTID = PLPLANWFACTIONSTEP.PLPLANWFACTIONSTEPID
		INNER JOIN PLPLANWFSTEP ON PLPLANWFSTEP.PLPLANWFSTEPID = PLPLANWFACTIONSTEP.PLPLANWFSTEPID
		INNER JOIN PLPLAN ON PLPLAN.PLPLANID = PLPLANWFSTEP.PLPLANID
		INNER JOIN PLPLANTYPE ON PLPLANTYPE.PLPLANTYPEID = PLPLAN.PLPLANTYPEID
		INNER JOIN PLPLANSTATUS ON PLPLANSTATUS.PLPLANSTATUSID = PLPLAN.PLPLANSTATUSID
		LEFT OUTER JOIN PLPLANWORKCLASS ON PLPLANWORKCLASS.PLPLANWORKCLASSID = PLPLAN.PLPLANWORKCLASSID	
		WHERE PLPLANACTIONREF.PLPLANID = @CaseID	
		UNION
		SELECT	DISTINCT PLPLAN.PLPLANID,
				PLPLAN.PLANNUMBER,
				PLPLANTYPE.PLANNAME AS PLANTYPE,
				PLPLANWORKCLASS.NAME AS WORKCLASS,
				PLPLANSTATUS.NAME AS STATUS,
				PLPLAN.APPLICATIONDATE,
				PLPLAN.EXPIREDATE
		FROM PLPLANWFSTEP
		INNER JOIN PLPLANWFACTIONSTEP ON PLPLANWFACTIONSTEP.PLPLANWFSTEPID = PLPLANWFSTEP.PLPLANWFSTEPID
		INNER JOIN PLPLANACTIONREF ON PLPLANACTIONREF.OBJECTID = PLPLANWFACTIONSTEP.PLPLANWFACTIONSTEPID
		INNER JOIN PLPLAN ON PLPLAN.PLPLANID = PLPLANACTIONREF.PLPLANID
		INNER JOIN PLPLANTYPE ON PLPLANTYPE.PLPLANTYPEID = PLPLAN.PLPLANTYPEID
		INNER JOIN PLPLANSTATUS ON PLPLANSTATUS.PLPLANSTATUSID = PLPLAN.PLPLANSTATUSID
		LEFT OUTER JOIN PLPLANWORKCLASS ON PLPLANWORKCLASS.PLPLANWORKCLASSID = PLPLAN.PLPLANWORKCLASSID	
		WHERE PLPLANWFSTEP.PLPLANID = @CaseID	
	END	
	ELSE IF @ModuleID = 2
	BEGIN
		SELECT	DISTINCT PLPLAN.PLPLANID,
				PLPLAN.PLANNUMBER,
				PLPLANTYPE.PLANNAME AS PLANTYPE,
				PLPLANWORKCLASS.NAME AS WORKCLASS,
				PLPLANSTATUS.NAME AS STATUS,
				PLPLAN.APPLICATIONDATE,
				PLPLAN.EXPIREDATE
		FROM	PMPERMITACTIONREF
		INNER JOIN PLPLANWFACTIONSTEP ON PMPERMITACTIONREF.OBJECTID = PLPLANWFACTIONSTEP.PLPLANWFACTIONSTEPID
		INNER JOIN PLPLANWFSTEP ON PLPLANWFSTEP.PLPLANWFSTEPID = PLPLANWFACTIONSTEP.PLPLANWFSTEPID
		INNER JOIN PLPLAN ON PLPLAN.PLPLANID = PLPLANWFSTEP.PLPLANID
		INNER JOIN PLPLANTYPE ON PLPLANTYPE.PLPLANTYPEID = PLPLAN.PLPLANTYPEID
		INNER JOIN PLPLANSTATUS ON PLPLANSTATUS.PLPLANSTATUSID = PLPLAN.PLPLANSTATUSID
		LEFT OUTER JOIN PLPLANWORKCLASS ON PLPLANWORKCLASS.PLPLANWORKCLASSID = PLPLAN.PLPLANWORKCLASSID	
		WHERE PMPERMITACTIONREF.PMPERMITID = @CaseID
		UNION
		SELECT	DISTINCT PLPLAN.PLPLANID,
				PLPLAN.PLANNUMBER,
				PLPLANTYPE.PLANNAME AS PLANTYPE,
				PLPLANWORKCLASS.NAME AS WORKCLASS,
				PLPLANSTATUS.NAME AS STATUS,
				PLPLAN.APPLICATIONDATE,
				PLPLAN.EXPIREDATE
		FROM PMPERMITWFSTEP
		INNER JOIN PMPERMITWFACTIONSTEP ON PMPERMITWFACTIONSTEP.PMPERMITWFSTEPID = PMPERMITWFSTEP.PMPERMITWFSTEPID
		INNER JOIN PLPLANACTIONREF ON PLPLANACTIONREF.OBJECTID = PMPERMITWFACTIONSTEP.PMPERMITWFACTIONSTEPID
		INNER JOIN PLPLAN ON PLPLAN.PLPLANID = PLPLANACTIONREF.PLPLANID
		INNER JOIN PLPLANTYPE ON PLPLANTYPE.PLPLANTYPEID = PLPLAN.PLPLANTYPEID
		INNER JOIN PLPLANSTATUS ON PLPLANSTATUS.PLPLANSTATUSID = PLPLAN.PLPLANSTATUSID
		LEFT OUTER JOIN PLPLANWORKCLASS ON PLPLANWORKCLASS.PLPLANWORKCLASSID = PLPLAN.PLPLANWORKCLASSID	
		WHERE PMPERMITWFSTEP.PMPERMITID = @CaseID
	END
END