
CREATE PROCEDURE [dbo].[GETCONDITIONLIBRARYLIST]
-- Add the parameters for the stored procedure here
@ConditionName nvarchar(max),
@ConditionDesc nvarchar(max),
@ConditionCategoryID char(36)
AS
BEGIN	
	IF (@ConditionName IS NOT NULL)
	BEGIN
		SET @ConditionName = '%' + @ConditionName + '%'
	END
	IF (@ConditionDesc IS NOT NULL)
	BEGIN
		SET @ConditionDesc = '%' + @ConditionDesc + '%'
	END
		
	SELECT	DISTINCT CONDITIONLIBRARY.CONDITIONLIBRARYID,
			CONDITIONLIBRARY.CONDITIONCATEGORYID,
			CONDITIONLIBRARY.NAME,
			CONDITIONLIBRARY.DESCRIPTION,
			CONDITIONCATEGORY.NAME AS CATEGORYNAME
	FROM CONDITIONLIBRARY	
	INNER JOIN CONDITIONCATEGORY ON CONDITIONCATEGORY.CONDITIONCATEGORYID =	CONDITIONLIBRARY.CONDITIONCATEGORYID		
	WHERE	(@ConditionName IS NULL OR CONDITIONLIBRARY.NAME LIKE @ConditionName) AND
			(@ConditionDesc IS NULL OR CONDITIONLIBRARY.DESCRIPTION LIKE @ConditionDesc) AND
			(@ConditionCategoryID IS NULL OR CONDITIONLIBRARY.CONDITIONCATEGORYID = @ConditionCategoryID)	
END
