
CREATE PROCEDURE [dbo].[GETERFILECATEGORYXREFLIST]
-- Add the parameters for the stored procedure here
@ERProjectFileID char(36)	
AS
BEGIN	
	SELECT	DISTINCT ERPROJECTFILECATEGORYXREF.ERPROJECTFILECATEGORYXREFID,
			ERPROJECTFILECATEGORYXREF.ERPROJECTFILEID,
			ERPROJECTFILECATEGORYXREF.ERPROJECTFILECATEGORYID,
			ERPROJECTFILECATEGORY.NAME AS CATEGORYNAME				
	FROM ERPROJECTFILECATEGORYXREF		
	INNER JOIN ERPROJECTFILECATEGORY ON ERPROJECTFILECATEGORY.ERPROJECTFILECATEGORYID = ERPROJECTFILECATEGORYXREF.ERPROJECTFILECATEGORYID	
	WHERE (ERPROJECTFILECATEGORYXREF.ERPROJECTFILEID = @ERProjectFileID)	       
END
