CREATE PROCEDURE [dbo].[GETERPORTALCASE]
-- Add the parameters for the stored procedure here
@CaseID char(36),
@ModuleID int
AS
BEGIN
	IF @ModuleID = 1
	BEGIN	
		SELECT	DISTINCT PLPLAN.PLPLANID AS CASEID,
				PLPLAN.PLANNUMBER AS CASENUMBER,				
				PLPLANSTATUS.NAME AS CASESTATUSNAME,				
				PLPLAN.APPLICATIONDATE,
				PLPLAN.COMPLETEDATE,
				PLPLAN.EXPIREDATE,
				NULL AS ISSUEDATE,
				PRPROJECT.NAME AS PROJECTNAME,
				PLPLANTYPE.PLANNAME AS CASETYPENAME,
				PLPLANWORKCLASS.NAME AS WORKCLASSNAME,
				1 AS MODULEID,
				'Plan' AS MODULENAME
		FROM PLPLAN		
		INNER JOIN PLPLANSTATUS ON PLPLANSTATUS.PLPLANSTATUSID = PLPLAN.PLPLANSTATUSID		
		INNER JOIN PLPLANTYPE ON PLPLANTYPE.PLPLANTYPEID = PLPLAN.PLPLANTYPEID
		LEFT OUTER JOIN PLPLANWORKCLASS ON PLPLANWORKCLASS.PLPLANWORKCLASSID = PLPLAN.PLPLANWORKCLASSID
		OUTER APPLY (SELECT TOP 1 PRPROJECTID FROM PRPROJECTPLAN WHERE PRPROJECTPLAN.PLPLANID = PLPLAN.PLPLANID) A
		LEFT OUTER JOIN PRPROJECT ON PRPROJECT.PRPROJECTID = A.PRPROJECTID	
		WHERE PLPLAN.PLPLANID = @CaseID
	END
	ELSE IF @ModuleID = 2
	BEGIN
		SELECT	DISTINCT PMPERMIT.PMPERMITID AS CASEID,
				PMPERMIT.PERMITNUMBER AS CASENUMBER,				
				PMPERMITSTATUS.NAME AS CASESTATUSNAME,				
				PMPERMIT.APPLYDATE AS APPLICATIONDATE,
				NULL AS COMPLETEDATE,
				PMPERMIT.EXPIREDATE,
				PMPERMIT.ISSUEDATE,
				PRPROJECT.NAME AS PROJECTNAME,
				PMPERMITTYPE.NAME AS CASETYPENAME,
				PMPERMITWORKCLASS.NAME AS WORKCLASSNAME,
				2 AS MODULEID,
				'Permit' AS MODULENAME
		FROM PMPERMIT		
		INNER JOIN PMPERMITSTATUS ON PMPERMITSTATUS.PMPERMITSTATUSID = PMPERMIT.PMPERMITSTATUSID		
		INNER JOIN PMPERMITTYPE ON PMPERMITTYPE.PMPERMITTYPEID = PMPERMIT.PMPERMITTYPEID
		LEFT OUTER JOIN PMPERMITWORKCLASS ON PMPERMITWORKCLASS.PMPERMITWORKCLASSID = PMPERMIT.PMPERMITWORKCLASSID
		OUTER APPLY (SELECT TOP 1 PRPROJECTID FROM PRPROJECTPERMIT WHERE PRPROJECTPERMIT.PMPERMITID = PMPERMIT.PMPERMITID) A
		LEFT OUTER JOIN PRPROJECT ON PRPROJECT.PRPROJECTID = A.PRPROJECTID	
		WHERE PMPERMIT.PMPERMITID = @CaseID
	END
END