
CREATE PROCEDURE [dbo].[GETEREVIEWCONFIGURATION]	
AS
BEGIN			
	DECLARE @ERFILETRANSFERSERVICEURL nvarchar(500)
	DECLARE @ENERGOVBUILD nvarchar(500)
	DECLARE @ERUPLOADPATH nvarchar(500)
	DECLARE @ERDOWNLOADPATH nvarchar(500)
	DECLARE @ENERGOVSILVERURL nvarchar(500)
	DECLARE @ERUSEDEFAULTCORRECTIONTYPE bit
	DECLARE @ERDEFAULTCORRECTIONTYPEID nvarchar(500)
	DECLARE @ALLOWTIMETRACKINGFORPLAN bit
	DECLARE @ERDEFAULTCORRECTIONTYPEDESCRIPTION nvarchar(max)
	DECLARE @ERDEFAULTCORRECTIONTYPEACTION nvarchar(max)
	DECLARE @ERDEFAULTCORRECTIONTYPENAME nvarchar(50)
	DECLARE @ERDEFAULTCORRECTIONTYPECATEGORY nvarchar(250)
	SELECT @ENERGOVBUILD = STRINGVALUE FROM SETTINGS WHERE NAME = 'EnerGovEnterpriseServerBuild'
	SELECT @ERFILETRANSFERSERVICEURL = STRINGVALUE FROM SETTINGS WHERE NAME = 'ERFILETRANSFERSERVICEURL'
	SELECT @ERUPLOADPATH = STRINGVALUE FROM SETTINGS WHERE NAME = 'ERUploadPath'
	SELECT @ERDOWNLOADPATH = STRINGVALUE FROM SETTINGS WHERE NAME = 'ERDownloadPath'
	SELECT @ENERGOVSILVERURL = STRINGVALUE FROM SETTINGS WHERE NAME = 'EnerGovSilverUrl'
	SELECT @ALLOWTIMETRACKINGFORPLAN = BITVALUE FROM SETTINGS WHERE NAME = 'AllowTimeTrackingForPlan'
	SELECT @ERUSEDEFAULTCORRECTIONTYPE = BITVALUE  FROM SETTINGS WHERE NAME = 'ERUseDefaultCorrectionType'
	SELECT @ERDEFAULTCORRECTIONTYPEID = STRINGVALUE FROM SETTINGS WHERE NAME = 'ERDefaultCorrectionTypeID'
	IF @ERDEFAULTCORRECTIONTYPEID IS NOT NULL
	BEGIN
		SELECT @ERDEFAULTCORRECTIONTYPEDESCRIPTION = PLPLANCORRECTIONTYPE.DESCRIPTION, 
		@ERDEFAULTCORRECTIONTYPEACTION = PLPLANCORRECTIONTYPE.CORRECTIVEACTION,
		@ERDEFAULTCORRECTIONTYPENAME = PLPLANCORRECTIONTYPE.NAME,
		@ERDEFAULTCORRECTIONTYPECATEGORY = PLCORRECTIONTYPECATEGORY.NAME
		FROM PLPLANCORRECTIONTYPE 
		LEFT OUTER JOIN PLCORRECTIONTYPECATEGORY ON PLCORRECTIONTYPECATEGORY.PLCORRECTIONTYPECATEGORYID = PLPLANCORRECTIONTYPE.PLCORRECTIONTYPECATEGORYID
		WHERE PLPLANCORRECTIONTYPEID = @ERDEFAULTCORRECTIONTYPEID 
	END
	SELECT 
	@ERFILETRANSFERSERVICEURL AS ERFILETRANSFERSERVICEURL, 
	@ENERGOVBUILD AS ENERGOVBUILD, 
	@ERUPLOADPATH AS ERUPLOADPATH, 
	@ERDOWNLOADPATH AS ERDOWNLOADPATH,
	@ENERGOVSILVERURL AS ENERGOVSILVERURL,	
	@ALLOWTIMETRACKINGFORPLAN AS ALLOWTIMETRACKINGFORPLAN,
	@ERUSEDEFAULTCORRECTIONTYPE AS ERUSEDEFAULTCORRECTIONTYPE,
	@ERDEFAULTCORRECTIONTYPEID AS ERDEFAULTCORRECTIONTYPEID,
	@ERDEFAULTCORRECTIONTYPEDESCRIPTION AS ERDEFAULTCORRECTIONTYPEDESCRIPTION,
	@ERDEFAULTCORRECTIONTYPEACTION AS ERDEFAULTCORRECTIONTYPEACTION,
	@ERDEFAULTCORRECTIONTYPENAME AS ERDEFAULTCORRECTIONTYPENAME,
	@ERDEFAULTCORRECTIONTYPECATEGORY AS ERDEFAULTCORRECTIONTYPECATEGORY
END
