CREATE PROCEDURE [dbo].[GETERPORTALDEFAULTCASELIST]
-- Add the parameters for the stored procedure here
@GlobalEntityID char(36),
@NumOfDay int	
AS
BEGIN
	DECLARE @ApplyDate datetime
	SET @ApplyDate = getdate() - @NumOfDay	

	SELECT	DISTINCT PLPLAN.PLPLANID AS CASEID,
			PLPLAN.PLANNUMBER AS CASENUMBER,				
			PLPLANSTATUS.NAME AS CASESTATUSNAME,				
			PLPLAN.APPLICATIONDATE,
			PLPLAN.COMPLETEDATE,
			PLPLAN.EXPIREDATE,
			NULL AS ISSUEDATE,
			PRPROJECT.NAME AS PROJECTNAME,
			PRPROJECT.PROJECTNUMBER AS PROJECTNUMBER,
			1 AS MODULEID,
			'Plan' AS MODULENAME							
	FROM PLPLAN		
	INNER JOIN PLPLANSTATUS ON PLPLANSTATUS.PLPLANSTATUSID = PLPLAN.PLPLANSTATUSID
	INNER JOIN PLPLANCONTACT ON PLPLANCONTACT.PLPLANID = PLPLAN.PLPLANID	
	LEFT OUTER JOIN PRPROJECTPLAN ON PRPROJECTPLAN.PLPLANID = PLPLAN.PLPLANID
	LEFT OUTER JOIN PRPROJECT ON PRPROJECT.PRPROJECTID = PRPROJECTPLAN.PRPROJECTID	
	WHERE (PLPLANCONTACT.GLOBALENTITYID = @GlobalEntityID AND PLPLAN.APPLICATIONDATE > @ApplyDate)
	UNION
	SELECT	DISTINCT PMPERMIT.PMPERMITID AS CASEID,
			PMPERMIT.PERMITNUMBER AS CASENUMBER,				
			PMPERMITSTATUS.NAME AS CASESTATUSNAME,				
			PMPERMIT.APPLYDATE AS APPLICATIONDATE,
			NULL AS COMPLETEDATE,
			PMPERMIT.EXPIREDATE,
			PMPERMIT.ISSUEDATE,
			PRPROJECT.NAME AS PROJECTNAME,
			PRPROJECT.PROJECTNUMBER AS PROJECTNUMBER,
			2 AS MODULEID,
			'Permit' AS MODULENAME								
	FROM PMPERMIT		
	INNER JOIN PMPERMITSTATUS ON PMPERMITSTATUS.PMPERMITSTATUSID = PMPERMIT.PMPERMITSTATUSID
	INNER JOIN PMPERMITCONTACT ON PMPERMITCONTACT.PMPERMITID = PMPERMIT.PMPERMITID	
	LEFT OUTER JOIN PRPROJECTPERMIT ON PRPROJECTPERMIT.PMPERMITID = PMPERMIT.PMPERMITID
	LEFT OUTER JOIN PRPROJECT ON PRPROJECT.PRPROJECTID = PRPROJECTPERMIT.PRPROJECTID	
	WHERE (PMPERMITCONTACT.GLOBALENTITYID = @GlobalEntityID AND PMPERMIT.APPLYDATE > @ApplyDate)
END