

CREATE PROCEDURE [dbo].[GETERFILECATEGORYLIST]
-- Add the parameters for the stored procedure here
@ERProjectID char(36)	
AS
BEGIN	
	SELECT DISTINCT ERPROJECTFILECATEGORY.ERPROJECTFILECATEGORYID, ERPROJECTFILECATEGORY.NAME
	FROM ERPROJECTFILECATEGORY	
	INNER JOIN ERPROJECTFILECATEGORYXREF ON ERPROJECTFILECATEGORY.ERPROJECTFILECATEGORYID = ERPROJECTFILECATEGORYXREF.ERPROJECTFILECATEGORYID
	INNER JOIN ERPROJECTFILE ON ERPROJECTFILE.ERPROJECTFILEID = ERPROJECTFILECATEGORYXREF.ERPROJECTFILEID
	WHERE ERPROJECTFILE.ERPROJECTID = @ERProjectID
	ORDER BY ERPROJECTFILECATEGORY.NAME ASC
END
