
CREATE PROCEDURE [dbo].[GETERPORTALERPROJECTFILELIST]
-- Add the parameters for the stored procedure here
@ERProjectID char(36)	
AS
BEGIN		
	SELECT	DISTINCT ERPROJECTFILE.ERPROJECTFILEID,
			ERPROJECTFILE.ERPROJECTID,				
			ERPROJECTFILE.FILENAME,
			FILECATEGORY.ERPROJECTFILECATEGORYID,
			FILECATEGORY.ERPROJECTFILECATEGORYXREFID,
			ERPROJECTFILE.CREATEDATE,
			ERPROJECTFILE.ALLOWREVISIONFILEUPLOAD,
			ERPROJECTFILE.ROWVERSION,
			ERPROJECTFILE.PENDING
	FROM ERPROJECTFILE
	OUTER APPLY (SELECT TOP 1 ERPROJECTFILECATEGORYXREF.ERPROJECTFILECATEGORYXREFID,ERPROJECTFILECATEGORYXREF.ERPROJECTFILECATEGORYID FROM ERPROJECTFILECATEGORYXREF WHERE ERPROJECTFILECATEGORYXREF.ERPROJECTFILEID = ERPROJECTFILE.ERPROJECTFILEID) FILECATEGORY				
	WHERE ERPROJECTFILE.ERPROJECTID = @ERProjectID AND ERPROJECTFILE.MARKDELETE = 0
	ORDER BY ERPROJECTFILE.FILENAME
END	
