
CREATE PROCEDURE [dbo].[GETERPLANPARENTPERMITLIST]
-- Add the parameters for the stored procedure here
@PlanID char(36)	
AS
BEGIN	
	SELECT	DISTINCT PMPERMIT.PMPERMITID,
			PMPERMIT.PERMITNUMBER,
			PMPERMITTYPE.NAME AS PERMITTYPENAME,
			PMPERMITWORKCLASS.NAME AS PERMITWORKCLASSNAME
	FROM PMPERMIT
	INNER JOIN PMPERMITTYPE ON PMPERMITTYPE.PMPERMITTYPEID = PMPERMIT.PMPERMITTYPEID
	LEFT OUTER JOIN PMPERMITWORKCLASS ON PMPERMITWORKCLASS.PMPERMITWORKCLASSID = PMPERMIT.PMPERMITWORKCLASSID
	INNER JOIN PMPERMITWFSTEP ON PMPERMITWFSTEP.PMPERMITID = PMPERMIT.PMPERMITID
	INNER JOIN PMPERMITWFACTIONSTEP ON PMPERMITWFACTIONSTEP.PMPERMITWFSTEPID = PMPERMITWFSTEP.PMPERMITWFSTEPID
	INNER JOIN PLPLANACTIONREF ON PLPLANACTIONREF.OBJECTID = PMPERMITWFACTIONSTEP.PMPERMITWFACTIONSTEPID
	WHERE PLPLANACTIONREF.PLPLANID = @PlanID
END
