
CREATE PROCEDURE [dbo].[GETFILEVERSIONMARKUPLIST]
-- Add the parameters for the stored procedure here
@FileVersionID char(36)	
AS
BEGIN	
	SELECT ERMARKUPELEMENTID AS UNIQUEID, PAGENUMBER, ELEMENTNUMBER, ELEMENTID
	FROM ERMARKUPELEMENT
	INNER JOIN PLPLANCORRECTION ON PLPLANCORRECTION.PLPLANCORRECTIONID = ERMARKUPELEMENT.PLPLANCORRECTIONID
	WHERE PLPLANCORRECTION.ERPROJECTFILEVERSIONID = @FileVersionID
	UNION
	SELECT ERRECOMMENDATIONELEMENTID AS UNIQUEID, PAGENUMBER, ELEMENTNUMBER, ELEMENTID
	FROM ERRECOMMENDATIONELEMENT
	INNER JOIN PLPLANRECOMMENDATION ON PLPLANRECOMMENDATION.PLPLANRECOMENDATIONID = ERRECOMMENDATIONELEMENT.PLPLANRECOMMENDATIONID
	WHERE PLPLANRECOMMENDATION.ERPROJECTFILEVERSIONID = @FileVersionID
END
