CREATE PROCEDURE [dbo].[GETITEMREVIEWCORRECTIONLIST]
-- Add the parameters for the stored procedure here
@ItemReviewID char(36),
@ModuleID int
AS
BEGIN	
	IF @ModuleID = 1
	BEGIN
		SELECT	DISTINCT PLPLANCORRECTION.PLPLANCORRECTIONID,  
				PLPLANCORRECTION.PLPLANID AS CASEID,
				PLPLANCORRECTION.PLPLANCORRECTIONTYPEID,
				PLPLANCORRECTIONTYPE.NAME AS CORRECTIONTYPENAME,
				PLCORRECTIONTYPECATEGORY.NAME AS CORRECTIONTYPECATEGORYNAME,
				PLPLANCORRECTION.PLITEMREVIEWID,			
				PLPLANCORRECTION.COMMENTS,
				PLPLANCORRECTION.CORRECTIVEACTION,
				PLPLANCORRECTION.ADDEDBYUSERID,
				USER1.FNAME AS ADDEDBYFIRSTNAME, 
				USER1.LNAME AS ADDEDBYLASTNAME,
				PLPLANCORRECTION.RESOLVEDBYUSERID, 
				USER2.FNAME AS RESOLVEDBYFIRSTNAME, 
				USER2.LNAME AS RESOLVEDBYLASTNAME,
				ERPROJECTFILEVERSION.ERPROJECTFILEVERSIONID,
				ERPROJECTFILEVERSION.SAVEFILENAME,
				PLPLANCORRECTION.RESOLVED,
				PLPLANCORRECTION.ISEREVIEW,
				PLPLANCORRECTION.REPLIED,
				1 AS MODULEID,
				'Plan' AS MODULENAME			
		FROM PLPLANCORRECTION	
		INNER JOIN PLPLANCORRECTIONTYPE ON PLPLANCORRECTIONTYPE.PLPLANCORRECTIONTYPEID = PLPLANCORRECTION.PLPLANCORRECTIONTYPEID
		LEFT OUTER JOIN PLCORRECTIONTYPECATEGORY ON PLCORRECTIONTYPECATEGORY.PLCORRECTIONTYPECATEGORYID = PLPLANCORRECTIONTYPE.PLCORRECTIONTYPECATEGORYID
		LEFT OUTER JOIN ERPROJECTFILEVERSION ON ERPROJECTFILEVERSION.ERPROJECTFILEVERSIONID = PLPLANCORRECTION.ERPROJECTFILEVERSIONID		
		LEFT OUTER JOIN USERS AS USER1 ON USER1.SUSERGUID = PLPLANCORRECTION.ADDEDBYUSERID
		LEFT OUTER JOIN USERS AS USER2 ON USER2.SUSERGUID = PLPLANCORRECTION.RESOLVEDBYUSERID	
		WHERE (PLPLANCORRECTION.PLITEMREVIEWID = @ItemReviewID)	       
	END
	ELSE IF @ModuleID = 2
	BEGIN
	SELECT	DISTINCT PLPLANCORRECTION.PLPLANCORRECTIONID,  
			PLPLANCORRECTION.PMPERMITID AS CASEID,
			PLPLANCORRECTION.PLPLANCORRECTIONTYPEID,
			PLPLANCORRECTIONTYPE.NAME AS CORRECTIONTYPENAME,
			PLCORRECTIONTYPECATEGORY.NAME AS CORRECTIONTYPECATEGORYNAME,
			PLPLANCORRECTION.PLITEMREVIEWID,			
			PLPLANCORRECTION.COMMENTS,
			PLPLANCORRECTION.CORRECTIVEACTION,
			PLPLANCORRECTION.ADDEDBYUSERID,
			USER1.FNAME AS ADDEDBYFIRSTNAME, 
			USER1.LNAME AS ADDEDBYLASTNAME,
			PLPLANCORRECTION.RESOLVEDBYUSERID, 
			USER2.FNAME AS RESOLVEDBYFIRSTNAME, 
			USER2.LNAME AS RESOLVEDBYLASTNAME,
			ERPROJECTFILEVERSION.ERPROJECTFILEVERSIONID,
			ERPROJECTFILEVERSION.SAVEFILENAME,
			PLPLANCORRECTION.RESOLVED,
			PLPLANCORRECTION.ISEREVIEW,
			PLPLANCORRECTION.REPLIED,
			2 AS MODULEID,
			'Permit' AS MODULENAME			
	FROM PLPLANCORRECTION	
	INNER JOIN PLPLANCORRECTIONTYPE ON PLPLANCORRECTIONTYPE.PLPLANCORRECTIONTYPEID = PLPLANCORRECTION.PLPLANCORRECTIONTYPEID
	LEFT OUTER JOIN PLCORRECTIONTYPECATEGORY ON PLCORRECTIONTYPECATEGORY.PLCORRECTIONTYPECATEGORYID = PLPLANCORRECTIONTYPE.PLCORRECTIONTYPECATEGORYID
	LEFT OUTER JOIN ERPROJECTFILEVERSION ON ERPROJECTFILEVERSION.ERPROJECTFILEVERSIONID = PLPLANCORRECTION.ERPROJECTFILEVERSIONID		
	LEFT OUTER JOIN USERS AS USER1 ON USER1.SUSERGUID = PLPLANCORRECTION.ADDEDBYUSERID
	LEFT OUTER JOIN USERS AS USER2 ON USER2.SUSERGUID = PLPLANCORRECTION.RESOLVEDBYUSERID	
	WHERE (PLPLANCORRECTION.PLITEMREVIEWID = @ItemReviewID)	       
	END
END