CREATE PROCEDURE [dbo].[GETITEMREVIEW]
-- Add the parameters for the stored procedure here
@ItemReviewID char(36),
@ModuleID int	
AS
BEGIN	
	IF @ModuleID = 1
	BEGIN
		SELECT	DISTINCT PLITEMREVIEW.PLITEMREVIEWID,  
				PLITEMREVIEW.PLPLANID AS CASEID,
				ERPROJECT.ERPROJECTID,
				PLSUBMITTALTYPE.TYPENAME AS SUBMITTALTYPENAME,
				PLITEMREVIEWSTATUS.PLITEMREVIEWSTATUSID,
				PLITEMREVIEWSTATUS.NAME AS STATUSNAME,
				PLITEMREVIEWTYPE.NAME AS ITEMREVIEWTYPENAME,
				PLITEMREVIEWTYPE.CODENAME AS CODENAME,
				PLITEMREVIEWTYPE.CODEURL AS CODEURL,
				DEPARTMENT.NAME AS DEPARTMENTNAME,
				PLITEMREVIEW.COMMENTS,
				PLITEMREVIEW.NOTREQUIRED,
				PLITEMREVIEW.COMPLETED,
				PLITEMREVIEW.PASSED,
				PLITEMREVIEW.PRIORITYORDER,
				PLITEMREVIEW.ASSIGNEDDATE,
				PLITEMREVIEW.DUEDATE,
				PLITEMREVIEW.COMPLETEDATE,
				PLITEMREVIEW.ASSIGNEDUSERID,
				USERS.FNAME,
				USERS.LNAME,
				PLITEMREVIEW.APPROVEDUSERID,
				PLITEMREVIEW.HASUNRESOLVEDCORRECTIONS,
				PLITEMREVIEW.LASTCHANGEDBY,
				PLITEMREVIEW.LASTCHANGEDON,
				PLITEMREVIEW.ROWVERSION,
				1 AS MODULEID
		FROM PLITEMREVIEW	
		INNER JOIN PLITEMREVIEWTYPE ON PLITEMREVIEWTYPE.PLITEMREVIEWTYPEID = PLITEMREVIEW.PLITEMREVIEWTYPEID
		INNER JOIN PLITEMREVIEWSTATUS ON PLITEMREVIEWSTATUS.PLITEMREVIEWSTATUSID = PLITEMREVIEW.PLITEMREVIEWSTATUSID
		LEFT OUTER JOIN DEPARTMENT ON DEPARTMENT.DEPARTMENTID = PLITEMREVIEWTYPE.DEPARTMENTID
		LEFT OUTER JOIN ERPROJECT ON ERPROJECT.PLPLANID = PLITEMREVIEW.PLPLANID
		INNER JOIN PLSUBMITTAL ON PLITEMREVIEW.PLSUBMITTALID = PLSUBMITTAL.PLSUBMITTALID
		INNER JOIN PLSUBMITTALTYPE ON PLSUBMITTALTYPE.PLSUBMITTALTYPEID = PLSUBMITTAL.PLSUBMITTALTYPEID		
		INNER JOIN USERS ON USERS.SUSERGUID = PLITEMREVIEW.ASSIGNEDUSERID
		WHERE (PLITEMREVIEW.PLITEMREVIEWID = @ItemReviewID)	
	END
	ELSE IF @ModuleID = 2
	BEGIN
	SELECT	DISTINCT PLITEMREVIEW.PLITEMREVIEWID,  
			PLITEMREVIEW.PMPERMITID AS CASEID,
			ERPROJECT.ERPROJECTID,
			PLSUBMITTALTYPE.TYPENAME AS SUBMITTALTYPENAME,
			PLITEMREVIEWSTATUS.PLITEMREVIEWSTATUSID,
			PLITEMREVIEWSTATUS.NAME AS STATUSNAME,
			PLITEMREVIEWTYPE.NAME AS ITEMREVIEWTYPENAME,
			PLITEMREVIEWTYPE.CODENAME AS CODENAME,
			PLITEMREVIEWTYPE.CODEURL AS CODEURL,
			DEPARTMENT.NAME AS DEPARTMENTNAME,
			PLITEMREVIEW.COMMENTS,
			PLITEMREVIEW.NOTREQUIRED,
			PLITEMREVIEW.COMPLETED,
			PLITEMREVIEW.PASSED,
			PLITEMREVIEW.PRIORITYORDER,
			PLITEMREVIEW.ASSIGNEDDATE,
			PLITEMREVIEW.DUEDATE,
			PLITEMREVIEW.COMPLETEDATE,
			PLITEMREVIEW.ASSIGNEDUSERID,
			USERS.FNAME,
			USERS.LNAME,
			PLITEMREVIEW.APPROVEDUSERID,
			PLITEMREVIEW.HASUNRESOLVEDCORRECTIONS,
			PLITEMREVIEW.LASTCHANGEDBY,
			PLITEMREVIEW.LASTCHANGEDON,
			PLITEMREVIEW.ROWVERSION,
			2 AS MODULEID
	FROM PLITEMREVIEW	
	INNER JOIN PLITEMREVIEWTYPE ON PLITEMREVIEWTYPE.PLITEMREVIEWTYPEID = PLITEMREVIEW.PLITEMREVIEWTYPEID
	INNER JOIN PLITEMREVIEWSTATUS ON PLITEMREVIEWSTATUS.PLITEMREVIEWSTATUSID = PLITEMREVIEW.PLITEMREVIEWSTATUSID
	LEFT OUTER JOIN DEPARTMENT ON DEPARTMENT.DEPARTMENTID = PLITEMREVIEWTYPE.DEPARTMENTID
	LEFT OUTER JOIN ERPROJECT ON ERPROJECT.PLPLANID = PLITEMREVIEW.PLPLANID
	INNER JOIN PLSUBMITTAL ON PLITEMREVIEW.PLSUBMITTALID = PLSUBMITTAL.PLSUBMITTALID
	INNER JOIN PLSUBMITTALTYPE ON PLSUBMITTALTYPE.PLSUBMITTALTYPEID = PLSUBMITTAL.PLSUBMITTALTYPEID		
	INNER JOIN USERS ON USERS.SUSERGUID = PLITEMREVIEW.ASSIGNEDUSERID
	WHERE (PLITEMREVIEW.PLITEMREVIEWID = @ItemReviewID)	
	END       
END