CREATE PROCEDURE GETMOBILECODECASEPARCELLIST
@CodeCaseId char(36)
AS
BEGIN
SELECT CMCODECASEPARCEL.CMCODECASEID, CMCODECASEPARCEL.CMCODECASEPARCELID, CMCODECASEPARCEL.PARCELID, CMCODECASEPARCEL.[PRIMARY],PARCEL.PARCELNUMBER, PARCEL.GISX, PARCEL.GISY FROM CMCODECASEPARCEL,PARCEL WHERE CMCODECASEID = @CodeCaseId AND PARCEL.PARCELID = CMCODECASEPARCEL.PARCELID ORDER BY PARCEL.PARCELNUMBER
END
