

CREATE PROCEDURE [dbo].[GETMYINBOXPLANLISTWITHLASTNDAYS]
-- Add the parameters for the stored procedure here
@AssignedUserID char(36),
@RoleID char(36)	,
@LastNDays int		
AS
BEGIN	
	SELECT	DISTINCT PLPLAN.PLPLANID,
			PLPLAN.PLANNUMBER,
			PLPLANTYPE.PLANNAME AS PLANTYPENAME,
			PLPLANWORKCLASS.NAME AS PLANWORKCLASSNAME,
			PLPLANSTATUS.NAME AS PLANSTATUSNAME,
			PLPLAN.DESCRIPTION AS PLANDESCRIPTION,
			PRPROJECT.NAME AS PROJECTNAME,
			DISTRICT.NAME AS DISTRICTNAME,
			ASSIGNEDUSER.FNAME,
			ASSIGNEDUSER.LNAME,
			PLPLAN.APPLICATIONDATE,
			PLPLAN.COMPLETEDATE,
			PLPLAN.EXPIREDATE,
			PLPLAN.APPROVALEXPIREDATE,
			PLPLAN.SQUAREFEET,
			PLPLAN.VALUE,
			PRPROJECT.PRPROJECTID
	FROM PLPLAN
	INNER JOIN PLITEMREVIEW	ON PLITEMREVIEW.PLPLANID = PLPLAN.PLPLANID	
	INNER JOIN USERS ON USERS.SUSERGUID = PLITEMREVIEW.ASSIGNEDUSERID
	LEFT OUTER JOIN USERS AS ASSIGNEDUSER ON ASSIGNEDUSER.SUSERGUID = PLPLAN.ASSIGNEDTO
	INNER JOIN PLPLANTYPE ON PLPLANTYPE.PLPLANTYPEID = PLPLAN.PLPLANTYPEID
	LEFT OUTER JOIN PLPLANWORKCLASS ON PLPLANWORKCLASS.PLPLANWORKCLASSID = PLPLAN.PLPLANWORKCLASSID
	INNER JOIN PLPLANSTATUS ON PLPLANSTATUS.PLPLANSTATUSID = PLPLAN.PLPLANSTATUSID
	OUTER APPLY (SELECT TOP 1 PRPROJECTID FROM PRPROJECTPLAN WHERE PRPROJECTPLAN.PLPLANID = PLPLAN.PLPLANID) A
	LEFT OUTER JOIN PRPROJECT ON PRPROJECT.PRPROJECTID = A.PRPROJECTID
	INNER JOIN DISTRICT ON DISTRICT.DISTRICTID = PLPLAN.DISTRICTID	
	LEFT OUTER JOIN ROLERECORDTYPEXREF ON ROLERECORDTYPEXREF.RECORDTYPEID = PLPLANTYPE.PLPLANTYPEID
	WHERE (PLITEMREVIEW.ASSIGNEDUSERID = @AssignedUserID) AND ((PLITEMREVIEW.COMPLETED=0) OR 
	(PLITEMREVIEW.COMPLETED =1 AND (PLITEMREVIEW.completedate= NULL OR DATEDIFF(DAY, PLITEMREVIEW.completedate,GETDATE()) <=@LastNDays))) AND
			(@RoleID is null OR @RoleID = '' OR (ROLERECORDTYPEXREF.ROLEID = @RoleID AND ROLERECORDTYPEXREF.VISIBLE = 1))      
END
