CREATE PROCEDURE GETMOBILEREQUESTPARCELLIST
@RequestId char(36)
AS
BEGIN
SELECT CITIZENREQUESTPARCEL.CITIZENREQUESTID, CITIZENREQUESTPARCEL.CITIZENREQUESTPARCELID, CITIZENREQUESTPARCEL.PARCELID, CITIZENREQUESTPARCEL.MAIN,PARCEL.PARCELNUMBER, PARCEL.GISX, PARCEL.GISY FROM CITIZENREQUESTPARCEL,PARCEL WHERE CITIZENREQUESTID = @RequestId AND  PARCEL.PARCELID = CITIZENREQUESTPARCEL.PARCELID ORDER BY PARCEL.PARCELNUMBER
END
