
CREATE PROCEDURE [dbo].[GETMOBILEREQUESTCONTACTLIST]
	@CitizenRequestId char(36)
	AS
	BEGIN
	SELECT	DISTINCT CITIZENREQUESTCALLERXREF.CITIZENREQUESTCALLERXREFID,
					GLOBALENTITY.GLOBALENTITYID,
					GLOBALENTITY.FIRSTNAME,	
					GLOBALENTITY.LASTNAME,	
					GLOBALENTITY.GLOBALENTITYNAME AS COMPANY,
					GLOBALENTITY.BUSINESSPHONE,
					GLOBALENTITY.HOMEPHONE,
					GLOBALENTITY.MOBILEPHONE,
					GLOBALENTITY.OTHERPHONE,
					GLOBALENTITY.EMAIL,
					CMCODECASECONTACTTYPE.CMCODECASECONTACTTYPEID,
					CMCODECASECONTACTTYPE.NAME AS CONTACTTYPE
			FROM	CITIZENREQUESTCALLERXREF
			INNER JOIN GLOBALENTITY ON GLOBALENTITY.GLOBALENTITYID = CITIZENREQUESTCALLERXREF.GLOBALENTITYID
			INNER JOIN CMCODECASECONTACTTYPE ON CMCODECASECONTACTTYPE.CMCODECASECONTACTTYPEID = CITIZENREQUESTCALLERXREF.CMCODECASECONTACTTYPEID 
			WHERE CITIZENREQUESTCALLERXREF.CITIZENREQUESTID = @CitizenRequestId	ORDER BY GLOBALENTITY.FIRSTNAME		
END

