CREATE PROCEDURE [dbo].[GETNOTIFICATIONITEMREVIEWLIST]
-- Add the parameters for the stored procedure here
@GlobalEntityID char(36)	
AS
BEGIN	
	SELECT	DISTINCT PLITEMREVIEW.PLITEMREVIEWID,  
			PLITEMREVIEW.PLPLANID AS CASEID,
			PLPLAN.PLANNUMBER AS CASENUMBER,	
			PLPLAN.APPLICATIONDATE,
			PLPLANWFACTIONSTEP.NAME AS SUBMITTALNAME,
			PLPLANWFACTIONSTEP.VERSIONNUMBER AS SUBMITTALVERSION,
			PLITEMREVIEWTYPE.NAME AS ITEMREVIEWTYPENAME,
			ERPROJECT.ERPROJECTID,
			1 AS MODULEID,
			'Plan' AS MODULENAME						
	FROM PLITEMREVIEW	
	INNER JOIN PLITEMREVIEWTYPE ON PLITEMREVIEWTYPE.PLITEMREVIEWTYPEID = PLITEMREVIEW.PLITEMREVIEWTYPEID		
	INNER JOIN PLSUBMITTAL ON PLITEMREVIEW.PLSUBMITTALID = PLSUBMITTAL.PLSUBMITTALID
	INNER JOIN PLPLANWFACTIONSTEP ON PLPLANWFACTIONSTEP.PLPLANWFACTIONSTEPID = PLSUBMITTAL.PLPLANWFACTIONSTEPID
	INNER JOIN PLPLAN ON PLPLAN.PLPLANID = PLITEMREVIEW.PLPLANID
	INNER JOIN COLLABORATION ON COLLABORATION.PLITEMREVIEWID = PLITEMREVIEW.PLITEMREVIEWID
	INNER JOIN PLPLANCONTACT ON PLPLANCONTACT.PLPLANID = PLPLAN.PLPLANID
	LEFT OUTER JOIN ERPROJECT ON ERPROJECT.PLPLANID = PLPLAN.PLPLANID
	WHERE (PLPLANCONTACT.GLOBALENTITYID = @GlobalEntityID)	
	UNION
	SELECT	DISTINCT PLITEMREVIEW.PLITEMREVIEWID,  
			PLITEMREVIEW.PMPERMITID AS CASEID,
			PMPERMIT.PERMITNUMBER AS CASENUMBER,	
			PMPERMIT.APPLYDATE AS APPLICATIONDATE,
			PMPERMITWFACTIONSTEP.NAME AS SUBMITTALNAME,
			PMPERMITWFACTIONSTEP.VERSIONNUMBER AS SUBMITTALVERSION,
			PLITEMREVIEWTYPE.NAME AS ITEMREVIEWTYPENAME,
			ERPROJECT.ERPROJECTID,
			2 AS MODULEID,
			'Permit' AS MODULENAME							
	FROM PLITEMREVIEW	
	INNER JOIN PLITEMREVIEWTYPE ON PLITEMREVIEWTYPE.PLITEMREVIEWTYPEID = PLITEMREVIEW.PLITEMREVIEWTYPEID		
	INNER JOIN PLSUBMITTAL ON PLITEMREVIEW.PLSUBMITTALID = PLSUBMITTAL.PLSUBMITTALID
	INNER JOIN PMPERMITWFACTIONSTEP ON PMPERMITWFACTIONSTEP.PMPERMITWFACTIONSTEPID = PLSUBMITTAL.PMPERMITWFACTIONSTEPID
	INNER JOIN PMPERMIT ON PMPERMIT.PMPERMITID = PLITEMREVIEW.PMPERMITID
	INNER JOIN COLLABORATION ON COLLABORATION.PLITEMREVIEWID = PLITEMREVIEW.PLITEMREVIEWID
	INNER JOIN PMPERMITCONTACT ON PMPERMITCONTACT.PMPERMITID = PMPERMIT.PMPERMITID
	LEFT OUTER JOIN ERPROJECT ON ERPROJECT.PLPLANID = PMPERMIT.PMPERMITID
	WHERE (PMPERMITCONTACT.GLOBALENTITYID = @GlobalEntityID)
	ORDER BY APPLICATIONDATE DESC
END