
CREATE PROCEDURE [dbo].[GETPTITEMREVIEWCOLLABLIST]
-- Add the parameters for the stored procedure here
@ItemReviewID char(36)	
AS
BEGIN	
	SELECT	DISTINCT COLLABORATION.COLLABORATIONID,  
			COLLABORATION.ERPROJECTID,
			COLLABORATION.PLITEMREVIEWID,			
			COLLABORATION.SUBJECT,
			COLLABORATION.MESSAGE,
			COLLABORATION.POSTBYUSER,
			USERS.FNAME AS POSTBYUSERFIRSTNAME,
			USERS.LNAME AS POSTBYUSERLASTNAME,
			COLLABORATION.POSTDATE,
			COLLABORATION.APPLICATIONID,
			COLLABORATION.MARKREAD				
	FROM COLLABORATION	
	INNER JOIN USERS ON USERS.SUSERGUID = COLLABORATION.POSTBYUSER				
	WHERE (COLLABORATION.PLITEMREVIEWID = @ItemReviewID)
	ORDER BY COLLABORATION.POSTDATE ASC	       
END
