CREATE PROCEDURE [dbo].[GETPTITEMREVIEWCORRECTIONLIST]
-- Add the parameters for the stored procedure here
@ItemReviewID char(36),
@ModuleID int	
AS
BEGIN	
	IF @ModuleID = 1
	BEGIN
		SELECT	DISTINCT PLPLANCORRECTION.PLPLANCORRECTIONID,  
				PLPLANCORRECTION.PLPLANID AS CASEID,
				PLPLANCORRECTION.PLITEMREVIEWID,			
				PLPLANCORRECTION.COMMENTS,
				PLPLANCORRECTIONTYPE.NAME AS CORRECTIONTYPENAME,
				PLPLANCORRECTION.CORRECTIVEACTION,
				ERPROJECTFILEVERSION.ERPROJECTFILEVERSIONID,
				ERPROJECTFILEVERSION.SAVEFILENAME,
				PLPLANCORRECTION.REPLIED,
				1 AS MODULEID,
				'Plan' AS MODULENAME								
		FROM PLPLANCORRECTION	
		INNER JOIN PLPLANCORRECTIONTYPE ON PLPLANCORRECTIONTYPE.PLPLANCORRECTIONTYPEID = PLPLANCORRECTION.PLPLANCORRECTIONTYPEID		
		LEFT OUTER JOIN ERPROJECTFILEVERSION ON ERPROJECTFILEVERSION.ERPROJECTFILEVERSIONID = PLPLANCORRECTION.ERPROJECTFILEVERSIONID				
		WHERE (PLPLANCORRECTION.PLITEMREVIEWID = @ItemReviewID AND ERPROJECTFILEVERSION.ALLOWVIEWCORRECTION = 1)	       
	END
	ELSE IF @ModuleID = 2
	BEGIN
		SELECT	DISTINCT PLPLANCORRECTION.PLPLANCORRECTIONID,  
				PLPLANCORRECTION.PMPERMITID AS CASEID,
				PLPLANCORRECTION.PLITEMREVIEWID,			
				PLPLANCORRECTION.COMMENTS,
				PLPLANCORRECTIONTYPE.NAME AS CORRECTIONTYPENAME,
				PLPLANCORRECTION.CORRECTIVEACTION,
				ERPROJECTFILEVERSION.ERPROJECTFILEVERSIONID,
				ERPROJECTFILEVERSION.SAVEFILENAME,
				PLPLANCORRECTION.REPLIED,
				2 AS MODULEID,
				'Permit' AS MODULENAME								
		FROM PLPLANCORRECTION	
		INNER JOIN PLPLANCORRECTIONTYPE ON PLPLANCORRECTIONTYPE.PLPLANCORRECTIONTYPEID = PLPLANCORRECTION.PLPLANCORRECTIONTYPEID		
		LEFT OUTER JOIN ERPROJECTFILEVERSION ON ERPROJECTFILEVERSION.ERPROJECTFILEVERSIONID = PLPLANCORRECTION.ERPROJECTFILEVERSIONID				
		WHERE (PLPLANCORRECTION.PLITEMREVIEWID = @ItemReviewID AND ERPROJECTFILEVERSION.ALLOWVIEWCORRECTION = 1)	
	END
END