

CREATE PROCEDURE [dbo].[GETPLANCONDITIONLIST]
-- Add the parameters for the stored procedure here
@PlanID char(36)	
AS
BEGIN	
	SELECT	DISTINCT PLPLANCONDITION.PLPLANCONDITIONID,
			PLPLANCONDITION.CONDITIONID,	
			PLPLANCONDITION.PLANID,	
			PLPLANCONDITION.ISSATISFIED,	
			PLPLANCONDITION.SCOPE,
			PLPLANCONDITION.CREATEDON			
	FROM	PLPLANCONDITION	
	WHERE PLPLANCONDITION.PLANID = @PlanID	
	ORDER BY CREATEDON DESC			
END
