
/*
EXEC rpt_GIS_SR_Avery_5160_Mailing_Labels 'START', 'END'
*/

CREATE PROCEDURE [dbo].rpt_GIS_SR_Avery_5160_Mailing_Labels
@LISTID AS VARCHAR(36)
AS

BEGIN

SELECT NAME1, NAME2, ADDRESS1, ADDRESS2, ADDRESS3, ADDRESS4, GISMAILINGRECIPIENTLISTRESULT.GISMAILINGRECIPIENTLISTID
FROM GISMAILINGRECIPIENTLISTRESULT
WHERE GISMAILINGRECIPIENTLISTRESULT.GISMAILINGRECIPIENTLISTID = @LISTID

END
