CREATE PROCEDURE [dbo].[USP_GISMAPLAYERXREF_UPDATE]
(
	@MAPLAYERSXREFID CHAR(36),
	@GISMAPLAYERID CHAR(36),
	@SUSERGUID CHAR(36),
	@SORTORDER INT,
	@DEFAULTACTIVE BIT
)
AS

UPDATE [dbo].[GISMAPLAYERXREF] SET
	[GISMAPLAYERID] = @GISMAPLAYERID,
	[SUSERGUID] = @SUSERGUID,
	[SORTORDER] = @SORTORDER,
	[DEFAULTACTIVE] = @DEFAULTACTIVE

WHERE
	[MAPLAYERSXREFID] = @MAPLAYERSXREFID