CREATE PROCEDURE [dbo].[USP_GLOBALENTITYACCOUNTTYPEGL_DELETE]
(
@GLOBALENTITYACCOUNTTYPEGLID CHAR(36)
)
AS
DELETE FROM [dbo].[GLOBALENTITYACCOUNTTYPEGL]
WHERE
	[GLOBALENTITYACCOUNTTYPEGLID] = @GLOBALENTITYACCOUNTTYPEGLID