CREATE PROCEDURE [dbo].[USP_GISMAILINGTEMPLATE_DELETE]
(
	@GISMAILINGTEMPLATEID CHAR(36),
	@ROWVERSION INT
)
AS
DELETE FROM [dbo].[GISMAILINGTEMPLATE]
WHERE
	[GISMAILINGTEMPLATEID] = @GISMAILINGTEMPLATEID AND 
	[ROWVERSION]= @ROWVERSION