CREATE PROCEDURE [dbo].[USP_GLOBALENTITYACCOUNTTYPEGL_INSERT]
(
	@GLOBALENTITYACCOUNTTYPEGLID CHAR(36),
	@GLOBALENTITYACCOUNTTYPEID CHAR(36),
	@DEBITGLACCOUNTID CHAR(36),
	@CREDITGLACCOUNTID CHAR(36),
	@CAPAYMENTTYPEID INT,
	@CAPAYMENTMETHODID CHAR(36)
)
AS

INSERT INTO [dbo].[GLOBALENTITYACCOUNTTYPEGL](
	[GLOBALENTITYACCOUNTTYPEGLID],
	[GLOBALENTITYACCOUNTTYPEID],
	[DEBITGLACCOUNTID],
	[CREDITGLACCOUNTID],
	[CAPAYMENTTYPEID],
	[CAPAYMENTMETHODID]
)

VALUES
(
	@GLOBALENTITYACCOUNTTYPEGLID,
	@GLOBALENTITYACCOUNTTYPEID,
	@DEBITGLACCOUNTID,
	@CREDITGLACCOUNTID,
	@CAPAYMENTTYPEID,
	@CAPAYMENTMETHODID
)