CREATE PROCEDURE [dbo].[USP_GISFEATURECLASS_INSERT]
(
	@GISFEATURECLASSID CHAR(36),
	@LAYERNUMBER INT,
	@ATTRIBUTEFIELD VARCHAR(50),
	@LAYERURL VARCHAR(200),
	@LAYERNAME VARCHAR(50),
	@ALIAS VARCHAR(50),
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
INSERT INTO [dbo].[GISFEATURECLASS](
	[GISFEATURECLASSID],
	[LAYERNUMBER],
	[ATTRIBUTEFIELD],
	[LAYERURL],
	[LAYERNAME],
	[ALIAS],
	[LASTCHANGEDBY],
	[LASTCHANGEDON],
	[ROWVERSION]
)
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
VALUES
(
	@GISFEATURECLASSID,
	@LAYERNUMBER,
	@ATTRIBUTEFIELD,
	@LAYERURL,
	@LAYERNAME,
	@ALIAS,
	@LASTCHANGEDBY,
	@LASTCHANGEDON,
	@ROWVERSION
)
SELECT * FROM @OUTPUTTABLE