CREATE PROCEDURE [dbo].[USP_GEOQUERY_INSERT]
(
	@GEOQUERYID CHAR(36),
	@QUERYNAME NVARCHAR(150),
	@FEATURECLASSNAME NVARCHAR(150),
	@FEATURECLASSID INT,
	@FIELDNAME NVARCHAR(150),
	@RETURNTYPE NVARCHAR(50),
	@RETURNEDFEATURECLASS NVARCHAR(150),
	@RETURNEDFEATURECLASSID INT,
	@GEOQUERYTYPEID CHAR(36),
	@RETURNFIELDNAME NVARCHAR(150),
	@RETURNFIELDTYPE NVARCHAR(50),
	@DISTANCE FLOAT(53),
	@GEOQUERYUNITTYPEID CHAR(36),
	@USEBUFFERRING BIT,
	@BUFFERFEATURECLASS NVARCHAR(150),
	@BUFFERFEATURECLASSID INT,
	@BUFFERGEOQUERYTYPEID CHAR(36),
	@APPLYSHAPEBUFFERING BIT,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
INSERT INTO [dbo].[GEOQUERY](
	[GEOQUERYID],
	[QUERYNAME],
	[FEATURECLASSNAME],
	[FEATURECLASSID],
	[FIELDNAME],
	[RETURNTYPE],
	[RETURNEDFEATURECLASS],
	[RETURNEDFEATURECLASSID],
	[GEOQUERYTYPEID],
	[RETURNFIELDNAME],
	[RETURNFIELDTYPE],
	[DISTANCE],
	[GEOQUERYUNITTYPEID],
	[USEBUFFERRING],
	[BUFFERFEATURECLASS],
	[BUFFERFEATURECLASSID],
	[BUFFERGEOQUERYTYPEID],
	[APPLYSHAPEBUFFERING],
	[LASTCHANGEDBY],
	[LASTCHANGEDON],
	[ROWVERSION]
)
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
VALUES
(
	@GEOQUERYID,
	@QUERYNAME,
	@FEATURECLASSNAME,
	@FEATURECLASSID,
	@FIELDNAME,
	@RETURNTYPE,
	@RETURNEDFEATURECLASS,
	@RETURNEDFEATURECLASSID,
	@GEOQUERYTYPEID,
	@RETURNFIELDNAME,
	@RETURNFIELDTYPE,
	@DISTANCE,
	@GEOQUERYUNITTYPEID,
	@USEBUFFERRING,
	@BUFFERFEATURECLASS,
	@BUFFERFEATURECLASSID,
	@BUFFERGEOQUERYTYPEID,
	@APPLYSHAPEBUFFERING,
	@LASTCHANGEDBY,
	@LASTCHANGEDON,
	@ROWVERSION
)
SELECT * FROM @OUTPUTTABLE