CREATE PROCEDURE [dbo].[USP_GISMAPLAYERXREF_INSERT]
(
	@MAPLAYERSXREFID CHAR(36),
	@GISMAPLAYERID CHAR(36),
	@SUSERGUID CHAR(36),
	@SORTORDER INT,
	@DEFAULTACTIVE BIT
)
AS

INSERT INTO [dbo].[GISMAPLAYERXREF](
	[MAPLAYERSXREFID],
	[GISMAPLAYERID],
	[SUSERGUID],
	[SORTORDER],
	[DEFAULTACTIVE]
)

VALUES
(
	@MAPLAYERSXREFID,
	@GISMAPLAYERID,
	@SUSERGUID,
	@SORTORDER,
	@DEFAULTACTIVE
)