CREATE PROCEDURE [dbo].[USP_GEOADDITEMREVIEW_DELETE_BYPROCESSID]
(
	@GEORULEPROCESSID CHAR(36)
)
AS
DELETE		[dbo].[GEOADDITEMREVIEW] FROM [dbo].[GEOADDITEMREVIEW]
INNER JOIN	[dbo].[GEORULEPROCESS]	ON [dbo].[GEORULEPROCESS].[GEORULEPROCESSID] = [dbo].[GEOADDITEMREVIEW].[GEORULEPROCESSID]
WHERE		[dbo].[GEORULEPROCESS].[GEORULEPROCESSID] =  @GEORULEPROCESSID