CREATE PROCEDURE [dbo].[USP_GISLLDATASOURCE_UPDATE]
(
	@GISLLDATASOURCEID CHAR(36),
	@ARCGISENDPOINT NVARCHAR(1000),
	@ARCGISLAYER VARCHAR(250),
	@USELIKEFORGIS BIT,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
UPDATE [dbo].[GISLLDATASOURCE] SET
	[ARCGISENDPOINT] = @ARCGISENDPOINT,
	[ARCGISLAYER] = @ARCGISLAYER,
	[USELIKEFORGIS] = @USELIKEFORGIS,
	[LASTCHANGEDBY] = @LASTCHANGEDBY,
	[LASTCHANGEDON] = @LASTCHANGEDON,
	[ROWVERSION] = @ROWVERSION + 1
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE
	[GISLLDATASOURCEID] = @GISLLDATASOURCEID AND 
	[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE