CREATE PROCEDURE [dbo].[USP_GET_ATTACHMENTGROUP_NAME]
	@ATTACHMENTID as varchar(36)
AS
BEGIN
	SELECT TOP 1 ISNULL([ATTACHMENTGROUP].[NAME],'') AS [NAME]
	FROM [ATTACHMENT]
	LEFT JOIN [ATTACHMENTGROUP] ON [ATTACHMENT].[ATTACHMENTGROUPID] = [ATTACHMENTGROUP].[ATTACHMENTGROUPID]
	WHERE [ATTACHMENT].[ATTACHMENTID] = @ATTACHMENTID
	   OR [ATTACHMENT].[TCMDOCID] = @ATTACHMENTID
END