CREATE PROCEDURE [dbo].[USP_GISZONEEXTERNALVALUE_DELETE]
(
@GISZONEEXTERNALVALUEID CHAR(36)
)
AS

DECLARE @GISZONEMAPPINGID CHAR(36)

SELECT @GISZONEMAPPINGID = [GISZONEMAPPINGID]
FROM   [dbo].[GISZONEEXTERNALVALUE] WHERE [GISZONEEXTERNALVALUEID] = @GISZONEEXTERNALVALUEID

EXEC [USP_GISZONETOINSPECTORDESIG_DELETE_BYPARENTID] @GISZONEMAPPINGID

DELETE FROM [dbo].[GISZONEEXTERNALVALUE]
WHERE
	[GISZONEEXTERNALVALUEID] = @GISZONEEXTERNALVALUEID