CREATE PROCEDURE [dbo].[USP_GISMAILINGTEMPLATE_UPDATE]
(
	@GISMAILINGTEMPLATEID CHAR(36),
	@NAME NVARCHAR(250),
	@DESCRIPTION NVARCHAR(500),
	@MAPSERVICEURL NVARCHAR(MAX),
	@FEATURECLASSNAME NVARCHAR(500),
	@NAME1 NVARCHAR(500),
	@NAME2 NVARCHAR(500),
	@ADDRESS1 NVARCHAR(500),
	@ADDRESS2 NVARCHAR(500),
	@ADDRESS3 NVARCHAR(500),
	@ADDRESS4 NVARCHAR(500),
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
UPDATE [dbo].[GISMAILINGTEMPLATE] SET
	[NAME] = @NAME,
	[DESCRIPTION] = @DESCRIPTION,
	[MAPSERVICEURL] = @MAPSERVICEURL,
	[FEATURECLASSNAME] = @FEATURECLASSNAME,
	[NAME1] = @NAME1,
	[NAME2] = @NAME2,
	[ADDRESS1] = @ADDRESS1,
	[ADDRESS2] = @ADDRESS2,
	[ADDRESS3] = @ADDRESS3,
	[ADDRESS4] = @ADDRESS4,
	[LASTCHANGEDBY] = @LASTCHANGEDBY,
	[LASTCHANGEDON] = @LASTCHANGEDON,
	[ROWVERSION] = @ROWVERSION + 1
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE
	[GISMAILINGTEMPLATEID] = @GISMAILINGTEMPLATEID AND 
	[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE