CREATE PROCEDURE [dbo].[USP_GEOFIELDMAPPINGTRANSLATE_DELETE]
(
@GEOFIELDMAPPINGTRANSLATEID CHAR(36)
)
AS
DELETE FROM [dbo].[GEOFIELDMAPPINGTRANSLATE]
WHERE
	[GEOFIELDMAPPINGTRANSLATEID] = @GEOFIELDMAPPINGTRANSLATEID