CREATE PROCEDURE [dbo].[USP_GEOFIELDMAPPINGTRANSLATE_UPDATE]
(
	@GEOFIELDMAPPINGTRANSLATEID CHAR(36),
	@GEOFIELDMAPPINGID CHAR(36),
	@GISATTRIBUTEVALUE NVARCHAR(MAX),
	@TRANSLATEDVALUE NVARCHAR(MAX)
)
AS

UPDATE [dbo].[GEOFIELDMAPPINGTRANSLATE] SET
	[GEOFIELDMAPPINGID] = @GEOFIELDMAPPINGID,
	[GISATTRIBUTEVALUE] = @GISATTRIBUTEVALUE,
	[TRANSLATEDVALUE] = @TRANSLATEDVALUE

WHERE
	[GEOFIELDMAPPINGTRANSLATEID] = @GEOFIELDMAPPINGTRANSLATEID