CREATE PROCEDURE [dbo].[USP_GISZONETOREVIEWITEMDESIG_INSERT]
(
	@GISZONETOREVIEWITEMDESIGID CHAR(36),
	@GISZONEREVIEWITEMVALUEID CHAR(36),
	@USERID CHAR(36),
	@PLITEMREVIEWTYPEID CHAR(36)	
)
AS

INSERT INTO [dbo].[GISZONETOREVIEWITEMDESIG](
	[GISZONETOREVIEWITEMDESIGID],
	[GISZONEREVIEWITEMVALUEID],
	[USERID],
	[PLITEMREVIEWTYPEID]	
)

VALUES
(
	@GISZONETOREVIEWITEMDESIGID,
	@GISZONEREVIEWITEMVALUEID,
	@USERID,
	@PLITEMREVIEWTYPEID
)