CREATE PROCEDURE [dbo].[USP_GISZONETOREVIEWITEMDESIG_DELETE]
(
	@GISZONETOREVIEWITEMDESIGID CHAR(36)	
)
AS
DELETE FROM [dbo].[GISZONETOREVIEWITEMDESIG]
WHERE
	[GISZONETOREVIEWITEMDESIGID] = @GISZONETOREVIEWITEMDESIGID