CREATE PROCEDURE [dbo].[USP_GEOFIELDMAPPINGTRANSLATE_DELETE_BYPROCESSID]
(
	@GEORULEPROCESSID CHAR(36)
)
AS
DELETE		[dbo].[GEOFIELDMAPPINGTRANSLATE] FROM [dbo].[GEOFIELDMAPPINGTRANSLATE]
INNER JOIN	[dbo].[GEOFIELDMAPPING]	ON [dbo].[GEOFIELDMAPPING].[GEOFIELDMAPPINGID] = [dbo].[GEOFIELDMAPPINGTRANSLATE].[GEOFIELDMAPPINGID]
INNER JOIN	[dbo].[GEORULEPROCESS]	ON [dbo].[GEORULEPROCESS].[GEORULEPROCESSID] = [dbo].[GEOFIELDMAPPING].[GEORULEPROCESSID]
WHERE		[dbo].[GEORULEPROCESS].[GEORULEPROCESSID] = @GEORULEPROCESSID