CREATE PROCEDURE [dbo].[USP_GISFEATURECLASSSEARCHFIELD_DELETE]
(
	@GISFEATURECLASSSEARCHFIELDID CHAR(36)
)
AS
DELETE FROM [dbo].[GISFEATURECLASSSEARCHFIELD]
WHERE [dbo].[GISFEATURECLASSSEARCHFIELD].[GISFEATURECLASSSEARCHFIELDID] = @GISFEATURECLASSSEARCHFIELDID