CREATE PROCEDURE [dbo].[USP_GEORULEPROCESS_DELETE]
(
	@GEORULEPROCESSID CHAR(36)
)
AS

EXEC [dbo].[USP_GEOFIELDMAPPINGTRANSLATE_DELETE_BYPROCESSID] @GEORULEPROCESSID
EXEC [dbo].[USP_GEOFIELDMAPPING_DELETE_BYPROCESSID] @GEORULEPROCESSID
EXEC [dbo].[USP_GEOADDITEMREVIEW_DELETE_BYPROCESSID] @GEORULEPROCESSID

DELETE FROM [dbo].[GEORULEPROCESS]
WHERE
	[GEORULEPROCESSID] = @GEORULEPROCESSID