CREATE PROCEDURE [common].[USP_USERSETTINGVALUES_GET]
	@USERID AS CHAR(36),
	@SETTINGNAMES AS RECORDNAMES READONLY
AS
BEGIN

SET NOCOUNT ON;

SELECT USERSETTINGVALUE.USERSETTINGVALUEID, USERSETTING.USERSETTINGID, USERSETTINGVALUE.STRINGVALUE, @USERID
FROM USERSETTINGVALUE
INNER JOIN USERSETTING ON USERSETTING.USERSETTINGID = USERSETTINGVALUE.USERSETTINGID
WHERE USERSETTINGVALUE.USERID = @USERID
AND USERSETTING.NAME IN (SELECT NAME FROM @SETTINGNAMES)

END