CREATE PROCEDURE [common].[USP_USERSETTINGVALUE_INSERT]
	@USERSETTINGVALUEID CHAR(36),
	@USERSETTINGID CHAR(36),
	@STRINGVALUE VARCHAR(MAX),
	@USERID CHAR(36)
AS

INSERT INTO USERSETTINGVALUE (USERSETTINGVALUEID, USERSETTINGID, USERID, STRINGVALUE)
VALUES (@USERSETTINGVALUEID, @USERSETTINGID, @USERID, @STRINGVALUE)