CREATE PROCEDURE [common].[USP_USERSETTINGVALUE_UPDATE]
	@USERSETTINGVALUEID CHAR(36),
	@STRINGVALUE VARCHAR(MAX)
AS


	UPDATE	USERSETTINGVALUE
	SET		STRINGVALUE = @STRINGVALUE
	WHERE	USERSETTINGVALUEID = @USERSETTINGVALUEID