CREATE PROCEDURE [common].[USP_BULKREQUEST_INSERT]
	@BULKREQUESTID CHAR(36),
	@BULKOBJECT VARCHAR(MAX),
	@REQUESTDATE DATETIME
AS
	
	INSERT INTO dbo.[BULKREQUEST](
		[BULKREQUESTID],
		[BULKOBJECT],
		[REQUESTDATE]
	) 
	VALUES (
		@BULKREQUESTID,
		@BULKOBJECT,
		@REQUESTDATE
	)