CREATE PROCEDURE [common].[USP_GETFORMATTEDFORMNAMES]
AS
WITH RAW_DATA AS (
		SELECT [dbo].[GETFORMATTEDFORMNAME](MENUS.SDESCRIPTION,SUBMENUS.SDESCRIPTION)
							+ '_' 
							+ SUBSTRING(SFORMNAME, LEN(SFORMNAME) - CHARINDEX('.', REVERSE(SFORMNAME)) + 2, CHARINDEX('.', REVERSE(SFORMNAME))) AS NAME, 
					   REPLACE(REPLACE(SCOMMONNAME,'Professional','Prof.'),'Management','Mgmt') AS SDESCRIPTION,
					   SFORMSGUID
							FROM FORMS 
								   INNER JOIN SUBMENUS ON SUBMENUS.SSUBMENUGUID = FORMS.FKSUBMENUGUID 
								   INNER JOIN MENUS ON MENUS.SMENUGUID = SUBMENUS.FKMENUGUID 
										WHERE ISNULL(IS_HTML_ACTIVE,0) = 0 AND SFORMNAME NOT LIKE '%GenericFormFrame%'
		UNION ALL
				SELECT  [dbo].[GETFORMATTEDFORMNAME](MENUS.SDESCRIPTION,SUBMENUS.SDESCRIPTION)
							+ '_'  
							+ REPLACE(REPLACE(HTML_COMMON_NAME, ' ', '_'), '&', '') AS NAME, 
					   REPLACE(REPLACE(SCOMMONNAME,'Professional','Prof.'),'Management','Mgmt') AS SDESCRIPTION,
					   SFORMSGUID 
						   FROM FORMS 
							  INNER JOIN SUBMENUS ON SUBMENUS.SSUBMENUGUID = FORMS.FKSUBMENUGUID 
							  INNER JOIN MENUS ON MENUS.SMENUGUID = SUBMENUS.FKMENUGUID 
									 WHERE IS_HTML_ACTIVE = 1 AND URL = '' AND SFORMNAME NOT LIKE '%GenericFormFrame%'
		 UNION ALL
				SELECT DISTINCT REPLACE(REPLACE(HTML_COMMON_NAME, ' ', '_'), '&', '') AS NAME,
					   REPLACE(HTML_COMMON_NAME, '&', 'and') AS SDESCRIPTION,
					   SFORMSGUID
						 FROM FORMS	WHERE IS_HTML_ACTIVE = 1 AND URL <> '' 
				 )  
				 

SELECT NAME,SDESCRIPTION,SFORMSGUID,ROW_NUMBER() OVER (ORDER BY NAME,SFORMSGUID) ROW_NUM 
FROM RAW_DATA  
ORDER BY ROW_NUM