CREATE PROCEDURE [common].[USP_BLCONTACTTYPESYSTEM_SELECT_LOOKUP]
AS
BEGIN
	SELECT 
		[dbo].[BLCONTACTTYPESYSTEM].[BLCONTACTTYPESYSTEMID],
		[dbo].[BLCONTACTTYPESYSTEM].[NAME]
	FROM  [dbo].[BLCONTACTTYPESYSTEM]
	ORDER BY [dbo].[BLCONTACTTYPESYSTEM].[NAME] ASC
END