CREATE PROCEDURE [common].[USP_IMINSPECTIONSTATUS_SELECT_LOOKUP]
AS
BEGIN
	SET NOCOUNT ON;
	SELECT  [dbo].[IMINSPECTIONSTATUS].[IMINSPECTIONSTATUSID],
			[dbo].[IMINSPECTIONSTATUS].[STATUSNAME] +' - '+ [dbo].[IMINSPECTIONLINK].NAME AS STATUSNAME			  
	FROM IMINSPECTIONSTATUS 
	LEFT JOIN IMINSPECTIONSTATUSENTITY	ON IMINSPECTIONSTATUS.IMINSPECTIONSTATUSENTITYID = IMINSPECTIONSTATUSENTITY.IMINSPECTIONSTATUSENTITYID
	LEFT JOIN IMINSPECTIONLINK ON IMINSPECTIONLINK.IMINSPECTIONLINKID = IMINSPECTIONSTATUSENTITY.IMINSPECTIONLINKID
	ORDER BY IMINSPECTIONSTATUS.STATUSNAME
END