CREATE PROCEDURE [common].[USP_IMINSPECTIONGISASSIGNMENT_SELECT_LOOKUP]
AS
BEGIN
	SET NOCOUNT ON;
	SELECT		[dbo].[IMINSPECTIONGISASSIGNMENT].[IMINSPECTIONGISASSIGNMENTID],
				[dbo].[IMINSPECTIONGISASSIGNMENT].[NAME]
	FROM		[dbo].[IMINSPECTIONGISASSIGNMENT]
	ORDER BY	[dbo].[IMINSPECTIONGISASSIGNMENT].[NAME]
END