CREATE PROCEDURE [common].[USP_WFACTIONSYSTEMTYPE_LOOKUP]
AS
SET NOCOUNT ON;
SELECT 
	[dbo].[WFACTIONSYSTEMTYPE].[WFACTIONSYSTEMTYPEID],
	[dbo].[WFACTIONSYSTEMTYPE].[NAME]
FROM [dbo].[WFACTIONSYSTEMTYPE]
ORDER BY [dbo].[WFACTIONSYSTEMTYPE].[NAME]