CREATE PROCEDURE [common].[USP_PMPERMITCAPAPPLICATIONTYPE_SELECT_LOOKUP]
AS
	SET NOCOUNT ON;
	SELECT 
		[dbo].[PMPERMITCAPAPPLICATIONTYPE].[PMPERMITCAPAPPLICATIONTYPEID],
		[dbo].[PMPERMITCAPAPPLICATIONTYPE].[NAME]
	FROM [dbo].[PMPERMITCAPAPPLICATIONTYPE]
	ORDER BY [dbo].[PMPERMITCAPAPPLICATIONTYPE].[NAME]