CREATE PROCEDURE [common].[USP_HISTORYSYSTEMSETUP_GETBYDISTINCTCOLUMNNAME]
(	
	@FORMID AS CHAR(36),
	@DISTINCTBYCOLUMN AS NVARCHAR(50) = '',
	@TIMEZONE_DIFFERENCE_IN_MINUTES AS FLOAT = 0
)
AS
BEGIN
	SELECT DISTINCT
		CASE
			WHEN @DISTINCTBYCOLUMN = 'ChangedOn' THEN CONVERT(NVARCHAR(MAX), DATEADD(MINUTE, @TIMEZONE_DIFFERENCE_IN_MINUTES, [dbo].[HISTORYSYSTEMSETUP].[CHANGEDON]), 101)
			WHEN @DISTINCTBYCOLUMN = 'User' THEN [dbo].[HISTORYSYSTEMSETUP].[CHANGEDBY]
			WHEN @DISTINCTBYCOLUMN = 'RecordChanged' THEN [dbo].[HISTORYSYSTEMSETUP].[RECORDNAME]
			WHEN @DISTINCTBYCOLUMN = 'Description' THEN [dbo].[HISTORYSYSTEMSETUP].[FIELDNAME]
			WHEN @DISTINCTBYCOLUMN = 'ActionType' THEN CONVERT(NVARCHAR(MAX), [dbo].[HISTORYSYSTEMSETUP].[ACTION])
		END AS COLUMNVALUE,
		CASE
			WHEN @DISTINCTBYCOLUMN = 'ChangedOn' THEN CONVERT(NVARCHAR(MAX), DATEADD(MINUTE, @TIMEZONE_DIFFERENCE_IN_MINUTES, [dbo].[HISTORYSYSTEMSETUP].[CHANGEDON]), 101)
			WHEN @DISTINCTBYCOLUMN = 'User' THEN ([dbo].[USERS].[LNAME] + COALESCE(', ' + [dbo].[USERS].[FNAME], ''))
			WHEN @DISTINCTBYCOLUMN = 'RecordChanged' THEN [dbo].[HISTORYSYSTEMSETUP].[RECORDNAME]
			WHEN @DISTINCTBYCOLUMN = 'Description' THEN [dbo].[HISTORYSYSTEMSETUP].[FIELDNAME]
			WHEN @DISTINCTBYCOLUMN = 'ActionType' THEN
				CASE
					WHEN [dbo].[HISTORYSYSTEMSETUP].[ACTION] = 1 THEN 'Added' 
					WHEN [dbo].[HISTORYSYSTEMSETUP].[ACTION] = 2 THEN 'Changed' 
					WHEN [dbo].[HISTORYSYSTEMSETUP].[ACTION] = 3 THEN 'Deleted' 
				END
		END AS COLUMNDATA
	FROM [dbo].[HISTORYSYSTEMSETUP]
	INNER JOIN [dbo].[USERS] ON [dbo].[USERS].[SUSERGUID] = [dbo].[HISTORYSYSTEMSETUP].[CHANGEDBY]
	WHERE [dbo].[HISTORYSYSTEMSETUP].[FORMID] = @FORMID
END