CREATE PROCEDURE [common].[USP_IMINSPECTIONCASEADDRESS_GETBYIDS]
(
	@INSPECTIONCASELIST RecordIDs READONLY
)
AS
BEGIN
	SELECT 
		[IMINSPECTIONCASEADDRESS].IMINSPECTIONCASEID,
		[IMINSPECTIONCASEADDRESS].IMINSPECTIONCASEADDRESSID, 
		[MAILINGADDRESS].ADDRESSLINE1,
		[MAILINGADDRESS].ADDRESSLINE2,
		[MAILINGADDRESS].ADDRESSLINE3,
		[MAILINGADDRESS].ADDRESSTYPE,
		[MAILINGADDRESS].ATTN,
		[MAILINGADDRESS].CITY,
		[MAILINGADDRESS].COMPSITE,
		[MAILINGADDRESS].COUNTRY,
		[MAILINGADDRESSCOUNTRYTYPE].MAILINGADDRESSCOUNTRYTYPEID,
		[MAILINGADDRESSCOUNTRYTYPE].MAILINGADDRESSCOUNTRYTYPENAME,
		[IMINSPECTIONCASEADDRESS].MAIN,
		[MAILINGADDRESS].POBOX,
		[MAILINGADDRESS].POSTALCODE,
		[MAILINGADDRESS].POSTDIRECTION,
		[MAILINGADDRESS].PREDIRECTION,
		[MAILINGADDRESS].PROVINCE,
		[MAILINGADDRESS].RURALROUTE,
		[MAILINGADDRESS].STATE,
		[MAILINGADDRESS].STATION,
		[MAILINGADDRESS].STREETTYPE,
		[MAILINGADDRESS].UNITORSUITE,
		[MAILINGADDRESS].ADDRESSID
	FROM [IMINSPECTIONCASEADDRESS] 
	INNER JOIN [MAILINGADDRESS] ON [IMINSPECTIONCASEADDRESS].MAILINGADDRESSID = [MAILINGADDRESS].MAILINGADDRESSID
	INNER JOIN [MAILINGADDRESSCOUNTRYTYPE] ON MAILINGADDRESS.COUNTRYTYPE = [MAILINGADDRESSCOUNTRYTYPE].MAILINGADDRESSCOUNTRYTYPEID
	INNER JOIN @INSPECTIONCASELIST INSPECTIONCASELIST ON [IMINSPECTIONCASEADDRESS].IMINSPECTIONCASEID = INSPECTIONCASELIST.RECORDID
	WHERE [IMINSPECTIONCASEADDRESS].MAIN = 1
END