CREATE PROCEDURE [common].[USP_GLOBALENTITY_SEARCH]
(
	@SEARCH				AS NVARCHAR(MAX)	=	'',
	@PAGE_NUMBER		AS INT				=	1,
	@PAGE_SIZE			AS INT				=	10,
	@IS_ASCENDING		AS BIT				=	1,
	@ACTIVEENTITYONLY	AS BIT				=	1,
	@IS_COMPANY			AS BIT				=	1,
	@IS_CONTACT			AS BIT				=	1
)
AS
WITH RAW_DATA AS (
	SELECT	[dbo].[GLOBALENTITY].[GLOBALENTITYID],
			[dbo].[GLOBALENTITY].[GLOBALENTITYNAME],
			[dbo].[GLOBALENTITY].[FIRSTNAME],
			[dbo].[GLOBALENTITY].[LASTNAME],
			[dbo].[GLOBALENTITY].[LASTNAME] + COALESCE(', ' + [dbo].[GLOBALENTITY].[FIRSTNAME], '') AS [FULLNAME],
			[dbo].[GLOBALENTITY].[EMAIL],
			CASE @IS_ASCENDING WHEN 1 THEN
				ROW_NUMBER() OVER(ORDER BY [dbo].[GLOBALENTITY].[GLOBALENTITYNAME], [dbo].[GLOBALENTITY].[FIRSTNAME], [dbo].[GLOBALENTITY].[LASTNAME])
			ELSE
				ROW_NUMBER() OVER(ORDER BY [dbo].[GLOBALENTITY].[GLOBALENTITYNAME], [dbo].[GLOBALENTITY].[FIRSTNAME], [dbo].[GLOBALENTITY].[LASTNAME] DESC)
			END AS RowNumber,
			COUNT(1) OVER() AS TotalRows,
			[dbo].[GLOBALENTITY].[CONTACTID],
			[dbo].[GLOBALENTITY].[ISACTIVE],
			[dbo].[GLOBALENTITY].[BUSINESSPHONE],
			[dbo].[GLOBALENTITY].[HOMEPHONE],
			[dbo].[GLOBALENTITY].[MOBILEPHONE],
			[dbo].[GLOBALENTITY].[OTHERPHONE],
			[dbo].[GLOBALENTITY].[FAX],
			[dbo].[GLOBALENTITY].[TITLE],			
			[dbo].[MAILINGADDRESS].[MAILINGADDRESSID],
			[dbo].[MAILINGADDRESS].[ADDRESSLINE1],
			[dbo].[MAILINGADDRESS].[ADDRESSLINE2],
			[dbo].[MAILINGADDRESS].[ADDRESSLINE3],
			[dbo].[MAILINGADDRESS].[CITY],
			[dbo].[MAILINGADDRESS].[STATE],
			[dbo].[MAILINGADDRESS].[POSTALCODE],
			[dbo].[MAILINGADDRESS].[COUNTRYTYPE],	
			[dbo].[MAILINGADDRESS].[POSTDIRECTION],
			[dbo].[MAILINGADDRESS].[PREDIRECTION],
			[dbo].[MAILINGADDRESS].[ADDRESSID],
			[dbo].[MAILINGADDRESS].[ADDRESSTYPE],
			[dbo].[MAILINGADDRESS].[STREETTYPE],
			[dbo].[MAILINGADDRESS].[UNITORSUITE],
			[dbo].[MAILINGADDRESS].[PROVINCE],
			[dbo].[MAILINGADDRESS].[RURALROUTE],
			[dbo].[MAILINGADDRESS].[STATION],
			[dbo].[MAILINGADDRESS].[COMPSITE],
			[dbo].[MAILINGADDRESS].[POBOX],
			[dbo].[MAILINGADDRESS].[ATTN],
			[dbo].[MAILINGADDRESS].[GENERALDELIVERY]
	FROM	[dbo].[GLOBALENTITY]		
			LEFT JOIN (SELECT TOP 1 GLOBALENTITYID, MAILINGADDRESSID FROM GLOBALENTITYMAILINGADDRESS					
					ORDER BY [GLOBALENTITYMAILINGADDRESS].[MAIN] DESC ) AS MailingAddressTable
				ON [GLOBALENTITY].[GLOBALENTITYID] = [MailingAddressTable].[GLOBALENTITYID]
			LEFT JOIN [MAILINGADDRESS] ON [MAILINGADDRESS].[MAILINGADDRESSID] = [MailingAddressTable].[MAILINGADDRESSID]	
	WHERE	(ISACTIVE = 1 OR ISACTIVE = @ACTIVEENTITYONLY)
			AND ([dbo].[GLOBALENTITY].[GLOBALENTITYNAME] LIKE '%'+ @SEARCH +'%'
				OR [dbo].[GLOBALENTITY].[FIRSTNAME] LIKE '%'+ @SEARCH +'%'
				OR [dbo].[GLOBALENTITY].[LASTNAME] LIKE '%'+ @SEARCH +'%'
				OR [dbo].[GLOBALENTITY].[EMAIL] LIKE '%'+ @SEARCH +'%'
				OR ([dbo].[GLOBALENTITY].[FIRSTNAME] + ' ' + [dbo].[GLOBALENTITY].[LASTNAME]) LIKE '%'+ @SEARCH +'%')
			AND ((@IS_COMPANY = 1 AND @IS_CONTACT = 1 AND [dbo].[GLOBALENTITY].[ISCOMPANY] = @IS_COMPANY AND [dbo].[GLOBALENTITY].[ISCONTACT] = @IS_CONTACT)
					OR (@IS_COMPANY = 1 AND @IS_CONTACT != 1 AND [dbo].[GLOBALENTITY].[ISCOMPANY] = @IS_COMPANY)
					OR (@IS_COMPANY != 1 AND @IS_CONTACT = 1 AND [dbo].[GLOBALENTITY].[ISCONTACT] = @IS_CONTACT)
					OR (@IS_COMPANY != 1 AND @IS_CONTACT != 1))
)
SELECT *
FROM RAW_DATA
WHERE
	RowNumber > @PAGE_SIZE * (@PAGE_NUMBER - 1) AND
	RowNumber <= @PAGE_SIZE * @PAGE_NUMBER
ORDER BY
	RowNumber