CREATE PROCEDURE [common].[USP_NOTIFICATIONS_INSERT]
(
	@NOTIFICATIONSID CHAR(36),
	@SUBJECT NVARCHAR(MAX),
	@BODY NVARCHAR(MAX),
	@UNIQUERECORDID CHAR(36),
	@FORMID CHAR(36)
)
AS

INSERT INTO [dbo].[NOTIFICATIONS](
	[NOTIFICATIONSID],
	[SUBJECT],
	[BODY],
	[UNIQUERECORDID],
	[FORMID]
)

VALUES
(
	@NOTIFICATIONSID,
	@SUBJECT,
	@BODY,
	@UNIQUERECORDID,
	@FORMID
)