CREATE PROCEDURE [common].[USP_ADDRESSLAYOUTSETUP_SELECT_LOOKUP]
AS
BEGIN
	SET NOCOUNT ON;
	SELECT		[dbo].[ADDRESSLAYOUTSETUP].[ADDRESSLAYOUTSETUPID],
				[dbo].[ADDRESSLAYOUTSETUP].[COUNTRYID],
				[dbo].[ADDRESSLAYOUTSETUP].[KEYTEXTBLOCKNAME],
				[dbo].[ADDRESSLAYOUTSETUP].[KEYCONTROLNAME],
				[dbo].[ADDRESSLAYOUTSETUP].[KEYBINDINGPROPERTYNAME],
				[dbo].[ADDRESSLAYOUTSETUP].[DEFAULTLABEL],
				[dbo].[ADDRESSLAYOUTSETUP].[NEWLABEL],
				[dbo].[ADDRESSLAYOUTSETUP].[DEFAULTTABINDEX],
				[dbo].[ADDRESSLAYOUTSETUP].[NEWTABINDEX],
				[dbo].[ADDRESSLAYOUTSETUP].[ISHIDE]
	FROM		[dbo].[ADDRESSLAYOUTSETUP]
	ORDER BY	[dbo].[ADDRESSLAYOUTSETUP].[DEFAULTTABINDEX]
END