CREATE PROCEDURE [common].[USP_SYSTEMTASKTYPEWORKCLASS_INSERT]
(
	@SYSTEMTASKTYPEWORKCLASSID CHAR(36),
	@SYSTEMTASKTYPEID INT,
	@PMPERMITTYPEWORKCLASSID CHAR(36),
	@PLPLANTYPEWORKCLASSID CHAR(36),
	@ACTIVE BIT,
	@BACKOFFICEORIGIN BIT,
	@ONLINEORIGIN BIT,
	@OTHERSOURCEORIGIN BIT,
	@DAYSUNTILDUE INT,
	@ASSIGNTOOBJECT INT,
	@TEAMASSIGNEDTOID CHAR(36),
	@DEFAULTASSIGNEDTOID CHAR(36),
	@UPDATEDBYID CHAR(36),
	@UPDATEDON DATETIME
)
AS

INSERT INTO [dbo].[SYSTEMTASKTYPEWORKCLASS](
	[SYSTEMTASKTYPEWORKCLASSID],
	[SYSTEMTASKTYPEID],
	[PMPERMITTYPEWORKCLASSID],
	[PLPLANTYPEWORKCLASSID],
	[ACTIVE],
	[BACKOFFICEORIGIN],
	[ONLINEORIGIN],
	[OTHERSOURCEORIGIN],
	[DAYSUNTILDUE],
	[ASSIGNTOOBJECT],
	[TEAMASSIGNEDTOID],
	[DEFAULTASSIGNEDTOID],
	[UPDATEDBYID],
	[UPDATEDON]
)

VALUES
(
	@SYSTEMTASKTYPEWORKCLASSID,
	@SYSTEMTASKTYPEID,
	@PMPERMITTYPEWORKCLASSID,
	@PLPLANTYPEWORKCLASSID,
	@ACTIVE,
	@BACKOFFICEORIGIN,
	@ONLINEORIGIN,
	@OTHERSOURCEORIGIN,
	@DAYSUNTILDUE,
	@ASSIGNTOOBJECT,
	@TEAMASSIGNEDTOID,
	@DEFAULTASSIGNEDTOID,
	@UPDATEDBYID,
	@UPDATEDON
)