CREATE PROCEDURE [common].[USP_IMINSPECTIONCATEGORY_SELECT_LOOKUP]
AS
BEGIN
	SET NOCOUNT ON;
	SELECT		[dbo].[IMINSPECTIONCATEGORY].[IMINSPECTIONCATEGORYID],
				[dbo].[IMINSPECTIONCATEGORY].[NAME],
				[dbo].[IMINSPECTIONCATEGORY].[CATEGORYLIMIT]
	FROM		[dbo].[IMINSPECTIONCATEGORY]
	ORDER BY	[dbo].[IMINSPECTIONCATEGORY].[NAME]
END