CREATE PROCEDURE [common].[USP_CMCODECATEGORY_SELECT_LOOKUP]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[CMCODECATEGORY].[CMCODECATEGORYID],
	[dbo].[CMCODECATEGORY].[NAME]
FROM [dbo].[CMCODECATEGORY] 
ORDER BY [dbo].[CMCODECATEGORY].[NAME] 
END