CREATE PROCEDURE [common].[USP_GISMAP_SELECT_LOOKUP]
AS
BEGIN
	SET NOCOUNT ON;
	SELECT		[dbo].[GISMAP].[GMAPID],
				[dbo].[GISMAP].[SMAPNAME]
	FROM		[dbo].[GISMAP]
	ORDER BY	[dbo].[GISMAP].[SMAPNAME]
END