CREATE PROCEDURE [common].[USP_ATTACHMENTGROUP_SELECT_LOOKUP_GETALL]
AS
SET NOCOUNT ON;
SELECT	
	[dbo].[ATTACHMENTGROUP].[ATTACHMENTGROUPID],
	[dbo].[ATTACHMENTGROUP].[NAME]
FROM [dbo].[ATTACHMENTGROUP]
ORDER BY [dbo].[ATTACHMENTGROUP].[NAME]