CREATE PROCEDURE [globalsetup].[USP_WFACTION_GETBYID]
(
	@WFACTIONID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[WFACTION].[WFACTIONID],
	[dbo].[WFACTION].[NAME],
	[dbo].[WFACTION].[DESCRIPTION],
	[dbo].[WFACTION].[WFACTIONTYPEID],
	[dbo].[WFACTION].[PASSDESCRIPTION],
	[dbo].[WFACTION].[FAILDESCRIPTION],
	[dbo].[WFACTION].[ALLOWREDO],
	[dbo].[WFACTION].[REDODESCRIPTION],
	[dbo].[WFACTION].[ICON],
	[dbo].[WFACTION].[DAYSTOCOMPLETE],
	[dbo].[WFACTION].[PLSUBMITTALTYPEID],
	[dbo].[WFACTION].[MEETINGTYPEID],
	[dbo].[WFACTION].[HEARINGTYPEID],
	[dbo].[WFACTION].[WORKFLOWCOMPLETETYPEID],
	[dbo].[WFACTION].[IMINSPECTIONTYPEID],
	[dbo].[WFACTION].[PLPLANTYPEID],
	[dbo].[WFACTION].[PLPLANWORKCLASSID],
	[dbo].[WFACTION].[PMPERMITTYPEID],
	[dbo].[WFACTION].[PMPERMITWORKCLASSID],
	[dbo].[WFACTION].[PLPLANACTIVITYTYPEID],
	[dbo].[WFACTION].[PMPERMITACTIVITYTYPEID],
	[dbo].[WFACTION].[CMCODEACTIVITYTYPEID],
	[dbo].[WFACTION].[RPTREPORTID],
	[dbo].[WFACTION].[RPTFRMTOBUSOBJMAPID],
	[dbo].[WFACTION].[BLLICENSETYPEID],
	[dbo].[WFACTION].[BLLICENSECLASSID],
	[dbo].[WFACTION].[BLLICENSEACTIVITYTYPEID],
	[dbo].[WFACTION].[TASKTYPEID],
	[dbo].[WFACTION].[CMCODEID],
	[dbo].[WFACTION].[IMINSPECTIONCASETYPEID],
	[dbo].[WFACTION].[ILLICENSEACTIVITYTYPEID],
	[dbo].[WFACTION].[EXAMTYPEID],
	[dbo].[WFACTION].[CAFEETEMPLATEID],
	[dbo].[WFACTION].[ISAUTOINVOICE],
	[dbo].[WFACTION].[ISREQUIREDFULLPAYMNENT],
	[dbo].[WFACTION].[OMOBJECTTYPEID],
	[dbo].[WFACTION].[OMOBJECTCLASSIFICATIONID],
	[dbo].[WFACTION].[COMPUTEFEEACTIONTYPEID],
	[dbo].[WFACTION].[ISUSEACTIONDATEASFEEDATE],
	[dbo].[WFACTION].[ISCOMPUTEMAINFEETEMPLATE],
	[dbo].[WFACTION].[CMCASETYPEID],
	[dbo].[WFACTION].[WKOTYPEID],
	[dbo].[WFACTION].[WKOTYPENAME],
	[dbo].[WFACTION].[WKOCLASSID],
	[dbo].[WFACTION].[WKOCLASSNAME],
	[dbo].[WFACTION].[LASTCHANGEDBY],
	[dbo].[WFACTION].[LASTCHANGEDON],
	[dbo].[WFACTION].[ROWVERSION],
	[dbo].[CMCODE].[CODENUMBER]
FROM [dbo].[WFACTION]
LEFT JOIN [dbo].[CMCODE] on [dbo].[CMCODE].[CMCODEID] = [dbo].[WFACTION].[CMCODEID]
WHERE
	[dbo].[WFACTION].[WFACTIONID] = @WFACTIONID  

END