CREATE PROCEDURE [globalsetup].[USP_IMNONCOMPLIANCERISK_SELECT_LOOKUP]
	AS
	SET NOCOUNT ON;
SELECT 
	[dbo].[IMNONCOMPLIANCERISK].[IMNONCOMPLIANCERISKID],
	[dbo].[IMNONCOMPLIANCERISK].[NAME]
FROM [dbo].[IMNONCOMPLIANCERISK]
ORDER BY [dbo].[IMNONCOMPLIANCERISK].[NAME]