CREATE PROCEDURE [globalsetup].[USP_PLITEMREVIEWSTATUS_SELECT_LOOKUP]
AS

SET NOCOUNT ON;
SELECT		[dbo].[PLITEMREVIEWSTATUS].[PLITEMREVIEWSTATUSID],
			[dbo].[PLITEMREVIEWSTATUS].[NAME]
FROM		[dbo].[PLITEMREVIEWSTATUS]
ORDER BY	[dbo].[PLITEMREVIEWSTATUS].[NAME]