CREATE PROCEDURE [globalsetup].[USP_IMCHECKLIST_SEARCH]
(
	@SEARCH AS NVARCHAR(MAX) = '',
	@PAGE_NUMBER AS INT = 1,
	@PAGE_SIZE AS INT = 10,
	@IS_ASCENDING AS BIT = 1
)
AS
WITH RAW_DATA AS (
	SELECT
		[dbo].[IMCHECKLIST].[IMCHECKLISTID],
		[dbo].[IMCHECKLIST].[NAME],
		[dbo].[IMCHECKLIST].[DESCRIPTION],		
		[dbo].[IMCHECKLISTCATEGORY].[NAME] AS [CHECKLISTCATEGORYNAME],		
		CASE @IS_ASCENDING WHEN 1 THEN
			ROW_NUMBER() OVER(ORDER BY [dbo].[IMCHECKLIST].[NAME])
		ELSE
			ROW_NUMBER() OVER(ORDER BY [dbo].[IMCHECKLIST].[NAME] DESC)
		END AS RowNumber,
		COUNT(1) OVER() AS TotalRows
	FROM [dbo].[IMCHECKLIST]
	LEFT join [dbo].[IMCHECKLISTCATEGORY] on [dbo].[IMCHECKLIST].[IMCHECKLISTCATEGORYID] = [dbo].[IMCHECKLISTCATEGORY].[IMCHECKLISTCATEGORYID]
	WHERE ([dbo].[IMCHECKLIST].[NAME] LIKE '%'+ @SEARCH +'%' 
	OR [dbo].[IMCHECKLIST].[DESCRIPTION] LIKE '%'+ @SEARCH +'%' 
	OR [dbo].[IMCHECKLISTCATEGORY].[NAME] LIKE '%'+ @SEARCH +'%')
)

SELECT * 
FROM RAW_DATA
WHERE
	RowNumber > @PAGE_SIZE * (@PAGE_NUMBER - 1) AND 
	RowNumber <= @PAGE_SIZE * @PAGE_NUMBER
ORDER BY 
	RowNumber