CREATE PROCEDURE [globalsetup].[USP_IMINSPECTIONCALENDAR_IMINSPECTIONCALHOLIDAY_GETBYPARENTID]
(
	@PARENTID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[IMINSPECTIONCALHOLIDAY].[IMINSPECTIONCALHOLIDAYID],
	[dbo].[IMINSPECTIONCALHOLIDAY].[IMINSPECTIONCALENDARID],
	[dbo].[IMINSPECTIONCALHOLIDAY].[NAME],
	[dbo].[IMINSPECTIONCALHOLIDAY].[HOLIDAYDATE]
FROM [dbo].[IMINSPECTIONCALHOLIDAY]
WHERE
	[dbo].[IMINSPECTIONCALHOLIDAY].[IMINSPECTIONCALENDARID] = @PARENTID  
ORDER BY
	[dbo].[IMINSPECTIONCALHOLIDAY].[NAME]
END