CREATE PROCEDURE [globalsetup].[USP_TYLERCASHIERINGTENDERTYPEUPDATEQUEUE_INSERT]
(
	@PAYMENTMETHODID CHAR(36) = NULL,
	@TENDERTYPEID INT = NULL,
	@PROCESSEDDATE DATETIME = NULL,
	@SUCCESS BIT = NULL,
	@SENTTOBUS BIT = NULL
)
AS
INSERT INTO [dbo].[TYLERCASHIERINGTENDERTYPEUPDATEQUEUE](
	[PAYMENTMETHODID],
	[TENDERTYPEID],
	[PROCESSEDDATE],
	[SUCCESS],
	[SENTTOBUS]
)
VALUES
(
	@PAYMENTMETHODID,
	@TENDERTYPEID,
	@PROCESSEDDATE,
	@SUCCESS,
	@SENTTOBUS
)