CREATE PROCEDURE [globalsetup].[USP_SERVICETASK_GET_NAME_BYSERVICETASKID]
(
	@SERVICETASKID	INT
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[SERVICETASK].[SERVICETASKID],
	[dbo].[SERVICETASK].[NAME]
FROM [dbo].[SERVICETASK]
WHERE
	[dbo].[SERVICETASK].[SERVICETASKID] = @SERVICETASKID
END