CREATE PROCEDURE [globalsetup].[USP_CUSTOMFIELDWORKSHEETITEM_GETBYFIELDID]
(
	@GCUSTOMFIELD CHAR(36)
)
AS
BEGIN
	SET NOCOUNT ON;
	SELECT 
		[dbo].[CUSTOMFIELDWORKSHEETITEM].[GCUSTOMFIELDWORKSHEETITEM],
		[dbo].[CUSTOMFIELDWORKSHEETITEM].[SVALUE],
		[dbo].[CUSTOMFIELDWORKSHEETITEM].[IORDER]
	FROM [dbo].[CUSTOMFIELDWORKSHEETITEM]
	INNER JOIN [dbo].[CUSTOMFIELDWORKSHEET] ON [dbo].[CUSTOMFIELDWORKSHEET].[GCUSTOMFIELDWORKSHEET] = [dbo].[CUSTOMFIELDWORKSHEETITEM].[FKGCUSTOMFIELDWORKSHEET]
	WHERE
		[dbo].[CUSTOMFIELDWORKSHEET].[FKGCUSTOMFIELD] = @GCUSTOMFIELD  
	ORDER BY
		[dbo].[CUSTOMFIELDWORKSHEETITEM].[IORDER]
END