CREATE PROCEDURE [globalsetup].[USP_CUSTOMFIELDTABLE_SELECT_BY_ID_LOOKUP]
(
	@ID CHAR(36)
)
AS
BEGIN
	SET NOCOUNT ON;
	SELECT 
		[dbo].[CUSTOMFIELDTABLE].[CUSTOMFIELDTABLEID],
		[dbo].[CUSTOMFIELDTABLE].[NAME],
		[dbo].[CUSTOMFIELDTABLE].[REQUIRED],
		[dbo].[CUSTOMFIELDTABLE].[DEFAULTROWNUM],
		[dbo].[CUSTOMFIELDTABLE].[SHOWONMOBILE],
		[dbo].[CUSTOMFIELDTABLE].[ISEDITINMOBILE],
		[dbo].[CUSTOMFIELDTABLE].[TOOLTIP]
	FROM [dbo].[CUSTOMFIELDTABLE]
	WHERE [dbo].[CUSTOMFIELDTABLE].[CUSTOMFIELDTABLEID] = @ID

	EXEC [globalsetup].[USP_CUSTOMFIELDTABLECOLUMNREF_SELECT_BYPARENTID_LOOKUP] @ID
END