CREATE PROCEDURE [globalsetup].[USP_WFACTIONGROUPACTIONXREF_GETALL]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[WFACTIONGROUPACTIONXREF].[WFACTIONGROUPACTIONXREFID],
	[dbo].[WFACTIONGROUPACTIONXREF].[WFACTIONGROUPID],
	[dbo].[WFACTION].[NAME],
	[dbo].[WFACTIONGROUPACTIONXREF].[WFACTIONID],
	[dbo].[WFACTIONGROUPACTIONXREF].[PRIORITYORDER],
	[dbo].[WFACTIONGROUPACTIONXREF].[SORTORDER],
	[dbo].[WFACTIONGROUPACTIONXREF].[AUTOFILL],
	[dbo].[WFACTIONGROUPACTIONXREF].[AUTORECEIVE]
FROM [dbo].[WFACTIONGROUPACTIONXREF]
JOIN [dbo].[WFACTION]
ON [dbo].[WFACTIONGROUPACTIONXREF].[WFACTIONID] = [dbo].[WFACTION].[WFACTIONID]
END