CREATE PROCEDURE [globalsetup].[USP_CAPRORATESCHEDULERATES_GETALL]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[CAPRORATESCHEDULERATES].[CAPRORATESCHEDULERATESID],
	[dbo].[CAPRORATESCHEDULERATES].[CAPRORATESCHEDULEID],
	[dbo].[CAPRORATESCHEDULERATES].[STARTDATE],
	[dbo].[CAPRORATESCHEDULERATES].[ENDDATE],
	[dbo].[CAPRORATESCHEDULERATES].[RATES]
FROM [dbo].[CAPRORATESCHEDULERATES]
ORDER BY
	[dbo].[CAPRORATESCHEDULERATES].[STARTDATE]
END