CREATE PROCEDURE [globalsetup].[USP_DYNAMIC_ACCOUNT_SQL_UDF_LOOKUP]
AS
	SET NOCOUNT ON;
SELECT    
    ROUTINE_SCHEMA + '.' + ROUTINE_NAME [FUNCTIONNAME]
FROM
    INFORMATION_SCHEMA.ROUTINES 
WHERE
    ROUTINE_TYPE = 'FUNCTION'
AND
	ROUTINE_SCHEMA = 'cashieringsetup'
ORDER BY ROUTINE_NAME