CREATE PROCEDURE [globalsetup].[USP_IMINSPECTORTYPEINSPECTIONTYPE_GETALL]
AS
BEGIN

SET NOCOUNT ON;

SELECT 
	[dbo].[IMINSPECTORTYPEINSPECTIONTYPE].[IMINSPECTORTYPEID],
	[dbo].[IMINSPECTORTYPEINSPECTIONTYPE].[IMINSPECTIONTYPEID],
	[dbo].[IMINSPECTIONTYPE].[NAME]
FROM [dbo].[IMINSPECTORTYPEINSPECTIONTYPE]

INNER JOIN [dbo].[IMINSPECTIONTYPE]
ON [dbo].[IMINSPECTIONTYPE].[IMINSPECTIONTYPEID] = [dbo].[IMINSPECTORTYPEINSPECTIONTYPE].[IMINSPECTIONTYPEID]

ORDER BY [dbo].[IMINSPECTIONTYPE].[NAME] ASC

END