CREATE PROCEDURE [globalsetup].[USP_WFENTITY_STEPTYPE_GETBYENTITYID]
(
	@WFENTITYID AS INT
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
		[dbo].[WFSTEPTYPE].[WFSTEPTYPEID],
		[dbo].[WFSTEPTYPE].[NAME]
FROM [dbo].[WFSTEPTYPE]
JOIN [dbo].[WFENTITYSTEPTYPE] ON [dbo].[WFSTEPTYPE].[WFSTEPTYPEID] = [dbo].[WFENTITYSTEPTYPE].[WFSTEPTYPEID]
WHERE [WFENTITYID] = @WFENTITYID
ORDER BY [dbo].[WFSTEPTYPE].[NAME]
END