CREATE PROCEDURE [globalsetup].[USP_COLICTYPECLASSREF_GETALL]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[COLICTYPECLASSREF].[COLICTYPEID],
	[dbo].[COLICTYPECLASSREF].[CLASSIFICATIONID],
	[dbo].[ILLICENSECLASSIFICATION].[NAME]
FROM
	[dbo].[COLICTYPECLASSREF]
INNER JOIN 
	[dbo].[ILLICENSECLASSIFICATION] ON [dbo].[ILLICENSECLASSIFICATION].[ILLICENSECLASSIFICATIONID] = [dbo].[COLICTYPECLASSREF].[CLASSIFICATIONID]
ORDER BY 
	[dbo].[ILLICENSECLASSIFICATION].[NAME]
END