CREATE PROCEDURE [globalsetup].[USP_WFSTEP_GETALL_BY_CRITERIA]
(
	@WFSTEPIDs AS [dbo].[RecordIDs] READONLY,
	@WFENTITYID AS INT
)
AS
BEGIN
SET NOCOUNT ON;
SELECT		
			[dbo].[WFSTEP].[WFSTEPID],
			[dbo].[WFSTEP].[NAME],
			[dbo].[WFSTEP].[DESCRIPTION],
			[dbo].[WFSTEPTYPE].[WFSTEPTYPEID],
			[dbo].[WFSTEPTYPE].[NAME] [TYPENAME]
FROM	
			[dbo].[WFSTEP]
INNER JOIN 
			[dbo].[WFSTEPTYPE] ON [dbo].[WFSTEP].[WFSTEPTYPEID] = [dbo].[WFSTEPTYPE].[WFSTEPTYPEID]
INNER JOIN
			[dbo].[WFENTITYSTEPTYPE] ON [dbo].[WFENTITYSTEPTYPE].[WFSTEPTYPEID] = [dbo].[WFSTEP].[WFSTEPTYPEID]
WHERE	
			[dbo].[WFSTEP].[WFSTEPID] IN (SELECT [RECORDID] FROM @WFSTEPIDs) AND [dbo].[WFENTITYSTEPTYPE].[WFENTITYID] = @WFENTITYID

EXEC [globalsetup].[USP_WORKFLOWGROUPACTION_GETALL_BY_WFENTITY] @WFENTITYID
END