CREATE PROCEDURE [globalsetup].[USP_CASCHEDULE_GETALL]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[CASCHEDULE].[CASCHEDULEID],
	[dbo].[CASCHEDULE].[NAME],
	[dbo].[CASCHEDULE].[DESCRIPTION],
	[dbo].[CASCHEDULE].[STARTDATE],
	[dbo].[CASCHEDULE].[ENDDATE],
	[dbo].[CASCHEDULE].[IGNOREYEAR],
	[dbo].[CASCHEDULE].[LASTCHANGEDBY],
	[dbo].[CASCHEDULE].[LASTCHANGEDON],
	[dbo].[CASCHEDULE].[ROWVERSION]
FROM 
	[dbo].[CASCHEDULE]
ORDER BY	
	[dbo].[CASCHEDULE].[NAME] 
END