CREATE PROCEDURE [globalsetup].[USP_CAMODULE_SELECT_LOOKUP]
AS
SET NOCOUNT ON;
SELECT		[dbo].[CAMODULE].[CAMODULEID],
			[dbo].[CAMODULE].[NAME],
			[dbo].[CAMODULE].[ISHTMLDEPRICATED]
FROM		[dbo].[CAMODULE]
ORDER BY	[dbo].[CAMODULE].[NAME]