CREATE PROCEDURE [globalsetup].[USP_ILLICENSESTATUS_SELECT_LOOKUP]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[ILLICENSESTATUSID],
	[NAME]	
FROM [dbo].[ILLICENSESTATUS]
ORDER BY [dbo].[ILLICENSESTATUS].[NAME]
END