CREATE PROCEDURE [globalsetup].[USP_CAPRORATIONMODEL_SELECT_LOOKUP]
AS
SET NOCOUNT ON;
SELECT		[dbo].[CAPRORATIONMODEL].[CAPRORATIONMODELID],
			[dbo].[CAPRORATIONMODEL].[NAME]
FROM		[dbo].[CAPRORATIONMODEL]
ORDER BY	[dbo].[CAPRORATIONMODEL].[NAME]