CREATE PROCEDURE [globalsetup].[USP_ILLICENSEACTIVITYTYPE_SELECT_LOOKUP]
AS
	SET NOCOUNT ON;
	SELECT		[dbo].[ILLICENSEACTIVITYTYPE].[ILLICENSEACTIVITYTYPEID],
				[dbo].[ILLICENSEACTIVITYTYPE].[NAME]
	FROM		[dbo].[ILLICENSEACTIVITYTYPE]
	ORDER BY	[dbo].[ILLICENSEACTIVITYTYPE].[NAME]