CREATE PROCEDURE [globalsetup].[USP_CUSTOMFIELDCOLUMNTEMPLATE_GETBYID]
(
	@CUSTOMFIELDCOLUMNTEMPLATEID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;

	SELECT 
		[dbo].[CUSTOMFIELDCOLUMNTEMPLATE].[CUSTOMFIELDCOLUMNTEMPLATEID],
		[dbo].[CUSTOMFIELDCOLUMNTEMPLATE].[FKCUSTOMFIELDLAYOUTCONTROLTYPE],
		[dbo].[CUSTOMFIELDCOLUMNTEMPLATE].[GCUSTOMFIELD],
		[dbo].[CUSTOMFIELDCOLUMNTEMPLATE].[SCOLUMNNAME],
		[dbo].[CUSTOMFIELDCOLUMNTEMPLATE].[SDESCRIPTION],
		[dbo].[CUSTOMFIELDCOLUMNTEMPLATE].[SFIELDTIP],
		[dbo].[CUSTOMFIELDCOLUMNTEMPLATE].[LASTCHANGEDBY],
		[dbo].[CUSTOMFIELDCOLUMNTEMPLATE].[LASTCHANGEDON],
		[dbo].[CUSTOMFIELDCOLUMNTEMPLATE].[ROWVERSION],
		[dbo].[CUSTOMFIELD].[FKICUSTOMFIELDTYPE],
		[dbo].[CUSTOMFIELD].[SFIELDNAME],
		[dbo].[CUSTOMFIELD].[SCUSTOMFIELD],
		[dbo].[CUSTOMFIELD].[BISPICKLIST],
		[dbo].[CUSTOMFIELD].[BISWORKSHEET],
		[dbo].[CUSTOMFIELD].[FKGCUSTOMFIELDTEMPLATE],
		[dbo].[CUSTOMFIELD].[FKCUSTOMFIELDTABLE],
		[dbo].[CUSTOMFIELD].[FKCUSTOMFIELDTABLECOLREF],
		[dbo].[CUSTOMFIELD].[COLUMNOPERATOR],
		[dbo].[CUSTOMFIELDPICKLIST].[GCUSTOMFIELDPICKLIST],
		[dbo].[CUSTOMFIELDPICKLIST].[BALLOWMULTIPLESELECTIONS],
		[dbo].[CUSTOMFIELDTEMPLATE].[TEMPLATENAME]
	FROM [dbo].[CUSTOMFIELDCOLUMNTEMPLATE]
			INNER JOIN [dbo].[CUSTOMFIELD]
					ON [dbo].[CUSTOMFIELDCOLUMNTEMPLATE].[GCUSTOMFIELD] = [dbo].[CUSTOMFIELD].[GCUSTOMFIELD]
			LEFT JOIN [dbo].[CUSTOMFIELDPICKLIST]
					ON [dbo].[CUSTOMFIELDCOLUMNTEMPLATE].[GCUSTOMFIELD] = [dbo].[CUSTOMFIELDPICKLIST].[FKGCUSTOMFIELD]
			LEFT JOIN [dbo].[CUSTOMFIELDTEMPLATE]
					ON [dbo].[CUSTOMFIELDTEMPLATE].[GCUSTOMFIELDTEMPLATE] = [dbo].[CUSTOMFIELD].[FKGCUSTOMFIELDTEMPLATE]
	WHERE
		[dbo].[CUSTOMFIELDCOLUMNTEMPLATE].[CUSTOMFIELDCOLUMNTEMPLATEID] = @CUSTOMFIELDCOLUMNTEMPLATEID  

	EXEC [globalsetup].[USP_CUSTOMFIELDPICKLISTITEM_GETBYCUSTOMFIELDCOLUMNTEMPLATEID] @CUSTOMFIELDCOLUMNTEMPLATEID

END