CREATE PROCEDURE [globalsetup].[USP_RPCONTACTTYPE_GETALL]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[RPCONTACTTYPE].[RPCONTACTTYPEID],
	[dbo].[RPCONTACTTYPE].[NAME],
	[dbo].[RPCONTACTTYPE].[DESCRIPTION],
	[dbo].[RPCONTACTTYPE].[RPCONTACTTYPESYSTEMID],
	[dbo].[RPCONTACTTYPE].[REQUIREDVALIDLIC],
	[dbo].[RPCONTACTTYPE].[LASTCHANGEDBY],
	[dbo].[RPCONTACTTYPE].[LASTCHANGEDON],
	[dbo].[RPCONTACTTYPE].[ROWVERSION]
FROM 
	[dbo].[RPCONTACTTYPE]
ORDER BY 
	[dbo].[RPCONTACTTYPE].[NAME]
END