CREATE PROCEDURE [globalsetup].[USP_CAFEEADJUSTABLECALC_GETBYPARENTID]
(
	@PARENTID CHAR(36)
)
AS
BEGIN
	SET NOCOUNT ON;
	SELECT 
		[dbo].[CAFEEADJUSTABLECALC].[CAFEEADJUSTABLECALCID],
		[dbo].[CAFEEADJUSTABLECALC].[CAFEEID],
		[dbo].[CAFEEADJUSTABLECALC].[LOWERLIMIT],
		[dbo].[CAFEEADJUSTABLECALC].[UPPERLIMIT],
		[dbo].[CAFEEADJUSTABLECALC].[UNLIMITED],
		[dbo].[CAFEEADJUSTABLECALC].[AMOUNT],
		[dbo].[CAFEEADJUSTABLECALC].[ADDITIONALAMOUNT],
		[dbo].[CAFEEADJUSTABLECALC].[ADDITIONALUNIT],
		[dbo].[CAFEEADJUSTABLECALC].[OVER],
		[dbo].[CAFEEADJUSTABLECALC].[CAFEESETUPID]
	FROM [dbo].[CAFEEADJUSTABLECALC]
	WHERE [dbo].[CAFEEADJUSTABLECALC].[CAFEEID] = @PARENTID
END