CREATE PROCEDURE [globalsetup].[USP_CAPRORATESCHEDULE_GETALL]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[CAPRORATESCHEDULE].[CAPRORATESCHEDULEID],
	[dbo].[CAPRORATESCHEDULE].[NAME],
	[dbo].[CAPRORATESCHEDULE].[DESCRIPTION],
	[dbo].[CAPRORATESCHEDULE].[LASTCHANGEDBY],
	[dbo].[CAPRORATESCHEDULE].[LASTCHANGEDON],
	[dbo].[CAPRORATESCHEDULE].[ROWVERSION]
FROM [dbo].[CAPRORATESCHEDULE]
ORDER BY
	[dbo].[CAPRORATESCHEDULE].[NAME]
	
EXEC [globalsetup].[USP_CAPRORATESCHEDULERATES_GETALL] 
END