CREATE PROCEDURE [globalsetup].[USP_IMINSPECTIONCATEGORY_GETALL]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[IMINSPECTIONCATEGORY].[IMINSPECTIONCATEGORYID],
	[dbo].[IMINSPECTIONCATEGORY].[NAME],
	[dbo].[IMINSPECTIONCATEGORY].[CATEGORYLIMIT],
	[dbo].[IMINSPECTIONCATEGORY].[LASTCHANGEDBY],
	[dbo].[IMINSPECTIONCATEGORY].[LASTCHANGEDON],
	[dbo].[IMINSPECTIONCATEGORY].[ROWVERSION]
FROM [dbo].[IMINSPECTIONCATEGORY]
 ORDER BY [dbo].[IMINSPECTIONCATEGORY].[NAME] ASC

 EXEC [globalsetup].[USP_IMINSPECTIONCATEGORYXREF_GETALL]

END