CREATE PROCEDURE [globalsetup].[USP_PLSUBMITTALSTATUS_GETALL]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[PLSUBMITTALSTATUS].[PLSUBMITTALSTATUSID],
	[dbo].[PLSUBMITTALSTATUS].[NAME],
	[dbo].[PLSUBMITTALSTATUS].[DESCRIPTION],
	[dbo].[PLSUBMITTALSTATUS].[SUCCESSFLAG],
	[dbo].[PLSUBMITTALSTATUS].[FAILUREFLAG],
	[dbo].[PLSUBMITTALSTATUS].[DESCRIPTION_SPANISH],
	[dbo].[PLSUBMITTALSTATUS].[NOTREQUIREDFLAG],
	[dbo].[PLSUBMITTALSTATUS].[LASTCHANGEDBY],
	[dbo].[PLSUBMITTALSTATUS].[LASTCHANGEDON],
	[dbo].[PLSUBMITTALSTATUS].[ROWVERSION]
FROM [dbo].[PLSUBMITTALSTATUS]
ORDER BY [dbo].[PLSUBMITTALSTATUS].[NAME] ASC
END