CREATE PROCEDURE [globalsetup].[USP_BONDINTERESTSCHEDULE_GETBYID]
(
	@BONDINTERESTSCHEDULEID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[BONDINTERESTSCHEDULE].[BONDINTERESTSCHEDULEID],
	[dbo].[BONDINTERESTSCHEDULE].[NAME],
	[dbo].[BONDINTERESTSCHEDULE].[DESCRIPTION],
	[dbo].[BONDINTERESTSCHEDULE].[ISCOMPOUNDINTEREST],
	[dbo].[BONDINTERESTSCHEDULE].[INTERESTMETHODID],
	[dbo].[BONDINTERESTSCHEDULE].[CAFEEID],
	[dbo].[BONDINTERESTSCHEDULE].[CHARGECODE],
	[dbo].[BONDINTERESTSCHEDULE].[LASTCHANGEDBY],
	[dbo].[BONDINTERESTSCHEDULE].[LASTCHANGEDON],
	[dbo].[BONDINTERESTSCHEDULE].[ROWVERSION],
	[dbo].[BONDINTERESTSCHEDULE].[JURISDICTIONID]
FROM [dbo].[BONDINTERESTSCHEDULE]
WHERE
	[dbo].[BONDINTERESTSCHEDULE].[BONDINTERESTSCHEDULEID] = @BONDINTERESTSCHEDULEID  
	
	EXEC [globalsetup].[USP_BONDINTERESTRATE_GETBYPARENTID] @BONDINTERESTSCHEDULEID
	EXEC [globalsetup].[USP_BONDGLACCOUNTXREF_GETBYPARENTID] @BONDINTERESTSCHEDULEID

END