CREATE PROCEDURE [globalsetup].[USP_HEARINGTYPEDATTENDEE_GETBYPARENTID]
(
@PARENTID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[HEARINGTYPEDATTENDEE].[HEARINGTYPEDATTENDEEID],
	[dbo].[HEARINGTYPEDATTENDEE].[HEARINGTYPEID],
	[dbo].[HEARINGTYPEDATTENDEE].[ATTENDEEID],
	[dbo].[HEARINGTYPEDATTENDEE].[ISUSER],
	[dbo].[HEARINGTYPEDATTENDEE].[ISCONTACT],
	[COMPANYNAME] = ISNULL([dbo].[GLOBALENTITY].[GLOBALENTITYNAME], ''),
	ISNULL([dbo].[GLOBALENTITY].[LASTNAME], [dbo].[USERS].[LNAME]) + COALESCE(', ' + ISNULL([dbo].[GLOBALENTITY].[FIRSTNAME], [dbo].[USERS].[FNAME]), '') AS [FULLNAME]
FROM [dbo].[HEARINGTYPEDATTENDEE]
LEFT JOIN [dbo].[GLOBALENTITY] WITH (NOLOCK) ON [dbo].[GLOBALENTITY].[GLOBALENTITYID] = [dbo].[HEARINGTYPEDATTENDEE].[ATTENDEEID]
LEFT JOIN [dbo].[USERS] WITH (NOLOCK) ON [dbo].[USERS].[SUSERGUID] = [dbo].[HEARINGTYPEDATTENDEE].[ATTENDEEID]
WHERE [dbo].[HEARINGTYPEDATTENDEE].[HEARINGTYPEID] = @PARENTID
ORDER BY ISNULL([dbo].[GLOBALENTITY].[FIRSTNAME], [dbo].[USERS].[FNAME])

END