CREATE PROCEDURE [globalsetup].[USP_CUSTOMFIELDTEMPLATEITEM_GETBYPARENTID]
(
	@GCUSTOMFIELDTEMPLATE CHAR(36)
)
AS
BEGIN
	SET NOCOUNT ON;
	SELECT 
		[dbo].[CUSTOMFIELDTEMPLATEITEM].[GCUSTOMFIELDTEMPLATEITEM],
		[dbo].[CUSTOMFIELDTEMPLATEITEM].[FKGCUSTOMFIELDTEMPLATE],
		[dbo].[CUSTOMFIELDTEMPLATEITEM].[SVALUE],
		[dbo].[CUSTOMFIELDTEMPLATEITEM].[IORDER],
		[dbo].[CUSTOMFIELDTEMPLATEITEM].[ISRETIRE]
	FROM [dbo].[CUSTOMFIELDTEMPLATEITEM]
			INNER JOIN [dbo].[CUSTOMFIELDTEMPLATE] 
						ON [dbo].[CUSTOMFIELDTEMPLATEITEM].[FKGCUSTOMFIELDTEMPLATE] = [dbo].[CUSTOMFIELDTEMPLATE].[GCUSTOMFIELDTEMPLATE]
	WHERE
		[dbo].[CUSTOMFIELDTEMPLATE].[GCUSTOMFIELDTEMPLATE] = @GCUSTOMFIELDTEMPLATE  
    ORDER BY 
	    [dbo].[CUSTOMFIELDTEMPLATEITEM].[IORDER], [dbo].[CUSTOMFIELDTEMPLATEITEM].[SVALUE]  
END