CREATE PROCEDURE [globalsetup].[USP_RPLANDLORDLICENSESTATUS_SELECT_LOOKUP]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[RPLANDLORDLICENSESTATUSID],
	[NAME]	
FROM [dbo].[RPLANDLORDLICENSESTATUS]
ORDER BY [dbo].[RPLANDLORDLICENSESTATUS].[NAME]
END