CREATE PROCEDURE [globalsetup].[USP_IMINSPECTIONCALENDAR_IMINSPECTIONCALAMPM_GETBYPARENTID]
(
	@PARENTID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[IMINSPECTIONCALAMPM].[IMINSPECTIONCALAMPMID],
	[dbo].[IMINSPECTIONCALAMPM].[AMPMTIMEID],
	[dbo].[IMINSPECTIONCALAMPM].[STARTTIME],
	[dbo].[IMINSPECTIONCALAMPM].[ENDTIME],
	[dbo].[IMINSPECTIONCALAMPM].[IMINSPECTIONCALENDARID]
FROM [dbo].[IMINSPECTIONCALAMPM]
WHERE
	[dbo].[IMINSPECTIONCALAMPM].[IMINSPECTIONCALENDARID] = @PARENTID 
ORDER BY 
	[dbo].[IMINSPECTIONCALAMPM].[AMPMTIMEID]
END