CREATE PROCEDURE [globalsetup].[USP_IMNONCOMPLIANCECATEGORY_SELECT_LOOKUP]
	AS
	SET NOCOUNT ON;
SELECT 
	[dbo].[IMNONCOMPLIANCECATEGORY].[IMNONCOMPLIANCECATEGORYID],
	[dbo].[IMNONCOMPLIANCECATEGORY].[NAME]
FROM [dbo].[IMNONCOMPLIANCECATEGORY]
ORDER BY [dbo].[IMNONCOMPLIANCECATEGORY].[NAME]