CREATE PROCEDURE [globalsetup].[USP_WFACTIONGROUPACTIONXREF_DELETE_BYPARENTID]
(
	@WFACTIONGROUPID CHAR(36)
)
AS
DELETE FROM [dbo].[WFACTIONGROUPACTIONXREF]
WHERE [dbo].[WFACTIONGROUPACTIONXREF].[WFACTIONGROUPID] = @WFACTIONGROUPID