CREATE PROCEDURE [globalsetup].[USP_CAFEETIMETRACKINGTYPEXREF_GETBYPARENTID]
(
	@PARENTID CHAR(36)
)
AS
BEGIN
	SET NOCOUNT ON;
	SELECT  
		[dbo].[CAFEETIMETRACKINGTYPEXREF].[CAFEETIMETRACKINGTYPEXREFID],
		[dbo].[CAFEETIMETRACKINGTYPEXREF].[CAFEEID],
		[dbo].[TIMETRACKINGTYPE].[TIMETRACKINGTYPEID],
		[dbo].[TIMETRACKINGTYPE].[NAME],
		[dbo].[TIMETRACKINGMODULE].[MODULEID]
	FROM [dbo].[CAFEETIMETRACKINGTYPEXREF]
	INNER JOIN [dbo].[TIMETRACKINGTYPE] ON [dbo].[TIMETRACKINGTYPE].[TIMETRACKINGTYPEID] = [dbo].[CAFEETIMETRACKINGTYPEXREF].[TIMETRACKINGTYPEID]
	INNER JOIN [dbo].[TIMETRACKINGMODULE] ON [dbo].[TIMETRACKINGMODULE].[MODULEID] = [dbo].[TIMETRACKINGTYPE].[MODULEID]
	WHERE [dbo].[CAFEETIMETRACKINGTYPEXREF].[CAFEEID] = @PARENTID
	ORDER BY [dbo].[TIMETRACKINGTYPE].[NAME]
END