CREATE PROCEDURE [globalsetup].[USP_ILLICENSECLASSIFICATION_GETALL]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[ILLICENSECLASSIFICATION].[ILLICENSECLASSIFICATIONID],
	[dbo].[ILLICENSECLASSIFICATION].[NAME],
	[dbo].[ILLICENSECLASSIFICATION].[DESCRIPTION],
	[dbo].[ILLICENSECLASSIFICATION].[LASTCHANGEDBY],
	[dbo].[ILLICENSECLASSIFICATION].[LASTCHANGEDON],
	[dbo].[ILLICENSECLASSIFICATION].[ROWVERSION]
FROM [dbo].[ILLICENSECLASSIFICATION] ORDER BY [dbo].[ILLICENSECLASSIFICATION].[NAME]
END