CREATE PROCEDURE [globalsetup].[USP_IMNONCOMPLIANCECODE_GETBYID]
(
	@IMNONCOMPLIANCECODEID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[IMNONCOMPLIANCECODE].[IMNONCOMPLIANCECODEID],
	[dbo].[IMNONCOMPLIANCECODE].[IMNONCOMPLIANCECATEGORYID],
	[dbo].[IMNONCOMPLIANCECODE].[DEFAULTRESPONSIBLEPARTYID],
	[dbo].[IMNONCOMPLIANCECODE].[DEFAULTNONCOMPLIANCERISKID],
	[dbo].[IMNONCOMPLIANCECODE].[COMPLIANCEDAYSUNTILDUE],
	[dbo].[IMNONCOMPLIANCECODE].[NAME],
	[dbo].[IMNONCOMPLIANCECODE].[DESCRIPTION],
	[dbo].[IMNONCOMPLIANCECODE].[LASTCHANGEDBY],
	[dbo].[IMNONCOMPLIANCECODE].[LASTCHANGEDON],
	[dbo].[IMNONCOMPLIANCECODE].[ROWVERSION]
FROM [dbo].[IMNONCOMPLIANCECODE]
WHERE
	[dbo].[IMNONCOMPLIANCECODE].[IMNONCOMPLIANCECODEID] = @IMNONCOMPLIANCECODEID  

EXEC [globalsetup].[USP_IMNONCOMPLIANCECODEREVISION_GETBYPARENTID] @IMNONCOMPLIANCECODEID

END