CREATE PROCEDURE [globalsetup].[USP_CAFEETEMPLATECHILDXREF_GETBYPARENTID]
	@CAFEETEMPLATEID CHAR(36)
AS
BEGIN
SET NOCOUNT ON;
	
	SELECT	[dbo].[CAFEETEMPLATECHILDXREF].[CAFEETEMPLATECHILDXREFID],
			[dbo].[CAFEETEMPLATECHILDXREF].[PARENTFEETEMPLATEID],
			[dbo].[CAFEETEMPLATECHILDXREF].[CHILDFEETEMPLATEID],
			[dbo].[CAFEETEMPLATE].[CAFEETEMPLATENAME],
			[dbo].[CAFEETEMPLATECHILDXREF].[CHILDORDER],
			[dbo].[CAFEETEMPLATECHILDXREF].[CACONDITIONGROUPID]
	FROM	[dbo].[CAFEETEMPLATECHILDXREF]
	INNER JOIN [dbo].[CAFEETEMPLATE] ON [dbo].[CAFEETEMPLATE].[CAFEETEMPLATEID] = [dbo].[CAFEETEMPLATECHILDXREF].[CHILDFEETEMPLATEID]
	WHERE	[dbo].[CAFEETEMPLATECHILDXREF].[PARENTFEETEMPLATEID] = @CAFEETEMPLATEID

END