CREATE PROCEDURE [globalsetup].[USP_CADISCOUNT_SEARCH]
(
	@SEARCH AS NVARCHAR(MAX) = '',
	@ENTITY AS INT = NULL,
	@PAGE_NUMBER AS INT = 1,
	@PAGE_SIZE AS INT = 10,
	@IS_ASCENDING AS BIT = 1
)
AS
WITH RAW_DATA AS (
	SELECT
	    [dbo].[CADISCOUNT].[CADISCOUNTID],
		[dbo].[CADISCOUNT].[NAME],		
		[dbo].[CADISCOUNT].[DESCRIPTION],
		[dbo].[CACOMPUTATIONTYPE].[NAME] AS DISCOUNTTYPE,
		[dbo].[CADISCOUNT].[CACOMPUTATIONTYPEID],
		CASE @IS_ASCENDING WHEN 1 THEN
			ROW_NUMBER() OVER(ORDER BY [dbo].[CADISCOUNT].[NAME])
		ELSE
			ROW_NUMBER() OVER(ORDER BY [dbo].[CADISCOUNT].[NAME] DESC)
		END AS RowNumber,
		COUNT(1) OVER() AS TotalRows
	FROM [dbo].[CADISCOUNT]
	JOIN [dbo].[CACOMPUTATIONTYPE]
	ON [dbo].[CACOMPUTATIONTYPE].[CACOMPUTATIONTYPEID] = [dbo].[CADISCOUNT].[CACOMPUTATIONTYPEID]
	LEFT JOIN [dbo].[CAMODULEDISCOUNTXREF] ON [dbo].[CAMODULEDISCOUNTXREF].[CADISCOUNTID] = [dbo].[CADISCOUNT].[CADISCOUNTID] AND @ENTITY IS NOT NULL
		LEFT JOIN [dbo].[CAENTITY] ON [dbo].[CAENTITY].[CAMODULEID] = [dbo].[CAMODULEDISCOUNTXREF].[CAMODULEID] AND @ENTITY IS NOT NULL
	WHERE (([dbo].[CADISCOUNT].[NAME] LIKE '%'+ @SEARCH +'%') OR ([dbo].[CADISCOUNT].[DESCRIPTION] LIKE '%'+ @SEARCH +'%'))
	AND (@ENTITY IS NULL OR [dbo].[CAMODULEDISCOUNTXREF].[CAMODULEID] IS NULL OR @ENTITY=[dbo].[CAENTITY].[CAENTITYID])
)

SELECT * 
FROM RAW_DATA
WHERE
	RowNumber > @PAGE_SIZE * (@PAGE_NUMBER - 1) AND 
	RowNumber <= @PAGE_SIZE * @PAGE_NUMBER
ORDER BY 
	RowNumber