CREATE PROCEDURE [globalsetup].[USP_GLOBALENTITYACCOUNTTYPEGL_GETALL]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[GLOBALENTITYACCOUNTTYPEGL].[GLOBALENTITYACCOUNTTYPEGLID],
	[dbo].[GLOBALENTITYACCOUNTTYPEGL].[GLOBALENTITYACCOUNTTYPEID],
	[dbo].[GLOBALENTITYACCOUNTTYPEGL].[DEBITGLACCOUNTID],
	[dbo].[GLOBALENTITYACCOUNTTYPEGL].[CREDITGLACCOUNTID],
	[dbo].[GLOBALENTITYACCOUNTTYPEGL].[CAPAYMENTTYPEID],
	[dbo].[GLOBALENTITYACCOUNTTYPEGL].[CAPAYMENTMETHODID],
	[DEBITGLACCOUNT].[NAME] AS [DEBITGLACCOUNTNAME],
	[CREDITTGLACCOUNT].[NAME] AS [CREDITGLACCOUNTNAME],
	[dbo].[CAPAYMENTMETHOD].[NAME] AS [PAYMENTMETHODNAME]
FROM [dbo].[GLOBALENTITYACCOUNTTYPEGL]
JOIN [dbo].[CAPAYMENTMETHOD] ON [dbo].[CAPAYMENTMETHOD].[CAPAYMENTMETHODID] = [dbo].[GLOBALENTITYACCOUNTTYPEGL].[CAPAYMENTMETHODID]
LEFT JOIN [dbo].[GLACCOUNT] [DEBITGLACCOUNT] ON [DEBITGLACCOUNT].[GLACCOUNTID] = [dbo].[GLOBALENTITYACCOUNTTYPEGL].[DEBITGLACCOUNTID]
LEFT JOIN [dbo].[GLACCOUNT] [CREDITTGLACCOUNT] ON [CREDITTGLACCOUNT].[GLACCOUNTID] = [dbo].[GLOBALENTITYACCOUNTTYPEGL].[CREDITGLACCOUNTID]
ORDER BY 
	[CREDITTGLACCOUNT].[NAME], [DEBITGLACCOUNT].[NAME]
END