CREATE PROCEDURE [globalsetup].[USP_TASKSTATUS_GETALL]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[TASKSTATUS].[TASKSTATUSID],
	[dbo].[TASKSTATUS].[TASKSTATUSNAME],
	[dbo].[TASKSTATUS].[ISCOMPLETED],
	[dbo].[TASKSTATUS].[LASTCHANGEDBY],
	[dbo].[TASKSTATUS].[LASTCHANGEDON],
	[dbo].[TASKSTATUS].[ROWVERSION]
FROM [dbo].[TASKSTATUS]
ORDER BY [dbo].[TASKSTATUS].[TASKSTATUSNAME] ASC
END