CREATE PROCEDURE [globalsetup].[USP_HEARINGSTATUS_GETALL]
AS
BEGIN
SELECT 
	[dbo].[HEARINGSTATUS].[HEARINGSTATUSID],
	[dbo].[HEARINGSTATUS].[NAME],
	[dbo].[HEARINGSTATUS].[DESCRIPTION],
	[dbo].[HEARINGSTATUS].[LASTCHANGEDBY],
	[dbo].[HEARINGSTATUS].[LASTCHANGEDON],
	[dbo].[HEARINGSTATUS].[ROWVERSION]
FROM [dbo].[HEARINGSTATUS] ORDER BY [dbo].[HEARINGSTATUS].[NAME] ASC
END