CREATE PROCEDURE [globalsetup].[USP_CAFEECONSTANT_GETALL]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[CAFEECONSTANT].[CAFEECONSTANTID],
	[dbo].[CAFEECONSTANT].[NAME],
	[dbo].[CAFEECONSTANT].[DESCRIPTION],
	[dbo].[CAFEECONSTANT].[VALUETYPEID],
	[dbo].[CAFEECONSTANT].[LASTCHANGEDBY],
	[dbo].[CAFEECONSTANT].[LASTCHANGEDON],
	[dbo].[CAFEECONSTANT].[ROWVERSION]
FROM 
	[dbo].[CAFEECONSTANT]
ORDER BY
	[dbo].[CAFEECONSTANT].[NAME]   
	
EXEC [globalsetup].[USP_CAFEECONSTANTVALUE_GETALL] 

END