CREATE PROCEDURE [globalsetup].[USP_PARCELCONTACTTYPE_GETALL]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[PARCELCONTACTTYPE].[PARCELCONTACTTYPEID],
	[dbo].[PARCELCONTACTTYPE].[NAME],
	[dbo].[PARCELCONTACTTYPE].[DESCRIPTION],
	[dbo].[PARCELCONTACTTYPE].[PARCELCONTACTSYSTEMTYPEID],
	[dbo].[PARCELCONTACTTYPE].[LASTCHANGEDBY],
	[dbo].[PARCELCONTACTTYPE].[LASTCHANGEDON],
	[dbo].[PARCELCONTACTTYPE].[ROWVERSION]
FROM [dbo].[PARCELCONTACTTYPE]
ORDER BY 
	[dbo].[PARCELCONTACTTYPE].[NAME]
END