CREATE PROCEDURE [globalsetup].[USP_CONDITIONCATEGORY_GETALL]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[CONDITIONCATEGORY].[CONDITIONCATEGORYID],
	[dbo].[CONDITIONCATEGORY].[NAME],
	[dbo].[CONDITIONCATEGORY].[DESCRIPTION],
	[dbo].[CONDITIONCATEGORY].[LASTCHANGEDBY],
	[dbo].[CONDITIONCATEGORY].[LASTCHANGEDON],
	[dbo].[CONDITIONCATEGORY].[ROWVERSION]
FROM [dbo].[CONDITIONCATEGORY]
ORDER BY 
	[dbo].[CONDITIONCATEGORY].[NAME]
END