CREATE PROCEDURE [globalsetup].[USP_CUSTOMFIELDTEMPLATE_GETBYID]
(
	@GCUSTOMFIELDTEMPLATE CHAR(36)
)
AS
BEGIN
	SET NOCOUNT ON;
	SELECT 
		[dbo].[CUSTOMFIELDTEMPLATE].[GCUSTOMFIELDTEMPLATE],
		[dbo].[CUSTOMFIELDTEMPLATE].[FKCUSTOMFIELDLAYOUTCONTROLTYPE],
		[dbo].[CUSTOMFIELDTEMPLATE].[TEMPLATENAME],
		[dbo].[CUSTOMFIELDTEMPLATE].[SDEFAULTVALUE],
		[dbo].[CUSTOMFIELDTEMPLATE].[SFIELDTIP],
		[dbo].[CUSTOMFIELDTEMPLATE].[ISACTIVE],
		[dbo].[CUSTOMFIELDTEMPLATE].[BALLOWMULTIPLESELECTIONS],
		[dbo].[CUSTOMFIELDLAYOUTCONTROLTYPE].[SNAME] AS CUSTOMFIELDLAYOUTCONTROLTYPENAME,
		[dbo].[CUSTOMFIELDTEMPLATE].[LASTCHANGEDBY],  
		[dbo].[CUSTOMFIELDTEMPLATE].[LASTCHANGEDON],  
		[dbo].[CUSTOMFIELDTEMPLATE].[ROWVERSION] 
	FROM [dbo].[CUSTOMFIELDTEMPLATE]
				INNER JOIN [dbo].[CUSTOMFIELDLAYOUTCONTROLTYPE] 
							ON [dbo].[CUSTOMFIELDTEMPLATE].[FKCUSTOMFIELDLAYOUTCONTROLTYPE] = [dbo].[CUSTOMFIELDLAYOUTCONTROLTYPE].[ICUSTOMFIELDLAYOUTCONTROLTYPE]
	WHERE
		[dbo].[CUSTOMFIELDTEMPLATE].[GCUSTOMFIELDTEMPLATE] = @GCUSTOMFIELDTEMPLATE  


	EXEC [globalsetup].[USP_CUSTOMFIELDTEMPLATEITEM_GETBYPARENTID] @GCUSTOMFIELDTEMPLATE
	EXEC [globalsetup].[USP_CUSTOMFIELDTEMPLATE_ASSOCIATEDFIELDS_GETBYCUSTOMFIELDTEMPLATEID] @GCUSTOMFIELDTEMPLATE

END