CREATE PROCEDURE [globalsetup].[USP_RPCONTACTTYPESYSTEM_SELECT_LOOKUP]
AS
SET NOCOUNT ON;
SELECT 
	[dbo].[RPCONTACTTYPESYSTEM].[RPCONTACTTYPESYSTEMID],
	[dbo].[RPCONTACTTYPESYSTEM].[NAME]
FROM [dbo].[RPCONTACTTYPESYSTEM]
ORDER BY [dbo].[RPCONTACTTYPESYSTEM].[NAME]