
CREATE PROCEDURE [dbo].[RevenueDashboardData]

@STARTDATE AS DATETIME,
@ENDDATE AS DATETIME,
@MODTYPE AS VARCHAR(50) = NULL,
@CASETYPE AS VARCHAR(36) = NULL
AS
BEGIN

DECLARE @STARTDATEY0 DATETIME
DECLARE @ENDDATEY0 DATETIME

SET @STARTDATEY0 = DATEADD(YEAR,-1,@STARTDATE)
SET @ENDDATEY0 = DATEADD(YEAR,-1,@ENDDATE)

SET @ENDDATE = DATEADD(S,-1,DATEADD(D,1,@ENDDATE))

SELECT     CATRANSACTION.CATRANSACTIONID, CATRANSACTIONFEE.CATRANSACTIONFEEID, CATRANSACTIONFEE.PAIDAMOUNT, CATRANSACTION.RECEIPTNUMBER, COALESCE (PMPERMIT.PERMITNUMBER, 
				  PLPLAN.PLANNUMBER, BLLICENSE.LICENSENUMBER, CMCODECASE.CASENUMBER, ILLICENSE.LICENSENUMBER, PRPROJECT.PROJECTNUMBER, BLGLOBALENTITYEXTENSION.REGISTRATIONID, IMINSPECTION.INSPECTIONNUMBER, IPCONDITION.CONDITIONNUMBER, RPPROPERTY.PROPERTYNUMBER, TXREMITTANCEACCOUNT.REMITTANCEACCOUNTNUMBER) AS CaseNumber, USERS.ID, CAINVOICE.CAINVOICEID, CAINVOICE.INVOICENUMBER, 
				  CACOMPUTEDFEE.COMPUTEDAMOUNT, CATRANSACTIONPAYMENT.PAYMENTDATE, CAPAYMENTMETHOD.NAME AS PaymentMethod, CATRANSACTIONPAYMENT.SUPPLEMENTALDATA, 
				  CATRANSACTIONSTATUS.NAME AS TransactionStatus, CAStatus_1.NAME AS InvoiceStatus, CATRANSACTIONTYPE.NAME AS TransactionType, CACOMPUTEDFEE.CACOMPUTEDFEEID, 
				  CAStatus_1.NAME AS [Transaction Fee Status], CATRANSACTION.GLOBALENTITYID, CAFEE.NAME AS FeeName, CAMODULE.NAME AS Module, CAENTITY.NAME AS Entity, CAINVOICEFEE.CAINVOICEFEEID, 
				  CMCASETYPE.NAME AS CODECASETYPE, BLLICENSECLASS.NAME AS BUSINESSLICENSECLASS, BLLICENSETYPE.NAME AS BUSINESSLICENSETYPE, 
				  PMPERMITWORKCLASS.NAME AS PERMITWORKCLASS, PMPERMITTYPE.NAME AS PERMITTYPE, PLPLANTYPE.PLANNAME AS PLANTYPE, PLPLANWORKCLASS.NAME AS PLANWORKCLASS, 
				  ILLICENSECLASSIFICATION.NAME AS PROFESSIONALLICENSETYPE, ILLICENSE.LICENSENUMBER AS PROFESSIONALLICENSENUMBER, ILLICENSETYPE.NAME AS PROFESSIONALLICENSETYPE, ILLICENSECLASSIFICATION.ILLICENSECLASSIFICATIONID, 
				  ILLICENSETYPE.ILLICENSETYPEID, PLPLANWORKCLASS.PLPLANWORKCLASSID, PLPLANTYPE.PLPLANTYPEID, PMPERMITTYPE.PMPERMITTYPEID, 
				  PMPERMITWORKCLASS.PMPERMITWORKCLASSID, CMCASETYPE.CMCASETYPEID, IMINSPECTIONTYPE.IMINSPECTIONTYPEID, IMINSPECTIONTYPE.NAME AS INSPECTIONTYPE, IPCONDITIONTYPE.IPCONDITIONTYPEID, RPPROPERTYTYPE.RPPROPERTYTYPEID, TXREMITTANCETYPE.TXREMITTANCETYPEID, BLLICENSECLASS.BLLICENSECLASSID, BLLICENSETYPE.BLLICENSETYPEID, 
				  COALESCE (CMCASETYPE.CMCASETYPEID, BLLICENSETYPE.BLLICENSETYPEID, PMPERMITTYPE.PMPERMITTYPEID, PLPLANTYPE.PLPLANTYPEID, ILLICENSETYPE.ILLICENSETYPEID, IMINSPECTIONTYPE.IMINSPECTIONTYPEID, IPCONDITIONTYPE.IPCONDITIONTYPEID, RPPROPERTYTYPE.RPPROPERTYTYPEID, TXREMITTANCETYPE.TXREMITTANCETYPEID, '') AS CASETYPEID, 
				  COALESCE (BLLICENSECLASS.BLLICENSECLASSID, PMPERMITWORKCLASS.PMPERMITWORKCLASSID, PLPLANWORKCLASS.PLPLANWORKCLASSID, ILLICENSECLASSIFICATION.ILLICENSECLASSIFICATIONID, '') AS WORKCLASSID,
				  COALESCE (CMCASETYPE.NAME, BLLICENSETYPE.NAME, PMPERMITTYPE.NAME, PLPLANTYPE.PLANNAME, ILLICENSETYPE.NAME, IMINSPECTIONTYPE.NAME, IPCONDITIONTYPE.NAME, RPPROPERTYTYPE.NAME, TXREMITTANCETYPE.NAME,'') AS CASETYPE, 
				  COALESCE (BLLICENSECLASS.NAME, PMPERMITWORKCLASS.NAME, PLPLANWORKCLASS.NAME, ILLICENSECLASSIFICATION.NAME, '') AS WORKCLASS
FROM        CATRANSACTIONTYPE INNER JOIN
				  CATRANSACTIONFEE INNER JOIN
				  CACOMPUTEDFEE ON CATRANSACTIONFEE.CACOMPUTEDFEEID = CACOMPUTEDFEE.CACOMPUTEDFEEID INNER JOIN
				  CATRANSACTION ON CATRANSACTIONFEE.CATRANSACTIONID = CATRANSACTION.CATRANSACTIONID INNER JOIN
				  USERS ON CATRANSACTION.CREATEDBY = USERS.SUSERGUID INNER JOIN
				  CATRANSACTIONPAYMENT ON CATRANSACTION.CATRANSACTIONID = CATRANSACTIONPAYMENT.CATRANSACTIONID INNER JOIN
				  CAPAYMENTMETHOD ON CATRANSACTIONPAYMENT.CAPAYMENTMETHODID = CAPAYMENTMETHOD.CAPAYMENTMETHODID INNER JOIN
				  CATRANSACTIONSTATUS ON CATRANSACTION.CATRANSACTIONSTATUSID = CATRANSACTIONSTATUS.CATRANSACTIONSTATUSID ON 
				  CATRANSACTIONTYPE.CATRANSACTIONTYPEID = CATRANSACTION.CATRANSACTIONTYPEID INNER JOIN
				  CASTATUS AS CAStatus_1 ON CATRANSACTIONFEE.CASTATUSID = CAStatus_1.CASTATUSID INNER JOIN
				  CAINVOICEFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CAINVOICEFEE.CACOMPUTEDFEEID INNER JOIN
				  CASTATUS INNER JOIN
				  CAINVOICE ON CASTATUS.CASTATUSID = CAINVOICE.CASTATUSID ON CAINVOICEFEE.CAINVOICEID = CAINVOICE.CAINVOICEID INNER JOIN
				  CAFEETEMPLATEFEE ON CACOMPUTEDFEE.CAFEETEMPLATEFEEID = CAFEETEMPLATEFEE.CAFEETEMPLATEFEEID INNER JOIN
				  CAFEE ON CAFEETEMPLATEFEE.CAFEEID = CAFEE.CAFEEID INNER JOIN
				  CAMODULE INNER JOIN
				  CAENTITY ON CAMODULE.CAMODULEID = CAENTITY.CAMODULEID INNER JOIN
				  CAMODULEFEEXREF ON CAMODULE.CAMODULEID = CAMODULEFEEXREF.CAMODULEID ON CAFEE.CAFEEID = CAMODULEFEEXREF.CAFEEID LEFT OUTER JOIN
				  ILLICENSEFEE INNER JOIN
				  ILLICENSE INNER JOIN
				  ILLICENSECLASSIFICATION ON ILLICENSE.ILLICENSECLASSIFICATIONID = ILLICENSECLASSIFICATION.ILLICENSECLASSIFICATIONID ON 
				  ILLICENSEFEE.ILLICENSEID = ILLICENSE.ILLICENSEID INNER JOIN
				  ILLICENSETYPE ON ILLICENSE.ILLICENSETYPEID = ILLICENSETYPE.ILLICENSETYPEID ON CACOMPUTEDFEE.CACOMPUTEDFEEID = ILLICENSEFEE.CACOMPUTEDFEEID LEFT OUTER JOIN
				  PLPLANWORKCLASS INNER JOIN
				  PLPLAN INNER JOIN
				  PLPLANFEE ON PLPLAN.PLPLANID = PLPLANFEE.PLPLANID INNER JOIN
				  PLPLANTYPE ON PLPLAN.PLPLANTYPEID = PLPLANTYPE.PLPLANTYPEID ON PLPLANWORKCLASS.PLPLANWORKCLASSID = PLPLAN.PLPLANWORKCLASSID ON 
				  CACOMPUTEDFEE.CACOMPUTEDFEEID = PLPLANFEE.CACOMPUTEDFEEID LEFT OUTER JOIN
				  PMPERMITTYPE INNER JOIN
				  PMPERMIT INNER JOIN
				  PMPERMITFEE ON PMPERMIT.PMPERMITID = PMPERMITFEE.PMPERMITID ON PMPERMITTYPE.PMPERMITTYPEID = PMPERMIT.PMPERMITTYPEID INNER JOIN
				  PMPERMITWORKCLASS ON PMPERMIT.PMPERMITWORKCLASSID = PMPERMITWORKCLASS.PMPERMITWORKCLASSID ON 
				  CACOMPUTEDFEE.CACOMPUTEDFEEID = PMPERMITFEE.CACOMPUTEDFEEID LEFT OUTER JOIN
				  CMCODECASEFEE INNER JOIN
				  CMCODECASE ON CMCODECASEFEE.CMCODECASEID = CMCODECASE.CMCODECASEID INNER JOIN
				  CMCASETYPE ON CMCODECASE.CMCASETYPEID = CMCASETYPE.CMCASETYPEID ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CMCODECASEFEE.CACOMPUTEDFEEID LEFT OUTER JOIN
				  
 				  IMINSPECTIONFEE INNER JOIN
				  IMINSPECTION ON IMINSPECTIONFEE.IMINSPECTIONID = IMINSPECTION.IMINSPECTIONID INNER JOIN
				  IMINSPECTIONTYPE ON IMINSPECTION.IMINSPECTIONTYPEID = IMINSPECTIONTYPE.IMINSPECTIONTYPEID ON CACOMPUTEDFEE.CACOMPUTEDFEEID = IMINSPECTIONFEE.CACOMPUTEDFEEID LEFT OUTER JOIN
  				  IPCONDITIONFEE INNER JOIN
				  IPCONDITION ON IPCONDITIONFEE.IPCONDITIONID = IPCONDITION.IPCONDITIONID INNER JOIN
				  IPCONDITIONTYPE ON IPCONDITION.IPCONDITIONTYPEID = IPCONDITIONTYPE.IPCONDITIONTYPEID ON CACOMPUTEDFEE.CACOMPUTEDFEEID = IPCONDITIONFEE.CACOMPUTEDFEEID LEFT OUTER JOIN
  				  RPPROPERTYFEE INNER JOIN
				  RPPROPERTY ON RPPROPERTYFEE.RPPROPERTYID = RPPROPERTY.RPPROPERTYID INNER JOIN
				  RPPROPERTYTYPE ON RPPROPERTY.RPPROPERTYTYPEID = RPPROPERTYTYPE.RPPROPERTYTYPEID ON CACOMPUTEDFEE.CACOMPUTEDFEEID = RPPROPERTYFEE.CACOMPUTEDFEEID LEFT OUTER JOIN
  				  TXREMITTANCEFEE INNER JOIN
  				  TXREMITTANCE ON TXREMITTANCEFEE.TXREMITTANCEID = TXREMITTANCE.TXREMITTANCEID INNER JOIN
  				  TXREMITTANCEACCOUNT ON TXREMITTANCEACCOUNT.TXREMITTANCEACCOUNTID = TXREMITTANCE.TXREMITTANCEACCOUNTID INNER JOIN
  				  TXREMITTANCETYPE ON TXREMITTANCEACCOUNT.TXREMITTANCETYPEID = TXREMITTANCETYPE.TXREMITTANCETYPEID ON CACOMPUTEDFEE.CACOMPUTEDFEEID = TXREMITTANCEFEE.CACOMPUTEDFEEID LEFT OUTER JOIN
                                    
				  PRPROJECTFEE INNER JOIN
				  PRPROJECT ON PRPROJECTFEE.PRPROJECTID = PRPROJECT.PRPROJECTID ON CACOMPUTEDFEE.CACOMPUTEDFEEID = PRPROJECTFEE.CACOMPUTEDFEEID LEFT OUTER JOIN
				  BLLICENSEFEE INNER JOIN
				  BLLICENSE ON BLLICENSEFEE.BLLICENSEID = BLLICENSE.BLLICENSEID INNER JOIN
				  BLLICENSECLASS ON BLLICENSE.BLLICENSECLASSID = BLLICENSECLASS.BLLICENSECLASSID INNER JOIN
				  BLLICENSETYPE ON BLLICENSE.BLLICENSETYPEID = BLLICENSETYPE.BLLICENSETYPEID ON CACOMPUTEDFEE.CACOMPUTEDFEEID = BLLICENSEFEE.CACOMPUTEDFEEID
				  LEFT OUTER JOIN BLGLOBALENTITYEXTENSIONFEE
					INNER JOIN BLGLOBALENTITYEXTENSION
					ON BLGLOBALENTITYEXTENSIONFEE.BLGLOBALENTITYEXTENSIONID = BLGLOBALENTITYEXTENSION.BLGLOBALENTITYEXTENSIONID
					ON CACOMPUTEDFEE.CACOMPUTEDFEEID = BLGLOBALENTITYEXTENSIONFEE.CACOMPUTEDFEEID
WHERE			  ((CATRANSACTIONPAYMENT.PAYMENTDATE BETWEEN @STARTDATE AND @ENDDATE) OR (CATRANSACTIONPAYMENT.PAYMENTDATE BETWEEN @STARTDATEY0 AND @ENDDATEY0)) AND (CATRANSACTIONTYPE.CATRANSACTIONTYPEID NOT IN (5, 6)) AND 
				  (CATRANSACTIONSTATUS.CATRANSACTIONSTATUSID NOT IN (2, 3)) AND (CAINVOICE.CASTATUSID <> 5) AND (CATRANSACTIONFEE.CASTATUSID NOT IN (5, 3))
ORDER BY CATRANSACTIONPAYMENT.PAYMENTDATE desc                  
END