CREATE PROCEDURE [dbo].[USP_RPTAUTOMAIL_INSERT]
(
	@RPTAUTOMAILID CHAR(36),
	@SESSIONNAME VARCHAR(255),
	@RPTDATERANGEID INT,
	@DAYNUMDATE INT,
	@RPTREPORTID CHAR(36),
	@RECURRENCEID CHAR(36),
	@DESCRIPTION VARCHAR(MAX),
	@LASTRECURRENCE DATETIME,
	@NEXTRECURRENCE DATETIME,
	@CUSTOMSUBJECT NVARCHAR(MAX),
	@CUSTOMBODY NVARCHAR(MAX),
	@FTPSETUPID CHAR(36),
	@SUBPATH NVARCHAR(255),
	@LASTCHANGEDON DATETIME,
	@LASTCHANGEDBY CHAR(36),
	@ROWVERSION INT,
	@RPTREPORTFILETYPEID INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
INSERT INTO [dbo].[RPTAUTOMAIL](
	[RPTAUTOMAILID],
	[SESSIONNAME],
	[RPTDATERANGEID],
	[DAYNUMDATE],
	[RPTREPORTID],
	[RECURRENCEID],
	[DESCRIPTION],
	[LASTRECURRENCE],
	[NEXTRECURRENCE],
	[CUSTOMSUBJECT],
	[CUSTOMBODY],
	[FTPSETUPID],
	[SUBPATH],
	[LASTCHANGEDON],
	[LASTCHANGEDBY],
	[ROWVERSION],
	[RPTREPORTFILETYPEID]
)
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
VALUES
(
	@RPTAUTOMAILID,
	@SESSIONNAME,
	@RPTDATERANGEID,
	@DAYNUMDATE,
	@RPTREPORTID,
	@RECURRENCEID,
	@DESCRIPTION,
	@LASTRECURRENCE,
	@NEXTRECURRENCE,
	@CUSTOMSUBJECT,
	@CUSTOMBODY,
	@FTPSETUPID,
	@SUBPATH,
	@LASTCHANGEDON,
	@LASTCHANGEDBY,
	@ROWVERSION,
	@RPTREPORTFILETYPEID
)
SELECT * FROM @OUTPUTTABLE