CREATE PROCEDURE [dbo].[USP_RPLANDLORDLICENSESTATUS_UPDATE]
(
	@RPLANDLORDLICENSESTATUSID CHAR(36),
	@NAME NVARCHAR(50),
	@DESCRIPTION NVARCHAR(MAX),
	@RPLANDLORDLICENSESYSSTATUSID INT,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
UPDATE [dbo].[RPLANDLORDLICENSESTATUS] SET
	[NAME] = @NAME,
	[DESCRIPTION] = @DESCRIPTION,
	[RPLANDLORDLICENSESYSSTATUSID] = @RPLANDLORDLICENSESYSSTATUSID,
	[LASTCHANGEDBY] = @LASTCHANGEDBY,
	[LASTCHANGEDON] = @LASTCHANGEDON,
	[ROWVERSION] = @ROWVERSION + 1
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE
	[RPLANDLORDLICENSESTATUSID] = @RPLANDLORDLICENSESTATUSID AND 
	[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE