CREATE PROCEDURE [dbo].[USP_RPPROPERTYACTIVITYTYPE_DELETE]
(
	@RPPROPERTYACTIVITYTYPEID CHAR(36),
	@ROWVERSION INT
)
AS
DELETE FROM [dbo].[RPPROPERTYACTIVITYTYPE]
WHERE
	[RPPROPERTYACTIVITYTYPEID] = @RPPROPERTYACTIVITYTYPEID AND 
	[ROWVERSION]= @ROWVERSION