CREATE PROCEDURE [dbo].[USP_RPPROPERTYACTIVITYTYPE_INSERT]
(
	@RPPROPERTYACTIVITYTYPEID CHAR(36),
	@NAME NVARCHAR(50),
	@DESCRIPTION NVARCHAR(MAX),
	@CANEDIT BIT,
	@CREATEID BIT,
	@PREFIXID NVARCHAR(20),
	@ALLOWDUPLICATE BIT,
	@CUSTOMFIELDLAYOUTID CHAR(36),
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
INSERT INTO [dbo].[RPPROPERTYACTIVITYTYPE](
	[RPPROPERTYACTIVITYTYPEID],
	[NAME],
	[DESCRIPTION],
	[CANEDIT],
	[CREATEID],
	[PREFIXID],
	[ALLOWDUPLICATE],
	[CUSTOMFIELDLAYOUTID],
	[LASTCHANGEDBY],
	[LASTCHANGEDON],
	[ROWVERSION]
)
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
VALUES
(
	@RPPROPERTYACTIVITYTYPEID,
	@NAME,
	@DESCRIPTION,
	@CANEDIT,
	@CREATEID,
	@PREFIXID,
	@ALLOWDUPLICATE,
	@CUSTOMFIELDLAYOUTID,
	@LASTCHANGEDBY,
	@LASTCHANGEDON,
	@ROWVERSION
)
SELECT * FROM @OUTPUTTABLE