CREATE PROCEDURE [dbo].[USP_RPTIMAGELIB_DELETE]
(
	@RPTIMAGELIBID CHAR(36),
	@ROWVERSION INT
)
AS
DELETE FROM [dbo].[RPTIMAGELIB]
WHERE
	[RPTIMAGELIBID] = @RPTIMAGELIBID AND 
	[ROWVERSION]= @ROWVERSION