CREATE PROCEDURE [dbo].[USP_RECURRENCE_SEARCH]
(
	@SEARCH AS NVARCHAR(MAX) = '',
	@PAGE_NUMBER AS INT = 1,
	@PAGE_SIZE AS INT = 10,
	@IS_ASCENDING AS BIT = 1,
	@LICENSECYCLETYPEID AS INT = 0
)
AS
WITH RAW_DATA AS (
	SELECT
		[dbo].[RECURRENCE].[RECURRENCEID],
		[dbo].[RECURRENCE].[NAME],
		CASE @IS_ASCENDING WHEN 1 THEN
			ROW_NUMBER() OVER(ORDER BY [dbo].[RECURRENCE].[NAME])
		ELSE
			ROW_NUMBER() OVER(ORDER BY [dbo].[RECURRENCE].[NAME] DESC)
		END AS RowNumber,
		COUNT(1) OVER() AS TotalRows
	FROM [dbo].[RECURRENCE]
	WHERE ([dbo].[RECURRENCE].[NAME] LIKE '%'+ @SEARCH +'%') 
	AND [dbo].[RECURRENCE].[LICENSECYCLETYPEID] = @LICENSECYCLETYPEID
)

SELECT * 
FROM RAW_DATA
WHERE
	RowNumber > @PAGE_SIZE * (@PAGE_NUMBER - 1) AND 
	RowNumber <= @PAGE_SIZE * @PAGE_NUMBER
ORDER BY 
	RowNumber