CREATE PROCEDURE [dbo].[USP_RPTREPORT_DELETE]
(
	@RPTREPORTID CHAR(36),
	@ROWVERSION INT
)
AS
SET NOCOUNT ON;
EXEC [dbo].[USP_RPTREPORTATTRIBUTE_DELETE_BYPARENTID] @RPTREPORTID
-- Delete Report Custom Field
EXEC [dbo].[USP_RPTCUSTOMFIELD_DELETE_BYPARENTID] @RPTREPORTID
SET NOCOUNT OFF;


DELETE FROM [dbo].[RPTREPORT]
WHERE
	[RPTREPORTID] = @RPTREPORTID AND 
	[ROWVERSION]= @ROWVERSION