CREATE PROCEDURE [dbo].[USP_RPTREPORTATTRIBUTE_DELETE_BYPARENTID]
(
 @REPORTID CHAR(36)
)
AS
BEGIN

DELETE FROM [dbo].[RPTREPORTATTRIBUTE] 
WHERE [dbo].[RPTREPORTATTRIBUTE].[RPTREPORTID] = @REPORTID

END