CREATE PROCEDURE [dbo].[USP_RPLANDLORDTYPECONTACTTYPE_UPDATE]
(
	@RPLANDLORDTYPECONTACTTYPEID CHAR(36),
	@RPCONTACTTYPEID CHAR(36),
	@RPLANDLORDLICENSETYPEID CHAR(36),
	@ISREQUIRED BIT,
	@CONTACTTYPEGROUP INT
)
AS

UPDATE [dbo].[RPLANDLORDTYPECONTACTTYPE] SET
	[RPCONTACTTYPEID] = @RPCONTACTTYPEID,
	[RPLANDLORDLICENSETYPEID] = @RPLANDLORDLICENSETYPEID,
	[ISREQUIRED] = @ISREQUIRED,
	[CONTACTTYPEGROUP] = @CONTACTTYPEGROUP

WHERE
	[RPLANDLORDTYPECONTACTTYPEID] = @RPLANDLORDTYPECONTACTTYPEID