CREATE PROCEDURE [dbo].[USP_RECORD_TYPE_RIGHTS_BY_USER_CASE_ID]
	@ID AS CHAR(36),
	@USER_ID AS CHAR(36)
AS

SELECT ROLERECORDTYPEXREF.VISIBLE, ROLERECORDTYPEXREF.ALLOWADD, ROLERECORDTYPEXREF.ALLOWDELETE, ROLERECORDTYPEXREF.ALLOWUPDATE
FROM ROLERECORDTYPEXREF
INNER JOIN USERS ON USERS.SROLEID = ROLERECORDTYPEXREF.ROLEID
INNER JOIN (
SELECT PMPERMITTYPEID AS TYPEID FROM PMPERMIT WHERE PMPERMITID = @ID
UNION ALL
SELECT PLPLANTYPEID AS TYPEID FROM PLPLAN WHERE PLPLANID = @ID
UNION ALL
SELECT PLAPPLICATIONTYPEID AS TYPEID FROM PLAPPLICATION WHERE PLAPPLICATIONID = @ID
UNION ALL
SELECT IMINSPECTIONTYPEID AS TYPEID FROM IMINSPECTION WHERE IMINSPECTIONID = @ID
UNION ALL
SELECT PRPROJECTTYPEID AS TYPEID FROM PRPROJECT WHERE PRPROJECTID = @ID
UNION ALL
SELECT CITIZENREQUESTTYPEID AS TYPEID FROM CITIZENREQUEST WHERE CITIZENREQUESTID = @ID
UNION ALL
SELECT CMCASETYPEID AS TYPEID FROM CMCODECASE WHERE CMCODECASEID = @ID
UNION ALL
SELECT BLLICENSETYPEID AS TYPEID FROM BLLICENSE WHERE BLLICENSEID = @ID
UNION ALL
SELECT ILLICENSETYPEID AS TYPEID FROM ILLICENSE WHERE ILLICENSEID = @ID
UNION ALL
SELECT IMINSPECTIONCASETYPEID AS TYPEID FROM IMINSPECTIONCASE WHERE IMINSPECTIONCASEID = @ID
UNION ALL
SELECT TXREMITTANCETYPEID AS TYPEID FROM TXREMITTANCEACCOUNT WHERE TXREMITTANCEACCOUNTID = @ID
UNION ALL
SELECT RPLANDLORDLICENSETYPEID AS TYPEID FROM RPLANDLORDLICENSE WHERE RPLANDLORDLICENSEID = @ID
UNION ALL
SELECT RPPROPERTYTYPEID AS TYPEID FROM RPPROPERTY WHERE RPPROPERTYID = @ID
UNION ALL
SELECT IPCASETYPEID AS TYPEID FROM IPCASE WHERE IPCASEID = @ID
UNION ALL
SELECT OMOBJECTTYPEID AS TYPEID FROM OMOBJECT WHERE OMOBJECTID = @ID
UNION ALL
SELECT PMRENEWALCASETYPEID AS TYPEID FROM PMRENEWALCASE WHERE PMRENEWALCASEID = @ID
) AS TYPE_DATA ON TYPE_DATA.TYPEID = ROLERECORDTYPEXREF.RECORDTYPEID
WHERE USERS.SUSERGUID = @USER_ID