CREATE PROCEDURE [dbo].[USP_ROLESCUSTOMFIELDS_UPDATE]
(
	@ROLECUSTOMFIELDID CHAR(36),
	@ROLEID CHAR(36),
	@CUSTOMFIELDID CHAR(36),
	@ISHIDDEN BIT,
	@ISDISABLED BIT,
	@CUSTOMFIELDTABLECOLUMNREFID CHAR(36)
)
AS

UPDATE [dbo].[ROLESCUSTOMFIELDS] SET	
	[ROLEID] = @ROLEID,
	[CUSTOMFIELDID] = @CUSTOMFIELDID ,
	[ISHIDDEN] = @ISHIDDEN,
	[ISDISABLED] = @ISDISABLED,
	[CUSTOMFIELDTABLECOLUMNREFID] = @CUSTOMFIELDTABLECOLUMNREFID

WHERE
	[ROLECUSTOMFIELDID] = @ROLECUSTOMFIELDID