CREATE PROCEDURE [dbo].[USP_ROLEMENUXREF_UPDATE]
(
	@FKROLEID CHAR(36),
	@FKMENUID CHAR(36),
	@BVISIBLE BIT
)
AS

UPDATE [dbo].[ROLEMENUXREF] SET
	[BVISIBLE] = @BVISIBLE

WHERE
	[FKROLEID] = @FKROLEID AND 
	[FKMENUID] = @FKMENUID