CREATE PROCEDURE [dbo].[USP_RPLANDLORDLICENSETYPE_DELETE]
(
	@RPLANDLORDLICENSETYPEID CHAR(36),
	@ROWVERSION INT
)
AS
BEGIN
SET NOCOUNT ON

EXEC [USP_RPLANDLORDTYPECONTACTTYPE_DELETE_BYPARENTID] @RPLANDLORDLICENSETYPEID

SET NOCOUNT OFF

DELETE FROM [dbo].[RPLANDLORDLICENSETYPE]
WHERE
	[RPLANDLORDLICENSETYPEID] = @RPLANDLORDLICENSETYPEID AND 
	[ROWVERSION]= @ROWVERSION
END