CREATE PROCEDURE [dbo].[USP_ROLEPAYMENTMETHODXREF_DELETE_BYUSERROLEID]
(
	@SROLEGUID CHAR(36)
)
AS
BEGIN
	DELETE FROM [dbo].[ROLEPAYMENTMETHODXREF]
	WHERE [dbo].[ROLEPAYMENTMETHODXREF].[SROLEGUID] = @SROLEGUID 
END