CREATE PROCEDURE [impactcase].[USP_IMPACTCASES_GETBYID]
	 @ID AS CHAR(36)
AS
	DECLARE @IMPACTCASELIST AS RecordIDs
	INSERT INTO @IMPACTCASELIST (RECORDID) VALUES (@ID)
	EXEC [impactcase].[USP_IMPACTCASES_GETBYIDS] @IMPACTCASELIST, null
RETURN 0