CREATE PROCEDURE [gissetup].[USP_PLITEMREVIEWTYPE_SEARCH]
(
	@SEARCH AS NVARCHAR(MAX)    =  '',
	@PAGE_NUMBER AS INT         =  1,
	@PAGE_SIZE AS INT           =  10,
	@IS_ASCENDING AS BIT        =  1,
	@DEPARTMENT_ID	AS CHAR(36) = null
)
AS

WITH RAW_DATA AS (
	SELECT    [dbo].[PLITEMREVIEWTYPE].[PLITEMREVIEWTYPEID],
		      [dbo].[PLITEMREVIEWTYPE].[NAME],
		      [dbo].[PLITEMREVIEWTYPE].[DESCRIPTION],
			  [dbo].[PLITEMREVIEWTYPE].[DEPARTMENTID],
		      [dbo].[DEPARTMENT].[NAME] AS [DEPARTMENTNAME],
		      CASE @IS_ASCENDING WHEN 1 THEN ROW_NUMBER() OVER(ORDER BY [dbo].[PLITEMREVIEWTYPE].[NAME])
		                                ELSE ROW_NUMBER() OVER(ORDER BY [dbo].[PLITEMREVIEWTYPE].[NAME] DESC)
		      END AS RowNumber,
		      COUNT(1) OVER() AS TotalRows
	FROM      [dbo].[PLITEMREVIEWTYPE]
	          LEFT JOIN [dbo].[DEPARTMENT] ON [dbo].[PLITEMREVIEWTYPE].[DEPARTMENTID] = [dbo].[DEPARTMENT].[DEPARTMENTID]
	WHERE     ([dbo].[PLITEMREVIEWTYPE].[NAME] LIKE '%'+ @SEARCH +'%' OR 
	          [dbo].[PLITEMREVIEWTYPE].[DESCRIPTION] LIKE '%'+ @SEARCH +'%') AND
	          ([dbo].[PLITEMREVIEWTYPE].[DEPARTMENTID] = ISNULL(@DEPARTMENT_ID,[dbo].[PLITEMREVIEWTYPE].[DEPARTMENTID]))
)

SELECT   * 
FROM     RAW_DATA
WHERE    RowNumber > @PAGE_SIZE * (@PAGE_NUMBER - 1) AND 
	     RowNumber <= @PAGE_SIZE * @PAGE_NUMBER
ORDER BY RowNumber