CREATE PROCEDURE [gissetup].[USP_GEOQUERY_SELECT_LOOKUP]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[GEOQUERY].[GEOQUERYID],
	[dbo].[GEOQUERY].[QUERYNAME],
	[dbo].[GEOQUERY].[FEATURECLASSNAME],
	[dbo].[GEOQUERY].[FIELDNAME],
	[dbo].[GEOQUERY].[RETURNTYPE],
	[dbo].[GEOQUERY].[RETURNEDFEATURECLASS],
	[dbo].[GEOQUERYTYPE].[QUERYTYPENAME]
FROM 
	[dbo].[GEOQUERY]
	INNER JOIN [dbo].[GEOQUERYTYPE] ON [dbo].[GEOQUERYTYPE].[GEOQUERYTYPEID] = [dbo].[GEOQUERY].[GEOQUERYTYPEID]
ORDER BY 
	[dbo].[GEOQUERY].[QUERYNAME]
END