CREATE TABLE [dbo].[SEARCHRENTALPROPCUSTOMFIELD] (
    [SEARCHRENTALPROPCUSTOMFIELDID] CHAR (36) NOT NULL,
    [SEARCHRENTALPROPID]            CHAR (36) NOT NULL,
    [SEARCHCUSTOMFIELDID]           CHAR (36) NOT NULL,
    CONSTRAINT [PK_SEARCHRENTALPROPCUSTOM] PRIMARY KEY CLUSTERED ([SEARCHRENTALPROPCUSTOMFIELDID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_CUSTOMFIELD_SEARCHRENTAL] FOREIGN KEY ([SEARCHRENTALPROPID]) REFERENCES [dbo].[SEARCHRENTALPROP] ([SEARCHRENTALPROPID]),
    CONSTRAINT [FK_RENTALCFID_SEARCHCF] FOREIGN KEY ([SEARCHCUSTOMFIELDID]) REFERENCES [dbo].[SEARCHCUSTOMFIELD] ([SEARCHCUSTOMFIELDID])
);

