CREATE TABLE [dbo].[SEARCHPROJECTCUSTOMFIELD] (
    [SEARCHPROJECTCUSTOMFIELDID] CHAR (36) NOT NULL,
    [SEARCHPROJECTID]            CHAR (36) NOT NULL,
    [SEARCHCUSTOMFIELDID]        CHAR (36) NOT NULL,
    CONSTRAINT [PK_SEARCHPROJECTCUSTOMFIELD] PRIMARY KEY CLUSTERED ([SEARCHPROJECTCUSTOMFIELDID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PROJECTCF_SEARCHPROJECT] FOREIGN KEY ([SEARCHPROJECTID]) REFERENCES [dbo].[SEARCHPROJECT] ([SEARCHPROJECTID]),
    CONSTRAINT [FK_PROJECTCF_SRCHCUSTOMFIELD] FOREIGN KEY ([SEARCHCUSTOMFIELDID]) REFERENCES [dbo].[SEARCHCUSTOMFIELD] ([SEARCHCUSTOMFIELDID])
);

