CREATE TABLE [dbo].[SEARCHLICENSECUSTOMFLD] (
    [SEARCHLICENSECUSTOMFLDID] CHAR (36) NOT NULL,
    [SEARCHLICENSEID]          CHAR (36) NOT NULL,
    [SEARCHCUSTOMFIELDID]      CHAR (36) NOT NULL,
    CONSTRAINT [PK_SEARCHLICENSECUSTOMFLD] PRIMARY KEY CLUSTERED ([SEARCHLICENSECUSTOMFLDID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_SEARCHLICENSECUSTOMFLD_SCF] FOREIGN KEY ([SEARCHCUSTOMFIELDID]) REFERENCES [dbo].[SEARCHCUSTOMFIELD] ([SEARCHCUSTOMFIELDID]),
    CONSTRAINT [FK_SEARCHLICENSECUSTOMFLD_SL] FOREIGN KEY ([SEARCHLICENSEID]) REFERENCES [dbo].[SEARCHLICENSE] ([SEARCHLICENSEID])
);

