CREATE TABLE [dbo].[SEARCHASSETMANAGEMENTCUSTOMFLD] (
    [SEARCHASSETMANAGEMENTCUSTOMFID] CHAR (36) NOT NULL,
    [SEARCHASSETMANAGEMENTID]        CHAR (36) NOT NULL,
    [SEARCHCUSTOMFIELDID]            CHAR (36) NOT NULL,
    CONSTRAINT [PK_SearchAssetManagementCustom] PRIMARY KEY CLUSTERED ([SEARCHASSETMANAGEMENTCUSTOMFID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_SearchAssetManagementCF_CF] FOREIGN KEY ([SEARCHCUSTOMFIELDID]) REFERENCES [dbo].[SEARCHCUSTOMFIELD] ([SEARCHCUSTOMFIELDID]),
    CONSTRAINT [FK_SearchAssetManagementCustom] FOREIGN KEY ([SEARCHASSETMANAGEMENTID]) REFERENCES [dbo].[SEARCHASSETMANAGEMENT] ([SEARCHASSETMANAGEMENTID])
);

