CREATE TABLE [dbo].[SEARCHPLPLANCUSTOMFLD] (
    [SEARCHPLPLANCUSTOMFLDID] CHAR (36) NOT NULL,
    [SEARCHPLPLANID]          CHAR (36) NOT NULL,
    [SEARCHCUSTOMFIELDID]     CHAR (36) NOT NULL,
    CONSTRAINT [PK_SearchPLPlanCustomFld] PRIMARY KEY CLUSTERED ([SEARCHPLPLANCUSTOMFLDID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_SearchPLPlanCF_CF] FOREIGN KEY ([SEARCHCUSTOMFIELDID]) REFERENCES [dbo].[SEARCHCUSTOMFIELD] ([SEARCHCUSTOMFIELDID]),
    CONSTRAINT [FK_SearchPLPlanCustom] FOREIGN KEY ([SEARCHPLPLANID]) REFERENCES [dbo].[SEARCHPLPLAN] ([SEARCHPLPLANID])
);

