CREATE TABLE [dbo].[SERVICETASKHISTORYACTION] (
    [SERVICETASKHISTORYACTIONID] CHAR (36)      NOT NULL,
    [SERVICETASKHISTORYDETAILID] CHAR (36)      NOT NULL,
    [ACTIONTYPE]                 NVARCHAR (50)  NOT NULL,
    [STARTTIME]                  DATETIME       NULL,
    [ENDTIME]                    DATETIME       NULL,
    [RESULT]                     NVARCHAR (50)  NULL,
    [ERROR]                      NVARCHAR (MAX) NULL,
    [ADDITIONALINFO]             NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_SERVICETASKHISTORYACTION] PRIMARY KEY NONCLUSTERED ([SERVICETASKHISTORYACTIONID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_SERVICETASKHISTACT_HST_DET] FOREIGN KEY ([SERVICETASKHISTORYDETAILID]) REFERENCES [dbo].[SERVICETASKHISTORYDETAIL] ([SERVICETASKHISTORYDETAILID])
);


GO
CREATE NONCLUSTERED INDEX [IX_SERVICETASKHISTACT_HST_DET]
    ON [dbo].[SERVICETASKHISTORYACTION]([SERVICETASKHISTORYDETAILID] ASC) WITH (FILLFACTOR = 90);

