CREATE TABLE [dbo].[SETTINGSMETADATA] (
    [SETTINGNAME]     NVARCHAR (50)  NOT NULL,
    [FRIENDLYNAME]    NVARCHAR (500) NOT NULL,
    [ISINTBASED]      BIT            NULL,
    [ISPASSWORDBASED] BIT            NULL,
    [ISENCRYPTED]     BIT            NULL,
    CONSTRAINT [PK_SETTINGSMETADATA] PRIMARY KEY CLUSTERED ([SETTINGNAME] ASC)
);

