CREATE TABLE [dbo].[STATE] (
    [STATEID]      CHAR (36)     NOT NULL,
    [NAME]         NVARCHAR (50) NULL,
    [ABBREVIATION] NVARCHAR (2)  NULL,
    CONSTRAINT [PK_State] PRIMARY KEY CLUSTERED ([STATEID] ASC) WITH (FILLFACTOR = 90)
);

