CREATE TABLE [dbo].[STREETTYPE] (
    [STREETTYPEID] INT           NOT NULL,
    [NAME]         NVARCHAR (15) NOT NULL,
    CONSTRAINT [PK_StreetType] PRIMARY KEY CLUSTERED ([STREETTYPEID] ASC) WITH (FILLFACTOR = 90)
);

