CREATE TABLE [dbo].[SUBMENUS] (
    [SSUBMENUGUID] CHAR (36)     CONSTRAINT [DF_SubMenus_sSubMenuGUID] DEFAULT (newid()) NOT NULL,
    [FKMENUGUID]   CHAR (36)     NOT NULL,
    [SDESCRIPTION] NVARCHAR (50) NOT NULL,
    [IORDER]       SMALLINT      CONSTRAINT [DF_SubMenus_iOrder] DEFAULT ((99)) NOT NULL,
    [EXTERNALMENU] BIT           DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_SubMenus] PRIMARY KEY CLUSTERED ([SSUBMENUGUID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_SubMenus_Menus] FOREIGN KEY ([FKMENUGUID]) REFERENCES [dbo].[MENUS] ([SMENUGUID])
);

