CREATE TABLE [dbo].[ERENTITYPROJECTSESSIONFILE] (
    [ERENTITYPROJECTSESSIONFILEID] CHAR (36)    NOT NULL,
    [ERENTITYPROJECTID]            VARCHAR (36) NOT NULL,
    [ERENTITYSESSIONID]            VARCHAR (36) NOT NULL,
    [ERPROJECTFILEVERSIONID]       CHAR (36)    NOT NULL,
    [ERENTITYPROJECTFILEID]        INT          NOT NULL,
    CONSTRAINT [PK_ERENTITYPROJECTSESSIONFILE] PRIMARY KEY NONCLUSTERED ([ERENTITYPROJECTSESSIONFILEID] ASC),
    CONSTRAINT [FK_ERENTITYPROJECTSESSIONFILE_ERENTITYPROJECT] FOREIGN KEY ([ERENTITYPROJECTID]) REFERENCES [dbo].[ERENTITYPROJECT] ([ERENTITYPROJECTID]),
    CONSTRAINT [FK_ERENTITYPROJECTSESSIONFILE_ERENTITYSESSION] FOREIGN KEY ([ERENTITYSESSIONID]) REFERENCES [dbo].[ERENTITYSESSION] ([ERENTITYSESSIONID]),
    CONSTRAINT [FK_ERENTITYPROJECTSESSIONFILE_ERPROJECTFILEVERSION] FOREIGN KEY ([ERPROJECTFILEVERSIONID]) REFERENCES [dbo].[ERPROJECTFILEVERSION] ([ERPROJECTFILEVERSIONID])
);


GO
CREATE NONCLUSTERED INDEX [IX_ERPROJECTFILEVERSIONID]
    ON [dbo].[ERENTITYPROJECTSESSIONFILE]([ERPROJECTFILEVERSIONID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_ERENTITYPROJECTID]
    ON [dbo].[ERENTITYPROJECTSESSIONFILE]([ERENTITYPROJECTID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_ERENTITYSESSIONID]
    ON [dbo].[ERENTITYPROJECTSESSIONFILE]([ERENTITYSESSIONID] ASC);

