CREATE TABLE [dbo].[ERENTITYSESSION] (
    [ERENTITYSESSIONID] VARCHAR (36)   NOT NULL,
    [SESSIONNAME]       VARCHAR (100)  NULL,
    [SESSIONSTATUSID]   INT            NULL,
    [PLSUBMITTALID]     CHAR (36)      NOT NULL,
    [APIRESPONSE]       NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_ERENTITYSESSION] PRIMARY KEY NONCLUSTERED ([ERENTITYSESSIONID] ASC),
    CONSTRAINT [FK_ERENTITYSESSION_PLSUBMITTAL] FOREIGN KEY ([PLSUBMITTALID]) REFERENCES [dbo].[PLSUBMITTAL] ([PLSUBMITTALID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PLSUBMITTALID]
    ON [dbo].[ERENTITYSESSION]([PLSUBMITTALID] ASC);

