CREATE TABLE [dbo].[ERFILEMARKUP] (
    [ERFILEMARKUPID]         CHAR (36)      NOT NULL,
    [ERENTITYSESSIONID]      VARCHAR (36)   NULL,
    [ERPROJECTFILEVERSIONID] CHAR (36)      NOT NULL,
    [MARKUPTYPE]             VARCHAR (50)   NOT NULL,
    [COMMENTS]               NVARCHAR (MAX) NOT NULL,
    [AUTHOR]                 VARCHAR (100)  NULL,
    [CREATEDBY]              CHAR (36)      NULL,
    [CREATEDON]              DATETIME       NOT NULL,
    [FILENAME]               VARCHAR (100)  NOT NULL,
    [PAGENUMBER]             INT            NOT NULL,
    PRIMARY KEY CLUSTERED ([ERFILEMARKUPID] ASC),
    CONSTRAINT [FK_FILEMARKUP_ERENTITYSESSION] FOREIGN KEY ([ERENTITYSESSIONID]) REFERENCES [dbo].[ERENTITYSESSION] ([ERENTITYSESSIONID]),
    CONSTRAINT [FK_FILEMARKUP_ERPROJECTFILEVERSION] FOREIGN KEY ([ERPROJECTFILEVERSIONID]) REFERENCES [dbo].[ERPROJECTFILEVERSION] ([ERPROJECTFILEVERSIONID])
);

