CREATE TABLE [dbo].[ERINTEGRATIONQUEUE] (
    [ERINTEGRATIONQUEUEID] CHAR (36)     NOT NULL,
    [ERENTITYPROJECTID]    VARCHAR (36)  NULL,
    [ERENTITYSESSIONID]    VARCHAR (36)  NULL,
    [PROCESSEDDATE]        DATETIME      NULL,
    [SUCCESS]              BIT           NULL,
    [CREATEDATE]           DATETIME      NOT NULL,
    [USERID]               CHAR (36)     NOT NULL,
    [RESULTLOG]            VARCHAR (MAX) NULL,
    [SENTTOBUS]            BIT           DEFAULT ((0)) NULL,
    [PROCESSTYPE]          INT           CONSTRAINT [DF_ERINTEGRATIONQUEUE_PROCESSTYPE] DEFAULT ((2)) NOT NULL,
    CONSTRAINT [PK_ERINTEGRATIONQUEUE] PRIMARY KEY CLUSTERED ([ERINTEGRATIONQUEUEID] ASC),
    CONSTRAINT [FK_ERINTEGRATIONQUEUE_ERENTITYPROJECT] FOREIGN KEY ([ERENTITYPROJECTID]) REFERENCES [dbo].[ERENTITYPROJECT] ([ERENTITYPROJECTID]),
    CONSTRAINT [FK_ERINTEGRATIONQUEUE_ERENTITYSESSION] FOREIGN KEY ([ERENTITYSESSIONID]) REFERENCES [dbo].[ERENTITYSESSION] ([ERENTITYSESSIONID]),
    CONSTRAINT [FK_ERINTEGRATIONQUEUE_USERS] FOREIGN KEY ([USERID]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);


GO
CREATE NONCLUSTERED INDEX [IX_ERINTEGRATIONQUEUE_ERENTITYSESSIONID_PROCESSTYPE]
    ON [dbo].[ERINTEGRATIONQUEUE]([ERENTITYSESSIONID] ASC, [PROCESSTYPE] ASC);

