CREATE TABLE [dbo].[ERMARKUPELEMENT] (
    [ERMARKUPELEMENTID]  CHAR (36)      NOT NULL,
    [PLPLANCORRECTIONID] CHAR (36)      NOT NULL,
    [PAGENUMBER]         INT            NOT NULL,
    [ELEMENTNUMBER]      INT            NULL,
    [COMMENTS]           NVARCHAR (MAX) NULL,
    [ELEMENTID]          NVARCHAR (50)  NULL,
    CONSTRAINT [PK_ERMarkupElement] PRIMARY KEY CLUSTERED ([ERMARKUPELEMENTID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_ERMarkup_Correction] FOREIGN KEY ([PLPLANCORRECTIONID]) REFERENCES [dbo].[PLPLANCORRECTION] ([PLPLANCORRECTIONID])
);

