CREATE TABLE [dbo].[ERPROJECTALERTS] (
    [ERPROJECTALERTSID] CHAR (36)     NOT NULL,
    [ERPROJECT]         CHAR (36)     NOT NULL,
    [ALERT]             VARCHAR (200) NULL,
    [ROWVERSION]        INT           NOT NULL,
    [ALERTDATE]         DATETIME      NULL,
    CONSTRAINT [PK_ERProjectAlerts] PRIMARY KEY CLUSTERED ([ERPROJECTALERTSID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_ERProjectAlerts_ERProject] FOREIGN KEY ([ERPROJECT]) REFERENCES [dbo].[ERPROJECT] ([ERPROJECTID])
);

