CREATE TABLE [dbo].[ERPROJECTFILEVERSION] (
    [ERPROJECTFILEVERSIONID] CHAR (36)      NOT NULL,
    [ERPROJECTFILEID]        CHAR (36)      NOT NULL,
    [ERPROJECTFILESTATUSID]  CHAR (36)      NOT NULL,
    [SAVEFILENAME]           NVARCHAR (200) NOT NULL,
    [PAGES]                  INT            NULL,
    [LOCKED]                 BIT            CONSTRAINT [DF_ERFileVersion_Locked] DEFAULT ((0)) NOT NULL,
    [FILEVERSION]            INT            NOT NULL,
    [CREATEDATE]             DATETIME       NOT NULL,
    [ROWVERSION]             INT            NOT NULL,
    [LASTCHANGEDON]          DATETIME       NULL,
    [LASTCHANGEDBY]          CHAR (36)      NULL,
    [LATEST]                 BIT            CONSTRAINT [DF_ERProjectFileVersion_Latest] DEFAULT ((1)) NOT NULL,
    [ALLOWVIEWCORRECTION]    BIT            CONSTRAINT [DF_ERProjectFileVersion_AllowViewCorrection] DEFAULT ((0)) NOT NULL,
    [MARKDELETE]             BIT            CONSTRAINT [DF_ERProjectFileVersion_MarkDelete] DEFAULT ((0)) NOT NULL,
    [SUBMITTED]              BIT            NULL,
    [LASTMODIFIED]           DATETIME       NULL,
    [SYSTEMTASKID]           CHAR (36)      NULL,
    [FILESTATUSID]           INT            NULL,
    [CREATEDBY]              CHAR (36)      NULL,
    [COMMENTS]               NVARCHAR (MAX) NULL,
    [ISFILESECURE]           BIT            NULL,
    [ISSELFSIGNED]           BIT            NULL,
    [ISTHIRDPARTYSIGNED]     BIT            NULL,
    [ORIGINFILENAME]         NVARCHAR (200) NULL,
    [NEEDATTENTION]          BIT            CONSTRAINT [DF_ERFileVersion_NeedAttention] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_ERProjectFileVersion] PRIMARY KEY CLUSTERED ([ERPROJECTFILEVERSIONID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_ERFileVersion_ERFile] FOREIGN KEY ([ERPROJECTFILEID]) REFERENCES [dbo].[ERPROJECTFILE] ([ERPROJECTFILEID]),
    CONSTRAINT [FK_ERFileVersion_ERFileStatus] FOREIGN KEY ([ERPROJECTFILESTATUSID]) REFERENCES [dbo].[ERPROJECTFILESTATUS] ([ERPROJECTFILESTATUSID]),
    CONSTRAINT [FK_ERProjectFileVersion_FileStatus] FOREIGN KEY ([FILESTATUSID]) REFERENCES [dbo].[FILESTATUS] ([FILESTATUSID]),
    CONSTRAINT [FK_ERProjectFileVersion_Users] FOREIGN KEY ([LASTCHANGEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID]),
    CONSTRAINT [FK_ERProjectFileVersion_Users_CreatedBy] FOREIGN KEY ([CREATEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);


GO
CREATE NONCLUSTERED INDEX [IX_ERPROJECTFILEVERSION_SYSTEMTASKID]
    ON [dbo].[ERPROJECTFILEVERSION]([SYSTEMTASKID] ASC);


GO
CREATE NONCLUSTERED INDEX [NCIDX_ERPROJECTFILEVERSION_MARKDELETE]
    ON [dbo].[ERPROJECTFILEVERSION]([MARKDELETE] ASC)
    INCLUDE([ERPROJECTFILEID], [SAVEFILENAME], [FILEVERSION], [CREATEDATE], [SYSTEMTASKID], [FILESTATUSID], [CREATEDBY]);


GO
CREATE NONCLUSTERED INDEX [NCIDX_ERPROJECTFILEVERSION_MARKDELETE_CREATEDBY]
    ON [dbo].[ERPROJECTFILEVERSION]([MARKDELETE] ASC, [CREATEDBY] ASC)
    INCLUDE([ERPROJECTFILEID], [SAVEFILENAME], [FILEVERSION], [CREATEDATE], [SYSTEMTASKID], [FILESTATUSID]);

