CREATE TABLE [dbo].[ERPROJECTFILEATTRIBUTETYPES] (
    [ERPROJECTFILEATTRIBUTETYPEID] INT           NOT NULL,
    [NAME]                         NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_ErProjectFileAttributeTypes] PRIMARY KEY CLUSTERED ([ERPROJECTFILEATTRIBUTETYPEID] ASC)
);

