CREATE TABLE [dbo].[ERPROJECTSTATUS] (
    [ERPROJECTSTATUSID]       CHAR (36)     NOT NULL,
    [NAME]                    NVARCHAR (50) NOT NULL,
    [ISDEFAULTSTATUS]         BIT           NULL,
    [ERPROJECTSYSTEMSTATUSID] INT           NOT NULL,
    CONSTRAINT [PK_ERProjectStatus] PRIMARY KEY CLUSTERED ([ERPROJECTSTATUSID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_ERProjStatus_SystemStat] FOREIGN KEY ([ERPROJECTSYSTEMSTATUSID]) REFERENCES [dbo].[ERPROJECTSYSTEMSTATUS] ([ERPROJECTSYSTEMSTATUSID])
);

