CREATE TABLE [dbo].[ERUPLOADPOSTQUEUE] (
    [ERUPLOADPOSTQUEUEID]     CHAR (36)       NOT NULL,
    [ERUPLOADFOLDERNAME]      NVARCHAR (1000) NULL,
    [ERUPLOADEFILENAME]       NVARCHAR (MAX)  NULL,
    [ERUPLOADENEWFILENAME]    NVARCHAR (MAX)  NULL,
    [ERUPLOADEORIGINFILENAME] NVARCHAR (MAX)  NULL,
    [CREATEDATE]              DATETIME        NOT NULL,
    [PROCESSDATE]             DATETIME        NULL,
    [RESULTLOG]               NVARCHAR (MAX)  NULL,
    [SENTTOBUS]               BIT             DEFAULT ((0)) NULL,
    CONSTRAINT [PK_ERUPLOADPOSTQUEUE] PRIMARY KEY CLUSTERED ([ERUPLOADPOSTQUEUEID] ASC)
);

