CREATE TABLE [dbo].[EXAMLINK] (
    [EXAMLINKID] INT           NOT NULL,
    [NAME]       NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_EXAMLINK] PRIMARY KEY CLUSTERED ([EXAMLINKID] ASC) WITH (FILLFACTOR = 90)
);

