CREATE TABLE [dbo].[EXAMRULE] (
    [EXAMRULEID]          CHAR (36)       NOT NULL,
    [TEXT]                NVARCHAR (2000) NOT NULL,
    [DESCRIPTION]         NVARCHAR (MAX)  NULL,
    [EXAMRULEVALUETYPEID] INT             NOT NULL,
    CONSTRAINT [PK_EXAMRULE] PRIMARY KEY CLUSTERED ([EXAMRULEID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_EXAMRULE_VALTYPE] FOREIGN KEY ([EXAMRULEVALUETYPEID]) REFERENCES [dbo].[EXAMRULEVALUETYPE] ([EXAMRULEVALUETYPEID])
);

