CREATE TABLE [dbo].[EXAMTYPERULE] (
    [EXAMTYPERULEID] CHAR (36)      NOT NULL,
    [EXAMTYPEID]     CHAR (36)      NOT NULL,
    [EXAMRULEID]     CHAR (36)      NOT NULL,
    [BITVALUE]       BIT            NULL,
    [STRINGVALUE]    NVARCHAR (500) NULL,
    [INTVALUE]       INT            NULL,
    CONSTRAINT [PK_EXAMTYPERULE] PRIMARY KEY NONCLUSTERED ([EXAMTYPERULEID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_EXAMTYPERULE_RULE] FOREIGN KEY ([EXAMRULEID]) REFERENCES [dbo].[EXAMRULE] ([EXAMRULEID]),
    CONSTRAINT [FK_EXAMTYPERULE_TYPE] FOREIGN KEY ([EXAMTYPEID]) REFERENCES [dbo].[EXAMTYPE] ([EXAMTYPEID])
);


GO
CREATE NONCLUSTERED INDEX [EXAMTYPERULE_IX_EXAMTYPEID]
    ON [dbo].[EXAMTYPERULE]([EXAMTYPEID] ASC);


GO

CREATE TRIGGER [TG_EXAMTYPERULE_UPDATE] ON [EXAMTYPERULE]
	AFTER UPDATE
AS
BEGIN
 INSERT INTO [HISTORYSYSTEMSETUP]
    (	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )

	SELECT
			[EXAMTYPE].[EXAMTYPEID],
			[EXAMTYPE].[ROWVERSION],
			GETUTCDATE(),
			[EXAMTYPE].[LASTCHANGEDBY],
			'Rule Setting - Bit Value',
			CASE [deleted].[BITVALUE] WHEN 1 THEN 'Yes' WHEN 0 THEN 'No'  ELSE '[none]' END,
			CASE [inserted].[BITVALUE] WHEN 1 THEN 'Yes' WHEN 0 THEN 'No'  ELSE '[none]' END,
			'Exam Type (' + [EXAMTYPE].[NAME] + '), Exam Rule ('+ [EXAMRULE].[TEXT] + ')',
			'B4DF1B5F-9A50-4053-8695-EE3A78674DCF',
			2,
			0,
			[EXAMRULE].[TEXT]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[EXAMTYPEID] = [inserted].[EXAMTYPEID]
			INNER JOIN [EXAMTYPE] ON [inserted].[EXAMTYPEID] = [EXAMTYPE].[EXAMTYPEID]
			INNER JOIN [EXAMRULE] ON [inserted].[EXAMRULEID] = [EXAMRULE].[EXAMRULEID]
	WHERE	([deleted].[BITVALUE] <> [inserted].[BITVALUE]) OR ([deleted].[BITVALUE] IS NULL AND [inserted].[BITVALUE] IS NOT NULL)
			OR ([deleted].[BITVALUE] IS NOT NULL AND [inserted].[BITVALUE] IS NULL)
	UNION ALL

	SELECT
			[EXAMTYPE].[EXAMTYPEID],
			[EXAMTYPE].[ROWVERSION],
			GETUTCDATE(),
			[EXAMTYPE].[LASTCHANGEDBY],
			'Rule Setting - String Value',
			ISNULL([deleted].[STRINGVALUE],'[none]'),
			ISNULL([inserted].[STRINGVALUE],'[none]'),
			'Exam Type (' + [EXAMTYPE].[NAME] + '), Exam Rule ('+ [EXAMRULE].[TEXT] + ')',
			'B4DF1B5F-9A50-4053-8695-EE3A78674DCF',
			2,
			0,
			[EXAMRULE].[TEXT]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[EXAMTYPEID] = [inserted].[EXAMTYPEID]
			INNER JOIN [EXAMTYPE] ON [inserted].[EXAMTYPEID] = [EXAMTYPE].[EXAMTYPEID]
			INNER JOIN [EXAMRULE] ON [inserted].[EXAMRULEID] = [EXAMRULE].[EXAMRULEID]
	WHERE	ISNULL([deleted].[STRINGVALUE],'') <> ISNULL([inserted].[STRINGVALUE],'')
	UNION ALL

	SELECT
			[EXAMTYPE].[EXAMTYPEID],
			[EXAMTYPE].[ROWVERSION],
			GETUTCDATE(),
			[EXAMTYPE].[LASTCHANGEDBY],
			'Rule Setting - Integer Value',
			ISNULL(CAST([deleted].[INTVALUE] AS NVARCHAR(255)),'[none]'),
			ISNULL(CAST([inserted].[INTVALUE]  AS NVARCHAR(255)),'[none]'),
			'Exam Type (' + [EXAMTYPE].[NAME] + '), Exam Rule ('+ [EXAMRULE].[TEXT] + ')',
			'B4DF1B5F-9A50-4053-8695-EE3A78674DCF',
			2,
			0,
			[EXAMRULE].[TEXT]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[EXAMTYPEID] = [inserted].[EXAMTYPEID]
			INNER JOIN [EXAMTYPE] ON [inserted].[EXAMTYPEID] = [EXAMTYPE].[EXAMTYPEID]
			INNER JOIN [EXAMRULE] ON [inserted].[EXAMRULEID] = [EXAMRULE].[EXAMRULEID]
	WHERE	ISNULL([deleted].[INTVALUE],'') <> ISNULL([inserted].[INTVALUE],'')
END