CREATE TABLE [dbo].[EXAMSITTING] (
    [EXAMSITTINGID]    CHAR (36)       NOT NULL,
    [EXAMTYPEID]       CHAR (36)       NOT NULL,
    [EXAMLOCATIONID]   CHAR (36)       NOT NULL,
    [EXAMFORMATID]     INT             NOT NULL,
    [EXAMSTATUSID]     CHAR (36)       NOT NULL,
    [SCHEDULEDDATE]    DATETIME        NOT NULL,
    [EXPIRATIONDATE]   DATETIME        NULL,
    [ADMINISTEREDBYID] CHAR (36)       NULL,
    [EXAMLINKID]       INT             NULL,
    [LINKID]           CHAR (36)       NULL,
    [LINKNUMBER]       NVARCHAR (50)   NULL,
    [LASTCHANGEDON]    DATETIME        NULL,
    [LASTCHANGEDBY]    CHAR (36)       NULL,
    [ROWVERSION]       INT             NOT NULL,
    [SCORE]            NUMERIC (10, 2) NULL,
    [SPECIALSITTING]   BIT             NOT NULL,
    [LOCATIONDETAILS]  NVARCHAR (MAX)  NULL,
    [SITTINGNUMBER]    NVARCHAR (50)   NOT NULL,
    [EXAMTIMESLOTID]   CHAR (36)       NOT NULL,
    [EXAMFORMATTYPEID] INT             NULL,
    [EXAMVERSIONID]    CHAR (36)       NULL,
    [EXAMREQUESTID]    CHAR (36)       NULL,
    CONSTRAINT [PK_EXAMSITTING] PRIMARY KEY NONCLUSTERED ([EXAMSITTINGID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_EXAMSITTING_EXAMREQUEST] FOREIGN KEY ([EXAMREQUESTID]) REFERENCES [dbo].[EXAMREQUEST] ([EXAMREQUESTID]),
    CONSTRAINT [FK_EXAMSITTING_EXAMVERSION] FOREIGN KEY ([EXAMVERSIONID]) REFERENCES [dbo].[EXAMVERSION] ([EXAMVERSIONID]),
    CONSTRAINT [FK_EXAMSITTING_FORMAT] FOREIGN KEY ([EXAMFORMATID]) REFERENCES [dbo].[EXAMFORMAT] ([EXAMFORMATID]),
    CONSTRAINT [FK_EXAMSITTING_FORMATTYPE] FOREIGN KEY ([EXAMFORMATTYPEID]) REFERENCES [dbo].[EXAMFORMATTYPE] ([EXAMFORMATTYPEID]),
    CONSTRAINT [FK_EXAMSITTING_LINK] FOREIGN KEY ([EXAMLINKID]) REFERENCES [dbo].[EXAMLINK] ([EXAMLINKID]),
    CONSTRAINT [FK_EXAMSITTING_LOCATION] FOREIGN KEY ([EXAMLOCATIONID]) REFERENCES [dbo].[EXAMLOCATION] ([EXAMLOCATIONID]),
    CONSTRAINT [FK_EXAMSITTING_STATUS] FOREIGN KEY ([EXAMSTATUSID]) REFERENCES [dbo].[EXAMSTATUS] ([EXAMSTATUSID]),
    CONSTRAINT [FK_EXAMSITTING_TIMESLOT] FOREIGN KEY ([EXAMTIMESLOTID]) REFERENCES [dbo].[EXAMTIMESLOT] ([EXAMTIMESLOTID]),
    CONSTRAINT [FK_EXAMSITTING_TYPE] FOREIGN KEY ([EXAMTYPEID]) REFERENCES [dbo].[EXAMTYPE] ([EXAMTYPEID]),
    CONSTRAINT [FK_EXAMSITTING_USERS] FOREIGN KEY ([ADMINISTEREDBYID]) REFERENCES [dbo].[USERS] ([SUSERGUID]),
    CONSTRAINT [FK_EXAMSITTING_USERS1] FOREIGN KEY ([LASTCHANGEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);


GO
CREATE NONCLUSTERED INDEX [IX_EXAMSITTING_LASTCHANGEDON]
    ON [dbo].[EXAMSITTING]([LASTCHANGEDON] ASC)
    INCLUDE([EXAMSITTINGID]);


GO

CREATE TRIGGER [TG_EXAMSITTING_UPDATE_ELASTIC] ON  EXAMSITTING
   AFTER UPDATE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [ELASTICSEARCHOBJECT]
    ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID() ,
		[Inserted].[EXAMSITTINGID] ,
        'EnerGovBusiness.SystemSetup.ExamSitting' ,
        [Inserted].[ROWVERSION] ,
        GETDATE() ,
        NULL ,
        2 ,
        (SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Inserted];

END
GO

CREATE TRIGGER [TG_EXAMSITTING_INSERT_ELASTIC] ON  EXAMSITTING
   AFTER INSERT
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [ELASTICSEARCHOBJECT]
    ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID() ,
		[Inserted].[EXAMSITTINGID] ,
        'EnerGovBusiness.SystemSetup.ExamSitting' ,
        [Inserted].[ROWVERSION] ,
        GETDATE() ,
        NULL ,
        1 ,
        (SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Inserted];

END
GO

CREATE TRIGGER [TG_EXAMSITTING_DELETE_ELASTIC] ON  EXAMSITTING
   AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [ELASTICSEARCHOBJECT]
    ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID() ,
		[Deleted].[EXAMSITTINGID] ,
        'EnerGovBusiness.SystemSetup.ExamSitting' ,
        [Deleted].[ROWVERSION] ,
        GETDATE() ,
        NULL ,
        3 ,
        (SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Deleted];

END