CREATE TABLE [dbo].[EXAMSITTINGWFXREF] (
    [EXAMSITTINGWFXREFID] CHAR (36)      NOT NULL,
    [EXAMSITTINGID]       CHAR (36)      NOT NULL,
    [EXAMSITTINGWFMSG]    NVARCHAR (200) NULL,
    CONSTRAINT [PK_EXAMSITTINGWFXREF] PRIMARY KEY NONCLUSTERED ([EXAMSITTINGWFXREFID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_EXAMSITTINGWFXREF_SITTING] FOREIGN KEY ([EXAMSITTINGID]) REFERENCES [dbo].[EXAMSITTING] ([EXAMSITTINGID])
);

