CREATE PROCEDURE [dbo].LINKED_REQUEST_DETAIL
	@ENTITY_ID AS CHAR(36),
	@MODULE_TYPE as VARCHAR(36),
	@FROM INT = 1,
	@TO INT,
	@PAGE_SIZE INT = 20,
	@SORT_FIELD VARCHAR(36),
	@IS_ASC BIT = 1,
	@USER_ID as CHAR(36)
AS
declare @DATA TABLE 
(
	CITIZENREQUESTID char(36)
)	
	IF (@MODULE_TYPE = 'ContactManagement')
	BEGIN
		INSERT INTO @DATA
		SELECT * FROM DBO.LINKEDREQUESTFROMCONTACT(@ENTITY_ID,@USER_ID)
	END
	IF (@MODULE_TYPE = 'CodeManagement')
	BEGIN
		INSERT INTO @DATA
		SELECT * FROM DBO.LINKEDREQUESTFROMCODECASE(@ENTITY_ID,@USER_ID)
	END
	IF (@MODULE_TYPE = 'ProjectManagement')
	BEGIN
		INSERT INTO @DATA
		SELECT * FROM DBO.LINKEDREQUESTFROMPROJECT(@ENTITY_ID,@USER_ID)
	END
	IF (@MODULE_TYPE = 'PropertyManagement')
	BEGIN
		INSERT INTO @DATA
		SELECT * FROM DBO.LINKEDREQUESTFROMPROPERTYMANAGEMENT(@ENTITY_ID,@USER_ID)
	END
BEGIN
WITH  ALLREQUESTSDETAILS AS (
SELECT DISTINCT request.CITIZENREQUESTID, request.REQUESTNUMBER, requestType.NAME REQUESTTYPE, requestStatus.STATUS, request.DATEFILED, request.COMPDEADLINE, request.COMPCOMPLETE
FROM CITIZENREQUEST request
INNER JOIN CITIZENREQUESTTYPE requestType on request.CITIZENREQUESTTYPEID = requestType.CITIZENREQUESTTYPEID
INNER JOIN CITIZENREQUESTSTATUS requestStatus on request.CITIZENREQUESTSTATUSID = requestStatus.CITIZENREQUESTSTATUSID
WHERE request.CITIZENREQUESTID in (select CITIZENREQUESTID from @DATA)),
NUMBEREDDATA AS (
SELECT CITIZENREQUESTID, REQUESTNUMBER,REQUESTTYPE,STATUS,DATEFILED,COMPDEADLINE,COMPCOMPLETE,
ROW_NUMBER() OVER(
ORDER BY
case when @is_asc = 1 AND @Sort_Field = 'REQUESTNUMBER' then REQUESTNUMBER END ASC, 
case when @is_asc = 0 AND @Sort_Field = 'REQUESTNUMBER' then REQUESTNUMBER END DESC,
case when @is_asc = 1 AND @Sort_Field = 'REQUESTTYPE' then REQUESTTYPE END ASC, 
case when @is_asc = 0 AND @Sort_Field = 'REQUESTTYPE' then REQUESTTYPE END DESC, 
case when @is_asc = 1 AND @Sort_Field = 'STATUS' then STATUS END ASC, 
case when @is_asc = 0 AND @Sort_Field = 'STATUS' then STATUS END DESC,
case when @is_asc = 1 AND @Sort_Field = 'STATUS' then STATUS END ASC, 
case when @is_asc = 0 AND @Sort_Field = 'STATUS' then STATUS END DESC,
case when @is_asc = 1 AND @Sort_Field = 'DATEFILED' then DATEFILED END ASC, 
case when @is_asc = 0 AND @Sort_Field = 'DATEFILED' then DATEFILED END DESC,
case when @is_asc = 1 AND @Sort_Field = 'COMPDEADLINE' then COMPDEADLINE END ASC, 
case when @is_asc = 0 AND @Sort_Field = 'COMPDEADLINE' then COMPDEADLINE END DESC,
case when @is_asc = 1 AND @Sort_Field = 'COMPCOMPLETE' then COMPCOMPLETE END ASC, 
case when @is_asc = 0 AND @Sort_Field = 'COMPCOMPLETE' then COMPCOMPLETE END DESC)
AS ROWNUMBER , COUNT(1) OVER() AS TOTAL_ROWS
from ALLREQUESTSDETAILS)
select * from NUMBEREDDATA WHERE ROWNUMBER > @FROM AND ROWNUMBER <= @TO
END