CREATE PROCEDURE [dbo].LINKED_RENTAL_PROPERTIES_DETAIL
	@ENTITY_ID AS CHAR(36),
	@MODULE_TYPE as char(36),
	@FROM INT = 1,
	@TO INT,
	@PAGE_SIZE INT = 20,
	@SORT_FIELD VARCHAR(36),
	@IS_ASC BIT = 1,
	@USER_ID as char(36)
AS
declare @DATA TABLE 
(
	RPPROPERTYID char(36)
)	
	IF (@MODULE_TYPE = 'ContactManagement')
	BEGIN
		INSERT INTO @DATA
		SELECT * FROM DBO.LINKEDRENTALPROPERTIESFROMCONTACT(@ENTITY_ID, @USER_ID)
	END
	IF (@MODULE_TYPE = 'PropertyManagement')
	BEGIN
		INSERT INTO @DATA
		SELECT * FROM DBO.LINKEDRENTALPROPERTIESFROMPROPERTYMANAGEMENT(@ENTITY_ID, @USER_ID)
	END

BEGIN
WITH LINKEDRENTALPROPERTIES AS(select RPPROPERTYID FROM @DATA), 
ALLRENTALPROPERTIESDETAILS AS (
SELECT rp.RPPROPERTYID, rp.PROPERTYNUMBER, rp.DESCRIPTION, rpt.NAME as PROPERTYTYPE, rpst.NAME as STATUS, rp.NUMBEROFUNITS, rp.APPLICATIONDATE, rp.ISSUEDATE, rp.EXPIRATIONDATE, rp.LASTINSPECTIONDATE
FROM RPPROPERTY rp
INNER JOIN RPPROPERTYSTATUS rpst ON rp.RPPROPERTYSTATUSID = rpst.RPPROPERTYSTATUSID
INNER JOIN RPPROPERTYTYPE rpt on rp.RPPROPERTYTYPEID = rpt.RPPROPERTYTYPEID
WHERE rp.RPPROPERTYID IN (SELECT RPPROPERTYID FROM LINKEDRENTALPROPERTIES)),
NUMBEREDDATA AS (SELECT ALLRENTALPROPERTIESDETAILS.RPPROPERTYID,PROPERTYTYPE, PROPERTYNUMBER,DESCRIPTION,NUMBEROFUNITS,STATUS,APPLICATIONDATE,ISSUEDATE,EXPIRATIONDATE, LASTINSPECTIONDATE,
ROW_NUMBER() OVER(
ORDER BY
case when @is_asc = 1 AND @Sort_Field = 'PROPERTYNUMBER' then PROPERTYNUMBER END ASC, 
case when @is_asc = 0 AND @Sort_Field = 'PROPERTYNUMBER' then PROPERTYNUMBER END DESC,
case when @is_asc = 1 AND @Sort_Field = 'PROPERTYTYPE' then PROPERTYTYPE END ASC, 
case when @is_asc = 0 AND @Sort_Field = 'PROPERTYTYPE' then PROPERTYTYPE END DESC,
case when @is_asc = 1 AND @Sort_Field = 'DESCRIPTION' then DESCRIPTION END ASC, 
case when @is_asc = 0 AND @Sort_Field = 'DESCRIPTION' then DESCRIPTION END DESC, 
case when @is_asc = 1 AND @Sort_Field = 'NUMBEROFUNITS' then NUMBEROFUNITS END ASC, 
case when @is_asc = 0 AND @Sort_Field = 'NUMBEROFUNITS' then NUMBEROFUNITS END DESC,
case when @is_asc = 1 AND @Sort_Field = 'STATUS' then STATUS END ASC, 
case when @is_asc = 0 AND @Sort_Field = 'STATUS' then STATUS END DESC,
case when @is_asc = 1 AND @Sort_Field = 'APPLICATIONDATE' then APPLICATIONDATE END ASC, 
case when @is_asc = 0 AND @Sort_Field = 'APPLICATIONDATE' then APPLICATIONDATE END DESC,
case when @is_asc = 1 AND @Sort_Field = 'ISSUEDATE' then ISSUEDATE END ASC, 
case when @is_asc = 0 AND @Sort_Field = 'ISSUEDATE' then ISSUEDATE END DESC,
case when @is_asc = 1 AND @Sort_Field = 'LASTINSPECTIONDATE' then LASTINSPECTIONDATE END ASC, 
case when @is_asc = 0 AND @Sort_Field = 'LASTINSPECTIONDATE' then LASTINSPECTIONDATE END DESC,
case when @is_asc = 1 AND @Sort_Field = 'EXPIRATIONDATE' then EXPIRATIONDATE END ASC, 
case when @is_asc = 0 AND @Sort_Field = 'EXPIRATIONDATE' then EXPIRATIONDATE END DESC)
AS ROWNUMBER , COUNT(1) OVER() AS TOTAL_ROWS
from ALLRENTALPROPERTIESDETAILS INNER JOIN LINKEDRENTALPROPERTIES on ALLRENTALPROPERTIESDETAILS.RPPROPERTYID = LINKEDRENTALPROPERTIES.RPPROPERTYID)
select * from NUMBEREDDATA WHERE ROWNUMBER > @FROM AND ROWNUMBER <= @TO
END