CREATE PROCEDURE [dbo].[LINKED_LAND_LORD_LICENSES_DETAIL]
	@ENTITY_ID as char(36),
	@FROM INT = 1,
	@TO INT,
	@PAGE_SIZE INT = 20,
	@SORT_FIELD char(36),
	@IS_ASC BIT = 1,
	@USER_ID AS CHAR(36)

AS
declare @DATA TABLE 
(
	RPLANDLORDLICENSEID char(36)
)
	BEGIN
		INSERT INTO @DATA
		SELECT * FROM DBO.LINKEDLANDLORDLICENSEFROMCONTACT(@ENTITY_ID, @USER_ID)
	END
BEGIN
		
		with LINKEDLANDLORDLICENSES AS( select RPLANDLORDLICENSEID FROM @DATA), 
		ALLLICENSES as (select llicense.RPLANDLORDLICENSEID, llicense.LANDLORDNUMBER, llicense.DESCRIPTION, licenseType.NAME as LICENSETYPE, licenseStatus.NAME as STATUS, llicense.APPLICATIONDATE, llicense.ISSUEDATE  from RPLANDLORDLICENSE llicense  
		INNER JOIN RPLANDLORDLICENSETYPE licenseType on llicense.RPLANDLORDLICENSETYPEID = licenseType.RPLANDLORDLICENSETYPEID  
		INNER JOIN RPLANDLORDLICENSESTATUS licenseStatus on llicense.RPLANDLORDLICENSESTATUSID = licenseStatus.RPLANDLORDLICENSESTATUSID
		where llicense.RPLANDLORDLICENSEID in (SELECT RPLANDLORDLICENSEID from LINKEDLANDLORDLICENSES)),  
		NUMBEREDDATA as (select ALLLICENSES.RPLANDLORDLICENSEID,LANDLORDNUMBER,DESCRIPTION,LICENSETYPE,STATUS, APPLICATIONDATE,ISSUEDATE,
		ROW_NUMBER() OVER(ORDER BY  
		case when @is_asc = 1 AND @Sort_Field = 'LANDLORDNUMBER' then LANDLORDNUMBER END ASC,  
		case when @is_asc = 0 AND @Sort_Field = 'LANDLORDNUMBER' then LANDLORDNUMBER END DESC,  
		case when @is_asc = 1 AND @Sort_Field = 'DESCRIPTION' then DESCRIPTION END ASC,  
		case when @is_asc = 0 AND @Sort_Field = 'DESCRIPTION' then DESCRIPTION END DESC,  
		case when @is_asc = 1 AND @Sort_Field = 'LICENSETYPE' then LICENSETYPE END ASC,  
		case when @is_asc = 0 AND @Sort_Field = 'LICENSETYPE' then LICENSETYPE END DESC,  
		case when @is_asc = 1 AND @Sort_Field = 'STATUS' then STATUS END ASC,  
		case when @is_asc = 0 AND @Sort_Field = 'STATUS' then STATUS END DESC,  
		case when @is_asc = 1 AND @Sort_Field = 'APPLICATIONDATE' then APPLICATIONDATE END ASC,  
		case when @is_asc = 0 AND @Sort_Field = 'APPLICATIONDATE' then APPLICATIONDATE END DESC,  
		case when @is_asc = 1 AND @Sort_Field = 'ISSUEDATE' then ISSUEDATE END ASC,  
		case when @is_asc = 0 AND @Sort_Field = 'ISSUEDATE' then ISSUEDATE END DESC)  
		AS ROWNUMBER, COUNT(1) OVER() AS TOTAL_ROWS from ALLLICENSES  
		INNER JOIN LINKEDLANDLORDLICENSES on ALLLICENSES.RPLANDLORDLICENSEID = LINKEDLANDLORDLICENSES.RPLANDLORDLICENSEID)  
		select * from NUMBEREDDATA WHERE ROWNUMBER > @From AND ROWNUMBER <= @To 
END