CREATE PROCEDURE [dbo].[USP_LANDMANAGEMENTCONTACTTYPE_DELETE]
(
	@LANDMANAGEMENTCONTACTTYPEID CHAR(36),
	@ROWVERSION INT
)
AS
DELETE FROM [dbo].[LANDMANAGEMENTCONTACTTYPE]
WHERE
	[LANDMANAGEMENTCONTACTTYPEID] = @LANDMANAGEMENTCONTACTTYPEID AND 
	[ROWVERSION]= @ROWVERSION