CREATE PROCEDURE [dbo].[USP_LICENSECYCLERECURRENCESETUP_INSERT]
(
	@LICENSECYCLERECURRENCESETUPID CHAR(36),
	@NAME NVARCHAR(50),
	@DESCRIPTION NVARCHAR(MAX),
	@RECURRENCEID CHAR(36),
	@LICENSECYCLETYPEID INT,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
INSERT INTO [dbo].[LICENSECYCLERECURRENCESETUP](
	[LICENSECYCLERECURRENCESETUPID],
	[NAME],
	[DESCRIPTION],
	[RECURRENCEID],
	[LICENSECYCLETYPEID],
	[LASTCHANGEDBY],
	[LASTCHANGEDON],
	[ROWVERSION]
)
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
VALUES
(
	@LICENSECYCLERECURRENCESETUPID,
	@NAME,
	@DESCRIPTION,
	@RECURRENCEID,
	@LICENSECYCLETYPEID,
	@LASTCHANGEDBY,
	@LASTCHANGEDON,
	@ROWVERSION
)
SELECT * FROM @OUTPUTTABLE