CREATE PROCEDURE [dbo].[USP_LICENSECYCLE_INSERT]
(
	@LICENSECYCLEID CHAR(36),
	@NAME NVARCHAR(50),
	@DESCRIPTION NVARCHAR(MAX),
	@CHARGERENEWALFEE BIT,
	@RENEWALCYCLEID CHAR(36),
	@RENEWALDEADLINEID CHAR(36),
	@INVOICEDEADLINEID CHAR(36),
	@ROWVERSION INT,
	@LASTCHANGEDON DATETIME,
	@LASTCHANGEDBY CHAR(36)
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
INSERT INTO [dbo].[LICENSECYCLE](
	[LICENSECYCLEID],
	[NAME],
	[DESCRIPTION],
	[CHARGERENEWALFEE],
	[RENEWALCYCLEID],
	[RENEWALDEADLINEID],
	[INVOICEDEADLINEID],
	[ROWVERSION],
	[LASTCHANGEDON],
	[LASTCHANGEDBY]
)
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
VALUES
(
	@LICENSECYCLEID,
	@NAME,
	@DESCRIPTION,
	@CHARGERENEWALFEE,
	@RENEWALCYCLEID,
	@RENEWALDEADLINEID,
	@INVOICEDEADLINEID,
	@ROWVERSION,
	@LASTCHANGEDON,
	@LASTCHANGEDBY
)
SELECT * FROM @OUTPUTTABLE