CREATE PROCEDURE [dbo].[USP_LICENSECYCLE_UPDATE]
(
	@LICENSECYCLEID CHAR(36),
	@NAME NVARCHAR(50),
	@DESCRIPTION NVARCHAR(MAX),
	@CHARGERENEWALFEE BIT,
	@RENEWALCYCLEID CHAR(36),
	@RENEWALDEADLINEID CHAR(36),
	@INVOICEDEADLINEID CHAR(36),
	@ROWVERSION INT,
	@LASTCHANGEDON DATETIME,
	@LASTCHANGEDBY CHAR(36)
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
UPDATE [dbo].[LICENSECYCLE] SET
	[NAME] = @NAME,
	[DESCRIPTION] = @DESCRIPTION,
	[CHARGERENEWALFEE] = @CHARGERENEWALFEE,
	[RENEWALCYCLEID] = @RENEWALCYCLEID,
	[RENEWALDEADLINEID] = @RENEWALDEADLINEID,
	[INVOICEDEADLINEID] = @INVOICEDEADLINEID,
	[ROWVERSION] = @ROWVERSION + 1,
	[LASTCHANGEDON] = @LASTCHANGEDON,
	[LASTCHANGEDBY] = @LASTCHANGEDBY
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE
	[LICENSECYCLEID] = @LICENSECYCLEID AND 
	[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE