CREATE  PROCEDURE [systemsettingsmanager].[USP_TEAM_GETALL]  
AS  
BEGIN 
SET NOCOUNT ON;
 SELECT
	 [TEAM].[TEAMID],
	 [TEAM].[NAME],
	 [TEAM].[TEAMIMAGE],
	 [TEAM].[USERID],
	 [USERS].[FNAME],
	 [USERS].[LNAME]
 FROM
	[dbo].[TEAM]
	INNER JOIN [dbo].[USERS] WITH (NOLOCK) ON [USERS].[SUSERGUID] = [TEAM].[USERID]
END