CREATE  PROCEDURE [systemsettingsmanager].[USP_RESOURCETYPE_GETALL]    
AS  
BEGIN     
SET NOCOUNT ON;
 SELECT   
 [RESOURCETYPE].[RESOURCETYPEID],  
 [RESOURCETYPE].[NAME]  
  FROM  [dbo].[RESOURCETYPE] WITH (NOLOCK)    
 ORDER BY [RESOURCETYPE].[NAME]  
END