CREATE PROCEDURE [energovnotifications].[USP_TASKUSER_BY_TASKID]
(
	@TASKID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[TASKUSER].[TASKUSERID],
	[dbo].[TASKUSER].[TASKID],
	[dbo].[TASKUSER].[USERID],
	[dbo].[USERS].[FNAME],
	[dbo].[USERS].[LNAME]
FROM [dbo].[TASKUSER] INNER JOIN [dbo].[USERS]
ON [dbo].[TASKUSER].[USERID] = [dbo].[USERS].[SUSERGUID]
WHERE
	[dbo].[TASKUSER].[TASKID] = @TASKID 
ORDER BY [dbo].[USERS].[LNAME], [dbo].[USERS].[FNAME]
END