CREATE PROCEDURE [energovnotifications].[USP_MYCALENDARHEARING_GETBYCRITERIA]
(
	@USERID CHAR(36),
	@STARTDATE DATETIME,
	@ENDDATE DATETIME
)
AS
BEGIN
SET NOCOUNT ON;
	SELECT DISTINCT
	[dbo].[HEARING].[HEARINGID],
	CASE WHEN [dbo].[HEARINGTYPE].[RECURRENCEID] IS NULL then [dbo].[HEARING].[SUBJECT] ELSE [dbo].[HEARINGTYPE].[NAME]  END as SUBJECT,
	[dbo].[HEARING].[HEARINGTYPEID],
	[dbo].[HEARING].[STARTDATE],
	[dbo].[HEARING].[ENDDATE],
	[dbo].[HEARING].[SHOWONCALENDAR],	
	[dbo].[HEARING].[ROWVERSION],
	CAST(CASE WHEN [dbo].[HEARINGTYPE].[RECURRENCEID] IS NULL THEN 0 ELSE 1 END AS BIT) AS ISRECURRENCE
	FROM [dbo].[HEARING]
	JOIN [dbo].[HEARINGATTENDEE] on [dbo].[HEARING].[HEARINGID] = [dbo].[HEARINGATTENDEE].[HEARINGID]
	JOIN [dbo].[HEARINGTYPE] on [dbo].[HEARING].[HEARINGTYPEID] = [dbo].[HEARINGTYPE].[HEARINGTYPEID]
	JOIN [dbo].[USERS] on [dbo].[HEARINGATTENDEE].[ATTENDEEID] = [dbo].[USERS].[SUSERGUID]
	WHERE
	 [dbo].[HEARING].[SHOWONCALENDAR] = 1 
	 AND ([dbo].[HEARINGATTENDEE].[ATTENDEEID] IS NOT NULL AND  
	 [dbo].[HEARINGATTENDEE].[ATTENDEEID] = @USERID AND [dbo].[HEARINGATTENDEE].[ISUSER] = 1)	
	AND (([dbo].[HEARING].[ENDDATE] >= @STARTDATE AND [dbo].[HEARING].[STARTDATE] < @ENDDATE))

END