CREATE PROCEDURE [energovnotifications].[USP_MYCALENDARMEETING_GETBYCRITERIA]
(
	@USERID CHAR(36),
	@STARTDATE DATETIME,
	@ENDDATE DATETIME
)
AS
BEGIN
SET NOCOUNT ON;
	SELECT DISTINCT
	[dbo].[MEETING].[MEETINGID],
	CASE WHEN [dbo].[MEETINGTYPE].[RECURRENCEID] IS NULL then [dbo].[MEETING].[SUBJECT] ELSE [dbo].[MEETINGTYPE].[NAME]  END as SUBJECT,
	[dbo].[MEETING].[MEETINGTYPEID],
	[dbo].[MEETING].[STARTDATE],
	[dbo].[MEETING].[ENDDATE],
	[dbo].[MEETING].[SHOWONCALENDAR],
	[dbo].[MEETING].[ROWVERSION],
	CAST(CASE WHEN [dbo].[MEETINGTYPE].[RECURRENCEID] IS NULL THEN 0 ELSE 1 END AS BIT) AS ISRECURRENCE
	FROM [dbo].[MEETING]
	JOIN [dbo].[MEETINGATTENDEE] on [dbo].[MEETING].[MEETINGID] = [dbo].[MEETINGATTENDEE].[HEARINGID]
	JOIN [dbo].[MEETINGTYPE] on [dbo].[MEETING].[MEETINGTYPEID] = [dbo].[MEETINGTYPE].[MEETINGTYPEID]
	JOIN [dbo].[USERS] on [dbo].[MEETINGATTENDEE].[ATTENDEEID] = [dbo].[USERS].[SUSERGUID]
	WHERE
		 [dbo].[MEETING].[SHOWONCALENDAR] = 1 
	 AND ([dbo].[MEETINGATTENDEE].[ATTENDEEID] IS NOT NULL AND  
	 [dbo].[MEETINGATTENDEE].[ATTENDEEID] = @USERID AND [dbo].[MEETINGATTENDEE].[ISUSER] = 1)	
	AND (([dbo].[MEETING].[ENDDATE] >= @STARTDATE AND [dbo].[MEETING].[STARTDATE] < @ENDDATE))

END