CREATE PROCEDURE [energovnotifications].[USP_TASKASSINGEDTOUSER_FILTERS_BYTASKSTATUS]
(
	@USERID CHAR(36),
	@ISTASKCOMPLETED AS BIT = NULL,
	@ISTASKCREATEDBYME AS BIT = 0
)
AS
BEGIN

SET NOCOUNT ON;

SELECT DISTINCT 
	[dbo].[USERS].[SUSERGUID],
	(COALESCE([dbo].[USERS].[FNAME] + ' ', '') + [dbo].[USERS].[LNAME]) AS ASSIGNEDTOUSER
FROM 
	[dbo].[TASK]
JOIN 
	[dbo].[TASKSTATUS] ON [dbo].[TASK].[TASKSTATUSID] = [dbo].[TASKSTATUS].[TASKSTATUSID]
LEFT JOIN 
	[dbo].[TASKUSER] ON [dbo].[TASK].[TASKID] = [dbo].[TASKUSER].[TASKID]
LEFT JOIN 
	[dbo].[USERS] ON [dbo].[TASKUSER].[USERID] = [dbo].[USERS].[SUSERGUID]
WHERE
	(@ISTASKCOMPLETED IS NULL OR ([dbo].[TASKSTATUS].[ISCOMPLETED] = @ISTASKCOMPLETED) AND [dbo].[USERS].[SUSERGUID]  IS NOT NULL)
	AND [dbo].[TASK].[TASKID] IN 
	(
		SELECT DISTINCT 
			[dbo].[TASK].[TASKID]
		FROM [dbo].[TASK]
		LEFT JOIN [dbo].[TASKUSER] ON [dbo].[TASKUSER].[TASKID] = [dbo].[TASK].[TASKID]
		WHERE 			
			(@ISTASKCREATEDBYME = 0 AND [dbo].[TASKUSER].[USERID] = @USERID) OR 
			(@ISTASKCREATEDBYME = 1 AND [dbo].[TASK].[CREATEDBYID] = @USERID)
	)
ORDER BY 
	ASSIGNEDTOUSER
END