CREATE PROCEDURE [energovnotifications].[USP_GLOBALMEETINGTYPE_GETALL]
AS
BEGIN
SET NOCOUNT ON;
	SELECT DISTINCT	
	[dbo].[MEETINGTYPE].[MEETINGTYPEID],
	[dbo].[MEETINGTYPE].[NAME]
	FROM [dbo].[MEETINGTYPE]
	ORDER BY [dbo].[MEETINGTYPE].[NAME]
END