CREATE TABLE [dbo].[DECISIONADDRESS] (
    [DECISIONADDRESSID] CHAR (36)     NOT NULL,
    [REQUIRED]          BIT           NULL,
    [INSTRUCTIONS]      VARCHAR (MAX) NULL,
    [ALLOWMANUALENTRY]  BIT           NULL,
    CONSTRAINT [PK_DECISIONADDRESS] PRIMARY KEY CLUSTERED ([DECISIONADDRESSID] ASC) WITH (FILLFACTOR = 90)
);

