CREATE TABLE [dbo].[DECISIONENTRYPAGE] (
    [DECISIONENTRYPAGEID] CHAR (36) NOT NULL,
    [DECISIONENTRYID]     CHAR (36) NOT NULL,
    [DECISIONPAGEID]      CHAR (36) NOT NULL,
    CONSTRAINT [PK_DecisionEntryPage] PRIMARY KEY CLUSTERED ([DECISIONENTRYPAGEID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_DecisionEntry_Page] FOREIGN KEY ([DECISIONPAGEID]) REFERENCES [dbo].[DECISIONPAGE] ([DECISIONPAGEID]),
    CONSTRAINT [FK_Page_DecisionEntry] FOREIGN KEY ([DECISIONENTRYID]) REFERENCES [dbo].[DECISIONENTRY] ([DECISIONENTRYID])
);

