CREATE TABLE [dbo].[DECISIONREQUEST] (
    [DECISIONREQUESTID]      CHAR (36)      NOT NULL,
    [CITIZENREQUESTTYPEID]   CHAR (36)      CONSTRAINT [DF_DECISIONREQUEST_CITIZENREQUESTTYPEID] DEFAULT (newid()) NULL,
    [CITIZENREQUESTSTATUSID] CHAR (36)      CONSTRAINT [DF_DECISIONREQUEST_CITIZENREQUESTSTATUSID] DEFAULT (newid()) NULL,
    [ASSIGNEDTO]             CHAR (36)      NULL,
    [DISTRICTID]             CHAR (36)      NULL,
    [REQUIREDUPLOADS]        INT            CONSTRAINT [DF_DECISIONREQUEST_REQUIREDUPLOADS] DEFAULT ((0)) NOT NULL,
    [UPLOADINFO]             NVARCHAR (MAX) CONSTRAINT [DF_DECISIONREQUEST_UPLOADINFO] DEFAULT ('') NOT NULL,
    [CITIZENREQUESTSOURCEID] CHAR (36)      NULL,
    CONSTRAINT [PK_DECISIONREQUEST] PRIMARY KEY CLUSTERED ([DECISIONREQUESTID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_DECISIONREQUEST_CRSOURCE] FOREIGN KEY ([CITIZENREQUESTSOURCEID]) REFERENCES [dbo].[CITIZENREQUESTSOURCE] ([CITIZENREQUESTSOURCEID]),
    CONSTRAINT [FK_DECISIONREQUEST_CRSTATUS] FOREIGN KEY ([CITIZENREQUESTSTATUSID]) REFERENCES [dbo].[CITIZENREQUESTSTATUS] ([CITIZENREQUESTSTATUSID]),
    CONSTRAINT [FK_DECISIONREQUEST_CRTYPE] FOREIGN KEY ([CITIZENREQUESTTYPEID]) REFERENCES [dbo].[CITIZENREQUESTTYPE] ([CITIZENREQUESTTYPEID]),
    CONSTRAINT [FK_DECISIONREQUEST_DISTRICT] FOREIGN KEY ([DISTRICTID]) REFERENCES [dbo].[DISTRICT] ([DISTRICTID]),
    CONSTRAINT [FK_DECISIONREQUEST_USERS] FOREIGN KEY ([ASSIGNEDTO]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);

