CREATE TABLE [dbo].[DECISIONPLAN] (
    [DECISIONPLANID]    CHAR (36)      NOT NULL,
    [PLPLANTYPEID]      CHAR (36)      NULL,
    [PLPLANSTATUSID]    CHAR (36)      NULL,
    [ASSIGNEDTO]        CHAR (36)      NULL,
    [DISTRICTID]        CHAR (36)      NULL,
    [REQUIREDUPLOADS]   INT            CONSTRAINT [DF_DECISIONPLAN_REQUIREDUPLOADS] DEFAULT ((0)) NOT NULL,
    [UPLOADINFO]        NVARCHAR (MAX) CONSTRAINT [DF_DECISIONPLAN_UPLOADINFO] DEFAULT ('') NOT NULL,
    [PLPLANWORKCLASSID] CHAR (36)      NULL,
    CONSTRAINT [PK_DECISIONPLAN] PRIMARY KEY CLUSTERED ([DECISIONPLANID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_DECISIONPLAN_DISTRICT] FOREIGN KEY ([DISTRICTID]) REFERENCES [dbo].[DISTRICT] ([DISTRICTID]),
    CONSTRAINT [FK_DECISIONPLAN_PLSTATUS] FOREIGN KEY ([PLPLANSTATUSID]) REFERENCES [dbo].[PLPLANSTATUS] ([PLPLANSTATUSID]),
    CONSTRAINT [FK_DECISIONPLAN_PLTYPE] FOREIGN KEY ([PLPLANTYPEID]) REFERENCES [dbo].[PLPLANTYPE] ([PLPLANTYPEID]),
    CONSTRAINT [FK_DECISIONPLAN_PLWKCLASS] FOREIGN KEY ([PLPLANWORKCLASSID]) REFERENCES [dbo].[PLPLANWORKCLASS] ([PLPLANWORKCLASSID]),
    CONSTRAINT [FK_DECISIONPLAN_USERS] FOREIGN KEY ([ASSIGNEDTO]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);

