CREATE TABLE [dbo].[DECISIONQUESTIONNAIRE] (
    [DECISIONQUESTIONNAIREID]  CHAR (36)      NOT NULL,
    [QUESTIONNAIRENAME]        NVARCHAR (50)  NOT NULL,
    [QUESTIONNAIREDESCRIPTION] NVARCHAR (MAX) NULL,
    [ROWVERSION]               INT            NOT NULL,
    [LASTCHANGEDBY]            CHAR (36)      NOT NULL,
    [LASTCHANGEDON]            DATETIME       NOT NULL,
    [ISSHOWNONLINE]            BIT            CONSTRAINT [DF_DecisionQuestionnaire_IsShownOnLine] DEFAULT ((0)) NOT NULL,
    [ONLINEDESCRIPTION]        NVARCHAR (50)  CONSTRAINT [DF_DecisionQuestionnaire_OnLineDescription] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_Questionnaire] PRIMARY KEY CLUSTERED ([DECISIONQUESTIONNAIREID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Questionnaire_Users] FOREIGN KEY ([LASTCHANGEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);

