CREATE TABLE [dbo].[DECISIONPERMIT] (
    [DECISIONPERMITID]    CHAR (36)      NOT NULL,
    [PMPERMITTYPEID]      CHAR (36)      NULL,
    [PMPERMITSTATUSID]    CHAR (36)      NULL,
    [ASSIGNEDTO]          CHAR (36)      NULL,
    [DISTRICTID]          CHAR (36)      NULL,
    [REQUIREDUPLOADS]     INT            CONSTRAINT [DF_DECISIONPERMIT_REQUIREDUPLOADS] DEFAULT ((0)) NOT NULL,
    [UPLOADINFO]          NVARCHAR (MAX) CONSTRAINT [DF_DECISIONPERMIT_UPLOADINFO] DEFAULT ('') NOT NULL,
    [PMPERMITWORKCLASSID] CHAR (36)      NULL,
    CONSTRAINT [PK_DECISIONPERMIT] PRIMARY KEY CLUSTERED ([DECISIONPERMITID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_DECISIONPERMIT_DISTRICT] FOREIGN KEY ([DISTRICTID]) REFERENCES [dbo].[DISTRICT] ([DISTRICTID]),
    CONSTRAINT [FK_DECISIONPERMIT_PMSTATUS] FOREIGN KEY ([PMPERMITSTATUSID]) REFERENCES [dbo].[PMPERMITSTATUS] ([PMPERMITSTATUSID]),
    CONSTRAINT [FK_DECISIONPERMIT_PMTYPE] FOREIGN KEY ([PMPERMITTYPEID]) REFERENCES [dbo].[PMPERMITTYPE] ([PMPERMITTYPEID]),
    CONSTRAINT [FK_DECISIONPERMIT_PMWKCLASS] FOREIGN KEY ([PMPERMITWORKCLASSID]) REFERENCES [dbo].[PMPERMITWORKCLASS] ([PMPERMITWORKCLASSID]),
    CONSTRAINT [FK_DECISIONPERMIT_USERS] FOREIGN KEY ([ASSIGNEDTO]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);

