CREATE PROCEDURE [managebusinesslicense].[USP_BLLICENSEADDRESS_GETBYIDS]
(
	@BLLICENSELIST RECORDIDS READONLY
)
AS
BEGIN
	SELECT 
		[BLLICENSEADDRESS].[BLLICENSEID],
		[BLLICENSEADDRESS].[BLLICENSEADDRESSID],
		[MAILINGADDRESS].[ADDRESSLINE1],
		[MAILINGADDRESS].[ADDRESSLINE2],
		[MAILINGADDRESS].[ADDRESSLINE3],
		[MAILINGADDRESS].[ADDRESSTYPE],
		[MAILINGADDRESS].[ATTN],
		[MAILINGADDRESS].[CITY],
		[MAILINGADDRESS].[COMPSITE],
		[MAILINGADDRESS].[COUNTRY],
		[MAILINGADDRESSCOUNTRYTYPE].[MAILINGADDRESSCOUNTRYTYPEID],
		[MAILINGADDRESSCOUNTRYTYPE].[MAILINGADDRESSCOUNTRYTYPENAME],
		[BLLICENSEADDRESS].[MAIN],
		[MAILINGADDRESS].[POBOX],
		[MAILINGADDRESS].[POSTALCODE],
		[MAILINGADDRESS].[POSTDIRECTION],
		[MAILINGADDRESS].[PREDIRECTION],
		[MAILINGADDRESS].[PROVINCE],
		[MAILINGADDRESS].[RURALROUTE],
		[MAILINGADDRESS].[STATE],
		[MAILINGADDRESS].[STATION],
		[MAILINGADDRESS].[STREETTYPE],
		[MAILINGADDRESS].[UNITORSUITE],
		[MAILINGADDRESS].[ADDRESSID] 
	FROM [dbo].[BLLICENSEADDRESS]
	INNER JOIN [dbo].[MAILINGADDRESS] ON [BLLICENSEADDRESS].[MAILINGADDRESSID] = [MAILINGADDRESS].[MAILINGADDRESSID]
	INNER JOIN [dbo].[MAILINGADDRESSCOUNTRYTYPE] ON [MAILINGADDRESS].[COUNTRYTYPE] = [MAILINGADDRESSCOUNTRYTYPE].[MAILINGADDRESSCOUNTRYTYPEID]
	INNER JOIN @BLLICENSELIST [BLLICENSELIST] ON [BLLICENSEADDRESS].[BLLICENSEID] = [BLLICENSELIST].[RECORDID]
	WHERE [BLLICENSEADDRESS].[MAIN] = 1
END