CREATE PROCEDURE [managebusinesslicense].[USP_BLCONTACTTYPE_GETBYBLLICENSEID]
(
	@BLLICENSEID CHAR(36)
)
AS
BEGIN
	SELECT DISTINCT -- TO AVOID DUPLICATE RECORD
		[BLLICENSECONTACT].[GLOBALENTITYID],
		[BLLICENSECONTACT].[BLCONTACTTYPEID],
		[BLCONTACTTYPE].[NAME] 
	 FROM [dbo].[BLLICENSECONTACT]
			INNER JOIN [dbo].[BLCONTACTTYPE] ON [BLLICENSECONTACT].[BLCONTACTTYPEID] = [BLCONTACTTYPE].[BLCONTACTTYPEID]
	WHERE [BLLICENSECONTACT].[BLLICENSEID] = @BLLICENSEID
END