CREATE PROCEDURE [managebusinesslicense].[USP_BLLICENSE_NONRENEWABLE_LICENSEINFO_GET]
	@BLLICENSEIDS RECORDIDS READONLY
AS
	SELECT	[BLLICENSE].[BLLICENSEID],
			[BLLICENSE].[LICENSENUMBER],
			[BLGLOBALENTITYEXTENSION].[COMPANYNAME],
			[BLGLOBALENTITYEXTENSION].[DBA]
	FROM BLLICENSE
	LEFT JOIN BLGLOBALENTITYEXTENSION ON [BLLICENSE].[BLGLOBALENTITYEXTENSIONID] = [BLGLOBALENTITYEXTENSION].[BLGLOBALENTITYEXTENSIONID]
	WHERE [BLLICENSE].[BLLICENSEID] IN (SELECT RECORDID FROM @BLLICENSEIDS)