CREATE PROCEDURE [plansetup].[USP_PLPLANSTATUS_SELECT_LOOKUP]
AS
	SET NOCOUNT ON;

	SELECT		[dbo].[PLPLANSTATUS].[PLPLANSTATUSID],
				[dbo].[PLPLANSTATUS].[NAME]
	FROM		[dbo].[PLPLANSTATUS]
	ORDER BY	[dbo].[PLPLANSTATUS].[NAME]