CREATE VIEW [inspection].[PARENTRECORDINFO]
AS
	SELECT        
		PMPERMIT.PMPERMITID AS RecordId, 
		PMPERMIT.PERMITNUMBER AS CaseNumber, 
		PMPERMIT.DESCRIPTION AS Description, 
		2 AS LinkType, 
		PMPERMITSTATUS.NAME AS CaseStatus, 
		PRPROJECT.NAME AS ProjectName, 
		PMPERMIT.LASTINSPECTIONDATE AS LastInspectionDate, 
		GISFEATURE.KEYVALUE as SpatialCollection
	FROM dbo.PMPERMIT
	INNER JOIN dbo.PMPERMITSTATUS ON PMPERMITSTATUS.PMPERMITSTATUSID = PMPERMIT.PMPERMITSTATUSID 
	LEFT OUTER JOIN dbo.PRPROJECTPERMIT ON PRPROJECTPERMIT.PMPERMITID = PMPERMIT.PMPERMITID 
	LEFT OUTER JOIN dbo.PRPROJECT ON PRPROJECT.PRPROJECTID = PRPROJECTPERMIT.PRPROJECTID
	OUTER APPLY (SELECT TOP(1) KEYVALUE FROM dbo.PMPERMITGISFEATURE WHERE PMPERMITID = PMPERMIT.PMPERMITID) AS GISFEATURE

	UNION ALL
	
	SELECT        
		PLPLAN.PLPLANID AS RecordId, 
		PLPLAN.PLANNUMBER AS CaseNumber, 
		PLPLAN.DESCRIPTION AS Description, 
		1 AS LinkType, 
		PLPLANSTATUS.NAME AS ParentCaseStatus, 
		PRPROJECT.NAME AS ProjectName, 
		NULL  AS LastInspectionDate, 
		GISFEATURE.KEYVALUE as SpatialCollection
	FROM dbo.PLPLAN
	INNER JOIN dbo.PLPLANSTATUS ON PLPLANSTATUS.PLPLANSTATUSID = plplan.PLPLANSTATUSID 
	LEFT OUTER JOIN dbo.PRPROJECTPLAN ON PRPROJECTPLAN.PLPLANID = plplan.PLPLANID 
	LEFT OUTER JOIN dbo.PRPROJECT ON PRPROJECT.PRPROJECTID = PRPROJECTPLAN.PRPROJECTID
	OUTER APPLY (SELECT TOP(1) KEYVALUE FROM dbo.PLPLANGISFEATURE WHERE PLPLANID = PLPLAN.PLPLANID) AS GISFEATURE

	UNION ALL

	SELECT        
		CMCODECASE.CMCODECASEID AS RecordId, 
		CMCODECASE.CASENUMBER AS CaseNumber, 
		CMCODECASE.DESCRIPTION AS Description, 
		3 AS LinkType, 
		CMCODECASESTATUS.NAME AS ParentCaseStatus, 
		PRPROJECT.NAME AS ProjectName, 
		NULL AS LastInspectionDate, 
		null as SpatialCollection
	FROM dbo.CMCODECASE 
	INNER JOIN dbo.CMCODECASESTATUS ON CMCODECASESTATUS.CMCODECASESTATUSID = CMCODECASE.CMCODECASESTATUSID 
	LEFT OUTER JOIN dbo.PRPROJECTCODECASE ON PRPROJECTCODECASE.CMCODECASEID = CMCODECASE.CMCODECASEID 
	LEFT OUTER JOIN dbo.PRPROJECT ON PRPROJECT.PRPROJECTID = PRPROJECTCODECASE.PRPROJECTID

	UNION ALL

	SELECT        
		ILLICENSE.ILLICENSEID AS RecordId, 
		ILLICENSE.LICENSENUMBER AS CaseNumber, 
		ILLICENSE.DESCRIPTION AS Description, 
		6 AS LinkType, 
		licensestatus.NAME AS ParentCaseStatus, 
		NULL AS ProjectName, 
		NULL AS LastInspectionDate, 
		null as SpatialCollection
	FROM dbo.ILLICENSE
	INNER JOIN dbo.ILLICENSESTATUS AS licensestatus ON licensestatus.ILLICENSESTATUSID = ILLICENSE.ILLICENSESTATUSID

	UNION ALL

	SELECT        
		BLLICENSE.BLLICENSEID AS RecordId, 
		BLLICENSE.LICENSENUMBER AS CaseNumber, 
		BLLICENSE.DESCRIPTION AS Description, 
		7 AS LinkType, 
		BLLICENSESTATUS.NAME AS ParentCaseStatus, 
		NULL AS ProjectName, 
		NULL AS LastInspectionDate, 
		null as SpatialCollection
	FROM  dbo.BLLICENSE
	INNER JOIN dbo.BLLICENSESTATUS ON BLLICENSESTATUS.BLLICENSESTATUSID = BLLICENSE.BLLICENSESTATUSID

	UNION ALL

	SELECT        
		CITIZENREQUEST.CITIZENREQUESTID AS RecordId, 
		CITIZENREQUEST.REQUESTNUMBER AS CaseNumber, 
		CITIZENREQUEST.DESCRIPTION AS Description, 
		4 AS LinkType, 
		CITIZENREQUESTSTATUS.STATUS AS ParentCaseStatus, 
		NULL AS ProjectName, 
		NULL AS LastInspectionDate, 
		null as SpatialCollection
	FROM  dbo.CITIZENREQUEST
	INNER JOIN dbo.CITIZENREQUESTSTATUS ON CITIZENREQUESTSTATUS.CITIZENREQUESTSTATUSID = CITIZENREQUEST.CITIZENREQUESTSTATUSID

	UNION ALL

	SELECT        
		BLGLOBALENTITYEXTENSION.BLGLOBALENTITYEXTENSIONID AS RecordId, 
		BLGLOBALENTITYEXTENSION.REGISTRATIONID AS CaseNumber, 
		BLGLOBALENTITYEXTENSION.DESCRIPTION AS Description, 
		5 AS LinkType, 
		BLEXTSTATUS.NAME AS ParentCaseStatus, 
		NULL AS ProjectName, 
		NULL AS LastInspectionDate, 
		null as SpatialCollection
	FROM  dbo.BLGLOBALENTITYEXTENSION
	INNER JOIN dbo.BLEXTSTATUS ON BLEXTSTATUS.BLEXTSTATUSID = BLGLOBALENTITYEXTENSION.BLEXTSTATUSID

	UNION ALL

	SELECT        
		RPLANDLORDLICENSE.RPLANDLORDLICENSEID AS RecordId, 
		RPLANDLORDLICENSE.LANDLORDNUMBER AS CaseNumber, 
		RPLANDLORDLICENSE.DESCRIPTION AS Description, 
		8 AS LinkType, 
		RPLANDLORDLICENSESTATUS.NAME AS ParentCaseStatus, 
		NULL AS ProjectName, 
		NULL AS LastInspectionDate, 
		null as SpatialCollection
	FROM  dbo.RPLANDLORDLICENSE
	INNER JOIN dbo.RPLANDLORDLICENSESTATUS ON RPLANDLORDLICENSESTATUS.RPLANDLORDLICENSESTATUSID = RPLANDLORDLICENSE.RPLANDLORDLICENSESTATUSID

	UNION ALL

	SELECT        
		RPPROPERTY.RPPROPERTYID AS RecordId, 
		RPPROPERTY.PROPERTYNUMBER AS CaseNumber, 
		RPPROPERTY.DESCRIPTION AS Description, 
		9 AS LinkType, 
		RPPROPERTYSTATUS.NAME AS ParentCaseStatus, 
		NULL AS ProjectName, 
		NULL AS LastInspectionDate, 
		null as SpatialCollection
	FROM  dbo.RPPROPERTY
	INNER JOIN dbo.RPPROPERTYSTATUS ON RPPROPERTYSTATUS.RPPROPERTYSTATUSID = RPPROPERTY.RPPROPERTYSTATUSID