
CREATE PROCEDURE [dbo].[rpt_SR_Code_Setup_Workflow_Template]
@CMCASETYPEID AS VARCHAR(36)
AS
SELECT     WFTEMPLATE.NAME AS WorkflowTemplate, WFSTEP.NAME AS WorkflowStep, WFTEMPLATESTEP.PRIORITYORDER AS StepPriority, 
                      WFTEMPLATESTEP.SORTORDER AS StepSort, WFACTION.NAME AS WorkflowAction, WFTEMPLATESTEPACTION.PRIORITYORDER AS ActionPriority, 
                      WFTEMPLATESTEPACTION.SORTORDER AS ActionSort, WFTEMPLATESTEP.AUTOFILL AS StepAutoFill, WFTEMPLATESTEPACTION.AUTOFILL AS ActionAutoFill, 
                      WFTEMPLATESTEPACTION.AUTORECEIVE AS ActionAutoReceive, CMCASETYPE.NAME AS CaseType
FROM         CMCASETYPE INNER JOIN
                      WFSTEP INNER JOIN
                      WFTEMPLATESTEP ON WFSTEP.WFSTEPID = WFTEMPLATESTEP.WFSTEPID INNER JOIN
                      WFTEMPLATE ON WFTEMPLATESTEP.WFTEMPLATEID = WFTEMPLATE.WFTEMPLATEID ON 
                      CMCASETYPE.WFTEMPLATEID = WFTEMPLATE.WFTEMPLATEID LEFT OUTER JOIN
                      WFACTION INNER JOIN
                      WFTEMPLATESTEPACTION ON WFACTION.WFACTIONID = WFTEMPLATESTEPACTION.WFACTIONID ON 
                      WFTEMPLATESTEP.WFTEMPLATESTEPID = WFTEMPLATESTEPACTION.WFTEMPLATESTEPID
WHERE CMCASETYPE.CMCASETYPEID = @CMCASETYPEID
