
CREATE PROCEDURE [dbo].[rpt_SR_SR_Permit_Setup]
AS
SELECT PMPERMITTYPE.PMPERMITTYPEID, PMPERMITTYPE.NAME AS PermitType, PMPERMITTYPE.PERMITPREFIX, PMPERMITTYPE.DAYSUNTILEXPIRE, 
       PMPERMITTYPE.DAYSUNTILEXPIREFROMLASTINSPECT, PMPERMITTYPE.ACTIVE, PMPERMITTYPE.AUTONUMBER, PMPERMITTYPE.COMMERCIAL, 
       PMPERMITTYPE.RESIDENTIAL, PMPERMITTYPE.VALUATION, PMPERMITTYPE.SQUAREFEET, PMPERMITTYPE.UNLIMITED, 
       PMPERMITTYPE.ALLOWINTERNETSUBMISSION, PMPERMITSTATUS.NAME AS Status, PMPERMITTYPE.FRIENDLYNAME
FROM PMPERMITTYPE
LEFT OUTER JOIN PMPERMITSTATUS ON PMPERMITTYPE.DEFAULTPMPERMITSTATUSID = PMPERMITSTATUS.PMPERMITSTATUSID

