
CREATE PROCEDURE [dbo].[rpt_SR_SR_Code_Setup_Code_List]

AS

SELECT	CMCODE.CODENUMBER, 
		CMCODECATEGORY.NAME AS CODECATEGORYNAME,
		CMCODEREVISION.REVISIONDATE,
		CMCODEREVISION.CODETEXT

FROM	CMCODE
		INNER JOIN CMCODECATEGORY ON CMCODE.CMCODECATEGORYID= CMCODECATEGORY.CMCODECATEGORYID
		INNER JOIN CMCODEREVISION ON CMCODE.CMCODEID = CMCODEREVISION.CMCODEID

WHERE	CMCODEREVISION.CURRENTREVISION = 1
