
CREATE PROCEDURE [dbo].[rpt_SR_Business_License_Setup_License_Classes]
@BUSINESSLICENSETYPEID AS VARCHAR(36)
AS
SELECT     BLLICENSECLASS.NAME AS ClassName, LICENSECYCLE.NAME AS CycleName, WFTEMPLATE.NAME AS WorkflowTemplate, 
                      CUSTOMFIELDLAYOUT.SNAME AS CustomFieldLayout, CUSTOMFIELDLAYOUT_1.SNAME AS OnlineCustomFieldLayout, 
                      CAFEETEMPLATE.CAFEETEMPLATENAME AS FeeTemplate, BLLICENSETYPECLASS.INTERNETFLAG AS InternetFlag, 
                      BLLICENSECAPAPPLICATIONTYPE.NAME AS InternetApplyType
FROM         BLLICENSECLASS INNER JOIN
                      BLLICENSETYPECLASS ON BLLICENSECLASS.BLLICENSECLASSID = BLLICENSETYPECLASS.BLLICENSECLASSID RIGHT OUTER JOIN
                      BLLICENSECAPAPPLICATIONTYPE ON 
                      BLLICENSETYPECLASS.BLLICENSECAPAPPLICATIONTYPEID = BLLICENSECAPAPPLICATIONTYPE.BLLICENSECAPAPPLICATIONTYPEID LEFT OUTER JOIN
                      CAFEETEMPLATE ON BLLICENSETYPECLASS.CAFEETEMPLATEID = CAFEETEMPLATE.CAFEETEMPLATEID LEFT OUTER JOIN
                      CUSTOMFIELDLAYOUT ON BLLICENSETYPECLASS.CUSTOMFIELDLAYOUTID = CUSTOMFIELDLAYOUT.GCUSTOMFIELDLAYOUTS LEFT OUTER JOIN
                      CUSTOMFIELDLAYOUT AS CUSTOMFIELDLAYOUT_1 ON 
                      BLLICENSETYPECLASS.ONLINECUSTOMFIELDLAYOUTID = CUSTOMFIELDLAYOUT_1.GCUSTOMFIELDLAYOUTS LEFT OUTER JOIN
                      WFTEMPLATE ON BLLICENSETYPECLASS.WFTEMPLATEID = WFTEMPLATE.WFTEMPLATEID LEFT OUTER JOIN
                      LICENSECYCLE ON BLLICENSETYPECLASS.LICENSECYCLEID = LICENSECYCLE.LICENSECYCLEID
WHERE BLLICENSETYPECLASS.BLLICENSETYPEID = @BUSINESSLICENSETYPEID
