
CREATE  PROCEDURE [dbo].[rpt_SR_SR_User_Setup_Report_Inspector_Type]
@USERGUID AS VARCHAR(36)
AS
SELECT IMINSPECTORTYPE.SNAME AS InspectorType
FROM IMINSPECTORTYPEUSER 
INNER JOIN IMINSPECTORTYPE ON IMINSPECTORTYPEUSER.INSPECTORTYPEID = IMINSPECTORTYPE.IMINSPECTORTYPEID
WHERE IMINSPECTORTYPEUSER.USERID = @USERGUID
