
CREATE PROCEDURE [dbo].[rpt_SR_SR_Fee_Setup]
AS
SELECT CAFEE.NAME AS FeeName, CAFEE.DESCRIPTION AS Description, CAFEE.NOTES AS Notes,  
       CACOMPUTATIONTYPE.NAME AS FeeType, CASCHEDULE.NAME AS FeeSchedule, CAFEESETUP.AMOUNT AS Amount, 
       CAFEESETUP.COMPUTATIONVALUE AS ComputationValue, CAFEESETUP.COMPUTATIONVALUENAME AS ComputationValueName, 
       CAFEESETUP.MINIMUMAMOUNT AS Minimum, CAFEESETUP.MAXIMUMAMOUNT AS Maximum, CAROUNDINGTYPE.DESCRIPTION AS RoundFee,
       CAFEESETUP.ROUNDINGVALUE, CAFEE.CAFEEID
FROM CAFEE 
INNER JOIN CACOMPUTATIONTYPE ON CAFEE.CACOMPUTATIONTYPEID = CACOMPUTATIONTYPE.CACOMPUTATIONTYPEID 
INNER JOIN CAFEESETUP ON CAFEE.CAFEEID = CAFEESETUP.CAFEEID 
LEFT JOIN CASCHEDULE ON CAFEESETUP.CASCHEDULEID = CASCHEDULE.CASCHEDULEID 
INNER JOIN CAROUNDINGTYPE ON CAFEESETUP.ROUNDINGTYPEID = CAROUNDINGTYPE.CAROUNDINGTYPEID


