
CREATE PROCEDURE [dbo].[SEARCHMOBILECODECONTACTLIST]
	@SearchText varchar(500)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @KEY VARCHAR(50) = 'MaxNoRowsToReturnQuickSearch'
	DECLARE @limit INT = 100
	IF EXISTS(SELECT * FROM SETTINGS WHERE NAME=@KEY)
	BEGIN
	  SELECT @limit=ISNULL(INTVALUE,100) FROM SETTINGS WHERE NAME=@KEY
	END

	SELECT TOP (@limit)
	  GLOBALENTITYID, 
	  GLOBALENTITYNAME,
	  FIRSTNAME,
	  LASTNAME,
	  EMAIL,
	  BUSINESSPHONE,
	  HOMEPHONE,
	  MOBILEPHONE,
	  OTHERPHONE 
	FROM GLOBALENTITY 
	WHERE GLOBALENTITYNAME LIKE @SearchText 
	 OR FIRSTNAME LIKE @SearchText 
	 OR LASTNAME LIKE @SearchText
	ORDER BY LASTNAME, FIRSTNAME
END