
CREATE Procedure [dbo].[SP_DELETE_PERMIT]
(
	@PMPERMITID char(36)
)
AS
BEGIN
	DECLARE @ORIGINALPERMITID CHAR(36)
	SET @ORIGINALPERMITID = @PMPERMITID;
	
	SET XACT_ABORT ON

	SET TRANSACTION ISOLATION LEVEL SERIALIZABLE

	BEGIN TRANSACTION

		CREATE TABLE #tmpTABLE (RECORDID char(36))
		
		-- Delete the 1st copied if failed some thing
		DELETE PMPERMITDIMENSION FROM PMPERMITDIMENSION WHERE PMPERMITID = @ORIGINALPERMITID;
		DELETE PMPERMITVALUATION FROM PMPERMITVALUATION WHERE PMPERMITID = @ORIGINALPERMITID;
		DELETE PMPERMITZONE FROM PMPERMITZONE WHERE PMPERMITID = @ORIGINALPERMITID;
		DELETE PMPERMITCONTACT FROM PMPERMITCONTACT WHERE PMPERMITID = @ORIGINALPERMITID;
		DELETE PMPERMITPARCEL FROM PMPERMITPARCEL WHERE PMPERMITID = @ORIGINALPERMITID;
		DELETE PMPERMITZONE FROM PMPERMITZONE WHERE PMPERMITID = @ORIGINALPERMITID;
		DELETE PMPERMITGISFEATURE FROM PMPERMITGISFEATURE WHERE PMPERMITID = @ORIGINALPERMITID;

		INSERT INTO #tmpTABLE
		(
			RECORDID
		) 
		SELECT MAILINGADDRESSID 
		FROM PMPERMITADDRESS WHERE PMPERMITID = @ORIGINALPERMITID;
		
		DELETE PMPERMITADDRESS FROM PMPERMITADDRESS WHERE PMPERMITID = @ORIGINALPERMITID;
		DELETE MAILINGADDRESS FROM MAILINGADDRESS TABLEA INNER JOIN #tmpTABLE TABLEB ON TABLEA.MAILINGADDRESSID = TABLEB.RECORDID;
		TRUNCATE TABLE #tmpTABLE;

		DELETE PMPERMITHOLD FROM PMPERMITHOLD WHERE PMPERMITID = @ORIGINALPERMITID;
		DELETE TIMETRACKING FROM TIMETRACKING WHERE PRIMARYRECORDID = @ORIGINALPERMITID;
		
		INSERT INTO #tmpTABLE
		(
			RECORDID
		) 
		SELECT CONDITIONID
		FROM PMPERMITCONDITION WHERE PMPERMITID = @ORIGINALPERMITID;
		
		DELETE PMPERMITCONDITION FROM PMPERMITCONDITION WHERE PMPERMITID = @ORIGINALPERMITID;
		DELETE PARCELCONDITION WHERE CONDITIONID IN (SELECT RECORDID FROM #tmpTABLE);
		DELETE CONDITION WHERE CONDITIONID IN (SELECT RECORDID FROM #tmpTABLE);
		TRUNCATE TABLE #tmpTABLE;
		
		INSERT INTO #tmpTABLE
		(
			RECORDID
		) 
		SELECT PMPERMITACTIVITYID
		FROM PMPERMITACTIVITY WHERE PMPERMITID = @ORIGINALPERMITID;
		
		DELETE PMPERMITACTIVITY FROM PMPERMITACTIVITY WHERE PMPERMITID = @ORIGINALPERMITID;
		
		DELETE CUSTOMSAVERPERMITMANAGEMENT FROM CUSTOMSAVERPERMITMANAGEMENT WHERE ID IN (SELECT RECORDID FROM #tmpTABLE)
		DELETE PMPERMITNOTE FROM PMPERMITNOTE WHERE PMPERMITID = @ORIGINALPERMITID;
		TRUNCATE TABLE #tmpTABLE;
		
		INSERT INTO #tmpTABLE
		(
			RECORDID
		) 
		SELECT CACOMPUTEDFEEID
		FROM PMPERMITFEE WHERE PMPERMITID = @ORIGINALPERMITID;
		
		DELETE PMPERMITFEE FROM PMPERMITFEE WHERE PMPERMITID = @ORIGINALPERMITID;
		DELETE CACOMPUTEDFEEXREF FROM CACOMPUTEDFEEXREF TABLEA INNER JOIN #tmpTABLE TABLEB ON TABLEA.CACOMPUTEDFEEID = TABLEB.RECORDID;
		DELETE CACOMPUTEDFEE FROM CACOMPUTEDFEE TABLEA INNER JOIN #tmpTABLE TABLEB ON TABLEA.CACOMPUTEDFEEID = TABLEB.RECORDID;
		TRUNCATE TABLE #tmpTABLE;

		DELETE PMPERMITACTIONREF FROM PMPERMITACTIONREF ACTIONREF 
		INNER JOIN PMPERMITWFACTIONSTEP TABLEA ON ACTIONREF.OBJECTID = TABLEA.PMPERMITWFACTIONSTEPID
		INNER JOIN PMPERMITWFSTEP STEP ON STEP.PMPERMITWFSTEPID = TABLEA.PMPERMITWFSTEPID AND STEP.PMPERMITID = @ORIGINALPERMITID;
		
		DELETE PLPLANACTIONREF FROM PLPLANACTIONREF ACTIONREF 
		INNER JOIN PMPERMITWFACTIONSTEP TABLEA ON ACTIONREF.OBJECTID = TABLEA.PMPERMITWFACTIONSTEPID
		INNER JOIN PMPERMITWFSTEP STEP ON STEP.PMPERMITWFSTEPID = TABLEA.PMPERMITWFSTEPID AND STEP.PMPERMITID = @ORIGINALPERMITID;
		
		DELETE PMPERMITWFACTIONSTEP FROM PMPERMITWFACTIONSTEP TABLEA 
		INNER JOIN PMPERMITWFSTEP STEP ON STEP.PMPERMITWFSTEPID = TABLEA.PMPERMITWFSTEPID AND STEP.PMPERMITID = @ORIGINALPERMITID;
		
		DELETE PMPERMITWFSTEP FROM PMPERMITWFSTEP WHERE PMPERMITID = @ORIGINALPERMITID;
		DELETE PMPERMIT WHERE PMPERMITID = @ORIGINALPERMITID;
		
		/*===========================================================================================================
		  COMMIT OR ROLL BACK - DO NOT REMOVE
		=============================================================================================================*/
		SELECT 'SUCCESS';
	END
