
CREATE PROCEDURE SP_UPSERT_CUST_DTE
	@CUSTOM_DATA CUSTOM_DTE_TYPE READONLY
AS
BEGIN
	
	SET NOCOUNT ON;
	UPDATE TARGET SET TARGET.DATEVALUE = SOURCE.DATEVALUE
	FROM CUSTOMSAVERTBLCOL_DATE TARGET
	INNER JOIN  @CUSTOM_DATA AS SOURCE ON 
		TARGET.OBJECTID = SOURCE.PARENT_ID AND TARGET.CFTABLECOLUMNREFID = SOURCE.CUSTOM_FIELD_ID AND TARGET.ROWNUMBER = SOURCE.ROWNUMBER

	INSERT INTO CUSTOMSAVERTBLCOL_DATE
		(
			CUSTOMSAVERTABLECOLUMNID,
			OBJECTID,
			MODULEID,
			CFTABLECOLUMNREFID,
			DATEVALUE,
			ROWNUMBER
		)
	SELECT 
		SOURCE.ID,
		SOURCE.PARENT_ID,
		SOURCE.MODULEID,
		SOURCE.CUSTOM_FIELD_ID,
		SOURCE.DATEVALUE,
		SOURCE.ROWNUMBER
	FROM @CUSTOM_DATA SOURCE
	LEFT OUTER JOIN CUSTOMSAVERTBLCOL_DATE TARGET WITH (NOLOCK) ON 
		TARGET.OBJECTID = SOURCE.PARENT_ID AND TARGET.CFTABLECOLUMNREFID = SOURCE.CUSTOM_FIELD_ID AND TARGET.ROWNUMBER = SOURCE.ROWNUMBER
	WHERE TARGET.CUSTOMSAVERTABLECOLUMNID IS NULL

END