
CREATE PROCEDURE SP_UPSERT_CUST_STR
	@CUSTOM_DATA CUSTOM_STR_TYPE READONLY
AS
BEGIN
	
	SET NOCOUNT ON;
	UPDATE TARGET SET TARGET.STRINGVALUE = SOURCE.STRINGVALUE
	FROM CUSTOMSAVERTBLCOL_STR TARGET
	INNER JOIN  @CUSTOM_DATA AS SOURCE ON 
		TARGET.OBJECTID = SOURCE.PARENT_ID AND TARGET.CFTABLECOLUMNREFID = SOURCE.CUSTOM_FIELD_ID AND TARGET.ROWNUMBER = SOURCE.ROWNUMBER

	INSERT INTO CUSTOMSAVERTBLCOL_STR
		(
			CUSTOMSAVERTABLECOLUMNID,
			OBJECTID,
			MODULEID,
			CFTABLECOLUMNREFID,
			STRINGVALUE,
			ROWNUMBER
		)
	SELECT 
		SOURCE.ID,
		SOURCE.PARENT_ID,
		SOURCE.MODULEID,
		SOURCE.CUSTOM_FIELD_ID,
		SOURCE.STRINGVALUE,
		SOURCE.ROWNUMBER
	FROM @CUSTOM_DATA SOURCE
	LEFT OUTER JOIN CUSTOMSAVERTBLCOL_STR TARGET WITH (NOLOCK) ON 
		TARGET.OBJECTID = SOURCE.PARENT_ID AND TARGET.CFTABLECOLUMNREFID = SOURCE.CUSTOM_FIELD_ID AND TARGET.ROWNUMBER = SOURCE.ROWNUMBER
	WHERE TARGET.CUSTOMSAVERTABLECOLUMNID IS NULL

END