CREATE PROCEDURE [dbo].[USP_SERVICE_UPDATE]
(
	@SERVICEID CHAR(36),
	@ISACTIVE BIT,
	@ISCOORDINATOR BIT,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
UPDATE [dbo].[SERVICE] SET
	[ISACTIVE] = @ISACTIVE,
	[ISCOORDINATOR] = @ISCOORDINATOR,
	[LASTCHANGEDBY] = @LASTCHANGEDBY,
	[LASTCHANGEDON] = @LASTCHANGEDON,
	[ROWVERSION] = @ROWVERSION + 1
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE
	[SERVICEID] = @SERVICEID AND 
	[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE