CREATE PROCEDURE [dbo].[USP_STATE_SELECT_LOOKUP]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[STATE].[STATEID],
	[dbo].[STATE].[NAME],
	[dbo].[STATE].[ABBREVIATION]
FROM [dbo].[STATE]
ORDER BY [dbo].[STATE].[ABBREVIATION]
END