CREATE PROCEDURE [dbo].[USP_SERVICE_DELETE]
(
	@SERVICEID CHAR(36),
	@ROWVERSION INT
)
AS
SET NOCOUNT ON;

EXEC [dbo].[USP_WINDOWSSERVICETASKCONFIG_DELETE_BYPARENTID] @SERVICEID

SET NOCOUNT OFF;

DELETE FROM [dbo].[SERVICE]
WHERE
	[SERVICEID] = @SERVICEID AND 
	[ROWVERSION]= @ROWVERSION