CREATE PROCEDURE [dbo].[USP_SCHEDULEPRIORITYSTATUS_INSERT]
(
	@SCHEDULEPRIORITYSTATUSID CHAR(36),
	@NAME NVARCHAR(100),
	@SYSTEMPRIORITY INT,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
INSERT INTO [dbo].[SCHEDULEPRIORITYSTATUS](
	[SCHEDULEPRIORITYSTATUSID],
	[NAME],
	[SYSTEMPRIORITY],
	[LASTCHANGEDBY],
	[LASTCHANGEDON],
	[ROWVERSION]
)
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
VALUES
(
	@SCHEDULEPRIORITYSTATUSID,
	@NAME,
	@SYSTEMPRIORITY,
	@LASTCHANGEDBY,
	@LASTCHANGEDON,
	@ROWVERSION
)
SELECT * FROM @OUTPUTTABLE