
CREATE PROCEDURE rpt_IP_SR_Monetary_Impact_Conditions_by_Contribution_Date

	@STARTDATE AS DATETIME,
	@ENDDATE AS DATETIME
AS

SET @STARTDATE = DATEADD(dd, DATEDIFF(dd, 0, @startdate), 0)
SET @ENDDATE = DATEADD(S,-1,DATEADD(D,1,@ENDDATE))  


SELECT	IPCONDITIONCATEGORY.IPCONDITIONCATEGORYID, IPCONDITIONCATEGORY.NAME 'IPCONDITIONCATEGORY_NAME',
		IPCASE.CASENUMBER, IPCASE.SOURCECASENUMBER,
		IPCONDITION.CONDITIONNUMBER, IPCONDITION.DESCRIPTION 'IPCONDITION_DESCRIPTION',
		CATRANSACTIONPAYMENT.PAYMENTDATE,
		DISTRICT.NAME 'DISTRICT_NAME',
		IPUNITTYPE.NAME 'IPUNITTYPE_NAME',
		IPCONDITIONMONETARY.ASSESSAMOUNT,
		SUM((CATRANSACTIONFEE.PAIDAMOUNT-(2*CATRANSACTIONFEE.REFUNDAMOUNT))) 'PAIDAMOUNT',
		COUNT( 1 ) 'NumberOfPayments',
		--(SELECT R.[IMAGE] FROM RPTIMAGELIB R
		--	WHERE R.IMAGENAME = 'Municipality_Logo') LOGO,
		(SELECT CASE WHEN R.[IMAGE] IS NULL THEN 'N' ELSE 'Y' END FROM RPTIMAGELIB R
			WHERE R.IMAGENAME = 'Municipality_Logo') SHOWLOGO,
		(SELECT R.REPORTTEXT FROM RPTTEXTLIB R
			WHERE R.TEXTNAME = 'Municipality_Name') Municipality_Name,	   
		(SELECT R.REPORTTEXT FROM RPTTEXTLIB R
			WHERE R.TEXTNAME = 'Municipality_Page_Footer') Municipality_Page_Footer

FROM	IPCASE 
		INNER JOIN IPCONDITION ON IPCASE.IPCASEID = IPCONDITION.IPCASEID 
		INNER JOIN IPCONDITIONTYPE ON IPCONDITION.IPCONDITIONTYPEID = IPCONDITIONTYPE.IPCONDITIONTYPEID
		INNER JOIN IPCONDITIONCATEGORY ON IPCONDITIONTYPE.IPCONDITIONCATEGORYID = IPCONDITIONCATEGORY.IPCONDITIONCATEGORYID 
		INNER JOIN DISTRICT ON IPCASE.DISTRICTID = DISTRICT.DISTRICTID 
		INNER JOIN IPUNITTYPE ON IPCONDITION.IPUNITTYPEID = IPUNITTYPE.IPUNITTYPEID
		INNER JOIN IPCONDITIONMONETARY ON IPCONDITION.IPCONDITIONID = IPCONDITIONMONETARY.IPCONDITIONID 
		INNER JOIN IPCONDITIONFEE ON IPCONDITION.IPCONDITIONID = IPCONDITIONFEE.IPCONDITIONID 
		INNER JOIN CACOMPUTEDFEE ON IPCONDITIONFEE.CACOMPUTEDFEEID = CACOMPUTEDFEE.CACOMPUTEDFEEID 
		INNER JOIN CATRANSACTIONFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CATRANSACTIONFEE.CACOMPUTEDFEEID
		INNER JOIN CATRANSACTION ON CATRANSACTIONFEE.CATRANSACTIONID = CATRANSACTION.CATRANSACTIONID 
		INNER JOIN CATRANSACTIONPAYMENT ON CATRANSACTION.CATRANSACTIONID = CATRANSACTIONPAYMENT.CATRANSACTIONID 

WHERE	IPCONDITION.MONETARY = 'true'
		AND CATRANSACTIONPAYMENT.PAYMENTDATE BETWEEN @STARTDATE AND @ENDDATE

GROUP BY	IPCONDITIONCATEGORY.IPCONDITIONCATEGORYID, IPCONDITIONCATEGORY.NAME, IPCASE.CASENUMBER, IPCONDITION.CONDITIONNUMBER, CATRANSACTIONPAYMENT.PAYMENTDATE, 
			IPCASE.SOURCECASENUMBER, DISTRICT.NAME, IPCONDITION.DESCRIPTION, IPUNITTYPE.NAME, IPCONDITIONMONETARY.ASSESSAMOUNT 

ORDER BY	IPCONDITIONCATEGORY.NAME, IPCONDITIONCATEGORY.IPCONDITIONCATEGORYID, IPCONDITION.CONDITIONNUMBER, IPCASE.SOURCECASENUMBER, DISTRICT.NAME 

