


-- [dbo].[rpt_IM_Inspection_Worksheet_Contact] 'eceb1e61-adea-4c35-98b9-d0200e1d92a4'
CREATE PROCEDURE [dbo].[rpt_IM_Inspection_Worksheet_Contact]
@IMINSPECTIONID AS VARCHAR(36)
AS

SELECT COALESCE (TB_PERMIT.ContactType, TB_PLAN.ContactType, TB_CODE.ContactType) AS ContactType, 
       COALESCE (TB_PERMIT.GLOBALENTITYNAME, TB_PLAN.GLOBALENTITYNAME, TB_CODE.GLOBALENTITYNAME) AS GlobalEntity, 
	   COALESCE (TB_PERMIT.GLOBALENTITYID, TB_PLAN.GLOBALENTITYID, TB_CODE.GLOBALENTITYID) AS GLOBALENTITYID,
       COALESCE (TB_PERMIT.FIRSTNAME + ' ' + TB_PERMIT.LASTNAME, TB_PLAN.FIRSTNAME + ' ' + TB_PLAN.LASTNAME, TB_CODE.FIRSTNAME + ' ' + TB_CODE.LASTNAME) AS Name
FROM  IMINSPECTIONACTREF
LEFT OUTER JOIN ( SELECT CMCODEWFACTIONSTEP.CMCODEWFACTIONSTEPID, CMCODECASECONTACTTYPE.NAME AS ContactType, 
                         GLOBALENTITY_2.GLOBALENTITYNAME, GLOBALENTITY_2.FIRSTNAME, GLOBALENTITY_2.LASTNAME,GLOBALENTITY_2.GLOBALENTITYID
                  FROM CMCODEWFACTIONSTEP 
                  INNER JOIN CMCODEWFSTEP ON CMCODEWFSTEP.CMCODEWFSTEPID = CMCODEWFACTIONSTEP.CMCODEWFSTEPID 
                  INNER JOIN CMCODECASE ON CMCODEWFSTEP.CMCODECASEID = CMCODECASE.CMCODECASEID 
                  INNER JOIN CMCODECASECONTACT ON CMCODECASE.CMCODECASEID = CMCODECASECONTACT.CMCODECASEID 
                  INNER JOIN CMCODECASECONTACTTYPE ON CMCODECASECONTACT.CMCODECASECONTACTTYPEID = CMCODECASECONTACTTYPE.CMCODECASECONTACTTYPEID 
                  INNER JOIN GLOBALENTITY AS GLOBALENTITY_2 ON CMCODECASECONTACT.GLOBALENTITYID = GLOBALENTITY_2.GLOBALENTITYID 
                ) AS TB_CODE ON IMINSPECTIONACTREF.OBJECTID = TB_CODE.CMCODEWFACTIONSTEPID 

LEFT OUTER JOIN ( SELECT PLPLANWFACTIONSTEP.PLPLANWFACTIONSTEPID, LANDMANAGEMENTCONTACTTYPE_1.NAME AS ContactType, 
                         GLOBALENTITY_1.GLOBALENTITYNAME, GLOBALENTITY_1.FIRSTNAME, GLOBALENTITY_1.LASTNAME, GLOBALENTITY_1.GLOBALENTITYID
                  FROM PLPLANWFACTIONSTEP
                  INNER JOIN PLPLANWFSTEP ON PLPLANWFSTEP.PLPLANWFSTEPID = PLPLANWFACTIONSTEP.PLPLANWFSTEPID 
                  INNER JOIN PLPLAN ON PLPLANWFSTEP.PLPLANID = PLPLAN.PLPLANID 
                  INNER JOIN PLPLANCONTACT ON PLPLAN.PLPLANID = PLPLANCONTACT.PLPLANID 
                  INNER JOIN LANDMANAGEMENTCONTACTTYPE AS LANDMANAGEMENTCONTACTTYPE_1 ON PLPLANCONTACT.LANDMANAGEMENTCONTACTTYPEID = LANDMANAGEMENTCONTACTTYPE_1.LANDMANAGEMENTCONTACTTYPEID 
                  INNER JOIN GLOBALENTITY AS GLOBALENTITY_1 ON GLOBALENTITY_1.GLOBALENTITYID = PLPLANCONTACT.GLOBALENTITYID 
                 ) AS TB_PLAN ON IMINSPECTIONACTREF.OBJECTID = TB_PLAN.PLPLANWFACTIONSTEPID 

LEFT OUTER JOIN ( SELECT PMPERMITWFACTIONSTEP.PMPERMITWFACTIONSTEPID, LANDMANAGEMENTCONTACTTYPE.NAME AS ContactType, 
                         GLOBALENTITY.GLOBALENTITYNAME, GLOBALENTITY.FIRSTNAME, GLOBALENTITY.LASTNAME,GLOBALENTITY.GLOBALENTITYID
                  FROM PMPERMITWFACTIONSTEP
                  INNER JOIN PMPERMITWFSTEP ON PMPERMITWFSTEP.PMPERMITWFSTEPID = PMPERMITWFACTIONSTEP.PMPERMITWFSTEPID 
                  INNER JOIN PMPERMIT ON PMPERMITWFSTEP.PMPERMITID = PMPERMIT.PMPERMITID 
                  INNER JOIN PMPERMITCONTACT ON PMPERMIT.PMPERMITID = PMPERMITCONTACT.PMPERMITID 
                  INNER JOIN LANDMANAGEMENTCONTACTTYPE ON PMPERMITCONTACT.LANDMANAGEMENTCONTACTTYPEID = LANDMANAGEMENTCONTACTTYPE.LANDMANAGEMENTCONTACTTYPEID 
                  INNER JOIN GLOBALENTITY ON PMPERMITCONTACT.GLOBALENTITYID = GLOBALENTITY.GLOBALENTITYID 
                ) AS TB_PERMIT ON IMINSPECTIONACTREF.OBJECTID = TB_PERMIT.PMPERMITWFACTIONSTEPID

WHERE COALESCE (TB_PERMIT.ContactType, TB_PLAN.ContactType, TB_CODE.ContactType) IS NOT NULL
AND IMINSPECTIONACTREF.IMINSPECTIONID = @IMINSPECTIONID

UNION ALL

SELECT COALESCE (TB_PERMIT.ContactType, TB_PLAN.ContactType, TB_CODE.ContactType) AS ContactType, 
       COALESCE (TB_PERMIT.GLOBALENTITYNAME, TB_PLAN.GLOBALENTITYNAME, TB_CODE.GLOBALENTITYNAME) AS GlobalEntity, 
	   COALESCE (TB_PERMIT.GLOBALENTITYID, TB_PLAN.GLOBALENTITYID, TB_CODE.GLOBALENTITYID) AS GlobalEntityID,
	   COALESCE (TB_PERMIT.FIRSTNAME + ' ' + TB_PERMIT.LASTNAME, TB_PLAN.FIRSTNAME + ' ' + TB_PLAN.LASTNAME, TB_CODE.FIRSTNAME + ' ' + TB_CODE.LASTNAME) AS Name
FROM  IMINSPECTIONCASE
LEFT OUTER JOIN ( SELECT CMCODECASE.CMCODECASEID AS CMCODEWFACTIONSTEPID, CMCODECASECONTACTTYPE.NAME AS ContactType, GLOBALENTITY_2.GLOBALENTITYID,
                         GLOBALENTITY_2.GLOBALENTITYNAME, GLOBALENTITY_2.FIRSTNAME, GLOBALENTITY_2.LASTNAME
                  FROM CMCODECASE  
                  INNER JOIN CMCODECASECONTACT ON CMCODECASE.CMCODECASEID = CMCODECASECONTACT.CMCODECASEID 
                  INNER JOIN CMCODECASECONTACTTYPE ON CMCODECASECONTACT.CMCODECASECONTACTTYPEID = CMCODECASECONTACTTYPE.CMCODECASECONTACTTYPEID 
                  INNER JOIN GLOBALENTITY AS GLOBALENTITY_2 ON CMCODECASECONTACT.GLOBALENTITYID = GLOBALENTITY_2.GLOBALENTITYID 
                ) AS TB_CODE ON IMINSPECTIONCASE.LINKID = TB_CODE.CMCODEWFACTIONSTEPID 

LEFT OUTER JOIN ( SELECT PLPLAN.PLPLANID AS PLPLANWFACTIONSTEPID, LANDMANAGEMENTCONTACTTYPE_1.NAME AS ContactType, GLOBALENTITY_1.GLOBALENTITYID,
                         GLOBALENTITY_1.GLOBALENTITYNAME, GLOBALENTITY_1.FIRSTNAME, GLOBALENTITY_1.LASTNAME
                  FROM  PLPLAN 
                 INNER JOIN PLPLANCONTACT ON PLPLAN.PLPLANID = PLPLANCONTACT.PLPLANID 
                 INNER JOIN LANDMANAGEMENTCONTACTTYPE AS LANDMANAGEMENTCONTACTTYPE_1 ON PLPLANCONTACT.LANDMANAGEMENTCONTACTTYPEID = LANDMANAGEMENTCONTACTTYPE_1.LANDMANAGEMENTCONTACTTYPEID 
                 INNER JOIN GLOBALENTITY AS GLOBALENTITY_1 ON GLOBALENTITY_1.GLOBALENTITYID = PLPLANCONTACT.GLOBALENTITYID 
                 ) AS TB_PLAN ON IMINSPECTIONCASE.LINKID = TB_PLAN.PLPLANWFACTIONSTEPID 

LEFT OUTER JOIN ( SELECT PMPERMIT.PMPERMITID AS PMPERMITWFACTIONSTEPID, LANDMANAGEMENTCONTACTTYPE.NAME AS ContactType, GLOBALENTITY.GLOBALENTITYID,
                         GLOBALENTITY.GLOBALENTITYNAME, GLOBALENTITY.FIRSTNAME, GLOBALENTITY.LASTNAME
                  FROM PMPERMIT 
                  INNER JOIN PMPERMITCONTACT ON PMPERMIT.PMPERMITID = PMPERMITCONTACT.PMPERMITID 
                  INNER JOIN LANDMANAGEMENTCONTACTTYPE ON PMPERMITCONTACT.LANDMANAGEMENTCONTACTTYPEID = LANDMANAGEMENTCONTACTTYPE.LANDMANAGEMENTCONTACTTYPEID 
                  INNER JOIN GLOBALENTITY ON PMPERMITCONTACT.GLOBALENTITYID = GLOBALENTITY.GLOBALENTITYID 
                ) AS TB_PERMIT ON IMINSPECTIONCASE.LINKID = TB_PERMIT.PMPERMITWFACTIONSTEPID

WHERE COALESCE (TB_PERMIT.ContactType, TB_PLAN.ContactType, TB_CODE.ContactType) IS NOT NULL
AND IMINSPECTIONCASE.IMINSPECTIONCASEID = @IMINSPECTIONID

UNION ALL


SELECT LANDMANAGEMENTCONTACTTYPE.NAME AS ContactType, 
       GLOBALENTITYNAME AS GlobalEntity, GLOBALENTITY.GLOBALENTITYID,
       FIRSTNAME + ' ' + LASTNAME AS Name
FROM   IMINSPECTIONCONTACT 
                  LEFT OUTER JOIN LANDMANAGEMENTCONTACTTYPE ON IMINSPECTIONCONTACT.CONTACTTYPEID = LANDMANAGEMENTCONTACTTYPE.LANDMANAGEMENTCONTACTTYPEID 
                  LEFT OUTER JOIN GLOBALENTITY  ON IMINSPECTIONCONTACT.GLOBALENTITYID = GLOBALENTITY.GLOBALENTITYID 
				  WHERE IMINSPECTIONCONTACT.IMINSPECTIONID = @IMINSPECTIONID
