

/****** Object:  StoredProcedure [dbo].[rpt_IP_SR_Impact_Case_Detail_Report]    Script Date: 01/08/2014 15:58:52 ******/
CREATE PROCEDURE [dbo].[rpt_IP_SR_Impact_Case_Detail_Report]
@IPCASEID AS VARCHAR(36)
AS

SELECT	IPCASE.IPCASEID, IPCASE.CASENUMBER, IPCASE.CREATEDDATE, IPCASE.APPROVALDATE, IPCASE.APPROVALEXPIREDDATE, IPCASE.SOURCECASENUMBER, IPCASE.DESCRIPTION, 
		IPCASESTATUS.NAME AS IPCASESTATUS, 
		IPCASETYPE.NAME AS IPCASETYPE, 
--		CASE IPCASE.SOURCECASEENTITY 
--			WHEN 1 THEN 'PLAN'
--			WHEN 2 THEN 'PERMIT'
--			ElSE ''
--		END as SOURCECASETYPE,
		DISTRICT.NAME AS DISTRICT, 
		PRPROJECT.NAME AS PROJECT,
		(SELECT R.[IMAGE] FROM RPTIMAGELIB R
		WHERE R.IMAGENAME = 'Municipality_Logo') LOGO,
	   (SELECT CASE WHEN R.[IMAGE] IS NULL THEN 'N' ELSE 'Y' END FROM RPTIMAGELIB R
		WHERE R.IMAGENAME = 'Municipality_Logo') SHOWLOGO,
	   (SELECT R.REPORTTEXT FROM RPTTEXTLIB R
		WHERE R.TEXTNAME = 'Municipality_Name') Municipality_Name,	   
	   (SELECT R.REPORTTEXT FROM RPTTEXTLIB R
		WHERE R.TEXTNAME = 'Municipality_Page_Footer') Municipality_Page_Footer

FROM	IPCASE 
		INNER JOIN IPCASETYPE ON IPCASE.IPCASETYPEID = IPCASETYPE.IPCASETYPEID 
		INNER JOIN IPCASESTATUS ON IPCASE.IPCASESTATUSID = IPCASESTATUS.IPCASESTATUSID 
		LEFT OUTER JOIN DISTRICT ON IPCASE.DISTRICTID = DISTRICT.DISTRICTID
		LEFT OUTER JOIN PRPROJECT ON PRPROJECT.PRPROJECTID = IPCASE.PRPROJECTID

WHERE IPCASE.IPCASEID = @IPCASEID

