
CREATE PROCEDURE rpt_IL_Standard_Professional_License_Renewal
@ILLICENSEID VARCHAR(36),
	@REPORTID VARCHAR(36)
AS

DECLARE @CUSTOMFIELDS NVARCHAR(MAX) = '';
EXEC [dbo].[GetCustomReportText] @REPORTID, @ILLICENSEID, @CUSTOMFIELDS OUTPUT; 

--DECLARE @ILLICENSEID VARCHAR(36) = '876f4f57-6538-49d4-a3f6-2bb17d4d56a5'

/*BUILD OWNER INFO*/
SELECT BLC.ILLICENSEID, GE.FIRSTNAME, GE.LASTNAME, GE.GLOBALENTITYID, BLCT.NAME CONTACTTYPE, GE.GLOBALENTITYNAME COMPANYNAME, 
	BLC.ISBILLING, GE.GLOBALENTITYNAME, GE.[IMAGE], GE.ISCOMPANY, GE.ISCONTACT, GE.MIDDLENAME,
	ROW_NUMBER() OVER (PARTITION BY BLC.ILLICENSEID ORDER BY  GE.GLOBALENTITYID) AS ROWNBR,
	CASE	WHEN LEN(LTRIM(GE.BUSINESSPHONE)) > 0 THEN GE.BUSINESSPHONE 
		WHEN LEN(LTRIM(GE.MOBILEPHONE)) > 0 THEN GE.MOBILEPHONE 
		WHEN LEN(LTRIM(GE.HOMEPHONE)) > 0 THEN GE.HOMEPHONE 
		WHEN LEN(LTRIM(GE.OTHERPHONE)) > 0 THEN GE.OTHERPHONE 
		ELSE '' END AS PHONE
INTO #CONTACT
FROM ILLICENSECONTACT BLC
INNER JOIN GLOBALENTITY GE ON BLC.GLOBALENTITYID = GE.GLOBALENTITYID
INNER JOIN BLCONTACTTYPE BLCT ON BLC.BLCONTACTTYPEID = BLCT.BLCONTACTTYPEID 
WHERE BLC.ILLICENSEID = @ILLICENSEID AND BLCT.NAME LIKE '%OWNER%'

/*LOCATION ADDRESS*/
SELECT BLA.MAIN, BLA.ILLICENSEID, MA.ADDRESSTYPE, RTRIM(MA.ADDRESSLINE1 + ' ' +	LTRIM(MA.PREDIRECTION + ' ') + LTRIM(MA.ADDRESSLINE2 + ' ') + 
	LTRIM(MA.STREETTYPE + ' ') + LTRIM(MA.POSTDIRECTION + ' ') + LTRIM(MA.UNITORSUITE + ' ')  + LTRIM(MA.ADDRESSLINE3)) ADDRESS_LINE1,
	RTRIM(CASE WHEN RTRIM(LTRIM(MA.CITY)) = '' THEN '' ELSE LTRIM(MA.CITY + ', ' ) END + LTRIM(MA.STATE + ' ') + 
	(CASE WHEN LEN(REPLACE(ISNULL(MA.POSTALCODE,''),'-','')) > 5 
		THEN SUBSTRING(REPLACE(ISNULL(MA.POSTALCODE,''),'-',''),1,5) + '-' + SUBSTRING(REPLACE(ISNULL(MA.POSTALCODE,''),'-',''),6,4)
		ELSE REPLACE(ISNULL(MA.POSTALCODE,''),'-','') END)) ADDRESS_LINE2,
	ROW_NUMBER() OVER (PARTITION BY BLA.ILLICENSEID ORDER BY CASE WHEN MA.ADDRESSTYPE LIKE '%LOCATION%' THEN 1 ELSE 2 END ) AS ROWNBR
INTO #LOCADDRESS
FROM ILLICENSEADDRESS BLA
INNER JOIN MAILINGADDRESS MA ON BLA.MAILINGADDRESSID = MA.MAILINGADDRESSID
WHERE BLA.ILLICENSEID = @ILLICENSEID

/*MAILING ADDRESS*/
SELECT  G.GLOBALENTITYID, MA.ADDRESSTYPE, RTRIM(MA.ADDRESSLINE1 + ' ' +	LTRIM(MA.PREDIRECTION + ' ') + LTRIM(MA.ADDRESSLINE2 + ' ') + 
	LTRIM(MA.STREETTYPE + ' ') + LTRIM(MA.POSTDIRECTION + ' ') + LTRIM(MA.UNITORSUITE + ' ')  + LTRIM(MA.ADDRESSLINE3)) ADDRESS_LINE1,
	RTRIM(CASE WHEN RTRIM(LTRIM(MA.CITY)) = '' THEN '' ELSE LTRIM(MA.CITY + ', ' ) END + LTRIM(MA.STATE + ' ') + 
	(CASE WHEN LEN(REPLACE(ISNULL(MA.POSTALCODE,''),'-','')) > 5 
		THEN SUBSTRING(REPLACE(ISNULL(MA.POSTALCODE,''),'-',''),1,5) + '-' + SUBSTRING(REPLACE(ISNULL(MA.POSTALCODE,''),'-',''),6,4)
		ELSE REPLACE(ISNULL(MA.POSTALCODE,''),'-','') END)) ADDRESS_LINE2,
	ROW_NUMBER() OVER (PARTITION BY G.GLOBALENTITYID ORDER BY CASE WHEN MA.ADDRESSTYPE LIKE '%MAILING%' THEN 1 ELSE 2 END ) AS ROWNBR
INTO #BUSADDRESS
FROM GLOBALENTITYMAILINGADDRESS G
INNER JOIN MAILINGADDRESS MA ON G.MAILINGADDRESSID = MA.MAILINGADDRESSID

/*ALL LICENSE FEES*/
SELECT BLF.ILLICENSEID, C.COMPUTEDAMOUNT FEEAMOUNT, C.FEENAME
INTO #FEES
FROM ILLICENSEFEE BLF
INNER JOIN CACOMPUTEDFEE C ON C.CACOMPUTEDFEEID = BLF.CACOMPUTEDFEEID
WHERE BLF.ILLICENSEID = @ILLICENSEID AND
	C.CASTATUSID NOT IN (5,9,10) AND 
	C.FEENAME NOT LIKE '%PENALTY%' AND
	(C.FEENAME NOT LIKE '% late %'
	AND C.FEENAME NOT LIKE 'late %'
	AND C.FEENAME NOT LIKE '% late')


CREATE INDEX TEMP1 ON #CONTACT (ILLICENSEID);
CREATE INDEX TEMP1 ON #LOCADDRESS (ILLICENSEID);
CREATE INDEX TEMP2 ON #LOCADDRESS (ROWNBR);
CREATE INDEX TEMP1 ON #BUSADDRESS (GLOBALENTITYID);
CREATE INDEX TEMP2 ON #BUSADDRESS (ROWNBR);
CREATE INDEX TEMP1 ON #FEES (ILLICENSEID);


/*BEGIN MAIN QUERY*/

SELECT IL.ILLICENSEID, IL.LICENSENUMBER, CASE WHEN IL.EXPIRATIONDATE = '1/1/2999' THEN NULL ELSE IL.EXPIRATIONDATE END AS EXPIRATIONDATE,
	IL.LICENSEYEAR,
	IL.ISSUEDATE,
	CASE WHEN GE.ISCOMPANY = 1 THEN GE.GLOBALENTITYNAME ELSE GE.FIRSTNAME + ' ' + GE.LASTNAME END AS BUSINESSNAME,
	CASE WHEN OWN.ISCOMPANY = 1 THEN OWN.GLOBALENTITYNAME ELSE OWN.FIRSTNAME + ' ' + OWN.LASTNAME  END OWNERNAME,
	MA.ADDRESS_LINE1 MADDRESS_LINE1, MA.ADDRESS_LINE2 MADDRESS_LINE2,
	LOC.ADDRESS_LINE1, LOC.ADDRESS_LINE2,
	ILT.NAME LICENSETYPE,
	ILC.NAME LICENSECLASS,
	F.FEENAME,
	F.FEEAMOUNT,
	STUFF((select  ', '+ (I3.NAME) 
			FROM ILLICENSE I
			INNER JOIN ILLICENSECLASSTYPEXREF I2 ON I.ILLICENSEID = I2.ILLICENSEID
			INNER JOIN ILLICENSECLASSTYPE I3 ON I3.ILLICENSECLASSTYPEID = I2.ILLICENSECLASSTYPEID
			WHERE I.ILLICENSEID = @ILLICENSEID
			for xml path(''), root('MyString'), type
		).value('/MyString[1]','varchar(max)'),1,2,'') AS 'BUSINESSTYPE',
	CASE WHEN (SELECT ISNULL(R.REPORTTEXT,'') FROM RPTTEXTLIB R
		WHERE R.TEXTNAME = 'Business_License_Renewal_Municipality_Name') = '' 
		THEN (SELECT R.REPORTTEXT FROM RPTTEXTLIB R
		WHERE R.TEXTNAME = 'Municipality_Name')
		ELSE (SELECT R.REPORTTEXT FROM RPTTEXTLIB R
		WHERE R.TEXTNAME = 'Business_License_Renewal_Municipality_Name') END Municipality_Name,
	CASE WHEN (SELECT ISNULL(R.REPORTTEXT,'') FROM RPTTEXTLIB R
		WHERE R.TEXTNAME = 'Business_License_Renewal_Municipality_Address') = '' 
		THEN (SELECT R.REPORTTEXT FROM RPTTEXTLIB R
		WHERE R.TEXTNAME = 'Municipality_Address')
		ELSE (SELECT R.REPORTTEXT FROM RPTTEXTLIB R
		WHERE R.TEXTNAME = 'Business_License_Renewal_Municipality_Address') END Municipality_Address,
	CASE WHEN (SELECT ISNULL(R.REPORTTEXT,'') FROM RPTTEXTLIB R
		WHERE R.TEXTNAME = 'Business_License_Renewal_Municipality_Phone_Number') = '' 
		THEN (SELECT R.REPORTTEXT FROM RPTTEXTLIB R
		WHERE R.TEXTNAME = 'Municipality_Phone_Number')
		ELSE (SELECT R.REPORTTEXT FROM RPTTEXTLIB R
		WHERE R.TEXTNAME = 'Business_License_Renewal_Municipality_Phone_Number') END Municipality_Phone_Number,
	(SELECT REPLACE(R.REPORTTEXT,CHAR(10),'<BR>') FROM RPTTEXTLIB R
		WHERE R.TEXTNAME = 'Professional_License_Renewal_Text1') Business_License_Renewal_Text1,
	(SELECT REPLACE(R.REPORTTEXT,CHAR(10),'<BR>') FROM RPTTEXTLIB R
		WHERE R.TEXTNAME = 'Professional_License_Renewal_Text2') Business_License_Renewal_Text2,
	(SELECT REPLACE(R.REPORTTEXT,CHAR(10),'<BR>') FROM RPTTEXTLIB R
		WHERE R.TEXTNAME = 'Professional_License_Renewal_Text3') Business_License_Renewal_Text3,
	(SELECT R.[IMAGE] FROM RPTIMAGELIB R
		WHERE R.IMAGENAME = 'Business_License_Logo') LOGO,
	(SELECT CASE WHEN R.[IMAGE] IS NULL  THEN 'N' ELSE 'Y' END FROM RPTIMAGELIB R
		WHERE R.IMAGENAME = 'Business_License_Logo') SHOWLOGO,
	@CUSTOMFIELDS CUSTOMFIELDS
FROM ILLICENSE IL
INNER JOIN GLOBALENTITY GE ON IL.GLOBALENTITYID = GE.GLOBALENTITYID
LEFT JOIN #CONTACT OWN ON IL.ILLICENSEID = OWN.ILLICENSEID
LEFT JOIN #LOCADDRESS LOC ON LOC.ILLICENSEID = IL.ILLICENSEID AND LOC.ROWNBR = 1
LEFT JOIN #BUSADDRESS MA ON MA.GLOBALENTITYID = GE.GLOBALENTITYID AND MA.ROWNBR = 1
LEFT JOIN ILLICENSETYPE ILT ON IL.ILLICENSETYPEID = ILT.ILLICENSETYPEID
LEFT JOIN ILLICENSECLASSIFICATION ILC ON IL.ILLICENSECLASSIFICATIONID = ILC.ILLICENSECLASSIFICATIONID
LEFT JOIN #FEES F ON IL.ILLICENSEID = F.ILLICENSEID
WHERE IL.ILLICENSEID = @ILLICENSEID

DROP TABLE #CONTACT;
DROP TABLE #LOCADDRESS;
DROP TABLE #BUSADDRESS;
DROP TABLE #FEES;