

/****** OBJECT:  StoredProcedure [dbo].[rpt_IP_SR_Impact_Case_Attached_Records_Report_Permit]    Script Date: 01/08/2014 15:58:52 ******/
CREATE PROCEDURE [dbo].[rpt_IP_SR_Impact_Case_Attached_Records_Report_Permit]
@IPCASEID AS VARCHAR(36)
AS

SELECT	IPCASEPERMITXREF.IPCASEID, 
		PMPERMIT.PMPERMITID, PMPERMIT.PERMITNUMBER, 
		PMPERMITTYPE.NAME PERMITTYPE, 
		PMPERMITWORKCLASS.NAME PERMITCLASS,
		PMPERMITSTATUS.NAME PMPERMITSTATUS,
		PERMIT_CONTACTS.ISBILLING, PERMIT_CONTACTS.CONTACTTYPE, PERMIT_CONTACTS.GLOBALENTITYNAME, PERMIT_CONTACTS.FIRSTNAME, PERMIT_CONTACTS.LASTNAME

FROM	IPCASEPERMITXREF 
		INNER JOIN PMPERMIT ON IPCASEPERMITXREF.PMPERMITID = PMPERMIT.PMPERMITID
		INNER JOIN PMPERMITTYPE ON PMPERMIT.PMPERMITTYPEID = PMPERMITTYPE.PMPERMITTYPEID
		INNER JOIN PMPERMITWORKCLASS ON PMPERMIT.PMPERMITWORKCLASSID = PMPERMITWORKCLASS.PMPERMITWORKCLASSID
		INNER JOIN PMPERMITSTATUS ON PMPERMIT.PMPERMITSTATUSID = PMPERMITSTATUS.PMPERMITSTATUSID
		LEFT OUTER JOIN (SELECT PMPERMITCONTACT.PMPERMITID, PMPERMITCONTACT.ISBILLING,
								GLOBALENTITY.GLOBALENTITYNAME, GLOBALENTITY.FIRSTNAME, GLOBALENTITY.LASTNAME,
								LANDMANAGEMENTCONTACTTYPE.NAME CONTACTTYPE
						 FROM	PMPERMITCONTACT 
								INNER JOIN LANDMANAGEMENTCONTACTTYPE ON PMPERMITCONTACT.LANDMANAGEMENTCONTACTTYPEID = LANDMANAGEMENTCONTACTTYPE.LANDMANAGEMENTCONTACTTYPEID
								INNER JOIN GLOBALENTITY ON PMPERMITCONTACT.GLOBALENTITYID = GLOBALENTITY.GLOBALENTITYID
						) AS PERMIT_CONTACTS ON PMPERMIT.PMPERMITID = PERMIT_CONTACTS.PMPERMITID

WHERE	IPCASEPERMITXREF.IPCASEID = @IPCASEID

