
CREATE PROCEDURE rpt_IP_SR_Impact_Reconciliation_Report
@ENDDATE		DATETIME 
AS

SET NOCOUNT ON
SET @ENDDATE = DATEADD(S,-1,DATEADD(D,1,@ENDDATE))

SELECT	IPCONDITIONCATEGORY.IPCONDITIONCATEGORYID, IPCONDITIONCATEGORY.PREFIX 'IPCONDITIONCATEGORY_PREFIX', 
		IPCONDITIONCATEGORY.NAME as CATEGORYNAME,
		SUM( CATRANSACTIONFEE.PAIDAMOUNT ) 'PAIDAMOUNT',
		SUM( CATRANSACTIONFEE.REFUNDAMOUNT ) 'REFUNDAMOUNT',
		--(SELECT R.[IMAGE] FROM RPTIMAGELIB R
		--	WHERE R.IMAGENAME = 'Municipality_Logo') LOGO,
		(SELECT CASE WHEN R.[IMAGE] IS NULL THEN 'N' ELSE 'Y' END FROM RPTIMAGELIB R
			WHERE R.IMAGENAME = 'Municipality_Logo') SHOWLOGO,
		(SELECT R.REPORTTEXT FROM RPTTEXTLIB R
			WHERE R.TEXTNAME = 'Municipality_Name') Municipality_Name,	   
		(SELECT R.REPORTTEXT FROM RPTTEXTLIB R
			WHERE R.TEXTNAME = 'Municipality_Page_Footer') Municipality_Page_Footer
	
FROM	IPCASE 
		INNER JOIN IPCONDITION ON IPCASE.IPCASEID = IPCONDITION.IPCASEID AND IPCONDITION.MONETARY = 1
		INNER JOIN IPCONDITIONTYPE ON IPCONDITION.IPCONDITIONTYPEID = IPCONDITIONTYPE.IPCONDITIONTYPEID
		INNER JOIN IPCONDITIONCATEGORY ON IPCONDITIONTYPE.IPCONDITIONCATEGORYID = IPCONDITIONCATEGORY.IPCONDITIONCATEGORYID
		INNER JOIN IPCONDITIONFEE ON IPCONDITION.IPCONDITIONID = IPCONDITIONFEE.IPCONDITIONID
		INNER JOIN CACOMPUTEDFEE ON IPCONDITIONFEE.CACOMPUTEDFEEID = CACOMPUTEDFEE.CACOMPUTEDFEEID AND CACOMPUTEDFEE.CASTATUSID not in (5,10) --Void, Deleted
		INNER JOIN CATRANSACTIONFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CATRANSACTIONFEE.CACOMPUTEDFEEID
		INNER JOIN CATRANSACTION ON CATRANSACTIONFEE.CATRANSACTIONID = CATRANSACTION.CATRANSACTIONID
		
WHERE	CATRANSACTION.TRANSACTIONDATE < @ENDDATE

GROUP BY IPCONDITIONCATEGORY.NAME, IPCONDITIONCATEGORY.IPCONDITIONCATEGORYID, IPCONDITIONCATEGORY.PREFIX

ORDER BY IPCONDITIONCATEGORY.NAME

