

CREATE PROCEDURE [dbo].[rpt_IM_Year_Over_Year_Inspection_Report_By_Inspection_Type]
@YEAR AS INT
AS
SELECT IMINSPECTIONTYPE.NAME AS InspectionType, IMINSPECTION.INSPECTIONNUMBER AS InspectionNumber, 
       IMINSPECTION.SCHEDULEDSTARTDATE AS ScheduledStartDate, IMINSPECTION.SCHEDULEDENDDATE AS ScheduledEndDate, 
       IMINSPECTION.ACTUALSTARTDATE AS ActualStartDate, IMINSPECTION.ACTUALENDDATE AS ActualEndDate
FROM IMINSPECTION 
INNER JOIN IMINSPECTIONTYPE ON IMINSPECTION.IMINSPECTIONTYPEID = IMINSPECTIONTYPE.IMINSPECTIONTYPEID

