

-- [dbo].[rpt_IM_Inspection_Worksheet] 'DC1B5B1C-36D3-4BFA-92FB-62455F2F9640'
CREATE PROCEDURE [dbo].[rpt_IM_Inspection_Worksheet]
@IMINSPECTIONID AS VARCHAR(36)
AS
SELECT IMINSPECTION.INSPECTIONNUMBER AS InspectionNumber, IMINSPECTION.LINKNUMBER AS CaseNumber, IMINSPECTION.ACTUALSTARTDATE AS ActualStartDate, 
       IMINSPECTIONTYPE.NAME AS InspectionType, IMINSPECTIONSTATUS.STATUSNAME AS InspectionStatus, WFENTITY.NAME AS Entity, MAILINGADDRESS.ADDRESSLINE1, 
	   MAILINGADDRESS.ADDRESSLINE2, MAILINGADDRESS.ADDRESSLINE3, MAILINGADDRESS.CITY, MAILINGADDRESS.STATE, 
	   MAILINGADDRESS.POSTALCODE, MAILINGADDRESS.POSTDIRECTION, MAILINGADDRESS.PREDIRECTION, MAILINGADDRESS.STREETTYPE, 
	   MAILINGADDRESS.UNITORSUITE, CHECKLIST.ChecklistItem, CHECKLIST.Passed, CHECKLIST.Comments
	   , (SELECT PARCEL.PARCELNUMBER AS ParcelNumber
			FROM IMINSPECTIONPARCEL 
			INNER JOIN PARCEL ON IMINSPECTIONPARCEL.PARCELID = PARCEL.PARCELID
			WHERE IMINSPECTIONPARCEL.IMINSPECTIONID = @IMINSPECTIONID
			and IMINSPECTIONPARCEL.MAIN = 1) PARCELID
		,(SELECT USERS.FNAME + ' ' + USERS.LNAME AS Inspector
			FROM IMINSPECTORREF 
			INNER JOIN USERS ON IMINSPECTORREF.USERID = USERS.SUSERGUID
			WHERE IMINSPECTORREF.INSPECTIONID = @IMINSPECTIONID 
				AND IMINSPECTORREF.BPRIMARY = 1) INSPECTOR
FROM IMINSPECTION 
INNER JOIN IMINSPECTIONTYPE ON IMINSPECTION.IMINSPECTIONTYPEID = IMINSPECTIONTYPE.IMINSPECTIONTYPEID 
INNER JOIN IMINSPECTIONSTATUS ON IMINSPECTION.IMINSPECTIONSTATUSID = IMINSPECTIONSTATUS.IMINSPECTIONSTATUSID 
INNER JOIN WFENTITY ON IMINSPECTION.IMINSPECTIONREQUESTEDSOURCEID = WFENTITY.WFENTITYID
LEFT  JOIN (SELECT MAILINGADDRESS.ADDRESSLINE1, MAILINGADDRESS.ADDRESSLINE2, MAILINGADDRESS.ADDRESSLINE3, MAILINGADDRESS.CITY, MAILINGADDRESS.STATE, 
				   MAILINGADDRESS.POSTALCODE, MAILINGADDRESS.POSTDIRECTION, MAILINGADDRESS.PREDIRECTION, MAILINGADDRESS.STREETTYPE, 
				   MAILINGADDRESS.UNITORSUITE, IMINSPECTIONADDRESS.IMINSPECTIONID
			FROM MAILINGADDRESS 
			INNER JOIN IMINSPECTIONADDRESS ON MAILINGADDRESS.MAILINGADDRESSID = IMINSPECTIONADDRESS.MAILINGADDRESSID
			WHERE IMINSPECTIONADDRESS.IMINSPECTIONID = @IMINSPECTIONID 
			AND IMINSPECTIONADDRESS.MAIN = 'TRUE') AS MAILINGADDRESS ON IMINSPECTION.IMINSPECTIONID = MAILINGADDRESS.IMINSPECTIONID
LEFT  JOIN (SELECT IMCHECKLIST.NAME AS ChecklistItem, IMINSPECTIONCHECKLISTXREF.PASSED AS Passed, IMINSPECTIONCHECKLISTXREF.COMMENTS AS Comments, IMINSPECTIONCHECKLISTXREF.IMINSPECTIONID
			FROM IMCHECKLIST 
			INNER JOIN IMINSPECTIONCHECKLISTXREF ON IMCHECKLIST.IMCHECKLISTID = IMINSPECTIONCHECKLISTXREF.IMCHECKLISTID) AS CHECKLIST ON IMINSPECTION.IMINSPECTIONID = CHECKLIST.IMINSPECTIONID
WHERE IMINSPECTION.IMINSPECTIONID = @IMINSPECTIONID

UNION ALL

SELECT 
IMINSPECTIONCASE.CASENO AS InspectionNumber,
       IMINSPECTIONCASE.LINKNUMBER AS CaseNumber, 
	   IMINSPECTIONCASE.STARTDATE AS ActualStartDate, 
       IMINSPECTIONCASETYPE.NAME AS InspectionType, IMINSPECTIONCASESTATUS.NAME AS InspectionStatus,
	   CHECKLIST.LINK_TYPE AS Entity, 
		MAILINGADDRESS.ADDRESSLINE1, 
	   MAILINGADDRESS.ADDRESSLINE2, MAILINGADDRESS.ADDRESSLINE3, MAILINGADDRESS.CITY, MAILINGADDRESS.STATE, 
	   MAILINGADDRESS.POSTALCODE, MAILINGADDRESS.POSTDIRECTION, MAILINGADDRESS.PREDIRECTION, MAILINGADDRESS.STREETTYPE, 
	   MAILINGADDRESS.UNITORSUITE, CHECKLIST.ChecklistItem, CHECKLIST.Passed, CHECKLIST.Comments,
	    (SELECT PARCEL.PARCELNUMBER AS ParcelNumber
			FROM IMINSPECTIONCASEPARCEL 
			INNER JOIN PARCEL ON IMINSPECTIONCASEPARCEL.PARCELID = PARCEL.PARCELID
			WHERE IMINSPECTIONCASEPARCEL.IMINSPECTIONCASEID = @IMINSPECTIONID
			and IMINSPECTIONCASEPARCEL.MAIN = 1) PARCELID,
		(SELECT USERS.FNAME + ' ' + USERS.LNAME AS Inspector
			FROM IMINSPECTORREF 
			INNER JOIN USERS ON IMINSPECTORREF.USERID = USERS.SUSERGUID
			WHERE IMINSPECTORREF.INSPECTIONID = @IMINSPECTIONID
				AND IMINSPECTORREF.BPRIMARY = 1) INSPECTOR
FROM IMINSPECTIONCASE
INNER JOIN IMINSPECTIONCASETYPE ON IMINSPECTIONCASE.IMINSPECTIONCASETYPEID = IMINSPECTIONCASETYPE.IMINSPECTIONCASETYPEID 
INNER JOIN IMINSPECTIONCASESTATUS ON IMINSPECTIONCASE.IMINSPECTIONCASESTATUSID = IMINSPECTIONCASESTATUS.IMINSPECTIONCASESTATUSID 

LEFT  JOIN (SELECT MAILINGADDRESS.ADDRESSLINE1, MAILINGADDRESS.ADDRESSLINE2, MAILINGADDRESS.ADDRESSLINE3, MAILINGADDRESS.CITY, MAILINGADDRESS.STATE, 
				   MAILINGADDRESS.POSTALCODE, MAILINGADDRESS.POSTDIRECTION, MAILINGADDRESS.PREDIRECTION, MAILINGADDRESS.STREETTYPE, 
				   MAILINGADDRESS.UNITORSUITE, IMINSPECTIONCASEADDRESS.IMINSPECTIONCASEID AS IMINSPECTIONID 
			FROM MAILINGADDRESS 
			INNER JOIN IMINSPECTIONCASEADDRESS ON MAILINGADDRESS.MAILINGADDRESSID = IMINSPECTIONCASEADDRESS.MAILINGADDRESSID
			WHERE IMINSPECTIONCASEADDRESS.IMINSPECTIONCASEID = @IMINSPECTIONID
			AND IMINSPECTIONCASEADDRESS.MAIN = 'TRUE') AS MAILINGADDRESS ON IMINSPECTIONCASE.IMINSPECTIONCASEID = MAILINGADDRESS.IMINSPECTIONID
LEFT  JOIN (SELECT IMCHECKLIST.NAME AS ChecklistItem, IMINSPECTIONCHECKLISTXREF.PASSED AS Passed, IMINSPECTIONCHECKLISTXREF.COMMENTS AS Comments, IMINSPECTIONCASE.IMINSPECTIONCASEID,
                   IMINSPECTIONLINK.NAME  AS LINK_TYPE
			FROM IMINSPECTIONCASE 
			INNER JOIN IMINSPECTION ON IMINSPECTIONCASE.IMINSPECTIONCASEID  = IMINSPECTION.IMINSPECTIONCASEID
			INNER JOIN IMINSPECTIONLINK ON IMINSPECTION.IMINSPECTIONLINKID = IMINSPECTIONLINK.IMINSPECTIONLINKID
			LEFT JOIN IMINSPECTIONCHECKLISTXREF ON IMINSPECTION.IMINSPECTIONID = IMINSPECTIONCHECKLISTXREF.IMINSPECTIONID
			LEFT JOIN IMCHECKLIST ON IMINSPECTIONCHECKLISTXREF.IMCHECKLISTID = IMCHECKLIST.IMCHECKLISTID 

			WHERE IMINSPECTIONCASE.IMINSPECTIONCASEID = @IMINSPECTIONID
			) AS CHECKLIST ON IMINSPECTIONCASE.IMINSPECTIONCASEID = CHECKLIST.IMINSPECTIONCASEID
WHERE IMINSPECTIONCASE.IMINSPECTIONCASEID = @IMINSPECTIONID



