CREATE PROCEDURE [dbo].[USP_ILLICENSETYPELICENSEGROUP_DELETE_BYPARENTID]
(
	@ILLICENSETYPEID CHAR(36)
)
AS
	DELETE FROM
			[dbo].[ILLICENSETYPELICENSEGROUP]
	WHERE
		ILLICENSETYPEID = @ILLICENSETYPEID