CREATE PROCEDURE [dbo].[USP_IPASSESSMENTMILESTONE_DELETE]
(
	@IPASSESSMENTMILESTONEID CHAR(36),
	@ROWVERSION INT
)
AS
DELETE FROM [dbo].[IPASSESSMENTMILESTONE]
WHERE
	[IPASSESSMENTMILESTONEID] = @IPASSESSMENTMILESTONEID AND 
	[ROWVERSION]= @ROWVERSION