CREATE PROCEDURE [dbo].[USP_IMINSPECTIONCALENDAR_INSERT]
(
	@IMINSPECTIONCALENDARID CHAR(36),
	@NAME NVARCHAR(50),
	@USESYSTEMHOLIDAYS BIT,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
INSERT INTO [dbo].[IMINSPECTIONCALENDAR](
	[IMINSPECTIONCALENDARID],
	[NAME],
	[USESYSTEMHOLIDAYS],
	[LASTCHANGEDBY],
	[LASTCHANGEDON],
	[ROWVERSION]
)
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
VALUES
(
	@IMINSPECTIONCALENDARID,
	@NAME,
	@USESYSTEMHOLIDAYS,
	@LASTCHANGEDBY,
	@LASTCHANGEDON,
	@ROWVERSION
)
SELECT * FROM @OUTPUTTABLE