CREATE PROCEDURE [dbo].[USP_IMINSPECTORTYPEINSPECTIONTYPE_DELETE_BYPARENTID]
(
@PARENTID CHAR(36)
)
AS
DELETE FROM [dbo].[IMINSPECTORTYPEINSPECTIONTYPE]
WHERE [dbo].[IMINSPECTORTYPEINSPECTIONTYPE].[IMINSPECTORTYPEID] = @PARENTID