CREATE PROCEDURE [dbo].[USP_ILLICENSEGROUP_DELETE]
(
	@ILLICENSEGROUPID CHAR(36),
	@ROWVERSION INT
)
AS
DELETE FROM [dbo].[ILLICENSEGROUP]
WHERE
	[ILLICENSEGROUPID] = @ILLICENSEGROUPID AND 
	[ROWVERSION]= @ROWVERSION