CREATE PROCEDURE [dbo].[USP_ILLICENSETYPELICENSECLASS_INSERT]
(
	@ILLICENSETYPELICENSECLASSID CHAR(36),
	@ILLICENSECLASSIFICATIONID CHAR(36),
	@ILLICENSETYPEID CHAR(36),
	@LICENSECYCLEID CHAR(36),
	@CUSTOMFIELDLAYOUTID CHAR(36),
	@WFTEMPLATEID CHAR(36),
	@CAFEETEMPLATEID CHAR(36),
	@ILLICENSECAPAPPLICATIONTYPEID INT,
	@INTERNETFLAG BIT,
	@ONLINECUSTOMFIELDLAYOUTID CHAR(36),
	@WFTEMPLATERENEWALID CHAR(36),
	@RENEWALDAYSPRIORTOEXPIRE INT,
	@CAPADDRESSREQUIRED BIT,
	@CANRENEWONLINE BIT,
	@CAPRENEWALAPPLICATIONTYPEID INT
)
AS

INSERT INTO [dbo].[ILLICENSETYPELICENSECLASS](
	[ILLICENSETYPELICENSECLASSID],
	[ILLICENSECLASSIFICATIONID],
	[ILLICENSETYPEID],
	[LICENSECYCLEID],
	[CUSTOMFIELDLAYOUTID],
	[WFTEMPLATEID],
	[CAFEETEMPLATEID],
	[ILLICENSECAPAPPLICATIONTYPEID],
	[INTERNETFLAG],
	[ONLINECUSTOMFIELDLAYOUTID],
	[WFTEMPLATERENEWALID],
	[RENEWALDAYSPRIORTOEXPIRE],
	[CAPADDRESSREQUIRED],
	[CANRENEWONLINE],
	[CAPRENEWALAPPLICATIONTYPEID]
)

VALUES
(
	@ILLICENSETYPELICENSECLASSID,
	@ILLICENSECLASSIFICATIONID,
	@ILLICENSETYPEID,
	@LICENSECYCLEID,
	@CUSTOMFIELDLAYOUTID,
	@WFTEMPLATEID,
	@CAFEETEMPLATEID,
	@ILLICENSECAPAPPLICATIONTYPEID,
	@INTERNETFLAG,
	@ONLINECUSTOMFIELDLAYOUTID,
	@WFTEMPLATERENEWALID,
	@RENEWALDAYSPRIORTOEXPIRE,
	@CAPADDRESSREQUIRED,
	@CANRENEWONLINE,
	@CAPRENEWALAPPLICATIONTYPEID
)