CREATE PROCEDURE [dbo].[USP_IMINSPECTIONCALENDAR_UPDATE]
(
	@IMINSPECTIONCALENDARID CHAR(36),
	@NAME NVARCHAR(50),
	@USESYSTEMHOLIDAYS BIT,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
UPDATE [dbo].[IMINSPECTIONCALENDAR] SET
	[NAME] = @NAME,
	[USESYSTEMHOLIDAYS] = @USESYSTEMHOLIDAYS,
	[LASTCHANGEDBY] = @LASTCHANGEDBY,
	[LASTCHANGEDON] = @LASTCHANGEDON,
	[ROWVERSION] = @ROWVERSION + 1
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE
	[IMINSPECTIONCALENDARID] = @IMINSPECTIONCALENDARID AND 
	[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE