CREATE PROCEDURE [dbo].[USP_IMINSPECTORTYPEINSPECTIONTYPE_INSERT]
(
	@IMINSPECTORTYPEID CHAR(36),
	@IMINSPECTIONTYPEID CHAR(36)
)
AS

INSERT INTO [dbo].[IMINSPECTORTYPEINSPECTIONTYPE](
	[dbo].[IMINSPECTORTYPEINSPECTIONTYPE].[IMINSPECTORTYPEID],
	[dbo].[IMINSPECTORTYPEINSPECTIONTYPE].[IMINSPECTIONTYPEID]
)
VALUES
(
	@IMINSPECTORTYPEID,
	@IMINSPECTIONTYPEID
)