CREATE PROCEDURE [dbo].[USP_IMINSPECTIONSTATUS_UPDATE]
(
	@IMINSPECTIONSTATUSID CHAR(36),
	@STATUSNAME NVARCHAR(50),
	@DESCRIPTION NVARCHAR(MAX),
	@INDICATESSUCCESS BIT,
	@IMINSPECTIONSTATUSENTITYID CHAR(36),
	@REINSPECTIONFLAG BIT,
	@INVIOLATIONFLAG BIT,
	@OUTOFVIOLATIONFLAG BIT,
	@EXTEND_EXPIRE_DATE BIT,
	@SCHEDULEDFLAG BIT,
	@WAITFLAG BIT,
	@PARTIALPASS BIT,
	@CANCELLEDFLAG BIT,
	@DESCRIPTION_SPANISH NVARCHAR(MAX),
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
UPDATE [dbo].[IMINSPECTIONSTATUS] SET
	[STATUSNAME] = @STATUSNAME,
	[DESCRIPTION] = @DESCRIPTION,
	[INDICATESSUCCESS] = @INDICATESSUCCESS,
	[IMINSPECTIONSTATUSENTITYID] = @IMINSPECTIONSTATUSENTITYID,
	[REINSPECTIONFLAG] = @REINSPECTIONFLAG,
	[INVIOLATIONFLAG] = @INVIOLATIONFLAG,
	[OUTOFVIOLATIONFLAG] = @OUTOFVIOLATIONFLAG,
	[EXTEND_EXPIRE_DATE] = @EXTEND_EXPIRE_DATE,
	[SCHEDULEDFLAG] = @SCHEDULEDFLAG,
	[WAITFLAG] = @WAITFLAG,
	[PARTIALPASS] = @PARTIALPASS,
	[CANCELLEDFLAG] = @CANCELLEDFLAG,
	[DESCRIPTION_SPANISH] = @DESCRIPTION_SPANISH,
	[LASTCHANGEDBY] = @LASTCHANGEDBY,
	[LASTCHANGEDON] = @LASTCHANGEDON,
	[ROWVERSION] = @ROWVERSION + 1
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE
	[IMINSPECTIONSTATUSID] = @IMINSPECTIONSTATUSID AND 
	[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE