CREATE PROCEDURE [dbo].[USP_IMNONCOMPLIANCECODEREVISION_INSERT]
(
	@IMNONCOMPLIANCECODEREVISIONID CHAR(36),
	@IMNONCOMPLIANCECODEID CHAR(36),
	@CODETEXT NVARCHAR(2000),
	@DEFAULTCOMMENTS NVARCHAR(2000),
	@REVISIONDATE DATETIME,
	@CURRENTREVISION BIT,
	@STARTDATE DATETIME,
	@ENDDATE DATETIME,
	@REVISIONNUMBER INT
)
AS

INSERT INTO [dbo].[IMNONCOMPLIANCECODEREVISION](
	[IMNONCOMPLIANCECODEREVISIONID],
	[IMNONCOMPLIANCECODEID],
	[CODETEXT],
	[DEFAULTCOMMENTS],
	[REVISIONDATE],
	[CURRENTREVISION],
	[STARTDATE],
	[ENDDATE],
	[REVISIONNUMBER]
)

VALUES
(
	@IMNONCOMPLIANCECODEREVISIONID,
	@IMNONCOMPLIANCECODEID,
	@CODETEXT,
	@DEFAULTCOMMENTS,
	@REVISIONDATE,
	@CURRENTREVISION,
	@STARTDATE,
	@ENDDATE,
	@REVISIONNUMBER
)