CREATE PROCEDURE [dbo].[USP_IPCASEALLOWEDCONTACTTYPE_DELETE]
(
@IPCASEALLOWEDCONTACTTYPEID CHAR(36)
)
AS
DELETE FROM [dbo].[IPCASEALLOWEDCONTACTTYPE]
WHERE
	[IPCASEALLOWEDCONTACTTYPEID] = @IPCASEALLOWEDCONTACTTYPEID