CREATE PROCEDURE [dbo].[USP_IMINSPECTIONCASESTATUS_DELETE]
(
	@IMINSPECTIONCASESTATUSID CHAR(36),
	@ROWVERSION INT
)
AS
DELETE FROM [dbo].[IMINSPECTIONCASESTATUS]
WHERE
	[IMINSPECTIONCASESTATUSID] = @IMINSPECTIONCASESTATUSID AND 
	[ROWVERSION]= @ROWVERSION