CREATE PROCEDURE [dbo].[USP_INTEGRATION_UPDATE_CAINTEGRATIONBATCHPROCESS_BATCH_TOTAL]
	@BATCH_TOTAL AS MONEY,
	@BATCH_ID AS NVARCHAR(50)
AS

BEGIN

UPDATE CAINTEGRATIONBATCHPROCESS 
SET BATCH_TOTAL = @BATCH_TOTAL 
WHERE FINANCEBATCHID = @BATCH_ID

END