CREATE PROCEDURE [dbo].[USP_INTEGRATION_INSERT_AR_AUDIT_LOG]
	@BATCH_ID AS NVARCHAR(50)
AS

BEGIN

INSERT INTO CAFINANCIALINTARAUDIT
( CATRANSACTIONARPOSTINGID, CHARGECODE, INVOICENUMBER, BATCHNUMBER, BATCHPROCESSEDDATE )
SELECT *
FROM (
SELECT DISTINCT CATRANSACTIONARPOSTING.CATRANSACTIONARPOSTINGID, COALESCE(CAFEE.ARFEECODE, '') ARFEECODE, CAINVOICE.INVOICENUMBER, CAINTEGRATIONBATCHPROCESS.FINANCEBATCHID, GETDATE() PROCESSEDDATE
FROM CAINTEGRATIONBATCHPROCESS
INNER JOIN CATRANSACTIONARINTEGRATION ON CAINTEGRATIONBATCHPROCESS.BATCH_NUMBER = CATRANSACTIONARINTEGRATION.BATCHNUMBER
INNER JOIN CATRANSACTIONARPOSTING ON CATRANSACTIONARINTEGRATION.CATRANSACTIONARPOSTINGID = CATRANSACTIONARPOSTING.CATRANSACTIONARPOSTINGID
INNER JOIN CATRANSACTIONARTYPE ON CATRANSACTIONARPOSTING.CATRANSACTIONARTYPEID = CATRANSACTIONARTYPE.CATRANSACTIONARTYPEID AND CATRANSACTIONARTYPE.CATRANSACTIONARTYPEID = 2 
INNER JOIN CAFINANCIALINTEGRATIONSETUP ON CAFINANCIALINTEGRATIONSETUP.CAFINANCIALINTEGRATIONSETUPID = CAINTEGRATIONBATCHPROCESS.CAFINANCIALINTEGRATIONSETUPID
INNER JOIN CAINVOICEFEEARPOSTING ON CATRANSACTIONARPOSTING.CATRANSACTIONARPOSTINGID = CAINVOICEFEEARPOSTING.CATRANSACTIONARPOSTINGID
INNER JOIN CAINVOICEFEE ON CAINVOICEFEEARPOSTING.CAINVOICEFEEID = CAINVOICEFEE.CAINVOICEFEEID
INNER JOIN CACOMPUTEDFEE ON CAINVOICEFEE.CACOMPUTEDFEEID = CACOMPUTEDFEE.CACOMPUTEDFEEID
INNER JOIN CAFEETEMPLATEFEE ON CACOMPUTEDFEE.CAFEETEMPLATEFEEID = CAFEETEMPLATEFEE.CAFEETEMPLATEFEEID
INNER JOIN CAFEE ON CAFEETEMPLATEFEE.CAFEEID = CAFEE.CAFEEID
INNER JOIN CAINVOICE ON CAINVOICEFEE.CAINVOICEID = CAINVOICE.CAINVOICEID 
LEFT OUTER JOIN JURISDICTION ON JURISDICTION.JURISDICTIONID = CAFEE.JURISDICTIONID 
UNION ALL
SELECT DISTINCT CATRANSACTIONARPOSTING.CATRANSACTIONARPOSTINGID, COALESCE(CAFEE.ARFEECODE, '') ARFEECODE, CAINVOICE.INVOICENUMBER, CAINTEGRATIONBATCHPROCESS.FINANCEBATCHID, GETDATE() PROCESSEDDATE
FROM CAINTEGRATIONBATCHPROCESS
INNER JOIN CATRANSACTIONARINTEGRATION ON CAINTEGRATIONBATCHPROCESS.BATCH_NUMBER = CATRANSACTIONARINTEGRATION.BATCHNUMBER
INNER JOIN CATRANSACTIONARPOSTING ON CATRANSACTIONARINTEGRATION.CATRANSACTIONARPOSTINGID = CATRANSACTIONARPOSTING.CATRANSACTIONARPOSTINGID
INNER JOIN CATRANSACTIONARTYPE ON CATRANSACTIONARPOSTING.CATRANSACTIONARTYPEID = CATRANSACTIONARTYPE.CATRANSACTIONARTYPEID AND CATRANSACTIONARTYPE.CATRANSACTIONARTYPEID = 2 
INNER JOIN CAFINANCIALINTEGRATIONSETUP ON CAFINANCIALINTEGRATIONSETUP.CAFINANCIALINTEGRATIONSETUPID = CAINTEGRATIONBATCHPROCESS.CAFINANCIALINTEGRATIONSETUPID
INNER JOIN CAINVMISCFEEARPOSTING ON CATRANSACTIONARPOSTING.CATRANSACTIONARPOSTINGID = CAINVMISCFEEARPOSTING.CATRANSACTIONARPOSTINGID
INNER JOIN CAINVOICEMISCFEE ON CAINVMISCFEEARPOSTING.CAINVOICEMISCFEEID = CAINVOICEMISCFEE.CAINVOICEMISCFEEID
INNER JOIN CAMISCFEE ON CAINVOICEMISCFEE.CAMISCFEEID = CAMISCFEE.CAMISCFEEID
INNER JOIN CAFEE ON CAMISCFEE.CAFEEID = CAFEE.CAFEEID
INNER JOIN CAINVOICE ON CAINVOICEMISCFEE.CAINVOICEID = CAINVOICE.CAINVOICEID 
LEFT OUTER JOIN JURISDICTION ON JURISDICTION.JURISDICTIONID = CAFEE.JURISDICTIONID 
) TB
WHERE FINANCEBATCHID = @BATCH_ID

END