CREATE PROCEDURE [dbo].[USP_ILLICENSEREQUIREDFIELD_UPDATE]
(
	@REQUIREDCUSTOMFIELDID CHAR(36),
	@SORTORDER INT
)
AS

UPDATE [dbo].[ILLICENSEREQUIREDFIELD] SET
	[SORTORDER] = @SORTORDER

WHERE
	[REQUIREDCUSTOMFIELDID] = @REQUIREDCUSTOMFIELDID