CREATE PROCEDURE [dbo].[USP_IPCONDITIONCATEGORY_DELETE]
(
	@IPCONDITIONCATEGORYID CHAR(36),
	@ROWVERSION INT
)
AS
DELETE FROM [dbo].[IPCONDITIONCATEGORY]
WHERE
	[IPCONDITIONCATEGORYID] = @IPCONDITIONCATEGORYID AND 
	[ROWVERSION]= @ROWVERSION