CREATE PROCEDURE [dbo].[USP_IMNONCOMPLIANCECODEREVISION_DELETE]
(
@IMNONCOMPLIANCECODEREVISIONID CHAR(36)
)
AS
DELETE FROM [dbo].[IMNONCOMPLIANCECODEREVISION]
WHERE
	[IMNONCOMPLIANCECODEREVISIONID] = @IMNONCOMPLIANCECODEREVISIONID