CREATE PROCEDURE [dbo].[USP_IMINSPECTIONCATEGORYXREF_DELETE_BYPARENTID]
(
@PARENTID CHAR(36)
)
AS
DELETE FROM [dbo].[IMINSPECTIONCATEGORYXREF]
WHERE 
	[dbo].[IMINSPECTIONCATEGORYXREF].[IMINSPECTIONCATEGORYID] = @PARENTID