CREATE PROCEDURE [dbo].[USP_IMINSPECTIONTYPE_DELETE]
(
	@IMINSPECTIONTYPEID CHAR(36),
	@ROWVERSION INT
)
AS
SET NOCOUNT ON;
EXEC [dbo].[USP_IMINSPECTIONTYPECHKLSTXREF_DELETE_BYPARENTID] @IMINSPECTIONTYPEID
EXEC [dbo].[USP_WFACTION_IMINSPECTIONTYPE_DELETE_BYPARENTID] @IMINSPECTIONTYPEID
SET NOCOUNT OFF;
DELETE FROM [dbo].[IMINSPECTIONTYPE]
WHERE
	[IMINSPECTIONTYPEID] = @IMINSPECTIONTYPEID AND 
	[ROWVERSION]= @ROWVERSION