CREATE PROCEDURE [dbo].[USP_INTEGRATION_GET_BATCH_FOR_INVOICE_EXPORT]
@BATCH_ID NVARCHAR(50),
@IS_PREVIEW BIT
AS
BEGIN

SELECT 
	CAINTEGRATIONBATCHPROCESS.BATCH_NUMBER, FEE_TB.CACOMPUTEDFEEID,
	CAINVOICE.INVOICENUMBER, CAINVOICE.INVOICEDATE, CAINVOICE.INVOICEDUEDATE,
	CASE WHEN LTRIM(RTRIM(COALESCE(GE.GLOBALENTITYNAME, ''))) = '' THEN COALESCE(GE.FIRSTNAME + ' ', '') + COALESCE(GE.LASTNAME, '') ELSE GE.GLOBALENTITYNAME END AS CUSTOMERNAME,
	GE.GLOBALENTITYID, GE.ISCOMPANY, GE.ISCONTACT,
	COALESCE(GE.EMAIL, '') EMAIL, COALESCE(GE.PREFCOMM, 0) PREFCOMM, 
	COALESCE(GE.HOMEPHONE, '') HOMEPHONE, COALESCE(GE.BUSINESSPHONE, '') BUSINESSPHONE, COALESCE(GE.MOBILEPHONE, '') MOBILEPHONE, COALESCE(GE.OTHERPHONE, '') OTHERPHONE, COALESCE(GE.FAX, '') FAX,
	REPLACE(COALESCE(MA.ADDRESSLINE1, '') + ' ' + COALESCE(MA.PREDIRECTION, '') + ' ' + COALESCE(MA.ADDRESSLINE2, '') + ' ' + COALESCE(MA.STREETTYPE, '') + ' ' + COALESCE(MA.POSTDIRECTION, ''), '  ', ' ') AS ADDRESSLINE1,
	CASE WHEN COALESCE(MA.UNITORSUITE, '') != '' THEN 'Unit: ' + UNITORSUITE END ADDRESSLINE2,
	MA.CITY, MA.[STATE], MA.POSTALCODE, 
	CASE WHEN COALESCE(MA.COUNTRY, '') = '' THEN MACT.MAILINGADDRESSCOUNTRYTYPENAME ELSE COALESCE(MA.COUNTRY, '') END AS COUNTRY,
	FEE_TB.ARFEECODE, FEE_TB.COMPUTEDAMOUNT, FEE_TB.AMOUNTPAIDTODATE, FEE_TB.FEENAME, 
	COALESCE(MODULE_PROPERTY_INFO.PARCELNUMBER, '') PARCELNUMBER, 
	COALESCE(MODULE_PROPERTY_INFO.FORMATTEDADDRESS, '') FORMATTEDADDRESS, 
	COALESCE(MODULE_PROPERTY_INFO.CASENUMBER, '') CASENUMBER, 
	COALESCE(MODULE_PROPERTY_INFO.LEGALDESCRIPTION, '') LEGALDESCRIPTION, 
	COALESCE(MODULE_PROPERTY_INFO.SUBDIVISION, '') SUBDIVISION,
	COALESCE(MODULE_PROPERTY_INFO.TAXNUMBER, '') TAXNUMBER,
	CAINTEGRATIONBATCHPROCESS.SUCCESS, CAINTEGRATIONBATCHPROCESS.FAILED_COUNT, CAINTEGRATIONBATCHPROCESS.FINANCEBATCHID,
	COALESCE(FEE_TB.FEENOTES, '') FEENOTES,
	COALESCE(FEE_TB.FEEID, '') FEEID

FROM CAINTEGRATIONBATCHPROCESS
INNER JOIN CAFINANCIALINTEGRATIONSETUP ON CAFINANCIALINTEGRATIONSETUP.CAFINANCIALINTEGRATIONSETUPID = CAINTEGRATIONBATCHPROCESS.CAFINANCIALINTEGRATIONSETUPID
INNER JOIN 
(
	SELECT 
		CAEXTERNALINVOICEBATCHFEE.BATCHNUMBER, CAINVOICEFEE.CAINVOICEID, CAINVOICEFEE.CAINVOICEFEEID FEEID, CACOMPUTEDFEE.CACOMPUTEDFEEID, CAFEE.ARFEECODE, 
		CACOMPUTEDFEE.COMPUTEDAMOUNT, CACOMPUTEDFEE.AMOUNTPAIDTODATE, CAFEE.[NAME] FEENAME, JURISDICTION.CAFINANCIALINTEGRATIONSETUPID,
		CACOMPUTEDFEE.[NOTES] FEENOTES
	FROM CAEXTERNALINVOICEBATCHFEE
	INNER JOIN CACOMPUTEDFEE ON CAEXTERNALINVOICEBATCHFEE.CACOMPUTEDFEEID = CACOMPUTEDFEE.CACOMPUTEDFEEID AND CACOMPUTEDFEE.CASTATUSID IN ( 1, 2, 6, 7 )
	INNER JOIN CAFEETEMPLATEFEE ON CACOMPUTEDFEE.CAFEETEMPLATEFEEID = CAFEETEMPLATEFEE.CAFEETEMPLATEFEEID
	INNER JOIN CAFEE ON CAFEETEMPLATEFEE.CAFEEID = CAFEE.CAFEEID
	INNER JOIN CAINVOICEFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CAINVOICEFEE.CACOMPUTEDFEEID
	LEFT OUTER JOIN JURISDICTION ON JURISDICTION.JURISDICTIONID = CAFEE.JURISDICTIONID
	UNION ALL
	SELECT 
		CAEXTERNALINVOICEBATCHMISCFEE.BATCHNUMBER, CAINVOICEMISCFEE.CAINVOICEID, CAINVOICEMISCFEE.CAINVOICEMISCFEEID FEEID, CAMISCFEE.CAMISCFEEID CACOMPUTEDFEEID, CAFEE.ARFEECODE, 
		CAMISCFEE.AMOUNT COMPUTEDAMOUNT, CAMISCFEE.PAIDAMOUNT AMOUNTPAIDTODATE, CAFEE.[NAME] FEENAME, JURISDICTION.CAFINANCIALINTEGRATIONSETUPID,
		CAFEE.[NOTES] FEENOTES
	FROM CAEXTERNALINVOICEBATCHMISCFEE
	INNER JOIN CAMISCFEE ON CAEXTERNALINVOICEBATCHMISCFEE.CAMISCFEEID = CAMISCFEE.CAMISCFEEID AND CAMISCFEE.CASTATUSID IN ( 1, 2, 6, 7 )
	INNER JOIN CAFEE ON CAMISCFEE.CAFEEID = CAFEE.CAFEEID
	INNER JOIN CAINVOICEMISCFEE ON CAMISCFEE.CAMISCFEEID = CAINVOICEMISCFEE.CAMISCFEEID
	LEFT OUTER JOIN JURISDICTION ON JURISDICTION.JURISDICTIONID = CAFEE.JURISDICTIONID
) FEE_TB ON CAINTEGRATIONBATCHPROCESS.BATCH_NUMBER = FEE_TB.BATCHNUMBER

INNER JOIN CAINVOICE ON FEE_TB.CAINVOICEID = CAINVOICE.CAINVOICEID AND CAINVOICE.CASTATUSID NOT IN ( 4, 5, 9, 10 )
LEFT OUTER JOIN GLOBALENTITY GE ON CAINVOICE.GLOBALENTITYID = GE.GLOBALENTITYID
LEFT OUTER JOIN GLOBALENTITYMAILINGADDRESS GEMA ON GEMA.GLOBALENTITYID = GE.GLOBALENTITYID AND GEMA.MAIN = 1
LEFT OUTER JOIN MAILINGADDRESS MA ON GEMA.MAILINGADDRESSID = MA.MAILINGADDRESSID
LEFT OUTER JOIN MAILINGADDRESSCOUNTRYTYPE MACT ON MA.COUNTRYTYPE = MACT.MAILINGADDRESSCOUNTRYTYPEID

LEFT OUTER JOIN 
(
	SELECT 
		CACOMPUTEDFEEID, 
		COALESCE(PARCEL.PARCELNUMBER,'') PARCELNUMBER, 
		REPLACE
		(COALESCE(MAILINGADDRESS.ADDRESSLINE1, '') + ' ' + COALESCE(MAILINGADDRESS.PREDIRECTION, '') + ' ' + COALESCE(MAILINGADDRESS.ADDRESSLINE2, '') + ' ' + COALESCE(MAILINGADDRESS.STREETTYPE, '') + ' ' + COALESCE(MAILINGADDRESS.POSTDIRECTION, '') + ' ' +
		CASE WHEN COALESCE(MAILINGADDRESS.UNITORSUITE, '') != '' THEN 'Unit: ' + MAILINGADDRESS.UNITORSUITE ELSE '' END + ' ' +
		COALESCE(MAILINGADDRESS.CITY, '') + ' ' + CASE MAILINGADDRESS.COUNTRYTYPE WHEN 2 THEN COALESCE(MAILINGADDRESS.PROVINCE, '') ELSE COALESCE(MAILINGADDRESS.[STATE], '') END + ' ' + COALESCE(MAILINGADDRESS.POSTALCODE, ''), '  ', ' '
		) AS FORMATTEDADDRESS,
		COALESCE(CASENUMBER,'') CASENUMBER, 
		COALESCE(LEGALDESCRIPTION,'') LEGALDESCRIPTION, 
		COALESCE(SUBDIVISION, '') SUBDIVISION,
		COALESCE(PARCEL.TAXNUMBER, '') TAXNUMBER
	FROM 
	(
		SELECT 
			CACOMPUTEDFEEID, PERMITNUMBER CASENUMBER, PARCELID, MAILINGADDRESSID
		FROM PMPERMIT 
		INNER JOIN PMPERMITFEE ON PMPERMIT.PMPERMITID = PMPERMITFEE.PMPERMITID 
		LEFT OUTER JOIN PMPERMITADDRESS ADDRESSONE ON PMPERMIT.PMPERMITID = ADDRESSONE.PMPERMITID AND ADDRESSONE.MAIN = 1
		LEFT OUTER JOIN PMPERMITPARCEL PARCELONE ON PMPERMIT.PMPERMITID = PARCELONE.PMPERMITID AND PARCELONE.MAIN = 1
		UNION ALL
		SELECT 
			CACOMPUTEDFEEID, PLANNUMBER CASENUMBER, PARCELID, MAILINGADDRESSID
		FROM PLPLAN 
		INNER JOIN PLPLANFEE ON PLPLAN.PLPLANID = PLPLANFEE.PLPLANID 
		LEFT OUTER JOIN PLPLANADDRESS ADDRESSONE ON PLPLAN.PLPLANID = ADDRESSONE.PLPLANID AND ADDRESSONE.MAIN = 1
		LEFT OUTER JOIN PLPLANPARCEL PARCELONE ON PLPLAN.PLPLANID = PARCELONE.PLPLANID AND PARCELONE.MAIN = 1
		UNION ALL
		SELECT 
			CACOMPUTEDFEEID, CASENUMBER CASENUMBER, PARCELID, MAILINGADDRESSID
		FROM CMCODECASE 
		INNER JOIN CMCODECASEFEE ON CMCODECASE.CMCODECASEID = CMCODECASEFEE.CMCODECASEID 
		LEFT OUTER JOIN CMCODECASEADDRESS ADDRESSONE ON CMCODECASE.CMCODECASEID = ADDRESSONE.CMCODECASEID AND ADDRESSONE.MAIN = 1
		LEFT OUTER JOIN CMCODECASEPARCEL PARCELONE ON CMCODECASE.CMCODECASEID = PARCELONE.CMCODECASEID AND PARCELONE.[PRIMARY] = 1
		UNION ALL
		SELECT 
			CACOMPUTEDFEEID, APPNUMBER CASENUMBER, PARCELID, MAILINGADDRESSID
		FROM PLAPPLICATION 
		INNER JOIN PLAPPLICATIONFEE ON PLAPPLICATION.PLAPPLICATIONID = PLAPPLICATIONFEE.PLAPPLICATIONID 
		LEFT OUTER JOIN PLAPPLICATIONADDRESS ADDRESSONE ON PLAPPLICATION.PLAPPLICATIONID = ADDRESSONE.PLAPPLICATIONID AND ADDRESSONE.MAIN = 1
		LEFT OUTER JOIN PLAPPLICATIONPARCEL PARCELONE ON PLAPPLICATION.PLAPPLICATIONID = PARCELONE.PLAPPLICATIONID AND PARCELONE.MAIN = 1
		UNION ALL
		SELECT 
			CACOMPUTEDFEEID, LICENSENUMBER CASENUMBER, PARCELID, MAILINGADDRESSID
		FROM BLLICENSE 
		INNER JOIN BLLICENSEFEE ON BLLICENSE.BLLICENSEID = BLLICENSEFEE.BLLICENSEID 
		LEFT OUTER JOIN BLLICENSEADDRESS ADDRESSONE ON BLLICENSE.BLLICENSEID = ADDRESSONE.BLLICENSEID AND ADDRESSONE.MAIN = 1
		LEFT OUTER JOIN BLLICENSEPARCEL PARCELONE ON BLLICENSE.BLLICENSEID = PARCELONE.BLLICENSEID AND PARCELONE.MAIN = 1
		UNION ALL
		SELECT 
			CACOMPUTEDFEEID, REGISTRATIONID CASENUMBER, PARCELID, MAILINGADDRESSID
		FROM BLGLOBALENTITYEXTENSION 
		INNER JOIN BLGLOBALENTITYEXTENSIONFEE ON BLGLOBALENTITYEXTENSION.BLGLOBALENTITYEXTENSIONID = BLGLOBALENTITYEXTENSIONFEE.BLGLOBALENTITYEXTENSIONID 
		LEFT OUTER JOIN BLGLOBALENTITYEXTENSIONADDRESS ADDRESSONE ON BLGLOBALENTITYEXTENSION.BLGLOBALENTITYEXTENSIONID = ADDRESSONE.BLGLOBALENTITYEXTENSIONID AND ADDRESSONE.MAIN = 1
		LEFT OUTER JOIN BLGLOBALENTITYEXTENSIONPARCEL PARCELONE ON BLGLOBALENTITYEXTENSION.BLGLOBALENTITYEXTENSIONID = PARCELONE.BLGLOBALENTITYEXTENSIONID AND PARCELONE.MAIN = 1
		UNION ALL
		SELECT 
			CACOMPUTEDFEEID, LICENSENUMBER CASENUMBER, PARCELID, MAILINGADDRESSID
		FROM ILLICENSE 
		INNER JOIN ILLICENSEFEE ON ILLICENSE.ILLICENSEID = ILLICENSEFEE.ILLICENSEID 
		LEFT OUTER JOIN ILLICENSEADDRESS ADDRESSONE ON ILLICENSE.ILLICENSEID = ADDRESSONE.ILLICENSEID AND ADDRESSONE.MAIN = 1
		LEFT OUTER JOIN ILLICENSEPARCEL PARCELONE ON ILLICENSE.ILLICENSEID = PARCELONE.ILLICENSEID AND PARCELONE.MAIN = 1
		UNION ALL
		SELECT 
			CACOMPUTEDFEEID, INSPECTIONNUMBER CASENUMBER, PARCELID, MAILINGADDRESSID
		FROM IMINSPECTION 
		INNER JOIN IMINSPECTIONFEE ON IMINSPECTION.IMINSPECTIONID = IMINSPECTIONFEE.IMINSPECTIONID 
		LEFT OUTER JOIN IMINSPECTIONADDRESS ADDRESSONE ON IMINSPECTION.IMINSPECTIONID = ADDRESSONE.IMINSPECTIONID AND ADDRESSONE.MAIN = 1
		LEFT OUTER JOIN IMINSPECTIONPARCEL PARCELONE ON IMINSPECTION.IMINSPECTIONID = PARCELONE.IMINSPECTIONID AND PARCELONE.MAIN = 1
		UNION ALL
		SELECT 
			CACOMPUTEDFEEID, PROJECTNUMBER CASENUMBER, PARCELID, MAILINGADDRESSID
		FROM PRPROJECT 
		INNER JOIN PRPROJECTFEE ON PRPROJECT.PRPROJECTID = PRPROJECTFEE.PRPROJECTID 
		LEFT OUTER JOIN PRPROJECTADDRESS ADDRESSONE ON PRPROJECT.PRPROJECTID = ADDRESSONE.PRPROJECTID AND ADDRESSONE.MAIN = 1
		LEFT OUTER JOIN PRPROJECTPARCEL PARCELONE ON PRPROJECT.PRPROJECTID = PARCELONE.PRPROJECTID AND PARCELONE.MAIN = 1
		UNION ALL
		SELECT 
			CACOMPUTEDFEEID, ACCOUNTNUMBER CASENUMBER, PARCELID, MAILINGADDRESSID
		FROM TXREMITTANCEACCOUNT
		INNER JOIN TXREMITTANCE ON TXREMITTANCEACCOUNT.TXREMITTANCEACCOUNTID = TXREMITTANCE.TXREMITTANCEACCOUNTID
		INNER JOIN TXREMITTANCEFEE ON TXREMITTANCE.TXREMITTANCEID = TXREMITTANCEFEE.TXREMITTANCEID 
		LEFT OUTER JOIN TXREMITTANCEACCOUNTADDRESS ADDRESSONE ON TXREMITTANCEACCOUNT.TXREMITTANCEACCOUNTID = ADDRESSONE.TXREMITTANCEACCOUNTID AND ADDRESSONE.MAIN = 1
		LEFT OUTER JOIN TXREMITTANCEACCOUNTPARCEL PARCELONE ON TXREMITTANCEACCOUNT.TXREMITTANCEACCOUNTID = PARCELONE.TXREMITTANCEACCOUNTID AND PARCELONE.MAIN = 1
		UNION ALL
		SELECT 
			CACOMPUTEDFEEID, LANDLORDNUMBER CASENUMBER, PARCELID, MAILINGADDRESSID
		FROM RPLANDLORDLICENSE 
		INNER JOIN RPLANDLORDLICENSEFEE ON RPLANDLORDLICENSE.RPLANDLORDLICENSEID = RPLANDLORDLICENSEFEE.RPLANDLORDLICENSEID 
		LEFT OUTER JOIN RPLANDLORDLICENSEADDRESS ADDRESSONE ON RPLANDLORDLICENSE.RPLANDLORDLICENSEID = ADDRESSONE.RPLANDLORDLICENSEID AND ADDRESSONE.MAIN = 1
		LEFT OUTER JOIN RPLANDLORDLICENSEPARCEL PARCELONE ON RPLANDLORDLICENSE.RPLANDLORDLICENSEID = PARCELONE.RPLANDLORDLICENSEID AND PARCELONE.MAIN = 1
		UNION ALL
		SELECT 
			CACOMPUTEDFEEID, PROPERTYNUMBER CASENUMBER, PARCELID, MAILINGADDRESSID
		FROM RPPROPERTY 
		INNER JOIN RPPROPERTYFEE ON RPPROPERTY.RPPROPERTYID = RPPROPERTYFEE.RPPROPERTYID 
		LEFT OUTER JOIN RPPROPERTYADDRESS ADDRESSONE ON RPPROPERTY.RPPROPERTYID = ADDRESSONE.RPPROPERTYID AND ADDRESSONE.MAIN = 1
		LEFT OUTER JOIN RPPROPERTYPARCEL PARCELONE ON RPPROPERTY.RPPROPERTYID = PARCELONE.RPPROPERTYID AND PARCELONE.MAIN = 1
	) MODULE_INFO 
	LEFT OUTER JOIN MAILINGADDRESS ON MODULE_INFO.MAILINGADDRESSID = MAILINGADDRESS.MAILINGADDRESSID
	LEFT OUTER JOIN PARCEL ON MODULE_INFO.PARCELID = PARCEL.PARCELID
) MODULE_PROPERTY_INFO ON FEE_TB.CACOMPUTEDFEEID = MODULE_PROPERTY_INFO.CACOMPUTEDFEEID


WHERE ( COALESCE(@BATCH_ID, '') != '' AND FINANCEBATCHID = @BATCH_ID )
AND CAFINANCIALINTEGRATIONSETUP.CAFINANCIALINTEGRATIONSETUPID = 
	CASE 
		WHEN CAFINANCIALINTEGRATIONSETUP.ISDEFAULT = 1 THEN COALESCE(FEE_TB.CAFINANCIALINTEGRATIONSETUPID ,CAFINANCIALINTEGRATIONSETUP.CAFINANCIALINTEGRATIONSETUPID)
		WHEN CAFINANCIALINTEGRATIONSETUP.ISDEFAULT = 0 THEN FEE_TB.CAFINANCIALINTEGRATIONSETUPID
		ELSE NULL
	END
AND ( ( @IS_PREVIEW = 0 AND SUCCESS = 0 ) OR ( @IS_PREVIEW = 1 ) )

ORDER BY FINANCEBATCHID, INVOICENUMBER


END