CREATE PROCEDURE [dbo].[USP_ILLICENSECLASSIFICATION_DELETE]
(
	@ILLICENSECLASSIFICATIONID CHAR(36),
	@ROWVERSION INT
)
AS
DELETE FROM [dbo].[ILLICENSECLASSIFICATION]
WHERE
	[ILLICENSECLASSIFICATIONID] = @ILLICENSECLASSIFICATIONID AND 
	[ROWVERSION]= @ROWVERSION