CREATE PROCEDURE [dbo].[USP_INSPECTIONEVENTQUEUE_UPDATE]
(
@INSPECTIONEVENTQUEUEID AS BIGINT,
@EVENTSTATUSID INT
)
AS  
BEGIN  
	SET NOCOUNT ON;
	UPDATE [dbo].[INSPECTIONEVENTQUEUE]
	SET 
		[PROCESSEDDATE] = GETDATE(),
		[EVENTSTATUSID] = @EVENTSTATUSID
	WHERE [dbo].[INSPECTIONEVENTQUEUE].[INSPECTIONEVENTQUEUEID] = @INSPECTIONEVENTQUEUEID

END