CREATE PROCEDURE [dbo].[USP_ILLICENSETYPECLASSTYPE_INSERT]
(
	@ILLICENSETYPECLASSTYPEID CHAR(36),
	@ILLICENSETYPEID CHAR(36),
	@ILLICENSECLASSTYPEID CHAR(36)
)
AS
INSERT INTO [dbo].[ILLICENSETYPECLASSTYPE](
	[ILLICENSETYPECLASSTYPEID],
	[ILLICENSETYPEID],
	[ILLICENSECLASSTYPEID]
)
VALUES
(
	@ILLICENSETYPECLASSTYPEID,
	@ILLICENSETYPEID,
	@ILLICENSECLASSTYPEID
)