CREATE PROCEDURE [dbo].[USP_INTEGRATION_CHECK_IF_BATCH_EXIST]
	@ExternalBatchNbr AS NVARCHAR(50)
AS

BEGIN

SELECT COUNT(*)
FROM CATRANSACTION
JOIN CATRANSACTIONPAYMENT ON CATRANSACTION.CATRANSACTIONID = CATRANSACTIONPAYMENT.CATRANSACTIONID
WHERE CATRANSACTION.EXTERNALBATCHNBR = @ExternalBatchNbr

END