CREATE PROCEDURE [dbo].[USP_IPCONDITIONCATEGORY_INSERT]
(
	@IPCONDITIONCATEGORYID CHAR(36),
	@NAME NVARCHAR(100),
	@DESCRIPTION NVARCHAR(MAX),
	@PREFIX NVARCHAR(10),
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
INSERT INTO [dbo].[IPCONDITIONCATEGORY](
	[IPCONDITIONCATEGORYID],
	[NAME],
	[DESCRIPTION],
	[PREFIX],
	[LASTCHANGEDBY],
	[LASTCHANGEDON],
	[ROWVERSION]
)
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
VALUES
(
	@IPCONDITIONCATEGORYID,
	@NAME,
	@DESCRIPTION,
	@PREFIX,
	@LASTCHANGEDBY,
	@LASTCHANGEDON,
	@ROWVERSION
)
SELECT * FROM @OUTPUTTABLE