CREATE PROCEDURE [dbo].[USP_IMINSPECTIONCATEGORYXREF_UPDATE]
(
	@IMINSPECTIONCATEGORYXREFID CHAR(36),
	@IMINSPECTIONCATEGORYID CHAR(36),
	@IMINSPECTIONTYPEGROUPID CHAR(36)
)
AS

UPDATE [dbo].[IMINSPECTIONCATEGORYXREF] SET
	[IMINSPECTIONCATEGORYID] = @IMINSPECTIONCATEGORYID,
	[IMINSPECTIONTYPEGROUPID] = @IMINSPECTIONTYPEGROUPID

WHERE
	[dbo].[IMINSPECTIONCATEGORYXREF].[IMINSPECTIONCATEGORYXREFID] = @IMINSPECTIONCATEGORYXREFID