CREATE PROCEDURE [dbo].[USP_INTEGRATION_UPDATE_CAINTEGRATIONBATCHPROCESS_AFTER_PROCESS]
	@SUCCESS AS BIT,
	@RESULT_LOG AS VARBINARY(MAX),
	@BLOCKAUTORESEND AS BIT,
	@PROCESSED_DATE AS DATETIME,
	@BATCH_ID AS NVARCHAR(50)
AS

BEGIN

UPDATE CAINTEGRATIONBATCHPROCESS 
SET 
FAILED_COUNT = CASE WHEN @SUCCESS = 0 THEN FAILED_COUNT + 1 ELSE FAILED_COUNT END, 
SUCCESS = @SUCCESS, 
RESULT_LOG = @RESULT_LOG, 
BLOCKAUTORESEND = @BLOCKAUTORESEND, 
PROCESSED_DATE = @PROCESSED_DATE 
WHERE FINANCEBATCHID = @BATCH_ID

END