CREATE PROCEDURE [dbo].[USP_IMNONCOMPLIANCECATEGORY_DELETE]
(
	@IMNONCOMPLIANCECATEGORYID CHAR(36),
	@ROWVERSION INT
)
AS
DELETE FROM [dbo].[IMNONCOMPLIANCECATEGORY]
WHERE
	[IMNONCOMPLIANCECATEGORYID] = @IMNONCOMPLIANCECATEGORYID AND 
	[ROWVERSION]= @ROWVERSION