CREATE PROCEDURE [dbo].[USP_INTEGRATION_GET_BATCH_FOR_AR]
	@BATCH_ID AS NVARCHAR(50),
	@IS_PREVIEW AS BIT
AS

BEGIN

SELECT *
FROM (

SELECT DISTINCT CAFEE.ARFEECODE, 
	CATRANSACTIONARPOSTING.POSTINGDATE, CATRANSACTIONARPOSTING.POSTINGAMOUNT, CATRANSACTIONARTYPE.CATRANSACTIONARTYPENAME,
	CATRANSACTIONARINTEGRATION.BATCHNUMBER, CAINVOICE.INVOICENUMBER,
	CAFEE.NAME FEENAME, CAFEE.ISARFEE, CATRANSACTIONARINTEGRATION.CATRANSACTIONARINTEGRATIONID,
	CAINTEGRATIONBATCHPROCESS.SUCCESS, CAINTEGRATIONBATCHPROCESS.FAILED_COUNT, CAINTEGRATIONBATCHPROCESS.FINANCEBATCHID, 
	CAFINANCIALINTEGRATIONSETUP.CAFINANCIALINTEGRATIONSETUPID BATCHFINANCESETUPID, JURISDICTION.CAFINANCIALINTEGRATIONSETUPID FEEFINANCESETUPID, CAFINANCIALINTEGRATIONSETUP.ISDEFAULT
FROM CAINTEGRATIONBATCHPROCESS
INNER JOIN CATRANSACTIONARINTEGRATION ON CAINTEGRATIONBATCHPROCESS.BATCH_NUMBER = CATRANSACTIONARINTEGRATION.BATCHNUMBER
INNER JOIN CATRANSACTIONARPOSTING ON CATRANSACTIONARINTEGRATION.CATRANSACTIONARPOSTINGID = CATRANSACTIONARPOSTING.CATRANSACTIONARPOSTINGID
INNER JOIN CATRANSACTIONARTYPE ON CATRANSACTIONARPOSTING.CATRANSACTIONARTYPEID = CATRANSACTIONARTYPE.CATRANSACTIONARTYPEID AND CATRANSACTIONARTYPE.CATRANSACTIONARTYPEID = 2 
INNER JOIN CAFINANCIALINTEGRATIONSETUP ON CAFINANCIALINTEGRATIONSETUP.CAFINANCIALINTEGRATIONSETUPID = CAINTEGRATIONBATCHPROCESS.CAFINANCIALINTEGRATIONSETUPID
INNER JOIN CAINVOICEFEEARPOSTING ON CATRANSACTIONARPOSTING.CATRANSACTIONARPOSTINGID = CAINVOICEFEEARPOSTING.CATRANSACTIONARPOSTINGID
INNER JOIN CAINVOICEFEE ON CAINVOICEFEEARPOSTING.CAINVOICEFEEID = CAINVOICEFEE.CAINVOICEFEEID
INNER JOIN CACOMPUTEDFEE ON CAINVOICEFEE.CACOMPUTEDFEEID = CACOMPUTEDFEE.CACOMPUTEDFEEID
INNER JOIN CAFEETEMPLATEFEE ON CACOMPUTEDFEE.CAFEETEMPLATEFEEID = CAFEETEMPLATEFEE.CAFEETEMPLATEFEEID
INNER JOIN CAFEE ON CAFEETEMPLATEFEE.CAFEEID = CAFEE.CAFEEID
INNER JOIN CAINVOICE ON CAINVOICEFEE.CAINVOICEID = CAINVOICE.CAINVOICEID 
LEFT OUTER JOIN JURISDICTION ON JURISDICTION.JURISDICTIONID = CAFEE.JURISDICTIONID 
UNION ALL
SELECT DISTINCT CAFEE.ARFEECODE, 
	CATRANSACTIONARPOSTING.POSTINGDATE, CATRANSACTIONARPOSTING.POSTINGAMOUNT, CATRANSACTIONARTYPE.CATRANSACTIONARTYPENAME,
	CATRANSACTIONARINTEGRATION.BATCHNUMBER, CAINVOICE.INVOICENUMBER,
	CAFEE.NAME FEENAME, CAFEE.ISARFEE, CATRANSACTIONARINTEGRATION.CATRANSACTIONARINTEGRATIONID,
	CAINTEGRATIONBATCHPROCESS.SUCCESS, CAINTEGRATIONBATCHPROCESS.FAILED_COUNT, CAINTEGRATIONBATCHPROCESS.FINANCEBATCHID, 
	CAFINANCIALINTEGRATIONSETUP.CAFINANCIALINTEGRATIONSETUPID BATCHFINANCESETUPID, JURISDICTION.CAFINANCIALINTEGRATIONSETUPID FEEFINANCESETUPID, CAFINANCIALINTEGRATIONSETUP.ISDEFAULT
FROM CAINTEGRATIONBATCHPROCESS
INNER JOIN CATRANSACTIONARINTEGRATION ON CAINTEGRATIONBATCHPROCESS.BATCH_NUMBER = CATRANSACTIONARINTEGRATION.BATCHNUMBER
INNER JOIN CATRANSACTIONARPOSTING ON CATRANSACTIONARINTEGRATION.CATRANSACTIONARPOSTINGID = CATRANSACTIONARPOSTING.CATRANSACTIONARPOSTINGID
INNER JOIN CATRANSACTIONARTYPE ON CATRANSACTIONARPOSTING.CATRANSACTIONARTYPEID = CATRANSACTIONARTYPE.CATRANSACTIONARTYPEID AND CATRANSACTIONARTYPE.CATRANSACTIONARTYPEID = 2 
INNER JOIN CAFINANCIALINTEGRATIONSETUP ON CAFINANCIALINTEGRATIONSETUP.CAFINANCIALINTEGRATIONSETUPID = CAINTEGRATIONBATCHPROCESS.CAFINANCIALINTEGRATIONSETUPID
INNER JOIN CAINVMISCFEEARPOSTING ON CATRANSACTIONARPOSTING.CATRANSACTIONARPOSTINGID = CAINVMISCFEEARPOSTING.CATRANSACTIONARPOSTINGID
INNER JOIN CAINVOICEMISCFEE ON CAINVMISCFEEARPOSTING.CAINVOICEMISCFEEID = CAINVOICEMISCFEE.CAINVOICEMISCFEEID
INNER JOIN CAMISCFEE ON CAINVOICEMISCFEE.CAMISCFEEID = CAMISCFEE.CAMISCFEEID
INNER JOIN CAFEE ON CAMISCFEE.CAFEEID = CAFEE.CAFEEID
INNER JOIN CAINVOICE ON CAINVOICEMISCFEE.CAINVOICEID = CAINVOICE.CAINVOICEID 
LEFT OUTER JOIN JURISDICTION ON JURISDICTION.JURISDICTIONID = CAFEE.JURISDICTIONID

) TB 
WHERE (@BATCH_ID = '')
   OR ((@BATCH_ID != '' AND ((@IS_PREVIEW = 1 AND FINANCEBATCHID = @BATCH_ID) 
                          OR (@IS_PREVIEW = 0 AND FINANCEBATCHID = @BATCH_ID AND SUCCESS = 0)))
       AND
       (TB.BATCHFINANCESETUPID = (CASE WHEN TB.ISDEFAULT = 1 THEN COALESCE(TB.FEEFINANCESETUPID, TB.BATCHFINANCESETUPID) 
	                                   WHEN TB.ISDEFAULT = 0 THEN TB.FEEFINANCESETUPID
								       ELSE NULL END)))

ORDER BY FINANCEBATCHID, BATCHNUMBER, INVOICENUMBER

END