CREATE PROCEDURE [dbo].[USP_IPCAPITALPROJECT_DELETE]
(
	@IPCAPITALPROJECTID CHAR(36),
	@ROWVERSION INT
)
AS
DELETE FROM [dbo].[IPCAPITALPROJECT]
WHERE
	[IPCAPITALPROJECTID] = @IPCAPITALPROJECTID AND 
	[ROWVERSION]= @ROWVERSION