CREATE PROCEDURE [dbo].[USP_IPCONDITIONCATEGORY_UPDATE]
(
	@IPCONDITIONCATEGORYID CHAR(36),
	@NAME NVARCHAR(100),
	@DESCRIPTION NVARCHAR(MAX),
	@PREFIX NVARCHAR(10),
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
UPDATE [dbo].[IPCONDITIONCATEGORY] SET
	[NAME] = @NAME,
	[DESCRIPTION] = @DESCRIPTION,
	[PREFIX] = @PREFIX,
	[LASTCHANGEDBY] = @LASTCHANGEDBY,
	[LASTCHANGEDON] = @LASTCHANGEDON,
	[ROWVERSION] = @ROWVERSION + 1
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE
	[IPCONDITIONCATEGORYID] = @IPCONDITIONCATEGORYID AND 
	[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE