CREATE PROCEDURE [dbo].[USP_IMCHECKLIST_INSERT]
(
	@IMCHECKLISTID CHAR(36),
	@IMCHECKLISTCATEGORYID CHAR(36),
	@NAME NVARCHAR(50),
	@DESCRIPTION NVARCHAR(MAX),
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
INSERT INTO [dbo].[IMCHECKLIST](
	[IMCHECKLISTID],
	[IMCHECKLISTCATEGORYID],
	[NAME],
	[DESCRIPTION],
	[LASTCHANGEDBY],
	[LASTCHANGEDON],
	[ROWVERSION]
)
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
VALUES
(
	@IMCHECKLISTID,
	@IMCHECKLISTCATEGORYID,
	@NAME,
	@DESCRIPTION,
	@LASTCHANGEDBY,
	@LASTCHANGEDON,
	@ROWVERSION
)
SELECT * FROM @OUTPUTTABLE