CREATE PROCEDURE [dbo].[USP_IPUNITTYPE_INSERT]
(
	@IPUNITTYPEID CHAR(36),
	@NAME NVARCHAR(100),
	@DESCRIPTION NVARCHAR(MAX),
	@ACTIVE BIT,
	@IGNOREONIMPACTEDRECORD BIT,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
INSERT INTO [dbo].[IPUNITTYPE](
	[IPUNITTYPEID],
	[NAME],
	[DESCRIPTION],
	[ACTIVE],
	[IGNOREONIMPACTEDRECORD],
	[LASTCHANGEDBY],
	[LASTCHANGEDON],
	[ROWVERSION]
)
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
VALUES
(
	@IPUNITTYPEID,
	@NAME,
	@DESCRIPTION,
	@ACTIVE,
	@IGNOREONIMPACTEDRECORD,
	@LASTCHANGEDBY,
	@LASTCHANGEDON,
	@ROWVERSION
)
SELECT * FROM @OUTPUTTABLE