CREATE PROCEDURE [dbo].[USP_ILMAPPEDVALUEGROUP_DELETE]
(
	@MAPPEDVALUEGROUPID CHAR(36),
	@ROWVERSION INT
)
AS
DELETE FROM [dbo].[ILMAPPEDVALUEGROUP]
WHERE
	[MAPPEDVALUEGROUPID] = @MAPPEDVALUEGROUPID AND 
	[ROWVERSION]= @ROWVERSION