CREATE PROCEDURE [dbo].[USP_ILMAPPEDVALUEGROUP_UPDATE]
(
	@MAPPEDVALUEGROUPID CHAR(36),
	@MAPPEDVALUE VARCHAR(50),
	@ILLICENSEGROUPID CHAR(36),
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
UPDATE [dbo].[ILMAPPEDVALUEGROUP] SET
	[MAPPEDVALUE] = @MAPPEDVALUE,
	[ILLICENSEGROUPID] = @ILLICENSEGROUPID,
	[LASTCHANGEDBY] = @LASTCHANGEDBY,
	[LASTCHANGEDON] = @LASTCHANGEDON,
	[ROWVERSION] = @ROWVERSION + 1
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE
	[MAPPEDVALUEGROUPID] = @MAPPEDVALUEGROUPID AND 
	[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE