CREATE PROCEDURE [dbo].[USP_IMINSPECTIONCASETYPE_DELETE]
(
	@IMINSPECTIONCASETYPEID CHAR(36),
	@ROWVERSION INT
)
AS
DELETE FROM [dbo].[IMINSPECTIONCASETYPE]
WHERE
	[IMINSPECTIONCASETYPEID] = @IMINSPECTIONCASETYPEID AND 
	[ROWVERSION]= @ROWVERSION