CREATE PROCEDURE [dbo].[USP_IPCONDITIONSTATUS_DELETE]
(
	@IPCONDITIONSTATUSID CHAR(36),
	@ROWVERSION INT
)
AS
DELETE FROM [dbo].[IPCONDITIONSTATUS]
WHERE
	[IPCONDITIONSTATUSID] = @IPCONDITIONSTATUSID AND 
	[ROWVERSION]= @ROWVERSION