CREATE PROCEDURE [dbo].[USP_ILLICENSETYPELICENSECLASS_UPDATE]
(
	@ILLICENSETYPELICENSECLASSID CHAR(36),
	@ILLICENSECLASSIFICATIONID CHAR(36),
	@ILLICENSETYPEID CHAR(36),
	@LICENSECYCLEID CHAR(36),
	@CUSTOMFIELDLAYOUTID CHAR(36),
	@WFTEMPLATEID CHAR(36),
	@CAFEETEMPLATEID CHAR(36),
	@ILLICENSECAPAPPLICATIONTYPEID INT,
	@INTERNETFLAG BIT,
	@ONLINECUSTOMFIELDLAYOUTID CHAR(36),
	@WFTEMPLATERENEWALID CHAR(36),
	@RENEWALDAYSPRIORTOEXPIRE INT,
	@CAPADDRESSREQUIRED BIT,
	@CANRENEWONLINE BIT,
	@CAPRENEWALAPPLICATIONTYPEID INT
)
AS

UPDATE [dbo].[ILLICENSETYPELICENSECLASS] SET
	[ILLICENSECLASSIFICATIONID] = @ILLICENSECLASSIFICATIONID,
	[ILLICENSETYPEID] = @ILLICENSETYPEID,
	[LICENSECYCLEID] = @LICENSECYCLEID,
	[CUSTOMFIELDLAYOUTID] = @CUSTOMFIELDLAYOUTID,
	[WFTEMPLATEID] = @WFTEMPLATEID,
	[CAFEETEMPLATEID] = @CAFEETEMPLATEID,
	[ILLICENSECAPAPPLICATIONTYPEID] = @ILLICENSECAPAPPLICATIONTYPEID,
	[INTERNETFLAG] = @INTERNETFLAG,
	[ONLINECUSTOMFIELDLAYOUTID] = @ONLINECUSTOMFIELDLAYOUTID,
	[WFTEMPLATERENEWALID] = @WFTEMPLATERENEWALID,
	[RENEWALDAYSPRIORTOEXPIRE] = @RENEWALDAYSPRIORTOEXPIRE,
	[CAPADDRESSREQUIRED] = @CAPADDRESSREQUIRED,
	[CANRENEWONLINE] = @CANRENEWONLINE,
	[CAPRENEWALAPPLICATIONTYPEID] = @CAPRENEWALAPPLICATIONTYPEID

WHERE
	[ILLICENSETYPELICENSECLASSID] = @ILLICENSETYPELICENSECLASSID