CREATE PROCEDURE [dbo].[USP_INTEGRATION_INSERT_CAEXTERNALINVOICEBATCHFEE]
	@BatchNumber NVARCHAR(50),
    @UniqueIds RecordIDs READONLY
AS
BEGIN
	INSERT INTO CAEXTERNALINVOICEBATCHFEE (CAEXTERNALINVOICEBATCHFEEID, CACOMPUTEDFEEID, BATCHNUMBER) 
	SELECT NEWID(), CACOMPUTEDFEEID, @BatchNumber
	FROM CACOMPUTEDFEE CF
	JOIN @UniqueIds [FEEIDs] ON CF.CACOMPUTEDFEEID = [FEEIDs].[RECORDID]
	WHERE NOT EXISTS ( SELECT 'X' FROM CAEXTERNALINVOICEBATCHFEE 
					   WHERE CAEXTERNALINVOICEBATCHFEE.CACOMPUTEDFEEID = CF.CACOMPUTEDFEEID );

	INSERT INTO CAEXTERNALINVOICEBATCHMISCFEE (CAEXTERNALINVOICEBATCHMISCFEEID, CAMISCFEEID, BATCHNUMBER)
	SELECT NEWID(), CAMISCFEEID, @BatchNumber
	FROM CAMISCFEE MF
	JOIN @UniqueIds [FEEIDs] ON MF.CAMISCFEEID = [FEEIDs].[RECORDID]
	AND NOT EXISTS ( SELECT 'X' FROM CAEXTERNALINVOICEBATCHMISCFEE 
					 WHERE CAEXTERNALINVOICEBATCHMISCFEE.CAMISCFEEID = MF.CAMISCFEEID );
END