CREATE PROCEDURE [dbo].[USP_INTEGRATION_GET_CAINTEGRATIONBATCHPROCESSID]
	@BATCH_NUMBER AS NVARCHAR(50)
AS

BEGIN

SELECT CAINTEGRATIONBATCHPROCESSID FROM CAINTEGRATIONBATCHPROCESS WHERE BATCH_NUMBER = @BATCH_NUMBER

END