CREATE PROCEDURE [dbo].[USP_ILLICENSEGROUP_UPDATE]
(
	@ILLICENSEGROUPID CHAR(36),
	@NAME NVARCHAR(50),
	@DESCRIPTION NVARCHAR(MAX),
	@MAXCOMMERCIALVALUE MONEY,
	@MAXRESIDENTIALVALUE MONEY,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
UPDATE [dbo].[ILLICENSEGROUP] SET
	[NAME] = @NAME,
	[DESCRIPTION] = @DESCRIPTION,
	[MAXCOMMERCIALVALUE] = @MAXCOMMERCIALVALUE,
	[MAXRESIDENTIALVALUE] = @MAXRESIDENTIALVALUE,
	[LASTCHANGEDBY] = @LASTCHANGEDBY,
	[LASTCHANGEDON] = @LASTCHANGEDON,
	[ROWVERSION] = @ROWVERSION + 1
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE
	[ILLICENSEGROUPID] = @ILLICENSEGROUPID AND 
	[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE