CREATE PROCEDURE [dbo].[USP_IMINSPECTORTYPE_DELETE]
(
	@IMINSPECTORTYPEID CHAR(36),
	@ROWVERSION INT
)
AS
SET NOCOUNT ON;

EXEC [dbo].[USP_IMINSPECTORTYPEINSPECTIONTYPE_DELETE_BYPARENTID] @IMINSPECTORTYPEID
	
SET NOCOUNT OFF;

DELETE FROM [dbo].[IMINSPECTORTYPE]
WHERE
	[dbo].[IMINSPECTORTYPE].[IMINSPECTORTYPEID] = @IMINSPECTORTYPEID AND 
	[dbo].[IMINSPECTORTYPE].[ROWVERSION]= @ROWVERSION