CREATE PROCEDURE [dbo].[USP_ILLICENSETYPELICENSECLASS_DELETE]
(
	@ILLICENSETYPELICENSECLASSID CHAR(36)
)
AS
BEGIN

DECLARE @ILLICENSECLASSIFICATIONID CHAR(36), @ILLICENSETYPEID CHAR(36)

SELECT @ILLICENSECLASSIFICATIONID = [dbo].[ILLICENSETYPELICENSECLASS].[ILLICENSECLASSIFICATIONID], 	@ILLICENSETYPEID = [dbo].[ILLICENSETYPELICENSECLASS].[ILLICENSETYPEID] 
	FROM [dbo].[ILLICENSETYPELICENSECLASS] WHERE ILLICENSETYPELICENSECLASSID  = @ILLICENSETYPELICENSECLASSID

-- Delete Required Fields for (ProfessionalLicenseType, ProfessionalLicenseTypeClassification)
EXEC [dbo].[USP_ILLICENSEREQUIREDFIELD_DELETE_BYPARENTID] @ILLICENSETYPEID, @ILLICENSECLASSIFICATIONID

-- Delete Online File types for (ProfessionalLicenseType, ProfessionalLicenseTypeClassification)
EXEC [USP_ATTACHMENTREQFILEREF_DELETE_BYPARENTID] @ILLICENSETYPEID, @ILLICENSECLASSIFICATIONID

DELETE FROM [dbo].[ILLICENSETYPELICENSECLASS]
WHERE
	[ILLICENSETYPELICENSECLASSID] = @ILLICENSETYPELICENSECLASSID   
END