CREATE PROCEDURE [dbo].[USP_IMNONCOMPLIANCECODEREVISION_UPDATE]
(
	@IMNONCOMPLIANCECODEREVISIONID CHAR(36),
	@IMNONCOMPLIANCECODEID CHAR(36),
	@CODETEXT NVARCHAR(2000),
	@DEFAULTCOMMENTS NVARCHAR(2000),
	@REVISIONDATE DATETIME,
	@CURRENTREVISION BIT,
	@STARTDATE DATETIME,
	@ENDDATE DATETIME,
	@REVISIONNUMBER INT
)
AS

UPDATE [dbo].[IMNONCOMPLIANCECODEREVISION] SET
	[IMNONCOMPLIANCECODEID] = @IMNONCOMPLIANCECODEID,
	[CODETEXT] = @CODETEXT,
	[DEFAULTCOMMENTS] = @DEFAULTCOMMENTS,
	[REVISIONDATE] = @REVISIONDATE,
	[CURRENTREVISION] = @CURRENTREVISION,
	[STARTDATE] = @STARTDATE,
	[ENDDATE] = @ENDDATE,
	[REVISIONNUMBER] = @REVISIONNUMBER

WHERE
	[IMNONCOMPLIANCECODEREVISIONID] = @IMNONCOMPLIANCECODEREVISIONID