CREATE PROCEDURE QUICKSEARCHMOBILECODEUSERLIST
@SearchText varchar(500)
AS
BEGIN
SELECT SUSERGUID,FNAME,LNAME,EMAIL,PHONE,BACTIVE FROM USERS WHERE ( FNAME like @SearchText or LNAME like @SearchText) AND BACTIVE =1
END
