CREATE PROCEDURE [dbo].[USP_QUERYACTIONFTP_UPDATE]
(
	@QUERYACTIONFTPID CHAR(36),
	@QUERYACTIONID CHAR(36),
	@FTPSETUPID CHAR(36),
	@SUBPATH NVARCHAR(255),
	@ATTACHMENTGROUPID CHAR(36),
	@FTPFILENAMEOPTIONID INT
)
AS
UPDATE [dbo].[QUERYACTIONFTP] SET
	[QUERYACTIONID] = @QUERYACTIONID,
	[FTPSETUPID] = @FTPSETUPID,
	[SUBPATH] = @SUBPATH,
	[ATTACHMENTGROUPID] = @ATTACHMENTGROUPID,
	[FTPFILENAMEOPTIONID] = @FTPFILENAMEOPTIONID
WHERE
	[QUERYACTIONFTPID] = @QUERYACTIONFTPID AND 
	[QUERYACTIONID]= @QUERYACTIONID