CREATE PROCEDURE [dbo].[USP_QUERYACTIONSETVALUE_INSERT]
(
	@QUERYACTIONSETVALUEID CHAR(36),
	@QUERYACTIONID CHAR(36),
	@SETVALUEFIELD NVARCHAR(MAX),
	@SETVALUEFIELDFRIENDLYNAME NVARCHAR(50),
	@SETVALUEFIELDVALUE NVARCHAR(MAX),
	@SETVALUEFIELDADJUSTMENTVALUE NVARCHAR(MAX),
	@SETVALUEWEEKDAYSONLY BIT,
	@SETVALUEUSEPREVIOUSWEEKDAY BIT
)
AS
DECLARE @OUTPUTTABLE as TABLE([QUERYACTIONSETVALUEID]  char(36))
INSERT INTO [dbo].[QUERYACTIONSETVALUE](
	[QUERYACTIONSETVALUEID],
	[QUERYACTIONID],
	[SETVALUEFIELD],
	[SETVALUEFIELDFRIENDLYNAME],
	[SETVALUEFIELDVALUE],
	[SETVALUEFIELDADJUSTMENTVALUE],
	[SETVALUEWEEKDAYSONLY],
	[SETVALUEUSEPREVIOUSWEEKDAY]
)
OUTPUT inserted.[QUERYACTIONSETVALUEID] INTO @OUTPUTTABLE
VALUES
(
	@QUERYACTIONSETVALUEID,
	@QUERYACTIONID,
	@SETVALUEFIELD,
	@SETVALUEFIELDFRIENDLYNAME,
	@SETVALUEFIELDVALUE,
	@SETVALUEFIELDADJUSTMENTVALUE,
	@SETVALUEWEEKDAYSONLY,
	@SETVALUEUSEPREVIOUSWEEKDAY
)
SELECT * FROM @OUTPUTTABLE