CREATE PROCEDURE [dbo].[USP_QUERYACTIONFTP_INSERT]
(
	@QUERYACTIONFTPID CHAR(36),
	@QUERYACTIONID CHAR(36),
	@FTPSETUPID CHAR(36),
	@SUBPATH NVARCHAR(255),
	@ATTACHMENTGROUPID CHAR(36),
	@FTPFILENAMEOPTIONID INT
)
AS
INSERT INTO [dbo].[QUERYACTIONFTP](
	[QUERYACTIONFTPID],
	[QUERYACTIONID],
	[FTPSETUPID],
	[SUBPATH],
	[ATTACHMENTGROUPID],
	[FTPFILENAMEOPTIONID]
)

VALUES
(
	@QUERYACTIONFTPID,
	@QUERYACTIONID,
	@FTPSETUPID,
	@SUBPATH,
	@ATTACHMENTGROUPID,
	@FTPFILENAMEOPTIONID
)