CREATE PROCEDURE [dbo].[USP_QUERYACTIONTASKUSER_INSERT]
(
	@QUERYACTIONTASKUSERID CHAR(36),
	@QUERYACTIONTASKID CHAR(36),
	@USERID CHAR(36)
)
AS
DECLARE @OUTPUTTABLE as TABLE([QUERYACTIONTASKUSERID]  char(36))
INSERT INTO [dbo].[QUERYACTIONTASKUSER](
	[QUERYACTIONTASKUSERID],
	[QUERYACTIONTASKID],
	[USERID]
)
OUTPUT inserted.[QUERYACTIONTASKUSERID] INTO @OUTPUTTABLE
VALUES
(
	@QUERYACTIONTASKUSERID,
	@QUERYACTIONTASKID,
	@USERID
)
SELECT * FROM @OUTPUTTABLE