CREATE PROCEDURE [dbo].[USP_QUERYACTIONTASK_DELETE]
(
@QUERYACTIONTASKID CHAR(36)
)
AS

EXEC [dbo].[USP_QUERYACTIONTASKUSER_DELETE_BYPARENTID] NULL, NULL, @QUERYACTIONTASKID

DELETE FROM [dbo].[QUERYACTIONTASK]
WHERE
	[QUERYACTIONTASKID] = @QUERYACTIONTASKID