

CREATE PROCEDURE [dbo].[rpt_CA_SR_Daily_Transaction_Listing]
@STARTDATE AS DATETIME,
@ENDDATE AS DATETIME,
@VOIDS AS NVARCHAR(3)
AS
BEGIN
SET @STARTDATE = DATEADD(dd, DATEDIFF(dd, 0, @STARTDATE), 0)
SET @ENDDATE = DATEADD(S,-1,DATEADD(D,1,@ENDDATE))
SELECT	CACOMPUTEDFEE.CACOMPUTEDFEEID, CACOMPUTEDFEE.FEENAME, CACOMPUTEDFEE.COMPUTEDAMOUNT
		, CATRANSACTION.TRANSACTIONDATE, CATRANSACTION.RECEIPTNUMBER
		, COALESCE(NULLIF(LTRIM(CATRANSACTION.EXTERNALBATCHNBR), ''), 'NONE SPECIFIED') AS EXTERNALBATCHNBR
		, (CATRANSACTIONFEE.PAIDAMOUNT - 2*CATRANSACTIONFEE.REFUNDAMOUNT) AS PAIDAMOUNT
		, COALESCE(USERS.SUSERGUID, 'NONE') SUSERGUID
		, COALESCE(USERS.FNAME, 'NO') FNAME, COALESCE(USERS.LNAME,'USER') LNAME
		, CAINVOICE.INVOICENUMBER
		, CAINVOICEFEE.CAINVOICEFEEID
		, CAPAYMENTMETHOD.NAME AS PaymentMethod
		, CATRANSACTIONTYPE.NAME AS TransactionType
		, CATRANSACTIONSTATUS.NAME AS TransactionStatus
		--,(SELECT R.[IMAGE] FROM RPTIMAGELIB R WHERE R.IMAGENAME = 'Municipality_Logo') LOGO
	    ,(SELECT CASE WHEN R.[IMAGE] IS NULL THEN 'N' ELSE 'Y' END FROM RPTIMAGELIB R WHERE R.IMAGENAME = 'Municipality_Logo') SHOWLOGO
	    ,(SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'Municipality_Name') Municipality_Name
	    ,(SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'Municipality_Page_Footer') Municipality_Page_Footer
FROM CACOMPUTEDFEE 
INNER JOIN CAINVOICEFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CAINVOICEFEE.CACOMPUTEDFEEID 
INNER JOIN CAINVOICE ON CAINVOICEFEE.CAINVOICEID = CAINVOICE.CAINVOICEID 
INNER JOIN CATRANSACTIONFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CATRANSACTIONFEE.CACOMPUTEDFEEID 
INNER JOIN CATRANSACTION ON CATRANSACTIONFEE.CATRANSACTIONID = CATRANSACTION.CATRANSACTIONID 
INNER JOIN CATRANSACTIONTYPE ON CATRANSACTION.CATRANSACTIONTYPEID = CATRANSACTIONTYPE.CATRANSACTIONTYPEID 
INNER JOIN CATRANSACTIONSTATUS ON CATRANSACTION.CATRANSACTIONSTATUSID = CATRANSACTIONSTATUS.CATRANSACTIONSTATUSID 
LEFT JOIN USERS ON CATRANSACTION.CREATEDBY = USERS.SUSERGUID 
INNER JOIN CATRANSACTIONPAYMENT ON CATRANSACTION.CATRANSACTIONID = CATRANSACTIONPAYMENT.CATRANSACTIONID
INNER JOIN CAPAYMENTMETHOD ON CATRANSACTIONPAYMENT.CAPAYMENTMETHODID = CAPAYMENTMETHOD.CAPAYMENTMETHODID
WHERE (CATRANSACTION.TRANSACTIONDATE BETWEEN @STARTDATE AND @ENDDATE)
	AND CASE WHEN @VOIDS = 'YES' 
			THEN 1
			ELSE CASE WHEN (CATRANSACTIONTYPE.NAME = 'Void Reversal') OR (CATRANSACTIONSTATUS.NAME = 'Void')
				THEN 0
				ELSE 1
				END
			END = 1
--AND   (CAINVOICE.CASTATUSID <> 5)

UNION ALL

SELECT	CAMISCFEE.CAMISCFEEID AS CACOMPUTEDFEEID, CAMISCFEE.FEENAME, CAMISCFEE.AMOUNT AS COMPUTEDAMOUNT
		, CATRANSACTION.TRANSACTIONDATE, CATRANSACTION.RECEIPTNUMBER
		, COALESCE(NULLIF(LTRIM(CATRANSACTION.EXTERNALBATCHNBR), ''), 'NONE SPECIFIED') AS EXTERNALBATCHNBR
		, (CATRANSACTIONMISCFEE.PAIDAMOUNT - 2*CATRANSACTIONMISCFEE.REFUNDAMOUNT) AS PAIDAMOUNT
		, COALESCE(USERS.SUSERGUID, 'NONE') SUSERGUID
		, COALESCE(USERS.FNAME, 'NO') FNAME, COALESCE(USERS.LNAME,'USER') LNAME
		, CAINVOICE.INVOICENUMBER
		, CAINVOICEMISCFEE.CAINVOICEMISCFEEID AS CAINVOICEFEEID
		, CAPAYMENTMETHOD.NAME AS PaymentMethod
		, CATRANSACTIONTYPE.NAME AS TransactionType
		, CATRANSACTIONSTATUS.NAME AS TransactionStatus
		--,(SELECT R.[IMAGE] FROM RPTIMAGELIB R WHERE R.IMAGENAME = 'Municipality_Logo') LOGO
	    ,(SELECT CASE WHEN R.[IMAGE] IS NULL THEN 'N' ELSE 'Y' END FROM RPTIMAGELIB R WHERE R.IMAGENAME = 'Municipality_Logo') SHOWLOGO
	    ,(SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'Municipality_Name') Municipality_Name
	    ,(SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'Municipality_Page_Footer') Municipality_Page_Footer
FROM CAMISCFEE 
INNER JOIN CAINVOICEMISCFEE ON CAMISCFEE.CAMISCFEEID = CAINVOICEMISCFEE.CAMISCFEEID 
INNER JOIN CAINVOICE ON CAINVOICEMISCFEE.CAINVOICEID = CAINVOICE.CAINVOICEID 
INNER JOIN CATRANSACTIONMISCFEE ON CAMISCFEE.CAMISCFEEID = CATRANSACTIONMISCFEE.CAMISCFEEID 
INNER JOIN CATRANSACTION ON CATRANSACTIONMISCFEE.CATRANSACTIONID = CATRANSACTION.CATRANSACTIONID 
INNER JOIN CATRANSACTIONTYPE ON CATRANSACTION.CATRANSACTIONTYPEID = CATRANSACTIONTYPE.CATRANSACTIONTYPEID 
INNER JOIN CATRANSACTIONSTATUS ON CATRANSACTION.CATRANSACTIONSTATUSID = CATRANSACTIONSTATUS.CATRANSACTIONSTATUSID 
LEFT JOIN USERS ON CATRANSACTION.CREATEDBY = USERS.SUSERGUID 
INNER JOIN CATRANSACTIONPAYMENT ON CATRANSACTION.CATRANSACTIONID = CATRANSACTIONPAYMENT.CATRANSACTIONID 
INNER JOIN CAPAYMENTMETHOD ON CATRANSACTIONPAYMENT.CAPAYMENTMETHODID = CAPAYMENTMETHOD.CAPAYMENTMETHODID
WHERE (CATRANSACTION.TRANSACTIONDATE BETWEEN @STARTDATE AND @ENDDATE)		 
	AND CASE WHEN @VOIDS = 'YES' 
			THEN 1
			ELSE CASE WHEN (CATRANSACTIONTYPE.NAME = 'Void Reversal') OR (CATRANSACTIONSTATUS.NAME = 'Void')
				THEN 0
				ELSE 1
				END
			END = 1
--AND   (CAInvoice.CAStatusID <> 5)

END
