

CREATE PROCEDURE [dbo].[rpt_CM_SR_Year_Over_Year_Code_Case_Report]
@YEAR AS INT
AS
SELECT CMCODECASE.CASENUMBER AS CodeCaseNumber, CMCASETYPE.NAME AS CodeCaseType, CMCODECASE.OPENEDDATE AS OpenedDate, 
       CMCODECASE.CLOSEDDATE AS ClosedDate,
	 --  (SELECT R.[IMAGE] FROM RPTIMAGELIB R
		--WHERE R.IMAGENAME = 'Municipality_Logo') LOGO,
	   (SELECT CASE WHEN R.[IMAGE] IS NULL THEN 'N' ELSE 'Y' END FROM RPTIMAGELIB R
		WHERE R.IMAGENAME = 'Municipality_Logo') SHOWLOGO,
	   (SELECT R.REPORTTEXT FROM RPTTEXTLIB R
		WHERE R.TEXTNAME = 'Municipality_Name') Municipality_Name,	   
	   (SELECT R.REPORTTEXT FROM RPTTEXTLIB R
		WHERE R.TEXTNAME = 'Municipality_Page_Footer') Municipality_Page_Footer

FROM CMCODECASE 
INNER JOIN CMCASETYPE ON CMCODECASE.CMCASETYPEID = CMCASETYPE.CMCASETYPEID
