
--   EXEC [rpt_CA_SR_Transactions_By_GL_Account_Param] 
CREATE PROCEDURE [dbo].[rpt_CA_SR_Transactions_By_GL_Account_Param]
--@STARTDATE AS DATETIME,
--@ENDDATE AS DATETIME
AS
BEGIN

--SET @STARTDATE = DATEADD(DAY, DATEDIFF(DAY, 0, @STARTDATE), 0)
--SET @ENDDATE = DATEADD(SECOND,-1,DATEDIFF(DAY,0,@ENDDATE) + 1)

SELECT DISTINCT X.GLACCOUNTID, X.GLACCOUNTNAME, X.ACCOUNTNUMBER
FROM (
SELECT COALESCE(GLACCOUNT.GLACCOUNTID,CAFEE.ARFEECODE,'') AS GLACCOUNTID
		, COALESCE(GLACCOUNT.NAME,CAFEE.ARFEECODE, '') AS GLACCOUNTNAME, COALESCE(GLACCOUNT.ACCOUNTNUMBER, 'NONE LISTED') AS ACCOUNTNUMBER
FROM CACOMPUTEDFEE 
INNER JOIN CAFEETEMPLATEFEE ON CACOMPUTEDFEE.CAFEETEMPLATEFEEID = CAFEETEMPLATEFEE.CAFEETEMPLATEFEEID
INNER JOIN CAFEE ON CAFEETEMPLATEFEE.CAFEEID = CAFEE.CAFEEID
--INNER JOIN CAINVOICEFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CAINVOICEFEE.CACOMPUTEDFEEID 
--INNER JOIN CAINVOICE ON CAINVOICEFEE.CAINVOICEID = CAINVOICE.CAINVOICEID 
INNER JOIN CATRANSACTIONFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CATRANSACTIONFEE.CACOMPUTEDFEEID 
INNER JOIN CATRANSACTION ON CATRANSACTIONFEE.CATRANSACTIONID = CATRANSACTION.CATRANSACTIONID 
INNER JOIN CATRANSACTIONTYPE ON CATRANSACTION.CATRANSACTIONTYPEID = CATRANSACTIONTYPE.CATRANSACTIONTYPEID 
INNER JOIN CATRANSACTIONSTATUS ON CATRANSACTION.CATRANSACTIONSTATUSID = CATRANSACTIONSTATUS.CATRANSACTIONSTATUSID 
--INNER JOIN CATRANSACTIONPAYMENT ON CATRANSACTION.CATRANSACTIONID = CATRANSACTIONPAYMENT.CATRANSACTIONID
--INNER JOIN CAPAYMENTMETHOD ON CATRANSACTIONPAYMENT.CAPAYMENTMETHODID = CAPAYMENTMETHOD.CAPAYMENTMETHODID
LEFT JOIN CATRANSACTIONFEEPOSTING ON CATRANSACTIONFEE.CATRANSACTIONFEEID = CATRANSACTIONFEEPOSTING.CATRANSACTIONFEEID
LEFT JOIN CATRANSACTIONGLPOSTING ON CATRANSACTIONFEEPOSTING.CATRANSACTIONGLPOSTINGID = CATRANSACTIONGLPOSTING.CATRANSACTIONGLPOSTINGID
LEFT JOIN GLACCOUNT ON CATRANSACTIONGLPOSTING.CREDITACCOUNTID = GLACCOUNT.GLACCOUNTID
WHERE (NOT (CATRANSACTIONTYPE.NAME = 'Void Reversal')) 
AND   (NOT (CATRANSACTIONSTATUS.NAME = 'Void')) 
--AND (CATRANSACTION.TRANSACTIONDATE BETWEEN @STARTDATE AND @ENDDATE)
--AND   (CAInvoice.CAStatusID <> 5)

UNION ALL

SELECT COALESCE(GLACCOUNT.GLACCOUNTID,CAFEE.ARFEECODE) AS GLACCOUNTID
		, COALESCE(GLACCOUNT.NAME,CAFEE.ARFEECODE, '') AS GLACCOUNTNAME, COALESCE(GLACCOUNT.ACCOUNTNUMBER, 'NONE LISTED') AS ACCOUNTNUMBER
FROM CAMISCFEE 
INNER JOIN CAFEE ON CAMISCFEE.CAFEEID = CAFEE.CAFEEID
--INNER JOIN CAINVOICEMISCFEE ON CAMISCFEE.CAMISCFEEID = CAINVOICEMISCFEE.CAMISCFEEID 
--INNER JOIN CAINVOICE ON CAINVOICEMISCFEE.CAINVOICEID = CAINVOICE.CAINVOICEID 
INNER JOIN CATRANSACTIONMISCFEE ON CAMISCFEE.CAMISCFEEID = CATRANSACTIONMISCFEE.CAMISCFEEID 
INNER JOIN CATRANSACTION ON CATRANSACTIONMISCFEE.CATRANSACTIONID = CATRANSACTION.CATRANSACTIONID 
INNER JOIN CATRANSACTIONTYPE ON CATRANSACTION.CATRANSACTIONTYPEID = CATRANSACTIONTYPE.CATRANSACTIONTYPEID 
INNER JOIN CATRANSACTIONSTATUS ON CATRANSACTION.CATRANSACTIONSTATUSID = CATRANSACTIONSTATUS.CATRANSACTIONSTATUSID 
--INNER JOIN CATRANSACTIONPAYMENT ON CATRANSACTION.CATRANSACTIONID = CATRANSACTIONPAYMENT.CATRANSACTIONID 
--INNER JOIN CAPAYMENTMETHOD ON CATRANSACTIONPAYMENT.CAPAYMENTMETHODID = CAPAYMENTMETHOD.CAPAYMENTMETHODID
LEFT JOIN CATRANSACTIONMISCFEEPOSTING ON CATRANSACTIONMISCFEE.CATRANSACTIONMISCFEEID = CATRANSACTIONMISCFEEPOSTING.CATRANSACTIONMISCFEEID 
LEFT JOIN CATRANSACTIONGLPOSTING ON CATRANSACTIONMISCFEEPOSTING.CATRANSACTIONGLPOSTINGID = CATRANSACTIONGLPOSTING.CATRANSACTIONGLPOSTINGID
LEFT JOIN GLACCOUNT ON CATRANSACTIONGLPOSTING.CREDITACCOUNTID = GLACCOUNT.GLACCOUNTID
WHERE (NOT (CATRANSACTIONTYPE.NAME = 'Void Reversal')) 
AND (NOT (CATRANSACTIONSTATUS.NAME = 'Void')) 
--AND (CATRANSACTION.TRANSACTIONDATE BETWEEN @STARTDATE AND @ENDDATE)	
--AND   (CAInvoice.CAStatusID <> 5)
) X
--WHERE X.GLACCOUNTID IS NOT NULL

END
