


CREATE PROCEDURE [dbo].[rpt_CR_Citizen_Request_Detailed_Report_Contact]
@REQUESTID AS VARCHAR(36)
AS
-- Contact
SELECT CITIZENREQUESTCALLERXREF.GLOBALENTITYID, CMCODECASECONTACTTYPE.NAME AS CONTACTTYPE, GLOBALENTITY.GLOBALENTITYNAME, GLOBALENTITY.FirStNAME, 
       GLOBALENTITY.LaStNAME, MAILINGADDRESS.ADDRESSLINE1, MAILINGADDRESS.ADDRESSLINE2, MAILINGADDRESS.ADDRESSLINE3, MAILINGADDRESS.CITY, MAILINGADDRESS.STATE, 
       MAILINGADDRESS.POSTALCODE, MAILINGADDRESS.POSTDIRECTION, MAILINGADDRESS.PREDIRECTION, MAILINGADDRESS.STREETTYPE, MAILINGADDRESS.ADDRESSTYPE, 
       MAILINGADDRESS.UNITORSUITE, GLOBALENTITY.BUSINESSPHONE, GLOBALENTITY.HOMEPHONE, GLOBALENTITY.MOBILEPHONE
FROM CITIZENREQUESTCALLERXREF 
INNER JOIN GLOBALENTITY ON CITIZENREQUESTCALLERXREF.GLOBALENTITYID = GLOBALENTITY.GLOBALENTITYID 
INNER JOIN CMCODECASECONTACTTYPE ON CITIZENREQUESTCALLERXREF.CMCODECASECONTACTTYPEID = CMCODECASECONTACTTYPE.CMCODECASECONTACTTYPEID
LEFT OUTER JOIN GLOBALENTITYMAILINGADDRESS ON GLOBALENTITYMAILINGADDRESS.GLOBALENTITYID = GLOBALENTITY.GLOBALENTITYID
LEFT OUTER JOIN MAILINGADDRESS ON MAILINGADDRESS.MAILINGADDRESSID = GLOBALENTITYMAILINGADDRESS.MAILINGADDRESSID
WHERE CITIZENREQUESTCALLERXREF.CITIZENREQUESTID = @REQUESTID


