
/****** Object:  StoredProcedure [dbo].[rpt_CA_SR_GL_Export_Transaction_Report] *******/

CREATE PROCEDURE rpt_CA_SR_GL_Export_Transaction_Report

@STARTDATE datetime,
@ENDDATE datetime

AS

BEGIN
-- SET NOCOUNT ON added to prevent extra result sets from interfering with SELECT statements.

SET NOCOUNT ON;

SET @STARTDATE=dateadd(dd,datediff(dd,0,@STARTDATE),0)
SET @ENDDATE=dateadd(ss,-1,datediff(dd,0,@ENDDATE) + 1)

DECLARE @TC AS BIT = (SELECT COALESCE(S.BITVALUE,0) FROM SETTINGS S WHERE S.[NAME] = 'EnableTCIntegration');

--Case Fee Payments

SELECT	COALESCE(CTGP.POSTINGAMOUNT,CTF.PAIDAMOUNT) POSTINGAMOUNT
		, COALESCE(CTGP.POSTINGDATE, TP.PAYMENTDATE) POSTINGDATE
		, COALESCE(CTGP.CREDITACCOUNTNUMBER, F.ARFEECODE) CREDITACCOUNTNUMBER
		, COALESCE(CTGP.DEBITACCOUNTNUMBER, F.ARFEECODE) DEBITACCOUNTNUMBER
		, CT.RECEIPTNUMBER
		, CASE WHEN TT.[NAME] IN ('Fee Payment','Account Deposit','Bond Payment')
			THEN 'CREDIT'
			ELSE 'DEBIT'
			END ARTYPE
		, CASE WHEN TT.[NAME] IN ('Fee Payment','Account Deposit','Bond Payment')
			THEN COALESCE(CTGP.CREDITACCOUNTNUMBER, F.ARFEECODE)
			ELSE COALESCE(CTGP.DEBITACCOUNTNUMBER, F.ARFEECODE)
			END GLACCOUNT
		--,(SELECT R.[IMAGE] FROM RPTIMAGELIB R WHERE R.IMAGENAME = 'Municipality_Logo') LOGO
	    ,(SELECT CASE WHEN R.[IMAGE] IS NULL THEN 'N' ELSE 'Y' END FROM RPTIMAGELIB R WHERE R.IMAGENAME = 'Municipality_Logo') SHOWLOGO
	    ,(SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'Municipality_Name') Municipality_Name
	    ,(SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'Municipality_Page_Footer') Municipality_Page_Footer
		
FROM	CATRANSACTION CT
		INNER JOIN CATRANSACTIONFEE	CTF ON CT.CATRANSACTIONID = CTF.CATRANSACTIONID
		INNER JOIN CATRANSACTIONTYPE TT ON CT.CATRANSACTIONTYPEID = TT.CATRANSACTIONTYPEID
		INNER JOIN CACOMPUTEDFEE CF ON CTF.CACOMPUTEDFEEID = CF.CACOMPUTEDFEEID
		INNER JOIN CAFEETEMPLATEFEE FTF ON CF.CAFEETEMPLATEFEEID = FTF.CAFEETEMPLATEFEEID
		INNER JOIN CAFEE F ON FTF.CAFEEID = F.CAFEEID
		INNER JOIN CATRANSACTIONPAYMENT TP ON CT.CATRANSACTIONID = TP.CATRANSACTIONID
		LEFT JOIN CATRANSACTIONFEEPOSTING CTFAP ON CTF.CATRANSACTIONFEEID = CTFAP.CATRANSACTIONFEEID
		LEFT JOIN CATRANSACTIONGLPOSTING CTGP ON CTFAP.CATRANSACTIONGLPOSTINGID = CTGP.CATRANSACTIONGLPOSTINGID

WHERE	CT.CATRANSACTIONTYPEID <> 6			-- Void Reversal
		AND CT.CATRANSACTIONSTATUSID <> 2	-- Void Transaction
		AND COALESCE(CTGP.POSTINGDATE, TP.PAYMENTDATE) BETWEEN @STARTDATE AND @ENDDATE

UNION ALL

--Miscellaneous Fee Payments

SELECT	COALESCE(CTGP.POSTINGAMOUNT,CTMF.PAIDAMOUNT) POSTINGAMOUNT
		, COALESCE(CTGP.POSTINGDATE, TP.PAYMENTDATE) POSTINGDATE
		, COALESCE(CTGP.CREDITACCOUNTNUMBER, F.ARFEECODE) CREDITACCOUNTNUMBER
		, COALESCE(CTGP.DEBITACCOUNTNUMBER, F.ARFEECODE) DEBITACCOUNTNUMBER
		, CT.RECEIPTNUMBER
		, CASE WHEN TT.[NAME] IN ('Fee Payment','Account Deposit','Bond Payment')
			THEN 'CREDIT'
			ELSE 'DEBIT'
			END ARTYPE
		, CASE WHEN TT.[NAME] IN ('Fee Payment','Account Deposit','Bond Payment')
			THEN COALESCE(CTGP.CREDITACCOUNTNUMBER, F.ARFEECODE)
			ELSE COALESCE(CTGP.DEBITACCOUNTNUMBER, F.ARFEECODE)
			END GLACCOUNT
		--,(SELECT R.[IMAGE] FROM RPTIMAGELIB R WHERE R.IMAGENAME = 'Municipality_Logo') LOGO
	    ,(SELECT CASE WHEN R.[IMAGE] IS NULL THEN 'N' ELSE 'Y' END FROM RPTIMAGELIB R WHERE R.IMAGENAME = 'Municipality_Logo') SHOWLOGO
	    ,(SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'Municipality_Name') Municipality_Name
	    ,(SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'Municipality_Page_Footer') Municipality_Page_Footer
		
FROM	CATRANSACTION CT
		INNER JOIN CATRANSACTIONMISCFEE CTMF ON CT.CATRANSACTIONID = CTMF.CATRANSACTIONID
		INNER JOIN CATRANSACTIONTYPE TT ON CT.CATRANSACTIONTYPEID = TT.CATRANSACTIONTYPEID
		INNER JOIN CAMISCFEE MF ON CTMF.CAMISCFEEID = MF.CAMISCFEEID
		INNER JOIN CAFEE F ON MF.CAFEEID = F.CAFEEID
		INNER JOIN CATRANSACTIONPAYMENT TP ON CT.CATRANSACTIONID = TP.CATRANSACTIONID
		LEFT JOIN CATRANSACTIONMISCFEEPOSTING CTMFP ON CTMF.CATRANSACTIONMISCFEEID = CTMFP.CATRANSACTIONMISCFEEID
		LEFT JOIN CATRANSACTIONGLPOSTING CTGP ON CTMFP.CATRANSACTIONGLPOSTINGID = CTGP.CATRANSACTIONGLPOSTINGID
		
WHERE	CT.CATRANSACTIONTYPEID <> 6			-- Void Reversal
		AND CT.CATRANSACTIONSTATUSID <> 2	-- Void Transaction
		AND COALESCE(CTGP.POSTINGDATE, TP.PAYMENTDATE) BETWEEN @STARTDATE AND @ENDDATE

UNION ALL

--Escrow Account Deposits

SELECT	COALESCE(CTGP.POSTINGAMOUNT, CTA.AMOUNT) POSTINGAMOUNT
		, COALESCE(CTGP.POSTINGDATE, TP.PAYMENTDATE) POSTINGDATE
		, COALESCE(CTGP.CREDITACCOUNTNUMBER, GEAT.CHARGECODE) CREDITACCOUNTNUMBER
		, COALESCE(CTGP.DEBITACCOUNTNUMBER, GEAT.CHARGECODE) DEBITACCOUNTNUMBER
		, CT.RECEIPTNUMBER
		, CASE WHEN TT.[NAME] IN ('Fee Payment','Account Deposit','Bond Payment')
			THEN 'CREDIT'
			ELSE 'DEBIT'
			END ARTYPE
		, CASE WHEN TT.[NAME] IN ('Fee Payment','Account Deposit','Bond Payment')
			THEN COALESCE(CTGP.CREDITACCOUNTNUMBER, GEAT.CHARGECODE)
			ELSE COALESCE(CTGP.DEBITACCOUNTNUMBER, GEAT.CHARGECODE)
			END GLACCOUNT
		--,(SELECT R.[IMAGE] FROM RPTIMAGELIB R WHERE R.IMAGENAME = 'Municipality_Logo') LOGO
	    ,(SELECT CASE WHEN R.[IMAGE] IS NULL THEN 'N' ELSE 'Y' END FROM RPTIMAGELIB R WHERE R.IMAGENAME = 'Municipality_Logo') SHOWLOGO
	    ,(SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'Municipality_Name') Municipality_Name
	    ,(SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'Municipality_Page_Footer') Municipality_Page_Footer
		
FROM	CATRANSACTION CT
		INNER JOIN CATRANSACTIONACCOUNT CTA ON CT.CATRANSACTIONID = CTA.CATRANSACTIONID
		INNER JOIN CATRANSACTIONTYPE TT ON CT.CATRANSACTIONTYPEID = TT.CATRANSACTIONTYPEID
		INNER JOIN GLOBALENTITYACCOUNT GEA ON CTA.ENTITYACCOUNTID = GEA.GLOBALENTITYACCOUNTID
		INNER JOIN GLOBALENTITYACCOUNTTYPE GEAT ON GEA.GLOBALENTITYACCOUNTTYPEID = GEAT.GLOBALENTITYACCOUNTTYPEID
		INNER JOIN CATRANSACTIONPAYMENT TP ON CT.CATRANSACTIONID = TP.CATRANSACTIONID
		LEFT JOIN CATRANSACTIONACCOUNTPOSTING CTAP ON CTA.CATRANSACTIONACCOUNTID = CTAP.CATRANSACTIONACCOUNTID
		LEFT JOIN CATRANSACTIONGLPOSTING CTGP ON CTAP.CATRANSACTIONGLPOSTINGID = CTGP.CATRANSACTIONGLPOSTINGID

WHERE	CT.CATRANSACTIONTYPEID <> 6			-- Void Reversal
		AND CT.CATRANSACTIONSTATUSID <> 2	-- Void Transaction
		AND COALESCE(CTGP.POSTINGDATE, TP.PAYMENTDATE) BETWEEN @STARTDATE AND @ENDDATE
END
