
CREATE PROCEDURE [dbo].[rpt_CM_SR_Case_Images_Note]
@CMCODECASEID AS VARCHAR(36)
AS
SELECT CMCODECASENOTE.CMCODECASENOTEID, CMCODECASENOTE.TEXT, CMCODECASENOTE.CREATEDBY, CMCODECASENOTE.CREATEDDATE, USERS.FNAME, USERS.LNAME
FROM CMCODECASENOTE 
INNER JOIN USERS ON CMCODECASENOTE.CREATEDBY = USERS.SUSERGUID
WHERE CMCODECASENOTE.CMCODECASEID = @CMCODECASEID
