

CREATE PROCEDURE [dbo].[rpt_CM_Code_Case_By_Violation_By_Opened_Date]
@STARTDATE AS DATETIME,
@ENDDATE AS DATETIME
AS
SET @ENDDATE = DATEADD(S,-1,DATEADD(D,1,@ENDDATE))
SELECT CMCODECASE.CASENUMBER AS CaseNumber, CMCASETYPE.NAME AS CaseType, CMCODE.CODENUMBER AS CodeNumber, 
       CMCODE.DESCRIPTION AS CodeDescription, CMCODECASESTATUS.NAME AS CaseStatus, CMCODECASE.OPENEDDATE AS OpenedDate, 
       CMCODECASE.CLOSEDDATE AS ClosedDate, CMCODECASE.CMCODECASEID AS CodeCaseID
FROM CMCODECASE 
INNER JOIN CMCASETYPE ON CMCODECASE.CMCASETYPEID = CMCASETYPE.CMCASETYPEID 
INNER JOIN CMCODECASESTATUS ON CMCODECASE.CMCODECASESTATUSID = CMCODECASESTATUS.CMCODECASESTATUSID
INNER JOIN CMCODEWFSTEP ON CMCODECASE.CMCODECASEID = CMCODEWFSTEP.CMCODECASEID 
INNER JOIN CMCODEWFACTIONSTEP ON CMCODEWFSTEP.CMCODEWFSTEPID = CMCODEWFACTIONSTEP.CMCODEWFSTEPID 
INNER JOIN CMVIOLATION ON CMCODEWFACTIONSTEP.CMCODEWFACTIONSTEPID = CMVIOLATION.CMCODEWFACTIONID 
INNER JOIN CMCODE ON CMVIOLATION.CMCODEID = CMCODE.CMCODEID 
WHERE CMCODECASE.OPENEDDATE BETWEEN @STARTDATE AND @ENDDATE

UNION ALL

SELECT CMCODECASE.CASENUMBER AS CaseNumber, CMCASETYPE.NAME AS CaseType, CMCODE.CODENUMBER AS CodeNumber, 
       CMCODE.DESCRIPTION AS CodeDescription, CMCODECASESTATUS.NAME AS CaseStatus, CMCODECASE.OPENEDDATE AS OpenedDate, 
       CMCODECASE.CLOSEDDATE AS ClosedDate, CMCODECASE.CMCODECASEID AS CodeCaseID
FROM CMCODECASE 
INNER JOIN CMCASETYPE ON CMCODECASE.CMCASETYPEID = CMCASETYPE.CMCASETYPEID 
INNER JOIN CMCODECASESTATUS ON CMCODECASESTATUS.CMCODECASESTATUSID = CMCODECASE.CMCODECASESTATUSID 
INNER JOIN CMCODEWFSTEP ON CMCODECASE.CMCODECASEID = CMCODEWFSTEP.CMCODECASEID 
INNER JOIN CMVIOLATION ON CMCODEWFSTEP.CMCODEWFSTEPID = CMVIOLATION.CMCODEWFSTEPID
INNER JOIN CMCODE ON CMCODE.CMCODEID = CMVIOLATION.CMCODEID 
WHERE CMCODECASE.OPENEDDATE BETWEEN @STARTDATE AND @ENDDATE

