

CREATE PROCEDURE [dbo].[rpt_CA_SR_Payments_By_User_Report_GrandSum]
@STARTDATE AS DATETIME,
@ENDDATE AS DATETIME
AS
BEGIN

SET @STARTDATE = DATEADD(DAY, DATEDIFF(DAY, 0, @STARTDATE), 0)
SET @ENDDATE = DATEADD(S,-1,DATEADD(D,1,@ENDDATE))

SELECT UPPER(TB.PaymentMethod) AS PaymentMethod, PAIDAMOUNT, TB.USERNAME
FROM (

SELECT USERS.SUSERGUID, USERS.FNAME + ' ' + USERS.LNAME as USERNAME, CAPAYMENTMETHOD.NAME AS PaymentMethod, CATRANSACTIONFEE.PAIDAMOUNT, 
       CATRANSACTION.RECEIPTNUMBER, CAINVOICE.INVOICENUMBER, CATRANSACTION.TRANSACTIONDATE, 
       CATRANSACTIONTYPE.NAME AS TransactionType, CATRANSACTIONSTATUS.NAME AS TransactionStatus, CAInvoice.CAStatusID
FROM CACOMPUTEDFEE
INNER JOIN CAINVOICEFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CAINVOICEFEE.CACOMPUTEDFEEID 
INNER JOIN CAINVOICE ON CAINVOICEFEE.CAINVOICEID = CAINVOICE.CAINVOICEID 
INNER JOIN CATRANSACTIONFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CATRANSACTIONFEE.CACOMPUTEDFEEID 
INNER JOIN CATRANSACTION ON CATRANSACTIONFEE.CATRANSACTIONID = CATRANSACTION.CATRANSACTIONID 
INNER JOIN CATRANSACTIONTYPE ON CATRANSACTION.CATRANSACTIONTYPEID = CATRANSACTIONTYPE.CATRANSACTIONTYPEID 
INNER JOIN CATRANSACTIONSTATUS ON CATRANSACTION.CATRANSACTIONSTATUSID = CATRANSACTIONSTATUS.CATRANSACTIONSTATUSID 
INNER JOIN USERS ON CATRANSACTION.CREATEDBY = USERS.SUSERGUID 
INNER JOIN CATRANSACTIONPAYMENT ON CATRANSACTION.CATRANSACTIONID = CATRANSACTIONPAYMENT.CATRANSACTIONID 
INNER JOIN CAPAYMENTMETHOD ON CATRANSACTIONPAYMENT.CAPAYMENTMETHODID = CAPAYMENTMETHOD.CAPAYMENTMETHODID
WHERE CATRANSACTIONPAYMENT.PAYMENTDATE BETWEEN @STARTDATE AND @ENDDATE
	AND   (NOT (CATRANSACTIONTYPE.NAME = 'Void Reversal')) 
	AND   (NOT (CATRANSACTIONTYPE.NAME = 'Refund'))
	AND   (NOT (CATRANSACTIONSTATUS.NAME = 'Void')) 
	AND   (CAInvoice.CAStatusID <> 5)

UNION ALL

SELECT USERS.SUSERGUID, USERS.FNAME + ' ' + USERS.LNAME as USERNAME, CAPAYMENTMETHOD.NAME AS PaymentMethod, CATRANSACTIONMISCFEE.PAIDAMOUNT, 
       CATRANSACTION.RECEIPTNUMBER, CAINVOICE.INVOICENUMBER, CATRANSACTION.TRANSACTIONDATE, 
       CATRANSACTIONTYPE.NAME AS TransactionType, CATRANSACTIONSTATUS.NAME AS TransactionStatus, CAInvoice.CAStatusID
FROM CAMISCFEE 
INNER JOIN CAINVOICEMISCFEE ON CAMISCFEE.CAMISCFEEID = CAINVOICEMISCFEE.CAMISCFEEID 
INNER JOIN CAINVOICE ON CAINVOICEMISCFEE.CAINVOICEID = CAINVOICE.CAINVOICEID 
INNER JOIN CATRANSACTIONMISCFEE ON CAMISCFEE.CAMISCFEEID = CATRANSACTIONMISCFEE.CAMISCFEEID 
INNER JOIN CATRANSACTION ON CATRANSACTIONMISCFEE.CATRANSACTIONID = CATRANSACTION.CATRANSACTIONID 
INNER JOIN CATRANSACTIONTYPE ON CATRANSACTION.CATRANSACTIONTYPEID = CATRANSACTIONTYPE.CATRANSACTIONTYPEID 
INNER JOIN CATRANSACTIONSTATUS ON CATRANSACTION.CATRANSACTIONSTATUSID = CATRANSACTIONSTATUS.CATRANSACTIONSTATUSID 
INNER JOIN USERS ON CATRANSACTION.CREATEDBY = USERS.SUSERGUID 
INNER JOIN CATRANSACTIONPAYMENT ON CATRANSACTION.CATRANSACTIONID = CATRANSACTIONPAYMENT.CATRANSACTIONID 
INNER JOIN CAPAYMENTMETHOD ON CATRANSACTIONPAYMENT.CAPAYMENTMETHODID = CAPAYMENTMETHOD.CAPAYMENTMETHODID
WHERE CATRANSACTIONPAYMENT.PAYMENTDATE BETWEEN @STARTDATE AND @ENDDATE
	AND   (NOT (CATRANSACTIONTYPE.NAME = 'Void Reversal')) 
	AND   (NOT (CATRANSACTIONTYPE.NAME = 'Refund'))
	AND   (NOT (CATRANSACTIONSTATUS.NAME = 'Void')) 
	AND   (CAInvoice.CAStatusID <> 5)

UNION ALL

SELECT USERS.SUSERGUID, USERS.FNAME + ' ' + USERS.LNAME as USERNAME, 'REFUND' AS PaymentMethod, 0 - CATRANSACTIONFEE.REFUNDAMOUNT AS PAIDAMOUNT,
       CATRANSACTION.RECEIPTNUMBER, CAINVOICE.INVOICENUMBER, CATRANSACTION.TRANSACTIONDATE, 
       CATRANSACTIONTYPE.NAME AS TransactionType, CATRANSACTIONSTATUS.NAME AS TransactionStatus, CAInvoice.CAStatusID
FROM CACOMPUTEDFEE 
INNER JOIN CAINVOICEFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CAINVOICEFEE.CACOMPUTEDFEEID 
INNER JOIN CAINVOICE ON CAINVOICEFEE.CAINVOICEID = CAINVOICE.CAINVOICEID 
INNER JOIN CATRANSACTIONFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CATRANSACTIONFEE.CACOMPUTEDFEEID 
INNER JOIN CATRANSACTION ON CATRANSACTIONFEE.CATRANSACTIONID = CATRANSACTION.CATRANSACTIONID 
INNER JOIN CATRANSACTIONTYPE ON CATRANSACTION.CATRANSACTIONTYPEID = CATRANSACTIONTYPE.CATRANSACTIONTYPEID 
INNER JOIN CATRANSACTIONSTATUS ON CATRANSACTION.CATRANSACTIONSTATUSID = CATRANSACTIONSTATUS.CATRANSACTIONSTATUSID 
INNER JOIN USERS ON CATRANSACTION.CREATEDBY = USERS.SUSERGUID 
INNER JOIN CATRANSACTIONPAYMENT ON CATRANSACTION.CATRANSACTIONID = CATRANSACTIONPAYMENT.CATRANSACTIONID 
INNER JOIN CAPAYMENTMETHOD ON CATRANSACTIONPAYMENT.CAPAYMENTMETHODID = CAPAYMENTMETHOD.CAPAYMENTMETHODID
WHERE CATRANSACTIONPAYMENT.PAYMENTDATE BETWEEN @STARTDATE AND @ENDDATE
	AND   (NOT (CATRANSACTIONTYPE.NAME = 'Void Reversal')) 
	AND   ((CATRANSACTIONTYPE.NAME = 'Refund'))
	AND   (NOT (CATRANSACTIONSTATUS.NAME = 'Void')) 
	AND   (CAInvoice.CAStatusID <> 5)

UNION ALL

SELECT USERS.SUSERGUID, USERS.FNAME + ' ' + USERS.LNAME as USERNAME, 'REFUND' AS PaymentMethod, 0 - CATRANSACTIONMISCFEE.REFUNDAMOUNT AS PAIDAMOUNT,
       CATRANSACTION.RECEIPTNUMBER, CAINVOICE.INVOICENUMBER, CATRANSACTION.TRANSACTIONDATE, 
       CATRANSACTIONTYPE.NAME AS TransactionType, CATRANSACTIONSTATUS.NAME AS TransactionStatus, CAInvoice.CAStatusID
FROM CAMISCFEE 
INNER JOIN CAINVOICEMISCFEE ON CAMISCFEE.CAMISCFEEID = CAINVOICEMISCFEE.CAMISCFEEID 
INNER JOIN CAINVOICE ON CAINVOICEMISCFEE.CAINVOICEID = CAINVOICE.CAINVOICEID 
INNER JOIN CATRANSACTIONMISCFEE ON CAMISCFEE.CAMISCFEEID = CATRANSACTIONMISCFEE.CAMISCFEEID 
INNER JOIN CATRANSACTION ON CATRANSACTIONMISCFEE.CATRANSACTIONID = CATRANSACTION.CATRANSACTIONID 
INNER JOIN CATRANSACTIONTYPE ON CATRANSACTION.CATRANSACTIONTYPEID = CATRANSACTIONTYPE.CATRANSACTIONTYPEID 
INNER JOIN CATRANSACTIONSTATUS ON CATRANSACTION.CATRANSACTIONSTATUSID = CATRANSACTIONSTATUS.CATRANSACTIONSTATUSID 
INNER JOIN USERS ON CATRANSACTION.CREATEDBY = USERS.SUSERGUID 
INNER JOIN CATRANSACTIONPAYMENT ON CATRANSACTION.CATRANSACTIONID = CATRANSACTIONPAYMENT.CATRANSACTIONID 
INNER JOIN CAPAYMENTMETHOD ON CATRANSACTIONPAYMENT.CAPAYMENTMETHODID = CAPAYMENTMETHOD.CAPAYMENTMETHODID
WHERE CATRANSACTIONPAYMENT.PAYMENTDATE BETWEEN @STARTDATE AND @ENDDATE
	AND   (NOT (CATRANSACTIONTYPE.NAME = 'Void Reversal')) 
	AND   ((CATRANSACTIONTYPE.NAME = 'Refund'))
	AND   (NOT (CATRANSACTIONSTATUS.NAME = 'Void')) 
	AND   (CAInvoice.CAStatusID <> 5)

) AS TB
--GROUP BY TB.PaymentMethod

END
