


CREATE PROCEDURE [dbo].[rpt_CM_Code_Detail_Report_Address]
@CODECASEID AS VARCHAR(36)
AS
SELECT MAILINGADDRESS.ADDRESSLINE1, MAILINGADDRESS.ADDRESSLINE2, MAILINGADDRESS.ADDRESSLINE3, MAILINGADDRESS.CITY, MAILINGADDRESS.STATE, MAILINGADDRESS.POSTALCODE, 
       MAILINGADDRESS.POSTDIRECTION, MAILINGADDRESS.PREDIRECTION, MAILINGADDRESS.STREETTYPE, MAILINGADDRESS.PARCELNUMBER, MAILINGADDRESS.UNITORSUITE, 
       CMCODECASEADDRESS.MAILINGADDRESSID, CMCODECASEADDRESS.MAIN
FROM CMCODECASEADDRESS 
INNER JOIN MAILINGADDRESS ON CMCODECASEADDRESS.MAILINGADDRESSID = MAILINGADDRESS.MAILINGADDRESSID
WHERE CMCODECASEADDRESS.CMCODECASEID = @CODECASEID


