

CREATE PROCEDURE [dbo].[rpt_CA_SR_Transactions_By_Module]
@STARTDATE AS DATETIME,
@ENDDATE AS DATETIME
AS
BEGIN

SET @STARTDATE = DATEADD(DAY, DATEDIFF(DAY, 0, @STARTDATE), 0)
SET @ENDDATE = DATEADD(SECOND,-1,DATEDIFF(DAY,0,@ENDDATE) + 1)
              
SELECT CAComputedFee.CAComputedFeeID, CATransaction.ReceiptNumber, CAInvoice.InvoiceNumber, 
		COALESCE(BLLICENSE.LICENSENUMBER, CMCODECASE.CASENUMBER, CODEVIO.CASENUMBER, ILLICENSE.LICENSENUMBER, PLAPPLICATION.APPNUMBER
		, PLPLAN.PLANNUMBER, PMPERMIT.PERMITNUMBER, PRPROJECT.PROJECTNUMBER, RPLANDLORDLICENSE.LANDLORDNUMBER
		, RPPROPERTY.PROPERTYNUMBER, TXREMITTANCEACCOUNT.REMITTANCEACCOUNTNUMBER, IPCASE.CASENUMBER) AS CaseNumber, 
       CATransactionFee.PaidAmount, CATransactionFee.REFUNDAMOUNT, CAComputedFee.ComputedAmount, 
       CATransaction.TRANSACTIONDATE, CAPaymentMethod.Name AS PaymentMethod, CATransactionPayment.SupplementalData, 
       CATransactionType.Name AS TransactionType, CACOMPUTEDFEE.FEEName AS FeeName, CAENTITY.Name AS Module
	   --,(SELECT R.[IMAGE] FROM RPTIMAGELIB R WHERE R.IMAGENAME = 'Municipality_Logo') LOGO
	   ,(SELECT CASE WHEN R.[IMAGE] IS NULL THEN 'N' ELSE 'Y' END FROM RPTIMAGELIB R WHERE R.IMAGENAME = 'Municipality_Logo') SHOWLOGO
	   ,(SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'Municipality_Name') Municipality_Name
	   ,(SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'Municipality_Page_Footer') Municipality_Page_Footer
FROM CACOMPUTEDFEE 
INNER JOIN CAINVOICEFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CAINVOICEFEE.CACOMPUTEDFEEID 
INNER JOIN CAINVOICE ON CAINVOICEFEE.CAINVOICEID = CAINVOICE.CAINVOICEID AND (CAInvoice.CAStatusID <> 5)
INNER JOIN CATRANSACTIONFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CATRANSACTIONFEE.CACOMPUTEDFEEID AND CATRANSACTIONFEE.CASTATUSID NOT IN (5,10) --VOID, DELETED
INNER JOIN CATRANSACTION ON CATRANSACTIONFEE.CATRANSACTIONID = CATRANSACTION.CATRANSACTIONID AND CATRANSACTION.CATRANSACTIONSTATUSID NOT IN (2,3) --VOID, NSF
INNER JOIN CATRANSACTIONTYPE ON CATRANSACTION.CATRANSACTIONTYPEID = CATRANSACTIONTYPE.CATRANSACTIONTYPEID AND CATRANSACTIONTYPE.CATRANSACTIONTYPEID NOT IN (5, 6) --NSF, VOID REVERSAL
INNER JOIN CATRANSACTIONSTATUS ON CATRANSACTION.CATRANSACTIONSTATUSID = CATRANSACTIONSTATUS.CATRANSACTIONSTATUSID 
INNER JOIN USERS ON CATRANSACTION.CREATEDBY = USERS.SUSERGUID 
INNER JOIN CATRANSACTIONPAYMENT ON CATRANSACTION.CATRANSACTIONID = CATRANSACTIONPAYMENT.CATRANSACTIONID AND CATRANSACTIONPAYMENT.CAPAYMENTSTATUSID NOT IN (3,5) --NSF, VOID
INNER JOIN CAPAYMENTMETHOD ON CATRANSACTIONPAYMENT.CAPAYMENTMETHODID = CAPAYMENTMETHOD.CAPAYMENTMETHODID
INNER JOIN CAFeeTemplateFee ON CAComputedFee.CAFeeTemplateFeeID = CAFeeTemplateFee.CAFeeTemplateFeeID 
INNER JOIN CAFeeTemplate ON CAFeeTemplateFee.CAFeeTemplateID = CAFEETEMPLATE.CAFEETEMPLATEID
INNER JOIN CAENTITY ON CAENTITY.CAENTITYID = CAFEETEMPLATE.CAENTITYID
LEFT OUTER JOIN CMCodeCaseFee ON CMCodeCaseFee.CAComputedFeeID = CAComputedFee.CAComputedFeeID
LEFT OUTER JOIN CMCodeCase ON CMCodeCaseFee.CMCodeCaseID = CMCodeCase.CMCodeCaseID 
LEFT OUTER JOIN CMVIOLATIONFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CMVIOLATIONFEE.CACOMPUTEDFEEID
LEFT OUTER JOIN CMVIOLATION ON CMVIOLATIONFEE.CMVIOLATIONID = CMVIOLATION.CMVIOLATIONID
LEFT OUTER JOIN CMCODEWFSTEP ON CMVIOLATION.CMCODEWFSTEPID = CMCODEWFSTEP.CMCODEWFSTEPID
LEFT OUTER JOIN CMCODECASE CODEVIO ON CMCODEWFSTEP.CMCODECASEID = CODEVIO.CMCODECASEID 
LEFT OUTER JOIN PRProjectFee ON CAComputedFee.CAComputedFeeID = PRProjectFee.CAComputedFeeID
LEFT OUTER JOIN PRProject ON PRProjectFee.PRProjectID = PRProject.PRProjectID
LEFT OUTER JOIN BLLicenseFee ON CAComputedFee.CAComputedFeeID = BLLicenseFee.CAComputedFeeID
LEFT OUTER JOIN BLLicense ON BLLicenseFee.BLLicenseID = BLLicense.BLLicenseID 
LEFT OUTER JOIN PLPlanFee ON CAComputedFee.CAComputedFeeID = PLPlanFee.CAComputedFeeID
LEFT OUTER JOIN PLPlan ON PLPlan.PLPlanID = PLPlanFee.PLPlanID 
LEFT OUTER JOIN PMPermitFee ON CAComputedFee.CAComputedFeeID = PMPermitFee.CAComputedFeeID
LEFT OUTER JOIN PMPermit ON PMPermit.PMPermitID = PMPermitFee.PMPermitID 
LEFT OUTER JOIN ILLICENSEFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = ILLICENSEFEE.CACOMPUTEDFEEID 
LEFT OUTER JOIN ILLICENSE ON ILLICENSEFEE.ILLICENSEID = ILLICENSE.ILLICENSEID 
LEFT OUTER JOIN PLAPPLICATIONFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = PLAPPLICATIONFEE.CACOMPUTEDFEEID 
LEFT OUTER JOIN PLAPPLICATION ON PLAPPLICATIONFEE.PLAPPLICATIONID = PLAPPLICATION.PLAPPLICATIONID 
LEFT OUTER JOIN RPLANDLORDLICENSEFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = RPLANDLORDLICENSEFEE.CACOMPUTEDFEEID 
LEFT OUTER JOIN RPLANDLORDLICENSE ON RPLANDLORDLICENSEFEE.RPLANDLORDLICENSEID = RPLANDLORDLICENSE.RPLANDLORDLICENSEID 
LEFT OUTER JOIN RPPROPERTYFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = RPPROPERTYFEE.CACOMPUTEDFEEID 
LEFT OUTER JOIN RPPROPERTY ON RPPROPERTYFEE.RPPROPERTYID = RPPROPERTY.RPPROPERTYID 
LEFT OUTER JOIN TXREMITTANCEFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = TXREMITTANCEFEE.CACOMPUTEDFEEID 
LEFT OUTER JOIN TXREMITTANCE ON TXREMITTANCEFEE.TXREMITTANCEID = TXREMITTANCE.TXREMITTANCEID 
LEFT OUTER JOIN TXREMITTANCEACCOUNT ON TXREMITTANCE.TXREMITTANCEACCOUNTID = TXREMITTANCEACCOUNT.TXREMITTANCEACCOUNTID
LEFT OUTER JOIN IPCONDITIONFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = IPCONDITIONFEE.CACOMPUTEDFEEID
LEFT OUTER JOIN IPCONDITION ON IPCONDITIONFEE.IPCONDITIONID = IPCONDITION.IPCONDITIONID
LEFT OUTER JOIN IPCASE ON IPCONDITION.IPCASEID = IPCASE.IPCASEID
WHERE CATransaction.TransactionDate BETWEEN @STARTDATE AND @ENDDATE
AND CACOMPUTEDFEE.CASTATUSID NOT IN (5,10) --VOID, DELETED

UNION ALL

SELECT CAMiscFee.CAMiscFeeID AS CAComputedFeeID, CATransaction.ReceiptNumber, CAInvoice.InvoiceNumber, 'Misc Fee' AS CaseNumber, 
       COALESCE(CATransactionMiscFee.PaidAmount, CATRANSACTIONPAYMENT.PAYMENTAMOUNT) AS PaidAmount, CATransactionMiscFee.REFUNDAMOUNT, CAMiscFee.Amount AS ComputedAmount, 
       CATransaction.TRANSACTIONDATE, CAPaymentMethod.Name AS PaymentMethod, CATransactionPayment.SupplementalData, 
       CATransactionType.Name AS TransactionType, CAMISCFEE.FEENAME AS FeeName, 'Cashier' AS Module 
	   --,(SELECT R.[IMAGE] FROM RPTIMAGELIB R WHERE R.IMAGENAME = 'Municipality_Logo') LOGO
	   ,(SELECT CASE WHEN R.[IMAGE] IS NULL THEN 'N' ELSE 'Y' END FROM RPTIMAGELIB R WHERE R.IMAGENAME = 'Municipality_Logo') SHOWLOGO
	   ,(SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'Municipality_Name') Municipality_Name
	   ,(SELECT R.REPORTTEXT FROM RPTTEXTLIB R WHERE R.TEXTNAME = 'Municipality_Page_Footer') Municipality_Page_Footer
FROM CAMISCFEE 
INNER JOIN CAINVOICEMISCFEE ON CAINVOICEMISCFEE.CAMISCFEEID = CAMISCFEE.CAMISCFEEID --AND CAINVOICEMISCFEE.CASTATUSID NOT IN (5,10) --VOID, DELETED
INNER JOIN CAINVOICE ON CAINVOICEMISCFEE.CAINVOICEID = CAINVOICE.CAINVOICEID AND (CAInvoice.CAStatusID <> 5)
LEFT OUTER JOIN CATRANSACTIONMISCFEE ON CAMISCFEE.CAMISCFEEID = CATRANSACTIONMISCFEE.CAMISCFEEID AND CATRANSACTIONMISCFEE.CASTATUSID NOT IN (5,10) --VOID, DELETED
INNER JOIN CATRANSACTIONINVOICE ON CATRANSACTIONINVOICE.CAINVOICEID = CAINVOICE.CAINVOICEID
INNER JOIN CATRANSACTION ON CATRANSACTIONINVOICE.CATRANSACTIONID = CATRANSACTION.CATRANSACTIONID AND CATRANSACTION.CATRANSACTIONSTATUSID NOT IN (2,3) --VOID, NSF
INNER JOIN CATRANSACTIONTYPE ON CATRANSACTION.CATRANSACTIONTYPEID = CATRANSACTIONTYPE.CATRANSACTIONTYPEID AND CATRANSACTIONTYPE.CATRANSACTIONTYPEID NOT IN (5, 6) --NSF, VOID REVERSAL
INNER JOIN CATRANSACTIONSTATUS ON CATRANSACTION.CATRANSACTIONSTATUSID = CATRANSACTIONSTATUS.CATRANSACTIONSTATUSID 
INNER JOIN CATRANSACTIONPAYMENT ON CATRANSACTION.CATRANSACTIONID = CATRANSACTIONPAYMENT.CATRANSACTIONID AND CATRANSACTIONPAYMENT.CAPAYMENTSTATUSID NOT IN (3,5) --NSF, VOID
INNER JOIN CAPAYMENTMETHOD ON CATRANSACTIONPAYMENT.CAPAYMENTMETHODID = CAPAYMENTMETHOD.CAPAYMENTMETHODID
WHERE CATransaction.TransactionDate BETWEEN @STARTDATE AND @ENDDATE AND 
CAMISCFEE.CASTATUSID NOT IN (5,10) --VOID, DELETED

END
