


CREATE PROCEDURE [dbo].[rpt_CA_SR_Transactions_By_GL_Account_GrandSum]
@STARTDATE AS DATETIME,
@ENDDATE AS DATETIME
AS
BEGIN

SET @STARTDATE = DATEADD(DAY, DATEDIFF(DAY, 0, @STARTDATE), 0)
SET @ENDDATE = DATEADD(SECOND,-1,DATEDIFF(DAY,0,@ENDDATE) + 1)

SELECT UPPER(TB.PaymentMethod) AS PaymentMethod, ISNULL(TB.PAIDAMOUNT,0) AS PAIDAMOUNT, ISNULL(TB.POSTINGAMOUNT,0) AS POSTINGAMOUNT
		, TB.GLACCOUNTID
FROM (

SELECT	CAPAYMENTMETHOD.NAME AS PaymentMethod, (CATRANSACTIONFEE.PAIDAMOUNT - 2*CATRANSACTIONFEE.REFUNDAMOUNT) AS PAIDAMOUNT,
		CASE WHEN (SELECT COALESCE(S.BITVALUE,0) FROM SETTINGS S WHERE S.NAME = 'EnableTCIntegration') = 0 THEN (
		CATRANSACTIONGLPOSTING.POSTINGAMOUNT * CASE WHEN CATRANSACTIONTYPE.NAME = 'Refund' THEN -1 ELSE 1 END)
		ELSE (CATRANSACTIONFEE.PAIDAMOUNT - 2*CATRANSACTIONFEE.REFUNDAMOUNT) END AS POSTINGAMOUNT
		, COALESCE(GLACCOUNT.GLACCOUNTID,CAFEE.ARFEECODE) AS GLACCOUNTID
FROM CACOMPUTEDFEE
INNER JOIN CAFEETEMPLATEFEE ON CACOMPUTEDFEE.CAFEETEMPLATEFEEID = CAFEETEMPLATEFEE.CAFEETEMPLATEFEEID
INNER JOIN CAFEE ON CAFEETEMPLATEFEE.CAFEEID = CAFEE.CAFEEID
INNER JOIN CAINVOICEFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CAINVOICEFEE.CACOMPUTEDFEEID 
INNER JOIN CAINVOICE ON CAINVOICEFEE.CAINVOICEID = CAINVOICE.CAINVOICEID 
INNER JOIN CATRANSACTIONFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CATRANSACTIONFEE.CACOMPUTEDFEEID 
INNER JOIN CATRANSACTION ON CATRANSACTIONFEE.CATRANSACTIONID = CATRANSACTION.CATRANSACTIONID 
INNER JOIN CATRANSACTIONTYPE ON CATRANSACTION.CATRANSACTIONTYPEID = CATRANSACTIONTYPE.CATRANSACTIONTYPEID 
INNER JOIN CATRANSACTIONSTATUS ON CATRANSACTION.CATRANSACTIONSTATUSID = CATRANSACTIONSTATUS.CATRANSACTIONSTATUSID 
INNER JOIN USERS ON CATRANSACTION.CREATEDBY = USERS.SUSERGUID 
INNER JOIN CATRANSACTIONPAYMENT ON CATRANSACTION.CATRANSACTIONID = CATRANSACTIONPAYMENT.CATRANSACTIONID 
INNER JOIN CAPAYMENTMETHOD ON CATRANSACTIONPAYMENT.CAPAYMENTMETHODID = CAPAYMENTMETHOD.CAPAYMENTMETHODID
LEFT JOIN CATRANSACTIONFEEPOSTING ON CATRANSACTIONFEE.CATRANSACTIONFEEID = CATRANSACTIONFEEPOSTING.CATRANSACTIONFEEID 
LEFT JOIN CATRANSACTIONGLPOSTING ON CATRANSACTIONFEEPOSTING.CATRANSACTIONGLPOSTINGID = CATRANSACTIONGLPOSTING.CATRANSACTIONGLPOSTINGID
LEFT JOIN GLACCOUNT ON CATRANSACTIONGLPOSTING.CREDITACCOUNTID = GLACCOUNT.GLACCOUNTID
WHERE (CATRANSACTION.TRANSACTIONDATE BETWEEN @STARTDATE AND @ENDDATE)
AND   (NOT (CATRANSACTIONTYPE.NAME = 'Void Reversal')) 
AND   (NOT (CATRANSACTIONSTATUS.NAME = 'Void')) 
--AND   (CAInvoice.CAStatusID <> 5)

UNION ALL

SELECT	CAPAYMENTMETHOD.NAME AS PaymentMethod, (CATRANSACTIONMISCFEE.PAIDAMOUNT - 2*CATRANSACTIONMISCFEE.REFUNDAMOUNT) AS PAIDAMOUNT,
		CASE WHEN (SELECT COALESCE(S.BITVALUE,0) FROM SETTINGS S WHERE S.NAME = 'EnableTCIntegration') = 0 THEN (
		CATRANSACTIONGLPOSTING.POSTINGAMOUNT * CASE WHEN CATRANSACTIONTYPE.NAME = 'Refund' THEN -1 ELSE 1 END)
		ELSE (CATRANSACTIONMISCFEE.PAIDAMOUNT - 2*CATRANSACTIONMISCFEE.REFUNDAMOUNT) END AS POSTINGAMOUNT
		, COALESCE(GLACCOUNT.GLACCOUNTID,CAFEE.ARFEECODE) AS GLACCOUNTID
FROM CAMISCFEE 
INNER JOIN CAFEE ON CAMISCFEE.CAFEEID = CAFEE.CAFEEID
INNER JOIN CAINVOICEMISCFEE ON CAMISCFEE.CAMISCFEEID = CAINVOICEMISCFEE.CAMISCFEEID 
INNER JOIN CAINVOICE ON CAINVOICEMISCFEE.CAINVOICEID = CAINVOICE.CAINVOICEID 
INNER JOIN CATRANSACTIONMISCFEE ON CAMISCFEE.CAMISCFEEID = CATRANSACTIONMISCFEE.CAMISCFEEID 
INNER JOIN CATRANSACTION ON CATRANSACTIONMISCFEE.CATRANSACTIONID = CATRANSACTION.CATRANSACTIONID 
INNER JOIN CATRANSACTIONTYPE ON CATRANSACTION.CATRANSACTIONTYPEID = CATRANSACTIONTYPE.CATRANSACTIONTYPEID 
INNER JOIN CATRANSACTIONSTATUS ON CATRANSACTION.CATRANSACTIONSTATUSID = CATRANSACTIONSTATUS.CATRANSACTIONSTATUSID 
INNER JOIN USERS ON CATRANSACTION.CREATEDBY = USERS.SUSERGUID 
INNER JOIN CATRANSACTIONPAYMENT ON CATRANSACTION.CATRANSACTIONID = CATRANSACTIONPAYMENT.CATRANSACTIONID 
INNER JOIN CAPAYMENTMETHOD ON CATRANSACTIONPAYMENT.CAPAYMENTMETHODID = CAPAYMENTMETHOD.CAPAYMENTMETHODID
LEFT JOIN CATRANSACTIONMISCFEEPOSTING ON CATRANSACTIONMISCFEE.CATRANSACTIONMISCFEEID = CATRANSACTIONMISCFEEPOSTING.CATRANSACTIONMISCFEEID 
LEFT JOIN CATRANSACTIONGLPOSTING ON CATRANSACTIONMISCFEEPOSTING.CATRANSACTIONGLPOSTINGID = CATRANSACTIONGLPOSTING.CATRANSACTIONGLPOSTINGID
LEFT JOIN GLACCOUNT ON CATRANSACTIONGLPOSTING.CREDITACCOUNTID = GLACCOUNT.GLACCOUNTID
WHERE (CATRANSACTION.TRANSACTIONDATE BETWEEN @STARTDATE AND @ENDDATE)
AND   (NOT (CATRANSACTIONTYPE.NAME = 'Void Reversal')) 
AND   (NOT (CATRANSACTIONSTATUS.NAME = 'Void')) 
--AND   (CAInvoice.CAStatusID <> 5)

) AS TB
--GROUP BY TB.PaymentMethod

END
