
CREATE PROCEDURE [dbo].[rpt_CR_SR_Citizen_Request_History_Report]
@REQUESTID AS VARCHAR(36)
AS
SELECT HISTORYCRMMANAGEMENT.CHANGEDON, HISTORYCRMMANAGEMENT.FIELDNAME, HISTORYCRMMANAGEMENT.OLDVALUE, 
       HISTORYCRMMANAGEMENT.NEWVALUE, HISTORYCRMMANAGEMENT.ADDITIONALINFO, USERS.FNAME + ' ' + USERS.LNAME AS USERNAME,
       CITIZENREQUEST.REQUESTNUMBER, HISTORYCRMMANAGEMENT.ROWVERSION, CONVERT(DATE,HISTORYCRMMANAGEMENT.CHANGEDON) AS ChangedDate,
	   (SELECT R.[IMAGE] FROM RPTIMAGELIB R
		WHERE R.IMAGENAME = 'Municipality_Logo') LOGO,
	   (SELECT CASE WHEN R.[IMAGE] IS NULL THEN 'N' ELSE 'Y' END FROM RPTIMAGELIB R
		WHERE R.IMAGENAME = 'Municipality_Logo') SHOWLOGO,
	   (SELECT R.REPORTTEXT FROM RPTTEXTLIB R
		WHERE R.TEXTNAME = 'Municipality_Name') Municipality_Name,	   
	   (SELECT R.REPORTTEXT FROM RPTTEXTLIB R
		WHERE R.TEXTNAME = 'Municipality_Page_Footer') Municipality_Page_Footer

FROM HISTORYCRMMANAGEMENT 
INNER JOIN CITIZENREQUEST ON HISTORYCRMMANAGEMENT.ID = CITIZENREQUEST.CITIZENREQUESTID 
INNER JOIN USERS ON HISTORYCRMMANAGEMENT.CHANGEDBY = USERS.SUSERGUID
WHERE CITIZENREQUEST.CITIZENREQUESTID = @REQUESTID

