


CREATE PROCEDURE [dbo].[rpt_CM_Code_Case_Activity_Report]
@CODECASEID AS VARCHAR(36)
AS
SELECT CM.CASENUMBER AS CaseNumber, CM.OPENEDDATE AS OpenedDate, CM.CLOSEDDATE AS ClosedDate, 
       CMCODEACTIVITYTYPE.NAME AS ActivityType, CMCODEACTIVITY.CODEACTIVITYCOMMENTS AS Comments, CMCODECASESTATUS.NAME AS CodeCaseStatus, 
       CMCASETYPE.NAME AS CaseType, USERS.FNAME + ' ' + USERS.LNAME AS CreatedBy, CMCODEACTIVITY.CREATEDON AS ActivityCreateDate, CMCODEACTIVITY.CMCODEACTIVITYID,
       CMCODEACTIVITY.CODEACTIVITYNAME AS ActivityName, CONVERT(VARCHAR(10), CMCODEACTIVITY.CREATEDON, 108) AS ActivityTime,
       (SELECT MAILINGADDRESS.ADDRESSLINE1
        FROM CMCODECASEADDRESS INNER JOIN MAILINGADDRESS ON CMCODECASEADDRESS.MAILINGADDRESSID = MAILINGADDRESS.MAILINGADDRESSID
        WHERE CMCODECASEADDRESS.CMCODECASEID = CM.CMCODECASEID AND CMCODECASEADDRESS.MAIN = 'TRUE') AS ADDRESSLINE1,
       (SELECT MAILINGADDRESS.ADDRESSLINE2
        FROM CMCODECASEADDRESS INNER JOIN MAILINGADDRESS ON CMCODECASEADDRESS.MAILINGADDRESSID = MAILINGADDRESS.MAILINGADDRESSID
        WHERE CMCODECASEADDRESS.CMCODECASEID = CM.CMCODECASEID AND CMCODECASEADDRESS.MAIN = 'TRUE') AS ADDRESSLINE2,
       (SELECT MAILINGADDRESS.ADDRESSLINE3
        FROM CMCODECASEADDRESS INNER JOIN MAILINGADDRESS ON CMCODECASEADDRESS.MAILINGADDRESSID = MAILINGADDRESS.MAILINGADDRESSID
        WHERE CMCODECASEADDRESS.CMCODECASEID = CM.CMCODECASEID AND CMCODECASEADDRESS.MAIN = 'TRUE') AS ADDRESSLINE3,
       (SELECT MAILINGADDRESS.CITY
        FROM CMCODECASEADDRESS INNER JOIN MAILINGADDRESS ON CMCODECASEADDRESS.MAILINGADDRESSID = MAILINGADDRESS.MAILINGADDRESSID
        WHERE CMCODECASEADDRESS.CMCODECASEID = CM.CMCODECASEID AND CMCODECASEADDRESS.MAIN = 'TRUE') AS CITY,
       (SELECT MAILINGADDRESS.POSTALCODE
        FROM CMCODECASEADDRESS INNER JOIN MAILINGADDRESS ON CMCODECASEADDRESS.MAILINGADDRESSID = MAILINGADDRESS.MAILINGADDRESSID
        WHERE CMCODECASEADDRESS.CMCODECASEID = CM.CMCODECASEID AND CMCODECASEADDRESS.MAIN = 'TRUE') AS POSTALCODE,
       (SELECT MAILINGADDRESS.POSTDIRECTION
        FROM CMCODECASEADDRESS INNER JOIN
        MAILINGADDRESS ON CMCODECASEADDRESS.MAILINGADDRESSID = MAILINGADDRESS.MAILINGADDRESSID
        WHERE CMCODECASEADDRESS.CMCODECASEID = CM.CMCODECASEID AND CMCODECASEADDRESS.MAIN = 'TRUE') AS POSTDIRECTION,
       (SELECT MAILINGADDRESS.PREDIRECTION
        FROM CMCODECASEADDRESS INNER JOIN MAILINGADDRESS ON CMCODECASEADDRESS.MAILINGADDRESSID = MAILINGADDRESS.MAILINGADDRESSID
        WHERE CMCODECASEADDRESS.CMCODECASEID = CM.CMCODECASEID AND CMCODECASEADDRESS.MAIN = 'TRUE') AS PREDIRECTION,
       (SELECT MAILINGADDRESS.STATE
        FROM CMCODECASEADDRESS INNER JOIN MAILINGADDRESS ON CMCODECASEADDRESS.MAILINGADDRESSID = MAILINGADDRESS.MAILINGADDRESSID
        WHERE CMCODECASEADDRESS.CMCODECASEID = CM.CMCODECASEID AND CMCODECASEADDRESS.MAIN = 'TRUE') AS STATE,
       (SELECT MAILINGADDRESS.STREETTYPE
        FROM CMCODECASEADDRESS INNER JOIN MAILINGADDRESS ON CMCODECASEADDRESS.MAILINGADDRESSID = MAILINGADDRESS.MAILINGADDRESSID
        WHERE CMCODECASEADDRESS.CMCODECASEID = CM.CMCODECASEID AND CMCODECASEADDRESS.MAIN = 'TRUE') AS STREETTYPE,
       (SELECT MAILINGADDRESS.UNITORSUITE
        FROM CMCODECASEADDRESS INNER JOIN MAILINGADDRESS ON CMCODECASEADDRESS.MAILINGADDRESSID = MAILINGADDRESS.MAILINGADDRESSID
        WHERE CMCODECASEADDRESS.CMCODECASEID = CM.CMCODECASEID AND CMCODECASEADDRESS.MAIN = 'TRUE') AS UNITORSUITE,
       (SELECT RTRIM(LTRIM(FNAME)) + ' ' + RTRIM(LTRIM(LNAME))
        FROM USERS
        WHERE USERS.SUSERGUID = CM.ASSIGNEDTO) AS AssignedTo
FROM CMCODECASE AS CM 
INNER JOIN CMCODECASESTATUS ON CM.CMCODECASESTATUSID = CMCODECASESTATUS.CMCODECASESTATUSID 
INNER JOIN CMCASETYPE ON CM.CMCASETYPEID = CMCASETYPE.CMCASETYPEID 
LEFT OUTER JOIN CMCODEACTIVITY ON CM.CMCODECASEID = CMCODEACTIVITY.CMCODECASEID 
LEFT OUTER JOIN CMCODEACTIVITYTYPE ON CMCODEACTIVITY.CMCODEACTIVITYTYPEID = CMCODEACTIVITYTYPE.CMCODEACTIVITYTYPEID 
LEFT OUTER JOIN USERS ON CMCODEACTIVITY.SUSERGUID = USERS.SUSERGUID
WHERE CM.CMCODECASEID = @CODECASEID

UNION ALL

SELECT CM.CASENUMBER AS CaseNumber, CM.OPENEDDATE AS OpenedDate, CM.CLOSEDDATE AS ClosedDate, 
       CMCODEACTIVITYTYPE.NAME AS ActivityType, CMCODEACTIVITY.CODEACTIVITYCOMMENTS AS Comments, CMCODECASESTATUS.NAME AS CodeCaseStatus, 
       CMCASETYPE.NAME AS CaseType, USERS.FNAME + ' ' + USERS.LNAME AS CreatedBy, CMCODEACTIVITY.CREATEDON AS ActivityCreateDate, CMCODEACTIVITY.CMCODEACTIVITYID,
       CMCODEACTIVITY.CODEACTIVITYNAME AS ActivityName, CONVERT(VARCHAR(10), CMCODEACTIVITY.CREATEDON, 108) AS ActivityTime,
      (SELECT MAILINGADDRESS.ADDRESSLINE1
       FROM CMCODECASEADDRESS INNER JOIN MAILINGADDRESS ON CMCODECASEADDRESS.MAILINGADDRESSID = MAILINGADDRESS.MAILINGADDRESSID
       WHERE CMCODECASEADDRESS.CMCODECASEID = CM.CMCODECASEID AND CMCODECASEADDRESS.MAIN = 'TRUE') AS ADDRESSLINE1,
      (SELECT MAILINGADDRESS.ADDRESSLINE2
       FROM CMCODECASEADDRESS INNER JOIN MAILINGADDRESS ON CMCODECASEADDRESS.MAILINGADDRESSID = MAILINGADDRESS.MAILINGADDRESSID
       WHERE CMCODECASEADDRESS.CMCODECASEID = CM.CMCODECASEID AND CMCODECASEADDRESS.MAIN = 'TRUE') AS ADDRESSLINE2,
      (SELECT MAILINGADDRESS.ADDRESSLINE3
       FROM CMCODECASEADDRESS INNER JOIN MAILINGADDRESS ON CMCODECASEADDRESS.MAILINGADDRESSID = MAILINGADDRESS.MAILINGADDRESSID
       WHERE CMCODECASEADDRESS.CMCODECASEID = CM.CMCODECASEID AND CMCODECASEADDRESS.MAIN = 'TRUE') AS ADDRESSLINE3,
      (SELECT MAILINGADDRESS.CITY
       FROM CMCODECASEADDRESS INNER JOIN MAILINGADDRESS ON CMCODECASEADDRESS.MAILINGADDRESSID = MAILINGADDRESS.MAILINGADDRESSID
       WHERE CMCODECASEADDRESS.CMCODECASEID = CM.CMCODECASEID AND CMCODECASEADDRESS.MAIN = 'TRUE') AS CITY,
      (SELECT MAILINGADDRESS.POSTALCODE
       FROM CMCODECASEADDRESS INNER JOIN MAILINGADDRESS ON CMCODECASEADDRESS.MAILINGADDRESSID = MAILINGADDRESS.MAILINGADDRESSID
       WHERE CMCODECASEADDRESS.CMCODECASEID = CM.CMCODECASEID AND CMCODECASEADDRESS.MAIN = 'TRUE') AS POSTALCODE,
      (SELECT MAILINGADDRESS.POSTDIRECTION
       FROM CMCODECASEADDRESS INNER JOIN MAILINGADDRESS ON CMCODECASEADDRESS.MAILINGADDRESSID = MAILINGADDRESS.MAILINGADDRESSID
       WHERE CMCODECASEADDRESS.CMCODECASEID = CM.CMCODECASEID AND CMCODECASEADDRESS.MAIN = 'TRUE') AS POSTDIRECTION,
      (SELECT MAILINGADDRESS.PREDIRECTION
       FROM CMCODECASEADDRESS INNER JOIN MAILINGADDRESS ON CMCODECASEADDRESS.MAILINGADDRESSID = MAILINGADDRESS.MAILINGADDRESSID
       WHERE CMCODECASEADDRESS.CMCODECASEID = CM.CMCODECASEID AND CMCODECASEADDRESS.MAIN = 'TRUE') AS PREDIRECTION,
      (SELECT MAILINGADDRESS.STATE
       FROM CMCODECASEADDRESS INNER JOIN MAILINGADDRESS ON CMCODECASEADDRESS.MAILINGADDRESSID = MAILINGADDRESS.MAILINGADDRESSID
       WHERE CMCODECASEADDRESS.CMCODECASEID = CM.CMCODECASEID AND CMCODECASEADDRESS.MAIN = 'TRUE') AS STATE,
      (SELECT MAILINGADDRESS.STREETTYPE
       FROM CMCODECASEADDRESS INNER JOIN MAILINGADDRESS ON CMCODECASEADDRESS.MAILINGADDRESSID = MAILINGADDRESS.MAILINGADDRESSID
       WHERE CMCODECASEADDRESS.CMCODECASEID = CM.CMCODECASEID AND CMCODECASEADDRESS.MAIN = 'TRUE') AS STREETTYPE,
      (SELECT MAILINGADDRESS.UNITORSUITE
       FROM CMCODECASEADDRESS INNER JOIN MAILINGADDRESS ON CMCODECASEADDRESS.MAILINGADDRESSID = MAILINGADDRESS.MAILINGADDRESSID
       WHERE CMCODECASEADDRESS.CMCODECASEID = CM.CMCODECASEID AND CMCODECASEADDRESS.MAIN = 'TRUE') AS UNITORSUITE,
      (SELECT RTRIM(LTRIM(FNAME)) + ' ' + RTRIM(LTRIM(LNAME))
       FROM USERS
       WHERE USERS.SUSERGUID = CM.ASSIGNEDTO) AS AssignedTo
FROM CMCODECASE AS CM 
INNER JOIN CMCODECASESTATUS ON CM.CMCODECASESTATUSID = CMCODECASESTATUS.CMCODECASESTATUSID 
INNER JOIN CMCASETYPE ON CM.CMCASETYPEID = CMCASETYPE.CMCASETYPEID 
LEFT OUTER JOIN CMCODEACTIVITY ON CM.CMCODECASEID = CMCODEACTIVITY.CMCODECASEID 
LEFT OUTER JOIN USERS ON CMCODEACTIVITY.SUSERGUID = USERS.SUSERGUID 
LEFT OUTER JOIN CMCODEACTIVITYTYPE ON CMCODEACTIVITY.CMCODEACTIVITYTYPEID = CMCODEACTIVITYTYPE.CMCODEACTIVITYTYPEID
LEFT OUTER JOIN CMCODEWFACTIONSTEP ON CMCODEACTIVITY.CMCODEWFACTIONSTEPID = CMCODEWFACTIONSTEP.CMCODEWFACTIONSTEPID
LEFT OUTER JOIN CMCODEWFSTEP ON CMCODEWFACTIONSTEP.CMCODEWFSTEPID = CMCODEWFSTEP.CMCODEWFSTEPID

WHERE CM.CMCODECASEID = @CODECASEID


