

CREATE PROCEDURE [dbo].[rpt_CA_SR_Daily_Transaction_Listing_Bonds]
@STARTDATE AS DATETIME,
@ENDDATE AS DATETIME
AS
BEGIN
SET @STARTDATE = DATEADD(dd, DATEDIFF(dd, 0, @STARTDATE), 0)
SET @ENDDATE = DATEADD(S,-1,DATEADD(D,1,@ENDDATE))
SELECT	CATRANSACTION.CATRANSACTIONID AS CACOMPUTEDFEEID, CATRANSACTION.RECEIPTNUMBER
		, CATRANSACTION.TRANSACTIONDATE
		, COALESCE(NULLIF(LTRIM(CATRANSACTION.EXTERNALBATCHNBR), ''), 'NONE SPECIFIED') AS EXTERNALBATCHNBR
		, 'BOND - ' + GLOBALENTITYACCOUNT.NAME AS FEENAME
		, CASE 
			WHEN CATransactionType.NAME LIKE 'Refund%' THEN 0 
			ELSE ISNULL(CATRANSACTIONPAYMENT.PAYMENTAMOUNT,0) 
		END AS PaidAmount
		, CASE 
			WHEN CATransactionType.NAME LIKE 'Refund%' THEN ISNULL(-CATRANSACTIONPAYMENT.PAYMENTAMOUNT,0) 
			ELSE 0 
		END AS REFUNDAMOUNT
		, COALESCE(USERS.SUSERGUID, 'NONE') SUSERGUID
		, COALESCE(USERS.FNAME, 'NO') FNAME, COALESCE(USERS.LNAME,'USER') LNAME
		, BOND.BONDNUMBER AS INVOICENUMBER
		, CAPAYMENTMETHOD.NAME AS PaymentMethod
		, CATRANSACTIONTYPE.NAME AS TransactionType
FROM	CATRANSACTIONBOND
		INNER JOIN CATRANSACTION ON CATRANSACTIONBOND.CATRANSACTIONID = CATRANSACTION.CATRANSACTIONID 
												AND CATRANSACTION.CATRANSACTIONSTATUSID <> 3	-- NSF
		INNER JOIN CATRANSACTIONPAYMENT ON CATRANSACTIONBOND.CATRANSACTIONID = CATRANSACTIONPAYMENT.CATRANSACTIONID 
												AND CATRANSACTIONPAYMENT.CAPAYMENTSTATUSID <> 3	 --NSF
		INNER JOIN CATRANSACTIONTYPE ON CATRANSACTION.CATRANSACTIONTYPEID = CATRANSACTIONTYPE.CATRANSACTIONTYPEID 
												AND CATRANSACTIONTYPE.CATRANSACTIONTYPEID <> 5		--NSF
		INNER JOIN CATRANSACTIONSTATUS ON CATRANSACTION.CATRANSACTIONSTATUSID = CATRANSACTIONSTATUS.CATRANSACTIONSTATUSID 
		INNER JOIN CAPAYMENTMETHOD ON CATRANSACTIONPAYMENT.CAPAYMENTMETHODID = CAPAYMENTMETHOD.CAPAYMENTMETHODID 
		LEFT JOIN USERS ON Users.sUserGUID = CATransaction.CreatedBy
		INNER JOIN BOND ON CATRANSACTIONBOND.BONDID = BOND.BONDID 
		INNER JOIN GLOBALENTITYACCOUNT ON BOND.GLOBALENTITYACCOUNTID = GLOBALENTITYACCOUNT.GLOBALENTITYACCOUNTID
		INNER JOIN BONDTYPE ON BOND.BONDTYPEID = BONDTYPE.BONDTYPEID
		LEFT OUTER JOIN ( 
			SELECT	BONDRELEASE.BONDID, 
					SUM(BONDRELEASE.AMOUNT) AS AMOUNT 
			FROM	BONDRELEASE 
			GROUP BY BONDRELEASE.BONDID 
		) AS BONDREFUND ON BOND.BONDID = BONDREFUND.BONDID

WHERE	CATRANSACTION.TRANSACTIONDATE BETWEEN @STARTDATE AND @ENDDATE

UNION ALL

SELECT	CATRANSACTION.CATRANSACTIONID AS CACOMPUTEDFEEID, CATRANSACTION.RECEIPTNUMBER
		, CATRANSACTION.TRANSACTIONDATE
		, COALESCE(NULLIF(LTRIM(CATRANSACTION.EXTERNALBATCHNBR), ''), 'NONE SPECIFIED') AS EXTERNALBATCHNBR
		, 'BOND - ' + GLOBALENTITYACCOUNT.NAME AS FEENAME
		, CASE 
			WHEN CATransactionType.NAME LIKE 'Refund%' THEN 0 
			ELSE ISNULL(CATRANSACTIONPAYMENT.PAYMENTAMOUNT,0) 
		END AS PaidAmount
		, CASE 
			WHEN CATransactionType.NAME LIKE 'Refund%' THEN ISNULL(-CATRANSACTIONPAYMENT.PAYMENTAMOUNT,0) 
			ELSE 0 
		END AS REFUNDAMOUNT
		, COALESCE(USERS.SUSERGUID, 'NONE') SUSERGUID
		, COALESCE(USERS.FNAME, 'NO') FNAME, COALESCE(USERS.LNAME,'USER') LNAME
		, BOND.BONDNUMBER AS INVOICENUMBER
		, CAPAYMENTMETHOD.NAME AS PaymentMethod
		, CATRANSACTIONTYPE.NAME AS TransactionType
FROM	CATRANSACTIONBOND
		INNER JOIN CATRANSACTION ON CATRANSACTIONBOND.CATRANSACTIONID = CATRANSACTION.PARENTTRANSACTIONID 
												AND CATRANSACTION.CATRANSACTIONSTATUSID <> 3	-- NSF
		INNER JOIN CATRANSACTIONPAYMENT ON CATRANSACTIONBOND.CATRANSACTIONID = CATRANSACTIONPAYMENT.CATRANSACTIONID 
												AND CATRANSACTIONPAYMENT.CAPAYMENTSTATUSID <> 3		--NSF
		INNER JOIN CATRANSACTIONTYPE ON CATRANSACTION.CATRANSACTIONTYPEID = CATRANSACTIONTYPE.CATRANSACTIONTYPEID 
												AND CATRANSACTIONTYPE.CATRANSACTIONTYPEID <> 5	--NSF
		INNER JOIN CATRANSACTIONSTATUS ON CATRANSACTION.CATRANSACTIONSTATUSID = CATRANSACTIONSTATUS.CATRANSACTIONSTATUSID 
		INNER JOIN CAPAYMENTMETHOD ON CATRANSACTIONPAYMENT.CAPAYMENTMETHODID = CAPAYMENTMETHOD.CAPAYMENTMETHODID 
		LEFT JOIN USERS ON Users.sUserGUID = CATransaction.CreatedBy
		INNER JOIN BOND ON CATRANSACTIONBOND.BONDID = BOND.BONDID 
		INNER JOIN GLOBALENTITYACCOUNT ON BOND.GLOBALENTITYACCOUNTID = GLOBALENTITYACCOUNT.GLOBALENTITYACCOUNTID
		INNER JOIN BONDTYPE ON BOND.BONDTYPEID = BONDTYPE.BONDTYPEID
		LEFT OUTER JOIN ( 
			SELECT	BONDRELEASE.BONDID, 
					SUM(BONDRELEASE.AMOUNT) AS AMOUNT 
			FROM	BONDRELEASE 
			GROUP BY BONDRELEASE.BONDID 
		) AS BONDREFUND ON BOND.BONDID = BONDREFUND.BONDID

WHERE	CATRANSACTION.TRANSACTIONDATE BETWEEN @STARTDATE AND @ENDDATE

END
