




CREATE PROCEDURE [dbo].[rpt_CR_Requests_Deadline_Date_Reports_Address]
@REQUESTID AS VARCHAR(36)
AS
SELECT MAILINGADDRESS.ADDRESSLINE1, MAILINGADDRESS.ADDRESSLINE2, MAILINGADDRESS.ADDRESSLINE3, MAILINGADDRESS.CITY, MAILINGADDRESS.STATE, 
       MAILINGADDRESS.POSTALCODE, MAILINGADDRESS.POSTDIRECTION, MAILINGADDRESS.PREDIRECTION, MAILINGADDRESS.STREETTYPE, MAILINGADDRESS.UNITORSUITE
FROM CITIZENREQUESTADDRESS 
INNER JOIN MAILINGADDRESS ON CITIZENREQUESTADDRESS.MAILINGADDRESSID = MAILINGADDRESS.MAILINGADDRESSID
WHERE CITIZENREQUESTADDRESS.CITIZENREQUESTID = @REQUESTID AND CITIZENREQUESTADDRESS.MAIN = 'TRUE'


