


CREATE PROCEDURE [dbo].[rpt_CR_Code_Enforcement_Complaints_Activity_Summary]
@STARTDATE AS DATETIME,
@ENDDATE AS DATETIME
AS
SET @ENDDATE = DATEADD(S,-1,DATEADD(D,1,@ENDDATE))
SELECT     REQUESTNUMBER AS RequestNumber, DATEFILED AS OpenedDate, COMPCOMPLETE AS CompleteDate, CITIZENREQUESTID, YEAR(DATEFILED) AS OpenYear, YEAR(COMPCOMPLETE) AS CloseYear
FROM         CITIZENREQUEST



