
/*
EXEC rpt_CA_SR_Audit_Report '20001001', '20990101'
*/

CREATE PROCEDURE rpt_CA_SR_Audit_Report
@STARTDATE AS DATETIME,
@ENDDATE AS DATETIME
AS

BEGIN
SET NOCOUNT ON

SET @STARTDATE = DATEADD(dd, DATEDIFF(dd, 0, @startdate), 0)
SET @ENDDATE = DATEADD(S,-1,DATEADD(D,1,@ENDDATE))
;

SELECT X.CACOMPUTEDFEEID, X.FEENAME, X.CHANGETYPE, X.MODIFICATIONDATE, X.NOTES, X.CHANGEDBY
		, X.REASONNAME, X.ORIGINAL_AMOUNT, X.NEW_AMOUNT--, X.CaseID, X.CaseNumber, X.MODULE, X.FEENAME
	   --, (SELECT R.[IMAGE] FROM RPTIMAGELIB R WHERE R.IMAGENAME = 'Municipality_Logo') LOGO
	   , (SELECT CASE WHEN R.[IMAGE] IS NULL THEN 'N' ELSE 'Y' END FROM RPTIMAGELIB R WHERE R.IMAGENAME = 'Municipality_Logo') SHOWLOGO
	   , (SELECT R.REPORTTEXT FROM RPTTEXTLIB R	WHERE R.TEXTNAME = 'Municipality_Name') Municipality_Name
	   , (SELECT R.REPORTTEXT FROM RPTTEXTLIB R	WHERE R.TEXTNAME = 'Municipality_Page_Footer') Municipality_Page_Footer
INTO #LIST
FROM (
SELECT CAFD.CACOMPUTEDFEEID, C.FEENAME, 'Delete' AS CHANGETYPE, CAFD.DELETIONDATE MODIFICATIONDATE,
	CAFD.NOTES, U.FNAME + ' ' + U.LNAME CHANGEDBY,
	CAFDR.REASONNAME,
	C.COMPUTEDAMOUNT ORIGINAL_AMOUNT, NULL AS NEW_AMOUNT
	--, CA.CaseID, CA.CaseNumber, CA.MODULE, CA.FEENAME
FROM CAFEEDELETION CAFD
INNER JOIN CAFEEDELETEREASON CAFDR ON CAFD.CAFEEDELETEREASONID = CAFDR.CAFEEDELETEREASONID
INNER JOIN USERS U ON CAFD.USERID = U.SUSERGUID
INNER JOIN CACOMPUTEDFEE C ON C.CACOMPUTEDFEEID = CAFD.CACOMPUTEDFEEID
--LEFT JOIN #CASES CA ON C.CACOMPUTEDFEEID = CA.CACOMPUTEDFEEID
WHERE CAFD.DELETIONDATE BETWEEN @STARTDATE AND @ENDDATE

UNION ALL

/*DOESN'T CURRENTLY APPEAR TO BE TRACKED*/
SELECT CAFD.CACOMPUTEDFEEID, C.FEENAME, 'Delete' AS CHANGETYPE, CAFD.DELETIONDATE MODIFICATIONDATE,
	CAFD.NOTES, U.FNAME + ' ' + U.LNAME CHANGEDBY,
	CAFDR.REASONNAME,
	C.AMOUNT ORIGINAL_AMOUNT, NULL AS NEW_AMOUNT
	--, CA.CaseID, CA.CaseNumber, CA.MODULE, CA.FEENAME
FROM CAFEEDELETION CAFD
INNER JOIN CAFEEDELETEREASON CAFDR ON CAFD.CAFEEDELETEREASONID = CAFDR.CAFEEDELETEREASONID
INNER JOIN USERS U ON CAFD.USERID = U.SUSERGUID
INNER JOIN CAMISCFEE C ON C.CAMISCFEEID = CAFD.CACOMPUTEDFEEID --NO CAFD.MISCFEEID OR CAMISCFEEDELETION TABLE
--LEFT JOIN #CASES CA ON C.CAMISCFEEID = CA.CACOMPUTEDFEEID
WHERE CAFD.DELETIONDATE BETWEEN @STARTDATE AND @ENDDATE

UNION ALL

SELECT CAFA.CACOMPUTEDFEEID, C.FEENAME, 'Adjustment' AS CHANGETYPE, CAFA.CHANGEDATE MODIFICATIONDATE,
	CAFA.NOTES, U.FNAME + ' ' + U.LNAME CHANGEDBY, CAFAR.REASONNAME
	, CAFA.OLDAMOUNT AS ORIGINAL_AMOUNT, CAFA.NEWAMOUNT AS NEW_AMOUNT
	--, CA.CaseID, CA.CaseNumber , CA.MODULE, CA.FEENAME
FROM CAFEEADJUSTMENT CAFA
INNER JOIN CAFEEADJUSTREASON CAFAR ON CAFA.CAFEEADJUSTREASONID = CAFAR.CAFEEADJUSTREASONID
INNER JOIN USERS U ON CAFA.USERID = U.SUSERGUID
INNER JOIN CACOMPUTEDFEE C ON CAFA.CACOMPUTEDFEEID = C.CACOMPUTEDFEEID
--LEFT JOIN #CASES CA ON CAFA.CACOMPUTEDFEEID = CA.CACOMPUTEDFEEID
WHERE CAFA.CHANGEDATE BETWEEN @STARTDATE AND @ENDDATE

UNION ALL

SELECT CAMFA.CAMISCFEEID, C.FEENAME, 'Adjustment' AS CHANGETYPE, CAMFA.CHANGEDATE MODIFICATIONDATE,
	CAMFA.NOTES, U.FNAME + ' ' + U.LNAME CHANGEDBY, CAFAR.REASONNAME
	, CAMFA.OLDAMOUNT AS ORIGINAL_AMOUNT, CAMFA.NEWAMOUNT AS NEW_AMOUNT
	--, CA.CaseID, CA.CaseNumber , CA.MODULE, CA.FEENAME
FROM CAMISCFEEADJUSTMENT CAMFA
INNER JOIN CAFEEADJUSTREASON CAFAR ON CAMFA.CAFEEADJUSTREASONID = CAFAR.CAFEEADJUSTREASONID
INNER JOIN USERS U ON CAMFA.USERID = U.SUSERGUID
INNER JOIN CAMISCFEE C ON CAMFA.CAMISCFEEID = C.CAMISCFEEID
--LEFT JOIN #CASES CA ON CAMFA.CAMISCFEEID = CA.CACOMPUTEDFEEID
WHERE CAMFA.CHANGEDATE BETWEEN @STARTDATE AND @ENDDATE

UNION ALL

SELECT CATF.CACOMPUTEDFEEID, C.FEENAME, CASE CAT.CATRANSACTIONTYPEID WHEN 4 THEN 'Refund' WHEN 5 THEN 'NSF' WHEN 6 THEN 'Void' END AS CHANGETYPE
		, CAT.LASTCHANGEDON MODIFICATIONDATE, CAT.NOTE NOTES, U.FNAME + ' ' + U.LNAME CHANGEDBY
		, CASE CAT.CATRANSACTIONTYPEID WHEN 4 THEN 'Refund' WHEN 5 THEN 'NSF' WHEN 6 THEN 'Void' END AS REASONNAME
		, CATF.PAIDAMOUNT ORIGINAL_AMOUNT, CATF.PAIDAMOUNT - CATF.REFUNDAMOUNT AS NEW_AMOUNT
		--, CA.CaseID, CA.CaseNumber, CA.MODULE, CA.FEENAME

FROM CATRANSACTION CAT
INNER JOIN CATRANSACTIONPAYMENT TP ON CAT.CATRANSACTIONID = TP.CATRANSACTIONID
INNER JOIN CATRANSACTIONFEE CATF ON CAT.CATRANSACTIONID = CATF.CATRANSACTIONID
INNER JOIN USERS U ON CAT.LASTCHANGEDBY = U.SUSERGUID
INNER JOIN CACOMPUTEDFEE C ON CATF.CACOMPUTEDFEEID = C.CACOMPUTEDFEEID
--LEFT JOIN #CASES CA ON CATF.CACOMPUTEDFEEID = CA.CACOMPUTEDFEEID
WHERE CAT.CATRANSACTIONTYPEID IN (4,5,6)
AND TP.PAYMENTDATE BETWEEN @STARTDATE AND @ENDDATE

UNION ALL

SELECT TMF.CAMISCFEEID, C.FEENAME, CASE CAT.CATRANSACTIONTYPEID WHEN 4 THEN 'Refund' WHEN 5 THEN 'NSF' WHEN 6 THEN 'Void' END AS CHANGETYPE
		, CAT.LASTCHANGEDON MODIFICATIONDATE, CAT.NOTE NOTES, U.FNAME + ' ' + U.LNAME CHANGEDBY
		, CASE CAT.CATRANSACTIONTYPEID WHEN 4 THEN 'Refund' WHEN 5 THEN 'NSF' WHEN 6 THEN 'Void' END AS REASONNAME
		, TMF.PAIDAMOUNT ORIGINAL_AMOUNT, TMF.PAIDAMOUNT - TMF.REFUNDAMOUNT AS NEW_AMOUNT
		--, CA.CaseID, CA.CaseNumber, CA.MODULE, CA.FEENAME

FROM CATRANSACTION CAT
INNER JOIN CATRANSACTIONPAYMENT TP ON CAT.CATRANSACTIONID = TP.CATRANSACTIONID
INNER JOIN CATRANSACTIONMISCFEE TMF ON CAT.CATRANSACTIONID = TMF.CATRANSACTIONID
INNER JOIN USERS U ON CAT.LASTCHANGEDBY = U.SUSERGUID
INNER JOIN CAMISCFEE C ON TMF.CAMISCFEEID = C.CAMISCFEEID
--LEFT JOIN #CASES CA ON TMF.CAMISCFEEID = CA.CACOMPUTEDFEEID
WHERE CAT.CATRANSACTIONTYPEID IN (4,5,6)
AND TP.PAYMENTDATE BETWEEN @STARTDATE AND @ENDDATE
) X
;

CREATE INDEX TEMP1 ON #LIST (CACOMPUTEDFEEID);

SELECT X.CACOMPUTEDFEEID, X.FEENAME, X.CHANGETYPE, X.MODIFICATIONDATE, X.NOTES, X.CHANGEDBY, X.REASONNAME
		, X.ORIGINAL_AMOUNT, X.NEW_AMOUNT, X.SHOWLOGO, X.Municipality_Name
		, X.Municipality_Page_Footer, X.CaseID, X.CaseNumber, X.MODULE
FROM (
SELECT C.CACOMPUTEDFEEID, C.FEENAME, C.CHANGETYPE, C.MODIFICATIONDATE, C.NOTES, C.CHANGEDBY, C.REASONNAME
		, C.ORIGINAL_AMOUNT, C.NEW_AMOUNT, C.SHOWLOGO, C.Municipality_Name, C.Municipality_Page_Footer
		, COALESCE(BLLICENSE.BLLICENSEID, CMCODECASE.CMCODECASEID, ILLICENSE.ILLICENSEID, PLAPPLICATION.PLAPPLICATIONID, PLPLAN.PLPLANID, PMPERMIT.PMPERMITID, PRPROJECT.PRPROJECTID,
				RPLANDLORDLICENSE.RPLANDLORDLICENSEID, RPPROPERTY.RPPROPERTYID, TXREMITTANCEACCOUNT.TXREMITTANCEACCOUNTID, IPCASE.IPCASEID, IMINSPECTION.IMINSPECTIONID, CC2.CMCODECASEID, INV.CAINVOICEID)AS CaseID
		, COALESCE(BLLICENSE.LICENSENUMBER, CMCODECASE.CASENUMBER, ILLICENSE.LICENSENUMBER, PLAPPLICATION.APPNUMBER, PLPLAN.PLANNUMBER, PMPERMIT.PERMITNUMBER, PRPROJECT.PROJECTNUMBER, 
                RPLANDLORDLICENSE.LANDLORDNUMBER, RPPROPERTY.PROPERTYNUMBER, TXREMITTANCEACCOUNT.REMITTANCEACCOUNTNUMBER, IPCASE.CASENUMBER, IMINSPECTION.INSPECTIONNUMBER, CC2.CASENUMBER, INV.INVOICENUMBER)AS CaseNumber
		, CASE WHEN BLLICENSE.BLLICENSEID IS NOT NULL THEN 'Business License'
			WHEN CMCODECASE.CMCODECASEID IS NOT NULL THEN 'Code Case'
			WHEN ILLICENSE.ILLICENSEID IS NOT NULL THEN 'Prof. License'
			WHEN PLAPPLICATION.PLAPPLICATIONID IS NOT NULL THEN 'Application'
			WHEN PLPLAN.PLPLANID IS NOT NULL THEN 'Plan'
			WHEN PMPERMIT.PMPERMITID IS NOT NULL THEN 'Permit'
			WHEN PRPROJECT.PRPROJECTID IS NOT NULL THEN 'Project'
			WHEN RPLANDLORDLICENSE.RPLANDLORDLICENSEID IS NOT NULL THEN 'Land Lord'
			WHEN RPPROPERTY.RPPROPERTYID IS NOT NULL THEN 'Property'
			WHEN TXREMITTANCEACCOUNT.TXREMITTANCEACCOUNTID IS NOT NULL THEN 'Tax Remittance'
			WHEN IPCASE.IPCASEID IS NOT NULL THEN 'Case'
			WHEN IMINSPECTION.IMINSPECTIONID IS NOT NULL THEN 'Inspection'
			WHEN CMVIOLATION.CMVIOLATIONID IS NOT NULL THEN 'Violation'
			ELSE 'Cashiering'
			END AS MODULE
FROM #LIST C
LEFT JOIN BLLICENSEFEE ON C.CACOMPUTEDFEEID = BLLICENSEFEE.CACOMPUTEDFEEID 
LEFT JOIN BLLICENSE ON BLLICENSEFEE.BLLICENSEID = BLLICENSE.BLLICENSEID 
LEFT JOIN CMCODECASEFEE ON C.CACOMPUTEDFEEID = CMCODECASEFEE.CACOMPUTEDFEEID 
LEFT JOIN CMCODECASE ON CMCODECASEFEE.CMCODECASEID = CMCODECASE.CMCODECASEID 
LEFT JOIN CMVIOLATIONFEE ON CMVIOLATIONFEE.CACOMPUTEDFEEID = C.CACOMPUTEDFEEID
LEFT JOIN CMVIOLATION ON CMVIOLATION.CMVIOLATIONID = CMVIOLATIONFEE.CMVIOLATIONID
--LEFT JOIN CMCODEWFACTIONSTEP ON CMCODEWFACTIONSTEP.CMCODEWFACTIONSTEPID = CMVIOLATION.CMCODEWFACTIONID
LEFT JOIN CMCODEWFSTEP ON CMCODEWFSTEP.CMCODEWFSTEPID = CMVIOLATION.CMCODEWFSTEPID
LEFT JOIN CMCODECASE CC2 ON CMCODEWFSTEP.CMCODECASEID = CC2.CMCODECASEID
LEFT JOIN ILLICENSEFEE ON C.CACOMPUTEDFEEID = ILLICENSEFEE.CACOMPUTEDFEEID 
LEFT JOIN ILLICENSE ON ILLICENSEFEE.ILLICENSEID = ILLICENSE.ILLICENSEID 
LEFT JOIN PLAPPLICATIONFEE ON C.CACOMPUTEDFEEID = PLAPPLICATIONFEE.CACOMPUTEDFEEID 
LEFT JOIN PLAPPLICATION ON PLAPPLICATIONFEE.PLAPPLICATIONID = PLAPPLICATION.PLAPPLICATIONID 
LEFT JOIN PLPLANFEE ON C.CACOMPUTEDFEEID = PLPLANFEE.CACOMPUTEDFEEID 
LEFT JOIN PLPLAN ON PLPLANFEE.PLPLANID = PLPLAN.PLPLANID 
LEFT JOIN PMPERMITFEE ON C.CACOMPUTEDFEEID = PMPERMITFEE.CACOMPUTEDFEEID 
LEFT JOIN PMPERMIT ON PMPERMITFEE.PMPERMITID = PMPERMIT.PMPERMITID 
LEFT JOIN PRPROJECTFEE ON C.CACOMPUTEDFEEID = PRPROJECTFEE.CACOMPUTEDFEEID 
LEFT JOIN PRPROJECT ON PRPROJECTFEE.PRPROJECTID = PRPROJECT.PRPROJECTID 
LEFT JOIN RPLANDLORDLICENSEFEE ON C.CACOMPUTEDFEEID = RPLANDLORDLICENSEFEE.CACOMPUTEDFEEID 
LEFT JOIN RPLANDLORDLICENSE ON RPLANDLORDLICENSEFEE.RPLANDLORDLICENSEID = RPLANDLORDLICENSE.RPLANDLORDLICENSEID 
LEFT JOIN RPPROPERTYFEE ON C.CACOMPUTEDFEEID = RPPROPERTYFEE.CACOMPUTEDFEEID 
LEFT JOIN RPPROPERTY ON RPPROPERTYFEE.RPPROPERTYID = RPPROPERTY.RPPROPERTYID 
LEFT JOIN TXREMITTANCEFEE ON C.CACOMPUTEDFEEID = TXREMITTANCEFEE.CACOMPUTEDFEEID 
LEFT JOIN TXREMITTANCE ON TXREMITTANCEFEE.TXREMITTANCEID = TXREMITTANCE.TXREMITTANCEID 
LEFT JOIN TXREMITTANCEACCOUNT ON TXREMITTANCE.TXREMITTANCEACCOUNTID = TXREMITTANCEACCOUNT.TXREMITTANCEACCOUNTID
LEFT JOIN IPCONDITIONFEE ON C.CACOMPUTEDFEEID = IPCONDITIONFEE.CACOMPUTEDFEEID
LEFT JOIN IPCONDITION ON IPCONDITIONFEE.IPCONDITIONID = IPCONDITION.IPCONDITIONID
LEFT JOIN IPCASE ON IPCONDITION.IPCASEID = IPCASE.IPCASEID
LEFT JOIN IMINSPECTIONFEE ON C.CACOMPUTEDFEEID = IMINSPECTIONFEE.CACOMPUTEDFEEID
LEFT JOIN IMINSPECTION ON IMINSPECTION.IMINSPECTIONID = IMINSPECTIONFEE.IMINSPECTIONID
LEFT OUTER JOIN CAINVOICEMISCFEE IMF ON IMF.CAMISCFEEID = C.CACOMPUTEDFEEID
LEFT OUTER JOIN CAINVOICE INV ON INV.CAINVOICEID = IMF.CAINVOICEID

--UNION ALL

--SELECT C.CACOMPUTEDFEEID, C.FEENAME, C.CHANGETYPE, C.MODIFICATIONDATE, C.NOTES, C.CHANGEDBY, C.REASONNAME
--		, C.ORIGINAL_AMOUNT, C.NEW_AMOUNT, C.SHOWLOGO, C.Municipality_Name, C.Municipality_Page_Footer
--		, INV.CAINVOICEID AS CaseID, INV.INVOICENUMBER AS CaseNumber, 'Cashiering' AS MODULE
--FROM #LIST C
--INNER JOIN CAINVOICEMISCFEE IMF ON IMF.CAMISCFEEID = C.CACOMPUTEDFEEID
--LEFT OUTER JOIN CAINVOICE INV ON INV.CAINVOICEID = IMF.CAINVOICEID
) X


DROP TABLE #LIST;

END 
