

create PROCEDURE [dbo].[rpt_CA_Open_Invoices_By_Module]

-- This query filters out all Invoices with Invoice Status of "Paid In Full" "Void" "Refunded";
-- If Billing Contact's address needs to be shown, please use "rpt_Contacts-Billing" stored procedure as a subreport for the report

@STARTDATE AS DATETIME,
@ENDDATE AS DATETIME
AS
SET @ENDDATE = DATEADD(S,-1,DATEADD(D,1,@ENDDATE))

SELECT CAINVOICE.INVOICENUMBER, CAINVOICE.INVOICEDATE, CAINVOICE.INVOICETOTAL, GLOBALENTITY.FIRSTNAME, GLOBALENTITY.LASTNAME, 
       GLOBALENTITY.GLOBALENTITYNAME, COALESCE (PLPLAN.PLANNUMBER, PMPERMIT.PERMITNUMBER, CMCODECASE.CASENUMBER, 
       PLAPPLICATION.APPNUMBER) AS CaseNumber, CACOMPUTEDFEE.COMPUTEDAMOUNT AS ComputedAmount, CAINVOICEFEE.PAIDAMOUNT, 
       CAENTITY.NAME AS ModuleName
FROM CAINVOICE 
INNER JOIN CASTATUS ON CAINVOICE.CASTATUSID = CASTATUS.CASTATUSID 
INNER JOIN GLOBALENTITY ON CAINVOICE.GLOBALENTITYID = GLOBALENTITY.GLOBALENTITYID 
INNER JOIN CAINVOICEFEE ON CAINVOICE.CAINVOICEID = CAINVOICEFEE.CAINVOICEID 
INNER JOIN CACOMPUTEDFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CAINVOICEFEE.CACOMPUTEDFEEID 
INNER JOIN CAFEETEMPLATEFEE ON CACOMPUTEDFEE.CAFEETEMPLATEFEEID = CAFEETEMPLATEFEE.CAFEETEMPLATEFEEID 
INNER JOIN CAFEETEMPLATE ON CAFEETEMPLATEFEE.CAFEETEMPLATEID = CAFEETEMPLATE.CAFEETEMPLATEID 
INNER JOIN CAENTITY ON CAFEETEMPLATE.CAENTITYID = CAENTITY.CAENTITYID 
LEFT OUTER JOIN PLPLANFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = PLPLANFEE.CACOMPUTEDFEEID 
LEFT OUTER JOIN PLPLAN ON PLPLANFEE.PLPLANID = PLPLAN.PLPLANID 
LEFT OUTER JOIN PMPERMITFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = PMPERMITFEE.CACOMPUTEDFEEID 
LEFT OUTER JOIN PMPERMIT ON PMPERMITFEE.PMPERMITID = PMPERMIT.PMPERMITID 
LEFT OUTER JOIN CMCODECASEFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = CMCODECASEFEE.CACOMPUTEDFEEID 
LEFT OUTER JOIN CMCODECASE ON CMCODECASEFEE.CMCODECASEID = CMCODECASE.CMCODECASEID 
LEFT OUTER JOIN PLAPPLICATIONFEE ON CACOMPUTEDFEE.CACOMPUTEDFEEID = PLAPPLICATIONFEE.CACOMPUTEDFEEID 
LEFT OUTER JOIN PLAPPLICATION ON PLAPPLICATIONFEE.PLAPPLICATIONID = PLAPPLICATION.PLAPPLICATIONID
WHERE (CAINVOICE.INVOICEDATE BETWEEN @STARTDATE AND @ENDDATE) 
AND (CAINVOICE.CASTATUSID NOT IN (4, 5, 9))
UNION ALL
SELECT CAINVOICE.INVOICENUMBER, CAINVOICE.INVOICEDATE, CAINVOICE.INVOICETOTAL, GLOBALENTITY.FIRSTNAME, GLOBALENTITY.LASTNAME, 
       GLOBALENTITY.GLOBALENTITYNAME, 'Misc Fee' AS CaseNumber, CAMISCFEE.AMOUNT AS ComputedAmount, CAMISCFEE.PAIDAMOUNT, 
       'Cashier' AS ModuleName
FROM CAINVOICE 
INNER JOIN CASTATUS ON CAINVOICE.CASTATUSID = CASTATUS.CASTATUSID 
INNER JOIN GLOBALENTITY ON CAINVOICE.GLOBALENTITYID = GLOBALENTITY.GLOBALENTITYID 
INNER JOIN CAINVOICEMISCFEE ON CAINVOICE.CAINVOICEID = CAINVOICEMISCFEE.CAINVOICEID 
INNER JOIN CAMISCFEE ON CAINVOICEMISCFEE.CAMISCFEEID = CAMISCFEE.CAMISCFEEID  	                     
WHERE (CAINVOICE.INVOICEDATE BETWEEN @STARTDATE AND @ENDDATE) 
AND (CAINVOICE.CASTATUSID NOT IN (4, 5, 9))


