

CREATE PROCEDURE [dbo].[rpt_CR_Citizen_Request_Detailed_Report_Project]
@REQUESTID AS VARCHAR(36)
AS
-- Project
SELECT PRPROJECT.NAME AS ProjectName
FROM PRPROJECTCITIZENREQUEST
INNER JOIN PRPROJECT ON PRPROJECTCITIZENREQUEST.PRPROJECTID = PRPROJECT.PRPROJECTID
WHERE PRPROJECTCITIZENREQUEST.CITIZENREQUESTID = @REQUESTID


