


CREATE PROCEDURE [dbo].[rpt_CM_Code_Detail_Report_Zone]
@CODECASEID AS VARCHAR(36)
AS
SELECT CMCODECASEZONE.MAIN, ZONE.ZONECODE, ZONE.NAME, CMCODECASEZONE.ZONEID
FROM CMCODECASEZONE 
INNER JOIN ZONE ON CMCODECASEZONE.ZONEID = ZONE.ZONEID
WHERE CMCODECASEZONE.CMCODECASEID = @CODECASEID


