CREATE PROCEDURE [dbo].[USP_COMAPPEDVALUECERTTYPE_UPDATE]
(
	@COMAPPEDVALUECERTTYPEID CHAR(36),
	@MAPPEDTYPE VARCHAR(50),
	@COSIMPLELICCERTTYPEID CHAR(36),
	@MAPPEDCATEGORY VARCHAR(50),
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
UPDATE [dbo].[COMAPPEDVALUECERTTYPE] SET
	[MAPPEDTYPE] = @MAPPEDTYPE,
	[COSIMPLELICCERTTYPEID] = @COSIMPLELICCERTTYPEID,
	[MAPPEDCATEGORY] = @MAPPEDCATEGORY,
	[LASTCHANGEDBY] = @LASTCHANGEDBY,
	[LASTCHANGEDON] = @LASTCHANGEDON,
	[ROWVERSION] = @ROWVERSION + 1
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE
	[COMAPPEDVALUECERTTYPEID] = @COMAPPEDVALUECERTTYPEID AND 
	[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE