CREATE PROCEDURE [dbo].[USP_CAPRORATESCHEDULERATES_UPDATE]
(
	@CAPRORATESCHEDULERATESID CHAR(36),
	@CAPRORATESCHEDULEID CHAR(36),
	@STARTDATE DATETIME,
	@ENDDATE DATETIME,
	@RATES DECIMAL(20,4)
)
AS

UPDATE [dbo].[CAPRORATESCHEDULERATES] SET
	[CAPRORATESCHEDULEID] = @CAPRORATESCHEDULEID,
	[STARTDATE] = @STARTDATE,
	[ENDDATE] = @ENDDATE,
	[RATES] = @RATES

WHERE
	[CAPRORATESCHEDULERATESID] = @CAPRORATESCHEDULERATESID