CREATE PROCEDURE [dbo].[USP_CAPRPTSETTINGS_DELETE]
(
	@CAPRPTSETTINGSID CHAR(36),
	@ROWVERSION INT
)
AS

DELETE FROM [dbo].[CAPRPTSETTINGS]
WHERE
	[CAPRPTSETTINGSID] = @CAPRPTSETTINGSID AND 
	[ROWVERSION]= @ROWVERSION