CREATE PROCEDURE [dbo].[USP_CACPITYPE_DELETE]
(
	@CACPITYPEID CHAR(36),
	@ROWVERSION INT
)
AS
BEGIN
	
	/* FOR CACPI 
		USED @TEMPCPIID TABLE TO HOLD THE CPIID.
		AFTER DELETEING RECORD IN CACPITYPEXREF TABLE UNABLE TO IDENTIY THE RECORD IN CACPI TABLE.
	*/

	SET NOCOUNT ON;

	DECLARE @TEMPCPIID AS TABLE(SL INT IDENTITY(1,1),CPIID CHAR(36))
	DECLARE @N INT
	DECLARE @CPIID CHAR(36)
	
	INSERT INTO @TEMPCPIID(CPIID)
	SELECT [dbo].[CACPI].[CACPIID] 
		FROM [dbo].[CACPI] 
	WHERE [dbo].[CACPI].[CACPIID] IN ( SELECT [dbo].[CACPITYPEXREF].[CACPIID] 
											FROM [dbo].[CACPITYPEXREF] 
										WHERE [dbo].[CACPITYPEXREF].[CACPITYPEID]=@CACPITYPEID)

	EXEC [USP_CACPITYPEXREF_DELETE_BYPARENTID] @CACPITYPEID	

	SET @N =(SELECT MAX([SL]) FROM @TEMPCPIID)
	
	WHILE(@N>0)
		BEGIN
			SELECT @CPIID=[CPIID] FROM @TEMPCPIID WHERE [SL]=@N
			EXEC [USP_CACPI_DELETE] @CPIID
			SET	@N=@N-1
		END
	
	EXEC [USP_CAFEESETUP_DELETE_BYPARENTID] @CACPITYPEID 

	SET NOCOUNT OFF;

	DELETE FROM [dbo].[CACPITYPE]
	WHERE
		[CACPITYPEID] = @CACPITYPEID AND 
		[ROWVERSION]= @ROWVERSION
END