CREATE PROCEDURE [dbo].[USP_CAFEESETUP_DELETE]
(
	@CAFEESETUPID CHAR(36),
	@ROWVERSION INT
)
AS

DECLARE @CAFEEID CHAR(36)

SELECT @CAFEEID = [CAFEEID]
FROM   [dbo].[CAFEESETUP] WHERE [CAFEESETUPID] = @CAFEESETUPID

EXEC [dbo].[USP_CAFEEADJUSTABLECALC_DELETE_BYPARENTID] @CAFEEID,@CAFEESETUPID

DELETE FROM [dbo].[CAFEESETUP]
WHERE
	[CAFEESETUPID] = @CAFEESETUPID AND 
	[ROWVERSION]= @ROWVERSION