CREATE PROCEDURE [dbo].[USP_CMCITATIONTYPE_DELETE]
(
	@CMCITATIONTYPEID CHAR(36),
	@ROWVERSION INT
)
AS

SET NOCOUNT ON;

EXEC [dbo].[USP_AUTONUMBERSETTINGS_DELETE] @CMCITATIONTYPEID;

SET NOCOUNT OFF;

DELETE FROM [dbo].[CMCITATIONTYPE] WHERE [CMCITATIONTYPEID] = @CMCITATIONTYPEID AND [ROWVERSION]= @ROWVERSION;