CREATE PROCEDURE [dbo].[USP_CUSTOMFIELD_UPDATE]
(
	@GCUSTOMFIELD CHAR(36),
	@FKICUSTOMFIELDTYPE INT,
	@SFIELDNAME NVARCHAR(50),
	@SCUSTOMFIELD NVARCHAR(50),
	@BISPICKLIST BIT,
	@BISWORKSHEET BIT,
	@FKGCUSTOMFIELDTEMPLATE CHAR(36),
	@FKCUSTOMFIELDTABLE CHAR(36),
	@FKCUSTOMFIELDTABLECOLREF CHAR(36),
	@COLUMNOPERATOR INT
)
AS

UPDATE [dbo].[CUSTOMFIELD] SET
	[FKICUSTOMFIELDTYPE] = @FKICUSTOMFIELDTYPE,
	[SFIELDNAME] = @SFIELDNAME,
	[SCUSTOMFIELD] = @SCUSTOMFIELD,
	[BISPICKLIST] = @BISPICKLIST,
	[BISWORKSHEET] = @BISWORKSHEET,
	[FKGCUSTOMFIELDTEMPLATE] = @FKGCUSTOMFIELDTEMPLATE,
	[FKCUSTOMFIELDTABLE] = @FKCUSTOMFIELDTABLE,
	[FKCUSTOMFIELDTABLECOLREF] = @FKCUSTOMFIELDTABLECOLREF,
	[COLUMNOPERATOR] = @COLUMNOPERATOR

WHERE
	[GCUSTOMFIELD] = @GCUSTOMFIELD