CREATE PROCEDURE [dbo].[USP_CAFEETEMPLATEFEEPRORATEDATE_UPDATE]
(
	@CAFEETEMPLATEFEEPRORATEDATEID CHAR(36),
	@CAFEETEMPLATEFEEID CHAR(36),
	@STARTOBJECTTYPEID INT,
	@STARTOBJECT NVARCHAR(100),
	@STARTOBJECTFRIENDLYNAME NVARCHAR(200),
	@ENDOBJECTTYPEID INT,
	@ENDOBJECT NVARCHAR(100),
	@ENDOBJECTFRIENDLYNAME NVARCHAR(200),
	@DAYSTOPRORATE INT
)
AS

UPDATE [dbo].[CAFEETEMPLATEFEEPRORATEDATE] SET
	[CAFEETEMPLATEFEEID] = @CAFEETEMPLATEFEEID,
	[STARTOBJECTTYPEID] = @STARTOBJECTTYPEID,
	[STARTOBJECT] = @STARTOBJECT,
	[STARTOBJECTFRIENDLYNAME] = @STARTOBJECTFRIENDLYNAME,
	[ENDOBJECTTYPEID] = @ENDOBJECTTYPEID,
	[ENDOBJECT] = @ENDOBJECT,
	[ENDOBJECTFRIENDLYNAME] = @ENDOBJECTFRIENDLYNAME,
	[DAYSTOPRORATE] = @DAYSTOPRORATE

WHERE
	[CAFEETEMPLATEFEEPRORATEDATEID] = @CAFEETEMPLATEFEEPRORATEDATEID