CREATE PROCEDURE [dbo].[USP_CACONDITIONGROUP_DELETE_BY_IDS]
(
	@CONDITIONGROUPIDS RECORDIDS READONLY
)
AS
BEGIN
	DECLARE @CONDITIONGROUPS RECORDIDS
	
	;WITH CTE_CONDITIONGROUPS (CACONDITIONGROUPID) AS (
		SELECT	[dbo].[CACONDITIONGROUP].[CACONDITIONGROUPID]
		FROM	[dbo].[CACONDITIONGROUP]
		JOIN @CONDITIONGROUPIDS ON RECORDID = [dbo].[CACONDITIONGROUP].[CACONDITIONGROUPID]
		UNION ALL		
		SELECT
				CAST([INNER_CACONDITIONGROUP].[CACONDITIONGROUPID] AS CHAR(36))
		FROM	[dbo].[CACONDITIONGROUP] [INNER_CACONDITIONGROUP]
		INNER JOIN CTE_CONDITIONGROUPS [EXAMINED_CONDITIONGROUPS] ON [EXAMINED_CONDITIONGROUPS].[CACONDITIONGROUPID] = [INNER_CACONDITIONGROUP].[PARENTCONDITIONGROUPID]
	)

	INSERT INTO @CONDITIONGROUPS (RECORDID)
	SELECT [CTE_CONDITIONGROUPS].[CACONDITIONGROUPID] FROM [CTE_CONDITIONGROUPS]

	EXEC [dbo].[USP_CACONDITION_DELETE_BY_CONDITIONGROUPIDS] @CONDITIONGROUPS
	
	DELETE FROM [dbo].[CACONDITIONGROUP]
	WHERE	[CACONDITIONGROUPID] IN (SELECT RECORDID FROM @CONDITIONGROUPS) 
END