CREATE PROCEDURE [dbo].[USP_CMCODECASEHOLDTYPECONTACTTYPEREF_INSERT]
(
	@CMCODECASEHOLDTYPECONTACTTYPEID	CHAR(36),
	@CMCODECASEHOLDTYPEID	CHAR(36),
	@CMCODECASECONTACTTYPEID	CHAR(36),
	@ACTIVE BIT
)
AS
BEGIN

INSERT INTO [dbo].[CMCODECASEHOLDTYPECONTACTTYPEREF](	
	[CMCODECASEHOLDTYPECONTACTTYPEID],
	[CMCODECASEHOLDTYPEID],
	[CMCODECASECONTACTTYPEID],
	[ACTIVE]
)

VALUES
(
	@CMCODECASEHOLDTYPECONTACTTYPEID,
	@CMCODECASEHOLDTYPEID,
	@CMCODECASECONTACTTYPEID,
	@ACTIVE
)
END