CREATE PROCEDURE [dbo].[USP_CADISCOUNTSETUP_DELETE]
(
	@CADISCOUNTSETUPID CHAR(36),
	@ROWVERSION INT
)
AS
DECLARE @CADISCOUNTID CHAR(36)

SELECT @CADISCOUNTID = [CADISCOUNTID]
FROM   [dbo].[CADISCOUNTSETUP] WHERE [CADISCOUNTSETUPID] = @CADISCOUNTSETUPID

EXEC [dbo].[USP_CADISCOUNTADJUSTABLECALC_DELETE_BYPARENTID] @CADISCOUNTID,@CADISCOUNTSETUPID


DELETE FROM [dbo].[CADISCOUNTSETUP]
WHERE
	[CADISCOUNTSETUPID] = @CADISCOUNTSETUPID AND 
	[ROWVERSION]= @ROWVERSION