CREATE PROCEDURE [dbo].[USP_CUSTOMFIELDTEMPLATEITEM_UPDATE]
(
	@GCUSTOMFIELDTEMPLATEITEM CHAR(36),
	@FKGCUSTOMFIELDTEMPLATE CHAR(36),
	@SVALUE VARCHAR(50),
	@IORDER INT,
	@ISRETIRE BIT
)
AS
UPDATE [dbo].[CUSTOMFIELDTEMPLATEITEM] SET
	[FKGCUSTOMFIELDTEMPLATE] = @FKGCUSTOMFIELDTEMPLATE,
	[SVALUE] = @SVALUE,
	[IORDER] = @IORDER,
	[ISRETIRE] = @ISRETIRE
WHERE
	[GCUSTOMFIELDTEMPLATEITEM] = @GCUSTOMFIELDTEMPLATEITEM