CREATE PROCEDURE [dbo].[USP_CUSTOMFIELDCOLUMNTEMPLATE_DELETE]
(
	@CUSTOMFIELDCOLUMNTEMPLATEID CHAR(36),
	@ROWVERSION INT
)
AS
DELETE FROM [dbo].[CUSTOMFIELDCOLUMNTEMPLATE]
WHERE
	[CUSTOMFIELDCOLUMNTEMPLATEID] = @CUSTOMFIELDCOLUMNTEMPLATEID AND 
	[ROWVERSION]= @ROWVERSION