CREATE PROCEDURE [dbo].[USP_CAEXPRESSION_DELETE]
(
@CAEXPRESSIONID CHAR(36)
)
AS

	DECLARE @EXPRESSIONIDS RECORDIDS

	INSERT INTO @EXPRESSIONIDS(RECORDID)
	VALUES (@CAEXPRESSIONID)
	
	EXEC [dbo].[USP_CAEXPRESSION_DELETE_BY_IDS] @EXPRESSIONIDS