CREATE PROCEDURE [dbo].[USP_CAMODULEFEEXREF_UPDATE]
(
	@CAMODULEFEEXREFID CHAR(36),
	@CAMODULEID INT,
	@CAFEEID CHAR(36),
	@CACPIREFERENCEDATEID CHAR(36),
	@CACOMPOUNDINGINTERESTREFERENCEDATEID CHAR(36)
)
AS
UPDATE	[dbo].[CAMODULEFEEXREF] SET
	[CAMODULEID] = @CAMODULEID,
	[CAFEEID] = @CAFEEID,
	[CACPIREFERENCEDATEID] = @CACPIREFERENCEDATEID,
	[CACOMPOUNDINGINTERESTREFERENCEDATEID] = @CACOMPOUNDINGINTERESTREFERENCEDATEID
WHERE
	[CAMODULEFEEXREFID] = @CAMODULEFEEXREFID