CREATE PROCEDURE [dbo].[USP_CADISCOUNTADJUSTABLECALC_DELETE]
(
@CADISCOUNTADJUSTABLECALCID CHAR(36)
)
AS
DELETE FROM [dbo].[CADISCOUNTADJUSTABLECALC]
WHERE
	[CADISCOUNTADJUSTABLECALCID] = @CADISCOUNTADJUSTABLECALCID