CREATE PROCEDURE [dbo].[USP_CUSTOMFIELDCOLUMNTEMPLATE_INSERT]
(
	@CUSTOMFIELDCOLUMNTEMPLATEID CHAR(36),
	@FKCUSTOMFIELDLAYOUTCONTROLTYPE INT,
	@GCUSTOMFIELD CHAR(36),
	@SCOLUMNNAME NVARCHAR(50),
	@SDESCRIPTION NVARCHAR(50),
	@SFIELDTIP NVARCHAR(MAX),
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
INSERT INTO [dbo].[CUSTOMFIELDCOLUMNTEMPLATE](
	[CUSTOMFIELDCOLUMNTEMPLATEID],
	[FKCUSTOMFIELDLAYOUTCONTROLTYPE],
	[GCUSTOMFIELD],
	[SCOLUMNNAME],
	[SDESCRIPTION],
	[SFIELDTIP],
	[LASTCHANGEDBY],
	[LASTCHANGEDON],
	[ROWVERSION]
)
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
VALUES
(
	@CUSTOMFIELDCOLUMNTEMPLATEID,
	@FKCUSTOMFIELDLAYOUTCONTROLTYPE,
	@GCUSTOMFIELD,
	@SCOLUMNNAME,
	@SDESCRIPTION,
	@SFIELDTIP,
	@LASTCHANGEDBY,
	@LASTCHANGEDON,
	@ROWVERSION
)
SELECT * FROM @OUTPUTTABLE