CREATE PROCEDURE [dbo].[USP_CAFEETEMPLATEFEE_UPDATE]
(
	@CAFEETEMPLATEFEEID CHAR(36),
	@CAFEETEMPLATEID CHAR(36),
	@CAFEEID CHAR(36),
	@ISMANUAL BIT,
	@FEEDESCRIPTION NVARCHAR(MAX),
	@FEEORDER INT,
	@FEEPRIORITY INT,
	@FEENAME NVARCHAR(50),
	@CACONDITIONGROUPID CHAR(36),
	@CAEXPRESSIONID CHAR(36),
	@ISHIDDEN BIT,
	@ROUNDINGTYPEID INT,
	@ROUNDINGVALUE DECIMAL(20,4),
	@DISPLAYDEFAULTINPUT BIT,
	@DISPLAYSINGLEINPUT BIT,
	@INPUTHIDDEN BIT,
	@ISONLINE BIT,
	@ISDISABLE BIT
)
AS

UPDATE [dbo].[CAFEETEMPLATEFEE] SET
	[CAFEETEMPLATEID] = @CAFEETEMPLATEID,
	[CAFEEID] = @CAFEEID,
	[ISMANUAL] = @ISMANUAL,
	[FEEDESCRIPTION] = @FEEDESCRIPTION,
	[FEEORDER] = @FEEORDER,
	[FEEPRIORITY] = @FEEPRIORITY,
	[FEENAME] = @FEENAME,
	[CACONDITIONGROUPID] = @CACONDITIONGROUPID,
	[CAEXPRESSIONID] = @CAEXPRESSIONID,
	[ISHIDDEN] = @ISHIDDEN,
	[ROUNDINGTYPEID] = @ROUNDINGTYPEID,
	[ROUNDINGVALUE] = @ROUNDINGVALUE,
	[DISPLAYDEFAULTINPUT] = @DISPLAYDEFAULTINPUT,
	[DISPLAYSINGLEINPUT] = @DISPLAYSINGLEINPUT,
	[INPUTHIDDEN] = @INPUTHIDDEN,
	[ISONLINE] = @ISONLINE,
	[ISDISABLE] = @ISDISABLE

WHERE
	[CAFEETEMPLATEFEEID] = @CAFEETEMPLATEFEEID