CREATE PROCEDURE [dbo].[USP_CUSTOMFIELDWORKSHEETITEM_DELETE]
(
@GCUSTOMFIELDWORKSHEETITEM CHAR(36)
)
AS
DELETE FROM [dbo].[CUSTOMFIELDWORKSHEETITEM]
WHERE
	[GCUSTOMFIELDWORKSHEETITEM] = @GCUSTOMFIELDWORKSHEETITEM