CREATE PROCEDURE [dbo].[USP_CUSTOMFIELDLAYOUT_SELECT_LOOKUP]
(
	@CUSTOMFIELDMODULEID INT,
	@IS_VERSION_2_INCLUDED BIT = 0
)
AS
SET NOCOUNT ON;
SELECT 
	[dbo].[CUSTOMFIELDLAYOUT].[GCUSTOMFIELDLAYOUTS],
	[dbo].[CUSTOMFIELDLAYOUT].[SNAME]
FROM [dbo].[CUSTOMFIELDLAYOUT]
WHERE [dbo].[CUSTOMFIELDLAYOUT].[CUSTOMFIELDMODULEID] = @CUSTOMFIELDMODULEID AND 
	([dbo].[CUSTOMFIELDLAYOUT].[ISVERSION2] = @IS_VERSION_2_INCLUDED OR [dbo].[CUSTOMFIELDLAYOUT].[ISVERSION2] = 0)
ORDER BY [dbo].[CUSTOMFIELDLAYOUT].[SNAME]