CREATE PROCEDURE [dbo].[USP_COHIDDENCONTACTTYPE_UPDATE]
(
	@COHIDDENCONTACTTYPEID CHAR(36),
	@SYSTEMMODULEID INT,
	@SROLEGUID CHAR(36),
	@CONTACTTYPEID CHAR(36)
)
AS

UPDATE [dbo].[COHIDDENCONTACTTYPE] SET
	[SYSTEMMODULEID] = @SYSTEMMODULEID,
	[SROLEGUID] = @SROLEGUID,
	[CONTACTTYPEID] = @CONTACTTYPEID

WHERE
	[COHIDDENCONTACTTYPEID] = @COHIDDENCONTACTTYPEID