CREATE PROCEDURE [dbo].[USP_CAPRORATESCHEDULE_DELETE]
(
	@CAPRORATESCHEDULEID CHAR(36),
	@ROWVERSION INT
)
AS
SET NOCOUNT ON

EXEC [USP_CAPRORATESCHEDULERATES_DELETE_BYPARENTID] @CAPRORATESCHEDULEID

SET NOCOUNT OFF

DELETE FROM [dbo].[CAPRORATESCHEDULE]
WHERE
	[CAPRORATESCHEDULEID] = @CAPRORATESCHEDULEID AND 
	[ROWVERSION]= @ROWVERSION