CREATE PROCEDURE [dbo].[USP_CUSTOMFIELD_DELETEBY_CUSTOMFIELDTABLECOLUMNREFID]  
(  
 @CUSTOMFIELDTABLECOLUMNREFID CHAR(36)
)  
AS  
DELETE [dbo].[CUSTOMFIELD]  FROM [dbo].[CUSTOMFIELD] 
  WHERE [dbo].[CUSTOMFIELD].[FKCUSTOMFIELDTABLECOLREF] IS NOT NULL 
	AND [dbo].[CUSTOMFIELD].[FKCUSTOMFIELDTABLECOLREF]=@CUSTOMFIELDTABLECOLUMNREFID