CREATE PROCEDURE [dbo].[USP_CACPIREFERENCEDATE_DELETE]
(
	@CACPIREFERENCEDATEID CHAR(36),
	@ROWVERSION INT
)
AS
DELETE FROM [dbo].[CACPIREFERENCEDATE]
WHERE
	[CACPIREFERENCEDATEID] = @CACPIREFERENCEDATEID AND 
	[ROWVERSION]= @ROWVERSION