CREATE PROCEDURE [dbo].[USP_CASCHEDULE_INSERT]
(
	@CASCHEDULEID CHAR(36),
	@NAME NVARCHAR(50),
	@DESCRIPTION NVARCHAR(MAX),
	@STARTDATE DATETIME,
	@ENDDATE DATETIME,
	@IGNOREYEAR BIT,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
INSERT INTO [dbo].[CASCHEDULE](
	[CASCHEDULEID],
	[NAME],
	[DESCRIPTION],
	[STARTDATE],
	[ENDDATE],
	[IGNOREYEAR],
	[LASTCHANGEDBY],
	[LASTCHANGEDON],
	[ROWVERSION]
)
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
VALUES
(
	@CASCHEDULEID,
	@NAME,
	@DESCRIPTION,
	@STARTDATE,
	@ENDDATE,
	@IGNOREYEAR,
	@LASTCHANGEDBY,
	@LASTCHANGEDON,
	@ROWVERSION
)
SELECT * FROM @OUTPUTTABLE