CREATE PROCEDURE [dbo].[USP_CAFEEADJUSTABLECALC_UPDATE]
(
	@CAFEEADJUSTABLECALCID CHAR(36),
	@CAFEEID CHAR(36),
	@LOWERLIMIT DECIMAL(20,4),
	@UPPERLIMIT DECIMAL(20,4),
	@UNLIMITED BIT,
	@AMOUNT MONEY,
	@ADDITIONALAMOUNT MONEY,
	@ADDITIONALUNIT DECIMAL(20,4),
	@OVER DECIMAL(20,4),
	@CAFEESETUPID CHAR(36)
)
AS

UPDATE [dbo].[CAFEEADJUSTABLECALC] SET
	[CAFEEID] = @CAFEEID,
	[LOWERLIMIT] = @LOWERLIMIT,
	[UPPERLIMIT] = @UPPERLIMIT,
	[UNLIMITED] = @UNLIMITED,
	[AMOUNT] = @AMOUNT,
	[ADDITIONALAMOUNT] = @ADDITIONALAMOUNT,
	[ADDITIONALUNIT] = @ADDITIONALUNIT,
	[OVER] = @OVER,
	[CAFEESETUPID] = @CAFEESETUPID

WHERE
	[CAFEEADJUSTABLECALCID] = @CAFEEADJUSTABLECALCID