CREATE PROCEDURE [dbo].[USP_CAFEETEMPLATEDISCOUNT_DELETE_BY_FEETEMPLATEID]
(
@CAFEETEMPLATEID CHAR(36)
)
AS

DECLARE @EXPRESSIONIDS RECORDIDS
DECLARE @CONDITIONGROUPIDS RECORDIDS

INSERT	INTO @EXPRESSIONIDS(RECORDID)
SELECT	[dbo].[CAFEETEMPLATEDISCOUNT].[CAEXPRESSIONID] FROM [dbo].[CAFEETEMPLATEDISCOUNT]
WHERE	[dbo].[CAFEETEMPLATEDISCOUNT].[CAFEETEMPLATEID] = @CAFEETEMPLATEID   

INSERT	INTO @CONDITIONGROUPIDS(RECORDID)
SELECT	[dbo].[CAFEETEMPLATEDISCOUNT].[CACONDITIONGROUPID] FROM [dbo].[CAFEETEMPLATEDISCOUNT]
WHERE	[dbo].[CAFEETEMPLATEDISCOUNT].[CAFEETEMPLATEID] = @CAFEETEMPLATEID

DELETE FROM [dbo].[CAFEETEMPLATEDISCOUNT]
WHERE
	[CAFEETEMPLATEID] = @CAFEETEMPLATEID  

EXEC [dbo].[USP_CAEXPRESSION_DELETE_BY_IDS] @EXPRESSIONIDS
EXEC [dbo].[USP_CACONDITIONGROUP_DELETE_BY_IDS] @CONDITIONGROUPIDS