CREATE PROCEDURE [dbo].[USP_CAPRPTSETTINGS_UPDATE]
(
	@CAPRPTSETTINGSID CHAR(36),
	@NAME NVARCHAR(100),
	@MODULETYPE CHAR(36),
	@MODULECLASS CHAR(36),
	@RPTREPORTID CHAR(36),
	@CAPMODULESID INT,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS

DECLARE @OUTPUTTABLE AS TABLE([ROWVERSION]  INT)
UPDATE	[dbo].[CAPRPTSETTINGS]
SET		[NAME] = @NAME,
		[MODULETYPE] = @MODULETYPE,
		[MODULECLASS] = @MODULECLASS,
		[RPTREPORTID] = @RPTREPORTID,
		[CAPMODULESID] = @CAPMODULESID,
		[LASTCHANGEDBY] = @LASTCHANGEDBY,
		[LASTCHANGEDON] = @LASTCHANGEDON,
		[ROWVERSION] = @ROWVERSION + 1
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE
	[CAPRPTSETTINGSID] = @CAPRPTSETTINGSID AND
	[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE