CREATE PROCEDURE [dbo].[USP_CAPRPTSETTINGS_INSERT]
(
	@CAPRPTSETTINGSID CHAR(36),
	@NAME NVARCHAR(100),
	@MODULETYPE CHAR(36),
	@MODULECLASS CHAR(36),
	@RPTREPORTID CHAR(36),
	@CAPMODULESID INT,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE AS TABLE([ROWVERSION]  INT)
INSERT INTO [dbo].[CAPRPTSETTINGS](
	[CAPRPTSETTINGSID],
	[NAME],
	[MODULETYPE],
	[MODULECLASS],
	[RPTREPORTID],
	[CAPMODULESID],
	[LASTCHANGEDBY],
	[LASTCHANGEDON],
	[ROWVERSION]
)
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
VALUES
(
	@CAPRPTSETTINGSID,
	@NAME,
	@MODULETYPE,
	@MODULECLASS,
	@RPTREPORTID,
	@CAPMODULESID,
	@LASTCHANGEDBY,
	@LASTCHANGEDON,
	@ROWVERSION
)
SELECT * FROM @OUTPUTTABLE