CREATE PROCEDURE [dbo].[USP_CMCODECASEHOLDTYPECONTACTTYPEREF_DELETE]
(
@CMCODECASEHOLDTYPECONTACTTYPEID CHAR(36)
)
AS
BEGIN

DELETE FROM [dbo].[CMCODECASEHOLDTYPECONTACTTYPEREF]
WHERE
	[CMCODECASEHOLDTYPECONTACTTYPEID] = @CMCODECASEHOLDTYPECONTACTTYPEID

END