CREATE PROCEDURE [dbo].[USP_CAFEETEMPLATECHILDXREF_INSERT]
(
	@CAFEETEMPLATECHILDXREFID CHAR(36),
	@PARENTFEETEMPLATEID CHAR(36),
	@CHILDFEETEMPLATEID CHAR(36),
	@CHILDORDER INT
)
AS

INSERT INTO [dbo].[CAFEETEMPLATECHILDXREF](
	[CAFEETEMPLATECHILDXREFID],
	[PARENTFEETEMPLATEID],
	[CHILDFEETEMPLATEID],
	[CHILDORDER],
	[CACONDITIONGROUPID]
)

VALUES
(
	@CAFEETEMPLATECHILDXREFID,
	@PARENTFEETEMPLATEID,
	@CHILDFEETEMPLATEID,
	@CHILDORDER,	
	NULL
)