CREATE PROCEDURE [dbo].[USP_CACHARGECODE_INSERT]
(
	@CACHARGECODEID CHAR(36),
	@CHARGECODE NVARCHAR(100),
	@DESCRIPTION NVARCHAR(MAX),
	@CAFINANCIALINTEGRATIONSETUPID CHAR(36)
)
AS

INSERT INTO [dbo].[CACHARGECODE](
	[CACHARGECODEID],
	[CHARGECODE],
	[DESCRIPTION],
	[CAFINANCIALINTEGRATIONSETUPID]
)

VALUES
(
	@CACHARGECODEID,
	@CHARGECODE,
	@DESCRIPTION,
	@CAFINANCIALINTEGRATIONSETUPID
)