CREATE PROCEDURE [dbo].[USP_CUSTOMFIELDTEMPLATEITEM_DELETE_BYPARENTID]
(
	@PARENTID CHAR(36)
)
AS

DELETE FROM [dbo].[CUSTOMFIELDTEMPLATEITEM]
WHERE
[dbo].[CUSTOMFIELDTEMPLATEITEM].[FKGCUSTOMFIELDTEMPLATE] = @PARENTID