CREATE PROCEDURE [dbo].[USP_CACONDITIONGROUP_INSERT]
(
	@CACONDITIONGROUPID CHAR(36),
	@PARENTCONDITIONGROUPID CHAR(36),
	@ISORGROUP BIT
)
AS

INSERT INTO [dbo].[CACONDITIONGROUP](
	[CACONDITIONGROUPID],
	[PARENTCONDITIONGROUPID],
	[ISORGROUP]
)

VALUES
(
	@CACONDITIONGROUPID,
	@PARENTCONDITIONGROUPID,
	@ISORGROUP
)