CREATE PROCEDURE [dbo].[USP_CUSTOMFIELDWORKSHEET_DELETE_BYPARENTID]
(
	@RECORDIDs RecordIDs READONLY
)
AS
DELETE FROM [dbo].[CUSTOMFIELDWORKSHEET]
WHERE
	[dbo].[CUSTOMFIELDWORKSHEET].[FKGCUSTOMFIELD] IN (SELECT RECORDID FROM @RECORDIDs)