CREATE PROCEDURE [dbo].[USP_CUSTOMFIELD_DELETEBY_CUSTOMFIELDTABLEID]  
(  
 @CUSTOMFIELDTABLEID CHAR(36)
)  
AS  
DELETE [dbo].[CUSTOMFIELD]  
  FROM [dbo].[CUSTOMFIELD] INNER JOIN [dbo].[CUSTOMFIELDTABLECOLUMNREF]  
  ON [dbo].[CUSTOMFIELD].[FKCUSTOMFIELDTABLECOLREF] = [dbo].[CUSTOMFIELDTABLECOLUMNREF].[CUSTOMFIELDTABLECOLUMNREFID]  
 WHERE  
  [dbo].[CUSTOMFIELD].[FKCUSTOMFIELDTABLECOLREF] IS NOT NULL   
  AND [dbo].[CUSTOMFIELDTABLECOLUMNREF].[CUSTOMFIELDTABLEID]=@CUSTOMFIELDTABLEID