CREATE PROCEDURE [dbo].[USP_CMCITATIONSTATUS_INSERT]
(
	@CMCITATIONSTATUSID CHAR(36),
	@NAME NVARCHAR(50),
	@DESCRIPTION NVARCHAR(255),
	@ISSUEDFLAG BIT,
	@CLOSEDFLAG BIT,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
INSERT INTO [dbo].[CMCITATIONSTATUS](
	[CMCITATIONSTATUSID],
	[NAME],
	[DESCRIPTION],
	[ISSUEDFLAG],
	[CLOSEDFLAG],
	[LASTCHANGEDBY],
	[LASTCHANGEDON],
	[ROWVERSION]
)
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
VALUES
(
	@CMCITATIONSTATUSID,
	@NAME,
	@DESCRIPTION,
	@ISSUEDFLAG,
	@CLOSEDFLAG,
	@LASTCHANGEDBY,
	@LASTCHANGEDON,
	@ROWVERSION
)
SELECT * FROM @OUTPUTTABLE