CREATE PROCEDURE [dbo].[USP_CMCODECASEHOLDTYPECONTACTTYPEREF_UPDATE]
(
	@CMCODECASEHOLDTYPECONTACTTYPEID	CHAR(36),
	@CMCODECASEHOLDTYPEID	CHAR(36),
	@CMCODECASECONTACTTYPEID	CHAR(36),
	@ACTIVE BIT
)
AS
BEGIN

UPDATE [dbo].[CMCODECASEHOLDTYPECONTACTTYPEREF] SET
	[CMCODECASEHOLDTYPEID] = @CMCODECASEHOLDTYPEID,
	[CMCODECASECONTACTTYPEID] = @CMCODECASECONTACTTYPEID,
	[ACTIVE] = @ACTIVE
WHERE
	[CMCODECASEHOLDTYPECONTACTTYPEID] = @CMCODECASEHOLDTYPECONTACTTYPEID  

END