CREATE PROCEDURE [dbo].[USP_CUSTOMFIELDWORKSHEETITEM_INSERT]
(
	@GCUSTOMFIELDWORKSHEETITEM CHAR(36),
	@FKGCUSTOMFIELDWORKSHEET CHAR(36),
	@SVALUE VARCHAR(50),
	@IORDER INT
)
AS

INSERT INTO [dbo].[CUSTOMFIELDWORKSHEETITEM](
	[GCUSTOMFIELDWORKSHEETITEM],
	[FKGCUSTOMFIELDWORKSHEET],
	[SVALUE],
	[IORDER]
)

VALUES
(
	@GCUSTOMFIELDWORKSHEETITEM,
	@FKGCUSTOMFIELDWORKSHEET,
	@SVALUE,
	@IORDER
)