CREATE PROCEDURE [dbo].[USP_CATEMPLATEFEEDISCOUNTXREF_INSERT]
(
	@CATEMPLATEFEEDISCOUNTXREFID CHAR(36),
	@CAFEETEMPLATEFEEID CHAR(36),
	@CAFEETEMPLATEDISCOUNTID CHAR(36),
	@SORTORDER INT
)
AS

INSERT INTO [dbo].[CATEMPLATEFEEDISCOUNTXREF](
	[CATEMPLATEFEEDISCOUNTXREFID],
	[CAFEETEMPLATEFEEID],
	[CAFEETEMPLATEDISCOUNTID],
	[SORTORDER]
)

VALUES
(
	@CATEMPLATEFEEDISCOUNTXREFID,
	@CAFEETEMPLATEFEEID,
	@CAFEETEMPLATEDISCOUNTID,
	@SORTORDER
)