CREATE PROCEDURE [dbo].[USP_CMCITATIONSTATUS_UPDATE]
(
	@CMCITATIONSTATUSID CHAR(36),
	@NAME NVARCHAR(50),
	@DESCRIPTION NVARCHAR(255),
	@ISSUEDFLAG BIT,
	@CLOSEDFLAG BIT,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
UPDATE [dbo].[CMCITATIONSTATUS] SET
	[NAME] = @NAME,
	[DESCRIPTION] = @DESCRIPTION,
	[ISSUEDFLAG] = @ISSUEDFLAG,
	[CLOSEDFLAG] = @CLOSEDFLAG,
	[LASTCHANGEDBY] = @LASTCHANGEDBY,
	[LASTCHANGEDON] = @LASTCHANGEDON,
	[ROWVERSION] = @ROWVERSION + 1
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE
	[CMCITATIONSTATUSID] = @CMCITATIONSTATUSID AND 
	[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE