CREATE PROCEDURE [dbo].[USP_CONDITIONLIBRARY_UPDATE]
(
	@CONDITIONLIBRARYID CHAR(36),
	@CONDITIONCATEGORYID CHAR(36),
	@NAME NVARCHAR(255),
	@DESCRIPTION NVARCHAR(MAX),
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
UPDATE [dbo].[CONDITIONLIBRARY] SET
	[CONDITIONCATEGORYID] = @CONDITIONCATEGORYID,
	[NAME] = @NAME,
	[DESCRIPTION] = @DESCRIPTION,
	[LASTCHANGEDBY] = @LASTCHANGEDBY,
	[LASTCHANGEDON] = @LASTCHANGEDON,
	[ROWVERSION] = @ROWVERSION + 1
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE
	[CONDITIONLIBRARYID] = @CONDITIONLIBRARYID AND 
	[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE