CREATE PROCEDURE [dbo].[USP_COMAPPEDVALUECERTTYPE_DELETE]
(
	@COMAPPEDVALUECERTTYPEID CHAR(36),
	@ROWVERSION INT
)
AS
DELETE FROM [dbo].[COMAPPEDVALUECERTTYPE]
WHERE
	[COMAPPEDVALUECERTTYPEID] = @COMAPPEDVALUECERTTYPEID AND 
	[ROWVERSION]= @ROWVERSION