CREATE PROCEDURE [dbo].[USP_CUSTOMFIELDTEMPLATEITEM_INSERT]
(
	@GCUSTOMFIELDTEMPLATEITEM CHAR(36),
	@FKGCUSTOMFIELDTEMPLATE CHAR(36),
	@SVALUE VARCHAR(50),
	@IORDER INT,
	@ISRETIRE BIT
)
AS

INSERT INTO [dbo].[CUSTOMFIELDTEMPLATEITEM](
	[GCUSTOMFIELDTEMPLATEITEM],
	[FKGCUSTOMFIELDTEMPLATE],
	[SVALUE],
	[IORDER],
	[ISRETIRE]
)

VALUES
(
	@GCUSTOMFIELDTEMPLATEITEM,
	@FKGCUSTOMFIELDTEMPLATE,
	@SVALUE,
	@IORDER,
	@ISRETIRE
)