CREATE PROCEDURE [dbo].[USP_CAFEETEMPLATE_SELECT_LOOKUP]
(
	@CAENTITYID INT
)
AS
SET NOCOUNT ON;
SELECT 
	[dbo].[CAFEETEMPLATE].[CAFEETEMPLATEID],
	[dbo].[CAFEETEMPLATE].[CAFEETEMPLATENAME]
FROM [dbo].[CAFEETEMPLATE]
WHERE [dbo].[CAFEETEMPLATE].[CAENTITYID] = @CAENTITYID
ORDER BY [dbo].[CAFEETEMPLATE].[CAFEETEMPLATENAME]