CREATE PROCEDURE [dbo].[USP_CAFEECONSTANT_INSERT]
(
	@CAFEECONSTANTID CHAR(36),
	@NAME NVARCHAR(50),
	@DESCRIPTION NVARCHAR(MAX),
	@VALUETYPEID INT,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
INSERT INTO [dbo].[CAFEECONSTANT](
	[CAFEECONSTANTID],
	[NAME],
	[DESCRIPTION],
	[VALUETYPEID],
	[LASTCHANGEDBY],
	[LASTCHANGEDON],
	[ROWVERSION]
)
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
VALUES
(
	@CAFEECONSTANTID,
	@NAME,
	@DESCRIPTION,
	@VALUETYPEID,
	@LASTCHANGEDBY,
	@LASTCHANGEDON,
	@ROWVERSION
)
SELECT * FROM @OUTPUTTABLE