CREATE PROCEDURE [dbo].[USP_CADISCOUNTSETUP_INSERT]
(
	@CADISCOUNTSETUPID CHAR(36),
	@CADISCOUNTID CHAR(36),
	@CASCHEDULEID CHAR(36),
	@AMOUNT MONEY,
	@MINIMUMAMOUNT MONEY,
	@MAXIMUMAMOUNT MONEY,
	@COMPUTATIONVALUE DECIMAL(20,4),
	@COMPUTATIONVALUENAME NVARCHAR(50),
	@ROUNDINGTYPEID INT,
	@ROUNDINGVALUE DECIMAL(20,4),
	@ROWVERSION INT,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
INSERT INTO [dbo].[CADISCOUNTSETUP](
	[CADISCOUNTSETUPID],
	[CADISCOUNTID],
	[CASCHEDULEID],
	[AMOUNT],
	[MINIMUMAMOUNT],
	[MAXIMUMAMOUNT],
	[COMPUTATIONVALUE],
	[COMPUTATIONVALUENAME],
	[ROUNDINGTYPEID],
	[ROUNDINGVALUE],
	[ROWVERSION],
	[LASTCHANGEDBY],
	[LASTCHANGEDON]
)
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
VALUES
(
	@CADISCOUNTSETUPID,
	@CADISCOUNTID,
	@CASCHEDULEID,
	@AMOUNT,
	@MINIMUMAMOUNT,
	@MAXIMUMAMOUNT,
	@COMPUTATIONVALUE,
	@COMPUTATIONVALUENAME,
	@ROUNDINGTYPEID,
	@ROUNDINGVALUE,
	@ROWVERSION,
	@LASTCHANGEDBY,
	@LASTCHANGEDON
)
SELECT * FROM @OUTPUTTABLE