CREATE PROCEDURE [dbo].[USP_CADISCOUNT_DELETE]
(
	@CADISCOUNTID CHAR(36),
	@ROWVERSION INT
)
AS

SET NOCOUNT ON;

EXEC [dbo].[USP_CADISCOUNTADJUSTABLECALC_DELETE_BYPARENTID] @CADISCOUNTID
EXEC [dbo].[USP_CADISCOUNTSETUP_DELETE_BYPARENTID] @CADISCOUNTID
EXEC [dbo].[USP_CAMODULEDISCOUNTXREF_DELETE_BYPARENTID] @CADISCOUNTID

SET NOCOUNT OFF;

DELETE FROM [dbo].[CADISCOUNT]
WHERE
	[CADISCOUNTID] = @CADISCOUNTID AND 
	[ROWVERSION]= @ROWVERSION