CREATE PROCEDURE [dbo].[USP_CATEMPLATEFEEDISCOUNTXREF_DELETE]
(
@CATEMPLATEFEEDISCOUNTXREFID CHAR(36)
)
AS
DELETE FROM [dbo].[CATEMPLATEFEEDISCOUNTXREF]
WHERE
	[CATEMPLATEFEEDISCOUNTXREFID] = @CATEMPLATEFEEDISCOUNTXREFID