CREATE PROCEDURE [dbo].[USP_CADISCOUNTADJUSTABLECALC_DELETE_BYPARENTID]
(
	@CADISCOUNTID CHAR(36),
	@CADISCOUNTSETUPID CHAR(36) = NULL
)
AS
BEGIN
	DELETE FROM [dbo].[CADISCOUNTADJUSTABLECALC] 
	WHERE  [dbo].[CADISCOUNTADJUSTABLECALC].[CADISCOUNTID] =@CADISCOUNTID AND (@CADISCOUNTSETUPID IS NULL OR [CADISCOUNTSETUPID] = @CADISCOUNTSETUPID)
END