CREATE PROCEDURE [dbo].[USP_CAFEETEMPLATECHILDXREF_UPDATE]
(
	@CAFEETEMPLATECHILDXREFID CHAR(36),
	@PARENTFEETEMPLATEID CHAR(36),
	@CHILDFEETEMPLATEID CHAR(36),
	@CHILDORDER INT
)
AS

UPDATE [dbo].[CAFEETEMPLATECHILDXREF] SET
	[PARENTFEETEMPLATEID] = @PARENTFEETEMPLATEID,
	[CHILDFEETEMPLATEID] = @CHILDFEETEMPLATEID,
	[CHILDORDER] = @CHILDORDER
WHERE
	[CAFEETEMPLATECHILDXREFID] = @CAFEETEMPLATECHILDXREFID