CREATE PROCEDURE [dbo].[USP_CAFEETIMETRACKINGTYPEXREF_DELETE_BYPARENTID]
(
	@PARENTID CHAR(36)
)
AS
BEGIN
	DELETE FROM [dbo].[CAFEETIMETRACKINGTYPEXREF]
	WHERE [dbo].[CAFEETIMETRACKINGTYPEXREF].[CAFEEID] = @PARENTID 
END