CREATE PROCEDURE [dbo].[USP_CMCASETYPE_DELETE]
(
	@CMCASETYPEID CHAR(36),
	@ROWVERSION INT
)
AS
BEGIN

SET NOCOUNT ON;

EXEC [dbo].[USP_CMCODECASECONTACTTYPEREF_DELETE_BYPARENTID] @CMCASETYPEID
EXEC [dbo].[USP_CMCODEALLOWEDACTIVITY_DELETE_BYPARENTID] @CMCASETYPEID
EXEC [dbo].[USP_CMCODECASEHOLDTYPEREF_DELETE_BYPARENTID] @CMCASETYPEID

SET NOCOUNT OFF;

DELETE FROM [dbo].[CMCASETYPE]
WHERE [CMCASETYPEID] = @CMCASETYPEID AND 	[ROWVERSION]= @ROWVERSION

END