CREATE PROCEDURE [dbo].[USP_CACONDITIONGROUP_UPDATE]
(
	@CACONDITIONGROUPID CHAR(36),
	@PARENTCONDITIONGROUPID CHAR(36),
	@ISORGROUP BIT
)
AS

UPDATE [dbo].[CACONDITIONGROUP] SET
	[PARENTCONDITIONGROUPID] = @PARENTCONDITIONGROUPID,
	[ISORGROUP] = @ISORGROUP

WHERE
	[CACONDITIONGROUPID] = @CACONDITIONGROUPID