CREATE PROCEDURE [dbo].[USP_CUSTOMFIELDOBJECT_DELETE]
(
	@GCUSTOMFIELD CHAR(36)
)
AS
DECLARE @DELETED_CUSTOM_FIELDS AS RecordIDs
INSERT INTO @DELETED_CUSTOM_FIELDS (RECORDID) VALUES (@GCUSTOMFIELD)

EXEC [dbo].[USP_CUSTOMFIELDPICKLISTITEM_DELETE_BYPARENTID] @DELETED_CUSTOM_FIELDS
EXEC [dbo].[USP_CUSTOMFIELDPICKLIST_DELETE_BYPARENTID] @DELETED_CUSTOM_FIELDS
EXEC [dbo].[USP_CUSTOMFIELDWORKSHEETITEM_DELETE_BYPARENTID] @DELETED_CUSTOM_FIELDS
EXEC [dbo].[USP_CUSTOMFIELDWORKSHEET_DELETE_BYPARENTID] @DELETED_CUSTOM_FIELDS

DELETE FROM [dbo].[CUSTOMFIELDOBJECT]
WHERE
	[GCUSTOMFIELD] = @GCUSTOMFIELD