CREATE PROCEDURE [dbo].[USP_CAFEETEMPLATE_UPDATE]
	@CAFEETEMPLATEID AS CHAR(36),
	@CAFEETEMPLATENAME AS NVARCHAR(60),
	@CAENTITYID AS INT,
	@CAFEETEMPLATEDESCRIPTION AS NVARCHAR(MAX),
	@ROWVERSION AS INT,
	@LASTCHANGEDON AS DATETIME,
	@LASTCHANGEDBY AS CHAR(36)
AS
BEGIN
	
	DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
	
	UPDATE [dbo].[CAFEETEMPLATE] 
		SET [CAENTITYID] = @CAENTITYID, 
			[CAFEETEMPLATENAME] = @CAFEETEMPLATENAME, 
			[CAFEETEMPLATEDESCRIPTION] = @CAFEETEMPLATEDESCRIPTION, 
			[ROWVERSION] = @ROWVERSION + 1, 
			[LASTCHANGEDON] = @LASTCHANGEDON, 
			[LASTCHANGEDBY] = @LASTCHANGEDBY
	OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
	WHERE
		[dbo].[CAFEETEMPLATE].[CAFEETEMPLATEID] = @CAFEETEMPLATEID AND 
		[ROWVERSION]= @ROWVERSION
			
	SELECT * FROM @OUTPUTTABLE

END