CREATE PROCEDURE [dbo].[USP_COLICENSECERTIFICATIONTYPE_DELETE]
(
	@COSIMPLELICCERTTYPEID CHAR(36),
	@ROWVERSION INT
)
AS
BEGIN
SET NOCOUNT ON

EXEC [USP_COLICTYPECLASSREF_DELETE_BYPARENTID] @COSIMPLELICCERTTYPEID
EXEC [USP_COLICTYPEGROUPREF_DELETE_BYPARENTID] @COSIMPLELICCERTTYPEID

SET NOCOUNT OFF
DELETE FROM [dbo].[COLICENSECERTIFICATIONTYPE]
WHERE
	[COSIMPLELICCERTTYPEID] = @COSIMPLELICCERTTYPEID AND 
	[ROWVERSION]= @ROWVERSION

END