CREATE PROCEDURE [dbo].[USP_CMCODECASESTATUS_UPDATE]
(
	@CMCODECASESTATUSID CHAR(36),
	@NAME VARCHAR(50),
	@DESCRIPTION NVARCHAR(MAX),
	@SUCCESSFLAG BIT,
	@FAILUREFLAG BIT,
	@CANCELLEDFLAG BIT,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
UPDATE [dbo].[CMCODECASESTATUS] SET	
	[NAME] = @NAME,
	[DESCRIPTION] = @DESCRIPTION,
	[SUCCESSFLAG] = @SUCCESSFLAG,
	[FAILUREFLAG] = @FAILUREFLAG,
	[CANCELLEDFLAG] = @CANCELLEDFLAG,
	[LASTCHANGEDBY] = @LASTCHANGEDBY,
	[LASTCHANGEDON] = @LASTCHANGEDON,
	[ROWVERSION] = @ROWVERSION + 1
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE
	[CMCODECASESTATUSID] = @CMCODECASESTATUSID AND 
	[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE