CREATE TABLE [dbo].[OBJECTCACHESTAGE] (
    [OBJECTCACHEID] CHAR (36)       NOT NULL,
    [ROOTCLASSNAME] NVARCHAR (500)  NOT NULL,
    [ROLEID]        CHAR (36)       NULL,
    [OBJECTDATA]    VARBINARY (MAX) NOT NULL,
    [CREATEDATE]    DATETIME        NOT NULL,
    [CACHEVERSION]  NVARCHAR (50)   NULL,
    CONSTRAINT [PK_OBJECTCACHESTAGE] PRIMARY KEY CLUSTERED ([OBJECTCACHEID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_OBJECTCACHESTAGE_Roles] FOREIGN KEY ([ROLEID]) REFERENCES [dbo].[ROLES] ([SROLEGUID])
);

