CREATE TABLE [dbo].[OBJECTCACHESTATUS] (
    [OBJECTCACHESTATUSID]   CHAR (36) DEFAULT (newid()) NOT NULL,
    [CACHEWILLCLEAR]        BIT       NOT NULL,
    [CACHECOMPLETEDAT]      DATETIME  NULL,
    [REMAININGCACHEREBUILD] INT       DEFAULT ((0)) NULL,
    CONSTRAINT [PK_OBJECTCACHESTATUS] PRIMARY KEY CLUSTERED ([OBJECTCACHESTATUSID] ASC) WITH (FILLFACTOR = 80)
);

