CREATE TABLE [dbo].[CACHECLEARAREA] (
    [CACHECLEARAREAID] INT           NOT NULL,
    [AREANAME]         NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_CACHECLEARAREA] PRIMARY KEY CLUSTERED ([CACHECLEARAREAID] ASC)
);

