CREATE TABLE [dbo].[CACONDITION] (
    [CACONDITIONID]       CHAR (36)      NOT NULL,
    [CACONDITIONGROUPID]  CHAR (36)      NOT NULL,
    [OPERANDTYPEID]       INT            NOT NULL,
    [OPERANDVALUE]        NVARCHAR (100) NULL,
    [OPERANDFRIENDLYNAME] NVARCHAR (MAX) NOT NULL,
    [OPERANDDATATYPEID]   INT            NOT NULL,
    [OPERATORID]          INT            NOT NULL,
    [COMPAREEXPRESSIONID] CHAR (36)      NULL,
    [CLASSNAME]           NVARCHAR (MAX) NULL,
    [CUSTOMFIELDTABLE]    NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_CACondition] PRIMARY KEY CLUSTERED ([CACONDITIONID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_CACondition_CompareExp] FOREIGN KEY ([COMPAREEXPRESSIONID]) REFERENCES [dbo].[CAEXPRESSION] ([CAEXPRESSIONID]),
    CONSTRAINT [FK_CACondition_Group] FOREIGN KEY ([CACONDITIONGROUPID]) REFERENCES [dbo].[CACONDITIONGROUP] ([CACONDITIONGROUPID])
);


GO
CREATE NONCLUSTERED INDEX [IX_CACONDITION_CACONDITIONGROUPID_OPERANDTYPEID_INCLUDES]
    ON [dbo].[CACONDITION]([CACONDITIONGROUPID] ASC, [OPERANDTYPEID] ASC)
    INCLUDE([COMPAREEXPRESSIONID], [OPERANDVALUE], [CLASSNAME], [CUSTOMFIELDTABLE]);


GO
CREATE NONCLUSTERED INDEX [IX_CACONDITION_COMPAREEXPRESSIONID]
    ON [dbo].[CACONDITION]([COMPAREEXPRESSIONID] ASC);


GO

CREATE TRIGGER [dbo].[TG_CACONDITION_UPDATE] ON  [dbo].[CACONDITION] 
   AFTER UPDATE
AS 
BEGIN	
	SET NOCOUNT ON;	
	-- DECLARATION OF TABLE TYPE VARIABLE 
	DECLARE @CONDITIONGROUPIDS [RecordIDs]
	DECLARE @PARENTCONDITIONGROUP AS TABLE(TOPPARENTCONDITIONGROUPID CHAR(36),CONDITIONGROUPID CHAR(36))

	-- GET INSERTED CACONDITIONGROUPID 
	INSERT INTO @CONDITIONGROUPIDS
	SELECT [inserted].[CACONDITIONGROUPID] FROM [inserted]

	-- GET TOPPARENTID FOR CONDITION GROUP
	INSERT INTO @PARENTCONDITIONGROUP(TOPPARENTCONDITIONGROUPID,CONDITIONGROUPID)
	SELECT * FROM  [dbo].[GETTOPPARENTCONDITIONGROUPIDS](@CONDITIONGROUPIDS)
	
	INSERT INTO [HISTORYSYSTEMSETUP]
    (	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	-------------------------------------------[CAFEETEMPLATEFEE]--------------------------------
	SELECT 
			[CAFEETEMPLATE].[CAFEETEMPLATEID],
			[CAFEETEMPLATE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEETEMPLATE].[LASTCHANGEDBY],
			'Operand Type',			
			(SELECT [dbo].[GETENUMNAMEBYENUTYPEANDVALUE](1,[deleted].[OPERANDTYPEID])),
			(SELECT [dbo].[GETENUMNAMEBYENUTYPEANDVALUE](1,[inserted].[OPERANDTYPEID])),
			'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee/Child Template (' + [CAFEETEMPLATEFEE].[FEENAME] +') Condition Group, Condition ('+[inserted].[OPERANDFRIENDLYNAME]+')',
			'CCA2295B-072A-494B-9C11-91424F59BC16',
			2,
			0,
			[CAFEETEMPLATE].[CAFEETEMPLATENAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CACONDITIONID] = [inserted].[CACONDITIONID]
			INNER JOIN @PARENTCONDITIONGROUP AS [PARENTCONDITIONGROUP] ON [PARENTCONDITIONGROUP].[CONDITIONGROUPID] = [inserted].[CACONDITIONGROUPID]
			INNER JOIN [dbo].[CAFEETEMPLATEFEE] ON [PARENTCONDITIONGROUP].[TOPPARENTCONDITIONGROUPID] = [CAFEETEMPLATEFEE].[CACONDITIONGROUPID] 
			INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEID]	
	WHERE	[deleted].[OPERANDTYPEID] <> [inserted].[OPERANDTYPEID]

	UNION ALL
	SELECT 
			[CAFEETEMPLATE].[CAFEETEMPLATEID],
			[CAFEETEMPLATE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEETEMPLATE].[LASTCHANGEDBY],
			'Operand Value',			
			ISNULL( [deleted].[OPERANDVALUE],'[none]'),
			ISNULL([inserted].[OPERANDVALUE],'[none]'),
			'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee/Child Template (' + [CAFEETEMPLATEFEE].[FEENAME] +') Condition Group, Condition ('+[inserted].[OPERANDFRIENDLYNAME]+')',
			'CCA2295B-072A-494B-9C11-91424F59BC16',
			2,
			0,
			[CAFEETEMPLATE].[CAFEETEMPLATENAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CACONDITIONID] = [inserted].[CACONDITIONID]
			INNER JOIN @PARENTCONDITIONGROUP AS [PARENTCONDITIONGROUP] ON [PARENTCONDITIONGROUP].[CONDITIONGROUPID] = [inserted].[CACONDITIONGROUPID]
			INNER JOIN [dbo].[CAFEETEMPLATEFEE] ON [PARENTCONDITIONGROUP].[TOPPARENTCONDITIONGROUPID] = [CAFEETEMPLATEFEE].[CACONDITIONGROUPID] 
			INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEID]	
	WHERE	ISNULL([deleted].[OPERANDVALUE],'') <> ISNULL([inserted].[OPERANDVALUE],'')
	
	UNION ALL	
	SELECT 
			[CAFEETEMPLATE].[CAFEETEMPLATEID],
			[CAFEETEMPLATE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEETEMPLATE].[LASTCHANGEDBY],
			'Operand Friendly Name',			
			[deleted].[OPERANDFRIENDLYNAME],
			[inserted].[OPERANDFRIENDLYNAME],
			'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee/Child Template (' + [CAFEETEMPLATEFEE].[FEENAME] +') Condition Group, Condition ('+[inserted].[OPERANDFRIENDLYNAME]+')',
			'CCA2295B-072A-494B-9C11-91424F59BC16',
			2,
			0,
			[CAFEETEMPLATE].[CAFEETEMPLATENAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CACONDITIONID] = [inserted].[CACONDITIONID]
			INNER JOIN @PARENTCONDITIONGROUP AS [PARENTCONDITIONGROUP] ON [PARENTCONDITIONGROUP].[CONDITIONGROUPID] = [inserted].[CACONDITIONGROUPID]
			INNER JOIN [dbo].[CAFEETEMPLATEFEE] ON [PARENTCONDITIONGROUP].[TOPPARENTCONDITIONGROUPID] = [CAFEETEMPLATEFEE].[CACONDITIONGROUPID] 
			INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEID]	
	WHERE	[deleted].[OPERANDFRIENDLYNAME] <> [inserted].[OPERANDFRIENDLYNAME]
	
	UNION ALL	
	SELECT 
			[CAFEETEMPLATE].[CAFEETEMPLATEID],
			[CAFEETEMPLATE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEETEMPLATE].[LASTCHANGEDBY],
			'Operand Data Type',					
			(SELECT [dbo].[GETENUMNAMEBYENUTYPEANDVALUE](2,[deleted].[OPERANDDATATYPEID])),
			(SELECT [dbo].[GETENUMNAMEBYENUTYPEANDVALUE](2,[inserted].[OPERANDDATATYPEID])),
			'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee/Child Template (' + [CAFEETEMPLATEFEE].[FEENAME] +') Condition Group, Condition ('+[inserted].[OPERANDFRIENDLYNAME]+')',
			'CCA2295B-072A-494B-9C11-91424F59BC16',
			2,
			0,
			[CAFEETEMPLATE].[CAFEETEMPLATENAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CACONDITIONID] = [inserted].[CACONDITIONID]
			INNER JOIN @PARENTCONDITIONGROUP AS [PARENTCONDITIONGROUP] ON [PARENTCONDITIONGROUP].[CONDITIONGROUPID] = [inserted].[CACONDITIONGROUPID]
			INNER JOIN [dbo].[CAFEETEMPLATEFEE] ON [PARENTCONDITIONGROUP].[TOPPARENTCONDITIONGROUPID] = [CAFEETEMPLATEFEE].[CACONDITIONGROUPID] 
			INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEID]	
	WHERE	[deleted].[OPERANDDATATYPEID] <> [inserted].[OPERANDDATATYPEID]

	UNION ALL	
	SELECT 
			[CAFEETEMPLATE].[CAFEETEMPLATEID],
			[CAFEETEMPLATE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEETEMPLATE].[LASTCHANGEDBY],
			'Operator Type',			
			(SELECT [dbo].[GETENUMNAMEBYENUTYPEANDVALUE](3,[deleted].[OPERATORID])),
			(SELECT [dbo].[GETENUMNAMEBYENUTYPEANDVALUE](3,[inserted].[OPERATORID])),
			'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee/Child Template (' + [CAFEETEMPLATEFEE].[FEENAME] +') Condition Group, Condition ('+[inserted].[OPERANDFRIENDLYNAME]+')',
			'CCA2295B-072A-494B-9C11-91424F59BC16',
			2,
			0,
			[CAFEETEMPLATE].[CAFEETEMPLATENAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CACONDITIONID] = [inserted].[CACONDITIONID]
			INNER JOIN @PARENTCONDITIONGROUP AS [PARENTCONDITIONGROUP] ON [PARENTCONDITIONGROUP].[CONDITIONGROUPID] = [inserted].[CACONDITIONGROUPID]
			INNER JOIN [dbo].[CAFEETEMPLATEFEE] ON [PARENTCONDITIONGROUP].[TOPPARENTCONDITIONGROUPID] = [CAFEETEMPLATEFEE].[CACONDITIONGROUPID] 
			INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEID]	
	WHERE	[deleted].[OPERATORID] <> [inserted].[OPERATORID]
	
	UNION ALL	
	SELECT 
			[CAFEETEMPLATE].[CAFEETEMPLATEID],
			[CAFEETEMPLATE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEETEMPLATE].[LASTCHANGEDBY],
			'Class Name',			
			ISNULL([deleted].[CLASSNAME],'[none]'),
			ISNULL([inserted].[CLASSNAME],'[none]'),
			'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee/Child Template (' + [CAFEETEMPLATEFEE].[FEENAME] +') Condition Group, Condition ('+[inserted].[OPERANDFRIENDLYNAME]+')',
			'CCA2295B-072A-494B-9C11-91424F59BC16',
			2,
			0,
			[CAFEETEMPLATE].[CAFEETEMPLATENAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CACONDITIONID] = [inserted].[CACONDITIONID]
			INNER JOIN @PARENTCONDITIONGROUP AS [PARENTCONDITIONGROUP] ON [PARENTCONDITIONGROUP].[CONDITIONGROUPID] = [inserted].[CACONDITIONGROUPID]
			INNER JOIN [dbo].[CAFEETEMPLATEFEE] ON [PARENTCONDITIONGROUP].[TOPPARENTCONDITIONGROUPID] = [CAFEETEMPLATEFEE].[CACONDITIONGROUPID] 
			INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEID]	
	WHERE	ISNULL([deleted].[CLASSNAME],'') <> ISNULL([inserted].[CLASSNAME],'')
	
	UNION ALL	
	SELECT 
			[CAFEETEMPLATE].[CAFEETEMPLATEID],
			[CAFEETEMPLATE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEETEMPLATE].[LASTCHANGEDBY],
			'Custom Field Table',			
			ISNULL([deleted].[CUSTOMFIELDTABLE],'[none]'),
			ISNULL([inserted].[CUSTOMFIELDTABLE],'[none]'),
			'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee/Child Template (' + [CAFEETEMPLATEFEE].[FEENAME] +') Condition Group, Condition ('+[inserted].[OPERANDFRIENDLYNAME]+')',
			'CCA2295B-072A-494B-9C11-91424F59BC16',
			2,
			0,
			[CAFEETEMPLATE].[CAFEETEMPLATENAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CACONDITIONID] = [inserted].[CACONDITIONID]
			INNER JOIN @PARENTCONDITIONGROUP AS [PARENTCONDITIONGROUP] ON [PARENTCONDITIONGROUP].[CONDITIONGROUPID] = [inserted].[CACONDITIONGROUPID]
			INNER JOIN [dbo].[CAFEETEMPLATEFEE] ON [PARENTCONDITIONGROUP].[TOPPARENTCONDITIONGROUPID] = [CAFEETEMPLATEFEE].[CACONDITIONGROUPID] 
			INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEID]	
	WHERE	ISNULL([deleted].[CUSTOMFIELDTABLE],'') <> ISNULL([inserted].[CUSTOMFIELDTABLE],'')
	
	UNION ALL	
	SELECT 
			[CAFEETEMPLATE].[CAFEETEMPLATEID],
			[CAFEETEMPLATE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEETEMPLATE].[LASTCHANGEDBY],
			'Expression',			
			ISNULL([CAEXPRESSION_DELETED].[VARIABLEINPUTNAME],'[none]'),
			ISNULL([CAEXPRESSION_INSERTED].[VARIABLEINPUTNAME],'[none]'),
			'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee/Child Template (' + [CAFEETEMPLATEFEE].[FEENAME] +') Condition Group, Condition ('+[inserted].[OPERANDFRIENDLYNAME]+')',
			'CCA2295B-072A-494B-9C11-91424F59BC16',
			2,
			0,
			[CAFEETEMPLATE].[CAFEETEMPLATENAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CACONDITIONID] = [inserted].[CACONDITIONID]
			INNER JOIN @PARENTCONDITIONGROUP AS [PARENTCONDITIONGROUP] ON [PARENTCONDITIONGROUP].[CONDITIONGROUPID] = [inserted].[CACONDITIONGROUPID]
			INNER JOIN [dbo].[CAFEETEMPLATEFEE] ON [PARENTCONDITIONGROUP].[TOPPARENTCONDITIONGROUPID] = [CAFEETEMPLATEFEE].[CACONDITIONGROUPID] 
			INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEID]	
			LEFT JOIN [dbo].[CAEXPRESSION] AS [CAEXPRESSION_DELETED] (NOLOCK)  ON [inserted].[COMPAREEXPRESSIONID] = [CAEXPRESSION_DELETED].[CAEXPRESSIONID] 
			LEFT JOIN [dbo].[CAEXPRESSION] AS [CAEXPRESSION_INSERTED] (NOLOCK)  ON [inserted].[COMPAREEXPRESSIONID] = [CAEXPRESSION_INSERTED].[CAEXPRESSIONID] 
	WHERE	ISNULL([deleted].[COMPAREEXPRESSIONID],'') <> ISNULL([inserted].[COMPAREEXPRESSIONID],'')
	
	-------------------------------[CAFEETEMPLATEDISCOUNT]----------------------------------------------
	UNION ALL
	SELECT 
			[CAFEETEMPLATE].[CAFEETEMPLATEID],
			[CAFEETEMPLATE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEETEMPLATE].[LASTCHANGEDBY],
			'Operand Type',			
			(SELECT [dbo].[GETENUMNAMEBYENUTYPEANDVALUE](1,[deleted].[OPERANDTYPEID])),
			(SELECT [dbo].[GETENUMNAMEBYENUTYPEANDVALUE](1,[inserted].[OPERANDTYPEID])),
			'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee Template Discount (' + [CADISCOUNT].[NAME] +') Condition Group, Condition ('+[inserted].[OPERANDFRIENDLYNAME]+')',
			'CCA2295B-072A-494B-9C11-91424F59BC16',
			2,
			0,
			[CAFEETEMPLATE].[CAFEETEMPLATENAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CACONDITIONID] = [inserted].[CACONDITIONID]
			INNER JOIN @PARENTCONDITIONGROUP AS [PARENTCONDITIONGROUP] ON [PARENTCONDITIONGROUP].[CONDITIONGROUPID] = [inserted].[CACONDITIONGROUPID]
			INNER JOIN [dbo].[CAFEETEMPLATEDISCOUNT] ON [PARENTCONDITIONGROUP].[TOPPARENTCONDITIONGROUPID] = [CAFEETEMPLATEDISCOUNT].[CACONDITIONGROUPID] 
			INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEDISCOUNT].[CAFEETEMPLATEID]				
			INNER JOIN [dbo].[CADISCOUNT] ON [CADISCOUNT].[CADISCOUNTID] = [CAFEETEMPLATEDISCOUNT].[CADISCOUNTID] 	
	WHERE	[deleted].[OPERANDTYPEID] <> [inserted].[OPERANDTYPEID]
	
	UNION ALL
	SELECT 
			[CAFEETEMPLATE].[CAFEETEMPLATEID],
			[CAFEETEMPLATE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEETEMPLATE].[LASTCHANGEDBY],
			'Operand Value',			
			ISNULL( [deleted].[OPERANDVALUE],'[none]'),
			ISNULL([inserted].[OPERANDVALUE],'[none]'),
			'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee Template Discount (' + [CADISCOUNT].[NAME] +') Condition Group, Condition ('+[inserted].[OPERANDFRIENDLYNAME]+')',
			'CCA2295B-072A-494B-9C11-91424F59BC16',
			2,
			0,
			[CAFEETEMPLATE].[CAFEETEMPLATENAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CACONDITIONID] = [inserted].[CACONDITIONID]
			INNER JOIN @PARENTCONDITIONGROUP AS [PARENTCONDITIONGROUP] ON [PARENTCONDITIONGROUP].[CONDITIONGROUPID] = [inserted].[CACONDITIONGROUPID]
			INNER JOIN [dbo].[CAFEETEMPLATEDISCOUNT] ON [PARENTCONDITIONGROUP].[TOPPARENTCONDITIONGROUPID] = [CAFEETEMPLATEDISCOUNT].[CACONDITIONGROUPID] 
			INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEDISCOUNT].[CAFEETEMPLATEID]				
			INNER JOIN [dbo].[CADISCOUNT] ON [CADISCOUNT].[CADISCOUNTID] = [CAFEETEMPLATEDISCOUNT].[CADISCOUNTID] 	
	WHERE	ISNULL([deleted].[OPERANDVALUE],'') <> ISNULL([inserted].[OPERANDVALUE],'')
	
	UNION ALL	
	SELECT 
			[CAFEETEMPLATE].[CAFEETEMPLATEID],
			[CAFEETEMPLATE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEETEMPLATE].[LASTCHANGEDBY],
			'Operand Friendly Name',			
			[deleted].[OPERANDFRIENDLYNAME],
			[inserted].[OPERANDFRIENDLYNAME],
			'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee Template Discount (' + [CADISCOUNT].[NAME] +') Condition Group, Condition ('+[inserted].[OPERANDFRIENDLYNAME]+')',
			'CCA2295B-072A-494B-9C11-91424F59BC16',
			2,
			0,
			[CAFEETEMPLATE].[CAFEETEMPLATENAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CACONDITIONID] = [inserted].[CACONDITIONID]
			INNER JOIN @PARENTCONDITIONGROUP AS [PARENTCONDITIONGROUP] ON [PARENTCONDITIONGROUP].[CONDITIONGROUPID] = [inserted].[CACONDITIONGROUPID]
			INNER JOIN [dbo].[CAFEETEMPLATEDISCOUNT] ON [PARENTCONDITIONGROUP].[TOPPARENTCONDITIONGROUPID] = [CAFEETEMPLATEDISCOUNT].[CACONDITIONGROUPID] 
			INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEDISCOUNT].[CAFEETEMPLATEID]				
			INNER JOIN [dbo].[CADISCOUNT] ON [CADISCOUNT].[CADISCOUNTID] = [CAFEETEMPLATEDISCOUNT].[CADISCOUNTID] 	
	WHERE	[deleted].[OPERANDFRIENDLYNAME] <> [inserted].[OPERANDFRIENDLYNAME]
	
	UNION ALL	
	SELECT 
			[CAFEETEMPLATE].[CAFEETEMPLATEID],
			[CAFEETEMPLATE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEETEMPLATE].[LASTCHANGEDBY],
			'Operand Data Type',					
			(SELECT [dbo].[GETENUMNAMEBYENUTYPEANDVALUE](2,[deleted].[OPERANDDATATYPEID])),
			(SELECT [dbo].[GETENUMNAMEBYENUTYPEANDVALUE](2,[inserted].[OPERANDDATATYPEID])),
			'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee Template Discount (' + [CADISCOUNT].[NAME] +') Condition Group, Condition ('+[inserted].[OPERANDFRIENDLYNAME]+')',
			'CCA2295B-072A-494B-9C11-91424F59BC16',
			2,
			0,
			[CAFEETEMPLATE].[CAFEETEMPLATENAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CACONDITIONID] = [inserted].[CACONDITIONID]
			INNER JOIN @PARENTCONDITIONGROUP AS [PARENTCONDITIONGROUP] ON [PARENTCONDITIONGROUP].[CONDITIONGROUPID] = [inserted].[CACONDITIONGROUPID]
			INNER JOIN [dbo].[CAFEETEMPLATEDISCOUNT] ON [PARENTCONDITIONGROUP].[TOPPARENTCONDITIONGROUPID] = [CAFEETEMPLATEDISCOUNT].[CACONDITIONGROUPID] 
			INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEDISCOUNT].[CAFEETEMPLATEID]				
			INNER JOIN [dbo].[CADISCOUNT] ON [CADISCOUNT].[CADISCOUNTID] = [CAFEETEMPLATEDISCOUNT].[CADISCOUNTID] 		
	WHERE	[deleted].[OPERANDDATATYPEID] <> [inserted].[OPERANDDATATYPEID]

	UNION ALL	
	SELECT 
			[CAFEETEMPLATE].[CAFEETEMPLATEID],
			[CAFEETEMPLATE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEETEMPLATE].[LASTCHANGEDBY],
			'Operator Type',			
			(SELECT [dbo].[GETENUMNAMEBYENUTYPEANDVALUE](3,[deleted].[OPERATORID])),
			(SELECT [dbo].[GETENUMNAMEBYENUTYPEANDVALUE](3,[inserted].[OPERATORID])),
			'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee Template Discount (' + [CADISCOUNT].[NAME] +') Condition Group, Condition ('+[inserted].[OPERANDFRIENDLYNAME]+')',
			'CCA2295B-072A-494B-9C11-91424F59BC16',
			2,
			0,
			[CAFEETEMPLATE].[CAFEETEMPLATENAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CACONDITIONID] = [inserted].[CACONDITIONID]
			INNER JOIN @PARENTCONDITIONGROUP AS [PARENTCONDITIONGROUP] ON [PARENTCONDITIONGROUP].[CONDITIONGROUPID] = [inserted].[CACONDITIONGROUPID]
			INNER JOIN [dbo].[CAFEETEMPLATEDISCOUNT] ON [PARENTCONDITIONGROUP].[TOPPARENTCONDITIONGROUPID] = [CAFEETEMPLATEDISCOUNT].[CACONDITIONGROUPID] 
			INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEDISCOUNT].[CAFEETEMPLATEID]				
			INNER JOIN [dbo].[CADISCOUNT] ON [CADISCOUNT].[CADISCOUNTID] = [CAFEETEMPLATEDISCOUNT].[CADISCOUNTID] 	
	WHERE	[deleted].[OPERATORID] <> [inserted].[OPERATORID]
	
	UNION ALL	
	SELECT 
			[CAFEETEMPLATE].[CAFEETEMPLATEID],
			[CAFEETEMPLATE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEETEMPLATE].[LASTCHANGEDBY],
			'Class Name',			
			ISNULL([deleted].[CLASSNAME],'[none]'),
			ISNULL([inserted].[CLASSNAME],'[none]'),
			'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee Template Discount (' + [CADISCOUNT].[NAME] +') Condition Group, Condition ('+[inserted].[OPERANDFRIENDLYNAME]+')',
			'CCA2295B-072A-494B-9C11-91424F59BC16',
			2,
			0,
			[CAFEETEMPLATE].[CAFEETEMPLATENAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CACONDITIONID] = [inserted].[CACONDITIONID]
			INNER JOIN @PARENTCONDITIONGROUP AS [PARENTCONDITIONGROUP] ON [PARENTCONDITIONGROUP].[CONDITIONGROUPID] = [inserted].[CACONDITIONGROUPID]
			INNER JOIN [dbo].[CAFEETEMPLATEDISCOUNT] ON [PARENTCONDITIONGROUP].[TOPPARENTCONDITIONGROUPID] = [CAFEETEMPLATEDISCOUNT].[CACONDITIONGROUPID] 
			INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEDISCOUNT].[CAFEETEMPLATEID]				
			INNER JOIN [dbo].[CADISCOUNT] ON [CADISCOUNT].[CADISCOUNTID] = [CAFEETEMPLATEDISCOUNT].[CADISCOUNTID] 		
	WHERE	ISNULL([deleted].[CLASSNAME],'') <> ISNULL([inserted].[CLASSNAME],'')
	
	UNION ALL	
	SELECT 
			[CAFEETEMPLATE].[CAFEETEMPLATEID],
			[CAFEETEMPLATE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEETEMPLATE].[LASTCHANGEDBY],
			'Custom Field Table',			
			ISNULL([deleted].[CUSTOMFIELDTABLE],'[none]'),
			ISNULL([inserted].[CUSTOMFIELDTABLE],'[none]'),
			'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee Template Discount (' + [CADISCOUNT].[NAME] +') Condition Group, Condition ('+[inserted].[OPERANDFRIENDLYNAME]+')',
			'CCA2295B-072A-494B-9C11-91424F59BC16',
			2,
			0,
			[CAFEETEMPLATE].[CAFEETEMPLATENAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CACONDITIONID] = [inserted].[CACONDITIONID]
			INNER JOIN @PARENTCONDITIONGROUP AS [PARENTCONDITIONGROUP] ON [PARENTCONDITIONGROUP].[CONDITIONGROUPID] = [inserted].[CACONDITIONGROUPID]
			INNER JOIN [dbo].[CAFEETEMPLATEDISCOUNT] ON [PARENTCONDITIONGROUP].[TOPPARENTCONDITIONGROUPID] = [CAFEETEMPLATEDISCOUNT].[CACONDITIONGROUPID] 
			INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEDISCOUNT].[CAFEETEMPLATEID]				
			INNER JOIN [dbo].[CADISCOUNT] ON [CADISCOUNT].[CADISCOUNTID] = [CAFEETEMPLATEDISCOUNT].[CADISCOUNTID] 	
	WHERE	ISNULL([deleted].[CUSTOMFIELDTABLE],'') <> ISNULL([inserted].[CUSTOMFIELDTABLE],'')
	
	UNION ALL	
	SELECT 
			[CAFEETEMPLATE].[CAFEETEMPLATEID],
			[CAFEETEMPLATE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEETEMPLATE].[LASTCHANGEDBY],
			'Expression',			
			ISNULL([CAEXPRESSION_DELETED].[VARIABLEINPUTNAME],'[none]'),
			ISNULL([CAEXPRESSION_INSERTED].[VARIABLEINPUTNAME],'[none]'),
			'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee Template Discount (' + [CADISCOUNT].[NAME] +') Condition Group, Condition ('+[inserted].[OPERANDFRIENDLYNAME]+')',
			'CCA2295B-072A-494B-9C11-91424F59BC16',
			2,
			0,
			[CAFEETEMPLATE].[CAFEETEMPLATENAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CACONDITIONID] = [inserted].[CACONDITIONID]
			INNER JOIN @PARENTCONDITIONGROUP AS [PARENTCONDITIONGROUP] ON [PARENTCONDITIONGROUP].[CONDITIONGROUPID] = [inserted].[CACONDITIONGROUPID]
			INNER JOIN [dbo].[CAFEETEMPLATEDISCOUNT] ON [PARENTCONDITIONGROUP].[TOPPARENTCONDITIONGROUPID] = [CAFEETEMPLATEDISCOUNT].[CACONDITIONGROUPID] 
			INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEDISCOUNT].[CAFEETEMPLATEID]				
			INNER JOIN [dbo].[CADISCOUNT] ON [CADISCOUNT].[CADISCOUNTID] = [CAFEETEMPLATEDISCOUNT].[CADISCOUNTID] 	
			LEFT JOIN [dbo].[CAEXPRESSION] AS [CAEXPRESSION_DELETED] (NOLOCK)  ON [inserted].[COMPAREEXPRESSIONID] = [CAEXPRESSION_DELETED].[CAEXPRESSIONID] 
			LEFT JOIN [dbo].[CAEXPRESSION] AS [CAEXPRESSION_INSERTED] (NOLOCK)  ON [inserted].[COMPAREEXPRESSIONID] = [CAEXPRESSION_INSERTED].[CAEXPRESSIONID] 
	WHERE	ISNULL([deleted].[COMPAREEXPRESSIONID],'') <> ISNULL([inserted].[COMPAREEXPRESSIONID],'')
END
GO

CREATE TRIGGER [dbo].[TG_CACONDITION_DELETE]  ON  [dbo].[CACONDITION]
   AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;	
	-- DECLARATION OF TABLE TYPE VARIABLE 
	DECLARE @CONDITIONGROUPIDS [RecordIDs]
	DECLARE @PARENTCONDITIONGROUP AS TABLE(TOPPARENTCONDITIONGROUPID CHAR(36),CONDITIONGROUPID CHAR(36))

	-- GET INSERTED CACONDITIONGROUPID 
	INSERT INTO @CONDITIONGROUPIDS
	SELECT [deleted].[CACONDITIONGROUPID] FROM [deleted]

	-- GET TOPPARENTID FOR CONDITION GROUP
	INSERT INTO @PARENTCONDITIONGROUP(TOPPARENTCONDITIONGROUPID,CONDITIONGROUPID)
	SELECT * FROM  [dbo].[GETTOPPARENTCONDITIONGROUPIDS](@CONDITIONGROUPIDS)

	INSERT INTO [HISTORYSYSTEMSETUP]
	(
		[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
	)
		SELECT 
        [CAFEETEMPLATE].[CAFEETEMPLATEID], 
        [CAFEETEMPLATE].[ROWVERSION],
        GETUTCDATE(),
		(SELECT dbo.UFN_GET_USERID_FROM_CONTEXT_INFO()),
        'Fee Template, Fee/Child Template, Condition Group, Condition Deleted',
        '',
        '',       
		'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee/Child Template (' + [CAFEETEMPLATEFEE].[FEENAME] +') Condition Group, Condition ('+[deleted].[OPERANDFRIENDLYNAME]+')',
		'CCA2295B-072A-494B-9C11-91424F59BC16',
		3,
		0,
		[CAFEETEMPLATE].[CAFEETEMPLATENAME]
    FROM [deleted]
	INNER JOIN @PARENTCONDITIONGROUP AS [PARENTCONDITIONGROUP] ON [PARENTCONDITIONGROUP].[CONDITIONGROUPID] = [deleted].[CACONDITIONGROUPID]
	INNER JOIN [dbo].[CAFEETEMPLATEFEE] ON [PARENTCONDITIONGROUP].[TOPPARENTCONDITIONGROUPID] = [CAFEETEMPLATEFEE].[CACONDITIONGROUPID] 
	INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEID]	
	
	UNION ALL 
	SELECT 
        [CAFEETEMPLATE].[CAFEETEMPLATEID], 
        [CAFEETEMPLATE].[ROWVERSION],
        GETUTCDATE(),
      (SELECT dbo.UFN_GET_USERID_FROM_CONTEXT_INFO()),
        'Fee Template, Fee Template Discount, Condition Group, Condition Deleted',
        '',
        '',       
		'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee Template Discount (' + [CADISCOUNT].[NAME] +') Condition Group, Condition ('+[deleted].[OPERANDFRIENDLYNAME]+')',
		'CCA2295B-072A-494B-9C11-91424F59BC16',
		3,
		0,
		[CAFEETEMPLATE].[CAFEETEMPLATENAME]
    FROM [deleted]
	INNER JOIN @PARENTCONDITIONGROUP AS [PARENTCONDITIONGROUP] ON [PARENTCONDITIONGROUP].[CONDITIONGROUPID] = [deleted].[CACONDITIONGROUPID]
	INNER JOIN [dbo].[CAFEETEMPLATEDISCOUNT] ON [PARENTCONDITIONGROUP].[TOPPARENTCONDITIONGROUPID] = [CAFEETEMPLATEDISCOUNT].[CACONDITIONGROUPID]
	INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEDISCOUNT].[CAFEETEMPLATEID]		
	INNER JOIN [dbo].[CADISCOUNT] ON [CADISCOUNT].[CADISCOUNTID] = [CAFEETEMPLATEDISCOUNT].[CADISCOUNTID] 
END
GO

CREATE TRIGGER [dbo].[TG_CACONDITION_INSERT] ON  [dbo].[CACONDITION]
   AFTER INSERT
AS 
BEGIN	
	SET NOCOUNT ON;	
	-- DECLARATION OF TABLE TYPE VARIABLE 
	DECLARE @CONDITIONGROUPIDS [RecordIDs]
	DECLARE @PARENTCONDITIONGROUP AS TABLE(TOPPARENTCONDITIONGROUPID CHAR(36),CONDITIONGROUPID CHAR(36))

	-- GET INSERTED CACONDITIONGROUPID 
	INSERT INTO @CONDITIONGROUPIDS
	SELECT [inserted].[CACONDITIONGROUPID] FROM [inserted]

	-- GET TOPPARENTID FOR CONDITION GROUP
	INSERT INTO @PARENTCONDITIONGROUP(TOPPARENTCONDITIONGROUPID,CONDITIONGROUPID)
	SELECT * FROM  [dbo].[GETTOPPARENTCONDITIONGROUPIDS](@CONDITIONGROUPIDS)
	
	INSERT INTO [HISTORYSYSTEMSETUP]
    (
        [ID],
        [ROWVERSION],
        [CHANGEDON],
        [CHANGEDBY],
        [FIELDNAME],
        [OLDVALUE],
        [NEWVALUE],
        [ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT 
        [CAFEETEMPLATE].[CAFEETEMPLATEID], 
        [CAFEETEMPLATE].[ROWVERSION],
        GETUTCDATE(),
        [CAFEETEMPLATE].[LASTCHANGEDBY],	
        'Fee Template, Fee/Child Template, Condition Group, Condition Added',
        '',
        '',       
		'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee/Child Template (' + [CAFEETEMPLATEFEE].[FEENAME] +') Condition Group, Condition ('+[inserted].[OPERANDFRIENDLYNAME]+')',
		'CCA2295B-072A-494B-9C11-91424F59BC16',
		1,
		0,
		[CAFEETEMPLATE].[CAFEETEMPLATENAME]
    FROM [inserted]	
	INNER JOIN @PARENTCONDITIONGROUP AS [PARENTCONDITIONGROUP] ON [PARENTCONDITIONGROUP].[CONDITIONGROUPID] = [inserted].[CACONDITIONGROUPID]
	INNER JOIN [dbo].[CAFEETEMPLATEFEE] ON [PARENTCONDITIONGROUP].[TOPPARENTCONDITIONGROUPID] = [CAFEETEMPLATEFEE].[CACONDITIONGROUPID] 
	INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEID]	
	
	UNION ALL 
	SELECT 
        [CAFEETEMPLATE].[CAFEETEMPLATEID], 
        [CAFEETEMPLATE].[ROWVERSION],
        GETUTCDATE(),
        [CAFEETEMPLATE].[LASTCHANGEDBY],	
        'Fee Template, Fee Template Discount, Condition Group, Condition  Added',
        '',
        '',       
		'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee Template Discount (' + [CADISCOUNT].[NAME] +') Condition Group, Condition ('+[inserted].[OPERANDFRIENDLYNAME]+')',
		'CCA2295B-072A-494B-9C11-91424F59BC16',
		1,
		0,
		[CAFEETEMPLATE].[CAFEETEMPLATENAME]
    FROM [inserted]	
	INNER JOIN @PARENTCONDITIONGROUP AS [PARENTCONDITIONGROUP] ON [PARENTCONDITIONGROUP].[CONDITIONGROUPID] = [inserted].[CACONDITIONGROUPID]
	INNER JOIN [dbo].[CAFEETEMPLATEDISCOUNT] ON [PARENTCONDITIONGROUP].[TOPPARENTCONDITIONGROUPID] = [CAFEETEMPLATEDISCOUNT].[CACONDITIONGROUPID] 
	INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEDISCOUNT].[CAFEETEMPLATEID]		
	INNER JOIN [dbo].[CADISCOUNT] ON [CADISCOUNT].[CADISCOUNTID] = [CAFEETEMPLATEDISCOUNT].[CADISCOUNTID] 		
END