CREATE TABLE [dbo].[CAENTITY] (
    [CAENTITYID]       INT           NOT NULL,
    [NAME]             NVARCHAR (50) NOT NULL,
    [CAMODULEID]       INT           NOT NULL,
    [ISHTMLDEPRICATED] BIT           NULL,
    CONSTRAINT [PK_CAEntity] PRIMARY KEY CLUSTERED ([CAENTITYID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_CAEntity_Module] FOREIGN KEY ([CAMODULEID]) REFERENCES [dbo].[CAMODULE] ([CAMODULEID])
);

