CREATE TABLE [dbo].[CAFEEGLACCOUNTXREF] (
    [CAFEEGLACCOUNTXREFID] CHAR (36)       NOT NULL,
    [CAFEEID]              CHAR (36)       NOT NULL,
    [DEBITGLACCOUNTID]     CHAR (36)       NULL,
    [CREDITGLACCOUNTID]    CHAR (36)       NULL,
    [CAPAYMENTTYPEID]      INT             CONSTRAINT [DEF_CAFeeGlAcctXRef_CAPaymtTypeID] DEFAULT ((1)) NOT NULL,
    [CAPAYMENTMETHODID]    CHAR (36)       CONSTRAINT [DF_CAFeeGLAcctXRef_PayMethod] DEFAULT ('5530AC74-FD8E-45A9-AB70-B4B1A82459C4') NOT NULL,
    [PERCENTAGE]           DECIMAL (20, 4) CONSTRAINT [DF_CAFeeGlAcctXRef_Percent] DEFAULT ((100)) NOT NULL,
    CONSTRAINT [PK_CAFeeGLAccountXRef] PRIMARY KEY CLUSTERED ([CAFEEGLACCOUNTXREFID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_CAFeeGLAccountXRef_CAFee] FOREIGN KEY ([CAFEEID]) REFERENCES [dbo].[CAFEE] ([CAFEEID]),
    CONSTRAINT [FK_CAFeeGLAccountXRef_Credit] FOREIGN KEY ([CREDITGLACCOUNTID]) REFERENCES [dbo].[GLACCOUNT] ([GLACCOUNTID]),
    CONSTRAINT [FK_CAFeeGLAccountXRef_Debit] FOREIGN KEY ([DEBITGLACCOUNTID]) REFERENCES [dbo].[GLACCOUNT] ([GLACCOUNTID]),
    CONSTRAINT [FK_CAFeeGLAcctXRef_PaymentType] FOREIGN KEY ([CAPAYMENTTYPEID]) REFERENCES [dbo].[CAPAYMENTTYPE] ([CAPAYMENTTYPEID]),
    CONSTRAINT [FK_CAFeeGLAcctXRef_PayMethod] FOREIGN KEY ([CAPAYMENTMETHODID]) REFERENCES [dbo].[CAPAYMENTMETHOD] ([CAPAYMENTMETHODID])
);


GO
CREATE NONCLUSTERED INDEX [CAFEEGLACCOUNTXREF_FEE]
    ON [dbo].[CAFEEGLACCOUNTXREF]([CAFEEID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [CAFEEGLACCOUNTXREF_PAYMENT]
    ON [dbo].[CAFEEGLACCOUNTXREF]([CAPAYMENTMETHODID] ASC)
    INCLUDE([CAPAYMENTTYPEID]);


GO

CREATE TRIGGER [TG_CAFEEGLACCOUNTXREF_DELETE] ON [CAFEEGLACCOUNTXREF]
	AFTER DELETE
AS
BEGIN
	SET NOCOUNT ON

	INSERT INTO [HISTORYSYSTEMSETUP]
	(
		[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
	)
	SELECT
			[CAFEE].[CAFEEID],
			[CAFEE].[ROWVERSION],
			GETUTCDATE(),
			(SELECT dbo.UFN_GET_USERID_FROM_CONTEXT_INFO()),
			'Fee Payment Method Deleted',
			'',
			'',
			'Fee (' + [CAFEE].[NAME] + '), Payment Method (' + [CAPAYMENTMETHOD].[NAME] + ')',
			'A66F715D-7817-4C5C-8D32-D9B22581828C',
			3,
			0,
			[CAPAYMENTMETHOD].[NAME]
	FROM	[deleted]	
	INNER JOIN [CAFEE] ON [deleted].[CAFEEID] = [CAFEE].[CAFEEID]
	INNER JOIN [CAPAYMENTMETHOD] ON [deleted].[CAPAYMENTMETHODID] = [CAPAYMENTMETHOD].[CAPAYMENTMETHODID]
END
GO

CREATE TRIGGER [dbo].[TG_CAFEEGLACCOUNTXREF_UPDATE] ON  [dbo].[CAFEEGLACCOUNTXREF]
   AFTER UPDATE
AS 
BEGIN	
	SET NOCOUNT ON;

	INSERT INTO [HISTORYSYSTEMSETUP]
    (	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT
			[CAFEE].[CAFEEID],
			[CAFEE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEE].[LASTCHANGEDBY],
			'Payment Method',
			[CAPAYMENTMETHOD_DELETED].[NAME],
			[CAPAYMENTMETHOD_INSERTED].[NAME],
			'Fee (' + [CAFEE].[NAME] + '), Payment Method (' + [CAPAYMENTMETHOD_INSERTED].[NAME] + ')',
			'A66F715D-7817-4C5C-8D32-D9B22581828C',
			2,
			0,
			[CAPAYMENTMETHOD_INSERTED].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CAFEEID] = [inserted].[CAFEEID]		
			INNER JOIN [CAFEE] ON [inserted].[CAFEEID] = [CAFEE].[CAFEEID]			
			INNER JOIN CAPAYMENTMETHOD CAPAYMENTMETHOD_DELETED WITH (NOLOCK) ON [deleted].[CAPAYMENTMETHODID] = [CAPAYMENTMETHOD_DELETED].[CAPAYMENTMETHODID]
			INNER JOIN CAPAYMENTMETHOD CAPAYMENTMETHOD_INSERTED WITH (NOLOCK) ON [inserted].[CAPAYMENTMETHODID] = [CAPAYMENTMETHOD_INSERTED].[CAPAYMENTMETHODID]
	WHERE	[deleted].[CAPAYMENTMETHODID] <> [inserted].[CAPAYMENTMETHODID]
	UNION ALL

	SELECT
			[CAFEE].[CAFEEID],
			[CAFEE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEE].[LASTCHANGEDBY],
			'GL Debit Account',
			ISNULL([GLACCOUNT_DELETED].[NAME], '[none]'),
			ISNULL([GLACCOUNT_INSERTED].[NAME], '[none]'),
			'Fee (' + [CAFEE].[NAME] + '), Payment Method (' + [CAPAYMENTMETHOD].[NAME] + ')',
			'A66F715D-7817-4C5C-8D32-D9B22581828C',
			2,
			0,
			[CAPAYMENTMETHOD].[NAME]
	FROM	[deleted]
	JOIN [inserted] ON [deleted].[CAFEEID] = [inserted].[CAFEEID]		
	INNER JOIN [CAFEE] ON [inserted].[CAFEEID] = [CAFEE].[CAFEEID]	
	INNER JOIN [CAPAYMENTMETHOD] ON [inserted].[CAPAYMENTMETHODID] = [CAPAYMENTMETHOD].[CAPAYMENTMETHODID]
	LEFT JOIN GLACCOUNT GLACCOUNT_DELETED WITH (NOLOCK) ON [deleted].[DEBITGLACCOUNTID] = [GLACCOUNT_DELETED].[GLACCOUNTID]
	LEFT JOIN GLACCOUNT GLACCOUNT_INSERTED WITH (NOLOCK) ON [inserted].[DEBITGLACCOUNTID] = [GLACCOUNT_INSERTED].[GLACCOUNTID]
	WHERE	ISNULL([deleted].[DEBITGLACCOUNTID], '') <> ISNULL([inserted].[DEBITGLACCOUNTID], '')
	UNION ALL

	SELECT
			[CAFEE].[CAFEEID],
			[CAFEE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEE].[LASTCHANGEDBY],
			'GL Credit Account',
			ISNULL([GLACCOUNT_DELETED].[NAME], '[none]'),
			ISNULL([GLACCOUNT_INSERTED].[NAME], '[none]'),
			'Fee (' + [CAFEE].[NAME] + '), Payment Method (' + [CAPAYMENTMETHOD].[NAME] + ')',
			'A66F715D-7817-4C5C-8D32-D9B22581828C',
			2,
			0,
			[CAPAYMENTMETHOD].[NAME]
	FROM	[deleted]
	JOIN [inserted] ON [deleted].[CAFEEID] = [inserted].[CAFEEID]		
	INNER JOIN [CAFEE] ON [inserted].[CAFEEID] = [CAFEE].[CAFEEID]	
	INNER JOIN [CAPAYMENTMETHOD] ON [inserted].[CAPAYMENTMETHODID] = [CAPAYMENTMETHOD].[CAPAYMENTMETHODID]
	LEFT JOIN GLACCOUNT GLACCOUNT_DELETED WITH (NOLOCK) ON [deleted].[CREDITGLACCOUNTID] = [GLACCOUNT_DELETED].[GLACCOUNTID]
	LEFT JOIN GLACCOUNT GLACCOUNT_INSERTED WITH (NOLOCK) ON [inserted].[CREDITGLACCOUNTID] = [GLACCOUNT_INSERTED].[GLACCOUNTID]
	WHERE	ISNULL([deleted].[CREDITGLACCOUNTID], '') <> ISNULL([inserted].[CREDITGLACCOUNTID], '')
	UNION ALL

	SELECT
			[CAFEE].[CAFEEID],
			[CAFEE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEE].[LASTCHANGEDBY],
			'Percentage',
			CONCAT(CAST([deleted].[PERCENTAGE] AS NVARCHAR(MAX)), '%'),
			CONCAT(CAST([inserted].[PERCENTAGE] AS NVARCHAR(MAX)), '%'),
			'Fee (' + [CAFEE].[NAME] + '), Payment Method (' + [CAPAYMENTMETHOD].[NAME] + ')',
			'A66F715D-7817-4C5C-8D32-D9B22581828C',
			2,
			0,
			[CAPAYMENTMETHOD].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CAFEEID] = [inserted].[CAFEEID]		
			INNER JOIN [CAFEE] ON [inserted].[CAFEEID] = [CAFEE].[CAFEEID]	
			INNER JOIN [CAPAYMENTMETHOD] ON [inserted].[CAPAYMENTMETHODID] = [CAPAYMENTMETHOD].[CAPAYMENTMETHODID]
	WHERE	[deleted].[PERCENTAGE] <> [inserted].[PERCENTAGE]
END
GO
CREATE TRIGGER [TG_CAFEEGLACCOUNTXREF_INSERT] ON [CAFEEGLACCOUNTXREF]
	AFTER INSERT
AS
BEGIN
	SET NOCOUNT ON

	INSERT INTO [HISTORYSYSTEMSETUP]
	(
		[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
	)
	SELECT 
			[CAFEE].[CAFEEID],
			[CAFEE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEE].[LASTCHANGEDBY],
			'Fee Payment Method Added',
			'',
			'',
			'Fee (' + [CAFEE].[NAME] + '), Payment Method (' + [CAPAYMENTMETHOD].[NAME] + ')',
			'A66F715D-7817-4C5C-8D32-D9B22581828C',
			1,
			0,
			[CAPAYMENTMETHOD].[NAME]
	FROM	[inserted]
	INNER JOIN [CAFEE] ON [inserted].[CAFEEID] = [CAFEE].[CAFEEID]
	INNER JOIN [CAPAYMENTMETHOD] ON [inserted].[CAPAYMENTMETHODID] = [CAPAYMENTMETHOD].[CAPAYMENTMETHODID]	
END