CREATE TABLE [dbo].[CAFEETEMPLATEFEEINPUT] (
    [CAFEETEMPLATEFEEINPUTID]  CHAR (36)      NOT NULL,
    [CAFEETEMPLATEFEEID]       CHAR (36)      NOT NULL,
    [CAFEETEMPLATEINPUTTYPEID] INT            CONSTRAINT [DF_CAFeeTemplFeeInput_Type] DEFAULT ((1)) NOT NULL,
    [INPUTVALUE]               NVARCHAR (50)  NULL,
    [INPUTFRIENDLYNAME]        NVARCHAR (MAX) NULL,
    [ISDISPLAY]                BIT            CONSTRAINT [DF_CAFeeTemplFeeInput_IsDisplay] DEFAULT ((0)) NOT NULL,
    [CUSTOMFIELDTABLE]         NVARCHAR (MAX) NULL,
    [CLASSNAME]                NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_CAFeeTemplateFeeInput] PRIMARY KEY CLUSTERED ([CAFEETEMPLATEFEEINPUTID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_CAFeeTemplFeeInput_Fee] FOREIGN KEY ([CAFEETEMPLATEFEEID]) REFERENCES [dbo].[CAFEETEMPLATEFEE] ([CAFEETEMPLATEFEEID]),
    CONSTRAINT [FK_CAFeeTemplFeeInput_Type] FOREIGN KEY ([CAFEETEMPLATEINPUTTYPEID]) REFERENCES [dbo].[CAFEETEMPLATEINPUTTYPE] ([CAFEETEMPLATEINPUTTYPEID])
);


GO
CREATE NONCLUSTERED INDEX [IX_CAFEETEMPLATEFEEINPUT_CAFEETEMPLATEFEEID]
    ON [dbo].[CAFEETEMPLATEFEEINPUT]([CAFEETEMPLATEFEEID] ASC);


GO

CREATE TRIGGER [dbo].[TG_CAFEETEMPLATEFEEINPUT_DELETE]  ON  [dbo].[CAFEETEMPLATEFEEINPUT]
   AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
	(
		[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
	)
	SELECT
		[CAFEETEMPLATE].[CAFEETEMPLATEID],
		[CAFEETEMPLATE].[ROWVERSION],
		GETUTCDATE(),			
		(SELECT dbo.UFN_GET_USERID_FROM_CONTEXT_INFO()),
		'Fee Template, Fee/Child Template, Fee Template Input Deleted',
        '',
        '',       
		'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee/Child Template (' + [CAFEETEMPLATEFEE].[FEENAME] +'), Fee Template Input ('+ [deleted].[INPUTFRIENDLYNAME] +' )',
		'CCA2295B-072A-494B-9C11-91424F59BC16',
		3,
		0,
		[CAFEETEMPLATE].[CAFEETEMPLATENAME]
    FROM [deleted]
	INNER JOIN [dbo].[CAFEETEMPLATEFEE] ON [deleted].[CAFEETEMPLATEFEEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEFEEID] 
	INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEID]	
END
GO

CREATE TRIGGER [dbo].[TG_CAFEETEMPLATEFEEINPUT_INSERT] ON  [dbo].[CAFEETEMPLATEFEEINPUT]
   AFTER INSERT
AS 
BEGIN	
	SET NOCOUNT ON;	
	INSERT INTO [HISTORYSYSTEMSETUP]
    (
        [ID],
        [ROWVERSION],
        [CHANGEDON],
        [CHANGEDBY],
        [FIELDNAME],
        [OLDVALUE],
        [NEWVALUE],
        [ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT 
        [CAFEETEMPLATE].[CAFEETEMPLATEID], 
        [CAFEETEMPLATE].[ROWVERSION],
        GETUTCDATE(),
        [CAFEETEMPLATE].[LASTCHANGEDBY],	
        'Fee Template, Fee/Child Template, Fee Template Input Added',
        '',
        '',       
		'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee/Child Template (' + [CAFEETEMPLATEFEE].[FEENAME] +'), Fee Template Input ('+ [inserted].[INPUTFRIENDLYNAME] +' )',
		'CCA2295B-072A-494B-9C11-91424F59BC16',
		1,
		0,
		[CAFEETEMPLATE].[CAFEETEMPLATENAME]
    FROM [inserted]
	INNER JOIN [dbo].[CAFEETEMPLATEFEE] ON [inserted].[CAFEETEMPLATEFEEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEFEEID] 
	INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEID]	
END
GO

CREATE TRIGGER [dbo].[TG_CAFEETEMPLATEFEEINPUT_UPDATE] ON  [dbo].[CAFEETEMPLATEFEEINPUT] 
   AFTER UPDATE
AS 
BEGIN	
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
    (	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT 
			[CAFEETEMPLATE].[CAFEETEMPLATEID],
			[CAFEETEMPLATE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEETEMPLATE].[LASTCHANGEDBY],
			'Fee Template Layout Input',			
			[CAFEETEMPLATEINPUTTYPE_DELETED].[NAME],
			[CAFEETEMPLATEINPUTTYPE_INSERTED].[NAME],
			'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee/Child Template (' + [CAFEETEMPLATEFEE].[FEENAME] +'), Fee Template Input ('+ [inserted].[INPUTFRIENDLYNAME] +' )',
			'CCA2295B-072A-494B-9C11-91424F59BC16',
			2,
			0,
			[CAFEETEMPLATE].[CAFEETEMPLATENAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CAFEETEMPLATEFEEINPUTID] = [inserted].[CAFEETEMPLATEFEEINPUTID]
			INNER JOIN [dbo].[CAFEETEMPLATEFEE] ON [inserted].[CAFEETEMPLATEFEEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEFEEID] 
			INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEID]	
			LEFT JOIN [dbo].[CAFEETEMPLATEINPUTTYPE] [CAFEETEMPLATEINPUTTYPE_DELETED] ON [deleted].[CAFEETEMPLATEINPUTTYPEID] = [CAFEETEMPLATEINPUTTYPE_DELETED].[CAFEETEMPLATEINPUTTYPEID]
			LEFT JOIN [dbo].[CAFEETEMPLATEINPUTTYPE] [CAFEETEMPLATEINPUTTYPE_INSERTED] ON [inserted].[CAFEETEMPLATEINPUTTYPEID] = [CAFEETEMPLATEINPUTTYPE_INSERTED].[CAFEETEMPLATEINPUTTYPEID]
	WHERE	[deleted].[CAFEETEMPLATEINPUTTYPEID] <> [inserted].[CAFEETEMPLATEINPUTTYPEID]

	UNION ALL
		SELECT 
			[CAFEETEMPLATE].[CAFEETEMPLATEID],
			[CAFEETEMPLATE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEETEMPLATE].[LASTCHANGEDBY],
			'Input Value',
			[deleted].[INPUTVALUE],
			[inserted].[INPUTVALUE],
			'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee/Child Template (' + [CAFEETEMPLATEFEE].[FEENAME] +'), Fee Template Input ('+	[inserted].[INPUTFRIENDLYNAME] +' )',
			'CCA2295B-072A-494B-9C11-91424F59BC16',
			2,
			0,
			[CAFEETEMPLATE].[CAFEETEMPLATENAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CAFEETEMPLATEFEEINPUTID] = [inserted].[CAFEETEMPLATEFEEINPUTID]
			INNER JOIN [dbo].[CAFEETEMPLATEFEE] ON [inserted].[CAFEETEMPLATEFEEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEFEEID] 
			INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEID]	
	WHERE	[deleted].[INPUTVALUE] <> [inserted].[INPUTVALUE]

	UNION ALL
		SELECT 
			[CAFEETEMPLATE].[CAFEETEMPLATEID],
			[CAFEETEMPLATE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEETEMPLATE].[LASTCHANGEDBY],
			'Input Friendly Name',
			[deleted].[INPUTFRIENDLYNAME],
			[inserted].[INPUTFRIENDLYNAME],
			'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee/Child Template (' + [CAFEETEMPLATEFEE].[FEENAME] +'), Fee Template Input ('+	[inserted].[INPUTFRIENDLYNAME] +' )',
			'CCA2295B-072A-494B-9C11-91424F59BC16',
			2,
			0,
			[CAFEETEMPLATE].[CAFEETEMPLATENAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CAFEETEMPLATEFEEINPUTID] = [inserted].[CAFEETEMPLATEFEEINPUTID]
			INNER JOIN [dbo].[CAFEETEMPLATEFEE] ON [inserted].[CAFEETEMPLATEFEEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEFEEID] 
			INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEID]	
	WHERE	[deleted].[INPUTFRIENDLYNAME] <> [inserted].[INPUTFRIENDLYNAME]

	UNION ALL
		SELECT 
			[CAFEETEMPLATE].[CAFEETEMPLATEID],
			[CAFEETEMPLATE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEETEMPLATE].[LASTCHANGEDBY],
			'Custom Field Table',			
			ISNULL([deleted].[CUSTOMFIELDTABLE],'[none]'),
			ISNULL([inserted].[CUSTOMFIELDTABLE],'[none]'),
			'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee/Child Template (' + [CAFEETEMPLATEFEE].[FEENAME] +'), Fee Template Input ('+	[inserted].[INPUTFRIENDLYNAME] +' )',
			'CCA2295B-072A-494B-9C11-91424F59BC16',
			2,
			0,
			[CAFEETEMPLATE].[CAFEETEMPLATENAME]
	FROM	[deleted]
		JOIN [inserted] ON [deleted].[CAFEETEMPLATEFEEINPUTID] = [inserted].[CAFEETEMPLATEFEEINPUTID]
			INNER JOIN [dbo].[CAFEETEMPLATEFEE] ON [inserted].[CAFEETEMPLATEFEEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEFEEID] 
			INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEID]	
	WHERE	ISNULL([deleted].[CUSTOMFIELDTABLE],'') <> ISNULL([inserted].[CUSTOMFIELDTABLE],'')

	UNION ALL
		SELECT 
			[CAFEETEMPLATE].[CAFEETEMPLATEID],
			[CAFEETEMPLATE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEETEMPLATE].[LASTCHANGEDBY],
			'Class Name',			
			ISNULL([deleted].[CLASSNAME],'[none]'),
			ISNULL([inserted].[CLASSNAME],'[none]'),
			'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee/Child Template (' + [CAFEETEMPLATEFEE].[FEENAME] +'), Fee Template Input ('+	[inserted].[INPUTFRIENDLYNAME] +' )',
			'CCA2295B-072A-494B-9C11-91424F59BC16',
			2,
			0,
			[CAFEETEMPLATE].[CAFEETEMPLATENAME]
	FROM	[deleted]
		JOIN [inserted] ON [deleted].[CAFEETEMPLATEFEEINPUTID] = [inserted].[CAFEETEMPLATEFEEINPUTID]
			INNER JOIN [dbo].[CAFEETEMPLATEFEE] ON [inserted].[CAFEETEMPLATEFEEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEFEEID] 
			INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEID]	
	WHERE	ISNULL([deleted].[CLASSNAME],'') <> ISNULL([inserted].[CLASSNAME],'')
	
	UNION ALL
		SELECT 
			[CAFEETEMPLATE].[CAFEETEMPLATEID],
			[CAFEETEMPLATE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEETEMPLATE].[LASTCHANGEDBY],
			'Is Display',			
			(CASE [deleted].[ISDISPLAY] WHEN 1 THEN 'Yes' ELSE 'No' END),
			(CASE [inserted].[ISDISPLAY] WHEN 1 THEN 'Yes' ELSE 'No' END),
			'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee/Child Template (' + [CAFEETEMPLATEFEE].[FEENAME] +'), Fee Template Input ('+	[inserted].[INPUTFRIENDLYNAME] +' )',
			'CCA2295B-072A-494B-9C11-91424F59BC16',
			2,
			0,
			[CAFEETEMPLATE].[CAFEETEMPLATENAME]
	FROM	[deleted]
		JOIN [inserted] ON [deleted].[CAFEETEMPLATEFEEINPUTID] = [inserted].[CAFEETEMPLATEFEEINPUTID]
			INNER JOIN [dbo].[CAFEETEMPLATEFEE] ON [inserted].[CAFEETEMPLATEFEEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEFEEID] 
			INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEID]
	WHERE	[deleted].[ISDISPLAY] <> [inserted].[ISDISPLAY]
END