CREATE TABLE [dbo].[CAFEEADJUSTABLECALC] (
    [CAFEEADJUSTABLECALCID] CHAR (36)       NOT NULL,
    [CAFEEID]               CHAR (36)       NOT NULL,
    [LOWERLIMIT]            DECIMAL (20, 4) NOT NULL,
    [UPPERLIMIT]            DECIMAL (20, 4) NOT NULL,
    [UNLIMITED]             BIT             NOT NULL,
    [AMOUNT]                MONEY           NOT NULL,
    [ADDITIONALAMOUNT]      MONEY           NOT NULL,
    [ADDITIONALUNIT]        DECIMAL (20, 4) NOT NULL,
    [OVER]                  DECIMAL (20, 4) NOT NULL,
    [CAFEESETUPID]          CHAR (36)       NOT NULL,
    CONSTRAINT [PK_CAFeeAdjustableCalc] PRIMARY KEY CLUSTERED ([CAFEEADJUSTABLECALCID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_CAFeeAdjustableCalc_CAFee] FOREIGN KEY ([CAFEEID]) REFERENCES [dbo].[CAFEE] ([CAFEEID]),
    CONSTRAINT [FK_CAFeeAdjustableCalc_Setup] FOREIGN KEY ([CAFEESETUPID]) REFERENCES [dbo].[CAFEESETUP] ([CAFEESETUPID])
);


GO
CREATE NONCLUSTERED INDEX [CAFEEADJUSTABLECALC_FEE]
    ON [dbo].[CAFEEADJUSTABLECALC]([CAFEEID] ASC);


GO
CREATE NONCLUSTERED INDEX [CAFEEADJUSTABLECALC_FEE_SETUP]
    ON [dbo].[CAFEEADJUSTABLECALC]([CAFEESETUPID] ASC);


GO

CREATE TRIGGER [TG_CAFEEADJUSTABLECALC_DELETE] ON [CAFEEADJUSTABLECALC]
	AFTER DELETE
AS
BEGIN
	SET NOCOUNT ON

	INSERT INTO [HISTORYSYSTEMSETUP]
	(
		[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
	)
	SELECT
			[CAFEE].[CAFEEID],
			[CAFEE].[ROWVERSION],
			GETUTCDATE(),
			(SELECT dbo.UFN_GET_USERID_FROM_CONTEXT_INFO()),
			'Fee - Adjustable Fees Deleted',
			'',
			'',
			'Fee (' + [CAFEE].[NAME] + '), Adjustable Fees For Fee Setup (' + ISNULL([CASCHEDULE].[NAME], '[none]') + ')',
			'A66F715D-7817-4C5C-8D32-D9B22581828C',
			3,
			0,
			ISNULL([CASCHEDULE].[NAME], '[none]')
	FROM	[deleted]	
	INNER JOIN [CAFEE] ON [deleted].[CAFEEID] = [CAFEE].[CAFEEID]	
	INNER JOIN [CAFEESETUP] WITH (NOLOCK) ON [deleted].[CAFEESETUPID] = [CAFEESETUP].[CAFEESETUPID]
	LEFT JOIN [CASCHEDULE] WITH (NOLOCK) ON [CASCHEDULE].[CASCHEDULEID] = [CAFEESETUP].[CASCHEDULEID]
END
GO
CREATE TRIGGER [TG_CAFEEADJUSTABLECALC_INSERT] ON [CAFEEADJUSTABLECALC]
	AFTER INSERT
AS
BEGIN
	SET NOCOUNT ON

	INSERT INTO [HISTORYSYSTEMSETUP]
	(
		[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
	)
	SELECT 
			[CAFEE].[CAFEEID],
			[CAFEE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEE].[LASTCHANGEDBY],
			'Fee - Adjustable Fees Added',
			'',
			'',
			'Fee (' + [CAFEE].[NAME] + '), Adjustable Fees For Fee Setup (' + ISNULL([CASCHEDULE].[NAME], '[none]') + ')',
			'A66F715D-7817-4C5C-8D32-D9B22581828C',
			1,
			0,
			ISNULL([CASCHEDULE].[NAME], '[none]')
	FROM	[inserted]
	INNER JOIN [CAFEE] ON [inserted].[CAFEEID] = [CAFEE].[CAFEEID]
	INNER JOIN [CAFEESETUP] WITH (NOLOCK) ON [inserted].[CAFEESETUPID] = [CAFEESETUP].[CAFEESETUPID]
	LEFT JOIN [CASCHEDULE] WITH (NOLOCK) ON [CASCHEDULE].[CASCHEDULEID] = [CAFEESETUP].[CASCHEDULEID]
END
GO

CREATE TRIGGER [dbo].[TG_CAFEEADJUSTABLECALC_UPDATE] ON  [dbo].[CAFEEADJUSTABLECALC]
   AFTER UPDATE
AS
BEGIN	
	SET NOCOUNT ON;

	INSERT INTO [HISTORYSYSTEMSETUP]
    (	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT
			[CAFEE].[CAFEEID],
			[CAFEE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEE].[LASTCHANGEDBY],
			'Lower Limit',
			CAST([deleted].[LOWERLIMIT] AS NVARCHAR(MAX)),
			CAST([inserted].[LOWERLIMIT] AS NVARCHAR(MAX)),			
			'Fee (' + [CAFEE].[NAME] + '), Adjustable Fees For Fee Setup (' + ISNULL([CASCHEDULE].[NAME], '[none]') + ')',
			'A66F715D-7817-4C5C-8D32-D9B22581828C',
			2,
			0,
			ISNULL([CASCHEDULE].[NAME], '[none]')
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CAFEEID] = [inserted].[CAFEEID]		
			INNER JOIN [CAFEE] ON [inserted].[CAFEEID] = [CAFEE].[CAFEEID]	
			INNER JOIN [CAFEESETUP] WITH (NOLOCK) ON [deleted].[CAFEESETUPID] = [CAFEESETUP].[CAFEESETUPID]
			LEFT JOIN [CASCHEDULE] WITH (NOLOCK) ON [CASCHEDULE].[CASCHEDULEID] = [CAFEESETUP].[CASCHEDULEID]
	WHERE	[deleted].[LOWERLIMIT] <> [inserted].[LOWERLIMIT]
	UNION ALL

	SELECT
			[CAFEE].[CAFEEID],
			[CAFEE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEE].[LASTCHANGEDBY],
			'Upper Limit',
			CAST([deleted].[UPPERLIMIT] AS NVARCHAR(MAX)),
			CAST([inserted].[UPPERLIMIT] AS NVARCHAR(MAX)),			
			'Fee (' + [CAFEE].[NAME] + '), Adjustable Fees For Fee Setup (' + ISNULL([CASCHEDULE].[NAME], '[none]') + ')',
			'A66F715D-7817-4C5C-8D32-D9B22581828C',
			2,
			0,
			ISNULL([CASCHEDULE].[NAME], '[none]')
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CAFEEID] = [inserted].[CAFEEID]		
			INNER JOIN [CAFEE] ON [inserted].[CAFEEID] = [CAFEE].[CAFEEID]	
			INNER JOIN [CAFEESETUP] WITH (NOLOCK) ON [deleted].[CAFEESETUPID] = [CAFEESETUP].[CAFEESETUPID]
			LEFT JOIN [CASCHEDULE] WITH (NOLOCK) ON [CASCHEDULE].[CASCHEDULEID] = [CAFEESETUP].[CASCHEDULEID]
	WHERE	[deleted].[UPPERLIMIT] <> [inserted].[UPPERLIMIT]
	UNION ALL

	SELECT
			[CAFEE].[CAFEEID],
			[CAFEE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEE].[LASTCHANGEDBY],
			'Unlimited Flag',
			CASE [deleted].[UNLIMITED] WHEN 1 THEN 'Yes' ELSE 'No' END,
			CASE [inserted].[UNLIMITED] WHEN 1 THEN 'Yes' ELSE 'No' END,
			'Fee (' + [CAFEE].[NAME] + '), Adjustable Fees For Fee Setup (' + ISNULL([CASCHEDULE].[NAME], '[none]') + ')',
			'A66F715D-7817-4C5C-8D32-D9B22581828C',
			2,
			0,
			ISNULL([CASCHEDULE].[NAME], '[none]')
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CAFEEID] = [inserted].[CAFEEID]		
			INNER JOIN [CAFEE] ON [inserted].[CAFEEID] = [CAFEE].[CAFEEID]	
			INNER JOIN [CAFEESETUP] WITH (NOLOCK) ON [deleted].[CAFEESETUPID] = [CAFEESETUP].[CAFEESETUPID]
			LEFT JOIN [CASCHEDULE] WITH (NOLOCK) ON [CASCHEDULE].[CASCHEDULEID] = [CAFEESETUP].[CASCHEDULEID]
	WHERE	[deleted].[UNLIMITED] <> [inserted].[UNLIMITED]
	UNION ALL

	SELECT
			[CAFEE].[CAFEEID],
			[CAFEE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEE].[LASTCHANGEDBY],
			'Amount',
			CAST(FORMAT([deleted].[AMOUNT], 'C4') AS NVARCHAR(MAX)),
			CAST(FORMAT([inserted].[AMOUNT], 'C4') AS NVARCHAR(MAX)),			
			'Fee (' + [CAFEE].[NAME] + '), Adjustable Fees For Fee Setup (' + ISNULL([CASCHEDULE].[NAME], '[none]') + ')',
			'A66F715D-7817-4C5C-8D32-D9B22581828C',
			2,
			0,
			ISNULL([CASCHEDULE].[NAME], '[none]')
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CAFEEID] = [inserted].[CAFEEID]		
			INNER JOIN [CAFEE] ON [inserted].[CAFEEID] = [CAFEE].[CAFEEID]	
			INNER JOIN [CAFEESETUP] WITH (NOLOCK) ON [deleted].[CAFEESETUPID] = [CAFEESETUP].[CAFEESETUPID]
			LEFT JOIN [CASCHEDULE] WITH (NOLOCK) ON [CASCHEDULE].[CASCHEDULEID] = [CAFEESETUP].[CASCHEDULEID]
	WHERE	[deleted].[AMOUNT] <> [inserted].[AMOUNT]	
	UNION ALL

	SELECT
			[CAFEE].[CAFEEID],
			[CAFEE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEE].[LASTCHANGEDBY],
			'Additional Amount',
			CAST(FORMAT([deleted].[ADDITIONALAMOUNT], 'C4') AS NVARCHAR(MAX)),
			CAST(FORMAT([inserted].[ADDITIONALAMOUNT], 'C4') AS NVARCHAR(MAX)),			
			'Fee (' + [CAFEE].[NAME] + '), Adjustable Fees For Fee Setup (' + ISNULL([CASCHEDULE].[NAME], '[none]') + ')',
			'A66F715D-7817-4C5C-8D32-D9B22581828C',
			2,
			0,
			ISNULL([CASCHEDULE].[NAME], '[none]')
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CAFEEID] = [inserted].[CAFEEID]		
			INNER JOIN [CAFEE] ON [inserted].[CAFEEID] = [CAFEE].[CAFEEID]	
			INNER JOIN [CAFEESETUP] WITH (NOLOCK) ON [deleted].[CAFEESETUPID] = [CAFEESETUP].[CAFEESETUPID]
			LEFT JOIN [CASCHEDULE] WITH (NOLOCK) ON [CASCHEDULE].[CASCHEDULEID] = [CAFEESETUP].[CASCHEDULEID]
	WHERE	[deleted].[ADDITIONALAMOUNT] <> [inserted].[ADDITIONALAMOUNT]	
	UNION ALL

	SELECT
			[CAFEE].[CAFEEID],
			[CAFEE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEE].[LASTCHANGEDBY],
			'Additional Unit',
			CAST([deleted].[ADDITIONALUNIT] AS NVARCHAR(MAX)),
			CAST([inserted].[ADDITIONALUNIT] AS NVARCHAR(MAX)),			
			'Fee (' + [CAFEE].[NAME] + '), Adjustable Fees For Fee Setup (' + ISNULL([CASCHEDULE].[NAME], '[none]') + ')',
			'A66F715D-7817-4C5C-8D32-D9B22581828C',
			2,
			0,
			ISNULL([CASCHEDULE].[NAME], '[none]')
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CAFEEID] = [inserted].[CAFEEID]		
			INNER JOIN [CAFEE] ON [inserted].[CAFEEID] = [CAFEE].[CAFEEID]	
			INNER JOIN [CAFEESETUP] WITH (NOLOCK) ON [deleted].[CAFEESETUPID] = [CAFEESETUP].[CAFEESETUPID]
			LEFT JOIN [CASCHEDULE] WITH (NOLOCK) ON [CASCHEDULE].[CASCHEDULEID] = [CAFEESETUP].[CASCHEDULEID]
	WHERE	[deleted].[ADDITIONALUNIT] <> [inserted].[ADDITIONALUNIT]	
	UNION ALL

	SELECT
			[CAFEE].[CAFEEID],
			[CAFEE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEE].[LASTCHANGEDBY],
			'Over',
			CAST([deleted].[OVER] AS NVARCHAR(MAX)),
			CAST([inserted].[OVER] AS NVARCHAR(MAX)),			
			'Fee (' + [CAFEE].[NAME] + '), Adjustable Fees For Fee Setup (' + ISNULL([CASCHEDULE].[NAME], '[none]') + ')',
			'A66F715D-7817-4C5C-8D32-D9B22581828C',
			2,
			0,
			ISNULL([CASCHEDULE].[NAME], '[none]')
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CAFEEID] = [inserted].[CAFEEID]		
			INNER JOIN [CAFEE] ON [inserted].[CAFEEID] = [CAFEE].[CAFEEID]	
			INNER JOIN [CAFEESETUP] WITH (NOLOCK) ON [deleted].[CAFEESETUPID] = [CAFEESETUP].[CAFEESETUPID]
			LEFT JOIN [CASCHEDULE] WITH (NOLOCK) ON [CASCHEDULE].[CASCHEDULEID] = [CAFEESETUP].[CASCHEDULEID]
	WHERE	[deleted].[OVER] <> [inserted].[OVER]
END