CREATE TABLE [dbo].[CAFEETEMPLATEINPUTTYPE] (
    [CAFEETEMPLATEINPUTTYPEID] INT            NOT NULL,
    [NAME]                     NVARCHAR (50)  NOT NULL,
    [DESCRIPTION]              NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_CAFeeTemplateInputType] PRIMARY KEY CLUSTERED ([CAFEETEMPLATEINPUTTYPEID] ASC) WITH (FILLFACTOR = 90)
);

