CREATE TABLE [dbo].[CAFEETEMPLATEFEEPRORATEDATE] (
    [CAFEETEMPLATEFEEPRORATEDATEID] CHAR (36)      NOT NULL,
    [CAFEETEMPLATEFEEID]            CHAR (36)      NOT NULL,
    [STARTOBJECTTYPEID]             INT            NOT NULL,
    [STARTOBJECT]                   NVARCHAR (100) NOT NULL,
    [STARTOBJECTFRIENDLYNAME]       NVARCHAR (200) NOT NULL,
    [ENDOBJECTTYPEID]               INT            NOT NULL,
    [ENDOBJECT]                     NVARCHAR (100) NOT NULL,
    [ENDOBJECTFRIENDLYNAME]         NVARCHAR (200) NOT NULL,
    [DAYSTOPRORATE]                 INT            NOT NULL,
    CONSTRAINT [PK_CAFEETEMPPRORATEDATEID] PRIMARY KEY NONCLUSTERED ([CAFEETEMPLATEFEEPRORATEDATEID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_CAPRORATEDATE_FEETEMPLATE] FOREIGN KEY ([CAFEETEMPLATEFEEID]) REFERENCES [dbo].[CAFEETEMPLATEFEE] ([CAFEETEMPLATEFEEID]),
    CONSTRAINT [FK_ENDOBJECT_TMPTYPE] FOREIGN KEY ([ENDOBJECTTYPEID]) REFERENCES [dbo].[CAFEETEMPLATEINPUTTYPE] ([CAFEETEMPLATEINPUTTYPEID]),
    CONSTRAINT [FK_STARTOBJECT_TMPTYPE] FOREIGN KEY ([STARTOBJECTTYPEID]) REFERENCES [dbo].[CAFEETEMPLATEINPUTTYPE] ([CAFEETEMPLATEINPUTTYPEID])
);


GO
CREATE NONCLUSTERED INDEX [IX_CAFEETEMPLATEFEEPRORATEDATE_CAFEETEMPLATEFEEID]
    ON [dbo].[CAFEETEMPLATEFEEPRORATEDATE]([CAFEETEMPLATEFEEID] ASC);


GO

CREATE TRIGGER [dbo].[TG_CAFEETEMPLATEFEEPRORATEDATE_UPDATE] ON  [dbo].[CAFEETEMPLATEFEEPRORATEDATE] 
   AFTER UPDATE
AS 
BEGIN	
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
    (	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT 
			[CAFEETEMPLATE].[CAFEETEMPLATEID],
			[CAFEETEMPLATE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEETEMPLATE].[LASTCHANGEDBY],
			'Start Type',			
			[CAFEETEMPLATEINPUTTYPE_DELETED].[NAME],
			[CAFEETEMPLATEINPUTTYPE_INSERTED].[NAME],
			'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee/Child Template (' + [CAFEETEMPLATEFEE].[FEENAME] +'), Setup Fee Prorate Input (Start Friendly Name: '+ [inserted].[STARTOBJECTFRIENDLYNAME] +' And End Date:'+ [inserted].[ENDOBJECTFRIENDLYNAME]+'  )',
			'CCA2295B-072A-494B-9C11-91424F59BC16',
			2,
			0,
			[CAFEETEMPLATE].[CAFEETEMPLATENAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CAFEETEMPLATEFEEPRORATEDATEID] = [inserted].[CAFEETEMPLATEFEEPRORATEDATEID]
			INNER JOIN [dbo].[CAFEETEMPLATEFEE] ON [inserted].[CAFEETEMPLATEFEEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEFEEID] 
			INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEID]
			LEFT JOIN [dbo].[CAFEETEMPLATEINPUTTYPE] [CAFEETEMPLATEINPUTTYPE_DELETED] ON [deleted].[STARTOBJECTTYPEID] = [CAFEETEMPLATEINPUTTYPE_DELETED].[CAFEETEMPLATEINPUTTYPEID]
			LEFT JOIN [dbo].[CAFEETEMPLATEINPUTTYPE] [CAFEETEMPLATEINPUTTYPE_INSERTED] ON [inserted].[STARTOBJECTTYPEID] = [CAFEETEMPLATEINPUTTYPE_INSERTED].[CAFEETEMPLATEINPUTTYPEID]
	WHERE	[deleted].[STARTOBJECTTYPEID]<> [inserted].[STARTOBJECTTYPEID]

	UNION ALL
	SELECT 
			[CAFEETEMPLATE].[CAFEETEMPLATEID],
			[CAFEETEMPLATE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEETEMPLATE].[LASTCHANGEDBY],
			'End Type',				
			[CAFEETEMPLATEINPUTTYPE_DELETED].[NAME],
			[CAFEETEMPLATEINPUTTYPE_INSERTED].[NAME],
			'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee/Child Template (' + [CAFEETEMPLATEFEE].[FEENAME] +'), Setup Fee Prorate Input (Start Friendly Name: '+ [inserted].[STARTOBJECTFRIENDLYNAME] +' And End Friendly Name:'+ [inserted].[ENDOBJECTFRIENDLYNAME]+'  )',
			'CCA2295B-072A-494B-9C11-91424F59BC16',
			2,
			0,
			[CAFEETEMPLATE].[CAFEETEMPLATENAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CAFEETEMPLATEFEEPRORATEDATEID] = [inserted].[CAFEETEMPLATEFEEPRORATEDATEID]
			INNER JOIN [dbo].[CAFEETEMPLATEFEE] ON [inserted].[CAFEETEMPLATEFEEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEFEEID] 
			INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEID]
			LEFT JOIN [dbo].[CAFEETEMPLATEINPUTTYPE] [CAFEETEMPLATEINPUTTYPE_DELETED] ON [deleted].[ENDOBJECTTYPEID] = [CAFEETEMPLATEINPUTTYPE_DELETED].[CAFEETEMPLATEINPUTTYPEID]
			LEFT JOIN [dbo].[CAFEETEMPLATEINPUTTYPE] [CAFEETEMPLATEINPUTTYPE_INSERTED] ON [inserted].[ENDOBJECTTYPEID] = [CAFEETEMPLATEINPUTTYPE_INSERTED].[CAFEETEMPLATEINPUTTYPEID]
	WHERE	[deleted].[STARTOBJECTTYPEID]<> [inserted].[STARTOBJECTTYPEID]
		
	UNION ALL
		SELECT 
			[CAFEETEMPLATE].[CAFEETEMPLATEID],
			[CAFEETEMPLATE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEETEMPLATE].[LASTCHANGEDBY],
			'Start Friendly Name',
			[deleted].[STARTOBJECTFRIENDLYNAME],
			[inserted].[STARTOBJECTFRIENDLYNAME],
			'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee/Child Template (' + [CAFEETEMPLATEFEE].[FEENAME] +'), Setup Fee Prorate Input (Start Friendly Name: '+ [inserted].[STARTOBJECTFRIENDLYNAME] +' And End Friendly Name:'+ [inserted].[ENDOBJECTFRIENDLYNAME]+'  )',
			'CCA2295B-072A-494B-9C11-91424F59BC16',
			2,
			0,
			[CAFEETEMPLATE].[CAFEETEMPLATENAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CAFEETEMPLATEFEEPRORATEDATEID] = [inserted].[CAFEETEMPLATEFEEPRORATEDATEID]
			INNER JOIN [dbo].[CAFEETEMPLATEFEE] ON [inserted].[CAFEETEMPLATEFEEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEFEEID] 
			INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEID]	
	WHERE	[deleted].[STARTOBJECTFRIENDLYNAME] <> [inserted].[STARTOBJECTFRIENDLYNAME]

	UNION ALL
		SELECT 
			[CAFEETEMPLATE].[CAFEETEMPLATEID],
			[CAFEETEMPLATE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEETEMPLATE].[LASTCHANGEDBY],
			'End Friendly Name',
			[deleted].[ENDOBJECTFRIENDLYNAME],
			[inserted].[ENDOBJECTFRIENDLYNAME],
			'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee/Child Template (' + [CAFEETEMPLATEFEE].[FEENAME] +'), Setup Fee Prorate Input (Start Friendly Name: '+ [inserted].[STARTOBJECTFRIENDLYNAME] +' And End Friendly Name:'+ [inserted].[ENDOBJECTFRIENDLYNAME]+'  )',
			'CCA2295B-072A-494B-9C11-91424F59BC16',
			2,
			0,
			[CAFEETEMPLATE].[CAFEETEMPLATENAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CAFEETEMPLATEFEEPRORATEDATEID] = [inserted].[CAFEETEMPLATEFEEPRORATEDATEID]
			INNER JOIN [dbo].[CAFEETEMPLATEFEE] ON [inserted].[CAFEETEMPLATEFEEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEFEEID] 
			INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEID]
	WHERE	[deleted].[ENDOBJECTFRIENDLYNAME] <> [inserted].[ENDOBJECTFRIENDLYNAME]
	   
	UNION ALL
		SELECT 
			[CAFEETEMPLATE].[CAFEETEMPLATEID],
			[CAFEETEMPLATE].[ROWVERSION],
			GETUTCDATE(),
			[CAFEETEMPLATE].[LASTCHANGEDBY],
			'Days To Pro Rate',			
			CONVERT(NVARCHAR(MAX), [deleted].[DAYSTOPRORATE]),
			CONVERT(NVARCHAR(MAX), [inserted].[DAYSTOPRORATE]),
			'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee/Child Template (' + [CAFEETEMPLATEFEE].[FEENAME] +'), Setup Fee Prorate Input (Start Friendly Name: '+ [inserted].[STARTOBJECTFRIENDLYNAME] +' And End Friendly Name:'+ [inserted].[ENDOBJECTFRIENDLYNAME]+'  )',
			'CCA2295B-072A-494B-9C11-91424F59BC16',
			2,
			0,
			[CAFEETEMPLATE].[CAFEETEMPLATENAME]
	FROM	[deleted]
		JOIN [inserted] ON [deleted].[CAFEETEMPLATEFEEPRORATEDATEID] = [inserted].[CAFEETEMPLATEFEEPRORATEDATEID]
			INNER JOIN [dbo].[CAFEETEMPLATEFEE] ON [inserted].[CAFEETEMPLATEFEEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEFEEID] 
			INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEID]
	WHERE	[deleted].[DAYSTOPRORATE] <> [inserted].[DAYSTOPRORATE]
END
GO


CREATE TRIGGER [dbo].[TG_CAFEETEMPLATEFEEPRORATEDATE_INSERT] ON  [dbo].[CAFEETEMPLATEFEEPRORATEDATE]
   AFTER INSERT
AS 
BEGIN	
	SET NOCOUNT ON;	
	INSERT INTO [HISTORYSYSTEMSETUP]
    (
        [ID],
        [ROWVERSION],
        [CHANGEDON],
        [CHANGEDBY],
        [FIELDNAME],
        [OLDVALUE],
        [NEWVALUE],
        [ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT 
        [CAFEETEMPLATE].[CAFEETEMPLATEID], 
        [CAFEETEMPLATE].[ROWVERSION],
        GETUTCDATE(),
        [CAFEETEMPLATE].[LASTCHANGEDBY],	
        'Fee Template, Fee/Child Template, Setup Fee Prorate Input Added',
        '',
        '',       
		'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee/Child Template (' + [CAFEETEMPLATEFEE].[FEENAME] +'), Setup Fee Prorate Input (Start Friendly Name: '+ [inserted].[STARTOBJECTFRIENDLYNAME] +' And End Friendly Name:'+ [inserted].[ENDOBJECTFRIENDLYNAME]+'  )',
		'CCA2295B-072A-494B-9C11-91424F59BC16',
		1,
		0,
		[CAFEETEMPLATE].[CAFEETEMPLATENAME]
    FROM [inserted]
	INNER JOIN [dbo].[CAFEETEMPLATEFEE] ON [inserted].[CAFEETEMPLATEFEEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEFEEID] 
	INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEID]	
END
GO

CREATE TRIGGER [dbo].[TG_CAFEETEMPLATEFEEPRORATEDATE_DELETE]  ON  [dbo].[CAFEETEMPLATEFEEPRORATEDATE]
   AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
	(
		[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
	)
	SELECT
		[CAFEETEMPLATE].[CAFEETEMPLATEID],
		[CAFEETEMPLATE].[ROWVERSION],
		GETUTCDATE(),			
		(SELECT dbo.UFN_GET_USERID_FROM_CONTEXT_INFO()),
		'Fee Template, Fee/Child Template, Setup Fee Prorate Input Deleted',
        '',
        '',       
		'Fee Template (' + [CAFEETEMPLATE].[CAFEETEMPLATENAME] + '), Fee/Child Template (' + [CAFEETEMPLATEFEE].[FEENAME] +'), Setup Fee Prorate Input (Start Friendly Name: '+ [deleted].[STARTOBJECTFRIENDLYNAME] +' And End Friendly Name:'+ [deleted].[ENDOBJECTFRIENDLYNAME]+'  )',
		'CCA2295B-072A-494B-9C11-91424F59BC16',
		3,
		0,
		[CAFEETEMPLATE].[CAFEETEMPLATENAME]
    FROM [deleted]
	INNER JOIN [dbo].[CAFEETEMPLATEFEE] ON [deleted].[CAFEETEMPLATEFEEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEFEEID] 
	INNER JOIN [dbo].[CAFEETEMPLATE] ON [CAFEETEMPLATE].[CAFEETEMPLATEID] = [CAFEETEMPLATEFEE].[CAFEETEMPLATEID]	
END