CREATE TABLE [dbo].[CAFEEROUNDINGTYPE] (
    [CAFEEROUNDINGTYPEID] INT            NOT NULL,
    [NAME]                NVARCHAR (50)  NOT NULL,
    [DESCRIPTION]         NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_CAFeeRoundingType] PRIMARY KEY CLUSTERED ([CAFEEROUNDINGTYPEID] ASC) WITH (FILLFACTOR = 90)
);

