CREATE TABLE [dbo].[CAINTEGRATIONBATCHGLTYPE] (
    [CAINTEGRATIONBATCHGLTYPEID] INT            NOT NULL,
    [NAME]                       NVARCHAR (50)  NOT NULL,
    [DESCRIPTION]                NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_CAINTEGRATIONBATCHGLTYPE] PRIMARY KEY CLUSTERED ([CAINTEGRATIONBATCHGLTYPEID] ASC)
);

