CREATE TABLE [dbo].[CAINTEGRATIONBATCHTYPE] (
    [CAINTEGRATIONBATCHTYPEID] INT            NOT NULL,
    [NAME]                     NVARCHAR (50)  NOT NULL,
    [DESCRIPTION]              NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_CAINTEGRATIONBATCHTYPE] PRIMARY KEY CLUSTERED ([CAINTEGRATIONBATCHTYPEID] ASC)
);

