CREATE TABLE [dbo].[CAMISCFEEADJUSTMENT] (
    [CAMISCFEEADJUSTMENTID] CHAR (36)      NOT NULL,
    [CAMISCFEEID]           CHAR (36)      NOT NULL,
    [CAFEEADJUSTREASONID]   CHAR (36)      NOT NULL,
    [USERID]                CHAR (36)      NOT NULL,
    [CHANGEDATE]            DATETIME       NOT NULL,
    [NOTES]                 NVARCHAR (MAX) NULL,
    [OLDAMOUNT]             MONEY          NOT NULL,
    [NEWAMOUNT]             MONEY          NOT NULL,
    CONSTRAINT [PK_CAMISCFEEADJUSTMENT] PRIMARY KEY CLUSTERED ([CAMISCFEEADJUSTMENTID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_MISCFEEADJUSTMENT_MISCFEE] FOREIGN KEY ([CAMISCFEEID]) REFERENCES [dbo].[CAMISCFEE] ([CAMISCFEEID]),
    CONSTRAINT [FK_MISCFEEADJUSTMENT_REASON] FOREIGN KEY ([CAFEEADJUSTREASONID]) REFERENCES [dbo].[CAFEEADJUSTREASON] ([CAFEEADJUSTREASONID]),
    CONSTRAINT [FK_MISCFEEADJUSTMENT_USER] FOREIGN KEY ([USERID]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);

