CREATE TABLE [dbo].[CAPSETTINGMETADATA] (
    [CAPSETTINGNAME] NVARCHAR (50)  NOT NULL,
    [FRIENDLYNAME]   NVARCHAR (MAX) NULL,
    [ISINTBASED]     BIT            NULL,
    CONSTRAINT [PK_CAPSETTINGMETADATA] PRIMARY KEY CLUSTERED ([CAPSETTINGNAME] ASC)
);

