CREATE TABLE [dbo].[CAROUNDINGTYPE] (
    [CAROUNDINGTYPEID] INT            NOT NULL,
    [NAME]             NVARCHAR (50)  NOT NULL,
    [DESCRIPTION]      NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_CARoundingType] PRIMARY KEY CLUSTERED ([CAROUNDINGTYPEID] ASC) WITH (FILLFACTOR = 90)
);

