CREATE TABLE [dbo].[CATILLSESSIONTCBATCH] (
    [CATILLSESSIONTCBATCHID] CHAR (36)     NOT NULL,
    [CATILLSESSIONID]        CHAR (36)     NOT NULL,
    [BATCHID]                INT           NOT NULL,
    [BATCHNUMBER]            NVARCHAR (35) NOT NULL,
    [ISBATCHCLOSED]          BIT           NOT NULL,
    CONSTRAINT [PK_CATILLSESSIONTCBATCH] PRIMARY KEY CLUSTERED ([CATILLSESSIONTCBATCHID] ASC),
    CONSTRAINT [FK_CATILLSESSION_CATILLSESS] FOREIGN KEY ([CATILLSESSIONID]) REFERENCES [dbo].[CATILLSESSION] ([CATILLSESSIONID])
);


GO
CREATE NONCLUSTERED INDEX [CATILLSESSIONTCBATCH_IX_TCBATCHNUMBER]
    ON [dbo].[CATILLSESSIONTCBATCH]([BATCHNUMBER] ASC);

