CREATE TABLE [dbo].[CATRANSACTIONARTYPE] (
    [CATRANSACTIONARTYPEID]   INT           NOT NULL,
    [CATRANSACTIONARTYPENAME] NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_CATRANSACTIONARTYPE] PRIMARY KEY CLUSTERED ([CATRANSACTIONARTYPEID] ASC) WITH (FILLFACTOR = 90)
);

