CREATE TABLE [dbo].[CATRANSACTIONGLPOSTING] (
    [CATRANSACTIONGLPOSTINGID] CHAR (36)      NOT NULL,
    [DEBITACCOUNTID]           CHAR (36)      NULL,
    [DEBITACCOUNTNUMBER]       NVARCHAR (500) NULL,
    [CREDITACCOUNTID]          CHAR (36)      NULL,
    [CREDITACCOUNTNUMBER]      NVARCHAR (500) NULL,
    [POSTINGDATE]              DATETIME       NOT NULL,
    [POSTINGAMOUNT]            MONEY          NOT NULL,
    [EXPORTEDON]               DATETIME       NULL,
    CONSTRAINT [PK_CATransactionGLPosting] PRIMARY KEY NONCLUSTERED ([CATRANSACTIONGLPOSTINGID] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [CATRANSACTIONGLPOSTING_EXPORT]
    ON [dbo].[CATRANSACTIONGLPOSTING]([POSTINGDATE] ASC, [EXPORTEDON] ASC) WITH (FILLFACTOR = 80);

