CREATE TABLE [dbo].[CATRANSACTIONPAYMENT] (
    [CATRANSACTIONPAYMENTID] CHAR (36)       NOT NULL,
    [CAPAYMENTTYPEID]        INT             NOT NULL,
    [CATRANSACTIONID]        CHAR (36)       NOT NULL,
    [PAYMENTDATE]            DATETIME        NOT NULL,
    [PAYMENTAMOUNT]          MONEY           NOT NULL,
    [PAYMENTNOTE]            NVARCHAR (MAX)  NULL,
    [CAPAYMENTSTATUSID]      INT             CONSTRAINT [DEF_CATransactionPayment_StatusID] DEFAULT ((1)) NOT NULL,
    [ROWVERSION]             INT             CONSTRAINT [DF_CATransactionPayment_RowVersion] DEFAULT ((1)) NOT NULL,
    [LASTCHANGEDON]          DATETIME        CONSTRAINT [DF_CATransactionPayment_LastChangedOn] DEFAULT (getdate()) NOT NULL,
    [LASTCHANGEDBY]          CHAR (36)       NOT NULL,
    [CAPAYMENTMETHODID]      CHAR (36)       CONSTRAINT [DF_CATransPayment_PayMethod] DEFAULT ('5530AC74-FD8E-45A9-AB70-B4B1A82459C4') NOT NULL,
    [SUPPLEMENTALDATA]       NVARCHAR (2200) NULL,
    [ISONLINE]               BIT             CONSTRAINT [DF_CATRANSACTIONPAYMENT_ISFROMCAP] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_CATransactionPayment] PRIMARY KEY NONCLUSTERED ([CATRANSACTIONPAYMENTID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_CATransactionPayment_Status] FOREIGN KEY ([CAPAYMENTSTATUSID]) REFERENCES [dbo].[CAPAYMENTSTATUS] ([CAPAYMENTSTATUSID]),
    CONSTRAINT [FK_CATransactionPayment_Type] FOREIGN KEY ([CAPAYMENTTYPEID]) REFERENCES [dbo].[CAPAYMENTTYPE] ([CAPAYMENTTYPEID]),
    CONSTRAINT [FK_CATransactionPayment_Users] FOREIGN KEY ([LASTCHANGEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID]),
    CONSTRAINT [FK_CATransPayment_PayMethod] FOREIGN KEY ([CAPAYMENTMETHODID]) REFERENCES [dbo].[CAPAYMENTMETHOD] ([CAPAYMENTMETHODID]),
    CONSTRAINT [FK_CATransPayment_Transaction] FOREIGN KEY ([CATRANSACTIONID]) REFERENCES [dbo].[CATRANSACTION] ([CATRANSACTIONID])
);


GO
CREATE NONCLUSTERED INDEX [IMPORT1]
    ON [dbo].[CATRANSACTIONPAYMENT]([CATRANSACTIONID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IMPORT2]
    ON [dbo].[CATRANSACTIONPAYMENT]([CAPAYMENTTYPEID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IMPORT3]
    ON [dbo].[CATRANSACTIONPAYMENT]([CAPAYMENTMETHODID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IMPORT4]
    ON [dbo].[CATRANSACTIONPAYMENT]([CAPAYMENTSTATUSID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [NCIDX_CATRANSACTIONPAYMENT_PAYMENTDATE_INCL]
    ON [dbo].[CATRANSACTIONPAYMENT]([PAYMENTDATE] ASC)
    INCLUDE([CAPAYMENTTYPEID], [CATRANSACTIONID], [PAYMENTAMOUNT]) WITH (FILLFACTOR = 90, PAD_INDEX = ON);


GO
CREATE NONCLUSTERED INDEX [NIDX_CATRANSACTIONPAYMENT_CATRANSACTIONID]
    ON [dbo].[CATRANSACTIONPAYMENT]([CATRANSACTIONID] ASC)
    INCLUDE([CATRANSACTIONPAYMENTID], [PAYMENTDATE], [PAYMENTAMOUNT], [CAPAYMENTMETHODID]);


GO
CREATE TRIGGER [TG_CATRANSACTIONPAYMENT_DELETE_ELASTIC_PAYMENT] ON CATRANSACTIONPAYMENT
	AFTER DELETE
AS
BEGIN
	SET NOCOUNT ON;
	
	INSERT INTO [ELASTICSEARCHOBJECT]
	 ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID(),
		[Deleted].[CATRANSACTIONPAYMENTID],
		'EnerGovBusiness.Cashier.CATransactionPayment',
		[Deleted].[ROWVERSION],
		GETDATE(),
		NULL,
		3,
		(SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Deleted];

END
GO

CREATE TRIGGER [TG_CATRANSACTIONPAYMENT_INSERT_ELASTIC_PAYMENT] ON CATRANSACTIONPAYMENT
	AFTER INSERT
AS
BEGIN
	SET NOCOUNT ON;
	
	INSERT INTO [ELASTICSEARCHOBJECT]
	 ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID(),
		[Inserted].[CATRANSACTIONPAYMENTID],
		'EnerGovBusiness.Cashier.CATransactionPayment',
		[Inserted].[ROWVERSION],
		GETDATE(),
		NULL,
		1,
		(SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [INSERTED];

END