CREATE TABLE [dbo].[CATRANSACTIONFEEARPOSTING] (
    [CATRANSACTIONFEEARPOSTINGID] CHAR (36) NOT NULL,
    [CATRANSACTIONFEEID]          CHAR (36) NOT NULL,
    [CATRANSACTIONARPOSTINGID]    CHAR (36) NOT NULL,
    CONSTRAINT [PK_CATRANSACTIONFEEARPOSTING] PRIMARY KEY CLUSTERED ([CATRANSACTIONFEEARPOSTINGID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_CATRFEEARPOST_ARPOST] FOREIGN KEY ([CATRANSACTIONARPOSTINGID]) REFERENCES [dbo].[CATRANSACTIONARPOSTING] ([CATRANSACTIONARPOSTINGID]),
    CONSTRAINT [FK_CATRFEEARPOST_TRFEE] FOREIGN KEY ([CATRANSACTIONFEEID]) REFERENCES [dbo].[CATRANSACTIONFEE] ([CATRANSACTIONFEEID])
);


GO
CREATE NONCLUSTERED INDEX [CATRANSACTIONFEEARPOSTING_CATRANSACTIONFEEID]
    ON [dbo].[CATRANSACTIONFEEARPOSTING]([CATRANSACTIONFEEID] ASC)
    INCLUDE([CATRANSACTIONARPOSTINGID]);

