CREATE TABLE [dbo].[CATRANSACTIONSTATUS] (
    [CATRANSACTIONSTATUSID] INT            NOT NULL,
    [NAME]                  NVARCHAR (50)  NOT NULL,
    [DESCRIPTION]           NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_CATransactionStatus] PRIMARY KEY CLUSTERED ([CATRANSACTIONSTATUSID] ASC) WITH (FILLFACTOR = 90)
);

