CREATE TABLE [dbo].[CATRANSACTIONARPOSTING] (
    [CATRANSACTIONARPOSTINGID] CHAR (36)      NOT NULL,
    [DEBITACCOUNTID]           CHAR (36)      NULL,
    [DEBITACCOUNTNUMBER]       NVARCHAR (100) NULL,
    [CREDITACCOUNTID]          CHAR (36)      NULL,
    [CREDITACCOUNTNUMBER]      NVARCHAR (100) NULL,
    [POSTINGDATE]              DATETIME       NOT NULL,
    [POSTINGAMOUNT]            MONEY          NOT NULL,
    [CATRANSACTIONARTYPEID]    INT            NULL,
    [POSTEDBYUSER]             CHAR (36)      NULL,
    [EXPORTEDON]               DATETIME       NULL,
    CONSTRAINT [PK_CATRANSACTIONARPOSTING] PRIMARY KEY CLUSTERED ([CATRANSACTIONARPOSTINGID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_CATARPOSTING_USER] FOREIGN KEY ([POSTEDBYUSER]) REFERENCES [dbo].[USERS] ([SUSERGUID]),
    CONSTRAINT [FK_CATRANARPOST_TRANTYPE] FOREIGN KEY ([CATRANSACTIONARTYPEID]) REFERENCES [dbo].[CATRANSACTIONARTYPE] ([CATRANSACTIONARTYPEID])
);


GO
CREATE NONCLUSTERED INDEX [CATRANSACTIONARPOSTING_EXPORT]
    ON [dbo].[CATRANSACTIONARPOSTING]([POSTINGDATE] ASC, [EXPORTEDON] ASC) WITH (FILLFACTOR = 90);

