CREATE TABLE [dbo].[CCAPIRECEIPTS] (
    [RECEIPTID]     CHAR (36)      NOT NULL,
    [ORDERNUMBER]   NVARCHAR (100) NOT NULL,
    [AMOUNT]        MONEY          NOT NULL,
    [PAYMENTMETHOD] NVARCHAR (100) NULL,
    [AUTHCODE]      NVARCHAR (100) NOT NULL,
    [RECEIPTOBJECT] NVARCHAR (MAX) NOT NULL,
    [ERRORMESSAGE]  NVARCHAR (MAX) NULL,
    [STATUSCODE]    INT            NOT NULL,
    [PROCESSED]     BIT            NOT NULL,
    [CREATEDATE]    DATETIME       NOT NULL,
    CONSTRAINT [PK_CCAPIRECEIPTS] PRIMARY KEY CLUSTERED ([RECEIPTID] ASC)
);

