CREATE TABLE [dbo].[CCAPIPAYMENTREQUESTS] (
    [PAYMENTREQUESTID]     CHAR (36)      NOT NULL,
    [CUSTOMEREMAILADDRESS] NVARCHAR (200) NULL,
    [BILLINGNAME]          NVARCHAR (200) NULL,
    [BILLINGSTREETADDRESS] NVARCHAR (200) NULL,
    [ZIPCODE]              NVARCHAR (50)  NULL,
    [CASENUMBER]           NVARCHAR (50)  NULL,
    [CREATEDDATE]          DATETIME       NOT NULL,
    CONSTRAINT [PK_CCAPIPAYMENTREQUESTS] PRIMARY KEY CLUSTERED ([PAYMENTREQUESTID] ASC)
);

