CREATE TABLE [dbo].[CITIZENREQUESTNOTE] (
    [REQUESTNOTEID]    CHAR (36)      NOT NULL,
    [CITIZENREQUESTID] CHAR (36)      NOT NULL,
    [TEXT]             NVARCHAR (MAX) NULL,
    [CREATEDBY]        CHAR (36)      NULL,
    [CREATEDDATE]      DATETIME       NULL,
    CONSTRAINT [PK_CitizenRequestNote] PRIMARY KEY CLUSTERED ([REQUESTNOTEID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_CitizenRequestNote_CitizenRequest] FOREIGN KEY ([CITIZENREQUESTID]) REFERENCES [dbo].[CITIZENREQUEST] ([CITIZENREQUESTID]),
    CONSTRAINT [FK_CitizenRequestNote_Users] FOREIGN KEY ([CREATEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);

