CREATE TABLE [dbo].[CITIZENREQUESTATTACHEDCASELIST] (
    [CITIZENREQUESTID]              CHAR (36)     NULL,
    [REQUESTATTACHEDCASETYPEID]     CHAR (36)     NULL,
    [ATTACHEDCASEID]                CHAR (36)     NULL,
    [CITIZENREQUESTATTACHCASELSTID] CHAR (36)     CONSTRAINT [DF_CitizenRequestAttachedCaseList_CitizenRequestAttachedCaseListID] DEFAULT (newid()) NOT NULL,
    [ATTACHEDCASENUMBER]            NVARCHAR (50) NULL,
    CONSTRAINT [PK_CitizenRequestAttachedCaseList] PRIMARY KEY CLUSTERED ([CITIZENREQUESTATTACHCASELSTID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_CitizenRequestAttachedCaseList_CitizenRequest] FOREIGN KEY ([CITIZENREQUESTID]) REFERENCES [dbo].[CITIZENREQUEST] ([CITIZENREQUESTID]),
    CONSTRAINT [FK_CitizenRequestAttachedCaseList_CitizenRequestAttachedCaseType] FOREIGN KEY ([REQUESTATTACHEDCASETYPEID]) REFERENCES [dbo].[CITIZENREQUESTATTACHEDCASETYPE] ([REQUESTATTACHEDCASETYPEID])
);


GO
CREATE NONCLUSTERED INDEX [NCIDX_CITIZENREQUESTATTACHEDCASELIST_CITIZENREQUESTID]
    ON [dbo].[CITIZENREQUESTATTACHEDCASELIST]([CITIZENREQUESTID] ASC) WITH (FILLFACTOR = 90, PAD_INDEX = ON);

