CREATE TABLE [dbo].[CITIZENREQUESTEVENTQUEUE] (
    [CITIZENREQUESTEVENTQUEUEID]  BIGINT        IDENTITY (1, 1) NOT NULL,
    [CITIZENREQUESTID]            CHAR (36)     NOT NULL,
    [REQUESTNUMBER]               NVARCHAR (50) NOT NULL,
    [CITIZENREQUESTEVENTTYPEID]   INT           NOT NULL,
    [EVENTSTATUSID]               INT           NOT NULL,
    [CREATEDDATE]                 DATETIME      NOT NULL,
    [PROCESSEDDATE]               DATETIME      NULL,
    [CITIZENREQUESTLASTCHANGEDBY] CHAR (36)     NULL,
    CONSTRAINT [PK_CITIZENREQUESTEVENTQUEUE] PRIMARY KEY CLUSTERED ([CITIZENREQUESTEVENTQUEUEID] ASC),
    CONSTRAINT [FK_CitizenRequestEventQueue_CitizenRequestEventType] FOREIGN KEY ([CITIZENREQUESTEVENTTYPEID]) REFERENCES [dbo].[CITIZENREQUESTEVENTTYPE] ([CITIZENREQUESTEVENTTYPEID]),
    CONSTRAINT [FK_CitizenRequestEventQueue_EventStatus] FOREIGN KEY ([EVENTSTATUSID]) REFERENCES [dbo].[EVENTSTATUS] ([EVENTSTATUSID]),
    CONSTRAINT [FK_CitizenRequestEventQueue_Users] FOREIGN KEY ([CITIZENREQUESTLASTCHANGEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);


GO
CREATE NONCLUSTERED INDEX [CITIZENREQUESTEVENTQUEUE_PROCESSEDDATE]
    ON [dbo].[CITIZENREQUESTEVENTQUEUE]([PROCESSEDDATE] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_CITIZENREQUESTEVENTQUEUE_CREATEDDATE]
    ON [dbo].[CITIZENREQUESTEVENTQUEUE]([CREATEDDATE] ASC);

