CREATE TABLE [dbo].[CMCODEALLOWEDACTIVITY] (
    [CMCODEALLOWEDACTIVITYID] CHAR (36) NOT NULL,
    [CMCASETYPEID]            CHAR (36) NOT NULL,
    [CMCODEACTIVITYTYPEID]    CHAR (36) NOT NULL,
    CONSTRAINT [PK_CMCodeAllowedActivity] PRIMARY KEY CLUSTERED ([CMCODEALLOWEDACTIVITYID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_CMAllowedAct_CMActType] FOREIGN KEY ([CMCODEACTIVITYTYPEID]) REFERENCES [dbo].[CMCODEACTIVITYTYPE] ([CMCODEACTIVITYTYPEID]),
    CONSTRAINT [FK_CMAllowedAct_CMCaseType] FOREIGN KEY ([CMCASETYPEID]) REFERENCES [dbo].[CMCASETYPE] ([CMCASETYPEID])
);


GO

CREATE TRIGGER [dbo].[TG_CMCODEALLOWEDACTIVITY_DELETE] 
   ON  [dbo].[CMCODEALLOWEDACTIVITY]
   AFTER DELETE
AS 
BEGIN	
	SET NOCOUNT ON;	
	INSERT INTO [HISTORYSYSTEMSETUP]
	(
		[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
	)
	SELECT
			[CMCASETYPE].[CMCASETYPEID],
			[CMCASETYPE].[ROWVERSION],
			GETUTCDATE(),
			(SELECT dbo.UFN_GET_USERID_FROM_CONTEXT_INFO()),			
			'Code Case Type Activity Type Deleted',
			'',
			'',			
			'Code Case Type (' + [CMCASETYPE].[NAME] + '), Activity Type Name (' + [CMCODEACTIVITYTYPE].[NAME] +')',
			'9C623A25-C14D-4380-B8E1-3713F569CE94',
			3,
			0,
			[CMCODEACTIVITYTYPE].[NAME]
	FROM	[deleted]
	INNER JOIN  CMCASETYPE ON CMCASETYPE.CMCASETYPEID = [deleted].CMCASETYPEID
	INNER JOIN CMCODEACTIVITYTYPE WITH (NOLOCK) ON CMCODEACTIVITYTYPE.CMCODEACTIVITYTYPEID = [deleted].CMCODEACTIVITYTYPEID
END
GO

CREATE TRIGGER [dbo].[TG_CMCODEALLOWEDACTIVITY_INSERT]
   ON  [dbo].[CMCODEALLOWEDACTIVITY] 
   AFTER INSERT
AS
BEGIN
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
    (
        [ID],
        [ROWVERSION],
        [CHANGEDON],
        [CHANGEDBY],
        [FIELDNAME],
        [OLDVALUE],
        [NEWVALUE],
        [ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT 
        [CMCASETYPE].[CMCASETYPEID], 
        [CMCASETYPE].[ROWVERSION],
        GETUTCDATE(),
        [CMCASETYPE].[LASTCHANGEDBY],
        'Code Case Type Activity Type Added',
        '',
        '',
		'Code Case Type (' + [CMCASETYPE].[NAME] + '), Activity Type Name (' + [CMCODEACTIVITYTYPE].[NAME] +')',
		'9C623A25-C14D-4380-B8E1-3713F569CE94',
		1,
		0,
		[CMCODEACTIVITYTYPE].[NAME]
    FROM [inserted]
	INNER JOIN CMCASETYPE ON CMCASETYPE.CMCASETYPEID = [inserted].CMCASETYPEID
	INNER JOIN CMCODEACTIVITYTYPE WITH (NOLOCK) ON CMCODEACTIVITYTYPE.CMCODEACTIVITYTYPEID = [inserted].CMCODEACTIVITYTYPEID
END