CREATE TABLE [dbo].[CMCODECASEHOLDTYPEREF] (
    [CMCODECASEHOLDTYPEID] CHAR (36) NOT NULL,
    [CMCASETYPEID]         CHAR (36) NOT NULL,
    [HOLDSETUPID]          CHAR (36) NOT NULL,
    CONSTRAINT [PK_CMCODECASEHOLDTYPEREF] PRIMARY KEY CLUSTERED ([CMCODECASEHOLDTYPEID] ASC),
    CONSTRAINT [FK_CMCODECASEHOLDTYPEREF_COTYPE] FOREIGN KEY ([CMCASETYPEID]) REFERENCES [dbo].[CMCASETYPE] ([CMCASETYPEID]),
    CONSTRAINT [FK_CMCODECASEHOLDTYPEREF_HOTYPE] FOREIGN KEY ([HOLDSETUPID]) REFERENCES [dbo].[HOLDTYPESETUPS] ([HOLDSETUPID])
);


GO
CREATE NONCLUSTERED INDEX [IX_CMCODECASEHOLDTYPEREF_CMCASETYPEID]
    ON [dbo].[CMCODECASEHOLDTYPEREF]([CMCASETYPEID] ASC);


GO

CREATE TRIGGER [dbo].[TG_CMCODECASEHOLDTYPEREF_INSERT]
   ON  [dbo].[CMCODECASEHOLDTYPEREF]
   AFTER INSERT
AS 
BEGIN	
	SET NOCOUNT ON;	
	INSERT INTO [HISTORYSYSTEMSETUP]
    (
        [ID],
        [ROWVERSION],
        [CHANGEDON],
        [CHANGEDBY],
        [FIELDNAME],
        [OLDVALUE],
        [NEWVALUE],
        [ADDITIONALINFO]
    )
	SELECT 
        [CMCASETYPE].[CMCASETYPEID], 
        [CMCASETYPE].[ROWVERSION],
        GETUTCDATE(),
        [CMCASETYPE].[LASTCHANGEDBY],	
        'Code Case Type Hold Type Added',
        '',
        '',       
		'Code Case Type (' + [CMCASETYPE].[NAME] + '), Hold Type Name (' + HOLDTYPESETUPS.[NAME] +')'
    FROM [inserted]
	INNER JOIN CMCASETYPE ON CMCASETYPE.CMCASETYPEID = [inserted].CMCASETYPEID
	INNER JOIN HOLDTYPESETUPS WITH (NOLOCK) ON HOLDTYPESETUPS.HOLDSETUPID = [inserted].HOLDSETUPID
END
GO

CREATE TRIGGER [dbo].[TG_CMCODECASEHOLDTYPEREF_DELETE]  
   ON  [dbo].[CMCODECASEHOLDTYPEREF] 
   AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
	(
		[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO]
	)
	SELECT
			[CMCASETYPE].[CMCASETYPEID],
			[CMCASETYPE].[ROWVERSION],
			GETUTCDATE(),			
			(SELECT dbo.UFN_GET_USERID_FROM_CONTEXT_INFO()),
			'Code Case Type Hold Type Deleted',
			'',
			'',
			'Code Case Type (' + [CMCASETYPE].[NAME] + '), Hold Type Name (' + HOLDTYPESETUPS.[NAME] +')'
	FROM	[deleted]
	INNER JOIN  CMCASETYPE ON CMCASETYPE.CMCASETYPEID = [deleted].CMCASETYPEID
	INNER JOIN HOLDTYPESETUPS WITH (NOLOCK) ON HOLDTYPESETUPS.HOLDSETUPID = [deleted].HOLDSETUPID
END