CREATE TABLE [dbo].[CMCODECASECONTACTTYPEREF] (
    [CONTACTTYPEEXTID]        CHAR (36) NOT NULL,
    [CMCODECASECONTACTTYPEID] CHAR (36) NOT NULL,
    [CONTACTTYPEGROUP]        INT       NULL,
    [ISREQUIRED]              BIT       CONSTRAINT [DF_CMCODECASECONTACTTYPEREF_REQ] DEFAULT ((0)) NOT NULL,
    [OBJCLASSID]              CHAR (36) NULL,
    [OBJTYPEID]               CHAR (36) NULL,
    [OBJMODULEID]             INT       NOT NULL,
    CONSTRAINT [PK_CMCODECASECONTACTTYPEREF] PRIMARY KEY CLUSTERED ([CONTACTTYPEEXTID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_CMCODECASECONTACTTYPEREF_COTYPE] FOREIGN KEY ([CMCODECASECONTACTTYPEID]) REFERENCES [dbo].[CMCODECASECONTACTTYPE] ([CMCODECASECONTACTTYPEID])
);


GO

CREATE TRIGGER [dbo].[TG_CMCODECASECONTACTTYPEREF_DELETE]  
   ON  [dbo].[CMCODECASECONTACTTYPEREF] 
   AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
	(
		[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
	)
	SELECT
			[CMCASETYPE].[CMCASETYPEID],
			[CMCASETYPE].[ROWVERSION],
			GETUTCDATE(),			
			(SELECT dbo.UFN_GET_USERID_FROM_CONTEXT_INFO()),
			'Code Case Type Contact Type Deleted',
			'',
			'',
			'Code Case Type (' + [CMCASETYPE].[NAME] + '), Contact Type Name (' + CMCODECASECONTACTTYPE.[NAME] +')',
			'9C623A25-C14D-4380-B8E1-3713F569CE94',
			3,
			0,
			CMCODECASECONTACTTYPE.[NAME]
	FROM	[deleted]
	INNER JOIN  CMCASETYPE ON CMCASETYPE.CMCASETYPEID = [deleted].OBJTYPEID
	INNER JOIN CMCODECASECONTACTTYPE WITH (NOLOCK) ON CMCODECASECONTACTTYPE.CMCODECASECONTACTTYPEID = [deleted].CMCODECASECONTACTTYPEID
END
GO

CREATE TRIGGER [dbo].[TG_CMCODECASECONTACTTYPEREF_INSERT]
   ON  [dbo].[CMCODECASECONTACTTYPEREF]
   AFTER INSERT
AS 
BEGIN	
	SET NOCOUNT ON;	
	INSERT INTO [HISTORYSYSTEMSETUP]
    (
        [ID],
        [ROWVERSION],
        [CHANGEDON],
        [CHANGEDBY],
        [FIELDNAME],
        [OLDVALUE],
        [NEWVALUE],
        [ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT 
        [CMCASETYPE].[CMCASETYPEID], 
        [CMCASETYPE].[ROWVERSION],
        GETUTCDATE(),
        [CMCASETYPE].[LASTCHANGEDBY],	
        'Code Case Type Contact Type Added', 
        '',
        '',       
		'Code Case Type (' + [CMCASETYPE].[NAME] + '), Contact Type Name (' + CMCODECASECONTACTTYPE.[NAME] +')',
		'9C623A25-C14D-4380-B8E1-3713F569CE94',
		1,
		0,
		CMCODECASECONTACTTYPE.[NAME]
    FROM [inserted]
	INNER JOIN CMCASETYPE ON CMCASETYPE.CMCASETYPEID = [inserted].OBJTYPEID
	INNER JOIN CMCODECASECONTACTTYPE WITH (NOLOCK) ON CMCODECASECONTACTTYPE.CMCODECASECONTACTTYPEID = [inserted].CMCODECASECONTACTTYPEID
END
GO

CREATE TRIGGER [dbo].[TG_CMCODECASECONTACTTYPEREF_UPDATE]
   ON  [dbo].[CMCODECASECONTACTTYPEREF] 
   AFTER UPDATE
AS 
BEGIN	
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
    (	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT 
			[CMCASETYPE].[CMCASETYPEID],
			[CMCASETYPE].[ROWVERSION],
			GETUTCDATE(),
			[CMCASETYPE].[LASTCHANGEDBY],
			'Required Flag',
			CASE [deleted].[ISREQUIRED] WHEN 1 THEN 'Yes' WHEN 0 THEN 'No'  ELSE '[none]' END,			
			CASE [inserted].[ISREQUIRED] WHEN 1 THEN 'Yes' WHEN 0 THEN 'No'  ELSE '[none]' END,						
			'Code Case Type (' + [CMCASETYPE].[NAME] + '), Contact Type Name (' + [CMCODECASECONTACTTYPE].[NAME] +')',
			'9C623A25-C14D-4380-B8E1-3713F569CE94',
			2,
			0,
			[CMCODECASECONTACTTYPE].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].OBJTYPEID = [inserted].OBJTYPEID
			INNER JOIN CMCASETYPE ON CMCASETYPE.CMCASETYPEID = [inserted].OBJTYPEID
			INNER JOIN CMCODECASECONTACTTYPE WITH (NOLOCK) ON CMCODECASECONTACTTYPE.CMCODECASECONTACTTYPEID = [inserted].CMCODECASECONTACTTYPEID
	WHERE	[deleted].[ISREQUIRED] <> [inserted].[ISREQUIRED]
	UNION ALL

	SELECT 
			[CMCASETYPE].[CMCASETYPEID],
			[CMCASETYPE].[ROWVERSION],
			GETUTCDATE(),
			[CMCASETYPE].[LASTCHANGEDBY],
			'Set',
			CONVERT(varchar(Max),ISNULL([deleted].[CONTACTTYPEGROUP],'[none]')),
			CONVERT(varchar(Max),ISNULL([inserted].[CONTACTTYPEGROUP],'[none]')),						
			'Code Case Type (' + [CMCASETYPE].[NAME] + '), Contact Type Name (' + [CMCODECASECONTACTTYPE].[NAME] +')',
			'9C623A25-C14D-4380-B8E1-3713F569CE94',
			2,
			0,
			[CMCODECASECONTACTTYPE].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].OBJTYPEID = [inserted].OBJTYPEID
			INNER JOIN CMCASETYPE ON CMCASETYPE.CMCASETYPEID = [inserted].OBJTYPEID
			INNER JOIN CMCODECASECONTACTTYPE WITH (NOLOCK) ON CMCODECASECONTACTTYPE.CMCODECASECONTACTTYPEID = [inserted].CMCODECASECONTACTTYPEID
	WHERE	ISNULL([deleted].[CONTACTTYPEGROUP],'') <> ISNULL([inserted].[CONTACTTYPEGROUP],'')
END