CREATE TABLE [dbo].[CMCODE] (
    [CMCODEID]                   CHAR (36)      NOT NULL,
    [DESCRIPTION]                NVARCHAR (MAX) NOT NULL,
    [CODENUMBER]                 NVARCHAR (50)  NOT NULL,
    [CMCODECATEGORYID]           CHAR (36)      NOT NULL,
    [CORRECTIVEACTION]           NVARCHAR (MAX) NULL,
    [WFACTIONGROUPID]            CHAR (36)      NULL,
    [CUSTOMFIELDLAYOUTID]        CHAR (36)      NULL,
    [COMPLIANCEDAYSUNTILDUEHIGH] INT            DEFAULT ((0)) NOT NULL,
    [CAFEETEMPLATEID]            CHAR (36)      NULL,
    [COMPLIANCEDAYSUNTILDUEMED]  INT            NULL,
    [COMPLIANCEDAYSUNTILDUELOW]  INT            NULL,
    [DEFAULTVIOLATIONPRIORITYID] CHAR (36)      NULL,
    [DEFAULTCMCOURTSTATUSID]     CHAR (36)      NULL,
    [LASTCHANGEDBY]              CHAR (36)      NULL,
    [LASTCHANGEDON]              DATETIME       CONSTRAINT [DF_CMCODE_LastChangedOn] DEFAULT (getutcdate()) NOT NULL,
    [ROWVERSION]                 INT            CONSTRAINT [DF_CMCODE_RowVersion] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_Code] PRIMARY KEY CLUSTERED ([CMCODEID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_CMCode_CMCodeCategoryID] FOREIGN KEY ([CMCODECATEGORYID]) REFERENCES [dbo].[CMCODECATEGORY] ([CMCODECATEGORYID]),
    CONSTRAINT [FK_CMCode_CourtStatus] FOREIGN KEY ([DEFAULTCMCOURTSTATUSID]) REFERENCES [dbo].[CMCOURTSTATUS] ([CMCOURTSTATUSID]),
    CONSTRAINT [FK_CMCode_CustomFieldLayout] FOREIGN KEY ([CUSTOMFIELDLAYOUTID]) REFERENCES [dbo].[CUSTOMFIELDLAYOUT] ([GCUSTOMFIELDLAYOUTS]),
    CONSTRAINT [FK_CMCode_FeeTemplate] FOREIGN KEY ([CAFEETEMPLATEID]) REFERENCES [dbo].[CAFEETEMPLATE] ([CAFEETEMPLATEID]),
    CONSTRAINT [FK_CMCODE_USERS] FOREIGN KEY ([LASTCHANGEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID]),
    CONSTRAINT [FK_CMCode_ViolationPriority] FOREIGN KEY ([DEFAULTVIOLATIONPRIORITYID]) REFERENCES [dbo].[CMCODEVIOLATIONPRIORITY] ([CMCODEVIOLATIONPRIORITYID]),
    CONSTRAINT [FK_CMCode_WFActionGroup] FOREIGN KEY ([WFACTIONGROUPID]) REFERENCES [dbo].[WFACTIONGROUP] ([WFACTIONGROUPID])
);


GO
CREATE TRIGGER [dbo].[TG_CMCODE_INSERT]
   ON  [dbo].[CMCODE]
   AFTER INSERT
AS 
BEGIN	
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
    (
        [ID],
        [ROWVERSION],
        [CHANGEDON],
        [CHANGEDBY],
        [FIELDNAME],
        [OLDVALUE],
        [NEWVALUE],
        [ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT 
        [inserted].[CMCODEID], 
        [inserted].[ROWVERSION],
        GETUTCDATE(),
        [inserted].[LASTCHANGEDBY],
        'Code Added',
        '',
        '',
        'Code (' + [inserted].[CODENUMBER] + ')',
		'3FAFB6FE-439F-48B0-978D-748BE8F5D52C',
		1,
		1,
		[inserted].[CODENUMBER]
    FROM [inserted]
END
GO

CREATE TRIGGER [dbo].[TG_CMCODE_UPDATE] 
   ON  [dbo].[CMCODE]   
   AFTER UPDATE
AS 
BEGIN
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
    (	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT 
			[inserted].[CMCODEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Code Number',
			[deleted].[CODENUMBER],
			[inserted].[CODENUMBER],
			'Code (' + [inserted].[CODENUMBER] + ')',
			'3FAFB6FE-439F-48B0-978D-748BE8F5D52C',
			2,
			1,
			[inserted].[CODENUMBER]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].CMCODEID = [inserted].CMCODEID
	WHERE	[deleted].[CODENUMBER] <> [inserted].[CODENUMBER]
	UNION ALL

	SELECT 
			[inserted].[CMCODEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Description',
			[deleted].[DESCRIPTION],
			[inserted].[DESCRIPTION],
			'Code (' + [inserted].[CODENUMBER] + ')',
			'3FAFB6FE-439F-48B0-978D-748BE8F5D52C',
			2,
			1,
			[inserted].[CODENUMBER]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].CMCODEID = [inserted].CMCODEID
	WHERE	[deleted].[DESCRIPTION] <> [inserted].[DESCRIPTION]
	UNION ALL

	SELECT 
			[inserted].[CMCODEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Corrective Action',
			ISNULL([deleted].[CORRECTIVEACTION],'[none]'),		
			ISNULL([inserted].[CORRECTIVEACTION],'[none]'),
			'Code (' + [inserted].[CODENUMBER] + ')',
			'3FAFB6FE-439F-48B0-978D-748BE8F5D52C',
			2,
			1,
			[inserted].[CODENUMBER]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].CMCODEID = [inserted].CMCODEID
	WHERE	ISNULL([deleted].[CORRECTIVEACTION],'') <> ISNULL([inserted].[CORRECTIVEACTION],'')
	UNION ALL

	SELECT 
			[inserted].[CMCODEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Compliance Days Until Due (High)',
			CONVERT(NVARCHAR(MAX),[deleted].[COMPLIANCEDAYSUNTILDUEHIGH]),
			CONVERT(NVARCHAR(MAX),[inserted].[COMPLIANCEDAYSUNTILDUEHIGH]),
			'Code (' + [inserted].[CODENUMBER] + ')',
			'3FAFB6FE-439F-48B0-978D-748BE8F5D52C',
			2,
			1,
			[inserted].[CODENUMBER]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].CMCODEID = [inserted].CMCODEID
	WHERE	[deleted].[COMPLIANCEDAYSUNTILDUEHIGH] <> [inserted].[COMPLIANCEDAYSUNTILDUEHIGH]
	UNION ALL

	SELECT 
			[inserted].[CMCODEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Compliance Days Until Due (Medium)',
			CASE WHEN [deleted].[COMPLIANCEDAYSUNTILDUEMED] IS NULL THEN '[none]' ELSE CONVERT(NVARCHAR(MAX), [deleted].[COMPLIANCEDAYSUNTILDUEMED]) END,
			CASE WHEN [inserted].[COMPLIANCEDAYSUNTILDUEMED] IS NULL THEN '[none]' ELSE CONVERT(NVARCHAR(MAX), [inserted].[COMPLIANCEDAYSUNTILDUEMED]) END,
			'Code (' + [inserted].[CODENUMBER] + ')',
			'3FAFB6FE-439F-48B0-978D-748BE8F5D52C',
			2,
			1,
			[inserted].[CODENUMBER]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].CMCODEID = [inserted].CMCODEID
	WHERE	ISNULL([deleted].[COMPLIANCEDAYSUNTILDUEMED],'') <> ISNULL([inserted].[COMPLIANCEDAYSUNTILDUEMED],'')
	UNION ALL

	SELECT 
			[inserted].[CMCODEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Compliance Days Until Due (Low)',
			CASE WHEN [deleted].[COMPLIANCEDAYSUNTILDUELOW] IS NULL THEN '[none]' ELSE CONVERT(NVARCHAR(MAX), [deleted].[COMPLIANCEDAYSUNTILDUELOW]) END,
			CASE WHEN [inserted].[COMPLIANCEDAYSUNTILDUELOW] IS NULL THEN '[none]' ELSE CONVERT(NVARCHAR(MAX), [inserted].[COMPLIANCEDAYSUNTILDUELOW]) END,			
			'Code (' + [inserted].[CODENUMBER] + ')',
			'3FAFB6FE-439F-48B0-978D-748BE8F5D52C',
			2,
			1,
			[inserted].[CODENUMBER]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].CMCODEID = [inserted].CMCODEID
	WHERE	ISNULL([deleted].[COMPLIANCEDAYSUNTILDUELOW],'') <> ISNULL([inserted].[COMPLIANCEDAYSUNTILDUELOW],'')
	UNION ALL	

	SELECT
			[inserted].[CMCODEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Work Flow Action Group',
			ISNULL([WFACTIONGROUP_DELETED].[NAME],'[none]'),
			ISNULL([WFACTIONGROUP_INSERTED].[NAME],'[none]'),
			'Code (' + [inserted].[CODENUMBER] + ')',
			'3FAFB6FE-439F-48B0-978D-748BE8F5D52C',
			2,
			1,
			[inserted].[CODENUMBER]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CMCODEID] = [inserted].[CMCODEID]
			LEFT OUTER JOIN WFACTIONGROUP WFACTIONGROUP_DELETED WITH (NOLOCK) ON [deleted].WFACTIONGROUPID = [WFACTIONGROUP_DELETED].WFACTIONGROUPID
			LEFT OUTER JOIN WFACTIONGROUP WFACTIONGROUP_INSERTED WITH (NOLOCK) ON [inserted].WFACTIONGROUPID = [WFACTIONGROUP_INSERTED].WFACTIONGROUPID
	WHERE	ISNULL([deleted].[WFACTIONGROUPID],'') <> ISNULL([inserted].[WFACTIONGROUPID],'')
	UNION ALL

	SELECT
			[inserted].[CMCODEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Code Category',
			[CMCODECATEGORY_DELETED].[NAME],
			[CMCODECATEGORY_INSERTED].[NAME],
			'Code (' + [inserted].[CODENUMBER] + ')',
			'3FAFB6FE-439F-48B0-978D-748BE8F5D52C',
			2,
			1,
			[inserted].[CODENUMBER]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CMCODEID] = [inserted].[CMCODEID]
			INNER JOIN CMCODECATEGORY CMCODECATEGORY_DELETED WITH (NOLOCK) ON [deleted].CMCODECATEGORYID = [CMCODECATEGORY_DELETED].CMCODECATEGORYID
			INNER JOIN CMCODECATEGORY CMCODECATEGORY_INSERTED WITH (NOLOCK) ON [inserted].CMCODECATEGORYID = [CMCODECATEGORY_INSERTED].CMCODECATEGORYID
	WHERE	[deleted].[CMCODECATEGORYID] <> [inserted].[CMCODECATEGORYID]
	UNION ALL

	SELECT
			[inserted].[CMCODEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Default Violation Priority',
			ISNULL([CMCODEVIOLATIONPRIORITY_DELETED].[NAME],'[none]'),
			ISNULL([CMCODEVIOLATIONPRIORITY_INSERTED].[NAME],'[none]'),
			'Code (' + [inserted].[CODENUMBER] + ')',
			'3FAFB6FE-439F-48B0-978D-748BE8F5D52C',
			2,
			1,
			[inserted].[CODENUMBER]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CMCODEID] = [inserted].[CMCODEID]
			LEFT OUTER JOIN CMCODEVIOLATIONPRIORITY CMCODEVIOLATIONPRIORITY_DELETED WITH (NOLOCK) ON [deleted].DEFAULTVIOLATIONPRIORITYID = [CMCODEVIOLATIONPRIORITY_DELETED].CMCODEVIOLATIONPRIORITYID
			LEFT OUTER JOIN CMCODEVIOLATIONPRIORITY CMCODEVIOLATIONPRIORITY_INSERTED WITH (NOLOCK) ON [inserted].DEFAULTVIOLATIONPRIORITYID = [CMCODEVIOLATIONPRIORITY_INSERTED].CMCODEVIOLATIONPRIORITYID
	WHERE	ISNULL([deleted].[DEFAULTVIOLATIONPRIORITYID],'') <> ISNULL([inserted].[DEFAULTVIOLATIONPRIORITYID],'')
	UNION ALL

	SELECT
			[inserted].[CMCODEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Custom Field',
			ISNULL([CUSTOMFIELDLAYOUT_DELETED].[SNAME],'[none]'),
			ISNULL([CUSTOMFIELDLAYOUT_INSERTED].[SNAME],'[none]'),
			'Code (' + [inserted].[CODENUMBER] + ')',
			'3FAFB6FE-439F-48B0-978D-748BE8F5D52C',
			2,
			1,
			[inserted].[CODENUMBER]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CMCODEID] = [inserted].[CMCODEID]
			LEFT OUTER JOIN CUSTOMFIELDLAYOUT CUSTOMFIELDLAYOUT_DELETED WITH (NOLOCK) ON [deleted].CUSTOMFIELDLAYOUTID = [CUSTOMFIELDLAYOUT_DELETED].GCUSTOMFIELDLAYOUTS
			LEFT OUTER JOIN CUSTOMFIELDLAYOUT CUSTOMFIELDLAYOUT_INSERTED WITH (NOLOCK) ON [inserted].CUSTOMFIELDLAYOUTID = [CUSTOMFIELDLAYOUT_INSERTED].GCUSTOMFIELDLAYOUTS			
	WHERE	ISNULL([deleted].[CUSTOMFIELDLAYOUTID],'') <> ISNULL([inserted].[CUSTOMFIELDLAYOUTID],'')
	UNION ALL

	SELECT
			[inserted].[CMCODEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Fee Template',
			ISNULL([CAFEETEMPLATE_DELETED].[CAFEETEMPLATENAME],'[none]'),
			ISNULL([CAFEETEMPLATE_INSERTED].[CAFEETEMPLATENAME],'[none]'),
			'Code (' + [inserted].[CODENUMBER] + ')',
			'3FAFB6FE-439F-48B0-978D-748BE8F5D52C',
			2,
			1,
			[inserted].[CODENUMBER]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CMCODEID] = [inserted].[CMCODEID]
			LEFT OUTER JOIN CAFEETEMPLATE CAFEETEMPLATE_DELETED WITH (NOLOCK) ON [deleted].CAFEETEMPLATEID = [CAFEETEMPLATE_DELETED].CAFEETEMPLATEID
			LEFT OUTER JOIN CAFEETEMPLATE CAFEETEMPLATE_INSERTED WITH (NOLOCK) ON [inserted].CAFEETEMPLATEID = [CAFEETEMPLATE_INSERTED].CAFEETEMPLATEID
	WHERE	ISNULL([deleted].[CAFEETEMPLATEID],'') <> ISNULL([inserted].[CAFEETEMPLATEID],'')
	UNION ALL	

	SELECT
			[inserted].[CMCODEID],
			[inserted].[ROWVERSION],
			GETUTCDATE(),
			[inserted].[LASTCHANGEDBY],
			'Default Court Status',
			ISNULL([CMCOURTSTATUS_DELETED].[NAME],'[none]'),
			ISNULL([CMCOURTSTATUS_INSERTED].[NAME],'[none]'),
			'Code (' + [inserted].[CODENUMBER] + ')',
			'3FAFB6FE-439F-48B0-978D-748BE8F5D52C',
			2,
			1,
			[inserted].[CODENUMBER]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CMCODEID] = [inserted].[CMCODEID]
			LEFT OUTER JOIN CMCOURTSTATUS CMCOURTSTATUS_DELETED WITH (NOLOCK) ON [deleted].[DEFAULTCMCOURTSTATUSID] = [CMCOURTSTATUS_DELETED].CMCOURTSTATUSID
			LEFT OUTER JOIN CMCOURTSTATUS CMCOURTSTATUS_INSERTED WITH (NOLOCK) ON [inserted].[DEFAULTCMCOURTSTATUSID] = [CMCOURTSTATUS_INSERTED].CMCOURTSTATUSID
	WHERE	ISNULL([deleted].[DEFAULTCMCOURTSTATUSID],'') <> ISNULL([inserted].[DEFAULTCMCOURTSTATUSID],'')
END
GO

CREATE TRIGGER [dbo].[TG_CMCODE_DELETE] 
   ON  [dbo].[CMCODE]
   AFTER DELETE
AS 
BEGIN	
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
	(	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )SELECT
			[deleted].[CMCODEID],
			[deleted].[ROWVERSION],
			GETUTCDATE(),
			(SELECT dbo.UFN_GET_USERID_FROM_CONTEXT_INFO()),
			'Code Deleted',
			'',
			'',
			'Code (' + [deleted].[CODENUMBER] + ')',
			'3FAFB6FE-439F-48B0-978D-748BE8F5D52C',
			3,
			1,
			[deleted].[CODENUMBER]
	FROM	[deleted]
END