CREATE TABLE [dbo].[CMCONTACTTYPESYSTEM] (
    [CMCONTACTTYPESYSTEMID] INT           NOT NULL,
    [NAME]                  NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_CMContactTypeSystem] PRIMARY KEY CLUSTERED ([CMCONTACTTYPESYSTEMID] ASC) WITH (FILLFACTOR = 90)
);

