CREATE TABLE [dbo].[CONDITIONSCOPE] (
    [CONDITIONSCOPEID] INT            NOT NULL,
    [SCOPENAME]        NVARCHAR (255) NOT NULL,
    CONSTRAINT [PK_ConditionScope] PRIMARY KEY CLUSTERED ([CONDITIONSCOPEID] ASC) WITH (FILLFACTOR = 90)
);

