CREATE TABLE [dbo].[CONTACTCONFIRMSTATUS] (
    [CONTACTCONFIRMSTATUSID] INT           NOT NULL,
    [NAME]                   NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_CONTACTCONFIRMSTATUS] PRIMARY KEY CLUSTERED ([CONTACTCONFIRMSTATUSID] ASC) WITH (FILLFACTOR = 90)
);

