CREATE TABLE [dbo].[CONTACTTYPE] (
    [CONTACTTYPEID] CHAR (36)     NOT NULL,
    [NAME]          VARCHAR (50)  NULL,
    [DESCRIPTION]   VARCHAR (MAX) NULL,
    CONSTRAINT [PK_AMContactType] PRIMARY KEY CLUSTERED ([CONTACTTYPEID] ASC) WITH (FILLFACTOR = 90)
);

