CREATE TABLE [dbo].[CUSTOMSAVERFIREOCCUPANCYMS] (
    [ID]                        CHAR (36) NOT NULL,
    [CUSTOMFIELDID]             CHAR (36) NOT NULL,
    [CUSTOMFIELDPICKLISTITEMID] CHAR (36) NOT NULL,
    CONSTRAINT [PK_FIREOCCUPANCYMS] PRIMARY KEY NONCLUSTERED ([ID] ASC, [CUSTOMFIELDID] ASC, [CUSTOMFIELDPICKLISTITEMID] ASC),
    CONSTRAINT [FIREOCCUPANCYMS_CustomField] FOREIGN KEY ([CUSTOMFIELDID]) REFERENCES [dbo].[CUSTOMFIELD] ([GCUSTOMFIELD]),
    CONSTRAINT [FIREOCCUPANCYMS_CustomFieldPi] FOREIGN KEY ([CUSTOMFIELDPICKLISTITEMID]) REFERENCES [dbo].[CUSTOMFIELDPICKLISTITEM] ([GCUSTOMFIELDPICKLISTITEM])
);


GO
CREATE NONCLUSTERED INDEX [FIREOCCUPANCYMS_ID]
    ON [dbo].[CUSTOMSAVERFIREOCCUPANCYMS]([ID] ASC);

