CREATE TABLE [dbo].[CUSTOMSAVERINDLICENSE] (
    [ID] CHAR (36) NOT NULL,
    CONSTRAINT [PK_IndLicense] PRIMARY KEY NONCLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);


GO

CREATE TRIGGER [TG_CUSTOMSAVERINDLICENSE_UPDATE_ELASTIC] ON  CUSTOMSAVERINDLICENSE
   AFTER UPDATE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [ELASTICSEARCHOBJECT]
    ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID() ,
		[I].[ILLICENSEID] ,
        'EnerGovBusiness.IndividualLicense.License' ,
        [I].[ROWVERSION] ,
        GETDATE() ,
        NULL ,
        2 ,
        (SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Inserted]
	JOIN [ILLICENSE] AS [I] WITH (NOLOCK) ON [I].[ILLICENSEID] = [Inserted].[ID];

END
