CREATE TABLE [dbo].[CUSTOMSAVERDECISIONENGINEWS] (
    [ID]                         CHAR (36)       NOT NULL,
    [CUSTOMFIELDID]              CHAR (36)       NOT NULL,
    [CUSTOMFIELDWORKSHEETITEMID] CHAR (36)       NOT NULL,
    [NUMERICVALUE]               DECIMAL (15, 2) NULL,
    CONSTRAINT [PK_CUSTOMSAVERDECENGMGMTWS] PRIMARY KEY NONCLUSTERED ([ID] ASC, [CUSTOMFIELDID] ASC, [CUSTOMFIELDWORKSHEETITEMID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CUSTOMSAVERDEWS_CFWSI] FOREIGN KEY ([CUSTOMFIELDWORKSHEETITEMID]) REFERENCES [dbo].[CUSTOMFIELDWORKSHEETITEM] ([GCUSTOMFIELDWORKSHEETITEM]),
    CONSTRAINT [CUSTOMSAVERDEWS_CUSTFIELD] FOREIGN KEY ([CUSTOMFIELDID]) REFERENCES [dbo].[CUSTOMFIELD] ([GCUSTOMFIELD]),
    CONSTRAINT [CUSTOMSAVERDEWS_DECENG] FOREIGN KEY ([ID]) REFERENCES [dbo].[CUSTOMSAVERDECISIONENGINE] ([ID])
);

