CREATE TABLE [dbo].[CUSTOMSAVERPERMITMANAGEMENTMS] (
    [ID]                        CHAR (36) NOT NULL,
    [CUSTOMFIELDID]             CHAR (36) NOT NULL,
    [CUSTOMFIELDPICKLISTITEMID] CHAR (36) NOT NULL,
    CONSTRAINT [PK_PermitManagementMS] PRIMARY KEY NONCLUSTERED ([ID] ASC, [CUSTOMFIELDID] ASC, [CUSTOMFIELDPICKLISTITEMID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [PermitManagementMS_CFPLI] FOREIGN KEY ([CUSTOMFIELDPICKLISTITEMID]) REFERENCES [dbo].[CUSTOMFIELDPICKLISTITEM] ([GCUSTOMFIELDPICKLISTITEM]),
    CONSTRAINT [PermitManagementMS_CustomField] FOREIGN KEY ([CUSTOMFIELDID]) REFERENCES [dbo].[CUSTOMFIELD] ([GCUSTOMFIELD]),
    CONSTRAINT [PermitManagementMS_PermitManag] FOREIGN KEY ([ID]) REFERENCES [dbo].[CUSTOMSAVERPERMITMANAGEMENT] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [PermitManagementMS_ID]
    ON [dbo].[CUSTOMSAVERPERMITMANAGEMENTMS]([ID] ASC) WITH (FILLFACTOR = 80);


GO

CREATE TRIGGER [TG_CUSTOMSAVERPERMITMANAGEMENTMS_UPDATE_ELASTIC] ON  CUSTOMSAVERPERMITMANAGEMENTMS
   AFTER UPDATE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [ELASTICSEARCHOBJECT]
    ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID() ,
		[P].[PMPERMITID] ,
        'EnerGovBusiness.PermitManagement.Permit' ,
        [P].[ROWVERSION] ,
        GETDATE() ,
        NULL ,
        2 ,
        (SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Inserted]
	JOIN [PMPERMIT] AS [P] WITH (NOLOCK) ON [P].[PMPERMITID] = [Inserted].[ID];

END