CREATE TABLE [dbo].[CUSTOMFIELDWORKSHEET] (
    [GCUSTOMFIELDWORKSHEET] CHAR (36) NOT NULL,
    [FKGCUSTOMFIELD]        CHAR (36) NOT NULL,
    CONSTRAINT [PK_CUSTOMFIELDWORKSHEET] PRIMARY KEY CLUSTERED ([GCUSTOMFIELDWORKSHEET] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_CUSTFLDWORKSHEET_CUSTOM] FOREIGN KEY ([FKGCUSTOMFIELD]) REFERENCES [dbo].[CUSTOMFIELD] ([GCUSTOMFIELD])
);

