CREATE TABLE [dbo].[CUSTOMSAVERTBLCOL_MNY] (
    [CUSTOMSAVERTABLECOLUMNID] CHAR (36) NOT NULL,
    [OBJECTID]                 CHAR (36) NOT NULL,
    [MODULEID]                 INT       NOT NULL,
    [CURRENCYVALUE]            MONEY     NULL,
    [CFTABLECOLUMNREFID]       CHAR (36) NOT NULL,
    [ROWNUMBER]                INT       NOT NULL,
    CONSTRAINT [PK_CUSTOMSAVERTBLCOL_MNY] PRIMARY KEY CLUSTERED ([CUSTOMSAVERTABLECOLUMNID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_CFSAVERTBL_COLREF_MNY] FOREIGN KEY ([CFTABLECOLUMNREFID]) REFERENCES [dbo].[CUSTOMFIELDTABLECOLUMNREF] ([CUSTOMFIELDTABLECOLUMNREFID])
);


GO
CREATE NONCLUSTERED INDEX [IX_CUSTOMSAVOBJID_MNY]
    ON [dbo].[CUSTOMSAVERTBLCOL_MNY]([OBJECTID] ASC, [CFTABLECOLUMNREFID] ASC, [ROWNUMBER] ASC)
    INCLUDE([CURRENCYVALUE]);


GO
CREATE NONCLUSTERED INDEX [IX_CFTABLECOLUMNREFID_MNY]
    ON [dbo].[CUSTOMSAVERTBLCOL_MNY]([CFTABLECOLUMNREFID] ASC);

