CREATE TABLE [dbo].[CUSTOMSAVERPLANMANAGEMENT2] (
    [ID] CHAR (36) NOT NULL,
    CONSTRAINT [PK_PlanManagement2] PRIMARY KEY NONCLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);


GO

CREATE TRIGGER [TG_CUSTOMSAVERPLANMANAGEMENT2_UPDATE_ELASTIC] ON  CUSTOMSAVERPLANMANAGEMENT2
   AFTER UPDATE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [ELASTICSEARCHOBJECT]
    ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID() ,
		[P].[PLPLANID] ,
        'EnerGovBusiness.PlanManagement.Plan' ,
        [P].[ROWVERSION] ,
        GETDATE() ,
        NULL ,
        2 ,
        (SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Inserted]
	JOIN [PLPLAN] AS [P] WITH (NOLOCK) ON [P].[PLPLANID] = [Inserted].[ID]

	UNION ALL
	
	SELECT 
		NEWID(),
		[PLAPPLICATION].[PLAPPLICATIONID],
		'EnerGovBusiness.PlanManagement.Application',
		[PLAPPLICATION].[ROWVERSION],
		GETDATE() ,
        NULL ,
		2,
		(SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Inserted]
	JOIN [PLAPPLICATION] WITH (NOLOCK) ON [PLAPPLICATION].[PLAPPLICATIONID] = [Inserted].[ID];

END
