CREATE TABLE [dbo].[CUSTOMFIELDWORKSHEETITEM] (
    [GCUSTOMFIELDWORKSHEETITEM] CHAR (36)    NOT NULL,
    [FKGCUSTOMFIELDWORKSHEET]   CHAR (36)    NOT NULL,
    [SVALUE]                    VARCHAR (50) NOT NULL,
    [IORDER]                    INT          NOT NULL,
    CONSTRAINT [PK_CUSTOMFIELDWORKSHEETITEM] PRIMARY KEY CLUSTERED ([GCUSTOMFIELDWORKSHEETITEM] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_CUSTFLDWSITEM_CUSTFLDWS] FOREIGN KEY ([FKGCUSTOMFIELDWORKSHEET]) REFERENCES [dbo].[CUSTOMFIELDWORKSHEET] ([GCUSTOMFIELDWORKSHEET])
);


GO
CREATE NONCLUSTERED INDEX [IX_CUSTOMFIELDWORKSHEETITEM_FKGCUSTOMFIELDWORKSHEET]
    ON [dbo].[CUSTOMFIELDWORKSHEETITEM]([FKGCUSTOMFIELDWORKSHEET] ASC);


GO

CREATE TRIGGER [dbo].[TG_CUSTOMFIELDWORKSHEETITEM_DELETE]  
    ON  [dbo].[CUSTOMFIELDWORKSHEETITEM]
   AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
	(
		[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
	)
	SELECT 
        [CUSTOMFIELDLAYOUT].[GCUSTOMFIELDLAYOUTS], 
        [CUSTOMFIELDLAYOUT].[ROWVERSION],
        GETUTCDATE(),
        [CUSTOMFIELDLAYOUT].[LASTCHANGEDBY],	
        'Custom Field Layout Worksheet Item Deleted',
        '',
        '',       
		'Custom Field Layout (' + [CUSTOMFIELDLAYOUT].[SNAME] + '), Field (' + [CUSTOMFIELD].[SCUSTOMFIELD] +'), Item (' + [deleted].[SVALUE] +')',
        'CCD23415-9668-462D-AFCC-3794BBAB9ADB',
		3,
		0,
		[deleted].[SVALUE]
    FROM [deleted]
    INNER JOIN [CUSTOMFIELDWORKSHEET] ON [CUSTOMFIELDWORKSHEET].[GCUSTOMFIELDWORKSHEET] = [deleted].[FKGCUSTOMFIELDWORKSHEET]
	INNER JOIN [CUSTOMFIELD] ON [CUSTOMFIELD].[GCUSTOMFIELD] = [CUSTOMFIELDWORKSHEET].[FKGCUSTOMFIELD]
    INNER JOIN [CUSTOMFIELDOBJECT] ON [CUSTOMFIELDOBJECT].[GCUSTOMFIELD] = [CUSTOMFIELD].[GCUSTOMFIELD]
	INNER JOIN [CUSTOMFIELDLAYOUT] ON [CUSTOMFIELDLAYOUT].[GCUSTOMFIELDLAYOUTS] = [CUSTOMFIELDOBJECT].[FKGCUSTOMFIELDLAYOUT]
	
END
GO

CREATE TRIGGER [dbo].[TG_CUSTOMFIELDWORKSHEETITEM_INSERT]
   ON  [dbo].[CUSTOMFIELDWORKSHEETITEM]
   AFTER INSERT
AS 
BEGIN	
	SET NOCOUNT ON;	
	INSERT INTO [HISTORYSYSTEMSETUP]
    (
        [ID],
        [ROWVERSION],
        [CHANGEDON],
        [CHANGEDBY],
        [FIELDNAME],
        [OLDVALUE],
        [NEWVALUE],
        [ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT 
        [CUSTOMFIELDLAYOUT].[GCUSTOMFIELDLAYOUTS], 
        [CUSTOMFIELDLAYOUT].[ROWVERSION],
        GETUTCDATE(),
        [CUSTOMFIELDLAYOUT].[LASTCHANGEDBY],	
        'Custom Field Layout Worksheet Item Added',
        '',
        '',       
		'Custom Field Layout (' + [CUSTOMFIELDLAYOUT].[SNAME] + '), Field (' + [CUSTOMFIELD].[SCUSTOMFIELD] +'), Item (' + [inserted].[SVALUE] +')',
        'CCD23415-9668-462D-AFCC-3794BBAB9ADB',
		1,
		0,
		[inserted].[SVALUE]
    FROM [inserted]
    INNER JOIN [CUSTOMFIELDWORKSHEET] ON [CUSTOMFIELDWORKSHEET].[GCUSTOMFIELDWORKSHEET] = [inserted].[FKGCUSTOMFIELDWORKSHEET]
	INNER JOIN [CUSTOMFIELD] ON [CUSTOMFIELD].[GCUSTOMFIELD] = [CUSTOMFIELDWORKSHEET].[FKGCUSTOMFIELD]
    INNER JOIN [CUSTOMFIELDOBJECT] ON [CUSTOMFIELDOBJECT].[GCUSTOMFIELD] = [CUSTOMFIELD].[GCUSTOMFIELD]
	INNER JOIN [CUSTOMFIELDLAYOUT] ON [CUSTOMFIELDLAYOUT].[GCUSTOMFIELDLAYOUTS] = [CUSTOMFIELDOBJECT].[FKGCUSTOMFIELDLAYOUT]

	
END
GO
CREATE TRIGGER [dbo].[TG_CUSTOMFIELDWORKSHEETITEM_UPDATE]
   ON  [dbo].[CUSTOMFIELDWORKSHEETITEM] 
   AFTER UPDATE
AS 
BEGIN	
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
    (	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT 
        [CUSTOMFIELDLAYOUT].[GCUSTOMFIELDLAYOUTS], 
        [CUSTOMFIELDLAYOUT].[ROWVERSION],
        GETUTCDATE(),
        [CUSTOMFIELDLAYOUT].[LASTCHANGEDBY],	
        'Value',
        [deleted].[SVALUE],
        [inserted].[SVALUE],       
		'Custom Field Layout (' + [CUSTOMFIELDLAYOUT].[SNAME] + '), Field (' + [CUSTOMFIELD].[SCUSTOMFIELD] +'), Item (' + [inserted].[SVALUE] +')',
        'CCD23415-9668-462D-AFCC-3794BBAB9ADB',
		2,
		0,
		[inserted].[SVALUE]
    FROM [deleted]
    INNER JOIN [inserted] ON [inserted].[GCUSTOMFIELDWORKSHEETITEM] = [deleted].[GCUSTOMFIELDWORKSHEETITEM] 
    INNER JOIN [CUSTOMFIELDWORKSHEET] ON [CUSTOMFIELDWORKSHEET].[GCUSTOMFIELDWORKSHEET] = [inserted].[FKGCUSTOMFIELDWORKSHEET]
	INNER JOIN [CUSTOMFIELD] ON [CUSTOMFIELD].[GCUSTOMFIELD] = [CUSTOMFIELDWORKSHEET].[FKGCUSTOMFIELD]
    INNER JOIN [CUSTOMFIELDOBJECT] ON [CUSTOMFIELDOBJECT].[GCUSTOMFIELD] = [CUSTOMFIELD].[GCUSTOMFIELD]
	INNER JOIN [CUSTOMFIELDLAYOUT] ON [CUSTOMFIELDLAYOUT].[GCUSTOMFIELDLAYOUTS] = [CUSTOMFIELDOBJECT].[FKGCUSTOMFIELDLAYOUT]
    WHERE [deleted].[SVALUE] <> [inserted].[SVALUE]
    UNION ALL
	SELECT 
        [CUSTOMFIELDLAYOUT].[GCUSTOMFIELDLAYOUTS], 
        [CUSTOMFIELDLAYOUT].[ROWVERSION],
        GETUTCDATE(),
        [CUSTOMFIELDLAYOUT].[LASTCHANGEDBY],	
        'Order',
        CAST([deleted].[IORDER] AS NVARCHAR(MAX)),
        CAST([inserted].[IORDER] AS NVARCHAR(MAX)),
		'Custom Field Layout (' + [CUSTOMFIELDLAYOUT].[SNAME] + '), Field (' + [CUSTOMFIELD].[SCUSTOMFIELD] +'), Item (' + [inserted].[SVALUE] +')',
        'CCD23415-9668-462D-AFCC-3794BBAB9ADB',
		2,
		0,
		[inserted].[SVALUE]
    FROM [deleted]
    INNER JOIN [inserted] ON [inserted].[GCUSTOMFIELDWORKSHEETITEM] = [deleted].[GCUSTOMFIELDWORKSHEETITEM] 
    INNER JOIN [CUSTOMFIELDWORKSHEET] ON [CUSTOMFIELDWORKSHEET].[GCUSTOMFIELDWORKSHEET] = [inserted].[FKGCUSTOMFIELDWORKSHEET]
	INNER JOIN [CUSTOMFIELD] ON [CUSTOMFIELD].[GCUSTOMFIELD] = [CUSTOMFIELDWORKSHEET].[FKGCUSTOMFIELD]
    INNER JOIN [CUSTOMFIELDOBJECT] ON [CUSTOMFIELDOBJECT].[GCUSTOMFIELD] = [CUSTOMFIELD].[GCUSTOMFIELD]
	INNER JOIN [CUSTOMFIELDLAYOUT] ON [CUSTOMFIELDLAYOUT].[GCUSTOMFIELDLAYOUTS] = [CUSTOMFIELDOBJECT].[FKGCUSTOMFIELDLAYOUT]
    WHERE [deleted].[IORDER] <> [inserted].[IORDER]
END