CREATE FUNCTION [codecase].[UFN_GET_CODECASE_VIOLATIONS_COUNT]
(
	@ENTITYID char(36)
)
RETURNS INT
AS
BEGIN
	DECLARE @COUNT AS INT
	SELECT @COUNT = COUNT(1)  
	FROM [dbo].[CMCODEWFSTEP] 
	INNER JOIN [dbo].[CMVIOLATION] ON [dbo].[CMCODEWFSTEP].[CMCODEWFSTEPID] = [dbo].[CMVIOLATION].[CMCODEWFSTEPID]	
	WHERE [dbo].[CMCODEWFSTEP].[CMCODECASEID] = @ENTITYID
	RETURN @COUNT;
END