CREATE PROCEDURE [managemyreview].[USP_PLITEMREVIEW_GETBYID_FORBLLICENSE]
(
	 @ID	CHAR(36)
)
AS
BEGIN

SELECT		PLITEMREVIEW.PLITEMREVIEWID				
			, PLITEMREVIEW.PLSUBMITTALID			
			, PLITEMREVIEW.ASSIGNEDUSERID 
			, PLITEMREVIEW.COMPLETEDATE 
			, PLITEMREVIEW.COMPLETED 
			, PLITEMREVIEW.NOTREQUIRED 
			, PLITEMREVIEW.DUEDATE 
			, BLLICENSE.BLLICENSEID AS ENTITYID
			, BLLICENSE.LICENSENUMBER AS ENTITYNUMBER
			, BLLICENSETYPE.BLLICENSETYPEID AS ENTITYTYPEID
			, BLLICENSETYPE.NAME AS ENTITYTYPENAME
			, BLLICENSECLASS.BLLICENSECLASSID AS ENTITYCLASSID
			, BLLICENSECLASS.NAME AS ENTITYCLASSNAME
			, BLLICENSE.DESCRIPTION AS ENTITYDESCRIPTION
			, BLLICENSE.APPLIEDDATE AS APPLIEDDATE
			, 3 AS MODULEID
			, PLSUBMITTALTYPE.PLSUBMITTALTYPEID AS SUBMITTALTYPEID
			, PLSUBMITTALTYPE.TYPENAME AS SUBMITTALTYPENAME
			, PLITEMREVIEWSTATUS.PLITEMREVIEWSTATUSID AS ITEMREVIEWSTATUSID
			, PLITEMREVIEWSTATUS.NAME AS ITEMREVIEWSTATUS
			, PLITEMREVIEWTYPE.PLITEMREVIEWTYPEID AS ITEMREVIEWTYPEID
			, PLITEMREVIEWTYPE.NAME AS ITEMREVIEWTYPE
			, BLLICENSEWFACTIONSTEP.VERSIONNUMBER AS VERSIONNUMBER
			, BLLICENSEADDRESS.BLLICENSEADDRESSID AS MAINADDRESSID
			, NULL AS PROJECTID
			, NULL AS PROJECTNAME
			, ERENTITYSESSION.ERENTITYSESSIONID AS SESSIONID
			, CAST(0 AS DECIMAL) AS SQUAREFEET
			, CAST(0 AS DECIMAL) AS VALUATIONVALUE
			, CAST(0 AS BIT) AS ISSUEDFLAG
			, CAST(0 AS BIT) AS COMPLETEDFLAG
			, CASEASSIGNEDTO.EMAIL AS CASEASSIGNEDTOEMAIL
			, CASEASSIGNEDTO.FNAME AS CASEASSIGNEDTOFIRSTNAME
			, CASEASSIGNEDTO.LNAME AS CASEASSIGNEDTOLASTNAME
			, BLGLOBALENTITYEXTENSION.COMPANYNAME AS BUSINESSNAME
			, NULL AS LICENSEHOLDERFIRSTNAME
			, NULL AS LICENSEHOLDERLASTNAME
			, BLLICENSE.EXPIRATIONDATE
			, BLLICENSE.LASTRENEWALDATE
			, BLLICENSE.TAXYEAR AS LICENSEYEAR
			, BLLICENSETYPE.NAME AS LICENSETYPE
			, BLLICENSESTATUS.NAME AS LICENSESTATUS
			, ZONE.ZONEID
			, ZONE.NAME AS ZONENAME
			, ZONE.ZONECODE
			, ZONE.DESCRIPTION AS ZONEDESCRIPTION
			, BLLICENSEADDRESS.BLLICENSEADDRESSID AS PARENTADDRESSID
			, USERS.FNAME AS ASSIGNEDUSERFIRSTNAME
			, USERS.LNAME AS ASSIGNEDUSERLASTNAME
			, BLLICENSEWFACTIONSTEP.BLLICENSEWFSTEPID AS BLLICENSEWFSTEPID
			, ERENTITYSESSION.SESSIONSTATUSID AS SESSIONSTATUSID
			, PLITEMREVIEWTYPE.CODENAME AS CODENAME
			, PLITEMREVIEWTYPE.CODEURL AS CODEURL
			, BLLICENSETYPE.BLLICENSETYPEMODULEID as LICENSETYPEMODULEID 
FROM		PLITEMREVIEW 
INNER JOIN	PLSUBMITTAL ON PLITEMREVIEW.PLSUBMITTALID = PLSUBMITTAL.PLSUBMITTALID
INNER JOIN	PLITEMREVIEWSTATUS ON PLITEMREVIEWSTATUS.PLITEMREVIEWSTATUSID = PLITEMREVIEW.PLITEMREVIEWSTATUSID
INNER JOIN	PLSUBMITTALTYPE ON PLSUBMITTAL.PLSUBMITTALTYPEID = PLSUBMITTALTYPE.PLSUBMITTALTYPEID
INNER JOIN	PLSUBMITTALSTATUS ON PLSUBMITTALSTATUS.PLSUBMITTALSTATUSID = PLSUBMITTAL.PLSUBMITTALSTATUSID
INNER JOIN	PLITEMREVIEWTYPE ON PLITEMREVIEW.PLITEMREVIEWTYPEID = PLITEMREVIEWTYPE.PLITEMREVIEWTYPEID
INNER JOIN	BLLICENSEWFACTIONSTEP ON BLLICENSEWFACTIONSTEP.BLLICENSEWFACTIONSTEPID = PLSUBMITTAL.BLLICENSEWFACTIONSTEPID
INNER JOIN	BLLICENSE ON BLLICENSE.BLLICENSEID = PLSUBMITTAL.BLLICENSEID
INNER JOIN	BLGLOBALENTITYEXTENSION ON BLGLOBALENTITYEXTENSION.BLGLOBALENTITYEXTENSIONID = BLLICENSE.BLGLOBALENTITYEXTENSIONID
INNER JOIN	BLLICENSETYPE ON BLLICENSE.BLLICENSETYPEID = BLLICENSETYPE.BLLICENSETYPEID
INNER JOIN	BLLICENSESTATUS ON BLLICENSE.BLLICENSESTATUSID = BLLICENSESTATUS.BLLICENSESTATUSID
INNER JOIN	BLLICENSECLASS ON BLLICENSE.BLLICENSECLASSID = BLLICENSECLASS.BLLICENSECLASSID
LEFT JOIN	BLLICENSEADDRESS ON BLLICENSE.BLLICENSEID = BLLICENSEADDRESS.BLLICENSEID AND BLLICENSEADDRESS.MAIN = 1
INNER JOIN	USERS ON USERS.SUSERGUID = PLITEMREVIEW.ASSIGNEDUSERID
LEFT JOIN   USERS AS CASEASSIGNEDTO ON CASEASSIGNEDTO.SUSERGUID = BLLICENSE.ISSUEDBY 
LEFT JOIN	ERENTITYSESSION ON ERENTITYSESSION.PLSUBMITTALID = PLSUBMITTAL.PLSUBMITTALID
LEFT JOIN	BLLICENSEZONE ON BLLICENSE.BLLICENSEID = BLLICENSEZONE.BLLICENSEID AND BLLICENSEZONE.MAIN = 1
LEFT JOIN	ZONE ON ZONE.ZONEID = BLLICENSEZONE.ZONEID
WHERE		PLITEMREVIEW.PLITEMREVIEWID = @ID

END