CREATE PROCEDURE [managemyreview].[USP_PLITEMREVIEW_GETBYASSIGNEDUSERS_ITEMREVIEWLIST]
(
	@ASSIGNEDUSERLIST RecordIDs Readonly,
	@ASSIGNEDTEAMLIST RecordIDs Readonly,
	@INCLUDECOMPLETED BIT,
	@INCLUDETEAM BIT,
	@MANAGERID CHAR(36) = NULL,
	@LAST30DAYS DATE = NULL,
	@LASTWEEKFIRSTDAY DATE = NULL,
	@LASTWEEKLASTDAY DATE = NULL,
	@OVERDUEDATE DATE = NULL,
	@THISWEEKFIRSTDAY DATE = NULL,
	@THISWEEKLASTDAY DATE = NULL,
	@TODAYDUEBEGINDATE DATE = NULL,
	@TODAYDUEENDDATE DATE = NULL,
	@UPCOMINGDUEBEGINDATE DATE = NULL,
	@UPCOMINGDUEENDDATE DATE = NULL,
	@THISWEEKLABEL VARCHAR(30) = NULL,
	@LASTWEEKLABEL VARCHAR(30) = NULL,
	@LAST30DAYSLABEL VARCHAR(30) = NULL,
	@TODAYLABEL VARCHAR(30) = NULL,
	@NEXT5DAYSLABEL VARCHAR(30) = NULL,
	@OVERDUELABEL VARCHAR(30) = NULL
)
AS
BEGIN
SET NOCOUNT ON;

IF @INCLUDECOMPLETED = 0
BEGIN
	WITH CTE_ITEMREVIEWLIST AS (
	SELECT		PLITEMREVIEWID
				, PLITEMREVIEW.PLSUBMITTALID 
				, PLITEMREVIEW.PRIORITYORDER
				, COALESCE(BLLICENSEWFACTIONSTEP.WORKFLOWSTATUSID, ILLICENSEWFACTIONSTEP.WORKFLOWSTATUSID, PMPERMITWFACTIONSTEP.WORKFLOWSTATUSID, PLPLANWFACTIONSTEP.WORKFLOWSTATUSID) AS WORKFLOWSTATUSID
	FROM		PLITEMREVIEW
	INNER JOIN	PLSUBMITTAL ON PLSUBMITTAL.PLSUBMITTALID = PLITEMREVIEW.PLSUBMITTALID
	LEFT JOIN	BLLICENSEWFACTIONSTEP ON BLLICENSEWFACTIONSTEP.BLLICENSEWFACTIONSTEPID = PLSUBMITTAL.BLLICENSEWFACTIONSTEPID
	LEFT JOIN	ILLICENSEWFACTIONSTEP ON ILLICENSEWFACTIONSTEP.ILLICENSEWFACTIONSTEPID = PLSUBMITTAL.ILLICENSEWFACTIONSTEPID
	LEFT JOIN	PMPERMITWFACTIONSTEP ON PMPERMITWFACTIONSTEP.PMPERMITWFACTIONSTEPID = PLSUBMITTAL.PMPERMITWFACTIONSTEPID
	LEFT JOIN	PLPLANWFACTIONSTEP ON PLPLANWFACTIONSTEP.PLPLANWFACTIONSTEPID = PLSUBMITTAL.PLPLANWFACTIONSTEPID
	WHERE NOTREQUIRED = 0 AND ASSIGNEDUSERID IS NOT NULL AND 
	(
	NOT EXISTS(SELECT * FROM @ASSIGNEDUSERLIST)  
	OR
	ASSIGNEDUSERID IN (SELECT RECORDID FROM @ASSIGNEDUSERLIST)
	)
				AND				PLITEMREVIEW.COMPLETED = 0
				AND				PLSUBMITTAL.COMPLETED = 0
		
	UNION ALL
	SELECT PLITEMREVIEWID
				, PLITEMREVIEW.PLSUBMITTALID 
				, PLITEMREVIEW.PRIORITYORDER
				, COALESCE(BLLICENSEWFACTIONSTEP.WORKFLOWSTATUSID, ILLICENSEWFACTIONSTEP.WORKFLOWSTATUSID, PMPERMITWFACTIONSTEP.WORKFLOWSTATUSID, PLPLANWFACTIONSTEP.WORKFLOWSTATUSID) AS WORKFLOWSTATUSID
	FROM		PLITEMREVIEW
	INNER JOIN	PLSUBMITTAL ON PLSUBMITTAL.PLSUBMITTALID = PLITEMREVIEW.PLSUBMITTALID
	LEFT JOIN	BLLICENSEWFACTIONSTEP ON BLLICENSEWFACTIONSTEP.BLLICENSEWFACTIONSTEPID = PLSUBMITTAL.BLLICENSEWFACTIONSTEPID
	LEFT JOIN	ILLICENSEWFACTIONSTEP ON ILLICENSEWFACTIONSTEP.ILLICENSEWFACTIONSTEPID = PLSUBMITTAL.ILLICENSEWFACTIONSTEPID
	LEFT JOIN	PMPERMITWFACTIONSTEP ON PMPERMITWFACTIONSTEP.PMPERMITWFACTIONSTEPID = PLSUBMITTAL.PMPERMITWFACTIONSTEPID
	LEFT JOIN	PLPLANWFACTIONSTEP ON PLPLANWFACTIONSTEP.PLPLANWFACTIONSTEPID = PLSUBMITTAL.PLPLANWFACTIONSTEPID
	WHERE NOTREQUIRED = 0 AND 
	ASSIGNEDUSERID IS NULL AND TEAMASSIGNEDTO IN (SELECT RECORDID FROM @ASSIGNEDTEAMLIST)
				AND				PLITEMREVIEW.COMPLETED = 0
				AND				PLSUBMITTAL.COMPLETED = 0
	) 
	, CTE_PRIORITY AS (
		SELECT	PLITEMREVIEW.PLSUBMITTALID
				, MIN(PLITEMREVIEW.PRIORITYORDER) AS MINPRIORITY
		FROM	PLITEMREVIEW
		INNER JOIN CTE_ITEMREVIEWLIST ON CTE_ITEMREVIEWLIST.PLSUBMITTALID = PLITEMREVIEW.PLSUBMITTALID
		AND		COMPLETED = 0
		GROUP BY PLITEMREVIEW.PLSUBMITTALID
	)
	SELECT			CTE_ITEMREVIEWLIST.PLITEMREVIEWID 
	FROM			CTE_ITEMREVIEWLIST
	WHERE			CTE_ITEMREVIEWLIST.PRIORITYORDER <= (SELECT MINPRIORITY FROM CTE_PRIORITY WHERE PLSUBMITTALID = CTE_ITEMREVIEWLIST.PLSUBMITTALID)
	AND				CTE_ITEMREVIEWLIST.WORKFLOWSTATUSID = 5	
	
END
ELSE
BEGIN
	SELECT		PLITEMREVIEW.PLITEMREVIEWID 
	FROM		PLITEMREVIEW
	WHERE		NOTREQUIRED = 0 AND (NOT EXISTS(SELECT * FROM @ASSIGNEDUSERLIST) OR ASSIGNEDUSERID IN (SELECT RECORDID FROM @ASSIGNEDUSERLIST)OR 
				(ASSIGNEDUSERID IS NULL AND TEAMASSIGNEDTO IN (SELECT RECORDID FROM @ASSIGNEDTEAMLIST)))
	AND			PLITEMREVIEW.COMPLETED = 1
	
END

END