CREATE PROCEDURE [managemyreview].[USP_PLITEMREVIEW_GETBYID_FORPERMIT]
(
	 @ID	CHAR(36)
)
AS
BEGIN

SELECT		PLITEMREVIEW.PLITEMREVIEWID				
			, PLITEMREVIEW.PLSUBMITTALID			
			, PLITEMREVIEW.ASSIGNEDUSERID 
			, PLITEMREVIEW.COMPLETEDATE 
			, PLITEMREVIEW.COMPLETED 
			, PLITEMREVIEW.NOTREQUIRED 
			, PLITEMREVIEW.DUEDATE 
			, PMPERMIT.PMPERMITID AS ENTITYID
			, PMPERMIT.PERMITNUMBER AS ENTITYNUMBER
			, PMPERMITTYPE.PMPERMITTYPEID AS ENTITYTYPEID
			, PMPERMITTYPE.NAME AS ENTITYTYPENAME
			, PMPERMITWORKCLASS.PMPERMITWORKCLASSID AS ENTITYCLASSID
			, PMPERMITWORKCLASS.NAME AS ENTITYCLASSNAME
			, PMPERMIT.DESCRIPTION AS ENTITYDESCRIPTION
			, PMPERMIT.APPLYDATE AS APPLIEDDATE
			, 2 AS MODULEID
			, PLSUBMITTALTYPE.PLSUBMITTALTYPEID AS SUBMITTALTYPEID
			, PLSUBMITTALTYPE.TYPENAME AS SUBMITTALTYPENAME
			, PLITEMREVIEWSTATUS.PLITEMREVIEWSTATUSID AS ITEMREVIEWSTATUSID
			, PLITEMREVIEWSTATUS.NAME AS ITEMREVIEWSTATUS
			, PLITEMREVIEWTYPE.PLITEMREVIEWTYPEID AS ITEMREVIEWTYPEID
			, PLITEMREVIEWTYPE.NAME AS ITEMREVIEWTYPE
			, PMPERMITWFACTIONSTEP.VERSIONNUMBER AS VERSIONNUMBER
			, PMPERMITADDRESS.MAILINGADDRESSID AS MAINADDRESSID
			, PRPROJECT.PRPROJECTID AS PROJECTID
			, PRPROJECT.NAME AS PROJECTNAME
			, ERENTITYSESSION.ERENTITYSESSIONID AS SESSIONID
			, PMPERMIT.SQUAREFEET
			, PMPERMIT.VALUE AS VALUATIONVALUE
			, PMPERMITSTATUS.ISSUEDFLAG
			, PMPERMITSTATUS.COMPLETEDFLAG
			, CASEASSIGNEDTO.EMAIL AS CASEASSIGNEDTOEMAIL
			, CASEASSIGNEDTO.FNAME AS CASEASSIGNEDTOFIRSTNAME
			, CASEASSIGNEDTO.LNAME AS CASEASSIGNEDTOLASTNAME
			, NULL AS BUSINESSNAME
			, NULL AS LICENSEHOLDERFIRSTNAME
			, NULL AS LICENSEHOLDERLASTNAME
			, NULL AS EXPIRATIONDATE
			, NULL AS LASTRENEWALDATE
			, 1900 AS LICENSEYEAR
			, NULL AS LICENSETYPE
			, NULL AS LICENSESTATUS
			, ZONE.ZONEID
			, ZONE.NAME AS ZONENAME
			, ZONE.ZONECODE
			, ZONE.DESCRIPTION AS ZONEDESCRIPTION
			, PMPERMITADDRESS.PMPERMITADDRESSID AS PARENTADDRESSID
			, USERS.FNAME AS ASSIGNEDUSERFIRSTNAME
			, USERS.LNAME AS ASSIGNEDUSERLASTNAME
			, PMPERMITWFACTIONSTEP.PMPERMITWFSTEPID AS PMPERMITWFSTEPID
			, ERENTITYSESSION.SESSIONSTATUSID AS SESSIONSTATUSID
			, PLITEMREVIEWTYPE.CODENAME AS CODENAME
			, PLITEMREVIEWTYPE.CODEURL AS CODEURL
			, NULL as LICENSETYPEMODULEID 
FROM		PLITEMREVIEW 
INNER JOIN	PLSUBMITTAL ON PLITEMREVIEW.PLSUBMITTALID = PLSUBMITTAL.PLSUBMITTALID
INNER JOIN	PLITEMREVIEWSTATUS ON PLITEMREVIEWSTATUS.PLITEMREVIEWSTATUSID = PLITEMREVIEW.PLITEMREVIEWSTATUSID
INNER JOIN	PLSUBMITTALTYPE ON PLSUBMITTAL.PLSUBMITTALTYPEID = PLSUBMITTALTYPE.PLSUBMITTALTYPEID
INNER JOIN	PLSUBMITTALSTATUS ON PLSUBMITTALSTATUS.PLSUBMITTALSTATUSID = PLSUBMITTAL.PLSUBMITTALSTATUSID
INNER JOIN	PLITEMREVIEWTYPE ON PLITEMREVIEW.PLITEMREVIEWTYPEID = PLITEMREVIEWTYPE.PLITEMREVIEWTYPEID
INNER JOIN	PMPERMITWFACTIONSTEP ON PMPERMITWFACTIONSTEP.PMPERMITWFACTIONSTEPID = PLSUBMITTAL.PMPERMITWFACTIONSTEPID
INNER JOIN	PMPERMIT ON PMPERMIT.PMPERMITID = PLSUBMITTAL.PMPERMITID
INNER JOIN	PMPERMITTYPE ON PMPERMIT.PMPERMITTYPEID = PMPERMITTYPE.PMPERMITTYPEID
INNER JOIN	PMPERMITSTATUS ON PMPERMIT.PMPERMITSTATUSID = PMPERMITSTATUS.PMPERMITSTATUSID
INNER JOIN	PMPERMITWORKCLASS ON PMPERMIT.PMPERMITWORKCLASSID = PMPERMITWORKCLASS.PMPERMITWORKCLASSID
LEFT JOIN	PMPERMITADDRESS ON PMPERMIT.PMPERMITID = PMPERMITADDRESS.PMPERMITID AND PMPERMITADDRESS.MAIN = 1
INNER JOIN	USERS ON USERS.SUSERGUID = PLITEMREVIEW.ASSIGNEDUSERID
LEFT JOIN  USERS AS CASEASSIGNEDTO ON CASEASSIGNEDTO.SUSERGUID = PMPERMIT.ASSIGNEDTO 
LEFT JOIN	PRPROJECTPERMIT ON PRPROJECTPERMIT.PMPERMITID = PMPERMIT.PMPERMITID
LEFT JOIN	PRPROJECT ON PRPROJECT.PRPROJECTID = PRPROJECTPERMIT.PRPROJECTID
LEFT JOIN	ERENTITYSESSION ON ERENTITYSESSION.PLSUBMITTALID = PLSUBMITTAL.PLSUBMITTALID
LEFT JOIN	PMPERMITZONE ON PMPERMIT.PMPERMITID = PMPERMITZONE.PMPERMITID AND PMPERMITZONE.MAIN = 1
LEFT JOIN	ZONE ON ZONE.ZONEID = PMPERMITZONE.ZONEID
WHERE		PLITEMREVIEW.PLITEMREVIEWID = @ID

END