CREATE PROCEDURE [managemyreview].[USP_PLITEMREVIEW_GETDASHBOARDDATA_FORCOMPLETEDREVIEWS]
(
	@ASSIGNEDUSERLIST RecordIDs READONLY
)
AS
BEGIN
SET NOCOUNT ON
SELECT			DISTINCT PLITEMREVIEWID,
				ASSIGNEDDATE,
				COMPLETEDATE,
				PLITEMREVIEWTYPE.PLITEMREVIEWTYPEID AS ITEMREVIEWTYPEID,
				PLITEMREVIEWTYPE.NAME AS ITEMREVIEWTYPE,
				DATEDIFF(DAY, ASSIGNEDDATE, COMPLETEDATE) AS TURNAROUNDTIME
FROM			PLITEMREVIEW 
INNER JOIN		PLITEMREVIEWSTATUS ON PLITEMREVIEWSTATUS.PLITEMREVIEWSTATUSID = PLITEMREVIEW.PLITEMREVIEWSTATUSID
INNER JOIN		PLITEMREVIEWTYPE ON PLITEMREVIEWTYPE.PLITEMREVIEWTYPEID = PLITEMREVIEW.PLITEMREVIEWTYPEID
WHERE			(PLITEMREVIEWSTATUS.FAILUREFLAG = 1 OR PLITEMREVIEWSTATUS.SUCCESSFLAG = 1)
AND				ASSIGNEDDATE IS NOT NULL
AND				COMPLETEDATE IS NOT NULL
AND				ASSIGNEDUSERID IN (SELECT RECORDID FROM @ASSIGNEDUSERLIST)				

END