CREATE PROCEDURE [managemyreview].[USP_PLITEMREVIEW_GETBYASSIGNEDUSERS_FACETS_ENTITYNUMBER]
(
	@ITEMREVIEWLIST RecordIDs READONLY
)
AS
BEGIN
SET NOCOUNT ON;

SELECT			BLLICENSE.BLLICENSEID AS ID
				, BLLICENSE.LICENSENUMBER AS NAME
				, COUNT(*) COUNT
FROM			PLITEMREVIEW 
INNER JOIN		@ITEMREVIEWLIST ON PLITEMREVIEW.PLITEMREVIEWID = RECORDID
INNER JOIN		PLSUBMITTAL ON PLITEMREVIEW.PLSUBMITTALID = PLSUBMITTAL.PLSUBMITTALID
INNER JOIN		BLLICENSE ON BLLICENSE.BLLICENSEID = PLSUBMITTAL.BLLICENSEID
GROUP BY		BLLICENSE.BLLICENSEID, BLLICENSE.LICENSENUMBER
UNION ALL
SELECT			ILLICENSE.ILLICENSEID AS ID
				, ILLICENSE.LICENSENUMBER AS NAME
				, COUNT(*) COUNT
FROM			PLITEMREVIEW 
INNER JOIN		@ITEMREVIEWLIST ON PLITEMREVIEW.PLITEMREVIEWID = RECORDID
INNER JOIN		PLSUBMITTAL ON PLITEMREVIEW.PLSUBMITTALID = PLSUBMITTAL.PLSUBMITTALID
INNER JOIN		ILLICENSE ON ILLICENSE.ILLICENSEID = PLSUBMITTAL.ILLICENSEID
GROUP BY		ILLICENSE.ILLICENSEID, ILLICENSE.LICENSENUMBER
UNION ALL
SELECT			PMPERMIT.PMPERMITID AS ID
				, PMPERMIT.PERMITNUMBER AS NAME
				, COUNT(*) COUNT
FROM			PLITEMREVIEW 
INNER JOIN		@ITEMREVIEWLIST ON PLITEMREVIEW.PLITEMREVIEWID = RECORDID
INNER JOIN		PLSUBMITTAL ON PLITEMREVIEW.PLSUBMITTALID = PLSUBMITTAL.PLSUBMITTALID
INNER JOIN		PMPERMIT ON PMPERMIT.PMPERMITID = PLSUBMITTAL.PMPERMITID
GROUP BY		PMPERMIT.PMPERMITID, PMPERMIT.PERMITNUMBER
UNION ALL
SELECT			PLPLAN.PLPLANID AS ID
				, PLPLAN.PLANNUMBER AS NAME
				, COUNT(*) COUNT
FROM			PLITEMREVIEW 
INNER JOIN		@ITEMREVIEWLIST ON PLITEMREVIEW.PLITEMREVIEWID = RECORDID
INNER JOIN		PLSUBMITTAL ON PLITEMREVIEW.PLSUBMITTALID = PLSUBMITTAL.PLSUBMITTALID
INNER JOIN		PLPLAN ON PLPLAN.PLPLANID = PLSUBMITTAL.PLPLANID
GROUP BY		PLPLAN.PLPLANID, PLPLAN.PLANNUMBER
ORDER BY COUNT(*) DESC, NAME

END