CREATE PROCEDURE [managemyreview].[USP_PLITEMREVIEW_GETBYASSIGNEDUSERS_FACETS_ENTITYCLASS]
(
	@ITEMREVIEWLIST RecordIDs READONLY
)
AS
BEGIN
SET NOCOUNT ON;

SELECT			BLLICENSECLASS.BLLICENSECLASSID AS ENTITYCLASSID
				, BLLICENSECLASS.NAME AS ENTITYCLASSNAME
				, COUNT(*) COUNT
FROM			PLITEMREVIEW 
INNER JOIN		@ITEMREVIEWLIST ON PLITEMREVIEW.PLITEMREVIEWID = RECORDID
INNER JOIN		PLSUBMITTAL ON PLITEMREVIEW.PLSUBMITTALID = PLSUBMITTAL.PLSUBMITTALID
INNER JOIN		BLLICENSE ON BLLICENSE.BLLICENSEID = PLSUBMITTAL.BLLICENSEID
INNER JOIN		BLLICENSECLASS ON BLLICENSE.BLLICENSECLASSID = BLLICENSECLASS.BLLICENSECLASSID
GROUP BY		BLLICENSECLASS.BLLICENSECLASSID, BLLICENSECLASS.NAME
UNION ALL
SELECT			ILLICENSECLASSIFICATION.ILLICENSECLASSIFICATIONID AS ENTITYCLASSID
				, ILLICENSECLASSIFICATION.NAME AS ENTITYCLASSNAME
				, COUNT(*) COUNT
FROM			PLITEMREVIEW 
INNER JOIN		@ITEMREVIEWLIST ON PLITEMREVIEW.PLITEMREVIEWID = RECORDID
INNER JOIN		PLSUBMITTAL ON PLITEMREVIEW.PLSUBMITTALID = PLSUBMITTAL.PLSUBMITTALID
INNER JOIN		ILLICENSE ON ILLICENSE.ILLICENSEID = PLSUBMITTAL.ILLICENSEID
INNER JOIN		ILLICENSECLASSIFICATION ON ILLICENSE.ILLICENSECLASSIFICATIONID = ILLICENSECLASSIFICATION.ILLICENSECLASSIFICATIONID
GROUP By		ILLICENSECLASSIFICATION.ILLICENSECLASSIFICATIONID, ILLICENSECLASSIFICATION.NAME
UNION ALL
SELECT			PMPERMITWORKCLASS.PMPERMITWORKCLASSID AS ENTITYCLASSID
				, PMPERMITWORKCLASS.NAME AS ENTITYCLASSNAME
				, COUNT(*) COUNT
FROM			PLITEMREVIEW 
INNER JOIN		@ITEMREVIEWLIST ON PLITEMREVIEW.PLITEMREVIEWID = RECORDID
INNER JOIN		PLSUBMITTAL ON PLITEMREVIEW.PLSUBMITTALID = PLSUBMITTAL.PLSUBMITTALID
INNER JOIN		PMPERMIT ON PMPERMIT.PMPERMITID = PLSUBMITTAL.PMPERMITID
INNER JOIN		PMPERMITWORKCLASS ON PMPERMIT.PMPERMITWORKCLASSID = PMPERMITWORKCLASS.PMPERMITWORKCLASSID
GROUP BY		PMPERMITWORKCLASS.PMPERMITWORKCLASSID, PMPERMITWORKCLASS.NAME
UNION ALL
SELECT			PLPLANWORKCLASS.PLPLANWORKCLASSID AS ENTITYCLASSID
				, PLPLANWORKCLASS.NAME AS ENTITYCLASSNAME
				, COUNT(*) COUNT
FROM			PLITEMREVIEW 
INNER JOIN		@ITEMREVIEWLIST ON PLITEMREVIEW.PLITEMREVIEWID = RECORDID
INNER JOIN		PLSUBMITTAL ON PLITEMREVIEW.PLSUBMITTALID = PLSUBMITTAL.PLSUBMITTALID
INNER JOIN		PLPLAN ON PLPLAN.PLPLANID = PLSUBMITTAL.PLPLANID
INNER JOIN		PLPLANWORKCLASS ON PLPLAN.PLPLANWORKCLASSID = PLPLANWORKCLASS.PLPLANWORKCLASSID
GROUP BY		PLPLANWORKCLASS.PLPLANWORKCLASSID, PLPLANWORKCLASS.NAME
ORDER BY COUNT(*) DESC, ENTITYCLASSID, ENTITYCLASSNAME

END