CREATE PROCEDURE [managemyreview].[USP_PLITEMREVIEW_LIGHTWEIGHT_GETBYID]
(
	 @ID	CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON

SELECT		PLITEMREVIEW.PLITEMREVIEWID,
            PLITEMREVIEW.NOTREQUIRED,
            PLITEMREVIEW.COMPLETED,
            PLITEMREVIEWSTATUS.PLITEMREVIEWSTATUSID,
            PLITEMREVIEWSTATUS.FAILUREFLAG,
            PLITEMREVIEWSTATUS.SUCCESSFLAG
FROM		PLITEMREVIEW
JOIN		PLITEMREVIEWSTATUS ON PLITEMREVIEWSTATUS.PLITEMREVIEWSTATUSID = PLITEMREVIEW.PLITEMREVIEWSTATUSID
WHERE		PLITEMREVIEWID = @ID                           

END