CREATE PROCEDURE [managemyreview].[USP_PLITEMREVIEW_HISTORY_GETBYENTITY_SUBMITTALID]
	@ENTITY_ID	CHAR(36), 
	@SUBMITTAL_ID	CHAR(36) 
AS
BEGIN
	DECLARE @TBL_SUBMITTAL TABLE 
	(
	   PLSUBMITTALID CHAR(36),
	   PLSUBMITTALPARENTID CHAR(36)
	)
	
	SET NOCOUNT ON;
  
   IF @SUBMITTAL_ID IS NOT NULL 
	BEGIN	    
		;WITH CTE1 AS
		(
			SELECT  PLSUBMITTALID, 
					PLSUBMITTALPARENTID 
			FROM    PLSUBMITTAL 
			WHERE   PLSUBMITTALID = @SUBMITTAL_ID
				UNION ALL
			SELECT  t.PLSUBMITTALID, 
					t.PLSUBMITTALPARENTID 
			FROM    PLSUBMITTAL t
					INNER JOIN CTE1 r ON r.PLSUBMITTALPARENTID = t.PLSUBMITTALID
		)
		,CTE2 AS
		(
			SELECT  PLSUBMITTALID, 
					PLSUBMITTALPARENTID
			FROM    PLSUBMITTAL 
			WHERE   PLSUBMITTALID = @SUBMITTAL_ID 	

			UNION ALL

			SELECT  t.PLSUBMITTALID, 
					t.PLSUBMITTALPARENTID 
			FROM    PLSUBMITTAL t
					INNER JOIN CTE2 ON CTE2.PLSUBMITTALID  = t.PLSUBMITTALPARENTID 
		)

		INSERT INTO @TBL_SUBMITTAL
		SELECT  PLSUBMITTALID, PLSUBMITTALPARENTID  FROM  CTE1 UNION SELECT PLSUBMITTALID, PLSUBMITTALPARENTID  FROM  CTE2;			
	END
   ELSE  
	BEGIN
		INSERT INTO @TBL_SUBMITTAL
			SELECT SUB.PLSUBMITTALID, SUB.PLSUBMITTALPARENTID FROM PLSUBMITTAL SUB
				WHERE SUB.PLPLANID = @ENTITY_ID OR SUB.PMPERMITID = @ENTITY_ID OR SUB.BLLICENSEID = @ENTITY_ID OR SUB.ILLICENSEID = @ENTITY_ID
	END

	SELECT	PLSUBMITTAL.PLSUBMITTALID, -- 0
			PLSUBMITTALTYPE.PLSUBMITTALTYPEID,  -- 1
			PLSUBMITTALTYPE.TYPENAME AS SUBMITTAL_TYPE_NAME,  -- 2
			PLSUBMITTALSTATUS.NAME AS SUBMITTAL_STATUS_NAME,  -- 3
			PLSUBMITTAL.DUEDATE,  -- 4
			PLSUBMITTAL.RECEIVEDDATE,  -- 5
			PLSUBMITTAL.COMPLETEDATE, -- 6
			(CASE WHEN PMPERMIT.PMPERMITID IS NOT NULL THEN 2 WHEN PLPLAN.PLPLANID IS NOT NULL THEN 1 WHEN BLLICENSE.BLLICENSEID IS NOT NULL THEN 3 WHEN ILLICENSE.ILLICENSEID IS NOT NULL THEN 4 ELSE 0 END) AS ENTITY_MODULE, -- 7
			COALESCE(PLPLAN.PLANNUMBER, PMPERMIT.PERMITNUMBER, BLLICENSE.LICENSENUMBER, ILLICENSE.LICENSENUMBER) AS ENTITY_NUMBER, --8
			COALESCE(PLPLANWFACTIONSTEP.NAME, PMPERMITWFACTIONSTEP.NAME, BLLICENSEWFACTIONSTEP.NAME, ILLICENSEWFACTIONSTEP.NAME) AS WFACTION_NAME, --9
			COALESCE(PLPLANWFACTIONSTEP.VERSIONNUMBER, PMPERMITWFACTIONSTEP.VERSIONNUMBER, BLLICENSEWFACTIONSTEP.VERSIONNUMBER, ILLICENSEWFACTIONSTEP.VERSIONNUMBER) AS VERSION_NUMBER,  -- 10
			COALESCE(PLPLAN.PLPLANID, PMPERMIT.PMPERMITID, BLLICENSE.BLLICENSEID, ILLICENSE.ILLICENSEID) AS ENTITYID --11
	FROM	@TBL_SUBMITTAL AS Submittal 
			JOIN PLSUBMITTAL ON PLSUBMITTAL.PLSUBMITTALID = Submittal.PLSUBMITTALID
			JOIN PLSUBMITTALTYPE ON PLSUBMITTALTYPE.PLSUBMITTALTYPEID = PLSUBMITTAL.PLSUBMITTALTYPEID
			JOIN PLSUBMITTALSTATUS ON PLSUBMITTALSTATUS.PLSUBMITTALSTATUSID = PLSUBMITTAL.PLSUBMITTALSTATUSID
			LEFT JOIN PLPLAN ON PLPLAN.PLPLANID = PLSUBMITTAL.PLPLANID
			LEFT JOIN PLPLANWFACTIONSTEP ON PLPLANWFACTIONSTEP.PLPLANWFACTIONSTEPID = PLSUBMITTAL.PLPLANWFACTIONSTEPID
			LEFT JOIN PMPERMIT ON PMPERMIT.PMPERMITID = PLSUBMITTAL.PMPERMITID
			LEFT JOIN PMPERMITWFACTIONSTEP ON PMPERMITWFACTIONSTEP.PMPERMITWFACTIONSTEPID = PLSUBMITTAL.PMPERMITWFACTIONSTEPID
			LEFT JOIN BLLICENSE ON BLLICENSE.BLLICENSEID = PLSUBMITTAL.BLLICENSEID
			LEFT JOIN BLLICENSEWFACTIONSTEP ON BLLICENSEWFACTIONSTEP.BLLICENSEWFACTIONSTEPID = PLSUBMITTAL.BLLICENSEWFACTIONSTEPID
			LEFT JOIN ILLICENSE ON ILLICENSE.ILLICENSEID = PLSUBMITTAL.ILLICENSEID
			LEFT JOIN ILLICENSEWFACTIONSTEP ON ILLICENSEWFACTIONSTEP.ILLICENSEWFACTIONSTEPID = PLSUBMITTAL.ILLICENSEWFACTIONSTEPID
	ORDER BY VERSION_NUMBER DESC

	SELECT	PLITEMREVIEW.PLSUBMITTALID, --0
			PLITEMREVIEW.PLITEMREVIEWID,  -- 1
			PLITEMREVIEW.COMPLETEDATE AS ITEMREVIEW_COMPLETEDATE,  -- 2
			PLITEMREVIEW.DUEDATE AS ITEMREVIEW_DUEDATE,   -- 3
			PLITEMREVIEW.PASSED,  -- 4
			CAST(CASE PLITEMREVIEW.NOTREQUIRED WHEN 1 THEN 0 ELSE 1 END AS BIT) AS ISREQUIRED,  -- 5
			PLITEMREVIEW.PRIORITYORDER,  -- 6
			PLITEMREVIEW.PLITEMREVIEWSTATUSID,  -- 7
			PLITEMREVIEWSTATUS.NAME AS ITEMREVIEW_STATUS_NAME,  -- 8
			PLITEMREVIEWTYPE.NAME AS ITEM_REVIEW_TYPE_NAME,  -- 9
			DEPARTMENT.NAME AS DEPARTMENT_NAME, -- 10
			USERS.FNAME,  -- 11
			USERS.LNAME,  -- 12	
			ASSIGNEDUSERID, --13
			PLITEMREVIEW.ASSIGNEDDATE, --14
			USERS.EMAIL		--15
	FROM	@TBL_SUBMITTAL AS Submittal
			JOIN PLITEMREVIEW ON PLITEMREVIEW.PLSUBMITTALID = Submittal.PLSUBMITTALID
			JOIN PLITEMREVIEWSTATUS ON PLITEMREVIEWSTATUS.PLITEMREVIEWSTATUSID = PLITEMREVIEW.PLITEMREVIEWSTATUSID
			JOIN PLITEMREVIEWTYPE ON PLITEMREVIEWTYPE.PLITEMREVIEWTYPEID = PLITEMREVIEW.PLITEMREVIEWTYPEID
			LEFT JOIN DEPARTMENT ON DEPARTMENT.DEPARTMENTID = PLITEMREVIEWTYPE.DEPARTMENTID
			LEFT JOIN USERS ON USERS.SUSERGUID = PLITEMREVIEW.ASSIGNEDUSERID
END