CREATE PROCEDURE [codecase].[USP_CMCODECASECONTACT_GETBYIDS]
	@CMCODECASELIST RecordIDs READONLY,
	@ROLEID AS CHAR(36)
AS
	BEGIN
	SELECT	[CMCODECASECONTACT].[CMCODECASEID],
			[CMCODECASECONTACT].[GLOBALENTITYID],
			[GLOBALENTITY].[FIRSTNAME],
			[GLOBALENTITY].[LASTNAME],
			[GLOBALENTITY].[GLOBALENTITYNAME],
			[CMCODECASECONTACT].[ISBILLING], 
			[GLOBALENTITY].[TITLE],
			[GLOBALENTITY].[ISACTIVE],
			[CMCODECASECONTACTTYPE].[CMCODECASECONTACTTYPEID],
			[CMCODECASECONTACTTYPENAME] = [CMCODECASECONTACTTYPE].[NAME],
			ISHIDDENCONTACTTYPE = (SELECT [codecase].[UFN_CHECK_CODECASE_HIDDENCONTACT] ([CMCODECASECONTACT].[CMCODECASECONTACTTYPEID], @ROLEID))		
	FROM	[dbo].[CMCODECASECONTACT]
			JOIN [dbo].[GLOBALENTITY] ON [dbo].[CMCODECASECONTACT].[GLOBALENTITYID] = [GLOBALENTITY].[GLOBALENTITYID]
			JOIN [dbo].[CMCODECASECONTACTTYPE] ON [CMCODECASECONTACTTYPE].[CMCODECASECONTACTTYPEID] = [CMCODECASECONTACT].[CMCODECASECONTACTTYPEID]
			JOIN @CMCODECASELIST CMCODECASELIST ON [dbo].[CMCODECASECONTACT].[CMCODECASEID] = [CMCODECASELIST].[RECORDID]
END