CREATE PROCEDURE [codecase].[USP_CMCODECASEVIOLATORADDRESS_GETBYIDS]
	@CMCODECASELIST RecordIDs READONLY
AS
	BEGIN
	SELECT	GLOBALENTITY.GLOBALENTITYID,
			GLOBALENTITYMAILINGADDRESS.GLOBALENTITYMAILINGADDRESSID,
			MAILINGADDRESS.ADDRESSLINE1,
			MAILINGADDRESS.ADDRESSLINE2,
			MAILINGADDRESS.ADDRESSLINE3,
			MAILINGADDRESS.ADDRESSTYPE,
			MAILINGADDRESS.ATTN,
			MAILINGADDRESS.CITY,
			MAILINGADDRESS.COMPSITE,
			MAILINGADDRESS.COUNTRY,
			MAILINGADDRESSCOUNTRYTYPE.MAILINGADDRESSCOUNTRYTYPEID,
			MAILINGADDRESSCOUNTRYTYPE.MAILINGADDRESSCOUNTRYTYPENAME,
			GLOBALENTITYMAILINGADDRESS.MAIN,
			MAILINGADDRESS.POBOX,
			MAILINGADDRESS.POSTALCODE,
			MAILINGADDRESS.POSTDIRECTION,
			MAILINGADDRESS.PREDIRECTION,
			MAILINGADDRESS.PROVINCE,
			MAILINGADDRESS.RURALROUTE,
			MAILINGADDRESS.STATE,
			MAILINGADDRESS.STATION,
			MAILINGADDRESS.STREETTYPE,
			MAILINGADDRESS.UNITORSUITE,
			MAILINGADDRESS.ADDRESSID
	FROM	GLOBALENTITYMAILINGADDRESS
			JOIN MAILINGADDRESS ON GLOBALENTITYMAILINGADDRESS.MAILINGADDRESSID = MAILINGADDRESS.MAILINGADDRESSID
			JOIN GLOBALENTITY ON GLOBALENTITY.GLOBALENTITYID = GLOBALENTITYMAILINGADDRESS.GLOBALENTITYID
			JOIN MAILINGADDRESSCOUNTRYTYPE ON MAILINGADDRESS.COUNTRYTYPE = MAILINGADDRESSCOUNTRYTYPE.MAILINGADDRESSCOUNTRYTYPEID
			JOIN @CMCODECASELIST CMCODECASELIST ON GLOBALENTITY.GLOBALENTITYID = CMCODECASELIST.RECORDID
	WHERE	GLOBALENTITYMAILINGADDRESS.MAIN = 1
	
END