CREATE PROCEDURE [codecase].[USP_CMCODECASE_RECENT]
(
  @USER_ID AS CHAR(36),
  @ROLEID AS CHAR(36)
)
AS
BEGIN
	DECLARE @RECENTCODECASELIST AS RecordIDs
	INSERT INTO @RECENTCODECASELIST (RECORDID)

	SELECT		TOP 15 RECENTHISTORYCODECASE.CODECASEID
	FROM		RECENTHISTORYCODECASE
	WHERE		RECENTHISTORYCODECASE.USERID = @USER_ID
	ORDER BY	RECENTHISTORYCODECASE.LOGGEDDATETIME DESC

	EXEC [codecase].[USP_CMCODECASE_GETBYIDS] @RECENTCODECASELIST, @USER_ID, @ROLEID

END