CREATE PROCEDURE [codecase].[USP_CMCODECASE_GETBYID]
(
	@ID AS CHAR(36),
	@ROLEID AS CHAR(36)
)
AS
BEGIN
	DECLARE @CMCODECASELIST AS RecordIDs
	INSERT INTO @CMCODECASELIST (RECORDID) VALUES (@ID)
	EXEC [codecase].[USP_CMCODECASE_GETBYIDS] @CMCODECASELIST, NULL, @ROLEID
END