CREATE PROCEDURE [dbo].[USP_ERPROJECTFILECATEGORY_INSERT]
(
	@ERPROJECTFILECATEGORYID CHAR(36),
	@NAME NVARCHAR(50),
	@DESCRIPTION NVARCHAR(MAX),
	@ALLOWEDFILETYPES NVARCHAR(MAX),
	@ATTACHMENTGROUPID CHAR(36),
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT,
	@FILENAMEPREFIX INT = 0,
	@FILENAMEPREFIXCUSTOM NVARCHAR(20) = NULL,
	@FILENAMEBODY INT = 2,
	@FILENAMEBODYCUSTOM NVARCHAR(50) = NULL,
	@FILENAMESUFFIX INT = 0,
	@FILENAMESUFFIXCUSTOM NVARCHAR(20) = NULL
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
INSERT INTO [dbo].[ERPROJECTFILECATEGORY](
	[ERPROJECTFILECATEGORYID],
	[NAME],
	[DESCRIPTION],
	[ALLOWEDFILETYPES],
	[ATTACHMENTGROUPID],
	[LASTCHANGEDBY],
	[LASTCHANGEDON],
	[ROWVERSION],
	[FILENAMEPREFIX],
	[FILENAMEPREFIXCUSTOM],
	[FILENAMEBODY],
	[FILENAMEBODYCUSTOM],
	[FILENAMESUFFIX],
	[FILENAMESUFFIXCUSTOM]
)
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
VALUES
(
	@ERPROJECTFILECATEGORYID,
	@NAME,
	@DESCRIPTION,
	@ALLOWEDFILETYPES,
	@ATTACHMENTGROUPID,
	@LASTCHANGEDBY,
	@LASTCHANGEDON,
	@ROWVERSION,
	@FILENAMEPREFIX,
	@FILENAMEPREFIXCUSTOM,
	@FILENAMEBODY,
	@FILENAMEBODYCUSTOM,
	@FILENAMESUFFIX,
	@FILENAMESUFFIXCUSTOM
)
SELECT * FROM @OUTPUTTABLE