CREATE PROCEDURE [dbo].[USP_EXAMTIMESLOT_INSERT]
(
	@EXAMTIMESLOTID CHAR(36),
	@NAME NVARCHAR(50),
	@STARTTIME DATETIME,
	@ENDTIME DATETIME,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
INSERT INTO [dbo].[EXAMTIMESLOT](
	[EXAMTIMESLOTID],
	[NAME],
	[STARTTIME],
	[ENDTIME],
	[LASTCHANGEDBY],
	[LASTCHANGEDON],
	[ROWVERSION]
)
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
VALUES
(
	@EXAMTIMESLOTID,
	@NAME,
	@STARTTIME,
	@ENDTIME,
	@LASTCHANGEDBY,
	@LASTCHANGEDON,
	@ROWVERSION
)
SELECT * FROM @OUTPUTTABLE