CREATE PROCEDURE [dbo].[USP_EXAMTYPERULE_INSERT]
(
	@EXAMTYPERULEID CHAR(36),
	@EXAMTYPEID CHAR(36),
	@EXAMRULEID CHAR(36),
	@BITVALUE BIT,
	@STRINGVALUE NVARCHAR(500),
	@INTVALUE INT
)
AS

INSERT INTO [dbo].[EXAMTYPERULE](
	[EXAMTYPERULEID],
	[EXAMTYPEID],
	[EXAMRULEID],
	[BITVALUE],
	[STRINGVALUE],
	[INTVALUE]
)

VALUES
(
	@EXAMTYPERULEID,
	@EXAMTYPEID,
	@EXAMRULEID,
	@BITVALUE,
	@STRINGVALUE,
	@INTVALUE
)