CREATE PROCEDURE [dbo].[USP_EXAMTYPE_DELETE]
(
	@EXAMTYPEID CHAR(36),
	@ROWVERSION INT
)
AS
BEGIN
SET NOCOUNT ON;

EXEC [dbo].[USP_EXAMTYPEVERSION_DELETE_BYPARENTID] @EXAMTYPEID
EXEC [dbo].[USP_EXAMTYPERULE_DELETE_BYPARENTID] @EXAMTYPEID
EXEC [dbo].[USP_EXAMSITTINGDATE_DELETE_BYPARENTID] @EXAMTYPEID

SET NOCOUNT OFF;

DELETE FROM [dbo].[EXAMTYPE]
WHERE
	[EXAMTYPEID] = @EXAMTYPEID AND 
	[ROWVERSION]= @ROWVERSION

END