CREATE PROCEDURE [dbo].[USP_EXAMTIMESLOT_DELETE]
(
	@EXAMTIMESLOTID CHAR(36),
	@ROWVERSION INT
)
AS
DELETE FROM [dbo].[EXAMTIMESLOT]
WHERE
	[EXAMTIMESLOTID] = @EXAMTIMESLOTID AND 
	[ROWVERSION]= @ROWVERSION