CREATE PROCEDURE [systemsetup].[USP_ROLESSETTING_SELECT_LOOKUP]
AS
SET NOCOUNT ON;
SELECT 
	[dbo].[ROLESSETTING].[ROLESSETTINGID],
	[dbo].[ROLESSETTING].[NAME]
FROM [dbo].[ROLESSETTING]
ORDER BY [dbo].[ROLESSETTING].[NAME] ASC