CREATE PROCEDURE [systemsetup].[USP_QUERYACTIONHOLDTYPE_GETBYPARENTID]
(
	@QUERYID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[QUERYACTIONHOLDTYPE].[QUERYACTIONHOLDTYPEID],
	[dbo].[QUERYACTIONHOLDTYPE].[QUERYACTIONID],
	[dbo].[QUERYACTIONHOLDTYPE].[HOLDSETUPID],
	[dbo].[QUERYACTIONHOLDTYPE].[COMMENTS]
FROM [dbo].[QUERYACTIONHOLDTYPE]
INNER JOIN [dbo].[QUERYACTION] ON [dbo].[QUERYACTION].[QUERYACTIONID] = 
[dbo].[QUERYACTIONHOLDTYPE].[QUERYACTIONID]
WHERE
	[dbo].[QUERYACTION].[QUERYID] = @QUERYID
END