CREATE PROCEDURE [systemsetup].[USP_IMINSPECTORTYPEUSER_GETBYPARENTID]
(
	@PARENTID CHAR(36)
)
AS
BEGIN
	SET NOCOUNT ON;

	SELECT		[dbo].[IMINSPECTORTYPEUSER].[INSPECTORTYPEID],
				[dbo].[IMINSPECTORTYPEUSER].[USERID],
				[dbo].[IMINSPECTORTYPEUSER].[PRIMARYINSPECTOR],
				[dbo].[IMINSPECTORTYPE].[SNAME] AS INSPECTORTYPENAME
	FROM		[dbo].[IMINSPECTORTYPEUSER]
				INNER JOIN [dbo].[IMINSPECTORTYPE] ON [dbo].[IMINSPECTORTYPEUSER].[INSPECTORTYPEID] = [dbo].[IMINSPECTORTYPE].[IMINSPECTORTYPEID]
	WHERE		[dbo].[IMINSPECTORTYPEUSER].[USERID] = @PARENTID
	ORDER BY	[dbo].[IMINSPECTORTYPE].[SNAME]
END