CREATE PROCEDURE [systemsetup].[USP_FTPTYPE_SELECT_LOOKUP]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[FTPTYPE].[FTPTYPEID],
	[dbo].[FTPTYPE].[NAME],
	[dbo].[FTPTYPE].[DESCRIPTION]
FROM 
	[dbo].[FTPTYPE]
ORDER BY 
	[dbo].[FTPTYPE].[NAME]
END