CREATE PROCEDURE [systemsetup].[USP_ATTACHMENTGROUPTCMXREF_GETALL]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT	[dbo].[ATTACHMENTGROUPTCMXREF].[ATTACHMENTGROUPTCMXREFID],
			[dbo].[ATTACHMENTGROUPTCMXREF].[ATTACHMENTGROUPID],
			[dbo].[ATTACHMENTGROUP].[NAME],
			[dbo].[ATTACHMENTGROUPTCMXREF].[ROWVERSION],
			[dbo].[ATTACHMENTGROUPTCMXREF].[LASTCHANGEDBY],
			[dbo].[ATTACHMENTGROUPTCMXREF].[LASTCHANGEDON]
	FROM	[dbo].[ATTACHMENTGROUPTCMXREF]
	INNER JOIN [dbo].[ATTACHMENTGROUP] ON [dbo].[ATTACHMENTGROUP].[ATTACHMENTGROUPID] = [dbo].[ATTACHMENTGROUPTCMXREF].[ATTACHMENTGROUPID]
	ORDER BY [dbo].[ATTACHMENTGROUP].[NAME]
END