CREATE PROCEDURE [systemsetup].[USP_WORKFLOWACTIONSETCALENDARDUEDA_GETBYPARENTID]
(
	@WORKFLOWID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[WORKFLOWACTIONSETCALENDARDUEDA].[WORKFLOWACTIONSETCALEDUEDTID],
	[dbo].[WORKFLOWACTIONSETCALENDARDUEDA].[WORKFLOWACTIONID],
	[dbo].[WORKFLOWACTIONSETCALENDARDUEDA].[SETVALUEFIELD],
	[dbo].[WORKFLOWACTIONSETCALENDARDUEDA].[SETVALUEFIELDFRIENDLYNAME]
FROM [dbo].[WORKFLOWACTIONSETCALENDARDUEDA]
INNER JOIN [dbo].[WORKFLOWACTION] ON [dbo].[WORKFLOWACTION].[WORKFLOWACTIONID] = [dbo].[WORKFLOWACTIONSETCALENDARDUEDA].[WORKFLOWACTIONID]
WHERE
	[dbo].[WORKFLOWACTION].[WORKFLOWID] = @WORKFLOWID
END