CREATE PROCEDURE [systemsetup].[USP_QUERYACTION_MAILMERGETEMPLATE_GETBYPARENTID]
(
	@QUERYID CHAR(36)
)
AS
BEGIN
	SELECT 
		[dbo].[QUERYACTION].[QUERYACTIONID],
		[dbo].[MAILMERGETEMPLATE].[MAILMERGETEMPLATEID],
		[dbo].[MAILMERGETEMPLATE].[SENDFROM],
		[dbo].[MAILMERGETEMPLATE].[SENDTO],		
		[dbo].[MAILMERGETEMPLATE].[CCTO],
		[dbo].[MAILMERGETEMPLATE].[BCCTO],
		[dbo].[MAILMERGETEMPLATE].[SUBJECT],
		[dbo].[MAILMERGETEMPLATE].[BODY],
		[dbo].[MAILMERGETEMPLATE].[ISHTML],
		[dbo].[MAILMERGETEMPLATE].[RPTREPORTID]
	FROM [dbo].[MAILMERGETEMPLATE]
	INNER JOIN [dbo].[QUERYACTIONMAILMERGETMPL] on [dbo].[MAILMERGETEMPLATE].[MAILMERGETEMPLATEID] = [dbo].[QUERYACTIONMAILMERGETMPL].[MAILMERGETEMPLATEID]	
	INNER JOIN [dbo].[QUERYACTION] on [dbo].[QUERYACTIONMAILMERGETMPL].[QUERYACTIONID] =[dbo].[QUERYACTION].[QUERYACTIONID]
	WHERE [dbo].[QUERYACTION].[QUERYID] = @QUERYID

END