CREATE PROCEDURE [systemsetup].[USP_WORKFLOWACTIONTASK_GETBYPARENTID]
(
	@WORKFLOWID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[WORKFLOWACTIONTASK].[WORKFLOWACTIONTASKID],
	[dbo].[WORKFLOWACTIONTASK].[WORKFLOWACTIONID],
	[dbo].[WORKFLOWACTIONTASK].[TASKSUBJECT],
	[dbo].[WORKFLOWACTIONTASK].[TASKTEXT],
	[dbo].[WORKFLOWACTIONTASK].[STARTDATE],
	[dbo].[WORKFLOWACTIONTASK].[DUEDATE],
	[dbo].[WORKFLOWACTIONTASK].[STARTTIME],
	[dbo].[WORKFLOWACTIONTASK].[DUETIME],
	[dbo].[WORKFLOWACTIONTASK].[STARTDATEOFFSETDAYS],
	[dbo].[WORKFLOWACTIONTASK].[DUEDATEOFFSETDAYS],
	[dbo].[WORKFLOWACTIONTASK].[TASKPRIORITYID],
	[dbo].[WORKFLOWACTIONTASK].[SHOWONCALENDAR],
	[dbo].[WORKFLOWACTIONTASK].[ASSIGNEDTO]
FROM [dbo].[WORKFLOWACTIONTASK]
INNER JOIN [dbo].[WORKFLOWACTION] ON [dbo].[WORKFLOWACTION].[WORKFLOWACTIONID] = [dbo].[WORKFLOWACTIONTASK].[WORKFLOWACTIONID]
WHERE
	[dbo].[WORKFLOWACTION].[WORKFLOWID] = @WORKFLOWID
END