CREATE PROCEDURE [systemsetup].[USP_QUERYACTIONATTACHDOC_GETBYPARENTID]
(
	@QUERYID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[QUERYACTIONATTACHDOC].[QUERYACTIONATTACHDOCID],
	[dbo].[QUERYACTIONATTACHDOC].[QUERYACTIONID],
	[dbo].[QUERYACTIONATTACHDOC].[ATTACHMENTGROUPID],
	[dbo].[QUERYACTIONATTACHDOC].[NOTES],
	[dbo].[QUERYACTIONATTACHDOC].[RPTREPORTID]
FROM [dbo].[QUERYACTIONATTACHDOC]
JOIN [dbo].[QUERYACTION] ON [dbo].[QUERYACTIONATTACHDOC].[QUERYACTIONID] = [dbo].[QUERYACTION].[QUERYACTIONID]
WHERE [dbo].[QUERYACTION].[QUERYID] = @QUERYID

END