CREATE PROCEDURE [systemsetup].[USP_RPTAUTOMAIL_GETALL]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[RPTAUTOMAIL].[RPTAUTOMAILID],
	[dbo].[RPTAUTOMAIL].[SESSIONNAME],
	[dbo].[RPTAUTOMAIL].[RPTDATERANGEID],
	[dbo].[RPTAUTOMAIL].[DAYNUMDATE],
	[dbo].[RPTAUTOMAIL].[RPTREPORTID],
	[dbo].[RPTAUTOMAIL].[RECURRENCEID],
	[dbo].[RPTAUTOMAIL].[DESCRIPTION],
	[dbo].[RPTAUTOMAIL].[LASTRECURRENCE],
	[dbo].[RPTAUTOMAIL].[NEXTRECURRENCE],
	[dbo].[RPTAUTOMAIL].[CUSTOMSUBJECT],
	[dbo].[RPTAUTOMAIL].[CUSTOMBODY],
	[dbo].[RPTAUTOMAIL].[FTPSETUPID],
	[dbo].[RPTAUTOMAIL].[SUBPATH],
	[dbo].[RPTAUTOMAIL].[LASTCHANGEDON],
	[dbo].[RPTAUTOMAIL].[LASTCHANGEDBY],
	[dbo].[RPTAUTOMAIL].[ROWVERSION],
	[dbo].[RPTREPORT].[REPORTNAME],
	[dbo].[RECURRENCE].[NAME],
	[dbo].[RPTREPORT].[RPTREPORTTYPEID],
	[dbo].[RPTAUTOMAIL].[RPTREPORTFILETYPEID]
FROM [dbo].[RPTAUTOMAIL] 
INNER JOIN [dbo].[RPTREPORT] ON [dbo].[RPTREPORT].[RPTREPORTID] = [dbo].[RPTAUTOMAIL].[RPTREPORTID]
INNER JOIN [dbo].[RECURRENCE] ON [dbo].[RECURRENCE].[RECURRENCEID] = [dbo].[RPTAUTOMAIL].[RECURRENCEID]
ORDER BY [dbo].[RPTAUTOMAIL].[SESSIONNAME] ASC

EXEC [systemsetup].[USP_RPTMAILTO_GETALL]
EXEC [systemsetup].[USP_RPTREPORTATTRIBUTE_GETALL] 
EXEC [systemsetup].[USP_RPTPRINTTO_GETALL]

END