CREATE PROCEDURE [systemsetup].[USP_QUERY_BY_QUERYBUILDERID]
(
	@QUERYBUILDERID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 	
	[dbo].[QUERY].[QUERYID],
	[dbo].[QUERY].[NAME]
FROM [dbo].[QUERY]
WHERE
	[dbo].[QUERY].[QUERYBUILDERID] = @QUERYBUILDERID
ORDER BY
	[dbo].[QUERY].[NAME]
END