CREATE PROCEDURE [systemsetup].[USP_CAPRPTSETTINGS_GETALL]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT		[dbo].[CAPRPTSETTINGS].[CAPRPTSETTINGSID],
				[dbo].[CAPRPTSETTINGS].[NAME],
				[dbo].[CAPRPTSETTINGS].[MODULETYPE],
				[dbo].[CAPRPTSETTINGS].[MODULECLASS],
				[dbo].[CAPRPTSETTINGS].[RPTREPORTID],
				[dbo].[CAPRPTSETTINGS].[CAPMODULESID],
				[dbo].[CAPRPTSETTINGS].[LASTCHANGEDBY],
				[dbo].[CAPRPTSETTINGS].[LASTCHANGEDON],
				[dbo].[CAPRPTSETTINGS].[ROWVERSION],
				COALESCE([PLAPPLICATIONTYPE].[APPLICATIONTYPENAME],
						[BLEXTCOMPANYTYPE].[NAME],
						[CASHIER].[CASHIERNAME],
						[CMCASETYPE].[NAME],
						[IMINSPECTIONTYPE].[NAME],
						[BLLICENSETYPE].[NAME],
						[PMPERMITTYPE].[NAME],
						[PLPLANTYPE].[PLANNAME],
						[ILLICENSETYPE].[NAME],
						[CITIZENREQUESTTYPE].[NAME],
						[TXREMITTANCETYPE].[NAME]) AS MODULETYPENAME,
				COALESCE([BLLICENSECLASS].[NAME],
						[PMPERMITWORKCLASS].[NAME],
						[PLPLANWORKCLASS].[NAME],
						[ILLICENSECLASSIFICATION].[NAME]) AS MODULECLASSNAME,
				[dbo].[RPTREPORT].[FRIENDLYNAME]
	FROM		[dbo].[CAPRPTSETTINGS]
				JOIN [dbo].[RPTREPORT] ON [dbo].[RPTREPORT].[RPTREPORTID] = [dbo].[CAPRPTSETTINGS].[RPTREPORTID]
				LEFT JOIN [dbo].[PLAPPLICATIONTYPE] ON [dbo].[PLAPPLICATIONTYPE].[PLAPPLICATIONTYPEID] = [dbo].[CAPRPTSETTINGS].[MODULETYPE]
				LEFT JOIN [dbo].[BLEXTCOMPANYTYPE] ON [dbo].[BLEXTCOMPANYTYPE].[BLEXTCOMPANYTYPEID] = [dbo].[CAPRPTSETTINGS].[MODULETYPE]
				LEFT JOIN (
							SELECT CASHIERID = '1', CASHIERNAME = 'Receipt'
							UNION
							SELECT CASHIERID = '2', CASHIERNAME = 'Invoice'
						  ) [CASHIER] ON [CASHIER].[CASHIERID] = [dbo].[CAPRPTSETTINGS].[MODULETYPE]
				LEFT JOIN [dbo].[CMCASETYPE] ON [dbo].[CMCASETYPE].[CMCASETYPEID] = [dbo].[CAPRPTSETTINGS].[MODULETYPE]
				LEFT JOIN [dbo].[IMINSPECTIONTYPE] ON [dbo].[IMINSPECTIONTYPE].[IMINSPECTIONTYPEID] = [dbo].[CAPRPTSETTINGS].[MODULETYPE]
				LEFT JOIN [dbo].[BLLICENSETYPE] ON [dbo].[BLLICENSETYPE].[BLLICENSETYPEID] = [dbo].[CAPRPTSETTINGS].[MODULETYPE]
				LEFT JOIN [dbo].[PMPERMITTYPE] ON [dbo].[PMPERMITTYPE].[PMPERMITTYPEID] = [dbo].[CAPRPTSETTINGS].[MODULETYPE]
				LEFT JOIN [dbo].[PLPLANTYPE] ON [dbo].[PLPLANTYPE].[PLPLANTYPEID] = [dbo].[CAPRPTSETTINGS].[MODULETYPE]
				LEFT JOIN [dbo].[ILLICENSETYPE] ON [dbo].[ILLICENSETYPE].[ILLICENSETYPEID] = [dbo].[CAPRPTSETTINGS].[MODULETYPE]
				LEFT JOIN [dbo].[CITIZENREQUESTTYPE] ON [dbo].[CITIZENREQUESTTYPE].[CITIZENREQUESTTYPEID] = [dbo].[CAPRPTSETTINGS].[MODULETYPE]
				LEFT JOIN [dbo].[TXREMITTANCETYPE] ON [dbo].[TXREMITTANCETYPE].[TXREMITTANCETYPEID] = [dbo].[CAPRPTSETTINGS].[MODULETYPE]

				LEFT JOIN [dbo].[BLLICENSECLASS] ON [dbo].[BLLICENSECLASS].[BLLICENSECLASSID] = [dbo].[CAPRPTSETTINGS].[MODULECLASS]
				LEFT JOIN [dbo].[PMPERMITWORKCLASS] ON [dbo].[PMPERMITWORKCLASS].[PMPERMITWORKCLASSID] = [dbo].[CAPRPTSETTINGS].[MODULECLASS]
				LEFT JOIN [dbo].[PLPLANWORKCLASS] ON [dbo].[PLPLANWORKCLASS].[PLPLANWORKCLASSID] = [dbo].[CAPRPTSETTINGS].[MODULECLASS]
				LEFT JOIN [dbo].[ILLICENSECLASSIFICATION] ON [dbo].[ILLICENSECLASSIFICATION].[ILLICENSECLASSIFICATIONID] = [dbo].[CAPRPTSETTINGS].[MODULECLASS]
	
	ORDER BY	COALESCE([PLAPPLICATIONTYPE].[APPLICATIONTYPENAME],
				[BLEXTCOMPANYTYPE].[NAME],
				[CASHIER].[CASHIERNAME],
				[CMCASETYPE].[NAME],
				[IMINSPECTIONTYPE].[NAME],
				[BLLICENSETYPE].[NAME],
				[PMPERMITTYPE].[NAME],
				[PLPLANTYPE].[PLANNAME],
				[ILLICENSETYPE].[NAME],
				[CITIZENREQUESTTYPE].[NAME],
				[TXREMITTANCETYPE].[NAME])
END