CREATE PROCEDURE [systemsetup].[USP_CAPSETTING_GETALL]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 	[dbo].[CAPSETTING].[CAPSETTINGID],
			[dbo].[CAPSETTING].[NAME],
			[dbo].[CAPSETTING].[BITVALUE],
			[dbo].[CAPSETTING].[STRINGVALUE],
			[dbo].[CAPSETTING].[INTVALUE],
			[dbo].[CAPSETTING].[IMAGEVALUE],
			[dbo].[CAPSETTING].[LASTCHANGEDBY],
			[dbo].[CAPSETTING].[LASTCHANGEDON],
			[dbo].[CAPSETTING].[ROWVERSION],
			[CAPSETTINGMETADATA].[FRIENDLYNAME]
	FROM	[dbo].[CAPSETTING]
			LEFT JOIN [dbo].[CAPSETTINGMETADATA] ON [dbo].[CAPSETTINGMETADATA].[CAPSETTINGNAME] = [dbo].[CAPSETTING].[NAME]
	ORDER BY [dbo].[CAPSETTING].[NAME] ASC
END