CREATE PROCEDURE [systemsetup].[USP_PLPLANCORRECTIONTYPE_SELECT_LOOKUP]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT		[dbo].[PLPLANCORRECTIONTYPE].[PLPLANCORRECTIONTYPEID],
				[dbo].[PLPLANCORRECTIONTYPE].[NAME]
	FROM		[dbo].[PLPLANCORRECTIONTYPE]
	ORDER BY	[dbo].[PLPLANCORRECTIONTYPE].[NAME]
END