CREATE PROCEDURE [systemsetup].[USP_RPTREPORTATTRIBUTE_GETBYRPTREPORTID]
(
	@RPTREPORTID AS CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[RPTREPORTATTRIBUTE].[RPTREPORTATTRIBUTEID],
	[dbo].[RPTREPORTATTRIBUTE].[RPTREPORTID],
	[dbo].[RPTREPORTATTRIBUTE].[PARAMETERNAME],
	[dbo].[RPTREPORTATTRIBUTE].[ISSTARTDATE],
	[dbo].[RPTREPORTATTRIBUTE].[CHILDPARAMETERNAME],
	[dbo].[RPTREPORTATTRIBUTE].[PROPERTYFRIENDLYNAME],
	[dbo].[RPTREPORTATTRIBUTE].[RPTPARAMTYPEID],
	[dbo].[RPTREPORTATTRIBUTE].[PARAMETERORDER],
	[dbo].[RPTREPORTATTRIBUTE].[PROPERTYTOKEN],
	[dbo].[RPTREPORTATTRIBUTE].[BUSINESSOBJECTPROPERTYNAME],
	[dbo].[RPTREPORTATTRIBUTE].[VALUESOURCE],
	[dbo].[RPTREPORTATTRIBUTE].[ISREQUIRED],
	[dbo].[RPTREPORTATTRIBUTE].[ISMULTI]
FROM  [dbo].[RPTREPORTATTRIBUTE]
WHERE [dbo].[RPTREPORTATTRIBUTE].[RPTREPORTID]=@RPTREPORTID
ORDER BY [dbo].[RPTREPORTATTRIBUTE].[PARAMETERORDER] ASC
END