CREATE PROCEDURE [systemsetup].[USP_ATTACHMENTGROUPROLEXREF_GETBYPARENTID]
(
	@PARENTID CHAR(36)
)
AS
BEGIN
	SET NOCOUNT ON;
	SELECT  
		[dbo].[ATTACHMENTGROUPROLEXREF].[ATTACHMENTGROUPROLEID],
		[dbo].[ATTACHMENTGROUPROLEXREF].[ATTACHMENTGROUPID],
		[dbo].[ATTACHMENTGROUPROLEXREF].[ROLEID],
		[dbo].[ATTACHMENTGROUP].[NAME],
		[dbo].[ATTACHMENTGROUP].[AVAILINPERMIT],
		[dbo].[ATTACHMENTGROUP].[AVAILINPLAN],
		[dbo].[ATTACHMENTGROUP].[AVAILINCODE],
		[dbo].[ATTACHMENTGROUP].[AVAILINCRM],
		[dbo].[ATTACHMENTGROUP].[AVAILINPROJECT],
		[dbo].[ATTACHMENTGROUP].[AVAILINWORKORDER],
		[dbo].[ATTACHMENTGROUP].[AVAILINASSET],
		[dbo].[ATTACHMENTGROUP].[AVAILININVOICE],
		[dbo].[ATTACHMENTGROUP].[AVAILINPAYMENT],
		[dbo].[ATTACHMENTGROUP].[AVAILININSPECTION],
		[dbo].[ATTACHMENTGROUP].[AVAILINCONTACT],
		[dbo].[ATTACHMENTGROUP].[AVAILINBUSINESSLICENSE],
		[dbo].[ATTACHMENTGROUP].[AVAILINBUSINESS],
		[dbo].[ATTACHMENTGROUP].[AVAILINPROLICENSE],
		[dbo].[ATTACHMENTGROUP].[AVAILINEXAMSITTING],
		[dbo].[ATTACHMENTGROUP].[AVAILINEXAMREQUEST],
		[dbo].[ATTACHMENTGROUP].[AVAILINEXAMLANDLORD],
		[dbo].[ATTACHMENTGROUP].[AVAILINEXAMRENTALPROPERTY],
		[dbo].[ATTACHMENTGROUP].[AVAILINEXAMTAXREMITTANCE],
		[dbo].[ATTACHMENTGROUP].[AVAILINCAP],
		[dbo].[ATTACHMENTGROUP].[AVAILINCAPCONTACTS],
		[dbo].[ATTACHMENTGROUP].[AVAILINOBJEC],
		[dbo].[ATTACHMENTGROUP].[AVAILINIMPACTCASE],
		[dbo].[ATTACHMENTGROUP].[AVAILINFIREOCCUPANCY]
	FROM [dbo].[ATTACHMENTGROUPROLEXREF]
	INNER JOIN [dbo].[ATTACHMENTGROUP] ON [dbo].[ATTACHMENTGROUPROLEXREF].[ATTACHMENTGROUPID] = [dbo].[ATTACHMENTGROUP].[ATTACHMENTGROUPID]
	WHERE [dbo].[ATTACHMENTGROUPROLEXREF].[ROLEID] = @PARENTID
	ORDER BY [dbo].[ATTACHMENTGROUP].[NAME]
END