CREATE PROCEDURE [systemsetup].[USP_CAPRPTSETTINGS_MODULETYPE_SEARCH]
(
	@SEARCH			AS NVARCHAR(MAX)	=	'',
	@PAGE_NUMBER	AS INT				=	1,
	@PAGE_SIZE		AS INT				=	10,
	@IS_ASCENDING	AS BIT				=	1,
	@CAPMODULESID	AS INT				=	0
)
AS

DECLARE @MODULENAME NVARCHAR(100) = (SELECT [CAPMODULES].[NAME] FROM [CAPMODULES] WITH (NOLOCK) WHERE [CAPMODULES].[CAPMODULESID] = @CAPMODULESID)

IF (@MODULENAME = 'Application')
BEGIN
	WITH RAW_DATA AS (
		SELECT	[dbo].[PLAPPLICATIONTYPE].[PLAPPLICATIONTYPEID] AS MODULETYPEID,
				[dbo].[PLAPPLICATIONTYPE].[APPLICATIONTYPENAME] AS MODULETYPENAME,
				CASE @IS_ASCENDING WHEN 1 THEN ROW_NUMBER() OVER(ORDER BY [dbo].[PLAPPLICATIONTYPE].[APPLICATIONTYPENAME])
									ELSE ROW_NUMBER() OVER (ORDER BY [dbo].[PLAPPLICATIONTYPE].[APPLICATIONTYPENAME] DESC)
				END AS RowNumber,
				COUNT(1) OVER() AS TotalRows
		FROM	[dbo].[PLAPPLICATIONTYPE]
		WHERE	[dbo].[PLAPPLICATIONTYPE].[APPLICATIONTYPENAME] LIKE '%'+ @SEARCH +'%'
	)
	SELECT		* 
	FROM		RAW_DATA
	WHERE		RowNumber > @PAGE_SIZE * (@PAGE_NUMBER - 1) AND RowNumber <= @PAGE_SIZE * @PAGE_NUMBER
	ORDER BY	RowNumber
END
ELSE IF (@MODULENAME = 'Business')
BEGIN
	WITH RAW_DATA AS (
		SELECT	[dbo].[BLEXTCOMPANYTYPE].[BLEXTCOMPANYTYPEID] AS MODULETYPEID,
				[dbo].[BLEXTCOMPANYTYPE].[NAME] AS MODULETYPENAME,
				CASE @IS_ASCENDING WHEN 1 THEN ROW_NUMBER() OVER(ORDER BY [dbo].[BLEXTCOMPANYTYPE].[NAME])
									ELSE ROW_NUMBER() OVER (ORDER BY [dbo].[BLEXTCOMPANYTYPE].[NAME] DESC)
				END AS RowNumber,
				COUNT(1) OVER() AS TotalRows
		FROM	[dbo].[BLEXTCOMPANYTYPE]
		WHERE	[dbo].[BLEXTCOMPANYTYPE].[NAME] LIKE '%'+ @SEARCH +'%'
	)
	SELECT		* 
	FROM		RAW_DATA
	WHERE		RowNumber > @PAGE_SIZE * (@PAGE_NUMBER - 1) AND RowNumber <= @PAGE_SIZE * @PAGE_NUMBER
	ORDER BY	RowNumber
END
ELSE IF (@MODULENAME = 'Cashier')
BEGIN
	SELECT	'2' AS MODULETYPEID, 'Invoice' AS MODULETYPENAME, 2 AS TotalRows
	UNION
	SELECT	'1' AS MODULETYPEID, 'Receipt' AS MODULETYPENAME, 2 AS TotalRows
	
END
ELSE IF (@MODULENAME = 'Code')
BEGIN
	WITH RAW_DATA AS (
		SELECT	[dbo].[CMCASETYPE].[CMCASETYPEID] AS MODULETYPEID,
				[dbo].[CMCASETYPE].[NAME] AS MODULETYPENAME,
				CASE @IS_ASCENDING WHEN 1 THEN ROW_NUMBER() OVER(ORDER BY [dbo].[CMCASETYPE].[NAME])
									ELSE ROW_NUMBER() OVER (ORDER BY [dbo].[CMCASETYPE].[NAME] DESC)
				END AS RowNumber,
				COUNT(1) OVER() AS TotalRows
		FROM	[dbo].[CMCASETYPE]
		WHERE	[dbo].[CMCASETYPE].[NAME] LIKE '%'+ @SEARCH +'%' AND [dbo].[CMCASETYPE].[ACTIVE] = 1
	)
	SELECT		* 
	FROM		RAW_DATA
	WHERE		RowNumber > @PAGE_SIZE * (@PAGE_NUMBER - 1) AND RowNumber <= @PAGE_SIZE * @PAGE_NUMBER
	ORDER BY	RowNumber
END
ELSE IF (@MODULENAME = 'Inspection')
BEGIN
	WITH RAW_DATA AS (
		SELECT	[dbo].[IMINSPECTIONTYPE].[IMINSPECTIONTYPEID] AS MODULETYPEID,
				[dbo].[IMINSPECTIONTYPE].[NAME] AS MODULETYPENAME,
				CASE @IS_ASCENDING WHEN 1 THEN ROW_NUMBER() OVER(ORDER BY [dbo].[IMINSPECTIONTYPE].[NAME])
									ELSE ROW_NUMBER() OVER (ORDER BY [dbo].[IMINSPECTIONTYPE].[NAME] DESC)
				END AS RowNumber,
				COUNT(1) OVER() AS TotalRows
		FROM	[dbo].[IMINSPECTIONTYPE]
		WHERE	[dbo].[IMINSPECTIONTYPE].[NAME] LIKE '%'+ @SEARCH +'%'
	)
	SELECT		* 
	FROM		RAW_DATA
	WHERE		RowNumber > @PAGE_SIZE * (@PAGE_NUMBER - 1) AND RowNumber <= @PAGE_SIZE * @PAGE_NUMBER
	ORDER BY	RowNumber
END
ELSE IF (@MODULENAME = 'License')
BEGIN
	WITH RAW_DATA AS (
		SELECT	[dbo].[BLLICENSETYPE].[BLLICENSETYPEID] AS MODULETYPEID,
				[dbo].[BLLICENSETYPE].[NAME] AS MODULETYPENAME,
				CASE @IS_ASCENDING WHEN 1 THEN ROW_NUMBER() OVER(ORDER BY [dbo].[BLLICENSETYPE].[NAME])
									ELSE ROW_NUMBER() OVER (ORDER BY [dbo].[BLLICENSETYPE].[NAME] DESC)
				END AS RowNumber,
				COUNT(1) OVER() AS TotalRows
		FROM	[dbo].[BLLICENSETYPE]
		WHERE	[dbo].[BLLICENSETYPE].[NAME] LIKE '%'+ @SEARCH +'%' AND [dbo].[BLLICENSETYPE].[ACTIVE] = 1
	)
	SELECT		* 
	FROM		RAW_DATA
	WHERE		RowNumber > @PAGE_SIZE * (@PAGE_NUMBER - 1) AND RowNumber <= @PAGE_SIZE * @PAGE_NUMBER
	ORDER BY	RowNumber
END
ELSE IF (@MODULENAME = 'Permit')
BEGIN
	WITH RAW_DATA AS (
		SELECT	[dbo].[PMPERMITTYPE].[PMPERMITTYPEID] AS MODULETYPEID,
				[dbo].[PMPERMITTYPE].[NAME] AS MODULETYPENAME,
				CASE @IS_ASCENDING WHEN 1 THEN ROW_NUMBER() OVER(ORDER BY [dbo].[PMPERMITTYPE].[NAME])
									ELSE ROW_NUMBER() OVER (ORDER BY [dbo].[PMPERMITTYPE].[NAME] DESC)
				END AS RowNumber,
				COUNT(1) OVER() AS TotalRows
		FROM	[dbo].[PMPERMITTYPE]
		WHERE	[dbo].[PMPERMITTYPE].[NAME] LIKE '%'+ @SEARCH +'%' AND [dbo].[PMPERMITTYPE].[ACTIVE] = 1
	)
	SELECT		* 
	FROM		RAW_DATA
	WHERE		RowNumber > @PAGE_SIZE * (@PAGE_NUMBER - 1) AND RowNumber <= @PAGE_SIZE * @PAGE_NUMBER
	ORDER BY	RowNumber
END
ELSE IF (@MODULENAME = 'Plan')
BEGIN
	WITH RAW_DATA AS (
		SELECT	[dbo].[PLPLANTYPE].[PLPLANTYPEID] AS MODULETYPEID,
				[dbo].[PLPLANTYPE].[PLANNAME] AS MODULETYPENAME,
				CASE @IS_ASCENDING WHEN 1 THEN ROW_NUMBER() OVER(ORDER BY [dbo].[PLPLANTYPE].[PLANNAME])
									ELSE ROW_NUMBER() OVER (ORDER BY [dbo].[PLPLANTYPE].[PLANNAME] DESC)
				END AS RowNumber,
				COUNT(1) OVER() AS TotalRows
		FROM	[dbo].[PLPLANTYPE]
		WHERE	[dbo].[PLPLANTYPE].[PLANNAME] LIKE '%'+ @SEARCH +'%' AND [dbo].[PLPLANTYPE].[ACTIVE] = 1
	)
	SELECT		* 
	FROM		RAW_DATA
	WHERE		RowNumber > @PAGE_SIZE * (@PAGE_NUMBER - 1) AND RowNumber <= @PAGE_SIZE * @PAGE_NUMBER
	ORDER BY	RowNumber
END
ELSE IF (@MODULENAME = 'Prof License')
BEGIN
	WITH RAW_DATA AS (
		SELECT	[dbo].[ILLICENSETYPE].[ILLICENSETYPEID] AS MODULETYPEID,
				[dbo].[ILLICENSETYPE].[NAME] AS MODULETYPENAME,
				CASE @IS_ASCENDING WHEN 1 THEN ROW_NUMBER() OVER(ORDER BY [dbo].[ILLICENSETYPE].[NAME])
									ELSE ROW_NUMBER() OVER (ORDER BY [dbo].[ILLICENSETYPE].[NAME] DESC)
				END AS RowNumber,
				COUNT(1) OVER() AS TotalRows
		FROM	[dbo].[ILLICENSETYPE]
		WHERE	[dbo].[ILLICENSETYPE].[NAME] LIKE '%'+ @SEARCH +'%' AND [dbo].[ILLICENSETYPE].[ACTIVE] = 1
	)
	SELECT		* 
	FROM		RAW_DATA
	WHERE		RowNumber > @PAGE_SIZE * (@PAGE_NUMBER - 1) AND RowNumber <= @PAGE_SIZE * @PAGE_NUMBER
	ORDER BY	RowNumber
END
ELSE IF (@MODULENAME = 'Request')
BEGIN
	WITH RAW_DATA AS (
		SELECT	[dbo].[CITIZENREQUESTTYPE].[CITIZENREQUESTTYPEID] AS MODULETYPEID,
				[dbo].[CITIZENREQUESTTYPE].[NAME] AS MODULETYPENAME,
				CASE @IS_ASCENDING WHEN 1 THEN ROW_NUMBER() OVER(ORDER BY [dbo].[CITIZENREQUESTTYPE].[NAME])
									ELSE ROW_NUMBER() OVER (ORDER BY [dbo].[CITIZENREQUESTTYPE].[NAME] DESC)
				END AS RowNumber,
				COUNT(1) OVER() AS TotalRows
		FROM	[dbo].[CITIZENREQUESTTYPE]
		WHERE	[dbo].[CITIZENREQUESTTYPE].[NAME] LIKE '%'+ @SEARCH +'%' AND [dbo].[CITIZENREQUESTTYPE].[ACTIVE] = 1
	)
	SELECT		* 
	FROM		RAW_DATA
	WHERE		RowNumber > @PAGE_SIZE * (@PAGE_NUMBER - 1) AND RowNumber <= @PAGE_SIZE * @PAGE_NUMBER
	ORDER BY	RowNumber
END
ELSE IF (@MODULENAME = 'TaxRemittance')
BEGIN
	WITH RAW_DATA AS (
		SELECT	[dbo].[TXREMITTANCETYPE].[TXREMITTANCETYPEID] AS MODULETYPEID,
				[dbo].[TXREMITTANCETYPE].[NAME] AS MODULETYPENAME,
				CASE @IS_ASCENDING WHEN 1 THEN ROW_NUMBER() OVER(ORDER BY [dbo].[TXREMITTANCETYPE].[NAME])
									ELSE ROW_NUMBER() OVER (ORDER BY [dbo].[TXREMITTANCETYPE].[NAME] DESC)
				END AS RowNumber,
				COUNT(1) OVER() AS TotalRows
		FROM	[dbo].[TXREMITTANCETYPE]
		WHERE	[dbo].[TXREMITTANCETYPE].[NAME] LIKE '%'+ @SEARCH +'%' AND [dbo].[TXREMITTANCETYPE].[ACTIVE] = 1
	)
	SELECT		* 
	FROM		RAW_DATA
	WHERE		RowNumber > @PAGE_SIZE * (@PAGE_NUMBER - 1) AND RowNumber <= @PAGE_SIZE * @PAGE_NUMBER
	ORDER BY	RowNumber
END