CREATE PROCEDURE [systemsetup].[USP_CLIENTCREDENTIAL_GETALL]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[CLIENTCREDENTIAL].[CLIENTCREDENTIALID],
	[dbo].[CLIENTCREDENTIAL].[CLIENTID],
	[dbo].[CLIENTCREDENTIAL].[SECRET],
	[dbo].[CLIENTCREDENTIAL].[SCOPE],
	[dbo].[CLIENTCREDENTIAL].[DESCRIPTION]
FROM 
	[dbo].[CLIENTCREDENTIAL]
ORDER BY 
	[dbo].[CLIENTCREDENTIAL].[CLIENTID]
END