CREATE PROCEDURE [systemsetup].[USP_WORKFLOWACTIONPARAMETER_GETBYPARENTID]
(
	@WORKFLOWID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[WORKFLOWACTIONPARAMETER].[WORKFLOWACTIONPARAMETERID],
	[dbo].[WORKFLOWACTIONPARAMETER].[WORKFLOWACTIONID],
	[dbo].[WORKFLOWACTIONPARAMETER].[PARAMETERNAME],
	[dbo].[WORKFLOWACTIONPARAMETER].[PARAMETERVALUE],
	[dbo].[WORKFLOWACTIONPARAMETER].[PARAMETERTYPE]
FROM [dbo].[WORKFLOWACTIONPARAMETER]
JOIN [dbo].[WORKFLOWACTION]  ON [dbo].[WORKFLOWACTIONPARAMETER].[WORKFLOWACTIONID] = [dbo].[WORKFLOWACTION].[WORKFLOWACTIONID]
WHERE [dbo].[WORKFLOWACTION].[WORKFLOWID] = @WORKFLOWID
ORDER BY [dbo].[WORKFLOWACTIONPARAMETER].[PARAMETERNAME]
END