CREATE PROCEDURE [systemsetup].[USP_QUERYBUILDER_SEARCH]
(
	@ROOTCLASSNAME AS NVARCHAR(MAX),
	@SEARCH AS NVARCHAR(MAX) = '',
	@PAGE_NUMBER AS INT = 1,
	@PAGE_SIZE AS INT = 10,
	@IS_ASCENDING AS BIT = 1
)
AS

WITH RAW_DATA AS(
	SELECT	[dbo].[QUERYBUILDER].[QUERYBUILDERID],
			[dbo].[QUERYBUILDER].[NAME],
			[dbo].[QUERYBUILDER].[DESCRIPTION],
			CASE @IS_ASCENDING WHEN 1 THEN
				ROW_NUMBER() OVER(ORDER BY [dbo].[QUERYBUILDER].[NAME])
			ELSE
				ROW_NUMBER() OVER(ORDER BY [dbo].[QUERYBUILDER].[NAME] DESC)
			END AS ROWNUMBER,
			COUNT(1) OVER() AS TotalRows
	FROM	[dbo].[QUERYBUILDER]
	WHERE	[dbo].[QUERYBUILDER].[ROOTCLASSNAME] = @ROOTCLASSNAME AND
			([dbo].[QUERYBUILDER].[NAME] LIKE '%'+@SEARCH+'%' OR [dbo].[QUERYBUILDER].[DESCRIPTION] LIKE '%'+@SEARCH+'%')
)

SELECT * 
FROM RAW_DATA
WHERE
	RowNumber > @PAGE_SIZE * (@PAGE_NUMBER - 1) AND 
	RowNumber <= @PAGE_SIZE * @PAGE_NUMBER
ORDER BY 
	RowNumber