CREATE PROCEDURE [systemsetup].[USP_MAILMERGETEMPLATEUSER_GETBYIDS]
(
	@MAILMERGETEMPLATEIDLIST RecordIDs READONLY
)
AS
BEGIN
	SET NOCOUNT ON;
	SELECT
		[dbo].[MAILMERGETEMPLATEUSER].[MAILMERGETEMPLATEUSERID],
		[dbo].[MAILMERGETEMPLATEUSER].[MAILMERGETEMPLATEID],
		[dbo].[USERS].[SUSERGUID],
		[dbo].[USERS].[FNAME],
		[dbo].[USERS].[LNAME],
		[dbo].[USERS].[ID],
		[dbo].[USERS].[EMAIL],
		[dbo].[MAILMERGETEMPLATEUSER].[MAILMERGETEMPLATEUSERTYPEID]
	FROM [dbo].[MAILMERGETEMPLATEUSER]
	INNER JOIN [dbo].[USERS] on [dbo].[MAILMERGETEMPLATEUSER].[USERID] = [dbo].[USERS].[SUSERGUID]
	WHERE [dbo].[MAILMERGETEMPLATEUSER].[MAILMERGETEMPLATEID] IN (SELECT [RECORDID] FROM @MAILMERGETEMPLATEIDLIST)
END