CREATE PROCEDURE [systemsetup].[USP_STOREDPROCEDUREPARAMETERS_BY_PROCEDURENAME]
(
	@PROCEDURENAME AS NVARCHAR(MAX)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[STOREDPROCEDUREPARAMETERS].[PARAMETERNAME],
	[dbo].[STOREDPROCEDUREPARAMETERS].[TYPENAME]
	FROM [dbo].[STOREDPROCEDUREPARAMETERS]
	WHERE [dbo].[STOREDPROCEDUREPARAMETERS].[PROCEDURENAME]=@PROCEDURENAME
	ORDER BY [dbo].[STOREDPROCEDUREPARAMETERS].PARAMETERNAME
END