CREATE PROCEDURE [systemsetup].[USP_BUSETTING_GETALL]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT		[dbo].[BUSETTING].[BUSETTINGID],
				[dbo].[BUSETTING].[ENTITY],
				[dbo].[BUSETTING].[STARTTIME],
				[dbo].[BUSETTING].[ENDTIME],
				[dbo].[BUSETTING].[NUMOFRECORD],
				[dbo].[BUSETTING].[ACTIVE],
				[dbo].[BUSETTING].[LASTCHANGEDBY],
				[dbo].[BUSETTING].[LASTCHANGEDON],
				[dbo].[BUSETTING].[ROWVERSION]
	FROM		[dbo].[BUSETTING]
			
	ORDER BY	[dbo].[BUSETTING].[BUSETTINGID]
END