CREATE PROCEDURE [systemsetup].[USP_ROLESROLESSETTING_GETBYUSERROLEID]
(
	@USERROLEID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
	SELECT 
		[dbo].[ROLESROLESSETTING].[ROLESSETTINGID],
		[dbo].[ROLESROLESSETTING].[ROLEID],
		[dbo].[ROLESSETTING].[NAME],
		[dbo].[ROLESROLESSETTING].[BITVALUE],
		[dbo].[ROLESROLESSETTING].[STRINGVALUE],
		[dbo].[ROLESROLESSETTING].[INTVALUE]
	FROM [dbo].[ROLESROLESSETTING]
	INNER JOIN [dbo].[ROLESSETTING] ON [dbo].[ROLESSETTING].[ROLESSETTINGID] = [dbo].[ROLESROLESSETTING].[ROLESSETTINGID]
	WHERE
		[dbo].[ROLESROLESSETTING].[ROLEID] = @USERROLEID
END