CREATE PROCEDURE [systemsetup].[USP_SERVICE_GETALL]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT		[dbo].[SERVICE].[SERVICEID],
				[dbo].[SERVICE].[MACHINENAME],
				[dbo].[SERVICE].[BASEDIRECTORY],
				[dbo].[SERVICE].[ISACTIVE],
				[dbo].[SERVICE].[ISV2],
				[dbo].[SERVICE].[ISCOORDINATOR],
				[dbo].[SERVICE].[SERVICEBASEURL],
				[dbo].[SERVICE].[LASTCHANGEDBY],
				[dbo].[SERVICE].[LASTCHANGEDON],
				[dbo].[SERVICE].[ROWVERSION]
	FROM  [dbo].[SERVICE]
	WHERE [dbo].[SERVICE].[ISV2] = 1
	ORDER BY	[dbo].[SERVICE].[MACHINENAME]

	EXEC [systemsetup].[USP_WINDOWSSERVICETASKCONFIG_GETALL]
END