CREATE PROCEDURE [systemsetup].[USP_CUSTOMFIELDMODULES_SELECT_LOOKUP]
AS
BEGIN
	SET NOCOUNT ON;
	SELECT 
	[dbo].[CUSTOMFIELDMODULES].[CUSTOMFIELDMODULEID],
	[dbo].[CUSTOMFIELDMODULES].[MODULENAME]
	FROM [dbo].[CUSTOMFIELDMODULES]
	ORDER BY [dbo].[CUSTOMFIELDMODULES].[MODULENAME]
END