CREATE PROCEDURE [systemsetup].[USP_FORMS_SELECT_LOOKUP]
AS
SET NOCOUNT ON;
SELECT 
	[dbo].[FORMS].[SFORMSGUID],
	[dbo].[FORMS].[SCOMMONNAME],
	[dbo].[FORMS].[FKSUBMENUGUID]
FROM [dbo].[FORMS]
ORDER BY [dbo].[FORMS].[IORDER] ASC