CREATE PROCEDURE [systemsetup].[USP_RPTREPORT_LOOKUP_FOR_SPECIFIC_RPTFORMTOBUSINESSOBJECTMAPPING_FORMNAME]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT		[RPTREPORT].[RPTREPORTID],
				[RPTREPORT].[FRIENDLYNAME],
				[RPTFORMTOBUSINESSOBJECTMAPPING].[FORMNAME]
	FROM		[RPTREPORT]
	JOIN		[RPTFORMTOBUSINESSOBJECTMAPPING] ON [RPTFORMTOBUSINESSOBJECTMAPPING].[RPTFRMTOBUSOBJMAPID] = [RPTREPORT].[RPTFRMTOBUSOBJMAPID]
	WHERE		[RPTFORMTOBUSINESSOBJECTMAPPING].[GENRICREPORT] = 0
				AND [RPTFORMTOBUSINESSOBJECTMAPPING].[FORMNAME] IN 
					('Application Documents'
					,'Business License Documents'
					,'Transaction Documents'
					,'Invoice Documents'
					,'Code Documents'
					,'Inspection Documents'
					,'Permit Documents'
					,'Plan Documents'
					,'Professional License Documents'
					,'Request Documents'
					,'Tax Remittance Documents'
					)
	ORDER BY	[RPTREPORT].[FRIENDLYNAME], [RPTFORMTOBUSINESSOBJECTMAPPING].[FORMNAME]
END