CREATE PROCEDURE [systemsetup].[USP_RPTPARAMVALUESOURCE_LOOKUP_BY_MODULE]
	@MODULE NVARCHAR(255)
AS
BEGIN
SET NOCOUNT ON;
SELECT  
	[dbo].[RPTPARAMVALUESOURCE].[RPTPARAMVALSRCID],
	[dbo].[RPTPARAMVALUESOURCE].[FRIENDLYNAME],
	[dbo].[RPTPARAMVALUESOURCE].[TABLENAME]
FROM [dbo].[RPTPARAMVALUESOURCE] 
WHERE [dbo].[RPTPARAMVALUESOURCE].[MODULE] LIKE ('%' + @MODULE + '%') OR
	  [dbo].[RPTPARAMVALUESOURCE].[MODULE]  = ('Global')
ORDER BY [dbo].[RPTPARAMVALUESOURCE].[TABLENAME]
END