CREATE PROCEDURE [systemsetup].[USP_PENDING_CAP_CONTACT_GETALL_BY_CRITERIA]
(  
  @SEARCH AS NVARCHAR(MAX) = '',
  @PAGE_NUMBER AS INT = 1,
  @PAGE_SIZE AS INT = 10,
  @IS_ASCENDING AS BIT = 1,  
  @PENDINGCAPCONTACTSORTBY VARCHAR(50) = ''
)
AS
BEGIN
SET NOCOUNT ON;
WITH RAW_DATA AS (
SELECT 
	[dbo].[GLOBALENTITY].[GLOBALENTITYID],	
	[dbo].[GLOBALENTITY].[GLOBALENTITYNAME],
	[dbo].[GLOBALENTITY].[ISCOMPANY],
	[dbo].[GLOBALENTITY].[ISCONTACT],	
	[dbo].[GLOBALENTITY].[EMAIL],
	[dbo].[GLOBALENTITY].[WEBSITE],
	[dbo].[GLOBALENTITY].[BUSINESSPHONE],
	[dbo].[GLOBALENTITY].[HOMEPHONE],
	[dbo].[GLOBALENTITY].[MOBILEPHONE],
	[dbo].[GLOBALENTITY].[OTHERPHONE],
	[dbo].[GLOBALENTITY].[FAX],	
	[dbo].[GLOBALENTITY].[FIRSTNAME],
	[dbo].[GLOBALENTITY].[LASTNAME],
	[dbo].[GLOBALENTITY].[MIDDLENAME],
	[dbo].[GLOBALENTITY].[TITLE],
	[dbo].[GLOBALENTITY].[LASTCHANGEDON],
	[dbo].[GLOBALENTITY].[LASTCHANGEDBY],
	[dbo].[GLOBALENTITY].[ROWVERSION],	
	[dbo].[GLOBALENTITY].[CONTACTID],
	[dbo].[GLOBALENTITY].[PREFCOMM],
	[dbo].[GLOBALENTITY].[ISACTIVE],
	[dbo].[USERS].[LNAME] + COALESCE(', ' + ISNULL([dbo].[USERS].[FNAME],[dbo].[USERS].[FNAME]), '') AS [REGISTEREDBY],
	[dbo].[GLOBALENTITY].[LASTNAME] + COALESCE(', ' + [dbo].[GLOBALENTITY].[FIRSTNAME], '') AS [FULLNAME],
	[dbo].[MAILINGADDRESS].[MAILINGADDRESSID],
	[dbo].[MAILINGADDRESS].[ADDRESSLINE1],
	[dbo].[MAILINGADDRESS].[ADDRESSLINE2],
	[dbo].[MAILINGADDRESS].[ADDRESSLINE3],
	[dbo].[MAILINGADDRESS].[CITY],
	[dbo].[MAILINGADDRESS].[STATE],
	[dbo].[MAILINGADDRESS].[POSTALCODE],
	[dbo].[MAILINGADDRESS].[COUNTRYTYPE],	
	[dbo].[MAILINGADDRESS].[POSTDIRECTION],
	[dbo].[MAILINGADDRESS].[PREDIRECTION],
	[dbo].[MAILINGADDRESS].[ADDRESSID],
	[dbo].[MAILINGADDRESS].[ADDRESSTYPE],
	[dbo].[MAILINGADDRESS].[STREETTYPE],
	[dbo].[MAILINGADDRESS].[UNITORSUITE],
	[dbo].[MAILINGADDRESS].[PROVINCE],
	[dbo].[MAILINGADDRESS].[RURALROUTE],
	[dbo].[MAILINGADDRESS].[STATION],
	[dbo].[MAILINGADDRESS].[COMPSITE],
	[dbo].[MAILINGADDRESS].[POBOX],
	[dbo].[MAILINGADDRESS].[ATTN],
	[dbo].[MAILINGADDRESS].[GENERALDELIVERY],
	[dbo].[USERS].[GLOBALENTITYID] AS REGISTEREDBYID,
	CASE WHEN @IS_ASCENDING = 1 THEN
            (CASE WHEN @PENDINGCAPCONTACTSORTBY = 'FIRSTNAME' THEN  ROW_NUMBER() OVER(ORDER BY [dbo].[GLOBALENTITY].[FIRSTNAME])
                  WHEN  @PENDINGCAPCONTACTSORTBY = 'LASTNAME' THEN ROW_NUMBER() OVER(ORDER BY [dbo].[GLOBALENTITY].[LASTNAME])
				  WHEN  @PENDINGCAPCONTACTSORTBY = 'EMAIL' THEN ROW_NUMBER() OVER(ORDER BY [dbo].[GLOBALENTITY].[EMAIL])
				  WHEN  @PENDINGCAPCONTACTSORTBY = 'GLOBALENTITYNAME' THEN ROW_NUMBER() OVER(ORDER BY [dbo].[GLOBALENTITY].[GLOBALENTITYNAME])
				  WHEN  @PENDINGCAPCONTACTSORTBY = 'CONTACTID' THEN ROW_NUMBER() OVER(ORDER BY [dbo].[GLOBALENTITY].[CONTACTID])
				  WHEN  @PENDINGCAPCONTACTSORTBY = 'TITLE' THEN ROW_NUMBER() OVER(ORDER BY [dbo].[GLOBALENTITY].[TITLE])
				  WHEN  @PENDINGCAPCONTACTSORTBY = 'MAINADDRESS' THEN ROW_NUMBER() OVER(ORDER BY [dbo].[MAILINGADDRESS].[ADDRESSLINE1],[dbo].[MAILINGADDRESS].[PREDIRECTION],
				  [dbo].[MAILINGADDRESS].[ADDRESSLINE2],[dbo].[MAILINGADDRESS].[STREETTYPE], [dbo].[MAILINGADDRESS].[POSTDIRECTION], [dbo].[MAILINGADDRESS].[COMPSITE],
				  [dbo].[MAILINGADDRESS].[POBOX], [dbo].[MAILINGADDRESS].[RURALROUTE], [dbo].[MAILINGADDRESS].[STATION], [dbo].[MAILINGADDRESS].[ADDRESSLINE3], [dbo].[MAILINGADDRESS].[UNITORSUITE],
				  [dbo].[MAILINGADDRESS].[CITY], [dbo].[MAILINGADDRESS].[STATE], [dbo].[MAILINGADDRESS].[POSTALCODE])
                  ELSE  ROW_NUMBER() OVER(ORDER BY [dbo].[GLOBALENTITY].[LASTNAME]) END)
         ELSE
            (CASE WHEN @PENDINGCAPCONTACTSORTBY = 'FIRSTNAME' THEN  ROW_NUMBER() OVER(ORDER BY [dbo].[GLOBALENTITY].[FIRSTNAME] DESC)
                  WHEN  @PENDINGCAPCONTACTSORTBY = 'LASTNAME' THEN ROW_NUMBER() OVER(ORDER BY [dbo].[GLOBALENTITY].[LASTNAME] DESC)
				  WHEN  @PENDINGCAPCONTACTSORTBY = 'EMAIL' THEN ROW_NUMBER() OVER(ORDER BY [dbo].[GLOBALENTITY].[EMAIL] DESC)
				  WHEN  @PENDINGCAPCONTACTSORTBY = 'GLOBALENTITYNAME' THEN ROW_NUMBER() OVER(ORDER BY [dbo].[GLOBALENTITY].[GLOBALENTITYNAME] DESC)
				  WHEN  @PENDINGCAPCONTACTSORTBY = 'CONTACTID' THEN ROW_NUMBER() OVER(ORDER BY [dbo].[GLOBALENTITY].[CONTACTID] DESC)
				  WHEN  @PENDINGCAPCONTACTSORTBY = 'TITLE' THEN ROW_NUMBER() OVER(ORDER BY [dbo].[GLOBALENTITY].[TITLE] DESC)
				  WHEN  @PENDINGCAPCONTACTSORTBY = 'MAINADDRESS' THEN ROW_NUMBER() OVER(ORDER BY [dbo].[MAILINGADDRESS].[ADDRESSLINE1],[dbo].[MAILINGADDRESS].[PREDIRECTION],
				  [dbo].[MAILINGADDRESS].[ADDRESSLINE2],[dbo].[MAILINGADDRESS].[STREETTYPE], [dbo].[MAILINGADDRESS].[POSTDIRECTION], [dbo].[MAILINGADDRESS].[COMPSITE],
				  [dbo].[MAILINGADDRESS].[POBOX], [dbo].[MAILINGADDRESS].[RURALROUTE], [dbo].[MAILINGADDRESS].[STATION], [dbo].[MAILINGADDRESS].[ADDRESSLINE3], [dbo].[MAILINGADDRESS].[UNITORSUITE],
				  [dbo].[MAILINGADDRESS].[CITY], [dbo].[MAILINGADDRESS].[STATE], [dbo].[MAILINGADDRESS].[POSTALCODE] DESC)
                  ELSE  ROW_NUMBER() OVER(ORDER BY [dbo].[GLOBALENTITY].[LASTNAME] DESC) END)  
       END AS RowNumber,
	   COUNT(1) OVER() AS TotalRows
FROM [dbo].[GLOBALENTITY]
	LEFT JOIN [USERS] ON [USERS].[SUSERGUID] = [GLOBALENTITY].[LASTCHANGEDBY]
	LEFT JOIN [GLOBALENTITYMAILINGADDRESS] ON [GLOBALENTITYMAILINGADDRESS].[GLOBALENTITYID] = [GLOBALENTITY].[GLOBALENTITYID] AND [GLOBALENTITYMAILINGADDRESS].[MAIN] = 1
	LEFT JOIN [MAILINGADDRESS] ON [MAILINGADDRESS].[MAILINGADDRESSID] = [GLOBALENTITYMAILINGADDRESS].[MAILINGADDRESSID]	
WHERE
	[ISACTIVE] = 0	
	AND ([dbo].[USERS].[COMPANY] like '%' + @SEARCH + '%'
	OR [dbo].[GLOBALENTITY].[FIRSTNAME] like '%' + @SEARCH + '%'
	OR [dbo].[GLOBALENTITY].[LASTNAME]  like '%' + @SEARCH + '%'
	OR [dbo].[GLOBALENTITY].[EMAIL] like '%' + @SEARCH + '%'
	OR [dbo].[GLOBALENTITY].[GLOBALENTITYNAME] like '%' + @SEARCH + '%'
	OR [dbo].[MAILINGADDRESS].[ADDRESSLINE1] like '%' + @SEARCH + '%'
	OR [dbo].[MAILINGADDRESS].[ADDRESSLINE2] like '%' + @SEARCH + '%'
	OR [dbo].[MAILINGADDRESS].[ADDRESSLINE3] like '%' + @SEARCH + '%'
	OR [dbo].[MAILINGADDRESS].[CITY] like '%' + @SEARCH + '%'
	OR [dbo].[MAILINGADDRESS].[POSTALCODE] like '%' + @SEARCH + '%'
	OR [dbo].[MAILINGADDRESS].[UNITORSUITE] like '%' + @SEARCH + '%')
	)
	SELECT * 
FROM RAW_DATA
WHERE
	RowNumber > @PAGE_SIZE * (@PAGE_NUMBER - 1) AND 
	RowNumber <= @PAGE_SIZE * @PAGE_NUMBER
ORDER BY
	RowNumber
END