CREATE PROCEDURE [systemsetup].[USP_CAFINANCIALINTEGRATIONTYPE_SELECT_LOOKUP]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT		[dbo].[CAFINANCIALINTEGRATIONTYPE].[CAFINANCIALINTEGRATIONTYPEID],
				[dbo].[CAFINANCIALINTEGRATIONTYPE].[NAME]
	FROM		[dbo].[CAFINANCIALINTEGRATIONTYPE]
	ORDER BY	[dbo].[CAFINANCIALINTEGRATIONTYPE].[NAME]
END