CREATE PROCEDURE [reviewcoordinator].[USP_ENTITY_CASE_GISFEATURE_GETBYENTITYIDS]
	@ENTITYIDS RECORDIDS READONLY
AS
BEGIN

SET NOCOUNT ON;
SELECT DISTINCT
	PMPERMITGISFEATURE.PMPERMITID ENTITYID,
	PMPERMITGISFEATURE.KEYVALUE
FROM PMPERMITGISFEATURE
INNER JOIN @ENTITYIDS on [@ENTITYIDS].RECORDID = PMPERMITGISFEATURE.PMPERMITID
UNION ALL
SELECT DISTINCT
	PLPLANGISFEATURE.PLPLANID ENTITYID,
	PLPLANGISFEATURE.KEYVALUE
FROM PLPLANGISFEATURE
INNER JOIN @ENTITYIDS on [@ENTITYIDS].RECORDID = PLPLANGISFEATURE.PLPLANID

END