CREATE PROCEDURE [reviewcoordinator].[USP_ENTITY_CASE_FACETS_GET]
	@ASSIGNEDUSERIDS AS RECORDIDS READONLY,
	@ASSIGNEDTEAMIDS AS RECORDIDS READONLY,
	@OWNEDTEAMIDS AS RECORDIDS READONLY,
	@TODAY AS DATE = NULL,
	@YESTERDAY AS DATE = NULL,
	@LASTBUSINESSDAY AS DATE = NULL
AS
BEGIN

SET NOCOUNT ON;

EXEC [reviewcoordinator].[USP_ENTITY_CASE_FACETS_GET_TODAY] @ASSIGNEDUSERIDS = @ASSIGNEDUSERIDS, @TODAY = @TODAY
EXEC [reviewcoordinator].[USP_ENTITY_CASE_FACETS_GET_YESTERDAY] @ASSIGNEDUSERIDS = @ASSIGNEDUSERIDS, @YESTERDAY = @YESTERDAY
EXEC [reviewcoordinator].[USP_ENTITY_CASE_FACETS_GET_LAST_BUSINESS_DAYS] @ASSIGNEDUSERIDS = @ASSIGNEDUSERIDS, @LASTBUSINESSDAY = @LASTBUSINESSDAY 

EXEC [reviewcoordinator].[USP_ENTITY_CASE_FACETS_GET_STATUS] @ASSIGNEDUSERIDS = @ASSIGNEDUSERIDS
EXEC [reviewcoordinator].[USP_ENTITY_CASE_FACETS_GET_ENTITY_TYPE] @ASSIGNEDUSERIDS = @ASSIGNEDUSERIDS
EXEC [reviewcoordinator].[USP_ENTITY_CASE_FACETS_GET_ENTITY_NUMBER] @ASSIGNEDUSERIDS = @ASSIGNEDUSERIDS
EXEC [reviewcoordinator].[USP_ENTITY_CASE_FACETS_GET_PROJECT] @ASSIGNEDUSERIDS = @ASSIGNEDUSERIDS

EXEC [reviewcoordinator].[USP_ENTITY_CASE_FACETS_GET_ASSIGNED_TO] @ASSIGNEDUSERIDS = @ASSIGNEDUSERIDS
EXEC [reviewcoordinator].[USP_ENTITY_CASE_FACETS_GET_ASSIGNED_TO_TEAM] @ASSIGNEDUSERIDS = @ASSIGNEDUSERIDS, @OWNEDTEAMIDS = @OWNEDTEAMIDS

END