CREATE PROCEDURE [reviewcoordinator].[USP_ENTITY_CASE_FACETS_GET_YESTERDAY]
	@ASSIGNEDUSERIDS AS RECORDIDS READONLY,
	@YESTERDAY AS DATE = NULL
AS
BEGIN

WITH YESTERDAY AS 
(
	SELECT 
		PMPERMIT.APPLYDATE APPLIEDDATE, 
		PMPERMIT.FINALIZEDATE COMPLETEDATE, 
		PMPERMIT.ASSIGNEDTO ASSIGNEDTO 
	FROM PMPERMIT
	UNION ALL
	SELECT 
		APPLICATIONDATE APPLIEDDATE, 
		PLPLAN.COMPLETEDATE COMPLETEDATE, 
		PLPLAN.ASSIGNEDTO ASSIGNEDTO 
	FROM PLPLAN
) 
SELECT ID = 'Yesterday', NAME = 'Yesterday', COUNT(*) COUNT
FROM YESTERDAY
WHERE 
	ASSIGNEDTO IN (SELECT RECORDID FROM @ASSIGNEDUSERIDS) AND 
	COMPLETEDATE IS NULL
	AND APPLIEDDATE >= @YESTERDAY AND APPLIEDDATE < DATEADD(D, 1, @YESTERDAY)

END