CREATE PROCEDURE [reviewcoordinator].[USP_INBOX_CARD_FACETS_GET_TODAY]
	@ASSIGNEDUSERIDS AS RECORDIDS READONLY,
	@ASSIGNEDTEAMIDS AS RECORDIDS READONLY,
	@TODAY AS DATE = NULL
AS
BEGIN

SELECT ID = 'Today', NAME = 'Today', COUNT(*) COUNT
	FROM SYSTEMTASK
	LEFT OUTER JOIN PLSUBMITTAL ON PLSUBMITTAL.PLSUBMITTALID = SYSTEMTASK.UNIQUERECORDID
	WHERE
		(SYSTEMTASK.ASSIGNEDTO IN (SELECT RECORDID FROM @ASSIGNEDUSERIDS) OR 
		(SYSTEMTASK.ASSIGNEDTO IS NULL AND TEAMASSIGNEDTO IN (SELECT RECORDID FROM @ASSIGNEDTEAMIDS))
		) AND COMPLETEDDATE IS NULL
	AND SYSTEMTASK.DUEDATE >= @TODAY AND SYSTEMTASK.DUEDATE < DATEADD(D, 1, @TODAY)
	AND [reviewcoordinator].[UFN_IS_SNOOZED](SNOOZETYPEID, 
		[reviewcoordinator].[UFN_HAS_INVOICE_BALANCE_DUE](COALESCE(PLSUBMITTAL.PMPERMITID, PLSUBMITTAL.PLPLANID, SYSTEMTASK.UNIQUERECORDID)), 
		SNOOZEUNTILDATE, @TODAY) = 0

END