CREATE PROCEDURE [reviewcoordinator].[USP_INBOX_CARD_GETBYID]
	@SYSTEMTASKID AS CHAR(36),
	@ALLOWHOLDOVERRIDE BIT
AS
BEGIN

DECLARE @PermitModule int = 2
DECLARE @PlanModule int = 1

DECLARE @fileStatusRequiredForResubmittal int = 4
DECLARE @workFlowStatusStarted int = 5

SET NOCOUNT ON;
WITH RAW_DATA AS (
-- permit: new files
SELECT 
		PMPERMIT.PMPERMITID ENTITYID,
		PMPERMIT.PERMITNUMBER ENTITYNUMBER,				
		PMPERMIT.DESCRIPTION ENTITYDESCRIPTION,		
		PMPERMIT.ROWVERSION ROWVERSION,
		PMPERMIT.PMPERMITTYPEID ENTITYTYPEID,
		PMPERMITTYPE.NAME ENTITYTYPE,
		PMPERMIT.PMPERMITWORKCLASSID ENTITYCLASSID,
		PMPERMITWORKCLASS.NAME ENTITYWORKCLASS,
		PMPERMITSTATUS.NAME ENTITYSTATUS,
		PLSUBMITTAL.PLSUBMITTALID SUBMITTALID,
		BALANCEDUE = [reviewcoordinator].[UFN_GET_BALANCE_DUE](PMPERMIT.PMPERMITID),
		@PermitModule MODULE,
		SYSTEMTASK.SYSTEMTASKID,
		SYSTEMTASK.DUEDATE,
		SYSTEMTASK.SYSTEMTASKTYPEID TASKTYPEID,
		COALESCE(NULLIF(SYSTEMTASKTYPE.CUSTOMNAME,''), SYSTEMTASKTYPE.NAME) TASKTYPENAME,
		SYSTEMTASK.COMPLETEDDATE,
		SYSTEMTASK.ASSIGNEDTO USERASSIGNEDTO,
		USERS.FNAME USERFIRSTNAME,
		USERS.LNAME USERLASTNAME,		
		ERENTITYPROJECT.ERENTITYPROJECTID,		
		PRPROJECT.NAME PROJECTNAME,
		PMPERMITSTATUS.ISSUEDFLAG,
		PMPERMITSTATUS.COMPLETEDFLAG,
		PMPERMITTYPEWORKCLASS.FILESETID,
		NEWFILECOUNT = (SELECT COUNT(*) FROM ERPROJECTFILEVERSION
			INNER JOIN ERPROJECTFILE ON ERPROJECTFILE.ERPROJECTFILEID = ERPROJECTFILEVERSION.ERPROJECTFILEID
			INNER JOIN ERPROJECT ON ERPROJECT.ERPROJECTID = ERPROJECTFILE.ERPROJECTID
			WHERE ERPROJECT.PMPERMITID = PMPERMIT.PMPERMITID AND ERPROJECTFILEVERSION.SYSTEMTASKID = SYSTEMTASK.SYSTEMTASKID AND 
			ERPROJECTFILEVERSION.MARKDELETE = 0),
		RESUBMITTALREQUIREMENTSCOUNT = 
			(select count(*) from PLSUBMITTAL
			inner join PLSUBMITTALFILEVERSION on PLSUBMITTALFILEVERSION.PLSUBMITTALID = PLSUBMITTAL.PLSUBMITTALID
			inner join ERPROJECTFILEVERSION on ERPROJECTFILEVERSION.ERPROJECTFILEVERSIONID = PLSUBMITTALFILEVERSION.ERPROJECTFILEVERSIONID
			where PLSUBMITTAL.PMPERMITID = PMPERMIT.PMPERMITID AND PLSUBMITTAL.COMPLETED = 0 AND ERPROJECTFILEVERSION.FILESTATUSID = @fileStatusRequiredForResubmittal),		
		HASSTOPHOLDS = [reviewcoordinator].[UFN_HAS_ACTIVE_STOP_HOLDS](PMPERMIT.PMPERMITID, @ALLOWHOLDOVERRIDE),
		PARCEL.PARCELNUMBER,
		SYSTEMTASKTYPESUBMITTALTYPE.AUTOCLOSESESSION,
		PMPERMITADDRESS.MAILINGADDRESSID,
		SYSTEMTASK.SNOOZETYPEID,
		SYSTEMTASK.SNOOZEUNTILDATE,
		ZONE.NAME ZONENAME,
		ZONE.ZONECODE,
		ZONE.DESCRIPTION ZONEDESCRIPTION,
		HASINVOICEBALANCEDUE = [reviewcoordinator].[UFN_HAS_INVOICE_BALANCE_DUE](PMPERMIT.PMPERMITID)
	FROM SYSTEMTASK
	INNER JOIN SYSTEMTASKTYPE ON SYSTEMTASKTYPE.SYSTEMTASKTYPEID = SYSTEMTASK.SYSTEMTASKTYPEID
	LEFT OUTER JOIN USERS ON USERS.SUSERGUID = SYSTEMTASK.ASSIGNEDTO
	INNER JOIN PMPERMIT ON PMPERMIT.PMPERMITID = SYSTEMTASK.UNIQUERECORDID
	INNER JOIN PMPERMITSTATUS ON PMPERMITSTATUS.PMPERMITSTATUSID = PMPERMIT.PMPERMITSTATUSID
	INNER JOIN PMPERMITTYPE ON PMPERMITTYPE.PMPERMITTYPEID = PMPERMIT.PMPERMITTYPEID
	INNER JOIN PMPERMITWORKCLASS ON PMPERMITWORKCLASS.PMPERMITWORKCLASSID = PMPERMIT.PMPERMITWORKCLASSID
	INNER JOIN PMPERMITTYPEWORKCLASS ON PMPERMITTYPEWORKCLASS.PMPERMITTYPEID = PMPERMITTYPE.PMPERMITTYPEID AND PMPERMITTYPEWORKCLASS.PMPERMITWORKCLASSID = PMPERMITWORKCLASS.PMPERMITWORKCLASSID
	LEFT OUTER JOIN PRPROJECTPERMIT ON PRPROJECTPERMIT.PMPERMITID = PMPERMIT.PMPERMITID
	LEFT OUTER JOIN PRPROJECT ON PRPROJECT.PRPROJECTID = PRPROJECTPERMIT.PRPROJECTID		
	LEFT OUTER JOIN PMPERMITADDRESS ON PMPERMITADDRESS.PMPERMITID = PMPERMIT.PMPERMITID AND PMPERMITADDRESS.MAIN = 1
	LEFT OUTER JOIN PMPERMITPARCEL ON PMPERMITPARCEL.PMPERMITID = PMPERMIT.PMPERMITID AND PMPERMITPARCEL.MAIN = 1
	LEFT OUTER JOIN PARCEL ON PARCEL.PARCELID = PMPERMITPARCEL.PARCELID	
	LEFT OUTER JOIN (
		SELECT TOP 1  1 AS RANKING, PLSUBMITTAL.PLSUBMITTALID, PLSUBMITTAL.PLSUBMITTALTYPEID, PLSUBMITTAL.PMPERMITID FROM PLSUBMITTAL
			INNER JOIN SYSTEMTASKSUBMITTAL ON SYSTEMTASKSUBMITTAL.PLSUBMITTALID = PLSUBMITTAL.PLSUBMITTALID
			INNER JOIN SYSTEMTASK ON SYSTEMTASK.SYSTEMTASKID = SYSTEMTASKSUBMITTAL.SYSTEMTASKID
		WHERE SYSTEMTASK.SYSTEMTASKID = @SYSTEMTASKID
		UNION
		SELECT TOP 1 2 AS RANKING, PLSUBMITTAL.PLSUBMITTALID, PLSUBMITTAL.PLSUBMITTALTYPEID, PLSUBMITTAL.PMPERMITID FROM PLSUBMITTAL
			INNER JOIN SYSTEMTASK ON SYSTEMTASK.UNIQUERECORDID = PLSUBMITTAL.PMPERMITID
			LEFT OUTER JOIN PMPERMITWFACTIONSTEP ON PMPERMITWFACTIONSTEP.PMPERMITWFACTIONSTEPID = PLSUBMITTAL.PMPERMITWFACTIONSTEPID
			LEFT OUTER JOIN (SELECT PLSUBMITTALID, COUNT(*) SESSIONSTATUSCOUNT FROM ERENTITYSESSION GROUP BY PLSUBMITTALID, SESSIONSTATUSID) 
			ENTITYSESSION ON ENTITYSESSION.PLSUBMITTALID = PLSUBMITTAL.PLSUBMITTALID
			WHERE PLSUBMITTAL.COMPLETED = 0 AND ISNULL(PMPERMITWFACTIONSTEP.WORKFLOWSTATUSID,0) = @workFlowStatusStarted 			
			AND SYSTEMTASK.SYSTEMTASKID = @SYSTEMTASKID
			ORDER BY RANKING, ENTITYSESSION.SESSIONSTATUSCOUNT DESC, PMPERMITWFACTIONSTEP.PRIORITYORDER, PLSUBMITTAL.DUEDATE, PMPERMITWFACTIONSTEP.IDENTITYCOLUMN
	) PLSUBMITTAL ON PLSUBMITTAL.PMPERMITID = PMPERMIT.PMPERMITID
	LEFT OUTER JOIN SYSTEMTASKTYPESUBMITTALTYPE ON SYSTEMTASKTYPESUBMITTALTYPE.SYSTEMTASKTYPEID = SYSTEMTASK.SYSTEMTASKTYPEID AND 
		SYSTEMTASKTYPESUBMITTALTYPE.PLSUBMITTALTYPEID = PLSUBMITTAL.PLSUBMITTALTYPEID
	LEFT OUTER JOIN ERENTITYPROJECT ON ERENTITYPROJECT.PMPERMITID = PMPERMIT.PMPERMITID
	LEFT OUTER JOIN PMPERMITZONE ON PMPERMITZONE.PMPERMITID = PMPERMIT.PMPERMITID AND PMPERMITZONE.MAIN = 1
	LEFT OUTER JOIN ZONE ON ZONE.ZONEID = PMPERMITZONE.ZONEID
UNION ALL
-- plan: new files
SELECT 
		PLPLAN.PLPLANID ENTITYID,
		PLPLAN.PLANNUMBER ENTITYNUMBER,				
		PLPLAN.DESCRIPTION ENTITYDESCRIPTION,		
		PLPLAN.ROWVERSION ROWVERSION,
		PLPLAN.PLPLANTYPEID ENTITYTYPEID,
		PLPLANTYPE.PLANNAME ENTITYTYPE,
		PLPLAN.PLPLANWORKCLASSID ENTITYCLASSID,
		PLPLANWORKCLASS.NAME ENTITYWORKCLASS,
		PLPLANSTATUS.NAME ENTITYSTATUS,
		PLSUBMITTAL.PLSUBMITTALID SUBMITTALID,
		BALANCEDUE = [reviewcoordinator].[UFN_GET_BALANCE_DUE](PLPLAN.PLPLANID),
		@PlanModule MODULE,
		SYSTEMTASK.SYSTEMTASKID,
		SYSTEMTASK.DUEDATE,
		SYSTEMTASK.SYSTEMTASKTYPEID TASKTYPEID,
		COALESCE(NULLIF(SYSTEMTASKTYPE.CUSTOMNAME,''), SYSTEMTASKTYPE.NAME) TASKTYPENAME,
		SYSTEMTASK.COMPLETEDDATE,
		SYSTEMTASK.ASSIGNEDTO USERASSIGNEDTO,
		USERS.FNAME USERFIRSTNAME,
		USERS.LNAME USERLASTNAME,
		ERENTITYPROJECT.ERENTITYPROJECTID,
		PRPROJECT.NAME PROJECTNAME,
		PLPLANSTATUS.SUCCESSFLAG ISSUEDFLAG,
		PLPLANSTATUS.SUCCESSFLAG COMPLETEDFLAG,
		PLPLANTYPEWORKCLASS.FILESETID,
		NEWFILECOUNT = (SELECT COUNT(*) FROM ERPROJECTFILEVERSION
			INNER JOIN ERPROJECTFILE ON ERPROJECTFILE.ERPROJECTFILEID = ERPROJECTFILEVERSION.ERPROJECTFILEID
			INNER JOIN ERPROJECT ON ERPROJECT.ERPROJECTID = ERPROJECTFILE.ERPROJECTID
			WHERE ERPROJECT.PLPLANID = PLPLAN.PLPLANID AND ERPROJECTFILEVERSION.SYSTEMTASKID = SYSTEMTASK.SYSTEMTASKID AND 
			ERPROJECTFILEVERSION.MARKDELETE = 0),
		RESUBMITTALREQUIREMENTSCOUNT = 
			(select count(*) from PLSUBMITTAL
			inner join PLSUBMITTALFILEVERSION on PLSUBMITTALFILEVERSION.PLSUBMITTALID = PLSUBMITTAL.PLSUBMITTALID
			inner join ERPROJECTFILEVERSION on ERPROJECTFILEVERSION.ERPROJECTFILEVERSIONID = PLSUBMITTALFILEVERSION.ERPROJECTFILEVERSIONID
			where PLSUBMITTAL.PLPLANID = PLPLAN.PLPLANID AND PLSUBMITTAL.COMPLETED = 0 AND ERPROJECTFILEVERSION.FILESTATUSID = @fileStatusRequiredForResubmittal),		
		HASSTOPHOLDS = [reviewcoordinator].[UFN_HAS_ACTIVE_STOP_HOLDS](PLPLAN.PLPLANID, @ALLOWHOLDOVERRIDE),
		PARCEL.PARCELNUMBER,
		SYSTEMTASKTYPESUBMITTALTYPE.AUTOCLOSESESSION,
		PLPLANADDRESS.MAILINGADDRESSID,
		SYSTEMTASK.SNOOZETYPEID,
		SYSTEMTASK.SNOOZEUNTILDATE,
		ZONE.NAME ZONENAME,
		ZONE.ZONECODE,
		ZONE.DESCRIPTION ZONEDESCRIPTION,
		HASINVOICEBALANCEDUE = [reviewcoordinator].[UFN_HAS_INVOICE_BALANCE_DUE](PLPLAN.PLPLANID)
	FROM SYSTEMTASK
	INNER JOIN SYSTEMTASKTYPE ON SYSTEMTASKTYPE.SYSTEMTASKTYPEID = SYSTEMTASK.SYSTEMTASKTYPEID
	LEFT OUTER JOIN USERS ON USERS.SUSERGUID = SYSTEMTASK.ASSIGNEDTO
	INNER JOIN PLPLAN ON PLPLAN.PLPLANID = SYSTEMTASK.UNIQUERECORDID
	INNER JOIN PLPLANSTATUS ON PLPLANSTATUS.PLPLANSTATUSID = PLPLAN.PLPLANSTATUSID
	INNER JOIN PLPLANTYPE ON PLPLANTYPE.PLPLANTYPEID = PLPLAN.PLPLANTYPEID
	INNER JOIN PLPLANWORKCLASS ON PLPLANWORKCLASS.PLPLANWORKCLASSID = PLPLAN.PLPLANWORKCLASSID
	INNER JOIN PLPLANTYPEWORKCLASS ON PLPLANTYPEWORKCLASS.PLPLANTYPEID = PLPLANTYPE.PLPLANTYPEID AND PLPLANTYPEWORKCLASS.PLPLANWORKCLASSID = PLPLANWORKCLASS.PLPLANWORKCLASSID
	LEFT OUTER JOIN PRPROJECTPLAN ON PRPROJECTPLAN.PLPLANID = PLPLAN.PLPLANID
	LEFT OUTER JOIN PRPROJECT ON PRPROJECT.PRPROJECTID = PRPROJECTPLAN.PRPROJECTID		
	LEFT OUTER JOIN PLPLANADDRESS ON PLPLANADDRESS.PLPLANID = PLPLAN.PLPLANID AND PLPLANADDRESS.MAIN = 1
	LEFT OUTER JOIN PLPLANPARCEL ON PLPLANPARCEL.PLPLANID = PLPLAN.PLPLANID AND PLPLANPARCEL.MAIN = 1
	LEFT OUTER JOIN PARCEL ON PARCEL.PARCELID = PLPLANPARCEL.PARCELID
	LEFT OUTER JOIN (
		SELECT TOP 1  1 AS RANKING, PLSUBMITTAL.PLSUBMITTALID, PLSUBMITTAL.PLSUBMITTALTYPEID, PLSUBMITTAL.PLPLANID FROM PLSUBMITTAL
			INNER JOIN SYSTEMTASKSUBMITTAL ON SYSTEMTASKSUBMITTAL.PLSUBMITTALID = PLSUBMITTAL.PLSUBMITTALID
			INNER JOIN SYSTEMTASK ON SYSTEMTASK.SYSTEMTASKID = SYSTEMTASKSUBMITTAL.SYSTEMTASKID
		WHERE SYSTEMTASK.SYSTEMTASKID = @SYSTEMTASKID
		UNION
		SELECT TOP 1 2 AS RANKING, PLSUBMITTAL.PLSUBMITTALID, PLSUBMITTAL.PLSUBMITTALTYPEID, PLSUBMITTAL.PLPLANID FROM PLSUBMITTAL
			INNER JOIN SYSTEMTASK ON SYSTEMTASK.UNIQUERECORDID = PLSUBMITTAL.PLPLANID
			LEFT OUTER JOIN PLPLANWFACTIONSTEP ON PLPLANWFACTIONSTEP.PLPLANWFACTIONSTEPID = PLSUBMITTAL.PLPLANWFACTIONSTEPID
			LEFT OUTER JOIN (SELECT PLSUBMITTALID, COUNT(*) SESSIONSTATUSCOUNT FROM ERENTITYSESSION GROUP BY PLSUBMITTALID, SESSIONSTATUSID) 
			ENTITYSESSION ON ENTITYSESSION.PLSUBMITTALID = PLSUBMITTAL.PLSUBMITTALID
			WHERE PLSUBMITTAL.COMPLETED = 0 AND ISNULL(PLPLANWFACTIONSTEP.WORKFLOWSTATUSID,0) = @workFlowStatusStarted 			
			AND SYSTEMTASK.SYSTEMTASKID = @SYSTEMTASKID
			ORDER BY RANKING, ENTITYSESSION.SESSIONSTATUSCOUNT DESC, PLPLANWFACTIONSTEP.PRIORITYORDER, PLSUBMITTAL.DUEDATE, PLPLANWFACTIONSTEP.IDENTITYCOLUMN
	) PLSUBMITTAL ON PLSUBMITTAL.PLPLANID = PLPLAN.PLPLANID
	LEFT OUTER JOIN SYSTEMTASKTYPESUBMITTALTYPE ON SYSTEMTASKTYPESUBMITTALTYPE.SYSTEMTASKTYPEID = SYSTEMTASK.SYSTEMTASKTYPEID AND 
		SYSTEMTASKTYPESUBMITTALTYPE.PLSUBMITTALTYPEID = PLSUBMITTAL.PLSUBMITTALTYPEID
	LEFT OUTER JOIN ERENTITYPROJECT ON ERENTITYPROJECT.PLPLANID = PLPLAN.PLPLANID
	LEFT OUTER JOIN PLPLANZONE ON PLPLANZONE.PLPLANID = PLPLAN.PLPLANID AND PLPLANZONE.MAIN = 1
	LEFT OUTER JOIN ZONE ON ZONE.ZONEID = PLPLANZONE.ZONEID
	UNION ALL
	-- permit: submittal
	SELECT 
		PMPERMIT.PMPERMITID ENTITYID,
		PMPERMIT.PERMITNUMBER ENTITYNUMBER,				
		PMPERMIT.DESCRIPTION ENTITYDESCRIPTION,		
		PMPERMIT.ROWVERSION ROWVERSION,
		PMPERMIT.PMPERMITTYPEID ENTITYTYPEID,
		PMPERMITTYPE.NAME ENTITYTYPE,
		PMPERMIT.PMPERMITWORKCLASSID ENTITYCLASSID,
		PMPERMITWORKCLASS.NAME ENTITYWORKCLASS,
		PMPERMITSTATUS.NAME ENTITYSTATUS,
		PLSUBMITTAL.PLSUBMITTALID SUBMITTALID,
		BALANCEDUE = [reviewcoordinator].[UFN_GET_BALANCE_DUE](PMPERMIT.PMPERMITID),
		@PermitModule MODULE,
		SYSTEMTASK.SYSTEMTASKID,
		SYSTEMTASK.DUEDATE,
		SYSTEMTASK.SYSTEMTASKTYPEID TASKTYPEID,
		COALESCE(NULLIF(SYSTEMTASKTYPE.CUSTOMNAME,''), SYSTEMTASKTYPE.NAME) TASKTYPENAME,
		SYSTEMTASK.COMPLETEDDATE,
		SYSTEMTASK.ASSIGNEDTO USERASSIGNEDTO,
		USERS.FNAME USERFIRSTNAME,
		USERS.LNAME USERLASTNAME,
		ERENTITYPROJECT.ERENTITYPROJECTID,
		PRPROJECT.NAME PROJECTNAME,
		PMPERMITSTATUS.ISSUEDFLAG,
		PMPERMITSTATUS.COMPLETEDFLAG,
		PMPERMITTYPEWORKCLASS.FILESETID,
		NEWFILECOUNT = (SELECT COUNT(*) FROM ERPROJECTFILEVERSION
			INNER JOIN ERPROJECTFILE ON ERPROJECTFILE.ERPROJECTFILEID = ERPROJECTFILEVERSION.ERPROJECTFILEID
			INNER JOIN ERPROJECT ON ERPROJECT.ERPROJECTID = ERPROJECTFILE.ERPROJECTID
			WHERE ERPROJECT.PMPERMITID = PMPERMIT.PMPERMITID AND ERPROJECTFILEVERSION.SYSTEMTASKID = SYSTEMTASK.SYSTEMTASKID AND 
			ERPROJECTFILEVERSION.MARKDELETE = 0),
		RESUBMITTALREQUIREMENTSCOUNT = 
			(select count(*) from PLSUBMITTAL
			inner join PLSUBMITTALFILEVERSION on PLSUBMITTALFILEVERSION.PLSUBMITTALID = PLSUBMITTAL.PLSUBMITTALID
			inner join ERPROJECTFILEVERSION on ERPROJECTFILEVERSION.ERPROJECTFILEVERSIONID = PLSUBMITTALFILEVERSION.ERPROJECTFILEVERSIONID
			where PLSUBMITTAL.PMPERMITID = PMPERMIT.PMPERMITID AND PLSUBMITTAL.COMPLETED = 0 AND ERPROJECTFILEVERSION.FILESTATUSID = @fileStatusRequiredForResubmittal),		
		HASSTOPHOLDS = [reviewcoordinator].[UFN_HAS_ACTIVE_STOP_HOLDS](PMPERMIT.PMPERMITID, @ALLOWHOLDOVERRIDE),
		PARCEL.PARCELNUMBER,
		SYSTEMTASKTYPESUBMITTALTYPE.AUTOCLOSESESSION,
		PMPERMITADDRESS.MAILINGADDRESSID,
		SYSTEMTASK.SNOOZETYPEID,
		SYSTEMTASK.SNOOZEUNTILDATE,
		ZONE.NAME ZONENAME,
		ZONE.ZONECODE,
		ZONE.DESCRIPTION ZONEDESCRIPTION,
		HASINVOICEBALANCEDUE = [reviewcoordinator].[UFN_HAS_INVOICE_BALANCE_DUE](PMPERMIT.PMPERMITID)
	FROM SYSTEMTASK
	INNER JOIN SYSTEMTASKTYPE ON SYSTEMTASKTYPE.SYSTEMTASKTYPEID = SYSTEMTASK.SYSTEMTASKTYPEID
	LEFT OUTER JOIN USERS ON USERS.SUSERGUID = SYSTEMTASK.ASSIGNEDTO
	INNER JOIN PLSUBMITTAL ON PLSUBMITTAL.PLSUBMITTALID = SYSTEMTASK.UNIQUERECORDID
	INNER JOIN PMPERMIT ON PMPERMIT.PMPERMITID = PLSUBMITTAL.PMPERMITID
	INNER JOIN PMPERMITSTATUS ON PMPERMITSTATUS.PMPERMITSTATUSID = PMPERMIT.PMPERMITSTATUSID
	INNER JOIN PMPERMITTYPE ON PMPERMITTYPE.PMPERMITTYPEID = PMPERMIT.PMPERMITTYPEID
	INNER JOIN PMPERMITWORKCLASS ON PMPERMITWORKCLASS.PMPERMITWORKCLASSID = PMPERMIT.PMPERMITWORKCLASSID
	INNER JOIN PMPERMITTYPEWORKCLASS ON PMPERMITTYPEWORKCLASS.PMPERMITTYPEID = PMPERMITTYPE.PMPERMITTYPEID AND PMPERMITTYPEWORKCLASS.PMPERMITWORKCLASSID = PMPERMITWORKCLASS.PMPERMITWORKCLASSID
	LEFT OUTER JOIN PRPROJECTPERMIT ON PRPROJECTPERMIT.PMPERMITID = PMPERMIT.PMPERMITID
	LEFT OUTER JOIN PRPROJECT ON PRPROJECT.PRPROJECTID = PRPROJECTPERMIT.PRPROJECTID		
	LEFT OUTER JOIN PMPERMITADDRESS ON PMPERMITADDRESS.PMPERMITID = PMPERMIT.PMPERMITID AND PMPERMITADDRESS.MAIN = 1
	LEFT OUTER JOIN PMPERMITPARCEL ON PMPERMITPARCEL.PMPERMITID = PMPERMIT.PMPERMITID AND PMPERMITPARCEL.MAIN = 1
	LEFT OUTER JOIN PARCEL ON PARCEL.PARCELID = PMPERMITPARCEL.PARCELID
	LEFT OUTER JOIN SYSTEMTASKTYPESUBMITTALTYPE ON SYSTEMTASKTYPESUBMITTALTYPE.SYSTEMTASKTYPEID = SYSTEMTASK.SYSTEMTASKTYPEID AND 
		SYSTEMTASKTYPESUBMITTALTYPE.PLSUBMITTALTYPEID = PLSUBMITTAL.PLSUBMITTALTYPEID
	LEFT OUTER JOIN ERENTITYPROJECT ON ERENTITYPROJECT.PMPERMITID = PMPERMIT.PMPERMITID
	LEFT OUTER JOIN PMPERMITZONE ON PMPERMITZONE.PMPERMITID = PMPERMIT.PMPERMITID AND PMPERMITZONE.MAIN = 1
	LEFT OUTER JOIN ZONE ON ZONE.ZONEID = PMPERMITZONE.ZONEID
	UNION ALL
	-- plan: submittal
	SELECT 
	PLPLAN.PLPLANID ENTITYID,
		PLPLAN.PLANNUMBER ENTITYNUMBER,				
		PLPLAN.DESCRIPTION ENTITYDESCRIPTION,		
		PLPLAN.ROWVERSION ROWVERSION,
		PLPLAN.PLPLANTYPEID ENTITYTYPEID,
		PLPLANTYPE.PLANNAME ENTITYTYPE,
		PLPLAN.PLPLANWORKCLASSID ENTITYCLASSID,
		PLPLANWORKCLASS.NAME ENTITYWORKCLASS,
		PLPLANSTATUS.NAME ENTITYSTATUS,
		PLSUBMITTAL.PLSUBMITTALID SUBMITTALID,
		BALANCEDUE = [reviewcoordinator].[UFN_GET_BALANCE_DUE](PLPLAN.PLPLANID),
		@PlanModule MODULE,
		SYSTEMTASK.SYSTEMTASKID,
		SYSTEMTASK.DUEDATE,
		SYSTEMTASK.SYSTEMTASKTYPEID TASKTYPEID,
		COALESCE(NULLIF(SYSTEMTASKTYPE.CUSTOMNAME,''), SYSTEMTASKTYPE.NAME) TASKTYPENAME,
		SYSTEMTASK.COMPLETEDDATE,
		SYSTEMTASK.ASSIGNEDTO USERASSIGNEDTO,
		USERS.FNAME USERFIRSTNAME,
		USERS.LNAME USERLASTNAME,
		ERENTITYPROJECT.ERENTITYPROJECTID,
		PRPROJECT.NAME PROJECTNAME,
		PLPLANSTATUS.SUCCESSFLAG ISSUEDFLAG,
		PLPLANSTATUS.SUCCESSFLAG COMPLETEDFLAG,
		PLPLANTYPEWORKCLASS.FILESETID,
		NEWFILECOUNT = (SELECT COUNT(*) FROM ERPROJECTFILEVERSION
			INNER JOIN ERPROJECTFILE ON ERPROJECTFILE.ERPROJECTFILEID = ERPROJECTFILEVERSION.ERPROJECTFILEID
			INNER JOIN ERPROJECT ON ERPROJECT.ERPROJECTID = ERPROJECTFILE.ERPROJECTID
			WHERE ERPROJECT.PLPLANID = PLPLAN.PLPLANID AND ERPROJECTFILEVERSION.SYSTEMTASKID = SYSTEMTASK.SYSTEMTASKID AND 
			ERPROJECTFILEVERSION.MARKDELETE = 0),
		RESUBMITTALREQUIREMENTSCOUNT = 
			(select count(*) from PLSUBMITTAL
			inner join PLSUBMITTALFILEVERSION on PLSUBMITTALFILEVERSION.PLSUBMITTALID = PLSUBMITTAL.PLSUBMITTALID
			inner join ERPROJECTFILEVERSION on ERPROJECTFILEVERSION.ERPROJECTFILEVERSIONID = PLSUBMITTALFILEVERSION.ERPROJECTFILEVERSIONID
			where PLSUBMITTAL.PLPLANID = PLPLAN.PLPLANID AND PLSUBMITTAL.COMPLETED = 0 AND ERPROJECTFILEVERSION.FILESTATUSID = @fileStatusRequiredForResubmittal),		
		HASSTOPHOLDS = [reviewcoordinator].[UFN_HAS_ACTIVE_STOP_HOLDS](PLPLAN.PLPLANID, @ALLOWHOLDOVERRIDE),
		PARCEL.PARCELNUMBER, 
		SYSTEMTASKTYPESUBMITTALTYPE.AUTOCLOSESESSION,
		PLPLANADDRESS.MAILINGADDRESSID,
		SYSTEMTASK.SNOOZETYPEID,
		SYSTEMTASK.SNOOZEUNTILDATE,
		ZONE.NAME ZONENAME,
		ZONE.ZONECODE,
		ZONE.DESCRIPTION ZONEDESCRIPTION,
		HASINVOICEBALANCEDUE = [reviewcoordinator].[UFN_HAS_INVOICE_BALANCE_DUE](PLPLAN.PLPLANID)
	FROM SYSTEMTASK
	INNER JOIN SYSTEMTASKTYPE ON SYSTEMTASKTYPE.SYSTEMTASKTYPEID = SYSTEMTASK.SYSTEMTASKTYPEID
	LEFT OUTER JOIN USERS ON USERS.SUSERGUID = SYSTEMTASK.ASSIGNEDTO
	INNER JOIN PLSUBMITTAL ON PLSUBMITTAL.PLSUBMITTALID = SYSTEMTASK.UNIQUERECORDID
	INNER JOIN PLPLAN ON PLPLAN.PLPLANID = PLSUBMITTAL.PLPLANID
	INNER JOIN PLPLANSTATUS ON PLPLANSTATUS.PLPLANSTATUSID = PLPLAN.PLPLANSTATUSID
	INNER JOIN PLPLANTYPE ON PLPLANTYPE.PLPLANTYPEID = PLPLAN.PLPLANTYPEID
	INNER JOIN PLPLANWORKCLASS ON PLPLANWORKCLASS.PLPLANWORKCLASSID = PLPLAN.PLPLANWORKCLASSID
	INNER JOIN PLPLANTYPEWORKCLASS ON PLPLANTYPEWORKCLASS.PLPLANTYPEID = PLPLANTYPE.PLPLANTYPEID AND PLPLANTYPEWORKCLASS.PLPLANWORKCLASSID = PLPLANWORKCLASS.PLPLANWORKCLASSID
	LEFT OUTER JOIN PRPROJECTPLAN ON PRPROJECTPLAN.PLPLANID = PLPLAN.PLPLANID
	LEFT OUTER JOIN PRPROJECT ON PRPROJECT.PRPROJECTID = PRPROJECTPLAN.PRPROJECTID		
	LEFT OUTER JOIN PLPLANADDRESS ON PLPLANADDRESS.PLPLANID = PLPLAN.PLPLANID AND PLPLANADDRESS.MAIN = 1
	LEFT OUTER JOIN PLPLANPARCEL ON PLPLANPARCEL.PLPLANID = PLPLAN.PLPLANID AND PLPLANPARCEL.MAIN = 1
	LEFT OUTER JOIN PARCEL ON PARCEL.PARCELID = PLPLANPARCEL.PARCELID
	LEFT OUTER JOIN SYSTEMTASKTYPESUBMITTALTYPE ON SYSTEMTASKTYPESUBMITTALTYPE.SYSTEMTASKTYPEID = SYSTEMTASK.SYSTEMTASKTYPEID AND 
		SYSTEMTASKTYPESUBMITTALTYPE.PLSUBMITTALTYPEID = PLSUBMITTAL.PLSUBMITTALTYPEID
	LEFT OUTER JOIN ERENTITYPROJECT ON ERENTITYPROJECT.PLPLANID = PLPLAN.PLPLANID
	LEFT OUTER JOIN PLPLANZONE ON PLPLANZONE.PLPLANID = PLPLAN.PLPLANID AND PLPLANZONE.MAIN = 1
	LEFT OUTER JOIN ZONE ON ZONE.ZONEID = PLPLANZONE.ZONEID
)
SELECT * FROM RAW_DATA WHERE SYSTEMTASKID = @SYSTEMTASKID

DECLARE @RESULT_ENTITYIDS RECORDIDS
;WITH ENTITY_IDS AS 
(
	SELECT * FROM (
	SELECT PMPERMITID ENTITYID, SYSTEMTASK.SYSTEMTASKID 
		FROM SYSTEMTASK
		INNER JOIN PMPERMIT ON PMPERMIT.PMPERMITID = SYSTEMTASK.UNIQUERECORDID
	UNION ALL
	SELECT PLPLAN.PLPLANID ENTITYID, SYSTEMTASK.SYSTEMTASKID
		FROM SYSTEMTASK
		INNER JOIN PLPLAN ON PLPLANID = SYSTEMTASK.UNIQUERECORDID
	UNION ALL
	SELECT COALESCE(PLSUBMITTAL.PMPERMITID, PLSUBMITTAL.PLPLANID) ENTITYID , SYSTEMTASK.SYSTEMTASKID
		FROM SYSTEMTASK
		INNER JOIN PLSUBMITTAL ON PLSUBMITTAL.PLSUBMITTALID = SYSTEMTASK.UNIQUERECORDID
	) QUERY_DATA
	WHERE SYSTEMTASKID = @SYSTEMTASKID
)
INSERT INTO @RESULT_ENTITYIDS SELECT ENTITYID FROM ENTITY_IDS

DECLARE @RESULT_SUBMITTALID CHAR(36)
;WITH SUBMITTAL_ID AS
(
	SELECT PLSUBMITTAL.PLSUBMITTALID, SYSTEMTASK.SYSTEMTASKID, PLSUBMITTAL.DUEDATE
	FROM SYSTEMTASK
	INNER JOIN PMPERMIT ON PMPERMIT.PMPERMITID = SYSTEMTASK.UNIQUERECORDID
	LEFT OUTER JOIN (
		SELECT TOP 1 PLSUBMITTAL.PLSUBMITTALID, PLSUBMITTAL.PLSUBMITTALTYPEID, PLSUBMITTAL.PMPERMITID, PLSUBMITTAL.DUEDATE FROM PLSUBMITTAL
			INNER JOIN SYSTEMTASK ON SYSTEMTASK.UNIQUERECORDID = PLSUBMITTAL.PMPERMITID
			LEFT OUTER JOIN PMPERMITWFACTIONSTEP ON PMPERMITWFACTIONSTEP.PMPERMITWFACTIONSTEPID = PLSUBMITTAL.PMPERMITWFACTIONSTEPID
			LEFT OUTER JOIN (SELECT PLSUBMITTALID, COUNT(*) SESSIONSTATUSCOUNT FROM ERENTITYSESSION GROUP BY PLSUBMITTALID, SESSIONSTATUSID) 
			ENTITYSESSION ON ENTITYSESSION.PLSUBMITTALID = PLSUBMITTAL.PLSUBMITTALID
			WHERE PLSUBMITTAL.COMPLETED = 0 AND ISNULL(PMPERMITWFACTIONSTEP.WORKFLOWSTATUSID,0) = @workFlowStatusStarted 			
			AND SYSTEMTASK.SYSTEMTASKID = @SYSTEMTASKID
			ORDER BY ENTITYSESSION.SESSIONSTATUSCOUNT DESC, PMPERMITWFACTIONSTEP.PRIORITYORDER, PLSUBMITTAL.DUEDATE, PMPERMITWFACTIONSTEP.IDENTITYCOLUMN
	) PLSUBMITTAL ON PLSUBMITTAL.PMPERMITID = PMPERMIT.PMPERMITID
	UNION ALL
	SELECT PLSUBMITTAL.PLSUBMITTALID, SYSTEMTASK.SYSTEMTASKID, PLSUBMITTAL.DUEDATE
	FROM SYSTEMTASK
	INNER JOIN PLPLAN ON PLPLAN.PLPLANID = SYSTEMTASK.UNIQUERECORDID
	LEFT OUTER JOIN (
		SELECT TOP 1 PLSUBMITTAL.PLSUBMITTALID, PLSUBMITTAL.PLSUBMITTALTYPEID, PLSUBMITTAL.PLPLANID, PLSUBMITTAL.DUEDATE FROM PLSUBMITTAL
			INNER JOIN SYSTEMTASK ON SYSTEMTASK.UNIQUERECORDID = PLSUBMITTAL.PLPLANID
			LEFT OUTER JOIN PLPLANWFACTIONSTEP ON PLPLANWFACTIONSTEP.PLPLANWFACTIONSTEPID = PLSUBMITTAL.PLPLANWFACTIONSTEPID
			LEFT OUTER JOIN (SELECT PLSUBMITTALID, COUNT(*) SESSIONSTATUSCOUNT FROM ERENTITYSESSION GROUP BY PLSUBMITTALID, SESSIONSTATUSID) 
			ENTITYSESSION ON ENTITYSESSION.PLSUBMITTALID = PLSUBMITTAL.PLSUBMITTALID
			WHERE PLSUBMITTAL.COMPLETED = 0 AND ISNULL(PLPLANWFACTIONSTEP.WORKFLOWSTATUSID,0) = @workFlowStatusStarted 			
			AND SYSTEMTASK.SYSTEMTASKID = @SYSTEMTASKID
			ORDER BY ENTITYSESSION.SESSIONSTATUSCOUNT DESC, PLPLANWFACTIONSTEP.PRIORITYORDER, PLSUBMITTAL.DUEDATE, PLPLANWFACTIONSTEP.IDENTITYCOLUMN
	) PLSUBMITTAL ON PLSUBMITTAL.PLPLANID = PLPLAN.PLPLANID
	UNION ALL
	SELECT PLSUBMITTALID, SYSTEMTASK.SYSTEMTASKID, PLSUBMITTAL.DUEDATE
	FROM SYSTEMTASK
	INNER JOIN PLSUBMITTAL ON PLSUBMITTAL.PLSUBMITTALID = SYSTEMTASK.UNIQUERECORDID
) SELECT TOP 1 @RESULT_SUBMITTALID = PLSUBMITTALID FROM SUBMITTAL_ID WHERE SYSTEMTASKID = @SYSTEMTASKID 

exec [reviewcoordinator].[USP_ADDRESS_GETBYENTITYIDS] @ENTITYIDS = @RESULT_ENTITYIDS
exec [reviewcoordinator].[USP_CONTACT_GETBYENTITYIDS] @ENTITYIDS = @RESULT_ENTITYIDS
exec [reviewcoordinator].[USP_HOLD_GETBYENTITYIDS] @ENTITYIDS = @RESULT_ENTITYIDS
exec [reviewcoordinator].[USP_ERENTITYPROJECTSESSIONFILE_GETBYPLSUBMITTALID] @PLSUBMITTALID = @RESULT_SUBMITTALID
exec [reviewcoordinator].[USP_ENTITY_CASE_GISFEATURE_GETBYENTITYIDS] @ENTITYIDS=@RESULT_ENTITYIDS

DECLARE @RESULT_SUBMITTALIDS RECORDIDS
INSERT INTO @RESULT_SUBMITTALIDS (RECORDID) VALUES (@RESULT_SUBMITTALID)

exec [reviewcoordinator].[USP_ERENTITYSESSION_GETBYPLSUBMITTALID] @PLSUBMITTALID = @RESULT_SUBMITTALID
exec [reviewcoordinator].[USP_ERENTITYPROJECTSESSIONFILE_GETBYPLSUBMITTALID] @PLSUBMITTALID = @RESULT_SUBMITTALID
exec [reviewcoordinator].[USP_ERENTITYSESSIONTRANSACTION_GETBYPLSUBMITTALIDS] @SUBMITTALIDS = @RESULT_SUBMITTALIDS
exec [reviewcoordinator].[USP_ERENTITYSESSIONTRANSACTIONTASK_GETBYPLSUBMITTALID] @PLSUBMITTALID = @RESULT_SUBMITTALID 
exec [reviewcoordinator].[USP_ERPROJECTFILEVERSION_GETBYENTITYIDS] @ENTITYIDS=@RESULT_ENTITYIDS

END