CREATE PROCEDURE [reviewcoordinator].[USP_USERS_ALLOWED_UPDATE_RECORDTYPES_GET]
@TYPEIDS RecordIds READONLY, 
@USERIDS RecordIds READONLY AS
 
BEGIN
SET NOCOUNT ON;

;WITH ROLE_IDS AS
(
	SELECT DISTINCT ROLES.SROLEGUID 
	FROM ROLES
	INNER JOIN ROLERECORDTYPEXREF ON ROLES.SROLEGUID = ROLERECORDTYPEXREF.ROLEID
	WHERE ROLERECORDTYPEXREF.RECORDTYPEID IN (SELECT RECORDID FROM @TYPEIDS)
	AND ROLERECORDTYPEXREF.ALLOWUPDATE = 1
	GROUP BY SROLEGUID
	HAVING COUNT(SROLEGUID) = (SELECT COUNT(DISTINCT RECORDID) FROM @TYPEIDS)
)
SELECT DISTINCT USERS.BACTIVE,
        USERS.CREATEDON,
        USERS.EMAIL,
        USERS.FNAME,
        USERS.ID,
        USERS.LASTCHANGEDON,
        USERS.LNAME,
        USERS.PHONE,
        USERS.SROLEID,
        USERS.SUSERGUID 
FROM USERS
WHERE USERS.BACTIVE = 1
AND USERS.SUSERGUID IN (SELECT RECORDID FROM @USERIDS)
AND USERS.SROLEID IN (SELECT SROLEGUID FROM ROLE_IDS)
order by USERS.FNAME
END