CREATE PROCEDURE [reviewcoordinator].[USP_INBOX_CARD_FACETS_GET_ASSIGNED_TO]
	@ASSIGNEDUSERIDS AS RECORDIDS READONLY,
	@ASSIGNEDTEAMIDS AS RECORDIDS READONLY,
	@TODAY AS DATE
AS
BEGIN

WITH ASSIGNED_TO AS
(
SELECT 		
		SYSTEMTASK.COMPLETEDDATE,
		SYSTEMTASK.TEAMASSIGNEDTO, 
		SYSTEMTASK.ASSIGNEDTO USERASSIGNEDTO,
		USERS.FNAME USERFIRSTNAME,
		USERS.LNAME USERLASTNAME,
		SYSTEMTASK.SYSTEMTASKID,
		SYSTEMTASK.SNOOZETYPEID, 
		SYSTEMTASK.SNOOZEUNTILDATE
	FROM SYSTEMTASK
	INNER JOIN USERS ON USERS.SUSERGUID = SYSTEMTASK.ASSIGNEDTO
	LEFT OUTER JOIN PLSUBMITTAL ON PLSUBMITTAL.PLSUBMITTALID = SYSTEMTASK.UNIQUERECORDID
WHERE
	(ASSIGNEDTO IN (SELECT RECORDID FROM @ASSIGNEDUSERIDS) OR 
	(ASSIGNEDTO IS NULL AND TEAMASSIGNEDTO IN (SELECT RECORDID FROM @ASSIGNEDTEAMIDS))
	) AND
	COMPLETEDDATE IS NULL
	AND [reviewcoordinator].[UFN_IS_SNOOZED](SNOOZETYPEID, 
		[reviewcoordinator].[UFN_HAS_INVOICE_BALANCE_DUE](COALESCE(PLSUBMITTAL.PMPERMITID, PLSUBMITTAL.PLPLANID, SYSTEMTASK.UNIQUERECORDID)), 
		SNOOZEUNTILDATE, @TODAY) = 0
)
SELECT USERASSIGNEDTO ID, USERFIRSTNAME FIRSTNAME, USERLASTNAME LASTNAME, COUNT(*) COUNT
FROM ASSIGNED_TO 
WHERE USERASSIGNEDTO IS NOT NULL
GROUP BY USERASSIGNEDTO, USERFIRSTNAME, USERLASTNAME
ORDER BY COUNT(*) DESC, USERFIRSTNAME, USERLASTNAME

END