CREATE PROCEDURE [reviewcoordinator].[USP_ERPROJECTFILEVERSION_GETBYENTITYID]
(
	@ENTITYID VARCHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	ERPROJECTFILEVERSIONID,
	SAVEFILENAME
FROM ERPROJECTFILEVERSION
INNER JOIN ERPROJECTFILE ON ERPROJECTFILE.ERPROJECTFILEID = ERPROJECTFILEVERSION.ERPROJECTFILEID
INNER JOIN ERPROJECT ON ERPROJECT.ERPROJECTID = ERPROJECTFILE.ERPROJECTID
WHERE
	ERPROJECT.PMPERMITID = @ENTITYID or ERPROJECT.PLPLANID = @ENTITYID
END