CREATE PROCEDURE [reviewcoordinator].[USP_INBOX_CARD_FACETS_GET]
	@ASSIGNEDUSERIDS AS RECORDIDS READONLY,
	@ASSIGNEDTEAMIDS AS RECORDIDS READONLY,
	@OWNEDTEAMIDS AS RECORDIDS READONLY,
	@TODAY AS DATE = NULL,
	@NEXTBUSINESSDAYBEGIN AS DATE = NULL,
	@NEXTBUSINESSDAYEND AS DATE = NULL,
	@OVERDUEDATE AS DATE = NULL
AS
BEGIN

SET NOCOUNT ON;
DECLARE @facetTypeIncomplete INT = 0;

EXEC [reviewcoordinator].[USP_INBOX_CARD_FACETS_GET_TODAY] @ASSIGNEDUSERIDS = @ASSIGNEDUSERIDS, @ASSIGNEDTEAMIDS = @ASSIGNEDTEAMIDS, @TODAY = @TODAY
EXEC [reviewcoordinator].[USP_INBOX_CARD_FACETS_GET_NEXT_BUSINESS_DAYS] @ASSIGNEDUSERIDS = @ASSIGNEDUSERIDS, @ASSIGNEDTEAMIDS = @ASSIGNEDTEAMIDS, @NEXTBUSINESSDAYBEGIN = @NEXTBUSINESSDAYBEGIN, @NEXTBUSINESSDAYEND = @NEXTBUSINESSDAYEND, @TODAY = @TODAY
EXEC [reviewcoordinator].[USP_INBOX_CARD_FACETS_GET_OVERDUE] @ASSIGNEDUSERIDS = @ASSIGNEDUSERIDS, @ASSIGNEDTEAMIDS = @ASSIGNEDTEAMIDS, @OVERDUEDATE = @OVERDUEDATE, @TODAY = @TODAY

EXEC [reviewcoordinator].[USP_INBOX_CARD_FACETS_GET_ASSIGNED_TO] @ASSIGNEDUSERIDS = @ASSIGNEDUSERIDS, @ASSIGNEDTEAMIDS = @ASSIGNEDTEAMIDS, @TODAY = @TODAY
EXEC [reviewcoordinator].[USP_INBOX_CARD_FACETS_GET_ASSIGNED_TO_TEAM] @ASSIGNEDUSERIDS = @ASSIGNEDUSERIDS, @OWNEDTEAMIDS = @OWNEDTEAMIDS, @TODAY = @TODAY

EXEC [reviewcoordinator].[USP_INBOX_CARD_FACETS_GET_TASK_TYPE] @FACETTYPE = @facetTypeIncomplete, @ASSIGNEDUSERIDS = @ASSIGNEDUSERIDS, @ASSIGNEDTEAMIDS = @ASSIGNEDTEAMIDS, @TODAY = @TODAY
EXEC [reviewcoordinator].[USP_INBOX_CARD_FACETS_GET_ENTITY_TYPE] @FACETTYPE = @facetTypeIncomplete, @ASSIGNEDUSERIDS = @ASSIGNEDUSERIDS, @ASSIGNEDTEAMIDS = @ASSIGNEDTEAMIDS, @TODAY = @TODAY
EXEC [reviewcoordinator].[USP_INBOX_CARD_FACETS_GET_ENTITY_NUMBER] @FACETTYPE = @facetTypeIncomplete, @ASSIGNEDUSERIDS = @ASSIGNEDUSERIDS, @ASSIGNEDTEAMIDS = @ASSIGNEDTEAMIDS, @TODAY = @TODAY

END