CREATE PROCEDURE [reviewcoordinator].[USP_ENTITY_CASE_FACETS_GET_ENTITY_TYPE]
	@ASSIGNEDUSERIDS AS RECORDIDS READONLY
AS
BEGIN

WITH ENTITY_TYPE AS 
(
	SELECT * FROM (	
	SELECT		
			PMPERMIT.PMPERMITTYPEID ENTITYTYPEID,
			PMPERMITTYPE.NAME ENTITYTYPE,
			PMPERMIT.ASSIGNEDTO ASSIGNEDTO,
			PMPERMIT.FINALIZEDATE COMPLETEDATE
		FROM PMPERMIT	
		INNER JOIN PMPERMITTYPE ON PMPERMITTYPE.PMPERMITTYPEID = PMPERMIT.PMPERMITTYPEID
		UNION ALL
		SELECT					
			PLPLAN.PLPLANTYPEID ENTITYTYPEID,
			PLPLANTYPE.PLANNAME ENTITYTYPE,
			PLPLAN.ASSIGNEDTO ASSIGNEDTO,
			PLPLAN.COMPLETEDATE COMPLETEDAT
		FROM PLPLAN			
		INNER JOIN PLPLANTYPE ON PLPLANTYPE.PLPLANTYPEID = PLPLAN.PLPLANTYPEID
) AS QUERY_DATA
	WHERE 	
	ASSIGNEDTO IN (SELECT RECORDID FROM @ASSIGNEDUSERIDS) AND
	COMPLETEDATE IS NULL
) 
SELECT ENTITYTYPEID ID, ENTITYTYPE NAME, COUNT(*) COUNT
FROM ENTITY_TYPE
WHERE ENTITYTYPEID IS NOT NULL
GROUP BY ENTITYTYPEID, ENTITYTYPE
ORDER BY COUNT(*) DESC, ENTITYTYPE

END