CREATE PROCEDURE [reviewcoordinator].[USP_ENTITY_CASE_FACETS_GET_PROJECT]
	@ASSIGNEDUSERIDS AS RECORDIDS READONLY
AS
BEGIN

WITH PROJECT AS 
(
	SELECT * FROM (	
	SELECT					
			PRPROJECT.PRPROJECTID PROJECTID,
			PRPROJECT.NAME PROJECTNAME,
			PMPERMIT.ASSIGNEDTO ASSIGNEDTO,
			PMPERMIT.FINALIZEDATE COMPLETEDATE
		FROM PMPERMIT			
		LEFT OUTER JOIN PRPROJECTPERMIT ON PRPROJECTPERMIT.PMPERMITID = PMPERMIT.PMPERMITID
		LEFT OUTER JOIN PRPROJECT ON PRPROJECT.PRPROJECTID = PRPROJECTPERMIT.PRPROJECTID	
		UNION ALL
		SELECT		
			
			PRPROJECT.PRPROJECTID PROJECTID,
			PRPROJECT.NAME PROJECTNAME,
			PLPLAN.ASSIGNEDTO ASSIGNEDTO,
			PLPLAN.COMPLETEDATE COMPLETEDATE
		FROM PLPLAN
		LEFT OUTER JOIN PRPROJECTPLAN ON PRPROJECTPLAN.PLPLANID = PLPLAN.PLPLANID
		LEFT OUTER JOIN PRPROJECT ON PRPROJECT.PRPROJECTID = PRPROJECTPLAN.PRPROJECTID	
) AS QUERY_DATA
	WHERE 	
	ASSIGNEDTO IN (SELECT RECORDID FROM @ASSIGNEDUSERIDS) AND
	COMPLETEDATE IS NULL
)
SELECT PROJECTID ID, PROJECTNAME NAME, COUNT(*) COUNT
FROM PROJECT 
GROUP BY PROJECTID, PROJECTNAME
ORDER BY COUNT(*) DESC, PROJECTNAME

END