CREATE PROCEDURE [reviewcoordinator].[USP_ENTITY_CASE_FACETS_GET_TODAY]
	@ASSIGNEDUSERIDS AS RECORDIDS READONLY,
	@TODAY AS DATE = NULL
AS
BEGIN

WITH TODAY AS 
(
	SELECT 
		PMPERMIT.APPLYDATE APPLIEDDATE, 
		PMPERMIT.FINALIZEDATE COMPLETEDATE, 
		PMPERMIT.ASSIGNEDTO ASSIGNEDTO 
	FROM PMPERMIT
	UNION ALL
	SELECT 
		APPLICATIONDATE APPLIEDDATE, 
		PLPLAN.COMPLETEDATE COMPLETEDATE, 
		PLPLAN.ASSIGNEDTO ASSIGNEDTO 
	FROM PLPLAN
) 
SELECT ID = 'Today', NAME = 'Today', COUNT(*) COUNT
FROM TODAY
WHERE 
	ASSIGNEDTO IN (SELECT RECORDID FROM @ASSIGNEDUSERIDS) AND 
	COMPLETEDATE IS NULL
	AND APPLIEDDATE >= @TODAY AND APPLIEDDATE < DATEADD(D, 1, @TODAY)

END