CREATE PROCEDURE [reviewcoordinator].[USP_ERFILEMARKUP_GETBYPLSUBMITTALID]
(
	@PLSUBMITTALID VARCHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT
	ERFILEMARKUP.ERFILEMARKUPID,
	ERFILEMARKUP.ERPROJECTFILEVERSIONID,
	ERFILEMARKUP.AUTHOR,
	ERFILEMARKUP.MARKUPTYPE,
	ERFILEMARKUP.COMMENTS,
	ERFILEMARKUP.CREATEDON,
	ERFILEMARKUP.FILENAME,
	ERFILEMARKUP.PAGENUMBER,
	ERFILEMARKUP.CREATEDBY,
	USERS.FNAME USERFIRSTNAME,
	USERS.LNAME USERLASTNAME
	FROM ERPROJECTFILEVERSION
	INNER JOIN PLSUBMITTALFILEVERSION ON ERPROJECTFILEVERSION.ERPROJECTFILEVERSIONID = PLSUBMITTALFILEVERSION.ERPROJECTFILEVERSIONID
	INNER JOIN ERENTITYSESSION AS ERENTITYSESSION ON PLSUBMITTALFILEVERSION.PLSUBMITTALID = ERENTITYSESSION.PLSUBMITTALID
	INNER JOIN ERFILEMARKUP AS ERFILEMARKUP ON (ERPROJECTFILEVERSION.ERPROJECTFILEVERSIONID = ERFILEMARKUP.ERPROJECTFILEVERSIONID) AND (ERFILEMARKUP.ERENTITYSESSIONID = ERENTITYSESSION.ERENTITYSESSIONID)
	LEFT OUTER JOIN USERS ON USERS.SUSERGUID = ERFILEMARKUP.CREATEDBY
WHERE PLSUBMITTALFILEVERSION.PLSUBMITTALID = @PLSUBMITTALID  AND ERPROJECTFILEVERSION.MARKDELETE = 0
ORDER BY ERFILEMARKUP.CREATEDON

END