CREATE TABLE [dbo].[BCSW_RECEIPT] (
    [RECEIPT_ID]     CHAR (36)     NOT NULL,
    [INVOICE_ID]     CHAR (36)     NOT NULL,
    [RECIEPT_OBJECT] VARCHAR (MAX) NOT NULL,
    [ERROR_MESSAGE]  VARCHAR (MAX) NULL,
    [TIME_STAMP]     DATETIME      NOT NULL,
    [STATUS_CODE]    INT           NULL,
    CONSTRAINT [PK_BCSW_RECEIPT] PRIMARY KEY CLUSTERED ([RECEIPT_ID] ASC) WITH (FILLFACTOR = 90)
);

