CREATE TABLE [dbo].[BLBATCHRENEWALLOG] (
    [BLBATCHRENEWALLOGID] CHAR (36)      NOT NULL,
    [BLBATCHRENEWALID]    CHAR (36)      NULL,
    [BLLICENSEID]         CHAR (36)      NULL,
    [RENEWEDBLLICENSEID]  CHAR (36)      NULL,
    [CAINVOICEID]         CHAR (36)      NULL,
    [PROCESSEDDATE]       DATETIME       NULL,
    [REMARKS]             NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_BLBATCHRENEWALLOG] PRIMARY KEY CLUSTERED ([BLBATCHRENEWALLOGID] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [NCIDX_BLBATCHRENEWALLOG_BLLICENSEID_CAINVOICEID]
    ON [dbo].[BLBATCHRENEWALLOG]([BLLICENSEID] ASC, [CAINVOICEID] ASC);


GO
CREATE NONCLUSTERED INDEX [NCIDX_BLBATCHRENEWALLOG_CAINVOICEID]
    ON [dbo].[BLBATCHRENEWALLOG]([CAINVOICEID] ASC);

