CREATE TABLE [dbo].[BLCONTACTTYPEREF] (
    [CONTACTTYPEEXTID]           CHAR (36) NOT NULL,
    [BLCONTACTTYPEID]            CHAR (36) NOT NULL,
    [CONTACTTYPEGROUP]           INT       NULL,
    [ISREQUIRED]                 BIT       CONSTRAINT [DF_BLCONTACTTYPEREF_REQ] DEFAULT ((0)) NOT NULL,
    [OBJCLASSID]                 CHAR (36) NULL,
    [OBJTYPEID]                  CHAR (36) NULL,
    [OBJMODULEID]                INT       NOT NULL,
    [ISDEFAULTONLINECONTACTTYPE] BIT       DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_BLCONTACTTYPEREF] PRIMARY KEY CLUSTERED ([CONTACTTYPEEXTID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_BLCONTACTTYPEREF_COTYPE] FOREIGN KEY ([BLCONTACTTYPEID]) REFERENCES [dbo].[BLCONTACTTYPE] ([BLCONTACTTYPEID])
);


GO
CREATE NONCLUSTERED INDEX [BLCONTACTTYPEREF_IX_OBJTYPEID]
    ON [dbo].[BLCONTACTTYPEREF]([OBJTYPEID] ASC);


GO

CREATE TRIGGER [dbo].[TG_BLCONTACTTYPEREF_DELETE] ON [dbo].[BLCONTACTTYPEREF]
   AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [HISTORYSYSTEMSETUP]
    (	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )

	SELECT
			[BLEXTCOMPANYTYPE].[BLEXTCOMPANYTYPEID],
			[BLEXTCOMPANYTYPE].[ROWVERSION],
			GETUTCDATE(),
			(SELECT dbo.UFN_GET_USERID_FROM_CONTEXT_INFO()),
			'Business Company Type Contact Type Deleted',
			'',
			'',
			'Business Company Type (' + [BLEXTCOMPANYTYPE].[NAME] + '),  Contact Type (' + [BLCONTACTTYPE].[NAME] + ')',
			'AD2A1266-BD91-418D-94E0-D99B930A57D0',
			3,
			0,
			[BLCONTACTTYPE].[NAME]
	FROM	[deleted]
			JOIN [BLCONTACTTYPE] ON [BLCONTACTTYPE].[BLCONTACTTYPEID] = [deleted].[BLCONTACTTYPEID]
			JOIN [BLEXTCOMPANYTYPE] ON [BLEXTCOMPANYTYPE].[BLEXTCOMPANYTYPEID] = [deleted].[OBJTYPEID]
	UNION ALL
	SELECT DISTINCT
			[BLLICENSETYPE].[BLLICENSETYPEID],
			[BLLICENSETYPE].[ROWVERSION],
			GETUTCDATE(),
			(SELECT dbo.UFN_GET_USERID_FROM_CONTEXT_INFO()),
			'Business License Type Contact Type Deleted',
			'',
			'',
			'Business License Type (' + [BLLICENSETYPE].[NAME] + '), Contact Type (' + [BLCONTACTTYPE].[NAME] + ')',
			'8C9D2A3A-2F18-45CE-B059-33A98C1EA148',
			3,
			0,
			[BLCONTACTTYPE].[NAME]
	FROM	[deleted]	
		LEFT JOIN [dbo].[BLLICENSETYPECLASS] ON [deleted].[OBJTYPEID] = [BLLICENSETYPEID] 
		INNER JOIN [dbo].[BLLICENSETYPE] ON [BLLICENSETYPE].[BLLICENSETYPEID] = [BLLICENSETYPECLASS].[BLLICENSETYPEID]
		LEFT JOIN [dbo].[BLLICENSECLASS] ON [deleted].[OBJCLASSID] = [BLLICENSECLASS].[BLLICENSECLASSID]
		INNER JOIN [dbo].[BLCONTACTTYPE] WITH (NOLOCK) ON [deleted].[BLCONTACTTYPEID] = [BLCONTACTTYPE].[BLCONTACTTYPEID]
	UNION ALL
	SELECT DISTINCT
			[ILLICENSETYPE].[ILLICENSETYPEID],
			[ILLICENSETYPE].[ROWVERSION],
			GETUTCDATE(),
			(SELECT dbo.UFN_GET_USERID_FROM_CONTEXT_INFO()),
			'Professional License Type Contact Type Deleted',
			'',
			'',
			'Professional License Type (' + [ILLICENSETYPE].[NAME] + '), Contact Type (' + [BLCONTACTTYPE].[NAME] + ')',
			'67978C16-D720-4F8E-8120-E00FBB732A77',
			3,
			0,
			[BLCONTACTTYPE].[NAME]
	FROM	[deleted]	
		INNER JOIN [dbo].[ILLICENSETYPE] ON [ILLICENSETYPE].[ILLICENSETYPEID] = [deleted].[OBJTYPEID]
		LEFT JOIN [dbo].[ILLICENSECLASSIFICATION] ON [deleted].[OBJCLASSID] = [ILLICENSECLASSIFICATION].[ILLICENSECLASSIFICATIONID]
		INNER JOIN [dbo].[BLCONTACTTYPE] WITH (NOLOCK) ON [deleted].[BLCONTACTTYPEID] = [BLCONTACTTYPE].[BLCONTACTTYPEID]
END
GO

CREATE TRIGGER [TG_BLCONTACTTYPEREF_INSERT] ON BLCONTACTTYPEREF
	AFTER INSERT
AS
BEGIN
	SET NOCOUNT ON

	INSERT INTO [HISTORYSYSTEMSETUP]
	(
		[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
	)
	SELECT 
			[BLEXTCOMPANYTYPE].[BLEXTCOMPANYTYPEID],
			[BLEXTCOMPANYTYPE].[ROWVERSION],
			GETUTCDATE(),
			[BLEXTCOMPANYTYPE].[LASTCHANGEDBY],
			'Business Company Type Contact Type Added',
			'',
			'',
			'Business Company Type (' + [BLEXTCOMPANYTYPE].[NAME] + '),  Contact Type (' + [BLCONTACTTYPE].[NAME] + ')',
			'AD2A1266-BD91-418D-94E0-D99B930A57D0',
			1,
			0,
			[BLCONTACTTYPE].[NAME]
	FROM	[inserted]
	JOIN BLEXTCOMPANYTYPE ON [inserted].[OBJTYPEID] = BLEXTCOMPANYTYPE.BLEXTCOMPANYTYPEID
	JOIN BLCONTACTTYPE WITH (NOLOCK) ON [inserted].BLCONTACTTYPEID = [BLCONTACTTYPE].[BLCONTACTTYPEID]
	UNION ALL
	SELECT DISTINCT
			[BLLICENSETYPE].[BLLICENSETYPEID],
			[BLLICENSETYPE].[ROWVERSION],
			GETUTCDATE(),
			[BLLICENSETYPE].[LASTCHANGEDBY],
			'Business License Type Contact Type Added',
			'',
			'',
			'Business License Type (' + [BLLICENSETYPE].[NAME] + '), Contact Type (' + [BLCONTACTTYPE].[NAME] + ')',
			'8C9D2A3A-2F18-45CE-B059-33A98C1EA148',
			1,
			0,
			[BLCONTACTTYPE].[NAME]
	FROM	[inserted]	
		LEFT JOIN [dbo].[BLLICENSETYPECLASS] ON [inserted].[OBJTYPEID] = [BLLICENSETYPEID] 
		INNER JOIN [dbo].[BLLICENSETYPE] ON [BLLICENSETYPE].[BLLICENSETYPEID] = [BLLICENSETYPECLASS].[BLLICENSETYPEID]
		LEFT JOIN [dbo].[BLLICENSECLASS] ON [inserted].[OBJCLASSID] = [BLLICENSECLASS].[BLLICENSECLASSID]
		INNER JOIN [dbo].[BLCONTACTTYPE] WITH (NOLOCK) ON [inserted].[BLCONTACTTYPEID] = [BLCONTACTTYPE].[BLCONTACTTYPEID]
	UNION ALL
	SELECT DISTINCT
			[ILLICENSETYPE].[ILLICENSETYPEID],
			[ILLICENSETYPE].[ROWVERSION],
			GETUTCDATE(),
			[ILLICENSETYPE].[LASTCHANGEDBY],
			'Professional License Type Contact Type Added',
			'',
			'',
			'Professional License Type (' + [ILLICENSETYPE].[NAME] + '), Contact Type (' + [BLCONTACTTYPE].[NAME] + ')',
			'67978C16-D720-4F8E-8120-E00FBB732A77',
			1,
			0,
			[BLCONTACTTYPE].[NAME]
	FROM	[inserted]	
		INNER JOIN [dbo].[ILLICENSETYPE] ON [ILLICENSETYPE].[ILLICENSETYPEID] = [inserted].[OBJTYPEID]
		LEFT JOIN [dbo].[ILLICENSECLASSIFICATION] ON [inserted].[OBJCLASSID] = [ILLICENSECLASSIFICATION].[ILLICENSECLASSIFICATIONID]
		INNER JOIN [dbo].[BLCONTACTTYPE] WITH (NOLOCK) ON [inserted].[BLCONTACTTYPEID] = [BLCONTACTTYPE].[BLCONTACTTYPEID]
END
GO

CREATE TRIGGER [dbo].[TG_BLCONTACTTYPEREF_UPDATE] ON [dbo].[BLCONTACTTYPEREF]
	AFTER UPDATE
AS 
BEGIN
	SET NOCOUNT ON;
		
    INSERT INTO [HISTORYSYSTEMSETUP]
    (	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT
			[BLEXTCOMPANYTYPE].[BLEXTCOMPANYTYPEID],
			[BLEXTCOMPANYTYPE].[ROWVERSION],
			GETUTCDATE(),
			[BLEXTCOMPANYTYPE].[LASTCHANGEDBY],
			'Business Company Type Contact Type Required Flag',
			CASE [deleted].[ISREQUIRED] WHEN 1 THEN 'Yes' ELSE 'No' END,
			CASE [inserted].[ISREQUIRED] WHEN 1 THEN 'Yes' ELSE 'No' END,
			'Business Company Type (' + [BLEXTCOMPANYTYPE].[NAME] + '),  Contact Type (' + [BLCONTACTTYPE].[NAME] + ')',
			'AD2A1266-BD91-418D-94E0-D99B930A57D0',
			2,
			0,
			[BLCONTACTTYPE].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CONTACTTYPEEXTID] = [inserted].[CONTACTTYPEEXTID]
			JOIN [BLCONTACTTYPE] ON [BLCONTACTTYPE].[BLCONTACTTYPEID] = [deleted].[BLCONTACTTYPEID]
			JOIN [BLEXTCOMPANYTYPE] ON [BLEXTCOMPANYTYPE].[BLEXTCOMPANYTYPEID] = [deleted].[OBJTYPEID]
	WHERE	[deleted].[ISREQUIRED] <> [inserted].[ISREQUIRED]
	UNION ALL
	SELECT
			[BLEXTCOMPANYTYPE].[BLEXTCOMPANYTYPEID],
			[BLEXTCOMPANYTYPE].[ROWVERSION],
			GETUTCDATE(),
			[BLEXTCOMPANYTYPE].[LASTCHANGEDBY],
			'Business Company Type Contact Type Default Online Contact Type Flag',
			CASE [deleted].[ISDEFAULTONLINECONTACTTYPE] WHEN 1 THEN 'Yes' ELSE 'No' END,
			CASE [inserted].[ISDEFAULTONLINECONTACTTYPE] WHEN 1 THEN 'Yes' ELSE 'No' END,
			'Business Company Type (' + [BLEXTCOMPANYTYPE].[NAME] + '),  Contact Type (' + [BLCONTACTTYPE].[NAME] + ')',
			'AD2A1266-BD91-418D-94E0-D99B930A57D0',
			2,
			0,
			[BLCONTACTTYPE].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CONTACTTYPEEXTID] = [inserted].[CONTACTTYPEEXTID]
			JOIN [BLCONTACTTYPE] ON [BLCONTACTTYPE].[BLCONTACTTYPEID] = [deleted].[BLCONTACTTYPEID]
			JOIN [BLEXTCOMPANYTYPE] ON [BLEXTCOMPANYTYPE].[BLEXTCOMPANYTYPEID] = [deleted].[OBJTYPEID]
	WHERE	[deleted].[ISDEFAULTONLINECONTACTTYPE] <> [inserted].[ISDEFAULTONLINECONTACTTYPE]
	UNION ALL
	SELECT 
			[BLEXTCOMPANYTYPE].[BLEXTCOMPANYTYPEID],
			[BLEXTCOMPANYTYPE].[ROWVERSION],
			GETUTCDATE(),
			[BLEXTCOMPANYTYPE].[LASTCHANGEDBY],
			'Business Company Type Contact Type Set',
			CASE WHEN [deleted].[CONTACTTYPEGROUP] IS NULL THEN '[none]' ELSE CONVERT(NVARCHAR(MAX), [deleted].[CONTACTTYPEGROUP]) END,
			CASE WHEN [inserted].[CONTACTTYPEGROUP] IS NULL THEN '[none]' ELSE CONVERT(NVARCHAR(MAX), [inserted].[CONTACTTYPEGROUP]) END,			
			'Business Company Type (' + [BLEXTCOMPANYTYPE].[NAME] + '),  Contact Type (' + [BLCONTACTTYPE].[NAME] + ')',
			'AD2A1266-BD91-418D-94E0-D99B930A57D0',
			2,
			0,
			[BLCONTACTTYPE].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CONTACTTYPEEXTID] = [inserted].[CONTACTTYPEEXTID]
			JOIN [BLCONTACTTYPE] ON [BLCONTACTTYPE].[BLCONTACTTYPEID] = [deleted].[BLCONTACTTYPEID]
			JOIN [BLEXTCOMPANYTYPE] ON [BLEXTCOMPANYTYPE].[BLEXTCOMPANYTYPEID] = [deleted].[OBJTYPEID]
	WHERE	ISNULL([deleted].[CONTACTTYPEGROUP],'') <> ISNULL([inserted].[CONTACTTYPEGROUP],'')
	UNION ALL
	SELECT DISTINCT
			[BLLICENSETYPE].[BLLICENSETYPEID],
			[BLLICENSETYPE].[ROWVERSION],
			GETUTCDATE(),
			[BLLICENSETYPE].[LASTCHANGEDBY],
			'Required Flag',
			CASE [deleted].[ISREQUIRED] WHEN 1 THEN 'Yes' ELSE 'No' END,
			CASE [inserted].[ISREQUIRED] WHEN 1 THEN 'Yes' ELSE 'No' END,
			'Business License Type (' + [BLLICENSETYPE].[NAME] + '), Contact Type (' + [BLCONTACTTYPE].[NAME] + ')',
			'8C9D2A3A-2F18-45CE-B059-33A98C1EA148',
			2,
			0,
			[BLCONTACTTYPE].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CONTACTTYPEEXTID] = [inserted].[CONTACTTYPEEXTID]
			INNER JOIN [BLLICENSETYPECLASS] ON [deleted].[OBJTYPEID] = [BLLICENSETYPEID] 
			INNER JOIN [BLLICENSETYPE] ON [BLLICENSETYPE].[BLLICENSETYPEID] = [BLLICENSETYPECLASS].[BLLICENSETYPEID]
			INNER JOIN [BLLICENSECLASS] ON [deleted].[OBJCLASSID] = [BLLICENSECLASS].[BLLICENSECLASSID]
			INNER JOIN [BLCONTACTTYPE] WITH (NOLOCK) ON [deleted].[BLCONTACTTYPEID] = [BLCONTACTTYPE].[BLCONTACTTYPEID]
	WHERE	[deleted].[ISREQUIRED] <> [inserted].[ISREQUIRED]
	UNION ALL
	SELECT DISTINCT
			[BLLICENSETYPE].[BLLICENSETYPEID],
			[BLLICENSETYPE].[ROWVERSION],
			GETUTCDATE(),
			[BLLICENSETYPE].[LASTCHANGEDBY],
			'Default Online Contact Type Flag',
			CASE [deleted].[ISDEFAULTONLINECONTACTTYPE] WHEN 1 THEN 'Yes' ELSE 'No' END,
			CASE [inserted].[ISDEFAULTONLINECONTACTTYPE] WHEN 1 THEN 'Yes' ELSE 'No' END,
			'Business License Type (' + [BLLICENSETYPE].[NAME] + '), Contact Type (' + [BLCONTACTTYPE].[NAME] + ')',
			'8C9D2A3A-2F18-45CE-B059-33A98C1EA148',
			2,
			0,
			[BLCONTACTTYPE].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CONTACTTYPEEXTID] = [inserted].[CONTACTTYPEEXTID]
			INNER JOIN [BLLICENSETYPECLASS] ON [deleted].[OBJTYPEID] = [BLLICENSETYPEID] 
			INNER JOIN [BLLICENSETYPE] ON [BLLICENSETYPE].[BLLICENSETYPEID] = [BLLICENSETYPECLASS].[BLLICENSETYPEID]
			INNER JOIN [BLLICENSECLASS] ON [deleted].[OBJCLASSID] = [BLLICENSECLASS].[BLLICENSECLASSID]
			INNER JOIN [BLCONTACTTYPE] WITH (NOLOCK) ON [deleted].[BLCONTACTTYPEID] = [BLCONTACTTYPE].[BLCONTACTTYPEID]
	WHERE	[deleted].[ISDEFAULTONLINECONTACTTYPE] <> [inserted].[ISDEFAULTONLINECONTACTTYPE]
	UNION ALL
	SELECT DISTINCT
			[BLLICENSETYPE].[BLLICENSETYPEID],
			[BLLICENSETYPE].[ROWVERSION],
			GETUTCDATE(),
			[BLLICENSETYPE].[LASTCHANGEDBY],
			'Set',
			CASE WHEN [deleted].[CONTACTTYPEGROUP] IS NULL THEN '[none]' ELSE CONVERT(NVARCHAR(MAX), [deleted].[CONTACTTYPEGROUP]) END,
			CASE WHEN [inserted].[CONTACTTYPEGROUP] IS NULL THEN '[none]' ELSE CONVERT(NVARCHAR(MAX), [inserted].[CONTACTTYPEGROUP]) END,			
			'Business License Type (' + [BLLICENSETYPE].[NAME] + '), Contact Type (' + [BLCONTACTTYPE].[NAME] + ')',
			'8C9D2A3A-2F18-45CE-B059-33A98C1EA148',
			2,
			0,
			[BLCONTACTTYPE].[NAME]
	FROM	[deleted]
			INNER JOIN [inserted] ON [deleted].[CONTACTTYPEEXTID] = [inserted].[CONTACTTYPEEXTID]
			INNER JOIN [BLLICENSETYPECLASS] ON [deleted].[OBJTYPEID] = [BLLICENSETYPEID] 
			INNER JOIN [BLLICENSETYPE] ON [BLLICENSETYPE].[BLLICENSETYPEID] = [BLLICENSETYPECLASS].[BLLICENSETYPEID]
			INNER JOIN [BLLICENSECLASS] ON [deleted].[OBJCLASSID] = [BLLICENSECLASS].[BLLICENSECLASSID]
			INNER JOIN [BLCONTACTTYPE] WITH (NOLOCK) ON [deleted].[BLCONTACTTYPEID] = [BLCONTACTTYPE].[BLCONTACTTYPEID]
	WHERE	ISNULL([deleted].[CONTACTTYPEGROUP],'') <> ISNULL([inserted].[CONTACTTYPEGROUP],'')
	UNION ALL
	SELECT DISTINCT
			[ILLICENSETYPE].[ILLICENSETYPEID],
			[ILLICENSETYPE].[ROWVERSION],
			GETUTCDATE(),
			[ILLICENSETYPE].[LASTCHANGEDBY],
			'Required Flag',
			CASE [deleted].[ISREQUIRED] WHEN 1 THEN 'Yes' ELSE 'No' END,
			CASE [inserted].[ISREQUIRED] WHEN 1 THEN 'Yes' ELSE 'No' END,
			'Professional License Type (' + [ILLICENSETYPE].[NAME] + '), Contact Type (' + [BLCONTACTTYPE].[NAME] + ')',
			'67978C16-D720-4F8E-8120-E00FBB732A77',
			2,
			0,
			[BLCONTACTTYPE].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CONTACTTYPEEXTID] = [inserted].[CONTACTTYPEEXTID]
			INNER JOIN [ILLICENSETYPE] ON [ILLICENSETYPE].[ILLICENSETYPEID] =  [deleted].[OBJTYPEID] 
			INNER JOIN [ILLICENSECLASSIFICATION] ON [deleted].[OBJCLASSID] = [ILLICENSECLASSIFICATION].[ILLICENSECLASSIFICATIONID]
			INNER JOIN [BLCONTACTTYPE] WITH (NOLOCK) ON [deleted].[BLCONTACTTYPEID] = [BLCONTACTTYPE].[BLCONTACTTYPEID]
	WHERE	[deleted].[ISREQUIRED] <> [inserted].[ISREQUIRED]
	UNION ALL
	SELECT DISTINCT
			[ILLICENSETYPE].[ILLICENSETYPEID],
			[ILLICENSETYPE].[ROWVERSION],
			GETUTCDATE(),
			[ILLICENSETYPE].[LASTCHANGEDBY],
			'Default Online Contact Type Flag',
			CASE [deleted].[ISDEFAULTONLINECONTACTTYPE] WHEN 1 THEN 'Yes' ELSE 'No' END,
			CASE [inserted].[ISDEFAULTONLINECONTACTTYPE] WHEN 1 THEN 'Yes' ELSE 'No' END,
			'Professional License Type (' + [ILLICENSETYPE].[NAME] + '), Contact Type (' + [BLCONTACTTYPE].[NAME] + ')',
			'67978C16-D720-4F8E-8120-E00FBB732A77',
			2,
			0,
			[BLCONTACTTYPE].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[CONTACTTYPEEXTID] = [inserted].[CONTACTTYPEEXTID]
			INNER JOIN [ILLICENSETYPE] ON [ILLICENSETYPE].[ILLICENSETYPEID] =  [deleted].[OBJTYPEID] 
			INNER JOIN [ILLICENSECLASSIFICATION] ON [deleted].[OBJCLASSID] = [ILLICENSECLASSIFICATION].[ILLICENSECLASSIFICATIONID]
			INNER JOIN [BLCONTACTTYPE] WITH (NOLOCK) ON [deleted].[BLCONTACTTYPEID] = [BLCONTACTTYPE].[BLCONTACTTYPEID]
	WHERE	[deleted].[ISDEFAULTONLINECONTACTTYPE] <> [inserted].[ISDEFAULTONLINECONTACTTYPE]
	UNION ALL
	SELECT DISTINCT
			[ILLICENSETYPE].[ILLICENSETYPEID],
			[ILLICENSETYPE].[ROWVERSION],
			GETUTCDATE(),
			[ILLICENSETYPE].[LASTCHANGEDBY],
			'Set',
			CASE WHEN [deleted].[CONTACTTYPEGROUP] IS NULL THEN '[none]' ELSE CONVERT(NVARCHAR(MAX), [deleted].[CONTACTTYPEGROUP]) END,
			CASE WHEN [inserted].[CONTACTTYPEGROUP] IS NULL THEN '[none]' ELSE CONVERT(NVARCHAR(MAX), [inserted].[CONTACTTYPEGROUP]) END,			
			'Professional License Type (' + [ILLICENSETYPE].[NAME] + '), Contact Type (' + [BLCONTACTTYPE].[NAME] + ')',
			'67978C16-D720-4F8E-8120-E00FBB732A77',
			2,
			0,
			[BLCONTACTTYPE].[NAME]
	FROM	[deleted]
			INNER JOIN [inserted] ON [deleted].[CONTACTTYPEEXTID] = [inserted].[CONTACTTYPEEXTID]
			INNER JOIN [ILLICENSETYPE] ON [ILLICENSETYPE].[ILLICENSETYPEID] =  [deleted].[OBJTYPEID] 
			INNER JOIN [ILLICENSECLASSIFICATION] ON [deleted].[OBJCLASSID] = [ILLICENSECLASSIFICATION].[ILLICENSECLASSIFICATIONID]
			INNER JOIN [BLCONTACTTYPE] WITH (NOLOCK) ON [deleted].[BLCONTACTTYPEID] = [BLCONTACTTYPE].[BLCONTACTTYPEID]
	WHERE	ISNULL([deleted].[CONTACTTYPEGROUP],'') <> ISNULL([inserted].[CONTACTTYPEGROUP],'')
END