CREATE TABLE [dbo].[BLEXTAMENDMENT] (
    [BLEXTAMENDMENTID]          CHAR (36) NOT NULL,
    [BLGLOBALENTITYEXTENSIONID] CHAR (36) NOT NULL,
    [AMENDMENTID]               CHAR (36) NOT NULL,
    [CREATEDBY]                 CHAR (36) NULL,
    [CREATEDATE]                DATETIME  NULL,
    CONSTRAINT [PK_BLEXTAMENDMENT] PRIMARY KEY CLUSTERED ([BLEXTAMENDMENTID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_BLEXTAMEND_AMENDMENT] FOREIGN KEY ([AMENDMENTID]) REFERENCES [dbo].[AMENDMENT] ([AMENDMENTID]),
    CONSTRAINT [FK_BLEXTAMEND_BLEXT] FOREIGN KEY ([BLGLOBALENTITYEXTENSIONID]) REFERENCES [dbo].[BLGLOBALENTITYEXTENSION] ([BLGLOBALENTITYEXTENSIONID]),
    CONSTRAINT [FK_BLEXTAMEND_CREATEDBY] FOREIGN KEY ([CREATEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);

