CREATE TABLE [dbo].[BLEXTHOLD] (
    [BLEXTHOLDID]               CHAR (36)      NOT NULL,
    [BLGLOBALENTITYEXTENSIONID] CHAR (36)      NOT NULL,
    [HOLDSETUPID]               CHAR (36)      NULL,
    [COMMENTS]                  NVARCHAR (MAX) NULL,
    [SUSERGUID]                 CHAR (36)      NULL,
    [CREATEDDATE]               DATETIME       NULL,
    [ORIGIN]                    CHAR (36)      NULL,
    [ORIGINNUMBER]              NVARCHAR (150) NULL,
    [EFFECTIVEENDDATE]          DATETIME       NULL,
    [ACTIVE]                    BIT            CONSTRAINT [DF_BLEXTHOLD_ACTIVE] DEFAULT ((1)) NOT NULL,
    [HOLDSEVERITYID]            INT            DEFAULT ((1)) NOT NULL,
    [ORIGINCMCODECASEID]        CHAR (36)      NULL,
    CONSTRAINT [PK_BLEXTHOLD] PRIMARY KEY CLUSTERED ([BLEXTHOLDID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_BLEXTHOLD_ENT] FOREIGN KEY ([BLGLOBALENTITYEXTENSIONID]) REFERENCES [dbo].[BLGLOBALENTITYEXTENSION] ([BLGLOBALENTITYEXTENSIONID]),
    CONSTRAINT [FK_BLEXTHOLD_HOLD] FOREIGN KEY ([HOLDSETUPID]) REFERENCES [dbo].[HOLDTYPESETUPS] ([HOLDSETUPID]),
    CONSTRAINT [FK_BLEXTHOLD_HoldSeverity] FOREIGN KEY ([HOLDSEVERITYID]) REFERENCES [dbo].[HOLDSEVERITY] ([HOLDSEVERITYID]),
    CONSTRAINT [FK_BLEXTHold_OriginCodeCase] FOREIGN KEY ([ORIGINCMCODECASEID]) REFERENCES [dbo].[CMCODECASE] ([CMCODECASEID]),
    CONSTRAINT [FK_BLEXTHOLD_USER] FOREIGN KEY ([SUSERGUID]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);


GO
CREATE NONCLUSTERED INDEX [IX_BLEXTHOLD_BLEXTHOLDID]
    ON [dbo].[BLEXTHOLD]([BLGLOBALENTITYEXTENSIONID] ASC)
    INCLUDE([BLEXTHOLDID]) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_BLEXTHOLDID_ORIGINCMCODECASEID]
    ON [dbo].[BLEXTHOLD]([ORIGINCMCODECASEID] ASC);

