CREATE TABLE [dbo].[BLEXTCOMPANYTYPEMODULE] (
    [BLEXTCOMPANYTYPEMODULEID] INT            NOT NULL,
    [NAME]                     NVARCHAR (100) NOT NULL,
    CONSTRAINT [PK_BusinessLicenseExtensionCompanyTypeModule] PRIMARY KEY CLUSTERED ([BLEXTCOMPANYTYPEMODULEID] ASC)
);

