CREATE TABLE [dbo].[BLGLOBALENTITYEXTENSIONCODECASEXREF] (
    [BLGLOBALENTITYEXTENSIONCODECASEXREFID] CHAR (36) NOT NULL,
    [BLGLOBALENTITYEXTENSIONID]             CHAR (36) NOT NULL,
    [CMCODECASEID]                          CHAR (36) NOT NULL,
    CONSTRAINT [PK_BLGlobalEntityExtensionCodeCaseXRef] PRIMARY KEY CLUSTERED ([BLGLOBALENTITYEXTENSIONCODECASEXREFID] ASC),
    CONSTRAINT [FK_GlobalEntityExtensionXRef] FOREIGN KEY ([BLGLOBALENTITYEXTENSIONID]) REFERENCES [dbo].[BLGLOBALENTITYEXTENSION] ([BLGLOBALENTITYEXTENSIONID]),
    CONSTRAINT [FK_GlobalEntityExtensionXRefCodeCase] FOREIGN KEY ([CMCODECASEID]) REFERENCES [dbo].[CMCODECASE] ([CMCODECASEID])
);


GO
CREATE NONCLUSTERED INDEX [IX_BLGLOBALENTITYEXTENSIONCODECASEXREF_BLGLOBALENTITYEXTENSIONID]
    ON [dbo].[BLGLOBALENTITYEXTENSIONCODECASEXREF]([BLGLOBALENTITYEXTENSIONID] ASC)
    INCLUDE([CMCODECASEID]);


GO
CREATE NONCLUSTERED INDEX [IX_BLGLOBALENTITYEXTENSIONCODECASEXREF_CMCODECASEID]
    ON [dbo].[BLGLOBALENTITYEXTENSIONCODECASEXREF]([CMCODECASEID] ASC);

