CREATE TABLE [dbo].[BLGLOBALENTITYEXTBUSTYPE] (
    [BLGLOBALENTITYEXTBUSTYPEID] CHAR (36) NOT NULL,
    [BLGLOBALENTITYEXTENSIONID]  CHAR (36) NOT NULL,
    [BLEXTBUSINESSTYPEID]        CHAR (36) NOT NULL,
    [MAIN]                       BIT       DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_BLGlobalEntityExtensionBusinessType] PRIMARY KEY CLUSTERED ([BLGLOBALENTITYEXTBUSTYPEID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_BLGlobalEntityExtensionBusinessType_BLExtBusinessType] FOREIGN KEY ([BLEXTBUSINESSTYPEID]) REFERENCES [dbo].[BLEXTBUSINESSTYPE] ([BLEXTBUSINESSTYPEID]),
    CONSTRAINT [FK_BLGlobalEntityExtensionBusinessType_BLGlobalEntityExtension] FOREIGN KEY ([BLGLOBALENTITYEXTENSIONID]) REFERENCES [dbo].[BLGLOBALENTITYEXTENSION] ([BLGLOBALENTITYEXTENSIONID])
);


GO
CREATE NONCLUSTERED INDEX [IX_BLGLBENTITYEXTTYPE_BUS]
    ON [dbo].[BLGLOBALENTITYEXTBUSTYPE]([BLGLOBALENTITYEXTENSIONID] ASC, [BLEXTBUSINESSTYPEID] ASC, [MAIN] ASC) WITH (FILLFACTOR = 90);


GO


CREATE TRIGGER [TG_BLGLOBALENTITYEXTBUSTYPE_DELETE_ELASTIC] ON  [BLGLOBALENTITYEXTBUSTYPE]
   AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [ELASTICSEARCHOBJECT]
    ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID() ,
		[B].[BLGLOBALENTITYEXTENSIONID] ,
        'EnerGovBusiness.BusinessLicense.BusinessLicenseGlobalEntityExtension' ,
        [B].[ROWVERSION] ,
        GETDATE() ,
        NULL ,
        2 ,
        (SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Deleted]
	JOIN [BLGLOBALENTITYEXTENSION] AS [B] WITH (NOLOCK) ON [B].[BLGLOBALENTITYEXTENSIONID] = [Deleted].[BLGLOBALENTITYEXTENSIONID]

END
GO

CREATE TRIGGER [TG_BLGLOBALENTITYEXTBUSTYPE_INSERTUPDATE_ELASTIC] ON  [BLGLOBALENTITYEXTBUSTYPE]
   AFTER INSERT, UPDATE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [ELASTICSEARCHOBJECT]
    ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID() ,
		[B].[BLGLOBALENTITYEXTENSIONID] ,
        'EnerGovBusiness.BusinessLicense.BusinessLicenseGlobalEntityExtension' ,
        [B].[ROWVERSION] ,
        GETDATE() ,
        NULL ,
        2 ,
        (SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Inserted]
	JOIN [BLGLOBALENTITYEXTENSION] AS [B] WITH (NOLOCK) ON [B].[BLGLOBALENTITYEXTENSIONID] = [Inserted].[BLGLOBALENTITYEXTENSIONID]

END