CREATE TABLE [dbo].[BLGLOBALENTITYEXTENSION] (
    [BLGLOBALENTITYEXTENSIONID] CHAR (36)      NOT NULL,
    [DISTRICTID]                CHAR (36)      NOT NULL,
    [GLOBALENTITYID]            CHAR (36)      NULL,
    [BLEXTCOMPANYTYPEID]        CHAR (36)      NOT NULL,
    [BLEXTLOCATIONID]           CHAR (36)      NOT NULL,
    [BLEXTSTATUSID]             CHAR (36)      NOT NULL,
    [EINNUMBER]                 NVARCHAR (11)  NULL,
    [STATETAXNUMBER]            NVARCHAR (20)  NULL,
    [DBA]                       NVARCHAR (100) NULL,
    [REGISTRATIONID]            VARCHAR (50)   NOT NULL,
    [ISCURRENTLYINBUSINESS]     BIT            DEFAULT ((0)) NOT NULL,
    [ROWVERSION]                INT            NOT NULL,
    [LASTCHANGEDON]             DATETIME       DEFAULT (getdate()) NOT NULL,
    [LASTCHANGEDBY]             CHAR (36)      NOT NULL,
    [OPENDATE]                  DATETIME       NULL,
    [CLOSEDATE]                 DATETIME       NULL,
    [LASTAUDITDATE]             DATETIME       NULL,
    [DESCRIPTION]               NVARCHAR (MAX) NULL,
    [IMPORTCUSTOMFIELDLAYOUTID] CHAR (36)      NULL,
    [SSN]                       NVARCHAR (256) NULL,
    [COMPANYNAME]               NVARCHAR (100) NULL,
    [EMAIL]                     NVARCHAR (250) NULL,
    [BUSINESSPHONE]             NVARCHAR (50)  NULL,
    [ISSUEDDATE]                DATETIME       NULL,
    CONSTRAINT [PK_BLGlobalEntityExtension] PRIMARY KEY CLUSTERED ([BLGLOBALENTITYEXTENSIONID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_BLExtension_GlobalEntity] FOREIGN KEY ([GLOBALENTITYID]) REFERENCES [dbo].[GLOBALENTITY] ([GLOBALENTITYID]),
    CONSTRAINT [FK_BLGLBEntExt_CompType] FOREIGN KEY ([BLEXTCOMPANYTYPEID]) REFERENCES [dbo].[BLEXTCOMPANYTYPE] ([BLEXTCOMPANYTYPEID]),
    CONSTRAINT [FK_BLGlobalEntExt_BLExtStatus] FOREIGN KEY ([BLEXTSTATUSID]) REFERENCES [dbo].[BLEXTSTATUS] ([BLEXTSTATUSID]),
    CONSTRAINT [FK_BLGlobalEntExt_District] FOREIGN KEY ([DISTRICTID]) REFERENCES [dbo].[DISTRICT] ([DISTRICTID]),
    CONSTRAINT [FK_BLGlobalEntExt_ExtLocation] FOREIGN KEY ([BLEXTLOCATIONID]) REFERENCES [dbo].[BLEXTLOCATION] ([BLEXTLOCATIONID]),
    CONSTRAINT [FK_BLGlobalEntExt_Users] FOREIGN KEY ([LASTCHANGEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID]),
    CONSTRAINT [FK_BLGlobalEntityExtension_CustomField] FOREIGN KEY ([IMPORTCUSTOMFIELDLAYOUTID]) REFERENCES [dbo].[CUSTOMFIELDLAYOUT] ([GCUSTOMFIELDLAYOUTS])
);


GO
CREATE NONCLUSTERED INDEX [IX_BLGLOBALENTITYEXTENSION_ENT]
    ON [dbo].[BLGLOBALENTITYEXTENSION]([GLOBALENTITYID] ASC);


GO
CREATE NONCLUSTERED INDEX [IMPORT1]
    ON [dbo].[BLGLOBALENTITYEXTENSION]([REGISTRATIONID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IX_BLGLOBALENTITYEXTENSION_LASTCHANGEDON]
    ON [dbo].[BLGLOBALENTITYEXTENSION]([LASTCHANGEDON] ASC)
    INCLUDE([BLGLOBALENTITYEXTENSIONID]);


GO
CREATE NONCLUSTERED INDEX [IX_BLGLOBALENTITYEXTENSION_BLEXTCOMPANYTYPEID]
    ON [dbo].[BLGLOBALENTITYEXTENSION]([BLEXTCOMPANYTYPEID] ASC);


GO


CREATE TRIGGER [TG_BLGLOBALENTITYEXTENSION_UPDATE_ELASTIC] ON  BLGLOBALENTITYEXTENSION
   AFTER UPDATE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [ELASTICSEARCHOBJECT]
    ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID() ,
		[Inserted].[BLGLOBALENTITYEXTENSIONID] ,
        'EnerGovBusiness.BusinessLicense.BusinessLicenseGlobalEntityExtension' ,
        [Inserted].[ROWVERSION] ,
        GETDATE() ,
        NULL ,
        2 ,
        (SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Inserted];

END
GO



CREATE TRIGGER [TG_BLGLOBALENTITYEXTENSION_INSERTUPDATE_ELASTIC_BL] ON  [BLGLOBALENTITYEXTENSION]
   AFTER INSERT, UPDATE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [ELASTICSEARCHOBJECT]
    ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID() ,
		[B].[BLLICENSEID] ,
        'EnerGovBusiness.BusinessLicense.BusinessLicense' ,
        [B].[ROWVERSION] ,
        GETDATE() ,
        NULL ,
        2 ,
        (SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Inserted]
	JOIN [BLLICENSE] AS [B] WITH (NOLOCK) ON [B].[BLGLOBALENTITYEXTENSIONID] = [Inserted].[BLGLOBALENTITYEXTENSIONID]

END
GO


CREATE TRIGGER [TG_BLGLOBALENTITYEXTENSION_DELETE_ELASTIC] ON  BLGLOBALENTITYEXTENSION
   AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [ELASTICSEARCHOBJECT]
    ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID() ,
		[Deleted].[BLGLOBALENTITYEXTENSIONID] ,
        'EnerGovBusiness.BusinessLicense.BusinessLicenseGlobalEntityExtension' ,
        [Deleted].[ROWVERSION] ,
        GETDATE() ,
        NULL ,
        3 ,
        (SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Deleted];

END
GO

CREATE TRIGGER [TG_BLGLOBALENTITYEXTENSION_INSERT_ELASTIC] ON  BLGLOBALENTITYEXTENSION
   AFTER INSERT
AS 
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [ELASTICSEARCHOBJECT]
    ( [ELASTICSEARCHOBJECTID] ,
        [OBJECTID] ,
        [OBJECTCLASSNAME] ,
        [ROWVERSION] ,
        [CREATEDATE] ,
        [PROCESSEDDATE] ,
        [OBJECTACTION] ,
        [INDEXNAME]
    )
	SELECT
		NEWID() ,
		[Inserted].[BLGLOBALENTITYEXTENSIONID] ,
        'EnerGovBusiness.BusinessLicense.BusinessLicenseGlobalEntityExtension' ,
        [Inserted].[ROWVERSION] ,
        GETDATE() ,
        NULL ,
        1 ,
        (SELECT STRINGVALUE FROM SETTINGS WITH (NOLOCK) WHERE NAME = 'ServiceBusTenant')
	FROM [Inserted];

END