CREATE TABLE [dbo].[BLGLOBALENTITYEXTENSIONPARENTC] (
    [BLGLOBALENTITYEXTPARENTCHILDID] CHAR (36) NOT NULL,
    [BLGLOBALENTITYEXTPARENTID]      CHAR (36) NOT NULL,
    [BLGLOBALENTITYEXTENSIONCHILDID] CHAR (36) NOT NULL,
    CONSTRAINT [PK_BLGlobalEntityExtensionParentChild] PRIMARY KEY CLUSTERED ([BLGLOBALENTITYEXTPARENTCHILDID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_BLGlobalEntityExtension_Child] FOREIGN KEY ([BLGLOBALENTITYEXTENSIONCHILDID]) REFERENCES [dbo].[BLGLOBALENTITYEXTENSION] ([BLGLOBALENTITYEXTENSIONID]),
    CONSTRAINT [FK_BLGlobalEntityExtension_Parent] FOREIGN KEY ([BLGLOBALENTITYEXTPARENTID]) REFERENCES [dbo].[BLGLOBALENTITYEXTENSION] ([BLGLOBALENTITYEXTENSIONID])
);

