CREATE TABLE [dbo].[BLLICENSETYPEMODULE] (
    [BLLICENSETYPEMODULEID] INT            NOT NULL,
    [NAME]                  NVARCHAR (100) NOT NULL,
    CONSTRAINT [PK_BLLicenseTypeModule] PRIMARY KEY CLUSTERED ([BLLICENSETYPEMODULEID] ASC)
);

