CREATE TABLE [dbo].[BLLICENSEALLOWEDACTIVITY] (
    [BLLICENSEALLOWEDACTIVITYID] CHAR (36) NOT NULL,
    [BLLICENSETYPEID]            CHAR (36) NOT NULL,
    [BLLICENSEACTIVITYTYPEID]    CHAR (36) NOT NULL,
    CONSTRAINT [PK_BLLicenseAllowedActivity] PRIMARY KEY CLUSTERED ([BLLICENSEALLOWEDACTIVITYID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_BLAllowedAct_BLActType] FOREIGN KEY ([BLLICENSEACTIVITYTYPEID]) REFERENCES [dbo].[BLLICENSEACTIVITYTYPE] ([BLLICENSEACTIVITYTYPEID]),
    CONSTRAINT [FK_BLAllowedAct_BLType] FOREIGN KEY ([BLLICENSETYPEID]) REFERENCES [dbo].[BLLICENSETYPE] ([BLLICENSETYPEID])
);


GO
CREATE NONCLUSTERED INDEX [IX_BLLICENSEALLOWEDACTIVITY_BLLICENSETYPEID]
    ON [dbo].[BLLICENSEALLOWEDACTIVITY]([BLLICENSETYPEID] ASC);


GO

CREATE TRIGGER [dbo].[TG_BLLICENSEALLOWEDACTIVITY_DELETE]  ON  [dbo].[BLLICENSEALLOWEDACTIVITY]
   AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
	(
		[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
	)
	SELECT
		[BLLICENSETYPE].[BLLICENSETYPEID],
		[BLLICENSETYPE].[ROWVERSION],
		GETUTCDATE(),			
		(SELECT dbo.UFN_GET_USERID_FROM_CONTEXT_INFO()),
		'Business License Type Allowed License Activity Deleted',
        '',
        '',       
		'Business License Type (' + [BLLICENSETYPE].[NAME] + '), Allowed License Activity Type (' + [BLLICENSEACTIVITYTYPE].[NAME] +')',
		'8C9D2A3A-2F18-45CE-B059-33A98C1EA148',
		3,
		0,
		[BLLICENSEACTIVITYTYPE].[NAME]
    FROM [deleted]
	INNER JOIN [BLLICENSETYPE] ON [BLLICENSETYPE].[BLLICENSETYPEID] = [deleted].[BLLICENSETYPEID]
	INNER JOIN [BLLICENSEACTIVITYTYPE] WITH (NOLOCK) ON [BLLICENSEACTIVITYTYPE].[BLLICENSEACTIVITYTYPEID] = [deleted].[BLLICENSEACTIVITYTYPEID]
END
GO

CREATE TRIGGER [dbo].[TG_BLLICENSEALLOWEDACTIVITY_INSERT] ON  [dbo].[BLLICENSEALLOWEDACTIVITY]
   AFTER INSERT
AS 
BEGIN	
	SET NOCOUNT ON;	
	INSERT INTO [HISTORYSYSTEMSETUP]
    (
        [ID],
        [ROWVERSION],
        [CHANGEDON],
        [CHANGEDBY],
        [FIELDNAME],
        [OLDVALUE],
        [NEWVALUE],
        [ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT 
        [BLLICENSETYPE].[BLLICENSETYPEID], 
        [BLLICENSETYPE].[ROWVERSION],
        GETUTCDATE(),
        [BLLICENSETYPE].[LASTCHANGEDBY],	
        'Business License Type Allowed License Activity Added',
        '',
        '',       
		'Business License Type (' + [BLLICENSETYPE].[NAME] + '), Allowed License Activity Type (' + [BLLICENSEACTIVITYTYPE].[NAME] +')',
		'8C9D2A3A-2F18-45CE-B059-33A98C1EA148',
		1,
		0,
		[BLLICENSEACTIVITYTYPE].[NAME]
    FROM [inserted]
	INNER JOIN [BLLICENSETYPE] ON [BLLICENSETYPE].[BLLICENSETYPEID] = [inserted].[BLLICENSETYPEID]
	INNER JOIN [BLLICENSEACTIVITYTYPE] WITH (NOLOCK) ON [BLLICENSEACTIVITYTYPE].[BLLICENSEACTIVITYTYPEID] = [inserted].[BLLICENSEACTIVITYTYPEID]
END