CREATE TABLE [dbo].[BLLICENSEREQUIREDFIELD] (
    [BLREQUIREDCUSTOMFIELD] CHAR (36) NOT NULL,
    [BLLICENSETYPECLASSID]  CHAR (36) NOT NULL,
    [GCUSTOMFIELD]          CHAR (36) NOT NULL,
    [SORTORDER]             INT       NULL,
    CONSTRAINT [PK_BLREQUIREDCUSTOMFIELD] PRIMARY KEY CLUSTERED ([BLREQUIREDCUSTOMFIELD] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_BLREQUIREDFIELD_CLASS] FOREIGN KEY ([BLLICENSETYPECLASSID]) REFERENCES [dbo].[BLLICENSETYPECLASS] ([BLLICENSETYPECLASSID]),
    CONSTRAINT [FK_BLREQUIREDFIELD_CUSTOMFIELD] FOREIGN KEY ([GCUSTOMFIELD]) REFERENCES [dbo].[CUSTOMFIELD] ([GCUSTOMFIELD])
);


GO
CREATE NONCLUSTERED INDEX [IX_BLLICENSEREQUIREDFIELD_BLLICENSETYPECLASSID]
    ON [dbo].[BLLICENSEREQUIREDFIELD]([BLLICENSETYPECLASSID] ASC);


GO

CREATE TRIGGER [dbo].[TG_BLLICENSEREQUIREDFIELD_UPDATE]   ON  [dbo].[BLLICENSEREQUIREDFIELD] 
   AFTER UPDATE
AS 
BEGIN	
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
    (	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT 
			[BLLICENSETYPE].[BLLICENSETYPEID],
			[BLLICENSETYPE].[ROWVERSION],
			GETUTCDATE(),			
			[BLLICENSETYPE].[LASTCHANGEDBY],
			'Sort Order',			
			CASE WHEN [deleted].[SORTORDER] IS NULL THEN '[none]' ELSE CONVERT(NVARCHAR(MAX), [deleted].[SORTORDER]) END,
			CASE WHEN [inserted].[SORTORDER] IS NULL THEN '[none]' ELSE CONVERT(NVARCHAR(MAX), [inserted].[SORTORDER]) END,		
			'Business License Type (' + [BLLICENSETYPE].[NAME] + '), Required Renewal Field Name (' + (CASE WHEN [CUSTOMFIELD].[SFIELDNAME]='' OR  [CUSTOMFIELD].[SFIELDNAME] IS NULL THEN [CUSTOMFIELD].SCUSTOMFIELD ELSE [CUSTOMFIELD].[SFIELDNAME]  END) +')',
			'8C9D2A3A-2F18-45CE-B059-33A98C1EA148',
			2,
			0,
			(CASE WHEN [CUSTOMFIELD].[SFIELDNAME]='' OR  [CUSTOMFIELD].[SFIELDNAME] IS NULL THEN [CUSTOMFIELD].SCUSTOMFIELD ELSE [CUSTOMFIELD].[SFIELDNAME]  END) 
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[BLREQUIREDCUSTOMFIELD] = [inserted].[BLREQUIREDCUSTOMFIELD]			
			INNER JOIN [BLLICENSETYPECLASS] ON [BLLICENSETYPECLASS].[BLLICENSETYPECLASSID] = [deleted].[BLLICENSETYPECLASSID]
			INNER JOIN [BLLICENSETYPE] ON [BLLICENSETYPE].[BLLICENSETYPEID] = [BLLICENSETYPECLASS].[BLLICENSETYPEID]
			INNER JOIN [CUSTOMFIELD] WITH (NOLOCK) ON [CUSTOMFIELD].[GCUSTOMFIELD] = [deleted].[GCUSTOMFIELD]		
	WHERE	ISNULL([deleted].[SORTORDER],'') <> ISNULL([inserted].[SORTORDER],'')
END
GO

CREATE TRIGGER [dbo].[TG_BLLICENSEREQUIREDFIELD_INSERT] ON  [dbo].[BLLICENSEREQUIREDFIELD]
   AFTER INSERT
AS 
BEGIN	
	SET NOCOUNT ON;	
	INSERT INTO [HISTORYSYSTEMSETUP]
    (
        [ID],
        [ROWVERSION],
        [CHANGEDON],
        [CHANGEDBY],
        [FIELDNAME],
        [OLDVALUE],
        [NEWVALUE],
        [ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT 
        [BLLICENSETYPE].[BLLICENSETYPEID], 
        [BLLICENSETYPE].[ROWVERSION],
        GETUTCDATE(),
        [BLLICENSETYPE].[LASTCHANGEDBY],	
        'Business License Type Required Renewal Field Added',
        '',
        '',       
		'Business License Type (' + [BLLICENSETYPE].[NAME] + '), Required Renewal Field Name (' + (CASE WHEN [CUSTOMFIELD].[SFIELDNAME]='' OR  [CUSTOMFIELD].[SFIELDNAME] IS NULL THEN [CUSTOMFIELD].SCUSTOMFIELD ELSE [CUSTOMFIELD].[SFIELDNAME]  END) +')',
		'8C9D2A3A-2F18-45CE-B059-33A98C1EA148',
		1,
		0,
		(CASE WHEN [CUSTOMFIELD].[SFIELDNAME]='' OR  [CUSTOMFIELD].[SFIELDNAME] IS NULL THEN [CUSTOMFIELD].SCUSTOMFIELD ELSE [CUSTOMFIELD].[SFIELDNAME]  END) 
    FROM [inserted]
	INNER JOIN [BLLICENSETYPECLASS] ON [BLLICENSETYPECLASS].[BLLICENSETYPECLASSID] = [inserted].[BLLICENSETYPECLASSID]
	INNER JOIN [BLLICENSETYPE] ON [BLLICENSETYPE].[BLLICENSETYPEID] = [BLLICENSETYPECLASS].[BLLICENSETYPEID]
	INNER JOIN [CUSTOMFIELD] WITH (NOLOCK) ON [CUSTOMFIELD].[GCUSTOMFIELD] = [inserted].[GCUSTOMFIELD]
END
GO

CREATE TRIGGER [dbo].[TG_BLLICENSEREQUIREDFIELD_DELETE]  ON  [dbo].[BLLICENSEREQUIREDFIELD]
   AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
	(
		[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
	)
	SELECT
		[BLLICENSETYPE].[BLLICENSETYPEID],
		[BLLICENSETYPE].[ROWVERSION],
		GETUTCDATE(),			
		(SELECT dbo.UFN_GET_USERID_FROM_CONTEXT_INFO()),
		'Business License Type Required Renewal Field Deleted',
        '',
        '',       
		'Business License Type (' + [BLLICENSETYPE].[NAME] + '), Required Renewal Field Name (' + (CASE WHEN [CUSTOMFIELD].[SFIELDNAME]='' OR  [CUSTOMFIELD].[SFIELDNAME] IS NULL THEN [CUSTOMFIELD].SCUSTOMFIELD ELSE [CUSTOMFIELD].[SFIELDNAME]  END) +')',
		'8C9D2A3A-2F18-45CE-B059-33A98C1EA148',
		3,
		0,
		(CASE WHEN [CUSTOMFIELD].[SFIELDNAME]='' OR  [CUSTOMFIELD].[SFIELDNAME] IS NULL THEN [CUSTOMFIELD].SCUSTOMFIELD ELSE [CUSTOMFIELD].[SFIELDNAME]  END) 
    FROM [deleted]
	INNER JOIN [BLLICENSETYPECLASS] ON [BLLICENSETYPECLASS].[BLLICENSETYPECLASSID] = [deleted].[BLLICENSETYPECLASSID]
	INNER JOIN [BLLICENSETYPE] ON [BLLICENSETYPE].[BLLICENSETYPEID] = [BLLICENSETYPECLASS].[BLLICENSETYPEID]
	INNER JOIN [CUSTOMFIELD] WITH (NOLOCK) ON [CUSTOMFIELD].[GCUSTOMFIELD] = [deleted].[GCUSTOMFIELD]
END