CREATE TABLE [dbo].[BLLICENSECAPAPPLICATIONTYPE] (
    [BLLICENSECAPAPPLICATIONTYPEID] INT           NOT NULL,
    [NAME]                          NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_BLLicenseCAPApplicationType] PRIMARY KEY CLUSTERED ([BLLICENSECAPAPPLICATIONTYPEID] ASC) WITH (FILLFACTOR = 90)
);

