CREATE TABLE [dbo].[BLLICENSEWFACTIONSTEP] (
    [BLLICENSEWFACTIONSTEPID]    CHAR (36)       NOT NULL,
    [BLLICENSEWFSTEPID]          CHAR (36)       NOT NULL,
    [WFACTIONTYPEID]             INT             NOT NULL,
    [DESCRIPTION]                NVARCHAR (MAX)  NULL,
    [PRIORITYORDER]              INT             NOT NULL,
    [STARTDATE]                  DATETIME        NULL,
    [ENDDATE]                    DATETIME        NULL,
    [ROWVERSION]                 INT             NOT NULL,
    [LASTCHANGEDON]              DATETIME        NOT NULL,
    [LASTCHANGEDBY]              CHAR (36)       NOT NULL,
    [WORKFLOWSTATUSID]           INT             NOT NULL,
    [LOCATION]                   NVARCHAR (50)   NULL,
    [EXPECTEDDURATIONHOURS]      DECIMAL (6, 2)  NULL,
    [EVENTDATE]                  DATETIME        NULL,
    [NAME]                       NVARCHAR (100)  NOT NULL,
    [HEARINGTYPEID]              CHAR (36)       NULL,
    [PASSDESCRIPTION]            NVARCHAR (30)   NOT NULL,
    [FAILDESCRIPTION]            NVARCHAR (30)   NOT NULL,
    [ALLOWREDO]                  BIT             NOT NULL,
    [REDODESCRIPTION]            NVARCHAR (30)   NULL,
    [ICON]                       VARBINARY (MAX) NULL,
    [DAYSTOCOMPLETE]             INT             NULL,
    [PLSUBMITTALTYPEID]          CHAR (36)       NULL,
    [MEETINGTYPEID]              CHAR (36)       NULL,
    [PLPLANWFPARENTACTIONSTEPID] CHAR (36)       NULL,
    [VERSIONNUMBER]              INT             NULL,
    [SORTORDER]                  INT             NOT NULL,
    [GENERALREASON]              NVARCHAR (MAX)  NULL,
    [AUTORECEIVE]                BIT             NOT NULL,
    [AUTOCOMPLETED]              BIT             NOT NULL,
    [WORKFLOWCOMPLETETYPEID]     INT             NULL,
    [IMINSPECTIONTYPEID]         CHAR (36)       NULL,
    [PMPERMITTYPEID]             CHAR (36)       NULL,
    [PMPERMITWORKCLASSID]        CHAR (36)       NULL,
    [BLLICENSETYPEID]            CHAR (36)       NULL,
    [BLLICENSECLASSID]           CHAR (36)       NULL,
    [RPTREPORTID]                CHAR (36)       NULL,
    [PLPLANTYPEID]               CHAR (36)       NULL,
    [PLPLANWORKCLASSID]          CHAR (36)       NULL,
    [BLLICENSEACTIVITYTYPEID]    CHAR (36)       NULL,
    [TASKTYPEID]                 CHAR (36)       NULL,
    [NOPRIORITY]                 BIT             DEFAULT ((0)) NOT NULL,
    [DUEDATE]                    DATETIME        NULL,
    [EXAMTYPEID]                 CHAR (36)       NULL,
    [CAFEETEMPLATEID]            CHAR (36)       NULL,
    [ISAUTOINVOICE]              BIT             CONSTRAINT [DF_BLLICENSEWFACTIONSTEP_ISAUTOINVOICE] DEFAULT ((0)) NOT NULL,
    [ISREQUIREDFULLPAYMNENT]     BIT             CONSTRAINT [DF_BLLICENSEWFACTIONSTEP_ISREQUIRED] DEFAULT ((0)) NOT NULL,
    [PARENTINSPECTIONNUMBER]     NVARCHAR (50)   NULL,
    [COMPUTEFEEACTIONTYPEID]     INT             DEFAULT ((0)) NULL,
    [ISUSEACTIONDATEASFEEDATE]   BIT             DEFAULT ((0)) NOT NULL,
    [ISCOMPUTEMAINFEETEMPLATE]   BIT             DEFAULT ((0)) NOT NULL,
    [INSPECTIONSET]              INT             CONSTRAINT [DF_BLLICENSEWFACTIONSTEP_SET] DEFAULT ((0)) NOT NULL,
    [CMCASETYPEID]               CHAR (36)       NULL,
    [IDENTITYCOLUMN]             BIGINT          IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_BLLicenseWFActionStep] PRIMARY KEY NONCLUSTERED ([BLLICENSEWFACTIONSTEPID] ASC),
    CONSTRAINT [FK_BLACTSTEP_CMCASETYPE] FOREIGN KEY ([CMCASETYPEID]) REFERENCES [dbo].[CMCASETYPE] ([CMCASETYPEID]),
    CONSTRAINT [FK_BLLicActionStep_BLLicStep] FOREIGN KEY ([BLLICENSEWFSTEPID]) REFERENCES [dbo].[BLLICENSEWFSTEP] ([BLLICENSEWFSTEPID]),
    CONSTRAINT [FK_BLLICENSEACTSTEP_EXAMTYPE] FOREIGN KEY ([EXAMTYPEID]) REFERENCES [dbo].[EXAMTYPE] ([EXAMTYPEID]),
    CONSTRAINT [FK_BLLicenseActStep_TaskType] FOREIGN KEY ([TASKTYPEID]) REFERENCES [dbo].[TASKTYPE] ([TASKTYPEID]),
    CONSTRAINT [FK_BLLicenseWFActionStep_BLLicenseClass] FOREIGN KEY ([BLLICENSECLASSID]) REFERENCES [dbo].[BLLICENSECLASS] ([BLLICENSECLASSID]),
    CONSTRAINT [FK_BLLicenseWFActionStep_BLLicenseType] FOREIGN KEY ([BLLICENSETYPEID]) REFERENCES [dbo].[BLLICENSETYPE] ([BLLICENSETYPEID]),
    CONSTRAINT [FK_BLLICENSEWFACTIONSTEP_CAFEETEMPLATE] FOREIGN KEY ([CAFEETEMPLATEID]) REFERENCES [dbo].[CAFEETEMPLATE] ([CAFEETEMPLATEID]),
    CONSTRAINT [FK_BLLicWFActStep_BLActStep] FOREIGN KEY ([PLPLANWFPARENTACTIONSTEPID]) REFERENCES [dbo].[BLLICENSEWFACTIONSTEP] ([BLLICENSEWFACTIONSTEPID]),
    CONSTRAINT [FK_BLLicWFActStep_HearType] FOREIGN KEY ([HEARINGTYPEID]) REFERENCES [dbo].[HEARINGTYPE] ([HEARINGTYPEID]),
    CONSTRAINT [FK_BLLicWFActStep_IMInspectType] FOREIGN KEY ([IMINSPECTIONTYPEID]) REFERENCES [dbo].[IMINSPECTIONTYPE] ([IMINSPECTIONTYPEID]),
    CONSTRAINT [FK_BLLicWFActStep_MeetType] FOREIGN KEY ([MEETINGTYPEID]) REFERENCES [dbo].[MEETINGTYPE] ([MEETINGTYPEID]),
    CONSTRAINT [FK_BLLicWFActStep_PLSubType] FOREIGN KEY ([PLSUBMITTALTYPEID]) REFERENCES [dbo].[PLSUBMITTALTYPE] ([PLSUBMITTALTYPEID]),
    CONSTRAINT [FK_BLLicWFActStep_PLType] FOREIGN KEY ([PLPLANTYPEID]) REFERENCES [dbo].[PLPLANTYPE] ([PLPLANTYPEID]),
    CONSTRAINT [FK_BLLicWFActStep_RPTReport] FOREIGN KEY ([RPTREPORTID]) REFERENCES [dbo].[RPTREPORT] ([RPTREPORTID]),
    CONSTRAINT [FK_BLLicWFActStep_Users] FOREIGN KEY ([LASTCHANGEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID]),
    CONSTRAINT [FK_BLLicWFActStep_WFActType] FOREIGN KEY ([WFACTIONTYPEID]) REFERENCES [dbo].[WFACTIONTYPE] ([WFACTIONTYPEID]),
    CONSTRAINT [FK_BLLicWFActStep_WFCompType] FOREIGN KEY ([WORKFLOWCOMPLETETYPEID]) REFERENCES [dbo].[WORKFLOWCOMPLETETYPE] ([WORKFLOWCOMPLETETYPEID]),
    CONSTRAINT [FK_BLLicWFActStep_WFStatus] FOREIGN KEY ([WORKFLOWSTATUSID]) REFERENCES [dbo].[WORKFLOWSTATUS] ([WORKFLOWSTATUSID]),
    CONSTRAINT [FK_BLWFACT_ACTIONTYPEID] FOREIGN KEY ([COMPUTEFEEACTIONTYPEID]) REFERENCES [dbo].[WFACTIONSYSTEMTYPE] ([WFACTIONSYSTEMTYPEID]),
    CONSTRAINT [FK_BLWFActStep_BLActType] FOREIGN KEY ([BLLICENSEACTIVITYTYPEID]) REFERENCES [dbo].[BLLICENSEACTIVITYTYPE] ([BLLICENSEACTIVITYTYPEID]),
    CONSTRAINT [FK_BLWFActStep_PLWorkClass] FOREIGN KEY ([PLPLANWORKCLASSID]) REFERENCES [dbo].[PLPLANWORKCLASS] ([PLPLANWORKCLASSID]),
    CONSTRAINT [FK_BLWFActStep_PMType] FOREIGN KEY ([PMPERMITTYPEID]) REFERENCES [dbo].[PMPERMITTYPE] ([PMPERMITTYPEID]),
    CONSTRAINT [FK_BLWFActStep_PMWorkClass] FOREIGN KEY ([PMPERMITWORKCLASSID]) REFERENCES [dbo].[PMPERMITWORKCLASS] ([PMPERMITWORKCLASSID])
);


GO
CREATE CLUSTERED INDEX [CLIDX_BLLICWFACTSTEP_IDCOL]
    ON [dbo].[BLLICENSEWFACTIONSTEP]([IDENTITYCOLUMN] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_BLLICENSEACTSTEP_STEP]
    ON [dbo].[BLLICENSEWFACTIONSTEP]([BLLICENSEWFSTEPID] ASC, [BLLICENSEWFACTIONSTEPID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_BLLICENSEWFACTIONSTEP_BLLICENSETYPEID]
    ON [dbo].[BLLICENSEWFACTIONSTEP]([BLLICENSETYPEID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_BLLICENSEWFACTIONSTEP_WORKFLOWSTATUSID]
    ON [dbo].[BLLICENSEWFACTIONSTEP]([WORKFLOWSTATUSID] ASC)
    INCLUDE([BLLICENSEWFACTIONSTEPID], [VERSIONNUMBER]);


GO
CREATE NONCLUSTERED INDEX [PLPLANWFPARENTACTIONSTEPID_IDX]
    ON [dbo].[BLLICENSEWFACTIONSTEP]([PLPLANWFPARENTACTIONSTEPID] ASC);

