CREATE TABLE [dbo].[BLLICENSENOTE] (
    [BLLICENSENOTEID] CHAR (36)      NOT NULL,
    [BLLICENSEID]     CHAR (36)      NOT NULL,
    [TEXT]            NVARCHAR (MAX) NULL,
    [CREATEDBY]       CHAR (36)      NULL,
    [CREATEDDATE]     DATETIME       NULL,
    [TITLE]           VARCHAR (50)   NULL,
    [PIN]             BIT            DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_BLLicenseNote] PRIMARY KEY CLUSTERED ([BLLICENSENOTEID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_BLLicenseNote_BLLicense] FOREIGN KEY ([BLLICENSEID]) REFERENCES [dbo].[BLLICENSE] ([BLLICENSEID]),
    CONSTRAINT [FK_BLLicenseNote_Users] FOREIGN KEY ([CREATEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);

