CREATE TABLE [dbo].[BLLICENSESTATUSSYSTEM] (
    [BLLICENSESTATUSSYSTEMID] INT           NOT NULL,
    [NAME]                    NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_BLLicenseStatusSystem] PRIMARY KEY CLUSTERED ([BLLICENSESTATUSSYSTEMID] ASC) WITH (FILLFACTOR = 90)
);

