CREATE TABLE [dbo].[BUFIELD] (
    [BUFIELDID]     CHAR (36)      NOT NULL,
    [BUSERVICEID]   CHAR (36)      NOT NULL,
    [CONTROLTYPE]   INT            NOT NULL,
    [FIELDTYPE]     INT            NOT NULL,
    [FIELDNAME]     NVARCHAR (MAX) NOT NULL,
    [FRIENDLYNAME]  NVARCHAR (100) NOT NULL,
    [VALUE]         NVARCHAR (500) NOT NULL,
    [ISCUSTOMFIELD] BIT            NOT NULL,
    CONSTRAINT [PK_BUFIELD] PRIMARY KEY CLUSTERED ([BUFIELDID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_BUFIELD_BUSERVICE] FOREIGN KEY ([BUSERVICEID]) REFERENCES [dbo].[BUSERVICE] ([BUSERVICEID])
);

