CREATE TABLE [dbo].[BULKREQUEST] (
    [BULKREQUESTID] CHAR (36)      NOT NULL,
    [BULKOBJECT]    NVARCHAR (MAX) NOT NULL,
    [REQUESTDATE]   DATETIME       NOT NULL,
    CONSTRAINT [PK_BULKUPDATEREQUEST] PRIMARY KEY NONCLUSTERED ([BULKREQUESTID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_BULKUPDATEREQUEST_REQUESTDATE]
    ON [dbo].[BULKREQUEST]([REQUESTDATE] ASC);

