CREATE TABLE [dbo].[BUMETADATA] (
    [BUMETADATAID] CHAR (36)      NOT NULL,
    [ENTITY]       INT            NOT NULL,
    [FIELDLABEL]   NVARCHAR (100) NOT NULL,
    [FIELDNAME]    NVARCHAR (250) NOT NULL,
    [CONTROLTYPE]  INT            NOT NULL,
    [FIELDTYPE]    INT            NOT NULL,
    CONSTRAINT [PK_BUMETADATA] PRIMARY KEY CLUSTERED ([BUMETADATAID] ASC) WITH (FILLFACTOR = 90)
);

