CREATE PROCEDURE [dbo].[USP_WORKFLOWACTIONPARAMETER_DELETE]
(
	@WORKFLOWACTIONPARAMETERID CHAR(36)
)
AS
DELETE FROM [dbo].[WORKFLOWACTIONPARAMETER]
WHERE [WORKFLOWACTIONPARAMETERID] = @WORKFLOWACTIONPARAMETERID