CREATE PROCEDURE [dbo].[USP_WORKFLOWACTIONSETCALENDARDUEDA_UPDATE]
(
	@WORKFLOWACTIONSETCALEDUEDTID CHAR(36),
	@WORKFLOWACTIONID CHAR(36),
	@SETVALUEFIELD NVARCHAR(MAX),
	@SETVALUEFIELDFRIENDLYNAME NVARCHAR(50)
)
AS
DECLARE @OUTPUTTABLE as TABLE([WORKFLOWACTIONSETCALEDUEDTID]  char(36))
	UPDATE [dbo].[WORKFLOWACTIONSETCALENDARDUEDA] SET
		   [SETVALUEFIELD] = @SETVALUEFIELD,
		   [SETVALUEFIELDFRIENDLYNAME] = @SETVALUEFIELDFRIENDLYNAME
	OUTPUT inserted.[WORKFLOWACTIONSETCALEDUEDTID] INTO @OUTPUTTABLE
	WHERE
		[WORKFLOWACTIONSETCALEDUEDTID] = @WORKFLOWACTIONSETCALEDUEDTID AND
		[WORKFLOWACTIONID] = @WORKFLOWACTIONID

SELECT * FROM @OUTPUTTABLE