CREATE PROCEDURE [dbo].[USP_WORKWEEK_UPDATE]
(
	@DAYOFWEEK INT,
	@STARTTIME DATETIME,
	@ENDTIME DATETIME,
	@ISWORKINGDAY BIT,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS

DECLARE @OUTPUTTABLE AS TABLE([ROWVERSION]  INT)
UPDATE	[dbo].[WORKWEEK]
SET		[STARTTIME] = @STARTTIME,
		[ENDTIME] = @ENDTIME,
		[ISWORKINGDAY] = @ISWORKINGDAY,
		[LASTCHANGEDBY] = @LASTCHANGEDBY,
		[LASTCHANGEDON] = @LASTCHANGEDON,
		[ROWVERSION] = @ROWVERSION + 1
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE
	[DAYOFWEEK] = @DAYOFWEEK AND
	[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE