CREATE PROCEDURE [dbo].[USP_WORKFLOW_INSERT]
(
	@WORKFLOWID CHAR(36),
	@MODULEID INT,
	@WORKFLOWNAME NVARCHAR(50),
	@ROOTCLASSNAME NVARCHAR(MAX),
	@LASTCHANGEDON DATETIME,
	@LASTCHANGEDBY CHAR(36),
	@ISSERVER BIT,
	@ISCLIENT BIT,
	@WORKFLOWDESCRIPTION NVARCHAR(MAX),
	@ISENABLED BIT,
	@ISPOSTPROCESS BIT,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
INSERT INTO [dbo].[WORKFLOW](
	[WORKFLOWID],
	[MODULEID],
	[WORKFLOWNAME],
	[ROOTCLASSNAME],
	[LASTCHANGEDON],
	[LASTCHANGEDBY],
	[ISSERVER],
	[ISCLIENT],
	[WORKFLOWDESCRIPTION],
	[ISENABLED],
	[ISPOSTPROCESS],
	[ROWVERSION]
)
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
VALUES
(
	@WORKFLOWID,
	@MODULEID,
	@WORKFLOWNAME,
	@ROOTCLASSNAME,
	@LASTCHANGEDON,
	@LASTCHANGEDBY,
	@ISSERVER,
	@ISCLIENT,
	@WORKFLOWDESCRIPTION,
	@ISENABLED,
	@ISPOSTPROCESS,
	@ROWVERSION
)
SELECT * FROM @OUTPUTTABLE