CREATE PROCEDURE [dbo].[USP_WORKFLOWACTION_INSERT]
(
	@WORKFLOWACTIONID CHAR(36),
	@WORKFLOWID CHAR(36),
	@WORKFLOWACTIONTYPEID INT,
	@ACTIONNAME NVARCHAR(50),
	@CUSTOMMESSAGE NVARCHAR(MAX),
	@ACTIONCLASSNAME NVARCHAR(MAX),
	@RUNONLYWHENDIRTY BIT,
	@DISABLEQUEUING BIT,
	@POSTWORKFLOW BIT	
)
AS
INSERT INTO [dbo].[WORKFLOWACTION](
	[WORKFLOWACTIONID],
	[WORKFLOWID],
	[WORKFLOWACTIONTYPEID],
	[ACTIONNAME],
	[CUSTOMMESSAGE],
	[ACTIONCLASSNAME],
	[RUNONLYWHENDIRTY],
	[DISABLEQUEUING],
	[POSTWORKFLOW]
)

VALUES
(
	@WORKFLOWACTIONID,
	@WORKFLOWID,
	@WORKFLOWACTIONTYPEID,
	@ACTIONNAME,
	@CUSTOMMESSAGE,
	@ACTIONCLASSNAME,
	@RUNONLYWHENDIRTY,
	@DISABLEQUEUING,
	@POSTWORKFLOW	
)