CREATE PROCEDURE [dbo].[USP_WORKFLOWACTIONHOLDTYPE_INSERT]
(
	@WORKFLOWACTIONHOLDTYPEID CHAR(36),
	@WORKFLOWACTIONID CHAR(36),
	@HOLDSETUPID CHAR(36),
	@COMMENTS NVARCHAR(MAX)
)
AS
DECLARE @OUTPUTTABLE as TABLE([WORKFLOWACTIONHOLDTYPEID]  char(36))
INSERT INTO [dbo].[WORKFLOWACTIONHOLDTYPE](
	[WORKFLOWACTIONHOLDTYPEID],
	[WORKFLOWACTIONID],
	[HOLDSETUPID],
	[COMMENTS]
)
OUTPUT inserted.[WORKFLOWACTIONHOLDTYPEID] INTO @OUTPUTTABLE
VALUES
(
	@WORKFLOWACTIONHOLDTYPEID,
	@WORKFLOWACTIONID,
	@HOLDSETUPID,
	@COMMENTS
)
SELECT * FROM @OUTPUTTABLE