CREATE PROCEDURE [dbo].[USP_WORKFLOWACTIONMAILMERGETMPL_INSERT]
(
	@WORKFLOWACTIONMAILMERGETMPLID CHAR(36),
	@WORKFLOWACTIONID CHAR(36),
	@MAILMERGETEMPLATEID CHAR(36)	
)
AS

INSERT INTO [dbo].[WORKFLOWACTIONMAILMERGETMPL](
	[WORKFLOWACTIONMAILMERGETMPLID],
	[WORKFLOWACTIONID],
	[MAILMERGETEMPLATEID]
)
VALUES(
	@WORKFLOWACTIONMAILMERGETMPLID,
	@WORKFLOWACTIONID,
	@MAILMERGETEMPLATEID
)