CREATE PROCEDURE [dbo].[USP_WORKFLOWACTIONSETVALUE_INSERT]
(
	@WORKFLOWACTIONSETVALUEID CHAR(36),
	@WORKFLOWACTIONID CHAR(36),
	@SETVALUEFIELD NVARCHAR(MAX),
	@SETVALUEFIELDFRIENDLYNAME NVARCHAR(50),
	@SETVALUEFIELDVALUE NVARCHAR(MAX),
	@SETVALUEFIELDADJUSTMENTVALUE NVARCHAR(MAX),
	@SETVALUEWEEKDAYSONLY BIT,
	@SETVALUEUSEPREVIOUSWEEKDAY BIT
)
AS
DECLARE @OUTPUTTABLE as TABLE([WORKFLOWACTIONSETVALUEID]  char(36))
INSERT INTO [dbo].[WORKFLOWACTIONSETVALUE](
	[WORKFLOWACTIONSETVALUEID],
	[WORKFLOWACTIONID],
	[SETVALUEFIELD],
	[SETVALUEFIELDFRIENDLYNAME],
	[SETVALUEFIELDVALUE],
	[SETVALUEFIELDADJUSTMENTVALUE],
	[SETVALUEWEEKDAYSONLY],
	[SETVALUEUSEPREVIOUSWEEKDAY]
)
OUTPUT inserted.[WORKFLOWACTIONSETVALUEID] INTO @OUTPUTTABLE
VALUES
(
	@WORKFLOWACTIONSETVALUEID,
	@WORKFLOWACTIONID,
	@SETVALUEFIELD,
	@SETVALUEFIELDFRIENDLYNAME,
	@SETVALUEFIELDVALUE,
	@SETVALUEFIELDADJUSTMENTVALUE,
	@SETVALUEWEEKDAYSONLY,
	@SETVALUEUSEPREVIOUSWEEKDAY
)
SELECT * FROM @OUTPUTTABLE