CREATE PROCEDURE [dbo].[USP_WFTEMPLATESTEPACTION_INSERT]
(
	@WFTEMPLATESTEPACTIONID CHAR(36),
	@WFTEMPLATESTEPID CHAR(36),
	@WFACTIONID CHAR(36),
	@PRIORITYORDER INT,
	@SORTORDER INT,
	@AUTORECEIVE BIT,
	@AUTOFILL BIT,
	@NOPRIORITY BIT,
	@ISCAPOPTIONALINSPECTION BIT,
	@INSPECTIONSET INT
)
AS

INSERT INTO [dbo].[WFTEMPLATESTEPACTION](
	[WFTEMPLATESTEPACTIONID],
	[WFTEMPLATESTEPID],
	[WFACTIONID],
	[PRIORITYORDER],
	[SORTORDER],
	[AUTORECEIVE],
	[AUTOFILL],
	[NOPRIORITY],
	[ISCAPOPTIONALINSPECTION],
	[INSPECTIONSET]
)

VALUES
(
	@WFTEMPLATESTEPACTIONID,
	@WFTEMPLATESTEPID,
	@WFACTIONID,
	@PRIORITYORDER,
	@SORTORDER,
	@AUTORECEIVE,
	@AUTOFILL,
	@NOPRIORITY,
	@ISCAPOPTIONALINSPECTION,
	@INSPECTIONSET
)