CREATE PROCEDURE [dbo].[USP_WORKFLOWCONDITION_DELETE_BYPARENTID]
(
	@WORKFLOWID CHAR(36),
	@WORKFLOWCONDITIONGROUPID CHAR(36)
	
)
AS
DELETE [dbo].[WORKFLOWCONDITION] FROM [dbo].[WORKFLOWCONDITION]
INNER JOIN [dbo].[WORKFLOWCONDITIONGROUP] ON [dbo].[WORKFLOWCONDITION].[WORKFLOWCONDITIONGROUPID] =  [dbo].[WORKFLOWCONDITIONGROUP].[WORKFLOWCONDITIONGROUPID]
WHERE
	(@WORKFLOWCONDITIONGROUPID IS NULL OR [dbo].[WORKFLOWCONDITION].[WORKFLOWCONDITIONGROUPID] = @WORKFLOWCONDITIONGROUPID) AND
	(@WORKFLOWID IS NULL OR [dbo].[WORKFLOWCONDITIONGROUP].[WORKFLOWID] = @WORKFLOWID)