CREATE PROCEDURE [dbo].[USP_WORKFLOWACTIONFTP_DELETE_BYPARENTID]
(
    @WORKFLOWID CHAR(36),
    @WORKFLOWACTIONID CHAR(36)
)
AS
DELETE [dbo].[WORKFLOWACTIONFTP] FROM [dbo].[WORKFLOWACTIONFTP]
INNER JOIN [dbo].[WORKFLOWACTION] ON [dbo].[WORKFLOWACTIONFTP].[WORKFLOWACTIONID] =  [dbo].[WORKFLOWACTION].[WORKFLOWACTIONID]
WHERE
	(@WORKFLOWID IS NULL OR [dbo].[WORKFLOWACTION].[WORKFLOWID]= @WORKFLOWID) 
    AND (@WORKFLOWACTIONID IS NULL OR [dbo].[WORKFLOWACTIONFTP].[WORKFLOWACTIONID] = @WORKFLOWACTIONID)