CREATE PROCEDURE [dbo].[USP_WFACTIONGROUPACTIONXREF_DELETE]
(
@WFACTIONGROUPACTIONXREFID CHAR(36)
)
AS
DELETE FROM [dbo].[WFACTIONGROUPACTIONXREF]
WHERE
	[WFACTIONGROUPACTIONXREFID] = @WFACTIONGROUPACTIONXREFID