CREATE PROCEDURE [energovshell].[USP_SUBMENUS_GETBY_USERID]
(
	@USERID CHAR(36)
)
AS
BEGIN	
    SET NOCOUNT ON;
	SELECT 
			[dbo].[FORMSUBCATEGORYSUBMENUXREF].[FKFORMSUBCATEGORYID] AS [FORMSUBCATEGORYID],
			[dbo].[SUBMENUS].[SSUBMENUGUID] AS [SUBMENUID]
	FROM	[dbo].[FORMSUBCATEGORYSUBMENUXREF] WITH (NOLOCK) 
		JOIN	[dbo].[ROLESUBMENUXREF] WITH (NOLOCK) ON [dbo].[ROLESUBMENUXREF].[FKSUBMENUID] = [dbo].[FORMSUBCATEGORYSUBMENUXREF].[FKSUBMENUID]
		JOIN    [dbo].[SUBMENUS] WITH (NOLOCK) ON [dbo].[SUBMENUS].[SSUBMENUGUID] = [dbo].[ROLESUBMENUXREF].[FKSUBMENUID]
		JOIN	[dbo].[ROLES] WITH (NOLOCK) ON [dbo].[ROLES].[SROLEGUID] = [dbo].[ROLESUBMENUXREF].[FKROLEID]
		JOIN	[dbo].[USERS] WITH (NOLOCK) ON [dbo].[USERS].[SROLEID] = [dbo].[ROLES].[SROLEGUID]
	WHERE	[dbo].[ROLESUBMENUXREF].[BVISIBLE] = 1 AND [dbo].[USERS].[SUSERGUID] = @USERID
END