CREATE PROCEDURE [energovshell].[USP_FORMCATEGORY_GETBY_USERID]
(
	@USERID CHAR(36)
)
AS
BEGIN	
    SET NOCOUNT ON;
	SELECT DISTINCT
			[dbo].[FORMCATEGORY].[NAME] AS [CATEGORYNAME],
			[dbo].[FORMCATEGORY].[FORMCATEGORYID] AS [CATEGORYID],
			[dbo].[FORMCATEGORY].[DISPLAYORDER] AS [CATEGORYDISPLAYORDER],
			[dbo].[FORMCATEGORY].[DISPLAYLABEL] AS [CATEGORYDISPLAYLABEL],
			[dbo].[FORMCATEGORY].[ISADMIN]  AS [CATEGORYISADMIN]
	FROM	[dbo].[FORMCATEGORY] WITH (NOLOCK) 
		JOIN	[dbo].[FORMCATEGORYFORMSUBCATEGORYXREF]  WITH (NOLOCK) ON [dbo].[FORMCATEGORY].[FORMCATEGORYID] = [dbo].[FORMCATEGORYFORMSUBCATEGORYXREF].[FKFORMCATEGORYID]
		JOIN	[dbo].[FORMSUBCATEGORY] WITH (NOLOCK) ON [dbo].[FORMSUBCATEGORY].[FORMSUBCATEGORYID] = [dbo].[FORMCATEGORYFORMSUBCATEGORYXREF].[FKFORMSUBCATEGORYID]
		JOIN	[dbo].[FORMSUBCATEGORYSUBMENUXREF] WITH (NOLOCK) ON [dbo].[FORMSUBCATEGORYSUBMENUXREF].[FKFORMSUBCATEGORYID] = [dbo].[FORMSUBCATEGORY].[FORMSUBCATEGORYID]
		JOIN	[dbo].[ROLESUBMENUXREF] WITH (NOLOCK) ON [dbo].[ROLESUBMENUXREF].[FKSUBMENUID] = [dbo].[FORMSUBCATEGORYSUBMENUXREF].[FKSUBMENUID]
		JOIN    [dbo].[SUBMENUS] WITH (NOLOCK) ON [dbo].[SUBMENUS].[SSUBMENUGUID] = [dbo].[ROLESUBMENUXREF].[FKSUBMENUID]
		JOIN	[dbo].[ROLES] WITH (NOLOCK) ON [dbo].[ROLES].[SROLEGUID] = [dbo].[ROLESUBMENUXREF].[FKROLEID]
		JOIN	[dbo].[USERS] WITH (NOLOCK) ON [dbo].[USERS].[SROLEID] = [dbo].[ROLES].[SROLEGUID]
	WHERE	[dbo].[ROLESUBMENUXREF].[BVISIBLE] = 1 AND [dbo].[USERS].[SUSERGUID] = @USERID

	EXEC [energovshell].[USP_FORMSUBCATEGORY_GETBY_USERID] @USERID
	EXEC [energovshell].[USP_SUBMENUS_GETBY_USERID] @USERID
	EXEC [energovshell].[USP_ENERGOVFORMS_GETBY_USERID] @USERID
END