CREATE PROCEDURE [dbo].[ADDERPORTALUSERMAILINGADDRESS]
-- Add the parameters for the stored procedure here
@MAILINGADDRESSID char(36),
@ADDRESSLINE1 nvarchar(200),
@ADDRESSLINE2 nvarchar(200),
@UNITORSUITE nvarchar(20),
@STREETTYPE nvarchar(50),
@CITY nvarchar(50),
@COUNTY nvarchar(50),
@STATE nvarchar(50),
@POSTALCODE nvarchar(50),
@COUNTRYTYPE int,
@LASTCHANGEDON datetime,
@LASTCHANGEDBY char(36)
AS
BEGIN		
	INSERT INTO MAILINGADDRESS 	
	(
	MAILINGADDRESSID,
	ADDRESSID,
	ADDRESSLINE1,
	ADDRESSLINE2,
	UNITORSUITE,
	STREETTYPE,
	CITY,
	COUNTY,
	STATE,
	POSTALCODE,
	COUNTRYTYPE,
	LASTCHANGEDON,
	LASTCHANGEDBY,
	ROWVERSION	
	)
	VALUES(
	@MAILINGADDRESSID,
	NULL,
	@ADDRESSLINE1,
	@ADDRESSLINE2,
	@UNITORSUITE,
	@STREETTYPE,
	@CITY,
	@COUNTY,
	@STATE,
	@POSTALCODE,
	@COUNTRYTYPE,
	@LASTCHANGEDON,
	@LASTCHANGEDBY,
	1	
	)		
END
