

CREATE PROCEDURE [dbo].[rpt_AM_Asset_Listing_By_Salvage_Date_Reports]
@STARTDATE AS DATETIME,
@ENDDATE AS DATETIME
AS
SET @ENDDATE = DATEADD(S,-1,DATEADD(D,1,@ENDDATE))
SELECT     AM.ASSETNO AS AssetNo, AM.NAME AS AssetName, AM.DESCRIPTION AS Description, AM.SERIALNO AS SerialNo, 
                      AM.PURCHASEDATE AS PurchaseDate, AM.PURCHASEVALUE AS PurchaseValue, AM.SALVAGEDATE AS SalvageDate, 
                      AM.SALVAGEVALUE AS SalvageValue, AM.YEARSOFUSEFULLIFE AS YearsOfUsefulLife, DEPARTMENT.NAME AS Department, 
                      AMASSETCLASS.NAME AS AssetClass, AMASSETTYPE.NAME AS AssetType,
                      (		SELECT			AMASSETSTATUS.NAME
							FROM			AMASSETSTATUS INNER JOIN
												AMASSET ON AMASSETSTATUS.AMASSETSTATUSID = AMASSET.AMASSETSTATUSID
							WHERE AMASSET.AMASSETID = AM.AMASSETID) AS Status
FROM         AMASSET AS AM INNER JOIN
                      AMASSETCLASS ON AM.AMASSETCLASSID = AMASSETCLASS.AMASSETCLASSID INNER JOIN
                      AMASSETTYPE ON AM.AMASSETTYPEID = AMASSETTYPE.AMASSETTYPEID INNER JOIN
                      DEPARTMENT ON AM.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
WHERE AM.SALVAGEDATE BETWEEN @STARTDATE AND @ENDDATE

