CREATE PROCEDURE [dbo].[USP_ATTACHMENTGROUPTCMXREF_DELETE]
(
	@ATTACHMENTGROUPTCMXREFID CHAR(36),
	@ROWVERSION INT
)
AS
DELETE FROM [dbo].[ATTACHMENTGROUPTCMXREF]
WHERE
	[ATTACHMENTGROUPTCMXREFID] = @ATTACHMENTGROUPTCMXREFID AND 
	[ROWVERSION]= @ROWVERSION