CREATE PROCEDURE [dbo].[USP_AUTONUMBERSETTINGS_GETBYID_SELECT]
(
@CLASSNAME CHAR(250)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[CLASSNAME],
	[FORMATSTRING],
	[PADWITHZEROSTOLENGTH],
	[NEXTVALUE],
	[USERESET],
	[LASTRESET]
FROM [dbo].[AUTONUMBERSETTINGS] (NOLOCK) 
	WHERE [dbo].[AUTONUMBERSETTINGS].[CLASSNAME]=@CLASSNAME
END