CREATE PROCEDURE [dbo].[USP_ATTACHMENTGROUP_UPDATE]
(
	@ATTACHMENTGROUPID CHAR(36),
	@NAME NVARCHAR(100),
	@DESCRIPTION NVARCHAR(250),
	@AVAILINPERMIT BIT,
	@AVAILINPLAN BIT,
	@AVAILINCODE BIT,
	@AVAILINCRM BIT,
	@AVAILINPROJECT BIT,
	@AVAILINWORKORDER BIT,
	@AVAILINASSET BIT,
	@AVAILININVOICE BIT,
	@AVAILINPAYMENT BIT,
	@AVAILININSPECTION BIT,
	@AVAILINCONTACT BIT,
	@AVAILINBUSINESSLICENSE BIT,
	@AVAILINBUSINESS BIT,
	@AVAILINPROLICENSE BIT,
	@AVAILINEXAMSITTING BIT,
	@AVAILINEXAMREQUEST BIT,
	@AVAILINEXAMLANDLORD BIT,
	@AVAILINEXAMRENTALPROPERTY BIT,
	@AVAILINEXAMTAXREMITTANCE BIT,
	@AVAILINCAP BIT,
	@AVAILINCAPCONTACTS BIT,
	@AVAILINOBJEC BIT,
	@AVAILINIMPACTCASE BIT,
	@AVAILINFIREOCCUPANCY BIT,
	@RECORDEDFILE BIT,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
UPDATE [dbo].[ATTACHMENTGROUP] SET
	[NAME] = @NAME,
	[DESCRIPTION] = @DESCRIPTION,
	[AVAILINPERMIT] = @AVAILINPERMIT,
	[AVAILINPLAN] = @AVAILINPLAN,
	[AVAILINCODE] = @AVAILINCODE,
	[AVAILINCRM] = @AVAILINCRM,
	[AVAILINPROJECT] = @AVAILINPROJECT,
	[AVAILINWORKORDER] = @AVAILINWORKORDER,
	[AVAILINASSET] = @AVAILINASSET,
	[AVAILININVOICE] = @AVAILININVOICE,
	[AVAILINPAYMENT] = @AVAILINPAYMENT,
	[AVAILININSPECTION] = @AVAILININSPECTION,
	[AVAILINCONTACT] = @AVAILINCONTACT,
	[AVAILINBUSINESSLICENSE] = @AVAILINBUSINESSLICENSE,
	[AVAILINBUSINESS] = @AVAILINBUSINESS,
	[AVAILINPROLICENSE] = @AVAILINPROLICENSE,
	[AVAILINEXAMSITTING] = @AVAILINEXAMSITTING,
	[AVAILINEXAMREQUEST] = @AVAILINEXAMREQUEST,
	[AVAILINEXAMLANDLORD] = @AVAILINEXAMLANDLORD,
	[AVAILINEXAMRENTALPROPERTY] = @AVAILINEXAMRENTALPROPERTY,
	[AVAILINEXAMTAXREMITTANCE] = @AVAILINEXAMTAXREMITTANCE,
	[AVAILINCAP] = @AVAILINCAP,
	[AVAILINCAPCONTACTS] = @AVAILINCAPCONTACTS,
	[AVAILINOBJEC] = @AVAILINOBJEC,
	[AVAILINIMPACTCASE] = @AVAILINIMPACTCASE,
	[AVAILINFIREOCCUPANCY] = @AVAILINFIREOCCUPANCY,
	[RECORDEDFILE] = @RECORDEDFILE,
	[LASTCHANGEDBY] = @LASTCHANGEDBY,
	[LASTCHANGEDON] = @LASTCHANGEDON,
	[ROWVERSION] = @ROWVERSION + 1
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE
	[ATTACHMENTGROUPID] = @ATTACHMENTGROUPID AND 
	[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE