CREATE PROCEDURE [dbo].[USP_ATTACHMENTREQFILEREF_INSERT]
(
	@ATTACHMENTREQFILEREFID CHAR(36),
	@NAME NVARCHAR(260),
	@ISREQUIRED BIT,
	@QUANTITY INT,
	@ATTACHMENTGROUPID CHAR(36),
	@OBJECTCLASSID CHAR(36),
	@OBJECTTYPEID CHAR(36)
)
AS

INSERT INTO [dbo].[ATTACHMENTREQFILEREF](
	[ATTACHMENTREQFILEREFID],
	[NAME],
	[ISREQUIRED],
	[QUANTITY],
	[ATTACHMENTGROUPID],
	[OBJECTCLASSID],
	[OBJECTTYPEID]
)

VALUES
(
	@ATTACHMENTREQFILEREFID,
	@NAME,
	@ISREQUIRED,
	@QUANTITY,
	@ATTACHMENTGROUPID,
	@OBJECTCLASSID,
	@OBJECTTYPEID
)