CREATE PROCEDURE [dbo].[USP_ADVANCEDSEARCHOUTPUTFIELD_DELETE]
(
@ADVANCEDSEARCHOUTPUTFIELDID CHAR(36)
)
AS
DELETE FROM [dbo].[ADVANCEDSEARCHOUTPUTFIELD]
WHERE
	[ADVANCEDSEARCHOUTPUTFIELDID] = @ADVANCEDSEARCHOUTPUTFIELDID