CREATE PROCEDURE [dbo].[USP_ADVANCEDSEARCHCRITERIASEARCHFIELD_GETBYPARENTID]
(
	@SEARCHCRITERIAID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[ADVANCEDSEARCHCRITERIASEARCHFIELDID],
	[OPERATORID],
	[SEARCHCRITERIAID],
	[FIELDID],
	[MATCHTYPEID],
	[BITVALUE],
	[STRINGVALUE],
	[FROMVALUE],
	[TOVALUE],
    [STARTDATE],
    [ENDDATE],
	[STRINGVALUES],
	[CUSTOMFIELDID],
	[STARTDATEKEY],
	[ENDDATEKEY],
	[SEARCHTYPEID],
	[CUSTOMFIELDTABLEID]
FROM [dbo].[ADVANCEDSEARCHCRITERIASEARCHFIELD]
WHERE
	[SEARCHCRITERIAID] = @SEARCHCRITERIAID  

END