CREATE PROCEDURE [dbo].[USP_ADVANCEDSEARCHCRITERIA_UPDATE]
(
	@ADVANCEDSEARCHCRITERIAID CHAR(36),
	@NAME NVARCHAR(100),
	@DESCRIPTION NVARCHAR(MAX),
	@USERID CHAR(36),
	@SHARED BIT,
	@SEARCHMODULE INT,
	@PAGESIZE INT,
	@PAGENUMBER INT,
	@CREATEDON DATETIME,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT,
	@CHILDMODULEPATH NVARCHAR(100)
)
AS
UPDATE [dbo].[ADVANCEDSEARCHCRITERIA] SET
	[ADVANCEDSEARCHCRITERIAID] = @ADVANCEDSEARCHCRITERIAID,
	[NAME] = @NAME,
	[DESCRIPTION] = @DESCRIPTION,
	[USERID] = @USERID,
	[SHARED] = @SHARED,
	[SEARCHMODULE] = @SEARCHMODULE,
	[PAGESIZE] = @PAGESIZE,
	[PAGENUMBER] = @PAGENUMBER,
	[CREATEDON] = @CREATEDON,
	[LASTCHANGEDBY] = @LASTCHANGEDBY,
	[LASTCHANGEDON] = @LASTCHANGEDON,
	[ROWVERSION] = @ROWVERSION + 1,
	[CHILDMODULEPATH] = @CHILDMODULEPATH
OUTPUT inserted.[ROWVERSION]
WHERE
	[ADVANCEDSEARCHCRITERIAID] = @ADVANCEDSEARCHCRITERIAID AND 
	[ROWVERSION]= @ROWVERSION