CREATE PROCEDURE [dbo].[USP_ATTACHMENTREQFILEREF_DELETE_BYPARENTID]
(
@PARENTID CHAR(36),
@BLLICENSECLASSID CHAR(36) = NULL
)
AS
DELETE FROM [dbo].[ATTACHMENTREQFILEREF]
WHERE
	[OBJECTTYPEID] = @PARENTID  
	AND 
	(@BLLICENSECLASSID IS NULL OR [dbo].[ATTACHMENTREQFILEREF].[OBJECTCLASSID] = @BLLICENSECLASSID)