CREATE PROCEDURE [communitydevelopmentsetup].[USP_PMPERMITTYPE_GETBYID]
(
	@PMPERMITTYPEID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[PMPERMITTYPE].[PMPERMITTYPEID],
	[dbo].[PMPERMITTYPE].[PMPERMITTYPEGROUPID],
	[dbo].[PMPERMITTYPE].[NAME],	
	[dbo].[PMPERMITTYPE].[DAYSUNTILEXPIRE],
	[dbo].[PMPERMITTYPE].[ACTIVE],
	[dbo].[PMPERMITTYPE].[UNLIMITED],
	[dbo].[PMPERMITTYPE].[PERMITPREFIX],
	[dbo].[PMPERMITTYPE].[AUTONUMBER],
	[dbo].[PMPERMITTYPE].[LASTNUMBER],
	[dbo].[PMPERMITTYPE].[REPORTNAME],
	[dbo].[PMPERMITTYPE].[COREPORTNAME],
	[dbo].[PMPERMITTYPE].[COCREPORTNAME],
	[dbo].[PMPERMITTYPE].[PERMITCARDREPORTNAME],
	[dbo].[PMPERMITTYPE].[ALLOWINTERNETSUBMISSION],
	[dbo].[PMPERMITTYPE].[COPREFIX],
	[dbo].[PMPERMITTYPE].[REQUIREDPLPLANTYPEID],
	[dbo].[PMPERMITTYPE].[PLANCOMPLETIONBEFOREISSUE],
	[dbo].[PMPERMITTYPE].[PLANCOMPLETIONBEFORECO],
	[dbo].[PMPERMITTYPE].[COMMERCIAL],
	[dbo].[PMPERMITTYPE].[RESIDENTIAL],
	[dbo].[PMPERMITTYPE].[DAYSUNTILEXPIREFROMLASTINSPECT],
	[dbo].[PMPERMITTYPE].[ALLOWISSUEOPENINVOICE],
	[dbo].[PMPERMITTYPE].[ALLOWISSUEUNSATISFIEDCONDITION],
	[dbo].[PMPERMITTYPE].[SCHEDULEINSPECTWITHOUTISSUED],
	[dbo].[PMPERMITTYPE].[SCHEDULEINSPECTWITHOPENINVOICE],
	[dbo].[PMPERMITTYPE].[NOTIFYUSERPERMITONPARCEL],
	[dbo].[PMPERMITTYPE].[DEFAULTPMPERMITSTATUSID],
	[dbo].[PMPERMITTYPE].[TABLENAME],
	[dbo].[PMPERMITTYPE].[FRIENDLYNAME],
	[dbo].[PMPERMITTYPE].[VALUATION],
	[dbo].[PMPERMITTYPE].[SQUAREFEET],
	[dbo].[PMPERMITTYPE].[DEFAULTWEBPMPERMITSTATUSID],
	[dbo].[PMPERMITTYPE].[USEPREFIXASSUFFIX],
	[dbo].[PMPERMITTYPE].[VALIDATESAGSTCERT],
	[dbo].[PMPERMITTYPE].[VALIDATESAGSTPROFILE],
	[dbo].[PMPERMITTYPE].[ALLOWOBJECTASSOCIATION],
	[dbo].[PMPERMITTYPE].[USECASETYPENUMBERING],
	[dbo].[PMPERMITTYPE].[ASSIGNEDUSER],
	[dbo].[PMPERMITTYPE].[LASTCHANGEDBY],
	[dbo].[PMPERMITTYPE].[LASTCHANGEDON],
	[dbo].[PMPERMITTYPE].[ROWVERSION],
	[dbo].[PMPERMITTYPE].[PMPERMITTYPECSSUPLOADSETTINGTYPEID]
FROM [dbo].[PMPERMITTYPE]
WHERE
	[PMPERMITTYPEID] = @PMPERMITTYPEID  

EXEC [communitydevelopmentsetup].[USP_PERMITTYPEWORKCLASS_GETBYPARENTID] @PMPERMITTYPEID
EXEC [communitydevelopmentsetup].[USP_PMPERMITTYPEUNITTYPE_GETBYPARENTID] @PMPERMITTYPEID
EXEC [communitydevelopmentsetup].[USP_PMCONTACTTYPEREF_GETBYPARENTID] @PMPERMITTYPEID
EXEC [communitydevelopmentsetup].[USP_ATTACHMENTREQFILEREF_PMPERMITTYPE_GETBYPARENTID] @PMPERMITTYPEID
EXEC [communitydevelopmentsetup].[USP_PMPERMITTYPEILLICTYPE_GETBYPARENTID] @PMPERMITTYPEID
EXEC [communitydevelopmentsetup].[USP_PMPERMITTYPEILLICTYPEILWC_GETBYPARENTID] @PMPERMITTYPEID
EXEC [communitydevelopmentsetup].[USP_PMPERMITTYPEILLICTYPEILWCT_GETBYPARENTID] @PMPERMITTYPEID

EXEC [communitydevelopmentsetup].[USP_PMPERMITTYPELICENSETYPE_GETBYPARENTID] @PMPERMITTYPEID
EXEC [communitydevelopmentsetup].[USP_PMWCCERTCLASS_GETBYPARENTID] @PMPERMITTYPEID
EXEC [communitydevelopmentsetup].[USP_PMPERMITTYPEBUSLICTYPE_GETBYPARENTID] @PMPERMITTYPEID
EXEC [communitydevelopmentsetup].[USP_PMPERMITTYPEBUSLICTYPEBUSWC_GETBYPARENTID] @PMPERMITTYPEID
EXEC [communitydevelopmentsetup].[USP_PMPERMITALLOWEDACTIVITY_GETBYPARENTID] @PMPERMITTYPEID


END