CREATE PROCEDURE [communitydevelopmentsetup].[USP_PRPROJECTTYPEPLANORDER_GETBYPARENTID]
(
	@PRPROJECTTYPEID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[PRPROJECTTYPEPLANORDER].[PRPROJECTTYPEPLANORDERID],
	[dbo].[PRPROJECTTYPEPLANORDER].[PRPROJECTTYPEID],
	[dbo].[PRPROJECTTYPEPLANORDER].[PLPLANTYPEID],
	[dbo].[PRPROJECTTYPEPLANORDER].[PLPLANWORKCLASSID],
	[dbo].[PRPROJECTTYPEPLANORDER].[PLANORDER],
	[dbo].[PRPROJECTTYPEPLANORDER].[AUTOADD]
FROM [dbo].[PRPROJECTTYPEPLANORDER]
WHERE
	[dbo].[PRPROJECTTYPEPLANORDER].[PRPROJECTTYPEID] = @PRPROJECTTYPEID  

END