CREATE PROCEDURE [communitydevelopmentsetup].[USP_LANDMANAGEMENTCONTACTSYSTEMTYP_GETALL]
AS
BEGIN
	SELECT 
		[dbo].[LANDMANAGEMENTCONTACTSYSTEMTYP].[LANDMANAGEMENTCONTACTSYSTEMTYP],
		[dbo].[LANDMANAGEMENTCONTACTSYSTEMTYP].[NAME]
	FROM  [dbo].[LANDMANAGEMENTCONTACTSYSTEMTYP]
	ORDER BY [dbo].[LANDMANAGEMENTCONTACTSYSTEMTYP].[NAME] ASC
END