CREATE PROCEDURE [communitydevelopmentsetup].[USP_OMOBJECTSTATUSSYSTEM_SELECT_LOOKUP]

AS
	SET NOCOUNT ON;
	SELECT		[dbo].[OMOBJECTSTATUSSYSTEM].[OMOBJECTSTATUSSYSTEMID],
				[dbo].[OMOBJECTSTATUSSYSTEM].[NAME]
	FROM		[dbo].[OMOBJECTSTATUSSYSTEM]
	ORDER BY	[dbo].[OMOBJECTSTATUSSYSTEM].[NAME]