CREATE PROCEDURE [communitydevelopmentsetup].[USP_PMPERMITTYPEBUSLICTYPE_GETBYPARENTID]
(
	@PMPERMITTYPEID CHAR(36)
)
AS
BEGIN
SELECT 
	[dbo].[PMPERMITTYPEBUSLICTYPE].[PMPERMITTYPEBUSLICTYPEID],
	[dbo].[PMPERMITTYPEBUSLICTYPE].[PMPERMITTYPEID],
	[dbo].[PMPERMITTYPEBUSLICTYPE].[PMPERMITWORKCLASSID],
	[dbo].[PMPERMITTYPEBUSLICTYPE].[BLLICENSETYPEID],
	[dbo].[PMPERMITTYPEBUSLICTYPE].[PMPERMITTYPEWORKCLASSID],
	[dbo].[BLLICENSETYPE].[NAME]
FROM [dbo].[PMPERMITTYPEBUSLICTYPE]
INNER JOIN [dbo].[BLLICENSETYPE]
	ON [dbo].[BLLICENSETYPE].[BLLICENSETYPEID] = [dbo].[PMPERMITTYPEBUSLICTYPE].[BLLICENSETYPEID]	
WHERE
	[dbo].[PMPERMITTYPEBUSLICTYPE].[PMPERMITTYPEID] = @PMPERMITTYPEID
ORDER BY [dbo].[BLLICENSETYPE].[NAME]
END