CREATE PROCEDURE [communitydevelopmentsetup].[USP_PLPLANTYPEUNITTYPE_GETBYPARENTID]
(
	@PLPLANTYPEID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[PLPLANTYPEUNITTYPE].[PLPLANTYPEUNITTYPEID],
	[dbo].[PLPLANTYPEUNITTYPE].[PLPLANTYPEID],
	[dbo].[PLPLANTYPEUNITTYPE].[PLPLANWORKCLASSID],
	[dbo].[PLPLANTYPEUNITTYPE].[IPUNITTYPEID],
	[dbo].[PLPLANTYPEUNITTYPE].[ISREQUIRED],
	[dbo].[PLPLANTYPEUNITTYPE].[UNITTYPEGROUP],
	[dbo].[IPUNITTYPE].[NAME]
FROM [dbo].[PLPLANTYPEUNITTYPE]
INNER JOIN [dbo].[IPUNITTYPE] 
	ON [dbo].[IPUNITTYPE].[IPUNITTYPEID] = [dbo].[PLPLANTYPEUNITTYPE].[IPUNITTYPEID]
WHERE
	[dbo].[PLPLANTYPEUNITTYPE].[PLPLANTYPEID] = @PLPLANTYPEID
ORDER BY [dbo].[PLPLANTYPEUNITTYPE].[PLPLANWORKCLASSID], [dbo].[IPUNITTYPE].[NAME]
END