CREATE PROCEDURE [communitydevelopmentsetup].[USP_PLAPPLICATIONSTATUS_SELECT_LOOKUP]

AS
	SET NOCOUNT ON;
	SELECT 
		[dbo].[PLAPPLICATIONSTATUS].[PLAPPLICATIONSTATUSID],
		[dbo].[PLAPPLICATIONSTATUS].[STATUS]
	FROM [dbo].[PLAPPLICATIONSTATUS]
	ORDER BY [dbo].[PLAPPLICATIONSTATUS].[STATUS]
RETURN 0