CREATE PROCEDURE [communitydevelopmentsetup].[USP_IPCASESTATUS_SELECT_LOOKUP]
AS
	SET NOCOUNT ON;
	SELECT 
		[dbo].[IPCASESTATUS].[IPCASESTATUSID],
		[dbo].[IPCASESTATUS].[NAME]
	FROM [dbo].[IPCASESTATUS]
	ORDER BY [dbo].[IPCASESTATUS].[NAME] ASC