CREATE PROCEDURE [communitydevelopmentsetup].[USP_PLAPPLICATIONTYPE_GETBYID]
(
	@PLAPPLICATIONTYPEID AS CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[PLAPPLICATIONTYPE].[PLAPPLICATIONTYPEID],
	[dbo].[PLAPPLICATIONTYPE].[APPLICATIONTYPENAME],
	[dbo].[PLAPPLICATIONTYPE].[DESCRIPTION],
	[dbo].[PLAPPLICATIONTYPE].[CUSTOMFIELDID],
	[dbo].[PLAPPLICATIONTYPE].[DEFAULTAPPLICATIONSTATUSID],
	[dbo].[PLAPPLICATIONTYPE].[PREFIX],
	[dbo].[PLAPPLICATIONTYPE].[ISAUTONUMBER],
	[dbo].[PLAPPLICATIONTYPE].[DEFAULTPERMITTYPE],
	[dbo].[PLAPPLICATIONTYPE].[DEFAULTPLANTYPE],
	[dbo].[PLAPPLICATIONTYPE].[CAFEETEMPLATEID],
	[dbo].[PLAPPLICATIONTYPE].[LASTCHANGEDBY],
	[dbo].[PLAPPLICATIONTYPE].[LASTCHANGEDON],
	[dbo].[PLAPPLICATIONTYPE].[ROWVERSION]
FROM [dbo].[PLAPPLICATIONTYPE]
WHERE [dbo].[PLAPPLICATIONTYPE].[PLAPPLICATIONTYPEID] = @PLAPPLICATIONTYPEID

EXEC [communitydevelopmentsetup].[USP_PLCONTACTTYPEREF_GETBYPARENTID] @PLAPPLICATIONTYPEID

EXEC [communitydevelopmentsetup].[USP_PLAPPLICATIONALLOWEDACTIVITY_GETBYPARENTID] @PLAPPLICATIONTYPEID

END