CREATE PROCEDURE [communitydevelopmentsetup].[USP_PMPERMITSTATUS_GETALL]
AS
BEGIN
	SELECT [dbo].[PMPERMITSTATUS].[PMPERMITSTATUSID],
			[dbo].[PMPERMITSTATUS].[NAME],		
			[dbo].[PMPERMITSTATUS].[HOLDFLAG],
			[dbo].[PMPERMITSTATUS].[DESCRIPTION],
			[dbo].[PMPERMITSTATUS].[COMPLETEDFLAG],
			[dbo].[PMPERMITSTATUS].[ISSUEDFLAG],
			[dbo].[PMPERMITSTATUS].[FAILUREFLAG],
			[dbo].[PMPERMITSTATUS].[CANCELLEDFLAG],
			[dbo].[PMPERMITSTATUS].[DESCRIPTION_SPANISH],
			[dbo].[PMPERMITSTATUS].[LASTCHANGEDBY],
			[dbo].[PMPERMITSTATUS].[LASTCHANGEDON],
			[dbo].[PMPERMITSTATUS].[ROWVERSION]		
	FROM  [dbo].[PMPERMITSTATUS] 
	ORDER BY [dbo].[PMPERMITSTATUS].[NAME] ASC
END