CREATE PROCEDURE [communitydevelopmentsetup].[USP_PMPERMITACTIVITYTYPE_GETALL]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[PMPERMITACTIVITYTYPE].[PMPERMITACTIVITYTYPEID],
	[dbo].[PMPERMITACTIVITYTYPE].[NAME],
	[dbo].[PMPERMITACTIVITYTYPE].[DESCRIPTION],
	[dbo].[PMPERMITACTIVITYTYPE].[CANEDIT],
	[dbo].[PMPERMITACTIVITYTYPE].[PREFIXID],
	[dbo].[PMPERMITACTIVITYTYPE].[ALLOWDUPLICATE],
	[dbo].[PMPERMITACTIVITYTYPE].[CREATEID],
	[dbo].[PMPERMITACTIVITYTYPE].[CUSTOMFIELDID],
	[dbo].[PMPERMITACTIVITYTYPE].[LASTCHANGEDBY],
	[dbo].[PMPERMITACTIVITYTYPE].[LASTCHANGEDON],
	[dbo].[PMPERMITACTIVITYTYPE].[ROWVERSION]
FROM [dbo].[PMPERMITACTIVITYTYPE] ORDER BY [dbo].[PMPERMITACTIVITYTYPE].[NAME]
END