CREATE PROCEDURE [communitydevelopmentsetup].[USP_LANDMANAGEMENTCONTACTTYPE_SEARCH]
(
	@SEARCH AS NVARCHAR(50) = '',
	@PAGE_NUMBER AS INT = 1,
	@PAGE_SIZE AS INT = 10,
	@IS_ASCENDING AS BIT = 1,
	@SYSTEM_TYPE_ID INT = -1
)
AS
WITH RAW_DATA AS (
	SELECT
		[dbo].[LANDMANAGEMENTCONTACTTYPE].[LANDMANAGEMENTCONTACTTYPEID],
		[dbo].[LANDMANAGEMENTCONTACTTYPE].[LANDMANAGEMENTCONTACTSYSTEMTYP],
		[dbo].[LANDMANAGEMENTCONTACTTYPE].[NAME],
		[dbo].[LANDMANAGEMENTCONTACTTYPE].[DESCRIPTION],
		[dbo].[LANDMANAGEMENTCONTACTSYSTEMTYP].[NAME] AS [SYSTEMTYPENAME],
		CASE @IS_ASCENDING WHEN 1 THEN
			ROW_NUMBER() OVER(ORDER BY [dbo].[LANDMANAGEMENTCONTACTTYPE].[NAME])
		ELSE
			ROW_NUMBER() OVER(ORDER BY [dbo].[LANDMANAGEMENTCONTACTTYPE].[NAME] DESC)
		END AS RowNumber,
		COUNT(1) OVER() AS TotalRows
	FROM [dbo].[LANDMANAGEMENTCONTACTTYPE]
	INNER JOIN [dbo].[LANDMANAGEMENTCONTACTSYSTEMTYP] ON [dbo].[LANDMANAGEMENTCONTACTSYSTEMTYP].[LANDMANAGEMENTCONTACTSYSTEMTYP] = [dbo].[LANDMANAGEMENTCONTACTTYPE].[LANDMANAGEMENTCONTACTSYSTEMTYP]
	WHERE ([dbo].[LANDMANAGEMENTCONTACTTYPE].[NAME] LIKE '%'+ @SEARCH +'%') AND 
		(@SYSTEM_TYPE_ID < 0 OR [dbo].[LANDMANAGEMENTCONTACTTYPE].[LANDMANAGEMENTCONTACTSYSTEMTYP] = @SYSTEM_TYPE_ID)
)

SELECT * 
FROM RAW_DATA
WHERE
	RowNumber > @PAGE_SIZE * (@PAGE_NUMBER - 1) AND 
	RowNumber <= @PAGE_SIZE * @PAGE_NUMBER
ORDER BY 
	RowNumber