CREATE PROCEDURE [communitydevelopmentsetup].[USP_PLAPPLICATIONACTIVITYTYPE_GETALL]
AS
BEGIN
SELECT 
	[dbo].[PLAPPLICATIONACTIVITYTYPE].[PLAPPLICATIONACTIVITYTYPEID],
	[dbo].[PLAPPLICATIONACTIVITYTYPE].[NAME],
	[dbo].[PLAPPLICATIONACTIVITYTYPE].[DESCRIPTION],
	[dbo].[PLAPPLICATIONACTIVITYTYPE].[CANEDIT],
	[dbo].[PLAPPLICATIONACTIVITYTYPE].[CREATEID],
	[dbo].[PLAPPLICATIONACTIVITYTYPE].[PREFIXID],
	[dbo].[PLAPPLICATIONACTIVITYTYPE].[ALLOWDUPLICATE],
	[dbo].[PLAPPLICATIONACTIVITYTYPE].[CUSTOMFIELDID],
	[dbo].[PLAPPLICATIONACTIVITYTYPE].[LASTCHANGEDBY],
	[dbo].[PLAPPLICATIONACTIVITYTYPE].[LASTCHANGEDON],
	[dbo].[PLAPPLICATIONACTIVITYTYPE].[ROWVERSION]
FROM [dbo].[PLAPPLICATIONACTIVITYTYPE] ORDER BY [dbo].[PLAPPLICATIONACTIVITYTYPE].[NAME] ASC
END