CREATE PROCEDURE [communitydevelopmentsetup].[USP_IPUNITTYPE_GETALL]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[IPUNITTYPE].[IPUNITTYPEID],
	[dbo].[IPUNITTYPE].[NAME],
	[dbo].[IPUNITTYPE].[DESCRIPTION],
	[dbo].[IPUNITTYPE].[ACTIVE],
	[dbo].[IPUNITTYPE].[IGNOREONIMPACTEDRECORD],
	[dbo].[IPUNITTYPE].[LASTCHANGEDBY],
	[dbo].[IPUNITTYPE].[LASTCHANGEDON],
	[dbo].[IPUNITTYPE].[ROWVERSION]
FROM [dbo].[IPUNITTYPE] ORDER BY [dbo].[IPUNITTYPE].[NAME]
END