CREATE PROCEDURE [communitydevelopmentsetup].[USP_IPCASETYPE_GETALL]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[IPCASETYPE].[IPCASETYPEID],
	[dbo].[IPCASETYPE].[NAME],
	[dbo].[IPCASETYPE].[DESCRIPTION],
	[dbo].[IPCASETYPE].[PREFIX],
	[dbo].[IPCASETYPE].[CUSTOMFIELDLAYOUTID],
	[dbo].[IPCASETYPE].[DEFAULTSTATUSID],
	[dbo].[IPCASETYPE].[DAYSTOCASEAPPROVALEXPIRE],
	[dbo].[IPCASETYPE].[ACTIVE],
	[dbo].[IPCASETYPE].[LASTCHANGEDBY],
	[dbo].[IPCASETYPE].[LASTCHANGEDON],
	[dbo].[IPCASETYPE].[ROWVERSION]
FROM [dbo].[IPCASETYPE]
ORDER BY [dbo].[IPCASETYPE].[NAME]
EXEC [communitydevelopmentsetup].[USP_IPCASEALLOWEDCONTACTTYPE_GETALL]
END