CREATE PROCEDURE [communitydevelopmentsetup].[USP_IPCONDITIONSTATUS_GETALL]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[IPCONDITIONSTATUS].[IPCONDITIONSTATUSID],
	[dbo].[IPCONDITIONSTATUS].[NAME],
	[dbo].[IPCONDITIONSTATUS].[DESCRIPTION],
	[dbo].[IPCONDITIONSTATUS].[IPCONDITIONSYSTEMSTATUSID],
	[dbo].[IPCONDITIONSTATUS].[LASTCHANGEDBY],
	[dbo].[IPCONDITIONSTATUS].[LASTCHANGEDON],
	[dbo].[IPCONDITIONSTATUS].[ROWVERSION]
FROM [dbo].[IPCONDITIONSTATUS] ORDER BY [dbo].[IPCONDITIONSTATUS].[NAME] ASC
END