CREATE PROCEDURE [communitydevelopmentsetup].[USP_PMPERMITVALUATIONGROUP_GETALL]
AS
BEGIN
SET NOCOUNT ON;
	SELECT 
		[dbo].[PMPERMITVALUATIONGROUP].[PMPERMITVALUATIONGROUPID],
		[dbo].[PMPERMITVALUATIONGROUP].[NAME],
		[dbo].[PMPERMITVALUATIONGROUP].[DESCRIPTION],
		[dbo].[PMPERMITVALUATIONGROUP].[LASTCHANGEDBY],
		[dbo].[PMPERMITVALUATIONGROUP].[LASTCHANGEDON],
		[dbo].[PMPERMITVALUATIONGROUP].[ROWVERSION]
	FROM [dbo].[PMPERMITVALUATIONGROUP] ORDER BY [dbo].[PMPERMITVALUATIONGROUP].[NAME] ASC
END