CREATE PROCEDURE [contactmanager].[USP_CONTACT_DUPLICATE_SEARCH]
(
	@FIRSTNAME NVARCHAR(50) = NULL,
	@LASTNAME NVARCHAR(50) = NULL,
	@ISCOMPANY AS BIT = 0,
	@COMPANYNAME NVARCHAR(100) = NULL,
	@EMAIL NVARCHAR(250) = NULL,
	@MOBILEPHONE NVARCHAR(50) = NULL
)
AS
BEGIN
SET NOCOUNT ON;

SELECT [GLOBALENTITYID]
	INTO #IDS
	FROM [GLOBALENTITY] WITH (NOLOCK)
	WHERE  [GLOBALENTITY].[ISACTIVE] = 1 AND
	(
	(LEN(ISNULL(@FIRSTNAME,'')) > 0 AND SUBSTRING(LTRIM(RTRIM([GLOBALENTITY].[FIRSTNAME])), 1, 1) = SUBSTRING(LTRIM(RTRIM(@FIRSTNAME)), 1, 1)
		AND	LEN(ISNULL(@LASTNAME,'')) > 0  AND LTRIM(RTRIM([GLOBALENTITY].[LASTNAME])) = LTRIM(RTRIM(@LASTNAME))) OR 
	(LEN(ISNULL(@COMPANYNAME,'')) > 0 AND [GLOBALENTITY].[ISCOMPANY] = 1 AND @ISCOMPANY = 1 AND LTRIM(RTRIM([GLOBALENTITY].[GLOBALENTITYNAME])) = LTRIM(RTRIM(@COMPANYNAME))) OR 
	(LEN(ISNULL(@EMAIL,'')) > 0 AND (LTRIM(RTRIM([GLOBALENTITY].[EMAIL])) = LTRIM(RTRIM(@EMAIL)) OR LTRIM(RTRIM([GLOBALENTITY].[OTHEREMAIL])) = LTRIM(RTRIM(@EMAIL)))) OR
	(LEN(ISNULL(@MOBILEPHONE,'')) > 0 AND LTRIM(RTRIM([GLOBALENTITY].[MOBILEPHONE])) = LTRIM(RTRIM(@MOBILEPHONE)))
	)

SELECT 
	[GLOBALENTITY].[GLOBALENTITYID],
	[GLOBALENTITY].[FIRSTNAME],
	[GLOBALENTITY].[LASTNAME],
	[GLOBALENTITY].[MIDDLENAME],
	[GLOBALPREFFERCOMM].[PREFNAME],
	[GLOBALENTITY].[EMAIL],
	[GLOBALENTITY].[GLOBALENTITYNAME],
	[GLOBALENTITY].[CONTACTID],
	[GLOBALENTITY].[ISCONTACT],
    [GLOBALENTITY].[ISACTIVE],
    [GLOBALENTITY].[ISCOMPANY],
	CAST(CASE WHEN EXISTS(SELECT [USERS].[GLOBALENTITYID] FROM [USERS] JOIN [APPLICATIONALLOWED] ON [USERS].SUSERGUID = [APPLICATIONALLOWED].[USERID]
	WHERE [APPLICATIONALLOWED].[APPLICATIONID] = 2 AND [APPLICATIONALLOWED].[APPROVED] = 1 AND [USERS].[GLOBALENTITYID] = [GLOBALENTITY].[GLOBALENTITYID]) 
	THEN 1 ELSE 0 END as bit) ISPORTALACCOUNT,
    [GLOBALENTITY].[TITLE],
    [GLOBALENTITY].[PREFCOMM],
    [GLOBALENTITY].[LASTCHANGEDON],
    [ChangedBy].[FNAME] + ' ' + [ChangedBy].[LNAME] LASTUPDATEDBY,
	[GLOBALENTITY].[BUSINESSPHONE],
	[GLOBALENTITY].[HOMEPHONE],
	[GLOBALENTITY].[MOBILEPHONE],
	[GLOBALENTITY].[OTHERPHONE],
	[GLOBALENTITY].[PARENTGLOBALENTITYID],
	[ParentGlobalEntity].[FIRSTNAME],
	[ParentGlobalEntity].[LASTNAME],
	[ParentGlobalEntity].[GLOBALENTITYNAME],
	[ParentGlobalEntity].[ISCOMPANY],
	CAST(0 as bit) ISPENDINGCONFIRMATION,
	[GLOBALENTITY].[OTHEREMAIL]
FROM [GLOBALENTITY] WITH (NOLOCK)
INNER JOIN [#IDS] ON [GLOBALENTITY].[GLOBALENTITYID] = [#IDS].[GLOBALENTITYID]
LEFT OUTER JOIN [USERS] ChangedBy WITH (NOLOCK) ON ChangedBy.SUSERGUID = [GLOBALENTITY].LASTCHANGEDBY
LEFT OUTER JOIN [GLOBALPREFFERCOMM] WITH (NOLOCK) ON [GLOBALPREFFERCOMM].[GLOBALPREFFERCOMMID] = [GLOBALENTITY].[PREFCOMM]
LEFT OUTER JOIN [GLOBALENTITY] ParentGlobalEntity WITH (NOLOCK) ON ParentGlobalEntity.GLOBALENTITYID = [GLOBALENTITY].PARENTGLOBALENTITYID;

WITH ADDRESSES_CTE (MAILINGADDRESSID, ROWNUMBER) AS
(
select 
	[MAILINGADDRESS].[MAILINGADDRESSID],	
	row_number() over (partition by
	[GLOBALENTITYMAILINGADDRESS].[GLOBALENTITYID] ORDER BY [GLOBALENTITYMAILINGADDRESS].[MAIN] desc) ROWNUMBER
	FROM [MAILINGADDRESS] WITH (NOLOCK)	
	INNER JOIN [GLOBALENTITYMAILINGADDRESS] WITH (NOLOCK) ON [MAILINGADDRESS].[MAILINGADDRESSID] = [GLOBALENTITYMAILINGADDRESS].[MAILINGADDRESSID]
	INNER JOIN [#IDS] ON [GLOBALENTITYMAILINGADDRESS].[GLOBALENTITYID] = [#IDS].[GLOBALENTITYID]
)
select 	 
	[MAILINGADDRESS].[MAILINGADDRESSID],
	[MAILINGADDRESS].[ADDRESSLINE1],
	[MAILINGADDRESS].[ADDRESSLINE2],
	[MAILINGADDRESS].[ADDRESSLINE3],
	[MAILINGADDRESS].[CITY],
	[MAILINGADDRESS].[STATE],
	[MAILINGADDRESS].[COUNTY],
	[MAILINGADDRESS].[COUNTRY],
	[MAILINGADDRESS].[POSTALCODE],
	[MAILINGADDRESS].[COUNTRYTYPE],
	[MAILINGADDRESS].[POSTDIRECTION],
	[MAILINGADDRESS].[PREDIRECTION],
	[MAILINGADDRESS].[ADDRESSID],
	[MAILINGADDRESS].[ADDRESSTYPE],
	[MAILINGADDRESS].[STREETTYPE],
	[MAILINGADDRESS].[PARCELID],
	[MAILINGADDRESS].[PARCELNUMBER],
	[MAILINGADDRESS].[UNITORSUITE],
	[MAILINGADDRESS].[PROVINCE],
	[MAILINGADDRESS].[RURALROUTE],
	[MAILINGADDRESS].[STATION],
	[MAILINGADDRESS].[COMPSITE],
	[MAILINGADDRESS].[POBOX],
	[MAILINGADDRESS].[ATTN],
	[MAILINGADDRESS].[ROWVERSION],
	[MAILINGADDRESSCOUNTRYTYPE].[MAILINGADDRESSCOUNTRYTYPENAME],
	[GLOBALENTITYMAILINGADDRESS].[GLOBALENTITYID]
FROM ADDRESSES_CTE
INNER JOIN [MAILINGADDRESS] WITH (NOLOCK) ON [MAILINGADDRESS].[MAILINGADDRESSID] = ADDRESSES_CTE.MAILINGADDRESSID
INNER JOIN [GLOBALENTITYMAILINGADDRESS] WITH (NOLOCK) ON [MAILINGADDRESS].[MAILINGADDRESSID] = [GLOBALENTITYMAILINGADDRESS].[MAILINGADDRESSID]
INNER JOIN [MAILINGADDRESSCOUNTRYTYPE] WITH (NOLOCK) ON [MAILINGADDRESSCOUNTRYTYPE].MAILINGADDRESSCOUNTRYTYPEID = [MAILINGADDRESS].COUNTRYTYPE
WHERE ADDRESSES_CTE.ROWNUMBER = 1

END