CREATE PROCEDURE [inspectiondashboard].[USP_RESOURCE_INSERT]
(
	@RESOURCEID CHAR(36),
	@USERID CHAR(36),
	@UNAVAILABLESTARTDATE DATETIME,
	@UNAVAILABLEENDDATE DATETIME,
	@REASON VARCHAR(MAX),
	@DELEGATEUSERID CHAR(36)
)
AS

INSERT INTO [dbo].[RESOURCE](
	[RESOURCEID],
	[USERID],
	[UNAVAILABLESTARTDATE],
	[UNAVAILABLEENDDATE],
	[REASON],
	[DELEGATEUSERID]
)

VALUES
(
	@RESOURCEID,
	@USERID,
	@UNAVAILABLESTARTDATE,
	@UNAVAILABLEENDDATE,
	@REASON,
	@DELEGATEUSERID
)