CREATE PROCEDURE [inspectiondashboard].[USP_IMINSPECTIONTYPES_WITH_GROUPS_SELECT_ALL]
(	
	@RECORDIDs RecordIDs READONLY
)
AS

SET NOCOUNT ON;

SELECT
	[dbo].[IMINSPECTIONTYPE].[IMINSPECTIONTYPEID],
	[dbo].[IMINSPECTIONTYPEGROUP].[IMINSPECTIONTYPEGROUPID],
	[dbo].[IMINSPECTIONTYPEGROUP].[NAME]
FROM [dbo].[IMINSPECTIONTYPE]
INNER JOIN @RECORDIDs ALL_TYPES ON ALL_TYPES.RECORDID = [dbo].[IMINSPECTIONTYPE].[IMINSPECTIONTYPEID]
LEFT OUTER JOIN [dbo].[IMINSPECTIONTYPEGROUP] ON [dbo].[IMINSPECTIONTYPEGROUP].[IMINSPECTIONTYPEGROUPID] = [dbo].[IMINSPECTIONTYPE].[IMINSPECTIONTYPEGROUPID]