CREATE PROCEDURE [inspectiondashboard].[USP_ZONE_MAPPING_FOR_SELECTED_INSPECTION_TYPES]
(	
	@RECORDIDs RecordIDs READONLY
)
AS

SET NOCOUNT ON;

SELECT
	[dbo].[IMINSPECTIONTYPE].[IMINSPECTIONTYPEID],
	[dbo].[IMINSPECTIONTYPE].[GISZONEMAPPINGID]
FROM [dbo].[IMINSPECTIONTYPE]
WHERE 
	[dbo].[IMINSPECTIONTYPE].[IMINSPECTIONTYPEID] IN (SELECT ALL_TYPES.RECORDID FROM @RECORDIDs ALL_TYPES) 
ORDER BY [dbo].[IMINSPECTIONTYPE].[IMINSPECTIONTYPEID]