CREATE PROCEDURE [inspectiondashboard].[USP_IMINSPECTORREF_INSERT]
(
	@INSPECTIONID CHAR(36),
	@USERID CHAR(36),
	@BPRIMARY BIT,
	@IMINSPECTORREFID CHAR(36)
)
AS

INSERT INTO [dbo].[IMINSPECTORREF](
	[INSPECTIONID],
	[USERID],
	[BPRIMARY],
	[IMINSPECTORREFID]
)

VALUES
(
	@INSPECTIONID,
	@USERID,
	@BPRIMARY,
	@IMINSPECTORREFID
)