CREATE PROCEDURE [inspectiondashboard].[USP_IMINSPECTIONTYPES_WITH_INSPECTORS]
(	
	@RECORDIDs RecordIDs READONLY
)
AS

SET NOCOUNT ON;

WITH DISTINCT_USERS_WITH_TYPES AS
(
	SELECT DISTINCT
		[dbo].[IMINSPECTORTYPEUSER].[USERID],
		[dbo].[IMINSPECTIONTYPE].[IMINSPECTIONTYPEID]
	FROM [dbo].[IMINSPECTIONTYPE]
	INNER JOIN [dbo].[IMINSPECTORTYPEINSPECTIONTYPE] ON [dbo].[IMINSPECTORTYPEINSPECTIONTYPE].[IMINSPECTIONTYPEID] = [dbo].[IMINSPECTIONTYPE].[IMINSPECTIONTYPEID]
	INNER JOIN [dbo].[IMINSPECTORTYPEUSER] ON [dbo].[IMINSPECTORTYPEUSER].[INSPECTORTYPEID] = [dbo].[IMINSPECTORTYPEINSPECTIONTYPE].[IMINSPECTORTYPEID]
	INNER JOIN @RECORDIDs ALL_TYPES ON ALL_TYPES.RECORDID = [dbo].[IMINSPECTIONTYPE].[IMINSPECTIONTYPEID]
)

SELECT DISTINCT_USERS_WITH_TYPES.USERID, COUNT(1) AS TOTAL_TYPES
FROM DISTINCT_USERS_WITH_TYPES
GROUP BY DISTINCT_USERS_WITH_TYPES.USERID