CREATE TABLE [dbo].[FILESET] (
    [FILESETID]     CHAR (36)      NOT NULL,
    [NAME]          NVARCHAR (100) NOT NULL,
    [DESCRIPTION]   NVARCHAR (MAX) NULL,
    [LASTCHANGEDON] DATETIME       NULL,
    [LASTCHANGEDBY] CHAR (36)      NULL,
    CONSTRAINT [PK_FileSet] PRIMARY KEY CLUSTERED ([FILESETID] ASC),
    CONSTRAINT [FK_FILESET_USERS] FOREIGN KEY ([LASTCHANGEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);

