CREATE TABLE [dbo].[FILESETFILECATEGORY] (
    [FILESETFILECATEGORYID]   CHAR (36) NOT NULL,
    [FILESETID]               CHAR (36) NOT NULL,
    [FILECATEGORYID]          CHAR (36) NOT NULL,
    [ISREQUIRED]              BIT       DEFAULT ((0)) NOT NULL,
    [NUMBEROFFILESALLOWED]    INT       DEFAULT ((1)) NOT NULL,
    [SUGGESTROUTEAS]          SMALLINT  NULL,
    [REQUIREDIGITALSIGNATURE] BIT       CONSTRAINT [DF_FILESETFILECATEGORY_REQUIREDIGITALSIGNATURE] DEFAULT ((0)) NOT NULL,
    [PREVENTLOCKEDSECURED]    BIT       CONSTRAINT [DF_FILESETFILECATEGORY_PREVENTLOCKEDSECURED] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_FileSetFileCategory] PRIMARY KEY CLUSTERED ([FILESETFILECATEGORYID] ASC),
    CONSTRAINT [FK_FILESETFILECATEGORY_FILECATEGORY] FOREIGN KEY ([FILECATEGORYID]) REFERENCES [dbo].[ERPROJECTFILECATEGORY] ([ERPROJECTFILECATEGORYID]),
    CONSTRAINT [FK_FILESETFILECATEGORY_FILESET] FOREIGN KEY ([FILESETID]) REFERENCES [dbo].[FILESET] ([FILESETID]) ON DELETE CASCADE
);

