CREATE TABLE [dbo].[FILESTATUS] (
    [FILESTATUSID] INT            NOT NULL,
    [NAME]         NVARCHAR (50)  NOT NULL,
    [CUSTOMNAME]   NVARCHAR (50)  NULL,
    [DESCRIPTION]  NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_FILESTATUSTYPE] PRIMARY KEY CLUSTERED ([FILESTATUSID] ASC)
);

