CREATE TABLE [dbo].[FIREOCCUPANCYADDRESS] (
    [FIREOCCUPANCYADDRESSID] CHAR (36) NOT NULL,
    [FIREOCCUPANCYID]        CHAR (36) NOT NULL,
    [MAILINGADDRESSID]       CHAR (36) NOT NULL,
    [MAIN]                   BIT       DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_FIREOCCUPANCYADDRESS] PRIMARY KEY NONCLUSTERED ([FIREOCCUPANCYADDRESSID] ASC),
    CONSTRAINT [FK_FIREOCCUPANCYADDRESS_FIREOCCUPANCY] FOREIGN KEY ([FIREOCCUPANCYID]) REFERENCES [dbo].[FIREOCCUPANCY] ([ID]),
    CONSTRAINT [FK_FIREOCCUPANCYADDRESS_MAILINGADDRESS] FOREIGN KEY ([MAILINGADDRESSID]) REFERENCES [dbo].[MAILINGADDRESS] ([MAILINGADDRESSID])
);


GO
CREATE NONCLUSTERED INDEX [IX_FIREOCCUPANCYADDRESS_FIREOCCUPANCY]
    ON [dbo].[FIREOCCUPANCYADDRESS]([FIREOCCUPANCYID] ASC);

