CREATE TABLE [dbo].[FIREOCCUPANCYPARCEL] (
    [FIREOCCUPANCYPARCELID] CHAR (36) NOT NULL,
    [FIREOCCUPANCYID]       CHAR (36) NOT NULL,
    [PARCELID]              CHAR (36) NOT NULL,
    [MAIN]                  BIT       DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_FIREOCCUPANCYPARCELID] PRIMARY KEY NONCLUSTERED ([FIREOCCUPANCYPARCELID] ASC),
    CONSTRAINT [FK_FIREOCCUPANCYPARCEL_FIREOCCUPANCY] FOREIGN KEY ([FIREOCCUPANCYID]) REFERENCES [dbo].[FIREOCCUPANCY] ([ID]),
    CONSTRAINT [FK_FIREOCCUPANCYPARCEL_PARCEL] FOREIGN KEY ([PARCELID]) REFERENCES [dbo].[PARCEL] ([PARCELID])
);


GO
CREATE NONCLUSTERED INDEX [IX_FIREOCCUPANCYPARCEL_FIREOCCUPANCY]
    ON [dbo].[FIREOCCUPANCYPARCEL]([FIREOCCUPANCYID] ASC);

