CREATE TABLE [dbo].[FIREOCCUPANCYNOTE] (
    [FIREOCCUPANCYNOTEID] CHAR (36)      NOT NULL,
    [FIREOCCUPANCYID]     CHAR (36)      NOT NULL,
    [TEXT]                NVARCHAR (MAX) NOT NULL,
    [CREATEDBY]           CHAR (36)      NULL,
    [CREATEDDATE]         DATETIME       NULL,
    [TITLE]               VARCHAR (50)   NULL,
    [PIN]                 BIT            DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_FIREOCCUPANCYNOTE] PRIMARY KEY CLUSTERED ([FIREOCCUPANCYNOTEID] ASC),
    CONSTRAINT [FK_FIREOCCUPANCYNOTE_FIREOCCUPANCY] FOREIGN KEY ([FIREOCCUPANCYID]) REFERENCES [dbo].[FIREOCCUPANCY] ([ID]),
    CONSTRAINT [FK_FIREOCCUPANCYNOTE_USERS] FOREIGN KEY ([CREATEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);

