CREATE TABLE [dbo].[FOALTERNATECONTACTTYPE] (
    [FOALTERNATECONTACTTYPEID] INT           NOT NULL,
    [NAME]                     NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_FOALTERNATECONTACTTYPE] PRIMARY KEY CLUSTERED ([FOALTERNATECONTACTTYPEID] ASC)
);

