CREATE TABLE [dbo].[FOALTERNATECONTACT] (
    [FOALTERNATECONTACTID]     CHAR (36)      NOT NULL,
    [FIREOCCUPANCYID]          CHAR (36)      NOT NULL,
    [FULLNAME]                 NVARCHAR (200) NOT NULL,
    [EMAIL]                    NVARCHAR (50)  NULL,
    [PHONENUMBER]              NVARCHAR (50)  NULL,
    [FOALTERNATECONTACTTYPEID] INT            NOT NULL,
    CONSTRAINT [PK_FOALTERNATECONTACTID] PRIMARY KEY CLUSTERED ([FOALTERNATECONTACTID] ASC),
    CONSTRAINT [FK_FOALTERNATECONTACT_FIREOCCUPANCY] FOREIGN KEY ([FIREOCCUPANCYID]) REFERENCES [dbo].[FIREOCCUPANCY] ([ID]),
    CONSTRAINT [FK_FOALTERNATECONTACT_FOALTERNATECONTACTTYPE] FOREIGN KEY ([FOALTERNATECONTACTTYPEID]) REFERENCES [dbo].[FOALTERNATECONTACTTYPE] ([FOALTERNATECONTACTTYPEID])
);


GO
CREATE NONCLUSTERED INDEX [IX_FOALTERNATECONTACT_FOALTERNATECONTACTTYPEID]
    ON [dbo].[FOALTERNATECONTACT]([FOALTERNATECONTACTTYPEID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_FOALTERNATECONTACT_FO]
    ON [dbo].[FOALTERNATECONTACT]([FIREOCCUPANCYID] ASC);

