CREATE TABLE [dbo].[FOBUSINESSSTATUS] (
    [FOBUSINESSSTATUSID] CHAR (36)      NOT NULL,
    [NAME]               NVARCHAR (50)  NOT NULL,
    [DESCRIPTION]        NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_FOBUSINESSSTATUS] PRIMARY KEY CLUSTERED ([FOBUSINESSSTATUSID] ASC)
);

