CREATE TABLE [dbo].[FOFIREALARMTYPEXREF] (
    [FOFIREALARMTYPEXREFID] CHAR (36) NOT NULL,
    [FIREOCCUPANCYID]       CHAR (36) NOT NULL,
    [FOFIREALARMTYPEID]     CHAR (36) NOT NULL,
    CONSTRAINT [PK_FOFIREALARMTYPEXREF] PRIMARY KEY NONCLUSTERED ([FOFIREALARMTYPEXREFID] ASC),
    CONSTRAINT [FK_FOFIREALARMTYPEXREF_FIREOCCUPANCY] FOREIGN KEY ([FIREOCCUPANCYID]) REFERENCES [dbo].[FIREOCCUPANCY] ([ID]),
    CONSTRAINT [FK_FOFIREALARMTYPEXREF_FOGENERATORTYPE] FOREIGN KEY ([FOFIREALARMTYPEID]) REFERENCES [dbo].[FOFIREALARMTYPE] ([FOFIREALARMTYPEID])
);


GO
CREATE NONCLUSTERED INDEX [IX_FOFIREALARMTYPEXREF_FIREOCCUPANCY]
    ON [dbo].[FOFIREALARMTYPEXREF]([FIREOCCUPANCYID] ASC);

