CREATE TABLE [dbo].[FORMCATEGORY] (
    [FORMCATEGORYID] CHAR (36)    NOT NULL,
    [NAME]           VARCHAR (50) NOT NULL,
    [DISPLAYLABEL]   VARCHAR (50) NOT NULL,
    [DISPLAYORDER]   INT          NOT NULL,
    [ISADMIN]        BIT          NULL,
    CONSTRAINT [PK_FORMCATEGORY] PRIMARY KEY CLUSTERED ([FORMCATEGORYID] ASC)
);

