CREATE TABLE [dbo].[FORMCATEGORYFORMSUBCATEGORYXREF] (
    [FKFORMCATEGORYID]    CHAR (36) NOT NULL,
    [FKFORMSUBCATEGORYID] CHAR (36) NOT NULL,
    [DISPLAYORDER]        INT       NOT NULL,
    CONSTRAINT [PK_FORMCATEGORYFORMSUBCATEGORYXREF] PRIMARY KEY CLUSTERED ([FKFORMCATEGORYID] ASC, [FKFORMSUBCATEGORYID] ASC),
    CONSTRAINT [FK_FORMCATEGORYFORMSUBCATEGORYXREF_FORMCATEGORY] FOREIGN KEY ([FKFORMCATEGORYID]) REFERENCES [dbo].[FORMCATEGORY] ([FORMCATEGORYID]),
    CONSTRAINT [FK_FORMCATEGORYFORMSUBCATEGORYXREF_FORMSUBCATEGORY] FOREIGN KEY ([FKFORMSUBCATEGORYID]) REFERENCES [dbo].[FORMSUBCATEGORY] ([FORMSUBCATEGORYID])
);

