CREATE TABLE [dbo].[FTPTYPE] (
    [FTPTYPEID]   INT            NOT NULL,
    [NAME]        NVARCHAR (50)  NOT NULL,
    [DESCRIPTION] NVARCHAR (100) NOT NULL,
    CONSTRAINT [PK_FTPTYPE] PRIMARY KEY CLUSTERED ([FTPTYPEID] ASC),
    CONSTRAINT [UC_FTPTYPE_NAME] UNIQUE NONCLUSTERED ([NAME] ASC)
);

