CREATE PROCEDURE [dbo].[USP_FTPSETUP_UPDATE]
(
	@FTPSETUPID CHAR(36),
	@NAME NVARCHAR(100),
	@DESCRIPTION NVARCHAR(250),
	@URL NVARCHAR(250),
	@USERNAME NVARCHAR(100),
	@PASSWORD NVARCHAR(100),
	@FTPTYPEID INT,
	@PORT INT,
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
UPDATE [dbo].[FTPSETUP] SET
	[NAME] = @NAME,
	[DESCRIPTION] = @DESCRIPTION,
	[URL] = @URL,
	[USERNAME] = @USERNAME,
	[PASSWORD] = @PASSWORD,
	[FTPTYPEID] = @FTPTYPEID,
	[PORT] = @PORT,
	[LASTCHANGEDBY] = @LASTCHANGEDBY,
	[LASTCHANGEDON] = @LASTCHANGEDON,
	[ROWVERSION] = @ROWVERSION + 1
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE
	[FTPSETUPID] = @FTPSETUPID AND 
	[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE