CREATE PROCEDURE [dbo].[USP_FEETEMPLATEINPUT_DELETE]
	@INPUTID CHAR(36),
	@ISFEEINPUT BIT
AS
IF @ISFEEINPUT = 1
	BEGIN
		-- Deletes child translations
		DELETE FROM [dbo].[CAFEEINPUTTRANSLATION]
		WHERE
			[CAFEETEMPLATEFEEINPUTID] = @INPUTID 

		DELETE FROM [dbo].[CAFEETEMPLATEFEEINPUT]
		WHERE
			[CAFEETEMPLATEFEEINPUTID] = @INPUTID
	END
ELSE
	BEGIN
		-- Deletes child translations
		DELETE FROM [dbo].[CADISCOUNTINPUTTRANSLATION]
		WHERE
			[CAFEETEMPLATEDISCOUNTINPUTID] = @INPUTID

		DELETE FROM [dbo].[CAFEETEMPLATEDISCOUNTINPUT]
		WHERE
			[CAFEETEMPLATEDISCOUNTINPUTID] = @INPUTID
	END