CREATE TABLE [dbo].[ADVANCEDSEARCHDATEKEY] (
    [ADVANCEDSEARCHDATEKEY]  INT           NOT NULL,
    [ADVANCEDSEARCHDATENAME] NVARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([ADVANCEDSEARCHDATEKEY] ASC)
);

