CREATE TABLE [dbo].[ADVANCEDSEARCHADDRESSFIELDSETUP] (
    [ADVANCEDSEARCHADDRESSFIELDSETUPID] INT       NOT NULL,
    [ADVANCEDSEARCHSYSTEMFIELDID]       INT       NOT NULL,
    [ADDRESSLAYOUTSETUPID]              CHAR (36) NOT NULL,
    CONSTRAINT [PK_ADVANCEDSEARCHADDRESSFIELDSETUP] PRIMARY KEY CLUSTERED ([ADVANCEDSEARCHADDRESSFIELDSETUPID] ASC),
    CONSTRAINT [FK_ADVANCEDSEARCHADDRESSFIELDSETUP_ADDRESSLAYOUTSETUP] FOREIGN KEY ([ADDRESSLAYOUTSETUPID]) REFERENCES [dbo].[ADDRESSLAYOUTSETUP] ([ADDRESSLAYOUTSETUPID]),
    CONSTRAINT [FK_ADVANCEDSEARCHADDRESSFIELDSETUP_ADVANCEDSEARCHSYSTEMFIELD] FOREIGN KEY ([ADVANCEDSEARCHSYSTEMFIELDID]) REFERENCES [dbo].[ADVANCEDSEARCHSYSTEMFIELD] ([ADVANCEDSEARCHSYSTEMFIELDID])
);

