CREATE TABLE [dbo].[ADVANCEDSEARCHSORTFIELD] (
    [ADVANCEDSEARCHSORTFIELDID] CHAR (36) NOT NULL,
    [SEARCHCRITERIAID]          CHAR (36) NOT NULL,
    [FIELDID]                   INT       NULL,
    [CUSTOMFIELDID]             CHAR (36) NULL,
    [DESCENDING]                BIT       NOT NULL,
    CONSTRAINT [PK_ADVANCEDSEARCHSORTFIELD] PRIMARY KEY CLUSTERED ([ADVANCEDSEARCHSORTFIELDID] ASC),
    CONSTRAINT [FK_ADVANCEDSEARCHSORTFIELD_CRITERIA] FOREIGN KEY ([SEARCHCRITERIAID]) REFERENCES [dbo].[ADVANCEDSEARCHCRITERIA] ([ADVANCEDSEARCHCRITERIAID]),
    CONSTRAINT [FK_ADVANCEDSEARCHSORTFIELD_CUSTOMFIELD] FOREIGN KEY ([CUSTOMFIELDID]) REFERENCES [dbo].[CUSTOMFIELDOBJECT] ([GCUSTOMFIELD]),
    CONSTRAINT [FK_ADVANCEDSEARCHSORTFIELD_SYSTEMFIELD] FOREIGN KEY ([FIELDID]) REFERENCES [dbo].[ADVANCEDSEARCHSYSTEMFIELD] ([ADVANCEDSEARCHSYSTEMFIELDID])
);


GO
CREATE NONCLUSTERED INDEX [IX_ADVANCEDSEARCHSORTFIELD_SEARCHCRITERIAID]
    ON [dbo].[ADVANCEDSEARCHSORTFIELD]([SEARCHCRITERIAID] ASC);

