CREATE TABLE [dbo].[ADVANCEDSEARCHOUTPUTFIELD] (
    [ADVANCEDSEARCHOUTPUTFIELDID] CHAR (36) NOT NULL,
    [SEARCHCRITERIAID]            CHAR (36) NOT NULL,
    [FIELDID]                     INT       NULL,
    [CUSTOMFIELDID]               CHAR (36) NULL,
    [ORDER]                       INT       NOT NULL,
    [CALCULATETOTAL]              BIT       NOT NULL,
    [CUSTOMFIELDTABLEID]          CHAR (36) NULL,
    CONSTRAINT [PK_ADVANCEDSEARCHOUTPUTFIELD] PRIMARY KEY CLUSTERED ([ADVANCEDSEARCHOUTPUTFIELDID] ASC),
    CONSTRAINT [FK_ADVANCEDSEARCHOUTPUTFIELD_CRITERIA] FOREIGN KEY ([SEARCHCRITERIAID]) REFERENCES [dbo].[ADVANCEDSEARCHCRITERIA] ([ADVANCEDSEARCHCRITERIAID]),
    CONSTRAINT [FK_ADVANCEDSEARCHOUTPUTFIELD_CUSTOMFIELD] FOREIGN KEY ([CUSTOMFIELDID]) REFERENCES [dbo].[CUSTOMFIELD] ([GCUSTOMFIELD]),
    CONSTRAINT [FK_ADVANCEDSEARCHOUTPUTFIELD_CUSTOMFIELDTABLEID] FOREIGN KEY ([CUSTOMFIELDTABLEID]) REFERENCES [dbo].[CUSTOMFIELDTABLE] ([CUSTOMFIELDTABLEID]),
    CONSTRAINT [FK_ADVANCEDSEARCHOUTPUTFIELD_SYSTEMFIELD] FOREIGN KEY ([FIELDID]) REFERENCES [dbo].[ADVANCEDSEARCHSYSTEMFIELD] ([ADVANCEDSEARCHSYSTEMFIELDID])
);


GO
CREATE NONCLUSTERED INDEX [IX_ADVANCEDSEARCHOUTPUTFIELD_SEARCHCRITERIAID]
    ON [dbo].[ADVANCEDSEARCHOUTPUTFIELD]([SEARCHCRITERIAID] ASC);

