CREATE TABLE [dbo].[AMASSETITEM] (
    [AMASSETITEMID]   CHAR (36)    NOT NULL,
    [AMASSETID]       CHAR (36)    NOT NULL,
    [ITEMID]          CHAR (36)    NOT NULL,
    [UNITOFMEASUREID] CHAR (36)    NOT NULL,
    [QUANTITY]        DECIMAL (18) NULL,
    CONSTRAINT [PK_PLPlanItem] PRIMARY KEY CLUSTERED ([AMASSETITEMID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_AMAssetItem_AMAsset] FOREIGN KEY ([AMASSETID]) REFERENCES [dbo].[AMASSET] ([AMASSETID]),
    CONSTRAINT [FK_AMAssetItem_Item] FOREIGN KEY ([ITEMID]) REFERENCES [dbo].[ITEM] ([ITEMID]),
    CONSTRAINT [FK_AMAssetItem_UnitOfMeasure] FOREIGN KEY ([UNITOFMEASUREID]) REFERENCES [dbo].[UNITOFMEASURE] ([UNITOFMEASUREID])
);

