CREATE TABLE [dbo].[AMCONTACTTYPE] (
    [AMCONTACTTYPEID]       CHAR (36)      NOT NULL,
    [NAME]                  NVARCHAR (50)  NOT NULL,
    [DESCRIPTION]           NVARCHAR (MAX) NULL,
    [AMCONTACTTYPESYSTEMID] INT            NOT NULL,
    CONSTRAINT [PK_AMContactType_1] PRIMARY KEY CLUSTERED ([AMCONTACTTYPEID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_AMContactType_TypeSystem] FOREIGN KEY ([AMCONTACTTYPESYSTEMID]) REFERENCES [dbo].[AMCONTACTTYPESYSTEM] ([AMCONTACTTYPESYSTEMID])
);

