CREATE TABLE [dbo].[AMCONTACTTYPESYSTEM] (
    [AMCONTACTTYPESYSTEMID] INT           NOT NULL,
    [NAME]                  NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_AMContactTypeSystem] PRIMARY KEY CLUSTERED ([AMCONTACTTYPESYSTEMID] ASC) WITH (FILLFACTOR = 90)
);

