CREATE TABLE [dbo].[AMENDMENTTYPEXREF] (
    [AMENDMENTTYPEXREFID] CHAR (36) NOT NULL,
    [AMENDMENTTYPEID]     CHAR (36) NOT NULL,
    [OBJMODULEID]         INT       NOT NULL,
    [OBJTYPEID]           CHAR (36) NULL,
    [OBJCLASSID]          CHAR (36) NULL,
    [INTERNETFLAG]        BIT       NOT NULL,
    CONSTRAINT [PK_AMENDMENTTYPEXREF] PRIMARY KEY CLUSTERED ([AMENDMENTTYPEXREFID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_AMENDTYPEXREF_AMENDTYPE] FOREIGN KEY ([AMENDMENTTYPEID]) REFERENCES [dbo].[AMENDMENTTYPE] ([AMENDMENTTYPEID])
);

