CREATE TABLE [dbo].[AMEQUIPMENTTYPE] (
    [AMEQUIPMENTTYPEID] CHAR (36)      NOT NULL,
    [NAME]              NVARCHAR (50)  NOT NULL,
    [DESCRIPTION]       NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_AMEquipmentType] PRIMARY KEY CLUSTERED ([AMEQUIPMENTTYPEID] ASC) WITH (FILLFACTOR = 90)
);

