CREATE TABLE [dbo].[AMTASK] (
    [AMTASKID]     CHAR (36)     NOT NULL,
    [AMTASKTYPEID] CHAR (36)     NOT NULL,
    [NAME]         VARCHAR (50)  NOT NULL,
    [DESCRIPTION]  VARCHAR (MAX) NULL,
    CONSTRAINT [PK_AMTask] PRIMARY KEY CLUSTERED ([AMTASKID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_AMTask_AMTaskType] FOREIGN KEY ([AMTASKTYPEID]) REFERENCES [dbo].[AMTASKTYPE] ([AMTASKTYPEID])
);

