CREATE TABLE [dbo].[AMTASKTYPE] (
    [AMTASKTYPEID] CHAR (36)      NOT NULL,
    [NAME]         NVARCHAR (36)  NOT NULL,
    [DESCRIPTION]  NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_AMTaskType] PRIMARY KEY CLUSTERED ([AMTASKTYPEID] ASC) WITH (FILLFACTOR = 90)
);

