CREATE TABLE [dbo].[AMWORKORDERTASKRESOURCE] (
    [AMWORKORDERTASKRESOURCEID] CHAR (36)       NOT NULL,
    [AMWORKORDERTASKID]         CHAR (36)       NOT NULL,
    [TIMEPLANNED]               DECIMAL (18, 2) NULL,
    [TIMEACTUAL]                DECIMAL (18, 2) NULL,
    [RATE]                      MONEY           NULL,
    [STARTDATE]                 DATETIME        NULL,
    [ENDDATE]                   DATETIME        NULL,
    [TIMEUNITOFMEASURE]         CHAR (36)       NULL,
    [AMRESOURCEID]              CHAR (36)       NOT NULL,
    CONSTRAINT [PK_AMWorkOrderTaskResource] PRIMARY KEY NONCLUSTERED ([AMWORKORDERTASKRESOURCEID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_AMWorkOrderTaskResource_AMR] FOREIGN KEY ([AMRESOURCEID]) REFERENCES [dbo].[AMRESOURCE] ([AMRESOURCEID]),
    CONSTRAINT [FK_AMWorkOrderTaskResource_AMW] FOREIGN KEY ([AMWORKORDERTASKID]) REFERENCES [dbo].[AMWORKORDERTASK] ([AMWORKORDERTASKID]),
    CONSTRAINT [FK_WorkOrderTaskResource_UnitO] FOREIGN KEY ([TIMEUNITOFMEASURE]) REFERENCES [dbo].[UNITOFMEASURE] ([UNITOFMEASUREID])
);


GO
CREATE NONCLUSTERED INDEX [IX_OrderTaskResource_Uom]
    ON [dbo].[AMWORKORDERTASKRESOURCE]([TIMEUNITOFMEASURE] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_OrderTaskRsx_Task]
    ON [dbo].[AMWORKORDERTASKRESOURCE]([AMWORKORDERTASKID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_OrdTaskResource_ResourceID]
    ON [dbo].[AMWORKORDERTASKRESOURCE]([AMRESOURCEID] ASC) WITH (FILLFACTOR = 90);

