CREATE TABLE [dbo].[AMWORKORDERSTATUS] (
    [AMWORKORDERSTATUSID] CHAR (36)     NOT NULL,
    [NAME]                VARCHAR (50)  NOT NULL,
    [DESCRIPTION]         VARCHAR (MAX) NULL,
    CONSTRAINT [PK_AMWorkOrderStatus] PRIMARY KEY CLUSTERED ([AMWORKORDERSTATUSID] ASC) WITH (FILLFACTOR = 90)
);

