CREATE TABLE [dbo].[AMWORKORDERRESOURCE] (
    [AMWORKORDERRESOURCEID] CHAR (36)       NOT NULL,
    [AMWORKORDERID]         CHAR (36)       NOT NULL,
    [TIMEPLANNED]           DECIMAL (18, 2) NULL,
    [TIMEACTUAL]            DECIMAL (18, 2) NULL,
    [RATE]                  MONEY           NULL,
    [STARTDATE]             DATETIME        NULL,
    [ENDDATE]               DATETIME        NULL,
    [TIMEUNITOFMEASURE]     CHAR (36)       NULL,
    [AMRESOURCEID]          CHAR (36)       NOT NULL,
    CONSTRAINT [PK_AMWorkOrderResource] PRIMARY KEY NONCLUSTERED ([AMWORKORDERRESOURCEID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_AMWOResource_AMWorkOrder] FOREIGN KEY ([AMWORKORDERID]) REFERENCES [dbo].[AMWORKORDER] ([AMWORKORDERID]),
    CONSTRAINT [FK_AMWOResource_UnitOfMeasure] FOREIGN KEY ([TIMEUNITOFMEASURE]) REFERENCES [dbo].[UNITOFMEASURE] ([UNITOFMEASUREID]),
    CONSTRAINT [FK_AMWorkOrderResource_AMResou] FOREIGN KEY ([AMRESOURCEID]) REFERENCES [dbo].[AMRESOURCE] ([AMRESOURCEID])
);


GO
CREATE NONCLUSTERED INDEX [IX_OrderResource_Measure]
    ON [dbo].[AMWORKORDERRESOURCE]([TIMEUNITOFMEASURE] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_OrderResource_OrderID]
    ON [dbo].[AMWORKORDERRESOURCE]([AMWORKORDERID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_OrderResource_ResourceID]
    ON [dbo].[AMWORKORDERRESOURCE]([AMRESOURCEID] ASC) WITH (FILLFACTOR = 90);

