CREATE TABLE [dbo].[AMWORKORDERTASK] (
    [AMWORKORDERTASKID] CHAR (36)     NOT NULL,
    [AMWORKORDERID]     CHAR (36)     NOT NULL,
    [TASKORDER]         INT           CONSTRAINT [DF_AMWorkOrderTask_Order] DEFAULT ((0)) NOT NULL,
    [COMPLETE]          BIT           NOT NULL,
    [NAME]              VARCHAR (50)  NOT NULL,
    [DESCRIPTION]       VARCHAR (MAX) NULL,
    [AMTASKID]          CHAR (36)     NULL,
    CONSTRAINT [PK_AMWorkOrderTask] PRIMARY KEY NONCLUSTERED ([AMWORKORDERTASKID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_AMWorkOrderTask_AMTask] FOREIGN KEY ([AMTASKID]) REFERENCES [dbo].[AMTASK] ([AMTASKID]),
    CONSTRAINT [FK_AMWorkOrderTask_AMWorkOrder] FOREIGN KEY ([AMWORKORDERID]) REFERENCES [dbo].[AMWORKORDER] ([AMWORKORDERID])
);


GO
CREATE NONCLUSTERED INDEX [IX_OrderTask_AMTaskID]
    ON [dbo].[AMWORKORDERTASK]([AMTASKID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_OrderTask_OrderID]
    ON [dbo].[AMWORKORDERTASK]([AMWORKORDERID] ASC) WITH (FILLFACTOR = 90);

