CREATE TABLE [dbo].[AMWORKORDERADDRESS] (
    [AMWORKORDERADDRESSID] CHAR (36) NOT NULL,
    [AMWORKORDERID]        CHAR (36) NOT NULL,
    [MAILINGADDRESSID]     CHAR (36) NOT NULL,
    [MAIN]                 BIT       NOT NULL,
    CONSTRAINT [PK_AMWorkOrderAddress] PRIMARY KEY CLUSTERED ([AMWORKORDERADDRESSID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_AMWOAddress_MailingAddress] FOREIGN KEY ([MAILINGADDRESSID]) REFERENCES [dbo].[MAILINGADDRESS] ([MAILINGADDRESSID]),
    CONSTRAINT [FK_AMWOAddress_WorkOrder] FOREIGN KEY ([AMWORKORDERID]) REFERENCES [dbo].[AMWORKORDER] ([AMWORKORDERID])
);

