CREATE TABLE [dbo].[APPLICATION] (
    [APPLICATIONID]   INT           NOT NULL,
    [APPLICATIONNAME] NVARCHAR (50) NOT NULL,
    [ACTIVE]          BIT           CONSTRAINT [DF_Application_Active] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_Application] PRIMARY KEY CLUSTERED ([APPLICATIONID] ASC) WITH (FILLFACTOR = 90)
);

