CREATE TABLE [dbo].[APPLICATIONUSERTYPE] (
    [APPLICATIONUSERTYPEID] CHAR (36)     NOT NULL,
    [APPLICATIONID]         INT           NOT NULL,
    [TYPEID]                INT           NOT NULL,
    [TYPENAME]              NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_ApplicationUserType] PRIMARY KEY CLUSTERED ([APPLICATIONUSERTYPEID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_UserType_Application] FOREIGN KEY ([APPLICATIONID]) REFERENCES [dbo].[APPLICATION] ([APPLICATIONID])
);

