CREATE TABLE [dbo].[ASSETGEOMETRYCOLLECTION] (
    [ASSETGEOMETRYCOLLECTIONID] CHAR (36)     NOT NULL,
    [NAME]                      VARCHAR (50)  NOT NULL,
    [DETAILS]                   VARCHAR (500) NULL,
    [CREATEDBY]                 CHAR (36)     NULL,
    [CREATEDDATE]               DATETIME      NULL,
    CONSTRAINT [PK_AssetGeometryCollection] PRIMARY KEY CLUSTERED ([ASSETGEOMETRYCOLLECTIONID] ASC) WITH (FILLFACTOR = 90)
);

