CREATE TABLE [dbo].[ATTACHMENTGROUPROLEXREF] (
    [ATTACHMENTGROUPROLEID] CHAR (36) NOT NULL,
    [ATTACHMENTGROUPID]     CHAR (36) NOT NULL,
    [ROLEID]                CHAR (36) NOT NULL,
    CONSTRAINT [PK_AttachmentGroupRoleXRef] PRIMARY KEY CLUSTERED ([ATTACHMENTGROUPROLEID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_AttachmentGroup] FOREIGN KEY ([ATTACHMENTGROUPID]) REFERENCES [dbo].[ATTACHMENTGROUP] ([ATTACHMENTGROUPID]),
    CONSTRAINT [FK_Roles] FOREIGN KEY ([ROLEID]) REFERENCES [dbo].[ROLES] ([SROLEGUID]),
    CONSTRAINT [IX_AttachmentGroupRoleXRef] UNIQUE NONCLUSTERED ([ATTACHMENTGROUPROLEID] ASC, [ROLEID] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [ATTACHMENTGROUPROLEXREF_IX_ROLEID]
    ON [dbo].[ATTACHMENTGROUPROLEXREF]([ROLEID] ASC, [ATTACHMENTGROUPID] ASC);


GO

CREATE TRIGGER [TG_ATTACHMENTGROUPROLEXREF_DELETE] ON [ATTACHMENTGROUPROLEXREF]
	AFTER DELETE
AS
BEGIN
	SET NOCOUNT ON

	INSERT INTO [HISTORYSYSTEMSETUP]
	(
		[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
	)
	SELECT
			[ROLES].[SROLEGUID],
			[ROLES].[ROWVERSION],
			GETUTCDATE(),
			(SELECT dbo.UFN_GET_USERID_FROM_CONTEXT_INFO()),
			'User Role - Attachment Group Deleted',
			'',
			'',
			'User Role (' + [ROLES].[ID] + '), Attachment Group (' + [ATTACHMENTGROUP].[NAME] + ')',
			'801F270F-912F-420A-91D6-82EBC3F351F3',
			3,
			0,
			[ATTACHMENTGROUP].[NAME]
	FROM	[deleted]	
	INNER JOIN [ROLES] ON [deleted].[ROLEID] = [ROLES].[SROLEGUID]	
	INNER JOIN [ATTACHMENTGROUP] WITH (NOLOCK) ON [ATTACHMENTGROUP].[ATTACHMENTGROUPID] = [deleted].[ATTACHMENTGROUPID]
END
GO

CREATE TRIGGER [TG_ATTACHMENTGROUPROLEXREF_INSERT] ON [ATTACHMENTGROUPROLEXREF]
	AFTER INSERT
AS
BEGIN
	SET NOCOUNT ON

	INSERT INTO [HISTORYSYSTEMSETUP]
	(
		[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
	)
	SELECT 
			[ROLES].[SROLEGUID],
			[ROLES].[ROWVERSION],
			GETUTCDATE(),
			[ROLES].[LASTCHANGEDBY],
			'User Role - Attachment Group Added',
			'',
			'',
			'User Role (' + [ROLES].[ID] + '), Attachment Group (' + [ATTACHMENTGROUP].[NAME] + ')',
			'801F270F-912F-420A-91D6-82EBC3F351F3',
			1,
			0,
			[ATTACHMENTGROUP].[NAME]
	FROM	[inserted]
	INNER JOIN [ROLES] ON [inserted].[ROLEID] = [ROLES].[SROLEGUID]
	INNER JOIN [ATTACHMENTGROUP] WITH (NOLOCK) ON [ATTACHMENTGROUP].[ATTACHMENTGROUPID] = [inserted].[ATTACHMENTGROUPID]
END