CREATE TABLE [dbo].[RECENTHISTORYAPPLICATION] (
    [RECENTHISTORYAPPLICATIONID] CHAR (36)     NOT NULL,
    [PLAPPLICATIONID]            CHAR (36)     NOT NULL,
    [LOGGEDDATETIME]             DATETIME      NOT NULL,
    [USERID]                     CHAR (36)     NOT NULL,
    [APPNUMBER]                  NVARCHAR (50) NULL,
    CONSTRAINT [PK_RECENTHISTORYAPPLICATION] PRIMARY KEY CLUSTERED ([RECENTHISTORYAPPLICATIONID] ASC),
    CONSTRAINT [FK_RECENTHISTORYAPPLICATION_USERS] FOREIGN KEY ([USERID]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);


GO
CREATE NONCLUSTERED INDEX [IX_RECENTHISTORYAPPLICATION_ALL]
    ON [dbo].[RECENTHISTORYAPPLICATION]([USERID] ASC, [APPNUMBER] DESC, [PLAPPLICATIONID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_RECENTHISTORYAPPLICATION_LOOKUP]
    ON [dbo].[RECENTHISTORYAPPLICATION]([PLAPPLICATIONID] ASC, [USERID] ASC, [APPNUMBER] DESC);

