CREATE TABLE [dbo].[RECENTHISTORYFIREOCCUPANCY] (
    [RECENTHISTORYFIREOCCUPANCYID] CHAR (36) NOT NULL,
    [FIREOCCUPANCYID]              CHAR (36) NOT NULL,
    [USERID]                       CHAR (36) NOT NULL,
    [LOGGEDDATETIME]               DATETIME  NOT NULL,
    CONSTRAINT [PK_RECENTHISTORYFIREOCCUPANCY] PRIMARY KEY CLUSTERED ([RECENTHISTORYFIREOCCUPANCYID] ASC),
    CONSTRAINT [FK_RECENTHISTORYFIREOCCUPANCY_FIREOCCUPANCY] FOREIGN KEY ([FIREOCCUPANCYID]) REFERENCES [dbo].[FIREOCCUPANCY] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_RECENTHISTORYFIREOCCUPANCY_USERS] FOREIGN KEY ([USERID]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);


GO
CREATE NONCLUSTERED INDEX [IX_RECENTHISTORYFIREOCCUPANCY_LOOKUP]
    ON [dbo].[RECENTHISTORYFIREOCCUPANCY]([USERID] ASC, [FIREOCCUPANCYID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_RECENTHISTORYFIREOCCUPANCY_FIREOCCUPANCYID]
    ON [dbo].[RECENTHISTORYFIREOCCUPANCY]([FIREOCCUPANCYID] ASC);

