CREATE TABLE [dbo].[RECENTHISTORYINSPECTIONCASE] (
    [RECENTHISTORYINSPECTIONCASEID] CHAR (36)     NOT NULL,
    [INSPECTIONCASEID]              CHAR (36)     NOT NULL,
    [LOGGEDDATETIME]                DATETIME      NOT NULL,
    [USERID]                        CHAR (36)     NOT NULL,
    [CASENUMBER]                    NVARCHAR (50) NULL,
    CONSTRAINT [PK_RECENTHISTORYINSPECTIONCASE] PRIMARY KEY CLUSTERED ([RECENTHISTORYINSPECTIONCASEID] ASC),
    CONSTRAINT [FK_RECENTHISTORYINSPECTIONCASE_USERS] FOREIGN KEY ([USERID]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);


GO
CREATE NONCLUSTERED INDEX [IX_RECENTHISTORYINSPECTIONCASE_LOOKUP]
    ON [dbo].[RECENTHISTORYINSPECTIONCASE]([INSPECTIONCASEID] ASC, [USERID] ASC, [CASENUMBER] DESC);


GO
CREATE NONCLUSTERED INDEX [IX_RECENTHISTORYINSPECTIONCASE_ALL]
    ON [dbo].[RECENTHISTORYINSPECTIONCASE]([USERID] ASC, [CASENUMBER] DESC, [INSPECTIONCASEID] ASC);

