CREATE TABLE [dbo].[RECORDSOURCE] (
    [RECORDSOURCEID] INT            NOT NULL,
    [NAME]           NVARCHAR (100) NOT NULL,
    CONSTRAINT [PK_RECORDSOURCE] PRIMARY KEY CLUSTERED ([RECORDSOURCEID] ASC)
);

