CREATE TABLE [dbo].[RESOURCESYSTEMTYPE] (
    [RESOURCESYSTEMTYPEID] INT           NOT NULL,
    [NAME]                 NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_RESOURCESYSTEMTYPE] PRIMARY KEY NONCLUSTERED ([RESOURCESYSTEMTYPEID] ASC)
);

