CREATE TABLE [dbo].[ROLEMENUXREF] (
    [FKROLEID] CHAR (36) NOT NULL,
    [FKMENUID] CHAR (36) NOT NULL,
    [BVISIBLE] BIT       NOT NULL,
    CONSTRAINT [PK_UserMenuXRef] PRIMARY KEY CLUSTERED ([FKROLEID] ASC, [FKMENUID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_RoleMenuXRef_Menus] FOREIGN KEY ([FKMENUID]) REFERENCES [dbo].[MENUS] ([SMENUGUID]),
    CONSTRAINT [FK_RoleMenuXRef_Roles] FOREIGN KEY ([FKROLEID]) REFERENCES [dbo].[ROLES] ([SROLEGUID])
);


GO
CREATE NONCLUSTERED INDEX [IX_ROLEMENUXREF_FKMENUID]
    ON [dbo].[ROLEMENUXREF]([FKMENUID] ASC);


GO

CREATE TRIGGER [TG_ROLEMENUXREF_INSERT] ON [ROLEMENUXREF]
	AFTER INSERT
AS
BEGIN
	SET NOCOUNT ON

	INSERT INTO [HISTORYSYSTEMSETUP]
	(
		[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
	)
	SELECT 
			[ROLES].[SROLEGUID],
			[ROLES].[ROWVERSION],
			GETUTCDATE(),
			[ROLES].[LASTCHANGEDBY],
			'User Role - Menu Added',
			'',
			'',
			'User Role (' + [ROLES].[ID] + '), Menu (' + [MENUS].[SDESCRIPTION] + ')',
			'801F270F-912F-420A-91D6-82EBC3F351F3',
			1,
			0,
			[MENUS].[SDESCRIPTION]
	FROM	[inserted]
	INNER JOIN [ROLES] ON [inserted].[FKROLEID] = [ROLES].[SROLEGUID]
	INNER JOIN [MENUS] WITH (NOLOCK) ON [MENUS].[SMENUGUID] = [inserted].[FKMENUID]
END
GO

CREATE TRIGGER [dbo].[TG_ROLEMENUXREF_UPDATE] ON  [dbo].[ROLEMENUXREF]
   AFTER UPDATE
AS 
BEGIN	
	SET NOCOUNT ON;
			
	INSERT INTO [HISTORYSYSTEMSETUP]
    (	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	
	SELECT 
			[ROLES].[SROLEGUID],
			[ROLES].[ROWVERSION],
			GETUTCDATE(),
			[ROLES].[LASTCHANGEDBY],
			'Visible Flag',			
			CASE [deleted].[BVISIBLE] WHEN 1 THEN 'Yes' ELSE 'No' END,
			CASE [inserted].[BVISIBLE] WHEN 1 THEN 'Yes' ELSE 'No' END,
			'User Role (' + [ROLES].[ID] + '), Menu (' + [MENUS].[SDESCRIPTION] +')',			
			'801F270F-912F-420A-91D6-82EBC3F351F3',
			2,
			0,
			[MENUS].[SDESCRIPTION]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[FKROLEID] = [inserted].[FKROLEID]			
			INNER JOIN [ROLES] ON [inserted].[FKROLEID] = [ROLES].[SROLEGUID]		
			INNER JOIN [MENUS] ON [inserted].[FKMENUID] = [MENUS].[SMENUGUID]
	WHERE	[deleted].[BVISIBLE] <> [inserted].[BVISIBLE]	

END