CREATE TABLE [dbo].[RPLANDLORDLICENSEFEE] (
    [RPLANDLORDLICENSEFEEID] CHAR (36) NOT NULL,
    [RPLANDLORDLICENSEID]    CHAR (36) NOT NULL,
    [CACOMPUTEDFEEID]        CHAR (36) NOT NULL,
    [CREATEDON]              DATETIME  NOT NULL,
    CONSTRAINT [PK_RPLANDLORDLICENSEFEE] PRIMARY KEY NONCLUSTERED ([RPLANDLORDLICENSEFEEID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_RPLLLICFEE_FEE] FOREIGN KEY ([CACOMPUTEDFEEID]) REFERENCES [dbo].[CACOMPUTEDFEE] ([CACOMPUTEDFEEID]),
    CONSTRAINT [FK_RPLLLICFEE_RPLLLICENSE] FOREIGN KEY ([RPLANDLORDLICENSEID]) REFERENCES [dbo].[RPLANDLORDLICENSE] ([RPLANDLORDLICENSEID])
);

