CREATE TABLE [dbo].[RPPROPERTYNOTE] (
    [RPPROPERTYNOTEID] CHAR (36)      NOT NULL,
    [RPPROPERTYID]     CHAR (36)      NOT NULL,
    [TEXT]             NVARCHAR (MAX) NULL,
    [CREATEDBY]        CHAR (36)      NOT NULL,
    [CREATEDDATE]      DATETIME       NOT NULL,
    CONSTRAINT [PK_RPPROPERTYNOTE] PRIMARY KEY NONCLUSTERED ([RPPROPERTYNOTEID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_RPPROPERTYNOTE_RPPROPERTY] FOREIGN KEY ([RPPROPERTYID]) REFERENCES [dbo].[RPPROPERTY] ([RPPROPERTYID]),
    CONSTRAINT [FK_RPPROPERTYNOTE_USERS] FOREIGN KEY ([CREATEDBY]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);

