CREATE TABLE [dbo].[RPPROPERTYHOLD] (
    [RPPROPERTYHOLDID] CHAR (36)      NOT NULL,
    [RPPROPERTYID]     CHAR (36)      NOT NULL,
    [HOLDSETUPID]      CHAR (36)      NOT NULL,
    [COMMENTS]         NVARCHAR (MAX) NULL,
    [SUSERGUID]        CHAR (36)      NULL,
    [CREATEDDATE]      DATETIME       NULL,
    [ORIGIN]           CHAR (36)      NULL,
    [ORIGINNUMBER]     NVARCHAR (150) NULL,
    [EFFECTIVEENDDATE] DATETIME       NULL,
    [ACTIVE]           BIT            NOT NULL,
    CONSTRAINT [PK_RPPROPERTYHOLD] PRIMARY KEY NONCLUSTERED ([RPPROPERTYHOLDID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PROPERTYHOLD_PROPERTY] FOREIGN KEY ([RPPROPERTYID]) REFERENCES [dbo].[RPPROPERTY] ([RPPROPERTYID]),
    CONSTRAINT [FK_PROPERTYHOLD_SETUPS] FOREIGN KEY ([HOLDSETUPID]) REFERENCES [dbo].[HOLDTYPESETUPS] ([HOLDSETUPID]),
    CONSTRAINT [FK_RPPROPERTYHOLD_USERS] FOREIGN KEY ([SUSERGUID]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);


GO
CREATE NONCLUSTERED INDEX [IX_RPPROPERTYHOLD_1]
    ON [dbo].[RPPROPERTYHOLD]([RPPROPERTYID] ASC)
    INCLUDE([RPPROPERTYHOLDID]) WITH (FILLFACTOR = 90);

