CREATE TABLE [dbo].[RPPROPERTYACTIVITY] (
    [RPPROPERTYACTIVITYID]     CHAR (36)      NOT NULL,
    [RPPROPERTYID]             CHAR (36)      NOT NULL,
    [RPPROPERTYACTIVITYTYPEID] CHAR (36)      NOT NULL,
    [PROPERTYACTIVITYNAME]     NVARCHAR (255) NOT NULL,
    [PROPERTYACTIVITYNUMBER]   NVARCHAR (255) NOT NULL,
    [PROPERTYACTIVITYCOMMENTS] NVARCHAR (MAX) NOT NULL,
    [SUSERGUID]                CHAR (36)      NOT NULL,
    [CREATEDON]                DATETIME       NOT NULL,
    CONSTRAINT [PK_RPPROPERTYACTIVITY] PRIMARY KEY NONCLUSTERED ([RPPROPERTYACTIVITYID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PROPERTYACT_ACTIVITYTYPE] FOREIGN KEY ([RPPROPERTYACTIVITYTYPEID]) REFERENCES [dbo].[RPPROPERTYACTIVITYTYPE] ([RPPROPERTYACTIVITYTYPEID]),
    CONSTRAINT [FK_PROPERTYACTIVITY_PROPERTY] FOREIGN KEY ([RPPROPERTYID]) REFERENCES [dbo].[RPPROPERTY] ([RPPROPERTYID]),
    CONSTRAINT [FK_RPPROPERTYACT_USERS] FOREIGN KEY ([SUSERGUID]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);

