CREATE TABLE [dbo].[RPTFORMTOBUSINESSOBJECTMAPPING] (
    [RPTFRMTOBUSOBJMAPID]   CHAR (36)      NOT NULL,
    [FORMNAME]              NVARCHAR (255) NULL,
    [TYPEOFBBUSINESSOBJECT] NVARCHAR (255) NULL,
    [GENRICREPORT]          BIT            NULL,
    [CUSTOMFIELDMODULEID]   INT            NULL,
    [SFORMSGUID]            CHAR (36)      NULL,
    [ISHTMLDEPRICATED]      BIT            NULL,
    CONSTRAINT [PK_RPTFormToBusinessObjectMapping] PRIMARY KEY CLUSTERED ([RPTFRMTOBUSOBJMAPID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_RPTFORMTOBUSINESSOBJECTMAPPING_FORMS] FOREIGN KEY ([SFORMSGUID]) REFERENCES [dbo].[FORMS] ([SFORMSGUID])
);

