CREATE TABLE [dbo].[RPTPARAMTYPE] (
    [RPTPARAMTYPEID] NUMERIC (18)   NOT NULL,
    [PARAMTYPE]      NVARCHAR (255) NULL,
    [GENERICREPORT]  BIT            DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_RPTParamType] PRIMARY KEY CLUSTERED ([RPTPARAMTYPEID] ASC) WITH (FILLFACTOR = 90)
);

