CREATE TABLE [dbo].[RPTPARAMVALUECOLLECTION] (
    [ROWIDNUM]                  CHAR (36)      NOT NULL,
    [RPTPARAMVALUECOLLECTIONID] CHAR (36)      NOT NULL,
    [RPTREPORTID]               CHAR (36)      NOT NULL,
    [PARAMNAME]                 NVARCHAR (255) NULL,
    [PARAMVALUE]                NVARCHAR (MAX) NULL,
    [ISMULTI]                   BIT            CONSTRAINT [DF_RPTParamValueCollection_IsMulti] DEFAULT ((0)) NULL,
    [CREATEDATE]                DATETIME       NULL,
    [ISREQUIRED]                BIT            CONSTRAINT [DF_RPTParamValueCollection_IsRequired] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_RPTParamValueCollection] PRIMARY KEY CLUSTERED ([ROWIDNUM] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [IX_RPTPARAMVALUECOLLECTION_ID]
    ON [dbo].[RPTPARAMVALUECOLLECTION]([RPTPARAMVALUECOLLECTIONID] ASC);

