CREATE TABLE [dbo].[RPTREPORTTYPE] (
    [RPTREPORTTYPEID] INT           NOT NULL,
    [TYPENAME]        NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_RPTREPORTTYPE] PRIMARY KEY CLUSTERED ([RPTREPORTTYPEID] ASC)
);

