CREATE PROCEDURE [dbo].[USP_JOBSCHEDULE_DELETE]
(
	@JOBSCHEDULEID CHAR(36),
	@ROWVERSION INT
)
AS
DELETE FROM [dbo].[JOBSCHEDULE]
WHERE
	[JOBSCHEDULEID] = @JOBSCHEDULEID AND 
	[ROWVERSION]= @ROWVERSION