CREATE PROCEDURE [permit].[USP_PMPERMITRENEWALCASE_GETBYIDS]
(
	@RECENTPERMITRENEWALCASEIDLIST AS RecordIDs READONLY,
	@USERID AS CHAR(36) = NULL
)
AS
BEGIN

SELECT 
	PMRENEWALCASE.PMRENEWALCASEID,
	PMRENEWALCASE.NUMBER, 
	PMRENEWALCASE.CASESTARTDATE,
	PMRENEWALCASE.CREATEDATE,
	PMRENEWALCASE.NEXTRENEWALDATE,
	PMRENEWALCASE.NEXTINVOICEDATE,
	PMRENEWALCASE.DESCRIPTION,
	PMRENEWALCASE.ROWVERSION,
	PMRENEWALCASETYPE.NAME AS TYPENAME,
	GLOBALENTITY.FIRSTNAME,
	GLOBALENTITY.LASTNAME,
	GLOBALENTITY.GLOBALENTITYNAME,
	GLOBALENTITY.CONTACTID,
	GLOBALENTITY.GLOBALENTITYID
FROM PMRENEWALCASE 
INNER JOIN PMRENEWALCASETYPE ON PMRENEWALCASE.PMRENEWALCASETYPEID = PMRENEWALCASETYPE.PMRENEWALCASETYPEID
INNER JOIN GLOBALENTITY ON PMRENEWALCASE.BILLINGCONTACTID = GLOBALENTITY.GLOBALENTITYID
INNER JOIN @RECENTPERMITRENEWALCASEIDLIST PMPERMITRENEWALCASEIDLIST ON PMRENEWALCASE.PMRENEWALCASEID = PMPERMITRENEWALCASEIDLIST.RECORDID
LEFT OUTER JOIN RECENTHISTORYPERMITRENEWALCASE ON RECENTHISTORYPERMITRENEWALCASE.PERMITRENEWALCASEID = PMRENEWALCASE.PMRENEWALCASEID AND RECENTHISTORYPERMITRENEWALCASE.USERID = @USERID
ORDER BY RECENTHISTORYPERMITRENEWALCASE.LOGGEDDATETIME DESC

END