CREATE PROCEDURE [permit].[USP_PMPERMIT_GETBYID]
(
	 @ID AS CHAR(36)
)
AS
BEGIN
DECLARE @PMPERMITLIST AS RecordIDs
INSERT INTO @PMPERMITLIST (RECORDID) VALUES (@ID)
EXEC [permit].[USP_PMPERMIT_GETBYIDS] @PMPERMITLIST, NULL
END