CREATE PROCEDURE [application].[USP_PLAPPLICATIONADDRESS_GETBYIDS]
(
	@PLAPPLICATIONLIST RecordIDs READONLY
)
AS
BEGIN
	SELECT 
		PLAPPLICATIONADDRESS.PLAPPLICATIONID,
		PLAPPLICATIONADDRESS.PLAPPLICATIONADDRESSID, 
		MAILINGADDRESS.ADDRESSLINE1,
		MAILINGADDRESS.ADDRESSLINE2,
		MAILINGADDRESS.ADDRESSLINE3,
		MAILINGADDRESS.ADDRESSTYPE,
		MAILINGADDRESS.ATTN,
		MAILINGADDRESS.CITY,
		MAILINGADDRESS.COMPSITE,
		MAILINGADDRESS.COUNTRY,
		MAILINGADDRESSCOUNTRYTYPE.MAILINGADDRESSCOUNTRYTYPEID,
		MAILINGADDRESSCOUNTRYTYPE.MAILINGADDRESSCOUNTRYTYPENAME,
		PLAPPLICATIONADDRESS.MAIN,
		MAILINGADDRESS.POBOX,
		MAILINGADDRESS.POSTALCODE,
		MAILINGADDRESS.POSTDIRECTION,
		MAILINGADDRESS.PREDIRECTION,
		MAILINGADDRESS.PROVINCE,
		MAILINGADDRESS.RURALROUTE,
		MAILINGADDRESS.STATE,
		MAILINGADDRESS.STATION,
		MAILINGADDRESS.STREETTYPE,
		MAILINGADDRESS.UNITORSUITE,
		MAILINGADDRESS.ADDRESSID
	FROM  [dbo].[PLAPPLICATIONADDRESS]
	JOIN MAILINGADDRESS ON PLAPPLICATIONADDRESS.MAILINGADDRESSID = MAILINGADDRESS.MAILINGADDRESSID
	JOIN MAILINGADDRESSCOUNTRYTYPE ON MAILINGADDRESS.COUNTRYTYPE = MAILINGADDRESSCOUNTRYTYPE.MAILINGADDRESSCOUNTRYTYPEID
	JOIN @PLAPPLICATIONLIST PLL ON PLAPPLICATIONADDRESS.PLAPPLICATIONID = PLL.RECORDID
	WHERE [dbo].[PLAPPLICATIONADDRESS].MAIN = 1
END