CREATE PROCEDURE [workflow].[USP_GET_BUSINESS_LICENSE_WORKFLOW_SUMMARY]
	@ID AS CHAR(36)
AS
SET NOCOUNT ON;

SELECT 
	BLLICENSEWFACTIONSTEP.WORKFLOWSTATUSID,
	COUNT(1) AS TOTAL
FROM
	BLLICENSEWFACTIONSTEP
INNER JOIN BLLICENSEWFSTEP ON BLLICENSEWFSTEP.BLLICENSEWFSTEPID = BLLICENSEWFACTIONSTEP.BLLICENSEWFSTEPID
wHERE 
	BLLICENSEWFSTEP.BLLICENSEID = @ID AND BLLICENSEWFACTIONSTEP.WORKFLOWSTATUSID NOT IN (4,3,2,7)
GROUP BY BLLICENSEWFACTIONSTEP.WORKFLOWSTATUSID