CREATE PROCEDURE [workflow].[USP_GET_PLAN_WORKFLOW_SUMMARY]
	@ID AS CHAR(36)
AS

SET NOCOUNT ON;

SELECT 
	PLPLANWFACTIONSTEP.WORKFLOWSTATUSID,
	COUNT(1) AS TOTAL
FROM
	PLPLANWFACTIONSTEP
INNER JOIN PLPLANWFSTEP ON PLPLANWFSTEP.PLPLANWFSTEPID = PLPLANWFACTIONSTEP.PLPLANWFSTEPID
wHERE 
	PLPLANWFSTEP.PLPLANID = @ID AND PLPLANWFACTIONSTEP.WORKFLOWSTATUSID NOT IN (4,3,2,7)
GROUP BY PLPLANWFACTIONSTEP.WORKFLOWSTATUSID