CREATE PROCEDURE [workflow].[USP_GET_FILEMARKUPS_BYSUBMITTALID]
	@SUBMITTALID CHAR(36)
AS
BEGIN
SET NOCOUNT ON; 
	SELECT		ERENTITYSESSION.ERENTITYSESSIONID, 
				ERFILEMARKUP.ERFILEMARKUPID,
				ERFILEMARKUP.ERPROJECTFILEVERSIONID,
				ERFILEMARKUP.AUTHOR,
				ERFILEMARKUP.MARKUPTYPE,
				ERFILEMARKUP.COMMENTS,
				ERFILEMARKUP.CREATEDON,
				ERFILEMARKUP.FILENAME,
				ERFILEMARKUP.PAGENUMBER,
				ERFILEMARKUP.CREATEDBY,
				USERS.FNAME USERFIRSTNAME,
				USERS.LNAME USERLASTNAME
	FROM		PLSUBMITTAL 
	INNER JOIN	PLSUBMITTALFILEVERSION ON PLSUBMITTALFILEVERSION.PLSUBMITTALID = PLSUBMITTAL.PLSUBMITTALID
	INNER JOIN	ERPROJECTFILEVERSION ON ERPROJECTFILEVERSION.ERPROJECTFILEVERSIONID = PLSUBMITTALFILEVERSION.ERPROJECTFILEVERSIONID
	INNER JOIN	ERENTITYSESSION AS ERENTITYSESSION ON PLSUBMITTALFILEVERSION.PLSUBMITTALID = ERENTITYSESSION.PLSUBMITTALID
	INNER JOIN	ERFILEMARKUP AS ERFILEMARKUP ON (ERPROJECTFILEVERSION.ERPROJECTFILEVERSIONID = ERFILEMARKUP.ERPROJECTFILEVERSIONID) AND (ERFILEMARKUP.ERENTITYSESSIONID = ERENTITYSESSION.ERENTITYSESSIONID)
	LEFT JOIN	USERS ON USERS.SUSERGUID = ERFILEMARKUP.CREATEDBY
	WHERE		ERPROJECTFILEVERSION.MARKDELETE = 0
	AND			PLSUBMITTAL.PLSUBMITTALID = @SUBMITTALID
	ORDER BY	ERFILEMARKUP.CREATEDON
END