CREATE PROCEDURE [workflow].[USP_GET_WORKFLOW_MODULE_BY_ENTITY_ID]
	@ID AS CHAR(36) 
AS

SET NOCOUNT ON;
-- word will match the enumeration in EnerGov, so please do not change the returned value
SELECT 'PermitManagement' FROM PMPERMIT WHERE PMPERMIT.PMPERMITID = @ID
UNION ALL
SELECT 'PlanManagement' FROM PLPLAN WHERE PLPLAN.PLPLANID = @ID
UNION ALL
SELECT 'ProfessionalLicense' FROM ILLICENSE WHERE ILLICENSE.ILLICENSEID = @ID
UNION ALL
SELECT 'BusinessLicense' FROM BLLICENSE WHERE BLLICENSE.BLLICENSEID = @ID
UNION ALL
SELECT 'CodeManagement' FROM CMCODECASE WHERE CMCODECASE.CMCODECASEID = @ID