CREATE PROCEDURE [workflow].[USP_GET_RECENT_WORKFLOW_ACTION_DETAILS]
	@ACTIONS [workflow].[ACTIONS_WITH_TYPES] READONLY
AS
/*
ReceiveSubmittal = 1,
HoldMeeting = 2,
HoldHearing = 3,
StopWorkflow = 4,
GenericAction = 5,
Inspection = 6,
CreatePlanCase = 7,
CreateSubPermit = 8,
Violation = 9,
PlanActivity = 10,
PermitActivity = 11
CodeActivity = 12
CreateReport = 13,
LicenseActivity = 14,
Task = 15,
InspectionCase = 16,
ProfessionalLicenseActivity = 17,
ExamRequest = 18,
ExamSitting = 19,
AssessFees = 20,
CreateObjectCase = 21,
CreateCodeCase = 22,
CreateWorkOrder = 23,
CreateBusinessLicense = 24,
    
*/
SET NOCOUNT ON;
IF EXISTS(SELECT * FROM @ACTIONS AS ACTIONS WHERE ACTIONS.ActionTypeId = 11)
BEGIN
	SELECT 
		dbo.PMPERMITACTIVITY.CREATEDON,
		dbo.USERS.FNAME + ' ' + dbo.USERS.LNAME AS USERNAME,
		ACTIONS.ActionId,
		ACTIONS.ActionTypeId
	FROM dbo.PMPERMITACTIVITY
	INNER JOIN @ACTIONS AS ACTIONS ON ACTIONS.ActionId = dbo.PMPERMITACTIVITY.PMPERMITWFACTIONSTEPID AND ACTIONS.ActionTypeId = 11
	LEFT OUTER JOIN dbo.USERS ON dbo.USERS.SUSERGUID = dbo.PMPERMITACTIVITY.SUSERGUID
END

IF EXISTS(SELECT * FROM @ACTIONS AS ACTIONS WHERE ACTIONS.ActionTypeId = 12)
BEGIN
	SELECT 
		dbo.CMCODEACTIVITY.CREATEDON,
		dbo.USERS.FNAME + ' ' + dbo.USERS.LNAME AS USERNAME,
		ACTIONS.ActionId,
		ACTIONS.ActionTypeId
	FROM dbo.CMCODEACTIVITY
	INNER JOIN @ACTIONS AS ACTIONS ON ACTIONS.ActionId = dbo.CMCODEACTIVITY.CMCODEWFACTIONSTEPID AND ACTIONS.ActionTypeId = 12
	LEFT OUTER JOIN dbo.USERS ON dbo.USERS.SUSERGUID = dbo.CMCODEACTIVITY.SUSERGUID
END

IF EXISTS(SELECT * FROM @ACTIONS AS ACTIONS WHERE ACTIONS.ActionTypeId = 22)
BEGIN
	SELECT 
		dbo.CMCODECASE.CLOSEDDATE,
		dbo.CMCODECASESTATUS.NAME AS STATUSNAME,
		dbo.CMCASETYPE.NAME AS TYPENAME,
		ACTIONS.ActionId,
		ACTIONS.ActionTypeId
	FROM dbo.CMCODECASEACTIONREF
	INNER JOIN dbo.CMCODECASE ON dbo.CMCODECASE.CMCODECASEID = dbo.CMCODECASEACTIONREF.CMCODECASEID
	INNER JOIN dbo.CMCODECASESTATUS ON dbo.CMCODECASESTATUS.CMCODECASESTATUSID = dbo.CMCODECASE.CMCODECASESTATUSID
	INNER JOIN dbo.CMCASETYPE ON dbo.CMCASETYPE.CMCASETYPEID = dbo.CMCODECASE.CMCASETYPEID
	INNER JOIN @ACTIONS AS ACTIONS ON ACTIONS.ActionId = dbo.CMCODECASEACTIONREF.CMCODECASEACTIONREFID AND ACTIONS.ActionTypeId = 22
END

IF EXISTS(SELECT * FROM @ACTIONS AS ACTIONS WHERE ACTIONS.ActionTypeId = 3)
BEGIN
	SELECT 
		dbo.HEARINGSTATUS.NAME AS STATUSNAME,
		dbo.HEARINGTYPE.NAME AS TYPENAME,
		dbo.HEARING.STARTDATE,
		dbo.HEARING.ENDDATE,
		dbo.HEARING.LOCATION,
		ACTIONS.ActionId,
		ACTIONS.ActionTypeId
	FROM dbo.HEARINGXREF
	INNER JOIN dbo.HEARING ON dbo.HEARING.HEARINGID = dbo.HEARINGXREF.HEARINGID
	INNER JOIN dbo.HEARINGSTATUS ON dbo.HEARINGSTATUS.HEARINGSTATUSID = dbo.HEARING.HEARINGSTATUSID
	INNER JOIN dbo.HEARINGTYPE ON dbo.HEARINGTYPE.HEARINGTYPEID = dbo.HEARING.HEARINGTYPEID
	INNER JOIN @ACTIONS AS ACTIONS ON ACTIONS.ActionId = dbo.HEARINGXREF.OBJECTID AND ACTIONS.ActionTypeId = 3
END

IF EXISTS(SELECT * FROM @ACTIONS AS ACTIONS WHERE ACTIONS.ActionTypeId = 6)
BEGIN
	SELECT 
		dbo.IMINSPECTIONSTATUS.STATUSNAME,
		dbo.IMINSPECTION.SCHEDULEDSTARTDATE,
		dbo.IMINSPECTION.ACTUALSTARTDATE,
		dbo.IMINSPECTION.ACTUALENDDATE,
		INSPECTORS_DATA.FNAME + ' ' + INSPECTORS_DATA.LNAME AS ASSIGNEDTO,
		ACTIONS.ActionId,
		ACTIONS.ActionTypeId
	FROM dbo.IMINSPECTIONACTREF
	INNER JOIN dbo.IMINSPECTION ON dbo.IMINSPECTION.IMINSPECTIONID = dbo.IMINSPECTIONACTREF.IMINSPECTIONID
	INNER JOIN dbo.IMINSPECTIONSTATUS ON dbo.IMINSPECTIONSTATUS.IMINSPECTIONSTATUSID = dbo.IMINSPECTION.IMINSPECTIONSTATUSID
	OUTER APPLY (
		SELECT TOP 1 
			dbo.IMINSPECTORREF.INSPECTIONID, 
			dbo.USERS.LNAME,
			dbo.USERS.FNAME
		FROM dbo.IMINSPECTORREF 
		INNER JOIN dbo.USERS ON dbo.USERS.SUSERGUID = dbo.IMINSPECTORREF.USERID
		WHERE dbo.IMINSPECTORREF.INSPECTIONID = dbo.IMINSPECTION.IMINSPECTIONID
		ORDER BY dbo.IMINSPECTORREF.BPRIMARY DESC
	) AS INSPECTORS_DATA
	INNER JOIN @ACTIONS AS ACTIONS ON ACTIONS.ActionId = dbo.IMINSPECTIONACTREF.OBJECTID AND ACTIONS.ActionTypeId = 6
END

IF EXISTS(SELECT * FROM @ACTIONS AS ACTIONS WHERE ACTIONS.ActionTypeId = 2)
BEGIN
	SELECT 
		dbo.MEETINGTYPE.NAME AS TYPENAME,
		dbo.MEETING.STARTDATE,
		dbo.MEETING.ENDDATE,
		dbo.MEETING.LOCATION,
		ACTIONS.ActionId,
		ACTIONS.ActionTypeId
	FROM dbo.MEETINGXREF
	INNER JOIN dbo.MEETING ON dbo.MEETING.MEETINGID = dbo.MEETINGXREF.MEETINGID
	INNER JOIN dbo.MEETINGTYPE ON dbo.MEETINGTYPE.MEETINGTYPEID = dbo.MEETING.MEETINGTYPEID
	INNER JOIN @ACTIONS AS ACTIONS ON ACTIONS.ActionId = dbo.MEETINGXREF.OBJECTID AND ACTIONS.ActionTypeId = 2
END

IF EXISTS(SELECT * FROM @ACTIONS AS ACTIONS WHERE ACTIONS.ActionTypeId = 21)
BEGIN
	SELECT 
		dbo.OMOBJECTTYPE.NAME AS TYPENAME,
		dbo.OMOBJECTSTATUS.NAME AS STATUSNAME,
		dbo.OMOBJECT.OPERATIONENDDATE,
		ACTIONS.ActionId,
		ACTIONS.ActionTypeId
	FROM dbo.OMOBJECTACTIONREF
	INNER JOIN dbo.OMOBJECT ON dbo.OMOBJECT.OMOBJECTID = dbo.OMOBJECTACTIONREF.OMOBJECTID
	INNER JOIN dbo.OMOBJECTTYPE ON dbo.OMOBJECTTYPE.OMOBJECTTYPEID = dbo.OMOBJECT.OMOBJECTTYPEID
	INNER JOIN dbo.OMOBJECTSTATUS ON dbo.OMOBJECTSTATUS.OMOBJECTSTATUSID = dbo.OMOBJECT.OMOBJECTSTATUSID
	INNER JOIN @ACTIONS AS ACTIONS ON ACTIONS.ActionId = dbo.OMOBJECTACTIONREF.CASEID AND ACTIONS.ActionTypeId = 21
END

IF EXISTS(SELECT * FROM @ACTIONS AS ACTIONS WHERE ACTIONS.ActionTypeId = 8)
BEGIN
	SELECT 
		dbo.PMPERMITSTATUS.NAME AS STATUSNAME,
		dbo.PMPERMITTYPE.NAME AS TYPENAME,
		dbo.PMPERMITWORKCLASS.NAME AS WORKCLASSNAME,
		COALESCE(dbo.USERS.FNAME + ' ' + dbo.USERS.LNAME, '') AS ASSIGNEDTO,
		dbo.PMPERMIT.FINALIZEDATE,
		ACTIONS.ActionId,
		ACTIONS.ActionTypeId
	FROM dbo.PMPERMITACTIONREF
	INNER JOIN dbo.PMPERMIT ON dbo.PMPERMIT.PMPERMITID = dbo.PMPERMITACTIONREF.PMPERMITID
	INNER JOIN dbo.PMPERMITSTATUS ON dbo.PMPERMITSTATUS.PMPERMITSTATUSID = dbo.PMPERMIT.PMPERMITSTATUSID
	INNER JOIN dbo.PMPERMITTYPE ON dbo.PMPERMITTYPE.PMPERMITTYPEID = dbo.PMPERMIT.PMPERMITTYPEID
	INNER JOIN dbo.PMPERMITWORKCLASS ON dbo.PMPERMITWORKCLASS.PMPERMITWORKCLASSID = dbo.PMPERMIT.PMPERMITWORKCLASSID
	LEFT OUTER JOIN dbo.USERS ON dbo.USERS.SUSERGUID = dbo.PMPERMIT.ASSIGNEDTO
	INNER JOIN @ACTIONS AS ACTIONS ON ACTIONS.ActionId = dbo.PMPERMITACTIONREF.OBJECTID AND ACTIONS.ActionTypeId = 8
END

IF EXISTS(SELECT * FROM @ACTIONS AS ACTIONS WHERE ACTIONS.ActionTypeId = 10)
BEGIN
	SELECT 
		dbo.PLPLANACTIVITY.CREATEDON,
		dbo.USERS.FNAME + ' ' + dbo.USERS.LNAME AS USERNAME,
		ACTIONS.ActionId,
		ACTIONS.ActionTypeId
	FROM dbo.PLPLANACTIVITY
	INNER JOIN @ACTIONS AS ACTIONS ON ACTIONS.ActionId = dbo.PLPLANACTIVITY.PLPLANWFACTIONSTEPID AND ACTIONS.ActionTypeId = 10
	LEFT OUTER JOIN dbo.USERS ON dbo.USERS.SUSERGUID = dbo.PLPLANACTIVITY.SUSERGUID
END

IF EXISTS(SELECT * FROM @ACTIONS AS ACTIONS WHERE ACTIONS.ActionTypeId = 7)
BEGIN
	SELECT 
		dbo.PLPLANSTATUS.NAME AS STATUSNAME,
		dbo.PLPLANTYPE.PLANNAME AS TYPENAME,
		dbo.PLPLANWORKCLASS.NAME AS WORKCLASSNAME,
		COALESCE(dbo.USERS.FNAME + ' ' + dbo.USERS.LNAME, '') AS ASSIGNEDTO,
		PLPLAN.COMPLETEDATE,
		ACTIONS.ActionId,
		ACTIONS.ActionTypeId
	FROM dbo.PLPLANACTIONREF
	INNER JOIN dbo.PLPLAN ON dbo.PLPLAN.PLPLANID = dbo.PLPLANACTIONREF.PLPLANID
	INNER JOIN dbo.PLPLANSTATUS ON dbo.PLPLANSTATUS.PLPLANSTATUSID = dbo.PLPLAN.PLPLANSTATUSID
	INNER JOIN dbo.PLPLANTYPE ON dbo.PLPLANTYPE.PLPLANTYPEID = dbo.PLPLAN.PLPLANTYPEID
	INNER JOIN dbo.PLPLANWORKCLASS ON dbo.PLPLANWORKCLASS.PLPLANWORKCLASSID = dbo.PLPLAN.PLPLANWORKCLASSID
	LEFT OUTER JOIN dbo.USERS ON dbo.USERS.SUSERGUID = dbo.PLPLAN.ASSIGNEDTO
	INNER JOIN @ACTIONS AS ACTIONS ON ACTIONS.ActionId = dbo.PLPLANACTIONREF.OBJECTID AND ACTIONS.ActionTypeId = 7
END

IF EXISTS(SELECT * FROM @ACTIONS AS ACTIONS WHERE ACTIONS.ActionTypeId = 13)
BEGIN
	SELECT 
		dbo.RPTREPORT.FRIENDLYNAME,
		ACTIONS.ActionId,
		ACTIONS.ActionTypeId
	FROM dbo.RPTREPORT
	INNER JOIN @ACTIONS AS ACTIONS ON ACTIONS.RelatedId = dbo.RPTREPORT.RPTREPORTID AND ACTIONS.ActionTypeId = 13
END

IF EXISTS(SELECT * FROM @ACTIONS AS ACTIONS WHERE ACTIONS.ActionTypeId = 1)
BEGIN
	SELECT 
		dbo.PLSUBMITTAL.PLSUBMITTALID,
		dbo.PLSUBMITTAL.COMPLETEDATE,
		dbo.PLSUBMITTALSTATUS.NAME AS STATUSNAME,
		dbo.PLSUBMITTAL.DUEDATE,
		ACTIONS.ActionId,
		ACTIONS.ActionTypeId
	FROM dbo.PLSUBMITTAL
	INNER JOIN dbo.PLSUBMITTALSTATUS ON dbo.PLSUBMITTALSTATUS.PLSUBMITTALSTATUSID = dbo.PLSUBMITTAL.PLSUBMITTALSTATUSID
	INNER JOIN @ACTIONS AS ACTIONS ON ACTIONS.RelatedId = dbo.PLSUBMITTAL.PLSUBMITTALID AND ACTIONS.ActionTypeId = 1

	SELECT 
		dbo.PLSUBMITTAL.PLSUBMITTALID,
		dbo.PLITEMREVIEWTYPE.NAME AS TYPENAME,
		dbo.PLSUBMITTAL.DUEDATE,
		dbo.USERS.FNAME,
		dbo.USERS.LNAME,
		ACTIONS.ActionId,
		ACTIONS.ActionTypeId
	FROM dbo.PLSUBMITTAL
	INNER JOIN dbo.PLITEMREVIEW ON dbo.PLITEMREVIEW.PLSUBMITTALID = dbo.PLSUBMITTAL.PLSUBMITTALID
	INNER JOIN dbo.PLITEMREVIEWTYPE ON dbo.PLITEMREVIEWTYPE.PLITEMREVIEWTYPEID = dbo.PLITEMREVIEW.PLITEMREVIEWTYPEID
	LEFT OUTER JOIN dbo.USERS ON dbo.USERS.SUSERGUID = dbo.PLITEMREVIEW.ASSIGNEDUSERID
	INNER JOIN @ACTIONS AS ACTIONS ON ACTIONS.RelatedId = dbo.PLSUBMITTAL.PLSUBMITTALID AND ACTIONS.ActionTypeId = 1
	WHERE dbo.PLITEMREVIEW.COMPLETED = 0 AND dbo.PLITEMREVIEW.NOTREQUIRED = 0
	ORDER BY dbo.PLITEMREVIEW.PRIORITYORDER, dbo.PLITEMREVIEWTYPE.NAME
END


IF EXISTS(SELECT * FROM @ACTIONS AS ACTIONS WHERE ACTIONS.ActionTypeId = 15)
BEGIN
	SELECT 
		dbo.TASKSTATUS.TASKSTATUSNAME AS STATUSNAME,
		dbo.TASKTYPE.NAME AS TYPENAME,
		dbo.TASK.DUEDATE,
		dbo.TASK.COMPLETEDDATE,
		dbo.TASKPRIORITY.TASKPRIORITYNAME,
		ACTIONS.ActionId,
		ACTIONS.ActionTypeId
	FROM dbo.TASKWFREF
	INNER JOIN dbo.TASK ON dbo.TASK.TASKID = dbo.TASKWFREF.TASKID
	INNER JOIN dbo.TASKSTATUS ON dbo.TASKSTATUS.TASKSTATUSID = dbo.TASK.TASKSTATUSID
	INNER JOIN dbo.TASKTYPE ON dbo.TASKTYPE.TASKTYPEID = dbo.TASK.TASKTYPEID
	INNER JOIN dbo.TASKPRIORITY ON dbo.TASKPRIORITY.TASKPRIORITYID = dbo.TASK.TASKPRIORITYID
	INNER JOIN @ACTIONS AS ACTIONS ON ACTIONS.ActionId = dbo.TASKWFREF.TASKWFREFID AND ACTIONS.ActionTypeId = 15
END

IF EXISTS(SELECT * FROM @ACTIONS AS ACTIONS WHERE ACTIONS.ActionTypeId = 9)
BEGIN
	SELECT 
		dbo.CMCODE.CODENUMBER,
		dbo.CMVIOLATIONSTATUS.NAME AS STATUSNAME,
		dbo.CMVIOLATION.COMPLIANCEDATE,
		dbo.CMVIOLATION.RESOLVEDDATE,
		ACTIONS.ActionId,
		ACTIONS.ActionTypeId
	FROM dbo.CMVIOLATION
	INNER JOIN dbo.CMCODE ON dbo.CMCODE.CMCODEID = dbo.CMVIOLATION.CMCODEID
	INNER JOIN dbo.CMVIOLATIONSTATUS ON dbo.CMVIOLATIONSTATUS.CMVIOLATIONSTATUSID = dbo.CMVIOLATION.CMVIOLATIONSTATUSID
	INNER JOIN @ACTIONS AS ACTIONS ON ACTIONS.ActionId = dbo.CMVIOLATION.CMCODEWFACTIONID AND ACTIONS.ActionTypeId = 9
END

IF EXISTS(SELECT * FROM @ACTIONS AS ACTIONS WHERE ACTIONS.ActionTypeId = 23)
BEGIN
	SELECT 
		dbo.PMPERMITWORKORDER.WORKORDERTYPENAME,
		dbo.PMPERMITWORKORDER.WORKORDERTYPECLASSNAME,
		dbo.PMPERMITWORKORDER.WORKORDERSTATUSNAME,
		ACTIONS.ActionId,
		ACTIONS.ActionTypeId
	FROM dbo.PMPERMITWORKORDER
	INNER JOIN @ACTIONS AS ACTIONS ON ACTIONS.ActionId = dbo.PMPERMITWORKORDER.PMPERMITWFACTIONSTEPID AND ACTIONS.ActionTypeId = 23
END