CREATE TABLE [dbo].[QUERYACTIONSETVALUE] (
    [QUERYACTIONSETVALUEID]        CHAR (36)      NOT NULL,
    [QUERYACTIONID]                CHAR (36)      NOT NULL,
    [SETVALUEFIELD]                NVARCHAR (MAX) NOT NULL,
    [SETVALUEFIELDFRIENDLYNAME]    NVARCHAR (50)  NOT NULL,
    [SETVALUEFIELDVALUE]           NVARCHAR (MAX) NOT NULL,
    [SETVALUEFIELDADJUSTMENTVALUE] NVARCHAR (MAX) NULL,
    [SETVALUEWEEKDAYSONLY]         BIT            DEFAULT ((0)) NOT NULL,
    [SETVALUEUSEPREVIOUSWEEKDAY]   BIT            DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_QUERYACTIONSETVALUE] PRIMARY KEY CLUSTERED ([QUERYACTIONSETVALUEID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_QUERYACTIONSETVALUE_Q] FOREIGN KEY ([QUERYACTIONID]) REFERENCES [dbo].[QUERYACTION] ([QUERYACTIONID])
);


GO
CREATE NONCLUSTERED INDEX [QUERYACTIONSETVALUE_QUERYACTIONID]
    ON [dbo].[QUERYACTIONSETVALUE]([QUERYACTIONID] ASC);


GO

CREATE TRIGGER [dbo].[TG_QUERYACTIONSETVALUE_UPDATE]
   ON  [dbo].[QUERYACTIONSETVALUE]
   AFTER UPDATE
AS 
BEGIN	
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
    (	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )	
	SELECT
			[QUERY].[QUERYID], 
			[QUERY].[ROWVERSION],
			GETUTCDATE(),
			[QUERY].[LASTCHANGEDBY],
			'Set Value Field',
			[deleted].[SETVALUEFIELD],
			[inserted].[SETVALUEFIELD],
			'Intelligent Query Action (' + [QUERY].[NAME] + '), Action (' + [QUERYACTION].[ACTIONNAME] +'), Action Type (' + [QUERYACTIONTYPE].[NAME] + ')',
			'C08776DA-046E-4E9B-9DE4-4CC2005A98CD',
			2,
			0,
			[QUERYACTION].[ACTIONNAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[QUERYACTIONID] = [inserted].[QUERYACTIONID]
			INNER JOIN [QUERYACTION] ON [QUERYACTION].[QUERYACTIONID] = [inserted].[QUERYACTIONID]
			INNER JOIN [QUERY] ON [QUERY].[QUERYID] = [QUERYACTION].[QUERYID]
			INNER JOIN [QUERYACTIONTYPE] WITH (NOLOCK) ON [QUERYACTIONTYPE].[QUERYACTIONTYPEID] = [QUERYACTION].[QUERYACTIONTYPEID]
	WHERE	[deleted].[SETVALUEFIELD] <> [inserted].[SETVALUEFIELD]

	UNION ALL
	SELECT
			[QUERY].[QUERYID], 
			[QUERY].[ROWVERSION],
			GETUTCDATE(),
			[QUERY].[LASTCHANGEDBY],
			'Field To Set',
			[deleted].[SETVALUEFIELDFRIENDLYNAME],
			[inserted].[SETVALUEFIELDFRIENDLYNAME],
			'Intelligent Query Action (' + [QUERY].[NAME] + '), Action (' + [QUERYACTION].[ACTIONNAME] +'), Action Type (' + [QUERYACTIONTYPE].[NAME] + ')',
			'C08776DA-046E-4E9B-9DE4-4CC2005A98CD',
			2,
			0,
			[QUERYACTION].[ACTIONNAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[QUERYACTIONID] = [inserted].[QUERYACTIONID]
			INNER JOIN [QUERYACTION] ON [QUERYACTION].[QUERYACTIONID] = [inserted].[QUERYACTIONID]
			INNER JOIN [QUERY] ON [QUERY].[QUERYID] = [QUERYACTION].[QUERYID]
			INNER JOIN [QUERYACTIONTYPE] WITH (NOLOCK) ON [QUERYACTIONTYPE].[QUERYACTIONTYPEID] = [QUERYACTION].[QUERYACTIONTYPEID]
	WHERE	[deleted].[SETVALUEFIELDFRIENDLYNAME] <> [inserted].[SETVALUEFIELDFRIENDLYNAME]

	UNION ALL
	SELECT
			[QUERY].[QUERYID], 
			[QUERY].[ROWVERSION],
			GETUTCDATE(),
			[QUERY].[LASTCHANGEDBY],
			'Enter New Value',
			[deleted].[SETVALUEFIELDVALUE],
			[inserted].[SETVALUEFIELDVALUE],
			'Intelligent Query Action (' + [QUERY].[NAME] + '), Action (' + [QUERYACTION].[ACTIONNAME] +'), Action Type (' + [QUERYACTIONTYPE].[NAME] + ')',
			'C08776DA-046E-4E9B-9DE4-4CC2005A98CD',
			2,
			0,
			[QUERYACTION].[ACTIONNAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[QUERYACTIONID] = [inserted].[QUERYACTIONID]
			INNER JOIN [QUERYACTION] ON [QUERYACTION].[QUERYACTIONID] = [inserted].[QUERYACTIONID]
			INNER JOIN [QUERY] ON [QUERY].[QUERYID] = [QUERYACTION].[QUERYID]
			INNER JOIN [QUERYACTIONTYPE] WITH (NOLOCK) ON [QUERYACTIONTYPE].[QUERYACTIONTYPEID] = [QUERYACTION].[QUERYACTIONTYPEID]
	WHERE	[deleted].[SETVALUEFIELDVALUE] <> [inserted].[SETVALUEFIELDVALUE]

	UNION ALL
	SELECT
			[QUERY].[QUERYID], 
			[QUERY].[ROWVERSION],
			GETUTCDATE(),
			[QUERY].[LASTCHANGEDBY],
			'Enter Adjustment Value',
			ISNULL([deleted].[SETVALUEFIELDADJUSTMENTVALUE],'[none]'),
			ISNULL([inserted].[SETVALUEFIELDADJUSTMENTVALUE],'[none]'),
			'Intelligent Query Action (' + [QUERY].[NAME] + '), Action (' + [QUERYACTION].[ACTIONNAME] +'), Action Type (' + [QUERYACTIONTYPE].[NAME] + ')',
			'C08776DA-046E-4E9B-9DE4-4CC2005A98CD',
			2,
			0,
			[QUERYACTION].[ACTIONNAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[QUERYACTIONID] = [inserted].[QUERYACTIONID]
			INNER JOIN [QUERYACTION] ON [QUERYACTION].[QUERYACTIONID] = [inserted].[QUERYACTIONID]
			INNER JOIN [QUERY] ON [QUERY].[QUERYID] = [QUERYACTION].[QUERYID]
			INNER JOIN [QUERYACTIONTYPE] WITH (NOLOCK) ON [QUERYACTIONTYPE].[QUERYACTIONTYPEID] = [QUERYACTION].[QUERYACTIONTYPEID]
	WHERE	ISNULL([deleted].[SETVALUEFIELDADJUSTMENTVALUE],'') <> ISNULL([inserted].[SETVALUEFIELDADJUSTMENTVALUE],'')

	UNION ALL
	SELECT
			[QUERY].[QUERYID], 
			[QUERY].[ROWVERSION],
			GETUTCDATE(),
			[QUERY].[LASTCHANGEDBY],
			'Set Value Weekday Only Flag',
			CASE [deleted].[SETVALUEWEEKDAYSONLY]  WHEN 1 THEN 'Yes' ELSE 'No' END,
			CASE [inserted].[SETVALUEWEEKDAYSONLY]  WHEN 1 THEN 'Yes' ELSE 'No' END,
			'Intelligent Query Action (' + [QUERY].[NAME] + '), Action (' + [QUERYACTION].[ACTIONNAME] +'), Action Type (' + [QUERYACTIONTYPE].[NAME] + ')',
			'C08776DA-046E-4E9B-9DE4-4CC2005A98CD',
			2,
			0,
			[QUERYACTION].[ACTIONNAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[QUERYACTIONID] = [inserted].[QUERYACTIONID]
			INNER JOIN [QUERYACTION] ON [QUERYACTION].[QUERYACTIONID] = [inserted].[QUERYACTIONID]
			INNER JOIN [QUERY] ON [QUERY].[QUERYID] = [QUERYACTION].[QUERYID]
			INNER JOIN [QUERYACTIONTYPE] WITH (NOLOCK) ON [QUERYACTIONTYPE].[QUERYACTIONTYPEID] = [QUERYACTION].[QUERYACTIONTYPEID]
	WHERE	[deleted].[SETVALUEWEEKDAYSONLY] <> [inserted].[SETVALUEWEEKDAYSONLY]

	UNION ALL
	SELECT
			[QUERY].[QUERYID], 
			[QUERY].[ROWVERSION],
			GETUTCDATE(),
			[QUERY].[LASTCHANGEDBY],
			'Set Value Use Previous Weekday Flag',
			CASE [deleted].[SETVALUEUSEPREVIOUSWEEKDAY]  WHEN 1 THEN 'Yes' ELSE 'No' END,
			CASE [inserted].[SETVALUEUSEPREVIOUSWEEKDAY]  WHEN 1 THEN 'Yes' ELSE 'No' END,
			'Intelligent Query Action (' + [QUERY].[NAME] + '), Action (' + [QUERYACTION].[ACTIONNAME] +'), Action Type (' + [QUERYACTIONTYPE].[NAME] + ')',
			'C08776DA-046E-4E9B-9DE4-4CC2005A98CD',
			2,
			0,
			[QUERYACTION].[ACTIONNAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[QUERYACTIONID] = [inserted].[QUERYACTIONID]
			INNER JOIN [QUERYACTION] ON [QUERYACTION].[QUERYACTIONID] = [inserted].[QUERYACTIONID]
			INNER JOIN [QUERY] ON [QUERY].[QUERYID] = [QUERYACTION].[QUERYID]
			INNER JOIN [QUERYACTIONTYPE] WITH (NOLOCK) ON [QUERYACTIONTYPE].[QUERYACTIONTYPEID] = [QUERYACTION].[QUERYACTIONTYPEID]
	WHERE	[deleted].[SETVALUEUSEPREVIOUSWEEKDAY] <> [inserted].[SETVALUEUSEPREVIOUSWEEKDAY]
END