CREATE TABLE [dbo].[QUERYACTIONSOCIALNETWORK] (
    [QUERYACTIONSOCIALNETWORKID] VARCHAR (36)   NOT NULL,
    [QUERYACTIONID]              CHAR (36)      NOT NULL,
    [TEXT]                       NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_QUERYACTIONSOCIALNETWORK] PRIMARY KEY CLUSTERED ([QUERYACTIONSOCIALNETWORKID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_QASOCIALNETWORK_QA] FOREIGN KEY ([QUERYACTIONID]) REFERENCES [dbo].[QUERYACTION] ([QUERYACTIONID])
);


GO
CREATE NONCLUSTERED INDEX [QUERYACTIONSOCIALNETWORK_QUERYACTIONID]
    ON [dbo].[QUERYACTIONSOCIALNETWORK]([QUERYACTIONID] ASC);


GO

CREATE TRIGGER [dbo].[TG_QUERYACTIONSOCIALNETWORK_UPDATE]
   ON  [dbo].[QUERYACTIONSOCIALNETWORK]
   AFTER UPDATE
AS 
BEGIN	
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
    (	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )	
	SELECT
			[QUERY].[QUERYID], 
			[QUERY].[ROWVERSION],
			GETUTCDATE(),
			[QUERY].[LASTCHANGEDBY],
			'Body',
			[deleted].[TEXT],
			[inserted].[TEXT],
			'Intelligent Query Action (' + [QUERY].[NAME] + '), Action (' + [QUERYACTION].[ACTIONNAME] +'), Action Type (' + [QUERYACTIONTYPE].[NAME] + ')',
			'C08776DA-046E-4E9B-9DE4-4CC2005A98CD',
			2,
			0,
			[QUERYACTION].[ACTIONNAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[QUERYACTIONID] = [inserted].[QUERYACTIONID]
			INNER JOIN [QUERYACTION] ON [QUERYACTION].[QUERYACTIONID] = [inserted].[QUERYACTIONID]
			INNER JOIN [QUERY] ON [QUERY].[QUERYID] = [QUERYACTION].[QUERYID]
			INNER JOIN [QUERYACTIONTYPE] WITH (NOLOCK) ON [QUERYACTIONTYPE].[QUERYACTIONTYPEID] = [QUERYACTION].[QUERYACTIONTYPEID]
	WHERE	[deleted].[TEXT] <> [inserted].[TEXT]
END