CREATE TABLE [dbo].[WFENTITYSTEPTYPE] (
    [WFENTITYID]   INT NOT NULL,
    [WFSTEPTYPEID] INT NOT NULL,
    CONSTRAINT [PK_WFEntityStepType] PRIMARY KEY CLUSTERED ([WFENTITYID] ASC, [WFSTEPTYPEID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_WFEntityStepType_WFEntity] FOREIGN KEY ([WFENTITYID]) REFERENCES [dbo].[WFENTITY] ([WFENTITYID]),
    CONSTRAINT [FK_WFEntityStepType_WFStepType] FOREIGN KEY ([WFSTEPTYPEID]) REFERENCES [dbo].[WFSTEPTYPE] ([WFSTEPTYPEID])
);

