CREATE TABLE [dbo].[WFTEMPLATESTEP] (
    [WFTEMPLATESTEPID] CHAR (36) NOT NULL,
    [WFTEMPLATEID]     CHAR (36) NOT NULL,
    [WFSTEPID]         CHAR (36) NOT NULL,
    [PRIORITYORDER]    INT       NOT NULL,
    [SORTORDER]        INT       DEFAULT ((0)) NOT NULL,
    [AUTOFILL]         BIT       CONSTRAINT [DF_WFTemplateStep_AutoFill] DEFAULT ((1)) NOT NULL,
    [NOPRIORITY]       BIT       DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_WFTemplateStep_1] PRIMARY KEY CLUSTERED ([WFTEMPLATESTEPID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_WFTemplateStep_WFStep] FOREIGN KEY ([WFSTEPID]) REFERENCES [dbo].[WFSTEP] ([WFSTEPID]),
    CONSTRAINT [FK_WFTemplateStep_WFTemplate] FOREIGN KEY ([WFTEMPLATEID]) REFERENCES [dbo].[WFTEMPLATE] ([WFTEMPLATEID])
);


GO
CREATE TRIGGER [dbo].[TG_WFTEMPLATESTEP_DELETE]  
   ON  [dbo].[WFTEMPLATESTEP] 
   AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
	(
		[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
	)
	SELECT
		[WFTEMPLATE].[WFTEMPLATEID],
		[WFTEMPLATE].[ROWVERSION],
		GETUTCDATE(),			
		(SELECT dbo.UFN_GET_USERID_FROM_CONTEXT_INFO()),
		'Workflow Template Workflow Step Deleted',
        '',
        '',       
		'Workflow Template (' + [WFTEMPLATE].[NAME] + '), Workflow Step Name (' + [WFSTEP].[NAME] +')',
		'4828BC29-4760-4E15-8B16-E6AFCD835AB8',
		3,
		0,
		[WFSTEP].[NAME]
    FROM [deleted]
	INNER JOIN [WFTEMPLATE] ON [WFTEMPLATE].[WFTEMPLATEID] = [deleted].[WFTEMPLATEID]
	INNER JOIN [WFSTEP] WITH (NOLOCK) ON [WFSTEP].[WFSTEPID] = [deleted].[WFSTEPID]
END
GO
CREATE TRIGGER [dbo].[TG_WFTEMPLATESTEP_INSERT]
   ON  [dbo].[WFTEMPLATESTEP]
   AFTER INSERT
AS 
BEGIN	
	SET NOCOUNT ON;	
	INSERT INTO [HISTORYSYSTEMSETUP]
    (
        [ID],
        [ROWVERSION],
        [CHANGEDON],
        [CHANGEDBY],
        [FIELDNAME],
        [OLDVALUE],
        [NEWVALUE],
        [ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT 
        [WFTEMPLATE].[WFTEMPLATEID], 
        [WFTEMPLATE].[ROWVERSION],
        GETUTCDATE(),
        [WFTEMPLATE].[LASTCHANGEDBY],	
        'Workflow Template Workflow Step Added',
        '',
        '',       
		'Workflow Template (' + [WFTEMPLATE].[NAME] + '), Workflow Step Name (' + [WFSTEP].[NAME] +')',
		'4828BC29-4760-4E15-8B16-E6AFCD835AB8',
		1,
		0,
		[WFSTEP].[NAME]
    FROM [inserted]
	INNER JOIN [WFTEMPLATE] ON [WFTEMPLATE].[WFTEMPLATEID] = [inserted].[WFTEMPLATEID]
	INNER JOIN [WFSTEP] WITH (NOLOCK) ON [WFSTEP].[WFSTEPID] = [inserted].[WFSTEPID]
END
GO
CREATE TRIGGER [dbo].[TG_WFTEMPLATESTEP_UPDATE]
   ON  [dbo].[WFTEMPLATESTEP]
   AFTER UPDATE
AS 
BEGIN	
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
    (	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )	
	SELECT
			[WFTEMPLATE].[WFTEMPLATEID],
			[WFTEMPLATE].[ROWVERSION],
			GETUTCDATE(),
			[WFTEMPLATE].[LASTCHANGEDBY],
			'Step Priority Order',
			CONVERT(NVARCHAR(MAX), [deleted].[PRIORITYORDER]),
			CONVERT(NVARCHAR(MAX), [inserted].[PRIORITYORDER]),
			'Workflow Template (' + [WFTEMPLATE].[NAME] + '), Workflow Step Name (' + [WFSTEP].[NAME] +')',
			'4828BC29-4760-4E15-8B16-E6AFCD835AB8',
			2,
			0,
			[WFSTEP].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[WFTEMPLATESTEPID] = [inserted].[WFTEMPLATESTEPID]
			INNER JOIN [WFTEMPLATE] ON [WFTEMPLATE].[WFTEMPLATEID] = [inserted].[WFTEMPLATEID]
			INNER JOIN [WFSTEP] WITH (NOLOCK) ON [WFSTEP].[WFSTEPID] = [inserted].[WFSTEPID]
	WHERE	[deleted].[PRIORITYORDER] <> [inserted].[PRIORITYORDER]
	UNION ALL
	SELECT
			[WFTEMPLATE].[WFTEMPLATEID],
			[WFTEMPLATE].[ROWVERSION],
			GETUTCDATE(),
			[WFTEMPLATE].[LASTCHANGEDBY],
			'Step Sort Order',
			CONVERT(NVARCHAR(MAX), [deleted].[SORTORDER]),
			CONVERT(NVARCHAR(MAX), [inserted].[SORTORDER]),
			'Workflow Template (' + [WFTEMPLATE].[NAME] + '), Workflow Step Name (' + [WFSTEP].[NAME] +')',
			'4828BC29-4760-4E15-8B16-E6AFCD835AB8',
			2,
			0,
			[WFSTEP].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[WFTEMPLATESTEPID] = [inserted].[WFTEMPLATESTEPID]
			INNER JOIN [WFTEMPLATE] ON [WFTEMPLATE].[WFTEMPLATEID] = [inserted].[WFTEMPLATEID]
			INNER JOIN [WFSTEP] WITH (NOLOCK) ON [WFSTEP].[WFSTEPID] = [inserted].[WFSTEPID]
	WHERE	[deleted].[SORTORDER] <> [inserted].[SORTORDER]
	UNION ALL
	SELECT
			[WFTEMPLATE].[WFTEMPLATEID],
			[WFTEMPLATE].[ROWVERSION],
			GETUTCDATE(),
			[WFTEMPLATE].[LASTCHANGEDBY],
			'Auto Fill Flag',
			CASE [deleted].[AUTOFILL]  WHEN 1 THEN 'Yes' ELSE 'No' END,
			CASE [inserted].[AUTOFILL] WHEN 1 THEN 'Yes' ELSE 'No' END,
			'Workflow Template (' + [WFTEMPLATE].[NAME] + '), Workflow Step Name (' + [WFSTEP].[NAME] +')',
			'4828BC29-4760-4E15-8B16-E6AFCD835AB8',
			2,
			0,
			[WFSTEP].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[WFTEMPLATESTEPID] = [inserted].[WFTEMPLATESTEPID]
			INNER JOIN [WFTEMPLATE] ON [WFTEMPLATE].[WFTEMPLATEID] = [inserted].[WFTEMPLATEID]
			INNER JOIN [WFSTEP] WITH (NOLOCK) ON [WFSTEP].[WFSTEPID] = [inserted].[WFSTEPID]
	WHERE	[deleted].[AUTOFILL] <> [inserted].[AUTOFILL]
	UNION ALL
	SELECT
			[WFTEMPLATE].[WFTEMPLATEID],
			[WFTEMPLATE].[ROWVERSION],
			GETUTCDATE(),
			[WFTEMPLATE].[LASTCHANGEDBY],
			'No Priority Flag',
			CASE [deleted].[NOPRIORITY]	 WHEN 1 THEN 'Yes' ELSE 'No' END,
			CASE [inserted].[NOPRIORITY] WHEN 1 THEN 'Yes' ELSE 'No' END,
			'Workflow Template (' + [WFTEMPLATE].[NAME] + '), Workflow Step Name (' + [WFSTEP].[NAME] +')',
			'4828BC29-4760-4E15-8B16-E6AFCD835AB8',
			2,
			0,
			[WFSTEP].[NAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[WFTEMPLATESTEPID] = [inserted].[WFTEMPLATESTEPID]
			INNER JOIN [WFTEMPLATE] ON [WFTEMPLATE].[WFTEMPLATEID] = [inserted].[WFTEMPLATEID]
			INNER JOIN [WFSTEP] WITH (NOLOCK) ON [WFSTEP].[WFSTEPID] = [inserted].[WFSTEPID]
	WHERE	[deleted].[NOPRIORITY] <> [inserted].[NOPRIORITY]
END