CREATE TABLE [dbo].[WORKFLOWACTIONSETCALENDARDUEDA] (
    [WORKFLOWACTIONSETCALEDUEDTID] CHAR (36)      NOT NULL,
    [WORKFLOWACTIONID]             CHAR (36)      NOT NULL,
    [SETVALUEFIELD]                NVARCHAR (MAX) NOT NULL,
    [SETVALUEFIELDFRIENDLYNAME]    NVARCHAR (50)  NOT NULL,
    CONSTRAINT [PK_WorkflowActionSetCalendarDueDate] PRIMARY KEY CLUSTERED ([WORKFLOWACTIONSETCALEDUEDTID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_WorkflowActionSetCalendarDueDate_WorkflowAction] FOREIGN KEY ([WORKFLOWACTIONID]) REFERENCES [dbo].[WORKFLOWACTION] ([WORKFLOWACTIONID])
);


GO
CREATE NONCLUSTERED INDEX [WORKFLOWACTIONSETCALENDARDUEDA_WORKFLOWACTIONID]
    ON [dbo].[WORKFLOWACTIONSETCALENDARDUEDA]([WORKFLOWACTIONID] ASC);


GO

CREATE TRIGGER [dbo].[TG_WORKFLOWACTIONSETCALENDARDUEDA_UPDATE]
   ON  [dbo].[WORKFLOWACTIONSETCALENDARDUEDA]
   AFTER UPDATE
AS 
BEGIN	
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
    (	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )	
	SELECT
			[WORKFLOW].[WORKFLOWID], 
			[WORKFLOW].[ROWVERSION],
			GETUTCDATE(),
			[WORKFLOW].[LASTCHANGEDBY],
			'Set Value Field',
			[deleted].[SETVALUEFIELD],
			[inserted].[SETVALUEFIELD],
			'Intelligent Object (' + [WORKFLOW].[WORKFLOWNAME] + '), Action (' + [WORKFLOWACTION].[ACTIONNAME] +'), Action Type (' + [WORKFLOWACTIONTYPE].[WORKFLOWACTIONTYPENAME] + ')',
			'F053A756-19BE-4A42-A70D-185D5B01C31A',
			2,
			0,
			[WORKFLOWACTION].[ACTIONNAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[WORKFLOWACTIONID] = [inserted].[WORKFLOWACTIONID]
			INNER JOIN [WORKFLOWACTION] ON [WORKFLOWACTION].[WORKFLOWACTIONID] = [inserted].[WORKFLOWACTIONID]
			INNER JOIN [WORKFLOW] ON [WORKFLOW].[WORKFLOWID] = [WORKFLOWACTION].[WORKFLOWID]
			INNER JOIN [WORKFLOWACTIONTYPE] WITH (NOLOCK) ON [WORKFLOWACTIONTYPE].[WORKFLOWACTIONTYPEID] = [WORKFLOWACTION].[WORKFLOWACTIONTYPEID]
	WHERE	[deleted].[SETVALUEFIELD] <> [inserted].[SETVALUEFIELD]

	UNION ALL
	SELECT
			[WORKFLOW].[WORKFLOWID], 
			[WORKFLOW].[ROWVERSION],
			GETUTCDATE(),
			[WORKFLOW].[LASTCHANGEDBY],
			'Set Value Field Friendly Name',
			[deleted].[SETVALUEFIELDFRIENDLYNAME],
			[inserted].[SETVALUEFIELDFRIENDLYNAME],
			'Intelligent Object (' + [WORKFLOW].[WORKFLOWNAME] + '), Action (' + [WORKFLOWACTION].[ACTIONNAME] +'), Action Type (' + [WORKFLOWACTIONTYPE].[WORKFLOWACTIONTYPENAME] + ')',
			'F053A756-19BE-4A42-A70D-185D5B01C31A',
			2,
			0,
			[WORKFLOWACTION].[ACTIONNAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[WORKFLOWACTIONID] = [inserted].[WORKFLOWACTIONID]
			INNER JOIN [WORKFLOWACTION] ON [WORKFLOWACTION].[WORKFLOWACTIONID] = [inserted].[WORKFLOWACTIONID]
			INNER JOIN [WORKFLOW] ON [WORKFLOW].[WORKFLOWID] = [WORKFLOWACTION].[WORKFLOWID]
			INNER JOIN [WORKFLOWACTIONTYPE] WITH (NOLOCK) ON [WORKFLOWACTIONTYPE].[WORKFLOWACTIONTYPEID] = [WORKFLOWACTION].[WORKFLOWACTIONTYPEID]
	WHERE	[deleted].[SETVALUEFIELDFRIENDLYNAME] <> [inserted].[SETVALUEFIELDFRIENDLYNAME]
END