CREATE TABLE [dbo].[WORKFLOWPROPERTYCONDITIONTYPE] (
    [WORKFLOWPROPERTYCONDTYPEID] INT           NOT NULL,
    [PROPERTYCONDITIONTYPENAME]  NVARCHAR (20) NULL,
    CONSTRAINT [PK_WorkflowPropertyConditionTy] PRIMARY KEY CLUSTERED ([WORKFLOWPROPERTYCONDTYPEID] ASC) WITH (FILLFACTOR = 90)
);

