CREATE TABLE [dbo].[WORKFLOWCONDITION] (
    [WORKFLOWCONDITIONID]           CHAR (36)      NOT NULL,
    [WORKFLOWCONDITIONGROUPID]      CHAR (36)      NOT NULL,
    [CLASSNAME]                     NVARCHAR (MAX) NOT NULL,
    [FRIENDLYCLASSNAME]             NVARCHAR (MAX) NOT NULL,
    [PROPERTYNAME]                  NVARCHAR (MAX) NULL,
    [FRIENDLYPROPERTYNAME]          NVARCHAR (MAX) NULL,
    [WORKFLOWCLASSCONDITIONTYPEID]  INT            NULL,
    [WORKFLOWPROPERTYCONDTYPEID]    INT            NULL,
    [PROPERTYCONDITIONCOMPAREVALUE] NVARCHAR (MAX) NULL,
    [CONDITIONNUMBER]               INT            NOT NULL,
    [WORKFLOWCONTROLTYPEID]         INT            NOT NULL,
    [CUSTOMFIELDNAME]               NVARCHAR (MAX) CONSTRAINT [DF_CustomFieldNam_WC] DEFAULT ('') NOT NULL,
    [CUSTOMFIELDTABLE]              NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_WorkflowCondition] PRIMARY KEY CLUSTERED ([WORKFLOWCONDITIONID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_WFCondition_WFClassConditio] FOREIGN KEY ([WORKFLOWCLASSCONDITIONTYPEID]) REFERENCES [dbo].[WORKFLOWCLASSCONDITIONTYPE] ([WORKFLOWCLASSCONDITIONTYPEID]),
    CONSTRAINT [FK_WFCondition_WFConditionGrou] FOREIGN KEY ([WORKFLOWCONDITIONGROUPID]) REFERENCES [dbo].[WORKFLOWCONDITIONGROUP] ([WORKFLOWCONDITIONGROUPID]),
    CONSTRAINT [FK_WFCondition_WFControlType] FOREIGN KEY ([WORKFLOWCONTROLTYPEID]) REFERENCES [dbo].[WORKFLOWCONTROLTYPE] ([WORKFLOWCONTROLTYPEID]),
    CONSTRAINT [FK_WFCondition_WFPropertyCondi] FOREIGN KEY ([WORKFLOWPROPERTYCONDTYPEID]) REFERENCES [dbo].[WORKFLOWPROPERTYCONDITIONTYPE] ([WORKFLOWPROPERTYCONDTYPEID])
);


GO
CREATE NONCLUSTERED INDEX [WorkflowCondition_WorkflowID]
    ON [dbo].[WORKFLOWCONDITION]([WORKFLOWCONDITIONGROUPID] ASC) WITH (FILLFACTOR = 90);


GO

CREATE TRIGGER [dbo].[TG_WORKFLOWCONDITION_DELETE]
	ON [dbo].[WORKFLOWCONDITION]
	AFTER DELETE
AS
BEGIN
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
	(
        [ID],
        [ROWVERSION],
        [CHANGEDON],
        [CHANGEDBY],
        [FIELDNAME],
        [OLDVALUE],
        [NEWVALUE],
        [ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT
		[WORKFLOW].[WORKFLOWID],
		[WORKFLOW].[ROWVERSION],
		GETUTCDATE(),
		(SELECT dbo.UFN_GET_USERID_FROM_CONTEXT_INFO()),
		'Workflow Condition Deleted',
		'',
		'',
		'Intelligent Object (' + [WORKFLOW].[WORKFLOWNAME] + '), Workflow Condition (' + COALESCE(NULLIF([deleted].[FRIENDLYPROPERTYNAME],''),[deleted].[FRIENDLYCLASSNAME]) +')',
		'F053A756-19BE-4A42-A70D-185D5B01C31A',
		3,
		0,
		'Workflow Condition (' + COALESCE(NULLIF([deleted].[FRIENDLYPROPERTYNAME],''),[deleted].[FRIENDLYCLASSNAME]) +')'
	FROM [deleted]
	INNER JOIN [WORKFLOWCONDITIONGROUP] ON  [deleted].[WORKFLOWCONDITIONGROUPID] = [WORKFLOWCONDITIONGROUP].[WORKFLOWCONDITIONGROUPID] 
	INNER JOIN [WORKFLOW] ON [WORKFLOWCONDITIONGROUP].[WORKFLOWID] = [WORKFLOW].[WORKFLOWID]
END
GO

CREATE TRIGGER [dbo].[TG_WORKFLOWCONDITION_UPDATE]
	ON [dbo].[WORKFLOWCONDITION]
	AFTER UPDATE
AS
BEGIN
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
	(
        [ID],
        [ROWVERSION],
        [CHANGEDON],
        [CHANGEDBY],
        [FIELDNAME],
        [OLDVALUE],
        [NEWVALUE],
        [ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT
		[WORKFLOW].[WORKFLOWID],
		[WORKFLOW].[ROWVERSION],
		GETUTCDATE(),
		[WORKFLOW].[LASTCHANGEDBY],
		'Class Condition Type',
		CASE [deleted].[WORKFLOWCLASSCONDITIONTYPEID] WHEN NULL THEN '[none]' ELSE
		(SELECT CLASSCONDITIONTYPENAME FROM WORKFLOWCLASSCONDITIONTYPE WHERE WORKFLOWCLASSCONDITIONTYPEID = [deleted].[WORKFLOWCLASSCONDITIONTYPEID])
		END,
		CASE [inserted].[WORKFLOWCLASSCONDITIONTYPEID] WHEN NULL THEN '[none]' ELSE
		(SELECT CLASSCONDITIONTYPENAME FROM WORKFLOWCLASSCONDITIONTYPE WHERE WORKFLOWCLASSCONDITIONTYPEID = [inserted].[WORKFLOWCLASSCONDITIONTYPEID])
		END,
		'Intelligent Object (' + [WORKFLOW].[WORKFLOWNAME] + '), Workflow Condition (' + COALESCE(NULLIF([deleted].[FRIENDLYPROPERTYNAME],''),[deleted].[FRIENDLYCLASSNAME]) +')',
		'F053A756-19BE-4A42-A70D-185D5B01C31A',
		2,
		0,
		'Workflow Condition (' + COALESCE(NULLIF([deleted].[FRIENDLYPROPERTYNAME],''),[deleted].[FRIENDLYCLASSNAME]) +')'
FROM [deleted]
INNER JOIN [inserted] ON [deleted].[WORKFLOWCONDITIONID] = [inserted].[WORKFLOWCONDITIONID]
INNER JOIN [WORKFLOWCONDITIONGROUP] ON [deleted].[WORKFLOWCONDITIONGROUPID] = [WORKFLOWCONDITIONGROUP].[WORKFLOWCONDITIONGROUPID]
INNER JOIN [WORKFLOW] ON [WORKFLOWCONDITIONGROUP].[WORKFLOWID] = [WORKFLOW].[WORKFLOWID]
WHERE ISNULL([deleted].[WORKFLOWCLASSCONDITIONTYPEID],'') <> ISNULL([inserted].[WORKFLOWCLASSCONDITIONTYPEID],'')
UNION ALL
SELECT
		[WORKFLOW].[WORKFLOWID],
		[WORKFLOW].[ROWVERSION],
		GETUTCDATE(),
		[WORKFLOW].[LASTCHANGEDBY],
		'Property Condition Type',
		CASE [deleted].[WORKFLOWPROPERTYCONDTYPEID] WHEN NULL THEN '[none]' ELSE
		(SELECT PROPERTYCONDITIONTYPENAME FROM WORKFLOWPROPERTYCONDITIONTYPE WHERE WORKFLOWPROPERTYCONDTYPEID = [deleted].[WORKFLOWPROPERTYCONDTYPEID])
		END,
		CASE [inserted].[WORKFLOWPROPERTYCONDTYPEID] WHEN NULL THEN '[none]' ELSE
		(SELECT PROPERTYCONDITIONTYPENAME FROM WORKFLOWPROPERTYCONDITIONTYPE WHERE WORKFLOWPROPERTYCONDTYPEID = [inserted].[WORKFLOWPROPERTYCONDTYPEID])
		END,
		'Intelligent Object (' + [WORKFLOW].[WORKFLOWNAME] + '), Workflow Condition (' + COALESCE(NULLIF([deleted].[FRIENDLYPROPERTYNAME],''),[deleted].[FRIENDLYCLASSNAME]) +')',
		'F053A756-19BE-4A42-A70D-185D5B01C31A',
		2,
		0,
		'Workflow Condition (' + COALESCE(NULLIF([deleted].[FRIENDLYPROPERTYNAME],''),[deleted].[FRIENDLYCLASSNAME]) +')'
FROM [deleted]
INNER JOIN [inserted] on [deleted].[WORKFLOWCONDITIONID] = [inserted].[WORKFLOWCONDITIONID]
INNER JOIN [WORKFLOWCONDITIONGROUP] ON [deleted].[WORKFLOWCONDITIONGROUPID] = [WORKFLOWCONDITIONGROUP].[WORKFLOWCONDITIONGROUPID]
INNER JOIN [WORKFLOW] ON [WORKFLOWCONDITIONGROUP].[WORKFLOWID] = [WORKFLOW].[WORKFLOWID]
WHERE ISNULL([deleted].[WORKFLOWPROPERTYCONDTYPEID],'') <> ISNULL([inserted].[WORKFLOWPROPERTYCONDTYPEID],'')
UNION ALL

--All fields excluding dropdown but including GeoRulesCallerType
SELECT
		[WORKFLOW].[WORKFLOWID],
		[WORKFLOW].[ROWVERSION],
		GETUTCDATE(),
		[WORKFLOW].[LASTCHANGEDBY],
		'Property Condition Compare Value',
		ISNULL([deleted].[PROPERTYCONDITIONCOMPAREVALUE],'[none]'),
		ISNULL([inserted].[PROPERTYCONDITIONCOMPAREVALUE],'[none]'),
		'Intelligent Object (' + [WORKFLOW].[WORKFLOWNAME] + '), Workflow Condition (' + COALESCE(NULLIF([deleted].[FRIENDLYPROPERTYNAME],''),[deleted].[FRIENDLYCLASSNAME]) +')',
		'F053A756-19BE-4A42-A70D-185D5B01C31A',
		2,
		0,
		'Workflow Condition (' + COALESCE(NULLIF([deleted].[FRIENDLYPROPERTYNAME],''),[deleted].[FRIENDLYCLASSNAME]) +')'
FROM [deleted]
INNER JOIN [inserted] on [deleted].[WORKFLOWCONDITIONID] = [inserted].[WORKFLOWCONDITIONID]
INNER JOIN [WORKFLOWCONDITIONGROUP] ON [deleted].[WORKFLOWCONDITIONGROUPID] = [WORKFLOWCONDITIONGROUP].[WORKFLOWCONDITIONGROUPID]
INNER JOIN [WORKFLOW] ON [WORKFLOWCONDITIONGROUP].[WORKFLOWID] = [WORKFLOW].[WORKFLOWID]
WHERE ISNULL([deleted].[PROPERTYCONDITIONCOMPAREVALUE],'') <> ISNULL([inserted].[PROPERTYCONDITIONCOMPAREVALUE],'')
AND ([deleted].[WORKFLOWCONTROLTYPEID] <> 1 OR [deleted].[PROPERTYNAME] = 'GeoRulesCallerType')
UNION ALL

--Regular dropdown fields with integer as unique id
SELECT
		[WORKFLOW].[WORKFLOWID],
		[WORKFLOW].[ROWVERSION],
		GETUTCDATE(),
		[WORKFLOW].[LASTCHANGEDBY],
		'Property Condition Compare Value',
		ISNULL(
		CASE [deleted].[PROPERTYCONDITIONCOMPAREVALUE] WHEN NULL THEN '[none]' 
		ELSE
		(SELECT [STRINGVALUE] FROM [LOOKUPVIEWFORINTEGERS] WHERE [UNIQUEID] = [deleted].[PROPERTYCONDITIONCOMPAREVALUE]
		AND [TABLENAME] IN
		(SELECT TOP 1 [dbo].[METADATACLASSPROPERTY].[LOOKUPTABLENAME] 
		FROM [METADATACLASS] JOIN [METADATACLASSPROPERTY]
		ON [METADATACLASS].[ID] = [METADATACLASSPROPERTY].[PARENTID] 
		WHERE [METADATACLASS].[TYPEFULLNAME] = [deleted].[CLASSNAME] AND 
		[METADATACLASSPROPERTY].[NAME] = [deleted].[PROPERTYNAME]))
		END,[deleted].[PROPERTYCONDITIONCOMPAREVALUE] ),
		ISNULL(
		CASE [inserted].[PROPERTYCONDITIONCOMPAREVALUE] WHEN NULL THEN '[none]' 
		ELSE
		(SELECT [STRINGVALUE] FROM [LOOKUPVIEWFORINTEGERS] WHERE [UNIQUEID] = [inserted].[PROPERTYCONDITIONCOMPAREVALUE]
		AND [TABLENAME] IN
		(SELECT TOP 1 [dbo].[METADATACLASSPROPERTY].[LOOKUPTABLENAME] FROM [METADATACLASS] JOIN [METADATACLASSPROPERTY]
		ON [METADATACLASS].[ID] = [METADATACLASSPROPERTY].[PARENTID] 
		WHERE [METADATACLASS].[TYPEFULLNAME] = [inserted].[CLASSNAME] AND 
		[METADATACLASSPROPERTY].[NAME] = [inserted].[PROPERTYNAME]))
		END,[inserted].[PROPERTYCONDITIONCOMPAREVALUE]  ),
		'Intelligent Object (' + [WORKFLOW].[WORKFLOWNAME] + '), Workflow Condition (' + COALESCE(NULLIF([deleted].[FRIENDLYPROPERTYNAME],''),[deleted].[FRIENDLYCLASSNAME]) +')',
		'F053A756-19BE-4A42-A70D-185D5B01C31A',
		2,
		0,
		'Workflow Condition (' + COALESCE(NULLIF([deleted].[FRIENDLYPROPERTYNAME],''),[deleted].[FRIENDLYCLASSNAME]) +')'
FROM [deleted]
INNER JOIN [inserted] on [deleted].[WORKFLOWCONDITIONID] = [inserted].[WORKFLOWCONDITIONID]
INNER JOIN [WORKFLOWCONDITIONGROUP] ON [deleted].[WORKFLOWCONDITIONGROUPID] = [WORKFLOWCONDITIONGROUP].[WORKFLOWCONDITIONGROUPID]
INNER JOIN [WORKFLOW] ON [WORKFLOWCONDITIONGROUP].[WORKFLOWID] = [WORKFLOW].[WORKFLOWID]
WHERE ISNULL([deleted].[PROPERTYCONDITIONCOMPAREVALUE],'') <> ISNULL([inserted].[PROPERTYCONDITIONCOMPAREVALUE],'')
AND [deleted].[WORKFLOWCONTROLTYPEID] = 1 AND [deleted].[CUSTOMFIELDNAME] = '' AND
[deleted].[PROPERTYNAME] <> 'GeoRulesCallerType' AND
(ISNUMERIC([deleted].[PROPERTYCONDITIONCOMPAREVALUE]) = 1 OR ISNUMERIC([inserted].[PROPERTYCONDITIONCOMPAREVALUE]) = 1)
UNION ALL

--Regular dropdown fields with guid as unique id
SELECT
		[WORKFLOW].[WORKFLOWID],
		[WORKFLOW].[ROWVERSION],
		GETUTCDATE(),
		[WORKFLOW].[LASTCHANGEDBY],
		'Property Condition Compare Value',
		ISNULL(
		CASE [deleted].[PROPERTYCONDITIONCOMPAREVALUE] WHEN NULL THEN '[none]' 
		ELSE
		(SELECT [STRINGVALUE] FROM [LOOKUPVIEW] 
		WHERE [UNIQUEID] = [deleted].[PROPERTYCONDITIONCOMPAREVALUE]
		AND [TABLENAME] IN
		(SELECT TOP 1 [dbo].[METADATACLASSPROPERTY].[LOOKUPTABLENAME] 
		FROM [METADATACLASS] JOIN [METADATACLASSPROPERTY]
		ON [METADATACLASS].[ID] = [METADATACLASSPROPERTY].[PARENTID] 
		WHERE [METADATACLASS].[TYPEFULLNAME] = [deleted].[CLASSNAME] AND 
		[METADATACLASSPROPERTY].[NAME] = [deleted].[PROPERTYNAME]))
		END,[deleted].[PROPERTYCONDITIONCOMPAREVALUE]),
	    ISNULL(
		CASE [inserted].[PROPERTYCONDITIONCOMPAREVALUE] WHEN NULL THEN '[none]' 
		ELSE
		(SELECT [STRINGVALUE] FROM [LOOKUPVIEW] 
		WHERE [UNIQUEID] = [inserted].[PROPERTYCONDITIONCOMPAREVALUE]
		AND [TABLENAME] IN
		(SELECT TOP 1 [dbo].[METADATACLASSPROPERTY].[LOOKUPTABLENAME] 
		FROM [METADATACLASS] JOIN [METADATACLASSPROPERTY]
		ON [METADATACLASS].[ID] = [METADATACLASSPROPERTY].[PARENTID] 
		WHERE [METADATACLASS].[TYPEFULLNAME] = [inserted].[CLASSNAME] AND 
		[METADATACLASSPROPERTY].[NAME] = [inserted].[PROPERTYNAME]))
		END,[inserted].[PROPERTYCONDITIONCOMPAREVALUE]),
		'Intelligent Object (' + [WORKFLOW].[WORKFLOWNAME] + '), Workflow Condition (' + COALESCE(NULLIF([deleted].[FRIENDLYPROPERTYNAME],''),[deleted].[FRIENDLYCLASSNAME]) +')',
		'F053A756-19BE-4A42-A70D-185D5B01C31A',
		2,
		0,
		'Workflow Condition (' + COALESCE(NULLIF([deleted].[FRIENDLYPROPERTYNAME],''),[deleted].[FRIENDLYCLASSNAME]) +')'
FROM [deleted]
INNER JOIN [inserted] on [deleted].[WORKFLOWCONDITIONID] = [inserted].[WORKFLOWCONDITIONID]
INNER JOIN [WORKFLOWCONDITIONGROUP] ON [deleted].[WORKFLOWCONDITIONGROUPID] = [WORKFLOWCONDITIONGROUP].[WORKFLOWCONDITIONGROUPID]
INNER JOIN [WORKFLOW] ON [WORKFLOWCONDITIONGROUP].[WORKFLOWID] = [WORKFLOW].[WORKFLOWID]
WHERE ISNULL([deleted].[PROPERTYCONDITIONCOMPAREVALUE],'') <> ISNULL([inserted].[PROPERTYCONDITIONCOMPAREVALUE],'')
AND [deleted].[WORKFLOWCONTROLTYPEID] = 1 AND [deleted].[CUSTOMFIELDNAME] = '' AND
[deleted].[PROPERTYNAME] <> 'GeoRulesCallerType'
AND ISNUMERIC([deleted].[PROPERTYCONDITIONCOMPAREVALUE]) = 0
AND ISNUMERIC([inserted].[PROPERTYCONDITIONCOMPAREVALUE]) = 0
UNION ALL

--Custom field dropdown
SELECT
		[WORKFLOW].[WORKFLOWID],
		[WORKFLOW].[ROWVERSION],
		GETUTCDATE(),
		[WORKFLOW].[LASTCHANGEDBY],
		'Property Condition Compare Value',
		ISNULL(
		CASE [deleted].[PROPERTYCONDITIONCOMPAREVALUE] WHEN NULL THEN '[none]' ELSE
		(SELECT [SVALUE] FROM [CUSTOMFIELDPICKLISTITEM] 
		WHERE [GCUSTOMFIELDPICKLISTITEM] = [deleted].[PROPERTYCONDITIONCOMPAREVALUE])
		END,[deleted].[PROPERTYCONDITIONCOMPAREVALUE]),
		ISNULL(
		CASE [inserted].[PROPERTYCONDITIONCOMPAREVALUE] WHEN NULL THEN '[none]' 
		ELSE
		(SELECT [SVALUE] FROM [CUSTOMFIELDPICKLISTITEM] 
		WHERE [GCUSTOMFIELDPICKLISTITEM] = [inserted].[PROPERTYCONDITIONCOMPAREVALUE])
		END, [inserted].[PROPERTYCONDITIONCOMPAREVALUE]),
		'Intelligent Object (' + [WORKFLOW].[WORKFLOWNAME] + '), Workflow Condition (' + COALESCE(NULLIF([deleted].[FRIENDLYPROPERTYNAME],''),[deleted].[FRIENDLYCLASSNAME]) +')',
		'F053A756-19BE-4A42-A70D-185D5B01C31A',
		2,
		0,
		'Workflow Condition (' + COALESCE(NULLIF([deleted].[FRIENDLYPROPERTYNAME],''),[deleted].[FRIENDLYCLASSNAME]) +')'
FROM [deleted]
INNER JOIN [inserted] on [deleted].[WORKFLOWCONDITIONID] = [inserted].[WORKFLOWCONDITIONID]
INNER JOIN [WORKFLOWCONDITIONGROUP] ON [deleted].[WORKFLOWCONDITIONGROUPID] = [WORKFLOWCONDITIONGROUP].[WORKFLOWCONDITIONGROUPID]
INNER JOIN [WORKFLOW] ON [WORKFLOWCONDITIONGROUP].[WORKFLOWID] = [WORKFLOW].[WORKFLOWID]
WHERE ISNULL([deleted].[PROPERTYCONDITIONCOMPAREVALUE],'') <> ISNULL([inserted].[PROPERTYCONDITIONCOMPAREVALUE],'')
AND [deleted].[WORKFLOWCONTROLTYPEID] = 1 AND [deleted].[CUSTOMFIELDNAME] <> ''
END
GO
CREATE TRIGGER [dbo].[TG_WORKFLOWCONDITION_INSERT]
	ON [dbo].[WORKFLOWCONDITION]
	AFTER INSERT
AS
BEGIN
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
	(
        [ID],
        [ROWVERSION],
        [CHANGEDON],
        [CHANGEDBY],
        [FIELDNAME],
        [OLDVALUE],
        [NEWVALUE],
        [ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )
	SELECT
		[WORKFLOW].[WORKFLOWID],
		[WORKFLOW].[ROWVERSION],
		GETUTCDATE(),
		[WORKFLOW].[LASTCHANGEDBY],
		'Workflow Condition Added',
		'',
		'',
		'Intelligent Object (' + [WORKFLOW].[WORKFLOWNAME] + '), Workflow Condition (' + COALESCE(NULLIF([inserted].[FRIENDLYPROPERTYNAME],''),[inserted].[FRIENDLYCLASSNAME]) +')',
		'F053A756-19BE-4A42-A70D-185D5B01C31A',
		1,
		0,
		'Workflow Condition (' + COALESCE(NULLIF([inserted].[FRIENDLYPROPERTYNAME],''),[inserted].[FRIENDLYCLASSNAME]) +')'
	FROM [inserted]
	INNER JOIN [WORKFLOWCONDITIONGROUP] ON  [inserted].[WORKFLOWCONDITIONGROUPID] = [WORKFLOWCONDITIONGROUP].[WORKFLOWCONDITIONGROUPID] 
	INNER JOIN [WORKFLOW] ON [WORKFLOWCONDITIONGROUP].[WORKFLOWID] = [WORKFLOW].[WORKFLOWID]
END