CREATE TABLE [dbo].[WORKFLOWCLASSPARAM] (
    [WORKFLOWCLASSPARAMID] CHAR (36)       NOT NULL,
    [CLASSNAME]            NVARCHAR (1000) NOT NULL,
    [PARAMETERNAME]        NVARCHAR (250)  NOT NULL,
    [PARAMETERVALUE]       NVARCHAR (MAX)  NOT NULL,
    CONSTRAINT [PK_WorkFlowClassParam] PRIMARY KEY CLUSTERED ([WORKFLOWCLASSPARAMID] ASC) WITH (FILLFACTOR = 90)
);

