CREATE TABLE [dbo].[WORKFLOWACTIONTASK] (
    [WORKFLOWACTIONTASKID] CHAR (36)      NOT NULL,
    [WORKFLOWACTIONID]     CHAR (36)      NOT NULL,
    [TASKSUBJECT]          NVARCHAR (MAX) NOT NULL,
    [TASKTEXT]             NVARCHAR (MAX) NOT NULL,
    [STARTDATE]            NVARCHAR (MAX) NOT NULL,
    [DUEDATE]              NVARCHAR (MAX) NOT NULL,
    [STARTTIME]            NVARCHAR (MAX) NOT NULL,
    [DUETIME]              NVARCHAR (MAX) NOT NULL,
    [STARTDATEOFFSETDAYS]  INT            NOT NULL,
    [DUEDATEOFFSETDAYS]    INT            NOT NULL,
    [TASKPRIORITYID]       INT            NOT NULL,
    [SHOWONCALENDAR]       BIT            NOT NULL,
    [ASSIGNEDTO]           NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_WorkflowActionTask] PRIMARY KEY CLUSTERED ([WORKFLOWACTIONTASKID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_WTask_Action] FOREIGN KEY ([WORKFLOWACTIONID]) REFERENCES [dbo].[WORKFLOWACTION] ([WORKFLOWACTIONID]),
    CONSTRAINT [FK_WTask_TaskPriority] FOREIGN KEY ([TASKPRIORITYID]) REFERENCES [dbo].[TASKPRIORITY] ([TASKPRIORITYID])
);


GO
CREATE NONCLUSTERED INDEX [IX_WorkflowActionTask]
    ON [dbo].[WORKFLOWACTIONTASK]([WORKFLOWACTIONID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [WORKFLOWACTIONTASK_TASKPRIORITYID]
    ON [dbo].[WORKFLOWACTIONTASK]([TASKPRIORITYID] ASC);


GO

CREATE TRIGGER [dbo].[TG_WORKFLOWACTIONTASK_UPDATE]
   ON  [dbo].[WORKFLOWACTIONTASK]
   AFTER UPDATE
AS 
BEGIN	
	SET NOCOUNT ON;
	INSERT INTO [HISTORYSYSTEMSETUP]
    (	[ID],
		[ROWVERSION],
		[CHANGEDON],
		[CHANGEDBY],
		[FIELDNAME],
		[OLDVALUE],
		[NEWVALUE],
		[ADDITIONALINFO],
		[FORMID],
		[ACTION],
		[ISROOT],
		[RECORDNAME]
    )	
	SELECT
			[WORKFLOW].[WORKFLOWID], 
			[WORKFLOW].[ROWVERSION],
			GETUTCDATE(),
			[WORKFLOW].[LASTCHANGEDBY],
			'Assigned To',
			[deleted].[ASSIGNEDTO],
			[inserted].[ASSIGNEDTO],
			'Intelligent Object (' + [WORKFLOW].[WORKFLOWNAME] + '), Action (' + [WORKFLOWACTION].[ACTIONNAME] +'), Action Type (' + [WORKFLOWACTIONTYPE].[WORKFLOWACTIONTYPENAME] + ')',
			'F053A756-19BE-4A42-A70D-185D5B01C31A',
			2,
			0,
			[WORKFLOWACTION].[ACTIONNAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[WORKFLOWACTIONID] = [inserted].[WORKFLOWACTIONID]
			INNER JOIN [WORKFLOWACTION] ON [WORKFLOWACTION].[WORKFLOWACTIONID] = [inserted].[WORKFLOWACTIONID]
			INNER JOIN [WORKFLOW] ON [WORKFLOW].[WORKFLOWID] = [WORKFLOWACTION].[WORKFLOWID]
			INNER JOIN [WORKFLOWACTIONTYPE] WITH (NOLOCK) ON [WORKFLOWACTIONTYPE].[WORKFLOWACTIONTYPEID] = [WORKFLOWACTION].[WORKFLOWACTIONTYPEID]
	WHERE	[deleted].[ASSIGNEDTO] <> [inserted].[ASSIGNEDTO]

	UNION ALL
	SELECT
			[WORKFLOW].[WORKFLOWID], 
			[WORKFLOW].[ROWVERSION],
			GETUTCDATE(),
			[WORKFLOW].[LASTCHANGEDBY],
			'Subject',
			[deleted].[TASKSUBJECT],
			[inserted].[TASKSUBJECT],
			'Intelligent Object (' + [WORKFLOW].[WORKFLOWNAME] + '), Action (' + [WORKFLOWACTION].[ACTIONNAME] +'), Action Type (' + [WORKFLOWACTIONTYPE].[WORKFLOWACTIONTYPENAME] + ')',
			'F053A756-19BE-4A42-A70D-185D5B01C31A',
			2,
			0,
			[WORKFLOWACTION].[ACTIONNAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[WORKFLOWACTIONID] = [inserted].[WORKFLOWACTIONID]
			INNER JOIN [WORKFLOWACTION] ON [WORKFLOWACTION].[WORKFLOWACTIONID] = [inserted].[WORKFLOWACTIONID]
			INNER JOIN [WORKFLOW] ON [WORKFLOW].[WORKFLOWID] = [WORKFLOWACTION].[WORKFLOWID]
			INNER JOIN [WORKFLOWACTIONTYPE]WITH (NOLOCK)  ON [WORKFLOWACTIONTYPE].[WORKFLOWACTIONTYPEID] = [WORKFLOWACTION].[WORKFLOWACTIONTYPEID]
	WHERE	[deleted].[TASKSUBJECT] <> [inserted].[TASKSUBJECT]

	UNION ALL
	SELECT
			[WORKFLOW].[WORKFLOWID], 
			[WORKFLOW].[ROWVERSION],
			GETUTCDATE(),
			[WORKFLOW].[LASTCHANGEDBY],
			'Body',
			[deleted].[TASKTEXT],
			[inserted].[TASKTEXT],
			'Intelligent Object (' + [WORKFLOW].[WORKFLOWNAME] + '), Action (' + [WORKFLOWACTION].[ACTIONNAME] +'), Action Type (' + [WORKFLOWACTIONTYPE].[WORKFLOWACTIONTYPENAME] + ')',
			'F053A756-19BE-4A42-A70D-185D5B01C31A',
			2,
			0,
			[WORKFLOWACTION].[ACTIONNAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[WORKFLOWACTIONID] = [inserted].[WORKFLOWACTIONID]
			INNER JOIN [WORKFLOWACTION] ON [WORKFLOWACTION].[WORKFLOWACTIONID] = [inserted].[WORKFLOWACTIONID]
			INNER JOIN [WORKFLOW] ON [WORKFLOW].[WORKFLOWID] = [WORKFLOWACTION].[WORKFLOWID]
			INNER JOIN [WORKFLOWACTIONTYPE] WITH (NOLOCK) ON [WORKFLOWACTIONTYPE].[WORKFLOWACTIONTYPEID] = [WORKFLOWACTION].[WORKFLOWACTIONTYPEID]
	WHERE	[deleted].[TASKTEXT] <> [inserted].[TASKTEXT]

	UNION ALL
	SELECT
			[WORKFLOW].[WORKFLOWID], 
			[WORKFLOW].[ROWVERSION],
			GETUTCDATE(),
			[WORKFLOW].[LASTCHANGEDBY],
			'Start Date',
			[deleted].[STARTDATE],
			[inserted].[STARTDATE],
			'Intelligent Object (' + [WORKFLOW].[WORKFLOWNAME] + '), Action (' + [WORKFLOWACTION].[ACTIONNAME] +'), Action Type (' + [WORKFLOWACTIONTYPE].[WORKFLOWACTIONTYPENAME] + ')',
			'F053A756-19BE-4A42-A70D-185D5B01C31A',
			2,
			0,
			[WORKFLOWACTION].[ACTIONNAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[WORKFLOWACTIONID] = [inserted].[WORKFLOWACTIONID]
			INNER JOIN [WORKFLOWACTION] ON [WORKFLOWACTION].[WORKFLOWACTIONID] = [inserted].[WORKFLOWACTIONID]
			INNER JOIN [WORKFLOW] ON [WORKFLOW].[WORKFLOWID] = [WORKFLOWACTION].[WORKFLOWID]
			INNER JOIN [WORKFLOWACTIONTYPE] WITH (NOLOCK) ON [WORKFLOWACTIONTYPE].[WORKFLOWACTIONTYPEID] = [WORKFLOWACTION].[WORKFLOWACTIONTYPEID]
	WHERE	[deleted].[STARTDATE] <> [inserted].[STARTDATE]

	UNION ALL
	SELECT
			[WORKFLOW].[WORKFLOWID], 
			[WORKFLOW].[ROWVERSION],
			GETUTCDATE(),
			[WORKFLOW].[LASTCHANGEDBY],
			'Start Time',
			[deleted].[STARTTIME],
			[inserted].[STARTTIME],
			'Intelligent Object (' + [WORKFLOW].[WORKFLOWNAME] + '), Action (' + [WORKFLOWACTION].[ACTIONNAME] +'), Action Type (' + [WORKFLOWACTIONTYPE].[WORKFLOWACTIONTYPENAME] + ')',
			'F053A756-19BE-4A42-A70D-185D5B01C31A',
			2,
			0,
			[WORKFLOWACTION].[ACTIONNAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[WORKFLOWACTIONID] = [inserted].[WORKFLOWACTIONID]
			INNER JOIN [WORKFLOWACTION] ON [WORKFLOWACTION].[WORKFLOWACTIONID] = [inserted].[WORKFLOWACTIONID]
			INNER JOIN [WORKFLOW] ON [WORKFLOW].[WORKFLOWID] = [WORKFLOWACTION].[WORKFLOWID]
			INNER JOIN [WORKFLOWACTIONTYPE] WITH (NOLOCK) ON [WORKFLOWACTIONTYPE].[WORKFLOWACTIONTYPEID] = [WORKFLOWACTION].[WORKFLOWACTIONTYPEID]
	WHERE	[deleted].[STARTTIME] <> [inserted].[STARTTIME]

	UNION ALL
	SELECT
			[WORKFLOW].[WORKFLOWID], 
			[WORKFLOW].[ROWVERSION],
			GETUTCDATE(),
			[WORKFLOW].[LASTCHANGEDBY],
			'Start Offset Days',
			CONVERT(NVARCHAR(MAX), [deleted].[STARTDATEOFFSETDAYS]),
			CONVERT(NVARCHAR(MAX), [inserted].[STARTDATEOFFSETDAYS]),
			'Intelligent Object (' + [WORKFLOW].[WORKFLOWNAME] + '), Action (' + [WORKFLOWACTION].[ACTIONNAME] +'), Action Type (' + [WORKFLOWACTIONTYPE].[WORKFLOWACTIONTYPENAME] + ')',
			'F053A756-19BE-4A42-A70D-185D5B01C31A',
			2,
			0,
			[WORKFLOWACTION].[ACTIONNAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[WORKFLOWACTIONID] = [inserted].[WORKFLOWACTIONID]
			INNER JOIN [WORKFLOWACTION] ON [WORKFLOWACTION].[WORKFLOWACTIONID] = [inserted].[WORKFLOWACTIONID]
			INNER JOIN [WORKFLOW] ON [WORKFLOW].[WORKFLOWID] = [WORKFLOWACTION].[WORKFLOWID]
			INNER JOIN [WORKFLOWACTIONTYPE] WITH (NOLOCK) ON [WORKFLOWACTIONTYPE].[WORKFLOWACTIONTYPEID] = [WORKFLOWACTION].[WORKFLOWACTIONTYPEID]
	WHERE	[deleted].[STARTDATEOFFSETDAYS] <> [inserted].[STARTDATEOFFSETDAYS]

	UNION ALL
	SELECT
			[WORKFLOW].[WORKFLOWID], 
			[WORKFLOW].[ROWVERSION],
			GETUTCDATE(),
			[WORKFLOW].[LASTCHANGEDBY],
			'Due Date',
			[deleted].[DUEDATE],
			[inserted].[DUEDATE],
			'Intelligent Object (' + [WORKFLOW].[WORKFLOWNAME] + '), Action (' + [WORKFLOWACTION].[ACTIONNAME] +'), Action Type (' + [WORKFLOWACTIONTYPE].[WORKFLOWACTIONTYPENAME] + ')',
			'F053A756-19BE-4A42-A70D-185D5B01C31A',
			2,
			0,
			[WORKFLOWACTION].[ACTIONNAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[WORKFLOWACTIONID] = [inserted].[WORKFLOWACTIONID]
			INNER JOIN [WORKFLOWACTION] ON [WORKFLOWACTION].[WORKFLOWACTIONID] = [inserted].[WORKFLOWACTIONID]
			INNER JOIN [WORKFLOW] ON [WORKFLOW].[WORKFLOWID] = [WORKFLOWACTION].[WORKFLOWID]
			INNER JOIN [WORKFLOWACTIONTYPE] WITH (NOLOCK) ON [WORKFLOWACTIONTYPE].[WORKFLOWACTIONTYPEID] = [WORKFLOWACTION].[WORKFLOWACTIONTYPEID]
	WHERE	[deleted].[DUEDATE] <> [inserted].[DUEDATE]

	UNION ALL
	SELECT
			[WORKFLOW].[WORKFLOWID], 
			[WORKFLOW].[ROWVERSION],
			GETUTCDATE(),
			[WORKFLOW].[LASTCHANGEDBY],
			'Due Time',
			[deleted].[DUETIME],
			[inserted].[DUETIME],
			'Intelligent Object (' + [WORKFLOW].[WORKFLOWNAME] + '), Action (' + [WORKFLOWACTION].[ACTIONNAME] +'), Action Type (' + [WORKFLOWACTIONTYPE].[WORKFLOWACTIONTYPENAME] + ')',
			'F053A756-19BE-4A42-A70D-185D5B01C31A',
			2,
			0,
			[WORKFLOWACTION].[ACTIONNAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[WORKFLOWACTIONID] = [inserted].[WORKFLOWACTIONID]
			INNER JOIN [WORKFLOWACTION] ON [WORKFLOWACTION].[WORKFLOWACTIONID] = [inserted].[WORKFLOWACTIONID]
			INNER JOIN [WORKFLOW] ON [WORKFLOW].[WORKFLOWID] = [WORKFLOWACTION].[WORKFLOWID]
			INNER JOIN [WORKFLOWACTIONTYPE] WITH (NOLOCK) ON [WORKFLOWACTIONTYPE].[WORKFLOWACTIONTYPEID] = [WORKFLOWACTION].[WORKFLOWACTIONTYPEID]
	WHERE	[deleted].[DUETIME] <> [inserted].[DUETIME]

	UNION ALL
	SELECT
			[WORKFLOW].[WORKFLOWID], 
			[WORKFLOW].[ROWVERSION],
			GETUTCDATE(),
			[WORKFLOW].[LASTCHANGEDBY],
			'Due Offset Days',
			CONVERT(NVARCHAR(MAX), [deleted].[DUEDATEOFFSETDAYS]),
			CONVERT(NVARCHAR(MAX), [inserted].[DUEDATEOFFSETDAYS]),
			'Intelligent Object (' + [WORKFLOW].[WORKFLOWNAME] + '), Action (' + [WORKFLOWACTION].[ACTIONNAME] +'), Action Type (' + [WORKFLOWACTIONTYPE].[WORKFLOWACTIONTYPENAME] + ')',
			'F053A756-19BE-4A42-A70D-185D5B01C31A',
			2,
			0,
			[WORKFLOWACTION].[ACTIONNAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[WORKFLOWACTIONID] = [inserted].[WORKFLOWACTIONID]
			INNER JOIN [WORKFLOWACTION] ON [WORKFLOWACTION].[WORKFLOWACTIONID] = [inserted].[WORKFLOWACTIONID]
			INNER JOIN [WORKFLOW] ON [WORKFLOW].[WORKFLOWID] = [WORKFLOWACTION].[WORKFLOWID]
			INNER JOIN [WORKFLOWACTIONTYPE] WITH (NOLOCK) ON [WORKFLOWACTIONTYPE].[WORKFLOWACTIONTYPEID] = [WORKFLOWACTION].[WORKFLOWACTIONTYPEID]
	WHERE	[deleted].[DUEDATEOFFSETDAYS] <> [inserted].[DUEDATEOFFSETDAYS]

	UNION ALL
	SELECT
			[WORKFLOW].[WORKFLOWID], 
			[WORKFLOW].[ROWVERSION],
			GETUTCDATE(),
			[WORKFLOW].[LASTCHANGEDBY],
			'Priority',
			DELETETASKPRIORITY.[TASKPRIORITYNAME],
			INSERTTASKPRIORITY.[TASKPRIORITYNAME],
			'Intelligent Object (' + [WORKFLOW].[WORKFLOWNAME] + '), Action (' + [WORKFLOWACTION].[ACTIONNAME] +'), Action Type (' + [WORKFLOWACTIONTYPE].[WORKFLOWACTIONTYPENAME] + ')',
			'F053A756-19BE-4A42-A70D-185D5B01C31A',
			2,
			0,
			[WORKFLOWACTION].[ACTIONNAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[WORKFLOWACTIONID] = [inserted].[WORKFLOWACTIONID]
			INNER JOIN [WORKFLOWACTION] ON [WORKFLOWACTION].[WORKFLOWACTIONID] = [inserted].[WORKFLOWACTIONID]
			INNER JOIN [WORKFLOW] ON [WORKFLOW].[WORKFLOWID] = [WORKFLOWACTION].[WORKFLOWID]
			INNER JOIN [WORKFLOWACTIONTYPE] WITH (NOLOCK) ON [WORKFLOWACTIONTYPE].[WORKFLOWACTIONTYPEID] = [WORKFLOWACTION].[WORKFLOWACTIONTYPEID]
			INNER JOIN [TASKPRIORITY] AS DELETETASKPRIORITY WITH (NOLOCK) ON DELETETASKPRIORITY.[TASKPRIORITYID] = [deleted].[TASKPRIORITYID]
			INNER JOIN [TASKPRIORITY] AS INSERTTASKPRIORITY WITH (NOLOCK) ON INSERTTASKPRIORITY.[TASKPRIORITYID] = [inserted].[TASKPRIORITYID]
	WHERE	[deleted].[TASKPRIORITYID] <> [inserted].[TASKPRIORITYID]

	UNION ALL
	SELECT
			[WORKFLOW].[WORKFLOWID], 
			[WORKFLOW].[ROWVERSION],
			GETUTCDATE(),
			[WORKFLOW].[LASTCHANGEDBY],
			'Show On Calendar Flag',
			CASE [deleted].[SHOWONCALENDAR]  WHEN 1 THEN 'Yes' ELSE 'No' END,
			CASE [inserted].[SHOWONCALENDAR]  WHEN 1 THEN 'Yes' ELSE 'No' END,
			'Intelligent Object (' + [WORKFLOW].[WORKFLOWNAME] + '), Action (' + [WORKFLOWACTION].[ACTIONNAME] +'), Action Type (' + [WORKFLOWACTIONTYPE].[WORKFLOWACTIONTYPENAME] + ')',
			'F053A756-19BE-4A42-A70D-185D5B01C31A',
			2,
			0,
			[WORKFLOWACTION].[ACTIONNAME]
	FROM	[deleted]
			JOIN [inserted] ON [deleted].[WORKFLOWACTIONID] = [inserted].[WORKFLOWACTIONID]
			INNER JOIN [WORKFLOWACTION] ON [WORKFLOWACTION].[WORKFLOWACTIONID] = [inserted].[WORKFLOWACTIONID]
			INNER JOIN [WORKFLOW] ON [WORKFLOW].[WORKFLOWID] = [WORKFLOWACTION].[WORKFLOWID]
			INNER JOIN [WORKFLOWACTIONTYPE] WITH (NOLOCK) ON [WORKFLOWACTIONTYPE].[WORKFLOWACTIONTYPEID] = [WORKFLOWACTION].[WORKFLOWACTIONTYPEID]
	WHERE	[deleted].[SHOWONCALENDAR] <> [inserted].[SHOWONCALENDAR]

END