CREATE TABLE [dbo].[WORKFLOWSOCIALNETWORKUSERS] (
    [GID]             VARCHAR (36)   NOT NULL,
    [DESCRIPTION]     NVARCHAR (200) NOT NULL,
    [USERTOKEN]       NVARCHAR (200) NULL,
    [SECRETTOKEN]     NVARCHAR (200) NULL,
    [PAGEID]          NVARCHAR (200) NULL,
    [USERNAME]        VARCHAR (200)  DEFAULT (NULL) NULL,
    [PAGEDESCRIPTION] VARCHAR (MAX)  DEFAULT (NULL) NULL,
    CONSTRAINT [PK_WorkflowSocialNetworkUsers] PRIMARY KEY CLUSTERED ([GID] ASC) WITH (FILLFACTOR = 90)
);

