CREATE TABLE [dbo].[WORKFLOWSTATUS] (
    [WORKFLOWSTATUSID] INT           NOT NULL,
    [NAME]             NVARCHAR (20) NOT NULL,
    CONSTRAINT [PK_WorkflowStatus] PRIMARY KEY CLUSTERED ([WORKFLOWSTATUSID] ASC) WITH (FILLFACTOR = 90)
);

