CREATE PROCEDURE [report].[USP_RPTPARAMVALUECOLLECTION_GETBYID]
(
	@RPTPARAMVALUECOLLECTIONID CHAR(36)
)
AS
BEGIN
	SET NOCOUNT ON;
	SELECT		[RPTPARAMVALUECOLLECTION].[ROWIDNUM],
				[RPTPARAMVALUECOLLECTION].[RPTPARAMVALUECOLLECTIONID],
				[RPTPARAMVALUECOLLECTION].[RPTREPORTID],
				[RPTPARAMVALUECOLLECTION].[PARAMNAME],
				[RPTPARAMVALUECOLLECTION].[PARAMVALUE],
				[RPTPARAMVALUECOLLECTION].[ISMULTI],
				[RPTPARAMVALUECOLLECTION].[CREATEDATE],
				[RPTPARAMVALUECOLLECTION].[ISREQUIRED]
	FROM		[dbo].[RPTPARAMVALUECOLLECTION]
	WHERE		[dbo].[RPTPARAMVALUECOLLECTION].[RPTPARAMVALUECOLLECTIONID] = @RPTPARAMVALUECOLLECTIONID
	ORDER BY	[dbo].[RPTPARAMVALUECOLLECTION].[PARAMNAME]
END