CREATE PROCEDURE [integration].[USP_GET_GL_POSTING_BY_RECEIPT] 
(
	@receipts [RecordNames] READONLY,  
	@includeExportedPreviously BIT, 
	@includeVoids BIT
)
AS
BEGIN

--Regular Invoiced Entity Fees
SELECT    
	[CATRANSACTION].[CATRANSACTIONTYPEID], 
	[CATRANSACTIONGLPOSTING].[CATRANSACTIONGLPOSTINGID], 
	[CATRANSACTIONGLPOSTING].[DEBITACCOUNTID], 
	[CATRANSACTIONGLPOSTING].[DEBITACCOUNTNUMBER],  
	[DEBITGL].[NAME] AS [DEBITNAME],
	[DEBITGL].[DESCRIPTION] AS [DEBITDESCRIPTION],
	[CATRANSACTIONGLPOSTING].[CREDITACCOUNTID], 
	[CATRANSACTIONGLPOSTING].[CREDITACCOUNTNUMBER], 
	[CREDITGL].[NAME] AS [CREDITNAME],
	[CREDITGL].[DESCRIPTION] AS [CREDITDESCRIPTION],
	[CATRANSACTIONGLPOSTING].[POSTINGDATE],   
	[CATRANSACTIONGLPOSTING].[POSTINGAMOUNT], 
	[CATRANSACTIONGLPOSTING].[EXPORTEDON],    
	[CATRANSACTION].[EXTERNALSYSTEMID], 
	[CATRANSACTION].[RECEIPTNUMBER], 
	[CATRANSACTION].[CATRANSACTIONSTATUSID],  
	[CATRANSACTION].[NOTE] AS [TRANSACTIONNOTE],  
	[CATRANSACTIONPAYMENT].[CATRANSACTIONPAYMENTID], 
	[CATRANSACTIONPAYMENT].[PAYMENTDATE], 
	[CATRANSACTIONPAYMENT].[PAYMENTAMOUNT],
	[CATRANSACTIONPAYMENT].[PAYMENTNOTE], 
	[CATRANSACTIONPAYMENT].[ROWVERSION], 
	[CATRANSACTIONPAYMENT].[LASTCHANGEDON], 
	[CATRANSACTIONPAYMENT].[SUPPLEMENTALDATA], 
	[CATRANSACTIONPAYMENT].[ISONLINE], 
	[CAPAYMENTMETHOD].[NAME] AS [PAYMENTMETHOD], 
	[CATRANSACTIONPAYMENT].[CAPAYMENTSTATUSID], 
	[CATRANSACTIONPAYMENT].[CAPAYMENTTYPEID], 
	[CATRANSACTIONPAYMENT].[CATRANSACTIONID],   
	[CATRANSACTIONPAYMENT].[LASTCHANGEDBY],
	[GLOBALENTITY].[GLOBALENTITYNAME] AS [PAYMENTCOMPANYNAME], 
	LTRIM(RTRIM((RTRIM([GLOBALENTITY].[FIRSTNAME]) + ' ' + LTRIM([GLOBALENTITY].[LASTNAME])))) AS [PAYMENTCONTACTNAME],
	(
		SELECT TOP (1) [GLAUDIT].[CHARGECODE] 
		FROM [CAFINANCIALINTGLAUDIT] AS [GLAUDIT] 
		WHERE [CATRANSACTIONFEEPOSTING].[CATRANSACTIONGLPOSTINGID] = [GLAUDIT].[CATRANSACTIONGLPOSTINGID]
	) AS [CHARGECODE],    
	(
		SELECT TOP (1) [CI].[INVOICENUMBER] 
		FROM [CAINVOICEFEE] AS [CIF] 
		JOIN [CAINVOICE] AS [CI] ON [CI].[CAINVOICEID] = [CIF].[CAINVOICEID] 
		WHERE [CATRANSACTIONFEE].[CACOMPUTEDFEEID] = [CIF].[CACOMPUTEDFEEID] 
		ORDER BY [CI].[INVOICEDATE] DESC
	) AS [INVOICENUMBER]    
FROM 
[CATRANSACTIONFEE]   
JOIN [CATRANSACTIONFEEPOSTING] ON [CATRANSACTIONFEE].[CATRANSACTIONFEEID] = [CATRANSACTIONFEEPOSTING].[CATRANSACTIONFEEID]   
JOIN [CATRANSACTIONGLPOSTING] ON [CATRANSACTIONFEEPOSTING].[CATRANSACTIONGLPOSTINGID] = [CATRANSACTIONGLPOSTING].[CATRANSACTIONGLPOSTINGID]   
JOIN [CATRANSACTION] ON [CATRANSACTIONFEE].[CATRANSACTIONID] = [CATRANSACTION].[CATRANSACTIONID]  
JOIN @receipts [RECEIPTS] ON [RECEIPTS].[Name] = [CATRANSACTION].[EXTERNALSYSTEMID]
JOIN [CATRANSACTIONPAYMENT] ON [CATRANSACTIONPAYMENT].[CATRANSACTIONID] = [CATRANSACTION].[CATRANSACTIONID]
JOIN [CAPAYMENTMETHOD] ON [CATRANSACTIONPAYMENT].[CAPAYMENTMETHODID] = [CAPAYMENTMETHOD].[CAPAYMENTMETHODID]
LEFT JOIN [GLOBALENTITY] ON [GLOBALENTITY].[GLOBALENTITYID] = [CATRANSACTION].[GLOBALENTITYID]
LEFT JOIN [GLACCOUNT] AS [CREDITGL] ON [CREDITGL].[GLACCOUNTID] = [CATRANSACTIONGLPOSTING].[CREDITACCOUNTID]
LEFT JOIN [GLACCOUNT] AS [DEBITGL] ON [DEBITGL].[GLACCOUNTID] = [CATRANSACTIONGLPOSTING].[DEBITACCOUNTID]	
WHERE 
([CATRANSACTIONGLPOSTING].[EXPORTEDON] IS NULL OR @includeExportedPreviously = 1) 
AND (((2 <> [CATRANSACTION].[CATRANSACTIONSTATUSID]) AND (6 <> [CATRANSACTION].[CATRANSACTIONTYPEID])) OR (@includeVoids = 1)) 


--Miscellaneous Invoiced Fees
UNION ALL
SELECT    
	[CATRANSACTION].[CATRANSACTIONTYPEID], 
	[CATRANSACTIONGLPOSTING].[CATRANSACTIONGLPOSTINGID], 
	[CATRANSACTIONGLPOSTING].[DEBITACCOUNTID], 
	[CATRANSACTIONGLPOSTING].[DEBITACCOUNTNUMBER],    
	[DEBITGL].[NAME] AS [DEBITNAME],
	[DEBITGL].[DESCRIPTION] AS [DEBITDESCRIPTION],
	[CATRANSACTIONGLPOSTING].[CREDITACCOUNTID], 
	[CATRANSACTIONGLPOSTING].[CREDITACCOUNTNUMBER], 
	[CREDITGL].[NAME] AS [CREDITNAME],
	[CREDITGL].[DESCRIPTION] AS [CREDITDESCRIPTION],
	[CATRANSACTIONGLPOSTING].[POSTINGDATE],   
	[CATRANSACTIONGLPOSTING].[POSTINGAMOUNT], 
	[CATRANSACTIONGLPOSTING].[EXPORTEDON],    
	[CATRANSACTION].[EXTERNALSYSTEMID], 
	[CATRANSACTION].[RECEIPTNUMBER], 
	[CATRANSACTION].[CATRANSACTIONSTATUSID],  
	[CATRANSACTION].[NOTE] AS [TRANSACTIONNOTE],  
	[CATRANSACTIONPAYMENT].[CATRANSACTIONPAYMENTID], 
	[CATRANSACTIONPAYMENT].[PAYMENTDATE], 
	[CATRANSACTIONPAYMENT].[PAYMENTAMOUNT], 
	[CATRANSACTIONPAYMENT].[PAYMENTNOTE], 
	[CATRANSACTIONPAYMENT].[ROWVERSION], 
	[CATRANSACTIONPAYMENT].[LASTCHANGEDON], 
	[CATRANSACTIONPAYMENT].[SUPPLEMENTALDATA], 
	[CATRANSACTIONPAYMENT].[ISONLINE], 
	[CAPAYMENTMETHOD].[NAME] AS [PAYMENTMETHOD], 
	[CATRANSACTIONPAYMENT].[CAPAYMENTSTATUSID],
	[CATRANSACTIONPAYMENT].[CAPAYMENTTYPEID], 
	[CATRANSACTIONPAYMENT].[CATRANSACTIONID],   
	[CATRANSACTIONPAYMENT].[LASTCHANGEDBY],
	[GLOBALENTITY].[GLOBALENTITYNAME] AS [PAYMENTCOMPANYNAME], 
	LTRIM(RTRIM((RTRIM([GLOBALENTITY].[FIRSTNAME]) + ' ' + LTRIM([GLOBALENTITY].[LASTNAME])))) AS [PAYMENTCONTACTNAME],
	(
		SELECT TOP (1) [GLAUDIT].[CHARGECODE] 
		FROM [CAFINANCIALINTGLAUDIT] AS [GLAUDIT] 
		WHERE [CATRANSACTIONMISCFEEPOSTING].[CATRANSACTIONGLPOSTINGID] = [GLAUDIT].[CATRANSACTIONGLPOSTINGID]
	) AS [CHARGECODE],    
	(
		SELECT TOP (1) [CI].[INVOICENUMBER] 
		FROM [CAINVOICEMISCFEE] AS [CIMF] 
		JOIN [CAINVOICE] AS [CI] ON [CI].[CAINVOICEID] = [CIMF].[CAINVOICEID] 
		WHERE [CATRANSACTIONMISCFEE].[CAMISCFEEID] = [CIMF].[CAMISCFEEID] 
		ORDER BY [CI].[INVOICEDATE] DESC
	) AS [INVOICENUMBER]    
FROM 
[CATRANSACTIONMISCFEE]  
JOIN [CATRANSACTIONMISCFEEPOSTING] ON [CATRANSACTIONMISCFEE].[CATRANSACTIONMISCFEEID] = [CATRANSACTIONMISCFEEPOSTING].[CATRANSACTIONMISCFEEID]   
JOIN [CATRANSACTIONGLPOSTING] ON [CATRANSACTIONMISCFEEPOSTING].[CATRANSACTIONGLPOSTINGID] = [CATRANSACTIONGLPOSTING].[CATRANSACTIONGLPOSTINGID]   
JOIN [CATRANSACTION] ON [CATRANSACTIONMISCFEE].[CATRANSACTIONID] = [CATRANSACTION].[CATRANSACTIONID]  
JOIN @receipts [RECEIPTS] ON [RECEIPTS].[Name] = [CATRANSACTION].[EXTERNALSYSTEMID]
JOIN [CATRANSACTIONPAYMENT] ON [CATRANSACTIONPAYMENT].[CATRANSACTIONID] = [CATRANSACTION].[CATRANSACTIONID]
JOIN [CAPAYMENTMETHOD] ON [CATRANSACTIONPAYMENT].[CAPAYMENTMETHODID] = [CAPAYMENTMETHOD].[CAPAYMENTMETHODID]
LEFT JOIN [GLOBALENTITY] ON [GLOBALENTITY].[GLOBALENTITYID] = [CATRANSACTION].[GLOBALENTITYID]
LEFT JOIN [GLACCOUNT] AS [CREDITGL] ON [CREDITGL].[GLACCOUNTID] = [CATRANSACTIONGLPOSTING].[CREDITACCOUNTID]
LEFT JOIN [GLACCOUNT] AS [DEBITGL] ON [DEBITGL].[GLACCOUNTID] = [CATRANSACTIONGLPOSTING].[DEBITACCOUNTID]	
WHERE 
([CATRANSACTIONGLPOSTING].[EXPORTEDON] IS NULL OR @includeExportedPreviously = 1) 
AND (((2 <> [CATRANSACTION].[CATRANSACTIONSTATUSID]) AND (6 <> [CATRANSACTION].[CATRANSACTIONTYPEID])) OR (@includeVoids = 1))


--Account Transaction Details
UNION ALL
SELECT    
	[CATRANSACTION].[CATRANSACTIONTYPEID], 
	[CATRANSACTIONGLPOSTING].[CATRANSACTIONGLPOSTINGID], 
	[CATRANSACTIONGLPOSTING].[DEBITACCOUNTID], 
	[CATRANSACTIONGLPOSTING].[DEBITACCOUNTNUMBER],
	[DEBITGL].[NAME] AS [DEBITNAME],
	[DEBITGL].[DESCRIPTION] AS [DEBITDESCRIPTION],
	[CATRANSACTIONGLPOSTING].[CREDITACCOUNTID], 
	[CATRANSACTIONGLPOSTING].[CREDITACCOUNTNUMBER], 
	[CREDITGL].[NAME] AS [CREDITNAME],
	[CREDITGL].[DESCRIPTION] AS [CREDITDESCRIPTION],
	[CATRANSACTIONGLPOSTING].[POSTINGDATE],   
	[CATRANSACTIONGLPOSTING].[POSTINGAMOUNT], 
	[CATRANSACTIONGLPOSTING].[EXPORTEDON],    
	[CATRANSACTION].[EXTERNALSYSTEMID], 
	[CATRANSACTION].[RECEIPTNUMBER], 
	[CATRANSACTION].[CATRANSACTIONSTATUSID],  
	[CATRANSACTION].[NOTE] AS [TRANSACTIONNOTE],  
	[CATRANSACTIONPAYMENT].[CATRANSACTIONPAYMENTID], 
	[CATRANSACTIONPAYMENT].[PAYMENTDATE], 
	[CATRANSACTIONPAYMENT].[PAYMENTAMOUNT], 
	[CATRANSACTIONPAYMENT].[PAYMENTNOTE], 
	[CATRANSACTIONPAYMENT].[ROWVERSION], 
	[CATRANSACTIONPAYMENT].[LASTCHANGEDON], 
	[CATRANSACTIONPAYMENT].[SUPPLEMENTALDATA], 
	[CATRANSACTIONPAYMENT].[ISONLINE], 
	[CAPAYMENTMETHOD].[NAME] AS [PAYMENTMETHOD], 
	[CATRANSACTIONPAYMENT].[CAPAYMENTSTATUSID], 
	[CATRANSACTIONPAYMENT].[CAPAYMENTTYPEID], 
	[CATRANSACTIONPAYMENT].[CATRANSACTIONID],   
	[CATRANSACTIONPAYMENT].[LASTCHANGEDBY],
	[GLOBALENTITY].[GLOBALENTITYNAME] AS [PAYMENTCOMPANYNAME], 
	LTRIM(RTRIM((RTRIM([GLOBALENTITY].[FIRSTNAME]) + ' ' + LTRIM([GLOBALENTITY].[LASTNAME])))) AS [PAYMENTCONTACTNAME],
	(
		SELECT TOP (1) [GLAUDIT].[CHARGECODE] 
		FROM [CAFINANCIALINTGLAUDIT] AS [GLAUDIT] 
		WHERE [CATRANSACTIONACCOUNTPOSTING].[CATRANSACTIONGLPOSTINGID] = [GLAUDIT].[CATRANSACTIONGLPOSTINGID]
	) AS [CHARGECODE],    
	'' AS [INVOICENUMBER]    
FROM 
[CATRANSACTIONACCOUNT] 
JOIN [CATRANSACTIONACCOUNTPOSTING] ON [CATRANSACTIONACCOUNT].[CATRANSACTIONACCOUNTID] = [CATRANSACTIONACCOUNTPOSTING].[CATRANSACTIONACCOUNTID]
JOIN [CATRANSACTIONGLPOSTING] AS [CATRANSACTIONGLPOSTING] ON [CATRANSACTIONACCOUNTPOSTING].[CATRANSACTIONGLPOSTINGID] = [CATRANSACTIONGLPOSTING].[CATRANSACTIONGLPOSTINGID]   
JOIN [CATRANSACTION] ON [CATRANSACTIONACCOUNT].[CATRANSACTIONID] = [CATRANSACTION].[CATRANSACTIONID]  
JOIN @receipts [RECEIPTS] ON [RECEIPTS].[Name] = [CATRANSACTION].[EXTERNALSYSTEMID]
JOIN [CATRANSACTIONPAYMENT] ON [CATRANSACTIONPAYMENT].[CATRANSACTIONID] = [CATRANSACTION].[CATRANSACTIONID]
JOIN [CAPAYMENTMETHOD] ON [CATRANSACTIONPAYMENT].[CAPAYMENTMETHODID] = [CAPAYMENTMETHOD].[CAPAYMENTMETHODID]
LEFT JOIN [GLOBALENTITY] ON [GLOBALENTITY].[GLOBALENTITYID] = [CATRANSACTION].[GLOBALENTITYID]
LEFT JOIN [GLACCOUNT] AS [CREDITGL] ON [CREDITGL].[GLACCOUNTID] = [CATRANSACTIONGLPOSTING].[CREDITACCOUNTID]
LEFT JOIN [GLACCOUNT] AS [DEBITGL] ON [DEBITGL].[GLACCOUNTID] = [CATRANSACTIONGLPOSTING].[DEBITACCOUNTID]	
WHERE  
([CATRANSACTIONGLPOSTING].[EXPORTEDON] IS NULL OR @includeExportedPreviously = 1) 
AND (((2 <> [CATRANSACTION].[CATRANSACTIONSTATUSID]) AND (6 <> [CATRANSACTION].[CATRANSACTIONTYPEID])) OR (@includeVoids = 1))

ORDER BY [POSTINGDATE], [CATRANSACTIONGLPOSTINGID]

END