CREATE FUNCTION [managebusinesslicense].[UDF_GET_BULKRENEWAL_COUNTS]()
RETURNS TABLE
AS
RETURN
(
	SELECT 
		[dbo].[BLBATCHRENEWALBLLICENSE].[BLBATCHRENEWALID], 
		COUNT(*) AS TOTALCOUNT, 
		SUM(CASE WHEN [dbo].[BLBATCHRENEWALBLLICENSE].[PROCESSEDDATE] IS NULL THEN 0 ELSE 1 END) AS PROCESSEDCOUNT, 
		SUM(CASE WHEN [dbo].[BLBATCHRENEWALBLLICENSE].[SUCCESS] = 0 THEN 1 ELSE 0 END) AS FAILEDCOUNT
	FROM [dbo].[BLBATCHRENEWALBLLICENSE] 
	JOIN [dbo].[BLBATCHRENEWAL] ON [dbo].[BLBATCHRENEWAL].[BLBATCHRENEWALID] = [dbo].[BLBATCHRENEWALBLLICENSE].[BLBATCHRENEWALID]
	GROUP BY [dbo].[BLBATCHRENEWALBLLICENSE].[BLBATCHRENEWALID] 
)