CREATE FUNCTION [managebusinesslicense].[UFN_GET_RECENTINVOICEDATE_GETBY_LICENSEID]
(
	@LICENSEID char(36)
)
RETURNS DATE
AS
BEGIN
	DECLARE @RECENTINVOICEDATE AS DATE
	SELECT @RECENTINVOICEDATE = [CAINVOICE].[INVOICEDATE]
	FROM [dbo].[BLLICENSEFEE] 
	INNER JOIN [dbo].[CACOMPUTEDFEE] ON [BLLICENSEFEE].[CACOMPUTEDFEEID] = [CACOMPUTEDFEE].[CACOMPUTEDFEEID]
	INNER JOIN [dbo].[CAINVOICEFEE] ON [CACOMPUTEDFEE].[CACOMPUTEDFEEID] = [CAINVOICEFEE].[CACOMPUTEDFEEID]
	INNER JOIN [dbo].[CAINVOICE] ON [CAINVOICEFEE].[CAINVOICEID] = [CAINVOICE].[CAINVOICEID]	
	WHERE [BLLICENSEFEE].[BLLICENSEID] = @LICENSEID
	-- 1 => Due | 6 => Invoiced | 7 => InvoicedPastDue | 3 => PartialPayment | 8 => PartialPaymentPastDue | 2 => PastDue
	ORDER BY (CASE WHEN ([CAINVOICE].[CASTATUSID] IN (1,6,7,3,8,2)) THEN 1 ELSE 0 END), [CAINVOICE].[INVOICEDATE] DESC
	RETURN @RECENTINVOICEDATE;
END