CREATE FUNCTION [businessmanagementsetup].[USF_HAS_BLEXTCOMPANYTYPE_USED_BY_BLEXTCOMPANYTYPEID]
(
@BLEXTCOMPANYTYPEID AS CHAR(36)  
)
RETURNS BIT
AS
BEGIN
    DECLARE @HASUSED BIT
    IF(EXISTS(SELECT 1 FROM [dbo].[BLGLOBALENTITYEXTENSION] WHERE [dbo].[BLGLOBALENTITYEXTENSION].[BLEXTCOMPANYTYPEID] = @BLEXTCOMPANYTYPEID))
    BEGIN
        SET @HASUSED=1
    END
    ELSE IF(EXISTS(SELECT 1 FROM [dbo].[SEARCHBUSINESSLICENSE] WHERE [dbo].[SEARCHBUSINESSLICENSE].[BLEXTCOMPANYTYPEID] = @BLEXTCOMPANYTYPEID))
    BEGIN
        SET @HASUSED=1
    END
    ELSE IF(EXISTS(SELECT 1 FROM [dbo].[SEARCHTAXREMITTANCE] WHERE [dbo].[SEARCHTAXREMITTANCE].[BLEXTCOMPANYTYPEID] = @BLEXTCOMPANYTYPEID))
    BEGIN
        SET @HASUSED=1
    END
    ELSE
    BEGIN
        SET @HASUSED=0
    END
    RETURN @HASUSED
END