CREATE PROCEDURE [dbo].[USP_HEARINGCASETYPE_INSERT]
(
	@CASETYPEID CHAR(36),
	@MODULEID INT,
	@TYPEID CHAR(36),
	@WORKCLASSID CHAR(36),
	@LIMIT INT,
	@HEARINGTYPEID CHAR(36),
	@MODULENAME NVARCHAR(50),
	@TYPENAME NVARCHAR(50),
	@WORKCLASSNAME NVARCHAR(50)
)
AS

INSERT INTO [dbo].[HEARINGCASETYPE](
	[CASETYPEID],
	[MODULEID],
	[TYPEID],
	[WORKCLASSID],
	[LIMIT],
	[HEARINGTYPEID],
	[MODULENAME],
	[TYPENAME],
	[WORKCLASSNAME]
)

VALUES
(
	@CASETYPEID,
	@MODULEID,
	@TYPEID,
	@WORKCLASSID,
	@LIMIT,
	@HEARINGTYPEID,
	@MODULENAME,
	@TYPENAME,
	@WORKCLASSNAME
)