CREATE PROCEDURE [dbo].[USP_HOLDTYPESETUPS_DELETE]
(
	@HOLDSETUPID CHAR(36),
	@ROWVERSION INT
)
AS
DELETE FROM [dbo].[HOLDTYPESETUPS]
WHERE
	[HOLDSETUPID] = @HOLDSETUPID AND 
	[ROWVERSION]= @ROWVERSION