CREATE PROCEDURE [dbo].[USP_HEARINGTYPE_DELETE]
(
	@HEARINGTYPEID CHAR(36),
	@ROWVERSION INT
)
AS

SET NOCOUNT ON;

EXEC [dbo].[USP_HEARINGTYPEDATTENDEE_DELETE_BYPARENTID] @HEARINGTYPEID
EXEC [dbo].[USP_HEARINGCASETYPE_DELETE_BYPARENTID] @HEARINGTYPEID
EXEC [dbo].[USP_WFACTION_HEARINGTYPE_DELETE_BYPARENTID] @HEARINGTYPEID

SET NOCOUNT OFF;

DELETE FROM [dbo].[HEARINGTYPE]
WHERE
	[HEARINGTYPEID] = @HEARINGTYPEID AND 
	[ROWVERSION] = @ROWVERSION