CREATE PROCEDURE [codemanagementsetup].[USP_CMCOURTSTATUS_SELECT_LOOKUP]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[CMCOURTSTATUS].[CMCOURTSTATUSID],
	[dbo].[CMCOURTSTATUS].[NAME]	
FROM [dbo].[CMCOURTSTATUS]
ORDER BY [dbo].[CMCOURTSTATUS].[NAME] ASC
END