CREATE PROCEDURE [codemanagementsetup].[USP_CMCITATIONTYPE_GETALL]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[CMCITATIONTYPE].[CMCITATIONTYPEID],
	[dbo].[CMCITATIONTYPE].[NAME],
	[dbo].[CMCITATIONTYPE].[DESCRIPTION],
	[dbo].[CMCITATIONTYPE].[PREFIX],
	[dbo].[CMCITATIONTYPE].[DEFAULTCITATIONSTATUSID],
	[dbo].[CMCITATIONTYPE].[ACTIVE],
	[dbo].[CMCITATIONTYPE].[AUTONUMBER],
	[dbo].[CMCITATIONTYPE].[TYPESPECIFICAUTONUMBER],
	[dbo].[CMCITATIONTYPE].[LASTCHANGEDBY],
	[dbo].[CMCITATIONTYPE].[LASTCHANGEDON],
	[dbo].[CMCITATIONTYPE].[ROWVERSION]
FROM [dbo].[CMCITATIONTYPE] 
ORDER BY [dbo].[CMCITATIONTYPE].[NAME]

END