CREATE PROCEDURE [codemanagementsetup].[USP_CMCODEREVISION_GETBYPARENTID]
(
	@PARENTID AS CHAR(36)
)
AS
BEGIN
SELECT 
	[dbo].[CMCODEREVISION].[CMCODEREVISIONID],
	[dbo].[CMCODEREVISION].[CMCODEID],
	[dbo].[CMCODEREVISION].[CODETEXT],
	[dbo].[CMCODEREVISION].[REVISIONDATE],
	[dbo].[CMCODEREVISION].[CURRENTREVISION],
	[dbo].[CMCODEREVISION].[STARTDATE],
	[dbo].[CMCODEREVISION].[ENDDATE],
	[dbo].[CMCODEREVISION].[REVISIONNUMBER]
FROM [dbo].[CMCODEREVISION]
INNER JOIN [dbo].[CMCODE] 
	ON [dbo].[CMCODEREVISION].[CMCODEID] = [dbo].[CMCODE].[CMCODEID]
WHERE [dbo].[CMCODEREVISION].[CMCODEID] = @PARENTID
ORDER BY [dbo].[CMCODEREVISION].[REVISIONNUMBER] 

END