CREATE PROCEDURE [codemanagementsetup].[USP_CMCODECASEHOLDTYPECONTACTTYPEREF_GETBYPARENTIDS]
(
	@CMCODECASEHOLDTYPEIDS RecordIDs READONLY
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[CMCODECASEHOLDTYPECONTACTTYPEREF].[CMCODECASEHOLDTYPECONTACTTYPEID],
	[dbo].[CMCODECASEHOLDTYPECONTACTTYPEREF].[CMCODECASEHOLDTYPEID],
	[dbo].[CMCODECASEHOLDTYPECONTACTTYPEREF].[CMCODECASECONTACTTYPEID],
	[dbo].[CMCODECASECONTACTTYPE].NAME AS CMCODECASECONTACTTYPENAME,
	[dbo].[CMCODECASEHOLDTYPECONTACTTYPEREF].[ACTIVE]
FROM [dbo].[CMCODECASEHOLDTYPECONTACTTYPEREF] 
JOIN [dbo].[CMCODECASECONTACTTYPE] ON [dbo].[CMCODECASECONTACTTYPE].CMCODECASECONTACTTYPEID=[dbo].[CMCODECASEHOLDTYPECONTACTTYPEREF].[CMCODECASECONTACTTYPEID]
WHERE
	[dbo].[CMCODECASEHOLDTYPECONTACTTYPEREF].[CMCODECASEHOLDTYPEID] IN (SELECT RECORDID FROM @CMCODECASEHOLDTYPEIDS )
ORDER BY 
	[dbo].[CMCODECASECONTACTTYPE].NAME
END