CREATE PROCEDURE [codemanagementsetup].[USP_CMCODECASEHOLDTYPEREF_GETBYIDS]
(
	@CMCODECASEHOLDTYPEIDS RecordIDs READONLY
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[CMCODECASEHOLDTYPEREF].[CMCODECASEHOLDTYPEID],
	[dbo].[CMCODECASEHOLDTYPEREF].[CMCASETYPEID],
	[dbo].[CMCODECASEHOLDTYPEREF].[HOLDSETUPID],
	[dbo].[HOLDTYPESETUPS].NAME AS HOLDSETUPNAME,
	[dbo].[HOLDTYPESETUPS].MODULEID,
	[dbo].[HOLDTYPE].HOLDTYPENAME
FROM [dbo].[CMCODECASEHOLDTYPEREF] 
JOIN [dbo].[HOLDTYPESETUPS] on [dbo].[HOLDTYPESETUPS].[HOLDSETUPID] = [dbo].[CMCODECASEHOLDTYPEREF].[HOLDSETUPID]
JOIN [dbo].[HOLDTYPE] ON [dbo].[HOLDTYPE].[HOLDTYPEID] = [dbo].[HOLDTYPESETUPS].[HOLDTYPEID]
WHERE
	[dbo].[CMCODECASEHOLDTYPEREF].[CMCODECASEHOLDTYPEID] IN (SELECT RECORDID FROM @CMCODECASEHOLDTYPEIDS) 
END