CREATE PROCEDURE [codemanagementsetup].[USP_CMCITATIONSTATUS_SELECT_LOOKUP]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[CMCITATIONSTATUS].[CMCITATIONSTATUSID],
	[dbo].[CMCITATIONSTATUS].[NAME]	
FROM [dbo].[CMCITATIONSTATUS]
ORDER BY [dbo].[CMCITATIONSTATUS].[NAME] ASC
END