CREATE PROCEDURE [codemanagementsetup].[USP_CMCODEACTIVITYTYPE_GETALL]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[CMCODEACTIVITYTYPE].[CMCODEACTIVITYTYPEID],
	[dbo].[CMCODEACTIVITYTYPE].[NAME],
	[dbo].[CMCODEACTIVITYTYPE].[DESCRIPTION],
	[dbo].[CMCODEACTIVITYTYPE].[CANEDIT],
	[dbo].[CMCODEACTIVITYTYPE].[CREATEID],
	[dbo].[CMCODEACTIVITYTYPE].[PREFIXID],
	[dbo].[CMCODEACTIVITYTYPE].[ALLOWDUPLICATE],
	[dbo].[CMCODEACTIVITYTYPE].[CUSTOMFIELDID],
	[dbo].[CMCODEACTIVITYTYPE].[LASTCHANGEDBY],
	[dbo].[CMCODEACTIVITYTYPE].[LASTCHANGEDON],
	[dbo].[CMCODEACTIVITYTYPE].[ROWVERSION]
FROM [dbo].[CMCODEACTIVITYTYPE] ORDER BY [dbo].[CMCODEACTIVITYTYPE].[NAME]

END