CREATE PROCEDURE [gissetupapp].[USP_GEOQUERY_GETALL]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[GEOQUERY].[GEOQUERYID],
	[dbo].[GEOQUERY].[QUERYNAME],
	[dbo].[GEOQUERY].[FEATURECLASSNAME],
	[dbo].[GEOQUERY].[FEATURECLASSID],
	[dbo].[GEOQUERY].[FIELDNAME],
	[dbo].[GEOQUERY].[RETURNTYPE],
	[dbo].[GEOQUERY].[RETURNEDFEATURECLASS],
	[dbo].[GEOQUERY].[RETURNEDFEATURECLASSID],
	[dbo].[GEOQUERY].[GEOQUERYTYPEID],
	[dbo].[GEOQUERY].[RETURNFIELDNAME],
	[dbo].[GEOQUERY].[RETURNFIELDTYPE],
	[dbo].[GEOQUERY].[DISTANCE],
	[dbo].[GEOQUERY].[GEOQUERYUNITTYPEID],
	[dbo].[GEOQUERY].[USEBUFFERRING],
	[dbo].[GEOQUERY].[BUFFERFEATURECLASS],
	[dbo].[GEOQUERY].[BUFFERFEATURECLASSID],
	[dbo].[GEOQUERY].[BUFFERGEOQUERYTYPEID],
	[dbo].[GEOQUERY].[APPLYSHAPEBUFFERING],
	[dbo].[GEOQUERY].[LASTCHANGEDBY],
	[dbo].[GEOQUERY].[LASTCHANGEDON],
	[dbo].[GEOQUERY].[ROWVERSION]
FROM [dbo].[GEOQUERY]
ORDER BY [dbo].[GEOQUERY].[QUERYNAME] ASC
END