CREATE PROCEDURE [gissetupapp].[USP_GEOFIELDMAPPINGTRANSLATE_GETBYPARENTID]
(
	@PARENTID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT		[dbo].[GEOFIELDMAPPINGTRANSLATE].[GEOFIELDMAPPINGTRANSLATEID],
			[dbo].[GEOFIELDMAPPINGTRANSLATE].[GEOFIELDMAPPINGID],
			[dbo].[GEOFIELDMAPPINGTRANSLATE].[GISATTRIBUTEVALUE],
			[dbo].[GEOFIELDMAPPINGTRANSLATE].[TRANSLATEDVALUE]
FROM		[dbo].[GEOFIELDMAPPINGTRANSLATE]
INNER JOIN	[dbo].[GEOFIELDMAPPING]	ON [dbo].[GEOFIELDMAPPING].[GEOFIELDMAPPINGID] = [dbo].[GEOFIELDMAPPINGTRANSLATE].[GEOFIELDMAPPINGID]
INNER JOIN	[dbo].[GEORULEPROCESS] ON [dbo].[GEORULEPROCESS].[GEORULEPROCESSID] = [dbo].[GEOFIELDMAPPING].[GEORULEPROCESSID]
WHERE		[dbo].[GEORULEPROCESS].[GEORULEID] = @PARENTID

END