CREATE PROCEDURE [gissetupapp].[USP_GISZONETOINSPECTORDESIG_GETALL]
AS
BEGIN

SET NOCOUNT ON;
SELECT 
	[dbo].[GISZONETOINSPECTORDESIG].[GISZONETOINSPECTORDESIGID],
	[dbo].[GISZONETOINSPECTORDESIG].[GISZONEEXTERNALVALUEID],
	[dbo].[GISZONETOINSPECTORDESIG].[USERID],
	[LASTNAME] = [dbo].[USERS].[LNAME],
	[FIRSTNAME] = ISNULL([dbo].[USERS].[FNAME],'')
FROM [dbo].[GISZONETOINSPECTORDESIG]
INNER JOIN [dbo].[USERS] ON [dbo].[GISZONETOINSPECTORDESIG].[USERID] = [dbo].[USERS].[SUSERGUID]
ORDER BY [dbo].[USERS].[LNAME] , ISNULL([dbo].[USERS].[FNAME],'') ASC

END