CREATE PROCEDURE [gissetupapp].[USP_MAILINGADDRESS_SEARCH]
(
	@SEARCH AS NVARCHAR(MAX) = '',
	@PAGE_NUMBER AS INT = 1,
	@PAGE_SIZE AS INT = 10,
	@IS_ASCENDING AS BIT = 1
)
AS
WITH RAW_DATA AS (
	SELECT
		[dbo].[MAILINGADDRESS].[MAILINGADDRESSID],
		[dbo].[MAILINGADDRESS].[ADDRESSLINE1],
		[dbo].[MAILINGADDRESS].[ADDRESSLINE2],
		[dbo].[MAILINGADDRESS].[CITY],
		[dbo].[MAILINGADDRESS].[STATE],
		[dbo].[MAILINGADDRESS].[POSTALCODE],
		CASE @IS_ASCENDING WHEN 1 THEN
			ROW_NUMBER() OVER(ORDER BY [dbo].[MAILINGADDRESS].[ADDRESSLINE1])
		ELSE
			ROW_NUMBER() OVER(ORDER BY [dbo].[MAILINGADDRESS].[ADDRESSLINE1] DESC)
		END AS RowNumber,
		COUNT(1) OVER() AS TotalRows
	FROM [dbo].[MAILINGADDRESS]	
	WHERE 
	(ISNULL([dbo].[MAILINGADDRESS].[ADDRESSLINE1], '') + ' ' + ISNULL([dbo].[MAILINGADDRESS].[ADDRESSLINE2], '') + ' ' + ISNULL([dbo].[MAILINGADDRESS].[CITY], '')
	 + ' ' + ISNULL([dbo].[MAILINGADDRESS].[STATE], '') + ' ' + ISNULL([dbo].[MAILINGADDRESS].[POSTALCODE], ''))
	 LIKE '%'+ @SEARCH +'%'
)

SELECT * 
FROM RAW_DATA
WHERE
	RowNumber > @PAGE_SIZE * (@PAGE_NUMBER - 1) AND 
	RowNumber <= @PAGE_SIZE * @PAGE_NUMBER
ORDER BY 
	RowNumber