CREATE PROCEDURE [gissetupapp].[USP_PLITEMREVIEWZONE_SELECT_LOOKUP]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[PLITEMREVIEWZONE].[PLITEMREVIEWZONEID],
	[dbo].[PLITEMREVIEWZONE].[NAME]
FROM 
	[dbo].[PLITEMREVIEWZONE]
ORDER BY 
	[dbo].[PLITEMREVIEWZONE].[NAME]

END