CREATE PROCEDURE [gissetupapp].[USP_ADDRESSLAYOUTSETUP_GETALL]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[ADDRESSLAYOUTSETUP].[ADDRESSLAYOUTSETUPID],
	[dbo].[ADDRESSLAYOUTSETUP].[COUNTRYID],
	[dbo].[ADDRESSLAYOUTSETUP].[KEYTEXTBLOCKNAME],
	[dbo].[ADDRESSLAYOUTSETUP].[KEYCONTROLNAME],
	[dbo].[ADDRESSLAYOUTSETUP].[KEYBINDINGPROPERTYNAME],
	[dbo].[ADDRESSLAYOUTSETUP].[DEFAULTLABEL],
	[dbo].[ADDRESSLAYOUTSETUP].[NEWLABEL],
	[dbo].[ADDRESSLAYOUTSETUP].[DEFAULTTABINDEX],
	[dbo].[ADDRESSLAYOUTSETUP].[NEWTABINDEX],
	[dbo].[ADDRESSLAYOUTSETUP].[ISHIDE],
	[dbo].[ADDRESSLAYOUTSETUP].[LASTCHANGEDBY],
	[dbo].[ADDRESSLAYOUTSETUP].[LASTCHANGEDON],
	[dbo].[ADDRESSLAYOUTSETUP].[ROWVERSION]
FROM [dbo].[ADDRESSLAYOUTSETUP]
ORDER BY [dbo].[ADDRESSLAYOUTSETUP].[NEWTABINDEX] ASC
END