CREATE PROCEDURE [gissetupapp].[USP_GEORULEPROCESSTYPE_SELECT_LOOKUP]
AS
SET NOCOUNT ON;
SELECT		[dbo].[GEORULEPROCESSTYPE].[GEORULEPROCESSTYPEID],
			[dbo].[GEORULEPROCESSTYPE].[GEORULEPROCESSTYPENAME],
			[dbo].[GEORULEPROCESSTYPE].[SYSTEMTYPE]
FROM		[dbo].[GEORULEPROCESSTYPE]
ORDER BY	[dbo].[GEORULEPROCESSTYPE].[GEORULEPROCESSTYPENAME]