CREATE PROCEDURE [gissetupapp].[USP_PLITEMREVIEWZONE_GETALL]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[PLITEMREVIEWZONE].[PLITEMREVIEWZONEID],
	[dbo].[PLITEMREVIEWZONE].[NAME],
	[dbo].[PLITEMREVIEWZONE].[DESCRIPTION],
	[dbo].[PLITEMREVIEWZONE].[DEFAULTTRAVELTIME],
	[dbo].[PLITEMREVIEWZONE].[LASTCHANGEDBY],
	[dbo].[PLITEMREVIEWZONE].[LASTCHANGEDON],
	[dbo].[PLITEMREVIEWZONE].[ROWVERSION]
FROM [dbo].[PLITEMREVIEWZONE]
ORDER BY [dbo].[PLITEMREVIEWZONE].[NAME] ASC
END