CREATE PROCEDURE [gissetupapp].[USP_GISMAP_SEARCH]
(
	@SEARCH			  AS NVARCHAR(255)	    =	'',
	@PAGE_NUMBER	  AS INT				=	1,
	@PAGE_SIZE		  AS INT				=	10,
	@IS_ASCENDING	  AS BIT				=	1
)
AS

WITH RAW_DATA AS (
	SELECT
			[dbo].[GISMAP].[GMAPID],
			[dbo].[GISMAP].[SMAPNAME],
			[dbo].[GISMAP].[SMAPURL],
			CASE @IS_ASCENDING WHEN 1 THEN
				ROW_NUMBER() OVER(ORDER BY [dbo].[GISMAP].[SMAPNAME])
			ELSE
				ROW_NUMBER() OVER(ORDER BY [dbo].[GISMAP].[SMAPNAME] DESC)
			END AS RowNumber,
			COUNT(1) OVER() AS TotalRows
	FROM	[dbo].[GISMAP]
	WHERE	[dbo].[GISMAP].[SMAPNAME] LIKE '%'+ @SEARCH +'%'
)

SELECT		* 
FROM		RAW_DATA
WHERE		RowNumber > @PAGE_SIZE * (@PAGE_NUMBER - 1) 
			AND RowNumber <= @PAGE_SIZE * @PAGE_NUMBER
ORDER BY	RowNumber