CREATE PROCEDURE [gissetupapp].[USP_GISFEATURECLASS_GETALL]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[GISFEATURECLASS].[GISFEATURECLASSID],
	[dbo].[GISFEATURECLASS].[LAYERNUMBER],
	[dbo].[GISFEATURECLASS].[ATTRIBUTEFIELD],
	[dbo].[GISFEATURECLASS].[LAYERURL],
	[dbo].[GISFEATURECLASS].[LAYERNAME],
	[dbo].[GISFEATURECLASS].[ALIAS],
	[dbo].[GISFEATURECLASS].[LASTCHANGEDBY],
	[dbo].[GISFEATURECLASS].[LASTCHANGEDON],
	[dbo].[GISFEATURECLASS].[ROWVERSION],
	COALESCE([dbo].[GISFEATURECLASS].[ALIAS] + ' - ' + [dbo].[GISFEATURECLASS].[ATTRIBUTEFIELD], COALESCE([dbo].[GISFEATURECLASS].[ALIAS], [dbo].[GISFEATURECLASS].[ATTRIBUTEFIELD]))
FROM [dbo].[GISFEATURECLASS]
ORDER BY [dbo].[GISFEATURECLASS].[ALIAS], [dbo].[GISFEATURECLASS].[ATTRIBUTEFIELD]
EXEC [gissetupapp].[USP_GISFEATURECLASSSEARCHFIELD_GETALL]

END