CREATE PROCEDURE [gissetupapp].[USP_GISZONETOREVIEWITEMDESIG_GETALL]
AS
BEGIN

SET NOCOUNT ON;
SELECT 
	[dbo].[GISZONETOREVIEWITEMDESIG].[GISZONETOREVIEWITEMDESIGID],
	[dbo].[GISZONETOREVIEWITEMDESIG].[GISZONEREVIEWITEMVALUEID],
	[dbo].[GISZONETOREVIEWITEMDESIG].[USERID],
	[dbo].[GISZONETOREVIEWITEMDESIG].[PLITEMREVIEWTYPEID],
	[LASTNAME] = [dbo].[USERS].[LNAME],
	[FIRSTNAME] = ISNULL([dbo].[USERS].[FNAME],''),
	[REVIEWITEMNAME] = [dbo].[PLITEMREVIEWTYPE].[NAME]	
FROM [dbo].[GISZONETOREVIEWITEMDESIG]
INNER JOIN [dbo].[USERS] ON [dbo].[GISZONETOREVIEWITEMDESIG].[USERID] = [dbo].[USERS].[SUSERGUID]
INNER JOIN [dbo].[PLITEMREVIEWTYPE] ON [dbo].[GISZONETOREVIEWITEMDESIG].[PLITEMREVIEWTYPEID] = [dbo].[PLITEMREVIEWTYPE].[PLITEMREVIEWTYPEID]
ORDER BY [dbo].[USERS].[LNAME] , ISNULL([dbo].[USERS].[FNAME],'') ASC

END