CREATE PROCEDURE [gissetupapp].[USP_GISZONEREVIEWITEMVALUE_GETALL]
AS
BEGIN

SET NOCOUNT ON;
SELECT 
	[dbo].[GISZONEREVIEWITEMVALUE].[GISZONEREVIEWITEMVALUEID],
	[dbo].[GISZONEREVIEWITEMVALUE].[GISZONEREVIEWITEMMAPPINGID],
	[dbo].[GISZONEREVIEWITEMVALUE].[VALUE],
	[dbo].[GISZONEREVIEWITEMVALUE].[PLITEMREVIEWZONEID],
	[ITEMREVIEWZONENAME] = [dbo].[PLITEMREVIEWZONE].[NAME]	
FROM [dbo].[GISZONEREVIEWITEMVALUE]
INNER JOIN [dbo].[PLITEMREVIEWZONE] ON [dbo].[GISZONEREVIEWITEMVALUE].[PLITEMREVIEWZONEID] = [dbo].[PLITEMREVIEWZONE].[PLITEMREVIEWZONEID]
ORDER BY [dbo].[GISZONEREVIEWITEMVALUE].[VALUE] ASC

END