CREATE PROCEDURE [businessmanagementsetup].[USP_EXAMLOCTIMESLOT_GETBYPARENTID]
(
	@PARENTID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[EXAMLOCTIMESLOT].[EXAMLOCTIMESLOTID],
	[dbo].[EXAMLOCTIMESLOT].[EXAMTIMESLOTID],
	[dbo].[EXAMLOCTIMESLOT].[EXAMLOCATIONID],
	[dbo].[EXAMLOCTIMESLOT].[ISDEFAULT],
	[dbo].[EXAMTIMESLOT].[NAME],
	[dbo].[EXAMTIMESLOT].[STARTTIME],
	[dbo].[EXAMTIMESLOT].[ENDTIME]	
FROM 
	[dbo].[EXAMLOCTIMESLOT]
INNER JOIN 
	[dbo].[EXAMTIMESLOT] ON [dbo].[EXAMTIMESLOT].[EXAMTIMESLOTID] = [dbo].[EXAMLOCTIMESLOT].[EXAMTIMESLOTID]
WHERE 
	[dbo].[EXAMLOCTIMESLOT].[EXAMLOCATIONID] = @PARENTID
ORDER BY 
	[dbo].[EXAMTIMESLOT].[NAME]

END