CREATE PROCEDURE [businessmanagementsetup].[USP_LICENSECYCLE_GETALL]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT		[dbo].[LICENSECYCLE].[LICENSECYCLEID],
				[dbo].[LICENSECYCLE].[NAME],
				[dbo].[LICENSECYCLE].[DESCRIPTION],
				[dbo].[LICENSECYCLE].[CHARGERENEWALFEE],
				[dbo].[LICENSECYCLE].[RENEWALCYCLEID],
				[LICENSECYCLERECURRENCESETUP_RENEWALCYCLE].[NAME] AS [RENEWALCYCLENAME],
				[dbo].[LICENSECYCLE].[RENEWALDEADLINEID],
				[LICENSECYCLERECURRENCESETUP_RENEWALDEADLINE].[NAME] AS [RENEWALDEADLINENAME],
				[dbo].[LICENSECYCLE].[INVOICEDEADLINEID],
				[LICENSECYCLERECURRENCESETUP_INVOICEDEADLINE].[NAME] AS [INVOICEDEADLINENAME],
				[dbo].[LICENSECYCLE].[ROWVERSION],
				[dbo].[LICENSECYCLE].[LASTCHANGEDON],
				[dbo].[LICENSECYCLE].[LASTCHANGEDBY]
	FROM		[dbo].[LICENSECYCLE]
				LEFT JOIN [LICENSECYCLERECURRENCESETUP] LICENSECYCLERECURRENCESETUP_RENEWALCYCLE WITH (NOLOCK) ON LICENSECYCLERECURRENCESETUP_RENEWALCYCLE.LICENSECYCLERECURRENCESETUPID = [LICENSECYCLE].[RENEWALCYCLEID]
				LEFT JOIN [LICENSECYCLERECURRENCESETUP] LICENSECYCLERECURRENCESETUP_RENEWALDEADLINE WITH (NOLOCK) ON LICENSECYCLERECURRENCESETUP_RENEWALDEADLINE.LICENSECYCLERECURRENCESETUPID = [LICENSECYCLE].[RENEWALDEADLINEID]
				LEFT JOIN [LICENSECYCLERECURRENCESETUP] LICENSECYCLERECURRENCESETUP_INVOICEDEADLINE WITH (NOLOCK) ON LICENSECYCLERECURRENCESETUP_INVOICEDEADLINE.LICENSECYCLERECURRENCESETUPID = [LICENSECYCLE].[INVOICEDEADLINEID]
	ORDER BY	[dbo].[LICENSECYCLE].[NAME] ASC
END