CREATE PROCEDURE [businessmanagementsetup].[USP_BLEXTBUSINESSTYPE_GETALL]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[BLEXTBUSINESSTYPE].[BLEXTBUSINESSTYPEID],
	[dbo].[BLEXTBUSINESSTYPE].[CODENUMBER],
	[dbo].[BLEXTBUSINESSTYPE].[NAME],
	[dbo].[BLEXTBUSINESSTYPE].[DESCRIPTION],
	[dbo].[BLEXTBUSINESSTYPE].[BLEXTBUSINESSCATEGORYID],
	[dbo].[BLEXTBUSINESSTYPE].[CODENUMBER] + ' - ' + [dbo].[BLEXTBUSINESSTYPE].[NAME],
	[dbo].[BLEXTBUSINESSTYPE].[LASTCHANGEDBY],
	[dbo].[BLEXTBUSINESSTYPE].[LASTCHANGEDON],
	[dbo].[BLEXTBUSINESSTYPE].[ROWVERSION]
FROM [dbo].[BLEXTBUSINESSTYPE]
ORDER BY [dbo].[BLEXTBUSINESSTYPE].[NAME] ASC

END