CREATE PROCEDURE [businessmanagementsetup].[USP_BLEXTBUSINESSCATEGORY_SELECT_LOOKUP]
AS
	SET NOCOUNT ON;
	SELECT 
		[dbo].[BLEXTBUSINESSCATEGORY].[BLEXTBUSINESSCATEGORYID],
		[dbo].[BLEXTBUSINESSCATEGORY].[NAME]
	FROM [dbo].[BLEXTBUSINESSCATEGORY]
	ORDER BY [dbo].[BLEXTBUSINESSCATEGORY].[NAME] ASC