CREATE PROCEDURE [businessmanagementsetup].[USP_ILLICENSEGROUP_GETALL]
AS
BEGIN
SELECT 
	[dbo].[ILLICENSEGROUP].[ILLICENSEGROUPID],
	[dbo].[ILLICENSEGROUP].[NAME],
	[dbo].[ILLICENSEGROUP].[DESCRIPTION],
	[dbo].[ILLICENSEGROUP].[MAXCOMMERCIALVALUE],
	[dbo].[ILLICENSEGROUP].[MAXRESIDENTIALVALUE],
	[dbo].[ILLICENSEGROUP].[LASTCHANGEDBY],
	[dbo].[ILLICENSEGROUP].[LASTCHANGEDON],
	[dbo].[ILLICENSEGROUP].[ROWVERSION]
FROM [dbo].[ILLICENSEGROUP]
ORDER BY [dbo].[ILLICENSEGROUP].[NAME] ASC
END