CREATE PROCEDURE [businessmanagementsetup].[USP_TXRPTPERIOD_SEARCH]
(
	@SEARCH AS NVARCHAR(MAX) = '',
	@PAGE_NUMBER AS INT = 1,
	@PAGE_SIZE AS INT = 10,
	@IS_ASCENDING AS BIT = 1
)
AS
WITH RAW_DATA AS (
	SELECT
		[dbo].[TXRPTPERIOD].[TXRPTPERIODID],
        [dbo].[TXRPTPERIOD].[NAME],		
		[dbo].[TXRPTPERIOD].[DESCRIPTION],
		CASE @IS_ASCENDING WHEN 1 THEN
			ROW_NUMBER() OVER(ORDER BY [dbo].[TXRPTPERIOD].[NAME])
		ELSE
			ROW_NUMBER() OVER(ORDER BY [dbo].[TXRPTPERIOD].[NAME] DESC)
		END AS RowNumber,
		COUNT(1) OVER() AS TotalRows
	FROM [dbo].[TXRPTPERIOD]
	WHERE ([dbo].[TXRPTPERIOD].[NAME] LIKE '%'+ @SEARCH +'%' OR [dbo].[TXRPTPERIOD].[DESCRIPTION] LIKE '%' + @SEARCH + '%')
)

SELECT * 
FROM RAW_DATA
WHERE
	RowNumber > @PAGE_SIZE * (@PAGE_NUMBER - 1) AND 
	RowNumber <= @PAGE_SIZE * @PAGE_NUMBER
ORDER BY 
	RowNumber