CREATE PROCEDURE [businessmanagementsetup].[USP_BLLICENSEREQUIREDFIELD_GETBYPARENTID]
(
@BLLICENSETYPEID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[BLLICENSEREQUIREDFIELD].[BLREQUIREDCUSTOMFIELD],
	[dbo].[BLLICENSETYPECLASS].[BLLICENSETYPEID],
	[dbo].[BLLICENSEREQUIREDFIELD].[BLLICENSETYPECLASSID],
	[dbo].[BLLICENSEREQUIREDFIELD].[GCUSTOMFIELD],
	[dbo].[BLLICENSEREQUIREDFIELD].[SORTORDER],
	CASE
		WHEN LEN(ISNULL([dbo].[CUSTOMFIELD].[SFIELDNAME],''))>0 THEN [dbo].[CUSTOMFIELD].[SFIELDNAME]
		ELSE [dbo].[CUSTOMFIELD].[SCUSTOMFIELD]
	END AS SFIELDNAME
FROM [dbo].[BLLICENSEREQUIREDFIELD]
INNER JOIN [dbo].[BLLICENSETYPECLASS]
ON [dbo].[BLLICENSEREQUIREDFIELD].[BLLICENSETYPECLASSID]=[dbo].[BLLICENSETYPECLASS].[BLLICENSETYPECLASSID]
INNER JOIN [dbo].[CUSTOMFIELD]
ON [dbo].[CUSTOMFIELD].[GCUSTOMFIELD]=[dbo].[BLLICENSEREQUIREDFIELD].[GCUSTOMFIELD]
WHERE [dbo].[BLLICENSETYPECLASS].[BLLICENSETYPEID]=@BLLICENSETYPEID

END