CREATE PROCEDURE [businessmanagementsetup].[USP_TXRPTPERIOD_GETALL]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[TXRPTPERIOD].[TXRPTPERIODID],
	[dbo].[TXRPTPERIOD].[NAME],
	[dbo].[TXRPTPERIOD].[DESCRIPTION],
	[dbo].[TXRPTPERIOD].[CUSTOMFIELDLAYOUTID],
	[dbo].[TXRPTPERIOD].[LASTCHANGEDBY],
	[dbo].[TXRPTPERIOD].[LASTCHANGEDON],
	[dbo].[TXRPTPERIOD].[ROWVERSION]
FROM [dbo].[TXRPTPERIOD]
ORDER BY [dbo].[TXRPTPERIOD].[NAME] ASC
END