CREATE PROCEDURE [businessmanagementsetup].[USP_RPPROPERTYSTATUS_GETALL]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[RPPROPERTYSTATUS].[RPPROPERTYSTATUSID],
	[dbo].[RPPROPERTYSTATUS].[NAME],
	[dbo].[RPPROPERTYSTATUS].[DESCRIPTION],
	[dbo].[RPPROPERTYSTATUS].[RPPROPERTYSYSSTATUSID],
	[dbo].[RPPROPERTYSTATUS].[LASTCHANGEDBY],
	[dbo].[RPPROPERTYSTATUS].[LASTCHANGEDON],
	[dbo].[RPPROPERTYSTATUS].[ROWVERSION]
FROM [dbo].[RPPROPERTYSTATUS]
ORDER BY [dbo].[RPPROPERTYSTATUS].[NAME] ASC

END