CREATE PROCEDURE [businessmanagementsetup].[USP_EXAMLOCATION_SEARCH]
(
	@SEARCH AS NVARCHAR(MAX) = '',
	@PAGE_NUMBER AS INT = 1,
	@PAGE_SIZE AS INT = 10,
	@IS_ASCENDING AS BIT = 1
)
AS
WITH RAW_DATA AS (
	SELECT
		[dbo].[EXAMLOCATION].[EXAMLOCATIONID],
		[dbo].[EXAMLOCATION].[NAME],
		[dbo].[EXAMLOCATION].[DESCRIPTION],		
		CASE @IS_ASCENDING WHEN 1 THEN
			ROW_NUMBER() OVER(ORDER BY [dbo].[EXAMLOCATION].[NAME])
		ELSE
			ROW_NUMBER() OVER(ORDER BY [dbo].[EXAMLOCATION].[NAME] DESC)
		END AS RowNumber,
		COUNT(1) OVER() AS TotalRows
	FROM [dbo].[EXAMLOCATION]
	WHERE ([dbo].[EXAMLOCATION].[NAME] LIKE '%'+ @SEARCH +'%' OR [dbo].[EXAMLOCATION].[DESCRIPTION] LIKE '%'+ @SEARCH +'%')
)

SELECT * 
FROM RAW_DATA
WHERE
	RowNumber > @PAGE_SIZE * (@PAGE_NUMBER - 1) AND 
	RowNumber <= @PAGE_SIZE * @PAGE_NUMBER
ORDER BY 
	RowNumber