CREATE PROCEDURE [businessmanagementsetup].[USP_RPLANDLORDTYPECONTACTTYPE_GETALL]
AS
BEGIN
	SET NOCOUNT ON;
	SELECT		[dbo].[RPLANDLORDTYPECONTACTTYPE].[RPLANDLORDTYPECONTACTTYPEID],
				[dbo].[RPLANDLORDTYPECONTACTTYPE].[RPCONTACTTYPEID],
				[dbo].[RPLANDLORDTYPECONTACTTYPE].[RPLANDLORDLICENSETYPEID],
				[dbo].[RPLANDLORDTYPECONTACTTYPE].[ISREQUIRED],
				[dbo].[RPLANDLORDTYPECONTACTTYPE].[CONTACTTYPEGROUP],
				[dbo].[RPCONTACTTYPE].[NAME]
	FROM		[dbo].[RPLANDLORDTYPECONTACTTYPE]
				INNER JOIN [dbo].[RPCONTACTTYPE] ON [dbo].[RPLANDLORDTYPECONTACTTYPE].[RPCONTACTTYPEID] = [dbo].[RPCONTACTTYPE].[RPCONTACTTYPEID]
	ORDER BY	[dbo].[RPCONTACTTYPE].[NAME] ASC
END