CREATE PROCEDURE [businessmanagementsetup].[USP_RPLANDLORDLICENSESTATUS_SELECT_LOOKUP]
AS
	SET NOCOUNT ON;
	SELECT 
		[dbo].[RPLANDLORDLICENSESTATUS].[RPLANDLORDLICENSESTATUSID],
		[dbo].[RPLANDLORDLICENSESTATUS].[NAME]
	FROM [dbo].[RPLANDLORDLICENSESTATUS]
	ORDER BY [dbo].[RPLANDLORDLICENSESTATUS].[NAME] ASC