CREATE PROCEDURE [businessmanagementsetup].[USP_ILLICENSETYPELICENSECLASS_GETBYPARENTID]
(
	@ILLICENSETYPEID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT
[dbo].[ILLICENSETYPELICENSECLASS].[ILLICENSETYPELICENSECLASSID],
[dbo].[ILLICENSETYPELICENSECLASS].[ILLICENSECLASSIFICATIONID],
[dbo].[ILLICENSETYPELICENSECLASS].[ILLICENSETYPEID],
[dbo].[ILLICENSETYPELICENSECLASS].[LICENSECYCLEID],
[dbo].[ILLICENSETYPELICENSECLASS].[CUSTOMFIELDLAYOUTID],
[dbo].[ILLICENSETYPELICENSECLASS].[WFTEMPLATEID],
[dbo].[ILLICENSETYPELICENSECLASS].[CAFEETEMPLATEID],
[dbo].[ILLICENSETYPELICENSECLASS].[ILLICENSECAPAPPLICATIONTYPEID],
[dbo].[ILLICENSETYPELICENSECLASS].[INTERNETFLAG],
[dbo].[ILLICENSETYPELICENSECLASS].[ONLINECUSTOMFIELDLAYOUTID],
[dbo].[ILLICENSETYPELICENSECLASS].[WFTEMPLATERENEWALID],
[dbo].[ILLICENSETYPELICENSECLASS].[RENEWALDAYSPRIORTOEXPIRE],
[dbo].[ILLICENSETYPELICENSECLASS].[CAPADDRESSREQUIRED],
[dbo].[ILLICENSETYPELICENSECLASS].[CANRENEWONLINE],
[dbo].[ILLICENSETYPELICENSECLASS].[CAPRENEWALAPPLICATIONTYPEID],
[ILLICENSECLASSIFICATION].[NAME] AS ILLICENSECLASSIFICATIONNAME,
[dbo].[LICENSECYCLE].[NAME] AS LICENSECYCLENAME,
[ILLICENSEWFTEMPLATE].[NAME] AS ILLICENSEWFTEMPLATENAME,
[ILLICENSEWFTEMPLATERENEWAL].[NAME] AS ILLICENSEWFTEMPLATERENEWALNAME,
[dbo].[CUSTOMFIELDLAYOUT].[SNAME] AS CUSTOMFIELDLAYOUTNAME,
[ONLINECUSTOMFIELDLAYOUT].[SNAME] AS ONLINECUSTOMFIELDLAYOUTNAME,
[FEESTEMPLATE].[CAFEETEMPLATENAME] AS CAFEETEMPLATENAME,
[ILLICENSEONLINEAPPLYTYPE].[NAME] AS ILLICENSEONLINEAPPLYTYPENAME,
[ILLICENSEONLINERENEWTYPE].[NAME] AS ILLICENSEONLINERENEWTYPENAME
	FROM
[dbo].[ILLICENSETYPELICENSECLASS] 
INNER JOIN [dbo].[WFTEMPLATE] [ILLICENSEWFTEMPLATE] 
	ON [ILLICENSEWFTEMPLATE].[WFTEMPLATEID] = [dbo].[ILLICENSETYPELICENSECLASS].[WFTEMPLATEID]
LEFT JOIN [dbo].[WFTEMPLATE] [ILLICENSEWFTEMPLATERENEWAL] 
	ON [ILLICENSEWFTEMPLATERENEWAL].[WFTEMPLATEID] = [dbo].[ILLICENSETYPELICENSECLASS].[WFTEMPLATERENEWALID]
INNER JOIN [dbo].[ILLICENSECLASSIFICATION] 
	ON [dbo].[ILLICENSECLASSIFICATION].[ILLICENSECLASSIFICATIONID] = [dbo].[ILLICENSETYPELICENSECLASS].[ILLICENSECLASSIFICATIONID]
LEFT JOIN [dbo].[CUSTOMFIELDLAYOUT] 
	ON [dbo].[CUSTOMFIELDLAYOUT].[GCUSTOMFIELDLAYOUTS] = [dbo].[ILLICENSETYPELICENSECLASS].[CUSTOMFIELDLAYOUTID]
LEFT JOIN [dbo].[CUSTOMFIELDLAYOUT] [ONLINECUSTOMFIELDLAYOUT] 
	ON [ONLINECUSTOMFIELDLAYOUT].[GCUSTOMFIELDLAYOUTS] = [dbo].[ILLICENSETYPELICENSECLASS].[ONLINECUSTOMFIELDLAYOUTID]
LEFT JOIN [dbo].[CAFEETEMPLATE] [FEESTEMPLATE]
	ON [FEESTEMPLATE].[CAFEETEMPLATEID] = [dbo].[ILLICENSETYPELICENSECLASS].[CAFEETEMPLATEID]
LEFT JOIN [dbo].[LICENSECYCLE] 
	ON [dbo].[LICENSECYCLE].[LICENSECYCLEID] = [dbo].[ILLICENSETYPELICENSECLASS].[LICENSECYCLEID]
INNER JOIN [dbo].[ILLICENSECAPAPPLICATIONTYPE][ILLICENSEONLINEAPPLYTYPE]
	ON [ILLICENSEONLINEAPPLYTYPE].[ILLICENSECAPAPPLICATIONTYPEID] =  [dbo].[ILLICENSETYPELICENSECLASS].[ILLICENSECAPAPPLICATIONTYPEID]
INNER JOIN [dbo].[ILLICENSECAPAPPLICATIONTYPE][ILLICENSEONLINERENEWTYPE]
	ON [ILLICENSEONLINERENEWTYPE].[ILLICENSECAPAPPLICATIONTYPEID] =  [dbo].[ILLICENSETYPELICENSECLASS].[CAPRENEWALAPPLICATIONTYPEID]

WHERE
	[dbo].[ILLICENSETYPELICENSECLASS].[ILLICENSETYPEID] = @ILLICENSETYPEID
	ORDER BY [dbo].[ILLICENSECLASSIFICATION].[NAME]
END