CREATE PROCEDURE [businessmanagementsetup].[USP_BLLICENSECLASS_SELECT_LOOKUP]
AS
SET NOCOUNT ON;
SELECT 
	[dbo].[BLLICENSECLASS].[BLLICENSECLASSID],
	[dbo].[BLLICENSECLASS].[NAME]
FROM [dbo].[BLLICENSECLASS]
ORDER BY [dbo].[BLLICENSECLASS].[NAME]