CREATE PROCEDURE [businessmanagementsetup].[USP_BLLICENSETYPE_GETBYID]  
(  
 @BLLICENSETYPEID CHAR(36)  
)  
AS  
BEGIN  
SET NOCOUNT ON; 

SELECT   
 [dbo].[BLLICENSETYPE].[BLLICENSETYPEID],  
 [dbo].[BLLICENSETYPE].[NAME],  
 [dbo].[BLLICENSETYPE].[PREFIX],  
 [dbo].[BLLICENSETYPE].[DESCRIPTION],  
 [dbo].[BLLICENSETYPE].[DEFAULTSTATUSID],  
 [dbo].[BLLICENSETYPE].[DEFAULTINTERNETBLLICSTATUSID],   
 [dbo].[BLLICENSETYPE].[DEFAULTRENEWSTATUSID],  
 [dbo].[BLLICENSETYPE].[DEFAULTWEBRENEWSTATUSID],  
 [dbo].[BLLICENSETYPE].[ACTIVE],  
 [dbo].[BLLICENSETYPE].[ISRENEWABLE],  
 [dbo].[BLLICENSETYPE].[CANRENEWONLINE],  
 [dbo].[BLLICENSETYPE].[ALLOWINTERNETSUBMISSION],
 [dbo].[BLLICENSETYPE].[ISRECEIPTSTYPE],
 [dbo].[BLLICENSETYPE].[ALLOWRENEWALLICENSENUM],
 [dbo].[BLLICENSETYPE].[SKIPPAYMENT],
 [dbo].[BLLICENSETYPE].[SETRENEWISSDATETOPRVEXPDATE],  
 [dbo].[BLLICENSETYPE].[SETISSUEDATEONRENEWAL],  
 [dbo].[BLLICENSETYPE].[USEACTUALRECEIPTSASEST],
 [dbo].[BLLICENSETYPE].[ANNUALIZERECONCILERECEIPTS],
 [dbo].[BLLICENSETYPE].[CURRENTYEARONRENEWALS],  
 [dbo].[BLLICENSETYPE].[MANAGEBUSINESSTYPECODES],
 [dbo].[BLLICENSETYPE].[REQUIREBUSINESSTYPECODES],
 [dbo].[BLLICENSETYPE].[REPORTRECEIPTSBYBUSINESSTYPECODE],
 [dbo].[BLLICENSETYPE].[LASTCHANGEDBY],  
 [dbo].[BLLICENSETYPE].[LASTCHANGEDON],  
 [dbo].[BLLICENSETYPE].[ROWVERSION],  
 [dbo].[BLLICENSETYPE].[BLLICENSETYPEMODULEID],
 (SELECT [dbo].[USF_HAS_BLLICENSETYPE_USED_BY_BLLICENSETYPEID] (@BLLICENSETYPEID)) AS BLLICENSETYPEHASUSED
FROM [dbo].[BLLICENSETYPE]
WHERE  
 [dbo].[BLLICENSETYPE].[BLLICENSETYPEID] = @BLLICENSETYPEID    

EXEC [businessmanagementsetup].[USP_BLLICENSETYPECLASS_GETBYPARENTID] @BLLICENSETYPEID
EXEC [businessmanagementsetup].[USP_BLTYPECLASSILTYPE_GETBYPARENTID] @BLLICENSETYPEID
EXEC [businessmanagementsetup].[USP_BLTYPECLASSILCLASS_GETBYPARENTID] @BLLICENSETYPEID
EXEC [businessmanagementsetup].[USP_BLLICENSEREQUIREDFIELD_GETBYPARENTID] @BLLICENSETYPEID
EXEC [businessmanagementsetup].[USP_BLCONTACTTYPEREF_GETBYPARENTID] @BLLICENSETYPEID
EXEC [businessmanagementsetup].[USP_ATTACHMENTREQFILEREF_GETBYPARENTID] @BLLICENSETYPEID
EXEC [businessmanagementsetup].[USP_BLLICENSEALLOWEDACTIVITY_GETBYPARENTID] @BLLICENSETYPEID

END