CREATE PROCEDURE [businessmanagementsetup].[USP_EXAMTYPE_GETBYID]
(
	@EXAMTYPEID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
	SELECT 
		[dbo].[EXAMTYPE].[EXAMTYPEID],
		[dbo].[EXAMTYPE].[NAME],
		[dbo].[EXAMTYPE].[FRIENDLYNAME],
		[dbo].[EXAMTYPE].[DESCRIPTION],
		[dbo].[EXAMTYPE].[EXAMFORMATID],
		[dbo].[EXAMTYPE].[DEFAULTEXAMSTATUSID],
		[dbo].[EXAMTYPE].[DEFAULTEXAMLOCATIONID],
		[dbo].[EXAMTYPE].[CUSTOMFIELDLAYOUTID],
		[dbo].[EXAMTYPE].[PREFIX],
		[dbo].[EXAMTYPE].[DAYSUNTILEXPIRE],
		[dbo].[EXAMTYPE].[ACTIVE],
		[dbo].[EXAMTYPE].[UNLIMITEDEXPIRATION],
		[dbo].[EXAMTYPE].[SITTINGDATEAVAILABILITYID],
		[dbo].[EXAMTYPE].[RECURRENCEID],
		[dbo].[RECURRENCE].[NAME] AS RECURRENCENAME,
		[dbo].[EXAMTYPE].[LASTCHANGEDBY],
		[dbo].[EXAMTYPE].[LASTCHANGEDON],
		[dbo].[EXAMTYPE].[ROWVERSION]
	FROM [dbo].[EXAMTYPE]
	LEFT JOIN [dbo].[RECURRENCE]
	ON [dbo].[RECURRENCE].[RECURRENCEID] = [dbo].[EXAMTYPE].[RECURRENCEID]
	WHERE
		[dbo].[EXAMTYPE].[EXAMTYPEID] = @EXAMTYPEID

	EXEC [businessmanagementsetup].[USP_EXAMTYPEVERSION_GETBYPARENTID] @EXAMTYPEID
	EXEC [businessmanagementsetup].[USP_EXAMTYPERULE_GETBYPARENTID] @EXAMTYPEID
	EXEC [businessmanagementsetup].[USP_EXAMSITTINGDATE_GETBYPARENTID] @EXAMTYPEID  

END