CREATE PROCEDURE [businessmanagementsetup].[USP_LICENSECYCLERECURRENCESETUP_SELECT_LOOKUP]
(
	@LICENSECYCLETYPEID INT
)
AS

SET NOCOUNT ON;

SELECT		[dbo].[LICENSECYCLERECURRENCESETUP].[LICENSECYCLERECURRENCESETUPID],
			[dbo].[LICENSECYCLERECURRENCESETUP].[NAME]
FROM		[dbo].[LICENSECYCLERECURRENCESETUP]
WHERE		[dbo].[LICENSECYCLERECURRENCESETUP].[LICENSECYCLETYPEID] = @LICENSECYCLETYPEID
ORDER BY	[dbo].[LICENSECYCLERECURRENCESETUP].[NAME]