CREATE PROCEDURE [businessmanagementsetup].[USP_EXAMVERSION_GETALL]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[EXAMVERSION].[EXAMVERSIONID],
	[dbo].[EXAMVERSION].[NAME],
	[dbo].[EXAMVERSION].[DESCRIPTION],
	[dbo].[EXAMVERSION].[LASTCHANGEDBY],
	[dbo].[EXAMVERSION].[LASTCHANGEDON],
	[dbo].[EXAMVERSION].[ROWVERSION]
FROM [dbo].[EXAMVERSION]
ORDER BY [dbo].[EXAMVERSION].[NAME]

END