CREATE PROCEDURE [businessmanagementsetup].[USP_BLEXTLOCATION_GETALL]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[BLEXTLOCATION].[BLEXTLOCATIONID],
	[dbo].[BLEXTLOCATION].[NAME],
	[dbo].[BLEXTLOCATION].[DESCRIPTION],
	[dbo].[BLEXTLOCATION].[LASTCHANGEDBY],
	[dbo].[BLEXTLOCATION].[LASTCHANGEDON],
	[dbo].[BLEXTLOCATION].[ROWVERSION]
FROM [dbo].[BLEXTLOCATION]
ORDER BY [dbo].[BLEXTLOCATION].[NAME] ASC
END