CREATE PROCEDURE [businessmanagementsetup].[USP_CUSTOMFIELD_SEARCH_BYNAME]
(
	@SEARCH AS NVARCHAR(MAX) = '',
	@PAGE_NUMBER AS INT = 1,
	@PAGE_SIZE AS INT = 10,
	@IS_ASCENDING AS BIT = 1,
	@CUSTOMFIELDLAYOUTIDS RecordIDs Readonly,
	@ONLINECUSTOMFIELDLAYOUTIDS RecordIDs Readonly
)
AS
WITH RESULT_DATA AS (
	SELECT [dbo].[CUSTOMFIELD].[GCUSTOMFIELD],
		CASE
			WHEN LEN(ISNULL([dbo].[CUSTOMFIELD].[SFIELDNAME],''))>0 THEN [dbo].[CUSTOMFIELD].[SFIELDNAME]
			ELSE [dbo].[CUSTOMFIELD].[SCUSTOMFIELD]
		END AS SFIELDNAME,
		CASE 
			WHEN [dbo].[CUSTOMFIELDOBJECT].[FKGCUSTOMFIELDLAYOUT] IN(SELECT RECORDID FROM  @ONLINECUSTOMFIELDLAYOUTIDS) THEN ' (ONLINE)'
			ELSE ''
		END AS ONLINEDESCRIPTION,
		CASE 
			WHEN [dbo].[CUSTOMFIELDOBJECT].[FKGCUSTOMFIELDLAYOUT] IN(SELECT RECORDID FROM  @ONLINECUSTOMFIELDLAYOUTIDS) THEN CAST('True' AS bit)
			ELSE CAST('False' AS bit)
		END AS ISONLINECUSTOMFIELDLAYOUT,
		[dbo].[CUSTOMFIELDOBJECT].[FKGCUSTOMFIELDLAYOUT],
		[dbo].[CUSTOMFIELDLAYOUT].[SNAME]
	FROM [dbo].[CUSTOMFIELD]
	INNER JOIN [dbo].[CUSTOMFIELDOBJECT]
	ON [dbo].[CUSTOMFIELD].[GCUSTOMFIELD] = [dbo].[CUSTOMFIELDOBJECT].[GCUSTOMFIELD]
	INNER JOIN [dbo].[CUSTOMFIELDLAYOUT]
	ON  [dbo].[CUSTOMFIELDLAYOUT].[GCUSTOMFIELDLAYOUTS]=[dbo].[CUSTOMFIELDOBJECT].[FKGCUSTOMFIELDLAYOUT] 
	WHERE ([dbo].[CUSTOMFIELDOBJECT].[FKGCUSTOMFIELDLAYOUT] IN (SELECT RECORDID FROM @CUSTOMFIELDLAYOUTIDS))
	OR ([dbo].[CUSTOMFIELDOBJECT].[FKGCUSTOMFIELDLAYOUT] IN (SELECT RECORDID FROM @ONLINECUSTOMFIELDLAYOUTIDS))
),
RAW_DATA AS (
	SELECT
		GCUSTOMFIELD,
		CONCAT(SFIELDNAME,ONLINEDESCRIPTION,' - (',SNAME,')') AS SFIELDNAME,
		FKGCUSTOMFIELDLAYOUT,
		ISONLINECUSTOMFIELDLAYOUT,
		CASE @IS_ASCENDING WHEN 1 THEN
			ROW_NUMBER() OVER(ORDER BY SFIELDNAME,ONLINEDESCRIPTION)
		ELSE
			ROW_NUMBER() OVER(ORDER BY SFIELDNAME DESC,ONLINEDESCRIPTION DESC)
		END AS RowNumber,
		COUNT(1) OVER() AS TotalRows
	FROM RESULT_DATA
	WHERE (SFIELDNAME LIKE '%'+ @SEARCH +'%')
)
SELECT * 
FROM RAW_DATA
WHERE
	RowNumber > @PAGE_SIZE * (@PAGE_NUMBER - 1) AND 
	RowNumber <= @PAGE_SIZE * @PAGE_NUMBER
ORDER BY 
	RowNumber