CREATE PROCEDURE [businessmanagementsetup].[USP_SITTINGDATEAVAILABILITY_SELECT_LOOKUP]
AS
SET NOCOUNT ON;
SELECT 
	[dbo].[SITTINGDATEAVAILABILITY].[SITTINGDATEAVAILABILITYID],
	[dbo].[SITTINGDATEAVAILABILITY].[NAME]
FROM
	[dbo].[SITTINGDATEAVAILABILITY]
ORDER BY
	[dbo].[SITTINGDATEAVAILABILITY].[NAME]