CREATE PROCEDURE [businessmanagementsetup].[USP_BLLICENSETYPECLASS_GETBYPARENTID]
(
	@BLLICENSETYPEID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT
[dbo].[BLLICENSETYPECLASS].[BLLICENSETYPECLASSID],
[dbo].[BLLICENSETYPECLASS].[BLLICENSETYPEID],
[dbo].[BLLICENSETYPECLASS].[BLLICENSECLASSID],
[dbo].[BLLICENSETYPECLASS].[LICENSECYCLEID],
[dbo].[BLLICENSETYPECLASS].[CUSTOMFIELDLAYOUTID],
[dbo].[BLLICENSETYPECLASS].[WFTEMPLATEID],
[dbo].[BLLICENSETYPECLASS].[CAFEETEMPLATEID],
[dbo].[BLLICENSETYPECLASS].[BLLICENSECAPAPPLICATIONTYPEID],
[dbo].[BLLICENSETYPECLASS].[INTERNETFLAG],
[dbo].[BLLICENSETYPECLASS].[ONLINECUSTOMFIELDLAYOUTID],
[dbo].[BLLICENSETYPECLASS].[WFTEMPLATERENEWALID],
[dbo].[BLLICENSETYPECLASS].[RENEWALDAYSPRIORTOEXPIRE],
[dbo].[BLLICENSETYPECLASS].[CANRENEWONLINE],
[dbo].[BLLICENSETYPECLASS].[ONLINERENEWTYPEID],
[dbo].[BLLICENSETYPECLASS].[CAPADDRESSREQUIRED],
[BLLICENSECLASS].[NAME] AS BLLICENSECLASSNAME,
[dbo].[LICENSECYCLE].[NAME] AS LICENSECYCLENAME,
[BLLICENSEWFTEMPLATE].[NAME] AS BLLICENSEWFTEMPLATENAME,
[BLLICENSEWFTEMPLATERENEWAL].[NAME] AS BLLICENSEWFTEMPLATERENEWALNAME,
[dbo].[CUSTOMFIELDLAYOUT].[SNAME] AS CUSTOMFIELDLAYOUTNAME,
[ONLINECUSTOMFIELDLAYOUT].[SNAME] AS ONLINECUSTOMFIELDLAYOUTNAME,
[FEESTEMPLATE].[CAFEETEMPLATENAME] AS CAFEETEMPLATENAME,
[BLLICENSEONLINEAPPLYTYPE].[NAME] AS BLLICENSEONLINEAPPLYTYPENAME,
[BLLICENSEONLINERENEWTYPE].[NAME] AS BLLICENSEONLINERENEWTYPENAME
	FROM
[dbo].[BLLICENSETYPECLASS] 
INNER JOIN [dbo].[WFTEMPLATE] [BLLICENSEWFTEMPLATE]
	ON [BLLICENSEWFTEMPLATE].[WFTEMPLATEID] = [dbo].[BLLICENSETYPECLASS].[WFTEMPLATEID]
LEFT JOIN [dbo].[WFTEMPLATE] [BLLICENSEWFTEMPLATERENEWAL]
	ON [BLLICENSEWFTEMPLATERENEWAL].[WFTEMPLATEID] = [dbo].[BLLICENSETYPECLASS].[WFTEMPLATERENEWALID]
INNER JOIN [dbo].[BLLICENSECLASS] 
	ON [dbo].[BLLICENSECLASS].[BLLICENSECLASSID] = [dbo].[BLLICENSETYPECLASS].[BLLICENSECLASSID]
LEFT JOIN [dbo].[CUSTOMFIELDLAYOUT] 
	ON [dbo].[CUSTOMFIELDLAYOUT].[GCUSTOMFIELDLAYOUTS] = [dbo].[BLLICENSETYPECLASS].[CUSTOMFIELDLAYOUTID]
LEFT JOIN [dbo].[CUSTOMFIELDLAYOUT] [ONLINECUSTOMFIELDLAYOUT]
	ON [ONLINECUSTOMFIELDLAYOUT].[GCUSTOMFIELDLAYOUTS] = [dbo].[BLLICENSETYPECLASS].[ONLINECUSTOMFIELDLAYOUTID]
LEFT JOIN [dbo].[CAFEETEMPLATE] [FEESTEMPLATE]
	ON [FEESTEMPLATE].[CAFEETEMPLATEID] = [dbo].[BLLICENSETYPECLASS].[CAFEETEMPLATEID]
LEFT JOIN [dbo].[LICENSECYCLE] 
	ON [dbo].[LICENSECYCLE].[LICENSECYCLEID] = [dbo].[BLLICENSETYPECLASS].[LICENSECYCLEID]
INNER JOIN [dbo].[BLLICENSECAPAPPLICATIONTYPE][BLLICENSEONLINEAPPLYTYPE]
	ON [BLLICENSEONLINEAPPLYTYPE].[BLLICENSECAPAPPLICATIONTYPEID] =  [dbo].[BLLICENSETYPECLASS].[BLLICENSECAPAPPLICATIONTYPEID]
INNER JOIN [dbo].[BLLICENSECAPAPPLICATIONTYPE][BLLICENSEONLINERENEWTYPE]
	ON [BLLICENSEONLINERENEWTYPE].[BLLICENSECAPAPPLICATIONTYPEID] =  [dbo].[BLLICENSETYPECLASS].[ONLINERENEWTYPEID]

WHERE
	[dbo].[BLLICENSETYPECLASS].[BLLICENSETYPEID] = @BLLICENSETYPEID
	ORDER BY [dbo].[BLLICENSECLASS].[NAME]
END