CREATE PROCEDURE [businessmanagementsetup].[USP_RPLANDLORDLICENSETYPE_GETALL]
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[RPLANDLORDLICENSETYPE].[RPLANDLORDLICENSETYPEID],
	[dbo].[RPLANDLORDLICENSETYPE].[NAME],
	[dbo].[RPLANDLORDLICENSETYPE].[DESCRIPTION],
	[dbo].[RPLANDLORDLICENSETYPE].[FRIENDLYNAME],
	[dbo].[RPLANDLORDLICENSETYPE].[PREFIX],
	[dbo].[RPLANDLORDLICENSETYPE].[DEFAULTSTATUSID],
	[dbo].[RPLANDLORDLICENSETYPE].[CUSTOMFIELDLAYOUTID],
	[dbo].[RPLANDLORDLICENSETYPE].[CAFEETEMPLATEID],
	[dbo].[RPLANDLORDLICENSETYPE].[ACTIVE],
	[dbo].[RPLANDLORDLICENSETYPE].[BLEINFORMATID],
	[dbo].[RPLANDLORDLICENSETYPE].[LASTCHANGEDBY],
	[dbo].[RPLANDLORDLICENSETYPE].[LASTCHANGEDON],
	[dbo].[RPLANDLORDLICENSETYPE].[ROWVERSION]
FROM [dbo].[RPLANDLORDLICENSETYPE]
ORDER BY [dbo].[RPLANDLORDLICENSETYPE].[NAME] ASC

EXEC [businessmanagementsetup].[USP_RPLANDLORDTYPECONTACTTYPE_GETALL]
END