CREATE PROCEDURE [businessmanagementsetup].[USP_ILLICENSETYPECLASSTYPE_GETBYPARENTID]
(
	@ILLICENSETYPEID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[dbo].[ILLICENSETYPECLASSTYPE].[ILLICENSETYPECLASSTYPEID],
	[dbo].[ILLICENSETYPECLASSTYPE].[ILLICENSETYPEID],
	[dbo].[ILLICENSETYPECLASSTYPE].[ILLICENSECLASSTYPEID],
	[dbo].[ILLICENSECLASSTYPE].[NAME]
FROM [dbo].[ILLICENSETYPECLASSTYPE]
INNER JOIN [dbo].[ILLICENSECLASSTYPE] 
	ON [dbo].[ILLICENSECLASSTYPE].[ILLICENSECLASSTYPEID] = [dbo].[ILLICENSETYPECLASSTYPE].[ILLICENSECLASSTYPEID]
WHERE
	[dbo].[ILLICENSETYPECLASSTYPE].[ILLICENSETYPEID] = @ILLICENSETYPEID
ORDER BY [dbo].[ILLICENSECLASSTYPE] .[NAME]
END