CREATE PROCEDURE [maps].[USP_PERMIT_PARCELSPLIT_DETAILS]
(
	@ENTITYID AS CHAR(36)
)
AS 
BEGIN
	DECLARE @ENTITYLIST AS RecordIDs
	INSERT INTO @ENTITYLIST (RECORDID) VALUES (@ENTITYID)
SELECT 
		PMPERMIT.PMPERMITID,
		PMPERMIT.PERMITNUMBER,
		PMPERMITTYPE.NAME, 
		PMPERMITWORKCLASS.NAME,
		'Permit' AS MODULE,
		PMPERMIT.PMPERMITTYPEID,
		PMPERMIT.PMPERMITWORKCLASSID,
		PMPERMIT.APPLYDATE,
		PROJECTDETAILS.PRPROJECTID,
		PROJECTDETAILS.NAME
	FROM PMPERMIT
	INNER JOIN PMPERMITTYPE ON PMPERMIT.PMPERMITTYPEID = PMPERMITTYPE.PMPERMITTYPEID
	INNER JOIN PMPERMITWORKCLASS ON PMPERMIT.PMPERMITWORKCLASSID = PMPERMITWORKCLASS.PMPERMITWORKCLASSID
	OUTER APPLY (SELECT TOP 1 PRPROJECT.PRPROJECTID, PRPROJECT.NAME 
		FROM PRPROJECTPERMIT
		INNER JOIN PRPROJECT ON PRPROJECT.PRPROJECTID = PRPROJECTPERMIT.PRPROJECTID
		WHERE PRPROJECTPERMIT.PMPERMITID = PMPERMIT.PMPERMITID) PROJECTDETAILS
	WHERE [PMPERMIT].[PMPERMITID] = @ENTITYID
	EXEC [common].[USP_PMPERMITADDRESS_GETBYIDS] @ENTITYLIST
	SELECT 
		PMPERMITPARCEL.PMPERMITPARCELID,
		PARCEL.PARCELID,
		PARCEL.PARCELNUMBER,
		PMPERMITPARCEL.MAIN,
		PMPERMITPARCEL.PARCELSPLITPROCESS
	FROM PMPERMITPARCEL
	INNER JOIN PARCEL ON PMPERMITPARCEL.PARCELID = PARCEL.PARCELID
	WHERE PMPERMITPARCEL.PMPERMITID = @ENTITYID AND (PMPERMITPARCEL.PARCELSPLITPROCESS = 1 OR PMPERMITPARCEL.MAIN = 1)
END