CREATE PROCEDURE [dbo].[USP_USERS_UPDATE]
(
	@SUSERGUID CHAR(36),
	@SROLEID CHAR(36),
	@SITEID NVARCHAR(10),
	@ID NVARCHAR(254),
	@FNAME NVARCHAR(30),
	@LNAME NVARCHAR(30),
	@PASSWORD NVARCHAR(100),
	@PHONE NVARCHAR(40),
	@EMAIL NVARCHAR(80),
	@BACTIVE BIT,
	@BGETINTERNETNOTES BIT,
	@BGETBUSINESSNOTES BIT,
	@BGETCODENEITES BIT,
	@LASTCHANGEDON DATETIME,
	@LASTCHANGEDBY CHAR(36),
	@GMAPID CHAR(36),
	@GLOBALENTITYID CHAR(36),
	@MAILINGADDRESSID CHAR(36),
	@ROWVERSION INT,
	@ISPASSWORDCHANGEREQUIRED BIT,
	@APPLICATIONERRORS BIT,
	@SECURITYISACTIVEDIRECTORY BIT,
	@COMPANY NVARCHAR(100),
	@MIDDLENAME NVARCHAR(50),
	@CREATEDON DATETIME,
	@TITLE VARCHAR(50),
	@CREDENTIALS VARCHAR(50),
	@OFFICEID CHAR(36),
	@LICENSE_SUITE NVARCHAR(MAX),
	@MAINMAPSORTORDER INT,
	@GLOBALPREFFERCOMMID INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
UPDATE [dbo].[USERS] SET
	[SROLEID] = @SROLEID,
	[SITEID] = @SITEID,
	[ID] = @ID,
	[FNAME] = @FNAME,
	[LNAME] = @LNAME,
	[PASSWORD] = @PASSWORD,
	[PHONE] = @PHONE,
	[EMAIL] = @EMAIL,
	[BACTIVE] = @BACTIVE,
	[BGETINTERNETNOTES] = @BGETINTERNETNOTES,
	[BGETBUSINESSNOTES] = @BGETBUSINESSNOTES,
	[BGETCODENEITES] = @BGETCODENEITES,
	[LASTCHANGEDON] = @LASTCHANGEDON,
	[LASTCHANGEDBY] = @LASTCHANGEDBY,
	[GMAPID] = @GMAPID,
	[GLOBALENTITYID] = @GLOBALENTITYID,
	[MAILINGADDRESSID] = @MAILINGADDRESSID,
	[ROWVERSION] = @ROWVERSION + 1,
	[ISPASSWORDCHANGEREQUIRED] = @ISPASSWORDCHANGEREQUIRED,
	[APPLICATIONERRORS] = @APPLICATIONERRORS,
	[SECURITYISACTIVEDIRECTORY] = @SECURITYISACTIVEDIRECTORY,
	[COMPANY] = @COMPANY,
	[MIDDLENAME] = @MIDDLENAME,
	[CREATEDON] = @CREATEDON,
	[TITLE] = @TITLE,
	[CREDENTIALS] = @CREDENTIALS,
	[OFFICEID] = @OFFICEID,
	[LICENSE_SUITE] = @LICENSE_SUITE,
	[MAINMAPSORTORDER] = @MAINMAPSORTORDER,
	[GLOBALPREFFERCOMMID] = @GLOBALPREFFERCOMMID
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
WHERE
	[SUSERGUID] = @SUSERGUID AND 
	[ROWVERSION]= @ROWVERSION

SELECT * FROM @OUTPUTTABLE