CREATE PROCEDURE [dbo].[USP_USERDEPARTMENT_DELETE]
(
@SUSERGUID CHAR(36),
@DEPARTMENTID CHAR(36)
)
AS
DELETE FROM [dbo].[USERDEPARTMENT]
WHERE
	[SUSERGUID] = @SUSERGUID AND 
	[DEPARTMENTID] = @DEPARTMENTID