CREATE PROCEDURE [incidentrequest].[USP_CITIZENREQUESTATTACHEDCASELIST_GETBYPARENTID]
(
	@PARENTID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[CMCASETYPE].[NAME],
	[CMCODECASE].[CASENUMBER],
	[CITIZENREQUESTATTACHEDCASETYPE].[REQUESTATTACHEDCASENAME],
	[CMCODECASESTATUS].[NAME],
	[USERS].[FNAME]+' '+[USERS].[LNAME] ,
	[CMCODECASE].[OPENEDDATE],
	[CMCODECASE].[CMCODECASEID]
FROM [CITIZENREQUESTATTACHEDCASELIST]
	INNER JOIN [CITIZENREQUESTATTACHEDCASETYPE] ON [CITIZENREQUESTATTACHEDCASELIST].[REQUESTATTACHEDCASETYPEID] = [CITIZENREQUESTATTACHEDCASETYPE].[REQUESTATTACHEDCASETYPEID]
	LEFT JOIN [CMCODECASE] ON [CMCODECASE].[CMCODECASEID] = [CITIZENREQUESTATTACHEDCASELIST].[ATTACHEDCASEID]
	LEFT JOIN [CMCASETYPE] ON [CMCASETYPE].[CMCASETYPEID] = [CMCODECASE].[CMCASETYPEID]
	LEFT JOIN [CMCODECASESTATUS] ON [CMCODECASESTATUS].[CMCODECASESTATUSID] = [CMCODECASE].[CMCODECASESTATUSID]
	LEFT JOIN [USERS] ON [USERS].[SUSERGUID] = [CMCODECASE].[ASSIGNEDTO]
WHERE 
	[CITIZENREQUESTATTACHEDCASELIST].[CITIZENREQUESTID] = @PARENTID
	AND
	[CITIZENREQUESTATTACHEDCASETYPE].[REQUESTATTACHEDCASETYPEID] IN ('BF1483A4-C57A-4463-ADC1-5F3B9293B3D4') --Code Case only 

END