CREATE PROCEDURE [incidentrequest].[USP_CONTACT_REQUEST_LINKEDRECORDS_GETBYPARENTID]
(
	@PARENTID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[CITIZENREQUEST].[REQUESTNUMBER],
	[CITIZENREQUESTTYPE].[NAME] REQUESTTYPE,
	[CITIZENREQUESTSTATUS].[STATUS],
	[CITIZENREQUESTSTATUS].[RESOLVEDFLAG]
FROM [CITIZENREQUEST]
INNER JOIN [CITIZENREQUESTCALLERXREF]
ON [CITIZENREQUEST].CITIZENREQUESTID = [CITIZENREQUESTCALLERXREF].CITIZENREQUESTID
INNER JOIN [CITIZENREQUESTTYPE] WITH (NOLOCK)
ON [CITIZENREQUESTTYPE].[CITIZENREQUESTTYPEID] = [CITIZENREQUEST].[CITIZENREQUESTTYPEID]
INNER JOIN [CITIZENREQUESTSTATUS] WITH (NOLOCK)
ON [CITIZENREQUESTSTATUS].[CITIZENREQUESTSTATUSID] = [CITIZENREQUEST].[CITIZENREQUESTSTATUSID]
WHERE
	[CITIZENREQUESTCALLERXREF].[GLOBALENTITYID] = @PARENTID
END