CREATE PROCEDURE [incidentrequest].[USP_CONTACT_INVOICE_GETBYPARENTID]
(
	@PARENTID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[CAINVOICE].[INVOICETOTAL],
	[CAINVOICE].[INVOICEDATE],
	[CAINVOICE].[INVOICEDUEDATE],
	[CASTATUS].[NAME] STATUSNAME,
	CAINVOICE.INVOICENUMBER
FROM [CAINVOICE]
INNER JOIN [CAINVOICECONTACT]
ON [CAINVOICE].CAINVOICEID = [CAINVOICECONTACT].CAINVOICEID
INNER JOIN [CASTATUS]
ON [CAINVOICE].CASTATUSID = [CASTATUS].CASTATUSID
WHERE
	[CAINVOICECONTACT].[GLOBALENTITYID] = @PARENTID
-- check for only invoice status of 'Due','Past Due','Partial Payment','Invoiced','Invoiced, Past Due','Partial Payment, Past Due'
AND [CAINVOICE].CASTATUSID IN (1,2,3,6,7,8)
END