CREATE PROCEDURE [incidentrequest].[USP_CONTACT_GETBYID]
(
	@CONTACTID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;

	SELECT 
	[GLOBALENTITY].[GLOBALENTITYID],
	[GLOBALENTITY].[CONTACTID],
	[GLOBALENTITY].[ISCOMPANY],	
	[GLOBALENTITY].[ISCONTACT],
	[GLOBALENTITY].[GLOBALENTITYNAME] COMPANYNAME,
	[GLOBALENTITY].[TITLE],
	[GLOBALENTITY].[FIRSTNAME],
	[GLOBALENTITY].[MIDDLENAME],
	[GLOBALENTITY].[LASTNAME],
	[GLOBALENTITY].[EMAIL],
	[GLOBALPREFFERCOMM].[PREFNAME],
	[GLOBALENTITY].[WEBSITE],
	[GLOBALENTITY].[ISACTIVE],
	[GLOBALENTITY].[BUSINESSPHONE],
	[GLOBALENTITY].[HOMEPHONE],
	[GLOBALENTITY].[MOBILEPHONE],
	[GLOBALENTITY].[FAX],
	[GLOBALENTITY].[OTHERPHONE],	
	[GLOBALENTITY].[IMAGE]
	FROM [GLOBALENTITY] 
	INNER JOIN [GLOBALPREFFERCOMM] WITH (NOLOCK)
	ON [GLOBALPREFFERCOMM].[GLOBALPREFFERCOMMID] = [GLOBALENTITY].[PREFCOMM]
	WHERE
		[GLOBALENTITY].[GLOBALENTITYID] = @CONTACTID

	EXEC [incidentrequest].USP_CONTACT_NOTE_GETBYPARENTID @CONTACTID
	EXEC [incidentrequest].USP_CONTACT_ADDRESS_GETBYPARENTID @CONTACTID
	EXEC [incidentrequest].USP_CONTACT_INVOICE_GETBYPARENTID @CONTACTID
	EXEC [incidentrequest].USP_CONTACT_HOLD_GETBYPARENTID @CONTACTID
	EXEC [incidentrequest].USP_CONTACT_CERTIFICATION_GETBYPARENTID @CONTACTID
	EXEC [incidentrequest].USP_CONTACT_CLASSIFICATION_GETBYPARENTID @CONTACTID
	EXEC [incidentrequest].USP_CONTACT_SUBCONTACT_GETBYPARENTID @CONTACTID
	EXEC [incidentrequest].USP_CONTACT_APPLICATION_LINKEDRECORDS_GETBYPARENTID @CONTACTID
	EXEC [incidentrequest].USP_CONTACT_BUSINESSLICENSE_LINKEDRECORDS_GETBYPARENTID @CONTACTID
	EXEC [incidentrequest].USP_CONTACT_BUSINESS_LINKEDRECORDS_GETBYPARENTID @CONTACTID
	EXEC [incidentrequest].USP_CONTACT_CODECASE_LINKEDRECORDS_GETBYPARENTID @CONTACTID
	EXEC [incidentrequest].USP_CONTACT_INSPECTION_LINKEDRECORDS_GETBYPARENTID @CONTACTID
	EXEC [incidentrequest].USP_CONTACT_IPCASE_LINKEDRECORDS_GETBYPARENTID @CONTACTID
	EXEC [incidentrequest].USP_CONTACT_LANDLICENSE_LINKEDRECORDS_GETBYPARENTID @CONTACTID
	EXEC [incidentrequest].USP_CONTACT_PERMIT_LINKEDRECORDS_GETBYPARENTID @CONTACTID
	EXEC [incidentrequest].USP_CONTACT_PERMITRENEWAL_LINKEDRECORDS_GETBYPARENTID @CONTACTID
	EXEC [incidentrequest].USP_CONTACT_PLAN_LINKEDRECORDS_GETBYPARENTID @CONTACTID
	EXEC [incidentrequest].USP_CONTACT_PROFLICENSE_LINKEDRECORDS_GETBYPARENTID @CONTACTID
	EXEC [incidentrequest].USP_CONTACT_PROJECT_LINKEDRECORDS_GETBYPARENTID @CONTACTID
	EXEC [incidentrequest].USP_CONTACT_REMITTANCE_LINKEDRECORDS_GETBYPARENTID @CONTACTID
	EXEC [incidentrequest].USP_CONTACT_RENTAL_LINKEDRECORDS_GETBYPARENTID @CONTACTID
	EXEC [incidentrequest].USP_CONTACT_REQUEST_LINKEDRECORDS_GETBYPARENTID @CONTACTID

END