CREATE PROCEDURE [incidentrequest].[USP_CONTACT_TYPE_GETBY_INSPECTIONLINKID]
	@INSPECTIONLINKID INT
AS
BEGIN
SET NOCOUNT ON;
	IF @INSPECTIONLINKID = 0
		SELECT 
			[dbo].[LANDMANAGEMENTCONTACTTYPE].[LANDMANAGEMENTCONTACTTYPEID] AS [CONTACTTYPEID],
			[dbo].[LANDMANAGEMENTCONTACTTYPE].[NAME],
			[dbo].[LANDMANAGEMENTCONTACTTYPE].[DESCRIPTION],
			[dbo].[LANDMANAGEMENTCONTACTSYSTEMTYP].[LANDMANAGEMENTCONTACTSYSTEMTYP] AS [SYSTEMCATEGORYID],
			[dbo].[LANDMANAGEMENTCONTACTSYSTEMTYP].[NAME] AS [SYSTEMCATEGORYNAME]
		FROM [dbo].[LANDMANAGEMENTCONTACTTYPE]
		INNER JOIN [dbo].[LANDMANAGEMENTCONTACTSYSTEMTYP] 
		ON [dbo].[LANDMANAGEMENTCONTACTTYPE].[LANDMANAGEMENTCONTACTSYSTEMTYP] = [dbo].[LANDMANAGEMENTCONTACTSYSTEMTYP].[LANDMANAGEMENTCONTACTSYSTEMTYP]
		UNION ALL
		SELECT 
			[dbo].[CMCODECASECONTACTTYPE].[CMCODECASECONTACTTYPEID] AS [CONTACTTYPEID],
			[dbo].[CMCODECASECONTACTTYPE].[NAME],
			[dbo].[CMCODECASECONTACTTYPE].[DESCRIPTION],
			[dbo].[CMCONTACTTYPESYSTEM].[CMCONTACTTYPESYSTEMID] AS [SYSTEMCATEGORYID],
			[dbo].[CMCONTACTTYPESYSTEM].[NAME] AS [SYSTEMCATEGORYNAME]
		FROM [dbo].[CMCODECASECONTACTTYPE]
		INNER JOIN [dbo].[CMCONTACTTYPESYSTEM] 
		ON [dbo].[CMCODECASECONTACTTYPE].[CMCONTACTTYPESYSTEMID] = [dbo].[CMCONTACTTYPESYSTEM].[CMCONTACTTYPESYSTEMID]
		UNION ALL
		SELECT 
			[dbo].[BLCONTACTTYPE].[BLCONTACTTYPEID] AS [CONTACTTYPEID],
			[dbo].[BLCONTACTTYPE].[NAME],
			[dbo].[BLCONTACTTYPE].[DESCRIPTION],
			[dbo].[BLCONTACTTYPESYSTEM].[BLCONTACTTYPESYSTEMID] AS [SYSTEMCATEGORYID],
			[dbo].[BLCONTACTTYPESYSTEM].[NAME] AS [SYSTEMCATEGORYNAME]
		FROM [dbo].[BLCONTACTTYPE]
		INNER JOIN [dbo].[BLCONTACTTYPESYSTEM]
		ON [dbo].[BLCONTACTTYPE].[BLCONTACTTYPESYSTEMID] = [dbo].[BLCONTACTTYPESYSTEM].[BLCONTACTTYPESYSTEMID]
		UNION ALL
		SELECT 
			[dbo].[RPCONTACTTYPE].[RPCONTACTTYPEID] AS [CONTACTTYPEID],
			[dbo].[RPCONTACTTYPE].[NAME],
			[dbo].[RPCONTACTTYPE].[DESCRIPTION],
			[dbo].[RPCONTACTTYPESYSTEM].[RPCONTACTTYPESYSTEMID] AS [SYSTEMCATEGORYID],
			[dbo].[RPCONTACTTYPESYSTEM].[NAME] AS [SYSTEMCATEGORYNAME]
		FROM [dbo].[RPCONTACTTYPE] 
		INNER JOIN [dbo].[RPCONTACTTYPESYSTEM] 
		ON [dbo].[RPCONTACTTYPE].[RPCONTACTTYPESYSTEMID] = [dbo].[RPCONTACTTYPESYSTEM].[RPCONTACTTYPESYSTEMID]

	IF @INSPECTIONLINKID = 1 OR @INSPECTIONLINKID = 2
		SELECT 
			[dbo].[LANDMANAGEMENTCONTACTTYPE].[LANDMANAGEMENTCONTACTTYPEID] AS [CONTACTTYPEID],
			[dbo].[LANDMANAGEMENTCONTACTTYPE].[NAME],
			[dbo].[LANDMANAGEMENTCONTACTTYPE].[DESCRIPTION],
			[dbo].[LANDMANAGEMENTCONTACTSYSTEMTYP].[LANDMANAGEMENTCONTACTSYSTEMTYP] AS [SYSTEMCATEGORYID],
			[dbo].[LANDMANAGEMENTCONTACTSYSTEMTYP].[NAME] AS [SYSTEMCATEGORYNAME]
		FROM [dbo].[LANDMANAGEMENTCONTACTTYPE]
		INNER JOIN [dbo].[LANDMANAGEMENTCONTACTSYSTEMTYP] 
		ON [dbo].[LANDMANAGEMENTCONTACTTYPE].[LANDMANAGEMENTCONTACTSYSTEMTYP] = [dbo].[LANDMANAGEMENTCONTACTSYSTEMTYP].[LANDMANAGEMENTCONTACTSYSTEMTYP]

	IF @INSPECTIONLINKID = 3 OR @INSPECTIONLINKID = 4
		SELECT 
			[dbo].[CMCODECASECONTACTTYPE].[CMCODECASECONTACTTYPEID] AS [CONTACTTYPEID],
			[dbo].[CMCODECASECONTACTTYPE].[NAME],
			[dbo].[CMCODECASECONTACTTYPE].[DESCRIPTION],
			[dbo].[CMCONTACTTYPESYSTEM].[CMCONTACTTYPESYSTEMID] AS [SYSTEMCATEGORYID],
			[dbo].[CMCONTACTTYPESYSTEM].[NAME] AS [SYSTEMCATEGORYNAME]
		FROM [dbo].[CMCODECASECONTACTTYPE]
		INNER JOIN [dbo].[CMCONTACTTYPESYSTEM] 
		ON [dbo].[CMCODECASECONTACTTYPE].[CMCONTACTTYPESYSTEMID] = [dbo].[CMCONTACTTYPESYSTEM].[CMCONTACTTYPESYSTEMID]

	IF @INSPECTIONLINKID = 5 OR @INSPECTIONLINKID = 6 OR @INSPECTIONLINKID = 7
		SELECT 
			[dbo].[BLCONTACTTYPE].[BLCONTACTTYPEID] AS [CONTACTTYPEID],
			[dbo].[BLCONTACTTYPE].[NAME],
			[dbo].[BLCONTACTTYPE].[DESCRIPTION],
			[dbo].[BLCONTACTTYPESYSTEM].[BLCONTACTTYPESYSTEMID] AS [SYSTEMCATEGORYID],
			[dbo].[BLCONTACTTYPESYSTEM].[NAME] AS [SYSTEMCATEGORYNAME]
		FROM [dbo].[BLCONTACTTYPE]
		INNER JOIN [dbo].[BLCONTACTTYPESYSTEM]
		ON [dbo].[BLCONTACTTYPE].[BLCONTACTTYPESYSTEMID] = [dbo].[BLCONTACTTYPESYSTEM].[BLCONTACTTYPESYSTEMID]

	IF @INSPECTIONLINKID = 8 OR @INSPECTIONLINKID = 9
		SELECT 
			[dbo].[RPCONTACTTYPE].[RPCONTACTTYPEID] AS [CONTACTTYPEID],
			[dbo].[RPCONTACTTYPE].[NAME],
			[dbo].[RPCONTACTTYPE].[DESCRIPTION],
			[dbo].[RPCONTACTTYPESYSTEM].[RPCONTACTTYPESYSTEMID] AS [SYSTEMCATEGORYID],
			[dbo].[RPCONTACTTYPESYSTEM].[NAME] AS [SYSTEMCATEGORYNAME]
		FROM [dbo].[RPCONTACTTYPE] 
		INNER JOIN [dbo].[RPCONTACTTYPESYSTEM] 
		ON [dbo].[RPCONTACTTYPE].[RPCONTACTTYPESYSTEMID] = [dbo].[RPCONTACTTYPESYSTEM].[RPCONTACTTYPESYSTEMID]
END