CREATE PROCEDURE [incidentrequest].[USP_CITIZENREQUESTADDRESS_GETBYPARENTID]
(
	@PARENTID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[MAILINGADDRESS].[ADDRESSTYPE],
	[MAILINGADDRESS].[ADDRESSLINE1],
	[MAILINGADDRESS].[ADDRESSLINE2],
	[MAILINGADDRESS].[ADDRESSLINE3],
	[MAILINGADDRESS].[STREETTYPE],
	[MAILINGADDRESS].[PREDIRECTION],
	[MAILINGADDRESS].[POSTDIRECTION],
	[MAILINGADDRESS].[UNITORSUITE],
	[MAILINGADDRESS].[CITY],
	[MAILINGADDRESS].[STATE],
	[MAILINGADDRESS].[POSTALCODE],
	[MAILINGADDRESS].[PARCELNUMBER],
	[MAILINGADDRESS].[COUNTRY],
	[CITIZENREQUESTADDRESS].[MAIN]	
FROM [dbo].[CITIZENREQUESTADDRESS]
INNER JOIN [MAILINGADDRESS] ON [MAILINGADDRESS].[MAILINGADDRESSID] = [CITIZENREQUESTADDRESS].[MAILINGADDRESSID]
WHERE
	[CITIZENREQUESTID] = @PARENTID
END