CREATE PROCEDURE [incidentrequest].[USP_CONTACT_SUBCONTACT_GETBYPARENTID]
(
	@PARENTID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[SUBCONTACT].[GLOBALENTITYNAME] COMPANYNAME,
	[SUBCONTACT].[FIRSTNAME],
	[SUBCONTACT].[LASTNAME],
	[SUBCONTACT].[MIDDLENAME],
	[SUBCONTACT].[TITLE],
	[SUBCONTACT].[GLOBALENTITYID]
FROM [GLOBALENTITY] MAINCONTACT
INNER JOIN [GLOBALENTITY] SUBCONTACT
ON [MAINCONTACT].GLOBALENTITYID = [SUBCONTACT].PARENTGLOBALENTITYID
WHERE
	[MAINCONTACT].[GLOBALENTITYID] = @PARENTID
END