CREATE PROCEDURE [incidentrequest].[USP_CONTACT_BUSINESSLICENSE_LINKEDRECORDS_GETBYPARENTID]
(
	@PARENTID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;
SELECT 
	[BLLICENSE].[LICENSENUMBER] CASENUMBER,
	[BLLICENSETYPE].[NAME] CASETYPE,
	[BLLICENSESTATUS].[NAME] [STATUS],
	[BLLICENSESTATUSSYSTEM].[NAME] SYSTEMSTATUS
FROM [BLLICENSE]
INNER JOIN [BLLICENSECONTACT]
ON [BLLICENSECONTACT].[BLLICENSEID] = [BLLICENSE].[BLLICENSEID]
INNER JOIN [BLLICENSETYPE] WITH (NOLOCK)
ON [BLLICENSETYPE].[BLLICENSETYPEID] = [BLLICENSE].[BLLICENSETYPEID]
INNER JOIN [BLLICENSESTATUS] WITH (NOLOCK)
ON [BLLICENSESTATUS].[BLLICENSESTATUSID] = [BLLICENSE].[BLLICENSESTATUSID]
INNER JOIN [BLLICENSESTATUSSYSTEM]
ON [BLLICENSESTATUS].[BLLICENSESTATUSSYSTEMID] = [BLLICENSESTATUSSYSTEM].[BLLICENSESTATUSSYSTEMID]
WHERE
	[BLLICENSECONTACT].[GLOBALENTITYID] = @PARENTID
END