CREATE PROCEDURE [filetransfer].[USP_ERPROJECTFILEVERSIONFILEATTRIBUTES_GETBYERPROJECTFILEVERSIONID]
(
	 @ERPROJECTFILEVERSIONID AS CHAR(36)
)
AS  
BEGIN  
 SET NOCOUNT ON;  

    SELECT    
        ERPROJECTFILEVERSIONFILEATTRIBUTES.ERPROJECTFILEVERSIONFILEATTRIBUTEID,
        ERPROJECTFILEVERSION.ERPROJECTFILEVERSIONID,
        ERPROJECTFILEVERSIONFILEATTRIBUTES.ERPROJECTFILEATTRIBUTETYPEID,
        ERPROJECTFILEVERSIONFILEATTRIBUTES.BITVALUE,
        ERPROJECTFILEVERSIONFILEATTRIBUTES.STRINGVALUE
    FROM  ERPROJECTFILEVERSIONFILEATTRIBUTES
        JOIN ERPROJECTFILEVERSION on ERPROJECTFILEVERSION.ERPROJECTFILEVERSIONID = ERPROJECTFILEVERSIONFILEATTRIBUTES.ERPROJECTFILEVERSIONID
        WHERE ERPROJECTFILEVERSION.ERPROJECTFILEVERSIONID = @ERPROJECTFILEVERSIONID

END