CREATE PROCEDURE [filetransfer].[USP_ERPROJECTFILE_GETBYID]
(
	 @FILEID AS CHAR(36)
)
AS  
BEGIN  
 SET NOCOUNT ON;  

    SELECT TOP 1
        ERPROJECTFILEVERSION.ERPROJECTFILEVERSIONID AS FileId,
        ERPROJECTFILEVERSION.SAVEFILENAME AS [FileName],
        ERPROJECT.UPLOADFOLDER AS FilePath,
        CASE WHEN ERPROJECTFILEVERSION.ISFILESECURE IS NULL THEN 0 ELSE ERPROJECTFILEVERSION.ISFILESECURE END AS IsFileSecure,
        COALESCE(ERPROJECTFILEVERSION.ISSELFSIGNED, 0) AS ISSELFSIGNED,
        COALESCE(ERPROJECTFILEVERSION.ISTHIRDPARTYSIGNED, 0) AS ISTHIRDPARTYSIGNED,
		ERPROJECTFILEVERSION.ORIGINFILENAME

    FROM ERPROJECT
        JOIN ERPROJECTFILE on ERPROJECT.ERPROJECTID = ERPROJECTFILE.ERPROJECTID
        JOIN ERPROJECTFILEVERSION on ERPROJECTFILE.ERPROJECTFILEID = ERPROJECTFILEVERSION.ERPROJECTFILEID
        WHERE ERPROJECTFILEVERSION.ERPROJECTFILEVERSIONID = @FILEID
         
    EXEC [filetransfer].[USP_ERPROJECTFILEVERSIONFILEATTRIBUTES_GETBYERPROJECTFILEVERSIONID] @ERPROJECTFILEVERSIONID = @FILEID

END