CREATE PROCEDURE [metadata].[USP_METADATACLASSPROPERTY_GETBYPARENTTYPENAME]
(
	@TYPEFULLNAME nvarchar(250),
	@PROPERTYNAMELIST LONG_NAMES READONLY 
 )
AS
BEGIN
	SET NOCOUNT ON;
	SELECT 
		[dbo].[METADATACLASSPROPERTY].[NAME],
		[dbo].[METADATACLASSPROPERTY].[FRIENDLYNAME],
		CASE WHEN [dbo].[METADATACLASSPROPERTY].[HASCHILDREN] = 1 THEN [dbo].[METADATACLASSPROPERTY].[TYPENAME] ELSE [dbo].[METADATACLASS].[NAME] END AS TYPENAME,
		CASE WHEN [dbo].[METADATACLASSPROPERTY].[HASCHILDREN] = 1 THEN [dbo].[METADATACLASSPROPERTY].[TYPEFULLNAME] ELSE [dbo].[METADATACLASS].[TYPEFULLNAME] END AS TYPEFULLNAME,
		[ISPRIMARYKEY],
		[GENERICTYPEISPRIMITIVE],
		[GENERICTYPEISENUMERABLE],
		[HASCHILDREN],
		[CONTROLTYPEID],
		[LOOKUPTABLENAME],
		[GISFEATURESETNAME],
		[ISGEOCALLERTYPE],
		[PROPERTYNAME],
		NULL AS CONDITIONID,
		[dbo].[METADATACLASSPROPERTY].[TYPENAME] AS DATATYPE,
		[dbo].[METADATACLASSPROPERTY].[ISWORKFLOWATTRIBUTE]
	FROM [dbo].[METADATACLASS]
	JOIN [dbo].[METADATACLASSPROPERTY] ON [dbo].[METADATACLASS].ID = [dbo].[METADATACLASSPROPERTY].PARENTID
	LEFT JOIN @PROPERTYNAMELIST PROPERTYNAMELIST ON [dbo].[METADATACLASSPROPERTY].[NAME] = PROPERTYNAMELIST.NAME
	WHERE [dbo].[METADATACLASS].TYPEFULLNAME = @TYPEFULLNAME AND
	(PROPERTYNAMELIST.[NAME] IS NOT NULL OR (SELECT COUNT(*) FROM @PROPERTYNAMELIST) = 0)
	ORDER BY [dbo].[METADATACLASSPROPERTY].[FRIENDLYNAME]

END