CREATE PROCEDURE [metadata].[USP_METADATACLASSPROPERTY_GETBYWORKFLOWID]
	(@WORKFLOWID char(36))
AS
BEGIN
	SET NOCOUNT ON;
	SELECT  
		ISNULL([dbo].[METADATACLASSPROPERTY].[NAME], [dbo].[METADATACLASS].[NAME]),
		ISNULL([dbo].[METADATACLASSPROPERTY].[FRIENDLYNAME], [dbo].[METADATACLASS].[FRIENDLYNAME]),
		CASE WHEN [dbo].[METADATACLASSPROPERTY].[HASCHILDREN] = 1 THEN [dbo].[METADATACLASSPROPERTY].[TYPENAME] ELSE [dbo].[METADATACLASS].[NAME] END AS TYPENAME,
		CASE WHEN [dbo].[METADATACLASSPROPERTY].[HASCHILDREN] = 1 THEN [dbo].[METADATACLASSPROPERTY].[TYPEFULLNAME] ELSE [dbo].[METADATACLASS].[TYPEFULLNAME] END AS TYPEFULLNAME,
		[ISPRIMARYKEY],
		[GENERICTYPEISPRIMITIVE],
		[GENERICTYPEISENUMERABLE],
		[HASCHILDREN],
		[CONTROLTYPEID],
		[LOOKUPTABLENAME],
		[GISFEATURESETNAME],
		[ISGEOCALLERTYPE],
		[dbo].[METADATACLASSPROPERTY].[PROPERTYNAME],
		[dbo].[WORKFLOWCONDITION].WORKFLOWCONDITIONID AS CONDITIONID,
		[dbo].[METADATACLASSPROPERTY].[TYPENAME] AS DATATYPE,
		[dbo].[METADATACLASSPROPERTY].[ISWORKFLOWATTRIBUTE]
	FROM [dbo].[WORKFLOWCONDITIONGROUP]
	JOIN [dbo].[WORKFLOWCONDITION] ON [dbo].[WORKFLOWCONDITIONGROUP].WORKFLOWCONDITIONGROUPID = [dbo].[WORKFLOWCONDITION].WORKFLOWCONDITIONGROUPID
	LEFT JOIN [dbo].[METADATACLASS] ON [dbo].[WORKFLOWCONDITION].CLASSNAME = [dbo].[METADATACLASS].TYPEFULLNAME
	LEFT JOIN [dbo].[METADATACLASSPROPERTY] ON [dbo].[METADATACLASS].ID = [dbo].[METADATACLASSPROPERTY].PARENTID AND [dbo].[WORKFLOWCONDITION].PROPERTYNAME = [dbo].[METADATACLASSPROPERTY].NAME
	WHERE [dbo].[WORKFLOWCONDITIONGROUP].WORKFLOWID = @WORKFLOWID AND ([dbo].[WORKFLOWCONDITION].CUSTOMFIELDNAME = '' OR [dbo].[WORKFLOWCONDITION].CUSTOMFIELDNAME IS NULL)

END