CREATE FUNCTION [laxreports].[CustomFieldTableRowNumbers]
(
	@TABLEID char(36),
	@PERMITID char(36),
	@MODULEID int
)
RETURNS @returntable TABLE
(
	RowNumber INT
)
AS
BEGIN
	INSERT @returntable
	SELECT 
		x.ROWNUMBER
	FROM (
		SELECT col.ROWNUMBER FROM [$(EnerGovDatabase)].dbo.CUSTOMSAVERTBLCOL_BLN col INNER JOIN [$(EnerGovDatabase)].dbo.CUSTOMFIELDTABLECOLUMNREF colref ON col.CFTABLECOLUMNREFID = colref.CUSTOMFIELDTABLECOLUMNREFID WHERE colref.CUSTOMFIELDTABLEID = @TABLEID AND col.OBJECTID = @PERMITID AND col.MODULEID = @MODULEID
		UNION SELECT col.ROWNUMBER FROM [$(EnerGovDatabase)].dbo.CUSTOMSAVERTBLCOL_DATE col INNER JOIN [$(EnerGovDatabase)].dbo.CUSTOMFIELDTABLECOLUMNREF colref ON col.CFTABLECOLUMNREFID = colref.CUSTOMFIELDTABLECOLUMNREFID WHERE colref.CUSTOMFIELDTABLEID = @TABLEID AND col.OBJECTID = @PERMITID AND col.MODULEID = @MODULEID
		UNION SELECT col.ROWNUMBER FROM [$(EnerGovDatabase)].dbo.CUSTOMSAVERTBLCOL_FLT col INNER JOIN [$(EnerGovDatabase)].dbo.CUSTOMFIELDTABLECOLUMNREF colref ON col.CFTABLECOLUMNREFID = colref.CUSTOMFIELDTABLECOLUMNREFID WHERE colref.CUSTOMFIELDTABLEID = @TABLEID AND col.OBJECTID = @PERMITID AND col.MODULEID = @MODULEID
		UNION SELECT col.ROWNUMBER FROM [$(EnerGovDatabase)].dbo.CUSTOMSAVERTBLCOL_INT col INNER JOIN [$(EnerGovDatabase)].dbo.CUSTOMFIELDTABLECOLUMNREF colref ON col.CFTABLECOLUMNREFID = colref.CUSTOMFIELDTABLECOLUMNREFID WHERE colref.CUSTOMFIELDTABLEID = @TABLEID AND col.OBJECTID = @PERMITID AND col.MODULEID = @MODULEID
		UNION SELECT col.ROWNUMBER FROM [$(EnerGovDatabase)].dbo.CUSTOMSAVERTBLCOL_LST col INNER JOIN [$(EnerGovDatabase)].dbo.CUSTOMFIELDTABLECOLUMNREF colref ON col.CFTABLECOLUMNREFID = colref.CUSTOMFIELDTABLECOLUMNREFID WHERE colref.CUSTOMFIELDTABLEID = @TABLEID AND col.OBJECTID = @PERMITID AND col.MODULEID = @MODULEID
		UNION SELECT col.ROWNUMBER FROM [$(EnerGovDatabase)].dbo.CUSTOMSAVERTBLCOL_MEM col INNER JOIN [$(EnerGovDatabase)].dbo.CUSTOMFIELDTABLECOLUMNREF colref ON col.CFTABLECOLUMNREFID = colref.CUSTOMFIELDTABLECOLUMNREFID WHERE colref.CUSTOMFIELDTABLEID = @TABLEID AND col.OBJECTID = @PERMITID AND col.MODULEID = @MODULEID
		UNION SELECT col.ROWNUMBER FROM [$(EnerGovDatabase)].dbo.CUSTOMSAVERTBLCOL_MNY col INNER JOIN [$(EnerGovDatabase)].dbo.CUSTOMFIELDTABLECOLUMNREF colref ON col.CFTABLECOLUMNREFID = colref.CUSTOMFIELDTABLECOLUMNREFID WHERE colref.CUSTOMFIELDTABLEID = @TABLEID AND col.OBJECTID = @PERMITID AND col.MODULEID = @MODULEID
		UNION SELECT col.ROWNUMBER FROM [$(EnerGovDatabase)].dbo.CUSTOMSAVERTBLCOL_MNY col INNER JOIN [$(EnerGovDatabase)].dbo.CUSTOMFIELDTABLECOLUMNREF colref ON col.CFTABLECOLUMNREFID = colref.CUSTOMFIELDTABLECOLUMNREFID WHERE colref.CUSTOMFIELDTABLEID = @TABLEID AND col.OBJECTID = @PERMITID AND col.MODULEID = @MODULEID) AS x
	GROUP BY x.ROWNUMBER
	ORDER BY x.ROWNUMBER

	RETURN
END
