CREATE FUNCTION [laxreports].[GetCustomFieldTableStringValue]
(
	@TABLEID char(36),
	@COLUMNID char(36),
	@OBJECTID char(36),
	@MODULEID int,
	@ROWNUMBER int
)
RETURNS NVARCHAR(50)
AS
BEGIN
	DECLARE @value NVARCHAR(50);

	SELECT TOP 1 @value = col.STRINGVALUE 
		FROM [$(EnerGovDatabase)].dbo.CUSTOMSAVERTBLCOL_STR col 
		INNER JOIN [$(EnerGovDatabase)].dbo.CUSTOMFIELDTABLECOLUMNREF colref ON col.CFTABLECOLUMNREFID = colref.CUSTOMFIELDTABLECOLUMNREFID
		WHERE col.OBJECTID = @OBJECTID AND col.ROWNUMBER = @ROWNUMBER AND colref.CUSTOMFIELDTABLEID = @TABLEID AND colref.CUSTOMFIELDCOLUMNTEMPLATEID = @COLUMNID;

	RETURN @value;

END
