CREATE FUNCTION [laxreports].[GetCustomFieldTableListItemValue]
(
	@TABLEID char(36),
	@COLUMNID char(36),
	@OBJECTID char(36),
	@MODULEID int,
	@ROWNUMBER int
)
RETURNS NVARCHAR(50)
AS
BEGIN
	DECLARE @value NVARCHAR(50);

	SELECT TOP 1 @value = cfpli.SVALUE 
		FROM [$(EnerGovDatabase)].dbo.CUSTOMSAVERTBLCOL_LST col 
		INNER JOIN [$(EnerGovDatabase)].dbo.CUSTOMFIELDTABLECOLUMNREF colref ON col.CFTABLECOLUMNREFID = colref.CUSTOMFIELDTABLECOLUMNREFID
		INNER JOIN [$(EnerGovDatabase)].dbo.CUSTOMFIELDPICKLISTITEM cfpli ON col.PICKLISTVALUE = cfpli.GCUSTOMFIELDPICKLISTITEM
		WHERE col.OBJECTID = @OBJECTID AND col.ROWNUMBER = @ROWNUMBER AND colref.CUSTOMFIELDTABLEID = @TABLEID AND colref.CUSTOMFIELDCOLUMNTEMPLATEID = @COLUMNID;

	RETURN @value;

END
