CREATE PROCEDURE [dbo].[DELETECASEPARCELPROJCONDITION]
	-- Add the parameters for the stored procedure here
	@ConditionID char(36),
	@ModuleID int	
	AS
	BEGIN		
		IF @ModuleID = 1
		BEGIN
			DELETE FROM PLPLANCONDITION WHERE CONDITIONID = @ConditionID
		END
		ELSE IF @ModuleID = 2
		BEGIN
			DELETE FROM PMPERMITCONDITION WHERE CONDITIONID = @ConditionID
		END
		DELETE FROM PARCELCONDITION WHERE CONDITIONID = @ConditionID
		DELETE FROM PRPROJECTCONDITION WHERE CONDITIONID = @ConditionID
	END