CREATE PROCEDURE [dbo].[USP_DEPARTMENT_INSERT]
(
	@DEPARTMENTID CHAR(36),
	@NAME NVARCHAR(50),
	@LASTCHANGEDBY CHAR(36),
	@LASTCHANGEDON DATETIME,
	@ROWVERSION INT
)
AS
DECLARE @OUTPUTTABLE as TABLE([ROWVERSION]  int)
INSERT INTO [dbo].[DEPARTMENT](
	[DEPARTMENTID],
	[NAME],
	[LASTCHANGEDBY],
	[LASTCHANGEDON],
	[ROWVERSION]
)
OUTPUT inserted.[ROWVERSION] INTO @OUTPUTTABLE
VALUES
(
	@DEPARTMENTID,
	@NAME,
	@LASTCHANGEDBY,
	@LASTCHANGEDON,
	@ROWVERSION
)
SELECT * FROM @OUTPUTTABLE