SELECT
    buis.BLGLOBALENTITYEXTENSIONID AS BusinessId,
    buis.REGISTRATIONID AS RegistrationId,
    buis.DBA AS TradeName,
    ISNULL((SELECT COUNT(licx.BLLICENSEID)
            FROM BLGLOBALENTITYEXTENSION buisx
            INNER JOIN BLLICENSE licx ON buisx.BLGLOBALENTITYEXTENSIONID = licx.BLGLOBALENTITYEXTENSIONID
            WHERE buisx.BLGLOBALENTITYEXTENSIONID = buis.BLGLOBALENTITYEXTENSIONID AND
                  licx.TAXYEAR = @TaxYear + 1 AND
                  licx.BLLICENSETYPEID IN @LicenseTypeIds AND
                  licx.BLLICENSECLASSID IN @LicenseClassIds), 0) AS NumberOfRenewedLicenses,
    ISNULL(glent.GLOBALENTITYNAME, buis.COMPANYNAME) AS CompanyName
FROM BLGLOBALENTITYEXTENSION buis
LEFT OUTER JOIN GLOBALENTITY glent ON buis.GLOBALENTITYID = glent.GLOBALENTITYID
INNER JOIN BLLICENSE lic ON buis.BLGLOBALENTITYEXTENSIONID = lic.BLGLOBALENTITYEXTENSIONID
INNER JOIN BLGLOBALENTITYEXTENSIONADDRESS buis_addr ON buis.BLGLOBALENTITYEXTENSIONID = buis_addr.BLGLOBALENTITYEXTENSIONID AND buis_addr.MAIN = 1
INNER JOIN MAILINGADDRESS ma ON buis_addr.MAILINGADDRESSID = ma.MAILINGADDRESSID
WHERE buis.BLEXTCOMPANYTYPEID = 'b0bcecf3-927a-45ac-b93a-45cc5a5c37c0' AND
      buis.BLEXTSTATUSID = '3d99f589-e6a1-48d1-9015-3f6973034da2' AND
      lic.BLLICENSETYPEID IN @LicenseTypeIds AND
      lic.BLLICENSECLASSID IN @LicenseClassIds AND
      lic.TAXYEAR = @TaxYear
GROUP BY buis.BLGLOBALENTITYEXTENSIONID, buis.REGISTRATIONID, buis.STATETAXNUMBER, buis.DBA, glent.GLOBALENTITYNAME, buis.COMPANYNAME;