

/****** OBJECT:  StoredProcedure [dbo].[rpt_OM_Object_Attached_Records_Report_Permit]    Script Date: 02/25/2011 15:58:52 ******/
CREATE PROCEDURE rpt_OM_SR_Object_Attached_Records_Report_Permit
@OMOBJECTID AS VARCHAR(36)
AS

SELECT	PMPERMITOBJECT.OMOBJECTID, 
		PMPERMIT.PMPERMITID, PMPERMIT.PERMITNUMBER, 
		PMPERMITTYPE.NAME PERMITTYPE, 
		PMPERMITWORKCLASS.NAME PERMITCLASS,
		PMPERMITSTATUS.NAME PMPERMITSTATUS,
		PERMIT_CONTACTS.ISBILLING, PERMIT_CONTACTS.CONTACTTYPE, PERMIT_CONTACTS.GLOBALENTITYNAME, PERMIT_CONTACTS.FIRSTNAME, PERMIT_CONTACTS.LASTNAME

FROM	PMPERMITOBJECT 
		INNER JOIN PMPERMIT ON PMPERMITOBJECT.PMPERMITID = PMPERMIT.PMPERMITID
		INNER JOIN PMPERMITTYPE ON PMPERMIT.PMPERMITTYPEID = PMPERMITTYPE.PMPERMITTYPEID
		INNER JOIN PMPERMITWORKCLASS ON PMPERMIT.PMPERMITWORKCLASSID = PMPERMITWORKCLASS.PMPERMITWORKCLASSID
		INNER JOIN PMPERMITSTATUS ON PMPERMIT.PMPERMITSTATUSID = PMPERMITSTATUS.PMPERMITSTATUSID
		LEFT OUTER JOIN (SELECT PMPERMITCONTACT.PMPERMITID, PMPERMITCONTACT.ISBILLING,
								GLOBALENTITY.GLOBALENTITYNAME, GLOBALENTITY.FIRSTNAME, GLOBALENTITY.LASTNAME,
								LANDMANAGEMENTCONTACTTYPE.NAME CONTACTTYPE
						 FROM	PMPERMITCONTACT 
								INNER JOIN LANDMANAGEMENTCONTACTTYPE ON PMPERMITCONTACT.LANDMANAGEMENTCONTACTTYPEID = LANDMANAGEMENTCONTACTTYPE.LANDMANAGEMENTCONTACTTYPEID
								INNER JOIN GLOBALENTITY ON PMPERMITCONTACT.GLOBALENTITYID = GLOBALENTITY.GLOBALENTITYID
						) AS PERMIT_CONTACTS ON PMPERMIT.PMPERMITID = PERMIT_CONTACTS.PMPERMITID

WHERE	PMPERMITOBJECT.OMOBJECTID = @OMOBJECTID

