
CREATE PROCEDURE rpt_OM_SR_Object_History_Report
@OMOBJECTID VARCHAR(36)
AS
SELECT	OMOBJECT.OBJECTNUMBER, HISTORYOBJECTMANAGEMENT.ROWVERSION, HISTORYOBJECTMANAGEMENT.CHANGEDON, HISTORYOBJECTMANAGEMENT.FIELDNAME, 
		HISTORYOBJECTMANAGEMENT.OLDVALUE, HISTORYOBJECTMANAGEMENT.NEWVALUE, HISTORYOBJECTMANAGEMENT.ADDITIONALINFO, USERS.FNAME, USERS.LNAME,
		(SELECT R.[IMAGE] FROM RPTIMAGELIB R
			WHERE R.IMAGENAME = 'Municipality_Logo') LOGO,
		(SELECT CASE WHEN R.[IMAGE] IS NULL THEN 'N' ELSE 'Y' END FROM RPTIMAGELIB R
			WHERE R.IMAGENAME = 'Municipality_Logo') SHOWLOGO,
		(SELECT R.REPORTTEXT FROM RPTTEXTLIB R
			WHERE R.TEXTNAME = 'Municipality_Name') Municipality_Name,	   
		(SELECT R.REPORTTEXT FROM RPTTEXTLIB R
			WHERE R.TEXTNAME = 'Municipality_Page_Footer') Municipality_Page_Footer
	   
FROM	OMOBJECT 
		INNER JOIN HISTORYOBJECTMANAGEMENT ON OMOBJECT.OMOBJECTID = HISTORYOBJECTMANAGEMENT.ID 
		INNER JOIN USERS ON HISTORYOBJECTMANAGEMENT.CHANGEDBY = USERS.SUSERGUID
WHERE	OMOBJECT.OMOBJECTID = @OMOBJECTID

