

CREATE PROCEDURE rpt_OM_SR_Object_Detailed_Report_AttachedObject
@OMOBJECTID AS VARCHAR(36)
AS

SELECT	OMOBJECT.OMOBJECTID, OMOBJECT.OBJECTNUMBER, OMOBJECT.OPERATIONSTARTDATE, OMOBJECT.INSTALLDATE, OMOBJECT.DESCRIPTION, 
		OMOBJECTSTATUS.NAME AS OBJECTSTATUS, OMOBJECTTYPE.NAME AS OBJECTTYPE, OMOBJECTCLASSIFICATION.NAME AS OBJECTCLASSIFICATION
		
FROM	OMOBJECT 
		INNER JOIN OMOBJECTTYPE ON OMOBJECT.OMOBJECTTYPEID = OMOBJECTTYPE.OMOBJECTTYPEID 
		INNER JOIN OMOBJECTSTATUS ON OMOBJECT.OMOBJECTSTATUSID = OMOBJECTSTATUS.OMOBJECTSTATUSID 
		INNER JOIN OMOBJECTCLASSIFICATION ON OMOBJECT.OMOBJECTCLASSIFICATIONID = OMOBJECTCLASSIFICATION.OMOBJECTCLASSIFICATIONID 
WHERE	OMOBJECT.OMOBJECTPARENTID = @OMOBJECTID

