
CREATE PROCEDURE rpt_OM_SR_Object_Listing
	@STARTDATE AS DATETIME,
	@ENDDATE AS DATETIME,
	@FILTER AS VARCHAR(150)
AS

SET @STARTDATE = DATEADD(dd, DATEDIFF(dd, 0, @startdate), 0)
SET @ENDDATE = DATEADD(S,-1,DATEADD(D,1,@ENDDATE))  
;

SELECT OMA.OMOBJECTID, MA.ADDRESSTYPE, RTRIM(MA.ADDRESSLINE1 + ' ' +	LTRIM(MA.PREDIRECTION + ' ') + LTRIM(MA.ADDRESSLINE2 + ' ') + 
	LTRIM(MA.STREETTYPE + ' ') + LTRIM(MA.POSTDIRECTION + ' ') + LTRIM(MA.UNITORSUITE + ' ')  + LTRIM(MA.ADDRESSLINE3)) ADDRESS_LINE1,
	RTRIM(CASE WHEN RTRIM(LTRIM(MA.CITY)) = '' THEN '' ELSE LTRIM(MA.CITY + ', ' ) END + LTRIM(MA.STATE + ' ') + MA.POSTALCODE) ADDRESS_LINE2 
INTO #MADDRESS
FROM OMOBJECTADDRESS OMA
INNER JOIN MAILINGADDRESS MA ON MA.MAILINGADDRESSID = OMA.MAILINGADDRESSID
WHERE OMA.MAIN = 1


SELECT	OM.OMOBJECTID, OM.CREATEDATE, OM.OBJECTNUMBER, OM.INSTALLDATE, OM.OPERATIONSTARTDATE, OM.OPERATIONENDDATE,
		OMT.NAME AS OBJECTTYPE, 
		OMS.NAME AS OBJECTSTATUS,  
		OMC.NAME AS OBJECTCLASS, 
		D.NAME AS DISTRICT,
		MA.ADDRESS_LINE1, MA.ADDRESS_LINE2,
--		(SELECT R.[IMAGE] FROM RPTIMAGELIB R
--			WHERE R.IMAGENAME = 'Municipality_Logo') LOGO,
		(SELECT CASE WHEN R.[IMAGE] IS NULL THEN 'N' ELSE 'Y' END FROM RPTIMAGELIB R
			WHERE R.IMAGENAME = 'Municipality_Logo') SHOWLOGO,
		(SELECT R.REPORTTEXT FROM RPTTEXTLIB R
			WHERE R.TEXTNAME = 'Municipality_Name') Municipality_Name,	   
		(SELECT R.REPORTTEXT FROM RPTTEXTLIB R
			WHERE R.TEXTNAME = 'Municipality_Page_Footer') Municipality_Page_Footer
	
FROM	OMOBJECT OM
		INNER JOIN OMOBJECTTYPE OMT ON OM.OMOBJECTTYPEID = OMT.OMOBJECTTYPEID 
		INNER JOIN OMOBJECTCLASSIFICATION OMC ON OM.OMOBJECTCLASSIFICATIONID = OMC.OMOBJECTCLASSIFICATIONID 
		INNER JOIN OMOBJECTSTATUS OMS ON OM.OMOBJECTSTATUSID = OMS.OMOBJECTSTATUSID 
		LEFT JOIN DISTRICT D ON OM.DISTRICTID = D.DISTRICTID
		LEFT JOIN #MADDRESS MA ON OM.OMOBJECTID = MA.OMOBJECTID
WHERE (CASE @FILTER 
	WHEN 'CREATE DATE' THEN OM.CREATEDATE
	WHEN 'INSTALL DATE' THEN OM.INSTALLDATE
	WHEN 'OPERATION START DATE' THEN OM.OPERATIONSTARTDATE 
	WHEN 'OPERATION END DATE' THEN OM.OPERATIONENDDATE END)
	BETWEEN @STARTDATE AND @ENDDATE


DROP TABLE #MADDRESS

