


/****** OBJECT:  StoredProcedure [dbo].[rpt_OM_Object_Attached_Records_Report_Permit]    Script Date: 02/25/2011 15:58:52 ******/
CREATE PROCEDURE rpt_OM_SR_Object_Attached_Records_Report_Inspection
@OMOBJECTID AS VARCHAR(36)
AS

SELECT	OBJECT_INSPECTIONS.OMOBJECTID, OBJECT_INSPECTIONS.IMINSPECTIONID, OBJECT_INSPECTIONS.INSPECTIONNUMBER, 
		IMINSPECTIONTYPE.NAME INSPECTIONTYPE, 
		IMINSPECTIONSTATUS.STATUSNAME INSPECTIONSTATUS,
		INSPECTORS.FNAME, INSPECTORS.LNAME,	
		INSPECTION_CONTACTS.ISBILLING, INSPECTION_CONTACTS.CONTACTTYPE, 
		INSPECTION_CONTACTS.GLOBALENTITYNAME, INSPECTION_CONTACTS.FIRSTNAME, INSPECTION_CONTACTS.LASTNAME

FROM	(SELECT PMPERMITOBJECT.OMOBJECTID, IMINSPECTION.IMINSPECTIONID, IMINSPECTION.INSPECTIONNUMBER, IMINSPECTION.IMINSPECTIONTYPEID, IMINSPECTION.IMINSPECTIONSTATUSID
		 FROM	PMPERMITOBJECT 
				INNER JOIN IMINSPECTION ON PMPERMITOBJECT.PMPERMITID = IMINSPECTION.LINKID 
		 WHERE	PMPERMITOBJECT.OMOBJECTID = @OMOBJECTID
		 
		 UNION
		 
		 SELECT PLPLANOBJECT.OMOBJECTID, 
				IMINSPECTION.IMINSPECTIONID, IMINSPECTION.INSPECTIONNUMBER, IMINSPECTION.IMINSPECTIONTYPEID, IMINSPECTION.IMINSPECTIONSTATUSID
		 FROM	PLPLANOBJECT 
				INNER JOIN IMINSPECTION ON PLPLANOBJECT.PLPLANID = IMINSPECTION.LINKID 
		 WHERE	PLPLANOBJECT.OMOBJECTID = @OMOBJECTID
		) AS OBJECT_INSPECTIONS 
		
		INNER JOIN IMINSPECTIONTYPE ON OBJECT_INSPECTIONS.IMINSPECTIONTYPEID = IMINSPECTIONTYPE.IMINSPECTIONTYPEID
		INNER JOIN IMINSPECTIONSTATUS ON OBJECT_INSPECTIONS.IMINSPECTIONSTATUSID = IMINSPECTIONSTATUS.IMINSPECTIONSTATUSID
		
		LEFT OUTER JOIN (SELECT IMINSPECTORREF.INSPECTIONID, USERS.FNAME, USERS.LNAME
						 FROM	IMINSPECTORREF 
								INNER JOIN USERS ON IMINSPECTORREF.USERID = USERS.SUSERGUID
						 WHERE	IMINSPECTORREF.BPRIMARY = 1
						) AS INSPECTORS ON INSPECTORS.INSPECTIONID = OBJECT_INSPECTIONS.IMINSPECTIONID
						
		LEFT OUTER JOIN (SELECT IMINSPECTIONCONTACT.IMINSPECTIONID, IMINSPECTIONCONTACT.ISBILLING,
								GLOBALENTITY.GLOBALENTITYNAME, GLOBALENTITY.FIRSTNAME, GLOBALENTITY.LASTNAME,
								LANDMANAGEMENTCONTACTTYPE.NAME CONTACTTYPE
						 FROM	IMINSPECTIONCONTACT 
								INNER JOIN LANDMANAGEMENTCONTACTTYPE ON IMINSPECTIONCONTACT.CONTACTTYPEID = LANDMANAGEMENTCONTACTTYPE.LANDMANAGEMENTCONTACTTYPEID
								INNER JOIN GLOBALENTITY ON IMINSPECTIONCONTACT.GLOBALENTITYID = GLOBALENTITY.GLOBALENTITYID
						) AS INSPECTION_CONTACTS ON OBJECT_INSPECTIONS.IMINSPECTIONID = INSPECTION_CONTACTS.IMINSPECTIONID


