CREATE FUNCTION [managebusiness].[UFN_GET_BLGLOBALENTITYEXTENSION_BALANCE_DUE]
(
    @BLGLOBALENTITYEXTENSIONID CHAR(36)
)
RETURNS MONEY
AS
BEGIN
    DECLARE @BALANCEDUE AS MONEY;
    SELECT @BALANCEDUE = ISNULL(SUM(CACOMPUTEDFEE.COMPUTEDAMOUNT - CACOMPUTEDFEE.AMOUNTPAIDTODATE), 0)
    FROM [dbo].[BLGLOBALENTITYEXTENSION]
        INNER JOIN [dbo].[BLGLOBALENTITYEXTENSIONFEE] 
            ON  [dbo].[BLGLOBALENTITYEXTENSION].[BLGLOBALENTITYEXTENSIONID] = [dbo].[BLGLOBALENTITYEXTENSIONFEE].[BLGLOBALENTITYEXTENSIONID]
        INNER JOIN [dbo].[CACOMPUTEDFEE]  
            ON [dbo].[BLGLOBALENTITYEXTENSIONFEE].[CACOMPUTEDFEEID] = [dbo].[CACOMPUTEDFEE].[CACOMPUTEDFEEID]
	WHERE [dbo].[CACOMPUTEDFEE].[CASTATUSID] NOT IN (10,5) -- DELETED & VOID
         AND [dbo].[BLGLOBALENTITYEXTENSION].[BLGLOBALENTITYEXTENSIONID] = @BLGLOBALENTITYEXTENSIONID
    RETURN @BALANCEDUE;	
END;