CREATE PROCEDURE [livelink].[USP_REQUEST_LOCATION_SELECT_LOOKUP]    
(    
 @REQUESTID VARCHAR(36)    
)    
AS    
BEGIN    
SET NOCOUNT ON; 
SELECT     
  [MAPREQUEST].[LOCATIONOBJECT],  
  [MAPREQUEST].[LOCATIONTYPE]   
  
FROM [dbo].[MAPREQUEST]  
   
WHERE [MAPREQUEST].[REQUESTID] = @REQUESTID    
     
END