CREATE PROCEDURE [livelink].[USP_COUNTRY_LIVELINK_SELECT_LOOKUP]
AS  
BEGIN  
SET NOCOUNT ON;  
SELECT   
 [dbo].[COUNTRY].[COUNTRYID],  
 [dbo].[COUNTRY].[COUNTRYNAME] AS [NAME]  
FROM [dbo].[COUNTRY] WITH (NOLOCK)   
ORDER BY [dbo].[COUNTRY].[COUNTRYNAME]   
END