CREATE TABLE [dbo].[GEOQUERYUNITTYPE] (
    [GEOQUERYUNITTYPEID] CHAR (36)     NOT NULL,
    [QUERYUNITTYPENAME]  NVARCHAR (50) NOT NULL,
    [ESRINUMBER]         INT           NOT NULL,
    CONSTRAINT [PK_GeoQueryUnitType] PRIMARY KEY CLUSTERED ([GEOQUERYUNITTYPEID] ASC) WITH (FILLFACTOR = 90)
);

