CREATE TABLE [dbo].[GEORULEPROCESSTYPE] (
    [GEORULEPROCESSTYPEID]   CHAR (36)     NOT NULL,
    [GEORULEPROCESSTYPENAME] NVARCHAR (50) NOT NULL,
    [SYSTEMTYPE]             INT           NOT NULL,
    CONSTRAINT [PK_PLGeoRuleType] PRIMARY KEY CLUSTERED ([GEORULEPROCESSTYPEID] ASC) WITH (FILLFACTOR = 90)
);

