CREATE TABLE [dbo].[GEORULECOMPARER] (
    [GEORULECOMPARERID] INT           NOT NULL,
    [COMPARERNAME]      NVARCHAR (20) NOT NULL,
    CONSTRAINT [PK_GeoRuleComparer] PRIMARY KEY CLUSTERED ([GEORULECOMPARERID] ASC) WITH (FILLFACTOR = 90)
);

