CREATE TABLE [dbo].[GISLLDATASOURCETYPE] (
    [GISLLDATASOURCETYPEID] CHAR (36)      NOT NULL,
    [NAME]                  VARCHAR (50)   NOT NULL,
    [DESCRIPTION]           NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_GISLLDataSourceType] PRIMARY KEY CLUSTERED ([GISLLDATASOURCETYPEID] ASC) WITH (FILLFACTOR = 90)
);

