CREATE TABLE [dbo].[GISMAILINGENTITY] (
    [GISMAILINGENTITYID] INT           NOT NULL,
    [NAME]               NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_GISMAILINGENTITY] PRIMARY KEY CLUSTERED ([GISMAILINGENTITYID] ASC) WITH (FILLFACTOR = 90)
);

