CREATE TABLE [dbo].[GISMAILINGRECIPIENTLIST] (
    [GISMAILINGRECIPIENTLISTID] CHAR (36)      NOT NULL,
    [NAME]                      NVARCHAR (250) NOT NULL,
    [DESCRIPTION]               NVARCHAR (500) NOT NULL,
    [GISMAILINGENTITYID]        INT            NULL,
    [LINKEDCASE]                CHAR (36)      NULL,
    [LINKNUMBER]                NVARCHAR (50)  NULL,
    [GISMAILINGTEMPLATEID]      CHAR (36)      DEFAULT (NULL) NULL,
    [CREATEDDATE]               DATETIME       DEFAULT (NULL) NULL,
    CONSTRAINT [PK_GISMAILINGRECIPIENTLIST] PRIMARY KEY CLUSTERED ([GISMAILINGRECIPIENTLISTID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_GISMAILINGRECIPIENTLIST_GISMAILINGTEMPLATE] FOREIGN KEY ([GISMAILINGTEMPLATEID]) REFERENCES [dbo].[GISMAILINGTEMPLATE] ([GISMAILINGTEMPLATEID]),
    CONSTRAINT [FK_GISMAILINGRECIPIENTLIST1] FOREIGN KEY ([GISMAILINGENTITYID]) REFERENCES [dbo].[GISMAILINGENTITY] ([GISMAILINGENTITYID])
);

