CREATE TABLE [dbo].[GLOBALACTIVITYTYPE] (
    [GLOBALACTIVITYTYPEID] CHAR (36)      NOT NULL,
    [NAME]                 NVARCHAR (50)  NOT NULL,
    [DESCRIPTION]          NVARCHAR (MAX) NULL,
    [CANEDIT]              BIT            NULL,
    [GENERATEAUTONUMBER]   BIT            NULL,
    [PREFIXID]             NVARCHAR (20)  NULL,
    [ALLOWDUPLICATE]       BIT            NULL,
    [CUSTOMFIELDID]        CHAR (36)      NULL,
    CONSTRAINT [PK_GlobalActivityType] PRIMARY KEY CLUSTERED ([GLOBALACTIVITYTYPEID] ASC) WITH (FILLFACTOR = 90)
);

