CREATE TABLE [dbo].[GLOBALENTITYHOLD] (
    [GLOBALENTITYHOLDID] CHAR (36)      NOT NULL,
    [GLOBALENTITYID]     CHAR (36)      NOT NULL,
    [HOLDSETUPID]        CHAR (36)      NULL,
    [ORIGIN]             CHAR (36)      NULL,
    [ORIGINNUMBER]       NVARCHAR (150) NULL,
    [SUSERGUID]          CHAR (36)      NULL,
    [COMMENTS]           NVARCHAR (MAX) NULL,
    [CREATEDDATE]        DATETIME       NULL,
    [EFFECTIVEENDDATE]   DATETIME       NULL,
    [ACTIVE]             BIT            CONSTRAINT [DF_GlobalEntityHold_Active] DEFAULT ((1)) NOT NULL,
    [HOLDSEVERITYID]     INT            DEFAULT ((1)) NOT NULL,
    [ORIGINCMCODECASEID] CHAR (36)      NULL,
    CONSTRAINT [PK_GlobalEntityHold] PRIMARY KEY CLUSTERED ([GLOBALENTITYHOLDID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_GlobalEntityHold_GlobalEnt] FOREIGN KEY ([GLOBALENTITYID]) REFERENCES [dbo].[GLOBALENTITY] ([GLOBALENTITYID]),
    CONSTRAINT [FK_GlobalEntityHold_Hold] FOREIGN KEY ([HOLDSETUPID]) REFERENCES [dbo].[HOLDTYPESETUPS] ([HOLDSETUPID]),
    CONSTRAINT [FK_GlobalEntityHold_HoldSeverity] FOREIGN KEY ([HOLDSEVERITYID]) REFERENCES [dbo].[HOLDSEVERITY] ([HOLDSEVERITYID]),
    CONSTRAINT [FK_GlobalEntityHold_OriginCodeCase] FOREIGN KEY ([ORIGINCMCODECASEID]) REFERENCES [dbo].[CMCODECASE] ([CMCODECASEID]),
    CONSTRAINT [FK_GlobalEntityHold_User] FOREIGN KEY ([SUSERGUID]) REFERENCES [dbo].[USERS] ([SUSERGUID])
);


GO
CREATE NONCLUSTERED INDEX [IX_GLOBALENTITYHOLDID_ORIGINCMCODECASEID]
    ON [dbo].[GLOBALENTITYHOLD]([ORIGINCMCODECASEID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_GLOBALENTITYHOLD_1]
    ON [dbo].[GLOBALENTITYHOLD]([GLOBALENTITYID] ASC)
    INCLUDE([GLOBALENTITYHOLDID]) WITH (FILLFACTOR = 90);

