CREATE TABLE [dbo].[GLOBALENTITYGLOBALENTITYTYPE] (
    [GLOBALENTITYTYPEID] CHAR (36) NOT NULL,
    [GLOBALENTITYID]     CHAR (36) NOT NULL,
    CONSTRAINT [PK_GlobalEntityGlobalType] PRIMARY KEY CLUSTERED ([GLOBALENTITYTYPEID] ASC, [GLOBALENTITYID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_EntityEntityType_Entity] FOREIGN KEY ([GLOBALENTITYID]) REFERENCES [dbo].[GLOBALENTITY] ([GLOBALENTITYID]),
    CONSTRAINT [FK_EntityEntityType_Type] FOREIGN KEY ([GLOBALENTITYTYPEID]) REFERENCES [dbo].[GLOBALENTITYTYPE] ([GLOBALENTITYTYPEID])
);

