 CREATE FUNCTION [energovhub].[UFN_GET_PROFFER_BALANCE_DUE]
(
     @CASEID CHAR(36)
)
RETURNS MONEY
AS
BEGIN
    DECLARE @BALANCEDUE AS MONEY
    SELECT @BALANCEDUE = ISNULL(SUM(CACOMPUTEDFEE.COMPUTEDAMOUNT - CACOMPUTEDFEE.AMOUNTPAIDTODATE),0)
    FROM [dbo].[IPCONDITIONFEE]
    INNER JOIN [dbo].[CACOMPUTEDFEE] ON  [IPCONDITIONFEE].[CACOMPUTEDFEEID] = [CACOMPUTEDFEE].[CACOMPUTEDFEEID]
    INNER JOIN [dbo].[IPCONDITION]  ON [IPCONDITIONFEE].[IPCONDITIONID] = [IPCONDITION].[IPCONDITIONID]
    WHERE
      [IPCONDITION].[IPCASEID] = @CASEID
    RETURN @BALANCEDUE;
END