CREATE TABLE [dbo].[LANDMANAGEMENTCONTACTSYSTEMTYP] (
    [LANDMANAGEMENTCONTACTSYSTEMTYP] INT           NOT NULL,
    [NAME]                           NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_LandManagementContactSystemType] PRIMARY KEY CLUSTERED ([LANDMANAGEMENTCONTACTSYSTEMTYP] ASC) WITH (FILLFACTOR = 90)
);

