CREATE TABLE [dbo].[LANDUSECASETYPE] (
    [LANDUSECASETYPEID] CHAR (36)     NOT NULL,
    [NAME]              NVARCHAR (50) NULL,
    CONSTRAINT [PK_LANDUSECASETYPE] PRIMARY KEY CLUSTERED ([LANDUSECASETYPEID] ASC) WITH (FILLFACTOR = 90)
);

