CREATE PROCEDURE [security].[USP_CLIENTCREDENTIAL_GETBYCLIENTKEY]
	@CLIENTKEY nvarchar(100)
AS
BEGIN
SET NOCOUNT ON;
	
SELECT 
	[dbo].[CLIENTCREDENTIAL].[CLIENTCREDENTIALID],
	[dbo].[CLIENTCREDENTIAL].[CLIENTID],
	[dbo].[CLIENTCREDENTIAL].[SECRET],
	[dbo].[CLIENTCREDENTIAL].[SCOPE],
	[dbo].[CLIENTCREDENTIAL].[DESCRIPTION],
	[dbo].[CLIENTCREDENTIAL].[CLIENTKEY],
	[dbo].[CLIENTCREDENTIAL].[NAME],
	[dbo].[CLIENTCREDENTIAL].[BASEURL],
	[dbo].[CLIENTCREDENTIAL].[CLIENTIDENTITYURL],
	[dbo].[CLIENTCREDENTIAL].[USERID]
FROM [dbo].[CLIENTCREDENTIAL]
WHERE [dbo].[CLIENTCREDENTIAL].[CLIENTKEY] = @CLIENTKEY

EXEC [security].[USP_CLIENTCREDENTIALSETTINGS_GETBYCLIENTKEY] @CLIENTKEY

END