CREATE PROCEDURE [security].[USP_USERIDENTITYSUBJECTVALUE_SELECT_BY_VALUE]
	@USERIDENTITYSUBJECTVALUEID NVARCHAR(255)
AS

SELECT
	[dbo].[USERIDENTITYSUBJECTVALUE].[USERID],
	[dbo].[USERS].[ID]
FROM [dbo].[USERIDENTITYSUBJECTVALUE]
INNER JOIN [dbo].[USERS] ON [dbo].[USERS].[SUSERGUID] = [dbo].[USERIDENTITYSUBJECTVALUE].[USERID]
WHERE [dbo].[USERIDENTITYSUBJECTVALUE].[USERIDENTITYSUBJECTVALUEID] = @USERIDENTITYSUBJECTVALUEID