CREATE PROCEDURE [globalsearch].[USP_CUSTONFIELDS_SEARCH_SELECT_LOOKUP]
	@SEARCH AS NVARCHAR(MAX) = '',
	@MODULEID AS INT = 1,
	@SUPPORTCUSTOMFIELDNAMESEARCH AS BIT = 0,
	@PAGE_NUMBER AS INT = 1,
	@PAGE_SIZE AS INT = 10,
	@IS_ASCENDING AS BIT = 1
AS
BEGIN

WITH MATCHED_CFs AS
(
	SELECT 
	CUSTOMFIELDID,
	CUSTOMFIELDNAME, 
	CUSTOMFIELDTYPEID, 
	CUSTOMFIELDLABELNAME, 
	LABEL, 
	CUSTOMFIELDDISPLAYNAME, 
	CUSTOMFIELDLAYOUTCONTROLTYPE,
	CUSTOMFIELDTABLENAME, 
	ROW_NUMBER() OVER (PARTITION BY CUSTOMFIELDDISPLAYNAME ORDER BY CUSTOMFIELDDISPLAYNAME) AS GRPROWNUMBER
	FROM (
	--Table columns
		SELECT 
        [dbo].[CUSTOMFIELD].[GCUSTOMFIELD] AS CUSTOMFIELDID,
		[dbo].[CUSTOMFIELD].[SFIELDNAME] AS CUSTOMFIELDNAME,
		[dbo].[CUSTOMFIELD].[FKICUSTOMFIELDTYPE] AS CUSTOMFIELDTYPEID,
		[dbo].[CUSTOMFIELDOBJECT].[SLABEL] AS CUSTOMFIELDLABELNAME,
		([dbo].[CUSTOMFIELDOBJECT].[SLABEL] + ' (' + [dbo].[CUSTOMFIELDLAYOUT].[SNAME] + ')') AS LABEL,
		([dbo].[CUSTOMFIELDOBJECT].[SLABEL] + ' (' + [dbo].[CUSTOMFIELD].[SFIELDNAME] + ', ' + [dbo].[CUSTOMFIELDTYPE].[SNAME] + ')') AS CUSTOMFIELDDISPLAYNAME,
		[dbo].[CUSTOMFIELDCOLUMNTEMPLATE].[FKCUSTOMFIELDLAYOUTCONTROLTYPE] AS CUSTOMFIELDLAYOUTCONTROLTYPE,
		[dbo].[CUSTOMFIELDTABLE].[NAME] AS CUSTOMFIELDTABLENAME
FROM [dbo].[CUSTOMFIELDTABLECOLUMNREF]
JOIN [dbo].[CUSTOMFIELDCOLUMNTEMPLATE] ON 
[dbo].[CUSTOMFIELDTABLECOLUMNREF].[CUSTOMFIELDCOLUMNTEMPLATEID] = [dbo].[CUSTOMFIELDCOLUMNTEMPLATE].[CUSTOMFIELDCOLUMNTEMPLATEID]
JOIN [dbo].[CUSTOMFIELD] ON [dbo].[CUSTOMFIELDCOLUMNTEMPLATE].[GCUSTOMFIELD] = [dbo].[CUSTOMFIELD].[GCUSTOMFIELD]
JOIN [dbo].[CUSTOMFIELDTABLE] ON [dbo].[CUSTOMFIELDTABLECOLUMNREF].[CUSTOMFIELDTABLEID] = [dbo].[CUSTOMFIELDTABLE].[CUSTOMFIELDTABLEID]
JOIN [dbo].[CUSTOMFIELD] AS [CUSTOMFIELD_TABLE] ON [dbo].[CUSTOMFIELDTABLE].[CUSTOMFIELDTABLEID] = [CUSTOMFIELD_TABLE].[FKCUSTOMFIELDTABLE]
JOIN [dbo].[CUSTOMFIELDTYPE] ON [CUSTOMFIELD_TABLE].[FKICUSTOMFIELDTYPE] = [dbo].[CUSTOMFIELDTYPE].[ICUSTOMFIELDTYPE]
JOIN [dbo].[CUSTOMFIELDOBJECT] ON  [CUSTOMFIELD_TABLE].[GCUSTOMFIELD] = [dbo].[CUSTOMFIELDOBJECT].[GCUSTOMFIELD]
JOIN [dbo].[CUSTOMFIELDLAYOUT] ON [dbo].[CUSTOMFIELDOBJECT].[FKGCUSTOMFIELDLAYOUT] = [dbo].[CUSTOMFIELDLAYOUT].[GCUSTOMFIELDLAYOUTS]
JOIN [dbo].[CUSTOMFIELDMODULES] ON [dbo].[CUSTOMFIELDLAYOUT].[CUSTOMFIELDMODULEID] = [dbo].[CUSTOMFIELDMODULES].[CUSTOMFIELDMODULEID]
WHERE [dbo].[CUSTOMFIELDMODULES].[CUSTOMFIELDMODULEID] = @MODULEID AND
		(([dbo].[CUSTOMFIELDOBJECT].[SLABEL] LIKE '%' +  @SEARCH +'%') OR (@SUPPORTCUSTOMFIELDNAMESEARCH = 1 AND [dbo].[CUSTOMFIELD].[SFIELDNAME] LIKE '%' + @SEARCH +'%'))

UNION
 --Table footer
SELECT 
        [dbo].[CUSTOMFIELD].[GCUSTOMFIELD] AS CUSTOMFIELDID,
		[dbo].[CUSTOMFIELD].[SFIELDNAME] AS CUSTOMFIELDNAME,
		[dbo].[CUSTOMFIELD].[FKICUSTOMFIELDTYPE] AS CUSTOMFIELDTYPEID,
		[dbo].[CUSTOMFIELDOBJECT].[SLABEL] AS CUSTOMFIELDLABELNAME,
		([dbo].[CUSTOMFIELDOBJECT].[SLABEL] + ' (' + [dbo].[CUSTOMFIELDLAYOUT].[SNAME] + ')') AS LABEL,
		([dbo].[CUSTOMFIELDOBJECT].[SLABEL] + ' (' + [dbo].[CUSTOMFIELD].[SFIELDNAME] + ', ' + [dbo].[CUSTOMFIELDTYPE].[SNAME] + ')') AS CUSTOMFIELDDISPLAYNAME,
		[dbo].[CUSTOMFIELDCOLUMNTEMPLATE].[FKCUSTOMFIELDLAYOUTCONTROLTYPE] AS CUSTOMFIELDLAYOUTCONTROLTYPE,
		[dbo].[CUSTOMFIELDTABLE].[NAME] AS CUSTOMFIELDTABLENAME

FROM [dbo].[CUSTOMFIELDTABLECOLUMNREF]
JOIN [dbo].[CUSTOMFIELDCOLUMNTEMPLATE] ON 
[dbo].[CUSTOMFIELDTABLECOLUMNREF].[CUSTOMFIELDCOLUMNTEMPLATEID] = [dbo].[CUSTOMFIELDCOLUMNTEMPLATE].[CUSTOMFIELDCOLUMNTEMPLATEID]
JOIN [dbo].[CUSTOMFIELD] ON [dbo].[CUSTOMFIELDTABLECOLUMNREF].[CUSTOMFIELDTABLECOLUMNREFID] = [dbo].[CUSTOMFIELD].[FKCUSTOMFIELDTABLECOLREF]
JOIN [dbo].[CUSTOMFIELDTABLE] ON [dbo].[CUSTOMFIELDTABLECOLUMNREF].[CUSTOMFIELDTABLEID] = [dbo].[CUSTOMFIELDTABLE].[CUSTOMFIELDTABLEID]
JOIN [dbo].[CUSTOMFIELD] AS [CUSTOMFIELD_REF] ON [dbo].[CUSTOMFIELDTABLE].[CUSTOMFIELDTABLEID] = [CUSTOMFIELD_REF].[FKCUSTOMFIELDTABLE]
JOIN [dbo].[CUSTOMFIELDTYPE] ON [CUSTOMFIELD_REF].[FKICUSTOMFIELDTYPE] = [dbo].[CUSTOMFIELDTYPE].[ICUSTOMFIELDTYPE]
JOIN [dbo].[CUSTOMFIELDOBJECT] ON  [CUSTOMFIELD_REF].[GCUSTOMFIELD] = [dbo].[CUSTOMFIELDOBJECT].[GCUSTOMFIELD]
JOIN [dbo].[CUSTOMFIELDLAYOUT] ON [dbo].[CUSTOMFIELDOBJECT].[FKGCUSTOMFIELDLAYOUT] = [dbo].[CUSTOMFIELDLAYOUT].[GCUSTOMFIELDLAYOUTS]
JOIN [dbo].[CUSTOMFIELDMODULES] ON [dbo].[CUSTOMFIELDLAYOUT].[CUSTOMFIELDMODULEID] = [dbo].[CUSTOMFIELDMODULES].[CUSTOMFIELDMODULEID]
WHERE [dbo].[CUSTOMFIELDMODULES].[CUSTOMFIELDMODULEID] = @MODULEID AND
		(([dbo].[CUSTOMFIELDOBJECT].[SLABEL] LIKE '%' +  @SEARCH +'%') OR (@SUPPORTCUSTOMFIELDNAMESEARCH = 1 AND [dbo].[CUSTOMFIELD].[SFIELDNAME] LIKE '%' + @SEARCH +'%'))

UNION
-- Table custom fields
SELECT 
        [dbo].[CUSTOMFIELD].[GCUSTOMFIELD] AS CUSTOMFIELDID,
		[dbo].[CUSTOMFIELD].[SFIELDNAME] AS CUSTOMFIELDNAME,
		[dbo].[CUSTOMFIELD].[FKICUSTOMFIELDTYPE] AS CUSTOMFIELDTYPEID,
		[dbo].[CUSTOMFIELDOBJECT].[SLABEL] AS CUSTOMFIELDLABELNAME,
		([dbo].[CUSTOMFIELDOBJECT].[SLABEL] + ' (' + [dbo].[CUSTOMFIELDLAYOUT].[SNAME] + ')') AS LABEL,
		([dbo].[CUSTOMFIELDOBJECT].[SLABEL] + ' (' + [dbo].[CUSTOMFIELD].[SFIELDNAME] + ', ' + [dbo].[CUSTOMFIELDTYPE].[SNAME] + ')') AS CUSTOMFIELDDISPLAYNAME,
		[dbo].[CUSTOMFIELDOBJECT].[FKCUSTOMFIELDLAYOUTCONTROLTYPE] AS CUSTOMFIELDLAYOUTCONTROLTYPE,
		[dbo].[CUSTOMFIELDTABLE].[NAME] AS CUSTOMFIELDTABLENAME
FROM [dbo].[CUSTOMFIELDTABLE]
JOIN [dbo].[CUSTOMFIELD] ON [dbo].[CUSTOMFIELDTABLE].[CUSTOMFIELDTABLEID] = [dbo].[CUSTOMFIELD].[FKCUSTOMFIELDTABLE]
JOIN [dbo].[CUSTOMFIELDTYPE] ON [dbo].[CUSTOMFIELD] .[FKICUSTOMFIELDTYPE] = [dbo].[CUSTOMFIELDTYPE].[ICUSTOMFIELDTYPE]
JOIN [dbo].[CUSTOMFIELDOBJECT] ON  [dbo].[CUSTOMFIELD] .[GCUSTOMFIELD] = [dbo].[CUSTOMFIELDOBJECT].[GCUSTOMFIELD]
JOIN [dbo].[CUSTOMFIELDLAYOUT] ON [dbo].[CUSTOMFIELDOBJECT].[FKGCUSTOMFIELDLAYOUT] = [dbo].[CUSTOMFIELDLAYOUT].[GCUSTOMFIELDLAYOUTS]
JOIN [dbo].[CUSTOMFIELDMODULES] ON [dbo].[CUSTOMFIELDLAYOUT].[CUSTOMFIELDMODULEID] = [dbo].[CUSTOMFIELDMODULES].[CUSTOMFIELDMODULEID]
WHERE [dbo].[CUSTOMFIELDMODULES].[CUSTOMFIELDMODULEID] = @MODULEID AND
		(([dbo].[CUSTOMFIELDOBJECT].[SLABEL] LIKE '%' +  @SEARCH +'%') OR (@SUPPORTCUSTOMFIELDNAMESEARCH = 1 AND [dbo].[CUSTOMFIELD].[SFIELDNAME] LIKE '%' + @SEARCH +'%'))

UNION
-- Regular custom fields
SELECT 
        [dbo].[CUSTOMFIELD].[GCUSTOMFIELD] AS CUSTOMFIELDID,
		[dbo].[CUSTOMFIELD].[SFIELDNAME] AS CUSTOMFIELDNAME,
		[dbo].[CUSTOMFIELD].[FKICUSTOMFIELDTYPE] AS CUSTOMFIELDTYPEID,
		[dbo].[CUSTOMFIELDOBJECT].[SLABEL] AS CUSTOMFIELDLABELNAME,
		([dbo].[CUSTOMFIELDOBJECT].[SLABEL] + ' (' + [dbo].[CUSTOMFIELDLAYOUT].[SNAME] + ')') AS LABEL,
		([dbo].[CUSTOMFIELDOBJECT].[SLABEL] + ' (' + [dbo].[CUSTOMFIELD].[SFIELDNAME] + ', ' + [dbo].[CUSTOMFIELDTYPE].[SNAME] + ')') AS CUSTOMFIELDDISPLAYNAME,
		[dbo].[CUSTOMFIELDOBJECT].[FKCUSTOMFIELDLAYOUTCONTROLTYPE] AS CUSTOMFIELDLAYOUTCONTROLTYPE,
		NULL AS CUSTOMFIELDTABLENAME
FROM [dbo].[CUSTOMFIELD]
JOIN [dbo].[CUSTOMFIELDTYPE] ON [dbo].[CUSTOMFIELD] .[FKICUSTOMFIELDTYPE] = [dbo].[CUSTOMFIELDTYPE].[ICUSTOMFIELDTYPE]
JOIN [dbo].[CUSTOMFIELDOBJECT] ON  [dbo].[CUSTOMFIELD] .[GCUSTOMFIELD] = [dbo].[CUSTOMFIELDOBJECT].[GCUSTOMFIELD]
JOIN [dbo].[CUSTOMFIELDLAYOUTCONTROLTYPE] ON [dbo].[CUSTOMFIELDOBJECT].[FKCUSTOMFIELDLAYOUTCONTROLTYPE] = [dbo].[CUSTOMFIELDLAYOUTCONTROLTYPE].[ICUSTOMFIELDLAYOUTCONTROLTYPE]
JOIN [dbo].[CUSTOMFIELDLAYOUT] ON [dbo].[CUSTOMFIELDOBJECT].[FKGCUSTOMFIELDLAYOUT] = [dbo].[CUSTOMFIELDLAYOUT].[GCUSTOMFIELDLAYOUTS]
JOIN [dbo].[CUSTOMFIELDMODULES] ON [dbo].[CUSTOMFIELDLAYOUT].[CUSTOMFIELDMODULEID] = [dbo].[CUSTOMFIELDMODULES].[CUSTOMFIELDMODULEID]
WHERE [dbo].[CUSTOMFIELDMODULES].[CUSTOMFIELDMODULEID] = @MODULEID AND
		(([dbo].[CUSTOMFIELDOBJECT].[SLABEL] LIKE '%' +  @SEARCH +'%') OR (@SUPPORTCUSTOMFIELDNAMESEARCH = 1 AND [dbo].[CUSTOMFIELD].[SFIELDNAME] LIKE '%' + @SEARCH +'%'))
AND
([dbo].[CUSTOMFIELDOBJECT].[BFOOTER] = 0 OR [dbo].[CUSTOMFIELDOBJECT].[BFOOTER] IS NULL)
AND [dbo].[CUSTOMFIELDLAYOUTCONTROLTYPE].[BHASDATA] = 1
AND [dbo].[CUSTOMFIELDLAYOUTCONTROLTYPE].[ICUSTOMFIELDLAYOUTCONTROLTYPE] NOT IN (8,9,10)

	 ) AS allCfs
),
NODUPLICATE_CFs AS
(
	SELECT 
	CUSTOMFIELDID,
	CUSTOMFIELDNAME, 
	CUSTOMFIELDTYPEID, 
	CUSTOMFIELDLABELNAME, 
	LABEL, 
	CUSTOMFIELDDISPLAYNAME, 
	CUSTOMFIELDLAYOUTCONTROLTYPE, 
	CUSTOMFIELDTABLENAME,
	ROW_NUMBER() OVER (ORDER BY CUSTOMFIELDLABELNAME) AS ROWNUMBER,
	COUNT(1) OVER() AS TotalRows
	FROM MATCHED_CFs WHERE GRPROWNUMBER = 1
)

SELECT * 
FROM NODUPLICATE_CFs
WHERE
	RowNumber > @PAGE_SIZE * (@PAGE_NUMBER - 1) AND 
	RowNumber <= @PAGE_SIZE * @PAGE_NUMBER
ORDER BY 
	RowNumber
END