CREATE PROCEDURE [globalsearch].[USP_RESOURCETYPE_SEARCH_SELECT_LOOKUP]
(
	@SEARCH AS NVARCHAR(MAX) = '',
	@PAGE_NUMBER AS INT = 1,
	@PAGE_SIZE AS INT = 10,
	@IS_ASCENDING AS BIT = 1,	
	@RESOURCETYPEID NVARCHAR(36)=''
)
AS
BEGIN
SET NOCOUNT ON;
;WITH RAW_DATA AS(
			SELECT 
				[RESOURCETYPE].[RESOURCETYPEID],
				[RESOURCETYPE].[NAME],
				CASE @IS_ASCENDING WHEN 1 THEN
					ROW_NUMBER() OVER(ORDER BY [dbo].[RESOURCETYPE].[NAME])
				ELSE
					ROW_NUMBER() OVER(ORDER BY [dbo].[RESOURCETYPE].[NAME] DESC)
				END AS ROWNUMBER,
				COUNT(1) OVER() AS TOTALROWS		
			FROM [dbo].[RESOURCETYPE]  WITH (NOLOCK)
			WHERE 
			((@RESOURCETYPEID IS NOT NULL OR @RESOURCETYPEID!='') AND [RESOURCETYPE].[RESOURCETYPEID] = @RESOURCETYPEID) 
			OR
			( (@RESOURCETYPEID IS NULL OR @RESOURCETYPEID='')AND [RESOURCETYPE].[NAME] LIKE '%'+@SEARCH+'%'))
SELECT 
	[RAW_DATA].[RESOURCETYPEID],
	[RAW_DATA].[NAME],
	[RAW_DATA].[TOTALROWS]
FROM RAW_DATA
WHERE
	RowNumber > @PAGE_SIZE * (@PAGE_NUMBER - 1) AND 
	RowNumber <= @PAGE_SIZE * @PAGE_NUMBER
ORDER BY 
	RowNumber
END