CREATE PROCEDURE [globalsearch].[USP_PROFESSIONAL_LICENSE_CLASS_TYPE_SEARCH_SELECT_LOOKUP]
(
  @SEARCH AS NVARCHAR(MAX) = '',
  @LICENSE_TYPE_ID CHAR(36) = '',
  @PAGE_NUMBER AS INT = 1,
  @PAGE_SIZE AS INT = 10,
  @IS_ASCENDING AS BIT = 1,
  @LICENSE_CLASS_TYPE_SORT_BY VARCHAR(50) = ''
)
AS
BEGIN
SET NOCOUNT ON;
WITH RAW_DATA AS(

SELECT [ILLICENSECLASSTYPEID], [NAME], [DESCRIPTION], [CATEGORY_NAME],

CASE WHEN @IS_ASCENDING = 1 THEN
            (CASE WHEN @LICENSE_CLASS_TYPE_SORT_BY = 'NAME' THEN  ROW_NUMBER() OVER(ORDER BY [TEMP].[NAME])
                  WHEN  @LICENSE_CLASS_TYPE_SORT_BY = 'DESCRIPTION' THEN ROW_NUMBER() OVER(ORDER BY [TEMP].[DESCRIPTION])
									WHEN  @LICENSE_CLASS_TYPE_SORT_BY = 'CATEGORY_NAME' THEN ROW_NUMBER() OVER(ORDER BY [TEMP].[NAME])
                  ELSE  ROW_NUMBER() OVER(ORDER BY [TEMP].[NAME]) END)
         ELSE
            (CASE WHEN @LICENSE_CLASS_TYPE_SORT_BY = 'NAME' THEN  ROW_NUMBER() OVER(ORDER BY [TEMP].[NAME] DESC)
                  WHEN  @LICENSE_CLASS_TYPE_SORT_BY = 'DESCRIPTION' THEN ROW_NUMBER() OVER(ORDER BY [TEMP].[DESCRIPTION] DESC)
									WHEN  @LICENSE_CLASS_TYPE_SORT_BY = 'CATEGORY_NAME' THEN ROW_NUMBER() OVER(ORDER BY [TEMP].[NAME] DESC)
                  ELSE  ROW_NUMBER() OVER(ORDER BY [TEMP].[NAME] DESC) END)    
       END AS RowNumber,
   COUNT(1) OVER() AS TotalRows
 
FROM
(SELECT DISTINCT
	 [ILLICENSECLASSTYPE].[ILLICENSECLASSTYPEID],
   [ILLICENSECLASSTYPE].[NAME],
   [ILLICENSECLASSTYPE].[DESCRIPTION],
	 [ILLICENSECLASSTYPECATEGORY].[NAME] AS CATEGORY_NAME
FROM [ILLICENSECLASSTYPE] WITH (NOLOCK)
INNER JOIN [ILLICENSECLASSTYPECATEGORY] WITH (NOLOCK) ON [ILLICENSECLASSTYPECATEGORY].[ILLICENSECLASSTYPECATEGORYID] = [ILLICENSECLASSTYPE].[ILLICENSECLASSTYPECATEGORYID]
INNER JOIN [ILLICENSETYPECLASSTYPE] WITH (NOLOCK) ON [ILLICENSECLASSTYPE].[ILLICENSECLASSTYPEID] = [ILLICENSETYPECLASSTYPE].[ILLICENSECLASSTYPEID]
LEFT JOIN [ILLICENSETYPE] WITH (NOLOCK) ON [ILLICENSETYPE].[ILLICENSETYPEID] = [ILLICENSETYPECLASSTYPE].[ILLICENSETYPEID]
WHERE (([ILLICENSETYPE].[ILLICENSETYPEID] = @LICENSE_TYPE_ID) OR (@LICENSE_TYPE_ID = ''))
   AND ([ILLICENSECLASSTYPE].[DESCRIPTION] like '%' + @SEARCH + '%'
   OR [ILLICENSECLASSTYPE].[NAME] like '%' + @SEARCH + '%'
   OR [ILLICENSECLASSTYPECATEGORY].[NAME]  like '%' + @SEARCH + '%')
) AS TEMP)

SELECT *
FROM RAW_DATA
WHERE
  RowNumber > @PAGE_SIZE * (@PAGE_NUMBER - 1) AND
  RowNumber <= @PAGE_SIZE * @PAGE_NUMBER
ORDER BY
  RowNumber
END