CREATE PROCEDURE [globalsearch].[USP_DEPARTMENT_GETBYDEPTIDS_GETBYUSERIDS]
(
	@USERIDS RECORDIDS  READONLY,	
	@DEPARTMENTIDS RECORDIDS  READONLY -- DEPARTMENTID
)
AS
BEGIN
SET NOCOUNT ON;
	SELECT  
		[USERDEPARTMENT].[SUSERGUID],
		[DEPARTMENT].[DEPARTMENTID],
		[DEPARTMENT].[NAME]
	FROM 
		[dbo].[USERDEPARTMENT] WITH (NOLOCK)
		INNER JOIN [dbo].[DEPARTMENT] WITH (NOLOCK) 
			ON [USERDEPARTMENT].[DEPARTMENTID] = [DEPARTMENT].[DEPARTMENTID]
		INNER JOIN [dbo].[USERS] WITH (NOLOCK) 
			ON [USERS].[SUSERGUID] = [USERDEPARTMENT].[SUSERGUID]
	WHERE (NOT EXISTS(SELECT RECORDID FROM @USERIDS) OR [USERS].[SUSERGUID] IN (SELECT [RECORDID] FROM @USERIDS ))	
	AND  (NOT EXISTS(SELECT RECORDID FROM @DEPARTMENTIDS) OR [DEPARTMENT].[DEPARTMENTID] IN (SELECT [RECORDID] FROM @DEPARTMENTIDS ))
	ORDER BY ([USERS].[LNAME]+' ' +[USERS].[FNAME]), [DEPARTMENT].[NAME]

END