CREATE PROCEDURE [globalsearch].[USP_CONDITIONLIBRARY_SEARCH_SELECT_LOOKUP]
(
	@SEARCH AS NVARCHAR(MAX) = '',
	@PAGE_NUMBER AS INT = 1,
	@PAGE_SIZE AS INT = 10,
	@IS_ASCENDING AS BIT = 1,	
	@CONDITIONCATEGORYIDS RecordIDs READONLY 
)
AS
BEGIN
SET NOCOUNT ON;
;WITH RAW_DATA AS(
		SELECT  [CONDITIONLIBRARY].[CONDITIONLIBRARYID],
				[CONDITIONLIBRARY].[NAME],
				[CONDITIONLIBRARY].[DESCRIPTION],
				[CONDITIONLIBRARY].[CONDITIONCATEGORYID],
				[CONDITIONCATEGORY].[NAME] AS [CATEGORYNAME],
				CASE @IS_ASCENDING WHEN 1 THEN
					ROW_NUMBER() OVER(ORDER BY [dbo].[CONDITIONLIBRARY].[NAME])
				ELSE
					ROW_NUMBER() OVER(ORDER BY [dbo].[CONDITIONLIBRARY].[NAME] DESC)
				END AS RowNumber,
				COUNT(1) OVER() AS TotalRows
		FROM [dbo].[CONDITIONLIBRARY] WITH (NOLOCK) INNER JOIN [dbo].[CONDITIONCATEGORY] WITH (NOLOCK)
				ON [CONDITIONLIBRARY].[CONDITIONCATEGORYID]=[CONDITIONCATEGORY].[CONDITIONCATEGORYID]
		 WHERE (
				[CONDITIONLIBRARY].[DESCRIPTION] LIKE '%'+@SEARCH+'%' OR
				[CONDITIONLIBRARY].[NAME] LIKE '%'+@SEARCH+'%' OR
				[CONDITIONCATEGORY].[NAME] LIKE '%'+@SEARCH+'%' 
				) AND ((SELECT CASE 
								WHEN (SELECT COUNT([RECORDID]) FROM  @CONDITIONCATEGORYIDS)=0  THEN 1
								WHEN (SELECT COUNT([RECORDID]) FROM  @CONDITIONCATEGORYIDS
																WHERE [RECORDID]=[CONDITIONLIBRARY].[CONDITIONCATEGORYID]) <> 0 THEN 1 
								ELSE 0 END)=1)
)
SELECT * 
FROM RAW_DATA
WHERE
	RowNumber > @PAGE_SIZE * (@PAGE_NUMBER - 1) AND 
	RowNumber <= @PAGE_SIZE * @PAGE_NUMBER
ORDER BY 
	RowNumber
END