CREATE PROCEDURE [globalsearch].[USP_USERS_GETBYID_LOOKUP]
(
	@SUSERGUID CHAR(36)
)
AS
BEGIN
SET NOCOUNT ON;

SELECT	[USERS].[SUSERGUID],
		[USERS].[FNAME]+' '+[USERS].[LNAME]
FROM [dbo].[USERS] WITH (NOLOCK)
WHERE
	 [USERS].[SUSERGUID]=@SUSERGUID

END