CREATE PROCEDURE [globalsearch].[USP_CAPITAL_PROJECT_SEARCH_SELECT_LOOKUP]
(
  @SEARCH AS NVARCHAR(MAX) = '',
  @PAGE_NUMBER AS INT = 1,
  @PAGE_SIZE AS INT = 10,
  @IS_ASCENDING AS BIT = 1
)
AS
BEGIN
SET NOCOUNT ON;
WITH RAW_DATA AS(
SELECT
   [IPCAPITALPROJECT].[IPCAPITALPROJECTID],
   [IPCAPITALPROJECT].[NAME],
   CASE @IS_ASCENDING WHEN 1 THEN
       ROW_NUMBER() OVER(ORDER BY [IPCAPITALPROJECT].[NAME])
   ELSE
       ROW_NUMBER() OVER(ORDER BY [IPCAPITALPROJECT].[NAME] DESC)
   END AS RowNumber,
   COUNT(1) OVER() AS TotalRows
FROM [IPCAPITALPROJECT] WITH (NOLOCK)
WHERE [IPCAPITALPROJECT].[NAME]  like '%' + @SEARCH + '%'
)
SELECT *
FROM RAW_DATA
WHERE
  RowNumber > @PAGE_SIZE * (@PAGE_NUMBER - 1) AND
  RowNumber <= @PAGE_SIZE * @PAGE_NUMBER
ORDER BY
  RowNumber
END