CREATE PROCEDURE [energovhub].[USP_ENERGOVHUB_RECENT_CASES]
	@USERID CHAR(36)
AS
BEGIN

	SET NOCOUNT ON;
	DECLARE @USERNAME VARCHAR(300)
	SELECT @USERNAME = (ISNULL([dbo].[USERS].[FNAME], '') + ' ' + ISNULL([dbo].[USERS].LNAME, '')) FROM [dbo].[USERS] WHERE [dbo].[USERS].SUSERGUID = @USERID

	SELECT TOP 50 RECORDID, CASENUMBER, ACTIVETIME,@USERNAME AS USERNAME, MODULENAME,RECENTFORM  FROM (
		SELECT TOP 50 [dbo].[RECENTHISTORYPERMIT].PERMITID AS RECORDID, [dbo].[RECENTHISTORYPERMIT].PERMITNUMBER AS CASENUMBER, [dbo].[RECENTHISTORYPERMIT].LOGGEDDATETIME AS ACTIVETIME, 'Permit' AS MODULENAME  , 1 As RECENTFORM  FROM [dbo].[RECENTHISTORYPERMIT] 
						WHERE [dbo].[RECENTHISTORYPERMIT].USERID = @USERID ORDER BY [dbo].[RECENTHISTORYPERMIT].LOGGEDDATETIME DESC
		UNION ALL
		SELECT TOP 50 [dbo].[RECENTHISTORYPLAN].PLANID AS RECORDID, [dbo].[RECENTHISTORYPLAN].PLANNUMBER AS CASENUMBER, [dbo].[RECENTHISTORYPLAN].LOGGEDDATETIME AS ACTIVETIME, 'Plan' AS MODULENAME ,2 As RECENTFORM FROM [dbo].[RECENTHISTORYPLAN] 
						WHERE [dbo].[RECENTHISTORYPLAN].USERID = @USERID ORDER BY [dbo].[RECENTHISTORYPLAN].LOGGEDDATETIME DESC
		UNION ALL
		SELECT TOP 50 [dbo].[RECENTHISTORYCODECASE].CODECASEID AS RECORDID, [dbo].[RECENTHISTORYCODECASE].CASENUMBER AS CASENUMBER, [dbo].[RECENTHISTORYCODECASE].LOGGEDDATETIME AS ACTIVETIME, 'Code Case' AS MODULENAME, 3 As RECENTFORM FROM [dbo].[RECENTHISTORYCODECASE] 
						WHERE [dbo].[RECENTHISTORYCODECASE].USERID = @USERID ORDER BY [dbo].[RECENTHISTORYCODECASE].LOGGEDDATETIME DESC
		UNION ALL
		SELECT TOP 50 [dbo].[RECENTHISTORYIMPACTCASE].IMPACTCASEID AS RECORDID, [dbo].[RECENTHISTORYIMPACTCASE].CASENUMBER AS CASENUMBER, [dbo].[RECENTHISTORYIMPACTCASE].LOGGEDDATETIME AS ACTIVETIME, 'Impact Case' AS MODULENAME , 4 As RECENTFORM FROM [dbo].[RECENTHISTORYIMPACTCASE] 
						WHERE [dbo].[RECENTHISTORYIMPACTCASE].USERID = @USERID ORDER BY [dbo].[RECENTHISTORYIMPACTCASE].LOGGEDDATETIME DESC
		UNION ALL
		SELECT TOP 50 [dbo].[RECENTHISTORYINSPECTIONCASE].INSPECTIONCASEID AS RECORDID, [dbo].[RECENTHISTORYINSPECTIONCASE].CASENUMBER AS CASENUMBER, [dbo].[RECENTHISTORYINSPECTIONCASE].LOGGEDDATETIME AS ACTIVETIME, 'Inspection Case' AS MODULENAME,5 As RECENTFORM  FROM [dbo].[RECENTHISTORYINSPECTIONCASE] 
						WHERE [dbo].[RECENTHISTORYINSPECTIONCASE].USERID = @USERID ORDER BY [dbo].[RECENTHISTORYINSPECTIONCASE].LOGGEDDATETIME DESC
		UNION ALL
		SELECT TOP 50 [dbo].[RECENTHISTORYINSPECTION].INSPECTIONID AS RECORDID, [dbo].[RECENTHISTORYINSPECTION].INSPECTIONNUMBER AS CASENUMBER, [dbo].[RECENTHISTORYINSPECTION].LOGGEDDATETIME AS ACTIVETIME, 'Inspection' AS MODULENAME,6 As RECENTFORM  FROM [dbo].[RECENTHISTORYINSPECTION] 
						WHERE [dbo].[RECENTHISTORYINSPECTION].USERID = @USERID ORDER BY [dbo].[RECENTHISTORYINSPECTION].LOGGEDDATETIME DESC
		UNION ALL 
		SELECT TOP 50 [dbo].[RECENTHISTORYBUSINESS].BLGLOBALENTITYEXTENSIONID AS RECORDID, [dbo].[RECENTHISTORYBUSINESS].COMPANYNAME AS CASENUMBER, [dbo].[RECENTHISTORYBUSINESS].LOGGEDDATETIME AS ACTIVETIME, 
				CASE WHEN [dbo].[BLEXTCOMPANYTYPE].BLEXTCOMPANYTYPEMODULEID = 1 THEN 'Business' ELSE 'Landlord' END AS MODULENAME,
				CASE WHEN [dbo].[BLEXTCOMPANYTYPE].BLEXTCOMPANYTYPEMODULEID = 1 THEN 7 ELSE 21 END As RECENTFORM 
				FROM [dbo].[RECENTHISTORYBUSINESS] INNER JOIN [dbo].[BLGLOBALENTITYEXTENSION] 
					ON [dbo].[RECENTHISTORYBUSINESS].[BLGLOBALENTITYEXTENSIONID] = [dbo].[BLGLOBALENTITYEXTENSION].[BLGLOBALENTITYEXTENSIONID]
				INNER JOIN [dbo].[BLEXTCOMPANYTYPE] 
					ON [dbo].[BLGLOBALENTITYEXTENSION].[BLEXTCOMPANYTYPEID] = [dbo].[BLEXTCOMPANYTYPE].[BLEXTCOMPANYTYPEID]	
						WHERE [dbo].[RECENTHISTORYBUSINESS].USERID = @USERID ORDER BY [dbo].[RECENTHISTORYBUSINESS].LOGGEDDATETIME DESC
		UNION ALL
		SELECT TOP 50 [dbo].[RECENTHISTORYBUSINESSLICENSE].LICENSEID AS RECORDID, [dbo].[RECENTHISTORYBUSINESSLICENSE].LICENSENUMBER AS CASENUMBER, [dbo].[RECENTHISTORYBUSINESSLICENSE].LOGGEDDATETIME AS ACTIVETIME, 	
				CASE WHEN [dbo].[BLLICENSETYPE].[BLLICENSETYPEMODULEID] = 1 THEN 'Business License' ELSE 'Rental Property' END AS MODULENAME,
				CASE WHEN [dbo].[BLLICENSETYPE].[BLLICENSETYPEMODULEID] = 1 THEN 8 ELSE 22 END As RECENTFORM 
				FROM [dbo].[RECENTHISTORYBUSINESSLICENSE] INNER JOIN [dbo].[BLLICENSE] 
						ON [dbo].[RECENTHISTORYBUSINESSLICENSE].[LICENSEID] = [dbo].[BLLICENSE].[BLLICENSEID]
					INNER JOIN [dbo].[BLLICENSETYPE] 
						ON [dbo].[BLLICENSE].[BLLICENSETYPEID] = [dbo].[BLLICENSETYPE].[BLLICENSETYPEID]	
						WHERE [dbo].[RECENTHISTORYBUSINESSLICENSE].USERID = @USERID ORDER BY [dbo].[RECENTHISTORYBUSINESSLICENSE].LOGGEDDATETIME DESC
		UNION ALL
		SELECT TOP 50 [dbo].[RECENTHISTORYGLOBALENTITY].GLOBALENTITYID AS RECORDID, [dbo].[RECENTHISTORYGLOBALENTITY].CONTACTNAME AS CASENUMBER, [dbo].[RECENTHISTORYGLOBALENTITY].LOGGEDDATETIME AS ACTIVETIME, 'Contact' AS MODULENAME,9 As RECENTFORM FROM [dbo].[RECENTHISTORYGLOBALENTITY] 
						WHERE [dbo].[RECENTHISTORYGLOBALENTITY].USERID = @USERID ORDER BY [dbo].[RECENTHISTORYGLOBALENTITY].LOGGEDDATETIME DESC
		UNION ALL
		SELECT TOP 50 [dbo].[RECENTHISTORYPROFESSIONALLICENSE].ILLICENSEID AS RECORDID, [dbo].[RECENTHISTORYPROFESSIONALLICENSE].ACCOUNTNUMBER AS CASENUMBER, [dbo].[RECENTHISTORYPROFESSIONALLICENSE].LOGGEDDATETIME AS ACTIVETIME, 'Professional License' AS MODULENAME,10 As RECENTFORM FROM [dbo].[RECENTHISTORYPROFESSIONALLICENSE] 
						WHERE [dbo].[RECENTHISTORYPROFESSIONALLICENSE].USERID = @USERID ORDER BY [dbo].[RECENTHISTORYPROFESSIONALLICENSE].LOGGEDDATETIME DESC
		UNION ALL
		SELECT TOP 50 [dbo].[RECENTHISTORYPROJECT].PROJECTID AS RECORDID, [dbo].[RECENTHISTORYPROJECT].PROJECTNUMBER AS CASENUMBER, [dbo].[RECENTHISTORYPROJECT].LOGGEDDATETIME AS ACTIVETIME, 'Project' AS MODULENAME,11 As RECENTFORM FROM [dbo].[RECENTHISTORYPROJECT] 
						WHERE [dbo].[RECENTHISTORYPROJECT].USERID = @USERID ORDER BY [dbo].[RECENTHISTORYPROJECT].LOGGEDDATETIME DESC
		UNION ALL
		SELECT TOP 50 [dbo].[RECENTHISTORYTAXREMIITANCEACCOUNT].TXREMITTANCEACCOUNTID AS RECORDID, [dbo].[RECENTHISTORYTAXREMIITANCEACCOUNT].ACCOUNTNUMBER AS CASENUMBER, [dbo].[RECENTHISTORYTAXREMIITANCEACCOUNT].LOGGEDDATETIME AS ACTIVETIME, 'Tax Remittance Account' AS MODULENAME,12 As RECENTFORM FROM [dbo].[RECENTHISTORYTAXREMIITANCEACCOUNT] 
						WHERE [dbo].[RECENTHISTORYTAXREMIITANCEACCOUNT].USERID = @USERID ORDER BY [dbo].[RECENTHISTORYTAXREMIITANCEACCOUNT].LOGGEDDATETIME DESC
		UNION ALL
		SELECT TOP 50 [dbo].[RECENTHISTORYAPPLICATION].PLAPPLICATIONID AS RECORDID, [dbo].[RECENTHISTORYAPPLICATION].APPNUMBER AS CASENUMBER, [dbo].[RECENTHISTORYAPPLICATION].LOGGEDDATETIME AS ACTIVETIME, 'Application' AS MODULENAME,13 As RECENTFORM FROM [dbo].[RECENTHISTORYAPPLICATION] 
						WHERE [dbo].[RECENTHISTORYAPPLICATION].USERID = @USERID ORDER BY [dbo].[RECENTHISTORYAPPLICATION].LOGGEDDATETIME DESC
		UNION ALL
		SELECT TOP 50 [dbo].[RECENTHISTORYEXAMREQUEST].EXAMREQUESTID AS RECORDID, [dbo].[RECENTHISTORYEXAMREQUEST].REQUESTNUMBER AS CASENUMBER, [dbo].[RECENTHISTORYEXAMREQUEST].LOGGEDDATETIME AS ACTIVETIME, 'Exam Request' AS MODULENAME,14 As RECENTFORM FROM [dbo].[RECENTHISTORYEXAMREQUEST] 
						WHERE [dbo].[RECENTHISTORYEXAMREQUEST].USERID = @USERID ORDER BY [dbo].[RECENTHISTORYEXAMREQUEST].LOGGEDDATETIME DESC
		UNION ALL
		SELECT TOP 50 [dbo].[RECENTHISTORYPERMITRENEWALCASE].PERMITRENEWALCASEID AS RECORDID, [dbo].[RECENTHISTORYPERMITRENEWALCASE].PERMITRENEWALCASENUMBER AS CASENUMBER, [dbo].[RECENTHISTORYPERMITRENEWALCASE].LOGGEDDATETIME AS ACTIVETIME, 'Permit Renewal Case' AS MODULENAME,15 As RECENTFORM FROM [dbo].[RECENTHISTORYPERMITRENEWALCASE] 
						WHERE [dbo].[RECENTHISTORYPERMITRENEWALCASE].USERID = @USERID ORDER BY [dbo].[RECENTHISTORYPERMITRENEWALCASE].LOGGEDDATETIME DESC
		UNION ALL
		SELECT TOP 50 [dbo].[RECENTHISTORYEXAMSITTING].EXAMSITTINGID AS RECORDID, [dbo].[RECENTHISTORYEXAMSITTING].SITTINGNUMBER AS CASENUMBER, [dbo].[RECENTHISTORYEXAMSITTING].LOGGEDDATETIME AS ACTIVETIME, 'Exam Sitting' AS MODULENAME,16 As RECENTFORM FROM [dbo].[RECENTHISTORYEXAMSITTING] 
						WHERE [dbo].[RECENTHISTORYEXAMSITTING].USERID = @USERID ORDER BY [dbo].[RECENTHISTORYEXAMSITTING].LOGGEDDATETIME DESC
		UNION ALL
		SELECT TOP 50 [dbo].[RECENTHISTORYOBJECTCASE].OBJECTCASEID AS RECORDID, [dbo].[RECENTHISTORYOBJECTCASE].OBJECTNUMBER AS CASENUMBER, [dbo].[RECENTHISTORYOBJECTCASE].LOGGEDDATETIME AS ACTIVETIME, 'Object' AS MODULENAME,17 As RECENTFORM FROM [dbo].[RECENTHISTORYOBJECTCASE] 
						WHERE [dbo].[RECENTHISTORYOBJECTCASE].USERID = @USERID ORDER BY [dbo].[RECENTHISTORYOBJECTCASE].LOGGEDDATETIME DESC
		UNION ALL 
		SELECT TOP 10
		[dbo].[RECENTCASE].RECORDID,[dbo].[RECENTCASE].CASENUMBER,[dbo].[RECENTCASE].ACTIVETIME,
		CASE 
			WHEN [dbo].[RECENTCASE].SFORMSGUID = '5663C05A-B176-4DC3-B8F2-E5714C7F3260' THEN 'Payment'
			WHEN [dbo].[RECENTCASE].SFORMSGUID = '7CE86904-7BEA-4E42-A5A4-A19C441247DF' THEN 'Invoice'
			WHEN [dbo].[RECENTCASE].SFORMSGUID = 'EE77BB37-BD67-4CD4-9D32-BEAA25E8EA9C' THEN 'Parcel'
		END  AS MODULENAME,
		CASE 
			WHEN [dbo].[RECENTCASE].SFORMSGUID = '5663C05A-B176-4DC3-B8F2-E5714C7F3260' THEN 18
			WHEN [dbo].[RECENTCASE].SFORMSGUID = '7CE86904-7BEA-4E42-A5A4-A19C441247DF' THEN 19
			WHEN [dbo].[RECENTCASE].SFORMSGUID = 'EE77BB37-BD67-4CD4-9D32-BEAA25E8EA9C' THEN 20
		END AS RECENTFORM
		FROM [dbo].[RECENTCASE]
		WHERE [dbo].[RECENTCASE].USERID = @USERID   AND [dbo].[RECENTCASE].SFORMSGUID in (
		'5663C05A-B176-4DC3-B8F2-E5714C7F3260', -- Payment 
		'7CE86904-7BEA-4E42-A5A4-A19C441247DF', -- Invoice
		'EE77BB37-BD67-4CD4-9D32-BEAA25E8EA9C'  -- Parcel Manager
		) 
		
	) RECENTS ORDER BY ACTIVETIME DESC

END