CREATE PROCEDURE [energovhub].[USP_COMPLETEDINSPECTIONS_GETALL]    
AS  
BEGIN    
SET NOCOUNT ON;

 SELECT   
        [ZONE].[NAME],
        [PLPLAN].[COMPLETED] AS COMPLETED
		FROM [dbo].[PLPLANZONE]
        INNER JOIN [dbo].[ZONE]  ON  [PLPLANZONE].[ZONEID] = [ZONE].[ZONEID]
        INNER JOIN [dbo].[PLPLAN] ON [PLPLANZONE].[PLPLANID] = [PLPLAN].[PLPLANID]

  UNION ALL

  SELECT
        [ZONE].[NAME] AS [NAME],
        [PMPERMITSTATUS].[COMPLETEDFLAG] AS COMPLETED
        FROM    [dbo].[PMPERMITZONE]
        INNER JOIN [dbo].[ZONE]  ON [PMPERMITZONE].[ZONEID] = [ZONE].[ZONEID]
        INNER JOIN [dbo].[PMPERMIT] ON [PMPERMITZONE].[PMPERMITID] = [PMPERMIT].[PMPERMITID]
        INNER JOIN [dbo].[PMPERMITSTATUS] ON [PMPERMIT].[PMPERMITSTATUSID] = [PMPERMITSTATUS].[PMPERMITSTATUSID]
END