CREATE PROCEDURE [inspection].[USP_IMINSPECTIONCASE_RECENT]
(
	 @USER_ID AS CHAR(36)
)
AS
BEGIN

	DECLARE @RECENTINSPECTIONCASELIST AS RecordIDs
	
	-- Get recent Inspection Case Ids
	INSERT INTO @RECENTINSPECTIONCASELIST (RECORDID)
	SELECT TOP 15 [dbo].[RECENTHISTORYINSPECTIONCASE].[INSPECTIONCASEID] 
		FROM [dbo].[RECENTHISTORYINSPECTIONCASE]
		WHERE [dbo].[RECENTHISTORYINSPECTIONCASE].USERID = @USER_ID
		ORDER BY [dbo].[RECENTHISTORYINSPECTIONCASE].LOGGEDDATETIME DESC

	-- Get inspection case details by Ids
	EXEC [common].[USP_IMINSPECTIONCASE_GETBYIDS] @RECENTINSPECTIONCASELIST, @USER_ID
	
END