CREATE PROCEDURE [holds].[USP_HOLDTYPESETUPS_LOOKUP_BYMODULE]
(
	@MODULEID INT
)
AS
BEGIN
	SET NOCOUNT ON;
	SELECT
		[dbo].[HOLDTYPESETUPS].[HOLDSETUPID],
		[dbo].[HOLDTYPESETUPS].[DESCRIPTION],
		[dbo].[HOLDTYPESETUPS].[NAME]
	FROM [dbo].[HOLDTYPESETUPS]
	WHERE ACTIVE = 1
	AND [HOLDTYPESETUPS].[MODULEID] = @MODULEID
	ORDER BY [dbo].[HOLDTYPESETUPS].[MODULEID],[dbo].[HOLDTYPESETUPS].[NAME]
END