CREATE PROCEDURE [teams].[USP_RESOURCE_AVAILABILITY_LISTING]
	@NOW DATETIME
AS

SELECT 
	[dbo].[RESOURCE].[USERID],
	[dbo].[RESOURCE].[UNAVAILABLESTARTDATE],
	[dbo].[RESOURCE].[UNAVAILABLEENDDATE],
	[dbo].[RESOURCE].[DELEGATEUSERID]
FROM [dbo].[RESOURCE]
WHERE  
	[dbo].[RESOURCE].[UNAVAILABLEENDDATE] >= @NOW
ORDER BY [dbo].[RESOURCE].[USERID]