CREATE PROCEDURE [teams].[USP_TEAM_MEMBERS_INSPECTORS_LISTING]
AS

SELECT DISTINCT
	[dbo].[USERS].[SUSERGUID],
	[dbo].[USERS].[FNAME],
	[dbo].[USERS].[LNAME],
	[dbo].[USERS].[BACTIVE]
FROM [dbo].[USERS]
INNER JOIN [dbo].[IMINSPECTORTYPEUSER] ON [dbo].[IMINSPECTORTYPEUSER].[USERID] = [dbo].[USERS].[SUSERGUID]
WHERE  
	[dbo].[USERS].[BACTIVE] = 1
ORDER BY [dbo].[USERS].[LNAME], [dbo].[USERS].[FNAME]